### ISSUE TITLE
Test-SqlPath does not accept multiple servers

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#1004]
### Is this a *feature* OR *bug*:

feature

### System Details

- Operating system name and version: Windows 10
- Output from `$PSVersionTable`: 

```
PS Presentations:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Output of dbatools version:

```
PS Presentations:\> (Get-Module dbatools -ListAvailable).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      942    -1
```

- SQL Server version for source/target

Multiple from SQL 2005 to SQL vNext (but that's not the point here ;-) )

### Steps to Reproduce

Get a list of SQL Servers
$SQLServers = (Get-VM -ComputerName beardnuc).Where{$_.Name -like '*SQL*' -and $_.Name -notlike 'SQL2008Ser2008'}.Name

run Test-SqlPath against the array
Test-SqlPath -SqlServer $SQLServers -Path '\\BeardNuc\SQLBackups'

### Action Results

New-Object : Cannot find an overload for "Server" and the argument count: "10".
At line:71 char:12
+ ...   $server = New-Object Microsoft.SqlServer.Management.Smo.Server $Sql ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

The property 'ApplicationName' cannot be found on this object. Verify that the property exists and can be set.

and then further errors

### Expected Results

PS Presentations:\> Test-SqlPathRob -SqlServer $SQLServers -Path \\beardnuc\sqlbackups

Server            Result
------            ------
[SQL2005Ser2003]    True
[SQL2012Ser08AG1]   True
[SQL2012Ser08AG2]   True
[SQL2012Ser08AG3]   True
[SQL2014Ser12R2]    True
[SQL2016N1]         True
[SQL2016N2]         True
[SQL2016N3]         True
[SQLVnextN1]        True
[SQLvNextN2]        True

### Code ????
I used this (without checking any guidelines ;-) ) to get the above results

foreach($instance in $sqlServer)
{
	$server = Connect-SqlServer -SqlServer $instance -SqlCredential $SqlCredential
	$sql = "EXEC master.dbo.xp_fileexist '$path'"
	$fileexist = $server.ConnectionContext.ExecuteWithResults($sql)

	if ($fileexist.tables.rows[0] -eq $true -or $fileexist.tables.rows[1] -eq $true)
	{
		$Result =  $true
	}
	else
	{
		$result = $false
	}
        [PSCustomObject]@{
    Server = $Server
    Result = $Result
    }
}

**Comment by niphlod** [comment]
it's not a bug per se ... the parameter clearly accepts only one value . 
I assigned the label enhancement as this is more a feature request, but this command is used in a lot of places as a subroutine so I wouldn't know if it'll be easy to fix this AND all the related cmdlets.

**Comment by SQLDBAWithABeard** [comment]
You are correct and I have altered re feature

yes I can see how there may be many changes required, maybe make Test-SqlPath an internal function and the enhanced version Test-DbaPath ?

**Comment by ctrlbold** [comment]
This will be Test-DbaSqlPath in 1.0

**Comment by potatoqualitee** [comment]
mannn this one is tough. i was all about to do it but it'd break our commands. what is the use case?

**Comment by SQLDBAWithABeard** [comment]
I know :-(

I was testing that 100 servers all had access to a fileshare for backups

So I altered it and did

$SQLServers = Get-SQLinstances -Environment Test
$path = '\beardnuc\sqlbackups'
Test-SqlPathRob -SqlServer $SQLServers -Path $path

Then 100 SQLNames and trues would be the result and I could do

Describe "test backups" {
    Context "Dev Environment" {
        $BackupTest = Test-SqlPathRob -SqlServer $SQLServers -Path $path
           It "All Servers have access to the Path $Path" {
          $Backups.Contains($false) | Should be $false
            }
     }
{

**Comment by potatoqualitee** [comment]
k, i'd like to move our current one to internal and then do this one like external. you okay with that @niphlod? I'd take care of the intenral one (and name it good ol' Test-SqlPath)

**Comment by niphlod** [comment]
assigning myself. most of the scary part was done in https://github.com/sqlcollaborative/dbatools/pull/2715. 
Following the same deal, we'd just have to add a sqlinstance property to it.
Summing up:
- old days: one instance, one path, output --> bool
- recent days: one instance, multiple paths, output --> pscustomobject with FilePath and FileExists props 
- future : one or multiple instances, multiple paths, output --> pscustomobject with FilePath, FileExists, sqlinstance, computername, instancename props
Should not break one thing.
