### ISSUE TITLE
Start-SqlMigration Enhancement - Search and Replace over databases/server

### ISSUE THREAD

**Issue by VolkerBachmann** [sqlcollaborative/dbatools#1011]
### Is this a *feature* OR *bug*:
It is a feature enhancement for a complete SQL Server Migration Skript

### System Details

- Operating system name and version: Windows Server 2016 (10.0.14393.953)
- Output from `$PSVersionTable`:
```
Name                           Value                                                                                                                                                        
----                           -----                                                                                                                                                        
PSVersion                      5.1.14393.953                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                      
BuildVersion                   10.0.14393.953                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                                      
Evaluate $PSVersionTable in PowerShell and paste the output here
```
- Output of dbatools version:
```
0.8.944
```
- SQL Server version for source/target
```
Source: 2008++
Target: 2016
```

**Comment by wsmelton** [comment]
Can you provide more details on what you mean by "search and replace on databases/servers"?

Are these additional parameters you see being added, and include what you functionality they would be providing.

**Comment by VolkerBachmann** [comment]
Sorry for the delay..
My SQL Server Development colleagues use Linked Server, opendataset or openrowset in several Views, Stored Procedures and so on.
I want to be able to seach and replace these with (maybe) a seperate command via powershell.
I think that could be helpful as part of a complete SQL Server Migration.
I've used the scripts for two Migrations until now and it worked very good for me.

**Comment by potatoqualitee** [comment]
Sounds like a command @Staggerlee011 would enjoy creating

**Comment by wsmelton** [comment]
I don't see this as being a command for common use, but more of a snippet that uses command within dbatools (e.g. Get-DbaDb<whatever object> then regex to replace the values in the scripted out objects). 

Going to close this one for now as don't really have anyone interested in taking it on, and no great interest seen in a need for it.
