### ISSUE TITLE
[Bug] Get-DbaPageFileSetting prompts for credentials

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1012]
### Is this a *feature* OR *bug*:

**Bug**

### System Details

- Operating system name and version: Windows Server 2012
- Output from `$PSVersionTable`: PoweShell 4.0 on host system

- Output of dbatools version: 0.8.931

- SQL Server version for source/target

SQL Server 2014

### Steps to Reproduce

`Get-DbaPageFileSetting <servername>`

### Action Results

It shows `Get-Credential` prompt when I did not provide any parameter for the credential. Cancelling the prompt still runs the command and outputs the results.

### Expected Results

It should not prompt for credential.

**Comment by PowerDBAKlaas** [comment]
@wsmelton did you test with differnet accounts, or on different servers? Do you allwasy get this prompt or only in one occasion? I cannot reproduce this.
(I do get some errors that I need to catch, but never a prompt)

**Comment by wsmelton** [comment]
In my lab (in AWS), no this does not happen. This is specific to a client environment in AWS and with 2 separate accounts get the same result. It is remote but executing the command locally on the server gives the same result as well.

**Comment by wsmelton** [comment]
We could likely just close this off and leave for documentation. As I'm likely to never figure out what is different in this client's environment than my AWS environment. I'll leave it up to you @PowerDBAKlaas

**Comment by PowerDBAKlaas** [comment]
OK
I just read the whole script and am puzzled how this even can happen. I'm not that experienced with Azure yet, so I may miss some specific issues there.
We'll be looking for a needle in a haystack, so I'd rather wait for additional cases,
although I'm very curious now; 😄
