### ISSUE TITLE
Get-dbaSpn not returning any results

### ISSUE THREAD

**Issue by mvillegascuellar** [sqlcollaborative/dbatools#1018]
### Is this a *feature* OR *bug*:

Bug

### System Details

- Operating system name and version: Microsoft Windows Server 2016 Standard 64-bit
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Output of dbatools version:

```
0.8.942
```

- SQL Server version for source/target: 2008R2

### Steps to Reproduce

I have a server that I am sure it has Spn configure because I tested it with the setspn tool and it returns results, however the command get-dbaspn does not return any output. I'd like to know if it is an issue with my environment or what.
Thanks.

![spn_error](https://cloud.githubusercontent.com/assets/25183564/24811904/9fd397cc-1b8d-11e7-9fb2-569d4d1f7768.png)

**Comment by wsmelton** [comment]
@mvillegascuellar can you verify there are no logs created from the command being executed? 

You can run this to get the path and files:

```powershell
dir (Get-DbaConfig -Name dbatoolslogpath).Value
```

If you have any, please edit your issue and attach those files. There should be an XML and LOG file generated if any exceptions are caught.

**Comment by mvillegascuellar** [comment]
Hi, 

I tried the command but no results came out.

![windows powershell](https://cloud.githubusercontent.com/assets/25183564/24867192/077d341e-1dd2-11e7-995e-8ea6a4403e0b.png)

**Comment by wsmelton** [comment]
Ok, can you update dbatools to the latest release ([0.8.942](https://github.com/sqlcollaborative/dbatools/releases/tag/v0.8.942))?

**Comment by mvillegascuellar** [comment]
I'm already on that version.

![windows powershell2](https://cloud.githubusercontent.com/assets/25183564/24867695/a9b5e04a-1dd3-11e7-8279-03e1b0665942.png)

**Comment by potatoqualitee** [comment]
this likely has to do with elevation. Please run the command again with the latest toolkit and see if you need to elevate. If not, please come here, we'll reopen and continue to dig.
