### ISSUE TITLE
Restore functions support for Azure Blob Container (URL path)

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1024]
### Is this a:
- [x] **feature** 
- [ ] **bug**

### System Details

- SQL Server version for source/target
Would only apply to SQL Server 2012+

### Expected Results

BackupToURL utilizes a credential within the instance to read and write to the Azure Blob storage. It supports performing the same `RESTORE` command you would against a local backup, just uses the `FROM URL` syntax instead of `FROM DISK`.

The parameter(s) I would see needed:
- [ ] `-AzureUrl` - Accepts the URL path to the blob container (no real way to verify it without using Azure PowerShell commands, just try to read the backup file)
- [ ] `-AzureCredential` - The name of the credential utilized by SQL Server to read/write to the Azure Blob container. Utilize `Get-DbaCredential` to verify existence.

The expectation would be that the DBA is responsible for configuring the Azure side of this, which would mean the credential is already created for the given SQL Server instance. This has to be done for you to use the Managed Backup feature for SQL Server as well, where SQL Server is managing the backup schedule/frequency/backup type performed.

## Commands involved (that I can see to date)
- [ ] Read-DbaBackupHeader
- [ ] Remove-DbaBackup
- [ ] Restore-DbaDatabase
- [ ] Restore-SqlBackupFromDirectory 
- [ ] Test-DbaLastBackup

**Internal functions**
- [ ] Restore-Database (_internal function_)
- [ ] Get-OlaHRestoreFile
- [ ] Get-FilteredRestoreFile
- [ ] Get-DirectoryRestoreFile

Likely the interanl functions might need new functions to specifically handle URL (Azure container) processing for simplicity/troubleshooting purposes.

Regarding Ola's `DatabaseBackup`, it does support performing the backup to a URL so that structure is simply created within the Azure Blob container.

**Comment by Stuart-Moore** [comment]
I'd say ignore anything that isn't restore-dbadatabase related as that's
the way forward as it can replace the others (IMHO) . And as it's modular
you can just add another internal get function to handle it (that was my
plan). Will be easier once I've gotten it all working with Fred's type
stuff as it's currently a bit of guess work working out what's being passed
back, so an azure backup type would probably make things a lot easier to
work with.

**Comment by Stuart-Moore** [comment]
Having had a play, it should be fairly easy to support this when working with Get-DbaBackupHistory output (for olaH or anyt other style backups.)

But if we want to allow the current scanning of folders/containers it'll get trickier as we'll either need to rely on the Azure cmdlets or usr iwr and the REST API.

That could be farmed out to the user to provide as an array of URLs which we can then parse as normal.

**Comment by wsmelton** [comment]
I'd go for the user passing in the URLs of the files. I would not get into trying to scan containers in Azure, because there will be to many factors that can affect performance.

Let me know if want testing.

**Comment by Stuart-Moore** [comment]
Oops, this didn't get assigned, so only just realised this is all live and working (in dev at least) for the last couple of weeks.
