### ISSUE TITLE
Invoke-DbaEditionUpgrade / Update-DbaEdition

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1029]
### Is this a *feature* OR *bug*:

feature post 1.0

Alias to Invoke-DbaEditionDowngrade?

Or just do Update-DbaEdition?

### Details
* Require \-SqlInstance and \-ProductKey
* Validate Product Key format using regex.
* Figure out instance name (get it from the SQL Server to be sure)
* Remotely execute `setup.exe /ACTION=editionupgrade /INSTANCENAME=$instanceName /PID=$productkey` plus whatever else needs to be executed to ensure there's no GUI. 
* If a GUI-free upgrade isn't possible, require that they can only run the command locally.
* Try a few different ways to find the setup.exe for SQL Server
* $env:ProgramFiles\Microsoft SQL Server\{80,90,100,110,120,130,etc)\Setup Bootstrap\Release\setup.exe
* Or if that doesn't work, failback to parsing out  $server.InstallSharedDirectory and $server.RootDirectory
* Prompt to restart SQL Server.
* Ensure the command handles clusters, too. It's a little different and may be a PITA.
* Make a map of [what's supported](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/supported-version-and-edition-upgrades), new command perhaps: Test-DbaEditionChange?

**Comment by wsmelton** [comment]
I would add in step that backup of system databases is performed prior to running the setup.

**Comment by wsmelton** [comment]
@niphlod I think this would be good to add in support for this via [Install-DbaInstance](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Install-DbaInstance.ps1).

Maybe just make this  as a wrapper command but you would be basically be just running the "install" with stripped down version of the parameters to support it.

**Comment by wsmelton** [comment]
@nvarscar something the install or update instance command could do?

**Comment by nvarscar** [comment]
Yes, this is covered by Install-DbaInstance by specifying `-Configuration @{ACTION="editionupgrade"}, but it would need the setup.exe path specified. Also, no cluster support per se, not even sure how cluster upgrade is different in this scenario.

**Comment by wsmelton** [comment]
Should be same process for cluster with just doing the offline node and then failover and such.

I'll close this one then.
