### ISSUE TITLE
Running ./install.ps1 blows away git repo

### ISSUE THREAD

**Issue by LambadaDelta** [sqlcollaborative/dbatools#1039]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.14409.1005                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14409.1005                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1  
```

- Output of dbatools version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      945    -1      
```
not sure if this comes from the install.ps1 as I have done the Install-Module version.
- SQL Server version for source/target
NA

#### Example:
Run Command:
```powershell
git clone https://github.com/sqlcollaborative/dbatools.git
#cd to new repo
cd dbatools
#example would see C:\g\r\dbatools [master]> 
#run installer
.\install.ps1
```
3. Received following error
```powershell
C:\g\r\dbatools [missing master]> 
```

## Action Results
death to my local repo :-1: 

## Expected Results
leave my repo alone :+1:

**Comment by ctrlbold** [comment]
LOL. Sorry, man. The expectation is that you are not running the installer from your git repo cuz they are two different things. 

If you would like to submit a PR for this, the fix would probably be something like

if (Test-Path "$localpath\.git") { throw "You cannot run the installer from your github repo" }

around line 41

**Comment by ChocolateMonkey** [comment]
Oh wait.. so does install.ps1 install the source I am looking at?

I was expecting something a bit more like this: https://github.com/dahlbyk/posh-git/blob/master/install.ps1

On 13 Apr 2017, at 16:20, Chrissy LeMaire <notifications@github.com<mailto:notifications@github.com>> wrote:


LOL. Sorry, man. The expectation is that you are not running the installer from your git repo cuz they are two different things.

If you would like to submit a PR for this, the fix would probably be something like

if (Test-Path "$localpath.git") { throw "You cannot run the installer from your github repo" }

around line 41

**Comment by ctrlbold** [comment]
Correct - it's the same exact source. Using the repo is for development while the installer is more for end-users.

**Comment by ChocolateMonkey** [comment]
I looked at the guides, method 4, the option for using this from the repo doesn't say you need to add it to the profile or modules?

**Comment by potatoqualitee** [comment]
It's true, I shortcut it. I'll be updating the downloads and getting started pages soon, my apologies.

**Comment by potatoqualitee** [comment]
fixed in earlier release - but now update-dbatools is borked because we include SMO which would be in use. but this is fixed, tanks for report. and we'll get update-dbatools fixed for the SMO thing in a minute.
