### ISSUE TITLE
Copy-SqlPolicyManagement

### ISSUE THREAD

**Issue by goforebroke** [sqlcollaborative/dbatools#1040]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Output of dbatools version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      945    -1
```

- SQL Server version for source/target

source: 2014
target: 2016

## Steps to Reproduce

 Copy-SqlPolicyManagement -Source sourceServer -Destination destinationServer

Migrates conditions, policies but not Policy categories. If policies have been assigned to a policy category, the categories must be created on the target in order for the policies to show up in SMSS.

## Attached screen shots/console output

- Use of Start-Transcript can help collection of console output and exceptions
- Provide screen shots of the output from your console if available.

### Import - Attach dbatools logs
- Latest release of dbatools now includes a messaging and logging system. You can find this information via the `Get-DbaConfig` function. Use of the Set-DbaConfig controls the configuration of the system.
- Ensure this returns **true**: `(Get-DbaConfig -Name errorlogenabled).value`
- Locate the log path for the error logs using this command: `(Get-DbaConfig -Name dbatoollogpath).Value`
- **Attach the latest xml and log files found in the path shown.**

**Comment by goforebroke** [comment]
Looks like the categories need to be brought over so they can match up with policies that have been paired with categories

PolicyStore.PolicyCategories Property
https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.dmf.policystore.policycategories.aspx

**Comment by potatoqualitee** [comment]
no, bot, still open
