### ISSUE TITLE
Get-DbaBackupHistory - Conversion Error

### ISSUE THREAD

**Issue by CharterSteel** [sqlcollaborative/dbatools#1042]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version:
Windows Server 2016 Standard
WindowsBuildLabEx                                       : 14393.953.amd64fre.rs1_release_inmarket.170303-1614
WindowsCurrentVersion                                   : 6.3

- Output from `$PSVersionTable`:
```
Name                           Value                                                                                                                                                                                  
----                           -----                                                                                                                                                                                  
PSVersion                      5.1.14393.953                                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                
BuildVersion                   10.0.14393.953                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                                    
SerializationVersion           1.1.0.1  
```
- Output of dbatools version: 0.8.945
```
ModuleType Version    Name
---------- -------    ---- 
Script     0.8.945    dbatools
```

- SQL Server version for source/target
13.0.4202.2

#### Example:
Ran the following:
`Get-DbaBackupHistory -SqlServer VMSk1 -Databases CSCMelting`

3. Received following error
> WARNING: [Get-DbaBackupHistory][14:10:34] Failed to process Instance VMSk1: Exception setting "FirstLsn": "Cannot convert value "832076000002404200001" to type "System.Int64". Error: "Value was either too large or too small for an Int64.""

If use the -Raw switch, I get results

#### Example:
No results returned without -Raw switch

#### Example:
I expected history results

[PowerShell_transcript.VMMARS1.mHx1AMRg.20170413141546.txt](https://github.com/sqlcollaborative/dbatools/files/920626/PowerShell_transcript.VMMARS1.mHx1AMRg.20170413141546.txt)

### Import - Attach dbatools logs

[dbatools_13092_message_0.zip](https://github.com/sqlcollaborative/dbatools/files/920643/dbatools_13092_message_0.zip)

**Comment by FriedrichWeinmann** [comment]
Hi, thanks for reporting the issue.
I can see exactly where I messed up, thank you for the detailed report. See how fast I can push a bugfix, shouldn't be too difficult.
Sorry about the mess, in all my test scenarios the number was simply smaller so the type issue never came up.

**Comment by FriedrichWeinmann** [comment]
Heya,

I fixed the thing as far as I can see. It's in this PR:
https://github.com/sqlcollaborative/dbatools/pull/1050

However there is no way for me to verify, since - as I mentioned - all my numbers are too small to make a difference here. Could you download library.ps1 from the PR, replace your current one (in the bin-subfolder of the module), start a new powershell console and try Get-DbaBackupHistory again?

Cheers,
Fred

**Comment by CharterSteel** [comment]
Hey Fred,

This is my first time working with anything on github, so I was not sure how to download the file. I finally went through the #1050 link in the email, to the commits tab, to the “<>” link, bin link, opened the library.ps1 file and manually copied the text into a new file on my machine. If there is a better way, please share.

The good news is that the new file did not throw an error when I executed:

Get-DbaBackupHistory -SqlServer vmsk1 -Databases CSCMelting

I got some nice output in table format:

SqlInstance Database   Type TotalSize DeviceType     Start                   Duration End
----------- --------   ---- --------- ----------     -----                   -------- ---
VMSK1       CSCMelting Log  258.32 MB Disk           2017-04-13 10:56:57.000 00:00:56 2017-04-13 10:57:53.000
VMSK1       CSCMelting Full           Disk           2017-04-13 10:34:23.000 00:18:12 2017-04-13 10:52:35.000
VMSK1       CSCMelting Log  257.53 MB Disk           2017-04-13 10:32:01.000 00:00:56 2017-04-13 10:32:57.000
VMSK1       CSCMelting Log  257.53 MB Disk           2017-04-13 10:21:43.000 00:00:56 2017-04-13 10:22:39.000
VMSK1       CSCMelting Full           Disk           2017-04-13 09:57:01.000 00:18:13 2017-04-13 10:15:14.000
VMSK1       CSCMelting Full           Virtual Device 2017-02-17 09:41:40.000 00:13:59 2017-02-17 09:55:39.000
VMSK1       CSCMelting Full           Virtual Device 2017-02-13 15:28:52.000 00:31:47 2017-02-13 16:00:39.000
VMSK1       CSCMelting Full           Virtual Device 2017-02-13 12:57:40.000 00:29:32 2017-02-13 13:27:12.000
VMSK1       CSCMelting Full           Disk           2017-02-08 00:00:59.000 00:03:03 2017-02-08 00:04:02.000


If there is something else I should do on github I would be glad to do it, just let me know.

John Hise
Manufacturing Intelligence System Architect

**Comment by FriedrichWeinmann** [comment]
Hi John,

glad to hear it worked. There is not really a faster way to copy a file from a PR unless you got a git desktop client and access to the main system (in which case you can clone the entire branch into a folder structure on your desktop).

I'll close this issue as resolved when the PR is merged.

Cheers,
Fred
