### ISSUE TITLE
Test-DbaLastBackup - copy file to destination default backup location if not on UNC path

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#1067]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## System Details

- Operating system name and version: Windows Server 2016
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

- Output of dbatools version:
0.8.945

- SQL Server version for source/target
2012

#### Example:
1. Use -CopyDestination flag to have the cmdlet copy the backup file from the local server drive over to the default backup directory of the destination server.
2. Restore from destination backup directory
3. Clean up files

**Comment by potatoqualitee** [comment]
hey jess! I'll add you to the SQL Collab org and can assign you to this task! Looking super forward to your PR.
