### ISSUE TITLE
Export-DbaTable

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1082]
## Is this:

- [x] *feature* 
- [ ] *bug*:

new command within 1.0 scope

## Details
Holy shit I didnt realize `$scripter.Options.ScriptData = $true` existed

We have the pipeable export commands already that arent yet released publicly. it could be new-dbascriptoption blah, get-dbatable | Export-DbaObject or whatever it's called then -scrittingoption $scriptingoption

https://www.mssqltips.com/sqlservertip/4822/exploring-sql-server-table-backup-methods/

@SQLvariant sayz "You want to use the transfer class." whatever that means.

**Comment by sqllensman** [comment]
If all that is wanted is to create a script to export the table data then this can be acheived via something like:

$options = New-DbaScriptingOption
$options.ScriptSchema = $false
$options.ScriptData = $true
$options.IncludeDatabaseContext  = $true

$obj = Get-DbaTable -SqlInstance lensmansb -Database AdventureWorks2014 -Table [HumanResources].[Department]

Export-DbaScript -InputObject $obj -ScriptingOptionsObject $options -Path C:\Temp\ScriptData.sql

This could easily be incorporated into a seperate command if it was needed.

**Comment by niphlod** [comment]
@potatoqualitee : did this land already ?

**Comment by potatoqualitee** [comment]
it has not - @sqllensman made a good point, but i think i'd still like a dedicated command that makes it more straightforward, perhaps `Export-DbaDbTableData`
