### ISSUE TITLE
Invoke-DbaDatabaseClone

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1083]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

command within 1.0 scope - to go along with migration theme

## Details

Interesting - I didn't see an SMO option.

https://www.mssqltips.com/sqlservertip/4822/exploring-sql-server-table-backup-methods/

Check for Microsoft SQL Server 2014 SP2 or higher since that's when it was introducd

**Comment by potatoqualitee** [comment]
also, not drunk. just took some melatonin and fighting sleep 😆

**Comment by niphlod** [comment]
we got it.
