### ISSUE TITLE
DataTable commands

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1100]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 

post 1.0

## Details

I'd like a suite of DataTable commands - New-DbaDataSet, New-DbaDataTable, (and to a lesser extent New-DbaDataRow, New-DbaDataColumn)  but I'd also like some action ones, like.. Merge and uhh, other stuff. @ConstantineK what you think?

**Comment by niphlod** [comment]
closing!
