### ISSUE TITLE
Copy-SqlCentralManagementServer does not respect WhatIf parameter

### ISSUE THREAD

**Issue by sqlsauce** [sqlcollaborative/dbatools#1107]
## Is this:

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version: Windows 7 SP1 Professional (6.1.7601)
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

- Output of dbatools version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      947    -1
```

- SQL Server version for source/target
Source: 2008 R2 SP3 (10.50.6220)
Destination: 2014 SP2 (12.0.5203)

## Steps to Reproduce

1. Create CMS on a SQL Server 2008 R2 instance.
2. Identify a SQL Server 2014 instance that does not have a CMS.
3. Run command:
```powershell
Copy-SqlCentralManagementServer -Source "Server1\Sql2008" -Destination "Server2\Sql2014" -WhatIf
```
4. The output indicates that it creates groups and skips individual servers. Below is an example of the output:
```powershell
Connecting to Central Management Servers
Creating group Group1
What if: Performing the operation "Copying Server3" on target "Server2\Sql2014".
```

## Action Results
The CMS and its groups are copied, ignoring the WhatIf parameter. Individual instances are not copied.

## Expected Results
1. Receive following output:
```powershell
What if: Performing the operation "Copying Group1 on target "Server2\Sql2014".
What if: Performing the operation "Copying Server3" on target "Server2\Sql2014".
```
2. Nothing should actually be copied.

**Comment by potatoqualitee** [comment]
Fixing this immediately, thank you for the report

**Comment by potatoqualitee** [comment]
K, I've got a fix in and hope for it to be released tomorrow

![image](https://cloud.githubusercontent.com/assets/8278033/25507651/a1fb33b8-2bad-11e7-867b-e33c4f58853c.png)

**Comment by sqlsauce** [comment]
Wow, that was fast! Thank you!

**Comment by potatoqualitee** [comment]
We don't mess around with WhatIf issues!
