### ISSUE TITLE
copy permission functions does not copies permission for extended sps e.g. xp_cmdshell or role

### ISSUE THREAD

**Issue by TheRockStarDBA** [sqlcollaborative/dbatools#1112]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x ] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                                                                                               
----                           -----                                                                                                                                                               
PSVersion                      4.0                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                                     
BuildVersion                   6.3.9600.17400                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                                                
PSRemotingProtocolVersion      2.2                                                                                                                                                                 
```

- Output of dbatools version:

```
PS C:\Windows\system32> get-module dbatools

ModuleType Version    Name                                ExportedCommands                                                                                                                         
---------- -------    ----                                ----------------                                                                                                                         
Script     0.0        dbatools                            {Backup-DbaDatabase, Clear-DbaSqlConnectionPool, Connect-AsServer, Connect-DbaSqlServer...}                                              
```

- SQL Server version for source 2008/2014 (target)

The function Copy-SqlSysDbUserObjects copies all the objects. It should also copy the permissions as well. None of the copy permissions functions copy permissions for extended SP or objects in master or msdb database. e.g. xp_cmdshell permission etc.

I found below script (http://stackoverflow.com/a/1862361/1387418)  that will be useful.

**Comment by wsmelton** [comment]
Well there is a separation of duties I think here to just note when the PR for this issue is submitted. In most commands we have for copying it only pertains to that item and **does not** include the dependent item(s). As an example: copying SQL Agent jobs. If the step in that job is for a specific database and that database does not exist on the destination then the command does not copy the database...it simply skips that agent job and moves on.

So in the same regard if  you copy an object from one database to another and want to include the permissions, then at a minimum the user must exist in that destination database. If they don't then the permissions **should not be copied**.

I would also note that the `Export-SqlUser` command **does copy** object level permissions for all schemas found in a database. I've tested this and it would include explicit permissions assigned to an extended stored procedure. So we would need to determine if we simply want to include a call to that function or repeat that code in the Copy function. If we want to perform a call to that function then we may need to adjust that command to include output the T-SQL instead of having to write it to a file.

**Comment by wsmelton** [comment]
@TheRockStarDBA can you name the functions you are referring to and update your PR with that information? Referring to this comment:

>None of the copy permissions functions

I only find 3 functions that even reference permissions:
- Get-DbaPermission (only goes to database level and not object level)
- Sync-SqlLoginPermissions (does not handle database , object level)
- Update-SqlPermissions (internal function but does not handle object level I believe)

**Comment by TheRockStarDBA** [comment]
@wsmelton

I agree that there is separation of duties. Allow me to provide a reason for my request :

The start-sqlmigration allows you to migrate the server in its entirety and it does an excellent job of migrating the entire server as per the options specified. For my case, I use 

`$cred = Get-Credential -UserName sa -Message "Enter Your SA password"

Start-SqlMigration -Source OldServer -SourceSqlCredential $cred -Destination NewServer -DestinationSqlCredential $cred -NoDatabases -NoSpConfigure -NoCentralManagementServer -DisableJobsOnDestination -NoDataCollector `

I only want to migrate all stuff excluding databases, sp_configure settings, CMS, data collector and want to disable the jobs on the new server. When run the start-SqlMigration, it DOES NOT copy the permissions esp. the system dbs - master and msdb.

For e.g. in my case, 
It does not copy the permissions for xp_cmdshell granted to different logins explicitely along with sp_OA* extended procs. 

If I rely on start-sqlmigration to do the work, then it should copy the explicit permissions (it copies the logins, users, etc.) 

Remember that system databases are unique since they are not copied over from one server to another. And we need to be careful to assign the permissions since it might break the app or processes who rely on the explicit permissions on variour system SPs or extended SPs for their functionality.

I even looked into Export-sqluser and it DOES NOT copy the extended SP permissions.

I am more inclined to Copy-SqlSysDbUserObjects as it is geared towards system db .. may be have a parameter like -permissions or whatever is suitable :-)

`
Synopsis
    Imports *all* user objects found in source SQL Server''s master, msdb and model databases to the destination.

Syntax
    Copy-SqlSysDbUserObjects [-Source] <Object> [-Destination] <Object> [[-SourceSqlCredential] <PSCredential>] [[-DestinationSqlCredential] <PSCredential>] [-Confirm ] [-WhatIf ] [<CommonParameters>]


Description
    Imports *all* user objects found in source SQL Server's master, msdb and model databases to the destination. This is useful because many DBA's store backup/maintenance procs/tables/triggers/etc (among other things) in master or msdb.
    
    It is also useful for migrating objects within the model database.`


Please let me know if I am missing anything.

Appreciate you looking into the issue and all the hard work that you guys are doing for the sql server and powershell community !

**Comment by wsmelton** [comment]
Ok, all clear now. In that regard we just need to work on adding the commands to handle the permissions in the Start-SqlMigration.

> I even looked into Export-sqluser and it DOES NOT copy the extended SP permissions.

The Export-SqlUser is fixed in the development branch where it will export the xp permissions, when Chrissy does the next merge to master that should be available to you. Sample output:
```powershell
C:\WINDOWS\system32> Import-Module C:\GitHub\dbatools\dbatools.psd1
C:\WINDOWS\system32> Export-SqlUser -SqlInstance manatarms -User TestLogin
[Export-SqlUser][10:28:18] Validating users on database [dbareports]
[Export-SqlUser][10:28:18] No users found on database '[dbareports]'
[Export-SqlUser][10:28:18] Validating users on database [JustDoIt]
[Export-SqlUser][10:28:18] No users found on database '[JustDoIt]'
[Export-SqlUser][10:28:18] Validating users on database [master]
[Export-SqlUser][10:28:19] Validating users on database [model]
[Export-SqlUser][10:28:19] No users found on database '[model]'
[Export-SqlUser][10:28:19] Validating users on database [msdb]
[Export-SqlUser][10:28:19] No users found on database '[msdb]'
[Export-SqlUser][10:28:19] Validating users on database [Northwind]
[Export-SqlUser][10:28:19] No users found on database '[Northwind]'
[Export-SqlUser][10:28:19] Validating users on database [pubs]
[Export-SqlUser][10:28:19] No users found on database '[pubs]'
[Export-SqlUser][10:28:19] Validating users on database [ReportServer]
[Export-SqlUser][10:28:19] No users found on database '[ReportServer]'
[Export-SqlUser][10:28:19] Validating users on database [ReportServerTempDB]
[Export-SqlUser][10:28:19] No users found on database '[ReportServerTempDB]'
[Export-SqlUser][10:28:19] Validating users on database [SSISDB]
[Export-SqlUser][10:28:19] No users found on database '[SSISDB]'
[Export-SqlUser][10:28:19] Validating users on database [tempdb]
[Export-SqlUser][10:28:19] No users found on database '[tempdb]'
[Export-SqlUser][10:28:19] Validating users on database [Woodworking]
[Export-SqlUser][10:28:19] No users found on database '[Woodworking]'
USE [master]
GO
CREATE ROLE [RSExecRole]
GO
CREATE USER [TestLogin] FOR LOGIN [TestLogin] WITH DEFAULT_SCHEMA=[dbo]
GO
GRANT CONNECT TO [TestLogin]  AS [dbo];
GO
GRANT EXECUTE ON OBJECT::[sys].[xp_cmdshell] TO [TestLogin]  AS [dbo];
GO
```

**Comment by TheRockStarDBA** [comment]
Thanks @wsmelton ! Any way I can use the output generated by `Export-SqlUser`  and pipe the results to get executed on the destination (new) server ? I am happy to use the dev version for now.

**Comment by wsmelton** [comment]
Since the module includes `Invoke-Sqlcmd2` you can do something like this if you want to get them all:
```powershell
$results = Export-SqlUser -SqlInstance <server>
$results = $results.Replace("GO","") #Invoke command does not handle the GO terminator since it uses SqlClient
Invoke-Sqlcmd2 -ServerInstance <server> -Query $results
```

**Comment by TheRockStarDBA** [comment]
@wsmelton  I replaced the Export-SqlUser  from the dev branch in the functions folder https://github.com/sqlcollaborative/dbatools/tree/development/functions . Then I unloaded the dbatools module and then imported it again.

When I run the Export-SqlUser -SqlInstance <server>, it does not script out the extended SPs. Any idea if I am doing anything wrong ?

Also, If you can help/guide on `Copy-SqlDatabaseMail` : https://gist.github.com/TheRockStarDBA/6a38d566465745a887dc93273db161f1

**Comment by potatoqualitee** [comment]
Agreed with @wsmelton  - I can see the requirement, but I don't think it's within scope of the command. We can, however, explore extending another permission-centric command like `Sync-DbaLoginPermission` if it doesn't exist already.
