### ISSUE TITLE
DbaInstanceParameter must accept .

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1119]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

##  Details

-SqlInstance . is valid but this chokes. It should handle . and not translate it, if possible. If a translation is required, then localhost will do. I think that . is named pipes whereas the rest are tcp

```
Invoke-DbaDiagnosticQuery : Cannot process argument transformation on parameter 'SqlInstance'. Cannot convert value "." to type "Sqlcollective.Dbatools.Parameter.DbaInstanceParameter[]". Error: "Cannot convert value "." to type
"Sqlcollective.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: .""
```

**Comment by FriedrichWeinmann** [comment]
Solved in:
https://github.com/sqlcollaborative/dbatools/pull/1132
