### ISSUE TITLE
dbadatetime, null if jan 1, 0001

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1128]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Details
SQL Agent is outrageous and gives the standard time of 1/1/0001 12:00:00 AM when something has never occurred. Can dbadatetime return null if it matches the above? Currently, it returns 0001-01-01 00:00:00.000

**Comment by FriedrichWeinmann** [comment]
Solved in:
https://github.com/sqlcollaborative/dbatools/pull/1132
