### ISSUE TITLE
Write-DbaDataTable erroring when piped to

### ISSUE THREAD

**Issue by dawgndad** [sqlcollaborative/dbatools#1134]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_
[transcript0.txt](https://github.com/sqlcollaborative/dbatools/files/971759/transcript0.txt)

- [ ] *feature* 
- [X ] *bug*:

## System Details

- Operating system name and version: Windows 2008 R2 and a Windows 2016 
- Output from `$PSVersionTable`:

/********************************Windows 2008 R2 server **************************/
Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      3.0                                                                                                               
WSManStackVersion              3.0                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                   
BuildVersion                   6.2.9200.16481                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0}                                                                                                   
PSRemotingProtocolVersion      2.2
/***********************************************************************************/

/****************************Windows 2016 Server *********************************/
Name                           Value                                                                                           
----                           -----                                                                                           
PSVersion                      5.1.14393.1066                                                                                  
PSEdition                      Desktop                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                         
BuildVersion                   10.0.14393.1066                                                                                 
CLRVersion                     4.0.30319.42000                                                                                 
WSManStackVersion              3.0                                                                                             
PSRemotingProtocolVersion      2.3                                                                                             
SerializationVersion           1.1.0.1 
/*************************************************************************************/

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
/******************** from 2008 server **********************************/
Get-Module : An item with the same key has already been added.
At line:1 char:2
+ (Get-Module dbatools -ListAvailable).Version
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Module], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.GetModuleCommand
/**************************************************************************/

/*******************from 2016 server *************************************/
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      948    -1      
0      8      901    -1      
0      8      692    -1  
/***********************************************************************/

```

- SQL Server version for source/target  - SQL 2012 SP3 CU7

## Steps to Reproduce

1: Created new SQLServerKey table in database..
![sqlserverkey](https://cloud.githubusercontent.com/assets/28313085/25634967/83b84d1e-2f4a-11e7-88ad-1da7e3a68613.JPG)

2: Ran this command :   Get-SqlServerKey -SQLCMS stentsql2012\sql2012 -verbose | Out-DbaDataTable | Write-DbaDataTable -SqlServer testdbasql2012\sql2012 -Table dbadmin.dbo.SQLServerKey

3: Receive the following when write-dbaDataTable executed:
Exception setting "Item": "Exception calling "set_Item" with "2" argument(s): "Column 'SQL Instance' does not belong to table .""
At line:181 char:7
+                         $datarow.Item($property.Name) = $property.value
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : CatchFromBaseAdapterParameterizedPropertySetValue
 
Exception setting "Item": "Exception calling "set_Item" with "2" argument(s): "Column 'SQL Version' does not belong to table .""
At line:181 char:7
+                         $datarow.Item($property.Name) = $property.value
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : CatchFromBaseAdapterParameterizedPropertySetValue
 
Exception setting "Item": "Exception calling "set_Item" with "2" argument(s): "Column 'SQL Edition' does not belong to table .""
At line:181 char:7
+                         $datarow.Item($property.Name) = $property.value
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : CatchFromBaseAdapterParameterizedPropertySetValue
 
Exception setting "Item": "Exception calling "set_Item" with "2" argument(s): "Column 'Product Key' does not belong to table .""
At line:181 char:7
+                         $datarow.Item($property.Name) = $property.value
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : CatchFromBaseAdapterParameterizedPropertySetValue

4: Table gets one integer entry in the first SQL Instance field and nulls in everything else

## Attached screen shots/console output

- Use of Start-Transcript can help collection of console output and exceptions
- Provide screen shots of the output from your console if available.

### Import - Attach dbatools logs
- Latest release of dbatools now includes a messaging and logging system. You can find this information via the `Get-DbaConfig` function. Use of the Set-DbaConfig controls the configuration of the system.
- Ensure this returns **true**: `(Get-DbaConfig -Name errorlogenabled).value`
**Verified**
- Locate the log path for the error logs using this command: `(Get-DbaConfig -Name dbatoollogpath).Value`
/**********************************No path returned from either server *****************************************/
- **Attach the latest xml and log files found in the path shown.**

**Comment by JohnRoos** [comment]
The problem seem to be the output from Get-SqlServerKey. It returns two objects. If you pipe the second object (not the string) it should work. I will look into fixing Get-SqlServerKey as soon as I have time.

**Comment by FriedrichWeinmann** [comment]
Thanks John for figuring that out.
@dawgndad : John's solution has been merged into development. Can you download the current development build and verify the solution?

**Comment by dawgndad** [comment]
Will be glad to, please point me to download, what I’m finding up on GitHub says it was updated 15 days ago.

Thanks

**Comment by JohnRoos** [comment]
Select the Development branch and click on "Clone or download" and then Download Zip.

Or just use this link: https://github.com/sqlcollaborative/dbatools/archive/development.zip
When you unzip it, the folder need to be named "dbatools" before you import it in PowerShell, or you might get errors.

**Comment by dawgndad** [comment]
I have verified that this is now working for me.  Thanks.
