### ISSUE TITLE
[2.0.0] Central Dba Server for Organization level information

### ISSUE THREAD

**Issue by FriedrichWeinmann** [sqlcollaborative/dbatools#1135]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## System Details

As it currently is, information is all handled locally by dbatools, there is no sharing between systems at all. That means, if we want to share information / configuration across multiple dbatools sessions on different machines within an organization, we currently need to manually synchronize that information (e.g.: Export to file and Import on the target).

Our own commands thus have only the user input to work with. We can do validation and sanity-checks, but there is no way to just leave information somewhere, where another dbatools console might catch that information.
An example:
 - On Restoring a database to a target server, the only options available are to place it in the default store or to explicitly specify the path.
 - We can now do a sanity check on whether enough space has been left (though we might want to support a minimum free margin at some point)
In contrast, we could support configuring paths where databases and logfiles go for this server. Then the command could automatically assign storage as needed. This however would still only be a local thing we'd have to teach it somehow. It'll be gone the next time, the coworkers will never see this setting.

What if such information could be stored in a SQL Database, and dbatools were able to _automatically_ detect that database and connect to it ? In this situation, a central store for information that should be shared across the organization could be realized.

Of course, all commands that utilize such a framework extension must _still_ be able to do without, as we can hardly ask for our own server as a _prerequisite_ for dbatools, but it would enable users to scale operations out across a far wider base.

**Comment by ClaudioESSilva** [comment]
I like the idea, but I see one (big) obstacle to implement this into the organizations.
**From my experience** we usually have access (SQL Port) from a 'central' instance to all running instances to gather information but **not the other way round**. 
The security guys typically do not like this :-)

If this would be a big no no for the majority of the people, maybe should be something not for 2.0 but instead to discuss to an v3.0

**Comment by FriedrichWeinmann** [comment]
Hm, I don't really see security concerns being an issue:
Any feature based on this must be optional (that is: Dbatools can run without) because we can't demand users setting a server up for us. Those with too strict security must live without this.

Either way, 2.0 is still fairly far in the future (more than a year), so I don't really intend to plan beyond that for now ^^

**Comment by ClaudioESSilva** [comment]
@FriedrichWeinmann I totally agree with you and I didn't mean this is a security concern 😄 
Just wondering how many people can take advantage of this feature. 
Trying to figure out the effort we will have vs number of effective uses.

**Comment by wsmelton** [comment]
Cleaning up issues...can reopen this once 2.0 gets closer...
