### ISSUE TITLE
DBAtools Time formats should understand string

### ISSUE THREAD

**Issue by FriedrichWeinmann** [sqlcollaborative/dbatools#1136]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## System Details

Currently, the dbatools time formats do not smoothly convert from string.

**Comment by potatoqualitee** [comment]
is this done, @FriedrichWeinmann ?

**Comment by niphlod** [comment]
not done yet .... maybe @zippy1981 can give a hand here ?

Basically 

[Sqlcollaborative.Dbatools.Utility.DbaTime]'08:00'

would need to happen without errors.

**Comment by zippy1981** [comment]
I'll try to find time. It should not be hard.

I think the answer would probably involve `TypeConverter` @FriedrichWeinmann if you want to look at how that works. I mean assuming you can't just make a simple constructor that takes a string and DateTime.TryParse or whatever.

**Comment by FriedrichWeinmann** [comment]
You can do just that Justin, I'd go with the constructor route. Just managed to finish a commission and don't have the head for it tonight, so I'm not going to complain if you pick it up. Otherwise I'll deal with it tomorrow after work.

**Comment by niphlod** [comment]
while there take a look also to #3709 , I think is related to DLL code too

**Comment by potatoqualitee** [comment]
all look closed 🎉
