### ISSUE TITLE
Support migration of Replication components between instances

### ISSUE THREAD

**Issue by ParvezSohail** [sqlcollaborative/dbatools#1137]
i have tried Start-SqlMigration script and it is awesome. Was just wondering whether it copies replication components from source to destination. I have transactional replication on my source and it is not copied to destination. Is there  anything i am missing silly or it doesn't support this yet?

Thanks,
Parvez

**Comment by wsmelton** [comment]
It looks like we have a placeholder for a command that was initialed started by @potatoqualitee but does not look like it was completed.

https://github.com/sqlcollaborative/dbatools/blob/master/functions/Copy-SqlReplication.ps1

**Comment by ParvezSohail** [comment]
Thanks wsmelton. I will wait for @potatoqualitee  to get this completed.

**Comment by wsmelton** [comment]
Replication objects are a black hole for most of us, let alone trying to figure out how RMO is used for the task. Right now this is not on the roadmap to support. If we come back around to it a new issue can be created.
