### ISSUE TITLE
Get-dbadatabasebackuphistory output issues

### ISSUE THREAD

**Issue by Stuart-Moore** [sqlcollaborative/dbatools#1143]
Output property backupsetupid should be backupsetid (when this is fixed please also look for the commented out fix in restore-dbadatabase) 

Filelist property isn't specified properly. Needs to return a hash table or an object as that's whats expected 

Both of these are prevent pipeline the output from this function into the restore chain. Have mitigated other issues in that side already.

**Comment by FriedrichWeinmann** [comment]
```PowerShell
Get-DbaBackupHistory -SqlServer ProdServer1 -Databases Hr,Finance | Restore-DbaDatabase -SqlServer StageSrv2 -DestinationDataDirectory D:\Staging
```
Should restore the database. Currently throws errors on the file relocate part of the restore. Have worked around most of the other things with the output changes.

**Comment by Stuart-Moore** [comment]
This issue also linked - https://github.com/sqlcollaborative/dbatools/issues/1196

**Comment by FriedrichWeinmann** [comment]
@Stuart-Moore is this still an issue or superseded by the many changes since? (DM me in Slack if it's still ongoing, otherwise feel free to close it)

**Comment by Stuart-Moore** [comment]
Nah, fixed a while ago. then fixed again last week. Test in CI build to catch it next time someone tinkers.
