### ISSUE TITLE
Trusted windows authentication issues in 0.8.950

### ISSUE THREAD

**Issue by ConstantineK** [sqlcollaborative/dbatools#1149]
## Is this:
- [ ] *feature* 
- [x] *bug*:

Referencing: https://twitter.com/psdbatools/status/861317073099788289
There is some windows trusted auth issues when using Windows 7, unspecified but @potatoqualitee said she had some insight into the issue.

Some context:
https://sqlcommunity.slackarchive.io/dbatools/page-100/ts-1494185846584086

Affects Get-DbaDatabase and Test-DbaLastBackup but not Test-SqlConnection.

**Comment by megamorf** [comment]
This also affects Server 2012R2

**Comment by wsmelton** [comment]
`Test-SqlConnection` is not effected because that function does not call any of the Connect functions to connect to a SQL Server instance.

**Comment by ConstantineK** [comment]
This was solved in the most recent update, please reopen if you are having the same issue.
Thanks!
