### ISSUE TITLE
ReuseFolderStructure sux

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#115]
![bug](https://cloud.githubusercontent.com/assets/8278033/17526330/801608aa-5e02-11e6-81dc-fc821608c19a.png)

**Comment by ctrlbold** [comment]
treebeard sez:
"I have a theory about the ReuseFolderStructure problem. When the default location for the user db files is the same as the system db files the SMO properties for DefaultFile and DefaultLog are supposedly not initialized. Until they are changed. Get-SqlDefaultPaths does check a few different ways."

**Comment by dansqldba** [comment]
@ctrlbold is this still valid?

**Comment by SirCaptainMitch** [comment]
@ctrlbold is this still a valid issue? If so can we get it broken out into a template?

**Comment by hintbw** [comment]
We found that fixing this issue occurs just in the validating this path because it is missing a ".filename" reference as part of looking at rows in a dataset. We fixed it locally but haven't gotten around to submitting a pull request

**Comment by ctrlbold** [comment]
Oh, @hintbw - I was just about to ask for you to come document your issue on this ticket. Yes, would super love a PR!

**Comment by niphlod** [comment]
@hintbw : any news on this ? if not, we'll take a stab at it

**Comment by potatoqualitee** [comment]
Being addressed in #1799

**Comment by potatoqualitee** [comment]
Should be fixed now D: in 0.9.127
