### ISSUE TITLE
Connect-SqlServer does not allow underscores in DNS names

### ISSUE THREAD

**Issue by Neratio** [sqlcollaborative/dbatools#1152]
## Is this:

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version: Windows Server 2012 R2 (6.3.9600)
- Output from `$PSVersionTable`:

 

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
- Output of dbatools version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      950    -1
```

- SQL Server version for source/target

11.0.5548.0

## Steps to Reproduce

1. Get-DbaDatabase -SqlInstance SVTEST_11
2. Received following warning:
```
WARNING: [Get-DbaDatabase][15:07:20] Failed to connect to: SVTEST_11
```
3. Seeing the following in `$Error`:
```
Connect-SqlServer : Cannot process argument transformation on parameter 'SqlServer'. Cannot convert value "SVTEST_11"
to type "Sqlcollective.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: SVTEST_11"
At line:133 char:56
+ ...              $server = Connect-SqlServer -SqlServer $instance -SqlCre ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Connect-SqlServer], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Connect-SqlServer

```

Happening with all names containing an underscore (_).
Without the underscore everything is working fine.

Worked through this and it seems like the following happens:
1. Connect-SQLServer is called
2. Calls constructor public DbaInstanceParameter(string Name)
3. Calls Utility.Validation.IsValidComputerTarget(tempString)
4. Calls Regex.IsMatch(temp, RegexHelper.ComputerTarget)
5. RegexHelper.ComputerTarget contains a regex that does not allow underscore in target names

## Attached screen shots/console output

![posh](https://cloud.githubusercontent.com/assets/8008344/25805854/82b452da-3401-11e7-9b82-175cc3d77872.png)

**Comment by FriedrichWeinmann** [comment]
Fixed in https://github.com/sqlcollaborative/dbatools/pull/1157
Please verify with the current development branch.

**Comment by Neratio** [comment]
Verified with current development, it's working as expected now! thanks

**Comment by FriedrichWeinmann** [comment]
Thanks for verifying!
Also thank you for notifying me about that error - should have caught that earlier!
