### ISSUE TITLE
start-migration error - "logical file ??? is not part of database ***.  Use RESTORE FILELISTONLY to list the logical filenames"...

### ISSUE THREAD

**Issue by JimBarnesMBA** [sqlcollaborative/dbatools#1153]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [X ] *bug*:

## System Details

- Operating system name and version: Windows Server 2012 R2 Datacenter

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.0.10586.117                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.10586.117                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                        

Name              : dbatools
Path              : C:\Users\jimb\Documents\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Description       : Provides extra functionality for SQL Server Database admins and enables SQL Server instance migrations.
Guid              : 9d139310-ce45-41ce-8e8b-d76335aa1789
Version           : 0.8.943
ModuleBase        : C:\Users\jimb\Documents\WindowsPowerShell\Modules\dbatools
ModuleType        : Script
PrivateData       : {PSData}
AccessMode        : ReadWrite
ExportedAliases   : {[Reset-SqlSaPassword, Reset-SqlSaPassword], [Copy-SqlUserDefinedMessage, Copy-SqlUserDefinedMessage], [Copy-SqlJobServer, Copy-SqlJobServer], [Restore-HallengrenBackup, 
                    Restore-HallengrenBackup]...}
ExportedCmdlets   : {}
ExportedFunctions : {[Start-SqlMigration, Start-SqlMigration], [Copy-SqlDatabase, Copy-SqlDatabase], [Copy-SqlLogin, Copy-SqlLogin], [Copy-SqlServerAgent, Copy-SqlServerAgent]...}
ExportedVariables : {}
NestedModules     : {}

- SQL Server version for source/target
source:  2005 - 9.00.5069.00
target: 2016 - 13.0.1601.5

## Steps to Reproduce
1. Created sql2016 named instance on target server
2. Run Command:
Start-SqlMigration -Source mbasql -Destination spaa-ddb-sql01\MBASQLPOC -BackupRestore -NetworkShare \\spaa-ddb-sql01\SQL_Transfer -force
3. Received following error for a number of databases (not all)

5/5/2017 5:36:27 PM

At line:462 char:5
+                 $restore.sqlrestore($server)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.MethodInvocationException: Exception calling "SqlRestore" with "1" argument(s): "Restore failed for Server 'spaa-ddb-sql01\MBASQLPOC'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Restore failed for Server 'spaa-ddb-sql01\MBASQLPOC'.  ---> Microsoft.SqlServer.Management.Smo.SmoException: System.Data.SqlClient.SqlError: Logical file 'sysft_docs' is not part of database 'EBS'. Use RESTORE FILELISTONLY to list the logical file names.
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQueryWithMessage(StringCollection queries, ServerMessageEventHandler dbccMessageHandler, Boolean errorsAsMessages, Boolean retry)
   at Microsoft.SqlServer.Management.Smo.BackupRestoreBase.ExecuteSql(Server server, StringCollection queries)
   at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Restore-SqlDatabase(Closure , FunctionContext )

note that "logical file" and "database" differs for each DB that gens the error, but the pattern/error is the same

copying each db via Copy-SqlDatabase works fine

errors log attached
[dbatools-exceptions.txt](https://github.com/sqlcollaborative/dbatools/files/983642/dbatools-exceptions.txt)

**Comment by potatoqualitee** [comment]
Thank you so much for the detailed report, @JimBarnesMBA! @Stuart-Moore, any chance you have an idea of what's going on here?

**Comment by VolkerBachmann** [comment]
@potatoqualitee I've had the same problem during one of my migrations as discussed on Slack with @ClaudioESSilva some weeks ago; We can't fix this and I copied the databases separate with your Copy-SqlDatabase command. the Rest of the scripts works.

**Comment by JimBarnesMBA** [comment]
so would you recommend as a failsafe to use the -noDatabases switch with the migration command, then add the DBs individually via the copy-SQLDatabase command?  Just trying to get to a foolproof way of migrating this box.  This is our production box, hence the abundance of caution.

**Comment by potatoqualitee** [comment]
Thanks so much @VolkerBachmann - did you guys figure out why the individual command works but not the overall one? Start-SqlMigration uses Copy-SqlDatabase.

@JimBarnesMBA - yeah you can skip with nodatabases then use Backup-DbaDatabase and Restore-DbaDatabase for the most control.

**Comment by Stuart-Moore** [comment]
Looks like it's barfing on a full text file, could be that the code doesn't
support that too well (it's the older style backup/restore). Will have a
better look when on a computer.

Cheers
Stuart

**Comment by JimBarnesMBA** [comment]
For what it's worth (not much) my guess was along the same lines.  I kind of thought that the code that creates the output line that says "Building file structure inventory for 1 databases" builds a list that doesn't actually correspond to the files for the database for some wacky 2005 reason.  Maybe I'll poke around in there if I get a chance.

**Comment by Stuart-Moore** [comment]
2005 source you say? FT in 2005 was a dog's breakfast in terms of files. It
was all in a seperate folder rather than in the usual files like it was
with 2008+, and this sometimes causes issues.

Just checked with some test dbs and the newer backup/restore stuff appears
to handle it OK.

**Comment by wsmelton** [comment]
There is an issue filed to have the `copy-sqldatabase` updated to utilize the new backup/restore commands: #991

Just have not gotten around to it (there are alot of issues filed for improving that Copy-SqlDatabase function).

**Comment by VolkerBachmann** [comment]
@potatoqualitee 
Sorry for confusing -  I must say that the Copy-SqlDatabase didn't work either and I used instead these commands:

Backup-DbaDatabase -SqlInstance dehosql7 -Type Full -BackupDirectory \\derzsql03\Transfer -FileCount 4  
Restore-DbaDatabase -SqlServer derzsql03 -Path \\derzsql03\Transfer -WithReplace 

After that the Start-SqlMigration -Verbose -NoDatabases ....
       does the Rest of the Job.

**Comment by potatoqualitee** [comment]
we moved to Backup-DbaDatabase and Restore-DbaDatabase within Copy-DbaDatabase - can you check to see if it works wel lfor you now, @VolkerBachmann ?

**Comment by potatoqualitee** [comment]
Fixed by relying on Backup/Restore in Copy-DbaDatabase 🎉
