### ISSUE TITLE
Get-DbaXEventSession errors on filter if session does not exist.

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1165]
## Is this:

- [ ] *feature* 
- [X] *bug*:

## System Details

- Operating system name and version: `Windows 7`
- Output from `$PSVersionTable`: `PowerShell 3.0`

- Output of dbatools version: `v 0.8.954`

- SQL Server version for source/target: Multiple but average is SQL Server 2012 of the 222 servers.

## Steps to Reproduce

1. Import-Module
2. Run Command:
```powershell
Get-DbaXEventSession -SqlInstance MyServer -Sessions "Session that does not exist"
```
3. Received following error
```powershell
Get-DbaXEventsSession : Cannot validate argument on parameter 'Sessions'. The argument "Session that does not exist" does not belong to the set "AlwaysOn_health,system_health" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
```

## Expected Results
1. Import-Module
2. Run Command:
```powershell
Get-DbaXEventSession -SqlInstance MyServer -Sessions "Session that does not exist"
```
3. Receive no output or at most warning message (if applicable)
```powershell
Warning: Session "Session that does not exist" not found.
```

**Comment by sqllensman** [comment]
This appears to be fixed .

The code now includes a filter for the Sessions and the above example returns no output.
