### ISSUE TITLE
Copy-SQLDatabase Locking Issues

### ISSUE THREAD

**Issue by jdanton** [sqlcollaborative/dbatools#1175]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x ] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
- Output of dbatools version:
```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.8.955    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy...
```

- SQL Server version for source/target

Source: 10.50.6220
Target: 11.0.6594

## Steps to Reproduce

1. Have databases with broker enabled on primary.
2.  Copy-SqlDatabase -Source "SRC\MSGP" -Destination Target -BackupRestore -NetworkShare \\bkpshare\backup\ -AllDatabases -NumberFiles 8

## Action Results
After restore script hangs on with lock on setting the database owner to SA being blocked by the following SQL. 

ALTER DATABASE [DB] SET  ENABLE_BROKER

## Expected Results
1. Created database/object/files/etc
2. Run Command:
```powershell
Copy-SqlDatabase -Source "SRC\MSGP" -Destination Target -BackupRestore -NetworkShare \\bkpshare\backup\ -AllDatabases -NumberFiles 8
```
3. Receive following output (if applicable)
```
######### Database: DB1 #########
Started: 05/10/2017 07:43:33
Successfully restored DB1 to Target
Updating database owner
Finished: 05/10/2017 07:43:42
Elapsed time: 00:00:08
```

## Attached screen shots/console output

SQL that hangs.

`ALTER DATABASE [DB] SET  ENABLE_BROKER`

**Comment by wsmelton** [comment]
It hangs because the system cannot get exclusive access to enable broker on the database. 

If you run the command over does it repeat?

**Comment by jdanton** [comment]
Right—if I run the command(s) standalone it works. However, the change owner command is what’s blocking it. I’m not sure what that just hangs. Killing the blocking session eventually lets it through.

jd

**Comment by wsmelton** [comment]
Based on the command as soon as it is restored we [set the owner](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-SqlDatabase.ps1#L1160) and then [set broker](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-SqlDatabase.ps1#L1268), but the database is still in single user mode. We do not set database to multiple user until [the end](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-SqlDatabase.ps1#L1291).

**Comment by wsmelton** [comment]
@jdanton how large is that database? Can you see what the change owner command is waiting on? 

First thought would be that the restore process has not completely finished, which SMO/PS may not be made aware of that so it just keeps chugging along.

**Comment by jdanton** [comment]
Not very large. I can try to repro again later today.

**Comment by Stuart-Moore** [comment]
@wsmelton I'm just converting it over to the new style backup restore stuff, which should remove that potential issue. Should have a branch pushed up tonight.
