### ISSUE TITLE
Grouping issue with Get-DbaBackupHistory

### ISSUE THREAD

**Issue by Stuart-Moore** [sqlcollaborative/dbatools#1196]
Pulling @asharovarov  comment from PR 1186 as it wasn't fixed in that merge 
He asked:
if you are looking at backup history could you please check behavior for multi-file backups. I think it previously it was returning 1 record with multiple files. Now it returns a record for each file. Is it expected behavior?

That behavior leads to multiple MOVE clauses for the same DB file in Restore-DbaDatabase. It doesn't cause any issues. But doesn't look clean.

**Comment by Stuart-Moore** [comment]
-Raw never grouped, just returned the raw data

The other methods should have returned grouped data for Path and Fullname properties, which was handled as an object/array With the new type, it's just returning the first value from that array

**Comment by potatoqualitee** [comment]
Should we return to pscustomobject?

**Comment by Stuart-Moore** [comment]
See latest pr for option B

**Comment by FriedrichWeinmann** [comment]
Slack is calling you :)

**Comment by Stuart-Moore** [comment]
Looks like this has been fixed in development. So closing
