### ISSUE TITLE
Set-DbaMaxMemory (multi-instance)

### ISSUE THREAD

**Issue by BrentOzar** [sqlcollaborative/dbatools#1198]
## Is this:
- [x] *feature* 
- [ ] *bug*:

(Name is totally up for debate, whatever works for the community.)

**Use case:** multiple instances running on one server (like after a multi-instance cluster failover, or just regular business-as-usual for a complex cluster.) We want to rebalance memory by setting max memory on each instance appropriately.

**How we wanna do it, v1:** 

1. User passes in a server name
2. We make a list of running instances on that node
3. We connect to each instance and get the total amount of data stored on that instance
4. We get the total memory on that node, and subtract how much memory should be left over for the OS using Kehayias's formula (same as Set-DbaMaxMemory today)
5. We divide up the remaining memory between the instances based on how much data they have, but no lower than 2GB per instance
6. We set the memory on each instance

**Design notes for later:** down the road, we'll look at wait stats on each instance because some instances might be idle, or some might have workloads that just don't hit storage much. That's going to be much more complex to code, though, and we'd rather wait to code that until this big fella goes live.

**Comment by wsmelton** [comment]
Edited post to number each item for v1 of the command...to better reference.

Just general notes for discussion...

(3) Possible use of `Get-DbaDatabaseFreeSpace` to pull the SpaceUsed on each database of a given instance...may not be accurate. We also have `Get-DbaTable` that pulls the information on each table, includes the IndexSpaceUsed/DataSpaceUsed.

(4) Based on how we want to pull the total memory on a given node, `Get-DbaMemoryUsage` gets the total server memory perf counter; or we just SMO to pull it from the Server object.

**Comment by wsmelton** [comment]
Cleaning up issues...

Someone wants to tackle this can re-open it.
