### ISSUE TITLE
Add Index Fragmentation information

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1216]
## Is this:

- [X] *feature* 
- [ ] *bug*:

Add the index fragmentation to the output of `Get-DbaHelpIndex` function. If this is not a good fit, or not easily added we can just as easily come up with a dedicated function for it...something like `Get-DbaIndexFragmentation` (which may be the best option).

**Comment by zippy1981** [comment]
Is this request "shovel ready" Can I work on this?
