### ISSUE TITLE
Standardize parmeters for all Get-Dba* functions

### ISSUE THREAD

**Issue by dawgndad** [sqlcollaborative/dbatools#1224]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x ] *feature* 
- [ ] *bug*:

## System Details

It would be cool and helpful if the inputs for each Get-DBAXXX commands had the same parameters.  Currently Get-DBAServerKey has a -SQLCMS parameter that allows for a quick and easy multi-server scan while others have single server or comma separated lists.  Preferably the option to grab a list of servers from a table would be great.

**Comment by potatoqualitee** [comment]
yeah that's a super outdated command from when dbatools was called sqlmigration back in 2014 👎 I saw that parameter yesterday and was horrified.

Fortunately, both command names and parameter names will be standardized in 1.0, which will be available in the upcoming months 👍

**Comment by niphlod** [comment]
we track this via code reviews. I think we all don't need a reminder that this a goal for us... feel free to reopen if you feel strongly about it
