### ISSUE TITLE
Test-DbaLastBackup not working in dev

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1255]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details

Test-DbaLastBackup in dev is not working, perhaps because of changes to get-dbabackuphistory? Please help -at a loss. It just says Failure

**Comment by wsmelton** [comment]
Resolved
