### ISSUE TITLE
Backup-DbaDatabase - upcoming features (request)

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#1258]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Features/changes 

- [ ] Folder structure and file name templates

### Examples for folder and file naming structure
Implement naming templates with ```-FolderStructure``` where we have following things:
- $Servername
- $Databasename
- $BackupType
- Date and Time ([custom date formats](https://blogs.technet.microsoft.com/heyscriptingguy/2015/01/23/create-custom-date-formats-with-powershell/))

#### Folder structure
- Default state
```$Servername_$databasename_$Backuptype_Ymd_HMS.[bak|trn]```
- **$FirstExample**
```$BackupDirectory\\$Servername\\$Databasename\\$BackupType\\$Servername_$databasename_$Backuptype_Ymd_HMS.[bak|trn]```
This is how Maintanace Solution builds folder structure
- **$SecondExample**
Template: ```$BackupDirectory\\$Servername\\$Databasename\\$BackupType\\Y\\V\\$Servername_$databasename_$Backuptype_Ymd_HMS.[bak|trn]```
Result: ```C:\Backups\SRV$Instance\WorldShippers\LOG\2017\20\SRV$Instance_WorldShippers_LOG_20170518_223500.trn```

#### Folder structure for different backup types
If you supply only [string] to ```-FolderStructure``` we go as described above, but if we get hashtable with structure like this {'ALL'='**$FirstExample**';'LOG'='**$SecondExample**'} we will handle FULL/DIFF/COPYONLY as stated in ```ALL``` and only LOG as its in ```LOG```. We may support hashtable name/value as ALL, FULL, DIFF, LOG, FULL_COPYONLY.

**Comment by Stuart-Moore** [comment]
The templates and stuff are now in
