### ISSUE TITLE
Copy-SqlSsisCatalog does not support named instances

### ISSUE THREAD

**Issue by goforebroke** [sqlcollaborative/dbatools#1263]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x ] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
- Output of dbatools version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      944    -1
```

- SQL Server version for source/target
Source: SQL Server 2014
Target: SQL Server 2014

## Steps to Reproduce

1. Run Command:
```
Copy-SqlSsisCatalog -Source namedinstance -Destination namedinstance -Folder "FolderName" -Project "ProjectName"
```
2. Received following error
```
An error occurred when checking the destination for Integration Services. Is
Integration Services installed?
At line:307 char:4
+             throw "An error occurred when checking the destination for
Integration Service ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (An error occure...ices instal
   led?:String) [], RuntimeException
    + FullyQualifiedErrorId : An error occured when checking the destination f
   or Integration Services. Is Integration Services installed?
```

## Expected Results

Looking at the source code the issue appears to be in the call to the function  `Get-RemoteIntegrationService`

If the target is a named instance, the instance name is not removed before setting the computer name to test if the SSIS service is running on the target:

Call to the function
```----------------------------------
try
		{
			Get-RemoteIntegrationService -Computer $Destination
		}
```
Function Snippet
```------------------------------------------------
Function Get-RemoteIntegrationService
		{
			param (
				[Object]$Computer
			)
			$result = Get-Service -ComputerName $Computer -Name msdts*
```

**Comment by wsmelton** [comment]
Thanks for reporting this one!

One of the features coming in our 1.0 release is new commands around ComputerManagement (aka WMI/CIM). When we implement this within this command we will add support for named instances.

**Comment by goforebroke** [comment]
No problem, thanks for making a great set of tools. Another thing to consider ....

ServerName, PortNumber

Hopefully the next release will handle named instances and the "ServerName, PortNumber"

**Comment by goforebroke** [comment]
has support for named instances been added?
