### ISSUE TITLE
Add parameter to close all connections when running Copy-SqlDatabase -WithReplace

### ISSUE THREAD

**Issue by CJChristensen** [sqlcollaborative/dbatools#1270]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```
PSVersion                      4.0                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                               
BuildVersion                   6.3.9600.17400                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                                          
PSRemotingProtocolVersion      2.2

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```
Script     0.8.948    dbatools                                            

- SQL Server version for source/target
2014

**Comment by wsmelton** [comment]
Closing this issue. Once build is released/pushed to master this feature will be available addressed.
