### ISSUE TITLE
Always Encrypted Cmdlets

### ISSUE THREAD

**Issue by zippy1981** [sqlcollaborative/dbatools#1292]
- [x] *feature* 
- [ ] *bug*:

## System Details

I propose the following improvments

* `Get-DbaMasterKey` We should add these members:
   * `CertificateExists` bool if the current user can read the certificate. Probably throws an exception if the answer is maybe, such as a need to ask the Azure Key Vault
  * GetCertificate should return the certificate in the same object format as `New-SelfSIgnedCertificate`
* `Invoke-DbaMasterKeyRotation -Database string|SmoDatabase|SqlClientConnection [-OldKey string|Certificate|MasterKey] -NewKey string|Certificate|MasterKey [-ColumnKeys IList<string>]` If you don't list the CEKs it will rotate for every column that the master key has. If you don't specify the old key, its going to replace all certificates for all master keys.
* `Set-SqlColumnEncryption2` A pure T-sql version of this function with more debugging and such.

**Comment by potatoqualitee** [comment]
hey @zippy1981 - thanks for the info! We actually have some encryption commands in the **develoment** branch. Can you take a look and let me know what you think of what we've got so far? We're still testing/fixing a couple, can't recall which ones tho lol. It's been a furious coding storm the past couple weeks.

```
PS C:\github\dbatools> Get-Command -Module dbatools -Type Function *masterKe* | select name

Name
----
Get-DbaMasterKey
New-DbaMasterKey
Remove-DbaMasterKey


PS C:\github\dbatools> Get-Command -Module dbatools -Type Function *certificate* | select name

Name
----
Export-DbaCertificate
Get-DbaCertificate
Import-DbaCertificate
New-DbaCertificate
Remove-DbaCertificate
```

The masterkey rotation looks cool, as does the Set-DbaColumnEncryption.

**Comment by zippy1981** [comment]
The DbaCertificate functions wont work with alwaysencrypted certificates as far as I can tell, but thats how it should be. The AlwaysEncryptedverts are  not stored in the DB.

GetDbaCertificate is pretty much what I envisioned. I'll see if SMO can pull the actual cert if the user has access to it 

I'll probably close this ticket soon and open up some smaller more specific ones.

**Comment by zippy1981** [comment]
@cl updated base ticket.

**Comment by zippy1981** [comment]
Doing #5639 brings us closer to this.

**Comment by zippy1981** [comment]
The thing is the sqlerver module makes the CMKs, CEKs and encrypts the columns. So what do we want to achieve?

* [ ] Get an unencrypted CEK from the DB
* [ ] Get-DbaColumnMasterKeys should query sys,column_master_keys and see if it can retrieve the key (and have a -IncludeCert to actually include the Cert as a property
* [ ] Invoke-DbaRotateCMK would take a Certificate or CMK as a parameter, rotate the CMK into the CEK, and then rotate the old CEK out with options to -DeleteOldCmk -DeleteOldCertificate

Also we need Azure Keyvault functionality. AzureRM is probably the best tool for that.

**Comment by wsmelton** [comment]
Cleaning up issues...

Someone wants to tackle this can re-open it.
