### ISSUE TITLE
 Out-GridView with PassThru should be possible to use for migrating logins, jobs and databases

### ISSUE THREAD

**Issue by peturgretars** [sqlcollaborative/dbatools#1296]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [X] *feature* 
- [ ] *bug*:

## System Details

- Operating system name and version: Windows 2016 
- Output from `$PSVersionTable`:

Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
PSVersion                      5.1.14393.1198                                                                                                                                                            
PSEdition                      Desktop                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                   
BuildVersion                   10.0.14393.1198                                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                       
SerializationVersion           1.1.0.1   

- Output of dbatools version:

```
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                               
---------- -------    ----                                ----------------                                                                                                                               
Script     0.8.956    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy-SqlServerAgent...}  

```

- SQL Server version for source/target
From SQL Server 2008 R2 and upwards. 

#### Example:
I have been using in past the following command to migrate selected databases from one instance to another using Out-Gridview and PassThru. This has been very useful when you have hundreds of databases and only want to migrated a portion of them. 

`Get-SqlDatabase -ServerInstance InstanceName | Out-GridView -PassThru | Copy-SqlDatabase -Destination InstanceName -BackupRestore -NetworkShare \\server\share`

I have now tried this for copying logins between instances. There are hundreds of logins and I would have only liked to copy portion of them but this does not seem to work with Copy-SqlLogin 

I would like to have this working with most of the Copy-Sql functions but starting with at least Copy-SqlLogin, Copy-SqlJob and Copy-SqlDatabase. 

Could this be already made available in dbatools version 1.0?

**Comment by potatoqualitee** [comment]
all 3 have been implemented 💯
