### ISSUE TITLE
Dev branch - piping gci to restore only restores full

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1300]
## Is this:

- [ ] *feature* 
- [x] *bug*:

## Details
Dev branch - 

gci \\dc\oladir | restore-dbadatabase bot with and without maintenancesolution param does not process full/diff/log - only full

**Comment by Stuart-Moore** [comment]
Afraid I can't replicate:
![image](https://cloud.githubusercontent.com/assets/5613670/26359509/92f5e172-3fcd-11e7-87b7-05471233c57d.png)
![image](https://cloud.githubusercontent.com/assets/5613670/26359587/cb7692b2-3fcd-11e7-8e63-34c25b2b57db.png)

Not run the actual restores, but the sql  includes files from FULL, DIFF and LOG.
When you're back could you try again, or let  me the folder you're having issues with please.

**Comment by Stuart-Moore** [comment]
Hey @potatoqualitee is this still an issue for you?

**Comment by Stuart-Moore** [comment]
Closing as no update and I couldn't repro
