### ISSUE TITLE
Copy-DbaDatabase - copy from older version SQL Server to newer

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#1302]
## Is this:

- [ ] *feature* 
- [x] *bug*:

#### Example:
1. Created database/object/files/etc
2. Run Command:
```powershell
Copy-DbaDatabase -Source SQLServer2012 -Destination SQLServer2008R2 -Database SomeVeryUsefulDatabase
```
3. Received following error
```powershell
Copy-DbaDatabase: ERROR: Destination server are older version than Source, database files or backup cant be copied from newer SQL Server to older SQL Server version.
```

**Comment by Zhunya** [comment]
-NoCopyOnly - is never used in Copy-DbaDatabase.

**Comment by wsmelton** [comment]
I was thinking about this last night for some of the other copy commands that couldn't support backward paths (e.g. Copy-SqlLogin the hash changed with 2012 so you can't copy a login from 2012 > 2008 R2).
