### ISSUE TITLE
Backup-DbaDatabase -SqlCredential -Database parameters cause error

### ISSUE THREAD

**Issue by CharterSteel** [sqlcollaborative/dbatools#1305]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x ] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                                                                                
----                           -----                                                                                                                                                
PSVersion                      5.1.14393.1198                                                                                                                                       
PSEdition                      Desktop          
                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                              
BuildVersion                   10.0.14393.1198                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                  
SerializationVersion           1.1.0.1 
```

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```
ModuleType Version    Name                                ExportedCommands                                                                                                          
---------- -------    ----                                ----------------                                                                                                          
Script     0.8.957    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy-SqlServerAgent...}

- SQL Server version for source/target

SQL 2017 CTP 2.0

#### Example:
1. Attempting to backup databases on remote machine
2. Run the following:
$BackDir='\\mfg_dev_jhhlt\AGShare\'+(get-date).ToString('yyyyMMdd')
Backup-DbaDatabase  -SqlInstance VMMars1\mfgSKVdb -BackupDirectory $BackDir `
 -Databases WorkCenterUtilization, SupervisorDB -Type Full -CompressBackup -CreateFolder -SqlCredential hisejouadmin

```
3. Received following error

Backup-DbaDatabase : A parameter cannot be found that matches parameter name 'Databases'.
At line:3 char:2
+  -Databases WorkCenterUtilization, SupervisorDB -Type Full -CompressB ...
+  ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Backup-DbaDatabase], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Backup-DbaDatabase


## Expected Results
 I expected a backup to happen.

If I run the same code, but leave out the SqlCredential parameter it works...

$BackDir='\\mfg_dev_jhhlt\AGShare\'+(get-date).ToString('yyyyMMdd')
Backup-DbaDatabase  -SqlInstance VMMars1\mfgSKVdb -BackupDirectory $BackDir `
 -Databases WorkCenterUtilization, SupervisorDB -Type Full -CompressBackup -CreateFolder

### Import - Attach dbatools logs
- Latest release of dbatools now includes a messaging and logging system. You can find this information via the `Get-DbaConfig` function. Use of the Set-DbaConfig controls the configuration of the system.
- Ensure this returns **true**: `(Get-DbaConfig -Name errorlogenabled).value`
- Locate the log path for the error logs using this command: `(Get-DbaConfig -Name dbatoollogpath).Value`
- **Attach the latest xml and log files found in the path shown.**

Get-DbaConfig -Name errorlogenabled).value returns as True, however
Get-DbaConfig -Name dbatoollogpath).Value seems to be null

**Comment by Stuart-Moore** [comment]
Is hisejouadmin just the username you want to connect with? The Sql credential parameter expects a Powershell credential (username and password). 

Can you please  try again adding:
$cred = get-credential 
Enter details in the box
And replacing hisejouadmin with $cred

**Comment by CharterSteel** [comment]
I tried it with the edit you suggested and got the same results. What is also odd is that when running  get-help Backup-DbaDatabase -Full I do not see Databases listed as a parameter either. Yet when called without the credential switch it runs.

I attached the help file output in case that helps. Do you use the credential switch without issue?

John Hise
Manufacturing Intelligence System Architect

**Comment by CharterSteel** [comment]
Let me ask a question after looking at some of the other scripts and how they used SqlCredential, I may have misunderstood something. Is that parameter only for sql logins? If so, then it makes sense that I was having trouble. That was actually a windows login that I was using. Some of the other scripts have flavors of sql credential and make a point to say that it is only for sql logins. If all that is true then it really is not a bug. The error message mislead me, coupled with get-help not showing the database parameter, and I got confused.

If the above is true then the issue can be cleared, sorry for any confusion.

John Hise
Manufacturing Intelligence System Architect

From: Hise, John
Sent: Wednesday, May 24, 2017 8:50 AM
To: 'sqlcollaborative/dbatools'; 'sqlcollaborative/dbatools'
Cc: 'Author'
Subject: RE: [sqlcollaborative/dbatools] Backup-DbaDatabase -SqlCredential -Database parameters cause error (#1305)

I tried it with the edit you suggested and got the same results. What is also odd is that when running  get-help Backup-DbaDatabase -Full I do not see Databases listed as a parameter either. Yet when called without the credential switch it runs.

I attached the help file output in case that helps. Do you use the credential switch without issue?

John Hise
Manufacturing Intelligence System Architect

**Comment by Stuart-Moore** [comment]
Hi,
Yes, that's our old style dynamic parameters. Once it's gotten a sql instance and credentials (if needed) it creates a database parameter filtered to existing dbs.

They're gradually being replaced with TEPP (Tab Expansion PlusPlus) as we type.

Cheers
Stuart
