### ISSUE TITLE
Add property IsAccessible to Get-DbaDatabase

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1310]
## Is this:

- [X] *feature* 
- [ ] *bug*:

In cases where a user (or dbatools function) needs to return the databases that are online and accessible (e.g. not a database in an AG secondary) there is no way to accurately determine this simply by checking the "Status" property. The "IsAccessible" column will return a bit value that accurately tells whether you can read objects/data from the database or not.

**Comment by potatoqualitee** [comment]
ouuu good one
