### ISSUE TITLE
Proposal Get-ConnectionStringBuilder

### ISSUE THREAD

**Issue by zippy1981** [sqlcollaborative/dbatools#1311]
- [x] *feature* 
- [ ] *bug*:

Started writing this before I got the official ok, but at least I'm figuring out Pester, etc.

Very simple idea. It takes a string as a parm, returns a [SqlConnctionStringBuilder](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnectionstringbuilder(v=vs.110).aspx). 

Long term goal would be to make  sure the cmdlets that take connection strings also accept this.

**Comment by zippy1981** [comment]
@potatoqualitee so can we close this or do we wait till it gets merged into master?

**Comment by potatoqualitee** [comment]
closed as soon as it's in dev is good with me
