### ISSUE TITLE
Restore-DbaDatabase to handle copy-only fulls

### ISSUE THREAD

**Issue by CharterSteel** [sqlcollaborative/dbatools#1320]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x ] *feature* 
- [ ] *bug*:

Just a request to handle using copy-only as the full anchor. In my version (0.8.957), the LSNs on the Tlogs do not meet the criteria used in Get-FilteredRestoreFile.ps1 when using a copy-only backup for the full. This is useful for using availability groups as the source of backups where you can only do copy-only for the fulls.

I did experiment and could get it to work by a small change in Get-FilteredRestoreFile.ps1, but do not know if there are unexpected consequences...the edit I tried is here where the first line is the commented out original, and second is the test. I changed -eq to -le for one of the comparisons.

                #$Tlogs = $SQLBackupdetails | Where-Object {$_.BackupTypeDescription -eq 'Transaction Log' -and $_.DatabaseBackupLSN -eq $Fullbackup.FirstLsn -and $_.LastLSN -gt $TlogStartLSN -and $_.BackupStartDate -lt $RestoreTime}
                $Tlogs = $SQLBackupdetails | Where-Object {$_.BackupTypeDescription -eq 'Transaction Log' -and $_.DatabaseBackupLSN -le $Fullbackup.FirstLsn -and $_.LastLSN -gt $TlogStartLSN -and $_.BackupStartDate -lt $RestoreTime}

**Comment by Stuart-Moore** [comment]
It'll be something to do with your particular setup as it doesn't really care about copyonly.

I've just built a test rig  using this: https://gist.github.com/Stuart-Moore/23f0302d9fec8ffec91f1a5a89eede11

And then restored it using these 2 commands:
Ignore the copyonly backup:
gci C:\dbatools\restoreCopyOnly\ | ?{$_.name -notlike "*only2.bak"} | Restore-DbaDatabase -SqlInstance localhost\sqlexpress2016

Start from the most recent full which happens to be a copyonly in this case:
gci C:\dbatools\restoreCopyOnly\ | Restore-DbaDatabase -SqlInstance localhost\sqlexpress2016 -OutputScriptOnly

Both restored fine.

Could I take a look at the file info of the files you're trying to restore please? If you could run this:

GCI \\path\to\backup\folders | Read-DbaBackupHeader -sqlserver $MySqlInstance | select @{Name='servername';e={"testserver"}}, @{n='databasename';e={"testdb"}}, FirstLsn,LastLsn, CheckPointLSN, DatabaseBackupLsn, DifferentialBaseLsn, BackupStartDate, BackupFinishDate, BackupTypeDescription, BackupSetGUID, FirstRecoveryForkID | ConvertTo-Json

replacing the path and sql instance, and then paste the output (or save to a file) and paste it up here that'd be great.

**Comment by CharterSteel** [comment]
Here you go Stuart. This is the output of the command you sent me. The bak file should be copy only; i.e. w/o the -NoCopyOnly switch. The trn files were created WITH the -NoCopyOnly switch.

[CopyOnlyFile.txt](https://github.com/sqlcollaborative/dbatools/files/1038319/CopyOnlyFile.txt)

**Comment by CharterSteel** [comment]
Must have hit the close and comment button by mistake.

**Comment by CharterSteel** [comment]
And to make sure I communicated well...I am talking about the scenario where I have already restored the bak and a series of trn files, but then want to restore the NEXT trn file, without restoring the whole set again. That is when I get the error. For instance, the get history command on the source instance grabs the file created in the last half hour and passes it to the restore command on a different instance. When trying to restore that one file I get the warning message

Get-DbaBackupHistory -SqlServer VMMars1\mfgskvdb -Databases SupervisorDB -Since  (get-date).AddMinutes(-30) |
Restore-DbaDatabase -SqlInstance VMMars1 -WithReplace

WARNING: Get-FilteredRestoreFile - No Full backup found to anchor the restore

**Comment by Zhunya** [comment]
Hi CharterSteel,

The version with which you tried to restore new log files, did you get it from development branch?
If not, please, get development branch and test it for continuos log files restore.

In current dev state Stuart made new switch "Continue" which you may find very useful in your situation.

But please be carefull, you use development branch on you own risk.

You just need to change you line to this one:
```powershell
Get-DbaBackupHistory -SqlServer VMMars1\mfgskvdb -Databases SupervisorDB -Since (get-date).AddMinutes(-30) | Restore-DbaDatabase -SqlInstance VMMars1 -Continue

```

**Comment by CharterSteel** [comment]
First, I will confess my unfamiliarity with github. I was unsure how to get the dev branch code. I finally found it and copied just the restore-dbadatabase code. It turns out it needed something in the internals folder. Rather than chase things around I brought down the entire dev branch and managed to get it installed. Here are some observations:

Running this...

Get-ChildItem -Path C:\Backup\20170531\SupervisorDB  |
Restore-DbaDatabase -SqlInstance VMMars1 -WithReplace -NoRecovery -StandbyDirectory C:\Backup

...worked great, no issues

Running this...

Get-dbabackuphistory -SqlInstance VMMars1\mfgSKVdb -Database SupervisorDB -Since (get-date).Date |
Restore-DbaDatabase -SqlInstance VMMars1  -WithReplace -NoRecovery -StandbyDirectory C:\Backup 

...did nothing. It does not seem to be handling the input from Get-DbaBackupHistory. Maybe because it is dev, but it used too.

So feeling a little suspicious about feeding the pipeline with the output of the backup history, I tried this having just did another log backup. The get/where part did indeed return the one file I was expecting...

Get-ChildItem -Path C:\Backup\20170531\SupervisorDB |
Where-Object { $_.CreationTime -ge (get-date).AddMinutes(-10)} |
Restore-DbaDatabase -SqlInstance VMMars1 -Continue -Verbose

...however I got this...

WARNING:  - Cannot connect to VMMars1

...seems to be something about the -Continue switch. I know it is in the dev branch, just wanted to let you know.

**Comment by Zhunya** [comment]
@CharterSteel 
To download dev branch do 4 next steps:
1. Push Branch button
2. Type "dev" in search box
3. Select "development"
4. Push "Clone or download" on the right side
after you download code, unzip it to any desired folder, open new Powershell console and import module from place you unzipped it to.

Then you can test how new code handle you problem and is it good for you.

![image](https://cloud.githubusercontent.com/assets/14327077/26654110/3457bf04-465e-11e7-9cfc-1f379cc8be65.png)

**Comment by CharterSteel** [comment]
Yep, that is what I did. I just did it again in case there was something new. I downloaded about 9:45am CST.

Another example. This code runs fine, I had to filter out the trn log that was getting created at the same time the full ran...

$DBNames = 'BackupTest'
foreach ($DBName in $DBNames){
$Path = 'C:\Backup\' +  (get-date).ToString('yyyyMMdd') + '\' + $DBName
$StandbyDirPath = 'C:\Backup\' +  (get-date).ToString('yyyyMMdd')
$LastBak =  GCI -Path $Path | 
Where-Object {$_.Extension -eq ".bak"} | select -Last 1

GCI -Path $Path |
Where-Object {$_.Name -ge $LastBak} |
Restore-DbaDatabase -SqlInstance VMMars1 -WithReplace -NoRecovery -StandbyDirectory $StandbyDirPath 
}

This code, only adding the -Continue switch...


$DBNames = 'BackupTest'
foreach ($DBName in $DBNames){
$Path = 'C:\Backup\' +  (get-date).ToString('yyyyMMdd') + '\' + $DBName
$StandbyDirPath = 'C:\Backup\' +  (get-date).ToString('yyyyMMdd')
$LastBak =  GCI -Path $Path | 
Where-Object {$_.Extension -eq ".bak"} | select -Last 1

GCI -Path $Path |
Where-Object {$_.Name -ge $LastBak} |
Restore-DbaDatabase -SqlInstance VMMars1 -WithReplace -NoRecovery -StandbyDirectory $StandbyDirPath -Continue
}
 
...gives error: WARNING:  - Cannot connect to VMMars1

These commands are coming from the same console session and user (me as a sysadmin). The -Continue switch is calling another piece of code that seems to be having trouble, at least for me; i.e. Get-RestoreContinuableDatabase.ps1

I just happened to think, I am testing with vNext CTP 2.0 . Maybe dbaTools does not work with this yet?

**Comment by CharterSteel** [comment]
Something else I have noticed...my code that fed the database names in via ... $DBNames = 'BackupTest' always failed when on the last database when I used $DBNames = 'BackupTest','WorkCenterUtilization' the SECOND time after the initial run; i.e. when the database did not exist it worked, but when trying it the second time it failed because there was a connection left for the database. You cannot restore a database in use. I finally created a database named "ZZZZ", and then the script seemed to connect to that database to do its thing. That way I could do the wholesale restores for all databases in the list.

Still getting the same warning about not being able to connect when trying to -Continue. I tried creating a sql user as an admin and passing in that credential with this code...

$cred = Get-Credential 
$files = Get-ChildItem C:\Backup\20170601\BackupTest
        $files | Restore-DbaDatabase -SqlInstance VMMars1  `
    			-continue -WithReplace -SqlCredential $cred `
    			-StandbyDirectory C:\Backup\20170601

...but no joy, same warning.

**Comment by Stuart-Moore** [comment]
Looks like an internal command got a rename. I've fixed up the bit that's erroring, so hopefully that should work now.

**Comment by CharterSteel** [comment]
WooHoo! ....  -Continue works now! Thanks much.

**Comment by CharterSteel** [comment]
BTW, looking at your picture I have to ask if you are indeed a falconer?

**Comment by Stuart-Moore** [comment]
I wish! Don't think my cats would appreciate sharing their house with one. I don't take good photos, so that's the best as the bird draws the eye ;)

Glad we've fixed your problem. Thanks for all the info, makes it a lot easier to find the issue if we've got that.
