### ISSUE TITLE
Password Related Cmdlets

### ISSUE THREAD

**Issue by zippy1981** [sqlcollaborative/dbatools#1321]
## Is this:
- [X] *feature* 
- [ ] *bug*:

It would be nice to have cmdlets to deal with sql server and ASP.NET passwords for the following scenarios.

* **Offline Sql Server password functions.** It's not hard to implement these in C#, and therefore powershell. It would be nice to be able to generate and verify password hashes offline
 * `Get-DbaSqlPasswordType` Get you the password type of a sql server password (apparently the algorithim change in 2012, I assume you can tell by the header of the hash
 * `Get-DbaSqlPasswordSalt` Get the salt of the password
 * `Get-DbaSqlPasswordHash` Generates a sql server password hash for a string. Optional [-Salt] option.
 * `Test-DbaSqlPasswordOffline` Compare a password to a hash
* **Asp.NET Password functions** Lots of DBAs have databases with the Owin ASP.NET passwords. Its convenient for DBAs to be able to reset them from powershell or verify them offline. I would start off implementing the EF6 version. This is trivial [as we could just call existing .NET dlls](https://aspnetidentity.codeplex.com/SourceControl/latest#src/Microsoft.AspNet.Identity.Core/Crypto.cs). It might make sense to copy this to our own class just because no every machine will have that DLL. 
 * `Get-DbaAspNetPasswordHash` Generate a password hash from a string with an option `-Salt` pre-specified. 
* `Get-DbaAspNetPasswordSalt` Return the salt part of a password string.
 * `Test-DbaAspNetPassword` I don't think we need the word offline here unlike the other cmdlet where thats the "big deal"

### Code considerations
Would it make sense to put all the C# code for this in a DLL, maybe in a separate project that becomes a separate nuget project? Maybe that is a future step? Is there an open source DLL that does all this in C# that we can wrap around?

### Old version considerations
I don't know if I can inspect password hash and say this hash uses the algorithm used by this version. I also don't know if I can manually insert a hash with an old password algorithm into sql server vnext so I don't need to go run multiple instances on my laptop.

If we go with the ASP.NET cmdlets, how far back do we want to go?

###References
* [Thorough code review of me doing the ASP.NET Implementation in PHP](https://codereview.stackexchange.com/questions/164144/asp-net-password-hashing-reimplemented-in-php/164189?noredirect=1#comment312211_164189).
* [The first google result of how password hashses work in sql server 2012 with enough info for me to get started](http://sqlity.net/en/2460/sql-password-hash/)
* Well apparently there are more options with [ASP.NET identity 3.0](https://github.com/aspnet/Identity/blob/e6f3ebf5810c793edc6f3b4ca3438194786b86a2/src/Microsoft.AspNetCore.Identity/PasswordHasher.cs).

**Comment by potatoqualitee** [comment]
Great ideas! I'd prefer Get-DbaSqlPassword with columns for the relevant information.

Test-DbaPassword probably could just do an -Offline option?

As for AspNet, I can see it being useful - i actually wanted to add something for SharePoint to SQL Server or vice versa dont remember. The /bin folder already has some dlls. Are they reasonable in size and properly licensed to be includedin GPL 3?

**Comment by zippy1981** [comment]
As for the DLLs, I don't know if any exist. Honestly the functions are pretty small. The ASP.NET code is MIT licensed (allowable for inclusion into GPL3 code), so no problem just copy-pasting that into dbatools. I would refactor it a bit to expose the ability to get the salt and set a specific salt.

**Comment by zippy1981** [comment]
Two questions @potatoqualitee  

1. If TestDbaPassword could verify the password offline, why would you even want to bother asking sql server to do it? Even if you could make an argument for that, I think offline would be default and you'd have `[switch] $Online, [PSObject] $ServerInstance`
1. What columns would you envision for `Get-DbaSqlPassword` ? Version, hash, salt?

**Comment by potatoqualitee** [comment]
1. I'm throwing stuff out there, I don't know shit ;) If SQL Server isn't needed, then we only do Test-DbaPassword
2. Yeah, the standard 3 (ComputerName, InstanceName, SqlInstance) plus those two and whatever else you think is important.

**Comment by zippy1981** [comment]
Work on the C# part of this is basically complete but in a separate repo for now.

https://github.com/zippy1981/Sqlcollective.Dbatools

Stay tunned will work with @FriedrichWeinmann to get this in the proper repo

**Comment by zippy1981** [comment]
Ok closing this issue. Opening a new one.
