### ISSUE TITLE
Linux/docker continous integration support

### ISSUE THREAD

**Issue by zippy1981** [sqlcollaborative/dbatools#1336]
## Is this:
- [X] *feature* 
- [ ] *bug*:

## System Details

- Operating system name and version:
Ubuntu Linux

## Objective

So rather than some overarching strategic plan to get dbatools working on linux (which ultimately depends on SMO being ported for us), lets just setup dbatools to run on CircleCI in a linux docker image and once we see what actually sort of works, go from there.

## Overview of steps

* Make a docker-compose.yml that spins up sql server for linux and a ubuntu image that installs powershell and mounts the git repo somwhere
* Setup CircleCI to do the following
 * Run the unit tests
 * Run the integration tests
 * Test that the log messages were not unusual

Once that's working maybe we could say "x% of our cmdlets actually work" or "maybe we should figure out how to tell if a cmdlet needs SMO or not." Then we can draw conclusions like "bitch at Microsoft to open source SMO or release it for linux" or "we can do this or that to make more of these cmdlets work on linux"

**Comment by wsmelton** [comment]
Every command is going to need SMO for the simple fact they all call `Connect-SqlServer`, which creates and outputs an SMO server object. We do not use exclusive .NET to make any connection to SQL Server so until SMO is ported to Linux dbatools will have to run on Windows.

**Comment by wsmelton** [comment]
Closing this as a good portion of the module runs in PS Core now which can be installed on Linux.
