### ISSUE TITLE
After upcoming release: Let's address the sysadmin requirement & providing more info on connect failure

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1355]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details
Let's address the sysadmin requirement & providing more info on connect failure

**Comment by wsmelton** [comment]
I'm not sure I follow what sysadmin requirement you are talking about?

Most actions we have in commands can be done without being given explicit sysadmin role membership. Are we talking about verifying a user's permissions when they connect or something? If so, why? 

Any error message you get from SQL Server, whether it be direct SMO or running a query, will give in the exception that permission was denied.

**Comment by wsmelton** [comment]
Quick idea...internal function that at most validates permissions. 

Initial version we just check for role membership, [example](https://sqldbawithabeard.com/2013/09/02/checking-sql-server-user-role-membership-with-powershell/).

I have not looked to deeply but have to think there is some Enum method in SMO that will cycle through permissions a given login has for instance level and database maybe that we could use for more detail checking.

Majority of the docs for SQL Server though only specify role membership. With a few actions noting things like `must have VIEW SERVER STATE`.

**Comment by wsmelton** [comment]
We then add a parameter to `Connect-SqlInstance` to pass in the permissions. Have some mapping maybe in a json file that we can update easily. Like `Permission` that would pass in say a role or explicit name:

```powershell
#action requires sysadmin role explicitly
Connect-SqlInstance -SqlInstance myserver -MinimumVersion 10 -Permissions securityadmin

#action requires explicit permissions, not requiring a role memebership
Connect-SqlInstance -SqlInstance myserver -MinimumVersion 12 -Permissions 'VIEW ANY DATABASE','VIEW SERVER STATE'
```

[Reference all SQL Server security posters](https://github.com/Microsoft/sql-server-samples/tree/master/samples/features/security/permissions-posters)

**Comment by wsmelton** [comment]
@potatoqualitee I think we have already addressed this one have we not?

**Comment by potatoqualitee** [comment]
No way,  cl!
