### ISSUE TITLE
Test-DbaSpn's output sometimes missing a variable

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1366]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details

```
WARNING: [Test-DbaSpn][02:05:07] AD lookup failure. This may be because the domain cannot be resolved for the SQL Server service account (NT Service\MSSQL$STANDARDRTM).
WARNING: [Test-DbaSpn][02:05:07] AD lookup failure. This may be because the domain cannot be resolved for the SQL Server service account ().
WARNING: [Test-DbaSpn][02:05:07] AD lookup failure. This may be because the domain cannot be resolved for the SQL Server service account (NT Service\MSSQL$STANDARDRTM).
WARNING: [Test-DbaSpn][02:05:07] AD lookup failure. This may be because the domain cannot be resolved for the SQL Server service account ().
```

Merci!

**Comment by niphlod** [comment]
hum. from the looks of it, it shouldn't even pick them up to look for an object. I'll try to see where it creeps in from the code.

BTW: is that happening on an env you have access to ?

**Comment by niphlod** [comment]
oh yes. found the bug. or, for better saying, found the missing feature. These cmdlets never supported the case of local accounts!

**Comment by potatoqualitee** [comment]
yeah, you know, it would be better if no warning was there for local accounts. A verbose perhaps. Thank you for taking the time to find the bug!

**Comment by niphlod** [comment]
better tackling them than opting out for a usecase scenario. Here you have it #1368
