### ISSUE TITLE
If $source exists as text within a trigger, it will materially change the content of the trigger

### ISSUE THREAD

**Issue by ConstantineK** [sqlcollaborative/dbatools#1383]
## Is this:
- [ ] *feature* 
- [x] *bug*:

In https://github.com/sqlcollaborative/dbatools/blob/master/functions/Copy-SqlServerTrigger.ps1#L143
we replace the instance name with the destination name, but in the case that the SQL Server name is also a keyword or something that is used in code, we might be making too greedy of a replacement. 

We need to replace only the location of the server within the portion that contains it instead of in the entire trigger.

#### Example:
1. Use Copy-SqlServerTrigger to copy a trigger
2. Name your source server any keyword which also appears in the trigger
3. The destination server (if the trigger is even created) will have a broken trigger.

**Comment by ConstantineK** [comment]
This approach appears in a few other commands, which I also want to document here.

**Comment by ConstantineK** [comment]
https://github.com/sqlcollaborative/dbatools/search?utf8=%E2%9C%93&q=%5BRegex%5D%3A%3AEscape%28%22%27%24source%27%22%29&type= There are >20 examples of this in the code, this looks like a burn down list after we find the general approach we want to take.

**Comment by wsmelton** [comment]
This should reference all the commands that use that pattern in code, along with the line number:
https://github.com/sqlcollaborative/dbatools/pull/1322

**Comment by wsmelton** [comment]
Chatting with @ConstantineK about this one in Slack as it is intriguing. @potatoqualitee I would say this revolves around the need to have the actual regex statement in the copy commands to begin with. I mean when you script a trigger (server or database) the is no reference to the server it came from in that script.

A SQL Job maybe the closes you get to needing it but even that is going to be special occasions. Unless someone has set the job server to a different server or something would be only reason it shows something other than `(local)`.

**Comment by potatoqualitee** [comment]
so far this seems to be an effective way to handle most migrations. I will suggest `Export-DbaScript` for more power over the process.
