### ISSUE TITLE
Name parameter New-DbaDatabaseSnapshot should be name of snapshot and not suffix

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1388]
## Is this:

- [ ] *feature* 
- [X] *bug*:

## Steps to Reproduce

1. Run Command:
```powershell
New-DbaDatabaseSnapshot -SqlInstance server -Database Northwind -Name Northwind_dbss
```
3. Received snapshot named "NorthwindNorthwind_dbss"

## Expected Results
1. Run Command:
```powershell
New-DbaDatabaseSnapshot -SqlInstance server -Database Northwind -Name Northwind_dbss
```
3. Receive snapshot named "Northwind_dbss"

As it is called "Name" it should be the exact name of the snapshot being created. If a user wants to append the something to the name of the snapshot a parameter like "Suffix" or "Append" should be provided.

**Comment by niphlod** [comment]
it's really neither, more of a "template" . 
If it's accepted as a solution I can work in a `-Name` that takes the exact string passed in OR a `-NameTemplate` that takes the interpolation as it is right now

**Comment by wsmelton** [comment]
Template does not sound right to me. Whether you want to use the math term (yeah I googled it :expressionless: ) you are appending the value to the basename of the snapshot. 

I would say offer both the `-Name` and a `-NameSuffix`, which is more self-explanatory than NameTemplate. I'll leave that to @potatoqualitee .

**Comment by niphlod** [comment]
you can pass a `-Name 'fool_{0}_snap'` to have the `{0}` placeholder to be picked up from the databasename... 

nonetheless in any other case is a suffix.

**Comment by Zhunya** [comment]
I working on template system for file and path parameters for Backup-DbaDatabase, may we move template handling to internal function?

**Comment by niphlod** [comment]
dunno if it's needed.... if you want to support flexibility, a template string is plenty. The "problem" here is just naming parameters properly, not the functionality itself

**Comment by niphlod** [comment]
@potatoqualitee : ideas on the parameter naming here ?

**Comment by potatoqualitee** [comment]
I like shawn's suggestions
