### ISSUE TITLE
[New Command] Test-DbaLoginAccess (similar to Test-DbaValidLogin)

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1395]
## Is this:

- [X] *feature* 
- [ ] *bug*:

Being that this could be very similar to Test-DBaValidLogin it may be prudent to see if this meets the requirement of just expanding the current function, or making a new one.

I want to say this had been discussed on the old Trello board but a function that offers something along the lines:

_format that could build this out as pester test first_

- Input an AD Windows Login, formatted as "Domain\Username"
- Output property HasAccess (true/false)
- Output property Path (or whatever) that shows the AD Group or explicit AD Login found on the instance.
- Output SQL SID and Windows SID ([reference on difference and possibly how](https://dba.stackexchange.com/questions/175271/how-do-i-translate-a-windows-sid-to-an-sql-server-server-user-sid)) 
- Possibly multiple objects returned if the "Domain\Username" is found to have access via multiple logins (explicit and AD Groups possibly).

This would utilize the `xp_logininfo` procedure, and there was some SMO method I recall seeing. Writing this out there may be an old issue already noting some of how this could be done.

**Comment by PowerDBAKlaas** [comment]
I remember having a lot of change requests on Test-DbaValidLogin that were never addressed.
A complete test would also include whether those accounts are disabled, and password has not expired,...

**Comment by wsmelton** [comment]
Which password (e.g. SQL Server or AD's)?

Disabled would be good but again (SQL Server or AD's)?

Password expired would not care from my perspective I only care if it has access to the system/databases....but something that could be included.

**Comment by PowerDBAKlaas** [comment]
Well, I see this command especially used in cases where a DBA wants to know why an account can or can't do his job, so all those properties are crucial.
At least that was the idea for Test-DbaValidLogin.
I think it would be handy to have all functionality in one command, unless there's other uses where all this would never be needed. But since both SQL Server and AD are going to be queried anyway, there's no extra cost.

**Comment by wsmelton** [comment]
Well based on initial review of `Test-DbaValidLogin` it DOES NOT validate a SQL Login. It only works with AD logins so that should actually be renamed or add the logic to accept any login type.

Which maybe we should have separate commands for each type because you do so much more to validate an AD account. Just have `Test-DbaSqlLogin` and `Test-DbaWindowsLogin`. I think those would be easier to test as well, trying to do all of that and then what this issue discusses would be a beast of a command.

Adding others to this so they can chime in if needed.

**Comment by niphlod** [comment]
no probl. Renaming the existing AD cmdlet was already something needed (see https://github.com/sqlcollaborative/dbatools/pull/994#issuecomment-291444502 )
Maybe now it's the time (i.e. before 1.0) ?

**Comment by PowerDBAKlaas** [comment]
@niphlod oh man, I totally forgot you did all that work. My memory got stuck in the phase where the original author didn't reply anymore.
Reading that discussion again, we were pretty smart back then, no? 😄 

@wsmelton you would split it because of the length of the code?
From a user's perspective I'd still prefer a single function. Maybe we can decide on that once there's some progress?

**Comment by wsmelton** [comment]
Not necessarily length but managing both sets of logic would be easier to have 2 separate commands. 

If we are talking about adding in logic of how an AD login has access, consider a login that has access via a sub-group that is 3 levels deep from the login group that was added to an instance. How much code would it take for you to build that path from a recursive search in AD? Adding a few lines to validate a SQL Login would obviously not be adding more than maybe a dozen lines of code....but why add more to an already fairly complex command.

**Comment by potatoqualitee** [comment]
This is a feature request, yah?

**Comment by wsmelton** [comment]
Closing this...if it comes back up we can create a new issue around what changes we want to make or need.
