### ISSUE TITLE
Get-DbaTopResourceUsage

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1430]
## Is this:

- [x] *feature* 
- [ ] *bug*:

## Proposal

**This is a post 1.0 command, just placing this here as a reminder and include specific that myself and Chrissy already discussed.**

Command that is built around [Michael J Swart's top resource hog queries](http://michaeljswart.com/2013/09/my-queries-for-top-20-resource-hogs/). Potential is to have a single command, then have parameters drive which resource set to return. Would need to make sure you are excluding the current session from the query, and what versions of SQL Server these support (think 2008+ only).

I have used these queries for years to gather information on a given instance and they work very well as-is. There is likely some improvements that can be made, or expanded upon with latest versions of SQL Server.

**Comment by potatoqualitee** [comment]
here you go, baw https://github.com/sqlcollaborative/dbatools/pull/2305
