### ISSUE TITLE
[New Command] Set-DbaAgPrimaryServer

### ISSUE THREAD

**Issue by pcomtois** [sqlcollaborative/dbatools#1432]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Context
I have a small suggestion to make for a new DBATool: a controlled AOAG Failover. (with validations).
 
My Network Admin is not very good with SQL, but he is good with Powershell. When he wants to do the Windows Updates on the AlwaysOn SQL servers, I would like him to be able to run a script that would automatically check what server is the active/primary Availability Group (is it the current server?) (Get-DbaAvailabilityGroup) and if it is (or not), then perform a Failover to the other node.
 
## Expected results
1. Admin logs in on ServerOne, runs the script on the desktop.
2. The script validates that the ServerOne is the current Primary, then failovers to the ServerTwo.
3. Admin makes the patches on ServerOne
4. Admin logs on ServerTwo, and there is a similar script on the desktop that he runs. 
5. It validates that the ServerTwo is the current Primary, then failovers to the ServerOne.
6. Admin makes the patches on ServerTwo

## Parameters
Parameters could include:
1. "With Validation" flag of current active node (i.e. server the script is run from) or not
2. Name of the Secondary Node to failover to (some configurations have multiple secondary)
3. Name of the Instance/AOAG group/Listener to validate and failover (we have 2 instances per server, 1 AOAG per instance)
4. Credentials (probably just like the Sql-CopyDatabase)

(Please find a better name for this than the one I suggested!)

**Comment by potatoqualitee** [comment]
I like this one, thanks for the suggestion 👍 Will likely be after 1.0

**Comment by sirsql** [comment]
AvailabilityGroup.PrimaryReplicaServerName through SMO will give you the primary from any of the replicas

**Comment by wsmelton** [comment]
Random thought it might not be bad idea to write a test command to support the failover option,but also to just give general synopsis on the state of the AG.

**Comment by sirsql** [comment]
I've been doing a bunch of this shenanigans in SMO recently (which is how I found out that read-routing lists are broken with 2016). It's not terrible, but it is a pain.

**Comment by wsmelton** [comment]
You mean broken via SMO for read-routing lists? I have them in use in production for a client on 2016 and they work fine.

**Comment by sirsql** [comment]
It doesn't accurately reflect read routing load balancing in 2016.

On Aug 20, 2017 6:25 PM, Shawn Melton <notifications@github.com> wrote:

You mean broken via SMO for read-routing lists? I have them in use in production for a client on 2016 and they work fine.

**Comment by potatoqualitee** [comment]
Covered by `Invoke-DbaAgFailover`. Please comment if that is not the case.
