### ISSUE TITLE
Get-DbaBackupHistory fails on case sensitive instances

### ISSUE THREAD

**Issue by KennyNeal** [sqlcollaborative/dbatools#1435]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [ x] *bug*:

## System Details

- Operating system name and version:
Name                           Value                                                                                                                      
----                           -----                                                                                                                      
PSVersion                      5.1.14394.1000                                                                                                             
PSEdition                      Desktop                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                    
BuildVersion                   10.0.14394.1000                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                            
WSManStackVersion              3.0                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                        
SerializationVersion           1.1.0.1 
```


- Output of dbatools version:
ModuleType Version    Name                                ExportedCommands                                                                                
---------- -------    ----                                ----------------                                                                                
Script     0.8.957    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy-SqlServerAgent...}                   
Script     0.8.956    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy-SqlServerAgent...}      

- SQL Server version for source/target
2012

## Steps to Reproduce
1) call Get-DbaBackupHistory against a CS instance
2. Received following error
Exception calling "ExecuteWithResults" with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch."
At line:373 char:4
+             $results = $server.ConnectionContext.ExecuteWithResults($ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ExecutionFailureException

**Comment by potatoqualitee** [comment]
We certainly do need to add CS to our test pool. I'll ask @Stuart-Moore to do this one, but I think he may be on vacation. Thanks for the report, Kenny! 

@Stuart-Moore  can you also add the try catches?

**Comment by niphlod** [comment]
this has been fixed already in development, although the cmdlet needs some love. Will do a PR in a bit.
