### ISSUE TITLE
[New Command] Ensure-DbaLogin

### ISSUE THREAD

**Issue by FriedrichWeinmann** [sqlcollaborative/dbatools#1447]
## Is this:

- [x] *feature*

## Use Case

Accelerates deployment scenarios by ensuring the necessary logins exist.

## Details

A new command that makes sure a login exists on an instance and has the necessary settings/permissions.
Example usage:
```PowerShell
Get-Content instances.txt | Where-Object { $_ -like "uat*" } | Ensure-DbaLogin -Name "foo" -Privilege "sysdamin" -DefaultLanguage "British"
Get-Content instances.txt | Where-Object { $_ -like "dev*" } | Ensure-DbaLogin -Name "bar" -Privilege "dbowner" -DefaultLanguage "British"
```

Sooo ... basic usage:
 - Accepts `[DbaInstanceParameter[]]` as input from pipeline
 - Can specify all default user settings
 - Supports all system wide privileges in any combination
 - Supports per-database privileges (one parameter per privilege, accepts array of databases)
 - Supports parameter `-Mode` (`[DbaMode]`) with default mode `"Lazy"`, determining behavior when a database doesn't exist

**Comment by potatoqualitee** [comment]
Hey @FriedrichWeinmann - nice idea! But Ensure is not an approved verb.

Chrissy

**Comment by FriedrichWeinmann** [comment]
Damn!
How about `New-DbaLogin` with an `-Update` switch that makes it not error out on an already existing user? (Which a command with the `New-` Verb should by default)

**Comment by wsmelton** [comment]
Based on PR sounds more like a Test-DbaLogin?

**Comment by FriedrichWeinmann** [comment]
"Test-" performs no changes. This one does.

**Comment by zippy1981** [comment]
It seems to me that if New-Item -Force creates or replaces a file (or whatever) then `New-DbaLogin -Force` is what we want to do here.

**Comment by zippy1981** [comment]
Ok there is no Cmdlet called New-DbaLogin apparently. I'm going to gather new information and then form a new opinion!

**Comment by zippy1981** [comment]
Ok so I think New-DbaLogin should wrap around Add-SqlLogin, with splatting, unless -Force is specified. Then I think the easiest path would be 

1. Get all the users, server roles and server perrms associated with the login
1. Drop the login
1. Create the login with `Add-SqlLogin`
1. Reassocaite the users with the login
1. Reassocaite the users with the server roles
1. Reassocaite any preexisting server permissions and roles.

 However I think some paramaters passes to Add-SqlLogin could conflict with existinf permisions, i.e. DENY vs GRANTs.

**Comment by wsmelton** [comment]
Cleaning up issues...

Someone wants to tackle this can re-open it.
