### ISSUE TITLE
Cosmetic typo in output in install.ps1: "isntaller

### ISSUE THREAD

**Issue by SharePointPog** [sqlcollaborative/dbatools#1459]
Typo in message in install.ps1.

(I am new to this project, and do not know how to do all those steps listed in the template bug report.)

**Comment by SharePointPog** [comment]
Because I did not know how to fill in the bug template, I created a pull request for this (trivial) misspelling fix:

https://github.com/sqlcollaborative/dbatools/pull/1460

**Comment by potatoqualitee** [comment]
resolved :) thanks @SharePointPog !
