### ISSUE TITLE
Cosmetic: mismatched parens in documentation web page https://dbatools.io/functions/copy-sqllogin/

### ISSUE THREAD

**Issue by SharePointPog** [sqlcollaborative/dbatools#1461]
Cosmetic: mismatched parens in documentation web page https://dbatools.io/functions/copy-sqllogin/

In the second paragraph, there are two opening parentheses and one closing one, which is slightly odd.

Also, although I don't know if it is worth mentioning, the first paragraph has several sentence fragments missing subjects: specifically the second & third sentences.

**Comment by wsmelton** [comment]
Thanks for reporting. Documentation will be overhauled for the 1.0 release on the web page but will not be something we get to u til the very end.
