### ISSUE TITLE
Typo in https://dbatools.io/functions/copy-sqlcredential/ ?

### ISSUE THREAD

**Issue by SharePointPog** [sqlcollaborative/dbatools#1462]
I don't understand the following sentence at https://dbatools.io/functions/copy-sqlcredential/

> This command requires sysadmin access on both the SQL Server and the Windows server.

I wonder if it was a typo for "both the source and destination servers" ?

**Comment by FriedrichWeinmann** [comment]
It means you need to authenticate both against the sql instance (with sysadmin privileges) and the windows operating system running the instance (with local admin)

**Comment by SharePointPog** [comment]
Which windows instance? The source? One of the destination cluster instances?

**Comment by SharePointPog** [comment]
Actually, never mind, someone closed my other documentation bug saying the documentation won't be fixed, because it is intended to all be replaced, so, probably not worth trying to figure this out.
