### ISSUE TITLE
Expand output of Get-DbaProcess

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1478]
## Is this:

- [X] *feature* 
- [ ] *bug*:

Using this command on customer environment trying to find out what certain logins I need to drop are doing (can't drop a login that is currently logged in). Finding that this does not output some of the information I need, which sp_whoisactive does provide but would be nice to have it added to this command.

I see the command is using `EnumProcess` to grab the sessions which is very limited on what properties it offers. We may need to change this to a more robust T-SQL statement. I have the query that is executed when you open the ActivityMonitor from 2008 R2 and 2014 instance. Maybe we expand it using that output? 

We could also offer the option of using `spWhoIsActive` if it is found and let them pass in the column output parameter to customize what is output if desired. Otherwise, it just does the default (just runs the procedure).

**Comment by potatoqualitee** [comment]
mmm get-dbaprocess was expanded quite a bit since 2017 💯
