### ISSUE TITLE
New Property [Get-DbaLogin]

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1479]
## Is this:

- [X] *feature* 
- [ ] *bug*:

Add the `CreateDate` to the output so we can see when the login was created.

**Comment by galador** [comment]
I put in a PR for this one, but I guess it didn't automatically link it:

https://github.com/sqlcollaborative/dbatools/pull/1486

**Comment by potatoqualitee** [comment]
i think it has to be in the commit message 👎

**Comment by potatoqualitee** [comment]
Thank you for the PR! 👍
