### ISSUE TITLE
Pester test coverage for Serializing Sqlcollaborative.Dbatools.Utility.Size

### ISSUE THREAD

**Issue by zippy1981** [sqlcollaborative/dbatools#1480]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [X] *feature* 
- [ ] *bug*:

@FriedrichWeinmann you claimed that properties had empty setters because of the way powershell serialization worked. Can you write a short pester Integration test that does the following:

```
$size [Serializing Sqlcollaborative.Dbatools.Utility.Size] 5
# serialize size
# deserialize size
```

Using whatever serialization method you were talking about that breaks if we delete the setters on the properties? Or just point me in the right direction.  I'd like to explore if there is a way to remove those empty setters through something even if the regular Serialization attributes don't work.

**Comment by FriedrichWeinmann** [comment]
Sorry, but can't _right now_
It takes preparing the groundwork for it a bit. Technically nothing too onerous, but I wanted to go over my assumptions and plan it to be rock solid before doing it and that would make it a non-too-minor feature. Given my current schedule I can't commit to pulling that off before July, sorry

**Comment by niphlod** [comment]
we have this already

**Comment by zippy1981** [comment]
@niphlod where do we have this?

**Comment by niphlod** [comment]
@zippy1981 : I may only say "we had" at this point, was just doing spring cleaning (probably based on discussions on slack)
Bug opened 9 months ago, inspected and closed 4 months ago.... too much water under the bridge to remember exactly. 
feel free to reopen if we're missing
