### ISSUE TITLE
New command - Find-DBATrigger and Find-DBAView

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#1498]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ x] *feature* 
- [ ] *bug*:

Request from James Anderson @databaseavenger 

Please can you do the same magic for views and triggers as find-dbastoredprocedure please

**Comment by potatoqualitee** [comment]
ouuuu i dig. @ClaudioESSilva  or @Staggerlee011

**Comment by SQLDBAWithABeard** [comment]
So this came about because of a conversation with James. He needed to find the Stored Procedures, Triggers and Views that referenced a specific column in a specific table in a specific way in a database.

He had to script out the entire database and use RegEx to do this. He asked if dbatools would do so and I said yes Find-DbaStoredProcedure could have done the Stored Procedures but not the triggers or the views.

Therefore the feature request is for Find- commands for Triggers and Views that will enable user to search them both using wildcard and regex in the same way as Find-DbaStoredProcedure

**Comment by ClaudioESSilva** [comment]
Done: https://github.com/sqlcollaborative/dbatools/pull/1520 😄 

So for triggers I took into account the 3 levels (Server, Database and Object)
![image](https://user-images.githubusercontent.com/19521315/27713767-1e3416fe-5d25-11e7-8e98-a934046e8014.png)

**Comment by potatoqualitee** [comment]
rock on, yall!
