### ISSUE TITLE
Support for splatting with commands

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1514]
## Is this:
- [ ] *feature* 
- [X] *bug*:

## System Details
This should be supported in PS2.0 and above when splatting was added.

## Steps to Reproduce

1. Import the dbatools module
2. Create a hash of any number of parameters for a given command:
```powershell
$params = @{ SqlInstance = 'manatarms'; Database='pubs' }
#or just
$params = @{ Database='pubs' }
```
3. Run the command Get-DbaDatabase
```powershell
Get-DbaDatabase $params
# or on second hash
Get-DbaDatabase -SqlInstance MyServer $params
```
![image](https://user-images.githubusercontent.com/11204251/27695534-ca2530ea-5cb4-11e7-8b34-b8342e6f1d10.png)

Both of the above options work with native commands in PowerShell. It would be good to be able to support this because splatting supports more gracefully handling variables/parameters being passed in with no value. 

As well, support for splatting would allow us to handle variables not being passed in to whatever wrapper script we are building around dbatools.

**Comment by FriedrichWeinmann** [comment]
Heya, hate to break it to you, but splatting works like this:

```PowerShell
$params = @{ SqlInstance = 'manatarms'; Database='pubs' }
Get-DbaDatabase @params
```
Don't miss the `@` :)

**Comment by potatoqualitee** [comment]
Oh dang, I totally missed that! I just saw a 'sea of blood' ;)
