### ISSUE TITLE
Get-DbaErrorLog

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1528]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Details
Basically, cannibalize @drewfurgiuele's version: 
http://port1433.com/2016/10/25/building-a-better-get-sqlerrorlog/

This one has the online and offline approach talked about in the channel. And is within scope for 1.0 cuz I need it ;)

**Comment by dbaduck** [comment]
On it.

**Comment by dbaduck** [comment]
I have pushed it up to my branch.  Is there anything else that you want me to change in it?

**Comment by potatoqualitee** [comment]
sweet, do a PR and we'll check it out, @dbaduck !! thanks man
