### ISSUE TITLE
Copy-DbaAgentOperator - bug 

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1543]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details
Could use some more information here - perhaps using the -InnerErrorException one (guessed the name)

````
WARNING: [Copy-DbaAgentOperator][22:20:31] Issue dropping operator | Exception calling "Drop" with "0" argument(s): "Drop failed for Operator 'The DBA Team'. "
[Copy-DbaAgentAlert][22:20:31] Creating Alert Defaults
SourceServer      : sql2014
DestinationServer : sql2016
Name              : Alert Defaults
Type              : Alert Defaults
Status            : Successful
DateTime          : 2017-07-02 22:20:31.374
````

**Comment by wsmelton** [comment]
What was the error in the logs?

**Comment by potatoqualitee** [comment]
actually this is as good as this one will get - it's already the innererror

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann - can you check the syntax here and tell me what I'm doing wrong?

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann - can you check the syntax here and tell me what I'm doing wrong?

I want to get " 'The DBA Team' is the fail-safe operator. You must
make another operator the fail-safe operator before 'The DBA Team' can be dropped." but all I get is can't be dropped.

System.Exception: Exception calling "Drop" with "0" argument(s): "Drop failed for
Operator 'The DBA Team'. " ---> System.Management.Automation.MethodInvocationException:
Exception calling "Drop" with "0" argument(s): "Drop failed for Operator 'The DBA Team'.
" ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Drop failed for
Operator 'The DBA Team'.  --->
Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred
while executing a Transact-SQL statement or batch. --->
System.Data.SqlClient.SqlException: 'The DBA Team' is the fail-safe operator. You must
make another operator the fail-safe operator before 'The DBA Team' can be dropped.

**Comment by potatoqualitee** [comment]
fixed - the script actually checks for failsafe but was using the wrong variable. @FriedrichWeinmann found it 💯
