### ISSUE TITLE
Copy-DbaSqlPolicyManagement - Does not validate job schedule exist

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1546]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [X] *bug*:

Command does not account for policies that are tied to automated schedules. If policy is set to run on a scheduled basis an associated SQL Agent job is created.

When you script out building the policy, adding the policy requires you to pass in the associated schedule ID. Unsure how we can do this via SMO or if it is possible.

To be addressed after copy object updates are done on all the Copy commands.

**Comment by potatoqualitee** [comment]
@wsmelton - you think we can get this done by bagofbobbish? I just found out that the SQL Saturdays are not this Saturday but the next, so we have a lil more time.

**Comment by wsmelton** [comment]
Question @potatoqualitee 

Most of the copy commands do not account for dependencies. Meaning if something is dependent upon an object being copied, it is skipped and noted as such (e.g. database for a SQL Agent job not on destination, that job is skipped). 

So in that pattern all this command needs to do is validate the job and schedule exist and if they don't we skip that policy. Right?

**Comment by potatoqualitee** [comment]
I think so? Just validate what is required for it to migrate - nothing more. i lost track 😂

**Comment by potatoqualitee** [comment]
Can you have this one looked at by Monday?

**Comment by potatoqualitee** [comment]
To reanswer, yes totally, just understood what you asked. That'd be perfect

**Comment by wsmelton** [comment]
Updated output that catches scheduled Policies:

![image](https://user-images.githubusercontent.com/11204251/45067523-476af480-b089-11e8-9754-546f67518518.png)

That to your liking @potatoqualitee ?

**Comment by wsmelton** [comment]
Found additional issue on the logic. When the policy is scripted out it will try to create the condition with it, so it either needs to skip doing conidiations of a policy is provided...or I just add in dropping the condition in the policy block.


Thoughts?

**Comment by potatoqualitee** [comment]
ahh yeah, that makes sense,

**Comment by potatoqualitee** [comment]
im gonna do this

**Comment by wsmelton** [comment]
Going to see if I can get this done tonight

**Comment by wsmelton** [comment]
Ok, so I can't duplicate this issue. Schedule or not the policy is still copied on latest release.
