### ISSUE TITLE
Invoke-DbaDatabaseUpgrade, multiple fixes needed

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1562]
## Is this:

- [ ] *feature* 
- [x] *bug*:

- [ ]  docstrings
- [ ]  needs to accept standard Database,ExcludeDatabase params
- [x]  "compatAbility --> compatIbility"
- [ ]  needs to skip over database that doesn't need upgrade at all
- [ ]  remove -ignorecompatibilityupdate parameter (given the cmdlet name, it NEEDS to upgrade something)
- [ ]  needs an output object

PS: just a reminder, maybe it slipped in

**Comment by potatoqualitee** [comment]
Thanks @niphlod - we'll get these fixes in before this beta release! Pretty straightforward.

**Comment by Staggerlee011** [comment]
hey, 

Because it runs a collection of procs that can be re-run and no way that i can think off to track. i kinda disagree with a few comments. or would like feed back on 

needs to skip over database that doesn't need upgrade at all
remove -ignorecompatibilityupdate parameter (given the cmdlet name, it NEEDS to upgrade something)

There are times where you upgraded a db (update the compatibility) but forgot to run the other 4 commands. So I dont agree with completely ignoring a database that has the servers compatibility.. 

As for output, is a customobject with:

Server: instance: Database: Compatbility  : Data_purity  : UpdateUsage : sp_updateStats : views 
Myserver: :         test         : 130                :  1                 : 1                      :1                         : 1 

ok?

**Comment by potatoqualitee** [comment]
> There are times where you upgraded a db (update the compatibility) but forgot to run the other 4 commands. So I dont agree with completely ignoring a database that has the servers compatibility..

Would agree

```
ComputerName     sql2016
InstanceName     sharepoint
SqlInstance     sql2016\sharepoint
Database     sharepoint_config
Compatability     130
DataPurity     Complete
UpdateUsage    Complete
UpdateStats   Complete
```

Here's some sample code to work from

````
[PSCustomObject]@{
                        ComputerName = $server.NetName
                        InstanceName = $server.ServiceName
                        SqlInstance = $server.DomainInstanceName
                        Rule = 'TF 1118 Enabled'
                        Recommended = $true
                        CurrentSetting = $false
				    }
````

**Comment by niphlod** [comment]
hum....
The name of the cmdlet must match what it does...
Why would you need to run any of the n steps if you didn't actually upgrade anything ?
and why would you need to call 
`Invoke-DbaDatabaseUpgrade .... -IgnoreCompatibilityUpdate`  ? 
It makes no sense (from a syntactical point of view) to "invoke an upgrade but leave the upgrade part out", given all the steps are needed to run ONLY after the aforementioned update.

Since those steps are untracked, you can't know beforehand if they have been executed or not, and they are preeeetty BEEFY commands.

In the scenario you proposed (when you upgraded the compatibility but forgot the 4 command), you can still call `Invoke-DbaDatabaseUpgrade ... ` and have all the needed operation ran correctly, but ............it's going to bite lots of people in the head if it takes all the databases on an instance, where maybe just 1 needs the "upgrade", but you still force everyone of the 4 steps to be ran.

At that/this point, I think it'd be a more useful pattern to have the cmdlet to be "fair": upgrade the compatibility always, unless it's already at the required level, which triggers skipping all subsequent steps.

When in need (because you may have forgot to run the additional steps), pass -Force in which runs all the steps no matter what.

**Comment by wsmelton** [comment]
Just to note what effect changing the compatibility mode can have, per documentation. Starting with 2008 or 2008 R2:

>Compatibility Levels and Stored Procedures

When a stored procedure executes, it uses the current compatibility level of the database in which it is defined. When the compatibility setting of a database is changed, all of its stored procedures are automatically recompiled accordingly.

**Comment by niphlod** [comment]
why has this been closed ? the commit which points to the fix didn't fix a single thing.

**Comment by niphlod** [comment]
except for spelling

**Comment by potatoqualitee** [comment]
Because I agreed with @Staggerlee011's statement that 

> There are times where you upgraded a db (update the compatibility) but forgot to run the other 4 commands. So I dont agree with completely ignoring a database that has the servers compatibility..

Were there any other issues that needed to be addressed?

**Comment by niphlod** [comment]
Once again, verb naming needs to matter. Invoke-DbaDatabaseUpgrade that doesn't upgrade isn't natural, at all.
Test-DbaDatabaseUpgrade maybe, but not invoke.

The bigger issue here is that right now you run over and over 4 ultrabeefy things on dbs that wouldn't need that.
If you wanna support the "statement", AT LEAST by default it should *skip* same-compat, unless -force is passed. It's going to crack a lot of instances with these defaults.

**Comment by potatoqualitee** [comment]
I understand your position with regards to naming. But _naming is hard_ ;) I have not seen any other more appropriate names. Do you have any suggestions?

The other part sounds reasonable. I'm adding some functionality to Copy-DbaDatabase and I don't think Stagger is available right now. Wold you have time to add the Force?

**Comment by niphlod** [comment]
just wanna avoid people cracking instances like I did.

**Comment by niphlod** [comment]
will do a PR in a bit

**Comment by niphlod** [comment]
@potatoqualitee : this should be it https://github.com/sqlcollaborative/dbatools/pull/1711

**Comment by potatoqualitee** [comment]
works!
