### ISSUE TITLE
Copy-SqlLogin should not require sysadmin privileges

### ISSUE THREAD

**Issue by paschott** [sqlcollaborative/dbatools#157]
Our PS/Sysadmin commented out some of the root-level checks to remove the "sysadmin" requirement.  However, this should probably be changed to something a bit more appropriate to check the actual permissions required (securityadmin?).

We were able to run the copy-sqllogin function with the source user set as a security admin.

**Comment by ConstantineK** [comment]
Looks like this is an issue with Connect-SqlServer generally requiring SA, we can definitely connect to the server with the -RegularUser switch, which wont attempt to enforce this.

There is still some mulling going on around general permissions and how much we want to manage them, I think the current behavior of the command is acknowleding that managing permissions is a PITA. 

Going forward, I think we have a few options:
1. Continue as usual until someone complains and add additional code
2. Make it easier to swap in a regular user and make them deal with the permissions of the user must be sufficient (obviously dealing with errors)
3. Code in the understanding of the required permissions to manage this feature, which will be a moving target as newer functions of SQL Server come out, but we could potentially abstract this into its own set of functions.
4. ???

I was wondering if you had any opinion on the topic @paschott?

**Comment by wsmelton** [comment]
My opinion is handle the option by just validating if the user has direct `sysadmin` privileges via role membership or explicitly granted `CONTROL SERVER`. If they do not then just post a warning like:

> [Security] The user account in use is not granted elevated privileges to [server name], some actions may fail or error.
