### ISSUE TITLE
New-DbaAgentSchedule - FrequencyType parameter showing numbers

### ISSUE THREAD

**Issue by mvillegascuellar** [sqlcollaborative/dbatools#1570]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [ x] *bug*:

When I try to create a new Agent Schedule, the parameter "FrequecyType" autocompletes numbers (1,128,16,32,4,64,8) and then the real Descriptive frequencies. I think numbers should be avoided for clarity of the command.

**Comment by potatoqualitee** [comment]
🙇 Thanks again, we'll get right on it
