### ISSUE TITLE
rename functions: replace Database by DB

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#1585]
- [x] *feature* 
- [ ] *bug*:

##
considering:
- function names can become quite long
- everybody knows DB stands for database

we should replace function names containing '...database...' by '...DB...'

Get-DbaDBMasterKey
Get-DbaDBUser
Get-DbaDBPartitionFunction
...

**Comment by potatoqualitee** [comment]
Get-DbaDbMasterKey is way better ;)

**Comment by niphlod** [comment]
if this is a rule, can a notepad ++ god like @potatoqualitee go ahead and rename all ? it's not the first massive rename we face. Basically anything in this list ("containing database but not 'ending' in 'database')

`Find-DbaCommand * | where commandname -like '*database*' | where commandname -notlike '*database'`
