### ISSUE TITLE
Get-DbaTable

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#1593]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

Try to find just by table name (no schema) and the output is blank. With schema worked.

#### Example:
1. Run Command:
```powershell
Get-DbaTable -SqlInstance DEV01 -Table MyTable
```
2. Received empty output. Even if the "MyTable" exists on one or multiple databases.

### Solution
Solved on PR: https://github.com/sqlcollaborative/dbatools/pull/1592

**Comment by potatoqualitee** [comment]
Thanks for reporting and solving everyone :D :D :D :D
