### ISSUE TITLE
Remove-DbaAgentSchedule

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1601]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

#### Example:
Running Remove-DbaAgentSchedule against a server with 1100 duplicate schedules I get the error below.

## Attached screen shots/console output

![image](https://user-images.githubusercontent.com/169602/27924207-217a76a2-6246-11e7-91f2-6936d9d23cf4.png)

**Comment by gbargsley** [comment]
More testing info.  If I just pass one schedule name it does not error but it only deletes one sysschedule and one sysjobschedule at a time.  I would think it would delete all schedules with that name if not attached to a job since I am not using -force.

**Comment by gbargsley** [comment]
Wrong button clicked.

**Comment by jpomfret** [comment]
I would agree that it should be changed to delete all schedules that match the name, but I'm unable to replicate the bug. When I pass in two names two schedules are deleted.

![image](https://user-images.githubusercontent.com/981370/28191336-a115721a-67fd-11e7-8cff-66a1f8de1790.png)

**Comment by sanderstad** [comment]
As far as I know this is fixed in PR 1613: https://github.com/sqlcollaborative/dbatools/pull/1613

**Comment by jpomfret** [comment]
Agreed! It does delete all schedules with the name passed in now.

It does remove schedules that are connected to jobs though, should that throw a warning that -force should be used to delete schedules that are in use? The wording in the output when the schedule is not in use makes me think it wouldn't delete schedules that are in use.

![image](https://user-images.githubusercontent.com/981370/28212047-adf16564-686d-11e7-87cb-4bb302527f07.png)

**Comment by potatoqualitee** [comment]
@sanderstad - please address

**Comment by potatoqualitee** [comment]
@jpomfret - would it be 👍 or 👎 if I included this command in tomorrow's release even w/o Sander addressing your Q?

**Comment by jpomfret** [comment]
As it is now it's a little destructive without warning. I feel like the other cmdlets would require -force to complete that kind of action. But maybe the fix to delete multiple schedules is more important to get it? Your call, I could try and take a look tomorrow if you wanted.

**Comment by potatoqualitee** [comment]
I like the -Force - if you can get it in, that'd be super helpful thank you!

**Comment by potatoqualitee** [comment]
fixed! You guys have been magical, thank you
