### ISSUE TITLE
Install-DbaFirstResponderKit Replace Message

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1604]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Steps to Reproduce
When running the command in the screen shot I get Confirm Folder Replace even when it was empty and I know the zip file and folder are not in the AppData\Local\Temp.

It appears to be like it is doing it twice.

It would also be nice if the output comment was the stored procedure was UPDATED or INSTALLED so you know.
## Attached screen shots/console output

![image](https://user-images.githubusercontent.com/169602/27925501-8cb14852-624a-11e7-937c-14d9355d96f2.png)

**Comment by niphlod** [comment]
are you on the latest ? I can't reproduce from development

**Comment by potatoqualitee** [comment]
another closed 💃
