### ISSUE TITLE
New-DbaDatabaseCertificate Appears to Do nothing

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1609]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

#### Example:
Run the command `New-DbaDatabaseCertificate -SqlInstance L7DR15466` and I get prompted for password.  Nothing happens. I run with -verbose and after entering password nothing happens.

## Attached screen shots/console output

![image](https://user-images.githubusercontent.com/169602/27955553-fd077f8c-62da-11e7-985d-ddfbfcfb1196.png)

**Comment by potatoqualitee** [comment]
tearin it UP! Thanks so much! 🙇

**Comment by jpomfret** [comment]
This issue is because no $Name was specified, options 
- make Name parameter required
- give Name a default value
- use Stop-Function if name isn't passed in, this doesn't seem like a great option to me

**Comment by jpomfret** [comment]
If we use a default Name we'd also need a default Subject as that can't be blank. Thoughts @potatoqualitee

**Comment by potatoqualitee** [comment]
🤔 Is name the name of the database? if so, require the name or alluserdatabases (new param) so they can make one for all of their dbs.

**Comment by jpomfret** [comment]
No Database defaults to master. Name is the name of the cert

**Comment by potatoqualitee** [comment]
ohhh mmmm name it the name of the database 👍

**Comment by potatoqualitee** [comment]
fixed by good ol' @jpomfret !
