### ISSUE TITLE
Get-DbaForceNetworkEncryption multiple suggestions

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1612]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Steps to Reproduce
-ComputerName parameter should be changed to -SQLInstance to match other commands and the help.

Example 1 of using local host does not work. and even when I put in the server name I get the message below.

There is an example with the -WhatIf parameter, but it is not defined as a parameter.
## Attached screen shots/console output

![image](https://user-images.githubusercontent.com/169602/27957160-ba3edab2-62e2-11e7-8021-5ea13db688ee.png)

**Comment by potatoqualitee** [comment]
hey @gbargsley - that is a good proposal! I also removed the example.
