### ISSUE TITLE
New-DbaDatabaseMasterKey and New-DbaDatabaseCertificate enhancement

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1616]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Steps to Reproduce

Working on testing and see a good improvement would be able to create the new master key from the backup taken using Backup-DbaDatabaseMasterKey.  This could also be done with New-DbaDatabaseCertificate to be able to create from Backup-DbaDatabaseCertificate.

**Comment by potatoqualitee** [comment]
I like that a lot, those would be Adds! Add-DbaComputerCertificate does something similar.

**Comment by potatoqualitee** [comment]
Oops wait, those are Restores D:

**Comment by potatoqualitee** [comment]
this was done last year, please let me know if they do not meet your specs
