### ISSUE TITLE
New-DbatoolsSupportPackage failure message

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1620]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Steps to Reproduce
I executed the command with the default output and a specified path and still get the error message in screen shot.  However, a file is generated and has data in it.

## Attached screen shots/console output

![image](https://user-images.githubusercontent.com/169602/27967065-4068f31a-6307-11e7-8cdc-1e1adea4d7c6.png)

**Comment by FriedrichWeinmann** [comment]
Can you zip and upload the data that was generated?

**Comment by gbargsley** [comment]
[dbatools_support_pack_2017_07_07-11_25_31.zip](https://github.com/sqlcollaborative/dbatools/files/1131693/dbatools_support_pack_2017_07_07-11_25_31.zip)

**Comment by potatoqualitee** [comment]
This is sorta my issue. I'll fix it.
