### ISSUE TITLE
Get and Set-DbaTcpPort throw errors referencing SqlWmi

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1622]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Steps to Reproduce
When I run Get-DbaTcpPort with detailed I get issue with SqlWmi.  This is on my local box, so not sure what that is about.  Then when I do Set-DbaTcpPort I get similar error about SqlWmi.

## Attached screen shots/console output

![image](https://user-images.githubusercontent.com/169602/27967759-e0ac1fda-6309-11e7-8e30-e445aee15b0a.png)

**Comment by wsmelton** [comment]
Using a local machine that is not a workgroup computer can get varying results for the WMI calls.

I tested this on domain environment and at least with default port 1433 it works as expected.

**Comment by potatoqualitee** [comment]
yeah this one will be chocked up to "SQLWMI could be improved" 👎
