### ISSUE TITLE
Read-DbaTraceFile enhancement suggestion

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1624]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Steps to Reproduce

Good function, but I could see it would be more useful if the following are added.
1. User the current default trace file by default so you do not have to go hunt the path and filename down to pass in.
2. Give the user a list of trace files in the default log directory and let them select which one to read

**Comment by wsmelton** [comment]
In regards to (2) I would be against that one. Trace files are not required to exists within the default trace file. I generally never save trace files there, when I use trace files. As well, on active instances that can be a big performance hit to try and dynamically get that list and provide via TEPP. [e.g. if command is run remotely it introduces having to use the admin share to get the list of files, not everyone could have access to that share.]

For (1) I mean it obviously warrants a `Get-DbaServerTrace` that finds what traces are configured. Even if a trace is not running the path of that trace would still be accessible. That could then be piped to this command. I do not believe we need to default anything on the path or file name, that can be provided via the Get command and then piped to this one.

**Comment by potatoqualitee** [comment]
> TEPP

Oh man, I love that idea, @wsmelton - can you support it? The query would be `select distinct path from sys.traces`

Updated this - added support for pipeline so 

`$servers | Read-DbaTraceFile` works

Also removed mandatory Path and added the default as default so it now does:

`Select path from sys.traces where is_default = 1"`

Will be submitting a PR once I get my stupid client working.
