### ISSUE TITLE
Copy-DbaDatabase NoRecovery parameter is not applying

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1626]
## Is this:

- [ ] *feature* 
- [X] *bug*:

## System Details
SQL Server 2014 for source and destination

```powershell
Copy-DbaDatabase -Source .. -Destination .. -Database MyDatabase -BackupRestore -NetworkShare '\\myserverpath' -NoRecovery
```

Database is restored with recovery.

**Comment by Stuart-Moore** [comment]
Has it actually touched the database? My understanding was that it didn't do anything if source -eq destination? Worked fine in the first example below, second one it didn't restore the db so appears to have ignored NoRecovery, but never got that far
![image](https://user-images.githubusercontent.com/5613670/27988488-e3d86300-641a-11e7-888e-f3befa2639fe.png)

**Comment by wsmelton** [comment]
This was on different servers, and the database didn't exist on the server. When the command completed the database was created on the destination and was left with recovery.

**Comment by Stuart-Moore** [comment]
Sorry, you're example looked like you were copying on the same. Thanks for the update, I'll play some more later on today.

**Comment by Stuart-Moore** [comment]
Which version of the module are you using? Got a report with 0.8.957 for norecovery in general, which I can't replicate with 0.8.961

**Comment by wsmelton** [comment]
It is from dev branch...I replicated it on a different server in a completely different environment.

**Comment by niphlod** [comment]
for what is worth, I can't replicate either

**Comment by Stuart-Moore** [comment]
I've just managed to repro on garbo. Got some free time so will look into it

**Comment by Zhunya** [comment]
If fix merged in to branch we can close issue?
