### ISSUE TITLE
New-DbaDatabaseSnapshot, date format inconsinstencies

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1636]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:
 ----

Every once in a while dates are formatted properly, other times they aren't

**Comment by potatoqualitee** [comment]
dude you were TEARRRING these up! I owe you so much of whatever you drink!
