### ISSUE TITLE
Restore-DDbadatabase module version 0.8.957

### ISSUE THREAD

**Issue by js0505** [sqlcollaborative/dbatools#1638]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x ] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```
Name                           Value                                                                                                                             
----                           -----                                                                                                                             
PSVersion                      4.0                                                                                                                               
WSManStackVersion              3.0                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                   
BuildVersion                   6.3.9600.17400                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                              
PSRemotingProtocolVersion      2.2

- Output of dbatools version: 

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```
ModuleType Version    Name
Script     0.8.957    dbatools 

- SQL Server version for source/target
2016 to 2016

#### Example:
1. Run Command:
```powershell
Restore-DbaDatabase -Path "Path" -SqlInstance SqlInstance -DatabaseName DBName -WithReplace -NoRecovery -OutputScriptOnly
```
3. Received following bug
```powershell
-Output Script does not print out -NoRecovery Option.  Take out option -OutputScriptonly and script still does not utilize the -NoRecovery Option.
```

#### Example:
1. Run Command:
```powershell
Restore-DbaDatabase -Path "Path" -SqlInstance SqlInstance -DatabaseName DBName -WithReplace -NoRecovery -OutputScriptOnly
```
2. Receive following output (if applicable)
```powershell
Script Should print out -NoRecovery
```

## Attached screen shots/console output

- Use of Start-Transcript can help collection of console output and exceptions
- Provide screen shots of the output from your console if available.

### Import - Attach dbatools logs
- Latest release of dbatools now includes a messaging and logging system. You can find this information via the `Get-DbaConfig` function. Use of the Set-DbaConfig controls the configuration of the system.
- Ensure this returns **true**: `(Get-DbaConfig -Name errorlogenabled).value`
- Locate the log path for the error logs using this command: `(Get-DbaConfig -Name dbatoollogpath).Value`
- **Attach the latest xml and log files found in the path shown.**

**Comment by Stuart-Moore** [comment]
Can't replicate in 0.8.961:
![image](https://user-images.githubusercontent.com/5613670/28021147-c30bd6ba-657e-11e7-9fd1-752a5850e55f.png)

Could you update and try again please.

**Comment by Stuart-Moore** [comment]
fixed
