### ISSUE TITLE
Copy-SqlDatabase add parameter -PreserveSecurity

### ISSUE THREAD

**Issue by pcomtois** [sqlcollaborative/dbatools#1641]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [X ] *feature* 
- [ ] *bug*:

## Enhancement feature
This feature would preserve the target database' security if the -Force flag is used, and if the target database exists.
This way, the Copy-SqlDatabase command will be usable to copy PROD data to DEV or QA easily, without having to script-save-delete-create the security of logins each time.

**Comment by wsmelton** [comment]
How does `Copy-DbaLogin` not solve your problem on this one? 

Are you referring to scripting out what permissions the user in the database has and mapping that to new logins in your lower environments? Otherwise `Copy-DbaLogin` copies the logins to your destination server and then are mapped to the databases.

**Comment by pcomtois** [comment]
Sample scenario: Copy an application's database from PROD to QA daily to have access to fresh data to analyse problems and test fixes. (80% of problems at my workplace are data-related. Long story *wink*).

I was thinking about a parameter that would preserve the Target database' security (SQL users and Windows users, plus their access) because I don't want my PROD users to have access to my QA server, and I also don't want to erase the QA team's special access on the QA server after a Copy. (QA team has no access at all to PROD, so a CopyDB to QA would remove their QA Read-Write access, for example).

I could probably script the Target security and run it after each Copy, but this example is just a small part of my DB management puzzle of 50 or so databases over 4 environments. The Security changes overtime everywhere, and scripts may not follow up fast enough or get neglected eventually. 

The suggested flag (the way I imagine it) would connect to the Target, script out the Users and their permissions, do the copy-database, then erase actual permissions and put back in place the scripted out ones. There could even be an alternative "-AppendSecurity" that would not erase permissions before (thus, in my example, just add the QA team's Read-Write permissions after the Copy).

**Comment by wsmelton** [comment]
I'm going to close this as no one else has weighed in whether this will be implemented.

I'm more of the belief to use export commands to output the current security in those target databases (in QA) before copying the database over. Once it is copied then you can reapply your logins and users.

Adding that level of function to the the database command is out of scope for me.
