### ISSUE TITLE
Measure-DbaBackupThroughput is inaccurate

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1642]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details

It's hard for me to fix this one because

* I'm bad at math
* All of the backups in my lab are so fast, I assumed the results were correct

Trying this in a prod environment showed that it just..doesn't work. Can someone who knows math and has fat backups please fix? 

![image](https://user-images.githubusercontent.com/8278033/28059656-2297baf8-6625-11e7-9a2b-4d2bef327066.png)

**Comment by niphlod** [comment]
checking....

**Comment by potatoqualitee** [comment]
😻

**Comment by niphlod** [comment]
yup. TotalsizeMB is not a property anymore of get-dbadatabasehistory. This cmdlet is in need of some love because get-dbabackuphistory slightly changed

**Comment by potatoqualitee** [comment]
ohhh so it did used to work! man, we need tests. Once it's fixed, I'll add a lil test to appveyor to ensure that stays right.
