### ISSUE TITLE
Please rename Was-Bound to Test-Bound

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1646]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details

I believe Was-Bound may be the only culprit throwing noun-verb warnings when our devs import .psm1. Test-Bound seems more appropriate, too.

**Comment by FriedrichWeinmann** [comment]
Implemented in https://github.com/sqlcollaborative/dbatools/pull/1702
