### ISSUE TITLE
Get-DbaDatabase processes all database even one specified in -Database parameter

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#1655]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:
![default](https://user-images.githubusercontent.com/14327077/28106839-232d1b88-66ee-11e7-8448-d83780902703.png)

- Output of dbatools version:
```
Latest available at moment
```

- SQL Server version for source/target
Version 12.0.5546.0
Edition Developer 64-bit

## Steps to Reproduce
```powershell
Get-DbaDatabase -SqlInstance srv-sql -Database db2 -RecoveryModel Simple
```

You will get all databases in instance with SIMPLE recovery model

![default](https://user-images.githubusercontent.com/14327077/28107069-eed6293c-66ee-11e7-88fc-45d434298bb9.png)

**Comment by PowerDBAKlaas** [comment]
the logic of sequential filtering is wrong in this function. It needs to be improved by
- making the filters additive
- remove the parameter sets
- replace `try catch` by checks for empty collections
- build a filter and pipe to `Where` no more than twice:
+ once to filter on all database object properties
+ optionally for the backuphistory filters by @niphlod 

bhamby is working on a fix already and Simone's isn't merged yet, so to avoid conflicts, we better wait for those two? @potatoqualitee

**Comment by potatoqualitee** [comment]
Everything has been merged - so when yall need to submit a PR, it's rady.

**Comment by potatoqualitee** [comment]
heck yeah! thanks @PowerDBAKlaas
