### ISSUE TITLE
Restore-DbaDatabase, -RestoredDatabaseNamePrefix not working

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1657]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

----
Current development
`Restore-DbaDatabase -SqlInstance aninstance -Path '\\path_to\restoretemp$' -DatabaseName dbname -MaintenanceSolutionBackup -XpDirTree -NoRecovery -WithReplace`
and
`Restore-DbaDatabase -SqlInstance aninstance -Path '\\path_to\restoretemp$' -DatabaseName dbname -MaintenanceSolutionBackup -XpDirTree -NoRecovery -WithReplace -RestoredDatabaseNamePrefix 'prettyprefix'`

end up with the same result, `dbname` being restored, while I _think_ it should become `prettyprefixdbname`
Mind that I'm passing `-withreplace` because the pre-check on existing db on the destination is not done on the prefixed name but on the databasename.

**Comment by Stuart-Moore** [comment]
That's by design

DatabaseName beats everything.

RestoredDatabaseNamePrefix is intended for when you're restoring a bunch of dbs and there's no way of specifying individual names for them all, you just prefix the name pulled from the headers. L575-578

Could shove in a warning message to let people know what's about to happen if both are specified?

**Comment by niphlod** [comment]
Ok, I'll retire the "bug" spec and ask for a feature then :P 
From the params description is in-spec of what you're saying but DatabaseName it's also used to filter through all the backup files in the dir. 
Being able to specify a fixed target name when you need to do 1:1 restores could be beneficial because pre-filtering the file set outside this cmdlet requires basically reimplementing a nice amount of the same code (or is there something that can be used instead already?)

**Comment by Stuart-Moore** [comment]
Yes, currently if you specify a DatabaseName we filter all the backups passed in down to that single database.

If you don't then we will try to restore every database passed in. That's what the prefix is there for. So if you wanted to clone all the user dbs on an instance then you could do:
Get-DbaBackupHistory -SqlInstance MyServer  | Restore-DbaDatabase -SqlInstance MyServer -DestinationFilePrefix Clone -RestoredDatababaseNamePrefix Clone
to avoid anything that already exists.

There's a couple of solutions that spring to mind for multiple dbs:

1. Change databaseName to an array of strings, and modify the filtering. Then that could be used with the -RestoredDatababaseNamePrefix 

2. Allow a complex Old to New name mapping. Would end up being something like the FileMapping parameter where it would want a hashtable to work

**Comment by niphlod** [comment]
the more I think of it the more I like best a get-me-whatever that scans files, that I can accumulate/edit before passing it down to restore-dbadatabase .... else the params on restore-dbadatabase will pile up with each and everyone's need.

**Comment by Stuart-Moore** [comment]
I can think of way to handle that with some code reuse. Get-DbaBackupFile
as a function name? Coukd then use the trustDbBackupHistory functionality
to save double scanning?

**Comment by niphlod** [comment]
yup, something like that. Also, being able to have something that pre-digests something restore-dbadatabase can handle will allow high-level functionality, as caching the scan. Maybe at this point open a feature req issue and close this, so you can get it tracked.

**Comment by Stuart-Moore** [comment]
Take 1 lashed up here - https://github.com/sqlcollaborative/dbatools/tree/Get-DbaBackupInformation

It needs some TLC before a PR, but want to make sure I'm on the right track before going to far, usage examples:

Get-DbaBackupInformation -SqlInstance localhost\sqlexpress2016 -Path C:\dbatools\ -DatabaseName blogtest, restoretime -Recurse | Restore-DbaDatabase -SqlInstance localhost\sqlexpr
ess2016 -DestinationFilePrefix BIT -DestinationFileSuffix BT -RestoredDatababaseNamePrefix BIT -TrustDbBackupHistory 

Will scan everything, filter down to those listed dbs and then push through restore. Uses TrustDB to avoid a second scan of files.

Get-DbaBackupInformation -SqlInstance localhost\sqlexpress2016 -Path C:\dbatools\ -DatabaseName blogtest, restoretime -XpDirTree | Restore-DbaDatabase -SqlInstance localhost\sqlexpr
ess2016 -DestinationFilePrefix BIT -DestinationFileSuffix BT -RestoredDatababaseNamePrefix BIT -TrustDbBackupHistory 

Same thing, but uses XpDirTree

-SourceInstance works in the same manner

It outputs Sqlcollaborative.Dbatools.Database.BackupHistory objects, so you could shove a Where-Object  between it and the restore to really go to town on the filtering

Or it could be saved somewhere and then pushed in at a later point in time.

That the sort of thing you were thinking of?

**Comment by potatoqualitee** [comment]
hey @niphlod - let me know where we are at. In general, is the command ready / have we concluded this an enhancement or bug?

**Comment by Stuart-Moore** [comment]
It'll be an enhancement. Basically it's allowing another way to build up
backuphistory and pass it into the restore stuff.

The function I pushed up is working, but doesn't meet style guidelines and
could do with some more error catching, But does the basics of what it's
supposed to.

Main thing I want to add is a way of persisting the information (so someone
can scan a load of files overnight and then restore from that during the
day to save scanning them repeatedly).

So just wanted a 'Yeah, this is in scope' type reply before putting more
time into it,

**Comment by potatoqualitee** [comment]
Sweet, k thanks! I'll move this out of bagofbobbish.

**Comment by niphlod** [comment]
@Stuart-Moore : sorry for checking back with a not-so-sweet delay, but YESS, I sooooo like it! 

(incidentally, "opening" this up also enables scanning on one instance and restoring into another, changing paths that do not need to be uniquely accessible (i.e. when you are shipping manually backups between shares and you do not leverage something like DFS or azure shares))

**Comment by niphlod** [comment]
@Stuart-Moore : do you need any help in bringing this to life ?

**Comment by Stuart-Moore** [comment]
funnily enough I was playing with it the other day. Let me dig some notes
out and see where I got to.

Now we have a formal type it's a bit easier to make everything tie together

**Comment by niphlod** [comment]
haha, no problem man, just happy to lend an hand if you need it (also, factorizing in a single place the "logic" for the restore checks could prove beneficial)

**Comment by Stuart-Moore** [comment]
Yes. Was thinking while cleaning the kitchen that doing this right would
remove a lot of stuff from the main function. Everything eventually coming
in to get-filtered as a dbatools history object.

And I’ve been playing with redoing the filtering as a reverse tree walk.
Makes it easier to cope with recovery forks if we need to, and makes one of
the anomalies less awkward as well.

Times the issue. But hopefully this migration project should be dead one
way or another in a fortnight

**Comment by Stuart-Moore** [comment]
Get-DbaBackupInformation is back in as a new PR.

Once it's in I'll start looking at using it as new input parser for Restore-DbaDatabase.

**Comment by Stuart-Moore** [comment]
OK, all of this is now 'in'

Just need to look at replacing the Get-DbaBackupHistory filtering with the new stuff, but will shove that in as a new issue
