### ISSUE TITLE
Restore-DbaDatabase, BackupSizeMB and CompressedBackupSizeMB are $null

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1658]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

-----
Current dev. The objects returned from Restore-DbaDatabase (which, in turn, I think uses Restore-DBFromFilteredArray) miss the properties BackupSizeMB and CompressedBackupSizeMB.
Doing a select * on them, they also miss BackupSize and CompressedBackupSize, which _should_ become the new default property returned with the pretty [dbasize] type

**Comment by ConstantineK** [comment]
Thanks @jpomfret for catching this one!
