### ISSUE TITLE
Functions ask for credential

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#1659]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

![default](https://user-images.githubusercontent.com/14327077/28110285-909f7b6e-66fa-11e7-82c3-985b3e16cf7d.png)

- Output of dbatools version:

![default](https://user-images.githubusercontent.com/14327077/28110310-a453c110-66fa-11e7-93ef-47d1fd24a7ff.png)

- SQL Server version for source/target
SQL Server 2014

#### Example:
1. Run any command Restore-DbaDatabase, Invoke-DbaDatabaseUpgrade, Invoke-DbaDatabaseShrink
2. Get credential request

![applicationframehost_2017-07-12_12-09-28](https://user-images.githubusercontent.com/14327077/28110459-30095166-66fb-11e7-8381-f954d838f698.png)

**Comment by potatoqualitee** [comment]
Hey @Stuart-Moore - I can repro this on the sql2014 server. You should have access if you'd like to use it to test. Thank you @Zhunya for the report!

**Comment by Zhunya** [comment]
Its not specifically related to Restore-DbaDatabase, I think its related to Connect-DbaSqlServer.

**Comment by Zhunya** [comment]
This only related to Powershell 4, on same server with WMF 5.1 installed, scrip ran w/o asking for credential.

**Comment by Zhunya** [comment]
Today from latest dev branch, VS Code runs as different user, and asking for credentials $(

![default](https://user-images.githubusercontent.com/14327077/28156636-3daf2b30-67bc-11e7-9efb-fecff39b5237.png)

**Comment by potatoqualitee** [comment]
interesting that it's all 3 - just n oticed that, i'll do my part

**Comment by potatoqualitee** [comment]
It's Invoke-DbaSqlcmd! Which needs to be renamed and all that jazz anyway. I'll fix but @FriedrichWeinmann  - we need to address the sqlcmd2 thing.

**Comment by potatoqualitee** [comment]
fixing ...slowly...

**Comment by potatoqualitee** [comment]
fixed across the board. @Stuart-Moore - LOVED those tests. They help guide me until i fixed it properly.
