### ISSUE TITLE
Remove-SqlOrphanUser doesn't handle non-existent schemas properly

### ISSUE THREAD

**Issue by tonyfairbanks** [sqlcollaborative/dbatools#1670]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version: Server 2016
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Output of dbatools version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      957    -1
0      8      944    -1
0      8      61     -1
0      8      5      56
0      8      5      53
```
Also tested with the bagofbobbish release.

- SQL Server version for source/target: SQL 2016

## Steps to Reproduce

1. Have a database with a mix of orphaned users that do and do not have a corresponding schema
2. Run Command:
```powershell
Remove-SqlOrphanUser -SqlServer SQL2016 -Databases Database_Name
```
3. Received following error
```powershell
Remove-SqlOrphanUser : Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database
'Database_Name'. "
At line:1 char:1
+ Remove-SqlOrphanUser -SqlServer SQL2016 -Databases Database_Name -V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Remove-SqlOrphanUser
```

## Action Results
The remove orphan command stops without removing all orphaned users. 

## Expected Results
All orphaned users are removed

## Attached screen shots/console output
[remove_failure_log.txt](https://github.com/sqlcollaborative/dbatools/files/1142854/remove_failure_log.txt)

## Bug analysis/fix
There is a bug in the code where it does not clear the $DropSchema variable when looping over each user. This results in it trying drop the schema for the previous user that had an associated schema, instead of skipping that step. This results in an error and the script stops. This can be seen in the attached debug output near the end of the log:
```
DEBUG:
DROP SCHEMA [Username_w_schema_c]
DROP USER [Username_without_schema]
```

The bug can be fixed by clearing the $DropSchema variable at the beginning of the  ```foreach ($User in $Users)``` loop in Remove-SqlOrphanUser.ps1

**Comment by ClaudioESSilva** [comment]
This is fixed.
https://github.com/sqlcollaborative/dbatools/blob/master/functions/Remove-DbaOrphanUser.ps1#L214
