### ISSUE TITLE
msbuild stopped being shipped with .NET Framework after 4.0

### ISSUE THREAD

**Issue by zippy1981** [sqlcollaborative/dbatools#1672]
## Is this:
- [ ] *feature* 
- [X] *bug*:

With .NET 4.5 msbuild was moved into Visual Studio [ref](https://stackoverflow.com/questions/12944502/build-asp-net-4-5-without-visual-studio-on-build-server). Pragmatically speaking for us, even though we are targeting .NET 4.5.2 (correct me if I'm wrong @FriedrichWeinmann), we are running msbuild from `C:\WINDOWS\Microsoft.Net\Framework64\v4.0.30319\msbuild.exe` This limits a lot of language features that are possible in Visual Studio like `$"Strings with {Variables}"` instead of `String.Format("strings with {0}", Variables)`. We have these options:

1. Live with .NET framework 4.0. This works untill we have a reason to need new features. Until then We should edit the csproj so even modern versions of Visual Studio will complain if we use new language features
1. Require contributors to install MSBuild Tools or visual studio. Basically, everyone who contributes has to have a version of MSBuild that can target the minimum framwork we expect with PowerShell 3.0.
1. The above option except we also save dbatools.dll in the development branch so we only have to build if we change things.

**Comment by FriedrichWeinmann** [comment]
1) Is totally fine with me
2) Is a no-go
3) I'd like to avoid, as that ends up with us back on the conflict list
If a 4.5+ feature ever becomes important, we may have o live with 3), but I'd like to avoid that. I'll update the csproj on the next PR

**Comment by FriedrichWeinmann** [comment]
Can't reduce the target framework level on the csproj after all - the powershell binary is a reference and requires 4.5.2

**Comment by potatoqualitee** [comment]
did your commit fix this @FriedrichWeinmann ?

**Comment by niphlod** [comment]
I'd say "fa sho it did".
