### ISSUE TITLE
Restore-DbaDatabase new parameter -RestoredDBSuffix

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#1674]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Exlanation

We already have

- DestinationFilePrefix
- DestinationFileSuffix
- RestoredDatababaseNamePrefix

But still no **RestoredDatabaseNameSuffix** (RestoredDBNameSuffix)!

**Comment by niphlod** [comment]
those are piling up fast, and some are exclusive. can't we design something around an easy to use template system ?

**Comment by Zhunya** [comment]
I love template, i'm frozed mine for Backup-DbaDatabase.

**Comment by Stuart-Moore** [comment]
Yes, we could. Probably not in time for v1 though

**Comment by Stuart-Moore** [comment]
Suffix  is in and working fine so closing.

There's plenty of other options for people to use with the mappings and such. Plus with the new pipe version they can always jump in and do it themselves.
