### ISSUE TITLE
Get-DbaDatabase -NoFullBackupSince broken, 'cause Get-DbaBackupHistory -Since and -LastFull together

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#1675]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

The Get-DbaBackupHistory has a `$Since` parameter that belongs to ParameterSetName "NoLast"
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaBackupHistory.ps1#L162

But also has a parameter `-LastFull` that belongs to ParameterSetName "Last" 
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaBackupHistory.ps1#L170

This means I can't run with both together. 

This also breaks the Get-DbaDatabase when using `-NoFullBackupSince`
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaDatabase.ps1#L209

![image](https://user-images.githubusercontent.com/19521315/28173730-32a981ba-67e7-11e7-9a7d-f4dce5449351.png)

I think we should be able to run `-Last` `-LastFull` or `-LastDiff` with `-Since`.
Thoughts?

**Comment by niphlod** [comment]
Picture a daily backup at 21:00:
- what's the last backup ? yesterday, at 21:00
- what's the last backup since 5 days ago? yesterday, at 21:00
- what's the last backup since x days ago? yesterday, at 21:00

Why would you wanna ask for Since to be able to work with Last ?

**Comment by Zhunya** [comment]
Have bugs too:
```powershell
Get-DbaBackupHistory -SqlInstance xxxxxxxx -Database xxxxxxA -Last
```

![default](https://user-images.githubusercontent.com/14327077/28174454-437eb3a8-67fa-11e7-8adb-a410bae27234.png)

Differential listed 2 times when, but

```powershell
Get-DbaBackupHistory -SqlInstance xxxxxxxx -Database xxxxxxA -Since '2017-07-12 22:00:00.000'
```
had it once
![default](https://user-images.githubusercontent.com/14327077/28174621-a5c4c002-67fa-11e7-9179-69208664ea44.png)

**Comment by ClaudioESSilva** [comment]
@niphlod just to cut down the number of records to search.
On big backuphistory tables hopefully we can save some time.

**Comment by niphlod** [comment]
@ClaudioESSilva : not going to cut that much. I live with ~200 db backed up every 15 min and retrieval doesn't take much time.

**Comment by niphlod** [comment]
Though I see the issue for get-dbadatabase -nofullsince .... but that's another story.

**Comment by Zhunya** [comment]
it is will be cool to get LastFull and LastDIFF at once!

**Comment by niphlod** [comment]
@Zhunya : is it current dev ? Double diff is something that got fixed in the last couple of days.

**Comment by wsmelton** [comment]
Yeah, `Since` is the proper term to say give me the last backups since this date.

It is something that works by itself as a filter and there would be no need to add the `Last` or `LastX` with it to me.

**Comment by Zhunya** [comment]
development branch midday today, will recheck

**Comment by ClaudioESSilva** [comment]
@niphlod @wsmelton sold! 😄

**Comment by wsmelton** [comment]
Also, why are we trying to get backup information by calling `Get-DbaDatabase`. If that depends on the backup history property in SMO, that is not very accurate method at all.

**Comment by Zhunya** [comment]
@wsmelton it queries msdb

**Comment by niphlod** [comment]
@wsmelton : get-dbadatabase uses get-dbabackuphistory for those. so this is a valid issue for that, but it's on get-dbadatabase shoulders. I'll fix it ASAP.

**Comment by Zhunya** [comment]
@niphlod doublechecked my pull version 7/13/2017 @ 4:29AM

**Comment by niphlod** [comment]
can you do a screen for 
get-dbabackuphistory ..... -lastdiff 
for me ?
-Last just calls -lastdiff internally.

**Comment by Zhunya** [comment]
here we go:
![default](https://user-images.githubusercontent.com/14327077/28175356-ae740436-67fc-11e7-9016-a82588047aab.png)

**Comment by niphlod** [comment]
oki, thanks! checking...

**Comment by niphlod** [comment]
BTW: we have also get-dbalastbackup that cycles over smo properties .... those params to get-dbadatabase would be a better fit for that instead.

**Comment by niphlod** [comment]
@ClaudioESSilva : would you take a shot at https://github.com/sqlcollaborative/dbatools/pull/1676 ?
