### ISSUE TITLE
Get-DbaLastBackup, _should_ be rewritten to use Get-DbaBackupHistory 

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1677]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

----

Given get-dbalastbackup uses SMO and that's deemed unreliable/people may want finer tuning I'd go for rewriting it to use Get-DbaBackupHistory  instead.

**Comment by potatoqualitee** [comment]
reverting due to compatibility issues - dang tests pass i dont know whats up with appveyor

**Comment by niphlod** [comment]
huh ????????????

**Comment by niphlod** [comment]
closed via #3162
