### ISSUE TITLE
Get-DbaBackupHistory, wrong data returned

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1678]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

------

To discuss with @Stuart-Moore principally but @ck, @potatoqualitee , @wsmelton , @PowerDBAKlaas , etc can chime in.

Currently get-dbabackuphistory RANK()s over backupset.backup_start_date DESC. To fetch the latest, rank is assumed to be 1.
First, RANK() over two identical values gives you the same RANK(). 
I'd go here with ROW_NUMBER().
Second, the "last backup" is the one that ENDED last, not the one it STARTED last (think concurrent, one to a slow destination, one to a fast one)

I'd go changing the query towards ROW_NUMBER() over backupset.backup_finish_date.

Does anyone agree or am I just too tired to make sense ?

**Comment by Stuart-Moore** [comment]
Makes sense to me

**Comment by ConstantineK** [comment]
Sounds intelligent, row_number() seems more appropriate in this case given the need and backups need to finish to be usable 🍡

**Comment by ConstantineK** [comment]
Just some clarifications based on further conversations and questions that came up in a discussion with @ClaudioESSilva :
* the msdb object backupset we use does not store failed backups https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/backupset-transact-sql 
* I haven't worked with them (at least on purpose) before, but concurrent database backups are possible and have even more powers that were added in 2005 with regard to fulls and logs running at the same time.

**Comment by ClaudioESSilva** [comment]
@niphlod @Stuart-Moore Correct me if I'm wrong.

The most recent backup is the one that have started later, right?
1. Start backup
2. While backup running throw a data change
3. start another backup
4. for some reason this second backup ends first

as your suggestion will return the backup started on step 1 because was the last to finish. But the real most recent is the one started on step 3 even if started later.

Am I missing something? 😅

**Comment by Stuart-Moore** [comment]
The last backup is the one with the highest lastlsn value.

Dates, pah! ;)

**Comment by ClaudioESSilva** [comment]
Totally agree!

**Comment by niphlod** [comment]
ok, then we all agree on row_number() vs rank(). 
Then, @ClaudioESSilva , (not considering lastlsn which I don't know if it's always naturally ordered), a backup technically is consistent with the state of it when mssql finished reading all the pages: it's more towards the end time than the start time. 

@Stuart-Moore : you played more than me with those numbers: can we safely go to last_lsn for ordering ?

To everybody here: backup_finish_date is the only one of the "choices" that has an index on msdb.

**Comment by PowerDBAKlaas** [comment]
Why not lastlsn?
And if not, in case there are 2 rows with the same finish date, wouldn't it be better to return both ( so RANK()), and then look at the lastlsn?
If we order by finishdate, the rownumber 1 will not be deterministic, will it?

**Comment by niphlod** [comment]
My main target is deterministic too. backup_set_id would be my first choice given it's a PK, hence the fastest "split brain scenario ruler" . In addition to what , is what we're discussing about.

see the differences in your own history
```
select * from (
select row_number() over (partition by database_name order by last_lsn) lsn_order,
row_number() over (partition by database_name order by backup_finish_date) finish_order,
row_number() over (partition by database_name order by backup_start_date) start_order,
last_lsn,
backup_finish_date,
backup_start_date,
database_name
from backupset
) a
where lsn_order != finish_order
or lsn_order != start_order
or start_order != finish_order```

**Comment by PowerDBAKlaas** [comment]
my history is pretty dull 😆 
finish_order and start_order are 100% the same, I have no backup_finish_date duplicates
but I do have a lot of backups with the same last_lsn 😞

**Comment by niphlod** [comment]
BTW2: the index hint has "solid" shoulders: that's what SMO uses.

```
select database_name, [type], max(backup_finish_date) from msdb..backupset
where [type] = 'D' or [type] = 'L' or [type]='I' group by database_name, [type]
```

**Comment by Stuart-Moore** [comment]
Same finish date/lastlsn have to be coped with, it's the how striped
backupsets will report.

I generally group by BackupSetID (msdb) or BackupSetGUID (headers) as that
gets any backups that are part of a striped set. Then order on LastLSN,

**Comment by niphlod** [comment]
should pose no issues because the cmdlet has a beefy section on processing striped backups as a side-piece. I'm still voting for row_number over backup_finish_date instead of the current solution of rank over backup_start_date

**Comment by tonyfountain** [comment]
Why not just use backup_set_id to order the results?  I use this in all my queries and never have an issue.

**Comment by niphlod** [comment]
has been implemented long ago. closing.
