### ISSUE TITLE
Moving to Connect-SqlInstance -MinimumVersion

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1680]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Details

Previously, for commands that run on specific instances (like 2005+), we would perform manual checks

````
if ($sourceserver.versionMajor -lt 9 -or $destserver.versionMajor -lt 9)  {
     Write-Output "Credentials are only supported in SQL Server 2005 and above. Skipping."
}
````

or

````
if ($server.versionMajor -lt 10) {
     Stop-Function -Message "This function does not support versions lower than SQL Server 2008 (v10). Skipping server $instance." -Continue
}	
````

This can now be managed using the internal command, which exists in nearly every command, 

`$server = Connect-SqlInstance -SqlInstance $instance -SqlCredential $SqlCredential`

This can now be changed to

`$server = Connect-SqlInstance -SqlInstance $instance -SqlCredential $SqlCredential -MinimumVersion 10`

So all commands that check the "old way" must

- [ ] Remove the old code check
- [ ] Add the appropriate parameter to Connect-SqlInstance

I search the files using PowerShell or Notepad++. The easiest way to find them is by searching for .VersionMajor (though not all version checks must be replaced - only the ones that stop the entire command)

**Comment by wsmelton** [comment]
Only special occasions where we have to do multiple Version checks (e.g. building dynamic SQL) should that cause adjusting `Connect-SqlInstance` as well?

An example that exist in `Backup-DbaDatabase`:

```powershell
if ($server.Edition -like 'Express*' -or ($server.VersionMajor -eq 10 -and $server.VersionMinor -eq 0 -and $server.Edition -notlike '*enterprise*') -or $server.VersionMajor -lt 10) {
					Write-Message -Level Warning -Message "Compression is not supported with this version/edition of Sql Server"
				}
```

Maybe we can also add a parameter to Connect for `Edition` as well?

**Comment by potatoqualitee** [comment]
done, afaik
