### ISSUE TITLE
Copy-SqlDatabase issue with Restore-DbaFromFilteredArray

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1681]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details
This may have already been solved, but a user reported the following

![image](https://user-images.githubusercontent.com/8278033/28185066-38ac667a-6816-11e7-9072-6c6ebebdc02c.png)

**Comment by Stuart-Moore** [comment]
I've just merged a PR into dev that should remove the error.
