### ISSUE TITLE
Connect-SqlInstance MinimumVersion issuewith validation

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1686]
## Is this:
- [ ] *feature* 
- [X] *bug*:

Use of the `-MinimumVersion` with instances that are offline is outputting incorrect warning:
![image](https://user-images.githubusercontent.com/11204251/28235987-ece42712-68df-11e7-9050-0a8557978bd1.png)

Both instances are stopped and not using the `-MinimumVersion` shows the instances are not accessible:
![image](https://user-images.githubusercontent.com/11204251/28235997-2783b716-68e0-11e7-9326-d3682f60fbf5.png)

Based on the logic it should try to connect to the instance before it throws a message about the version.

**Comment by potatoqualitee** [comment]
@wsmelton good catch. ive submitted a pr but am waiting for tests. please try with this code

https://github.com/sqlcollaborative/dbatools/pull/1763/files
