### ISSUE TITLE
Convert Test-RunAsAdmin to Test-ElevationRequirement

### ISSUE THREAD

**Issue by FriedrichWeinmann** [sqlcollaborative/dbatools#1692]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [X] *feature* 
- [X] *bug*:

## System Details

The current implementation of Test-RunAsAdmin has some serious issues:
 - Illegal use of `break`
 - Design issues for a command with the `Test-` Verb

Example uses of the intended command:
```PowerShell
if (Test-ElevationRequirement -ComputerName $computer -Not) { return }
if (Test-ElevationRequirement -ComputerName $computer -Not -Continue ) { continue }
if (Test-ElevationRequirement -ComputerName $computer -Not -Continue -ContinueLabel main ) { continue main }
if (Test-ElevationRequirement -ComputerName $computer -NoStop ) {
    # Whatever
}
```

Additional required ToDos:
 - Update all instances where it is currently used, as it changes the behavior of the function
 - Update Stop-Function so it can interrupt commands on a higher level instead of the one where it was called

**Comment by niphlod** [comment]
@FriedrichWeinmann : I do not think this is still valid, can you please close this if it has already been solved ?

**Comment by niphlod** [comment]
closing......
