### ISSUE TITLE
Missing 2008 startup scripts in appveyor tests

### ISSUE THREAD

**Issue by ConstantineK** [sqlcollaborative/dbatools#1703]
## Is this:

- [ ] *feature* 
- [X] *bug*:

#### Example:
1. Examine tests
https://github.com/sqlcollaborative/dbatools/blob/development/tests/appveyor.sqlserver.ps1#L68  
2. Examine folders 
https://github.com/sqlcollaborative/appveyor-lab
3. Note that the appveyor tests indicate a folder named sql2008-startup, and that there is no such folder in the second link. 

## Expected Results
Some folder containing the startup scripts, potentially containing the same general approach as the 2016 startup scripts.

**Comment by potatoqualitee** [comment]
hey @ConstantineK  - it exists, there's just nothing in it yet - that may be why it doesn't show up on github

![image](https://user-images.githubusercontent.com/8278033/28325282-a9bb1f4e-6bdd-11e7-828e-25c0b7dceb7d.png)
