### ISSUE TITLE
New command: Get-DbaFile (up for name change)

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1706]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Details

This one is awesome and up for grabs - use `Show-DbaServerFileSystem` for folders maybe? 

Here's a mockup - except it would need the additional columns ComputerName, etc

![image](https://user-images.githubusercontent.com/8278033/28261458-af33da46-6adf-11e7-8071-ffa71e55d90d.png)

**Comment by potatoqualitee** [comment]
Yeahhh, I tried finding the SMO equivalent but couldn't find it.

**Comment by niphlod** [comment]
There are a few implementations around in dbatools that could benefit from a factorized common method. borrow a few params from its "spawner" (get-childitem) and it's good to go.

**Comment by potatoqualitee** [comment]
yeah, stuart's commands have some code in them -- that Get-XpDirTreeRestoreFile prolly

**Comment by potatoqualitee** [comment]
SO GOOD!
