### ISSUE TITLE
Stop-Function outputs Messages twice

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1708]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details
This occurs when no error is passed

![image](https://user-images.githubusercontent.com/8278033/28266384-d883f79a-6af4-11e7-8bb1-59883df75c25.png)

**Comment by wsmelton** [comment]
Can you include the calling of the `Stop-Function` that generates that line?

**Comment by jpomfret** [comment]
Believe this is the call that's generating the message twice 
`Stop-Function -Message "$db is already attached to $server" -Target $db -Continue`
