### ISSUE TITLE
Get-DbaBackupHistory -SqlInstance sql2016 -Last is weird

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1715]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details
This doesn't happen every time - and Test-DbaLastBackup works well with no exceptions, even though it calls this same command (but maybe limits it to a database)

![image](https://user-images.githubusercontent.com/8278033/28292510-926854c6-6b4f-11e7-8800-b5dacd65ec0d.png)

Also - unsure if htis is related. Doesn't always happen.

![image](https://user-images.githubusercontent.com/8278033/28292609-0ce06be4-6b50-11e7-90ba-7ca5ad003f46.png)

The below resulted from

````
		$null = $db | Backup-DbaDatabase -Type Full
		$null = $db | Backup-DbaDatabase -Type Differential
		$null = $db | Backup-DbaDatabase -Type Log
		$null = $db | Backup-DbaDatabase -Type Log
````

![image](https://user-images.githubusercontent.com/8278033/28293378-3387b7bc-6b54-11e7-9f61-e6a06f5140ad.png)

**Comment by potatoqualitee** [comment]
I do continue to get errors but so randomly - even with a new session

![image](https://user-images.githubusercontent.com/8278033/28293243-86a937d2-6b53-11e7-8955-a1131f49dc9b.png)

**Comment by potatoqualitee** [comment]
It seems like there are too many backup files that are in the final list, but they don't all restore

![image](https://user-images.githubusercontent.com/8278033/28294204-c841d794-6b58-11e7-980b-26fccd934c32.png)

**Comment by Stuart-Moore** [comment]
Looks like an error with multiple backups in a file. which was working
I'll take a look

**Comment by potatoqualitee** [comment]
This was submitted yesterday - prior to your merged PR for today

**Comment by Stuart-Moore** [comment]
It's still broken for those :( 

It's in Restore-DbaDatabase:
![image](https://user-images.githubusercontent.com/5613670/28317043-4107bef0-6bbd-11e7-9474-1977b3708c85.png)

That was working. I'll get it fixed and put a test in

**Comment by potatoqualitee** [comment]
Oh man, you're awesome! Thank you. I'll wait for that for the release - I expect it'll be late tonight.

**Comment by Stuart-Moore** [comment]
This ones all done.

I'll close it till the next one comes along....

**Comment by potatoqualitee** [comment]
thanks so much 🌈
