### ISSUE TITLE
[System.Management.Automation.CredentialAttribute()] causes prompts in win7/psv3

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1721]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details

I have tested and found this to be a severe issue impacting win7/ps3 - Win2012R2 works as expected. I recall we added that for a reason - who can remind me? @niphlod ? @wsmelton ?

I'd like to stick with just `[PSCredential]` instead of `[PSCredential][System.Management.Automation.CredentialAttribute()]`

For anyone who'd liek to see it in action, the `win7` box is available. I ran Get-DbaDatabase.

**Comment by potatoqualitee** [comment]
Excellent - shawn found a solution 

`[PSCredential][System.Management.Automation.Credential()]$Credential = [System.Management.Automation.PSCredential]::Empty,`

**Comment by PowerDBAKlaas** [comment]
It's been a while, but I think I tried that one before and I got prompts right then. 🤔

**Comment by potatoqualitee** [comment]
Gonna just remove `[System.Management.Automation.Credential()]` - adding that empty broke all kinds of commands.

**Comment by potatoqualitee** [comment]
We can revisit at a later time - right now this is resolved-ish.
