### ISSUE TITLE
Spelling error in Find-DbaDatabase and incorrect instance name in connect warning

### ISSUE THREAD

**Issue by NeoPangea** [sqlcollaborative/dbatools#1724]
In the find-dbadatabase function there is a spelling error on line  131 where ExtendedPropteries should be ExtendedProperties.

Also Line 81 returns a warning about being unable to connect when the connection attempt returns an error. The Warning however returns the $server object which contains the name of the previous successful connection attempt. My guess is that it should use the $instance object instead.

**Comment by potatoqualitee** [comment]
Thanks so much for the report, @NeoPangea! We'll fix that by today's release.

**Comment by potatoqualitee** [comment]
fixed 💃
