### ISSUE TITLE
Enable-DbaForceNetworkEncryption does not set to Tru

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1733]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Steps to Reproduce
When function is run and no certificate exists I think it should give a proper message.
When function runs it says ForceEncryption false and nothing happens.

## Attached screen shots/console output
![image](https://user-images.githubusercontent.com/169602/28318444-7c1e4c02-6b90-11e7-8105-024613d22099.png)

**Comment by potatoqualitee** [comment]
Fixed, thanks! plz test
