### ISSUE TITLE
Test-DbaLastBackup issues

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1736]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

##  Details
So it may be improperly reporting that the files don't exist but it surely is reporting falsely that the restore was a success in the event it was skipped.

![image](https://user-images.githubusercontent.com/8278033/28326143-3b2303dc-6be0-11e7-87a5-1398829c42da.png)

**Comment by Stuart-Moore** [comment]
just pushed a fix. Didn't appear to be a test to see if the database had backups.....

**Comment by potatoqualitee** [comment]
thanks @Stuart-Moore !
