### ISSUE TITLE
InModule.Help.Exceptions.ps1 efficiency

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1752]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Details
InModule.Help.Exceptions.ps1 is by far the longest running test in our collection. Can someone take a look and make it faster?

**Comment by potatoqualitee** [comment]
Perhaps @FriedrichWeinmann or @niphlod

**Comment by niphlod** [comment]
that was always a sore point, by far it's the one that shows best "piping" limitations of powershell (just because pester leverages it a lot). We can surely do best, I'll make a note to inspect it properly.
