### ISSUE TITLE
Copy-DbaDatabase - lots of can't update owner

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1756]
![image](https://user-images.githubusercontent.com/8278033/28363869-7030cb02-6c82-11e7-9d92-44d146e62539.png)

**Comment by gbargsley** [comment]
I had that, but related it to a database that did not have an owner on source.  Do you have owner on source?

**Comment by SQLDBAWithABeard** [comment]
Unable to reproduce with login not available on destination - Will try removing source owner login

**Comment by potatoqualitee** [comment]
ah ha! maybe not? should fail back to sa if it cannot find owner @SQLDBAWithABeard please use Get-SaLoginName to find name of "sa"

thanks!

**Comment by niphlod** [comment]
I recently corrected the logic, but it was to match the backup/restore with the attach/detach. what's the method used in this example ?

**Comment by potatoqualitee** [comment]
What you mean? Oh. this was a backup/restore

**Comment by niphlod** [comment]
ok, so it's the one that I recently updated. if you run it with -Verbose it shows the target db owner that it's trying to set.

**Comment by niphlod** [comment]
the logic is from https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-DbaDatabase.ps1#L1113 and a few lines down

**Comment by SQLDBAWithABeard** [comment]
Copy-DBADatabase calls Set-DbaDatabaseOwner 
which will use sa if no targetlogin parameter but fail if target login not available on destination

Set-DbaDatabaseOwner -SqlInstance rob-xps\bolton -Database dba-admin -TargetLogin TestOwner
WARNING: [Set-DbaDatabaseOwner][12:47:49] TestOwner is not a valid login on rob-xps\bolton. Moving on.

**Comment by SQLDBAWithABeard** [comment]
so something to do with get-saloginname returning null ?

Still cant reproduce

**Comment by niphlod** [comment]
let her make a run with -Verbose and we'll see.

**Comment by SQLDBAWithABeard** [comment]
yes - Possibly also version specific

**Comment by potatoqualitee** [comment]
for me, I'll just tell it to not try to update the owner if the owner isnull, will fix myself thanks all

**Comment by niphlod** [comment]
@potatoqualitee so is this still valid ? sorry to cc you but I feel responsible :P

**Comment by niphlod** [comment]
@potatoqualitee : can you recheck and close ? I can't reproduce.

**Comment by xs2nasir** [comment]
how to change database owner to sa when the database in norecovery
