### ISSUE TITLE
Tests updated with variable names for servers - to consider

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1758]
Hey Constantine,
Just a note that I recently discovered Context is sort of isolated (I suppose I should read up formally on Pester) and _some_ variables do not persist unless $script: is used. 

I littered Copy-DbaDatabase with some forced static names, my apologies. I simply couldn't get it working and it was strange. Ultimately, after the detach/attach, I had to use 

````
$db1 = (Connect-DbaSqlServer -SqlInstance localhost).Databases['detachattach']
$db2 = (Connect-DbaSqlServer -SqlInstance localhost\sql2016).Databases['detachattach']
````

Instead of Get-DbaDatabase for consistent results ¯\_(ツ)_/¯

**Comment by ConstantineK** [comment]
No apologies needed! It sounds like I should dive into the pester docs a bit deeper and dispel some illusions I have about its control flow. 

Thanks for catching this one!
