### ISSUE TITLE
Support ability to shrink log file of database involved in Availability Group

### ISSUE THREAD

**Issue by amigosnw** [sqlcollaborative/dbatools#1769]
One thing that I've found to be a challenge is to shrink a database log file that is in an alwaysOn configuration. Could you automate that process so that I don't have to remove the database and re-enter it into the AG?

**Comment by wsmelton** [comment]
You do not have to remove the database in an AG to shrink the log file. You simply can only do this on the primary replica. However if there are inactive portions of the log file then the shrink operation will work.

If you do not see it shrink you follow the normal process just like it is a normal (non AG) database on why the log space is not being released. Which if you are having to constantly do that then there are other issues that should be fixed.

**Comment by wsmelton** [comment]
You should be able to utilize the `Invoke-DbaDatabaseShrink` and specify the `LogsOnly` to shrink the database, just make sure you point that command at the primary replica.
