### ISSUE TITLE
Copy-SqlLogin should warn or not copy SQL Logins if the destination doesn't have mixed mode enabled

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#177]
Question raised during presentation at SQL Saturday, this cmdlet should probably warn or just not copy over SQL Logins if mixed mode authentication is not enabled on the target.

**Comment by SirCaptainMitch** [comment]
I felt like a warning was better then outright not doing the thing. Having them enable mixed mode after seems less frustrating than to enable it and start the copy again.  

Although I suppose the reverse could be said as well.

**Comment by ConstantineK** [comment]
Closed in #358.
