### ISSUE TITLE
Rename-DbaDatabase, new function

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1775]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

------
In the need of something that renames a database, optionally renaming underlying files too.
PS: remember to suggest to backup master afterwards

**Comment by potatoqualitee** [comment]
awesome!

**Comment by potatoqualitee** [comment]
Dupe of #289 which contains more info
