### ISSUE TITLE
Default behavior of Stop-Function

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1779]
I find that we use -Continue more than not. Would it be possible to continue by default and instead use -ExpectReturn, which would allow us to do

````
Stop-Function -Message "Whatevo" -Target $db -ExpectReturn
return
````

**Comment by FriedrichWeinmann** [comment]
Technically possible.

I'd disagree with the idea on both a tactical and strategic level.
 - Its default behavior would be to affect the calling function in a way that one does not expect from PowerShell
 - Superficially, it does exactly what you'd want in `return` situations, even without the return! Only it uses continue to do so, breaking scripts using dbatools commands (so it'll work fine in most of our internal tests but break in the field)
 - With the current notation, its behavior is easily visible from reading. It requires insider knowledge to understand it in the version you propose to practice.

So in the final calculation, in return for a minor laziness reward it'd invite massive error in use and risk of undetected failure.
Now I really like you and generally mind my tone, but if you want that implemented, you'll have to do it yourself over some fairly graphic commentary from me ;)

**Comment by potatoqualitee** [comment]
LOL LOL! Your bugs assignments are outrageous.
