### ISSUE TITLE
Start-SqlMigration error

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#179]
Running Start-SqlMigration on local machine with SQL Server 2014 --> SQL Server 2016. I get an error around the linked server migration that references "unknown key size". The script continues like it is working, even showing messages like it is...but it basically stopped and quit as the error message shows. The process did not do any hard stop (if it should have).

[Pastebin of output log](http://pastebin.com/dPUEBSyB).

**Comment by mbourgon** [comment]
Having the same problem.

**Comment by ctrlbold** [comment]
Thanks for the report. That error does need to be cleaned up -- likely a divide by zero or something because it couldn't access your server 

Please confirm you are running as administrator if you're running the command locally. Also, confirm that you can do this 

```
Invoke-Command -ScriptBlock { Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server"  } -ComputerName whateveryourSourceServerIs
```

**Comment by niphlod** [comment]
@wsmelton : last ping for tonight. Can you do the steps outlined by @ctrlbold ?

**Comment by mbourgon** [comment]
Apologies, I personally cannot - the 2014 servers I had have been turned off.

**Comment by wsmelton** [comment]
My issue was because I was not using a remote machine, and not on a domain. The pastebin link shows the error repeats over and over again when you check for the remote registry.

```
Checking if Remote Registry is enabled
[manatarms] Connecting to remote server manatarms failed with the following error message : WinRM cannot process the
request. The following error with errorcode 0x8009030e occurred while using Negotiate authentication: A specified logon
session does not exist. It may already have been terminated.  
 Possible causes are:
  -The user name or password specified are invalid.
  -Kerberos is used when no authentication method and no user name are specified.
  -Kerberos accepts domain user names, but not local user names.
  -The Service Principal Name (SPN) for the remote computer name and port does not exist.
  -The client and remote computers are in different domains and there is no trust between the two domains.
 After checking for the above issues, try the following:
  -Check the Event Viewer for events related to authentication.
  -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or
use HTTPS transport.
 Note that computers in the TrustedHosts list might not be authenticated.
   -For more information about WinRM configuration, run the following command: winrm help config. For more information,
see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (manatarms:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : 1312,PSSessionStateBroken
```

Same issue running the command from @ctrlbold if you are on a workgroup computer (which will not have WinRm configured by default in Windows), that command is not going to work as expected. Could hold true as well for those that use a machine over a VPN that can touch their network, but the machine they use to connect is not actually on the domain (like a consultant)... but I don't have that setup to test out.

**Comment by wsmelton** [comment]
We can just close this if we are not going to support running from a workgroup computer. I don't see a reason to as it will not be a common scenario we should see.
