### ISSUE TITLE
Copy-DbaAgentSharedSchedule copy selected shared schedules

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#1796]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [X] *feature* 
- [ ] *bug*:

## Enhancement description:
Add a `-SharedSchedule` parameter to Copy-DbaAgentSharedSchedule to allow the user to copy one or more Agent shared schedules from the source server to the destination. Presently this function copies all shared schedules.

**Comment by wsmelton** [comment]
This command no longer exists. `Copy-DbaAgentSchedule -ScheduleName` should support all schedules.
