### ISSUE TITLE
Commands missing DbaInstanceParmeter type

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1797]
Following commands need to have the `ComputerName` or `SqlInstance` updated to `[DbaInstanceParameter]` as the parameter type.

- [x] Clear-DbaSqlConnectionPool.ps1
- [x] Get-DbaAgentSchedule.ps1
- [x] Get-DbaClientProtocol.ps1
- [x] Get-DbaCmConnection.ps1
- [x] Get-DbaDiskSpace.ps1
- [x] Get-DbaLocaleSetting.ps1
- [x] Get-DbaMsdtc.ps1
- [x] Get-DbaNetworkActivity.ps1
- [x] Get-DbaPageFileSetting.ps1
- [x] Get-DbaSpn.ps1
- [x] Get-DbaSqlProductKey.ps1
- [x] Invoke-DbaLogShipping.ps1
- [x] Invoke-DbaLogShippingRecovery.ps1
- [x] New-DbaAgentSchedule.ps1
- [x] New-DbaSqlConnectionStringBuilder.ps1
- [x] Remove-DbaAgentJob.ps1
- [x] Remove-DbaAgentSchedule.ps1
- [x] Set-DbaPowerPlan.ps1
- [x] Test-DbaDiskAlignment.ps1
- [x] Test-DbaDiskAllocation.ps1
- [x] Test-DbaLinkedServerConnection.ps1
- [x] Test-DbaPowerPlan.ps1

**Comment by ConstantineK** [comment]
Closing as this as aged beyond usefulness, talked to @wsmelton and he said we would revisit on 1.0-en-ing.
