### ISSUE TITLE
Copy-DbaDatabase ReuseFolderStructure fails on 0.9.7 build 

### ISSUE THREAD

**Issue by TheRockStarDBA** [sqlcollaborative/dbatools#1799]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [ x] *bug*:

## System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                                                                                                                                 
----                           -----                                                                                                                                                                                                 
PSVersion                      4.0                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                                                       
BuildVersion                   6.3.9600.17400                                                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                                                                                  
PSRemotingProtocolVersion      2.2         
```                                                                                                                                                                                          

Evaluate $PSVersionTable in PowerShell and paste the output here
```
```
Name                           Value                                                                                                                                                                                                 
----                           -----                                                                                                                                                                                                 
PSVersion                      4.0                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                                                       
BuildVersion                   6.3.9600.17400                                                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                                                                                  
PSRemotingProtocolVersion      2.2       
```                                                                                                                                                                                            

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```
```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      9      7      -1      

```
- SQL Server version for source/target

**Source** - Microsoft SQL Server 2008 (SP4) - 10.0.6000.29 (X64) 
	Sep  3 2014 04:11:34 
	Copyright (c) 1988-2008 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

**Destination** - Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64) 
	Jun 17 2016 19:14:09 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )



## Steps to Reproduce

#### Example:
1. Created database/object/files/etc
2. Run Command:
```powershell
Get-DbaFunction -SqlInstance MyServer | Get-DbaSomeOtherFunction -FilterSwitch -StelleEyedMissileMan
```
3. Received following error
```https://gist.github.com/TheRockStarDBA/765fe010cd12fc8aa47b095373aa7f27

Also

7/20/2017 5:02:51 PM

At line:582 char:38
+                     $FilteredFiles | Restore-DBFromFilteredArray -SqlInstance $S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is an empty string.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
7/20/2017 5:02:52 PM
```

**Comment by potatoqualitee** [comment]
@theRockStarDBA the issue doesn't seem to list the command that you actually ran but i believe it's

`Copy-DbaDatabase -Source sql2016a -Destination sql2016c -Force -ReuseSourceFolderStructure -BackupRestore -NetworkShare \\dc\sql -Database Test`

I tracked it down to an issue with the Restore command and ReuseSourceFolderStructure and have asked @Stuart-Moore to take a look.

**Comment by potatoqualitee** [comment]
I revisited this command on the most recent version and it seems there were issues - not with Restore but with Copy. I'm about to submit a PR

**Comment by potatoqualitee** [comment]
Sorry, should be both with restore and copy

**Comment by potatoqualitee** [comment]
try now plz
