### ISSUE TITLE
Local <> Local Server

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#180]
The local <> local server check has bad logic. Expects to always migrate remotely.

**Comment by ClaudioESSilva** [comment]
Can anyone point to the script / line where this is happening?
I'm using the following code to validate `if ($env:computername -eq $sourcenetbios)` and it has been working just fine.

**Comment by dansqldba** [comment]
@ClaudioESSilva I think this is a general comment on the module, not anything specific. A list of cmdlets where this applies would be useful though. If you find or know of any, perhaps just add them to this issue?

Original Trello thingy: https://trello.com/c/BtxSo9qk

**Comment by ClaudioESSilva** [comment]
The use of `$env:COMPUTERNAME` appears on the following modules:
- SharedFunctions.ps1
   -> Invoke-ManagedComputerCommand
   -> Test-SqlConnection
- Move-SqlDatabaseFile.ps1
- Reset-SqlAdmin.ps1

PS: Search done on development branch

**Comment by wsmelton** [comment]
Closing as not relevant anymore.
