### ISSUE TITLE
Backup-DbaDatabase BackupFileName to unc fails

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1800]
![image](https://user-images.githubusercontent.com/8278033/28439669-2279badc-6da3-11e7-8e76-bc9300bf7aa8.png)

**Comment by Stuart-Moore** [comment]
BackupFileName is just the filename

BackupDirectory is the path
So
 `Backup-DbaDatabase -Sqlinstance sql2016 -BackupDirectory \\dc\sql\ -BackupFileName testa.bak` 
would work

**Comment by potatoqualitee** [comment]
ah ha! thank you!
