### ISSUE TITLE
Download location for sp_WhoIsActive incorrect

### ISSUE THREAD

**Issue by deadwoodx** [sqlcollaborative/dbatools#1809]
Getting error when running `Install-DbaWhoIsActive`

WARNING: [Install-DbaWhoIsActive][10:55:30] Couldn't download sp_WhoisActive. Please download and install manually from http://whoisactive.com/who_is_active_v11_17.zip. | The remote server returned an error: (404) Not Found.

Correct location is currently http://whoisactive.com/downloads/who_is_active_v11_17.zip

**Comment by potatoqualitee** [comment]
hey @deadwoodx - thank you so much for this issue report! Super important, thank you. 

I see you corrected it in your own repo, if you'd like to add it to ours, please do submit  PR. If you have any issues with PRs you can hit up @ConstantineK on GitHub or ck on dbatools.io/slack

**Comment by deadwoodx** [comment]
Happy to do so.

Thanks for the quick response

On 21 Jul 2017 12:24 pm, "Chrissy LeMaire" <notifications@github.com> wrote:

hey @deadwoodx <https://github.com/deadwoodx> - thank you so much for this
issue report! Super important, thank you.

I see you corrected it in your own repo, if you'd like to add it to ours,
please do submit PR. If you have any issues with PRs you can hit up
@ConstantineK <https://github.com/constantinek> on GitHub or ck on
dbatools.io/slack

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/1809#issuecomment-316976662>,
or mute the thread

**Comment by potatoqualitee** [comment]
hey @deadwoodx - any chance you can get this PR in within the next few hours? I'll be doing a release and would like to include the updated location!

Thanks much,
Chrissy

**Comment by deadwoodx** [comment]
Hi

Sorry, will struggle today.

The link is below

http://whoisactive.com/downloads/who_is_active_v11_17.zip




On 22 Jul 2017 11:08 am, "Chrissy LeMaire" <notifications@github.com> wrote:

hey @deadwoodx <https://github.com/deadwoodx> - any chance you can get this
PR in within the next few hours? I'll be doing a release and would like to
include the updated location!

Thanks much,
Chrissy

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/1809#issuecomment-317172976>,
or mute the thread

**Comment by potatoqualitee** [comment]
No problem, I'll update 👍 Looking forward to your next contribution, sorry I had to rush this one 💔
