### ISSUE TITLE
Find-DuplicateIndexes not outputing all of the results in file

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#181]
Find-DuplicateIndexes - not outputting all of the results in file, only outputs first record for each database that it finds duplicate for.  Gridview shows all the results correctly.

(Cláudio Silva)

> The main goal is output the drop statements for the selected rows.
> Isn't this what is happening?

(Chrissy LeMaire)

> That is my understanding as well. @js0505 did you select the ones you wanted to output the T-SQL for?
> Can you paste the full command you used?

(js0505)

> Yes, I select the ones I wanted for output, however, when there is more than one (Well technically 2 because of the duplicate) in the list per database, it will only output the first click to the file. Command was Find-SqlDuplicateIndex -SqlServer ServerA

**Comment by ClaudioESSilva** [comment]
@js0505 can't replicate :disappointed: 
I run on server with mutiple databases, 3 of them have duplicates. For each database the grid appears. I selected 2 different rows in the grid and the scrip is generated for each row.
Can you help me to reproduce it?

**Comment by niphlod** [comment]
+1 on @ClaudioESSilva : can't reproduce. @js0505 can you please help us ? If not, I think this will need to be closed, at least until someone else can pop up with a reproducible environment.
