### ISSUE TITLE
Bug in module load where SMO is not installed

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1812]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Window Server 2012 R2, 6.0
 - PowerShell Version: 4.0
 - SQL Server (Edition|Version): N/A

## Steps to Reproduce
Install or download the master branch to a fresh Window Server 2012 R2. Upon importing the module receive message that SMO is not installed and needs to be.

![image](https://user-images.githubusercontent.com/11204251/28472770-78ea2474-6e07-11e7-858f-557e20479798.png)

Identified in line via Slack with @potatoqualitee that [line 17](https://github.com/sqlcollaborative/dbatools/blob/master/dbatools.psm1#L17) needs to be updated.

 - [x] Attach any screenshots (if possible/allowed)
 - [x] Attach output from PowerShell console (if possible/allowed)

**Comment by potatoqualitee** [comment]
fixed - removed the failover entirely
