### ISSUE TITLE
Copy-DbaCredential

### ISSUE THREAD

**Issue by artyq** [sqlcollaborative/dbatools#1815]
## Bug Report
Copy-DBACredential -Source SQLServer1 -Destination SQLServer2 -CredentialIdentity MyCred

Does not copy the one credential specified.  It copies all credentials on the source to the destination.

A version I downloaded in May that used Copy-SqlCredential -Source SQLServer1 -Destination SQLServer2 -Credentials MyCred copies the one credential specified.

**Comment by potatoqualitee** [comment]
Thanks for the report, @artyq ! We'll get on this as soon as possible.

**Comment by wsmelton** [comment]
@artyq  I cannot duplicate this issue with the latest version of the module.

- Are you running `0.9.10` or higher of the module?
- Can you provide what output you get from the command or screenshots?

**Comment by potatoqualitee** [comment]
I could, @wsmelton and fixed it in #1832. The issue was with $Credential and $CredentialIdentity which didnt exist until the PR. I piggybacked off of your other work, thank you 💯
