### ISSUE TITLE
Event notifications and related permissions disappear

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#182]
Found that event notifications can get lost when you convert.  Found that you have to re-apply connect permissions.  Note, ensure broker got copied over, I have seen where it has not.

(Chrissy LeMaire)

> @js0505 You are a gold mine! Thank you. Can you give me steps to reproduce? Some T-SQL from start to finish would be great.

(js0505)

> During my next migration from a system that contains EN I will work on generating the script for you. We are doing migrations all month so hopefully next week.

(Chrissy LeMaire)

> @js0505 when you say " ensure broker got copied over", is that the Broker Enabled or something else? I don't use Event Notifications, but they look like they are scoped at the DB. Is this accurate? Are they usually copied properly during backup/restore?

(js0505)

> Broker Enabled, and yes "usually" everything gets copied over, however, there are times I have to GRANT CONNECT ON::ServiceBroker TO ACCOUNT on the endpoint server.

**Comment by niphlod** [comment]
@wsmelton, @ctrlbold : this did ever got fixed ? if not, it'd be time to, just to not keep lingering issues too much.

**Comment by wsmelton** [comment]
Closing. If this comes up during cleanup party we can just create a new issue.
