### ISSUE TITLE
Add .Query to SMO Database Object

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1821]
## Feature Request
We      ❤️      $server.Query

Can we also get $db.Query() as well that executes within the context of the SMO Database? 

### Problem to solve

Convenience

**Comment by FriedrichWeinmann** [comment]
Implemented in https://github.com/sqlcollaborative/dbatools/pull/1830

**Comment by potatoqualitee** [comment]
thank you! 🍰
