### ISSUE TITLE
Add Support for GO in .Query

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1823]
.NET doesn't like the GO keyword, which is basically SQL Server Management Studio's word for `;`

````
System.Management.Automation.MethodInvocationException: Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database
'master'. "" ---> System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. " --->
Microsoft.SqlServer.Management.Smo.FailedOperationException: Execute with results failed for Database 'master'.  ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while
executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
````

Could GO be parsed using regex and placed with `;`?

thanks!

**Comment by ClaudioESSilva** [comment]
If we gonna do this, please make sure there is a parameter to specify the batch separator.
![image](https://user-images.githubusercontent.com/19521315/28497726-6142eda4-6f85-11e7-9f90-b73c04e7dba8.png)

**Comment by wsmelton** [comment]
`.NET doesn't like the GO keyword, which is basically SQL Server Management Studio's word for ;`

Not exactly. `GO` is a batch separator that Microsoft came up with for performance reasons. A semicolon `;` is a just a statement terminator that is part of ANSI standards.

I would actually advise against this because there are certain T-SQL statements that require a batch separator. As well, you can cause performance issues when you remove the batch separator from some T-SQL, not sure what we are using would be affected but overall it could down the road.

**Comment by potatoqualitee** [comment]
TIL. I wondered why they didn't behave exactly the same!

Nevertheless, what I proposed to @FriedrichWeinmann in private was essentially a batcher

`foreach ($query in ($sql -Split "\nGO\b")) {`

**Comment by niphlod** [comment]
I'd go for `[regex]::split($sql, '(?smi)^[\s]?GO[\s]?$')` , see https://github.com/sqlcollaborative/Invoke-SqlCmd2/issues/10

**Comment by potatoqualitee** [comment]
Got a solution!

```
$parseoptions = New-Object Microsoft.SqlServer.Management.SqlParser.Parser.ParseOptions
$parseoptions.BatchSeparator = 'GO'
$batch = [Microsoft.SqlServer.Management.SqlParser.Parser.Parser]::Parse($sql, $parseoptions)
````

**Comment by niphlod** [comment]
is it REALLY really needed instead of a simple regex ?!?!? mwhahah.

**Comment by potatoqualitee** [comment]
regex: Exception calling "ExecuteReader" with "0" argument(s): "Incorrect syntax near 'GO'." 👎 

So far, fucking nothing has worked. I hate this batchparser bug.

**Comment by potatoqualitee** [comment]
trying with invoke-sqlcmd2

```
[19:04:11][1.08 s] C:\github\dbatools> Get-DbaUserLevelPermission -SqlInstance $script:instance1 -Database tempdb
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Must declare the scalar variable "@database_principal".
Incorrect syntax near ')'.
Must declare the table variable "@T".
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Must declare the scalar variable "@database_role".
Incorrect syntax near ')'.
Must declare the table variable "@T".
The label 'ExitFunction' has already been declared. Label names must be unique within a query batch or stored procedure.
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Incorrect syntax near 'GO'.
Must declare the scalar variable "@Grantee".
Must declare the scalar variable "@Grantee".
Must declare the table variable "@T".
Must declare the scalar variable "@Grantee".
Must declare the table variable "@T".
Must declare the table variable "@T".
```

**Comment by jeffchulg** [comment]
Hi there, maybe this link could help:
https://social.technet.microsoft.com/Forums/en-US/3ebfad71-46d3-4d77-80dc-748c564bd05a/incorrect-syntax-near-39go39?forum=winserverpowershell

**Comment by baingar** [comment]
I modified the function as suggested by @niphlod . While ReadAllText, I would parse the commands using [Regex]::Split and run a loop to declare each batch as SqlCommands and execute them. Hope that helps.

**Comment by ConstantineK** [comment]
Reduced @cviorel's issue to a difference in how SSMS and we handle things in our connections and queries.

If you run the following query in SSMS it will work and fail with any of the proposed methods I have read:
```
if object_id('tempdb..#example') is not null drop table #example
create table #example (wut int) 
go
insert #example (wut) 
select 1
```

When I took a look a little deeper, I found that's because the GO keyword doesnt say "split this up into logical parts" but in fact "hey send these grouped together, but keep my session open", and implementing that behavior is going to probably need to happen on a much lower level.

References:
https://dba.stackexchange.com/a/13700/15642
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql#temporary-tables

**Comment by cviorel** [comment]
Update:
The exact same command runs fine when connection pool is not used.

As soon as  connection pool kicks in, we have sp_reset_connection showing up in the trace.
This will, among others, drop all temporary objects.

Do we have a possibility to add this a parameter for the connection? Something like:
`$srv.NonPooledConnection = $true`

Ref:
https://stackoverflow.com/questions/641120/what-does-exec-sp-reset-connection-mean-in-sql-server-profiler#2924456

**Comment by potatoqualitee** [comment]
:O whoa, i wonder what else this impacts. You can add a -NonPooled param to the internal Connect-SqlInstance command and then use `$server.ConnectionContext.Connect()` instead of `$server.ConnectionContext.SqlConnectionObject.Open()` (it's in two places)

![image](https://user-images.githubusercontent.com/8278033/33321331-9f6f5c3c-d445-11e7-885f-68856ec3b8d9.png)

**Comment by potatoqualitee** [comment]
I'mma do this and PR !

**Comment by potatoqualitee** [comment]
oh, this is done 👍

**Comment by psluke** [comment]
@potatoqualitee - do you mean that it's considered to be solved and 'go' statements are now supported e.g. by Invoke-Sqlcmd2 ?

**Comment by potatoqualitee** [comment]
yes, @psluke  - I believe it was @niphlod who added it

**Comment by psluke** [comment]
Unfortunately, I still receive "incorrect syntax near 'GO'" running: [Re-Index WSUS DB](https://gallery.technet.microsoft.com/scriptcenter/6f8cde49-5c52-4abd-9820-f1d270ddea61). Module-Version is '0.9.358'... is this working for anyone?

**Comment by niphlod** [comment]
use the get-help, luke

**Comment by psluke** [comment]
@niphlod - I don't get it, I'm sorry... Do you want me to post a message log or sth else?

**Comment by potatoqualitee** [comment]
lol i think he was making a star wars joke. Please try with the latest version - 0.9.375. If it's not working, I may have forgotten to import his changes from the original repo. Let me know and I'll have it fixed today if it's broken.

**Comment by niphlod** [comment]
pskenobi says "invoke-sqlcmd2 needs -ParseGo"
