### ISSUE TITLE
[Blog] Copy-DbaLogin write-up

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1824]
I didn't even remember LoginRenameHashtable existed! Can someone please write an in-depth blog post about Copy-DbaLogin that we can put on dbatools blog?

thanks !

**Comment by garethnewman** [comment]
What format would prefer this in?

**Comment by garethnewman** [comment]
hmmm https://dbatools.io/functions/copy-dbalogin/ done?

**Comment by potatoqualitee** [comment]
naw, that's not in-depth. this is!

https://dbatools.io/find-sql-instances/

**Comment by wsmelton** [comment]
A starting point @potatoqualitee 

https://gist.github.com/wsmelton/236d12e907f18359adeff57acb512371

I have really no idea how to add a blog post to the site being hosted on GitHub.

**Comment by wsmelton** [comment]
We can probably create this issue on the doc site now that it is hosted on GitHub if needed. Closing this one for now though.

**Comment by potatoqualitee** [comment]
yeah i need to finish migrating to GH instead of the kludgy way i did it. that is on the agenda by end of year. sorry for the hold up.
