### ISSUE TITLE
Get-DbaLastGoodCheckDb Missing -Message parameter

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#1838]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Win10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): SQL2008|Enterprise

## Steps to Reproduce
Put a database inaccessible (for example: offline) and run the Get-DbaLastGoodCheckDb on that instance
`Get-DbaLastGoodCheckDb -SqlInstance sql2008`

 - [x] Attach any screenshots (if possible/allowed)
![image](https://user-images.githubusercontent.com/19521315/28497662-686e1fd2-6f84-11e7-934c-c4527be4c93f.png)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by FriedrichWeinmann** [comment]
Resolved by @ClaudioESSilva in https://github.com/sqlcollaborative/dbatools/pull/1839
