### ISSUE TITLE
WhatIf and Confirm parameters

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#184]
The standard (and easiest) way to add WhatIf and Confirm parameters is to use the SupportsShouldProcess parameter of the CmdletBinding attribute. It adds the code/help automatically for you. 

Otherwise, you need to add both manually, so that's a related doc issue. 
https://trello.com/c/ZcZgUk12/292-help-for-whatif-confirm

**Comment by niphlod** [comment]
I think this has been agreed upon (by a vast majority if not by all). 
@ctrlbold unless told so, I'd close this in a few days.

**Comment by SirCaptainMitch** [comment]
@wsmelton / @ctrlbold can this be closed out?

**Comment by PowerDBAKlaas** [comment]
Originally, the Pester tests required docs to contain whatif and confirm,
but when we discovered it should be autogenerated and not be in the docs, I thought Rob changed the Pester tests, or was certainly planning to.
The rule is there should NOT be comment based help for those, right?

**Comment by wsmelton** [comment]
Closing this one, don't think it is relevant anymore.
