### ISSUE TITLE
Get-DbaTcpPort with -Detailed parameter can return messy output

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#1843]
## Bug Report
When running `Get-DbaTcpPort` with `-Detailed` parameter and with more than on instance (one **must be** the sql2008 (dbatools lab)) will return messy output. 
Won't show other instances name. (See screenshot below)

When running only for sql2008 it writes a warning but the output is OK.

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Win10
 - PowerShell Version: v5.1
 - SQL Server (Edition|Version): I don't think SQL Server Edition/Version is relevant in this case

## Steps to Reproduce

 - [x] Attach any screenshots (if possible/allowed)
![image](https://user-images.githubusercontent.com/19521315/28498009-8703ec4e-6f8c-11e7-9f03-2508ccdc072e.png)

 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)

> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        Connecting to sql2008                                                                                                                                                          
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        IP Address from sql2008 is 10.0.1.167                                                                                                                                          
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        Your PowerShell Version is 5                                                                                                                                                   
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        Getting computer information from sql2008                                                                                                                                      
> 7/23/2017 9:54:03 AM Get-DbaCmObject               Verbose                        Configuration loaded | Cache disabled: False | Bad Credential Cache disabled: False | CimRM disabled: False | CimDCOM disabled: False | Wmi disabled: True | PowerShellRemot...
> 7/23/2017 9:54:03 AM Get-DbaCmObject               VeryVerbose sql2008            [sql2008] Retrieving Management Information                                                                                                                                    
> 7/23/2017 9:54:03 AM Get-DbaCmObject               Verbose                        [sql2008] Accessing computer using Cim over WinRM                                                                                                                              
> 7/23/2017 9:54:03 AM Get-DbaCmObject               Verbose                        [sql2008] Accessing computer using Cim over WinRM - Success!                                                                                                                   
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        Resolving sql2008 using .NET.Dns GetHostEntry                                                                                                                                  
> 7/23/2017 9:54:03 AM Get-DbaTcpPort                Verbose                        Trying with ComputerName (SQL2008)                                                                                                                                             
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        Connecting to SQL2008                                                                                                                                                          
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        IP Address from SQL2008 is 10.0.1.167                                                                                                                                          
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        Your PowerShell Version is 5                                                                                                                                                   
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        Getting computer information from SQL2008                                                                                                                                      
> 7/23/2017 9:54:03 AM Get-DbaCmObject               Verbose                        Configuration loaded | Cache disabled: False | Bad Credential Cache disabled: False | CimRM disabled: False | CimDCOM disabled: False | Wmi disabled: True | PowerShellRemot...
> 7/23/2017 9:54:03 AM Get-DbaCmObject               VeryVerbose sql2008            [sql2008] Retrieving Management Information                                                                                                                                    
> 7/23/2017 9:54:03 AM Get-DbaCmObject               Verbose                        [sql2008] Accessing computer using Cim over WinRM                                                                                                                              
> 7/23/2017 9:54:03 AM Get-DbaCmObject               Verbose                        [sql2008] Accessing computer using Cim over WinRM - Success!                                                                                                                   
> 7/23/2017 9:54:03 AM Resolve-DbaNetworkName        Verbose                        Resolving sql2008 using .NET.Dns GetHostEntry                                                                                                                                  
> 7/23/2017 9:54:03 AM Invoke-ManagedComputerCommand Verbose                        Local connection attempt to SQL2008 failed. Connecting remotely.                                                                                                               
> 7/23/2017 9:54:04 AM Get-DbaTcpPort                Verbose                        Trying with FQDN because ComputerName failed                                                                                                                                   
> 7/23/2017 9:54:04 AM Resolve-DbaNetworkName        Verbose                        Connecting to sql2008.base.local                                                                                                                                               
> 7/23/2017 9:54:04 AM Resolve-DbaNetworkName        Verbose                        IP Address from sql2008.base.local is 10.0.1.167                                                                                                                               
> 7/23/2017 9:54:04 AM Resolve-DbaNetworkName        Verbose                        Your PowerShell Version is 5                                                                                                                                                   
> 7/23/2017 9:54:04 AM Resolve-DbaNetworkName        Verbose                        Getting computer information from sql2008.base.local                                                                                                                           
> 7/23/2017 9:54:04 AM Get-DbaCmObject               Verbose                        Configuration loaded | Cache disabled: False | Bad Credential Cache disabled: False | CimRM disabled: False | CimDCOM disabled: False | Wmi disabled: True | PowerShellRemot...
> 7/23/2017 9:54:04 AM Get-DbaCmObject               VeryVerbose sql2008.base.local [sql2008.base.local] Retrieving Management Information                                                                                                                         
> 7/23/2017 9:54:04 AM Get-DbaCmObject               Verbose                        [sql2008.base.local] Accessing computer using Cim over WinRM                                                                                                                   
> 7/23/2017 9:54:04 AM Get-DbaCmObject               Verbose                        [sql2008.base.local] Accessing computer using Cim over WinRM - Success!                                                                                                        
> 7/23/2017 9:54:04 AM Resolve-DbaNetworkName        Verbose                        Resolving sql2008 using .NET.Dns GetHostEntry                                                                                                                                  
> 7/23/2017 9:54:04 AM Invoke-ManagedComputerCommand Verbose                        Local connection attempt to sql2008.base.local failed. Connecting remotely.                                                                                                    
> 7/23/2017 9:54:05 AM Get-DbaTcpPort                Warning     MSSQLSERVER        Could not get detailed information  

 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by potatoqualitee** [comment]
Oh cool, i know how to fix
