### ISSUE TITLE
Write-DbaDataTable "Schema does not exist" issue

### ISSUE THREAD

**Issue by BartekR** [sqlcollaborative/dbatools#1845]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools? (0.9.15)
- [x] Verified errors are not related to permissions? (using `sa` account)
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System Windows 10 Home, v 1703, compilation 15063.483
 - PowerShell Version: 5.1
 - SQL Server for Linux RC1, CTP 2.1

## Steps to Reproduce

1. Ensure that schema name does exist in target database but not in `master` database
2. Run any command that inserts data using `Write-DbaDataTable` to table in target database in target schema
3. Get the error "Schema does not exist"
4. Create schema also in `master` database
5. Problem disapears.
6. Drop schema in `master` database
7. It still works OK for `tempdb`, stops working for user database
8. If working with `tempdb` - drop schema in `master` database , restart server, create schema in `tempdb` database, run `Write-OutDbaDataTable` again - "Schema does not exist"

The problem verified with `tempdb` database as well as user database. Tested with parameters:
`-Table userdb.userschema.usertable`
`-Database userdb -Schema userschema -Table usertable`

Sample code (works after schema `imnotinmaster` is created in` tempdb`):
```
 $cred = Get-Credential sa
 Get-Process -Name powershell* | Out-DbaDataTable | Write-DbaDataTable -SqlInstance 127.0.0.1:14333 -SqlCredential $cred -Table tempdb.imnotinmaster.PowerShellProcesses -AutoCreateTable 
```

Probably the error with schema checking, line 399:
`if($schema -notin $server.Databases[0].Schemas.Name)`

Should be (?):
`if($schema -notin $server.Databases[$Database].Schemas.Name)`

 - [x] Attach any screenshots (if possible/allowed)
![write-dbadatatable_error](https://user-images.githubusercontent.com/181985/28498036-6e532bca-6f95-11e7-89b5-d89c8e1996ac.png)
 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)

```
23.07.2017 10:52:28 Out-DbaDataTable   Debug                        Bound parameters:                                                          
23.07.2017 10:52:28 Out-DbaDataTable   Debug                        TimeSpanType = TotalMilliseconds | SizeType = Int64                        
23.07.2017 10:52:28 Write-DbaDataTable VeryVerbose     MSSQLSERVER  Connecting to 127.0.0.1,14333                                              
23.07.2017 10:52:28 Out-DbaDataTable   InternalComment              Finished                                                                   
23.07.2017 10:52:28 Write-DbaDataTable Warning                      Schema does not exist                                                      

```

**Comment by potatoqualitee** [comment]
loving that sql server for linux! what what! 

Thanks for this report! I'll assign it and hopefully we can get this resolved this week.

**Comment by ClaudioESSilva** [comment]
This was fixed here -> https://github.com/sqlcollaborative/dbatools/commit/00fffb20b223088368ad9ddd84214fb41cdb171e#diff-263662ad62ba0ca6b00ef913b20569a8 by @burnbay 
Can be closed.
