### ISSUE TITLE
Change ComputerNamePhysicalNetBIOS to $instance.ComputerName where applicable

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1846]
The following commands use `$server.ComputerNamePhysicalNetBIOS` which should be changed to `$instance.ComputerName`

Do Change
* Remove-DbaDatabaseSafely
* Repair-DbaServerName
* Set-DbaTcpPort.ps1
* Test-DbaLastBackup (one instance of its usage needs to use `$instance.IsLocalHost`)
*  Watch-DbaDbLogin

Do **NOT** change
* Copy-DbaDatabase
* Get-DbaClusterActiveNode
* Get-DbaServerInstallDate
* Resolve-NetBiosName
* Resolve-SqlIpAddress
* Repair-DbaServerName
* Test-DbaServerName.ps1

**Comment by niphlod** [comment]
removed Get-DbaAgentJobOutputfile as it got fixed.
