### ISSUE TITLE
Copy-SqlLogin issues

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#185]
- [x] Detect schema ownership prior to user drop attempt
- [ ] Will not drop login in destination if permissions are set
- [x] Test task

**Comment by dansqldba** [comment]
Changed to "task list" to see how useful they are.

**Comment by ConstantineK** [comment]
Just published branch fix-sqlloginschema to alter the owned schemas and make them dbo, as well as change the hardcoded sa account to use the internal function to find it. 

Wondering a bit more about "Will not drop login in destination if permissions are set", could you break that out a bit more @wsmelton ?

**Comment by wsmelton** [comment]
@ConstantineK We can likely close this if you want because I have no clue what that open item was referring to...this is one I created based on an card from Trello. [Way back when they were being kept on the board.]

**Comment by ConstantineK** [comment]
Cool.
