### ISSUE TITLE
Can't count number of passed $sqlserver params when piped using $sqlserver.count

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#187]
Instead, do $servercount = ++$i inside PROCESS then implement it like so

```
if ($servercount -eq 1)
{
    throw $_
}
else
{
    Write-Warning "Can't connect to $servername. Moving on."
    Continue
}
```

**Comment by niphlod** [comment]
@wsmelton : what is the command this was referred to ? if the issue isn't still valid, can you close it ?

**Comment by wsmelton** [comment]
No clue. This is one that was migrated from the Trello board, which most of those were archived.
