### ISSUE TITLE
Copy-SqlDatabase leaves connection open on source

### ISSUE THREAD

**Issue by sqlsauce** [sqlcollaborative/dbatools#1880]
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information

 - Operating System (Name|Version): Windows 7 SP1 Professional (6.1.7601)
 - PowerShell Version: 5.0.10586.117
 - SQL Server (Edition|Version): source: Standard 2008 SP 4, target: Standard 2014 SP2 CU4

## Steps to Reproduce

1. Migrate a database from one instance to another via backup/restore using the -Force flag.
2. Long after the process succeeds, there will be a spid left connected to the database on the source system with ProgramName of "dbatools PowerShell module - dbatools.io," which blocks taking that database offline.

**Comment by wsmelton** [comment]
Is that open SPID shown to be waiting on anything? What is the status of that connection/session showing?

**Comment by niphlod** [comment]
this was due to bad connection handling in older versions of the module. Closing as I can't replicate it for some time now.
