### ISSUE TITLE
Copy-SqlServerAgent is aliased incorrectly

### ISSUE THREAD

**Issue by Rebenton** [sqlcollaborative/dbatools#1896]
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Enterprise
 - PowerShell Version: 5.1.14393.1198
 - SQL Server (Edition|Version): SQL Server 2014 SP1 (12.0.4100.1)
 - dbatools Version: 0.9.18

## Steps to Reproduce

Simply run:

`Copy-SqlServerAgent -source server1 -destination server2`

To receive the following PS Error:

```
Copy-SqlServerAgent : The term 'Copy-DbaServerAgent' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ Copy-SqlServerAgent -source server1 -destination server2
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Copy-DbaServerAgent:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

So it's really trying to run Copy-DbaServerAgent, but a quick peek with Get-Command shows that the function is called Copy-DbaSqlServerAgent, not Copy-DbaServerAgent. 

```
PS> Get-Command -CommandType Function -Name Copy-*Agent -module dbatools

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Copy-DbaSqlServerAgent                             0.9.18     dbatools
```

I think it's just a typo on line 142 of /dbatools.psm1; changing "Copy-DbaServerAgent" to "Copy-DbaSqlServerAgent" should fix it, but I'm new to this and a PR seemed like a lot of work for an alias typo. ;)

**Comment by potatoqualitee** [comment]
Thanks so much @Rebenton! 

Now I'm confused and don't remember if it was supposed to have a Sql in there. @PowerDBAKlaas can you let me know and I'll get this in in tomorrow's release? /cc @wsmelton

**Comment by wsmelton** [comment]
It used to be called `Copy-SqlServerAgent' now it is currently called `Copy-DbaSqlServerAgent`

We could probably shorten it to `Copy-DbaSqlAgent`.

**Comment by PowerDBAKlaas** [comment]
SqlAgent... 2
SqlServerAgent... 2
DbaAgent... 24
😄 
![image](https://user-images.githubusercontent.com/22813386/28609416-e1084316-71e4-11e7-981c-e2fb489c18b9.png)

**Comment by potatoqualitee** [comment]
Ohhh I remember why - this is a wrapper, similar to Start-SqlMigration. It's the entire agent. 

But it looks like Copy-DbaSqlServerAgent exists in there 🤔

**Comment by niphlod** [comment]
fixed.
