### ISSUE TITLE
Get-DbaDiskSpace - Output format issue

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#190]
Get-DbaDiskSpace - Output format might give an error like "Cannot convert value "1.010.880,00" to type "System.Int64"" when try to set the value to an int/long variable. It is not really a bug is an improvement that can be made to the digit symbol group not be returned.

For example: 1.010.880,00 should be returned to: 1010880,00

Here I'm trying to set the value for an [long]$variable the FreeInKB from the Get-DbaDiskSpace.

Obviously I can replace the '.' or ',' for '' and work, but I think once this command can and should be reused should be more generic.
Thoughts?

**Comment by ClaudioESSilva** [comment]
I have test it and it is OK!
PS: have used Commit https://github.com/sqlcollaborative/dbatools/commit/c83f2da67222ecff49aba28cc1ea0617563e0265
