### ISSUE TITLE
Sync-DbaSqlLoginPermission Error

### ISSUE THREAD

**Issue by bobnosrati** [sqlcollaborative/dbatools#1909]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 7 Pro
 - PowerShell Version: 3
 - SQL Server (Edition|Version): SQL Server 2012 Enterprise

## Steps to Reproduce
Executed Sync-DbaSqlLoginPermission passing in Source and Destination. Received error 'Object reference not set to an instance of an object'
 - [x] Attach any screenshots (if possible/allowed)
 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

[dbatoolslog.txt](https://github.com/sqlcollaborative/dbatools/files/1177387/dbatoolslog.txt)
![image](https://user-images.githubusercontent.com/30443498/28633116-9a9d6af2-71e7-11e7-9fa2-2c3a29f9f678.png)

**Comment by potatoqualitee** [comment]
Thanks @bobnosrati - this is our second report, I'll have our big 🐞  guy @ConstantineK look into it immediately

**Comment by wsmelton** [comment]
@bobnosrati was there an XML file generated in the log path for your session? You can get the path using `(Get-DbaConfig -Name dbatoolslogpath).Value`.

Alternative if you reproduce the issue in a new PS session, after it errors execute `Get-DbaToolsLog -Errors | select FunctionName, Message | ft -wrap`

**Comment by bobnosrati** [comment]
I recreated the issue and this is the log output

"Attempting to connect to SQL Servers..","Verbose, Debug","7/26/2017 2:38:57 PM","Sync-DbaSqlLoginPermission","Verbose","8c9c1ad0-1a6c-4ae9-8840-30e5f6ffbab7",
"Using the alias Sync-DbaSqlLoginPermission is deprecated! This alias will be removed in version 1.0.0, use Sync-DbaSqlLoginPermission instead","Debug, Warning","7/26/2017 2:38:57 PM","Sync-DbaSqlLoginPermission","Warning","8c9c1ad0-1a6c-4ae9-8840-30e5f6ffbab7",

**Comment by wsmelton** [comment]
@bobnosrati was there no XML file generated in your user profile path `$env:USERPROFILE\AppData\Roaming\PowerShell\dbatools` or the path shown by the previous command?

We need the full exception information from the errors. As well the version of the module you have installed would be helpful as well to try and duplicate the issue.

**Comment by ConstantineK** [comment]
Unfortunately I have win 7 running 5.1, but I am testing this out now.

It looks like I have an additional error to report relating to the DbaInstanceParameter type, this occurred with both .\2014 and localhost\2014 
```
PS 07/26/2017 21:35:17> Sync-DbaSqlLoginPermission -Source . -Destination ".\2014"
Sync-DbaSqlLoginPermission : Cannot process argument transformation on parameter 'Destination'. Cannot convert value ".\2014" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: .\2014" At line:1 char:51
+ Sync-DbaSqlLoginPermission -Source . -Destination ".\2014"
+                                                   ~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Sync-DbaSqlLoginPermission], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Sync-DbaSqlLoginPermission
```

On a set of local instances I am not immediately able to reproduce the problem, digging a bit deeper.

**Comment by ConstantineK** [comment]
@FriedrichWeinmann reports unable to repro this unrelated issue with the type conversion. 

In other news, went through some mocks to see if anything happens when we return $null in a few places, and I am not seeing a good error throwing in that fashion.

Resolve-NetBiosName and Connect-SqlInstance returning garbage doesn't seem to give the same or similar error messages, the following pass for me locally. 

```
Context "Connect-SqlInstance" { 
        Mock -CommandName 'Connect-SqlInstance' -MockWith { $null } -ModuleName dbatools

        It 'Will complain about argument validation when Connect-SqlInstance returns a null value..' {                        
            { Sync-DbaSqlLoginPermission -Source $Instances[0] -Destination $Instances[1] } | Should Throw "Cannot validate argument on parameter 'sourceServer'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again."
        }
    }
        
    Context "Resolve-NetBiosName" { 
        Mock -CommandName 'Resolve-NetBiosName' -MockWith { $null } -ModuleName dbatools

        It 'Does not care that Resolve-NetBiosName returns null.' {
            { Sync-DbaSqlLoginPermission -Source $Instances[0] -Destination $Instances[1] } | Should Not Throw
        }
    }
```

My nose tells me we are seeing some C# component fail (mainly because that's where I see object issues such as this throwing errors) but without additional logs mentioned above, getting additional information via catching the exception in a debugger, or some additional tidbits moving further is probably going to be a crap shoot.

@bobnosrati any luck with the file @wsmelton mentions?

**Comment by bobnosrati** [comment]
Let me know if this is helpful
[dbatools_3904_error_94.txt](https://github.com/sqlcollaborative/dbatools/files/1180862/dbatools_3904_error_94.txt)

**Comment by ConstantineK** [comment]
Totally is, thanks @bobnosrati!

**Comment by ConstantineK** [comment]
`Failed to perform Grant on CONNECT to DOMAIN\Username on Accounting on SERVER1\APP. | Exception calling "Grant" with "3" argument(s): "Grant failed for Database 'Accounting'. "` looks like your problem!

Now we just need to figure out how to raise this error more clearly and find out why this grant failed so we can prevent this error in the future.

**Comment by ConstantineK** [comment]
So the main thing left (imo) is figuring out why we are throwing this fairly crappy error instead of the more clear grant issue error, and then finding out if we should be raising or warning about this in a specific fashion.

**Comment by wsmelton** [comment]
I would take a stab it is because the `Sync-DbaLoginPermission` > `Sync-Only` > `Update-SqlPermissions` The full error is not trickling back up that path.

**Comment by niphlod** [comment]
is this still valid after the latest additions to the logging framework ?

**Comment by wsmelton** [comment]
I'm not aware it has been fixed. On most commands the stop-function calls need to have the Exception flag added and `$_.Exception.InnerException.InnerException.InnerException` so the proper error gets output. 

Although just thinking now I think @potatoqualitee did do a commit that changed around how the inner exception is found and output.
