### ISSUE TITLE
General - Do not strip FQDN

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#191]
If someone specifies an FQDN, reattach the domain back to the server name when testing for netbios/ip/etc. $server.ComputerNamePhysicalNetBIOS + $domain. This impacts many commands, including Remove-SqlDatabaseSafely which broke for me because the server's dns wasn't in my search suffix.

**Comment by SirCaptainMitch** [comment]
Is this something that is being discussed in the style guide? 

If not, should it? Seems like an issue item won't have the same impact in terms of discussion.

**Comment by SirCaptainMitch** [comment]
@ctrlbold @ConstantineK is this item in the style guide? seems like it should be.

**Comment by niphlod** [comment]
PS: also watch out because the "domain from AD" may very well not coincide with the "domain from DNS".

**Comment by potatoqualitee** [comment]
We need to discuss this at length in #dbatools-style then come up with a solution, find the impacted commands and create a new issue. Please see #dbatools-style
