### ISSUE TITLE
Invoke-Ola* cmdlets

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1913]
## Feature Request

Being able to invoke ola's procedures with all the param validation would be a good thing. I'll take this upon myself.

- Invoke-OlaDbBackup
- Invoke-OlaIndexOptimize
- Invoke-OlaDbIntegrity

**Comment by potatoqualitee** [comment]
awesome_sauce x2

**Comment by wsmelton** [comment]
I'll be interested to see how you handle the output of the command when you pass in `@Execute=N'N'`. This causes a TON of text to spit out on large databases. Be nice to parse that out into some readable format, not sure if that is too far fetched.

**Comment by wsmelton** [comment]
> Invoke-OlaDbIntegrity

We already have `Start-DbccCheck` as an internal function...why not just make that external and then add in logic from Ola's processing. I don't recall his proc doing anything special.

**Comment by andreasjordan** [comment]
Hi @niphlod - still working on this?

**Comment by wsmelton** [comment]
Closing, if we want to revisit can open a new issue.

**Comment by potatoqualitee** [comment]
@claude ultrathink a complete plan for @niphlod's  proposed commands based on Ola Hallengren's current scripts (attached)

[MaintenanceSolution.sql](https://github.com/user-attachments/files/23695699/MaintenanceSolution.sql)

The scripts should include ValidateSets and no ParameterSets. Other validation as required.

After reviewing the uploaded Ola script, any other command suggestions? I dont want 15 but popular or combo kills are good.

**Comment by potatoqualitee** [comment]
@niphlod pls advise and if you like, guide claude on design. if you like it, then i think we should do one PR per command to get the highest quality code.

**Comment by niphlod** [comment]
this "can" be done as long as what we validate is the actual content of the sprocs .... we should insert at least a check on the version of the versions of the underlying stored procedures (because validation "could" be different if parameters change). Writing regression tests for everything is another huge deal, as it'll catch regressions early.
we shouldn't do invoke-dbaolacommand.

**Comment by andreasjordan** [comment]
This is the oldest open issue now. Should I ask claude to create the first command? Maybe starting with Invoke-DbaOlaDbIntegrity as it has the least number of parameters?

**Comment by potatoqualitee** [comment]
Do we want to do this? should we? if so, for dbatools 3, maybe we should do a dbatools.ola ;) or a dbatools.maintenance 

and our examples should include Get-Content params.json | Invoke-Whataver bc man 66 params is insane, also we have to keep it up to date and should probably include a scheduled task to download the latest and update, like a dependabot

**Comment by JohnNelsonNumber2** [comment]
My two cents, you already have a few with "DbaMaintenanceSolution" in the name...just thinking through naming to either match what's already there or rename?  But I love the idea myself...

<img width="1028" height="304" alt="Image" src="https://github.com/user-attachments/assets/326c1f5e-dfa5-4e2b-b364-931049b740ef" />
