### ISSUE TITLE
Get-DbaRunningJob - New Property Request

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1917]
## Feature Request

Like to see in the output when the job started running. The SMO under JobServer will not likely have it and you will need to query `xp_sqlagent_enum_jobs` and then map them based on the job ID.

Query can be found [here](https://dba.stackexchange.com/a/180469/507) but I'll put here in case it gets modified:
```sql
-- From http://www.databasejournal.com/features/mssql/article.php/10894_3491201_2/Detecting-The-State-of-a-SQL-Server-Agent-Job.htm
    CREATE TABLE #ENUM_JOB 
    ( 
        Job_ID UNIQUEIDENTIFIER, 
        Last_Run_Date INT, 
        Last_Run_Time INT, 
        Next_Run_Date INT, 
        Next_Run_Time INT, 
        Next_Run_Schedule_ID INT, 
        Requested_To_Run INT, 
        Request_Source INT, 
        Request_Source_ID VARCHAR(100), 
        Running INT, 
        Current_Step INT, 
        Current_Retry_Attempt INT, 
        State INT 
    )
    INSERT INTO #ENUM_JOB 
         EXEC master.dbo.xp_sqlagent_enum_jobs 1,garbage
    SELECT E.*, SJ.name AS job_name, SJS.step_name
        FROM #ENUM_JOB AS E
        JOIN msdb.dbo.sysjobs AS SJ
            ON SJ.job_id = E.Job_ID
        JOIN msdb.dbo.sysjobsteps AS SJS
            ON SJS.job_id = SJ.job_id
            AND SJS.step_id = E.Current_Step
    DROP TABLE #ENUM_JOB
```
 
### Problem to solve

If I'm looking for running jobs I'd like to know when it started.

**Comment by JoDouglass** [comment]
Found this while trying to find the same functionality - I agree that this would be really handy. I don't think you need to use xp_sqlagent_enum_jobs to do this, though. There are some scripts at my work which check for long-running jobs using a query similar to this:

````sql
select
  [job].[job_id],
  [job].[originating_server_id],
  [job].[originating_server],
  [job].[name],
  [job].[description],
  [job].[category_id],
  [activity].[session_id],
  [activity].[run_requested_date],
  [activity].[start_execution_date],
  [activity].[stop_execution_date]
  from [msdb].[dbo].[sysjobs_view] as [job]
  inner join [msdb].[dbo].[sysjobactivity] as [activity]
    on [job].[job_id] = [activity].[job_id]
 where [activity].[run_requested_date] is not null
   and [activity].[stop_execution_date] is null;
````

There's more information available in sysjobactivity, too - although it doesn't have info about the current step; sysjobactivity only has the last executed step and when that happened.

This blog article does something very similar, too - but with a left outer join to sysjobhistory to grab the status if available: https://am2.co/2016/02/xp_sqlagent_enum_jobs_alt/
