### ISSUE TITLE
Remove-SqlDatabaseSafely - SQL Agent check

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#192]
The check isn't accurate. Copy-SqlAgent stuff has a more accurate check. In this case, Agent was running but couldn't be verified, and the script attempted to start Agent. In SSMS, the circle was white. Probably related.

**Comment by SQLDBAWithABeard** [comment]
@wsmelton Which command has the better check? I cant seem to see it

**Comment by wsmelton** [comment]
I actually don't remember submitting this... Could have been one from trello that I pulled over.

**Comment by SQLDBAWithABeard** [comment]
Added 1f3051a0e5416144c2d828a4774952522f56a7c3 with check for $agentservice.length and prompt to continue
