### ISSUE TITLE
add execution policy info to downloads page

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1924]
thats all

**Comment by niphlod** [comment]
@potatoqualitee : https://dbatools.io/download/ needs some love in this regard, maybe just a link to https://dbatools.io/soup2nutz/ ?

**Comment by niphlod** [comment]
@potatoqualitee : last warning (or feel free to assign to a WP editor of your choice)

**Comment by potatoqualitee** [comment]
sorry my notifications all got lost in the mix. done
