### ISSUE TITLE
Test-DbaMaxMemory error 

### ISSUE THREAD

**Issue by sqlpadawan** [sqlcollaborative/dbatools#1927]
### General Troubleshooting steps

- [ x] Verified running latest release of dbatools?
- [x ] Verified errors are not related to permissions?
- [x ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
Win 10 Pro
 - PowerShell Version: 
PSVersion                      5.1.14393.1480
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1480
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - SQL Server (Edition|Version): 
SQL 2014 SP2

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ x] Attach output from PowerShell console (if possible/allowed)
[Test-DbaMaxMemory Error.txt](https://github.com/sqlcollaborative/dbatools/files/1183759/Test-DbaMaxMemory.Error.txt)

**Comment by potatoqualitee** [comment]
Thanks! Was able to repro. Will have a fix in within a couple hours!
