### ISSUE TITLE
Get-SqlRegisteredServername - Return NetBIOS names

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#193]
Could be a switch such as -HostNames or -NetBIOS etc. Will allow piping to cmdlets which don't take SQL connection strings such as Get-DiskSpace or Test-SqlDiskAllocation.

**Comment by dansqldba** [comment]
I think this has already been done @ctrlbold ?

**Comment by ctrlbold** [comment]
Nope, not yet. Should be easy, but I didn't get to it this time around.

**Comment by dansqldba** [comment]
Found it, this was added a while ago... in #85.
