### ISSUE TITLE
Get-DbaAvailabilityGroup IsPrimary Always Returns False

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#1932]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2016 Standard
 - PowerShell Version: 5.1.14393.1198
 - SQL Server (Edition|Version): 2016 Enterprise

## Steps to Reproduce
`Get-DbaAvailabilityGroup -sqlinstance SERVERNAME -AvailabilityGroup AGNAME -IsPrimary | select IsPrimary`

 - [x] Attach output from PowerShell console (if possible/allowed)
IsPrimary = False

### Problem to solve
IsPrimary always returns false.

**Comment by awickham10** [comment]
I have a pull request coming to fix this.

**Comment by wsmelton** [comment]
Closing as fixed.
