### ISSUE TITLE
Server caching

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1957]
No idea if this is a server caching issue but I've experienced this for a few hours now -- new connections try to connect to a database that was previously dropped

![image](https://user-images.githubusercontent.com/8278033/28756180-7bc68c00-7569-11e7-9fe9-fb50c81b6b25.png)

If we do leave stuff open like that, can we reset them, perhaps? With the defaultdb of the user and a refresh()?

**Comment by niphlod** [comment]
is this still happening @potatoqualitee  ?

**Comment by niphlod** [comment]
is this still happening @potatoqualitee ?

**Comment by potatoqualitee** [comment]
good q, ill have to look

**Comment by potatoqualitee** [comment]
This has been caught.

![image](https://user-images.githubusercontent.com/8278033/48563761-5249cd00-e8f5-11e8-9e39-7ccbcce92ed1.png)

**Comment by potatoqualitee** [comment]
oh also, for the other thing..it hasnt happeend since
