### ISSUE TITLE
Get-DbaDatabaseFile reports that database not accessible

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#1958]
## Bug Report
Get-DbaDatabaseFile always skips `RESTORING`, `SUSPECT` and maybe other states, that not `ONLINE`.

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

**Comment by niphlod** [comment]
@Zhunya : how would you get data from an unaccessible database ?
