### ISSUE TITLE
Start-SQLMigration fails to backup and restore databases

### ISSUE THREAD

**Issue by brink668** [sqlcollaborative/dbatools#1968]
### General Troubleshooting steps
- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System: (Server 2012R2 x64)
 - PowerShell Version: 4.0
 - Source: SQL Server 2014 Enterprise w SP2
 - Destination: SQL Server 2014 Enterprise w SP2

## Steps to Reproduce
Command Run:
`Start-SqlMigration -Source TEST-SQL2 -Destination PROD-SQL2 -BackupRestore -NetworkShare \\PROD-SQL2\Transfer -Force`

## Error
```
Migrating databases
Start-SqlMigration : Database migration reported the following error Cannot process argument transformation on parameter 'IncludeSupportDbs'. Cannot convert value "System.String" to 
type "System.Management.Automation.SwitchParameter". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
```

**Comment by niphlod** [comment]
fairly sure this has been fixed. IncludeSupportDbs is passed down just to copy-dbadatabase which has the correct type. @brink668 : feel free to reopen if this still happens
