### ISSUE TITLE
Missing functions around SQL Agent after rename

### ISSUE THREAD

**Issue by sqlhammer** [sqlcollaborative/dbatools#1969]
## Bug Report
The following cmdlets are broken because their Copy-Sql* names are deprecated and there is no associated Copy-Dba* function.

- Copy-SqlSharedSchedule
- Copy-SqlOperator
- Copy-SqlProxyAccount
- Copy-SqlJob

### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Pro
 - PowerShell Version: 5.1.14393.1480
 - SQL Server (Edition|Version): 2016 Developer

## Steps to Reproduce

Copy-SqlSharedSchedule -Source $PrimaryReplica -Destination $SecondaryReplica
Copy-SqlOperator -Source $PrimaryReplica -Destination $SecondaryReplica
Copy-SqlProxyAccount -Source $PrimaryReplica -Destination $SecondaryReplica
Copy-SqlJob -Source $PrimaryReplica -Destination $SecondaryReplica

 - [ ] Attach any screenshots (if possible/allowed)
 - [X] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [X] Attach output from PowerShell console (if possible/allowed)

[dbatools-errors-console-output.txt](https://github.com/sqlcollaborative/dbatools/files/1188136/dbatools-errors-console-output.txt)
[dbatools-errors.txt](https://github.com/sqlcollaborative/dbatools/files/1188137/dbatools-errors.txt)

**Comment by potatoqualitee** [comment]
perfect issue, thank you! will get a fix for this today

**Comment by wsmelton** [comment]
```
Copy-SqlSharedSchedule > Copy-DbaAgentSharedSchedule
Copy-SqlOperator > Copy-DbaAgentOperator
Copy-SqlProxyAccount > Copy-DbaAgentProxyAccount
Copy-SqlJob > Copy-DbaAgentJob
```

**Comment by wsmelton** [comment]
Just referencing...lines in `dbatools.psm1` to address

[Line 162](https://github.com/sqlcollaborative/dbatools/blob/development/dbatools.psm1#L162)
[Line 166](https://github.com/sqlcollaborative/dbatools/blob/development/dbatools.psm1#L166)
[Line 168](https://github.com/sqlcollaborative/dbatools/blob/development/dbatools.psm1#L168)
[Line 173](https://github.com/sqlcollaborative/dbatools/blob/development/dbatools.psm1#L173)

**Comment by niphlod** [comment]
fixed via https://github.com/sqlcollaborative/dbatools/pull/1981
