### ISSUE TITLE
Install-DbaWhoIsActive make dynamic on version

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1974]
## Feature Request
Update command to be dynamic when downloading the latest version of the procedure. Right now it has hard coded value.

### Problem to solve

As time goes and updates are made to sp_whoisactive would require us to also maintain that versioning in the function. Updating this to be more dynamic offers less management on code for our side.
### Additional information
Example of getting the latest version. As it stands going to the sit there are 2 versions listed, the first one is showing as the latest version so it would be assumed that going forward this logic should work.
```powershell
$baseUrl = "http://whoisactive.com/downloads"
$latest = ((Invoke-WebRequest -uri http://whoisactive.com/downloads).Links | where href -match "who_is_active" | select href -First 1).href
$baseUrl + "/" + $latest
```

**Comment by potatoqualitee** [comment]
i like dat

**Comment by alevyinroc** [comment]
Started looking at this tonight. The current version has the WhoIsActive latest version name hardcoded into the function and uses to look for a local copy only in the case where the user _doesn't_ want to update from online.

Should we change the function to require the user to specify the path to their local copy if they want to use one, and then punt to downloading the latest from the internet if no local copy is specified?

**Comment by wsmelton** [comment]
Could offer to do the following:

1) Check a `$Source` instance for the command, and then copy that out and push to the `$SqlInstance`
2) Validate a `$LocalFile` and if found then just use that to push to `$SqlInstance`
3) Final would be to go download it, or try.

**Comment by alevyinroc** [comment]
This is complete with #2041
