### ISSUE TITLE
import error on WS2012R2

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1990]
## Bug Report

```
VERBOSE: Loading 'FormatsToProcess' from path '...............\xml\dbatools.Format.ps1xml'.
VERBOSE: Loading module from path '........................................\dbatools.psm1'.
Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At line:56 char:5
+     [OutputType([Microsoft.SqlServer.Management.Smo.QueryStoreOptions ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At line:56 char:5
+     [OutputType([Microsoft.SqlServer.Management.Smo.QueryStoreOptions ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

```

----
on ps4, WS2012R2, current development

**Comment by potatoqualitee** [comment]
I changed the SMO load order because the included SMO from 2017 does not support Integration Services.  The load order is if no 2016 then 2014, if no 2014, then included 2017 SMO.

I'm not sure what the solution is here. I was able to import the module on WS2012R2 but could not run the command

```
PS C:\Users\ctrlb> "sql2016" | Get-DbaQueryStoreConfig
Get-DbaQueryStoreConfig : Unable to find type [Microsoft.SqlServer.Management.Smo.QueryStoreOptions]. Make sure that
the assembly that contains this type is loaded.
At line:1 char:13
+ "sql2016" | Get-DbaQueryStoreConfig
````

@FriedrichWeinmann spoke the other night about potentially adding a thing where you can pick your SMO version

**Comment by niphlod** [comment]
I'm on WS2012R2 with 2014 and that error shows up.

**Comment by potatoqualitee** [comment]
k, if we remove the unsupported output types then it should be good and only fail when the command is run. I just don't know of a good solution until we have a solid SMO suite. And QueryStoreOptions don't eist in SMO 2014.

OutputType([Microsoft.SqlServer.Management.Smo.QueryStoreOptions[]])]

**Comment by niphlod** [comment]
closing as fixed
