### ISSUE TITLE
Add option to connect to SQLInstance with Port number defined

### ISSUE THREAD

**Issue by dawgndad** [sqlcollaborative/dbatools#1997]
Can an option be added -Port for connecting to SQL Instances that have secured ports?

**Comment by potatoqualitee** [comment]
Hey @dawgndad - you can specify alternative ports like so

`Get-DbaDatabsae -SqlInstance 'sql01,49271'` or `Get-DbaDatabsae -SqlInstance sql01:49271`

**Comment by potatoqualitee** [comment]
I'll go ahead and close this issue. If you experience issues with using a comma or colon, let me know.

**Comment by eliassal** [comment]
Hi, I have a sql docker container up and running and able to access it throuhgh SSMS locally or remotelly, restore Adventureworks DB......., I try
`Get-DbaService -SqlInstance 'puppetCentos2k8,1401'`

I get

> WARNING: [15:20:57][Get-DbaService] Failed to resolve or to connect to localhost. | Multiple protocol connections were attempted, but no successful connections could be established with the specified computer.

**Comment by niphlod** [comment]
@eliassal : "Retrieves SQL Server-related Windows services from local or remote computers." . What do you want to retrieve from docker (assuming it's a linux-based on)

**Comment by eliassal** [comment]
puppetCentos2k8 is the host where the docker container runs and listen on port 1401. When I run the command on my machine to sql server it returns back all sql services, I want to do the same thing with the sql running in a container. Yes, the container is linux-based

**Comment by niphlod** [comment]
@eliassal : that's my point. Get-DbaService works only when targets are Sql Server-related **WINDOWS** services. 
In other words, it won't ever work if the target is a linux docker container.

**Comment by eliassal** [comment]
OK thannks, got it. Is there a list of commands that does not work for sql on Linux? So the question again, lets imagine i it a windows sql, would the following work
Get-DbaService -SqlInstance 'puppetCentos2k8,1401'

**Comment by niphlod** [comment]
Yeah, it would. As for the list of commands compatible .... wouldn't instead be better to know what you're trying to use and see if it works or not ? We have nearly 700 commands.

**Comment by eliassal** [comment]
I just noticed in your documentation, you indicate on linux 75% of the commands are OK, so you should be aware if I am not mistaken which commands do not work with linux environment, no?

**Comment by niphlod** [comment]
there's a clear tag at the top, "Availability", that should reflect where commands are working

<img width="643" height="220" alt="Image" src="https://github.com/user-attachments/assets/4f8b8be5-567b-48fa-b35f-3ae3e4991224" />

most of our commands are working on any platform, but it's from the point of view of the "runner" of the commands, rather than the target sql instance's operating system. 

Get-DbaService's case is moot : it was created to "interact" with windows services, so it just works on target system being Windows, irregardless of "from where you can run the function"
