### ISSUE TITLE
Write-DbaDataTable errors writing to local named instance referenced as .\instancename

### ISSUE THREAD

**Issue by sqlpadawan** [sqlcollaborative/dbatools#1998]
### General Troubleshooting steps

- [ x] Verified running latest release of dbatools?
- [ x] Verified errors are not related to permissions?
- [ x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
Win 10 
 - PowerShell Version: 
PSVersion                      5.1.14393.1480
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1480
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - SQL Server (Edition|Version): 
SQL 2014 SP2 Developer

## Steps to Reproduce

Get-DbaServerProtocol -Server .\SQL2014DEV | Out-DbaDataTable | Write-DbaDataTable -SqlServer .\SQL2014DEV -Table tempdb.dbo.DbaServerProtocol -Truncate -AutoCreateTable -Confirm:$false -WarningAction:silentlycontinue

 - [ x] Attach any screenshots (if possible/allowed)
![capture](https://user-images.githubusercontent.com/10745602/28938004-ad800732-785a-11e7-915b-4d1cdb08e1dc.PNG)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

## Feature Request

Write output from function to sql table.

### Problem to solve

Unable to write data table to local instance .\instancename (although using localhost\instancename works fine).

**Comment by niphlod** [comment]
we do not support the dot notation ATM to identify instances in any command. typing localhost is not that big of a deal and to keep everything "sane" we ruled to avoid this "possibility". Sorry
