### ISSUE TITLE
Get-SqlRegisteredServerName output to Write-DbaDataTable doesn't write field values

### ISSUE THREAD

**Issue by sqlpadawan** [sqlcollaborative/dbatools#1999]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
Win 10 
 - PowerShell Version: 
PSVersion                      5.1.14393.1480
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1480
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - SQL Server (Edition|Version): 
SQL2014SP2 Developer

## Steps to Reproduce

Get-SqlRegisteredServerName -SqlInstance myregsvr | Out-DbaDataTable | Write-DbaDataTable -SqlInstance localhost\SQL2014DEV -Table tempdb.dbo.SqlRegisteredServerName -Truncate -AutoCreateTable -Confirm:$false -WarningAction:silentlycontinue

 - [x] Attach any screenshots (if possible/allowed)
![capture_1_1](https://user-images.githubusercontent.com/10745602/28939455-5bf0c456-785f-11e7-83a0-2b3c119e3689.PNG)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
write output  from Get-SqlRegisteredServerName to sql table.

### Additional information

Looking at what was written to the sql table, and the output when running in the console, the length of the server name is written, not the actual name of the server.

**Comment by wsmelton** [comment]
This is because `Get-SqlRegisteredServerName` outputs as an array to utilize it with other commands. 

Writing the data output from this function would require we change that output so I'll leave that to @potatoqualitee if she wants to go that route.

The reason you see just numbers in your table is because the array that is output only contains one property, the `Length`. So your table is being populated with the character length of each server name returned.

**Comment by wsmelton** [comment]
@sqlpadawan a method to use in the current state of the command is to convert it to a custom object with a property name that `Out-DbaDataTable` will respect.

```powershell
Get-DbaRegisteredServerName -SqlInstance regsrv | foreach {[pscustomobject]@{ServerName=$_}} | Out-DbaDataTable | ...
```
![image](https://user-images.githubusercontent.com/11204251/28944636-edbe742e-7868-11e7-8b2f-642b1ac00cad.png)

**Comment by sqlpadawan** [comment]
Thanks, this was an attempt at a work around to get a list of servers because of an error with the group param (and i'm pretty sure i've already seen an issue for that). Probably not worth changing, chalk it up to a ps noob.

**Comment by wsmelton** [comment]
We had an issue with the group parameter but that was fixed partially. 

If you enter a group name that is a sub group or child, it will not pull the info. It only supports the full path to that child folder right now.
