### ISSUE TITLE
Error handling if they occur

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2001]
## Bug Report
Today most of function did not give clear errors description due to code complexity, not just poswershell but lot of code around any low level function we use.
## Example
```
Exception calling "Query" with "2" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute
with results failed for Database '<database>'. ""
At line:163 char:5
+                 $results = $server.Query($sql,$db.name)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The above example clearly shows the frustration experienced by the user, encompassing his misunderstanding of what is happening.

We need to provide clear information on any error encountered, that allows us to spend more time on other pleasant pursuits.

## What to do
Expand Exception object and all his InnerException, because only two last Inner Exceptions contains useful information on encountered errors.

**Comment by potatoqualitee** [comment]
this should be fixed 🎉
