### ISSUE TITLE
The DbaCredentialParameter - killing the unneeded credential prompts permanently

### ISSUE THREAD

**Issue by FriedrichWeinmann** [sqlcollaborative/dbatools#2003]
- [x] Feature

The plan is to create a special parameter class for credential objects, thereby eliminating the automatic credential prompt on older PowerShell version while - at the same time - granting additional usability upgrades.

The basic features are:
 - Accept PSCredential object as input
 - Accept null as input
 - Accept string as input, prompt for password
 - Accept Network-credentials as input

Can be used in all instances that ...
 - Ask for a PSCredential
 - Ask for a NetworkCredential

Now, if we do this, we might as well go whole hog and here's a few ideas on how this could be extended:
 - We could provide a function (`Register-DbaCredential` or something like that), that stores credentials. They could either be assigned to all connections to a server, or could be automatically retrieved when passing the correct name as string to the parameter class.
 - We could automatically register credentials we prompt for and remember them
 - We could automatically register credentials we prompt for and remember them, but disable the feature by default
 - When prompting for credentials (only when specifying a string as input), we could add a checkbox to the prompt, offering the user to remember the credentials, either for the next time he specifies the string or for all connections the credentials are actually used for.

Feedback on those ideas most welcome :)

Cheers,
Fred

**Comment by FriedrichWeinmann** [comment]
Example on how it would look in practice:
```PowerShell
# Old
[PSCredential]$SqlCredential

# New
[DbaCredential]$SqlCredential
```
No other change necessary to use/implement it

**Comment by wsmelton** [comment]
What encryption method would you use to store the credentials? 

Would it be accessible from local machine only (like central machine), only by user that created it or by anyone? 

_Sent from my Verizon SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FriedrichWeinmann** [comment]
Would be totally current user only, encryption already provided thanks to windows security (basically the exact same way PSCredential does, as that'll be the medium I'd use).

**Comment by potatoqualitee** [comment]
yes please! 🏆 

any chance we can get a dbainstance param alias for dbainstanceparameter?
