### ISSUE TITLE
Copy-DbaAgentAlert - skipps alerts when no severity specified

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2004]
## Bug Report
We have a lot of Alerts with definition by error number not severity. If you try to copy any of these alerts to another server will get error:
`Alert [Error xxxxx] has already been defined to use the severity 0. Skipping.`

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Source 2008 R2, Target 2016 SP1 CU3

## Steps to Reproduce
[development +0 ~0 -0]> Copy-DbaAgentAlert -Source srv-sqlxxxx -Destination srv-sql-xxxx

![default](https://user-images.githubusercontent.com/14327077/28965248-c8eb630e-7918-11e7-81d5-e450d6596c99.png)

### Problem to solve
Have ability to copy alerts with defined alert number not severity

**Comment by wsmelton** [comment]
Just so we can improve the test around the command, could provide a scripted alert that you found had the issue? 

Also to make sure I'm clear on what you mean. 

_Sent from my Verizon SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Zhunya** [comment]
Those two bellow are very good examples

```SQL
EXEC msdb.dbo.sp_add_alert @name=N'Error 5572', 
		@message_id=5572, 
		@severity=0, 
		@enabled=1, 
		@delay_between_responses=0, 
		@include_event_description_in=1, 
		@category_name=N'Agent Alerts Sev 23', 
		@job_id=N'00000000-0000-0000-0000-000000000000'
GO
```

```SQL
EXEC msdb.dbo.sp_add_alert @name=N'Error 3452', 
		@message_id=3452, 
		@severity=0, 
		@enabled=1, 
		@delay_between_responses=0, 
		@include_event_description_in=1, 
		@category_name=N'Agent Alerts Sev 10', 
		@job_id=N'00000000-0000-0000-0000-000000000000'
GO
```

Thank you @wsmelton!

**Comment by potatoqualitee** [comment]
I believe this has been fixed at some point. Please let me know if you continue to have issues. I successfully copied.

![image](https://user-images.githubusercontent.com/8278033/48740590-5d379100-ec58-11e8-9500-f0040200ea3a.png)
