### ISSUE TITLE
Backup-DbaDatabase not always doing diffs

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2014]
Got a report from a user via email and was able to repro with

`Backup-DbaDatabase -SqlInstance localhost -Type Diff`

![image](https://user-images.githubusercontent.com/8278033/28984892-6c21ce90-7960-11e7-8a94-ac15181402c3.png)

Specifying the database makes diff work, though as does piping (but only a single object) 🤔  (Though Type is misleading and will always say Full)

piping 1 object
![image](https://user-images.githubusercontent.com/8278033/28985171-9035c312-7961-11e7-95bc-870f5d8f47b6.png)

piping multiple objects

![image](https://user-images.githubusercontent.com/8278033/28985215-c009e276-7961-11e7-9d96-405faea9509a.png)

**Comment by Stuart-Moore** [comment]
That's strange. Will have a look
