### ISSUE TITLE
Test-DbaSpn 

### ISSUE THREAD

**Issue by kiransqldba** [sqlcollaborative/dbatools#2019]
First of all, Thank you very much every contributor for making this awesome tool                                
 Test-DbaSpn for remote server displays current sql server service account information also showing clusterd property incorrect

Test
1.tested for 10 different servers with all proper permission

**Comment by wsmelton** [comment]
Can you give an example output and what you would expect to see? 

What version of the module are you using?

**Comment by kiransqldba** [comment]
Windows Server - 2012 R2 Enterprise
Powershell module - 4.0
Sql server -Sql 2014 Standard edition

It's my work boxes so can't share output
Example :-
Run Test-DbaSpn for server2 from server1 and it's showing server1's sql service account information.

**Comment by wsmelton** [comment]
Ah! Gotcha. 

We will take a look.
