### ISSUE TITLE
Find-SqlUnusedIndex - Improve documentation

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#202]
At least, output column list in description section is not correct

**Comment by dansqldba** [comment]
@ClaudioESSilva is this still valid?

**Comment by ctrlbold** [comment]
Yah, I'm gonna move this one to the next release, but please do validate @ClaudioESSilva

**Comment by ClaudioESSilva** [comment]
Yes, still valid.

**Comment by niphlod** [comment]
@ClaudioESSilva : ping ... is this still valid ?
