### ISSUE TITLE
Get-DbaComputerSystem

### ISSUE THREAD

**Issue by kiransqldba** [sqlcollaborative/dbatools#2026]
Command - Get-DbaComputerSystem
Is it possible to add Available Sql Instances and Tcp port Fields with result?

**Comment by wsmelton** [comment]
This command is specific to OS information, not software installed.

**Comment by wsmelton** [comment]
Additional commands to get system info are in the works. 

What do you mean by ports, just ones associated with SQL Server or ones in use?

**Comment by kiransqldba** [comment]
Okay.Thanks for clarification Shawn!
Sql server TCP/IP port.

**Comment by wsmelton** [comment]
Not in front of a computer but fairly sure we have a command that pulls service and port info.

**Comment by galador** [comment]
There's [`Get-DbaTcpPort`](https://dbatools.io/functions/get-dbatcpport/).... in case you hadn't already found it @kiransqldba
