### ISSUE TITLE
Copy-SqlServerAgent fails to copy over SSIS jobs - Proxy Accounts

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#203]
Client environment tried to copy over SQL Agent and gives warning that jobs are being skipped because the proxy account does not exist....when it actually copied it over correctly. All jobs tied to that proxy though are being skipped.

**Comment by wsmelton** [comment]
Just ran Copy-SqlJob and it copies them without issues or warnings...None of the jobs were skipped.

**Comment by wsmelton** [comment]
Adding one more note, once client tried to run the SSIS jobs I had to reapply the password on the credential tied to the proxy account. Will have to see if I can recreate this issue in my domain lab and will update.

**Comment by niphlod** [comment]
@wsmelton : any update on this ?

**Comment by wsmelton** [comment]
Closing this one out until I can reproduce it.
