### ISSUE TITLE
Set-DbaSpConfigure works but outputs wrong and missing info in warning

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2032]
![image](https://user-images.githubusercontent.com/8278033/29020805-814ad2bc-7b63-11e7-9654-a2831eebcca1.png)

Just needs some variables fixed

**Comment by nvarscar** [comment]
Submitted PR. Do we need pester for that? Cause rn there is none 🤷‍♂️

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/commit/4c24b0b9d78c1169afee5fd285bbb8f7d0b54abf
