### ISSUE TITLE
Pester test that tests Connect-SqlInstance for Credential Support

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2034]
This would be fun

Login with the credential via Connect-SqlInstance (since internals are exposed) then do a Get-DbaProcess using the same credential to ensure that credential is logged in and doing stuff.

**Comment by nvarscar** [comment]
I can help with that. 
PS how come that there is still no New-DbaLogin 🤔 nice opportunity to add it

**Comment by potatoqualitee** [comment]
awesomeee. I never dared cuz it just seemed like a lot of work ;) Second to New-DbaDatabase. Please do! You may also need Set-DbaServerRole to add the appropriate role.
