### ISSUE TITLE
Test-DbaConnectionAuthScheme Showing incorrect net_transport and auth_scheme

### ISSUE THREAD

**Issue by kiransqldba** [sqlcollaborative/dbatools#2036]
OS - Windows Server 2012 R2
Powershell version - 4.0
Sql - Sql server 2014

Test-DbaConnectionAuthScheme showing incorrect net_transport and auth_scheme when connect from remote server

Showing correct info from same server.

**Comment by potatoqualitee** [comment]
hey @kiransqldba - thanks for the report. We are using T-SQL to figure it out - `"SELECT @@SERVERNAME AS ServerName, net_transport, auth_scheme from sys.dm_exec_connections WHERE session_id = @@SPID"`

How are you determining the net_transport and auth_scheme?

**Comment by kiransqldba** [comment]
Hello Chrissy,

Thank you very much to put your effort to make this free tool for everyone.

Yes I use same dmv to find Auth_scheme. I will also review code if I can help.

-Kiran

**Comment by potatoqualitee** [comment]
Our pleasure 👯 !

Interesting - perhaps PS is connecting in a different way than (I'd assume...) SSMS? Can you try with sqlcmd.exe, too?

**Comment by kiransqldba** [comment]
Interesting.

I tried on few other instances and getring right info even I checked code which looks good.
I think that few of the instnaces have AD service account issue which I have to take a look.
