### ISSUE TITLE
Backup-DbaDatabase - is not do backup at all

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2038]
## Bug Report
one simple command is not working at all:

```powershell
Backup-DbaDatabase -SqlInstance <sql_server_name> -Database <database_to_backup> -BackupDirectory \\SRV-BACKUP01\SQL_BACKUP\Archive -Type Full -CompressBackup -Verbose
```
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Workstation Windows 10, Server Windows 2008 R2
 - PowerShell Version: PS5.1
 - SQL Server (Edition|Version): 12.0.5546.0 Microsoft SQL Server Developer (64-bit)

 ## Steps to Reproduce

![default](https://user-images.githubusercontent.com/14327077/29047257-98550052-7bd3-11e7-99b3-88db820b2007.png)

**Comment by Zhunya** [comment]
its all about error handling, if I know from command why he stops.

![2017-08-08_01-08-23](https://user-images.githubusercontent.com/14327077/29047834-5b270ae2-7bd6-11e7-985b-5afcec457f9a.png)

**Comment by niphlod** [comment]
from the screenshot I'd be concerned about "the uuid server" :P 
what about $error[0].Exception.InnerException (add .InnerException until a good message comes around ?? )

**Comment by niphlod** [comment]
damn, sorry, I see you're familiar with the loop ^_^ .

**Comment by Zhunya** [comment]
Yeah, having detailed information on whats caused error saves us a lot of time )

**Comment by niphlod** [comment]
maybe we can use a better call to Stop-Function . Hopefully the "nest level" is always the same.

**Comment by wsmelton** [comment]
Yeah. The only option that could be done would be to update the `stop-function` command to include the `-InnerException`. However we've already discussed how we can try to get the error to trickle up to the host but it is not something that can be done across the board, or guaranteed to work for every occasion as I understand it.
