### ISSUE TITLE
Copy-SqlAgentJob dealing with jobs where owner does not exist on destination

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#204]
When copying jobs maybe add a switch (or include it in force) that if the owner of a job does not exist the job will simply be assigned to the "sa" account.

Job ownership is one of those things in best practice that jobs shouldn't be owned by users as those accounts are most commonly dropped if the person leaves and such. Situations where SSRS are involved is a special case that those jobs should be owned by the SSRS service account. [Although moving of SSRS jobs should probably be skipped. SSRS migration is a process all byitself.]

**Comment by wsmelton** [comment]
The catch found on this (believe it was discussed in slack channel when I found it)....the owner of a job is a straight string for string match to `$server.Logins`. 

Which this is not sufficient in cases where an owner is a valid login, because it is part of a Windows Group. The login would have to be done in 2 stages:

1. Does login exist on the instance
2. Does login have access through a Windows Group login (discussion in Slack noted use of `IsWindowsGroupMember` method, you pass in the group name).

**Comment by wsmelton** [comment]
@dansqldba @ctrlbold any opinion on how you would like to deal with this one...can think of following options to consider right off:

1. Adress how logins are compared in this command?
2. Create shared function for comparing logins maybe?
3. Create parameter like "DefaultToSa" or something if logins are not found on destination, or just have "-Force" inherit this trait?

**Comment by potatoqualitee** [comment]
I would like this to default to sa with a -Force (but not say, whatever is returned from internal command `Get-SqlSaLogin`) - can I put this on you or your team's radar, @wsmelton ?
