### ISSUE TITLE
Get-DbaLogin:  add parameter ExcludeFilter to allow filtering logins like '##*','NT *'

### ISSUE THREAD

**Issue by MARCO-K** [sqlcollaborative/dbatools#2044]
## Feature Request
  Add an additional parameter to Get-DbaLogin to exclude system/built-in logins.

### Problem to solve
Currently only following logins can be excluded:

- [object[]]$ExcludeLogin,
- [switch]$HasAccess,
- [switch]$Locked,
- [switch]$Disabled

I want to have an additional paramter to exclude $NoSystem logins too.

A simple new parameter can exlude these accounts based on their names:

` if ($NoSystem) 
{ $serverLogins = $serverLogins | Where-Object { !(($_.Name.StartsWith('##') -or $_.Name -eq 'sa' -or $_.Name.StartsWith('NT AUTHORITY\') -or $_.Name.StartsWith('NT SERVICE\'))) }
}`

### Additional information
I've already tested the new paramter for SQL versions 2008-2012.

**Comment by wsmelton** [comment]
I do believe we have had a conversation/discussion around this previously. Logins that are like `##` are not technically system logins, they are user logins specific to features/components of SQL Server. (e.g one is created for PBM, SSIS catalog, etc.).

What you are basically proposing is treating a specific list of logins as if `IsSystem` is set to 1.

 I would not say creating a parameter to exclude hard coded logins that are not technically "system" logins. We could add a filter that allows for wildcards, like `-ExcludeFilter`. Use case like `-ExcludeFilter '##*','NT *'`

**Comment by MARCO-K** [comment]
Hi Shawn,

that's why I wasn't sure how to name them... 
> "system/built-in logins"

But basically it would help a lot to have a `-ExcludeFilter`.

**Comment by SQLDBAWithABeard** [comment]
This has been completed
