### ISSUE TITLE
Out-DbaDataTable seems slow

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2046]
@jpomfret reported some slowness that I can repro. Jess, did it get slower recently?

Here's my sample

![image](https://user-images.githubusercontent.com/8278033/29076558-2865e616-7c56-11e7-824d-f4956af35f3d.png)

7429 with 26 columns (Kawww!) when piped takes 1 min, 47 seconds. When used as `InputObject` then 22 seconds. Not so bad I suppose, considering how wide it is.

**Comment by JohnRoos** [comment]
Sorry for taking so long to respond to this.

I have reproduced the same behaviour and this is a tricky one.

What takes time with this function is to go through all the properties for each object in the pipeline or in the inputobject array. The time it takes to go through them increases dramatically if you increase the number of properties. In the example above its actually 7429*26 objects to process. Thats almost 200 000 objects to process and possibly convert.

This functions is very dynamic so if speed is important, I would recommend to either lower the amount of properties (and not use the pipeline) or write a specific function tailored for the situation.

I have done some improvements to the function, which in my tests reduces the time spent on this particular example with about 30%. I hope that helps a bit.
