### ISSUE TITLE
Latest dbatools release (0.9.24) takes significantly longer to import than 0.8.947

### ISSUE THREAD

**Issue by gwojan** [sqlcollaborative/dbatools#2051]
On my workstation it takes 2 seconds to import the latest dbatools. 0.8.947 loaded without any perceptible delay.

On a server (WS2012R2, PowerShell 4, 8 vCPU) running about 20% CPU utilization `Import-Module dbatools` takes **37 seconds**! I have closed and reopened fresh PowerShell console instances and the timing is consistently 37+ seconds.

**Comment by potatoqualitee** [comment]
hey @gwojan - thanks for the report! Can you do a -verbose and see where it sits?

**Comment by gwojan** [comment]
Okay... I've tested multiple versions on my laptop going back from 0.9.24 to 0.8.974 and there doesn't appear to be any major difference in import times - I guess I wasn't paying close attention two the 2 second import time and I was taking advantage of implicit module import. Here are the first few lines of verbose output:

PS C:\Users\bubba> Import-Module dbatools -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.24\dbatools.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\dbatools\0.9.24\xml\dbatools.Format.ps1xml'.
**VERBOSE: Populating RepositorySourceLocation property for module dbatools.**
_VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.24\dbatools.psm1'._
VERBOSE: Exporting function 'Connect-AsServer'.
VERBOSE: Exporting function 'Connect-SqlInstance'.

The load delay occurs right after the line in italics is rendered.

Here's the first few lines of verbose output from the server:
PS C:\Users\bubba> Import-Module dbatools -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\xml\dbatools.Format.ps1xml'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psm1'.
VERBOSE: Exporting function 'Connect-AsServer'.

Notice this line from my workstation, in bold above, is not written in the verbose server output:

`VERBOSE: Populating RepositorySourceLocation property for module dbatools.`

Also, the delay occurs before the _VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.24\dbatools.psm1'._ is written to the console.

The server is not Internet connected. Is there a chance when `dbatools` is loading it's trying to reach out and touch someone and the delay is that connection attemp timeout? ;-)

**Comment by gwojan** [comment]
I also noticed there is a `\bin\projects` directory with project source code being included in the 0.9.x releases I've installed.

**Comment by FriedrichWeinmann** [comment]
Ah. That might be it - the wait could be the CLR timeout.
Can you try cloning the master branch and importing that on the server?

**Comment by FriedrichWeinmann** [comment]
Master should be unsigned

**Comment by potatoqualitee** [comment]
master is still signed - it's just authenticode signed and not fully catalog signed (neither is the Gallery)

I have offline servers and load in 3-10 seconds - @powerdbaklaas had a similar issue that had to do with the local and domain ExecutionPolicy. He linked out to an article by Tobias Weltner. I'll find it again once I wake up 😌

**Comment by potatoqualitee** [comment]
Yes we discussed it here: https://github.com/sqlcollaborative/dbatools/issues/779
And Klaas linked to: http://www.powertheshell.com/understanding-execution-policy/

**Comment by gwojan** [comment]
@potatoqualitee That was it! The server execution policy was set to `RemoteSigned`. Setting execution policy to `Bypass` seems to resolve the issue. I'm not sure how I missed the previously reported issue -- I guess I need to work on my GitHub search-fu... 😉 

Thanks again for the help! 😃

**Comment by potatoqualitee** [comment]
So happy that helped! I'll include this in a FAQ - it is hard to find. I found it by searching for ExecutionPolicy in the closed issues so it's reasonable you didn't find it ;)
