### ISSUE TITLE
Export-SqlLogins 

### ISSUE THREAD

**Issue by kiransqldba** [sqlcollaborative/dbatools#2061]
OS - Window Server 2012R2
SQL - 2014 
PS - 4.0

Export-SqlLogins exports all the database logins eventhough selected database like below,

 Export-SqlLogin -SqlInstance Prod1 -Database Test1 -FilePath '\\Location\backup\login.sql'

**Comment by wsmelton** [comment]
Please include version of dbatools module you are using...

**Comment by wsmelton** [comment]
I can duplicate this in the latest version under development though.

**Comment by kiransqldba** [comment]
I tested in Beta 0.9.22

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/pull/3296
