### ISSUE TITLE
Exclude Offline Databases from default Get-DbaSchemaChangeHistory

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#2064]
### Problem to solve
When running just the sql instance command if there is an offline database a warning is displayed for the DB(s).  I think it should bypass any offline databases.

### Additional information

![image](https://user-images.githubusercontent.com/169602/29153845-a3015428-7d55-11e7-9bde-19455e107314.png)

**Comment by niphlod** [comment]
already fixed, skips unaccessible databases now

**Comment by niphlod** [comment]
nope. it skips, but with a warning. PR coming soon
