### ISSUE TITLE
Wrong boot time in Get-DbaUptime

### ISSUE THREAD

**Issue by csolje** [sqlcollaborative/dbatools#2066]
## Bug Report
The Command is showing that the SQL Server is running before the Windows OS

### General Troubleshooting steps

- [x ] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2016
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): SQL Server 2012 std

## Steps to Reproduce
Just ran the command and the boot time on the sql is different from the OS as in the SQL Server is running before the OS.

![image](https://user-images.githubusercontent.com/3214200/29158854-d2a9226c-7dac-11e7-8071-601c24a3cf9b.png)

**Comment by niphlod** [comment]
sounds like timezone issues ... lemme check.

**Comment by niphlod** [comment]
Thanks for the report. It was indeed a timezone issue. Fortunately, there's an easy fix.

**Comment by niphlod** [comment]
@csolje , this https://github.com/niphlod/dbatools/commit/435d9767b89b8f0ffe1bfa3161a0b2540fc38b47 fixes the problem. It's included in a "major" PR (https://github.com/sqlcollaborative/dbatools/pull/2059) that solves other "OS interaction issues". As soon as it gets merged, it'll be fixed.

**Comment by csolje** [comment]
@niphlod great

**Comment by potatoqualitee** [comment]
That PR is amazing! I'll merge it as soon as it passes the tests @niphlod
