### ISSUE TITLE
Set-DbaDbCompression - bugs and feature request all-in one

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2073]
## Bug Report
Errors when running command to compress all databases:
`Incorrect syntax near 'NO_GAIN'.`

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 / Windows 2012 R2
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 13.0.4422 STD

## Steps to Reproduce

![2017-08-10_22-45-15](https://user-images.githubusercontent.com/14327077/29189178-5db50b8e-7e1e-11e7-869e-3b664911fa39.png)

![default](https://user-images.githubusercontent.com/14327077/29189460-461a4fec-7e1f-11e7-9298-7c621162d5e4.png)

## Feature Request
In order of importance

1. Have ability to choose compression by ROW/PAGE
2. If `MaxRunTime` not specified, run as long as you needed
3. Have switch to just compress all database objects, no matter what expertise have to say =) (in case if `- PercentCompression 0' is not working as CompressAllDatabase)

### Problem to solve

Some time we need more brainless things.

**Comment by js0505** [comment]
Just saw this, will work on the bug fix first then the feature requests.

**Comment by jpomfret** [comment]
Question on the cmdlets Test and Set-DbaDbCompression, first off, should Set call Test? They both run pretty much the same T-SQL query to get the results, would also be useful to run something like this so you could review suggestions, maybe manually remove some if wanted and then pass into Set.

Thoughts welcome, trying to use this in my environment and I feel like it needs some love and looking for some guidance.

```
$compressionSuggestion = Test-DbaDbCompression -Sqlinstance Server1 
Set-DbaDBCompression -InputObject $compressionSuggestion
```

**Comment by Zhunya** [comment]
#FEATURE REQUEST
`Set-DbaDbCompression -SqlInstance Server1 -Database DB1 -Compression Page`
And all database will be compressed with DATA_COMPRESSION = PAGE, very useful for DEV/TEST environments where we short on storage space.

**Comment by jpomfret** [comment]
@Zhunya I'll make sure to add that in too, agreed that would be useful.

**Comment by Zhunya** [comment]
Closing
