### ISSUE TITLE
Invoke-DbaLogShipping 

### ISSUE THREAD

**Issue by lukecl** [sqlcollaborative/dbatools#2074]
## Bug Report
When running 
receive error on test-path when using remote credentials, also double hop issue when running via winrm when creating directories with new-item.

Test-Path : Cannot retrieve the dynamic parameters for the cmdlet. The FileSystem provider supports credentials only on the New-PSDrive cmdlet. Perform the operation again without specifying credentials.
At line:1297 char:15
 if (-not (Test-Path -Path $DatabaseCopyDestinationFolder -Credentials
### General Troubleshooting steps

- running development branch, previous release "960" Invoke-DbaLogShipping does not work
- believe the issue is related to test-path not supporting credentials properly.
- Can duplicate in new/fresh PowerShell.exe session

### Version Information
 - WIndows Server 2016
 - PowerShell Version: 5

 - SQL Server 2016 standard

## Steps to Reproduce
Run remotely via winrm or on primary node.
Invoke-DbaLogShipping -SourceSqlInstance WIN2016\PRIMARY -DestinationSqlInstance WIN2016-DR -Database trans -BackupNetworkPath \\WIN2016\logship -Force -CompressBackup -CopyDestinationFolder \\server-dr\logship -SourceCredential $Source_Credentials -SourceSqlCredential $Source_Credentials -DestinationCredential $Dest_Credentials -Verbose -DestinationSqlCredential $Dest_Credentials

### Problem to solve
Update test-path to Test-DbaSqlPath, also good for to keep with common functions

Also when running remotly via winrm issue with double hops occur when using New-item.
Recommend updating to use New-DbaSqlDirectory

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/pull/2075
