### ISSUE TITLE
Get-DbaDatabasefiles.ps1 support for FILESTREAM/In-Memory

### ISSUE THREAD

**Issue by nedotter** [sqlcollaborative/dbatools#2087]
## Feature Request

If a database contains FILESTREAM or durable memory-optimized data, those features are ignored when executing Get-DbaDatabasefiles. 

Get-DbaDatabasefiles uses an INNER JOIN to sys.dm_io_virtual_file_stats, which filters out streaming data,  including both FILESTREAM and In-Memory containers, and as a result, doesn't provide the total storage footprint for a database. 

If that was changed to a LEFT JOIN, then you would have to differentiate the type_desc column. From sys.databasefiles, it will return FILESTREAM for both FILESTREAM and In-Memory containers. What you really want is the type_desc column from sys.filegroups, which would return:

MEMORY_OPTIMIZED_DATA_FILEGROUP, or 
FILESTREAM_DATA_FILEGROUP

**Comment by niphlod** [comment]
well, Get-DatabaseFile can't return directories, can it ? ;-) 
Dunno if get-dbadatabasefile is the best place to insert those.
The total footprint is in get-dbadatabase, hopefully.

**Comment by nedotter** [comment]
I've tested changing the query that Get-DatabaseFile creates, to use a LEFT JOIN to sys.dm_io_virtual_file_stats, and does exactly what's needed, i.e. returns the total storage and complete list of files for a database. That sounds to me exactly what Get-DatabaseFile is supposed to do.

**Comment by niphlod** [comment]
MMO and FS are directories, not files.

**Comment by nedotter** [comment]
Correct, but they still contribute to the total storage footprint for a database. I'll have a look at get-dbadatabase and perhaps you're correct, it's a better place for this change.

**Comment by niphlod** [comment]
can you attach here the query you're using ? I'm not seeing size reported for those dirs just left joining

**Comment by nedotter** [comment]
Verified the results, and you are correct about FILESTREAM size not being reported, but the size of memory-optimized filegroups is. 

Also had a look at get-dbadatabasefile, and it returns info for all databases, which is not ideal. 

SELECT
    fg.name AS FileGroupName
   ,df.file_id AS 'ID'
   ,df.type
   ,df.type_desc AS TypeDescription
   ,fg.type_desc AS FGTypeDescription -- I added this
   ,df.name AS LogicalName
   ,mf.physical_name AS PhysicalName
   ,df.state_desc AS State
   ,df.max_size AS MaxSize
   ,df.growth AS Growth
   ,FILEPROPERTY(df.name, 'spaceused') AS UsedSpace
   ,df.size AS Size
   ,vfs.size_on_disk_bytes AS size_on_disk_bytes
   ,CASE df.state_desc WHEN 'OFFLINE' THEN 'True' ELSE 'False' END AS IsOffline
   ,CASE mf.is_read_only WHEN 1 THEN 'True' WHEN 0 THEN 'False' END AS IsReadOnly
   ,CASE mf.is_media_read_only WHEN 1 THEN 'True' WHEN 0 THEN 'False' END AS IsReadOnlyMedia
   ,CASE mf.is_sparse WHEN 1 THEN 'True' WHEN 0 THEN 'False' END AS IsSparse
   ,CASE mf.is_percent_growth WHEN 1 THEN 'Percent' WHEN 0 THEN 'kb' END AS GrowthType
   ,CASE mf.is_read_only WHEN 1 THEN 'True' WHEN 0 THEN 'False' END AS IsReadOnly
   ,vfs.num_of_writes AS NumberOfDiskWrites
   ,vfs.num_of_reads AS NumberOfDiskReads
   ,vfs.num_of_bytes_read AS BytesReadFromDisk
   ,vfs.num_of_bytes_written AS BytesWrittenToDisk
   ,fg.data_space_id AS FileGroupDataSpaceId
   ,fg.type AS FileGroupType
   ,fg.type_desc AS FileGroupTypeDescription
   ,CASE fg.is_default WHEN 1 THEN 'True' WHEN 0 THEN 'False' END AS FileGroupDefault
   ,fg.is_read_only AS FileGroupReadOnly
FROM sys.database_files df
LEFT OUTER JOIN sys.filegroups fg ON df.data_space_id = fg.data_space_id
LEFT JOIN sys.dm_io_virtual_file_stats(DB_ID(), NULL) vfs ON df.file_id = vfs.file_id
INNER JOIN sys.master_files mf ON df.file_id = mf.file_id
                              AND mf.database_id = DB_ID()

**Comment by niphlod** [comment]
@nedotter : let's go in order.
- get-dbadatabasefile has a -Database parameter if you want info only for those db(s)
- both (FS and MMO) are not files, just dirs
- there's no way to tell FS size from within MSSQL (the only way would be to measure up the dir size via Windows APIs)
- we can get size of Memory Optimized Filegroup directory from sys.database_files
- lots of properties returned for "standard files" for both FS and MMO are nulls
- ultimately, the total usage of the database is "size" from get-dbadatabase, and there's no other place to get it

That being said, I'm not sure get-dbadatabasefile is the right place to pull FS and MMO infos.

**Comment by nedotter** [comment]
Understood, so your suggestion is to re-submit this suggestion under the heading of "get-dbadatabase"?

**Comment by niphlod** [comment]
what problem does get-dbadatabase show ?

**Comment by nedotter** [comment]
I'm not only interested in total usage, as it does not answer critical questions that DBAs who have to manage memory-optimized need to know, i.e.: 

1. How many containers does the memory-optimized database have? (related to RTO)

2. How much durable memory-optimized data exists in this database? This is required knowledge if you need to restore this database to another server, i.e. to determine if the target server has enough resources to actually restore the database. Granted that the storage footprint doesn't always accurately line up with the durable memory-optimized data requirements, because the files on disk must go through state changes to be garbage collected. 

The query I sent can do answer both of those questions for memory-optimized databases, but as you said it's related to files that exist in folders, and is a bit of a poor fit for Get-DbaDatabasefiles. It also doesn't accurately report the storage footprint for FILESTREAM/FILETABLE.

Also, it would be great to know if a memory-optimized database is bound to a resource pool. I have a db that is, but get-dbadatabase doesn't indicate that. 

I would hope that a great tool such as dbatools would be able to be report on all aspects of what comprises a database. Unfortunately, what we've got now with get-dbadatabase and Get-DbaDatabasefiles is not able to do that for memory-optimized databases.

**Comment by wsmelton** [comment]
Both 1 and 2 sound like a command just for that part of the database to me. 



_Sent from my Htc HTC6545LVW using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wsmelton** [comment]
Get-DbaDatabase is limited to what is returned by the SMO object. We do not prefer to expand the object much beyond that. 

The Resource group info should be a command itself, unless that info is under the database SMO object.

_Sent from my Htc HTC6545LVW using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nedotter** [comment]
Thanks for the feedback.
