### ISSUE TITLE
Out-DbaDataTable Datatype Change later on in Object

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2095]
I'm having an issue with `Test-DbaLatstBackup | Out-DbaDatatable` because I have a column that starts out as DateTime then later on in the object is an array of DateTime (which I generally handle with `-join "','"`)

Commenting out line 261 which sets an explicit datatype fixed the issue but that's a bad solution. Would it be possible to evaluate all rows before determining a datatype?

Also, can you please add `-or ... System.String[]` to line 280?

Thanks much,
Chrissy

**Comment by potatoqualitee** [comment]
Also, would it be prudent to add a -Raw param that just sets everything to a string?

**Comment by oribesser** [comment]
Hi,
It is somehow similar to what I stated on issue #1985 
I've handled it by not using one-by-one pipeline processing (not using the 'process' block), but instead aggregating all the objects first - this allows to make better assumptions on the data type to choose.
an example:
https://gist.github.com/oribesser/aa6b7749c9056bc4f9c027e297454134

**Comment by potatoqualitee** [comment]
Oh cool, thank you. I've asked @JohnRoos to take a look at that issue as well. Thanks for the report @oribesser!
