### ISSUE TITLE
Copy-DbaAudit bug reported via email

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2116]
> Hey there,
> You have a bug in your Copy-SqlAudit function.  It reports "Cannot bind argument to parameter 'Path' because it is an empty string." when you are trying to copy an Audit that writes to the application log.  It's the check on the file path that's failing so I wrote a fix for it if you're interested.
> 
> My new line is simply:
> `if (($audit.Filepath) -ne $null -AND $(Test-SqlPath -SqlServer $destserver -Path $audit.Filepath) -eq $false)`
> 
> 

That's all the old variables so would need to be updated to  using test-dbasqlpath -sqlilnstance

**Comment by dhtaylor** [comment]
With the merge of this fix, does this close the issue?

**Comment by garethnewman** [comment]
Hmmm is this fixed already?

**Comment by potatoqualitee** [comment]
looks like it! Please let us know if either of you have issues.
