### ISSUE TITLE
Restore-DbaDatabase with UseSourceDataDirectory

### ISSUE THREAD

**Issue by NeilWinder** [sqlcollaborative/dbatools#2119]
When I try to restore an existing database with the -UseSourceDataDirectory and -WithReplace options I get an error saying that the .mdf file already exists. When I don't use -UseSourceDataDirectory and specify an existing location the database is restored correctly.

For example, this works fine:
Restore-DbaDatabase -MaintenanceSolutionBackup: True -SqlInstance: MyInstance -Path: Y:\backups\MyDB -WithReplace: True -DestinationDataDirectory: e:\data\MyDB -DatabaseName: MyDB

But this gives an error:
Restore-DbaDatabase -MaintenanceSolutionBackup: True -SqlInstance: MyInstance -Path: Y:\backups\MyDB -WithReplace: True -ReuseSourceFolderStructure: True -DatabaseName: MyDB

WARNING: [Restore-DbaDatabase][16:25:54] Restore of MyDB failed, Destination File E:\data\MyDB\MyDB.mdf  exists on MyInstance

**Comment by Stuart-Moore** [comment]
Hi,
does the file exist at the second location? (E:\data\MyDB\MyDB.mdf)

And could you let us have the verbose output of an example of failing
please. Just trying to work it out, but unfortunately have limited
resources as I'm on vacation atm so the more I've got to go on the easier
it is

Cheers
Stuart

**Comment by NeilWinder** [comment]
Yes, the file is there. Basically I'm restoring a newer backup of MyDB to replace the current one. This is a DR server so every time the production server creates a backup I'm restoring it on the DR server.

If it helps, I believe the problem is in Restore-DBFromFilteredArray.ps1 around line 143. It creates the source folder structure if it doesn't exist, but if one of the files does exist then the function is exited. I think that's fine, but maybe at some point it should check for the -WithReplace option to allow the restore?

Attached is the verbose output.

[restore-verbose.txt](https://github.com/sqlcollaborative/dbatools/files/1235220/restore-verbose.txt)

**Comment by Stuart-Moore** [comment]
Fixed in #2145
