### ISSUE TITLE
New command to change service account using SQL WMI 

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2120]
http://sqlity.net/en/2368/service-master-key/

"However, if you use the SQL Server Configuration Manager to change the service account, it will automatically take care of decrypting the service master key before the account change and re-encrypting it afterwards. This is another reason, why you always want to use that tool when changing SQL Server service level settings."

**Comment by nvarscar** [comment]
In addition to the service master key encryption, there's a whole bunch of Windows permissions that need to be assigned to the new account. This is another reason why all the whitepapers insist on using SQL Server Configuration Manager. More details here: [https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions](url)

**Comment by potatoqualitee** [comment]
Yep, and Config Manager is all SQL WMI, so that'll all taken care of. 

This page even has the required code 💃 
https://blogs.msdn.microsoft.com/timomta/2014/02/20/automating-sql-service-accountpassword-changes/

You seem like the perfect candidate to be this command's author, @nvarscar ;)

**Comment by nvarscar** [comment]
@potatoqualitee Really? If that's the case I'll test that and will probably be able to either add a new command for it, or add a method to the Get-DbaSqlService to change the account. Or both, actually. I'll do some research and get back with some code, hopefully :+1:

**Comment by wsmelton** [comment]
We do not use methods in Get commands, and I would prefer this to be a command by itself and not have all the code sitting in Get-DbaSqlService.

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/pull/2332. we even have a dedicated scenario in our CI 😉
