### ISSUE TITLE
Restore-DBFromFilteredArray calls Stop-DbaProcess with incorrect parameter. Additionally verbose output gives the impression that restore succeeded, but testing of the object returned from Restore-DbaDatabase for the RestoreComplete value returns False.

### ISSUE THREAD

**Issue by pbarryuk** [sqlcollaborative/dbatools#2126]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Enterprise
 - PowerShell Version: 

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  953     

 - SQL Server (Edition|Version): SQL Server 2016 Enterprise Edition (Build 13.0.4446)

## Steps to Reproduce

Trying to restore a database using restore-dbadatabase with the following parameters:

- -FileMapping (passing an  array to move the files on restore)

- -WithReplace

The restore detected sessions using the 

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)

VERBOSE: [Get-FilteredRestoreFile][13:42:08] Got a Full/Diff backups, now find all Tlogs needed
VERBOSE: [Get-FilteredRestoreFile][13:42:08] Filtered 0 log backups down to 0
VERBOSE: [Get-FilteredRestoreFile][13:42:08] 0 Transaction Log backups found
VERBOSE: [Restore-DbaDatabase][13:42:08]  dbs to restore
VERBOSE: [Restore-DbaDatabase][13:42:08] Starting FileSet
VERBOSE: Test-DbaLsnChain - Testing LSN Chain
VERBOSE: Test-DbaLsnChain - Passed LSN Chain checks
VERBOSE: Test-DbaRestoreVersion - RestoreVersion is 11
VERBOSE: Test-DbaRestoreVersion - Closing smo connection
VERBOSE: [Restore-DBFromFilteredArray][13:42:09] Starting
VERBOSE: [Restore-DBFromFilteredArray][13:42:09] Parameters bound: SqlInstance, DbName, SqlCredential, RestoreTime, DestinationDataDirectory, DestinationLogDirectory, NoRecovery, TrustDbBackupHistory, ReplaceDatabase, ScriptOnly, filestructure, VerifyOnly, UseDestinationDefaultDirectories, ReuseSourceFolderStructure, DestinationFilePrefix, MaxTransferSize, BufferCount, BlockSize, StandbyDirectory, Continue, AzureCredential, ReplaceDbNameInFile, DestinationFileSuffix, OldDatabaseName
**VERBOSE: [Restore-DBFromFilteredArray][13:42:10] Set [REDACTED] single_user to kill processes
PS>TerminatingError(Stop-DbaProcess): "A parameter cannot be found that matches parameter name 'Databases'."**
VERBOSE: [Restore-DBFromFilteredArray][13:42:11] No processes to kill in [REDACTED]
VERBOSE: [Restore-DBFromFilteredArray][13:42:11] RPcount = 1
VERBOSE: [Restore-DBFromFilteredArray][13:42:11] Restoring [REDACTED]backup starting at order 1 - LSN 280000001692000001 in \\REDACTED]\[REDACTED]\[REDACTED]\[REDACTED]_201708171341-1-of-8.bak
VERBOSE: [Restore-DBFromFilteredArray][13:42:11] Relocating [REDACTED]to J:\SQLData\[REDACTED].MDF, 
Relocating [REDACTED]_log to I:\SQLLogs\[REDACTED]_log.ldf
VERBOSE: [Restore-DBFromFilteredArray][13:42:11] Beginning Restore of [REDACTED]
VERBOSE: [Restore-DBFromFilteredArray][13:42:11] restoring [REDACTED] to latest point in time
VERBOSE: [Restore-DBFromFilteredArray][13:42:11] restore action = Database
VERBOSE: [Restore-DBFromFilteredArray][13:42:11] Doing Recovery on last file
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Adding device
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Adding device
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Adding device
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Adding device
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Adding device
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Adding device
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Adding device
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Adding device
VERBOSE: [Restore-DBFromFilteredArray][13:42:12] Performing restore action
VERBOSE: [Restore-DBFromFilteredArray][13:42:33] Failed, Closing Server connection
WARNING: [Restore-DBFromFilteredArray][13:42:33] Failed to restore db [REDACTED], stopping | Exception calling "SqlRestore" with "1" argument(s): "Restore failed for Server '[REDACTED]'. "
VERBOSE: [Restore-DBFromFilteredArray][13:42:33] Succeeded, Closing Server connection
**VERBOSE: [Restore-DbaDatabase][13:42:33] Database [REDACTED] restored successfully**
	Results from restore of [REDACTED]:
 

SqlInstance            : [REDACTED]
DatabaseName           : [REDACTED]
DatabaseOwner          : [REDACTED]
NoRecovery             : False
WithReplace            : True
**RestoreComplete        : False**

**Comment by pbarryuk** [comment]
The issue is that `Restore-DBFromFilteredArray` can call 

`Stop-DbaProcess -SqlInstance $Server -Databases $Dbname -WarningAction Silentlycontinue`

`Stop-DbaProcess` takes the parameter -Database (with not s). 

I would really like to fix this simple oversight - but I have no idea how GitHub works - if someone could point me in the direction of some idiots introductory guide GitHub to make my first change I would be very grateful.

**Comment by Stuart-Moore** [comment]
Looks like a change elsewhere in the model as it was working OK.

We have a guide here on your first pull request (github speak for change
submission)
https://github.com/sqlcollaborative/dbatools/wiki/Your-First-Pull-Request

If that doesn't make sense (github doesn't the first Times) then asking on
our slack channel on the sqlcommunity slack will you get you more advice

Afraid I'm on holiday this week or I'd walk you through it

Cheers
Stuart

**Comment by Stuart-Moore** [comment]
Fixed in #2145
