### ISSUE TITLE
Help Text for Get-DbaDatabase Indicates Online Instead of Normal

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#2127]
Status Parameter description indicates "Could include Emergency, Online, Offline, Recovering, Restoring, Standby or Suspect."

It should indicate "Normal" instead of "Online."

**Comment by potatoqualitee** [comment]
Thanks for the report! Our awesome copy editor Andy may have it fixed shortly 🏆

**Comment by alevyinroc** [comment]
I haven't been in this function yet so I'll give it the full treatment while I'm fixing this issue.

**Comment by potatoqualitee** [comment]
Thanks so much!
