### ISSUE TITLE
Backup-DbaDatabase and SupportsShouldProcess

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2132]
It'd be great to have a -WhatIf! Thought it already did, tried to use it tonight and it was not avail.

merci 🙇

**Comment by wsmelton** [comment]
Just noting that the restore command does not have it either but does have the `OutputScriptOnly`.

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/pull/2489
