### ISSUE TITLE
Backup-DBADatabase fails when splatting and providing UNC share in the BackupDirectory parameter

### ISSUE THREAD

**Issue by luisaranda** [sqlcollaborative/dbatools#2133]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2 Standard
 - PowerShell Version: 5.1.14409.1005
 - SQL Server (Edition|Version): Microsoft SQL Server 2014 (SP2) Enterprise

## Steps to Reproduce

 - [x] Attach any screenshots (if possible/allowed)
 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
When "splatting" the command and providing a UNC share in the BackupDirectory parameter the backup fails.

Splatting and using a local folder works fine.

If the command is used without "splatting" and an UNC share it works as expected

### Additional information
![dbatools issue](https://user-images.githubusercontent.com/11068876/29482447-f0268ef0-8456-11e7-8f5c-ad1ec51b6f09.jpg)
[dbatoolslog.txt](https://github.com/sqlcollaborative/dbatools/files/1236006/dbatoolslog.txt)

**Comment by wsmelton** [comment]
Can you grab the log from that session and attach it? Should be under the user profile (`Get-DbaConfig` will show the exact log path).

**Comment by luisaranda** [comment]
[dbatools_15240_error_1.txt](https://github.com/sqlcollaborative/dbatools/files/1237221/dbatools_15240_error_1.txt)

[dbatools_15240_message_0.txt](https://github.com/sqlcollaborative/dbatools/files/1237223/dbatools_15240_message_0.txt)

**Comment by Stuart-Moore** [comment]
It appears to be generally working:
![image](https://user-images.githubusercontent.com/5613670/29962690-f2651ac4-8efb-11e7-9c29-88c7ea5f2ac0.png)

unfortunately SMO isn't great at pushing errors. Could you try it again, and see if there's an error in the SQL Server error log. Usually Backup writes more meaningful information in there.

**Comment by luisaranda** [comment]
Weird it is working now 
![image](https://user-images.githubusercontent.com/11068876/30086892-31ee54ac-9263-11e7-893a-12b63492d461.png)
