### ISSUE TITLE
Get-SqlRegisteredServerName - add exclude dynamic param

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#214]
I need to ignore my sql2k box. Excluding would be useful.

**Comment by SirCaptainMitch** [comment]
This is a bug? Or an enhancement? I'm not super certain, but leaning towards bug for now. Can we get some clarification?

**Comment by niphlod** [comment]
an enhancement, but as you can see it's already assigned to @ctrlbold . 

It'll be redone in 1.0 - @powerdbaklaas and @ctrlbold are going to redesign a server-getter

**Comment by niphlod** [comment]
ping to @potatoqualitee and/or @PowerDBAKlaas . Is something "in the works" or can we tackle this ?

**Comment by potatoqualitee** [comment]
This command needs a big ol rework - Name should be a property and not the whole output. Please do tackle by renaming and making more robust by outputting the SMO object. Hopefully the .toString() will be the needed name.

In addition, cna you append a new Property with the netbios name? Using Resolve-DbaNetworkName (perhaps hidden behind a new switch if you want.)

Also @wsmelton may have the TEPP stuff you need.

**Comment by potatoqualitee** [comment]
I just tried rewriting this command to support it but it was too challenging. Ultimately, this command will go away but the one that replaces it will indeed include Group and ExcludeGroup. Promise <3
