### ISSUE TITLE
Get-DbaDatabase when more then one server in -sqlinstance write the servername

### ISSUE THREAD

**Issue by csolje** [sqlcollaborative/dbatools#2142]
## Feature Request
It would be nice if Get-DbaDatabase -SqlInstance sql01, sql02

writes out the servername/InstanceName for each database when there is more then one server/instance in the parameter -SqlInstance

**Comment by PowerDBAKlaas** [comment]
@csolje do you have an example where it doesn't do that?
[ComputerName], [InstanceName] and [SqlInstance] are in the default output.

**Comment by csolje** [comment]
![image](https://user-images.githubusercontent.com/3214200/29618048-20b1e42a-8817-11e7-95e2-26d04297f472.png)

**Comment by PowerDBAKlaas** [comment]
this is probably due to the default formatting.
The computername and instancename shuld be there, they just don't fit on the screen with those defaults.
if you add `| format-list` or `| format-table computername, databasename,size` or `| Out-Gridview` what do you get?

**Comment by PowerDBAKlaas** [comment]
the 'missing' computername & instancename are not because of this function.
Both are returned as expected, but hidden by view definitions that are not ours, but got in the way on @csolje 's system.
No action required.
