### ISSUE TITLE
Import of module causes buildlog file to be generated

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2148]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session on new server?

### Version Information
 - Operating System (Name|Version): Window Server 2012 R2
 - PowerShell Version: ```Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2```
 - SQL Server (Edition|Version): N/A

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)
Download module via `httsp://dbatools.io/zip` and then import and it will sit for a few seconds. I know this should be the portion that is building the DLL file, and as soon as it is done I can check the root folder where I expanded the zip file. An `msbuild.log` file is generated.

![image](https://user-images.githubusercontent.com/11204251/29725600-50662394-8992-11e7-8c27-a634c84aff3f.png)

![image](https://user-images.githubusercontent.com/11204251/29725605-5478248c-8992-11e7-870a-a373b40f9e92.png)

I can't provide the full file because it is two large for me to pull from client environments. I'll have to get a new server built in my lab and can provide the full output if required.
### Problem to solve

Main one is why the log is generated as it seems to indicate errors.

**Comment by niphlod** [comment]
@wsmelton : with all the changes done to our "build system" I feel we can close this now, I can't repro
