### ISSUE TITLE
Get-DbaUptime output needs update

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2152]
## Feature Request

The output of this command is controlled by two parameters: 
```powershell
.PARAMETER SqlOnly
Excludes the Windows server information

.PARAMETER WindowsOnly
Excludes the SQL server information
```

This does not really conform to our standard in other commands of having a default output and then users doing a `select-object` to return all of it.

### Problem to solve

I would say the last bit of code in this function that sets the output needs to be adjusted to be controlled by `$defaults` variable as we do with other functions. Then just pass that into `Select-DefaultView`. I would also suggest just having the SQL only output as default, or just outputting it all.

Could just work on adjusting it and see what makes the most sense.

**Comment by potatoqualitee** [comment]
I agree that it should better conform to the way we do stuff and it needs an update to use Select-DefaultView 👍

**Comment by potatoqualitee** [comment]
I also like having the Windows info by default, however, and just skipping it when it needs to be skipped. The variable names need updating as well. Should be ExcludeSql and ExcludeWindows

**Comment by wsmelton** [comment]
My point is to match our other commands and the format we have been doing, the exclude parameters should not be there at all. Just let the command output all of it.
