### ISSUE TITLE
Start-DbaSqlService is starting services I did not tell it to

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2157]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Pro
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Developer | 2016

## Steps to Reproduce
Just issue `Start-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver` as I wanted to start the database engine.

The issue is it also started 3 other services that I did not want started.

![image](https://user-images.githubusercontent.com/11204251/29786267-189836c2-8bf0-11e7-948e-3c4d321de63a.png)

As well, we need to shut the warnings off for the CmObject command, we don't need to see the output of warnings in my opinion.

**Comment by nvarscar** [comment]
@wsmelton All of the services in the log belong to MSSQLSERVER instance, that's why they got started. If you want to start only one specific service type, try using the -Type parameter.

**Comment by wsmelton** [comment]
So we are not matching the functionality that `Start-Service` does? I'll just use that one because it is less typing for me. :)

**Comment by nvarscar** [comment]
@wsmelton absolutely, if you have a single machine and know the service name, it's much easier to use `start-service` (that one however wouldn't ensure that the service was successfully started). This command is designed to work with multiple services and multiple servers at once, using the right order to stop and start services.
RE warnings, I'll look into it, but they come from CmObject function, and I'm not entirely sure why at this point.
