### ISSUE TITLE
Stop-DbaSqlService few issues

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2158]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Pro
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Developer | 2016

## Steps to Reproduce
Stopping SSRS and SSAS services if you do not provide an instance name it seems to try and stop everything. It should only default to the default instance name if one is not provided.

![image](https://user-images.githubusercontent.com/11204251/29786443-cbc596ea-8bf0-11e7-80d0-4aae7ff91aba.png)

The warning message is not very clear as well or readable as to why it didn't stop. In this case I know why, because the service was already stopped but that is not noted anywhere in the output:

```
WARNING: [Stop-DbaSqlService][12:57:49] The attempt to stop the service MSOLAP$NUMBER12 on MANATARMS returned the following error: The reque
sted control code cannot be sent to the service because the state of the service (Win32_BaseService.State property) is equal to 0, 1, or 2.
WARNING: [Stop-DbaSqlService][12:57:49] The attempt to stop the service MSSQLServerOLAPService on MANATARMS returned the following error: Th
e requested control code cannot be sent to the service because the state of the service (Win32_BaseService.State property) is equal to 0, 1,
 or 2.
```

In addition, the call to `Update-SerivceStatus` should be wrapped in a try/catch block since that command just throws the error. The catch block should utilize the `Stop-Function` so the error is written to the dbatools log properly.

**Comment by nvarscar** [comment]
The error you see is a native service control error returned by a corresponding WMI namespace (which is sometimes too vague, as in the example you posted). I'll add more checks to the function code to prevent it from stopping services that are already stopped (same for start/restart).
Will also re-visit the error handling in `Update-SerivceStatus`, which uses `Write-Message -Level Warning` instead of `Stop-Function` in the try/catch block.

**Comment by potatoqualitee** [comment]
Thanks so much for testing, @wsmelton!

**Comment by nvarscar** [comment]
All of the issues have been addressed - thanks a ton!
