### ISSUE TITLE
Import-DbaCsvToSql fails importing CSV file from UNC path

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#2161]
### General Troubleshooting steps

See slack thread:
https://sqlcommunity.slack.com/archives/C1M2WEASG/p1503708871000074

- [X] Verified running latest release of dbatools? 0.9.39
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Enterprise 1703 15063.413
 - PowerShell Version: 5.1.15063.413
 - SQL Server (Edition|Version): SQL 2008 R2 SP3 Standard 10.50.6220

## UNC path without quotes
Import-DbaCsvToSql -Csv \\\network\share\folder\path\folder\0015.csv -SqlInstance MyServer -Database MyDatabase -Table MyTable

results in:

New-Object : Exception calling ".ctor" with "1" argument(s): "The given path's format is not supported."
At line:470 char:20
+ ... umnparser = New-Object Microsoft.VisualBasic.FileIO.TextFieldParser($ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

## UNC path with double quotes

Import-DbaCsvToSql -Csv "\\\network\share\folder\path\folder\0015.csv" -SqlInstance MyServer -Database MyDatabase -Table MyTable

results in:

New-Object : Exception calling ".ctor" with "1" argument(s): "The given path's format is not supported."
At line:470 char:20
+ ... umnparser = New-Object Microsoft.VisualBasic.FileIO.TextFieldParser($ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by alevyinroc** [comment]
@wsuhoey & I discussed on Slack before opening this. It appears to me that it's something to do with how we're passing the CSV file path into `Microsoft.VisualBasic.FileIO.TextFieldParser` but more debugging is needed.

**Comment by Stuart-Moore** [comment]
Was fixed with #2184
