### ISSUE TITLE
Copy-DbaSqlServerAgent fails when copying across a job that's dependent on a new proxy account or operator.

### ISSUE THREAD

**Issue by JoDouglass** [sqlcollaborative/dbatools#2166]
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions? (I am running the command from an account which has sysadmin on both the source and destination instances.)
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 7
 - PowerShell Version: 5
 - SQL Server (Edition|Version): 2016 Standard

## Steps to Reproduce
Steps:
1) Create an operator (Jo) on instance A.
2) Create a proxy (SSIS Proxy) account on instance A.
3) Create a job (Job 1) on instance A with a step that uses the new operator.
4) Create another job (Job 2) which sends a notification to the new proxy account.
5) Run Copy-DbaSqlServerAgent with server A as the source, and server B as the destination.

Results:
1) Operator copy successful.
2) Proxy account copy successful.
3) Job 1 copy fails due to operator not existing. (WARNING: [Copy-DbaAgentJob][hh:mm:ss] Operator(s) Jo doesn't exist on destination. Skipping job [Job 1])
4) Job 2 copy fails due to proxy account not existing. (WARNING: [Copy-DbaAgentJob][hh:mm:ss] Proxy Account(s) S doesn't exist on destination. Skipping job [Job 2].)
5) Checking instance B will confirm that the operator and proxy exist, but the jobs do not.

Running Copy-DbaSqlServerAgent again (without -Force) will result in everything working:
1) Operator skipped as it already exists.
2) Proxy account skipped as it already exists.
3) Job 1 copy successful.
4) Job 2 copy successsful.

However, running Copy-DbaSqlServerAgent **with** -Force will get a different result:
1) Dropping/recreating the operator will be successful.
2)The dropping of the proxy account will fail (WARNING: [Copy-DbaAgentProxyAccount][hh:mm:ss] Issue dropping proxy account | Exception calling "Drop" with "0" argument(s): "D
rop failed for ProxyAccount 'SSIS Proxy'. ")
3) The copy of the job dependent on the operator will fail again (WARNING: [Copy-DbaAgentJob][hh:mm:ss] Operator(s) Jo doesn't exist on destination. Skipping job [Job 1).
4) The copy of the job dependent on the proxy account will be successful.

I get the same results from subsequent runs regardless of whether I run it in the same session as the first run, or a separate one.

I'm going to try recreating this again from home and will edit to include logs once I have ones without work instance names included.

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Additional information

As discussed in the Slack #dbatools channel with @wsmelton and @alevyinroc on 2017-08-29. At the time I thought that Copy-DbaAgentJob was always failing if I passed an SMO rather than a server name, but this may have been my error; I'll try recreating again from home and add further details.

**Comment by potatoqualitee** [comment]
Thanks so much for the detailed report! We'll take a look asap.
