### ISSUE TITLE
Restore-DbaDatabase\Get-FilteredRestoreFile - skipping a TRN after the DIFF and so complains of LSN break in chain

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#2167]
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2016
 - PowerShell Version: 5.1.14393.1198
 - SQL Server (Edition|Version): SQL Server 2012 & 2016

## Steps to Reproduce
```
Restore-DbaDatabase -Path \\server1\BackupTest\Database1\ -SqlInstance server1 -DatabaseName Database1 -useDestinationDefaultDirectories
```
In the path folder there is a full backup, differential and several log backups. there is a log backup between the diff and trn that are mentioned in the error below:

```
WARNING: Test-DbaLsnChain - Break in LSN Chain between
\\server1\BackupTest\database1\database1_backup_201707310300_diff.bak and
\\servre1\BackupTest\database1\database1_backup_201707310555.trn
```

The issue seems to be within Get-FilteredRestoreFile and the TRN that is being skipped has the same LSN as the lastLSN of the differential backup. PR incoming...

**Comment by Zhunya** [comment]
I have same issue, and yes problem in that weird -ge )
