### ISSUE TITLE
Test-DBADiskAllocation to a SQL Cluster with two instances bug (edge Case)

### ISSUE THREAD

**Issue by PsPsam** [sqlcollaborative/dbatools#2171]
## Bug Report
Trying to use Test-DBADiskAllocation on a Windows failovercluster that has two SQL cluster on it. 
CLSQL01 and CLSQL02
CLSQL01 has only default instance
CLSQL02 has only a named instance CLSQL02\Skype

When I run Test-DBADiskAllocation agains CLSQL01 the skript tries to connect both SQL Instance on CLSQL01 IP.

It should only connect to the default instance.

CLSQL01
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions? Can connect with SSMS and powershell 
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 and Windows server 2012 R2
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): SQL 2014 12.0.4439.1

## Steps to Reproduce
Set up a failover cluster
Install two sql clusters on the windows failover cluster. CLSQL1 and CLSQL2

Setup the CLSQL2 as a named instans.

 - [X] Attach any screenshots (if possible/allowed)
![image](https://user-images.githubusercontent.com/20344934/29873090-60f853fe-8d92-11e7-99c0-1ba18f43029d.png)

 - [X] Attach output from PowerShell console (if possible/allowed)
[Cluster2.txt](https://github.com/sqlcollaborative/dbatools/files/1263631/Cluster2.txt)

**Comment by potatoqualitee** [comment]
It does try to connect to all instances on a host to ensure $isSqlDisk is accurate. This provides the most coverage for most cases. I recommend running with NoSqlCheck
