### ISSUE TITLE
Unexpected never-ending repeat exec of command against target at regular intervals

### ISSUE THREAD

**Issue by SQLGB** [sqlcollaborative/dbatools#2173]
### General Troubleshooting steps
- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2 Standard
 - PowerShell Versions: 5.1.14409.1005 and 5.0.10586.117
 - SQL Server (Edition|Version): Enterprise 2012

## Steps to Reproduce
Run database activity monitoring tool of your choice on target database instance to capture dbatools activity.  Run a command like the following in PowerShell ISE, observe expected activity in monitoring tool.  Wait three minutes, then observe duplicate activity against the target from dbatools when no additional commands have been executed.

### Problem to solve
Unexpected and never-ending repeat execution of command against target instance at regular intervals.  Running a command like the following in PowerShell ISE queries the target server for the needed info and returns the results, but then continues to query the target server once every three minutes (without displaying any additional output in PowerShell ISE), and the connection to the server is never closed.  I've seen these stay open for days on end.  Additionally, when PowerShell ISE is finally closed, the PowerShell_ise.exe process in Windows does not end, and the connections to the database are STILL open.  You must force kill the connections on the target server and/or force kill the PowerShell_ise.exe process in Windows.

Example command execution:
Get-DbaDatabaseSpace -sqlserver myservername

### Additional information
I'm a fairly new dbatools user, so I'm not certain if this is expected or intentional behavior, but it seems odd.  I mentioned it in the #dbatools Slack channel, and @wsmelton suggested I report it here.  The Get-DbaDatabaseSpace command is mentioned above as an example, but I've seen similar behavior with other commands as well.  Same behavior observed on two clients (clients in this case were running Windows Server OS) against multiple SQL Server instances of multiple versions / builds.  The delay between repeat execution may vary depending on the dbatools command in question.  Same behavior observed in both PowerShell ISE and PowerShell command-line utility (slight difference is that exiting command-line PowerShell process does actually end the Windows process and close database connections without requiring Windows process kill or database connection kill).

**Comment by potatoqualitee** [comment]
Super interesting! We rely on SQL Server Connection pooling to kill threads. If you'd like to force closures, you can `Clear-DbaSqlConnectionPool` or close the application (ISE/cmd) executing the commands. 

Commands should not repeat, however, that's not something I've ever seen. I'll dig into it, thanks for the report.

**Comment by wsmelton** [comment]
I can confirm and duplicate this at least from the basic instance I have on my local machine. Ran a command with an XE session monitoring logins and I get multiple.

Left my PS session running in VS Code and restarted my instance (SQL Server) and immediately had two connections show up for dbatools module (application name that we set was showing up) as soon as the instance accepted connections.

**Comment by SQLGB** [comment]
Looks like this may have gotten some attention in recent builds like 0.9.42; thank you for this.  It appears that commands such as Get-DbaDatabaseSpace are no longer executed once every three minutes after initial execution.

Interestingly, a portion of the original issue remains -- if running from PowerShell ISE, exiting ISE via the "exit" command does result in closing of the ISE application window, but the corresponding process is still running in Windows and it retains an open connection to any servers which were queried via Get-DbaDatabaseSpace (and possibly other commands/functions) prior to exiting.  User must terminate the ISE process via "End Task" in Windows Task Manager (or similar) to end the process, which in turn closes the open database connections.

The exit behavior from PS.EXE is different -- if you run DbaDatabaseSpace from PS.EXE, then enter "exit" to quit, the application window closes and the corresponding Windows process closes as well, closing any remaining database connections.

Is additional work planned on this issue, or is this the expected behavior when running via ISE?

**Comment by potatoqualitee** [comment]
hey @sqlgb - thanks for reporting this issue (and updating so often 👍 ). We did change our caching from async to sync. I'm not sure about the powershell.exe vs ISE but will have someone look into it.

**Comment by wsmelton** [comment]
That behavior is part of the ISE with regards to the process (powershell.exe) still running if you close via `exit` in the console window. The module would have no control over that application. We cannot control the process not closing itself when you close the ISE.
