### ISSUE TITLE
Sync-DbaSqlLoginPermission: -Login abcd does not work

### ISSUE THREAD

**Issue by lfagetti** [sqlcollaborative/dbatools#2176]
### General Troubleshooting steps

- [ ] Verified running latest release of dbatools? YES
- [ ] Verified errors are not related to permissions? YES
- [ ] Can duplicate in new/fresh PowerShell.exe session? YES

### Version Information
 - Operating System (Name|Version):  W2012R2 Std
 - PowerShell Version: 5.1.14409.1005
 - SQL Server (Edition|Version): SQL2016

## Steps to Reproduce
Sync-DbaSqlLoginPermission -Source "xxxsql01" -Destination "xxxsql01\lab2016" -Login ppp_test1 -Verbose

### Additional information

All logins from Source (AD or SQL logins) are sync'ed, not just ppp_test1.

**Comment by wsmelton** [comment]
@lfagetti I am not able to duplicate this issue can you provide what version of the module you are running?

**Comment by jablonde** [comment]
I have the same issue.  I only want to update the permissions for a single login, however when running the command below, *all* logins are processed.

Sync-DbaSqlLoginPermission -Source "sourcesql" -Destination "destinationsql" -Login "blah" -Verbose

Version Information
DbaTools Version: 0.9.306
Operating System (Name|Version): W2012R2 Datacenter
PowerShell Version: 5.1.16299.251
SQL Server (Edition|Version): SQL2014
