### ISSUE TITLE
Get-DbaBackupHistory -LastFull is broken

### ISSUE THREAD

**Issue by Sobbie** [sqlcollaborative/dbatools#2181]
### General Troubleshooting steps
Got the latest version.

- [ x ] Verified running latest release of dbatools?
- [ x ] Verified errors are not related to permissions?
- [ x ] Can duplicate in new/fresh PowerShell.exe session?  also talked with wsmelton on this in slack

### Version Information
 - Operating System (Name|Version): Windows 7
> [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
6      1      7601   65536
 - PowerShell Version: 
> $psversiontable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18728
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

 - SQL Server (Edition|Version): 

Build | Edition | NameLevel | SPLevel | CULevel | KBLevel
-- | -- | -- | -- | -- | --
12.0.5000 | Standard Edition (64-bit) | 2014 | SP2 LATEST | 3171021

## Steps to Reproduce
run the following command
"Get-DbaBackupHistory -SqlInstance server -LastFull"
on my system it returns NOTHING.  if I run the same command with a database
nothing to screenshot as it just doesnt return anything (or the last database).  

### Problem to solve
Would like "get-dbabackuphistory -sqlinstance SERVER -lastfull" to return the last full backup for each database on the instance.

**Comment by js0505** [comment]
I came across this last week and have utilized the following command to do an actual restore: $File = Get-ChildItem \\$server\PATH\FULL -recurse 
    $File | Restore-DbaDatabase -SqlInstance $UATServer -DatabaseName $dbname -MaintenanceSolutionBackup -WithReplace -verbose

**Comment by js0505** [comment]
I know there is another bug for -Last and I think that has been fixed, however using Get-ChildItem resolved my issue with the Get

**Comment by Stuart-Moore** [comment]
Hi,
Can you run `get-dbabackuphistory -sqlinstance SERVER -lastfull -verbose` and post up the output please

and then can you run `get-dbabackuphistory -sqlinstance SERVER -lastfull -debug`. This will drop out the T-SQL that's running under the hood, can you try running that in the target instance and see if it returns anything.

**Comment by Stuart-Moore** [comment]
Turns out someone else was already looking into this. It's just been merged into the dev branch if you'd like to take a look.
