### ISSUE TITLE
Invoke-SqlCmd2 fails with UNC path

### ISSUE THREAD

**Issue by jondavis9898** [sqlcollaborative/dbatools#2192]
## Bug Report

Executing Invoke-SqlCmd2 and providing an UNC based InputFile results in the error described below.  The reason for this is error is that [Line 295](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Invoke-SqlCmd2.ps1#L295) of the script obtains the 'path' property returned from Resolve-Path, however for UNC paths, the path value contains provider information.  Using the ProviderPath property would resolve the UNC path issue without regressing existing functionality.

### General Troubleshooting steps

- [X] Verified running latest release of dbatools? 0.9.39
- [X] Verified errors are not related to permissions? Yes
- [X] Can duplicate in new/fresh PowerShell.exe session? Yes

### Version Information
 - Operating System (Name|Version): Windows Server 2016 Standard Version 1607 OS Build 14393.1593
 - PowerShell Version: 5.1.14393.1532
 - SQL Server (Edition|Version): Microsoft SQL Server 2016 (SP1-CU3) (KB4019916) - 13.0.4435.0 (X64) 

## Steps to Reproduce

 - [X] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [X] Attach output from PowerShell console (if possible/allowed)

```
PS C:\> Invoke-Sqlcmd2 -ServerInstance "localhost" -InputFile "\\localhost\scripts\test.sql"
Exception calling "ReadAllText" with "1" argument(s): "The given path's format is not supported."
At line:299 char:13
+             $Query =  [System.IO.File]::ReadAllText("$filePath")
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
 
Exception calling "Fill" with "1" argument(s): "ExecuteReader: CommandText property has not been initialized"
At line:454 char:17
+                 [void]$da.fill($ds)
+                 ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
```

## Feature Request

Ability to run scripts from a UNC share

### Problem to solve
Unable to run scripts from UNC share

### Additional information
```
PS C:\> $filePath = $(Resolve-Path "\\localhost\scripts\test.sql")

PS C:\> $filePath.Path
Microsoft.PowerShell.Core\FileSystem::\\localhost\scripts\test.sql

PS C:\> $filePath.ProviderPath
\\localhost\scripts\test.sql

PS C:\> $filePath = $(Resolve-Path "Y:\test.sql")

PS C:\> $filePath.Path
Y:\test.sql

PS C:\> $filePath.ProviderPath
Y:\test.sql

PS C:\> y:

PS Y:\> $filePath = $(Resolve-Path "./test.sql")

PS Y:\> $filePath.Path
Y:\test.sql

PS Y:\> $filePath.ProviderPath
Y:\test.sql
```

**Comment by alevyinroc** [comment]
I've created [PR 8](https://github.com/sqlcollaborative/Invoke-SqlCmd2/pull/11) against the `Invoke-SqlCmd2` repository to fix this. Once that's merged, the function will be copied into dbatools.

**Comment by jondavis9898** [comment]
@alevyinroc  Thank you for addressing this, greatly appreciated! Looks like [PR 11](https://github.com/sqlcollaborative/Invoke-SqlCmd2/pull/11) was merged, look forward to it being brought over to dbatools.

**Comment by alevyinroc** [comment]
@jondavis9898 it's already in the development branch! https://github.com/sqlcollaborative/dbatools/blob/development/functions/Invoke-SqlCmd2.ps1

**Comment by jondavis9898** [comment]
@alevyinroc Awesome, thank you again!!
