### ISSUE TITLE
Error with Get-DbaDatabase using parameter -NoFullBackupSince

### ISSUE THREAD

**Issue by mvillegascuellar** [sqlcollaborative/dbatools#2194]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

## Steps to Reproduce

When I execute the cmdlet Get-DbaDatabase using parameter -NoFullBackupSince I get the following error:

```
Get-DbaBackupHistory : A parameter cannot be found that matches parameter name 'IgnoreCopyOnly'.
At line:266 char:66
+ ... (Get-DbaBackupHistory -SqlInstance $server -LastFull -IgnoreCopyOnly)
+                                                          ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-DbaBackupHistory], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-DbaBackupHistory
```

 - [x] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

![powershell_2017-09-04_10-01-21](https://user-images.githubusercontent.com/25183564/30031668-063ed8e2-9158-11e7-9797-3cc821ef839b.png)

**Comment by Stuart-Moore** [comment]
Oops, that'll have been broken for a while, thanks for reminding.

Just submitted a PR in that fixes it.

**Comment by Stuart-Moore** [comment]
issues fixed with last merge on 5/09/2017
