### ISSUE TITLE
Find-DbaSqlInstance and how to dig deeper

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2199]
## Feature Request

Have ability to go as deep in finding any server which is linked somehow to our original server in question.
So, if you see any Linked Server, Service Broker Route, AG. Anything else anyone think of?

### Problem to solve
Get as much information as we can from one starting point.

### Additional information
this was from DM conversation with @potatoqualitee on Slack

**Comment by potatoqualitee** [comment]
Thanks, @Zhunya! @nullbind (Scott Sutherland) will be working on this command - he already has it very well mapped out. Scott, I think this recursive check would be fun to slate for perhaps v1.1 if it's not already included in your original markup.

**Comment by potatoqualitee** [comment]
done 🎉
