### ISSUE TITLE
Backup database - 'smart' new features

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#2211]
## Feature Request

- If doing a transaction log backup and LSN chain is not intact switch to do a full backup
- Auto discovery - if set to backup all databases on a server and a new one is found include that

Envisioning scheduling the backup command to run fulls once a week, diffs once a night, trns every hour perhaps, then on the hourly runs if the LSN chain was broken or a new db was found take a full backup. Perhaps some limits on size of db, wouldn't want a busy 2TB database suddenly being backed up in the day.

### Additional information
Adding this to keep track of ideas that were discussed on slack channel.

**Comment by niphlod** [comment]
Add the possibility to change path if the backup "method" changes. I
usually store fulls in a different path than diff and yet another for
incrementals.

Il 08 set 2017 4:27 PM, "Jess Pomfret" <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
We should ensure we don't end up on @spaghettidba's list ;)

https://spaghettidba.com/2017/09/13/expensive-enterprise-backup-tools-a-survival-guide/

**Comment by Stuart-Moore** [comment]
What @potatoqualitee  says. none of those things don't belong in BACKUP function. they belong in a supporting function or set of scripts that people can use.

Small functions that do one properly is a good maxim.

If people really want that sort of thing, then may we branch out into writing some configurations tools using dbatools primitives. Be easy enough to do all of the above by scheduling combinations of Get-DbaDatabase, Test-DbaLsnChain, Backup-DbaDatabase, New-DbaAgent* etc.

**Comment by wsmelton** [comment]
Cleaning up issues...

Someone wants to tackle this can re-open it.
