### ISSUE TITLE
Do we have dbatools for powershell on linux?

### ISSUE THREAD

**Issue by gowtham500** [sqlcollaborative/dbatools#2216]
Do we have dbatools for powershell on linux? If yes, 
1. can you please provide instructions on how to install.
2. Sample scripts for powershell on linux using DBATOOLS

**Comment by wsmelton** [comment]
At this time it would not work on Linux the last I heard because SMO has not been completely ported to Linux.

**Comment by wsmelton** [comment]
Which actually once SMO and .NET are fully ported over to PowerShell Core will begin fully testing dbatools for Linux OS. Until that time though we have not begun to fully support Linux and PowerShell Core.

**Comment by gowtham500** [comment]
Thanks for the reply.
Recently I found .net being moved, but not sure if all nationality is moved.
Thanks for looking into this.

**Comment by wsmelton** [comment]
.NET core is available but not in fully supported (last time I checked). You have to have that installed before you can utilize PS Core on Linux. The main missing piece is SMO which once the [sqltoolsservice](https://github.com/Microsoft/sqltoolsservice) has this working for all the libraries we can start working on dbatools support for Linux full steam.
