### ISSUE TITLE
Replace use of Detailed or Simple parameters

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2217]
To follow standards of current commands any command that currently utilizes `-Detailed` and/or `-Simple` should be replaced to utilize `Select-DefaultView` internal function call. So this would mean the "simple" output would generally become the default properties to output. Then the detailed, if applicable would be obtained by piping to `select *`. In cases where a command only has a detailed and it already utilizes the default view function, just remove the code for the parameter.

Rough draft list of commands found to still have these parameters in use:
_search done via VS Code for text `PARAMETER Detailed`_
- [ ] Find-DbaAgentJob
- [x] Find-DbaDatabase
- [x] Get-DbaClusterActiveNode
- [x] Get-DbaDiskSpace
- [ ] Get-DbaRunningJob.ps1 
- [x] Get-DbaSpConfigure
- [ ] Get-DbaTcpPort
- [x] Repair-DbaServerName
- [x] Test-DbaConnectionAuthSchema
- [x] Test-DbaDatabaseCollation
- [x] Test-DbaDatabaseCompatibility
- [x] Test-DbaDatabaseOwner
- [x] Test-DbaDiskAlignment
- [x] Test-DbaDiskAllocation
- [x] Test-DbaFullRecoveryModel
- [x] Test-DbaJobOwner
- [x] Test-DbaMaxDop
- [x] Test-DbaPowerPlan
- [x] Test-DbaServerName
- [x] Test-DbaTempdbConfiguration
- [x] Test-DbaValidLogin
- [x] Test-DbaVirtualLogFile

Determined by @potatoqualitee and @wsmelton  that this parameter stays
_search done via VS Code for text `PARAMETER Simple`_
~~- [ ] Get-DbaMemoryUsage~~
~~- [ ] Get-DbaStartupParameter~~
~~- [ ] Read-DbaBackupHeader~~
~~- [ ] Test-DbaLogShippingStatus~~

### important [Updated]

The following block needs to be added to the `begin{}` block of the command, if there is not already a begin block then just add it.

```powershell
begin {
    Test-DbaDeprecation -DeprecatedOn 1.0.0 -Parameter Detailed
}
```

Due to how we handle test for parameters we need to make the following adjustments to the commands:
- Alias the Detailed parameter, if possible
- If you cannot alias the parameter then leave it in the param block.
- Update parameter in the help documents to this:
```
.PARAMETER Detailed
    Output all properties, will be deprecated in 1.0.0 release.
```
- You can remove the parameter's references in the examples, and just replace with `| Select-Object *`

The above commands should be addressed in a 1:1 ratio for the PR, meaning one command per PR.

If you are working on commands in the above list, assign yourself to this issue **and** comment to which command you will work on.

**Comment by joshcorr** [comment]
Grabbed Test-DbaValidLogin and submitted Pull Request.

**Comment by joshcorr** [comment]
Working on Find-DbaDatabase next.

**Comment by joshcorr** [comment]
Checked off Repair-DbaServerName and Test-DbaVirtualLogFile as they seem to have already been fixed and have had the parameter removed.

**Comment by joshcorr** [comment]
Working on Test-DbaDatabaseCollation, Test-DbaDiskAllocation, and Test-DbaMaxDop as one Pull since they all have a similar documentation/begin block issue.

**Comment by joshcorr** [comment]
Worked on Get-DbaDiskSpace, Get-DbaSpConfigure, Test-DbaPowerPlan, Test-DbaServerName (and it's reference in Repair-DbaServerName). Going to try and do this as One Pull Request.

**Comment by joshcorr** [comment]
Marked Test-DbaDatabaseCompatibility as Completed as it already has the Test-DbaDeprecation warning in place.

**Comment by joshcorr** [comment]
Working on Get-DbaTcpPort

**Comment by joshcorr** [comment]
Still working on Get-DbaTcpPort 😩

**Comment by potatoqualitee** [comment]
can we plz leave in the 4 simples? 🙏
