### ISSUE TITLE
Review & update comment-based help, other text and style in functions

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#2219]
I'm overdue in opening this issue.

All comment-based help needs to be reviewed for spelling, grammar and other editorial consistency. Longer GPL notice will be replaced with a more succinct version.

Code formatting will also be revised to be consistent across functions (I hope) and text output to the user checked for the same issues comment-based help is.

I've already completed a number of functions but many more remain.

**Comment by niphlod** [comment]
@alevyinroc : can we close this "as part of the ongoing effort to make CBH good" ?
