### ISSUE TITLE
Copy-SqlLogin and Database in Availability Group

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#222]
Testing in lab to implement dbatools and desire was to only copy over logins that were new, so no use of the `-Force` parameter.

I have not looked in detail but there is shared functions erring when trying to create a login that was added to a primary replica on secondaries. Just based on errors it is from the code trying to apply the permissions in the database, which is not going to be allowed if the database is involved in an AG. First guess there just needs to be a check to make sure the database is accessible, like `IsAccessible` or something before trying to apply the permission on the destination.

In the end the login is created, it just errors trying to apply permissions. In the case of an AG, the permissions will be picked up once a failover to that secondary occurs because the login is copied with the same SID.

Exception output log:
[dbatools-exceptions.txt](https://github.com/sqlcollaborative/dbatools/files/491493/dbatools-exceptions.txt)

**Comment by wsmelton** [comment]
The issue is within function `Update-SqlPermissions` of the SharedFunction.ps1.

At line 1499, it simply does `if ($destdb -ne $null)`. Quick fix I think would be to just include a check in the start of that code block of:
`if (!$destdb.IsAccessible)
{
   Write-Output "Database is not accessible. Skipping"
   Continue
}`

**Comment by wsmelton** [comment]
Issue also exist in `Sync-SqlLoginPermissions.ps1`, lines 407 and 483.

You do not see the exception for this unless you use `-SyncOnly` with `Copy-SqlLogin`

**Comment by dansqldba** [comment]
Fixed by #223.
