### ISSUE TITLE
Add tags to the .NOTES section of all comment-based help

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#2220]
`Find-DbaCommand` parses comment-based help for a line starting with `Tags:` which contains a comma-delimited string of words which are tags that have been applied to that function.

Need to:
* Standardize the taxonomy/classification
* Publish the list of tags and their usage
* Apply to each function consistently

Tags will not be applied to functions that are private to other functions.

**Comment by potatoqualitee** [comment]
This is done eh? 🥳  If not, we can create pester tests to detect

**Comment by niphlod** [comment]
yup, in addition, tagging helps building the tag cloud of docs.dbatools.io. It _could_ replace https://dbatools.io/commands/ which is maintained by hand by @ClaudioESSilva

**Comment by potatoqualitee** [comment]
OH!! i love that idea! that's a perfect use of tags!
