### ISSUE TITLE
Get-DbaSqlBuildReference

### ISSUE THREAD

**Issue by kiransqldba** [sqlcollaborative/dbatools#2230]
Get-DbaSqlBuildReference provide all the information except Sql edition.

**Comment by niphlod** [comment]
It's a reference for build number to know if you're "compliant" to whatever SP+CU you wanna deploy on the infrastructure.....not an edition reference. 
Is it really needed ? Not hard at all to pull, just a root property of the SMO.

**Comment by kiransqldba** [comment]
You are right, but it's very helpful to have edition information too.

**Comment by wsmelton** [comment]
I would say this does not need to be added as it is out of spec to the command. If a user wants to have the Edition information added to the output they can easily do that via other methods.

The build information in this command does not pertain to the Edition of SQL Server as already stated.
