### ISSUE TITLE
Test-DbaDbCompression - Arithmetic overflow error converting bigint to data type numeric.

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2231]
## Bug Report
Run Test-DbaDbCompression against database with BLOB tables (755'105,875 MB).
Got this error - Arithmetic overflow error converting bigint to data type numeric.

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): WIndows 10 1703
 - PowerShell Version: 5.1.15063.413
 - SQL Server (Edition|Version): 11.0.6607

one more fragment from $error[0] | select *
```powershell
ScriptStackTrace:
    at Stop-Function, <No file>: line 197
    at Test-DbaDbCompression<Process>, <No file>: line 443
    at <ScriptBlock>, <No file>: line 1
```

**Comment by Zhunya** [comment]
poor report I know...

**Comment by potatoqualitee** [comment]
I think that's enough info 👍

**Comment by Zhunya** [comment]
Problem with implicit conversation in `tmp_cte`
