### ISSUE TITLE
Test-DbaLastBackup - SQL Server cannot process this media family

### ISSUE THREAD

**Issue by cabana1** [sqlcollaborative/dbatools#2232]
## Bug Report
Test-DbaLastBackup doesn't have LiteSpeed restore functionality (or Ola using Litespeed)

### General Troubleshooting steps

- [ x] Verified running latest release of dbatools?
- [ x] Verified errors are not related to permissions?
- [x ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): win 2012 r2
 - PowerShell Version: 4
 - SQL Server (Edition|Version): source 2016, dest 2008r2 (but will be done on all version)

## Steps to Reproduce

Test-DbaLastBackup -SqlInstance '(source),port' -Destination '(destination),port' -DataDirectory S:\Data -LogDirectory T:\TLog

At line:171 char:21
+                     $datatable = $restore.ReadBackupHeader($server)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: The media family on device '(path and database name)_Full_2017-09-13-170505.bak' is incorrectly formed. SQL Server cannot process this media family.
RESTORE HEADERONLY is terminating abnormally.
   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteWithResults(String query)
   at Microsoft.SqlServer.Management.Smo.BackupRestoreBase.ExecuteSqlWithResults(Server server, String cmd)
   at Microsoft.SqlServer.Management.Smo.Restore.ReadBackupHeader(Server srv)
   at CallSite.Target(Closure , CallSite , Object , Object )

## Feature Request

  I would like to be able to test restores of Litespeed backups.
  I have some litespeed backups and some Ola backups.  It would be great if the script could handle either dynamically.   

Here is what a litespeed restore script looks, if it helps:
exec master.dbo.xp_restore_database @database = N'(dbname)' ,
@filename = N'(path)\(dbname)_Full_2017-09-13-170505.bak',
@filenumber = 1,
@with = N'STATS = 10',
@affinity = 0,
@logging = 0

**Comment by cabana1** [comment]
I as able to tell the issue is on line 171 in Read-DbaBackupHeader.ps1.  
                    $datatable = $restore.ReadBackupHeader($server)

It can't read the backup header of the Litespeed backup.  I'm sure the related restore must be different too.

**Comment by Stuart-Moore** [comment]
Yes. Litespeed use their own proprietary format for backups and a compiled
dll via an xp stored procedure to do anything with them.
Last time I checked they didn't have a powershell implementation either.

So we'd need to write lots of string mangling code and invoke-sqlcmd2
statements.

Plus someone would have to provide us with a litespeed license for testing
:)

**Comment by wsmelton** [comment]
@cabana1 At this time we are not supporting 3rd party backup tools. LS is one that creates a proprietary backup format unlike others so we cannot provide any test/sandbox environment to develop. As well, we would not be able to perform any integration testing against it using Appveyor.

Licensing wise with LS you can restore a backup without purchasing any licenses, just have to install LS to have the procs and DLLs available. However, to perform the backup for testing a restore, does require licensing.
