### ISSUE TITLE
error  - Copy-DbaSqlServerAgent : Unable to find type [DbaInstanceParameter]

### ISSUE THREAD

**Issue by earledgar** [sqlcollaborative/dbatools#2233]
i'm getting this error when i run the copy-dbasqlserveragent -source server1 -destination server2

Copy-DbaSqlServerAgent : Unable to find type [DbaInstanceParameter]. Make sure that the assembly that contains this
type is loaded.
At line:1 char:1
+ Copy-DbaSqlServerAgent -Source callisto.enterprise.nacorporation.com -Destinatio ...
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DbaInstanceParameter:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by wsmelton** [comment]
Closing this issue, if you are still receiving this error under the latest release please reopen.
