### ISSUE TITLE
Export-DbaLogin is not filtering databases on -Database parameter

### ISSUE THREAD

**Issue by backintheday41** [sqlcollaborative/dbatools#2238]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
Manufacturer             : Microsoft Corporation
Architecture             : 64-bit
Version                  : 10.0.14393
Build                    : 14393

 - PowerShell Version:                                                                                                                                             
PSVersion                      5.1.14393.1532                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                 
BuildVersion                   10.0.14393.1532                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                         
WSManStackVersion              3.0                                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                                     
SerializationVersion           1.1.0.1

 - SQL Server (Edition|Version): 
Build          : 11.0.6020
NameLevel      : 2012
SPLevel        : {SP3, LATEST}
CULevel        : 
KBLevel        : 3072779

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

When using Export-DbaLogin, the -Database parameter does not filter the results.  Logins for all databases are processed.

### Problem to solve

The output from Export-DbaLogin should relate to only the database(s) noted after the -Database parameter.

### Additional information

I believe the problem may lie in the code where early on the databases to be mapped are first set to the list of all databases, and even though the -Databases parameter is evaluated and that list is set, that list of database is not included in the processing later.  The original list of all databases is processed.  The particular line of code I am referencing is Line 325 where $sourceDb is set.

**Comment by niphlod** [comment]
I recall I already put the hands on this. Will check it and come back.

Il 15 set 2017 5:16 PM, "backintheday41" <notifications@github.com> ha
scritto:

**Comment by niphlod** [comment]
ok, indeed I did. 
@backintheday41 the -Database parameter allows to filter out database-level permissions/roles extraction, not to avoid processing logins that have no database-level permissions/roles. 
I *guess* it could be an enhancement (`-OnlyMappedLogins` ?), but it'll disrupt the current behaviour.

@potatoqualitee , @PowerDBAKlaas , @ClaudioESSilva, @wsmelton  ... opinions ?

**Comment by wsmelton** [comment]
First glance without debugging it or running it...would seem that we simply need to adjust this to filter the right area.

```powershell
if ($userName -notin $DbMapping.LoginName) {
					Write-Message -Level VeryVerbose -Message "Skipping as $userName is not mapped to an user of the databases."
					continue
				}
				$dbs = $sourceLogin.EnumDatabaseMappings()
				# Adding database mappings and securables
				foreach ($db in $dbs) {
					$dbName = $db.dbname
					$sourceDb = $server.Databases[$dbName]
					$dbUserName = $db.username
```

The variable `$DbMapping` seems to hold the list of databases that were passed into `-Database` parameter. So in the `foreach`  at [line 323](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaLogin.ps1#L323) I would think should be filtered based on the databases in `$DBMapping`. So if `-NoDatabases` was specified and `-Database` was then you would filter that `$dbs` to only be the ones in `$DBMapping`.

Again just first glance at it.

**Comment by niphlod** [comment]
that filtering part was added because enumerating was taking a lot of time, but it didn't change the original behaviour: this function exports all logins (unless -Logins or -ExcludeLogins is passed). 
The database filtering part is only used to avoid enumerating database-level permissions, not to filter out logins not mapped to the databases you specify.

**Comment by wsmelton** [comment]
So the help needs to be updated because:

1. All it states for that parameter is the below, which is generic for all the commands. We should be specifying what the parameter actually does since it is obviously not clear.

>The database(s) to process. Options for this list are auto-populated from the server. If unspecified, all databases will be processed.

2. There are no examples showing how to use this parameter in the command...likely just a slip of the mind for the author I guess 😁 

Then as well, how do we add the ability to only export logins for a specific database...I rarely ever export every login on an instance if needed?

**Comment by niphlod** [comment]
"that's how it was supposed to be". 
I asked for @ClaudioESSilva and @potatoqualitee insights exactly for this purpose.

**Comment by potatoqualitee** [comment]
I defer to @ClaudioESSilva - these login commands drive me too crazy ;)

**Comment by backintheday41** [comment]
Thank you all for looking into this!  I really appreciate it.

My specific use-case is that I am refreshing a lower environment database with production. I would like to export the logins and permissions from the lower environment database first before overwriting it with the production database - after which I would like to execute the exported login script to put the lower environment permissions back in place.  Perhaps there is a better way to do this with other dbatools commands?  Maybe even a more comprehensive approach?

I agree that an enhancement for Export-DbaLogin might be that when the -Database parameter and the -Login parameter are used, only logins and database permissions/roles for that database and that login will be scripted.

**Comment by niphlod** [comment]
yeah, right now you'd need to "cheat" with
```
$db = get-dbadatabase -sqlinstance sourceinstance -database userdb1
$logins = ($db.enumloginmappings()) | select -expandproperty LoginName | Where { $_ -ne 'sa' }
export-dbalogin -sqlinstance sourceinstance -database userdb1 -login $logins
```

**Comment by backintheday41** [comment]
The "cheat" you suggested gives the same exact output as the following:

`Export-DbaLogin -SqlInstance sourceinstance -Database userdb1 -Login 'domain\user1','domain\user2','sqluser1','sqluser2','sqluser3' -FilePath C:\output.sql`

The output includes login creations, database user creations, and database-level roles and permissions for the above logins for all databases in the instance.

Again, thanks so much for looking into this!

Seth

**Comment by niphlod** [comment]
Isn't what were you looking for? It's what it'd report if Claudio accepts
the behaviour change

Il 20 set 2017 3:18 PM, "backintheday41" <notifications@github.com> ha
scritto:

**Comment by backintheday41** [comment]
I apologize if I haven't communicated well throughout these comments.

I am not expecting to see any grants related to any other databases except the one I specify.  That is, anything scripted that is related to any other database user creations, or database-level roles and permissions would be more than expected.  I'm still not quite sure I understand the purpose of the -Database parameter if grants are scripted for all databases when only one is specified - except that it seems it is meant to filter out - which you did note earlier.

For all other dbatools commands (that I've used at least), the -Database parameter is meant as an inclusion, so I assumed it would include that in the scripting, and only that.

To be honest, even the purpose of command itself is misleading per the documentation if it "Migrates logins with SIDs, passwords, defaultdb, server roles & securables, _database permissions & securables_, login attributes (enforce password policy, expiration, etc)."

If you're still confused.  No worries, so am I.

**Comment by backintheday41** [comment]
Oh my goodness.  I feel so inadequate as a human being right now.  Directly underneath Export-DbaLogin on the Command Index page of the dbatools website is the command Export-DbaUser which is what I needed.

My apologies.  So other than perhaps clarifying the usage of Export-DbaLogin a little better somehow, I don't know that I have much more to say about it at this point.

Sincerely,
Seth

**Comment by niphlod** [comment]
No problems whatsoever.
Programs need coders AND users. 
If somehow you got yourself "lost in translation" we may be able to help out others in your situation improving only the docs and not the code itself.
To sum up: 
- Export-DbaLogin works at "instance level". The main "filter" is "Login", not "Database". Database is an additional filter to avoid exporting database-level permission for the logins.
- Export-DbaUser works at "database level". The main "filter" is "Database"

Both export SOME data about the roles of a user in the database. Export-DbaLogin does it so for every mapped login to an user. Export-DbaUser is not aware of any login, because it works at a lower level.
