### ISSUE TITLE
Export-DbaSpConfigure.ps1

### ISSUE THREAD

**Issue by SQLUnderworld** [sqlcollaborative/dbatools#2239]
### Additional information

Is it really necessary to call sp_configure? Couldn't master.sys.configurations just be queried instead?

**Comment by wsmelton** [comment]
(1) Yes in order to support those that still run SQL Server 2005. 

(2) Not if you are running SQL Server 2005 :grin:

**Comment by wsmelton** [comment]
> Couldn't master.sys.configurations just be queried instead?

The intent of this function is to export the configuration as a script to allow you to save it as version control, or be able to easily have a script to quick set another instance or something...which is what it does. You cannot take the output of `master.sys.configurations` and just "import" that to another SQL Server, you have to run `sp_configure` in T-SQL. So a correction to my previous answer on this question, it would be no regardless of SQL Server version.

**Comment by niphlod** [comment]
@wsmelton : I feel like this can be closed but you're the absolute master of *-dbaspconfigure .... I'll leave you the option ^_^
