### ISSUE TITLE
Make Write-Message -WhatIf aware

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2252]
User had an issue where Write-Message was messing up with -WhatIf. Turns out it was trying to write a string that couldn't exist yet. Can we please make Write-Message whatif aware so that it doesn't log stuff.. or is there a better way to go about it like prepending WhatIf to the log?

**Comment by IISResetMe** [comment]
@potatoqualitee @FriedrichWeinmann mind if I grab this?

**Comment by potatoqualitee** [comment]
That'd be great! thank youuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu!

**Comment by FriedrichWeinmann** [comment]
Closing this issue, as likely fixed and not enough information to hunt it down if it isn't
