### ISSUE TITLE
Invoke-DbaLogShipping error

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#2255]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools? 0.9.46
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 2016 Server
 - PowerShell Version: 5.0
 - SQL Server (Edition|Version): 2014 Standard Edition sp2

## Steps to Reproduce
Executing the Invoke-DBALogShipping to setup a new log shipping instance.

### Problem to solve
The secondary database setup is not getting created correctly.  If I go into the primary database and click on the ... button for the secondary database configuration, I receive an error.  I think the issue may be in New-DbaLogShippingSecondaryPrimary.ps1.

I think the @copy_job_id and @restore_job_id need to have the OUTPUT keyword at the end.  

200 	# Set up the query 
201 	$Query = " 
202         DECLARE @LS_Secondary__CopyJobId AS uniqueidentifier 
203         DECLARE @LS_Secondary__RestoreJobId	AS uniqueidentifier 
204         DECLARE @LS_Secondary__SecondaryId AS uniqueidentifier  
205         EXEC master.dbo.sp_add_log_shipping_secondary_primary  
206                 @primary_server = N'$PrimaryServer'  
207                 ,@primary_database = N'$PrimaryDatabase'  
208                 ,@backup_source_directory = N'$BackupSourceDirectory'  
209                 ,@backup_destination_directory = N'$BackupDestinationDirectory'  
210                 ,@copy_job_name = N'$CopyJob'  
211                 ,@restore_job_name = N'$RestoreJob'  
212 				,@file_retention_period = $FileRetentionPeriod  
213 				,@copy_job_id = @LS_Secondary__CopyJobId 
214                 ,@restore_job_id = @LS_Secondary__RestoreJobId 
215                 ,@secondary_id = @LS_Secondary__SecondaryId OUTPUT "

**Comment by niphlod** [comment]
fixed via e9c03f5 and fa6baec
