### ISSUE TITLE
Test-DbaLastBackup LSN broken

### ISSUE THREAD

**Issue by beanbrown** [sqlcollaborative/dbatools#2258]
## Bug Report
This may be related to #2182, same error message about LSN broken.

**Comment by Stuart-Moore** [comment]
Hi,
Can you try again please and see if #2182 did fix the issue or if we have another outstanding issue.

Cheers
Stuart

**Comment by Stuart-Moore** [comment]
Closing as no update. Assuming #2182 did fix it.
