### ISSUE TITLE
TestDBA-SPN Feature Request

### ISSUE THREAD

**Issue by banditkd** [sqlcollaborative/dbatools#2261]
### Problem to solve
Can test-dbaspn be modified to work with Managed Service Accounts. I believe the issue is that when the command see a $ at the end of the service account it assumes that it is a computer object rather than a service account.

### Additional information
if I try and get the spn's for a test server with 3 instances I get this

test-dbaspn -ComputerName TestSQL1
WARNING: [Test-DbaSpn][11:29:45] SQL Service account not found. Results may not be accurate.

ComputerName           : 
InstanceName           : SQL2012
SqlProduct             : SQL Server 2012 Developer Edition (64-bit)
InstanceServiceAccount : TestDomain\SQLSVC001$
RequiredSPN            : MSSQLSvc/TestSQL1.TestDomain.lan:SQL2012
IsSet                  : False
Cluster                : False
TcpEnabled             : True
Port                   : 
DynamicPort            : False
Warning                : None
Error                  : None
Credential             : 

WARNING: [Test-DbaSpn][11:29:45] SQL Service account not found. Results may not be accurate.
ComputerName           : 
InstanceName           : SQL2014
SqlProduct             : SQL Server 2014 Developer Edition (64-bit)
InstanceServiceAccount : TestDomain\SQLSVC002$
RequiredSPN            : MSSQLSvc/TestSQL1.TestDomain.lan:SQL2014
IsSet                  : False
Cluster                : False
TcpEnabled             : True
Port                   : 
DynamicPort            : False
Warning                : None
Error                  : None
Credential             : 

WARNING: [Test-DbaSpn][11:29:45] SQL Service account not found. Results may not be accurate.
ComputerName           : 
InstanceName           : SQL2016
SqlProduct             : SQL Server 2016 Developer Edition (64-bit)
InstanceServiceAccount : TestDomain\SQLSVC003$
RequiredSPN            : MSSQLSvc/TestSQL1.TestDomain.lan:SQL2016
IsSet                  : False
Cluster                : False
TcpEnabled             : True
Port                   : 
DynamicPort            : False
Warning                : None
Error                  : None
Credential             : 

WARNING: [Test-DbaSpn][11:29:45] SQL Service account not found. Results may not be accurate.
ComputerName           : 
InstanceName           : SQL2012
SqlProduct             : SQL Server 2012 Developer Edition (64-bit)
InstanceServiceAccount : TestDomain\SQLSVC001$
RequiredSPN            : MSSQLSvc/TestSQL1.TestDomain.lan:54803
IsSet                  : False
Cluster                : False
TcpEnabled             : True
Port                   : 54803
DynamicPort            : True
Warning                : Dynamic port is enabled
Error                  : None
Credential             : 

WARNING: [Test-DbaSpn][11:29:45] SQL Service account not found. Results may not be accurate.
ComputerName           : 
InstanceName           : SQL2014
SqlProduct             : SQL Server 2014 Developer Edition (64-bit)
InstanceServiceAccount : TestDomain\SQLSVC002$
RequiredSPN            : MSSQLSvc/TestSQL1.TestDomain.lan:54877
IsSet                  : False
Cluster                : False
TcpEnabled             : True
Port                   : 54877
DynamicPort            : True
Warning                : Dynamic port is enabled
Error                  : None
Credential             : 

WARNING: [Test-DbaSpn][11:29:45] SQL Service account not found. Results may not be accurate.
ComputerName           : 
InstanceName           : SQL2016
SqlProduct             : SQL Server 2016 Developer Edition (64-bit)
InstanceServiceAccount : TestDomain\SQLSVC003$
RequiredSPN            : MSSQLSvc/TestSQL1.TestDomain.lan:54967
IsSet                  : False
Cluster                : False
TcpEnabled             : True
Port                   : 54967
DynamicPort            : True
Warning                : Dynamic port is enabled
Error                  : None
Credential             : 

I have also tested Get-DBASPN and it seems to have problems when using the ComputerName parameter

Get-DbaSpn -ComputerName TestSQL1
WARNING: [Test-DbaSpn][11:46:44] SQL Service account not found. Results may not be accurate.
WARNING: [Test-DbaSpn][11:46:44] SQL Service account not found. Results may not be accurate.
WARNING: [Test-DbaSpn][11:46:44] SQL Service account not found. Results may not be accurate.
WARNING: [Test-DbaSpn][11:46:44] SQL Service account not found. Results may not be accurate.
WARNING: [Test-DbaSpn][11:46:44] SQL Service account not found. Results may not be accurate.
WARNING: [Test-DbaSpn][11:46:44] SQL Service account not found. Results may not be accurate.

However if I use the AccountName it returns this

get-dbaspn -AccountName TestDomain\SQLSVC003$

Input        : TestDomain\SQLSVC003$
AccountName  : TestDomain\SQLSVC003$
ServiceClass : MSSQLSvc
Port         : 54967
SPN          : MSSQLSvc/TestSQL1.TestDomain.lan:54967

Input        : TestDomain\SQLSVC003$
AccountName  : TestDomain\SQLSVC003$
ServiceClass : MSSQLSvc
Port         : 
SPN          : MSSQLSvc/TestSQL1.TestDomain.lan:SQL2016

**Comment by niphlod** [comment]
argh, I don't have MSAs or gMSAs around to test. Would anyone be willing to do a few trials to see what needs to be fixed ?

**Comment by banditkd** [comment]
of course I can help out. I'll spin up some instances on Azure. Getting a dab hand at it as we are switch all our instances over to MSA's :)

**Comment by Redwood001** [comment]
Hi @banditkd

Could you also please est gMSA we migrate our MSA to gMSA in November of this year.

**Comment by banditkd** [comment]
Hi @Redwood001 yes of course. We are using gmsa for all our 2016 instances so I would plan to cover both.

**Comment by niphlod** [comment]
Can you hit me on slack so we can arrange a timeframe to run a few tests?

Il 16 ott 2017 9:31 PM, "Mark Kaveney-Davis" <notifications@github.com> ha
scritto:

Hi @Redwood001 <https://github.com/redwood001> yes of course. We are using
gmsa for all our 2016 instances so I would plan to cover both.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/2261#issuecomment-337008536>,
or mute the thread
