### ISSUE TITLE
Piping output from Get-DbaBackupHistory to Restore-DbaDatabase fails

### ISSUE THREAD

**Issue by Bendy22** [sqlcollaborative/dbatools#2264]
The below command does not successfully restore a database. 

`Get-DbaBackupHistory -SqlInstance $sourceinstance -Database $database -Last | Restore-DbaDatabase -SqlInstance $destinationinstance -NoRecovery -Verbose`

For every file it finds in the chain, the below two messages are returned:

`VERBOSE: [Restore-DbaDatabase][09:43:13] Unverified input, full scans`
`VERBOSE: [Restore-DbaDatabase][09:43:13] type = string[]`

### General Troubleshooting steps

- [X] Verified running latest release of dbatools? 0.9.48
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Windows Server 2012 R2)
 - PowerShell Version: 5.1.14409.1012
 - SQL Server (Source - SQL 2012 Enterprise | Destination - SQL 2016 Enterprise)

## Steps to Reproduce
Existing source instance with backup chain that includes FULL -> DIFF -> LOGs. Destination with plenty of space.

Command:
Get-DbaBackupHistory -SqlInstance $sourceinstance -Database $database -Last -Verbose | Restore-DbaDatabase -SqlInstance $destinationinstance -NoRecovery -Verbose

Output:

`VERBOSE: [Get-DbaBackupHistory][09:57:28] Connecting to CT11A0401DB01
VERBOSE: [Get-DbaBackupHistory][09:57:29] Connecting to CT11A0401DB01
VERBOSE: [Get-DbaBackupHistory][09:57:30] Processing CorpBimbo_Test_c0401
VERBOSE: [Get-DbaBackupHistory][09:57:30] Executing sql query
VERBOSE: [Get-DbaBackupHistory][09:57:30] Processing as Grouped output
VERBOSE: [Get-DbaBackupHistory][09:57:30] 1 result-groups found
VERBOSE: [Get-DbaBackupHistory][09:57:30] Connecting to CT11A0401DB01
VERBOSE: [Get-DbaBackupHistory][09:57:30] Processing CorpBimbo_Test_c0401
VERBOSE: [Get-DbaBackupHistory][09:57:30] Executing sql query
VERBOSE: [Get-DbaBackupHistory][09:57:30] Processing as Grouped output
VERBOSE: [Get-DbaBackupHistory][09:57:30] 1 result-groups found
VERBOSE: [Get-DbaBackupHistory][09:57:30] Valid Differential backup 
VERBOSE: [Get-DbaBackupHistory][09:57:30] Connecting to CT11A0401DB01
VERBOSE: [Get-DbaBackupHistory][09:57:30] Executing sql query
VERBOSE: [Get-DbaBackupHistory][09:57:30] Processing as Grouped output
VERBOSE: [Get-DbaBackupHistory][09:57:30] 54 result-groups found
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:30] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:30] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Unverified input, full scans
VERBOSE: [Restore-DbaDatabase][09:57:31] type = string[]
VERBOSE: [Restore-DbaDatabase][09:57:31] Remote server, checking folders
VERBOSE: [Restore-DbaDatabase][09:57:31] sorting uniquely
VERBOSE: [Get-FilteredRestoreFile][09:57:31] Read File headers (Read-DBABackupHeader)
VERBOSE: [Get-FilteredRestoreFile][09:57:37] 0 Files to filter
VERBOSE: [Get-FilteredRestoreFile][09:57:37] 0 database to process
VERBOSE: [Restore-DbaDatabase][09:57:37] 0 dbs to restore`

**Comment by Bendy22** [comment]
[dbatoolslog.txt](https://github.com/sqlcollaborative/dbatools/files/1317969/dbatoolslog.txt)

**Comment by Bendy22** [comment]
@LeedsDBA told me to add the -TrustDbBackupHistory parameter to Restore-DbaDatabase which allows this to work. Thanks!

**Comment by potatoqualitee** [comment]
@Stuart-Moore - would it be possible to perhaps prompt (and bypass the prompt too) the user to trust the backup history if stuff is received but 0 databases are found?
