### ISSUE TITLE
Copy-DbaSsisCatalog fails when only one SSIS service is running on destination server

### ISSUE THREAD

**Issue by coloradotechie** [sqlcollaborative/dbatools#2278]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?  (Downloaded and installed on 9/20/2017 via 
`
Invoke-Expression (Invoke-WebRequest -UseBasicParsing https://dbatools.io/in)
`

- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Windows Server 2012 R2): 
 - PowerShell Version: 

```
PS C:\Windows\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

 - SQL Server (SQL 2016|13.0.4451): 

## Steps to Reproduce

I only have one SSIS instance running, it appears that the `Copy-DbaSsisCatalog` function calls the `Get-RemoteIntegrationService` function... and `Get-RemoteIntegrationService` calls `Get-DbaSqlService -ComputerName $Computer | Where-Object Servicename -like "MsDts*"` ... and it is erroring out when `$result.Count -gt 0` fails (line 113 on https://github.com/sqlcollaborative/dbatools/blob/master/functions/Copy-DbaSsisCatalog.ps1)

I think line 113 fails because only one object is returned, and thus it isn't a collection? (And thus the .Count property is empty?)

Changing line 113 solved it for me:

```
#Old Line 113
if ($result.Count -gt 0) {
#New Line 113:
if ($result) {
```

 - [x] Attach any screenshots (if possible/allowed)
Screenshot of error:
![image](https://user-images.githubusercontent.com/1759990/30712223-87dfaf70-9ec8-11e7-8740-8c9bf2fdea47.png)

Screenshot of related lines from Copy-DbaSsisCatalog:
![image](https://user-images.githubusercontent.com/1759990/30712333-f4a0aa2e-9ec8-11e7-992a-9e74fca87c38.png)

### Problem to solve
I think the `$result = Get-DbaSqlService -ComputerName $Computer | Where-Object Servicename -like "MsDts*"` call might need to be changed to `Get-DbaSqlService -Type SSIS` (however, my testing shows the same issue).

In the end, it appears that `$result = Get-DbaSqlService -ComputerName $Computer | Where-Object Servicename -like "MsDts*"` has a value, the the .count property is empty when $result is only one object.

**Comment by nvarscar** [comment]
Fixed.
