### ISSUE TITLE
Copy-DBAAgentJob fails to copy job dependent upon a proxy that does exist on destination

### ISSUE THREAD

**Issue by nmacehiter** [sqlcollaborative/dbatools#2284]
Please see relevant sections of the log below:

VERBOSE: [Copy-DbaAgentProxyAccount][15:32:12] Copying server proxy account CopyBackupProxy
VERBOSE: [Copy-DbaAgentProxyAccount][15:32:12] Copying server proxy account CopyBackupProxy
SourceServer      : inf-sql01
SourceServer      : inf-sql01
DestinationServer : inf-sql02
DestinationServer : inf-sql02
Name              : CopyBackupProxy
Name              : CopyBackupProxy
Type              : ProxyAccount
Type              : ProxyAccount
Status            : Successful
Status            : Successful
DateTime          : 2017-09-21 15:32:12.740
DateTime          : 2017-09-21 15:32:12.740
...
...
VERBOSE: [Copy-DbaAgentJob][15:32:15] Working on job: DBM - DatabaseBackup - SYSTEM_DATABASES - FULL - 0500
VERBOSE: [Copy-DbaAgentJob][15:32:15] Working on job: DBM - DatabaseBackup - SYSTEM_DATABASES - FULL - 0500
SourceServer      : inf-sql01
SourceServer      : inf-sql01
DestinationServer : inf-sql02
DestinationServer : inf-sql02
Name              : DBM - DatabaseBackup - SYSTEM_DATABASES - FULL - 0500
Name              : DBM - DatabaseBackup - SYSTEM_DATABASES - FULL - 0500
Status            : Skipped
Status            : Skipped
Notes             : Job is dependent on proxy C
Notes             : Job is dependent on proxy C
DateTime          : 2017-09-21 15:32:15.146
DateTime          : 2017-09-21 15:32:15.146

Running copy-sqljob after running Start-DBAMigration successfully copied the job
SourceServer      : inf-sql01
DestinationServer : inf-sql02
Name              : DBM - DatabaseBackup - SYSTEM_DATABASES - FULL - 0500
Status            : Successful
Notes             :
DateTime          : 2017-09-21 16:32:42.780

**Comment by wsmelton** [comment]
@nmacehiter just to clarify that I can duplicate the same situation can you provide a script of the proxy and job? (you can cleanse the names if needed)

**Comment by wsmelton** [comment]
As well, did you use `Start-DbaMigration` for this process?

**Comment by nmacehiter** [comment]
# Proxy Script

USE [msdb]
GO

/****** Object:  ProxyAccount [CopyBackupProxy]    Script Date: 9/24/2017 9:04:31 AM ******/
EXEC msdb.dbo.sp_add_proxy @proxy_name=N'CopyBackupProxy',@credential_name=N'BackupCopyUser', 
		@enabled=1
GO

EXEC msdb.dbo.sp_grant_proxy_to_subsystem @proxy_name=N'CopyBackupProxy', @subsystem_id=3
GO

# Job

USE [msdb]
GO

/****** Object:  Job [DBM - DatabaseBackup - SYSTEM_DATABASES - FULL - 0500]    Script Date: 9/24/2017 9:05:55 AM ******/
BEGIN TRANSACTION
DECLARE @ReturnCode INT
SELECT @ReturnCode = 0
/****** Object:  JobCategory [Database Maintenance]    Script Date: 9/24/2017 9:05:55 AM ******/
IF NOT EXISTS (SELECT name FROM msdb.dbo.syscategories WHERE name=N'Database Maintenance' AND category_class=1)
BEGIN
EXEC @ReturnCode = msdb.dbo.sp_add_category @class=N'JOB', @type=N'LOCAL', @name=N'Database Maintenance'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback

END

DECLARE @jobId BINARY(16)
EXEC @ReturnCode =  msdb.dbo.sp_add_job @job_name=N'DBM - DatabaseBackup - SYSTEM_DATABASES - FULL - 0500', 
		@enabled=1, 
		@notify_level_eventlog=2, 
		@notify_level_email=0, 
		@notify_level_netsend=0, 
		@notify_level_page=0, 
		@delete_level=0, 
		@description=N'Source: https://ola.hallengren.com', 
		@category_name=N'Database Maintenance', 
		@owner_login_name=N'sa', @job_id = @jobId OUTPUT
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
/****** Object:  Step [DatabaseBackup - SYSTEM_DATABASES - FULL]    Script Date: 9/24/2017 9:05:55 AM ******/
EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'DatabaseBackup - SYSTEM_DATABASES - FULL', 
		@step_id=1, 
		@cmdexec_success_code=0, 
		@on_success_action=3, 
		@on_success_step_id=0, 
		@on_fail_action=4, 
		@on_fail_step_id=3, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'CmdExec', 
		@command=N'sqlcmd -E -S $(ESCAPE_SQUOTE(SRVR)) -d master -Q "EXECUTE [dbo].[DatabaseBackup] @Databases = ''SYSTEM_DATABASES'', @Directory = N''D:\sqlbackups'', @BackupType = ''FULL'', @Verify = ''Y'', @Compress = ''Y'', @CleanupTime = 504, @CleanupMode = ''AFTER_BACKUP'', @CheckSum = ''Y'', @LogToTable = ''Y''" -b', 
		@output_file_name=N'$(ESCAPE_SQUOTE(SQLLOGDIR))\DatabaseBackup_$(ESCAPE_SQUOTE(JOBID))_$(ESCAPE_SQUOTE(STEPID))_$(ESCAPE_SQUOTE(STRTDT))_$(ESCAPE_SQUOTE(STRTTM)).txt', 
		@flags=0
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
/****** Object:  Step [Execute Copy Files Scheduled Task]    Script Date: 9/24/2017 9:05:55 AM ******/
EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'Execute Copy Files Scheduled Task', 
		@step_id=2, 
		@cmdexec_success_code=0, 
		@on_success_action=1, 
		@on_success_step_id=0, 
		@on_fail_action=4, 
		@on_fail_step_id=3, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'CmdExec', 
		@command=N'schtasks /Run /TN "Copy sqlbackups inf-sqlsvr01 to inf-backupsvr01"', 
		@flags=0, 
		@proxy_name=N'CopyBackupProxy'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
/****** Object:  Step [Failure Email Notification]    Script Date: 9/24/2017 9:05:55 AM ******/
EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'Failure Email Notification', 
		@step_id=3, 
		@cmdexec_success_code=0, 
		@on_success_action=2, 
		@on_success_step_id=0, 
		@on_fail_action=2, 
		@on_fail_step_id=0, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'TSQL', 
		@command=N'DECLARE @subject NVARCHAR(200)
DECLARE @jobname NVARCHAR(128)
DECLARE @body NVARCHAR(1000)
DECLARE @recipients NVARCHAR(200)

SELECT @jobname = name
FROM msdb..sysjobs
WHERE job_id = $(ESCAPE_NONE(JOBID))

SELECT @recipients = email_address 
from msdb..sysoperators
where name = ''SQLAlerts''

SET @subject = ''SharedSQL Job Failed - ''+ @jobname
SET @body = ''Job ''+ @jobname + '' has failed to complete''

EXEC msdb.dbo.sp_send_dbmail @profile_name = ''EmailAlerts'', @recipients = @recipients, @body = @body, @subject = @subject
', 
		@database_name=N'master', 
		@flags=0
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_update_job @job_id = @jobId, @start_step_id = 1
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_add_jobschedule @job_id=@jobId, @name=N'Sunday @5am', 
		@enabled=1, 
		@freq_type=8, 
		@freq_interval=1, 
		@freq_subday_type=1, 
		@freq_subday_interval=0, 
		@freq_relative_interval=0, 
		@freq_recurrence_factor=1, 
		@active_start_date=20170716, 
		@active_end_date=99991231, 
		@active_start_time=50000, 
		@active_end_time=235959, 
		@schedule_uid=N'16e3dd8b-4ee2-4b9b-8135-261f30bdf042'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_add_jobserver @job_id = @jobId, @server_name = N'(local)'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
COMMIT TRANSACTION
GOTO EndSave
QuitWithRollback:
    IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION
EndSave:

GO

**Comment by nmacehiter** [comment]
As I indicated above I did use Start-DbaMigration which uses Copy-DbaAgentJob. When I ran copy-sqljob it worked without problems, suggesting that the problem lies with Copy-DbaAgentJob
