### ISSUE TITLE
Test-DbaLastBackup Read from Folder

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#2285]
## Feature Request

Instead of the function reading the source msdb, could it be added to read from a folder structure to get the full backup and run the test from their?

**Comment by potatoqualitee** [comment]
hey @gbargsley - is it not getting the last backup in your environment? If it is and you want it from another folder, that'd likely be out of scope but within scope for a new command `Test-DbaDbBackup`

**Comment by gbargsley** [comment]
It is and I just checked the verbose output and see what the function is doing.  I still think reading from folder might be a good option since I might not want this traffic hitting my production msdb to build the restore chain.

**Comment by Stuart-Moore** [comment]
`Gci c:\Gbarglseys\backups -recurse | Restore-DbaDatabase -sqlinstance someserver `

Does what you're asking. Scans all the backups in a group of folders, and restores every database it finds in there to it's latest point in time. Feel free to add other Restore-DbaDatabase parameters to emulate the other Test-DbaLastBackup features
