### ISSUE TITLE
Test-DbaLastBackup Apply Full/Diff/Tlog

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#2286]
## Feature Request

Is it possible to extend the test to diff and tlog backups.  While testing the full is good, if a diff or tlog chain is broken or corrupt the backups are not truly good.  We have a TSQL solution that will restore the full and do checkdb and then do the full / diff then do the checkdb.  Final test is full / diff / random tlog date and time for a PIT restore and then apply all tlogs to get to that PIT.

**Comment by niphlod** [comment]
It's already doing it, why should be there a switch to ignore incrementals?

Il 22 set 2017 1:44 PM, "Garry Bargsley" <notifications@github.com> ha
scritto:
