### ISSUE TITLE
0.9.52 install fails

### ISSUE THREAD

**Issue by cabana1** [sqlcollaborative/dbatools#2289]
## Bug Report
0.9.52 install fails.  Still on older version 0.9.34.
### General Troubleshooting steps

- [ ] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?  run as admin
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 2012 r2
 - PowerShell Version: 4
 - SQL Server (Edition|Version): source 2016, dest 2008r2 (but will be done on all version)

## Steps to Reproduce
Install-Module -Name dbatools -Force

 - [ ] Attach any screenshots (if possible/allowed)
 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

[dbatools_952.txt](https://github.com/sqlcollaborative/dbatools/files/1324627/dbatools_952.txt)

**Comment by potatoqualitee** [comment]
Thanks for the report, @cabana1! @FriedrichWeinmann or @zippy1981 - can you take a look at the log? Looks VS or library related.

**Comment by FriedrichWeinmann** [comment]
Hi Chrissy,

found the issue. Basically, that version doesn't have the assembly used for the tests library.
For some reason it appears to execute the build process as part of the install module process, possibly during the validation process, probably an old version of the package manager.
Doesn't affect installed or copied versions, as the libraries come pre-compiled and the module doesn't try to import the test library. We can change this behavior in a configuration setting, so the test library will only be compiled when run against appveyor or a user opts in.

In the mean time, until that's implemented, alternative means of installing the module should work well for @cabana1 

Cheers

**Comment by cabana1** [comment]
I was able to load the newest version by doing this:
Install-Module -Name dbatools -RequiredVersion 0.9.56 -Force

Thanks!
