### ISSUE TITLE
New Commands: Enable/Disable-DbaTraceFlag

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2299]
### Problem to solve

Need to have a command that you can easily enable or disable a global trace flag on a single or multiple instances.

**Comment by potatoqualitee** [comment]
😍

**Comment by tonyfountain** [comment]
I actually have a script for that already.  It enables globally and sets the registry settings.  I can fix it up to adhere to your coding requirements and share it.

**Comment by wsmelton** [comment]
These would only pertain to setting them globally in T-SQL sessions, not as startup parameters. We already have a command that adjusts the startup parameters.

**Comment by tonyfountain** [comment]
Shaun that's fine, I can yank out the other stuff.

**Comment by wsmelton** [comment]
All yours then...if you need help with PR submittal or getting setup just hit us up on Slack.

**Comment by Stuart-Moore** [comment]
Is this different to PR2345?

**Comment by gbargsley** [comment]
I just did this last week.  To bad I don't know how to link an issue to a PR.

**Comment by wsmelton** [comment]
Ah, didn't see that PR.

@gbargsley you just use "fix", "fixes", "fixed" and then "#<PR number>" and it will link to that. (e.g #2345 )

**Comment by wsmelton** [comment]
That is to say, you can add those keywords in a commit message or the PR itself. If you add them in a commit message it is supposed to close the associated issue when it gets merged into the master branch.

**Comment by potatoqualitee** [comment]
closed as fixed 😍
