### ISSUE TITLE
No Full backup found to anchor the restore

### ISSUE THREAD

**Issue by tonyfountain** [sqlcollaborative/dbatools#2306]
## Bug Report (or possibly me just messing things up :))

Trying to use modified results from Get-DbaBackupHistory piped to Restore-DbaDatabase and receive error "WARNING: [Get-FilteredRestoreFile][09:45:10] No Full backup found to anchor the restore".  Basically I'm modifying the path and full name properties of the results to represent a location on another server where the files are copied to.

- [Yes - 0.9.54] Verified running latest release of dbatools? 
- [Yes - I am sysadmin] Verified errors are not related to permissions?
- [Yes] Can duplicate in new/fresh PowerShell.exe session? Yes.

**### Version Information**
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5.1.15063.608
 - SQL Server (Edition|Version): Microsoft SQL Server 2012 Enterprise Edition: Core-based Licensing (64-bit) / SP3 / CU10

**## Steps to Reproduce**
Testing script attached (Test DBATools.io.ps1)

**- [N/A ] Attach any screenshots (if possible/allowed)**
**- [Yes] Attach logs generated by dbatools (`Get-DbatoolsLog`)**
9/25/2017 10:00:05 AM, Get-FilteredRestoreFile, Exception, Microsoft.PowerShell.Commands.GroupInfo, No Full backup found to anchor the restore

**- [Yes - but modified to protect the innocent] Attach output from PowerShell console (if possible/allowed)**
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<server name>$<instance name>_<database name>_FULL_20170924_040000.bak
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<server name>$<instance name>_<database name>_DIFF_20170925_040001.bak
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925080001.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925081501.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925083001.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925084501.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925090000.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925091501.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925093000.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925094500.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925100001.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925101500.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925103001.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925104500.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925110001.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925111500.trn
VERBOSE: [Restore-DbaDatabase][10:00:04] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:04] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925113001.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925114501.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925120000.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925121501.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925123000.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925124500.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925130001.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925131500.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925133001.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Trust Database Backup History Set
VERBOSE: [Restore-DbaDatabase][10:00:05] adding BackupPath - <drive>:\<mount point><share and path>\<database name>_20170925134501.trn
VERBOSE: [Restore-DbaDatabase][10:00:05] Remote server, checking folders
VERBOSE: [Restore-DbaDatabase][10:00:05] sorting uniquely
VERBOSE: [Get-FilteredRestoreFile][10:00:05] Processing trusted backup history
VERBOSE: [Get-FilteredRestoreFile][10:00:05] 26 Files to filter
VERBOSE: [Get-FilteredRestoreFile][10:00:05] 1 database to process
VERBOSE: [Get-FilteredRestoreFile][10:00:05] Find Newest Full backup - <database name>
VERBOSE: dbname = 
WARNING: [Get-FilteredRestoreFile][10:00:05] No Full backup found to anchor the restore
VERBOSE: [Restore-DbaDatabase][10:00:05] 0 dbs to restore

## Feature Request
Pipe modified results of Get-DbaBackupHistory to Restore-DbaDatabase

### Problem to solve
Resolve "No Full backup found to anchor to the restore" error message.
[Test DBATools.io.zip](https://github.com/sqlcollaborative/dbatools/files/1329757/Test.DBATools.io.zip)

**Comment by tonyfountain** [comment]
Actually, not sure if this is a bug or not.  I removed the -TrustBackupHistory switch and it seems to work now.  I do recall adding that in previously to get around another error that was cropping up in a previous version of DBATools.  That must be resolved now.

**Comment by Stuart-Moore** [comment]
Hi,
Been playing with this, I'm not sure it's an issue. 

Restore-DbaDatabase is expecting a proper BackupHistory object (we have our own internal dbatools types), not raw input. Raw is just a bunch of strings, so we parse those as files.

with the BackupHistory object, Fullname is actually a string array. This piece of code (NOT an example of best practice btw!) works for me:

```
$backups = Get-DbaBackupHistory -SqlInstance localhost\sqlexpress2016 -Database restoretimecleanGe -Last

$backups | %{
         $_.Fullname | %{move-item $_ ($_ -replace 'c:\\dbatools\\multi\\','C:\dbatools\rtge\')}
         $_.Fullname = $_.fullname -replace 'c:\\dbatools\\multi\\','C:\dbatools\rtge\'
    }

$backups | Restore-DbaDatabase -SqlInstance localhost\sqlexpress2016 -DatabaseName rtge -DestinationFilePrefix rtge -TrustDbBackupHistory -WithReplace
```

The example there is a striped backup, so it renames all the paths in FullName. I've also tested it with a more traditional single backup file and that works as well.

Feel free to reopen the issue if you believe there's a bug. Or ping me on slack if you want some more info to help with your script.
