### ISSUE TITLE
Database restore fails: The regular expression pattern is not valid.

### ISSUE THREAD

**Issue by uuksu** [sqlcollaborative/dbatools#2313]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System: Windows Server 2012 R2 Datacenter, 6.3 (Build 9600)
 - PowerShell Version: 4.0
 - SQL Server:
 	- Source: SQL Server 2014 Standard (12.0.2548.0)
 	- Destination SQL Server 2014 Developer (12.0.5000.0)

## Steps to Reproduce

Execute command "Start-DbaMigration -Source servername -Destination servername\MSSQLSERVER14DEV -BackupRestore -NetworkShare C:\db"

Execution starts and everything seems to be fine. When database migration start it shows progress bar and backup seems to be succesful. Then database migration fails with message: "

> Migrating databases.
WARNING: [Restore-DbaDatabase][06:32:21] Restore of database1 failed | The regular expression pattern
.MSSQLSERVER\MSSQL\DATA\database1_reference_211_db is not valid.
WARNING: [Copy-DbaDatabase][06:32:21] Failed to restore database1 to servername\MSSQLSERVER14DEV. Aborting routine for
 this database.
SourceServer        : servername
SourceDatabase      : database1
DestinationServer   : servername\MSSQLSERVER14DEV
DestinationDatabase : database1
Type                : Database (BackupRestore).
Status              : Failed
Notes               : Failed to restore database.
DateTime            : 2017-09-26 06:32:17.582

> WARNING: [Backup-DbaDatabase][06:32:21] Backup Failed:  Exception calling "SqlBackup" with "1" argument(s): "Backup
failed for Server 'servername'. "
WARNING: [Copy-DbaDatabase][06:32:21] Backup Failed. Does SQL Server account NT Service\MSSQLSERVER have access to
Aborting routine for this database.
SourceServer        : servername
SourceDatabase      : database2
DestinationServer   : servername\MSSQLSERVER14DEV
DestinationDatabase : database2
Type                : Database (BackupRestore).
Status              : Failed
Notes               : Backup failed. Verify service account access to C:\db
DateTime            : 2017-09-26 06:32:21.450

After this no databases have been migrated. "C:\db" folder shows three files:

> database1_201709260630-1-of-3.bak
> database1_201709260630-2-of-3.bak
> database1_201709260630-3-of-3.bak
> 

Attached log file with few sequential tries.

[dbatools.log](https://github.com/sqlcollaborative/dbatools/files/1332089/dbatools.log)

**Comment by Stuart-Moore** [comment]
@uuksu  - do your data and log files have extensions? I can replicate if I try to copy a db without them, otherwise it's all good for me.

Don't think we envisioned this. But if that is the case it's something we need to cope with, so I'll look at a fix.

**Comment by uuksu** [comment]
Actually yes, it seems so. Under \MSSQL\DATA I have "Gateware_reference_211_db" and "Gateware_reference_211_dblog" without any extensions just like you doubt.

**Comment by Stuart-Moore** [comment]
Thanks for confirming. I've just pushed the fix into the Development branch. So if you want it now you can pull that, or I expect it'll be pushed into master pretty soon if you want to want for the 'prod' release

**Comment by scatmull** [comment]
I can confirm this fixed our issue and we were able to backup/restore our filestream enabled databases.  Thanks for the quick fix!  It kept our sprint on track.  I love dbatools!
