### ISSUE TITLE
Reported issue with Copy-DbaDatabaseMail

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2315]
User reports the following which suggests a logic issue within the script.

So i started afresh with no accounts on server one and no accounts on server two
I then create one account on Server One and use the following command to sync to Server Two: Copy-DbaDatabaseMail -Source Blah3\DBA_TEST -Destination Blah4\DBA_TEST
it copies over my profile with no problems, including the correct SMTP server name
but if i create another account, and sync that across using the same command, i get a warning in powershell:
WARNING: [Copy-DbaDatabaseMailServer][11:28:28] Mail server smtp.blah.com exists at destination. Use -Force to drop and migrate.

SourceServer   : Blah3\DBA_TEST
DestinationServer : Blah4\DBA_TEST
Name       : smtp.blah.com
Type       : Mail Server
Status      : Skipped
DateTime     : 2017-09-26 11:28:28.296

it creates my second account one the destination server, but for smtp name it uses the actual sql server name instead of smtp.blah.com

so it's almost as if it's treating the smtp server name as a shared object

**Comment by wsmelton** [comment]
I'm not able to duplicate this issue.

**Comment by potatoqualitee** [comment]
cant repro maybe this is an issue with dual loading?
