### ISSUE TITLE
Invoke-DbaDatabaseClone, edition check

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#2325]
## Bug Report
Invoke-DbaDatabaseClone checks just for version -gt 2014SP2 but, actually, for the 2016 version, the feature is unavailable till 2016SP1.

**Comment by potatoqualitee** [comment]
whyyyy you gotta be so detail orientttted ;) Admittedly, i knew but was lazy 🌜

**Comment by niphlod** [comment]
give it a low prio or a far in the future milestone, but it's still a bug ...

**Comment by niphlod** [comment]
btw, that's exactly the reason why appveyor fails miserably ^_^
