### ISSUE TITLE
Connect-DbaInstance: Command name not present

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2354]
## Bug Report

Got warning about command name deprecation `Connect-DbaSqlServer`:

![default](https://user-images.githubusercontent.com/14327077/31004052-5eaeca9e-a4fb-11e7-9d3f-00e30ef48821.png)

But `Connect-DbaInstance` not exist.

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

**Comment by nvarscar** [comment]
It's Get-DbaInstance, from what I see, not Connect. A pity though, I liked how Connect-DbaSqlServer was different from all other Get-* commands, as if it's one of a kind.

**Comment by potatoqualitee** [comment]
hey @Zhunya - did Connect-DbaInstance ever exist? Connect-DbaSqlServer has been renamed to Get-DbaInstance

![image](https://user-images.githubusercontent.com/8278033/31030538-ff3ac53a-a555-11e7-8a72-a0d6fe47353b.png)

**Comment by Zhunya** [comment]
Yeah, beast in small details.Did not saw `Get-` before DbaInstance.

Sorry

**Comment by Zhunya** [comment]
Fixed in #2384
