### ISSUE TITLE
Cannot process argument transformation on parameter 'SqlInstance'. Cannot convert value to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]"

### ISSUE THREAD

**Issue by dmercc** [sqlcollaborative/dbatools#2355]
### General Troubleshooting steps

- [x ] Verified running latest release of dbatools?
0.9.48
- [ x] Verified errors are not related to permissions?
- [x ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Win10 Version 10.0.10586 build 10586
 - PowerShell Version: 5.0.10586.1106
 - SQL Server (Edition|Version): 13.0.4435 (SQL2016 SP1 CU3)

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
This may very well be a beginners error, but i get this error when I try to access a particular instance (we only work with instances, not stand-alone servers).

Get-DbaAgentAlert -SqlServer server\instance

Cannot process argument transformation on parameter 'SqlInstance'. Cannot convert value to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]"

The helppage indicates that this is how you type in server/instance

https://dbatools.io/functions/get-dbaagentalert/

**Comment by Stuart-Moore** [comment]
Are there any 'unusual' characters in this instance's name? The only way I can replicate is with 
`Get-DbaAgentAlert -SqlInstance "local,host\sqlexpress"` and similar. Otherwise it works with all of my instances at work.

**Comment by dmercc** [comment]
Our instancenames our called A,B,C,D etc....
Just one single letter.
A typical cmdlet would look like this:
**Get-DbaAgentAlert -SQLServer SRV1\A**
And that would generate the error i mentionend earlier.

**Comment by potatoqualitee** [comment]
Oh, great report! That is indeed an unhandled name

![image](https://user-images.githubusercontent.com/8278033/31016192-0693cc50-a524-11e7-9041-3e95e97d7499.png)

@FriedrichWeinmann - can you please add support for single letter instances?

**Comment by dmercc** [comment]
Oh, nice to know it's something that can be fixed. Thanks!

**Comment by potatoqualitee** [comment]
Indeed, now fixed in 0.9.61!

![image](https://user-images.githubusercontent.com/8278033/31044442-c646c8a8-a5cf-11e7-840b-fc6b27e61ddf.png)

Thanks for the report

**Comment by potatoqualitee** [comment]
Thank you for your prompt response @FriedrichWeinmann !

**Comment by dmercc** [comment]
Nice and swift work! Thanks
