### ISSUE TITLE
Invoke-DbaLogShipping SQL Server 2005 bugs

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#2358]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 2012R2
 - PowerShell Version: 5.0
 - SQL Server (Edition|Version): SQL Server 2005 (sorry)

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
Not sure if this is a SQL Server 2005 issue or a new configuration issue.  But in the 4 internal scripts New-DbaLogShippingPrimaryDatabase, New-DbaLogShippingPrimarySecondary, New-DbaLogShippingSecondaryDatabase, New-DbaLogShippingSecondaryPrimary, there is a sql parameter @overwrite = 1.  I was getting an error on this option when setting up a new Log Shipping on SQL 2005.  

Second issue with SQL 2005, was in New-DbaLogShippingPrimaryDatabase, there is a call to sp_add_log_shipping_primary_database with @backup_compression.  That didn't exist in 2005, so that was throwing an error even when set to 0.

**Comment by potatoqualitee** [comment]
Thanks fr reporting this. I have noted it to sander
