### ISSUE TITLE
Restore-DbaBackup progress bar information

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2365]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Window Server 2016
 - PowerShell Version: 5.0
 - SQL Server (Edition|Version): 2016 | Enterprise

## Steps to Reproduce
Restore a database to a given instance of SQL Server, is the progress bar supposed to be showing the server I'm restoring to? As-is it shows just "servername"

![image](https://user-images.githubusercontent.com/11204251/31051045-91d951ea-a623-11e7-85a6-1c9fece1797d.png)

**Comment by Stuart-Moore** [comment]
No, it shouldn't . MIssing $ on L359 in Restore-DbFromFilteredArray. Will
submit a PR in a bit to fix.

**Comment by Stuart-Moore** [comment]
Thats now in the dev branch if you want to give it a go. Or it'll probably be in master in  a couple of days at the current rate!

Thanks for spotting that, must have watched that screen 100s of times writing the thing but hadn't spotted it.
