### ISSUE TITLE
Get-FilteredRestoreFile - TLog selection starts too early

### ISSUE THREAD

**Issue by LeeFramp** [sqlcollaborative/dbatools#2374]
Hi,

I found that the list of filtered TLogs produced by Get-FilteredRestoreFile (via Restore-DBADatabase) was including 1 TLog that was too early for our SQL instance to restore.

In the example below (I redacted first portion of LSN for clarity) the filter was including Tlog backups 3, 4 and 5, however SQL can only restore starting with Tlog backup 4.

I fixed this locally by changing filter to specify TLog backup Last LSN must be greater than Full Backup **Last LSN**. Currently the script specifies TLog backup Last LSN must be greater than Full Backup **First LSN**.

  | First LSN | Last LSN
-- | -- | --
Full Backup | 65,600,001 | 74,400,001
  |   |  
Tlog Backup 1 | 46,400,001 | 52,800,001
Tlog Backup 2 | 52,800,001 | 59,200,001
Tlog Backup 3 | 59,200,001 | 65,600,001
Tlog Backup 4 | 65,600,001 | 81,600,001
Tlog Backup 5 | 81,600,001 | 88,000,001

**Comment by nvarscar** [comment]
Awesome finding! Thanks so much for providing LSNs along with the bug report - was able to recreate the scenario in no time! Will be using those LSNs in the pester tests to avoid such cases in future releases.

**Comment by Stuart-Moore** [comment]
@nvarscar  or @LeeFramp  - was this fixed with the PR and merger?

If so I'll close it down.

**Comment by LeeFramp** [comment]
Hi Stuart,

Yes, I'm happy this fixed the issue I was having.

Regards,

Lee Frampton
