### ISSUE TITLE
[New Command] Test-DbaSqlBuild

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2375]
### Problem to solve
Get-DbaSqlBuildReference provides build information and the closest match:
![image](https://user-images.githubusercontent.com/11204251/31129802-443d2070-a81b-11e7-90b6-c0481f2f0ca1.png)

Discussion with the team at Pythian and we'd like to have a command that we can utilize to determine the path to get up to the latest build. 

So my local instance is SQL Server 2014 SP1 + some unknown patch since it does not match what is in our build reference file. The test command would have similar output but include some additional information:

```
SqlInstance: MANATARMS\SQL12
Current Build: 12.0.4237
Current SP: SP1
Current CU: 
Recommended SP: <latest SP number>
Recommended CU: <latest CU to SP, or lastest CU to RTM>
Recommended KB: < could just be comma separated list of KB #s >
```

**Comment by niphlod** [comment]
I think I remember starting a discussion with @ClaudioESSilva  and logging a ticket about what would be needed to test the build.....

**Comment by wsmelton** [comment]
This one: #1919 ? @niphlod

**Comment by niphlod** [comment]
yes! 

BTW: 4237 should be there, but as of right now serves as a good example

**Comment by niphlod** [comment]
in the end we went for a small DSL like "-maxbehind `1SP 2CU`" which should suffice for most scenarios. Will start coding once I get a bit of free time

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/pull/2988
