### ISSUE TITLE
Get-DbaCmObject clarification

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2379]
-- Ignore all $credential refs, just found it sorry! --

![image](https://user-images.githubusercontent.com/8278033/31171320-85080a72-a8ff-11e7-9a19-21c2375d4461.png)

As you can see, not all ErrorActions are available

![image](https://user-images.githubusercontent.com/8278033/31171395-c8a80c46-a8ff-11e7-9cc5-68fa5c9c374b.png)

Ultimately, this happened because i did it against localhost and this namespace, I assume, needs RunAs creds?

**Comment by FriedrichWeinmann** [comment]
Hi Chrissy,
by your kindness, use the current dev branch when complaining about things not working, as they might already be solved :hmpf:
Kidding aside, I already stumbled over this and fixed it on the side (accidentally actually, as I had that somewhere in that recent big PR of mine)

**Comment by niphlod** [comment]
poor fullcomputername.

**Comment by nvarscar** [comment]
Re code on the screenshot: I like the way you think 😉
