### ISSUE TITLE
Remove-SqlDatabaseSafely fails to perform final drop w/ no addtl info

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#238]
Sleeping for a few seconds to ensure the next step (DBCC) succeeds

> WARNING: FAILED : Restore Job Rationalised Database Restore Script for db1 failed on sql01 - aborting routine for db1
> WARNING: Check the Agent Job History on sql01 - if you have SSMS2016 July release or later
> WARNING: Get-SqlAgentJobHistory -JobName Rationalised Database Restore Script for db1 -ServerInstance sql01 -OutcomesType Failed

The job shows as succeeded in Agent, but the database hasn't been dropped for a final time. Can we get a Write-Exception or is that not possible because it's something in Agent?

**Comment by SQLDBAWithABeard** [comment]
There is a write-exception in that Catch already. Can we reproduce so that I can have a look?

**Comment by ctrlbold** [comment]
mmmm so far, it's only failed at work so I can't paste screenshots, but it didn't report that it was writing to the exception log. I'll dig deeper tomorrow.

**Comment by ctrlbold** [comment]
Have an additional report: 

> I have noticed an issue with Remove-SQLDatabaseSafely.... for large dbs, I always get error:  Sleeping for a few seconds to ensure the next step (DBCC) succeeds
> WARNING: FAILED : Restore Job Rationalised Database Restore Script for DB failed on DB - aborting routine for DB
> reproduced in several different  SQL 2012 environments at different patch levels
> however if I run the rationalized job manually it works
> I think it is probably related to the sleep not going long enough

**Comment by SQLDBAWithABeard** [comment]
Thank you I will take a look at that tomorrow and see if there is another way. Cant remember why I had the sleep in there in the first place.

**Comment by ctrlbold** [comment]
Did you see, Chris mentioned this potential fix https://files.slack.com/files-pri/T1LTZ0BQV-F2NJ2416G/pasted_image_at_2016_10_12_03_39_pm.png
