### ISSUE TITLE
Get-DbaSqlService 

### ISSUE THREAD

**Issue by banditkd** [sqlcollaborative/dbatools#2390]
## Bug Report
When running Get-DbaSqlService it throws the error below

PS C:\Windows\system32> Get-DbaSqlService TESTSERVER
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value
for a preference parameter, and has been replaced by the default value. For more information, see the Help topic,
"about_Preference_Variables."
At line:138 char:51
+             if ($connection.CimDCOM -notlike "Disabled") { $enabledProtocols += "CimDCOM" ...
+                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException

WARNING: [Get-DbaSqlService][16:11:27] No Sql Services found on TESTSERVER

### General Troubleshooting steps

- [X ] Verified running latest release of dbatools?
- [ X] Verified errors are not related to permissions?
- [ X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
Windows Server 2012R2

 - PowerShell Version: 
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.3.9600.18728
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
 - SQL Server (Edition|Version): 
SQL 2012 SP2 CU15 Enterprise 

## Steps to Reproduce
Install dbatools 0.9.62

PS C:\Windows\system32> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.9.62     dbatools                            {Add-DbaComputerCertificate, Backup-DbaDatabase, Backup-Db...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.1    PowerShellGet                       {Find-DscResource, Find-Module, Find-Script, Get-Installed...

I have traced the issue back to the last working version which was 0.9.53 so it seems the issue was introduced as part of 0.9.54 commit. 

PS H:\> PS C:\Windows\system32> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.9.53     dbatools                            {Add-DbaComputerCertificate, Backup-DbaDatabase, Backup-Db...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.1    PowerShellGet                       {Find-DscResource, Find-Module, Find-Script, Get-Installed...

ComputerName : TESTSERVER
ServiceName  : MSSQLSERVER
ServiceType  : Engine
InstanceName : MSSQLSERVER
DisplayName  : SQL Server (MSSQLSERVER)
State        : Running
StartMode    : Automatic

ComputerName : TESTSERVER
ServiceName  : SQLBrowser
ServiceType  : Browser
InstanceName :
DisplayName  : SQL Server Browser
State        : Stopped
StartMode    : Disabled

ComputerName : TESTSERVER
ServiceName  : SQLSERVERAGENT
ServiceType  : Agent
InstanceName : MSSQLSERVER
DisplayName  : SQL Server Agent (MSSQLSERVER)
State        : Running
StartMode    : Automatic

I have also tested it with 0.9.63 and now the error seems to be handled.

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann and @nvarscar - to sum up: the error is handled but the information is incorrect. `0.9.53` finds servers that `0.9.62` does not.

thanks for the report!

**Comment by FriedrichWeinmann** [comment]
Alright, found the issue, solved and tested it:
https://github.com/sqlcollaborative/dbatools/pull/2391

**Comment by FriedrichWeinmann** [comment]
Issue solved, closing
