### ISSUE TITLE
Set-SqlMaxMemory - Wrong variable $servername

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#240]
On line 89 (https://github.com/sqlcollaborative/dbatools/blob/development/functions/Set-SqlMaxMemory.ps1#L89) inside if block for testing sysadmin permissions we are using `$servername` but this variable does not exists on the script.
Should be `$sqlserver` instead.

**Comment by ConstantineK** [comment]
This is fixed in #304
