### ISSUE TITLE
T-SQL Parser as part of Microsoft.SqlServer.Management.SqlParser

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2400]
https://sqlblogcasts.com/blogs/sqlandthelike/archive/2012/03/13/parsing-t-sql-the-easy-way.aspx

It's a T-SQL Parser. Not sure if it'll be helpful for us internally but maybe?

**Comment by nvarscar** [comment]
I actually see a use case for it: parsing a tsql file to find if it contains any 'dangerous' statements (server level management, global roles management, etc). Might be useful in automated deployments.

**Comment by andreasjordan** [comment]
As the link is not working anymore, I will close this.
@potatoqualitee : If you find the website again, please reopen or open a new issue.
