### ISSUE TITLE
Test-DbaJobOwner not defaulting to sa

### ISSUE THREAD

**Issue by SimonHellings** [sqlcollaborative/dbatools#2402]
## Bug Report
In the documentation for this function it states "By default, the function will check against ‘sa’ for ownership", however, when I ran it:

`Test-DbaJobOwner -SqlServer MyServer`

It incorrectly returned that all my jobs where owned by sa, because the target shows as blank:

Server       : MyServer
Job          : MyFirstJob
CurrentOwner : sa
TargetOwner  : 
OwnerMatch   : False

### General Troubleshooting steps

This works perfectly for the function `test-dbaDatabaseOwner`. 
 I've had a quick look at the code for both and the logic for sa is different between them.

dbaDatabaseOwner

```if ($TargetLogin.length -eq 0) { 
				$TargetLogin = ($server.logins | Where-Object { $_.id -eq 1 }).Name 
 			} 
```

vs

dbaJobOwner

```if ($Login -and ( ($server.VersionMajor -lt 9) -and ([string]::IsNullOrEmpty($Login)) )) { 
 				$Login = "sa" 
 			} 
 			# dynamic sa name for orgs who have changed their sa name 
 			if ($Login -eq "sa") { 
 				$Login = ($server.Logins | Where-Object { $_.id -eq 1 }).Name 
 			} 
```

I'm not sure that the test is correct in the JobOwner function and could be more inclusive to test for sa or empty string?

`if ($Login -eq "sa" -or $Login.Length = 0) `

### Version Information
 - Operating System (Name|Version): Windows 2012R2
 - PowerShell Version: 5.1.14409.1012
 - SQL Server (Edition|Version): SQL Server 2014 (SP2-CU3) Standard (have also tested against 2008 --> 2016SP1)

## Steps to Reproduce
`Test-DbaJobOwner -SqlServer MyServer`

returns blank target

###  Work Around
As a work around adding the parameter `-Login sa` does resolve the issue; this is more a consistency thing between functions.

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/commit/27ceb7124b3e41b6198d1112ec5604ee3a6c3a91#diff-f6bcafef9459d3aabf5fda70c7280d7f
