### ISSUE TITLE
Test-DbaVirtualLogFile - this commands needs to actually test something

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2407]
This command as-is does not test anything, it simply gets the VLF count and returns the information.

It should actually test the information. I would propose the current version of Test-DbaVirtualLogFile be renamed to `Get-DbaDbVirtualLogFile` or just `Get-DbaDbVlf`.

Then a proper Test-DbaVirtualLogFile command is written that validates the VLF count and offer some recommendation based on that count. I would expect based on the [gold standard](https://www.sqlskills.com/blogs/kimberly/transaction-log-vlfs-too-many-or-too-few/).

I don't know if we want to work out calculating based on the size of the current log file, how many VLFs it should have if you grew the file out properly (based on the gold standard). If it does not match then we should pop out a warning on it. I would say that is what a proper test command should provide, not just output of DBCC LOGINFO.

**Comment by potatoqualitee** [comment]
As mentioned in your PR, @ClaudioESSilva had some plans to do a test and afaik it was based on one of Paul's posts.

**Comment by potatoqualitee** [comment]
Hey @ClaudioESSilva - any chance you can get around to this in the next week? I have a great lil project that could use it ;)

**Comment by ClaudioESSilva** [comment]
Yes, that's true. We have talked before to implement some math to say "based on X% offset you are over/below the number of VLFs".
I will pick this one, but not this year! 😅

**Comment by Stuart-Moore** [comment]
I think I posted something as well that would work out if your vlf size was
flat, growing or shrinking via regression so we could tell growth type.

**Comment by js0505** [comment]
Don't know if this will help out but Tracy Boggiano did a post a few months back on VLF's: [http://tracyboggiano.com/archive/2017/09/high-vlf-count-fix/](http://tracyboggiano.com/archive/2017/09/high-vlf-count-fix/)

**Comment by potatoqualitee** [comment]
propose to remove this command in favor of `Get`

**Comment by potatoqualitee** [comment]
or actually, let's rename it to `Measure-`?

**Comment by wsmelton** [comment]
Well to measure or test it would be a wrapper for the `Get` command, so this one I'd say rename to get and then a new command becomes the measure or test. 

A measure command would be something that outputs aggregated information.

**Comment by potatoqualitee** [comment]
we do have a `Get` that is unaggregated, so changing this to `Measure` could work?

**Comment by wsmelton** [comment]
Oh, forgot about that one....then yeah just rename it to measure and we should be good.
