### ISSUE TITLE
Copy-DbaDatabase fails in Get-FilteredRestoreFile

### ISSUE THREAD

**Issue by cabana1** [sqlcollaborative/dbatools#2429]
### General Troubleshooting steps

- [x ] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): win 2012 r2
 - PowerShell Version: 5
 - SQL Server (Edition|Version): sql 2014

## Steps to Reproduce
$source = "sourceserver,port"
 $destination = "destinationserver,port"
 Copy-DbaDatabase -Source $source -Destination $destination -Database "DBNAME" -verbose -BackupRestore -force -NetworkShare \\sharepath

The backup to a share or the destination server works fine.  It errors on [Get-FilteredRestoreFile].  I can see it prints the dbname:

VERBOSE: [Get-FilteredRestoreFile][08:30:38] Find Newest Full backup - DBNAME
VERBOSE: dbname = PORTNUMBER DBNAME

Console output attached.

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
It looks like the split on comma in the code is causing a problem when a port is provided (line 169):

            $ServerName, $databaseName = $Database.Name.split(',').trim()
            Write-verbose "dbname = $databasename"
            $SQLBackupdetails = $AllSQLBackupdetails | Where-Object {$_.ServerName -eq $ServerName -and $_.DatabaseName -eq $DatabaseName.trim()}
            #If we're continuing a restore, then we aren't going to be needing a full backup....
            $TlogStartlsn = 0
            if (!($continue)) {
                $Fullbackup = $SQLBackupdetails | where-object {$_.BackupTypeDescription -eq 'Database' -and $RestoreTime -ge $_.BackupStartDate} | Sort-Object -Property LastLSN -descending | Select-Object -First 1
                $TlogStartlsn = $Fullbackup.LastLsn
                if ($Fullbackup -eq $null) {
                    Stop-Function -Message "No Full backup found to anchor the restore" -Continue -Target $database
                    break
                }
                #This scans for striped full backups to build the results
                $Results += $SQLBackupdetails | where-object {$_.BackupTypeDescription -eq "Database" -and $_.FirstLSN -eq $FullBackup.FirstLSN -and $_.BackupSetGUID -eq $FullBackup.BackupSetGUID}
            }

this makes the code throw an error:  WARNING: [Get-FilteredRestoreFile][08:45:43] No Full backup found to anchor the restore
 
I have to pass in servername,port.  This appears to cause a problem in this function.

### Additional information

[copy database error.txt](https://github.com/sqlcollaborative/dbatools/files/1372312/copy.database.error.txt)

**Comment by dczarny** [comment]
I am seeing the same thing with the backup-dbadatabase command.  I am seeing it with servers that have named instances.  Not sure if that is part of the issue or not.

PS E:\Powershell\MaintenancePlan> Get-DbaBackupHistory -SqlInstance ServerName -Database DatabaseName -Last

SqlInstance    Database Type         TotalSize DeviceType Start                   Duration End                    
-----------    -------- ----         --------- ---------- -----                   -------- ---                    
ServerName DatabaseName    Full         1.69 GB   Disk       2017-10-19 08:31:19.000 00:04:43 2017-10-19 08:36:02.000
ServerName DatabaseName    Differential 4.77 MB   Disk       2017-10-19 09:48:35.000 00:00:01 2017-10-19 09:48:36.000



PS E:\Powershell\MaintenancePlan> Backup-DbaDatabase -SqlInstance ServerName -Database DatabaseName -BackupDirectory \\BackupLocation\SQLBackups1\machinename\DIFF -Type Differential -CreateFolder -Checksum -Verify
WARNING: \\BackupLocation\SQLBackups1\ryantms\DIFF\DatabaseName already exists
WARNING: [Get-FilteredRestoreFile][10:02:19] No Full backup found to anchor the restore
WARNING: [Backup-DbaDatabase][10:02:19] Backup Failed:  Cannot index into a null array.


SqlInstance      : ServerName
DatabaseName     : DatabaseName
BackupComplete   : False
BackupFilesCount : 1
BackupFile       : DatabaseName_201710191002.bak
BackupFolder     : \\BackupLocation\SQLBackups1\ryantms\DIFF\DatabaseName
BackupPath       : \\BackupLocation\SQLBackups1\ryantms\DIFF\DatabaseName\DatabaseName_201710191002.bak
Script           : BACKUP DATABASE [DatabaseName] TO  DISK = N'\\BackupLocation\SQLBackups1\ryantms\DIFF\DatabaseName\DatabaseName_201710191002.bak' WITH  DIFFERENTIAL , NOFORMAT, NOINIT, NOSKIP, REWIND, NOUNLOAD,  STATS = 1, CHECKSUM
Verified         : False
Type             : Differential




PS E:\Powershell\MaintenancePlan> Get-DbaBackupHistory -SqlInstance ServerName -Database DatabaseName -Last

SqlInstance    Database Type         TotalSize DeviceType Start                   Duration End                    
-----------    -------- ----         --------- ---------- -----                   -------- ---                    
ServerName DatabaseName    Full         1.69 GB   Disk       2017-10-19 08:31:19.000 00:04:43 2017-10-19 08:36:02.000
ServerName DatabaseName    Differential 4.77 MB   Disk       2017-10-19 10:02:16.000 00:00:01 2017-10-19 10:02:17.000

**Comment by Stuart-Moore** [comment]
Working on some other bits with restore atm, and hoping to roll the fix for
this in to that.

Potentially pushing up later tonight

Cheers
Stuart

**Comment by Stuart-Moore** [comment]
Just pushed up #2479 which should fix this. if you could take the restorebits branch for a test drive that'd be great

**Comment by cabana1** [comment]
I tested this and it works now.  Thanks @Stuart-Moore!
