### ISSUE TITLE
DbaMaxMemory

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#243]
- [ ] Copy Get-SqlMaxMemory to Test-DbaMaxMemory
- [ ] Rename Get-SqlMaxMemory to Get-DbaMaxMemory
- [ ] Remove recommendation from within Get-DbaMaxMemory
- [ ] Add Notes column with info to Test-DbaMaxMemory

**Comment by ie-zero** [comment]
Apologies but I did not spot this earlier. I have raised PR #340 "Memory suggestions are offered by Test-SqlMaxMemory" which implements more-or-less is this functionality. 

I will rename the Get-SqlMaxMemory to Get-DbaMaxMemory as proposed here. 

@ctrlbold: Could you kindly clarify please what information the new column in Test-DbaMaxMemory should include?

**Comment by ctrlbold** [comment]
Hey thanks again for taking time out of your weekend to help!

The notes column should be titled Notes and say "This is a general recommendation that does account for specialized environments."

**Comment by ie-zero** [comment]
It is my pleasure. 

I also spotted Set-SqlMaxMemory cmdlet. should we rename this as well to Set-DbaMaxMemory?

**Comment by ctrlbold** [comment]
Yes, please 👍  I mentioned in the previous code review that I'll take care of the psd1 and psm1 once the PR is approved. There, I'll add the newly named commands and alias the old ones.

**Comment by PowerDBAKlaas** [comment]
Wouldn't it be an enhancement if we rename both Get- and Test-DbaMaxMemory to DbaMemorySettings and include the MinMemory?
I see the Get-dbaMaxMemory already returns a few extra columns, so it's probably not a big deal to add MinMemory. I believe this would be better than creating separate functions for MinMemory, because one would mostly want to see them together.
Especially on virtual machines MinMemory is an important setting.

**Comment by ctrlbold** [comment]
I'm open to that, though this is one of my oldest commands and people expect it to be named MaxMemory. Actually, I really want MaxMemory [tho i'm open to be convinced later, just not ready to let go now ;)]. Can you do MinMemory and then make a third one that does both?

I could never find a good formula for MinMemory, you?

**Comment by PowerDBAKlaas** [comment]
I don't know if it's possible to calculate advice on minmemory. I suppose a lot of settings in VMWare or whatever influence the behaviour, and the load on other machines that share the resources. I don't know much about those things (thin and thick provisioining, ballooning,...)
It would be useful to see anyway, in the Get- function for sure.

If we rename the existing function and add Get-DbaMaxMemory as an alias, would that satisfy all needs?

**Comment by ctrlbold** [comment]
Done AF!
