### ISSUE TITLE
Test-DbaConnectionAuthScheme

### ISSUE THREAD

**Issue by Redwood001** [sqlcollaborative/dbatools#2431]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Windows Server |2012R2): 
 - PowerShell Version:  5.1
 - SQL Server (2016|SP1 CU4): 

## Steps to Reproduce
When I run Test-DbaConnectionAuthScheme -SqlInstance Server1 I receive this error:

Write-Message : Cannot process argument transformation on parameter 'Silent'. Cannot c
onvert value "" to type "System.Boolean". Boolean parameters accept only Boolean value
s and numbers, such as $True, $False, 1 or 0.
At line:98 char:5
+ ...              Write-Message -Level Warning -Message  "$_ `nMoving on."
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Message], ParameterBindingArgum 
   entTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Write-Message

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by Redwood001** [comment]
Hi I saw the issue is fixed in 0.9.69
Now my pester test work fine. 
Good work THANKS

**Comment by potatoqualitee** [comment]
Our pleasure! Thank you for reporting the issue.
