### ISSUE TITLE
Test-DbaPowerPlan is not working on other language

### ISSUE THREAD

**Issue by chrgraefe** [sqlcollaborative/dbatools#245]
Hi

Test-DbaPowerPlan isn't working correctly on my german server.
Instead of "High Performance" the phrase "Höchstleistung" is printed to the display.

![image](https://cloud.githubusercontent.com/assets/4922897/19191290/1c94b06e-8ca2-11e6-8bc8-219e36d41ca7.png)

I think we have to check against serveral values, because of the localisation.

kind regards

**Comment by ctrlbold** [comment]
A few folks came up with the solution to look by GUID instead 💃 

`Get-CimInstance -classname Win32_PowerPlan -Namespace "root\cimv2\power"

ElementName      GUID
-----------      ----
Balanced         {381b4222-f694-41f0-9685-ff5bb260df2e}
High performance {8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c}
Power saver      {a1841308-3541-4fab-bc81-f71556f20b4a}`

So an easy solution appears possible and we will also keep this in mind for other comparisons. Will fix in future release. Thank you for the bug report.

**Comment by ctrlbold** [comment]
Please ensure that the recommended power plan is in the user's native language as well. Merci!

**Comment by ConstantineK** [comment]
Fixed and Merged in #280.

**Comment by ctrlbold** [comment]
Hey @chrgraefe, we'll be releasing the fix shortly. Would you be able to test it? The code looks good, it works in English, but changing the regional settings in Win10 wasn't enough to change the language entirely.
