### ISSUE TITLE
Repair-DbaRestoringDatabase

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2451]
https://blog.sqlauthority.com/2014/11/25/sql-server-fix-the-database-model-is-marked-restoring-and-is-in-a-state-that-does-not-allow-recovery-to-be-run/

**Comment by Stuart-Moore** [comment]
We have all the bits, bar a RECOVERY option on Restore-DbaDatabase, and then it's just a wrapper around existing functionality

Be back in a bit

**Comment by potatoqualitee** [comment]
i saw at least two ppl reference it on slack which is where i got the idea. i think its used more (ive had to do something similar in the past)

**Comment by andreasjordan** [comment]
Is this still a problem with current versions of SQL Server?

**Comment by potatoqualitee** [comment]
Most places aren't updated on current versions so if it's good enough for old ones and interesting to you, I'm very open to it.

**Comment by potatoqualitee** [comment]
yeah, dave's thing is super specific. I was thinking more about using EMERGENCY mode

https://blog.netnerds.net/2011/07/sql-server-surefire-restore-method-for-connection-hammered-databases/
https://www.sqlskills.com/blogs/paul/checkdb-from-every-angle-emergency-mode-repair-the-very-very-last-resort/

**Comment by potatoqualitee** [comment]
I'll close this for now. If anyone thinks it's worthwhile, please feel free to comment.
