### ISSUE TITLE
Get-DbaDatabaseFile - fails on older compatibility level

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2453]
## Bug Report
When querying SQL Server 2008 R2 with database with level 80 (in my situation) you get error:
`Incorrect syntax near ')'.`

### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 2008 R2
 - Database Compatibility Level: 80

## Steps to Reproduce

![default](https://user-images.githubusercontent.com/14327077/31612003-f897aa34-b286-11e7-9f07-c64939451dbd.png)

**Comment by ClaudioESSilva** [comment]
HI @Zhunya for this command we should use the database `CompatibilityLevel` instead of the engine version ( `serverMajor`).

Do you want to try to do that change and test it? 😄

**Comment by wsmelton** [comment]
@ClaudioESSilva both checks are still required because the query in use is dependent up on the major version of SQL Server ([example](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaDatabaseFile.ps1#L113)).

**Comment by wsmelton** [comment]
Only thing we should have to do off the top is simply throw a warning when a 2000 compatible database is found that it is not supported. Unless we also want to include a T-SQL query that covers that "version".

**Comment by niphlod** [comment]
fixed a long time ago
