### ISSUE TITLE
Test-DbaLastBackup BackupDate output data issue when diff backups involved

### ISSUE THREAD

**Issue by DAZCUK46** [sqlcollaborative/dbatools#2455]
### General Troubleshooting steps

- [Y] Verified running latest release of dbatools?
- [Y] Verified errors are not related to permissions?
- [Y] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - dbatools Version: 0.9.70
 - Operating System (Name|Version): Windows 10 Professional
 - PowerShell Version: 5.0.10586.672
 - SQL Server (Edition|Version): SQL Server 2016 Enterprise
 
## Steps to Reproduce

1/ Setup this table to log results on $LoggingServer in a database called 'AuditDB' :

CREATE TABLE [dbo].[DbaTools_Test-DbaLastBackupLog]
(
[SourceServer] NVARCHAR(250) NULL,
[TestServer] NVARCHAR(250) NULL,
[Database] NVARCHAR(250) NULL,
[FileExists] NVARCHAR(20) NULL,
[Size] NVARCHAR(20) NULL,
[RestoreResult] NVARCHAR(200) NULL,
[DBCCResult] NVARCHAR(200) NULL,
[RestoreStart] DATETIME NULL,
[RestoreEnd] DATETIME NULL,
[RestoreElasped] TIME NULL,
[DbccStart] DATETIME NULL,
[DbccEnd] DATETIME NULL,
[DbccElapsed] TIME NULL,
[BackupDate] [datetime] NULL,
[BackupFiles] NVARCHAR(300) NULL
) ON [PRIMARY]
GO

2/ Ensure a full backup and then a differential backup has been taken on at least one database on $servers

3/  Execute dbatools script: 

Import-Module dbatools
$TestServer = 'UATSQL-A\UAT'
$LoggingServer = 'SQL-A\PROD'
$servers = 'SQL-A\PROD'
$Results = $servers.ForEach{Test-DbaLastBackup -SqlServer $_ -Destination $TestServer -MaxMB 1000}
$DataTable = Out-DbaDataTable -InputObject $Results
Write-DbaDataTable -SqlServer $LoggingServer -Database AuditDB -Schema dbo -Table DbaTools_Test-DbaLastBackupLog -KeepNulls -InputObject $DataTable

4/ Issue

Script will produce an error similar to below: 

_'Exception setting "Item": "Exception calling "set_Item" with "2" argument(s): "String was not recognized as a valid DateTime.Couldn't store <15/10/2017 21:35:04, 16/10/2017 16:21:27> in BackupDate Column.  Expected type is DateTime.""
At line:280 char:9
    + $datarow.Item($property.Name) = $property.value -join ", 
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : CatchFromBaseAdapterParameterizedPropertySetValue'_

 
Full Backup Date = 15/10/2017 21:35:04
Diff Backup Date = 16/10/2017 16:21:27
 

 
$Results stores two dates (Full & Diff backup date) in "BackupDate" when a Diff backup has occurred since last full backup identified by running $results[x].BackupDate

$DataTable "BackupDate" variable cannot hold multiple backup dates due to being a DateTime data type 

Data is still written to "DbaTools_Test-DbaLastBackupLog" table but "BackupDate" column is NULL for any database in the above scenario, altering table for "BackupDate" column to NVARCHAR doesn't help as $DataTable defaults to DateTime data type.

**Comment by Stuart-Moore** [comment]
Hi,
That's by design.

when more than one backup is needed to perform the test  (Striping, log, diff, etc), then we return the information about all the backups used, like this:
![image](https://user-images.githubusercontent.com/5613670/31649174-6f725cd0-b309-11e7-8ea7-c5aecb3ea410.png)
So we return an array of files and dates as we've no way of knowing which one of those pieces of information you want.

If you'd like to suggest a new output structure, please feel free :+1:

There are 2 ways you could modify your script in the meantime:
1) Add computed fields to your result set using Calculated properties:
```
$Results = $servers.ForEach{Test-DbaLastBackup -SqlServer $_ -Destination $TestServer -MaxMB 1000 | select *, @{Name='FirstBackupDate'; Expression={$_.BackupDate[0]}}, @{Name='FirstBackupFile'; Expression={$_.BackupFiles[0]}}}
```
or you can replace them:
```
$Results = $servers.ForEach{Test-DbaLastBackup -SqlServer $_ -Destination $TestServer -MaxMB 1000 | select *, @{Name='BackupDate'; Expression={$_.BackupDate[0]}}, @{Name='BackupFile'; Expression={$_.BackupFiles[0]}} -ExcludeProperty backupdate, backupfiles}
```

2)  unpack them into a new array if you want them all (quick and dirty exampl that'll work against a single db resultset, but could be wrapped in a loop to cope with more):
```
$temp = @()
for ($i=0; $i -lt $.BackupFiles.Count; $i++){
    $Temp += $t | select *, @{Name='BackupDate'; e={$_.BackupDate[$i]}}, @{Name='BackupFiles'; e={$_.BackupFiles[$i]}} -ExcludeProperty backupdate, backupfiles
}
```

**Comment by DAZCUK46** [comment]
Thanks Stuart I implemented point 1. and works a treat.

Regards,
Darren.
