### ISSUE TITLE
DbaInstanceParameter error

### ISSUE THREAD

**Issue by StWade** [sqlcollaborative/dbatools#2458]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools? Just downloaded DBATools, hope it was the latest release
- [x] Verified errors are not related to permissions? pretty sure. I did work with the System Admin to resolve my issue
- [x] Can duplicate in new/fresh PowerShell.exe session? yes

### Version Information
 - Operating System (Name|Version): 
 - PowerShell Version: 
 - SQL Server (Edition|Version): 

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by potatoqualitee** [comment]
hey @StWade - thanks for taking the time to fill out a report! unfortunately, we cant see any errors. Do you have a screenshot or the results of `Get-DbaToolsLog`?

**Comment by StWade** [comment]
This is what I get when I execute Get-DbaToolsLog
[cid:image001.png@01D3474C.BE2070C0]

This is the error I get with Start-DbaMigration.  I just blacked out the server names.
[cid:image004.png@01D3474C.F0507E50]

Thank you

Stephen Wade (Steve)
MS SQL Database Administrator
(W) 801.401.5700
Schedule: 4x10, 6:00 - 4:30, Monday -Thursday
[http://home.csw.l-3com.com/services/SLC-VMS/L3%20Logos/L3%20Technologies/_t/L3ball-3D_RedWh_NoBkgnd_ThreeQtrInDiameter_png.jpg]<http://home.csw.l-3com.com/services/SLC-VMS/_layouts/listform.aspx?PageType=4&ListId=%7bC4E0C91D-3912-4095-9C08-74815FC55F04%7d&ID=50>

**Comment by StWade** [comment]
The attached file shows the errors I get.

Stephen Wade (Steve)

CONFIDENTIALITY NOTICE: This email and any attachments are for the sole use of the intended recipient and may contain material that is proprietary, confidential, privileged or otherwise legally protected or restricted under applicable government laws. Any review, disclosure, distributing or other use without expressed permission of the sender is strictly prohibited. If you are not the intended recipient, please contact the sender and delete all copies without reading, printing, or saving.

Effective immediately my new email address is stephen.wade@L3T.com. Please update your records.

**Comment by wsmelton** [comment]
@StWade  When you respond via emails, those images/logs you attache to the email are not going to be included. You will need to login to GitHub site and attach the logs and images.
