### ISSUE TITLE
Copy-DbaDatabase.ps1 has error, but processing still continues

### ISSUE THREAD

**Issue by coloradotechie** [sqlcollaborative/dbatools#2460]
## Bug Report

Command that causes failure:

`copy-dbadatabase -source nathan32baseEnv -destination localhost -backuprestore -networkshare \\source32BaseEnv\Shared -reusesourcefolderstructure -database AdventureWorks2012`

See attached for verbose output
[verbose_output.txt](https://github.com/sqlcollaborative/dbatools/files/1392607/verbose_output.txt)

```
Join-AdminUnc : Cannot validate argument on parameter 'filepath'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At line:952 char:47
+                     $remotePath = Join-AdminUNC $destNetBios $remotePath
+                                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-AdminUnc], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Join-AdminUnc

Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:954 char:22
+                     if (!(Test-Path $remotePath)) {
+                                     ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
   PathCommand
```

Line number of failure:
Copy-DbaDatabase.ps1: Line 952

`$remotePath = Split-Path $fgRows`

I believe it is failing because Line 952 should be:
`$remotePath = Split-Path $fgRows['filename']`

However, even though it is failing, the `return` on line 960 only drops the execution out of the current if statement, and processing continues as normal.

So, it seems there are probably 2 bugs:

1) the `$remotePath = Split-Path $fgRows['filename']` issue on line 952
2) The `return` on line 960 should probably cause the current database to be skipped completely (instead of just dropping out of the if block from lines 954 to 961.

These are just my thoughts/observations.

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2
 - PowerShell Version: 4.0
 - SQL Server (Edition|Version): 2012 Standard

## Steps to Reproduce

Run `Copy-DbaDatabase -reusesourcefolderstructure`

**Comment by wsmelton** [comment]
@coloradotechie I can't find the PR but seem to recall we've had one that addressed the join path issue before. Can you pull the latest release down and give it another try? 

_I know that `if (!(Test-Path $remotePath))` was specifically targeted in a PR._

**Comment by potatoqualitee** [comment]
heyyy me too 

![image](https://user-images.githubusercontent.com/8278033/32563081-8c3d1cd4-c4b0-11e7-927f-e333489f0fb3.png)

with the newest version :(

**Comment by coloradotechie** [comment]
@wsmelton - I just ran
`
Invoke-Expression (Invoke-WebRequest -UseBasicParsing https://dbatools.io/in)
`
on a new server and I'm still getting the same error:

![image](https://user-images.githubusercontent.com/1759990/32904059-cffdde46-cab3-11e7-857c-183bd4fef7be.png)

**Comment by potatoqualitee** [comment]
Happy to report this was fixed a while back! Please update to the latest version of dbatools.
