### ISSUE TITLE
Found a math error Test-DbaIdentityUsage with negative bigints

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#2467]
## Bug Report
I was running this against a table that had been seeded as the max bigint negative value.  The current math tries to subtract negative which ends up adding the max bigint value to itself and cannot fit in bigint.
### General Troubleshooting steps

- [X ] Verified running latest release of dbatools?
- [X ] Verified errors are not related to permissions?
- [X ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Win10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 2012 Ent

## Steps to Reproduce
Run against a table that has bigint and seed value is max - value and then add 2 tables

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by potatoqualitee** [comment]
I don't believe this is an issue anymore. If it is, please feel free to reopen.
