### ISSUE TITLE
Should have a CONTRIBUTING.md 

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#248]
Reading this post [https://poshoholic.com/2016/09/30/get-your-powershell-game-on-for-the-hacktoberfest-challenge/](https://poshoholic.com/2016/09/30/get-your-powershell-game-on-for-the-hacktoberfest-challenge/) and then looking at the resources on the [hacktoberfest](https://hacktoberfest.digitalocean.com/#resources) site and also thinking about people who need to contribute and those who have asked me how they start - we should have a CONTRIBUTING.md

**Comment by ctrlbold** [comment]
already filed under #228 ;)

**Comment by SQLDBAWithABeard** [comment]
Man how did I miss that - I did look D'oh
