### ISSUE TITLE
Adjusting Get-DbaRoleMember

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2485]
## Feature Request

[This command](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaRoleMember.ps1) does not allow you to **only** pull server-level role members. Is there any reason why we created it in this manner?

If I just want sysadmin role members it still has to run through all the databases and their role members. On a server with 1 database this may work but servers that have 100+ where I just want to verify who is in sysadmin it does not.

### Problem to solve

I want to audit an instance's server-level role(s) or even just test existence of a login in a specific server-level role(s).

Option 1:

- Add additional parameters to the current command to `-IgnoreDatabaseRoles` or a `-ServerRole` that if that is server-level role is provided **it does not** parse the roles in a database.

Option 2:

- Rename the current command to `Get-DbaDbRoleMember`
- Create a new command `Get-DbaServerRoleMember`

**Comment by PowerDBAKlaas** [comment]
@wsmelton I can't think of a valid reason. It probably got lost in the -Include... vs -No... vs -Exclude... vs -...Only vs ... strategy changes.
I think it's best to add a switch to the existing function.

**Comment by wsmelton** [comment]
I guess my next question would be then why do we have one command that touches two different objects?

If we build out a command such as `Get-DbaRole` then it would be assumed that should be allowed to pipe to `Get-DbaRoleMember`, which in the current state would seem impossible to do since that role member command is focused on database roles.

**Comment by PowerDBAKlaas** [comment]
Well, I didn't consider the members to be objects. It's the result of the `Enummember()` and `EnumServerRoleMembers()` methods and PSCustomObject at both levels. Since I didn't see any other use for those than display, I thought it most practical to put them together.

I don't know if I misjudged that and it would be possible to create 'useful' objects after all?

Feeding the roles through the pipeline would indeed change the strategy, unless those could be accepted as strings and handled in an `-IncludeRole` kind of way.

**Comment by wsmelton** [comment]
Only thing that has stirred my interest is this issue #2441 but also with the AG commands I need to be able to get server-level roles and adjust them to build an AG.

So I guess we just need to decide how we want to move forward with it.

**Comment by PowerDBAKlaas** [comment]
The current method could be `(Get-DbaRoleMember -... -IncludeServerLevel).Where({$_.Database -eq $Null})`
The fastest improvement IMO is to get rid of the `-IncludeServerLevel` and replace it with a `-ExcludeDBLevel` and `-ExcludeServerLevel`, I guess.

IIRC we chose at one point to make 'include all' our general default and add `-Exclude...` or `-No...` where needed. But that was a long time ago. Do we have that written down somewhere?

The Roles themselves are different types, although they seem very similar. It would indeed be very probable we need to have separate `Get-DbaDbRole` and `Get-DbaServerRole`. But the Members are just a list of strings. Do you think it's necessary to split that up?

**Comment by niphlod** [comment]
major refactoring happening in https://github.com/sqlcollaborative/dbatools/issues/4128
