### ISSUE TITLE
Copy-DbaSsisCatalog can't find the SSIS installed on the destination server

### ISSUE THREAD

**Issue by csolje** [sqlcollaborative/dbatools#2493]
## Bug Report
When running Copy-DbaSsisCatalog -source isscasaar170\insightprod -destination issgi-asopa004\insight it comes with the following error: (note that I have copy the full content of the dbatools-exceptions.txt file)

19-10-2017 15:12:29

At line:129 char:17
+ ...             throw "No Integration Services' service was found on the  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.RuntimeException: No Integration Services' service was found on the destination, please ensure the feature is installed and running.
19-10-2017 15:15:50

At line:129 char:17
+ ...             throw "No Integration Services' service was found on the  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.RuntimeException: No Integration Services' service was found on the destination, please ensure the feature is installed and running.
19-10-2017 15:20:02

At line:129 char:17
+ ...             throw "No Integration Services' service was found on the  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.RuntimeException: No Integration Services' service was found on the destination, please ensure the feature is installed and running.
23-10-2017 10:05:24

At line:129 char:17
+ ...             throw "No Integration Services' service was found on the  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.RuntimeException: No Integration Services' service was found on the destination, please ensure the feature is installed and running.
23-10-2017 10:06:33

At line:129 char:17
+ ...             throw "No Integration Services' service was found on the  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.RuntimeException: No Integration Services' service was found on the destination, please ensure the feature is installed and running.
23-10-2017 10:13:17

At line:129 char:17
+ ...             throw "No Integration Services' service was found on the  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.RuntimeException: No Integration Services' service was found on the destination, please ensure the feature is installed and running.
23-10-2017 10:20:23

At line:129 char:17
+ ...             throw "No Integration Services' service was found on the  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.RuntimeException: No Integration Services' service was found on the destination, please ensure the feature is installed and running.```

### General Troubleshooting steps

I just installed the new development dbatools today.
I am sysadmin and local admin on both servers
I have done it in 3 different fresh PowerShell Sessions

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2016
 - PowerShell Version: v5.1
 - SQL Server (Edition|Version): Microsoft SQL Server 2012 (SP3-CU10) (KB4025925) - 11.0.6607.3 (X64) 

## Steps to Reproduce

$ Copy-DbaSsisCatalog -source isscasaar170\insightprod -destination issgi-asopa004\insight

I have looked into the function Copy-DbaSsisCatalog and found that it uses Get-DbaSqlService.
Here is the result by running the Get-DbaSqlService -Computer sql01\instance01:
$ Get-DbaSqlService -Server issgi-asopa004\insightprod -Type SSIS

ComputerName : ISSGI-ASOPA004
ServiceName  : MsDtsServer110
ServiceType  : SSIS
InstanceName :
DisplayName  : SQL Server Integration Services 11.0
State        : Running
StartMode    : Automatic

![image](https://user-images.githubusercontent.com/3214200/31880909-3a8b85fe-b7e2-11e7-89b2-e5c6bb0d519c.png)

Here is the Get-DbatoolsLog:

23-10-2017 10:05:21	Resolve-DbaNetworkName	Verbose		Connecting to ISSGI-ASOPA004.region.iss.biz	
23-10-2017 10:05:21	Resolve-DbaNetworkName	VeryVerbose		IP Address from ISSGI-ASOPA004.region.iss.biz is 10.160.8.23	
23-10-2017 10:05:21	Resolve-DbaNetworkName	System		Your PowerShell Version is 5	
23-10-2017 10:05:21	Resolve-DbaNetworkName	VeryVerbose		Getting computer information from issgi-asopa004.region.iss.biz	
23-10-2017 10:05:21	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:05:21	Get-DbaCmObject	VeryVerbose	issgi-asopa004.re...	[issgi-asopa004.region.iss.biz] Retrieving Management Information	
23-10-2017 10:05:21	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM	
23-10-2017 10:05:22	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM - Failed!	
23-10-2017 10:05:22	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM	
23-10-2017 10:05:22	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM - Success!	
23-10-2017 10:05:23	Resolve-DbaNetworkName	VeryVerbose		Resolving issgi-asopa004.region.iss.biz using .NET.Dns GetHostEntry	
23-10-2017 10:05:23	Get-DbaSqlService	Verbose		Getting SQL Server namespace on ISSGI-ASOPA004	
23-10-2017 10:05:23	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:05:23	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:05:23	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:05:23	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:05:23	Get-DbaSqlService	Verbose		Getting Cim class SqlService in Namespace ComputerManagement11 on ISSGI-ASOPA004.	
23-10-2017 10:05:23	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:05:23	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:05:23	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:05:23	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:05:23	Get-DbaSqlService	Verbose		Creating output objects	
23-10-2017 10:06:31	Resolve-DbaNetworkName	Verbose		Connecting to ISSGI-ASOPA004.region.iss.biz	
23-10-2017 10:06:31	Resolve-DbaNetworkName	VeryVerbose		IP Address from ISSGI-ASOPA004.region.iss.biz is 10.160.8.23	
23-10-2017 10:06:31	Resolve-DbaNetworkName	System		Your PowerShell Version is 5	
23-10-2017 10:06:31	Resolve-DbaNetworkName	VeryVerbose		Getting computer information from issgi-asopa004.region.iss.biz	
23-10-2017 10:06:31	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:06:31	Get-DbaCmObject	VeryVerbose	issgi-asopa004.re...	[issgi-asopa004.region.iss.biz] Retrieving Management Information	
23-10-2017 10:06:31	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM	
23-10-2017 10:06:31	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM - Failed!	
23-10-2017 10:06:31	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM	
23-10-2017 10:06:31	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM - Success!	
23-10-2017 10:06:32	Resolve-DbaNetworkName	VeryVerbose		Resolving issgi-asopa004.region.iss.biz using .NET.Dns GetHostEntry	
23-10-2017 10:06:32	Get-DbaSqlService	Verbose		Getting SQL Server namespace on ISSGI-ASOPA004	
23-10-2017 10:06:32	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:06:32	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:06:32	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:06:32	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:06:32	Get-DbaSqlService	Verbose		Getting Cim class SqlService in Namespace ComputerManagement11 on ISSGI-ASOPA004.	
23-10-2017 10:06:32	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:06:32	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:06:32	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:06:33	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:06:33	Get-DbaSqlService	Verbose		Creating output objects	
23-10-2017 10:07:06	Get-DbaDatabase	Verbose		Connecting to issgi-asopa004\INSIGHTPROD.	
23-10-2017 10:13:16	Resolve-DbaNetworkName	Verbose		Connecting to issgi-asopa004	
23-10-2017 10:13:16	Resolve-DbaNetworkName	VeryVerbose		IP Address from issgi-asopa004 is 10.160.8.23	
23-10-2017 10:13:16	Resolve-DbaNetworkName	System		Your PowerShell Version is 5	
23-10-2017 10:13:16	Resolve-DbaNetworkName	VeryVerbose		Getting computer information from issgi-asopa004.region.iss.biz	
23-10-2017 10:13:16	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:13:16	Get-DbaCmObject	VeryVerbose	issgi-asopa004.re...	[issgi-asopa004.region.iss.biz] Retrieving Management Information	
23-10-2017 10:13:16	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM	
23-10-2017 10:13:16	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM - Failed!	
23-10-2017 10:13:16	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM	
23-10-2017 10:13:16	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM - Success!	
23-10-2017 10:13:17	Resolve-DbaNetworkName	VeryVerbose		Resolving issgi-asopa004.region.iss.biz using .NET.Dns GetHostEntry	
23-10-2017 10:13:17	Get-DbaSqlService	Verbose		Getting SQL Server namespace on ISSGI-ASOPA004	
23-10-2017 10:13:17	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:13:17	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:13:17	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:13:17	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:13:17	Get-DbaSqlService	Verbose		Getting Cim class SqlService in Namespace ComputerManagement11 on ISSGI-ASOPA004.	
23-10-2017 10:13:17	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:13:17	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:13:17	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:13:17	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:13:17	Get-DbaSqlService	Verbose		Creating output objects	
23-10-2017 10:18:40	Resolve-DbaNetworkName	Verbose		Connecting to issgi-asopa004	
23-10-2017 10:18:40	Resolve-DbaNetworkName	VeryVerbose		IP Address from issgi-asopa004 is 10.160.8.23	
23-10-2017 10:18:40	Resolve-DbaNetworkName	System		Your PowerShell Version is 5	
23-10-2017 10:18:40	Resolve-DbaNetworkName	VeryVerbose		Getting computer information from issgi-asopa004.region.iss.biz	
23-10-2017 10:18:40	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:18:40	Get-DbaCmObject	VeryVerbose	issgi-asopa004.re...	[issgi-asopa004.region.iss.biz] Retrieving Management Information	
23-10-2017 10:18:40	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM	
23-10-2017 10:18:40	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM - Failed!	
23-10-2017 10:18:40	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM	
23-10-2017 10:18:40	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM - Success!	
23-10-2017 10:18:41	Resolve-DbaNetworkName	VeryVerbose		Resolving issgi-asopa004.region.iss.biz using .NET.Dns GetHostEntry	
23-10-2017 10:18:41	Get-DbaSqlService	Verbose		Getting SQL Server namespace on ISSGI-ASOPA004	
23-10-2017 10:18:41	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:18:41	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:18:41	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:18:41	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:18:41	Get-DbaSqlService	Verbose		Getting Cim class SqlService in Namespace ComputerManagement11 on ISSGI-ASOPA004.	
23-10-2017 10:18:41	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:18:41	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:18:41	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:18:42	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:18:42	Get-DbaSqlService	Verbose		Creating output objects	
23-10-2017 10:18:50	Resolve-DbaNetworkName	Verbose		Connecting to issgi-asopa004	
23-10-2017 10:18:50	Resolve-DbaNetworkName	VeryVerbose		IP Address from issgi-asopa004 is 10.160.8.23	
23-10-2017 10:18:50	Resolve-DbaNetworkName	System		Your PowerShell Version is 5	
23-10-2017 10:18:50	Resolve-DbaNetworkName	VeryVerbose		Getting computer information from issgi-asopa004.region.iss.biz	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:18:50	Get-DbaCmObject	VeryVerbose	issgi-asopa004.re...	[issgi-asopa004.region.iss.biz] Retrieving Management Information	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM - Failed!	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM - Success!	
23-10-2017 10:18:50	Resolve-DbaNetworkName	VeryVerbose		Resolving issgi-asopa004.region.iss.biz using .NET.Dns GetHostEntry	
23-10-2017 10:18:50	Get-DbaSqlService	Verbose		Getting SQL Server namespace on ISSGI-ASOPA004	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:18:50	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:18:50	Get-DbaSqlService	Verbose		Getting Cim class SqlService in Namespace ComputerManagement11 on ISSGI-ASOPA004.	
23-10-2017 10:18:50	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:18:50	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:18:51	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:18:51	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:18:51	Get-DbaSqlService	Verbose		Creating output objects	
23-10-2017 10:20:21	Resolve-DbaNetworkName	Verbose		Connecting to issgi-asopa004	
23-10-2017 10:20:22	Resolve-DbaNetworkName	VeryVerbose		IP Address from issgi-asopa004 is 10.160.8.23	
23-10-2017 10:20:22	Resolve-DbaNetworkName	System		Your PowerShell Version is 5	
23-10-2017 10:20:22	Resolve-DbaNetworkName	VeryVerbose		Getting computer information from issgi-asopa004.region.iss.biz	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:20:22	Get-DbaCmObject	VeryVerbose	issgi-asopa004.re...	[issgi-asopa004.region.iss.biz] Retrieving Management Information	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM - Failed!	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM - Success!	
23-10-2017 10:20:22	Resolve-DbaNetworkName	VeryVerbose		Resolving issgi-asopa004.region.iss.biz using .NET.Dns GetHostEntry	
23-10-2017 10:20:22	Get-DbaSqlService	Verbose		Getting SQL Server namespace on ISSGI-ASOPA004	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:20:22	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:20:22	Get-DbaSqlService	Verbose		Getting Cim class SqlService in Namespace ComputerManagement11 on ISSGI-ASOPA004.	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:20:22	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:20:22	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:20:23	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:20:23	Get-DbaSqlService	Verbose		Creating output objects	
23-10-2017 10:20:37	Resolve-DbaNetworkName	Verbose		Connecting to issgi-asopa004	
23-10-2017 10:20:37	Resolve-DbaNetworkName	VeryVerbose		IP Address from issgi-asopa004 is 10.160.8.23	
23-10-2017 10:20:37	Resolve-DbaNetworkName	System		Your PowerShell Version is 5	
23-10-2017 10:20:37	Resolve-DbaNetworkName	VeryVerbose		Getting computer information from issgi-asopa004.region.iss.biz	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:20:37	Get-DbaCmObject	VeryVerbose	issgi-asopa004.re...	[issgi-asopa004.region.iss.biz] Retrieving Management Information	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over WinRM - Failed!	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		[issgi-asopa004.region.iss.biz] Accessing computer using Cim over DCOM - Success!	
23-10-2017 10:20:37	Resolve-DbaNetworkName	VeryVerbose		Resolving issgi-asopa004.region.iss.biz using .NET.Dns GetHostEntry	
23-10-2017 10:20:37	Get-DbaSqlService	Verbose		Getting SQL Server namespace on ISSGI-ASOPA004	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:20:37	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:20:37	Get-DbaSqlService	Verbose		Getting Cim class SqlService in Namespace ComputerManagement11 on ISSGI-ASOPA004.	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		Configuration loaded | Cache disabled: False	
23-10-2017 10:20:37	Get-DbaCmObject	VeryVerbose	issgi-asopa004	[issgi-asopa004] Retrieving Management Information	
23-10-2017 10:20:37	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM	
23-10-2017 10:20:38	Get-DbaCmObject	Verbose		[issgi-asopa004] Accessing computer using Cim over WinRM - Success!	
23-10-2017 10:20:38	Get-DbaSqlService	Verbose		Creating output objects	

 - [x] Attach any screenshots (if possible/allowed)
 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)

**Comment by nvarscar** [comment]
Cannot reproduce so far. The parameter type conversion seems to be working fine. 
Could you please post `Get-Module dbatools` to see what is the actual version of the dbatools module you're using? Unfortunately, I cant find that information in the logs. I'm currently on 0.9.62.

**Comment by csolje** [comment]
I am running the 0.9.73

**Comment by wsmelton** [comment]
@csolje Is SQL Server 2012 on both source and destination? Are there any other versions of SSIS installed?

**Comment by BartekR** [comment]
Tested with 0.9.83; Copy-SsisDbaCatalog works OK on named instances; copied from SQL2016 to SQL2017. Which versions do you use?

**Comment by csolje** [comment]
@wsmelton yes it is

**Comment by csolje** [comment]
hmm for some reason I am using 0.9.73

**Comment by niphlod** [comment]
@csolje : is this still valid ?

**Comment by csolje** [comment]
@niphlod no ill close it now
