### ISSUE TITLE
Feature Request - Invoke-DbaDiagnosticQuery

### ISSUE THREAD

**Issue by SQLUnderworld** [sqlcollaborative/dbatools#2498]
Feature Request

### Problem to solve
When I execute

Invoke-DbaDiagnosticQuery -SqlInstance SERVER_NAME | Export-DbaDiagnosticQuery -Path C:\Users\xxxx\Desktop\GB_DMVs

...or...

$Instances=@('')
$Instances=(Get-Content C:\Users\xxxx\Desktop\ServerInstanceList.txt)

foreach ($Instance in $Instances)
{
 Invoke-DbaDiagnosticQuery -SqlInstance $Instance | Export-DbaDiagnosticQuery -Path C:\Users\xxxx\Desktop\GB_DMVs
}

...there can be over 100 .csv files as well as multiple .sqlplan files. It requires a lot of further manual effort to get the documents into one spreadsheet which can be sent as a report.

### Additional information

Link to one of GB's BLank Results Spreadsheets: https://www.dropbox.com/s/3si5pbqbv3t218n/SQL%20Server%202016%20Diagnostic%20Results.xlsx?dl=1

Or, the link to his latest DMV page:

https://www.sqlskills.com/blogs/glenn/sql-server-diagnostic-information-queries-for-october-2017/

Or, here it is attached:
[SQL Server 2016 Diagnostic Results.xlsx](https://github.com/sqlcollaborative/dbatools/files/1408887/SQL.Server.2016.Diagnostic.Results.xlsx)

**Comment by wsmelton** [comment]
I'm not sure I follow, what is it you are actually wanting the command to do?

**Comment by potatoqualitee** [comment]
I think @andrekamman added some sort of support for Excel - play around with ` Export-DbaDiagnosticQuery -ConvertTo Excel` and see if that works.

**Comment by SQLUnderworld** [comment]
Looks like I may have left some info out of my feature request. Apologies.

I meant to include [this link](http://www.sqlstad.nl/powershell/automate-glenn-berrys-dmv-scrips-with-powershell/). 

Also, the Convert-SqlServerInventoryClixmlToExcel.ps1 script found [here](https://sqlpowerdoc.codeplex.com/) does something similar to what I'm asking... It's different in the sense that it parses apart XML and then creates multiple tabs in Excel for each logical grouping of information (info. unrelated to GB's DMVs, I should add). My thought is that separate tabs (worksheets) per query would be highly beneficial to the community. I pointed to Glenn Berry's blank result worksheet to indicate how he organizes the results of his own code.

**Comment by wsmelton** [comment]
The Excel support on Export-DbaDiagnosticQuery requires the ImportExcel module to exist on the machine, however that only supports generating a new Excel file. It could be possible we can manipulate the command more but it would require a full dependency on the ImportExcel module. [ @potatoqualitee is that something you are ok with? ]

**Comment by potatoqualitee** [comment]
unfortunately not :( It's not a nicely contained module like Invoke-SqlCmd2

**Comment by wsmelton** [comment]
To accomplish this feature would require full module of ImportExcel to be backed into dbatools, which won't happen.

Someone is welcome to share a script (e.g. gist, blog post) on how you might accomplish this using the two modules together but it won't be added into dbatools.
