### ISSUE TITLE
Get-ParamSqlDatabases always filters out system databases

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#253]
@ctrlbold: Get-ParamSqlDatabases filters out system databases, but when using a cmdlet such as Get-DbaLastGoodCheckDb, I would expect there to be no restriction on the database list?

Perhaps a switch in Get-ParamSqlDatabases to include system databases is in order?

**Comment by ctrlbold** [comment]
Totally. Should have a -NoSystem to exclude system. The most important place this is updated would be the migration scripts.

**Comment by SirCaptainMitch** [comment]
With the merge I think this one is good to be closed? Still new to this.

**Comment by dansqldba** [comment]
Certainly can be closed. If you include certain text in your comments, issues will be closed automatically when the commit gets merged into master.

For your learning pleasure: https://help.github.com/articles/closing-issues-via-commit-messages/
