### ISSUE TITLE
IgnoreLogBackups does not completely ignore.

### ISSUE THREAD

**Issue by josh-simar** [sqlcollaborative/dbatools#2551]
- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

 - Operating System (Name|Version): Windows 2012
 - PowerShell Version: 3
 - SQL Server (Edition|Version): SQL 2014

## Steps to Reproduce
Have database with log backups.
Delete most recent Differential backup so that command will fail.
Run Test-DBALastBackup with -IgnoreLogBackups and without -CopyFile.
See that while log backups were not restored they are shown in the output.

**Comment by wsmelton** [comment]
Can you include what error you are getting?
