### ISSUE TITLE
Enhance the output properties of Get-DbaSqlService

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#2554]
## Feature Request

Add more uptime data to the property output for the Get-DbaSqlService.

Example:
SqlServer     : PRDBISADM01
SqlStartTime  : 10/27/2017 6:08:57 PM
SinceSqlStart : 0 days 2 hours 30 minutes 29 seconds
ComputerName  : PRDBISADM01
ServiceName   : SQLSERVERAGENT
State         : Running

**Comment by potatoqualitee** [comment]
as far as i know, this woudl require logging into the sql server itself (which may be diff credentials) which would be out of scope. if that is not the case, please let me know.
