### ISSUE TITLE
Get-DbaAgentSchedule, include "plain English" description in output

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#2559]
## Feature Request
It would be very handy if `GetDbaAgentSchedule` could include the "plain English" version of the schedule, similar to what is displayed in SSMS. I don't believe it does this at the moment.

### Problem to solve
I need to create a report, for consumption by others who might not necessarily have access to SQL instances, so they can see what the backup schedules are. Currently I can achieve this for myself by using a Central Management Server and running the following code against all msdb databases:

`sp_help_schedule @include_description = 1`

I can interpret what "Every 1 week(s) on Sunday at 1500" means, which is the kind of output that SP gives us, but it's not exactly what I would call plain English ;) For example, "Sunday at 1500" is not 3pm on a Sunday, it's actually 00:15:00am. Very different!

### Additional information

This information appears to be available, ready made, if the following is anything to go by:  https://dba.stackexchange.com/questions/10018/job-schedule-view

They're creating a new object with `Microsoft.SqlServer.Management.SqlMgmt.JobScheduleData`, then getting the `Description` property from that. It looks exactly the same, to me, as shown in SSMS.

If this property were added, I could automate code which inserts the results into a database table, then write an SSRS report against the data, thus my manager will be happy.

Name|Schedules
-------|-----------
ASPState_Job_DeleteExpiredSessions|Occurs every day every 1 minute(s) between 00:00:00 and 23:59:59. Schedule will be used starting on 16/10/2000.
syspolicy_purge_history|Occurs every day at 02:00:00. Schedule will be used starting on 1/01/2008.

Keep up the great work, dudes, you're killin' it!

**Comment by dansqldba** [comment]
Managed to fudge this together with the code from the link above, to get my report written; what I've done _definitely_ needs replacing with 100% dbatools dependant code!

I'm having issues getting it to run on something other than my own machine, to automate the capture of data. I can see why SMO is included in dbatools now... Uhg.

Here's what I've ended up producing. I used Split on "." on the description to just get the first bit, made it more readable.

![backupschedules](https://user-images.githubusercontent.com/20303014/32961686-700215ac-cbc1-11e7-919c-e74a1cc093d1.png)

**Comment by dansqldba** [comment]
The fudged code I put together has stopped working, since I had my work PC formatted; I've put SSMS 2017 on here and sqlmgmt.dll doesn't seem to provide the information. I had it working briefly with the sqlmgmt.dll from SSMS 2016, but it's broken again. Possibly something to do with the order in which I'm loading things, but I really don't know.

Also I'm now realising why sqlmgmt.dll isn't included with SMO in dbatools, because it's not part of SMO is it? It's a DLL specific to Management Studio. I'm not sure what that will mean for inclusion in dbatools, I'm guessing it complicates matters though.

**Comment by potatoqualitee** [comment]
It's includable - many of our DLLs are from SSMS. Let me take a look!

**Comment by potatoqualitee** [comment]
can you test this branch? https://github.com/sqlcollaborative/dbatools/tree/dan

**Comment by dansqldba** [comment]
The `sqlmgmt.dll` included in the branch above (believed to be 2017 RTM) works with the code I put together on Friday, which relies on SQLPS and is based on the code from [here](https://dba.stackexchange.com/questions/10018/job-schedule-view). Thanks, my hacky rubbish is working again!

If you can include this DLL with dbatools, even though it isn't technically part of SMO, I imagine someone will be able to add the "plain English" description of a SQL Agent Job Schedule to `Get-DbaAgentSchedule` as originally described. This will make my life easier and script much smaller!

It seems to be a difficult piece of information to acquire by any other method. Microsoft have already done the interpretation for SSMS, so it makes sense to re-use their code instead of re-inventing the wheel, as others have done with T-SQL.

Also, I now have a better idea why the phrase "DLL hell" became a thing.
