### ISSUE TITLE
Copy-DbaCredential fails on credentials which contain '][' character combination in their name, for example replication credentials

### ISSUE THREAD

**Issue by pportnoy** [sqlcollaborative/dbatools#2560]
## Bug Report
Copy-DbaCredential fails on credentials which contain '][' character combination in their name, for example replication credentials.
This is especially sensitive for credentials required for replication - SQL Server auto-creates the credentials following the aforementioned naming convention

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server|2012 R2
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Enterprise|SQL Server 2016

## Steps to Reproduce
Create a credential on the source that contains the '][' character combination in the credential name itself. For example, "[REPL][SOMERANDOMCREDENTIAL][NAME]".
Try running `Copy-DbaCredential -Source SourceServer -Destination SomeOtherDestinationServer`.
Following output is generated:
```
WARNING: [Copy-Credential][14:36:40] Error creating credential | Exception calling "Query" with "1" argument(s):
"Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. ""
SourceServer      : SourceServer
DestinationServer : SomeOtherDestinationServer
Name              : [REPL][SOMERANDOMCREDENTIAL][NAME]
Status            : Skipping
DateTime          : 2017-10-30 14:36:40.893
```

### Problem to solve
The script that is generated and executed by `dbatools` looks like this:
```
CREATE CREDENTIAL [[REPL][SOMERANDOMCREDENTIAL][NAME]] WITH IDENTITY = N'CONTOSO\SOMEUSER', SECRET = N'SomeSecret'
```

Unfortunately the syntax that is used is incorrect. The closing bracket within the credential name should be escaped by using the double-closing bracket. The correct syntax would be:
```
CREATE CREDENTIAL [[REPL]][SOMERANDOMCREDENTIAL]][NAME]]] WITH IDENTITY = N'CONTOSO\SOMEUSER', SECRET = N'SomeSecret'
```

### Additional information

The error is caused by the following lines in `Copy-DbaCredential`:
- [Line 207](https://github.com/sqlcollaborative/dbatools/blob/18d7b0ffc0e19e9911d011ab1c86ecd6c0015bb3/functions/Copy-DbaCredential.ps1#L209) - here the credential name is selected. In the example the "name" column will contain '[REPL][SOMERANDOMCREDENTIAL][NAME]'
- [Line 347](https://github.com/sqlcollaborative/dbatools/blob/18d7b0ffc0e19e9911d011ab1c86ecd6c0015bb3/functions/Copy-DbaCredential.ps1#L347) - here the aforementioned credential name is wrapped in '[' and ']' without properly escaping the contents.

**Comment by josh-simar** [comment]
This should now be fixed. Can we close this Issue?
