### ISSUE TITLE
Get-DbaPermission fails on a database with case sensitive collation 

### ISSUE THREAD

**Issue by yeghisheh** [sqlcollaborative/dbatools#2571]
- [+ ] Verified running latest release of dbatools?
- [+ ] Verified errors are not related to permissions?

**Comment by PowerDBAKlaas** [comment]
@yeghisheh can you describe the error and / or include some screenshots, please?

**Comment by yeghisheh** [comment]
in my case I tried to run the cmdlet on server which has Latin1_General_BIN collation and it failed
and tried on server with default collation but including a database with collation Latin1_General_BIN, it run for all databases except that one.

Please review sql codes included in cmdlet, there are defined an alias "sys.all_objects o" (with lowercase "o") and the alias used in columns area as "COALESCE(O.type_desc,sp.class_desc)" (with upper case "O"), so the difference yielded to errors for case sensitive collations

Regards
