### ISSUE TITLE
Write-Message.ps1 error

### ISSUE THREAD

**Issue by cabana1** [sqlcollaborative/dbatools#2572]
## Bug Report
I'm getting an error with Write-Message.ps1 when a PS script is called in sql agent
### General Troubleshooting steps

- [x ] Verified running latest release of dbatools?
- [x ] Verified errors are not related to permissions?
- [x ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): win 2012 r2
 - PowerShell Version: 5
 - SQL Server (Edition|Version): sql2014

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve

Attached is the log for when it works in the ISE.
The Error I get from the SQL Agent is:

A job step received an error at line 268 in a PowerShell script. The corresponding line is '			Write-Verbose $newMessage
'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'Operation is not valid due to the current state of the object.

In looking at the code it doesn't like the write-verbose in the write-message module.

[ps logging.txt](https://github.com/sqlcollaborative/dbatools/files/1431561/ps.logging.txt)

### Additional information
I'm not sure why this works in the ISE and not the sql job.
I have tried different sql accounts, but none seem to work (to rule out permissions).
Is this because it is called in a job?  Without the logging to a file it seems to work fine from a job.

**Comment by FriedrichWeinmann** [comment]
Hi cabana,

thank you for reporting this issue.
How have you set up the job? Are you using a PowerShell step? We have bad experiences with that one, especially where odd behavior we cannot reproduce in the shell/ise is concerned.
If that's not the case, please show us what commands you are running to help us with the troubleshooting.

Chrissy wrote a comprehensive blog post on this:
https://dbatools.io/agent/

Cheers,
Fred

**Comment by cabana1** [comment]
I am using a powershell step.  
I'll check the blog post.

Thanks!
