### ISSUE TITLE
Issue loading module

### ISSUE THREAD

**Issue by TheRockStarDBA** [sqlcollaborative/dbatools#2575]
@ClaudioESSilva   @potatoqualitee 

I downloaded using Invoke-Expression (Invoke-WebRequest -UseBasicParsing https://dbatools.io/in)
and update the dbatools module as well.

I am sa and local admin on both source and destination servers.

1.  Copy-DbaCredential.ps1 is broken (below stop function error pops up in `start-dbamigration` as well)

The term 'Stop-Function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Stop-Function:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

and  from get-dbatoolslog .. I get below 

[Copy-Credential][17:26:30] Error creating credential | Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. ""

>10/31/2017 5:11:35 PM Register-DbaRunspace Verbose dbatools-logging     Updating runspace: dbatools-logging                                                                                                                          
10/31/2017 5:11:35 PM Start-DbaRunspace    Verbose dbatools-logging     Starting runspace: dbatools-logging                                                                                                                          
10/31/2017 5:11:35 PM Register-DbaRunspace Verbose dbatools-teppasyn... Updating runspace: dbatools-teppasynccache                                                                                                                   
10/31/2017 5:11:35 PM Start-DbaRunspace    Verbose dbatools-teppasyn... Starting runspace: dbatools-teppasynccache                                                                                                                   
10/31/2017 5:11:35 PM Register-DbaRunspace Verbose dbatools-maintenance Updating runspace: dbatools-maintenance                                                                                                                      
10/31/2017 5:11:35 PM Start-DbaRunspace    Verbose dbatools-maintenance Starting runspace: dbatools-maintenance                                                                                                                      
10/31/2017 5:12:17 PM Copy-DbaCredential   Verbose                      Getting NetBios name for server\InstanceName                                                                                                                    
10/31/2017 5:12:17 PM Copy-DbaCredential   Verbose                      Checking if Remote Registry is enabled on server\InstanceName                                                                                         
10/31/2017 5:12:17 PM Copy-Credential      Verbose                      Collecting Credential logins and passwords on server\InstanceName                                                                                                 
10/31/2017 5:12:33 PM Copy-Credential      Verbose                      Starting migration                                                                                                                                           
10/31/2017 5:12:33 PM Copy-Credential      Verbose                      Attempting to migrate ##xp_cmdshell_proxy_account##                                                                                                          
10/31/2017 5:12:33 PM Copy-Credential      Debug                        CREATE CREDENTIAL [##xp_cmdshell_proxy_account##] WITH IDENTITY = N'', SECRET = N''                                                                          
10/31/2017 5:12:33 PM Copy-Credential      Warning ##xp_cmdshell_pro... Error creating credential 

2.  [Update-SqlPermissions][16:12:35] Failed to change job owner for ... | You cannot call a method on a null-valued expression.

3. [Copy-DbaAgentSharedSchedule][16:25:16] Issue dropping schedule | Exception calling "Drop" with "0" argument(s): "Drop failed for JobSchedule

4. [Copy-DbaAgentJob][16:26:12] Issue copying job | Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. ""

**Comment by wsmelton** [comment]
The error on the function not existing tells me the module did not import properly. Did you see any errors with importing?

**Comment by TheRockStarDBA** [comment]
The module imports fine.  How can I check if there is any errors .. it does not display any errors when importing the module.

**Comment by wsmelton** [comment]
If you run the command again, once that session finishes or errors execute `$error[0] | select *`

**Comment by TheRockStarDBA** [comment]
PS D:\DBA> $error[0] | select *
writeErrorStream      : True
PSMessageDetails      : 
OriginInfo            : intny10d
Exception             : System.Management.Automation.RemoteException: The term 'Stop-Function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
                        verify that the path is correct and try again.
TargetObject          : Stop-Function
CategoryInfo          : ObjectNotFound: (Stop-Function:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
ErrorDetails          : 
InvocationInfo        : 
ScriptStackTrace      : 
PipelineIterationInfo : {}

**Comment by TheRockStarDBA** [comment]
Also getting below when running start-dbamigration

`writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. "" ---> 
                        System.Management.Automation.MethodInvocationException: Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for 
                        Database 'master'. "" ---> System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. " ---> 
                        Microsoft.SqlServer.Management.Smo.FailedOperationException: Execute with results failed for Database 'master'.  ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred 
                        while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: The specified '@server' is invalid (valid values are returned by sp_helpserver).
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(StringCollection sqlCommands)
                           at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteWithResults(StringCollection query)
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteWithResults(StringCollection sqlCommands)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteWithResults(StringCollection sqlCommands)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at <ScriptBlock>(Closure , FunctionContext )
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, 
                        ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
                           at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object 
                        dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.PSScriptMethod.InvokeScript(String methodName, ScriptBlock script, Object this, Object[] arguments)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
                           --- End of inner exception stack trace ---
TargetObject          : Reinitialize subscriptions having data validation failures
CategoryInfo          : NotSpecified: (Reinitialize su...dation failures:String) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Copy-DbaAgentJob,Stop-Function
ErrorDetails          : Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. ""
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, <No file>: line 198
                        at Copy-DbaAgentJob<Process>, <No file>: line 250
                        at Copy-DbaSqlServerAgent<Process>, <No file>: line 116
                        at Start-DbaMigration<Process>, <No file>: line 568
                        at <ScriptBlock>, <No file>: line 8
PipelineIterationInfo : {0, 1}`

**Comment by potatoqualitee** [comment]
Please close PowerShell, the ISE and delete all instances of dbatools, either using Uninstall-Module or deleting it manually from all paths in $env:PSMODULEPATH. Then reinstall.

**Comment by TheRockStarDBA** [comment]
Thanks @potatoqualitee .. Will try that out and update here. Will it take care of all the errors that I am facing ?

**Comment by niphlod** [comment]
@TheRockStarDBA : it should have fixed everything. Can you please confirm and close the issue if it worked ?

**Comment by TheRockStarDBA** [comment]
It did not fix the issue. What logs you need ? Thanks.

**Comment by niphlod** [comment]
@TheRockStarDBA : start from Get-DbatoolsLog, we'll go from there.

@wsmelton and @potatoqualitee : what additional data would we need ?

**Comment by potatoqualitee** [comment]
This is 100% fixed by Remove-Module dbatools, deleting all instances of dbatools, then Reinstalling per dbatools.io/download. Fred will be releasing a better fix once he's back from 🌴 🍹

**Comment by wsmelton** [comment]
Going to close this issue as the module load process has been updated multiple times since this issue was created. If the issue still exists please open a new issue with details on errors and such.
