### ISSUE TITLE
Get-DbaDatabaseFreeSpace add autogrow info columns

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#258]
Add columns that calculate the growth possibilities of every data file can be  very useful to a DBA:
The growth setting in pct or KB.
The growth 'amount'.
How much can a file really grow?
How much space is left to max size?
How much space do you think you have but will never be used because this is the remainder after the last possible autogrow?

**Comment by dansqldba** [comment]
Addressed in PR #259
