### ISSUE TITLE
Add release data to Get-DbaSqlBuildReference

### ISSUE THREAD

**Issue by Jagoop** [sqlcollaborative/dbatools#2582]
## Feature Request

Make Get-DbaSqlBuildReference return information on when a given build was released.
![get-dbasqlbuildreference_suggestion](https://user-images.githubusercontent.com/13745852/32357752-cd58bb64-bffc-11e7-9e60-4d4c0cd7c952.png)

### Problem to solve
When generating lists of instance and their build level, It would be useful to be able to make comparisons between instance not-up-to-date with how much newer the current/newest CU/build actually is.

### Additional information
I believe that release information is available on several on the known build/release sites, so it should be possible to retrieve this data.

**Comment by niphlod** [comment]
I don't think the release date is such a tremendous indicator on what's the release your instance is on. 
To fill the void in your scenario, we wanna give out a companion `Test-` command that checks how many releases is the instance behind .... join us at https://github.com/sqlcollaborative/dbatools/issues/2375
