### ISSUE TITLE
Change that -LogsOnly to Type = All, Data, Log

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2590]
For Invoke-DbaDatabaseShrink and deprecate LogsOnly

**Comment by dgmyrs** [comment]
@potatoqualitee, do you mind if I tackle this one?  I have a keen interest in this command.  I'm not sure if there is a process for assigning these?

**Comment by potatoqualitee** [comment]
yes please! that'd be fabulous. you'd assign yourself, let me add you to the sqlcollab group so that you can do that

**Comment by potatoqualitee** [comment]
`You've invited Doug Meyers to SQL Server Community Collaborative ! They'll be receiving an email shortly. They can also visit https://github.com/sqlcollaborative to accept the invitation.`

**Comment by potatoqualitee** [comment]
yesssssss
