### ISSUE TITLE
Export-SqlLogins not exporting Object Level permissions

### ISSUE THREAD

**Issue by js0505** [sqlcollaborative/dbatools#260]
Need to add EnumObjectPermissions to be able to export database level object permissions.  I am thinking the below should work.
# Collect and output Object Level Permissions

```
                $perms = $sourcedb.EnumObjectPermissions($username)
                foreach ($perm in $perms)
                {
                    $permstate = $perm.permissionstate
                    $permtype = $perm.PermissionType
                    $grantor = $perm.grantor

                    if ($permstate -eq "GrantWithGrant")
                    {
                        $grantwithgrant = "WITH GRANT OPTION"
                        $permstate = "grant"
                    }
                    else
                    {
                        $grantwithgrant = $null
                    }

                    $outsql += "$permstate $permtype ON $($_.ObjectName) TO [$username]"
                }
```

**Comment by ClaudioESSilva** [comment]
Hi @js0505,
I think that enhancement as place on a new command `Export-SqlUser` (along with `Copy-SqlUser`).
We can't forget that Login object is not the same as User object. Mixing both here is not the best option (IMHO).
I have a draft for Export-SqlUser. I will add both to trello board.

But I want to here other opinions :smile:

**Comment by js0505** [comment]
Also - the script exports using ALTER ROLE even on 2008 R2 systems.  Need to update script to focus on version and then use either exec sp_addrolemember or ALTER ROLE .

**Comment by js0505** [comment]
Also - Script does not output the "SCHEMA::[dbo]" on something like GRANT VIEW DEFINITION ON SCHEMA::[dbo] TO UserA  output is GRANT VIEW DEFINITION ON TO UserA.

**Comment by wsmelton** [comment]
This command is for exporting logins so would not include specific database level object permissions, and shouldn't. A database level permission would be included in a separate command, and maybe at that point we could make a wrapper to do something like `Export-DbaSqlAccount` that utilizes both `Export-DbaSqlLogin` and `Export-DbaSqlUser`.

Closing this for now...if anyone feels it should be opened by all means.
