### ISSUE TITLE
Copy-SqlLogin - Using -SyncOnly fails

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#261]
It seems when you use the -SyncOnly switch of Copy-SqlLogin, it utilises Sync-SqlLoginPermissions. Unfortunately, it doesn't pass any credentials to this cmdlet so it fails.

In my ham fisted attempt to fix it (by adding credentials) I still couldn't get it to work, so it needs a professional ;)

**Comment by dansqldba** [comment]
Disclaimer, I could be completely wrong about this, but there's definitely something not right!?

**Comment by potatoqualitee** [comment]
Yep! You were right, Dan. Thank you! Fix will be in master shortly.
