### ISSUE TITLE
Enable-DbaAgHadr does not change the value

### ISSUE THREAD

**Issue by EmDBA** [sqlcollaborative/dbatools#2615]
Enable-DbaAgHadr returns an error

### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 2012 R2 Standard + 2016 Standard
 - PowerShell Version: 5.1.14393.1613
 - SQL Server (Edition|Version): 2012 Enterprise + 2016 Enterprise
 - Local + Remote

## Steps to Reproduce

Enable-DbaAgHadr -SqlInstance [SERVERNAME\INSTANCE] 
## dbatools logs

9/11/2017 12:28:02 Resolve-DbaNetworkName      Verbose                              Connecting to XXX                                                                                               
9/11/2017 12:28:02 Resolve-DbaNetworkName      VeryVerbose                          IP Address from XXX is XXX                                                                              
9/11/2017 12:28:02 Resolve-DbaNetworkName      System                               Your PowerShell Version is 5                                                                                              
9/11/2017 12:28:02 Resolve-DbaNetworkName      VeryVerbose                          Getting computer information from XXX                                                        
9/11/2017 12:28:02 Get-DbaCmObject             Verbose                              Configuration loaded | Cache disabled: False                                                                              
9/11/2017 12:28:02 Get-DbaCmObject             VeryVerbose     						XXX... [XXX] Retrieving Management Information                                                       
9/11/2017 12:28:02 Get-DbaCmObject             Verbose                              [XXX] Accessing computer using Cim over DCOM                                                  
9/11/2017 12:28:02 Get-DbaCmObject             Verbose                              [XXX] Accessing computer using Cim over DCOM - Success!                                       
9/11/2017 12:28:02 Resolve-DbaNetworkName      Verbose                              Unable to get computer information from XXX                                                                      
9/11/2017 12:28:02 Resolve-DbaNetworkName      VeryVerbose                          Resolving XXX using .NET.Dns GetHostEntry                                                                        
9/11/2017 12:28:02 Get-DbaAgHadr               Verbose                              Attempting to connect to XXX                                                                                     
9/11/2017 12:28:02 Resolve-DbaNetworkName      Verbose                              Connecting to XXX                                                                            
9/11/2017 12:28:02 Resolve-DbaNetworkName      VeryVerbose                          IP Address from XXX is XXX                                                            
9/11/2017 12:28:02 Resolve-DbaNetworkName      System                               Your PowerShell Version is 5                                                                                              
9/11/2017 12:28:02 Resolve-DbaNetworkName      VeryVerbose                          Getting computer information from XXX                                                         
9/11/2017 12:28:02 Get-DbaCmObject             Verbose                              Configuration loaded | Cache disabled: False                                                                              
9/11/2017 12:28:02 Get-DbaCmObject             VeryVerbose    						XXX... [XXX] Retrieving Management Information                                                       
9/11/2017 12:28:02 Get-DbaCmObject             Verbose                              [XXX] Accessing computer using Cim over DCOM                                                  
9/11/2017 12:28:02 Get-DbaCmObject             Verbose                              [XXX] Accessing computer using Cim over DCOM - Success!                                       
9/11/2017 12:28:02 Resolve-DbaNetworkName      Verbose                              Unable to get computer information from XXX                                                  
9/11/2017 12:28:03 Resolve-DbaNetworkName      VeryVerbose                          Resolving XXX using .NET.Dns GetHostEntry 

### Problem to solve

PS C:\Windows> Enable-DbaAgHadr -SqlInstance [SERVERNAME\INSTANCE] 
You cannot call a method on a null-valued expression.
At line:95 char:6
 +$sqlService.ChangeHadrServiceSetting($Enabled)
 +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 +CategoryInfo          : InvalidOperation: (:) [], RuntimeException
 +FullyQualifiedErrorId : InvokeMethodOnNull
 
ComputerName : XXX
InstanceName : XXX
SqlInstance  : XXX
HadrPrevious : 
HadrCurrent  :

**Comment by wsmelton** [comment]
If you are able to run `New-DbatoolsSupportPackage -Path <your desired path>`, this will generate a zip file that you can post via the site to this issue it will provide us more details on the error.

If you cannot use that method please provide the full output of `$error[0] | select *` after you run the command.

**Comment by EmDBA** [comment]
System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server XXX failed with the following error message : WinRM cannot process the request. The following error with errorcode 0x80090322 occurred while using Kerberos authentication: An unknown security error occurred.  
 Possible causes are:
  -The user name or password specified are invalid.
  -Kerberos is used when no authentication method and no user name are specified.
  -Kerberos accepts domain user names, but not local user names.
  -The Service Principal Name (SPN) for the remote computer name and port does not exist.
  -The client and remote computers are in different domains and there is no trust between the two domains.
 After checking for the above issues, try the following:
  -Check the Event Viewer for events related to authentication.
  -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.
 Note that computers in the TrustedHosts list might not be authenticated.
   -For more information about WinRM configuration, run the following command: winrm help config. For more information, see the about_Remote_Troubleshooting Help topic.	XXX	OpenError: (XXX:String) [], PSRemotingTransportException	-2144108387,PSSessionStateBroken	[XXX] Connecting to remote server XXX failed with the following error message : WinRM cannot process the request. The following error with errorcode 0x80090322 occurred while using Kerberos authentication: An unknown security error occurred.  
 Possible causes are:
  -The user name or password specified are invalid.
  -Kerberos is used when no authentication method and no user name are specified.
  -Kerberos accepts domain user names, but not local user names.
  -The Service Principal Name (SPN) for the remote computer name and port does not exist.
  -The client and remote computers are in different domains and there is no trust between the two domains.
 After checking for the above issues, try the following:
  -Check the Event Viewer for events related to authentication.
  -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.
 Note that computers in the TrustedHosts list might not be authenticated.
   -For more information about WinRM configuration, run the following command: winrm help config. For more information, see the about_Remote_Troubleshooting Help topic.	System.Management.Automation.InvocationInfo	at Invoke-Command2, <No file>: line 49
at Resolve-DbaNetworkName<Process>, <No file>: line 207
at Invoke-ManagedComputerCommand, <No file>: line 54
at Get-DbaAgHadr<Process>, <No file>: line 50
at Enable-DbaAgHadr<Process>, <No file>: line 108
at <ScriptBlock>, <No file>: line 1	{}

**Comment by wsmelton** [comment]
@EmDBA that error indicates this is a permissions and/or PowerShell remoting issue. Whichever machine and user account you are using does not have access to run the command on the remote instance/computer.
