### ISSUE TITLE
Connect-SqlServer - Add switch for lowest supported version

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#262]
-LowestVersion (or something) ..make it an int..

8 or 2000 = SQL Server 2000
9 or 2005 = SQL Server 2005
10 or 2008 = SQL Server 2008
11 or 2012 = SQL Server 2012
12 or 2014 = SQL Server 2014

This will make it easier to support lowest version across the board

**Comment by niphlod** [comment]
this is closed via 7168ccbbedf3d49b9566664bd709d32d3184e956

**Comment by potatoqualitee** [comment]
LOL! Yall. I woke up the other day thinking I had this incredibly original idea and I was so excited to implement it. Turns out, I had the same idea nearly a year ago 😆

**Comment by potatoqualitee** [comment]
Thank you for your cleanup, @niphlod !!
