### ISSUE TITLE
New-DbaAgentSchedule throws error without any good meaning

### ISSUE THREAD

**Issue by chrgraefe** [sqlcollaborative/dbatools#2629]
## Bug Report

Try to create a schedule but because of missing parameter the command is throwing a meaningless error message.

_WARNING: [New-DbaAgentSchedule][11:28:07] Something went wrong adding the schedule. | Exception calling "Create" with "0" argument(s): "Create failed for JobSchedule 'schedule_DatabaseBackup - USER_DATABASES - FULL'. "_

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System : Windows 10
 - PowerShell Version: PS 5.1
 - SQL Server : SQL Server 2016 Dev Edition

## Steps to Reproduce

- Install Ola Hallgren Maintenance Solution
- run the following command
```
$instance = "localhost\SQL2016"
$jobUserDbFull = "DatabaseBackup - USER_DATABASES - FULL"
New-DbaAgentSchedule -SqlInstance $instance -Job $jobUserDbFull -Schedule "schedule_$jobUserDbFull" -FrequencyType Weekly -FrequencyInterval Sunday -StartDate "20170101" -StartTime "000000" -EndDate "20991231" -EndTime "235959" -Debug
```

With the additional parameter "-FrequencyRecurrenceFactor 1" the problem does not arise.

## Feature Request

Provide a check, that a parameter is missing or something like that.

**Comment by Stuart-Moore** [comment]
Was fixed in dev with merge of #2631. Should be in master now as well
