### ISSUE TITLE
Restore-DbaDatabase (Timeouts and Connection reusue)

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2634]
## Bug Report
Restore command stops on timeout.

### General Troubleshooting steps

- [X] Verified running latest release of dbatools? latest development tree for Oct.10
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 2012
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 2016 SP1+

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Additional information

 
![default](https://user-images.githubusercontent.com/14327077/32690455-1fcabf48-c708-11e7-93c0-ecc14d19e3ba.png)

**Comment by Zhunya** [comment]
![default](https://user-images.githubusercontent.com/14327077/32690541-66ee9a4c-c709-11e7-9a20-5bcbd966cabc.png)

- no progress in PS window
- tooo much connections for just restore, why not reuse connection

**Comment by Zhunya** [comment]
master tree have same bug with timeouts

**Comment by ConstantineK** [comment]
It looks like there is probably two bugs going on here, re-using connections and statement vs connection timeout.

**Comment by ConstantineK** [comment]
Looks like the statement timeout piece is due to the fact that we dont have a root level configuration item to set this, we currently recommend passing a SQL connection to your commands via Connect-DbaInstance with the -StatementTimeout parameter for the statement timeout issues at the moment.

**Comment by ConstantineK** [comment]
From the channel discussion, here is an example of that, we also generally recommend putting SOME positive integer as a timeout parameter.
```
$srv = Connect-DbaInstance -SqlInstance $SQLServer -StatementTimeout 0

Restore-DbaDatabase -SqlInstance $srv -DatabaseName "MyDB" `
       -Path "\\nas_server\SQLBackups\MyRestoreServer\MyDB" `
           -MaintenanceSolutionBackup -WithReplace -IgnoreLogBackup `
               -DestinationDataDirectory "D:\SQLData" -DestinationLogDirectory "D:\SQLData" `
                   -ErrorAction Stop (edited)
```

**Comment by Zhunya** [comment]
Seems I have black mark from Stuart =)

![default](https://user-images.githubusercontent.com/14327077/32773258-9d7635fc-c939-11e7-8244-1d9bf92bbb6a.png)

Backups made on SQL Server 2008 R2, and restoring it on SQL Server 2016 SP1.

**Comment by Stuart-Moore** [comment]
That'll be Test-DbaSqlPath spawning connections

for the LSN Chain try doing:

Restore-DbaDatabase [All you switches] -GetBackupInformation gbi

$gbi now contains the file info being passed in. Feel free to anonymise any of the values you don't want to send. Then
$gbi | export-CliXml -Depth 5 -patch c:\whatever.xml

And upload the xml file please

**Comment by potatoqualitee** [comment]
Ohhh this is what I saw over the weekend

**Comment by Stuart-Moore** [comment]
Which bit?

**Comment by potatoqualitee** [comment]
That switch I was talking about that I thought you'd potentially added

**Comment by Stuart-Moore** [comment]
Timeout issues should be a thing of the past.

Will sort out the connection reuse thing next when I've got some time.

**Comment by Stuart-Moore** [comment]
Turns out it too less time than expected. 

If anyone ( @zhunya ?) fancies taking it for a spin it's here - https://github.com/sqlcollaborative/dbatools/tree/restoreconnections

Initial testing here looks good, but want a :+1: before PRing it.

**Comment by Zhunya** [comment]
Will test asap. But not too soon. )

On 14 Nov 2017 5:38 p.m., "Stuart Moore" <notifications@github.com> wrote:

Turns out it too less time than expected.

If anyone ( @Zhunya <https://github.com/zhunya> ?) fancies taking it for a
spin it's here - https://github.com/sqlcollaborative/dbatools/
tree/restoreconnections

Initial testing here looks good, but want a 👍 before PRing it.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/2634#issuecomment-344278538>,
or mute the thread
