### ISSUE TITLE
Dbatools Config - New feature request for debugging mode

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2638]
## Feature Request

Noticed in the `Get-DbaConfig` output there is now a developer module configuration. The only one listed is `developer.mode.enable` which appears to be around the logging/message system.

### Problem to solve
We currently have the variable `$dbatools_dotsourcemodule` to utilize for having the code dot sourced into our current session. This was added some time back to appease those of that want to debug the module using PowerShell debug engine.

Can we have this variable added into the configuration? Either one of two options would suite me:

1. Just have it be part of the current `developer.mode.enable` so when that is enabled it adds the advanced logging **AND** ensures code is dot sourced.
2. Add another configuration under the developer module as something like `developer.mode.dotsource` maybe?

**Comment by FriedrichWeinmann** [comment]
Heya, it's technically doable, but might be a bit unintuitive.
You see, module import happens _before_ the configuration system is ready to rock.

I can work around that though and it won't affect performance.

**Comment by FriedrichWeinmann** [comment]
And there you go: https://github.com/sqlcollaborative/dbatools/pull/2639
Added a now configuration scope though, since those are the import options after all (even though some of them are useful to developers only)
