### ISSUE TITLE
 Test-DbaDatabaseOwner and unknown login

### ISSUE THREAD

**Issue by chrgraefe** [sqlcollaborative/dbatools#2649]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: PS 5.1
 - SQL Server (Edition|Version): SQL2016/DEV

## Steps to Reproduce
Run this command:
 Test-DbaDatabaseOwner -SqlInstance localhost\SQL2016 -TargetLogin UnknownUser

Result:
Invalid login: UnknownUser
At line:91 char:6
+                     throw "Invalid login: $TargetLogin"
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Invalid login: UnknownUser:String) [], RuntimeException
    + FullyQualifiedErrorId : Invalid login: UnknownUser

## Feature Request
Catch error with a better error message

**Comment by sanderstad** [comment]
This item seems to be resolved in the latest version of dbatools
![image](https://user-images.githubusercontent.com/6154981/39762566-43d65f1e-52db-11e8-8398-ad8000126189.png)
