### ISSUE TITLE
Request new command: Start-DbaExport

### ISSUE THREAD

**Issue by milawd** [sqlcollaborative/dbatools#2655]
## Feature Request

The purpose of Start-DbaExport is to export an entire instance of SQL Server to a file. This is useful for source control purposes or even "dataless" migration purposes. 

### Problem to solve
Ability to create a dataless export of a SQL Server instance or instances for source control or migration purposes

**Comment by niphlod** [comment]
https://docs.dbatools.io/#Export-DbaScript was born. Feel free to reopen in case you're missing something from it
