### ISSUE TITLE
Set-DbaMaxDop fails due to missing instance name

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#2657]
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System: Win10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 2016 SP1 Dev Edition

## Steps to Reproduce
1. Execute `Test-DbaMaxDop` against instance
2. Execute `Set-DbaMaxDop` against the same instance with the recommended `MaxDop` setting
3. Receive warning/error. `MaxDop` isn't set.

```
C:\...\_Projects\Server Config>Test-DbaMaxDop -SqlInstance 'SERVER\INSTANCE'


ComputerName          : SERVER
InstanceName          : INSTANCE
SqlInstance           : SERVER\INSTANCE
Database              : N/A
DatabaseMaxDop        : N/A
CurrentInstanceMaxDop : 4
RecommendedMaxDop     : 8
Notes                 : Before changing MaxDop, consider that the lower value may have been intentionally set.



C:\...\_Projects\Server Config>set-DbaMaxDop -SqlInstance 'SERVER\INSTANCE' -MaxDop 8
WARNING: Can't connect to @{Instance=} or access denied. Skipping.
C:\...\_Projects\Server Config>
```

Per @FriedrichWeinmann  in Slack, `Set-DbaMaxDop` calls `Test-DbaMaxDop` internally and is attempting to use the `Instance` property which is not returned by `Test-DbaMaxDop`

**Comment by josh-simar** [comment]
Logged a fix I hope works for this.
