### ISSUE TITLE
Copy-DbaCredential needs some loving

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2662]
its just not working for me, at least local (as admin). you can see the incorrect (empty) tsql being passed in -Debug

**Comment by schafjoe** [comment]
I was looking at this issue. On line 343, if I can change the Where-Object { $_.Credential -eq $credentialName } to Where-Object { $_.Credential -eq "[$credentialName]" }, the function works.
The reason for this is that the Credential has the brackets around it and the $credentialName does not.

**Comment by potatoqualitee** [comment]
awesome, please do @schafjoe !

**Comment by schafjoe** [comment]
@potatoqualitee, I have never done this. I was testing on my system when I discovered the fix.

**Comment by potatoqualitee** [comment]
Do you need assistance creating a PR? We have a couple tutorials and are available on #dbatools in Slack

For dbatools specific PR tutorials, you can find the one that suits your style at https://dbatools.io/contributing/

**Comment by schafjoe** [comment]
I am unable to install any GitHub tools on my system and I currently do not have time to do this. The credit for the fix does not mean much to me. Go ahead and do the PR yourself.

**Comment by potatoqualitee** [comment]
heck yeah, that worked, thanks!
