### ISSUE TITLE
Get-DbaRegisteredServer, returning only blank rows

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#2667]
## Bug Report
I have a script which relies on `Get-DbaRegisteredServer` that has stopped working. When I try this command interactively in the ISE, I still can't get anything out of it, other than blank rows.

### General Troubleshooting steps

- [x] Verified running latest release of dbatools? (0.9.98)
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session? (clean install of dbatools and fresh ISE session running as admin)

### Version Information
- Operating System (Name|Version): Windows 7 SP1 x86
- PowerShell Version: 5.0.10586.117
- SQL Server (Edition|Version): Multiple (see below)

## Steps to Reproduce
Use a Central Management Server on one of the versions I have tested below:

- SQL Server 2008 R2
- SQL Server 2016
- SQL Server 2017

I have tried the following:

- Creating a new CMS on each of the versions above
- Creating a few entries into each CMS at the root
- Creating a few entries into each CMS inside a top level group
- Creating a few entries into each CMS inside a sub level group (such as test\test2)

All I ever get is blank rows, which total the number of expected rows, with the headings of Mode and Name.

**Comment by potatoqualitee** [comment]
does it work with the console? I am unable to repro :(

![image](https://user-images.githubusercontent.com/8278033/32841993-39e889ca-ca1c-11e7-98d9-8e34e4bfd63b.png)

**Comment by dansqldba** [comment]
Disregard, taking a sledgehammer to it all (for a third time) seems to have fixed it !@#
