### ISSUE TITLE
Feature Request: DisplayName data in Find-LoginInGroup 

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbatools#2671]
## Feature Request

Add DisplayName field to Find-DbaLoginInGroup output.

### Problem to solve

Often times AD usernames are not consistent or clear as to who/what they exactly map to. Adding in the DisplayName property adds more useful information to be able to act on when pulling up all the AD users in a database.

### Additional information

I have this implemented locally already - if this feature req is approved I will open a PR to add it to the script. 

![image](https://user-images.githubusercontent.com/16843041/32858411-64b27074-ca19-11e7-97cd-3a199c9f33d0.png)

**Comment by niphlod** [comment]
it could be the entry for "let's add firstname and lastname too, and canonicalname, and distinguishedname" ... being a tool for dba, that work with samaccount name format exclusively, I'd be against having that outputted by default. A better way would be to return the member object (hidden) which can be later properly managed

`Find-DbaLoginInGroup -sqlinstance localhost | % {  select $_.SqlInstance, $_.member.FirstName   }` can be added as example to let user start grasping the added feature.

**Comment by LowlyDBA** [comment]
I agree about adding all the others as well, but I wonder if breaking out first/last from DisplayName gets too dicey when you figure in the many potentially (undetectable) variations (first, last; last, first; first last; last first; last, first middle_initial; etc.)

**Comment by niphlod** [comment]
that's why it's better to return a hidden `member` object that everybody can then query to each own tailored set of properties.

**Comment by LowlyDBA** [comment]
Yeah, I agree on that as well - just wanted to address your example that was using a FirstName field, which I think would be pretty difficult to actually have available. I'll open up a PR soon based on the above. Thanks for the feedback

**Comment by niphlod** [comment]
whooopsie, got it. use $_.member.DisplayName by all means in the example ^_^

**Comment by potatoqualitee** [comment]
I kinda do like the DisplayName and would find that useful for myself.
