### ISSUE TITLE
Restore-DbaDatabase: -IgnoreLogBackup is not ignoring log backups and broken LSN chain

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2674]
## Bug Report
- `IgnoreLogBackup` is not working, and we get broken LSN chain (see screenshot *1)
- If `IgnoreLogBackup` not used, database restored w/o error
- If `OutpuScriptsOnly` with `IgnoreLogBackup` restore finished normally in SSMS

### General Troubleshooting steps

- [X] Verified running latest release of dbatools - 0.9.100
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Restore database from SQL Server 2008R2 to SQL Server 2016 SP1

## Steps to Reproduce
*1
![default](https://user-images.githubusercontent.com/14327077/32879191-0de8c2ce-caba-11e7-8858-c036b7c8501c.png)

**Comment by Stuart-Moore** [comment]
Any chance of the actual LSNs involved? quickest way is

Restore-DbaDatabase -<Your Parameters) -SelectBackupInformation sbi
-StopAfterSelectBackupInformation
$sbi | Export-CliXML -Depth 5 -Patch c:\paths\somthing.xml

and send me the xml file. If you want to hide data in $sbi, then that's
easy enough todo as long as dates, types and LSNs are not altered

**Comment by Zhunya** [comment]
Still working to give you as much info as I can, sorry for delay.

**Comment by Stuart-Moore** [comment]
Actually, send me before and after:

Restore-DbaDatabase -<Your Parameters) -GetBackupInformation gbi
-SelectBackupInformation sbi -StopAfterSelectBackupInformation
$sbi | Export-CliXML -Depth 5 -Patch c:\paths\somthing.xml
$gbi | Export-CliXML -Depth 5 -Patch c:\paths\somthingElse.xml

Then I can see what's missing or if it was missing earlier.

**Comment by Stuart-Moore** [comment]
No worries on time! Once I've got that data I can fix it, and shove some
tests in so it doesn't break again

Going to get the CDC stuff out of the way first, then look at this stuff.

**Comment by Zhunya** [comment]
Sent you .zip in Slack with two results, more testing to go with other switches )

**Comment by Zhunya** [comment]
Sent you second xml where i get error with LSN chain due to "empty" TLOG files.

![default](https://user-images.githubusercontent.com/14327077/32887267-65699f72-cad4-11e7-93b2-8983e8b48f0d.png)

**Comment by Stuart-Moore** [comment]
The first screenshot, is that from a  newer version of SQL Server for you? 

The new stuff uses the same filtering for empty logs, but it looks like SQL is complaining about restoring just one empty file which used to work (or at least was signed off on). I can fix it, just strange that it's now an issue.

now going to look at the next one

**Comment by Zhunya** [comment]
I'm restoring backups from older version to newer (2008R2 > 2016SP1)

**Comment by Zhunya** [comment]
I have another DB on 2008R2, and restore process runs w/o errors

**Comment by Stuart-Moore** [comment]
So that error was restoring from 2008r2 -> 2016sp1?

Does the same command error if going 2008r2 -> 2008r2?

If it does it's a versioning error. Hopefully the new fix would work with the old system, but I'd need you to test it as we don't have any other real test rigs that have the empty t-log issue.

Basically I'd filter out everything with $_.FirstLsn -eq $_.LastLsn, and we should still have a good chain. It's just that we don't do that atm and it's quite a big change without a reliable AppVeyor test :(

**Comment by Zhunya** [comment]
I tryed to restore to same server, as we can see, Get-DbaBackupHistory gives wrong result at start

![default](https://user-images.githubusercontent.com/14327077/32966895-698119aa-cbec-11e7-9f61-93fab3805fd5.png)

**Comment by Zhunya** [comment]
And one more test with -Path switch with LSN error and empty file names in error message
![default](https://user-images.githubusercontent.com/14327077/32967265-04b93974-cbee-11e7-828c-275233971740.png)

Above two test was on source server 2008 R2

**Comment by Stuart-Moore** [comment]
Will add Get-DbaBackuphistory to the list of things to fix

Just pushed up a branch called restorelsn. Can you give that one a go please. Passes tests here, but those aren't 'real world'.

**Comment by Zhunya** [comment]
ok

**Comment by Stuart-Moore** [comment]
Thanks. It's going to ignore completely any logs with firstlsn=lastlsn, which should break anything, but is different to how we were doing things.

If that works, I'll back port it into history

**Comment by Zhunya** [comment]
WARNING: Test-DbaLsnChain - Break in LSN Chain between
D:\SQL_BACKUP\SRV1\v8_VDUPP\FULL\SRV-1C-VKD_v8_VDUPP_FULL_20171119_220024.bak and
D:\SQL_BACKUP\SRV1\v8_VDUPP\LOG\SRV-1C-VKD_v8_VDUPP_LOG_20171119_221700.trn
WARNING: [Restore-DbaDatabase][17:45:33] tsts_v8_VDUPP failed testing, AllowContinue not set, exiting

Sent you new portion with GBI and SBI info

**Comment by Stuart-Moore** [comment]
Thanks, have pushed a small update up to that branch that should fix that error.

Once I've got something that works I need to work out if we've broken anything else with it as well

**Comment by Zhunya** [comment]
Working now, will test more tomorrow.

**Comment by Zhunya** [comment]
Cloosind
