### ISSUE TITLE
Restore-DbaDatabase: Feature Request - add file counter to progress

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2675]
## Feature Request

User may want to know how much files restored, for big TLOG files its maybe useful to see when restore process finished (%

### Problem to solve

Be informed on how process going

**Comment by Stuart-Moore** [comment]
Rolling this into you other issue as it's fairly simple

Going with "Backup x of y" as an addition to the progress bar. That OK?

**Comment by Zhunya** [comment]
Yeah! It ok =)

**Comment by Stuart-Moore** [comment]
Cool, will close this now
