### ISSUE TITLE
Start-SqlMigration error SQL 2000 to 2008R2

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#268]
I was able to successfully migrate all my databases except 1 database on the start-sqlmigration command.  The backup went fine and I was able to manually restore the backup that was created.  It's just the restore failed.  This is the error that I received in the error log.  Please let me know if you want me to test something or need more information.

10/17/2016 10:06:44 AM
C:\Users\dczarny\Documents\WindowsPowerShell\Modules\dbatools\functions\Copy-SqlDatabase.ps1
At C:\Users\dczarny\Documents\WindowsPowerShell\Modules\dbatools\functions\Copy-SqlDatabase.ps1:395 char:5
-                 $restore.sqlrestore($server)
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  System.Management.Automation.MethodInvocationException: Exception calling "SqlRestore" with "1" argument(s): "Restore failed for Server 'DFWQPPNSQL01'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Restore failed for Server 'DFWQPPNSQL01'.  ---> Microsoft.SqlServer.Management.Smo.SmoException: System.Data.SqlClient.SqlError: Directory lookup for the file "E:\MSSQL7\Data\Response_Info.Ndf" failed with the operating system error 3(The system cannot find the path specified.).
  at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQueryWithMessage(StringCollection queries, ServerMessageEventHandler dbccMessageHandler, Boolean errorsAsMessages)
  at Microsoft.SqlServer.Management.Smo.BackupRestoreBase.ExecuteSql(Server server, StringCollection queries)
  at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
  --- End of inner exception stack trace ---
  at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
  at CallSite.Target(Closure , CallSite , Object , Object )
  --- End of inner exception stack trace ---
  at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
  at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by dczarny** [comment]
I think I found out more on this error.  the database I am restoring from SQL Server 2000 had a secondary data file.  Around line 836, there is a check for source version.  If the version is SQL Server 2000, this query gets run $sql = "select DB_NAME (dbid) as dbname, name, filename, CASE WHEN groupid = 1 THEN 'ROWS' WHEN groupid = 0 THEN 'LOG' END as filetype from sysaltfiles".  The issue is if the secondary data file is in a different filegroup, that case statement returns NULL instead of ROWS.  Can we just put CASE WHEN groupid >=1 ...?

**Comment by ClaudioESSilva** [comment]
Yes @dczarny at least that query need to change.
I suggest to write the query as the following:
`select DB_NAME (dbid) as dbname, name, filename, CASE WHEN groupid = 0 THEN 'LOG' ELSE 'ROWS' END as filetype from sys.sysaltfiles`

If you can test it, please change your .ps1 script save and Import again the module.
Thanks!

**Comment by dczarny** [comment]
I am making your change and will test it.  I will let you know the results.  Thanks.

**Comment by dczarny** [comment]
Worked perfectly.

**Comment by ClaudioESSilva** [comment]
Thanks @dczarny 
Excellent! 
Do you want to do a pull request and correct the issue?

**Comment by dczarny** [comment]
I haven't done that yet.  I am taking baby steps.  Is there any documentation I can follow to fix it?

**Comment by ClaudioESSilva** [comment]
@dczarny Are you already on #slack?
Please join SQLCommunity. Enter yout email here https://dbatools.io/slack and you will receive an invite.
Join on #dbatools channel and someone will guide you helping doing your first pull request! :smile:

**Comment by ctrlbold** [comment]
@dczarny you can also follow this step-by-step tutorial. This would be a really easy straightforward first Pull Request :D 

https://github.com/sqlcollaborative/dbatools/wiki/Your-First-Pull-Request

**Comment by niphlod** [comment]
got fixed in the meantime, closing (but @dczarny feel free to reopen if I'm wrong  )
