### ISSUE TITLE
export-dbalogin doesn't work correctly if there's a mismatch between login name and user name

### ISSUE THREAD

**Issue by Tonyw72** [sqlcollaborative/dbatools#2680]
- [0.9.100] Verified running latest release of dbatools? 
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

## Steps to Reproduce
When running export-dbalogin and there's a mismatch between the login name and the database user name, the roles and other permissions aren't traversed and added to the output string.

I believe these can be fixed by replacing $username with $dbUserName on the following lines

343:
if ($role.EnumMembers() -contains $dbUserName) {  #was username

345:
$outsql += "ALTER ROLE [$roleName] ADD MEMBER [$dbUserName]" #was userName

350:
$perms = $sourceDb.EnumDatabasePermissions($dbUserName) # was userName

364:
$outsql += "$permState $permType TO [$dbUserName] $grantWithGrant AS [$grantor]" #was userName

**Comment by ClaudioESSilva** [comment]
Hi, @Tonyw72 thanks for your troubleshooting and report.
I have done the changes (they are on PR #3004).

**Comment by Tonyw72** [comment]
Looks good to me.
Many thanks !
