### ISSUE TITLE
Retain Destination permissions with Copy-DBADatabase

### ISSUE THREAD

**Issue by KennyNeal** [sqlcollaborative/dbatools#2681]
## Feature Request

Can a switch be added to retain the users and permissions from the destination database when it's replaced using Copy-DbaDatabase? 

### Problem to solve
Users and permissions differ between prod, test, and dev instances. It would be nice if the copy process could extract the permissions from the destination and then replace them after a successful restore.

**Comment by niphlod** [comment]
From a design standpoint, Copy-DbaDatabase should not ever care about users and permissions. It *copies* a database. You are in the need of a *migrate* database, users and permissions, which involves several steps... let's see what they could be and discuss those, as I'm not sure there really is a "one way to do it" properly:
- take note of login-->user mappings on the dest
- take note of permissions (which can be granted to the user itself or a role a user is in) on the dest
- copy-dbadatabase from source to dest
- drop every role to the newly created database on dest
- recreate the roles, with the permissions
- recreate users tied to logins and assign membership to the roles

And the long list of problems begin (we need to untangle those before deeming such "feature" possible): 
- what to do in case user A in mapped to login B which has a server role permission on dest but not in source ? do we need to keep login B on dest in sync with the source ?
- if environments are different, are you sure that the only different thing is permissions ? What about when you need to port a new version of the database from prod to test to do a regression test and developers need a less strict set of permission to be able to debug ?
- usually prod has the least possible number of users, test has more, dev more (prod is accessed only by apps, test from apps and testers/devs, dev by pretty much everything). Are you happy with leaving orphan users behind ? Then you can manage things just rebinding logins to users ?


IMHO, if you are in charge of maintaining a different set of permissions between prod test and dev, the only *safe* way to do so would be to have a standard set of roles with each own the needed permission and map users to different memberships between envs (the method is called RBAC). 
Database permissions are stored with the database, with all the needed roles available in all environments. You manage different needs managing a different set of memberships on different envs.
You can keep things *clean* removing orphan users, but from a security standpoint you don't need to handle those.
If you don't follow the RBAC rule, I think for *some* usecases you can just use Export-DbaUser/Get-DbaPermission and reapply that script after the restore. Then you just need to remap logins to users ?!

Please take this not as a "it's a big no-no" (except for the fact this *feature* won't live in Copy-DbaDatabase) but a possibility for everyone to chime in and tell their story (and/or provide their solution).
We can eventually "fill the void" with an helper command that you can just rig pre and post copy-dbadatabase.

**Comment by potatoqualitee** [comment]
agreed that this would be a post-migration command
