### ISSUE TITLE
Issue : Error in Get-DbaDiskSpace

### ISSUE THREAD

**Issue by EmDBA** [sqlcollaborative/dbatools#2686]
## Bug Report

There is a bug in Get-DbaDiskSpace
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 2012 R2 Standard + 2016 Standard
 - PowerShell Version: 5.1.14393.1613
 - SQL Server (Edition|Version): 2012 Enterprise + 2016 Enterprise

## Steps to Reproduce
PS C:\> Get-DbaDiskSpace -ComputerName SERVERNAME
WARNING: Get-DbaDiskSpace - Cannot connect to WMI on SERVERNAME.

### Additional information

[Get-DbaDiskSpace.log](https://github.com/sqlcollaborative/dbatools/files/1482275/Get-DbaDiskSpace.log)

The strange part is here where we see that he tries to add the suffix of another domain controller.
My desktop is in domainA and the server is in domainB. We have a full trust between the domains.

[dbatool.log](https://github.com/sqlcollaborative/dbatools/files/1481480/dbatool.log)

**Comment by niphlod** [comment]
hum: get-Dbadiskspace doesn't use resolve-dbanetworkname  ?! what version are you on ?

**Comment by EmDBA** [comment]
0.9.65

**Comment by EmDBA** [comment]
After multiple check it's related to the firewall, don't forget to open the icmp between your client and the server

**Comment by EmDBA** [comment]
This issue is corrected in #2427

**Comment by wycislo** [comment]
When I execute get-dbadiskspace on the server I get failed to connect to <servername>. | invalid class

I have opened icmp - no joy (not sure how firewall setting affects diskspace commands)


get-dbadiskspace <servername>
WARNING: [09:25:06][Get-DbaDiskSpace] Failed to connect to <servername> | Invalid class

[environment]::osversion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.14393.0 Microsoft Windows NT 10.0.14393.0

**Comment by potatoqualitee** [comment]
hey @wycislo  -- please create a new issue with the required details. It'll help us solve this issue. this command needs acesss wo WMI/CIM i believe. When you open the new issue, please let me know if you can connect using invoke-command -computer

**Comment by wycislo** [comment]
When I try to connect to this server from a remote computer (my laptop). The error message is [Get-DbaDiskSpace] Failed to connect to <servername> | the specified class does not exist in the given namespace.

**Comment by wycislo** [comment]
Test-DbaCmConnection -ComputerName <myservername> -Credential $ServerCredential -Type CimDCOM, CimRM
Returns: 
ComputerName Available User             Override DisabledConnectionTypes
------------ --------- ----             -------- -----------------------
#########                             Wmi, PowerShellRemoting

Somehow WMI, powershellremoting are disabled connection types.
