### ISSUE TITLE
Functionality Request: New Features

### ISSUE THREAD

**Issue by forensicsguy20012004** [sqlcollaborative/dbatools#270]
Hello All...first I want to say what an AWESOME project this is...you all do outstanding work. 

Is there a potential for a new functions that CREATE as apposed to copy/migrate/test? If I missed it I apologize, but was looking for something like CREATE-Database, if I missed, I am sorry.

Second, most Github MSSQL server projects that I am on do not take into account AlwaysOn configurations or clustered instances in a multi-subnet. With that said...if they team is willing to discuss a new function like CREATE-Database ... I believe it would be best for it to be AlwaysOn "ready" and cluster "ready."

Like I mentioned, I might have missed some of the AlwaysOn functionality in the current functions...I apologize.

Thank you for your time and effort...this project is AWESOME, I use the functions daily and think this is one of the most agile teams I have seen.

Thanks,
Matt

**Comment by wsmelton** [comment]
Matt, thanks for the feedback. This is actually a command more suited for Microsoft's module, sqlserver. It has actually been submitted to them on the trello board as New-Database:

https://trello.com/c/c5H9VJxA/28-new-sqldatabase

**Comment by forensicsguy20012004** [comment]
@wsmelton ....Cool thank you very much good sir. If you want you can close this issue/comment. I am good with it. :)

Matt

**Comment by dansqldba** [comment]
Thanks for the kind words @forensicsguy20012004 :)
