### ISSUE TITLE
Start-BitsTransfer while copying database from one server to another server using copy-dbadatabase cmdlet

### ISSUE THREAD

**Issue by suganthanraj** [sqlcollaborative/dbatools#2702]
### Version Information
 - Operating System (WINDOWS SERVER 2012 R2)
 - PowerShell Version: 4.0
 - SQL Server (2012 Enterprise Edition): 

## Steps to Reproduce

I need to migrate database from Server1 to server2. I used copy-DbaDatabase cmdlet to migrate database by detachattach parameter. when i executing this command i got this below error

Start-BitsTransfer : Access is denied.
At line:565 char:7
+                         Start-BitsTransfer -Source $from -Destination $remotefilename
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand
 
Start-BitsTransfer : Access is denied.
At line:565 char:7
+                         Start-BitsTransfer -Source $from -Destination $remotefilename
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand
 
WARNING: [Mount-SqlDatabase][23:24:55] Issue mounting database. | Exception calling "AttachDatabase" with "4" argument(s): "Attach database failed for Server 'WIN-SQL-NODE1\SQLDEV1'. "
![copydbadatabase-cmdlet](https://user-images.githubusercontent.com/3103064/32993760-9694f26c-cd82-11e7-8f76-02fcf24c6e6a.png)
![error](https://user-images.githubusercontent.com/3103064/32993761-96e039a2-cd82-11e7-8cf3-2f6f66f72900.png)

 Copy-DbaDatabase -Source $srcInstance -SourceSqlCredential $srcCreds -Destination $descInstance -DestinationSqlCredential $descCreds -Database $dbName -DetachAttach

        Copy-DbaLogin -Source $srcInstance -SourceSqlCredential $srcCreds -Destination $descInstance  -DestinationSqlCredential $descCreds  -Login $dbUsers

Eventhough i used Sql login credential for both servers server1 and server2

**Comment by wsmelton** [comment]
The file level permissions have to be there to copy the files from one server to another. So if the login running the command does not have permissions to each location then the transfer of the files can't be done.

**Comment by suganthanraj** [comment]
Need to set file level permissions manually or can set through cmdlets itself.. So for each file have to set file level permissions. Is there any optional parameter in dbatools modules inbuilt to set file level permissions?

**Comment by wsmelton** [comment]
No ability to control file level access in dbatools. Regardless the account executing the command has to have the rights to read/write to the destination. If your account has that access then the Bit transfer command should work as expected.

The detach/attach method requires file level access in order to work. The SQL Login credential you passed in is simply to access SQL Server, it is not used to access the physical file location of the files which is required to copy them.

**Comment by suganthanraj** [comment]
@wsmelton There is no alternative for this operations.... I need this operation to work as expected.. Can you suggest any alternative for this operations

**Comment by wsmelton** [comment]
1. `Backup-DbaDatabase` to a directory for the source instance.
2. Copy that backup file to a directory the destination has access (SQL Server service account)
3. `Restore-DbaDatabase` pointing at that destination path for the backup.
