### ISSUE TITLE
SQL Server 2000 does not have a sys schema and some commands use sys.xp_ in calling

### ISSUE THREAD

**Issue by ConstantineK** [sqlcollaborative/dbatools#2705]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
All
 - PowerShell Version: 
All
 - SQL Server (Edition|Version): 
2000

## Steps to Reproduce

On SQL 2000 Restore-DbaDatabase attempts to enumerate the file system with xp_dirtree and qualifies the command with the sys schema, which does not work in SQL 2000

### Problem to solve

We may need some additional testing to detect this condition in our code, but this is more static analysis than BDD type stuff.

Would this make more sense as a custom linter thing (eg psanalyzer) or even though its more related to static analysis does it makes sense to stick it in the standard test functions?

**Comment by ConstantineK** [comment]
@pollusb reported this issue this morning, it looks like this issue has a fairly narrow scope.

https://github.com/sqlcollaborative/dbatools/search?l=PowerShell&q=%22.sys.xp%22&type=&utf8=%E2%9C%93

**Comment by potatoqualitee** [comment]
Thanks, @ConstantineK !
