### ISSUE TITLE
Read-DbaBackupHeader on SQL 2000 fails to to missing DatabaseBackupLsn

### ISSUE THREAD

**Issue by ConstantineK** [sqlcollaborative/dbatools#2707]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
All
 - PowerShell Version: 
All
 - SQL Server (Edition|Version): 
SQL 2000

## Steps to Reproduce

Read-DbaBackupHeader on a SQL 2000 box file will fail to populate the header information with a DatabaseBackupLsn because RESTORE HEADERONLY on SQL 2000 doesnt contain that column, and we are simply projecting all the values available, This then flows down the line to cause failures in several commands when working with SQL 2000 backups. 

Example database backup headers from SQL 2000 database issue was reported from:
```
BackupName    NULL
BackupDescription    NULL
BackupType    1
ExpirationDate    NULL
Compressed    0
Position    1
DeviceType    2
UserName    Expungedusername
ServerName    Expungedserver
DatabaseName    Expungeddatabase
DatabaseVersion    539
DatabaseCreationDate    2013-05-29 18:01
BackupSize    3084800
FirstLsn    2.39E+17
LastLsn    2.39E+17
CheckpointLsn    2.39E+17
DifferentialBaseLsn    2.39E+17
BackupStartDate    2017-11-20 10:18
BackupFinishDate    2017-11-20 10:18
SortOrder    0
CodePage    228
UnicodeLocaleId    1036
UnicodeComparisonStyle    196609
CompatibilityLevel    80
SoftwareVendorId    4608
SoftwareVersionMajor    8
SoftwareVersionMinor    0
SoftwareVersionBuild    2066
MachineName    Expungedmachinename
Flags    0
BindingId    {03346492-8277-46FA-967A-FACD3FEC6073}
RecoveryForkId    {03346492-8277-46FA-967A-FACD3FEC6073}
Collation    French_CI_AS
```

This also needs to be tested on SQL 2005 as the MSDN docs say that they only currently apply to SQL 2008 and later.

### Problem to solve
We will need to figure out which one of these fields we want to use for this downstream stuff to work properly when restoring databases in SQL 2000.

if it is all in doubt across versions we might want to start making sure we enumerate required values instead of just taking the output of an SMO method, but that does add some extra complexity.

**Comment by niphlod** [comment]
@Stuart-Moore : I feel this has been already done but please check and, in case, close ^_^

**Comment by Stuart-Moore** [comment]
restore headeronly is broken in sql2000. The agreed fix (cl approved) was that you'll need to do something like:
```
$BackupHistory = Get-DbaBackupInformation -SqlInstance sql2005 -Path \\backups\sql2000\ProdDb
$BackupHistory | Restore-Dbadatabase -SqlInstance sql2000 -TrustDbBackupHistory
```
