### ISSUE TITLE
Get-DbaDbVirtualLogFiles

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#2709]
## Bug Report

Examples aren't accurate

### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server
 - PowerShell Version: 5.1.14393.1532
 - SQL Server (Edition|Version): 2012

## Steps to Reproduce
`get-help Get-DbaDbVirtualLogFile -e`

![image](https://user-images.githubusercontent.com/981370/33039065-b9751bf4-ce04-11e7-8c5e-557e0d016424.png)

## Feature Request
I can update this - just wanted to make sure it was agreed upon this was an issue, I believe it should state the the VLF details are returned not number of VLFs, perhaps we could add an example that pipes into Group-Object to get counts per database.

**Comment by jpomfret** [comment]
@gbargsley can you test this and confirm?

**Comment by gbargsley** [comment]
I am not sure of the question.  Are you saying the examples are not worded properly for the output expected?

**Comment by jpomfret** [comment]
Yeah, maybe I'm wrong. I looked at the help and saw I was going to get 'all user database virtual log file counts' so was suprised when I got a more raw output of an object containing all the VLFs, I had to pipe to a Group-Object to get the database - count format I was expecting.
