### ISSUE TITLE
copy-sqlLogin error

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#271]
I found an error with the Copy-SqlLogin.ps1 that is causing me some problems copying SQL Logins from SQL Server 2000 to 2008R2.  After looking at it, on linke 285 where the $sqlfailsafe variable is building a string to create the login, there is another variable reference $language.  I don't see that variable created or referenced anywhere else in the code.  This is the error I am receiving.  When I hard code the $language variable to English, my error goes away.

C:\Users\dczarny\Documents\WindowsPowerShell\Modules\dbatools\functions\Copy-SqlLogin.ps1
At C:\Users\dczarny\Documents\WindowsPowerShell\Modules\dbatools\functions\Copy-SqlLogin.ps1:287 char:9
+                                 $null = $destserver.ConnectionContext.ExecuteNonQuery($sqlfailsafe)
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.MethodInvocationException: Exception calling "ExecuteNonQuery" with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch." ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )

**Comment by ConstantineK** [comment]
Good catch!
I took a look and it appears that you are right,  $language isn't used again, but language is referenced in the following way: `$destlogin.Language = $sourcelogin.Language` to ensure they match.

I think replacing all instances of `$language` with `$($sourcelogin.Language)` would effectively do what is intended, I can shoot that off in a minute.

**Comment by dczarny** [comment]
I got this message yesterday when testing a start-migration.  Is this related to the change made?  I don't get the same error message when I just run copy-sqllogin for a couple of accounts.

Start-SqlMigration : Login migration reported the following error Cannot validate argument on parameter 'destlogin'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again. 
At line:1 char:1
+ Start-SqlMigration -Source PPNTEST.emsinet-test.com -Destination DFWQPPNSQL01.em ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Start-SqlMigration

**Comment by ConstantineK** [comment]
Talked to @dczarny in slack, looks like this issue may have arisen due to some side effects, after updating it went away. Going to look at the other login issues.
