### ISSUE TITLE
Update-dbatools failing to update all folders/files of the module via zip download (not Gallery)

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#2714]
## Bug Report
Last week, I was trying to resolve an issue with a script I'd written which relied on dbatools. The latest version would resolve my issue, so I updated with Update-dbatools, as I've always done.

The code which would fix my problem was not finding its way onto my machine via the updater, despite the module reporting back as the version expected and the update process not throwing any errors. 

In the end, I had to completely remove dbatools and start again. This resulted in an installation of the module where the contents matched what is hosted on GitHub, as expected, with most/all files timestamped 14/11/2017 at 18:46pm GMT.

In `C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\functions` the timestamps on the files, prior to the complete removal of the module, were from July 2017. This did not match the timestamps on the files in the root of the module, which unfortunately I didn't note down. This made me wonder if Update-dbatools had stopped working at some point, even though I've been running it for months. 

The psd1 file also contained the correct version, which is why the update and Get-Module were reporting the version as recent.

I put this down to months of updating and mucking around, while I was doing QA for the team and so on, constantly overwriting the module and other mad things, so a fresh start seemed like a good idea.

Today, I see there's been a new version released, so I ran Update-dbatools again. The same thing is still happening for me, it seems the contents of the root folder `C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\` **are** getting updated with the contents of the zip folder which is being downloaded, but anything _below_ that (functions, internal etc) are not. This results in a module which is reporting to be a newer version than it actually is, because only the contents of the root of the module are being updated by the zip extraction/copy!

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions? (TBC)
- [x] Can duplicate in new/fresh PowerShell.exe session? (TBC)

### Version Information
 - Operating System (Name|Version): Windows 7 Pro x86
 - PowerShell Version: 5.0

## Steps to Reproduce
You need to have installed the module via `Invoke-Expression (Invoke-WebRequest -UseBasicParsing https://dbatools.io/in)` then try to update it using `Update-dbatools`. You won't see any failures, as the `install.ps1` file which handles the updates uses `-ErrorAction SilentlyContinue` on pretty much everything to bury exceptions.

Line 99 should be the offending line, you can remove the `-ErrorAction SilentlyContinue` and run `Update-dbatools` to observe it is failing to overwrite subfolders/files.

You can also reproduce this at the command line with just `Move-Item` and a few files/folders of your own creation to observe the same behaviour.

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Additional information
- The initial installation wasn't done via the Gallery
- Haven't tried different branches, didn't realise that was a thing until just now
- No errors are being thrown, not sure the process of extracting the zip or copying the files has any error handling anyway? Things appear to be buried by `-ErrorAction SilentlyContinue`
- Running from PowerShell ISE (Administrator)
- Admin of my local machine

**Comment by wsmelton** [comment]
If you are working on it we might want to add some debug options.

The item that would "overwrite" the files would be on line 99, `Move-Item` command. We do a `-Force` so it should work but don't have set up to test that right now.

**Comment by dansqldba** [comment]
I don't have the time until Friday to give this the effort it requires, but I did just check over the code again in my lunch break. The `Move-Item` line you mention has `-ErrorAction SilentlyContinue` so I simply took that out, then ran `Update-dbatools` again.

```
Move-Item : Cannot create a file when that file already exists.
At C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\install.ps1:99 char:1
+ Move-Item -Path "$temp\dbatools-$branch\*" $path -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Daniel...-master\.github:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
 
Move-Item : Cannot create a file when that file already exists.
At C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\install.ps1:99 char:1
+ Move-Item -Path "$temp\dbatools-$branch\*" $path -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Daniel...ools-master\bin:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
 
Move-Item : Cannot create a file when that file already exists.
At C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\install.ps1:99 char:1
+ Move-Item -Path "$temp\dbatools-$branch\*" $path -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Daniel...aster\functions:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
 
Move-Item : Cannot create a file when that file already exists.
At C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\install.ps1:99 char:1
+ Move-Item -Path "$temp\dbatools-$branch\*" $path -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Daniel...master\internal:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
 
Move-Item : Cannot create a file when that file already exists.
At C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\install.ps1:99 char:1
+ Move-Item -Path "$temp\dbatools-$branch\*" $path -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Daniel...master\optional:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
 
Move-Item : Cannot create a file when that file already exists.
At C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\install.ps1:99 char:1
+ Move-Item -Path "$temp\dbatools-$branch\*" $path -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Daniel...ls-master\tests:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
 
Move-Item : Cannot create a file when that file already exists.
At C:\Users\DanielAlexander\Documents\WindowsPowerShell\Modules\dbatools\install.ps1:99 char:1
+ Move-Item -Path "$temp\dbatools-$branch\*" $path -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Daniel...ools-master\xml:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
```

This suggests the directories and their contents aren't being overwritten, even with the `-Force` parameter, the `-ErrorAction SilentlyContinue` has been burying those errors, presumably for a long time.

**Comment by dansqldba** [comment]
Also, I was able to fully reproduce this behaviour at the command line, using `Move-Item` only, with a couple of folders and text files.

`Move-Item` doesn't replace the contents of a subfolder, even with `-Force`, if it already exists at the destination. The root of the folder does get moved/replaced however, as is the case with the `Update-dbatools` function. This is why the root of the module is getting updated, but nothing else.

From what I can remember, the module didn't originally have a folder hierarchy, this was something I suggested a long time ago and @potatoqualitee used PowerShell Studio to move a lot of stuff around. I'm not sure when that was though, over a year ago I expect?

Install.ps1 contains a number of other instances of `-ErrorAction SilentlyContinue` being used throughout the script, there may be other issues with it.

**Comment by wsmelton** [comment]
Well being that it is potentially run outside of the module import we cannot add our log system to it.

A possible workaround would be to pipe the files to `Move-Item`. If you use something like below see if that works for your situation and then we can update the script:

```powershell
Get-ChildItem "$temp\dbatools-$branch" -Recurse | Move-Item -Destination $path -ErrorAction SilentlyContinue -Force
```

**Comment by dansqldba** [comment]
That seems to have resulted in the contents of the module all being in the root ;)

Having spoken to @ConstantineK and @FriedrichWeinmann in Slack, they think this is a major bug, based on my horrible explanations, so they're going to dive into it. A rewrite of the install.ps1 script was on Fred's todo list already, so he's moved it up, CK is going to see if he can address the immediate problem.

**Comment by ConstantineK** [comment]
So went deeper with the issue and found that we are probably going to need to refactor the entire process, the issues that arise are:

- Installing the module (by default) works fine, the initial import fails to load the module so there are no issues with locked files.
- Updating the module again via install.ps1 will attempt to overwrite files in use because as the the module now exists and was imported to find the base path, and the SMO dlls are loaded.
- After talking with Fred and reading the docs, I see no clear method to "unimport" the dlls besides killing the selfsafe process that we are in, so he suggested creating a new folder, import those dlls over the existing ones (so they are no longer in use) then cleaning them up later via the maint runspace.

The other piece is that we are potentially leaving artifacts between module versions, and I think we might want to commit on removing all files and folders in the module dir.

Move-Item and Copy-Item struggle with different types of existing files or folders, but in the case of a truly empty directory we can guarantee a simple move process.

Nowhere near what I want, but something that basically handles all but the dlls is in https://github.com/sqlcollaborative/dbatools/blob/fix-install/install.ps1

**Comment by FriedrichWeinmann** [comment]
In a recent release we updated the installation script. It should now recognize locked files, roll back changes on failure and provide advice on how to make the update/installation succeed after all.
If you could confirm this for yourself @dansqldba that would be appreciated

**Comment by niphlod** [comment]
@dansqldba : any updates on this ? feel free to close the PR if this has been fixed.

**Comment by JanMulkens** [comment]
@FriedrichWeinmann @dansqldba @niphlod 
I've found that I need to do a get-process | Where-object -eq 'powershell_ise' | stop-process every time I want to do a manual update through the zip file and also want to overwrite the dll's in the bin directory.
None of the described methods in the install.ps1 file actually seem to work when copying over the files from the zip file.
Which actually is very annoying if I want to ensure all files are updated.

disclaimer: It might be that I'm just not following instructions correctly

**Comment by JanMulkens** [comment]
Just thanking myself for being awesome and making this a public comment so I could find it again...

This still isn't solved, the DLL's are still read only and the only way I can reinstall dbatools while offline is by killing all powershell processes (so not only closing the windows).
Nowadays I do this a bit more drastic using: 
`get-process | Where-object ProcessName -like 'powershell*' | stop-process `

**Comment by wsmelton** [comment]
This is an issue with ISE and not the module itself. Nothing we can do about it truth be told.

**Comment by potatoqualitee** [comment]
Agreed. It's something I just accept, and one of the reasons Install-Module places it into numbered folders (except with older versions). I recommend installing [PowerShellGet](https://docs.microsoft.com/en-us/powershell/gallery/getting-started), which will better manage modules.  install.ps1 is about as good as it can get.
