### ISSUE TITLE
Find-DbaOrphanedFile does not find files in directory of tempdb files if different from data and log paths

### ISSUE THREAD

**Issue by dgmyrs** [sqlcollaborative/dbatools#2725]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
 - PowerShell Version: 
 - SQL Server (Edition|Version): 

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

## Feature Request
It would be ideal if Find-DbaOrphanedFile by default looks in the directories where tempdb data and log files are stored.  It is fairly common to have these on a separate drive or file system.

**Comment by dgmyrs** [comment]
In looking through the code, I think the best option would be to just add the paths of all current data and log files for attached databases.  That way you would get any paths that are in use on the instance.  Anyone disagree with that?

**Comment by niphlod** [comment]
closed via #2726
