### ISSUE TITLE
Copy-SqlLogin - Get-Help output bug (missing DynamicParameters)

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/dbatools#274]
There are a few omissions in the Copy-SqlLogin cmdlet. If I run Get-Help, I don't see the -login in the parameter syntax, nor in the parameter list. Same for -exclude

I'd change the "login to server" verbiage to "login to instance", so people are clear.

The docs also don't quite explain which properties are copied, and which may not be. I'd like an explicit list of the items that are checked and transferred.

The web page at https://dbatools.io/functions/copy-sqllogin/ describes the cmdlet lightly as well. Not sure that's an issue as Get-Help is probably a better place for tech docs.

**Comment by wsmelton** [comment]
Yeah, the help is on the todo list. The parameters that are dynamic don't get picked up by Get-Help, which the ones you noted are dynamic.

**Comment by wsmelton** [comment]
The login properties included is everything, the command scripts the login out and then applies it to the destination. This would be same thing as scripting it from SSMS. 

There is another issue recorded on check around comparing logins at the destination. Some commands are only doing straight compare by just name. We are working on validating if the login explicitly exist or if it has access via a group login.

**Comment by dansqldba** [comment]
Is this still valid?

**Comment by niphlod** [comment]
@wsmelton : just pinging against staleness. is this still valid ?

**Comment by way0utwest** [comment]
Only if you want the parameter documentation either in Get-Help or the page. I still don't see it.

**Comment by wsmelton** [comment]
We can leave this one open. 

The dynamic params are going away to Tab EPP but I'm not sure how that is effected with `Get-Help`. I know we do have a main goal of revamping the help documentation anyway so either way it will get addressed.

**Comment by potatoqualitee** [comment]
Now that we've moved to TabExpansionPlusPlus, this has been resolved across all commands 👍 

![image](https://user-images.githubusercontent.com/8278033/28499550-cd2def18-6fb8-11e7-95fa-23f079e2ccf9.png)
