### ISSUE TITLE
Remove-SqlDatabase in internals has better alternatives

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#2742]
Test-DbaLastBackup, Remove-DbaDatabaseSafely should switch to Remove-DbaDatabase.

**Comment by wsmelton** [comment]
In reference to `Copy-DbaDatabase` what portion or action would you replace with the remove command?

**Comment by niphlod** [comment]
Just did a quick text search of remove-database. If copy-dbadatabase has no
references to it my bad, my eyes crossed.

Il 29 nov 2017 2:29 AM, "Shawn Melton" <notifications@github.com> ha
scritto:

**Comment by niphlod** [comment]
as it [turns out](https://github.com/sqlcollaborative/dbatools/search?utf8=%E2%9C%93&q=Restore-Database&type=), Copy-DbaDatabase does not has a reference to Remove-Database. Sorry!

**Comment by potatoqualitee** [comment]
it probably does an inadequate .drop() - Remove would fa sho remove.
