### ISSUE TITLE
Copy-SqlLogin - Limitation with local machine accounts

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/dbatools#275]
I don't see a limitation listed that Copy-SqlLogin doesn't work with local machine accounts. If I try to transfer a local account (non-domain) I get a "Skipped, because a local machine account.

This should be doc'd, or allowed.

**Comment by ctrlbold** [comment]
I've seen other instances where local accounts are desired (like multiple instances on one server.) Support for this request will be added, perhaps as -IncludeLocalAccounts, and included in the November Milestone.

**Comment by ctrlbold** [comment]
Fixed in tomorrow's release! Already in dev.
