### ISSUE TITLE
Error : 'AuthorizationManager check failed' while loading dbatools.psm1 module through sql agent job

### ISSUE THREAD

**Issue by sagarkvs** [sqlcollaborative/dbatools#2751]
A job step received an error at line 4 in a PowerShell script. The corresponding line is 'Import-Module C:\Windows\System32\WindowsPowerShell\v1.0\Modules\dbatools\dbatools.psm1 -force'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'AuthorizationManager check failed.  '.  Process Exit Code -1.  The step failed.

need help in importing the module through the sql agent job

**Comment by niphlod** [comment]
The module is the psd1 file, not the psm1. What syntax are you using to
import the module?

Il 30 nov 2017 10:54 AM, "sagarkvs" <notifications@github.com> ha scritto:

**Comment by sagarkvs** [comment]
Import-Module C:\Windows\System32\WindowsPowerShell\v1.0\Modules\dbatools\dbatools.psm1 -force

**Comment by niphlod** [comment]
that's the error. 
a) you installed it system-wise so you can just do "import-module dbatools"
b) if you ever want to skip the install part, you need to put it in a folder and "import-module path_to\dbatools.ps**d**1"

Go here for all the options : dbatools.io/install

**Comment by sagarkvs** [comment]
module is loading fine when loading through powershellISE, facing error while running through sql agent job
A job step received an error at line 1 in a PowerShell script. The corresponding line is 'Import-Module dbatools -force'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'Errors occurred while loading the format data file:  Microsoft.PowerShell, , C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\dbatools\xml\dbatools.Format.ps1xml: The file was skipped because of the following validation exception: AuthorizationManager check failed..   '.  Process Exit Code -1.  The step failed.
