### ISSUE TITLE
Missing build number for SQL Server 2014

### ISSUE THREAD

**Issue by chrgraefe** [sqlcollaborative/dbatools#2752]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): WIN10
 - PowerShell Version: PS 5.1
 - SQL Server (Edition|Version): SQL Server 2014 SP2

## Steps to Reproduce
run

```powershell
Get-DbaSqlBuildReference -SqlInstance MyServer\SQL2014
```
Output:
```
SqlInstance    : myServer\SQL2014
Build          : 12.0.5207
NameLevel      : 2014
SPLevel        : {SP2, LATEST}
CULevel        :
KBLevel        : 3194714
SupportedUntil : 09.07.2024 00:00:00
MatchType      : Approximate
Warning        : 12.0.5207 not found, closest build we have is 12.0.5203
```

## Feature Request
please add this entry to dbatools-index.json

```json
    {
        "Version":  "12.0.5207",
        "KBList":  "4019093"
    },
```

### Problem to solve
Correct output no guessing

**Comment by niphlod** [comment]
thanks for the report

**Comment by niphlod** [comment]
@chrgraefe : you can do right now `Get-DbaSqlBuildReference -SqlInstance MyServer\SQL2014 -Update` to have the most up-to-date info.

We'll ship the update with the module the next release.

**Comment by chrgraefe** [comment]
Hello Simone,

the change is not available via -Update Switch, yet.
I will test it tomorrow when it is merged to master.

**Comment by niphlod** [comment]
it is

![image](https://user-images.githubusercontent.com/122119/33429452-2bbd51fc-d5cd-11e7-9af2-58d5f8fcf6c9.png)

**Comment by chrgraefe** [comment]
I will believe, but I get this:
[image: Inline-Bild 1]

2017-11-30 12:51 GMT+01:00 Simone Bizzotto <notifications@github.com>:

**Comment by niphlod** [comment]
the images need attachment via githuib issues, in email replies they get discarded

**Comment by chrgraefe** [comment]
![image](https://user-images.githubusercontent.com/4922897/33430051-68e16b3e-d5cf-11e7-8abe-855d24d15408.png)

**Comment by chrgraefe** [comment]
Closed accidentally
