### ISSUE TITLE
[Repair-DbaOrphanUser/Remove-DbaOrphanUser] Processes correctly but ends with an error.

### ISSUE THREAD

**Issue by MakwaWes** [sqlcollaborative/dbatools#2754]
### General Troubleshooting steps

- [ ] Verified running latest release of dbatools?
0.9.108
- [ ] Can duplicate in new/fresh PowerShell.exe session?
Yes

### Version Information
 - Operating System (Name|Version): Windows Server 2012
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Microsoft SQL Server Standard (64-bit) 11.0.5678.0

## Steps to Reproduce

SharePoint Content Databases migrated and having a bunch of orphan users.
While running the following cmdlet, the orphan users are removed but the cmdlet ends up with an error.
`Remove-DbaOrphanUser -SqlInstance $sqlInstance -Database $myCDB -EnableException -Force`

Outputs correctly the orphan users deleted but ends with this error message from [Write-Message] function :
```
Instance          : mySqlServer\myNamedInstance
Database          : myContentDBName-01
SchemaName        : myADDomain\svc_acct_orphan01
Action            : DROP
SchemaOwnerBefore : myADDomain\svc_acct_orphan01
SchemaOwnerAfter  : N/A

Instance          : mySqlServer\myNamedInstance
Database          : myContentDBName-02
SchemaName        : myADDomain\svc_acct_orphan02
Action            : DROP
SchemaOwnerBefore : myADDomain\svc_acct_orphan02
SchemaOwnerAfter  : N/A

Write-Message : Cannot process argument transformation on parameter 'Level'. Cannot convert value "Error" to type "Sqlcollaborative.Dbatools.dbaSystem.MessageLevel".
Error: "Unable to match the identifier name Error to a valid enumerator name. Specify one of the following enumerator names and try again:
Critical, Important, Output, Significant, VeryVerbose, Verbose, SomewhatVerbose, System, Debug, InternalComment, Warning"
At line:333 char:28
+                         Write-Message -Level Error -Message $_
+                                              ~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Message], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Write-Message
```

### Problem to solve
Could it be possible to fix this cosmetic error message please ?

### Additional information
Thanks for your hard work, one of the best PowerShell modules. Using it daily and for automation scripts !
🥇

**Comment by ClaudioESSilva** [comment]
Hi, @MakwaWes thank you for your report and kind words.
I have submitted a PR (#2768) with the fix.

I would like to ask if you can re-run the command after because if it jumped to the `catch` block some error happened and we would like to know what is.

**Comment by MakwaWes** [comment]
Hi,
I'm not sure how to perform what you ask me. The complete error message is in the initial post.
What I can tell is that the error always displays at the end, after dropping all the orphan users.
Regards.

**Comment by ClaudioESSilva** [comment]
Hi @MakwaWes,
Please get the latest version (0.9.115) where it is already fixed and run again the same command in the same situation and confirm if no further errors occurs.
Thanks

**Comment by MakwaWes** [comment]
Hello @ClaudioESSilva,
I tried the cmdlet 'Remove-DbaOrphanUser' using the module version 0.9.121 and I didn't get an error message but a warning message :
```
Message               : Failure | Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database 'MyDatabase'. "
Source                :
StackTrace            :
TargetSite            :
HResult               : -2146233088
HelpLink              :
Data                  : {}
InnerException        : Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database 'MyDatabase'. "
ExceptionTypeName     : System.Exception
ExceptionData         : {}
CategoryInfo          : NotSpecified: ([MyDatabase]:String) [], Exception
ErrorDetails          :
FullyQualifiedErrorId : dbatools_Remove-DbaOrphanUser
InvocationInfo        :
ScriptStackTrace      :
TargetObject          : [MyDatabase]
FunctionName          : Remove-DbaOrphanUser
Timestamp             : 2017-12-12 11:39:41
Runspace              : 0f864c8e-69e8-472a-8498-d549a39c0e96
```

Again, it only happens at the end of the process, for the final user removal. All the others are removed without issues.
```
VERBOSE: [Remove-DbaOrphanUser][11:39:40] User [MyDomain\SomeUserA] owns one or more schemas.
VERBOSE: [Remove-DbaOrphanUser][11:39:40] The schema 'MyDomain\SomeUserA' have the same name as user [MyDomain\SomeUserA]. Schema will be dropped.
VERBOSE: Performing the operation "Dropping schema 'MyDomain\SomeUserA'." on target "MyDatabase".
VERBOSE: Performing the operation "Dropping user [MyDomain\SomeUserA]" on target "MyDatabase".
VERBOSE: [Remove-DbaOrphanUser][11:39:40] User [MyDomain\SomeUserA] was dropped from MyDatabase.
VERBOSE: [Remove-DbaOrphanUser][11:39:40] User [MyDomain\AnotherUserB] does not own any schema. Will be dropped.
VERBOSE: Performing the operation "Dropping user [MyDomain\AnotherUserB]" on target "MyDatabase".
WARNING: [Remove-DbaOrphanUser][11:39:41] Failure | Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database 'MyDatabase'.  "
VERBOSE: [Remove-DbaOrphanUser][11:39:41] Total Elapsed time: 00:00:25.8359804
```

Thanks for your time.

**Comment by ClaudioESSilva** [comment]
Thanks @MakwaWes that is what I want because I knew that the error stills there (because I don't know yet what it is 😂 )

So after that execution, you still see the MyDomain\AnotherUserB user? 
Do you confirm that it wasn't removed?

**Comment by ClaudioESSilva** [comment]
If it still being there can you please run manually the:
`DROP USER [MyDomain\AnotherUserB]`
Put the error message here, please.
Thanks!

**Comment by MakwaWes** [comment]
The user [MyDomain\AnotherUserB] is correctly removed from the database. I can't run the tsql on it anymore.

**Comment by ClaudioESSilva** [comment]
Ok. Let's go further.
We have a Debug message that will write the TSQL that will run.

Can you please run the following line of code
`Get-DbatoolsLog | Where-Object Level -eq Debug | Select-Object *`
and hide sensitive data so we can analyse the Debug message.

If nothing is returned (because you already close the console), please, open a new one reproduce the error and then run this command.

you will get something like this:
![image](https://user-images.githubusercontent.com/19521315/33899426-5e7f3dd6-df63-11e7-9078-3287f620ee89.png)

**Comment by MakwaWes** [comment]
Here you go :
```
Message      :
               DROP SCHEMA [MyDomain\SomeUserA]
               DROP USER [MyDomain\SomeUserA]
Type         : Debug
Timestamp    : 2017-12-13 15:26:02
FunctionName : Remove-DbaOrphanUser
Level        : Debug
Runspace     : e92943bc-9340-4d15-a245-b52ec02ca72c
TargetObject :

Message      :
               DROP SCHEMA [MyDomain\SomeUserA]
               DROP USER [MyDomain\AnotherUserB]
Type         : Debug
Timestamp    : 2017-12-13 15:26:02
FunctionName : Remove-DbaOrphanUser
Level        : Debug
Runspace     : e92943bc-9340-4d15-a245-b52ec02ca72c
TargetObject :
```
It seems that the last command kept a non-related TSQL regarding the "schema".

**Comment by ClaudioESSilva** [comment]
Thanks, @MakwaWes !
I was able to reproduce the issue. Submitted a PR (https://github.com/sqlcollaborative/dbatools/pull/2854) with the fix.

**Comment by ClaudioESSilva** [comment]
@MakwaWes can you please pull last version from the gallery (0.9.125) and run it again? 😊 
Thanks!

**Comment by MakwaWes** [comment]
Hi,
I tried with dbatools version 0.9.135 and it worked all the way through !
Good job.
