### ISSUE TITLE
Restore-DbaDatabase fails on non-English server/instance

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2763]
_Thanks to @pollusb for finding this issue for us._

## Steps to Reproduce
```
(Connect-DbaInstance -SqlInstance "CLUSTER23").Language
Français (France)
```
Trying to run `Restore-DbaDatabase` against a non-English server/instance causes errors because we have column names referenced in English only. Use of just `-ScriptOnly` errors on call to `Test-DBaLastBackup`, which in turn is calling `Get-DbaDatabaseFile` and that has a column referenced as `'MB Free'`, which does not exist due to language.

### Problem to solve

Need to account for column names referenced in procedures and T-SQL based queries when on non-English servers.

Potential workaround in this case will be to look at column orders and maybe dynamically look up what the column name is instead of hard coding it.

**Comment by niphlod** [comment]
fixed via https://github.com/pollusb/dbatools/commit/e6c11f01ee56099f1973b4d5c222852b5bbae161
