### ISSUE TITLE
Set-DBAPowerPlan fails on None English language machines

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#2769]
## Bug Report

Test-DbaPowerPlan correctly handles different languages but Set-DbaPowerPlan fails as it has hardcoded parameter set for English and also this line fails on none-english language machines

https://github.com/sqlcollaborative/dbatools/blob/master/functions/Set-DbaPowerPlan.ps1#L104

### General Troubleshooting steps

- [ X] Verified running latest release of dbatools?
- [ X] Verified errors are not related to permissions?
- [ X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System Replicated on various OS's and hardware
## Steps to Reproduce

**Comment by SQLDBAWithABeard** [comment]
@jaapbrasser agreed that he would fix this one for us :-)

**Comment by Splaxi** [comment]
Was this ever fixed?

**Comment by potatoqualitee** [comment]
Yes, actually! https://github.com/sqlcollaborative/dbatools/blob/master/functions/Set-DbaPowerPlan.ps1#L169

**Comment by potatoqualitee** [comment]
Users will still have to use the english equivalent of the parameters tho.

**Comment by potatoqualitee** [comment]
Wait, no I'm wrong. This can be fixed by using tEPP and i'm eager to avoid school work brb

**Comment by Splaxi** [comment]
Please fix the spelling in "reqested" in the function while you are at it ;)

**Comment by potatoqualitee** [comment]
Done ;)
