### ISSUE TITLE
Replace causes instance names to break

### ISSUE THREAD

**Issue by RichieBzzzt** [sqlcollaborative/dbatools#2782]
https://github.com/sqlcollaborative/dbatools/blob/b68cfdade04ec6d3fec44fec9a9999fcef5081b0/functions/New-DbaPublishProfile.ps1#L128

Tesing on an instance with dashes in name and whne passing in connection string 'SERVER=BB-SQL-123-01\INAMEIntegrated Security=True;Database=master' the replace on this line causes following error - 

"WARNING: [New-DbaPublishProfile][10:58:07] Failure | Cannot convert value "BB\SQL\123\01\INAME" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: BB\SQL\123\01\INAME""

When removing replace am able to create publish profile.

**Comment by potatoqualitee** [comment]
ohh snap, lemme fix
