### ISSUE TITLE
"Database doesn't exist" not really a problem when publishing a dacpac

### ISSUE THREAD

**Issue by RichieBzzzt** [sqlcollaborative/dbatools#2783]
https://github.com/sqlcollaborative/dbatools/blob/b68cfdade04ec6d3fec44fec9a9999fcef5081b0/functions/Publish-DbaDacpac.ps1#L140

If a database doesn't exist then the deployment script will create database. So not sure we need to check if it already exists or not (assume when connection is created it defaults to users default database anyway?)

**Comment by potatoqualitee** [comment]
i actually had big ol errors when the db didnt exist. mine defaults to master.

I did see there's an option to autocreate a db, perhaps we can add that to the profile maker? (though I still think we should keep the check in if possible since i did get errors)

**Comment by potatoqualitee** [comment]
Perhaps your experience is if -Database is not required (unsure if yes or no). If -Database is optional, we can remove it and also remove the check.

**Comment by RichieBzzzt** [comment]
If you mean the "CreateNewDatabase" param that will drop and recreate the database, so all data will be lost.

Unfortunately, -Database is required.

Did you get errors when trying to connect, or was it errors from the publish?

**Comment by RichieBzzzt** [comment]
It is one ofhte most misleading keywords since NOLOCK..!

Is it possible that the database you were trying to publish had referencesto objects outside ofthe database? ie I havea view on one database that looks at another datbase, and I have to create the other database first before I can create the other database. Same for linked servers.

If you can share dacpac then forward it to me via Slack?

**Comment by potatoqualitee** [comment]
yep, one moment

**Comment by RichieBzzzt** [comment]
Closed with ```b4f76eb
