### ISSUE TITLE
Invoke-DbaDatabaseShrink should skip offline and snapshots

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#2787]
### General Troubleshooting steps

- [X ] Verified running latest release of dbatools?
- [ ] Verified errors are not related to permissions?
- [ ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
 - PowerShell Version: 
 - SQL Server (Edition|Version): 

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

## Feature Request
Add skip of databases that are not online and cannot be shrunk,  Use IsAccessible property.

**Comment by niphlod** [comment]
fixed via https://github.com/sqlcollaborative/dbatools/commit/5d23ac3a2b377a41ef637c0aba2c0d82ea2656aa#diff-7f4806ae4cd44ab9998b9a934409a8aa
