### ISSUE TITLE
Copy-SqlLogin - missing grant connect to database after revoke

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#279]
Steps to reproduce.  I ran copy-sqldatabase to copy a database from SQL Server 2000 to 2008R2.  Database restored properly.  I ran copy-sqllogin to copy b2buser from 2000 to 2008R2.  There is a revoked connect that happens, but I don't think the database grant connect ever happens.  This makes it so the user cannot login.  Here is the output:

PS C:\Windows\system32> Copy-SqlLogin -Verbose -Source PPNTEST -Destination DFWQPPNSQL01 -Logins b2buser
Attempting to connect to SQL Servers..
VERBOSE: Performing the operation "Showing time started message" on target "console".
Migration started: 10/19/2016 10:25:45
VERBOSE: Performing the operation "Showing migration attempt message" on target "console".
Attempting Login Migration
VERBOSE: Performing the operation "Adding SQL login b2buser" on target "DFWQPPNSQL01".
Attempting to add b2buser to DFWQPPNSQL01
Setting b2buser SID to source username SID
Setting login language to us_english
Set b2buser defaultdb to PPNMain
Successfully added b2buser to DFWQPPNSQL01
VERBOSE: Performing the operation "Updating SQL login b2buser permissions" on target "DFWQPPNSQL01".
Successfully revoked CONNECT from b2buser on ChoicePoint on DFWQPPNSQL01
VERBOSE: Performing the operation "Showing time elapsed message" on target "console".
Login migration completed: 10/19/2016 10:25:52
Total elapsed time: 00:00:06

**Comment by dczarny** [comment]
This looks like it is happening from the Update-SqlPermissions function on line 342 in Copy-SQLLogin.  If I comment that function out, it doesn't run the REVOKE Connect on the database.

**Comment by dczarny** [comment]
What is the need for the update-sqlPermissions function when copying logins?  Am I missing something, or is this an unnecessary action?  If you copy a login from server A to server B and it keeps the same SID, then you shouldn't have to do anything with permissions.  That would take care of the authentication.  The authorization to the database would already be there in the form of a user account.  Maybe if use the force switch, this would try and drop the user permissions and add them back.  But there still would be the bug of Revoking the database CONNECT permissions and not granting the database CONNECT permissions.

**Comment by ctrlbold** [comment]
Thanks, @dczarny. Our professional bug killer is on the case ;)

**Comment by ConstantineK** [comment]
Hey @dczarny, 
I was thinking about this bug, and think we have a few things to pull apart.

An issue where a revoke happens without a grant boils down to two things:
1. Should we modify database principle permissions?
2. Do the permissions (once we iterate over them) reflect the source? 

I took a look at both update and sync sqlpermissions in the project, and it looks like both are effectively considering the case of a blank server with maybe a database on it, but that database doesnt have permissions (or if it does, it needs them overwritten.) 

From your case I read that (and I also do this same thing) you are restoring databases from an environment (potentially even the source environment) and want to migrate just the server principles, thus allowing access to the database and worst case updating SIDs to match. 

For case 2: 
I looked through the code and didn't see an obvious case of permissions being mismatched on the hosts, and I was hoping you could confirm that the revoke permission doesn't exist in the source environment? 

If it does, we need to trace down a bug in update-sqlpermissions, and can start to isolate that.

For case 1:
I think the SQL migration scripts that many of these cmdlets are generated from assume that you cannot take your database permissions for granted and that you would want the behavior you are not interested in.

It might be a useful switch to have, as I do believe this is a common use case. 
I will go back to the group and see what they think, let me know if you find that the logins had different permissions across your environment.
Thanks!

**Comment by dczarny** [comment]
For case 1:  Yes all that is correct.  I was using start-sqlmigration to upgrade from SQL 2000 to 2008R2.  For that scenario you only need to backup and restore the databases, then copy the logins.  Once the SIDs for the logins are copied over, it will automatically pick up all the permissions in the databases for that user.  There is no need to drop the database level user permissions and add them back since they would already be there from the restore.  
For case 2:  That is correct the revoke doesn't exist in the source permission.  If I just use the copy-sqllogin command to copy a login (my case is 2000 to 2008R2), the login comes over perfectly, except the login is no longer attached to the databases it should be attached to.  As a work around, I just have been manually  running the grant connect tsql to fix it.  So I am guessing somehow in the code its skipping that step.  Can you confirm that is happening?  I haven't tried to use the copy-sqllogin from any other version than 2000, so maybe its just an issue with that version as a source?

**Comment by ConstantineK** [comment]
Hey @dczarny thanks for the quick response!
I will see if I can confirm #2 and maybe that is the case, I do have a SQL2000 instance available so I will see if there is some missing column or piece of data which is causing the issue.

I may have to rope you in if I miss the problem :)

**Comment by ctrlbold** [comment]
Hey @ConstantineK, a user emailed me and said "So far things have been going well but I noticed some issues with the logins and the user database mappings. It sounds a bit similar to what is reported here.
Some user that has been copied  from source and had dbo in user and dbo in default schema for database mapping but after copying login and database the mapping was gone. If I tried to manually fix it I would get the following error: Error 15023: User already exists in current database"

Perhaps this provides insight?

**Comment by ConstantineK** [comment]
It does sound like what @dczarny was talking about. I will dive deeper.

**Comment by dczarny** [comment]
As a work around, if it's just a couple of logins, they can just "Grant Connect" for each database the corresponding user is in.

**Comment by ConstantineK** [comment]
@dczarny one question, does this same issue happen when going from 2005 to later versions?

@ctrlbold I just noted the following comment in the text which may mean we simply cant do this? 
# These operations are only supported by SQL Server 2005 and above.
# Securables: Connect SQL, View any database, Administer Bulk Operations, etc.

Sorry about the late response on this one :D

**Comment by dczarny** [comment]
You can't just put a blanket tsql grant connect statement?  There isn't any user in a database that isn't allowed to connect to the database?

Thank you,
Derek Czarny


________________________________

**Comment by ConstantineK** [comment]
Hey @dczarny,

I maybe didn't explain my total reasoning for the question.

I was wondering if you had a problem if the user was on 2005 given your circumstances (and so the lack of information in the source server was to blame and should be handled for 2000 instances) or if it had a greater scope because @ctrlbold's report was slightly different.

**Comment by dczarny** [comment]
I just tested it from 2008r2. So you are probably correct, it's something missing from sql 2000.

Thank you,
Derek Czarny


________________________________

**Comment by potatoqualitee** [comment]
hey @ConstantineK - can we get it to skip whatever it needs to in 2000/2005 or whatever the solution is?

**Comment by wsmelton** [comment]
Is there any additional progress needed for this issue?

**Comment by dczarny** [comment]
I don't think so.  I think this has been solved for a while now.

Thank you,
Derek Czarny

________________________________

**Comment by potatoqualitee** [comment]
Thanks to you both!
