### ISSUE TITLE
Deprecated parameter usage for Get-DbaDiskSpace in Expand-DbaTLogResponsibly

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2800]
## Bug Report

Seems `Expand-DbaTLogResponsibly` need to be touched:

WARNING: [Get-DbaDiskSpace][13:10:42] Using the parameter Unit is deprecated. This parameter will be removed in version
 1.0.0, check in the documentation what parameter to use instead

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

## Steps to Reproduce

Expand-DbaTLogResponsibly -SqlInstance <Server> -Database <Database> -TargetLogSizeMB 10000

**Comment by ClaudioESSilva** [comment]
Thanks @Zhunya fixed!
