### ISSUE TITLE
new function to show Distributed Transaction Coordinator (MSDTC) State 

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#281]
I've been discovering some info about the DTC for some time.
Now I've put 3 of my old scripts together and created a function to show the state of the service, the security settings and the CID's all together in one object per computer.
I think this is very useful to those DBA's who have to tolerate MSDTC,
so I suggest this new function: Get-DbaMSDTC

There's also a way to alter some of those settings, so Set-DbaMSDTC may follow later.

There's also the possibility to show transactions that are held open by the DTC, but that needs to be separated because that's not collected per host, but per instance.

**Comment by wsmelton** [comment]
What version of OS would your code support?

**Comment by PowerDBAKlaas** [comment]
So far, tests ran successful on Win Server 2008 R2 (6.1.7601 Enterprise & Standard), 2012 R2 (6.3.9600 Standard) and 2016 (10.0.14393 Datacenter)

**Comment by ctrlbold** [comment]
Hey @PowerDBAKlaas, please put all new command requests on the trello board (dbatools.io/trello), I'll add this one along with yall comments.
