### ISSUE TITLE
Get-DbaHelpIndex, add column to account for index and stats separately

### ISSUE THREAD

**Issue by PianoMatt** [sqlcollaborative/dbatools#2819]
### Problem to solve
The output for Get-DbaHelpIndex does not include the index name or the statistics name. It would be helpful to have the index name and statistics name included in the output. Also please consider changing the name of the output column ObjectName to be TableName.

### Additional information

There is an input parameter also named ObjectName, but it is always a table. Would TableName for the input parameter be more clear?

Thanks,
Matthew

**Comment by wsmelton** [comment]
Are you referring to stats that the `-IncludeStats` parameter outputs?

**Comment by PianoMatt** [comment]
Yes, if stats are included, the stats name is not displayed. Neither the stats name nor the index name is displayed in the output.

**Comment by PianoMatt** [comment]
I modified Get-DbaHelpIndex.ps1 on my computer. I added 
IndexName        = $detail.IndexName in two spots at the end, and I'm getting the IndexName and StatisticsName returned.

**Comment by jpomfret** [comment]
I believe this is resolved, index and stats name are returned in output now. @wsmelton or @PianoMatt  ok to close?
![image](https://user-images.githubusercontent.com/981370/46885583-67c76500-ce26-11e8-941f-4737a8aaf7b1.png)

**Comment by jpomfret** [comment]
I don't disagree, it was like that when I found it 😊.I can change it, add a column to the output when '-includestats' but that would be a breaking change for people currently using it?

**Comment by wsmelton** [comment]
Yep... Sure would be but most of 1.0 if going to break many things ;)

**Comment by potatoqualitee** [comment]
breaking change welcomed now @jpomfret. It would be amaaazig if you could do the fix.

**Comment by jpomfret** [comment]
Let me see what I can do tomorrow 😁

**Comment by potatoqualitee** [comment]
🎉 🎉 🎉 🎉

**Comment by jpomfret** [comment]
Broke out Statistics into their very own column... PR incoming
![image](https://user-images.githubusercontent.com/981370/48634507-ac996b00-e993-11e8-922a-6bb0e24c4074.png)
