### ISSUE TITLE
Set-DbaStartupParameter requires Service to be running

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#2822]
### Problem to solve
Many of the common Scenarios for changing Startup Parameters for a SQL Server instance are to correct a Service that is not running. As written the Set-DbaStartupParameter function cannot address any of these issues.

### Additional information
The Set-DbaStartupParameter function has option to set the -m switch to allow Server to be started in Single User Mode. The most common reason for this is to restore master database.
However after setting the database into Single-User mode and restoring the database the master database the Service is immediately stopped. As Set-DbaStartupParameter will not work against a stopped service the command cannot be used to revert the change

Other examples like fixing incorrect memory allocations or moving location of Master or Error logs after a disk failure also require modifying the Startup parameters of a stopped instance

**Comment by Stuart-Moore** [comment]
PR #2823 in.

Can you take it for a test drive please, just to sanity check my choice of flow.

**Comment by sqllensman** [comment]
Thanks.

Will check now

**Comment by sqllensman** [comment]
Is now Working as I would expect.
Was able to do a restore of master DB in single script

Only small issues
The comment based help has a minor Spelling error
"Note, that with this switch Paths will be ignored unless you also speficy Force"

Also could look to clarify the impact of Offline and Force. It took me a few minutes to realise that using Offline without force will ignore the values of MasterData, MasterLog and ErrorLog and use the previously recorded values.

**Comment by Stuart-Moore** [comment]
Fix is merged into development so closing this.
