### ISSUE TITLE
Copy-DbaDatabase Invalid network path

### ISSUE THREAD

**Issue by mattbkarp** [sqlcollaborative/dbatools#2829]
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System: Win 7 Professional
 - PowerShell Version:
PS U:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
3      0      -1     -1

 - SQL Server (Edition|Version): Source Enterprise Edition 10.0.1600.22 Target Enterprise Edition 14.0.3008.27

## Steps to Reproduce
Getting this error when I run this command:

PS U:\> Copy-DbaDatabase -Source Server1 -Destination Server2 -AllDatabases -BackupRestore -NetworkShare \\\MachineName\FolderName1\FolderName2 -NumberFiles 8 -ReuseSourceFolderStructure -Force

Note:  I had to put in 3 backslashes in the UI for the -NetworkShare parameter to render properly but I am only using 2 when I pass in the parameter

******************************************************************************************************************************
Database (BackupRestore) DatabaseName Successful
Join-AdminUnc : Cannot validate argument on parameter 'filepath'. The argument is null or empty. Supply an argument
that is not null or empty and then try the command again.
At line:954 char:47
+                     $remotePath = Join-AdminUNC $destNetBios $remotePath
+                                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-AdminUnc], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Join-AdminUnc

Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:956 char:22
+                     if (!(Test-Path $remotePath)) {
*****************************************************************************************************************************

**Comment by wsmelton** [comment]
- Can you provide what version of the module you are working with?
- Can you provide the full error output from your execution? `$error[0] | select *` will grab that information.
- Also, what UI are you referring to using?

**Comment by niphlod** [comment]
hi @mattbkarp : can you provide the needed info ? If not, we're going to close this as it can't be replicated
