### ISSUE TITLE
Is it possible to skip Update-SqlPermissions alone from copy-DbaLogin?

### ISSUE THREAD

**Issue by sagarkvs** [sqlcollaborative/dbatools#2833]
I am looking for an option to skip Update-SqlPermissions alone from copy-DbaLogin module, i do not see any parameter defined to skip it, is there any other way we can skip?

**Comment by wsmelton** [comment]
At this time there is not any option to skip it. Can you provide the use case you are trying to solve?

**Comment by sagarkvs** [comment]
I am using copy-dbalogin in my custom script to sync the logins between primary and secondary replicas configured in Availability group. its trying to update the permissions as well when copying the logins, which is taking more time and throwing warning.

**Comment by wsmelton** [comment]
Yeah `Copy-DbaLogin` was not written around use with AG replicas in mind. There are a few issues currently around [Availability Groups](https://github.com/sqlcollaborative/dbatools/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Topic%3A+Availability+Groups%22+) that include some references to sync'n objects between replicas. 

A more appropriate command is being considered to handle an AG environment, it would basically just exclude the database parts (which is what throws the warnings).

**Comment by niphlod** [comment]
refer to the [goodies](https://github.com/sqlcollaborative/dbatools/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Availability+Groups%22+) to keep updated
