### ISSUE TITLE
Backup/Restore Piping

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2839]
A user ran this: `Backup-DbaDatabase -SqlInstance server\instance -Database test -BackupDirectory \\myshare\ -CopyOnly -CompressBackup | Restore-DbaDatabase  -SqlInstance server\instance -DatabaseName test2  -ReplaceDbNameInFile -WithReplace`

And had this returned:

````System.Exception: SqlInstance server\instance cannot access @{SqlInstance=server\instance; DatabaseName=test; BackupComplete=True; BackupFilesCount=1; BackupFile=test_201712121705.bak; BackupFolder=\\myshare\; BackupPath=\\myshare\test_201712121705.bak; Script=BACKUP DATABASE [test] TO  DISK = N'\\myshare\test_201712121705.bak' WITH  COPY_ONLY, NOFORMAT, NOINIT, NOSKIP, REWIND, NOUNLOAD, COMPRESSION,  STATS = 1; Notes=; FullName=\\myshare\test_201712121705.bak; FileList=System.Object[]; SoftwareVersionMajor=11; Verified=False; Type=Full; FirstLsn=34000000002400001; DatabaseBackupLsn=0; CheckPointLsn=34000000002400001; LastLsn=34000000002700001; BackupSetId=2053; LastRecoveryForkGUID=8d0cd8bd-aec8-4961-bdfe-68ea499c5644}\      
NotSpecified: (:) [], Exception dbatools_Get-XpDirTreeRestoreFile       
System.Management.Automation.InvocationInfo at Stop-Function, <No file>: line 185
at Get-XpDirTreeRestoreFile, <No file>: line 52
at Get-DbaBackupInformation<Process>, <No file>: line 214
at Restore-DbaDatabase<Process>, <No file>: line 519
at Select-DefaultView<Process>, <No file>: line 63
at Backup-DbaDatabase<Process>, <No file>: line 500
at <ScriptBlock>, <No file>: line 1 {}  
````

And I tried it and got something similar
`Backup-DbaDatabase -SqlInstance localhost -Database db1 -BackupDirectory \\dc\sql -CopyOnly -CompressBackup | Restore-DbaDatabase  -SqlInstance sql2017 -DatabaseName test2  -ReplaceDbNameInFile -WithReplace`

![image](https://user-images.githubusercontent.com/8278033/33895551-1029831e-df61-11e7-9156-e40ae830f167.png)

Would it be possible for you to add a test for this as well?

Thanks much!

**Comment by EmDBA** [comment]
The error occured in version 0.9.119

**Comment by potatoqualitee** [comment]
And 122

**Comment by Stuart-Moore** [comment]
Needs -TrustDbBackupHistory :)

But let me have a play around to see if I can get around that requirement

**Comment by EmDBA** [comment]
it works again, thank you Stuart-Moore
