### ISSUE TITLE
Copy-SqlDatabase - Suggestion to allow specifying file location on destination server

### ISSUE THREAD

**Issue by paololec** [sqlcollaborative/dbatools#284]
Ability to specify on destination server where to put files (not using default location for data and log, but specific custom location).

**Comment by potatoqualitee** [comment]
hey @paololec - good news/bad news ;D This is indeed supported, but you'll need to use

`Backup-DbaDatabase | Restore-DbaDatabase`

Backup to a shared directory then use $DestinationDataDirectory & $DestinationLogDirectory or $FileMapping
