### ISSUE TITLE
New Command: New-DbaDbUser to add a user to a database

### ISSUE THREAD

**Issue by frank687** [sqlcollaborative/dbatools#2851]
## Feature Request

There is an existing command to Remove-DbaDbUser but no corresponding Add command.

### Problem to solve
This is an inconsistency. 

### Additional information

Accept pipeline input from New-DbaLogin
Returns the newly created user

**Comment by niphlod** [comment]
fixed via https://github.com/sqlcollaborative/dbatools/commit/a14117203bf3d0c1f86e499c2722da289947c29d
