### ISSUE TITLE
Restore-DbaDatabase Try to put FileStream files on the source path

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#2859]
## Bug Report
While implementing a FileStream check on `Test-DbaMigrationConstraint` I found that FileStream files will try to restore on the **source** default path. If the path does not exists will fail.

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

## Steps to Reproduce
 - [x] Attach any screenshots (if possible/allowed)
`Backup-DbaDatabase -SqlInstance sql2012 -Database db3 -BackupDirectory "\\dc\sql\SQL2012"  | Restore-DbaDatabase -SqlInstance sql2016 -DestinationDataDirectory "C:\temp" -DestinationLogDirectory "C:\temp"

![image](https://user-images.githubusercontent.com/19521315/33999158-a221aa86-e0e1-11e7-8d86-dfa4d94b3560.png)

 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)
[DbatoolsLog_Backup_Restore_one_db.txt](https://github.com/sqlcollaborative/dbatools/files/1559728/DbatoolsLog_Backup_Restore_one_db.txt)
Here I can see the `Test-DbaDatabaseCompatibility` being called for every single DB even that I just passed one.
 - [X] Attach output from PowerShell console (if possible/allowed)
See screenshot
`
## Feature Request
Implement a new parameter like `-DestinationDataDirectory` and `-DestinationLogDirectory` for FileStream filegroups.

### Problem to solve
Being able to restore a database that uses FileStream to a specific directory

**Comment by niphlod** [comment]
closed via #2892
