### ISSUE TITLE
Copy-SqlLogin - can -Force copy login if login exists and connected

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#286]
Please fix issue with killing login connection on destination instance when Copy-SqlLogin used with -Force switch.

**Comment by ctrlbold** [comment]
Talked to him directly and he'd like a check to see if the user is logged in, and if they are, he'd like a notification before their connection is killed basically saying they're logged in and their connection will be killed.

**Comment by SirCaptainMitch** [comment]
> he'd like a notification before their connection is killed basically saying they're logged in and their connection will be killed.

So if they are logged in, output "User is logged in, the connection will be killed." and then kill the connection anyways? Or just a warning that says "User is logged in, this would kill the connection."

**Comment by Zhunya** [comment]
I think if user specified -Force flag, it is better to just kill process and procede forward with all remaining things.

**Comment by ctrlbold** [comment]
So what your'e saying @Zhunya is that you want the login to be skipped if its logged in? Logins are skipped if Force isn't specified. Not using Force would be a better solution.

**Comment by Zhunya** [comment]
Not usign Force for production system better solution, I agree. But if Force specified just kill all login connections add recreate login, thats it, is it clear now? Some times it's very hard for me to explain things in English, sorry.

**Comment by ctrlbold** [comment]
Ahh yes, very clear now, thank you. That was the original intent of -Force but the kill connection was not immediately before the drop, so the login had time to log back in. We fixed that yesterday in PR #285. Does that cover all of your concerns?

**Comment by Zhunya** [comment]
Yes, thank you!

**Comment by ctrlbold** [comment]
Excellent, will close this issue. Thanks for following up, @SirCaptainMitch!

**Comment by Zhunya** [comment]
Hi,

If we follow logic, just kill login connections and that it.

Thanks,
Oleg.

On Oct 27, 2016 01:02, "SirCaptainMitch" <notifications@github.com> wrote:

he'd like a notification before their connection is killed basically saying
they're logged in and their connection will be killed.

So if they are logged in, output "User is logged in, the connection will be
killed." and then kill the connection anyways? Or just a warning that says
"User is logged in, this would kill the connection."

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/286#issuecomment-256490382>,
or mute the thread
