### ISSUE TITLE
Restore-DbaDatabase reads only 1 file with striped backup sets

### ISSUE THREAD

**Issue by EmDBA** [sqlcollaborative/dbatools#2871]
Restore-DbaDatabase reads only 1 file when I pass multiple backups files in the pipe.

You can reproduce the issue with : 

`Backup-DbaDatabase -SqlInstance server\instance -Database test -FileCount 4 -BackupDirectory \\myshare`
`$files = Get-ChildItem \\myshare`
`$files | Restore-DbaDatabase -SqlInstance server\instance`

The output of the command : 
[output 1.txt](https://github.com/sqlcollaborative/dbatools/files/1562209/output.1.txt)

The output of $error[0] | select * : 
[output 2.txt](https://github.com/sqlcollaborative/dbatools/files/1562213/output.2.txt)

**Comment by niphlod** [comment]
fixed via #2875
