### ISSUE TITLE
Restore-DbaDatabase Progress bar no longer works

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#2878]
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows Server 2016
 - PowerShell Version: 5.1.14393.1532
 - SQL Server (Edition|Version): Target 2016 13.0.4422

## Steps to Reproduce
`Restore-DbaDatabase -Path \\server1\BackupTest\Backups\ -SqlInstance server1 -useDestinationDefaultDirectories`

![image](https://user-images.githubusercontent.com/981370/34057714-2cc26026-e1a6-11e7-8f8a-412adc5bb382.png)
Progress stays at 0% until it's finished and it just closes. Restore works fine, just doesn't report progress.

## Additional Info
Tested with latest dev version too (0.9.128) and still have the issue

**Comment by Zhunya** [comment]
Working on this one

**Comment by jpomfret** [comment]
Thanks! If it helps I believe the changes on Nov 8th in the following commit were when it stopped working:
https://github.com/sqlcollaborative/dbatools/commit/a46a5a9b30423119e649e94f0b774a11ba03fce9

There was a change from using Restore-DBFilteredArray to Invoke-DbaAdvancedRestore.

Let me know if you need a tester later on.

**Comment by Zhunya** [comment]
Yes, Stuart made RDDv2, and in this version progress broken, it's just cosmetic thing.

**Comment by niphlod** [comment]
remember take care also of ```"`n"``` inside write-progress.

**Comment by niphlod** [comment]
I'll take this on since it's due for some time now

**Comment by potatoqualitee** [comment]
Oh, man. Thanks @niphlod - I sat tonight with my team waiting and I didn't see the progress bar move for the longest time - I manually checked the execution time and was so relieved to see it was 99% complete.

In addition, I also have a weird unicode character.

![image](https://user-images.githubusercontent.com/8278033/35408788-a5c2bf72-0210-11e8-8c2f-dd6fd4f4d49f.png)

Backup progress bar looks good.

**Comment by niphlod** [comment]
Not unicode, just "crlf",  it was mentioned in the related issue.
Will check in a few what stuart reported. I'm usually annoyed by progress
info but it totally makes sense with restore*

Il 25 gen 2018 8:45 PM, "Chrissy LeMaire" <notifications@github.com> ha
scritto:
