### ISSUE TITLE
Copy-DbaDatabase no longer supports 2000 :(

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2879]
Unintended consequence of moving to using command that does not support 2000. Can we please ensure copy-dbadatabase supports sql server 2000? This is a high priority fix if possible, let me know if you dont have time this week, Stuart.

![image](https://user-images.githubusercontent.com/8278033/34060072-6cdac310-e1e2-11e7-993c-0296cadf8f8e.png)

**Comment by Stuart-Moore** [comment]
Only just seen this.

There's probably a work around, but it's not going to be pretty. The 2k5 and above fix is a nice proper PS pipeline trick which aligns with all the other examples we show for working with backup and restore. So it'll be  a kludge based on the version and an if statement

**Comment by potatoqualitee** [comment]
that seems liek the only way to do it, which sounds good to me

**Comment by Stuart-Moore** [comment]
Is there an 'official' dbatools reason we don't use the sql2000 backup history stuff? It's a bit sparser than 2k5 onwards, but there's enough in there to build the output object for Backups (LSNs, paths, files)

Could hide it as an internal function, and call from Get-DbabackupHistory to keep things clean?

**Comment by Stuart-Moore** [comment]
A quick tinker shows that there's only a few bits that 2000 doesn't support. So we can't make it work properly under Get-DbaBackupHistory, but could certainly have an internal reference to split inside Backup-DbaDatabase to pull from Get-DbaBackupHistory or internal\Get-LimitedBackupHistory based on version of sql doing the backup.

If anyone wants to say yay or nay on the overall idea I'll pick it up in the morning

**Comment by Stuart-Moore** [comment]
Hid the fix in Backup-DbaDatabase so it should be transparent for anything else relying on that that's not been spotted yet
