### ISSUE TITLE
New-DbaAgentJob throws error when WhatIf switch used

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#2887]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Windows 8.1): 
 - PowerShell Version: 5.1

## Steps to Reproduce

Run the following command
New-DbaAgentJob -SqlInstance InstanceName -Job 'Job One' -Description 'Test' -WhatIf 

Produces following error:
format-default : To accomplish this action, set property Category.
    + CategoryInfo          : NotSpecified: (:) [format-default], PropertyNotSetException
    + FullyQualifiedErrorId : Microsoft.SqlServer.Management.Smo.PropertyNotSetException,Microsoft.PowerShell.Commands.FormatDefaultCommand

If change to use
New-DbaAgentJob -SqlInstance InstanceName -Job 'Job One' -Description 'Test' -Category 'Uncategorized (Local)' -WhatIf  

get slightly different error message:
format-default : To accomplish this action, set property CategoryID.
    + CategoryInfo          : NotSpecified: (:) [format-default], PropertyNotSetException
    + FullyQualifiedErrorId : Microsoft.SqlServer.Management.Smo.PropertyNotSetException,Microsoft.PowerShell.Commands.FormatDefaultCommand
### Additional information
Adding a value for CategoryId does not change result

Running against other versions of SQL Server don't change result

**Comment by sqllensman** [comment]
Some additional experimenting and issue appears the code that returns the created job object
is being done outside of the Should Process block.

When run with WhatIf the $currentjob object is not properly set

Moving this output statement fixes errror

**Comment by ConstantineK** [comment]
Closing, merged.
