### ISSUE TITLE
New cmdlet request - Rename-SqlDatabase

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#289]
Change name of one or more properties of a database:
- change database name
- change logical names, may be with template
- change file name, may be with template

Template parameters:
- %PX prefix
- %DN database name
- %FG file group name
- %FT file type
- %DT datetime
- %SX sufix

**Comment by SirCaptainMitch** [comment]
I think that this has also been asked for in Copy-SqlDatabase. By adding this as a separate cmdlet we could potentially just call it there instead of adding a bunch of new code to the Copy-SQlDatabase.

**Comment by potatoqualitee** [comment]
Gorgeous design, @Zhunya ! I'be brought it back up again and hopefully someone can get on it.

**Comment by niphlod** [comment]
Going to write something but either with *PX* or <PX>. "%" is a valid character for a file, while * and < aren't. ATM I feel <PX> is more pleasant but changing that before the final release won't be an issue.

**Comment by niphlod** [comment]
this is now in development. Happy renaming!
