### ISSUE TITLE
Piping Get-DbaRegisteredServer output throws warning for servers with AG read-intent setting

### ISSUE THREAD

**Issue by sqlworldwide** [sqlcollaborative/dbatools#2894]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Target Microsoft SQL Server 2016 (SP1-CU3) (KB4019916) - 13.0.4435.0 (X64) 
	Apr 27 2017 17:36:12 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: ) (Hypervisor)

## Steps to Reproduce
Command to run:
`Get-DbaRegisteredServer -SqlInstance  CMSServer -ExcludeGroup dev| Install-DbaWhoIsActive -Database master|format-table`

Warning:
```
WARNING: [Install-DbaWhoIsActive][09:47:15] Failed to install stored procedure. | The following exception occurred while trying to enumerate the coll
ection: "The target database ('databaseinAG') is in an availability group and is currently accessible for connections when the application intent is set to r
ead only. For more information about application intent, see SQL Server Books Online.".
```

**Comment by niphlod** [comment]
not really a problem for Get-DbaCmsRegServer rather for "executors" who don't really know how to cook a non-standard "plain" connection. A newer more "recent" issue has been posted on the same "base problem"... will try to see if we can get invoke-dbaquery on board for it and then use it throughout the module (at least for install-). Keep updated on the issue and reporting your concerns at https://github.com/sqlcollaborative/dbatools/issues/3451
