### ISSUE TITLE
Include IF NOT EXISTS for Export-DbaUser

### ISSUE THREAD

**Issue by milawd** [sqlcollaborative/dbatools#2906]
The script created by Export-DbaUser does not include IF NOT EXISTS which would harden the script by preventing an error if the user already exist when running the it against a target database.

This is what is currently being scripted. 

CREATE USER [astra] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [astra]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [astra]
GO

It should be scripted as:

IF NOT EXISTS(SELECT name FROM sys.database_principals WHERE name ='astra')
CREATE USER [astra] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [astra]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [astra]
GO

**Comment by potatoqualitee** [comment]
I believe this was recently resolved by @ClaudioESSilva - claudio plz confirm 🎖

**Comment by ClaudioESSilva** [comment]
Hi @milawd, I have added this yesterday. Can you confirm you are using the latest version?
Thank you.

**Comment by milawd** [comment]
I ran Update-dbatools and the execute the following:

PS C:\Windows\system32> Export-DbaUser -SqlInstance localhost -Database mydatabase -User astra
[Export-DbaUser][10:14:54] Validating users on database [mydataabse]
USE [mydatabase]
GO
CREATE ROLE [db_executeuser]
GO
CREATE ROLE [db_executor]
GO
CREATE USER [astra] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [astra]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [astra]
GO
GRANT CONNECT TO [astra]  AS [dbo];
GO

Am I missing something?

**Comment by milawd** [comment]
Everything is working now...Thanks for implementing this
