### ISSUE TITLE
Install-Dba* need to support -LocalFile

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2909]
## Feature Request

Sometimes we cant have an Internet access, so we need ability to install from local file.

### Function need to be tweaked for  `-LocalFile` support
* Install-DbaFirstResponderKit
* Install-DbaMaintenanceSolution
### Already support `-LocalFile`
* Install-DbaWhoIsActive

**Comment by Tonyw72** [comment]
Just saw this...

I added a -Path parameter to Install-DbaMaintenanceSolution here:
https://github.com/Tonyw72/dbatools/tree/Add-Path-to-Install-dbaMaintenanceSolution

**Comment by potatoqualitee** [comment]
sweet! all looks good
