### ISSUE TITLE
Get-DbaServerRole does not output members

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#2911]
## Bug Report
Get-DbaServerRole doesnot output members only role information

There is no Login parameter as mentioned in the examples

### General Troubleshooting steps

- [X ] Verified running latest release of dbatools?
Yup 0.9.136 as 135 did not load the command!!
- [X ] Verified errors are not related to permissions?
- [ X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System 10.0.10586.0 Microsoft Windows NT 10.0.10586.0
 - PowerShell Version: 5.0.10586.1007
 - SQL Server
Major  Minor  Build  Revision
-----  -----  -----  --------
13     0      4001   -1      

## Steps to Reproduce

Get-DbaaServerRole -SqlInstance XXXX | ft

![image](https://user-images.githubusercontent.com/6729780/34202679-65fdfa12-e570-11e7-9ab3-8e1d8894adde.png)

![image](https://user-images.githubusercontent.com/6729780/34202725-8d5bc5d0-e570-11e7-9e98-80ab08309ff9.png)

Interestingly I couldnt find this command and wrote an update to Get-DbaRoleMember which did this and works as I expect

https://github.com/SQLDBAWithABeard/dbatools/commit/1aaf9702759f66f353d330f43ddc1d8144a695f8

**Comment by SQLDBAWithABeard** [comment]
pagin @wsmelton

**Comment by wsmelton** [comment]
Removed references to logins in help and examples.
