### ISSUE TITLE
Restore-DBADatabase gives a prompt for Powershell credential

### ISSUE THREAD

**Issue by MarinaSegal** [sqlcollaborative/dbatools#2918]
## Bug Report

 - PowerShell Version: 
 - SQL Server (Edition|Version): enterprise 2014-->

## Steps to Reproduce

![pscredentialprompt](https://user-images.githubusercontent.com/34749490/34270945-04674c34-e63f-11e7-96aa-9dd7377f402b.png)

 - [ ] Attach any screenshots (if possible/allowed)
 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Additional information

[DBAToolsLogout.txt](https://github.com/sqlcollaborative/dbatools/files/1580491/DBAToolsLogout.txt)

**Comment by potatoqualitee** [comment]
That is nasty, sorry. Can you attach the output of Get-DbatoolsLog so that we can see where it stopped? Then @Stuart-Moore can take a closer look. Stuart, it's likely an older system (Win2k12R2 with PS4. I can provide a server for you if you need to troubleshoot, I've seen this before)

**Comment by MarinaSegal** [comment]
Thanks, for the such quick respond. I just attached DBAToolsLog

**Comment by Stuart-Moore** [comment]
@potatoqualitee  - Test system would be good thanks

@MarinaSegal - Could you let me have the command line you were using to perform the restore? And can you let have the full error output please, it's truncated in the attached log, but it looks like it failed in Test-DbaBackupInformation trying to access the pathsh File G:\MSSQL_DATA\CCAH_MAIN... and  File I:\MSSQL_LOG\CCAH_MAIN_... but I don't have the actual error.

**Comment by MarinaSegal** [comment]
Hi there,I think you are right, running  with option  TrustBackupHistory  is not giving a prompt.I am using:  Restore-DbaDatabase  -SqlInstance SQLDBA2 -Path '\\sqldba2\j$\MSSQL_Backups\SQLDBA2\CCAH_MAIN\FULL'  -DatabaseName '\TESTDBDeleteOK' -OutputScriptOnlyI a m attaching support pack.
Merry Christmas, and Happy Holidays to you!
 Marina Segal 

    On Friday, December 22, 2017 2:44 AM, Stuart Moore <notifications@github.com> wrote:
 

 @potatoqualitee - Test system would be good thanks@MarinaSegal - Could you let me have the command line you were using to perform the restore? And can you let have the full error output please, it's truncated in the attached log, but it looks like it failed in Test-DbaBackupInformation trying to access the pathsh File G:\MSSQL_DATA\CCAH_MAIN... and File I:\MSSQL_LOG\CCAH_MAIN_... but I don't have the actual error.—

**Comment by Zhunya** [comment]
@MarinaSegal is it requirements that database name start with `\`?

**Comment by MarinaSegal** [comment]
Oleg, PrivetNo, it was a typo. I run it without |, and got the same result. The out put in the attachment.
Marina Segal 

    On Friday, December 22, 2017 11:28 AM, Oleg Strutinskii <notifications@github.com> wrote:
 

 @MarinaSegal is it requirements that database name start with \?—

**Comment by MarinaSegal** [comment]
I am closing this issue.  The problem was caused by passing the multiple databases, the function as it states supports only one database passed.

**Comment by potatoqualitee** [comment]
Excellent, thanks Marina! And thank you Stuart.
