### ISSUE TITLE
issue with sqlps / sqlserver being loaded after and .Query() disappearing

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2919]
I'm kinda thinking no but is there any way to prevent this?

![image](https://user-images.githubusercontent.com/8278033/34280222-a165d97a-e6b6-11e7-9be1-872d5bdc8a9f.png)

**Comment by wsmelton** [comment]
Being that we use the same library I don't see this being correct-able. For the most part we advertise that dbatools does not play well with the other modules.

I have not tested any of it since new releases have come around. Do we still need to look into this one, or just close?
