### ISSUE TITLE
Feature Request: Backup-DbaDatabase - backup name would include the instance name

### ISSUE THREAD

**Issue by MarinaSegal** [sqlcollaborative/dbatools#2921]
It would be nice if the backup name would include the instance name, this way the databses with the same names from the different servers will not be overwritten

**Comment by potatoqualitee** [comment]
I do like and support this idea, similar to Ola's setup-ish.

**Comment by wsmelton** [comment]
Are you saying doing something like this causes the backups to be overwritten?

```Backup-DbaDatabase -SqlInstance Server1,Server2,Server3,Server4 -Database Database1 -BackupDirectory '\\fileserver1\Backups'```

If so then I would consider this a bug and not a feature request @potatoqualitee

**Comment by MarinaSegal** [comment]
technically yes, this a bug, if you backup with the same name  from the different servers(example master) there is a chance that the backups will have the same timestamp.

**Comment by wsmelton** [comment]
Is it appending the backup to that same file or actually overwriting it from the next server?

**Comment by MarinaSegal** [comment]
It looks like it only does backup for the first server in the list.I used :Backup-DbaDatabase -SqlInstance  essdevdb,sqldba2,sqldba1 -Database CCAH_MAIN -BackupDirectory \\sqldba2\j$ -CopyOnly -type Fulland from Read-DbaBackupHeader -SqlInstance sqldba2 -Path  '\\sqldba2\j$\CCAH_MAIN_201712222204.bak'I am getting first server name. Am I using Backup-DbaDatabase incorrectly?
Thank you,Marina Segal 

    On Friday, December 22, 2017 9:39 PM, Shawn Melton <notifications@github.com> wrote:
 

 Is it appending the backup to that same file or actually overwriting it from the next server?—

**Comment by Stuart-Moore** [comment]
It'll be appending as we don't set INIT which defaults to true under smo 

Adding the server name to the filename is easy enough, will get it in today if not tomorrow
