### ISSUE TITLE
Faeture Request: Restore-DBADatabase: 

### ISSUE THREAD

**Issue by MarinaSegal** [sqlcollaborative/dbatools#2922]
### General Troubleshooting steps

- [ ] Verified running latest release of dbatools?
- [ ] Verified errors are not related to permissions?
- [ ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
 - PowerShell Version: 
 - SQL Server (Edition|Version): 

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by wsmelton** [comment]
@MarinaSegal I don't see any content in the request. The function noted in the title already exist. If you want to update your issue with the exact problem you are having with the function we can reopen it.

**Comment by MarinaSegal** [comment]
Sorry, Do you mean that is possible to accomplish by using other function? Or do you mean it is a parameter for Restore-DBADatabase?

**Comment by wsmelton** [comment]
Is what possible? Your issue has no content noting an question or problem.
