### ISSUE TITLE
Get-DbaToolsLog - Debug output should remove new lines

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2923]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
N/A

## Steps to Reproduce

Cause an error in any command that executes T-SQL, something like `Backup-DbaDatabase`. Output Get-DbaToolsLog will show the debug events from commands like `Get-DbabackupHistory` that were executed. However the output is unreadable.

It would be best to remove new lines from that output so it is just one big long string text. It will be a little unreadable, but the output will be easier to capture to tables, csv output, or our own log files in our scripts.

![image](https://user-images.githubusercontent.com/11204251/34316711-edcb8886-e761-11e7-87cf-bab154acb6e7.png)

**Comment by tengen10** [comment]
Would replacing the newlines with a string of "[CRLF]" work?
