### ISSUE TITLE
Remove-DbaDatabaseSafely and Remove-DbaDatabase

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2924]
This is strictly for discussion purposes and documenting opinions (compared to losing this in Slack 🐰 )

We have `Remove-DbaDatabase` and then `Remove-DbaDatabaseSafely`.

Remove-DbaDatabaseSafely, I'm not sure I follow some of the functionality in this command. One is the portion of removing database on Server1 but then having it create a SQL Agent job on Server2 that puts it back. Why would you want to restore the database back on Server2?

The main reason for this discussion is because the safe command needs a **big/huge** rewrite. It has multiple included functions that are now public functions (backups, new agent jobs, start Agent service, etc.).

**Comment by niphlod** [comment]
the way I see it, Remove-DbaDatabaseSafely was created to remove a database but be able to restore it "in a somewhat automated way".
Guess the major usecase is avoid wasting space on pricey drive but have a final golden backup in a slow/unexpensive storage offsite in case a dev pops by asking for the database (he just told you to drop).

The fact that a job can be created on server2 is just added bells and whistles, given that the most relevant thing - logic-wise - is done on server1, right before dropping the database.
You may want to drop a database from server1, cause, e.g., you're going to dispose it totally, but have a server2 which is the new substitute....
Or, server2 can be the trashbin server where every database goes to die ^_^... that being said, the added value of this function is not the possibility to have the job created on server2 but just the logic that _should_ ensure you have a last full consistent backup, verified, checked etc etc etc before dropping alltogether.
