### ISSUE TITLE
ContainmentType value different from [Microsoft.SqlServer.Management.Smo.ContainmentType]

### ISSUE THREAD

**Issue by irfancharania** [sqlcollaborative/dbatools#2938]
We've got dbatools installed on the build server, and I'm running scripts using Team Foundation Server PowerShell build task.

When calling **Repair-DbaOrphanUser** function from my script, I'm running into an issue with the following statement:
[$db.ContainmentType -ne [Microsoft.SqlServer.Management.Smo.ContainmentType]::None](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Repair-DbaOrphanUser.ps1#L135)

With the TFS build task always equates to **True**
Running with -NoProfile, it equates to **False** (the expected result)

Unfortunately, I don't have a way to specify "-NoProfile" as part of the build task.

Can you help me "reset" whatever may be causing this issue from within my script?

I'm using PowerShell 4.0

######################

**Called from Windows PowerShell ISE:**

PS E:\Tools\PowerShellScripts> $env:PSModulePath = $env:PSModulePath + ";C:\Program Files\WindowsPowerShell\Modules;"
Import-Module dbatools
Import-Module SQLPS -DisableNameChecking

PS SQLSERVER:\> $db = Get-DbaDatabase -SqlInstance "[instancename]" -Database "[dbname]"

PS SQLSERVER:\> $db.ContainmentType -ne [Microsoft.SqlServer.Management.Smo.ContainmentType]::None
True

Same steps called from PowerShell -NoProfile gives expected result of False

**Comment by potatoqualitee** [comment]
hey @irfancharania - thanks for the report. I'll let @ClaudioESSilva look into this more but I suggest importing dbatools _after_ SQLPS because SQLPS overrides some of our settings. I don't think this will impact this specific command, but you'll have issues later on.

**Comment by irfancharania** [comment]
Moving it above dbatools caused errors.

I'm not sure why the original script had "Import-Module SQLPS -DisableNameChecking" but removing it seems to have fixed the issue. I was able to run the whole script (with other functions) successfully.

Thanks! :)
