### ISSUE TITLE
Copy-SqlLogin suggestion for default database

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#295]
I noticed that copy-sqllogin sets the default database to master if the original default database doesnot exist on the destination server. I would alter that for none-sysadmins - these are the rules I set

sysadmins - default database master - as if SQL is available master should be available

None-sysadmins - specific database if absolutely needed otherwise tempdb as if SQL is available for normal users then tempdb should be available and also this mitigates users being unable to logon when their default database is moved from the server or becomes unavailable when they only need to access a different database and also mitigates the risk of users creating objects in or accessing the master database should further permissions allow them to when they "forget" to use the USE [DB} statement

My suggestion use tempdb as default database if default database does not exist

**Comment by niphlod** [comment]
this actually is the easier fix ever (https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-SqlLogin.ps1#L244) . 
The thing is, either we agree upon tempdb as the new default, fix it, and close this
or
we just close this.

**Comment by niphlod** [comment]
this will now get tracked onto #303 . Let's move the discussion there.
