### ISSUE TITLE
Command to Automatically add given dbs or list of dbs to AlwaysON Availability Group

### ISSUE THREAD

**Issue by TheRockStarDBA** [sqlcollaborative/dbatools#2956]
## Feature Request

 What problem or scenario would you like to solve with dbatools?

### Problem to solve
My company has a self service portal - "DatabaseAsService". We allow App team to create/backup/login provision databases.

Imagine just like Amazon or Azure that allows customers to create / backup and create logins etc.

Current need is to automatically add the new dbs to AlwaysON Availability Group (AOAG). This will auto provide HADR for new dbs 

It would be excellent if dbatools provide such flexibility using command like 

>**Add-DbaDBToAgHadr**  -sqlInstance -sqlcredential -db  -AGName (can be found with Get-DbaAvailabilityGroup)  -backupPath

### Additional information

- Check AOAG prerequisites and then only proceed further.
- Should have IgnoreDBs (single db or dblist)
- Should have -db (single db or dblist)
- Should have -backupPath (backup share accessible to all replicas)
- Accept AGName this way if multiple AG then it know what AG to add db to.
- should drop the restoring db on secondary or just use replace.
- Take full and tlog (if db is big, should go to msdb to see if any log backups needs to be applied).

This command can be invoked by ServerLevel Trigger (e.g. see my answer here https://dba.stackexchange.com/a/40275/8783)

We can poll sys.databases by createdate as well periodically and call the new command to add dbs to AOAG.

For newer versions, [automatic seeding](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/automatically-initialize-always-on-availability-group) should be supported as well. I am mainly looking for sql server 2014.

**This command will be invaluable for automation.**

 Note: @codykonior has done [some good work in this area](https://www.codykonior.com/2015/11/29/automatic-alwayson-availability-groups-for-sharepoint-on-sql-server/).

**Comment by wsmelton** [comment]
Thank you for the request. I'm going to close this one though because we already have a master issue related to the AG commands we are working on...I'm hoping to get these knocked out in next few months.

#1712
