### ISSUE TITLE
Plan cache, adhoc workloads and clearing the single-use plan cache bloat

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2966]
https://www.sqlskills.com/blogs/kimberly/plan-cache-adhoc-workloads-and-clearing-the-single-use-plan-cache-bloat/

Not sure what to name this command, but basically turn the following into a PS command (but use PS Stylings)

```sql
SELECT MB = sum(cast((CASE WHEN usecounts = 1 AND objtype IN ('Adhoc', 'Prepared') THEN size_in_bytes ELSE 0 END) as decimal(12,2)))/1024/1024 , UseCount = sum(CASE WHEN usecounts = 1 AND objtype IN ('Adhoc', 'Prepared') THEN 1 ELSE 0 END)
FROM sys.dm_exec_cached_plans
```

**Comment by chrgraefe** [comment]
I like Get-DbaQueryPlan in conjunction with Remove-DbaQueryPlan

Imagine you can filter query plans by type (Adhoc, Prepared) or by used database object or by used Memory of a single plan. 
The filtered result goes into Remove-DbaQueryPlan

just thougths

**Comment by potatoqualitee** [comment]
Ohhh great call! Thank you

**Comment by tboggiano** [comment]
I can work on this.

**Comment by wsmelton** [comment]
@chrgraefe how would Get-DbaQueryPlan differ from [Get-DbaExecutionPlan](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Get-DbaExecutionPlan.ps1)? // @potatoqualitee

**Comment by tboggiano** [comment]
That goes and gets specific query plan details this is set up to tell how much is being used by adhoc workloads that may be bloating your plan cache.  Then a second cmdlet to clear those from the plan cache to reclaim that memory for use by the plan cache or buffer pool or anything else SQL Server decides to use it for.

**Comment by potatoqualitee** [comment]
thanks tracy! here is a template that you can use for t-sql based commands. feel free to gut as necessary (but leave in the first 3 fields to keep standardized output)

https://github.com/sqlcollaborative/dbatools-templates/blob/master/Get-DbaSqlQueryBased.ps1

in the event that you dont need $db.Query(), you can use $server.Query() (our own add-on) 👍

**Comment by wsmelton** [comment]
Ok, so there is no need to write a new command to get query plans. The current command should be adjusted to also meet your needs. Unless @potatoqualitee sees a different need.

**Comment by potatoqualitee** [comment]
ahh good point, I think the removal would be beneficial however

**Comment by tboggiano** [comment]
Maybe it just needs to be named better, Get-DbaAdhocPlanUsage so you can see what how much memory is being used by adhoc workloads.  And Remove-AdhocPlans to remove them from the cache if they are over a certain threshold.  We aren't talking about removing or retrieving a single execution plan but rather all adhoc plans so Get-DbaExecutionPlan doesn't fit the build for what is linked in the the SQLskills article.

**Comment by potatoqualitee** [comment]
Also a good point

**Comment by wsmelton** [comment]
Review of that SQLSkills articles @potatoqualitee this is more a test command than anything. It is pulling aggregated data on the plan cache and then testing for a given threshold, then based on that you remove all or just the ad-hoc plans. So whether you call it `Test-DbaPlanUsage` or `Test-DbaAdhocPlanUsage` could be done. In that event, you could go either way of using the get command we have and aggregate the data using PowerShell-way or just letting T-SQL code from the article be used (which will likely perform better on large systems).

I will leave it up to @potatoqualitee to make the final call.

**Comment by wsmelton** [comment]
The `Remove-DbaQueryPlan` I think could also be named wrong, if we are being strict to what the article is referring to.

There are [8 different ways to clear the plan cache in SQL Server](https://www.sqlskills.com/blogs/glenn/eight-different-ways-to-clear-the-sql-server-plan-cache/). If the remove command will support all 8 options, then I'd say it meets the purpose. If not, then it is more like `Clear-DbaExecutionPlan [-Adhoc] [-All]`.

**Comment by tboggiano** [comment]
Just my two cents worth I've needed to set up jobs for this.  Even when for adhoc optimize for adhoc worklaod was turned on. See my blog post here where I automated this a few other troublesome cahces. ]http://tracyboggiano.com/archive/2017/10/cleaning-up-troublesome-sql-server-caches-using-up-memory/)
