### ISSUE TITLE
New-DbaClientAlias

### ISSUE THREAD

**Issue by goforebroke** [sqlcollaborative/dbatools#2974]
### General Troubleshooting steps

- [X ] Verified running the latest release of dbatools?
- [ X] Verified errors are not related to permissions?
- [ X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): 
Windows 2016
 - PowerShell Version: 
v5
 - SQL Server (Edition|Version): 
2012 and above

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

## Feature Request

Can a parameter be added to support populating the "Parameters" field for an alias?

**Comment by potatoqualitee** [comment]
doesn't sound too hard, can you show me a screenshot or give me an example of the ideal usage?

**Comment by goforebroke** [comment]
New-DbaClientAlias works great setting an alias for a named instance per your examples, but what if sql server is running as a default instance on a non default port (not 1433)? If a default instance is running on a port other than 1433, the connection must be made with "ServerName,PortNbr".  An alias with the port specified in the "Parameters" field will allow me to connect from the workstation with "ServerName" only.

**Comment by potatoqualitee** [comment]
Does this solve the problem?
`New-DbaClientAlias -ServerName 'abc,123' -Alias hello`

![image](https://user-images.githubusercontent.com/8278033/34543051-55fafd20-f0df-11e7-87f1-e35811b7037c.png)

**Comment by goforebroke** [comment]
Yes it does thank you! Configuration Mgr strips out the port and places it in the parameter field automatically. Thank you very much

**Comment by goforebroke** [comment]
These are very useful tools that have saved a lot time and assisted with automation through our private cloud. We use them extensively since our environment is quite large. We use SQLServerDSC and DBATools to automatically provision our SQL Installs (DB, SSAS, SSRS, SSIS, Mgmt Studio) and adhere to a set of installation & performance standards. Thank you for such a useful resource.

**Comment by potatoqualitee** [comment]
I'm super happy that helped! And always love to hear about how dbatools is being used 🤗 

I will update the webpage and examples so others can know how to do it.
