### ISSUE TITLE
Get-DbaBackupHistory reports incorrect TotalSize for backups that are striped.

### ISSUE THREAD

**Issue by tengen10** [sqlcollaborative/dbatools#2981]
### General Troubleshooting steps

- [X] Verified running the latest release of dbatools? 
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 2016. 
 - PowerShell Version:     5.1.14393.1944      
 - SQL Server (Edition|Version): SQL 2008, SQL 2016

## Steps to Reproduce
```
-- Create a backup with multiple files
BACKUP DATABASE [DB1] 
TO  DISK = N'c:\temp\db1_1.bak'
,  DISK = N'c:\temp\db1_2.bak'
,  DISK = N'c:\temp\db1_3.bak'
,  DISK = N'c:\temp\db1_4.bak' 
WITH INIT
GO
```

Run Get-DBABackuphistory -database DB1  | Select TotalSize

The size will be larger than expected.   The msdb..backupset column backup_size appears to be the total size of the backup irrespective of the number of files it's striped over.  When the join occurs to that table it returns one row for each file in the stripe set and the total size rather than than the size of each file in the set.  Those rows then appear to be summed and returned.

`
$historyObject.TotalSize = ($group.Group.TotalSize | Measure-Object -Sum).Sum
`

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by potatoqualitee** [comment]
Thanks @tengen10!
