### ISSUE TITLE
Copy-DbaCredential doesn't seem to work for Azure storage access key credentials

### ISSUE THREAD

**Issue by pagerwho** [sqlcollaborative/dbatools#2994]
When I attempted to use Copy-DbaCredential to migrate a Azure Storage account credential from one of my servers (12.0.5546) to another (13.0.4422) the secret seems to get garbled.  Re-entering the secret resolves the issue.  This causes any Azure backups/restores to fail in unexpected ways.

**Comment by potatoqualitee** [comment]
hey pager, can you confirm this is still an issue? my assumption is yes

**Comment by pagerwho** [comment]
Hi Chrissy,

I'm not able to validate if this issue remains at this time as my current position is not making use of Azure for backups.

**Comment by potatoqualitee** [comment]
I just tested and things look good, pasted some sample code from [SO](https://stackoverflow.com/questions/44556794/create-credential-is-not-supported-in-this-version-of-sql-server-azure-sql-d) and it exported properly with `Export-DbaCredential` which uses the same decrypt mechanism 👍

````
CREATE CREDENTIAL [mycredential] WITH IDENTITY = N'storageaccountname', SECRET = N'DefaultEndpointsProtocol=https;AccountName=storageaccountname;AccountKey=8L==;EndpointSuffix=core.windows.net'

CREATE CREDENTIAL [azureblob] WITH IDENTITY = N'SHARED ACCESS SIGNATURE', SECRET = N'testtest'
````
