### ISSUE TITLE
Export-DbaLogin uses "ALTER ROLE ADD MEMBER" on older versions of Sql Server where it's not supported

### ISSUE THREAD

**Issue by dnc-msimons** [sqlcollaborative/dbatools#2995]
## Bug Report

Export-DbaLogin outputs role membership additions as:
ALTER ROLE [<role>] ADD MEMBER [<user>]
which is only valid syntax starting with SQL 2012 (according to https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-role-transact-sql).

Export-DbaUser outputs role membership additions as:
EXEC sys.sp_addrolemember @rolename = N'<role>', @membername = N'<user>'

### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2008 R2 Enterprise
 - PowerShell Version:  5.1.14409.1012
 - SQL Server (Edition|Version): SQL Server 2008 R2 SP1 10.50.2550.0

**Comment by ClaudioESSilva** [comment]
Thanks for the report @dnc-msimons .
We are aware of it. I'm currently working on an improvement to this command to behave like `Export-DbaUser`.

**Comment by ClaudioESSilva** [comment]
Hi @dnc-msimons,
Please pick the latest version and give it a try! If it is OK we will close this issue.

Thanks!

**Comment by dnc-msimons** [comment]
Hi @ClaudioESSilva, 

On line 323 where it's working on server-level roles:
                        $outsql += "EXEC sys.sp_addrolemember @rolename = N'$roleName', @membername = N'$userName'"

The function name for server role changes should be "sys.sp_addsrvrolemember" and instead of "@membername", it should be "@loginame"

                        $outsql += "EXEC sys.sp_addsvrrolemember @rolename = N'$roleName', @loginame = N'$userName'"

**Comment by dnc-msimons** [comment]
And thanks for taking this on.

The output of this function and Export-DbaUser saved me hours of manual work for a domain-forest collapse project we've got going on.

**Comment by ClaudioESSilva** [comment]
Thanks @dnc-msimons.
PR in place. If you can, get it and test again, please.

**Comment by dnc-msimons** [comment]
Looks good to me.  Thanks again, Claudio!

**Comment by ClaudioESSilva** [comment]
Thanks @dnc-msimons.
Will close this one.
