### ISSUE TITLE
Find-DbaOrphanedFile bug

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#300]
From two users:

1. Hekaton directories were appearing
2. This issue:

I found a bug in the Find-DBaOrphanedFiles command. if you have any filestream filegroup, this would include in-memory tables, then this command flags those files as orphans.

A where clause could be added to the sql that gets all files to only get types 0 and 1. This would stop the  command from incorrectly flagging these as orphans.

line 100: 	$sql = "SELECT Physical_Name AS filename FROM sys.master_files mf INNER JOIN  sys.databases db ON db.database_id = mf.database_id where type in (0,1)"

alternatively, directories can be added to the filesondisk results. this would be preferred as it would also check for these valid file but would unfortunately find any other directories in the paths. (this edit attached).

[bk-Find-DbaOrphanedFile.txt](https://github.com/sqlcollaborative/dbatools/files/570154/bk-Find-DbaOrphanedFile.txt)

Please resolve in November

**Comment by ctrlbold** [comment]
User for issue #1 just reported that it was indeed a orphaned hekaton directory. Would love to get the files within the directory but uh, unsure how to do that since the stored proc returns only filenames so getting the associated directory would be challenging,

**Comment by ConstantineK** [comment]
this was fixed in #307
