### ISSUE TITLE
Invoke-DbaSqlCmd - please accept filesystem object

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3018]
[13:33:28][00:00:00] C:\github\dbachecks> Invoke-DbaSqlcmd -SqlInstance sql2012 -File (Get-ChildItem $home\downloads\xe\*.sql)
Invoke-DbaSqlCmd : Cannot process argument transformation on parameter 'File'. Cannot convert value to type
System.String.
At line:1 char:45

**Comment by potatoqualitee** [comment]
Noooo and GO too

![image](https://user-images.githubusercontent.com/8278033/34825953-ea46996c-f6d4-11e7-8f4d-fc85393ba69a.png)

**Comment by potatoqualitee** [comment]
Thre must be something in SqlCommand that supports go

**Comment by chrgraefe** [comment]
An Example, but without SqlCommand
https://weblogs.asp.net/jongalloway/Handling-_2200_GO_2200_-Separators-in-SQL-Scripts-_2D00_-the-easy-way

**Comment by niphlod** [comment]
No issues, just sidecases that IMHO are not sufficient enough to postpone
the fix further

Gimme a few hours and I'll update invoke-sqlcmd2 properly, than we can
merge back here.

Il 11 gen 2018 4:58 PM, "Friedrich Weinmann" <notifications@github.com> ha
scritto:

**Comment by niphlod** [comment]
for "GO", see https://github.com/sqlcollaborative/Invoke-SqlCmd2/pull/18

**Comment by FriedrichWeinmann** [comment]
Implemented in:
https://github.com/sqlcollaborative/dbatools/pull/3024
