### ISSUE TITLE
Find-DbaOrphanedFile returns bad info

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#302]
I found what I think are two issues.

1.) On a Windows 2008 Server with SQL 2008 the command returns the same file twice. 
2.)  The second issue is the file returned actually is connected to a database if you look in master_files

Attached is an export @ctrlbold had me generate on the system and two screens shots of the file/db in question.
![1](https://cloud.githubusercontent.com/assets/169602/20010962/0a378be4-a278-11e6-9ed3-87b8420914fa.PNG)
![2](https://cloud.githubusercontent.com/assets/169602/20010965/0beaa2aa-a278-11e6-8ad7-7138517a6f6c.PNG)

**Comment by ConstantineK** [comment]
This should be fixed in #263, and in fact @gbargsley tested it for me.
