### ISSUE TITLE
Backup-DbaDatabase using -WhatIf receives error

### ISSUE THREAD

**Issue by backintheday41** [sqlcollaborative/dbatools#3020]
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
[dbatools_support_pack_2018_01_11-11_53_25.zip](https://github.com/sqlcollaborative/dbatools/files/1623444/dbatools_support_pack_2018_01_11-11_53_25.zip)

## Steps to Reproduce

A dbatools support package is attached to this issue.

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

## Feature Request

When executing Backup-DbaDatabase with the -WhatIf parameter, errors are returned: "Add-Member : Cannot bind argument to parameter 'InputObject' because it is null."

### Problem to solve

Allow the function to adequately report results when the -WhatIf parameter is used.

### Additional information

A dbatools support package is attached to this issue.

**Comment by Stuart-Moore** [comment]
Fixed with PR #3056
