### ISSUE TITLE
Restore-DbaDatabase - restored database left in restoring state

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#3027]
## Bug Report

As can be seen on screenshot

- function restores last file twice (4 and 5)
- leaves restored database in `Restoring` state (but 2 and 3 telling us another story)

Seems this happens due to time which points right in backup starting point, its time when LOG backup starts.

![2018-01-12_10-01-56](https://user-images.githubusercontent.com/14327077/34863483-bfc13592-f780-11e7-9098-31af1132691e.png)

Second related error:

```powershell
>$bh = Get-DbaBackupHistory -SqlInstance srv-sql\u -Database v8_2017 -Last
> $bh | Restore-DbaDatabase -SqlInstance srv-sql\u -DestinationDataDirectory J:\MSSQL\DATA -DestinationLogDirectory M:\MSSQL\DATA -RestoreTime '2018-01-12 09:07:01' -TrustDbBackupHistory -DestinationFilePrefix 2170112_0900_ -RestoredDatababaseNamePrefix 2170112_0900_

WARNING: [Test-DbaLsnChain][11:05:47] More than 1 full backup from a different LSN, or less than 1, neither supported
WARNING: [Restore-DbaDatabase][11:05:47] 2170112_0900_2170112_0900_v8_2017 failed testing, AllowContinue not set, exiting
```
GetBackupInformation and SelectBackupInformation here - [gbi_sbi.zip](https://github.com/sqlcollaborative/dbatools/files/1625315/gbi_sbi.zip)

If Restore time not equals backup start time we will not get this error.

### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

## Steps to Reproduce
```powershell
Restore-DbaDatabase -Path \\srv-backup01\sql_backup\Archive\SRV-1C -SqlInstance srv-1c-dev -DatabaseName v8_Update -WithReplace -RestoreTime '2018-01-11 18:00:00'
```

**Comment by Stuart-Moore** [comment]
Was this working a couple of days ago? There was a change pushed in for Select-DbaBackupInformation that altered an time matching case

**Comment by Zhunya** [comment]
Pulled latest dev and got second error.
Run first command to be sure, error with recovery in place.

**Comment by Zhunya** [comment]
Usually I don't have restores to point in time, so can't say when it worked fine. And remembering problem with restore to point in time, when StopAt equals backup start time I add/subtract one second

**Comment by Zhunya** [comment]
Run First test again, database left in restoring state and this error 

```powershell
SqlInstance            : SRV-1C
DatabaseName           : v8_DELETE_ME_Update
DatabaseOwner          : *
NoRecovery             : True
WithReplace            : True
RestoreComplete        : True
BackupFilesCount       : 1
RestoredFilesCount     : 2
BackupSizeMB           : 5,83
CompressedBackupSizeMB : 1,21
BackupFile             : \\srv-backup01\sql_backup\Archive\SRV-1C\SRV-1C_v8__LOG_20180111_173000.trn
RestoredFile           : delete_mev8_.mdf,delete_mev8_log.ldf
RestoreDirectory       : E:\MSSQL\Data
Script                 : {RESTORE LOG [v8_DELETE_ME_Update] FROM  DISK = N'\\srv-backup01\sql_backup\Archive\SRV-1C\SRV-1C_v8_LOG_20180111_173000.trn' WITH  FILE = 1,  MOV           E N'v8_UPP' TO N'E:\MSSQL\Data\delete_mev8_.mdf',  MOVE N'v8__log' TO N'E:\MSSQL\Data\delete_mev8_log.ldf',  NORECOVERY, NOUNLOAD,  STATS = 10,  STOPAT = N'01/11/2018 18:00:00'}

WARNING: [Invoke-DbaAdvancedRestore][12:35:30] Failed to restore db v8_DELETE_ME_Update, stopping | Exception calling
"SqlRestore" with "1" argument(s): "Restore failed for Server 'srv-1c-dev'. "

SqlInstance            : SRV-1C
DatabaseName           : v8_DELETE_ME_Update
DatabaseOwner          : *
NoRecovery             : False
WithReplace            : True
RestoreComplete        : False
BackupFilesCount       : 1
RestoredFilesCount     : 2
BackupSizeMB           : 3,58
CompressedBackupSizeMB : 0,87
BackupFile             : \\srv-backup01\sql_backup\Archive\SRV-1C\SRV-1C-_LOG_20180111_180000.trn
RestoredFile           : delete_medelete_mev8_.mdf,delete_medelete_mev_log.ldf
RestoreDirectory       : E:\MSSQL\Data
Script                 : {RESTORE LOG [v8_DELETE_ME_Update] FROM  DISK = N'\\srv-backup01.\sql_backup\Archive\SRV-1C\SRV-1C-v8__LOG_20180111_180000.trn' WITH  FILE = 1,  MOVE N'v8' TO N'E:\MSSQL\Data\delete_medelete_mev8_.mdf',  MOVE N'v8_log' TO N'E:\MSSQL\Data\delete_medelete_mev8_og.ldf',  NOUNLOAD,  STATS = 10,  STOPAT = N'01/11/2018 18:00:00'}
```

Error message was: 
```
The file 'v8_log' cannot be moved by this RESTORE operation.
Problems were identified while planning for the RESTORE statement. Previous messages provide details.
RESTORE LOG is terminating abnormally.
```

**Comment by Zhunya** [comment]
Seems this is fixed by #3032

Needs more testing

**Comment by Stuart-Moore** [comment]
Really? Bloody 'ell, that's a suprise! Still think it was @nvarscar patch that's most likely to have fixed yours.

**Comment by Stuart-Moore** [comment]
Morning,
Is this definitely fixed now?

**Comment by Zhunya** [comment]
Hi,
have no time to test on weekend, give me more time please, will report later today

**Comment by Stuart-Moore** [comment]
No problem. Was just closing down a couple of Issues, and wanted to check
if this one was still needed.

**Comment by Zhunya** [comment]
Tried to run some tests to restore DB to point in time, and have error described in [comment above](https://github.com/sqlcollaborative/dbatools/issues/3027#issuecomment-357192659). When `RestoreTime` -eq `BackupStartTime` restore process finish with error.

- source instance — SQL Server 2008 R2
- destination instance — SQL Server 2014
- Command issued: `Restore-DbaDatabase -Path \\srv-backup01\sql_backup\Archive\SRV-1C -SqlInstance srv-1c-dev -DatabaseName v8_DELETE_ME_Update -WithReplace -RestoreTime '2018-01-11 17:30:00' -DestinationFilePrefix filePrefix_` (folder with just bunch of backup files for one database)
- Latest restored LOG was from 17:00:00 (backups in 30 min increment)
- if `RestoreTime` not equals `BackupStartTime` restore finish w/o errors.

**Comment by nvarscar** [comment]
Hmm. Can it be that the same backup file gets selected twice because of the ambiguity in predicates in elect-DbaBackupInformation?

```
                $FilteredLogs = $DatabaseHistory | Where-Object {$_.Type -in ('Log', 'Transaction Log') -and $_.Start -le $RestoreTime -and $_.LastLSN.ToString() -ge $LogBaseLsn -and $_.FirstLSN -ne $_.LastLSN}  | Sort-Object -Property LastLsn, FirstLsn
<...>
                $dbHistory += $DatabaseHistory | Where-Object {$_.Type -in ('Log', 'Transaction Log') -and $_.End -ge $RestoreTime
```
If $RestoreTime -eq backup start time, than $_.Start -le $RestoreTime will include the last needed backup, but then, when it comes to selecting the last backup in the chain that started after $RestoreTime, the script will also include the same backup file: $_.End -ge $RestoreTime
Maybe replacing `$_.Start -le $RestoreTime` with `$_.Start -lt $RestoreTime` will fix the issue?

**Comment by nvarscar** [comment]
Also, there is probably an even better option: to move last T-Log part before grouping so that even if they manage to capture the same log file, only one of the results will be added to the output:
```
                $FilteredLogs = $DatabaseHistory | Where-Object {$_.Type -in ('Log', 'Transaction Log') -and $_.Start -le $RestoreTime -and $_.LastLSN.ToString() -ge $LogBaseLsn -and $_.FirstLSN -ne $_.LastLSN}  | Sort-Object -Property LastLsn, FirstLsn
                # Get Last T-log
                $FilteredLogs += $DatabaseHistory | Where-Object {$_.Type -in ('Log', 'Transaction Log') -and $_.End -ge $RestoreTime -and $_.DatabaseBackupLSN -eq $Full.CheckpointLSN} | Sort-Object -Property LastLsn, FirstLsn  | Select-Object -First 1
                $GroupedLogs = $FilteredLogs | Group-Object -Property LastLSN, FirstLSN
                ForEach ($Group in $GroupedLogs) {
                    $Log = $DatabaseHistory | Where-Object {$_.BackupSetID -eq $Group.group[0].BackupSetID} | select-object -First 1
                    $Log.FullName = ($DatabaseHistory | Where-Object {$_.BackupSetID -eq $Group.group[0].BackupSetID}).Fullname
                    $dbhistory += $Log
                }
```

**Comment by Zhunya** [comment]
@nvarscar solution works

**Comment by nvarscar** [comment]
I slept on it and came up with a scenario where grouping that includes last T-Log might actually remove that particular T-Log from the list altogether, like this:

Type | FirstLsn | LastLsn
----- | ---------|---------
Full|1|2
TLog|1|3
TLog|3|4
TLog|4|4
TLog|4|4 <- Restore point

That, in turn, might be solved by ordering dataset by BackupSetId as well prioritizing the last backup over first:
```
                $FilteredLogs = $DatabaseHistory | Where-Object {$_.Type -in ('Log', 'Transaction Log') -and $_.Start -le $RestoreTime -and $_.LastLSN.ToString() -ge $LogBaseLsn -and $_.FirstLSN -ne $_.LastLSN} 
                # Get Last T-log
                $FilteredLogs += $DatabaseHistory | Where-Object {$_.Type -in ('Log', 'Transaction Log') -and $_.End -ge $RestoreTime -and $_.DatabaseBackupLSN -eq $Full.CheckpointLSN} | Sort-Object -Property LastLsn, FirstLsn, BackupSetId  | Select-Object -First 1
                $FilteredLogs = $FilteredLogs | Sort-Object -Property LastLsn, FirstLsn, @{Expression = {$_.BackupSetId}; Descending = $true} 
```

**Comment by Zhunya** [comment]
Closing... all fine now.
