### ISSUE TITLE
Get-DbaBackupHistory - should include uncompressed backup information

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#3035]
## Feature Request
In cases where we want to review backup history for growth or predicting space requirements for database growth it would help to include the following:

- compressed backup size
- uncompressed backup size
- Compression ratio (`mediaset.dbo.backup_size/mediaset.dbo.compressed_backup_size`).

It seems reading the code that the `TotalSize` property is the compressed backup size so to prevent the need of changing other commands just have new properties added as maybe `TotalSize_Uncompressed` and `CompressionRatio`.

**Comment by Stuart-Moore** [comment]
Thanks for reminding me I was working on this. resurrected an old branch and PR 3057 should do this.
