### ISSUE TITLE
Azure SQL: Logical SQL Server has lots of empty properties

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#3073]
## Information

We can connect to a logical server in Azure as we do to a SQL Instance.
But lots of the properties of the server object will not be populated.

## Problem

Issues can occur when functions rely on instance properties to do their thing.
@FriedrichWeinmann is already working to replace the missing [NetName], [InstanceName] and [ServiceName],
but more functions can be impacted, when using Backup Directory, Logins, Mail or other.

[serverprops.txt](https://github.com/sqlcollaborative/dbatools/files/1635081/serverprops.txt)

**Comment by wsmelton** [comment]
The other problem (not sure if it is on your text file) is the version returned when you connect to Azure SQL instance. It will not match up to any version of an on premise instance. So in commands where we validate the version to be higher than say 2012 it can still fail on Azure SQL, even though code base is higher that SQL Server.

**Comment by PowerDBAKlaas** [comment]
Indeed.
And similar problems on the database level.
A SQL Database has no `.QueryStoreOptions` properties, although there is Query Store.
Would T-SQL be the most reliable way to go for some functions?

**Comment by wsmelton** [comment]
Even if query store does not exist just means commands we have that touch it (or try to) via SMO would fail. So we might need to put in some check to validate if the server is Azure SQL or not.

Maybe an internal command or something that does that check, or we add a special property in the connect command?

**Comment by PowerDBAKlaas** [comment]
I was wrong on the QueryStoreOptions: they are there just as on SQL Server.
It is `Get-AzureRmSqlDatabase` that returns a different object: `Microsoft.Azure.Commands.Sql.Database.Model.AzureSqlDatabaseModel`
(Just found another issue with this one: SMO object does not contain all properties, `[sys].[database_query_store_options]` has more. So, T-SQL would be the best way to go anyway, but this is an issue for the QueryStore functions.)

**Comment by andreasjordan** [comment]
This issue has a Feature label - but I don't see the needed feature here. Can we close this?
