### ISSUE TITLE
Add a OutFileMapping switch and output to Get-DbaDatabaseFile

### ISSUE THREAD

**Issue by Stuart-Moore** [sqlcollaborative/dbatools#3080]
### Problem to solve
Add an easy way to build the FileMapping Hashtable for Restore-DbaDatabase from an existing database

For example:
`$FileMapping = Get-DbaDatabaseFile -SqlInstance Instance1 -Database db1 -OutFileMapping`

Would return $FileMapping of type Hashtable like this:
```
$FileMapping = @{
"Datafile1"  = "c:\data\datafile1.mdf";
"Datafile2" = "d:\ArchiveData\File2.mdf";
"LogFile1" = "e:\LogFiles\Log1.ldf"}
```

**Comment by potatoqualitee** [comment]
please do 👍

**Comment by ChrisTuckerNM** [comment]
Questions:
1) Should the command be called with multiple SqlInstance values, what would the behavior be?
2) Does select-object @{Name="name"; Expression={$_.LogicalName}},@{Name="value"; Expression={$_.PhysicalName}} cover the requirement?

**Comment by Stuart-Moore** [comment]
Morning,
1- Good question. Personal preference would be for a custom object along the lines of:
[PSCustomObject]@{
ComputerName
InstanceName
Database
MappingHash
}

Whilst this usecase doesn't really support multiple dbs (Restore won't use hash for moves atm if more than 1 db is specified, though that's not a breaker, so it could be implement post this) this one would be consistent with dbatools practice, and make it easy for the user to extract the ones they need with a pipe through Where-Object

Or we could just refuse multiple instances with this switch.........

2 - I don't think so. The Restore command is expecting a hashtable for all the files in a db whereas  that would just provide the table for 1 file so the user would still need to concatenate them themselves

This option is really going to be adding another output option. The current code spits out an object per file, whereas this would be an object per database, so probably branch at L175, group by databasename and then looping through that.

**Comment by niphlod** [comment]
I don't think is good to change result format via a single switch. 
Instead of changing behaviour and result format at this point I'd go for splitting an internal function that fetches the info per database (and can be reused by restore-dbadatabase) and is used within get-dbadatabasefile to give the same result as it is now.

**Comment by niphlod** [comment]
I don't expect much user would need it as it's really easy to build that up starting from get-dbadatabasefile straight. Get-DbaDatabaseFileMap as internal sounds good.

**Comment by Stuart-Moore** [comment]
Yeah, I vaguely remember that was the gist of the slack conversation. 
`Get-This | Select-This | Format-That`
but was seen as too tricky by the other party.

Maybe just add examples to the CBH for restore-dbadatabase under the Filemapping parameter help and Get-DbaDatabaseFile in the example sections?

**Comment by ChrisTuckerNM** [comment]
I'm advocating an example in CBH too.

**Comment by ChrisTuckerNM** [comment]
Taking myself off this till we understand what..

**Comment by andreasjordan** [comment]
Interesting feature.

We only need info returned from Get-DbaDatabase:

```
$db = Get-DbaDatabase -SqlInstance SRV1B -Database AdventureWorks
$fileMap = @{}
foreach ($file in $db.FileGroups.Files) {
    $fileMap[$file.Name] = $file.FileName
}
foreach ($file in $db.LogFiles) {
    $fileMap[$file.Name] = $file.FileName 
}
[PSCustomObject]@{ 
    ComputerName = $db.ComputerName
    InstanceName = $db.InstanceName
    SqlInstance  = $db.SqlInstance
    Database     = $db.Name
    FileMap      = $fileMap
}
```

Do we agree on Get-DbaDbFileMap as the name of the new command?

**Comment by potatoqualitee** [comment]
Good command name, but does `Get-DbaDbFile` not fit the bill?

![image](https://user-images.githubusercontent.com/8278033/122930569-62a76b80-d36c-11eb-8ab9-49b198055cbc.png)

**Comment by andreasjordan** [comment]
We need that hash that is returned in FileMap.

**Comment by potatoqualitee** [comment]
oh ah! sorry, I skipped to the bottom. k, sounds good!

**Comment by andreasjordan** [comment]
@potatoqualitee : As you are creating a lot of new commands at the moment: Can you take my code (https://github.com/sqlcollaborative/dbatools/issues/3080#issuecomment-845136694) and create the command around it?

I would think we only need parameters -SqlInstance, -SqlCredential and -Database, maybe allow piped input from Get-DbaDatabase as well.

**Comment by potatoqualitee** [comment]
I can indeed 👍🏼
