### ISSUE TITLE
Get-DbaBackupHistory with -LastFullBackup — sometimes wrong output

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#3087]
## Bug Report
![image](https://user-images.githubusercontent.com/14327077/35087893-c80c850a-fc42-11e7-8f8c-188c7d5e8e3b.png)

`Get-DbaBackupHistory` with `Get-DbaRegisteredServer`
- (1-2) wrong `SqlInstance` reported. Those databases (*2011 and *2017) on different cluster resource group (SRV-SQL-CLA) on second physical in same physical cluster. 
- (3-5) wrong date for last full backup

**Comment by niphlod** [comment]
for 3-5 ..... 5 shows the START date, 3 shows the END date. isn't that just fine ?

**Comment by Stuart-Moore** [comment]
3 Looks like job start time. Nothing to do with backup start time. Backups are started sequentially, so that will increase as you run through the job, explains 4&5

Run Get-DbaBackuphistory directly against the instances to work out if that's culprit

Then run it with -Debug and run the T-SQL in SSMS against the instance to see if the history is an issue. If it's wrong there, there's nothing we can do.

**Comment by Zhunya** [comment]
- 3 first run command `Get-DbaRegisteredServer` + `Get-DbaBackupHistory` - last backup DATE (skip time) is wrong
- 4 after spotting difference in host name, I run `Get-DbaDatabase` where we spot difference in FULL backup DATE with (3) and with agent job (5) 
- 5 finaly I'm looking an agent job log

 I'm ok with `TIME` minutes but `DATE` differs between `Get-DbaBackupHistory -LastFull' and `Get-DbaDatabase` `LastFullBackup' property values.

**Comment by Zhunya** [comment]
and of course - Why `SqlInstance` for those databases reported incorrectly with piping `Get-DbaRegisteredServer` to `Get-DbaDatabase`

**Comment by Stuart-Moore** [comment]
you need to start breaking down the pipeline to work out where the error is. First of try something like this 
```
('localhost\sqlexpress2016','localhost\developer2016') | Get-DbaBackupHistory -LastFull | Where-Object {} | OGV
```

Could be Get-DbaRegSrv is reporting the servername rather than the instancename.

**Comment by Zhunya** [comment]
Thank you guys, I broke pipeline, problem in `Get-DbaBackupHistory`, will look into internals soon.

**Comment by niphlod** [comment]
@Zhunya : is this still valid ? if not, would you mind close this issue ?

**Comment by Zhunya** [comment]
Yes, issue is still valid, I will PR fix ASAP.

**Comment by Zhunya** [comment]
I'll close this one, I found that this is not a bug, but "feature" (line 287).
Get-DbaBackupHistory need little bit of love.
