### ISSUE TITLE
New cmdlet request - SQL 2016 AOAG direct seeding

### ISSUE THREAD

**Issue by Zuldan** [sqlcollaborative/dbatools#310]
Currently the only way to setup direct seeding is by SQL query. It would be fantastic to have a cmdlet to setup a direct seed as well as a cmdlet to read the current status of a direct seed to make it easier for us Powershell guys to setup AOAG and perform migrations.

@MikeFal has a great blog on it http://www.mikefal.net/2016/06/14/tsql2sday-sql-2016-direct-seeding/

**Comment by wsmelton** [comment]
Thanks @Zuldan for the request. I will get with @ctrlbold how we might we implement this feature.

This looks intriguing. I'm thinking more toward building out cmdlet(s) that would help you build the AG (just the AG part, not the WSFC). We could then workout how to make the cmdlet(s) support the current features from 2012+, to include direct seeding. There are a few of us that work with AGs a good bit that could work something out for this request.

**Comment by Zuldan** [comment]
Sounds like a good plan @wsmelton. Looking forward to direct seeding support in Powershell! ;-)

**Comment by ctrlbold** [comment]
I dig, but suck with AGs for now. Who else on the team does AGs and would like to participate in design? @Zuldan what would you like to see?

**Comment by Zuldan** [comment]
Looks like @MikeFal is the AG guru. Here's him using native AG cmdlets http://www.mikefal.net/2015/03/10/building-availability-groups-with-powershell/

@ctrlbold I'm still testing AG in 2016 in the lab. Will let you know my thoughts after some further investigation of the new features.

**Comment by potatoqualitee** [comment]
@wsmelton - I've created a new tag called AG and will tag all AG's as we go since this is something that we'd like to focus on in the near future

**Comment by potatoqualitee** [comment]
This is now supported in `New-DbaAvailabilityGroup` 🍰 💯
