### ISSUE TITLE
Copy-SqlDatabase -BackupRestore -Networkshare fails

### ISSUE THREAD

**Issue by Mandarnold** [sqlcollaborative/dbatools#311]
The copy-sqldatabase.ps1 uses the Test-SqlPath.ps1 for testing the Networkshare-Parameter is work. Something inside the Test-SQLPath.ps1 doesn't work correctly. No matter, what I've been testing against SQL-Server 2014 (German Language) works for me. When I comment out the lines 679 - 690

<#
		if ($NetworkShare.Length -gt 0)
		{
			if ($(Test-SqlPath -SqlServer $sourceserver -Path $NetworkShare) -eq $false)
			{
				throw "$Source cannot access $NetworkShare"
			}
			
			if ($(Test-SqlPath -SqlServer $destserver -Path $NetworkShare) -eq $false)
			{
				throw "$Destination cannot access $NetworkShare"
			}
		}

#>
the copy-sqldatabase works perfect. Otherwise I become always just the following error:

DB1 cannot access \\DB1.local\tmp
In C:\Users\Administrator\Documents\WindowsPowerShell\Modules\dbatools\functions\Copy-SqlDatabase.ps1:684 Zeichen:5
+                 throw "$Source cannot access $NetworkShare"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (DB1 cannot....local\tmp:String) [], RuntimeException
    + FullyQualifiedErrorId : DB1 cannot access \\db1.local\tmp

**Comment by matzerj** [comment]
dbatools executes this stored procedure within test-sqlpath.ps1: `EXEC master.dbo.xp_fileexist '$path'`
I ran that xp in SQL Mgmt Studio which returned values in German but dbatools is expecting it in English.

I've modified the file like this:
	`if ($fileexist.tables.rows['Die Datei ist vorhanden.'] -eq $true -or $fileexist.tables.rows['Die Datei ist ein Verzeichnis.'] -eq $true -or $fileexist.tables.rows['File Exists'] -eq $true -or $fileexist.tables.rows['File is a Directory'] -eq $true)`

So test-sqlpath will return $true on a German system. This way copy-sqldatabases worked flawlessly.

**Comment by ConstantineK** [comment]
Thank you @matzerj for the drive by fix :) 

However when I take a step back, its clear we cant encode every language into the solution, and so I am going to test using the position of the column and see how that works.

This may mean some slight refactoring/internationalization work needs to be done in our codebase 🎱

**Comment by ConstantineK** [comment]
This has been fixed, let me know if there are any additional issues @matzerj!
