### ISSUE TITLE
Import-CsvToSql - does not work for schemas other than 'dbo'

### ISSUE THREAD

**Issue by ntr** [sqlcollaborative/dbatools#312]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

If schema is specified in table name parameter - importer tries to create another table in dbo schema. If schema is not specified - exception is throw. In both cases there is no way to populate desired table

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. create table `TestSchema.TestDB` in non `TestSchema` schema
2. call ``Import-CsvToSql -Csv test.csv -SqlServer . -Database TestDB -Table 'TestSchema.TestDB' -FirstRowColumns``
3. TestSchema.TestDB is not populated

another approach:
1. create table `TestSchema.TestDB` in non `TestSchema` schema
2. call ``Import-CsvToSql -Csv test.csv -SqlServer . -Database TestDB -Table 'TestDB' -FirstRowColumns``
3. Getting exception Import-CsvToSql : Exception setting "Item": "Exception calling "set_Item" with "2" argument(s): "Cannot 
find column 0.""

**What is the expected behavior?**
Either `TestSchema.TestDB` is populated or it should be another parameter where you can specify desired db schema. 

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
windows, 0.8.61

**Comment by ntr** [comment]
One of the option could be fix location https://github.com/sqlcollaborative/dbatools/blob/master/functions/CsvSqlimport.ps1#L748

instead of 
`select count(*) from master.dbo.sysdatabases where name = '$database'` 

consider using 
`SELECT count(*)
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA + '.' + TABLE_NAME = '$database'`

**Comment by Stuart-Moore** [comment]
Can see a couple of ways to fix this, but as a n00b contributer, not sure which one fits in better with the project's aims:

1) Assume a table name with a . in it is schema defined and parse suitably. Would also potentially then need to check that the schema existed, and also check with the user that was the action they wanted

2) Add a schema parameter to explicity state if it wants to be somewhere other than dbo. Could tie in nicely with dynamic parameters, and as it's explict if the schema doesn't exist could create it as it's definitely what the user wants.

**Comment by SirCaptainMitch** [comment]
Adding a new Param seems like the best option to me on this one. Im not sure if anyone else wants to weigh in, but splitting on a '.' in the table name seems like it's asking for some trouble. Albeit, not that much trouble. But I think explicitly declaring a schema in a param and defaulting to dbo is the better option.

**Comment by ctrlbold** [comment]
Fixed in #342 👍
