### ISSUE TITLE
Get-DbaLastGoodCheckDb rounds down DaysSinceLastGoodCheckDb

### ISSUE THREAD

**Issue by petervandivier** [sqlcollaborative/dbatools#3135]
## Bug Report

`Get-DbaLastGoodCheckDb` `DaysSinceLastGoodCheckDb` returns floor/integer value. Displaying a Calendar Datetime that is 7 days, 23 hours in the past next to a label of `DaysSinceLastGoodCheckDb` equals 7 can be initially misleading. 

### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?

## Steps to Reproduce

```powershell
$ServerInstance="localhost"
Get-DbaLastGoodCheckDb -SqlServer $ServerInstance | Where-Object {
    ($_.Status -eq "CheckDB should be performed") -and `
    ($_.DaysSinceLastGoodCheckDb -le 7)
} | ft
```

...or more generally...

```powershell
New-TimeSpan "2018-01-22 00:00" "2018-01-29 00:00" | Select Days,TotalDays
New-TimeSpan "2018-01-22 00:00" "2018-01-29 23:59" | Select Days,TotalDays
New-TimeSpan "2018-01-22 00:00" "2018-01-30 00:00" | Select Days,TotalDays
```

## Feature Request

The general query "_Has there been a good CheckDB in the last 7 days._" Returns true from days 0-7 up through day 8. 

### Problem to solve

Instead of using `(New-TimeSpan).Days` at [line 137](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Get-DbaLastGoodCheckDb.ps1#L137), perhaps use `(New-TimeSpan).TotalDays` or call out in documentation that it is a zero-indexed integer. 

To be fair, a `TotalDaysSinceLastGoodCheckDb` of 7.9 becoming a `DaysSinceLastGoodCheckDb` of 7 still results in the `Status` of <kbd>CheckDB should be performed</kbd>. However: when querying "_Show me all DBs without a good CheckDB in the last 7 days._", this behavior requires that the user know to compare `-ge 7` instead of `-gt 7`.

**Comment by potatoqualitee** [comment]
Wow! Thanks for including the fix in there. I just submitted a PR. Please let me know if it helps:
https://github.com/sqlcollaborative/dbatools/pull/3316
