### ISSUE TITLE
Comment based Help for Stop-DbaPfDataCollectorSet refers to Start instead of Stop

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#3142]
## Bug Report
The Comment Based Help for Stop-DbaPfDataCollectorSet displays refers to Starting instead of Stopping
### General Troubleshooting steps

- [Y ] Verified running the latest release of dbatools?
- [ Y] Verified errors are not related to permissions?
- [Y ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

## Steps to Reproduce

Get-Help Stop-DbaPfDataCollectorSet  has multiple references to Start instead of Stop

There are issues with Synopsis, Description and Examples

**Comment by alevyinroc** [comment]
Already planning on a review/update of this CBH per request from @potatoqualitee last week, so I'll make sure this is covered by that work

**Comment by alevyinroc** [comment]
Resolved with the above PR

**Comment by alevyinroc** [comment]
Just noticed that I missed something
