### ISSUE TITLE
Connect-DbaInstance does not set StatementTimeout when value of 0 is passed

### ISSUE THREAD

**Issue by tonyfountain** [sqlcollaborative/dbatools#3156]
## Bug Report
When calling Connect-DbaInstance and passing a value of 0 to the StatementTimeout parameter, the function does not actually set $server.ConnectionContext.StatementTimeout.

### General Troubleshooting steps
[Microsoft.SqlServer.Management.Smo.Server]$server = Connect-DbaInstance -SqlInstance $TargetSqlServer -StatementTimeout 0;
Write-Output ($server.ConnectionContext.StatementTimeout);

- [Y] Verified running the latest release of dbatools?
- [Y] Verified errors are not related to permissions?
- [Y] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Microsoft Windows Server 2016 Standard
 - PowerShell Version: 5.1.14393.1944
 - SQL Server (Edition|Version): Standard / 2012

## Steps to Reproduce
Please see General Troubleshooting steps.

### Problem to solve
Allow StatementTimeout to be set to 0 (or infinite)

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/commit/9a5f55bdbe3cdfd23a3fc403bfaba69b8bc88ccd
