### ISSUE TITLE
Orphan users (windows users) 

### ISSUE THREAD

**Issue by markinmon** [sqlcollaborative/dbatools#3157]
Running DBAtools orphan users shows 0 users and things like EXEC sp_change_users_login 'Report' returns 0 users, all should be good right ?

This query below returns the users and the accounts it returns do not have a login in the master database. I can add the account and the user drops off the query below. 
```
USE [master]
GO
CREATE LOGIN [windows username here] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO



 SELECT  *
 FROM    sys.database_principals
 WHERE   sid NOT IN ( SELECT sid
                          FROM   sys.server_principals ) -- No login with a matching SID
         AND (type = 'U' --WINDOWS_USER
                  )
         AND principal_id > 4 -- filter system (well-known) principals


```

dbatools version info 
```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      9      174    -1     


```

**Comment by niphlod** [comment]
watch out because "orphan" windows users may be left in by design when you work with windows groups.

**Comment by ClaudioESSilva** [comment]
I understand what you mean @markinmon .
However, this command born to do the job of `sp_change_users_login` and that is why do not take into account the windows logins.

If we agree that it make sense having a new switch to verify also the windows accounts, we can implement it. But it will be something to do after v1.0

@niphlod @wsmelton @sqllensman @potatoqualitee 
please share your toughts too

**Comment by potatoqualitee** [comment]
i have no opinion either way and will defer to others 👍

**Comment by wsmelton** [comment]
I would not agree with adding this because contained databases can give you different results as well. If someone has stronger belief that it should be just open a new issue.
