### ISSUE TITLE
Get-DbaLastBackup is really messed up

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3158]
Can someone please assist asap? This happened on two diff env

![image](https://user-images.githubusercontent.com/8278033/35417475-e1795d6a-022d-11e8-9503-da4846b127c6.png)

![image](https://user-images.githubusercontent.com/8278033/35417510-0a1fe48c-022e-11e8-8134-18633d502b7f.png)

**Comment by potatoqualitee** [comment]
thanks so much - sucks that the tests pass 👎

**Comment by potatoqualitee** [comment]
not locally but on appveyor

**Comment by potatoqualitee** [comment]
i reverted to the old version for now - which likely has some bugs but works

**Comment by Stuart-Moore** [comment]
That looks like issues with the dbatools type library. Does it work with
-raw?

**Comment by Stuart-Moore** [comment]
Can't replicate here with latest Dev:
![image](https://user-images.githubusercontent.com/5613670/35429358-a08e3c42-026b-11e8-800a-a9d0250e9064.png)

Can't post the OGV shot without redacting huge amouts, but all looks good the servers I'm querying.

Is this on garbo?

**Comment by Stuart-Moore** [comment]
Works for me on Garbo as well with a fresh pull of development:
![image](https://user-images.githubusercontent.com/5613670/35429818-958eee5c-026d-11e8-8159-736815833c83.png)

**Comment by Stuart-Moore** [comment]
Got it now.

It works fine with a single db, but returns the right results for a single.
Can't get the sea of blood though

**Comment by Stuart-Moore** [comment]
Found the issue, just debugging and testing a fix.

**Comment by niphlod** [comment]
closed via #3162
