### ISSUE TITLE
Remote Powershell fails when using SSRS with Kerberos authentication

### ISSUE THREAD

**Issue by alonsoh** [sqlcollaborative/dbatools#316]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behavior?
WinRM commands fail with this message:
Connecting to remote server devsql failed with the following error message : WinRM cannot process the request. The following error with errorcode 0x80090322 occurred while using Kerberos authentication: An unknown security error occurred. 
This is because WinRM is trying to use the HTTP SPN setup for SSRS.
I've managed to "fix" it by doing the following on each Invoke-Command:

```powershell
$SessionOption = New-PSSessionOption -IncludePortInSPN
Invoke-Command -SessionOption $SessionOption -ComputerName $sourcenetbios...

```

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
- Have SSRS installed using Kerberos Authentication.
- Run Copy-SqlCredential
- It will fail on any Invoke-Command or this command: winrm id -r:$sourcenetbios 2>$null | Out-Null

### What is the expected behavior?
To be able to run a command in the remote host.

### Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?

Windows.
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  117
```

**Comment by ctrlbold** [comment]
Thanks @alonsoh, I actually just fixed this in a recent PR. Should be released by this weekend. If you'd like it now, it is in the development branch.

**Comment by alonsoh** [comment]
Hi @ctrlbold, that's great! Did you had to include the SessionOption? Thanks.

**Comment by ctrlbold** [comment]
oh, hey. no i had just skipped it with some warnings. i always hated that piece of test code (and test-winrm doesnt work). Thanks for pointing me back to $SessionOption = New-PSSessionOption -IncludePortInSPN
Invoke-Command -SessionOption $SessionOption -ComputerName $sourcenetbios... -- I'll test it that way and get it in by this release either way.

**Comment by alonsoh** [comment]
No problem, let me know if I can help in any way. Thanks.

**Comment by niphlod** [comment]
@ctrlbold : can you wrap this up ? IMHO with all the new tooling from @FriedrichWeinmann this needs closure.

**Comment by potatoqualitee** [comment]
Thanks @niphlod - sorry I missed all of your awesome followups.

@alonsoh - can you please test with the latest release? Should be 0.9.15 or above.

**Comment by wsmelton** [comment]
Closing this issue as resolved.

If further issues arise please submit new issue with details.
