### ISSUE TITLE
Error importing the module in Powershell Core 6.0.1 on Linux

### ISSUE THREAD

**Issue by rrg92** [sqlcollaborative/dbatools#3166]
### General Troubleshooting steps
- [x] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): CentOS 7
 - PowerShell Version: 6.0.1 (Core)
 - SQL Server (Edition|Version): Not applicable

## Steps to Reproduce

Install latest dbatools
Try to import the module (import-module dbatools)
You will see a lot of errors generated by import process. Check log [PowershellCoreDbaToolsInput.txt](https://github.com/sqlcollaborative/dbatools/files/1668691/PowershellCoreDbaToolsInput.txt)

![image](https://user-images.githubusercontent.com/16887793/35454079-b8c60fea-02b3-11e8-8688-332321497be3.png)

### Additional information

The problem is related with slash in paths passed to methods from .NET objects.
Powershell core just handle slashs (\ and /) passed to cmdlets. But, using a method from a object, not a cmdlet, requires the correct path according with the OS rules.

My suggestion is use the [IO.Path]::DirectorySeparatorChar to build the paths to any file or directory.

**Comment by wsmelton** [comment]
At this time we are not able to support PowerShell 6.0+. At a future point, we will begin working to support it but there is no ETA right now.

There are other issues besides the file path issue you noted that will prevent the module from importing...many.
