### ISSUE TITLE
Set-dbatcpport static port incorrect

### ISSUE THREAD

**Issue by goforebroke** [sqlcollaborative/dbatools#3170]
### General Troubleshooting steps

- [ ] Verified running the latest release of dbatools?  0.9.135
- [X ] Verified errors are not related to permissions?
- [ X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): 
Windows 2016/Windows 10

 - PowerShell Version: 
v5
 - SQL Server (Edition|Version): 
2012 - 2017
## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

Set-DbaTcpPort -SqlInstance Server\InstanceName -Port ####

Setting a static port for a named instance sets both the "TCP Port" and "TCP Dynamic Ports" in SQL configuration manager\SQL Network Configuration. 

We set the tcp port for a named instance because we don't allow SQL Server to dynamically register SPN's in AD.

## Feature Request

 "TCP Dynamic Ports" should be set blank when a tcp port is provided for SQL Server.

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port

**Comment by awickham10** [comment]
I confirmed this. When using Configuration Manager and setting the TCP Port to 14333 and TCP Dynamic Ports to 0, both were being listened on at startup.

Tough call on enhancement versus bug. If you set a static port I'm pretty sure you don't want dynamic ports enabled... but maybe you do.

**Comment by goforebroke** [comment]
I would say this is a bug in the code considering the MSFT white doc says to make "TCP Dynamic Ports" blank if it you plan on specifying a port.

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port

"3. If the TCP Dynamic Ports dialog box contains 0, indicating the Database Engine is listening on dynamic ports, delete the 0."

"4. In the IPn Properties area box, in the TCP Port box, type the port number you want this IP address to listen on, and then click OK."

**Comment by potatoqualitee** [comment]
Unless this was changed since April 7, I'm not seeing where we modify `TCP Dynamic Ports`

```
$tcpport = $IpAddress.IpAddressProperties | Where-Object {
                $_.Name -eq 'TcpPort'
            }

            $oldport = $tcpport.Value
            try {
                $tcpport.value = $port
                $tcp.Alter()
```

In particular, that ` $_.Name -eq 'TcpPort'` filters out  `Name -eq TcpDynamicPorts`

When I ran the command

`Set-DbaTcpPort -SqlInstance sql2017 -Port 14334`

It still returned empty

![image](https://user-images.githubusercontent.com/8278033/48567238-df445480-e8fc-11e8-94b8-1dfc662aeca4.png)

Further warnings or tests would be a feature

**Comment by andreasjordan** [comment]
I'll have a look...

**Comment by andreasjordan** [comment]
To get an idea of how we can solve this, I've created a demo: #7358
