### ISSUE TITLE
Extend Set-DbaLogin to change PasswordPolicy switch

### ISSUE THREAD

**Issue by chrgraefe** [sqlcollaborative/dbatools#3179]
## Feature Request
I cant configure the passwort policy switch with this command

### Problem to solve
I want to change it if PoSh

### Additional information

`
ALTER LOGIN [sa] WITH CHECK_POLICY=ON;
`

**Comment by awickham10** [comment]
Looks like this one has been implemented and needs closed.

```powershell
Set-DbaLogin -SqlInstance 'MyServerName' -Login 'sa' -PasswordPolicyEnforced'
```
