### ISSUE TITLE
Information for IgnoreLogBackups parameter in Get-DBABackupInformation does not make sense

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#3180]
### General Troubleshooting steps

- [ x] Verified running the latest release of dbatools? 0.9.188

https://github.com/sqlcollaborative/dbatools/blob/master/functions/Get-DbaBackupInformation.ps1#L60

Sat with a client and can't make sense of @Stuart-Moore Help statement

 This switch only works with MaintenanceSoltion, as we can then now that all file in LOG are to be ignored.

**Comment by Zhunya** [comment]
Fixed in #3032
