### ISSUE TITLE
DBATools fails on PowerShell 6.0

### ISSUE THREAD

**Issue by dalehhirt** [sqlcollaborative/dbatools#3189]
### General Troubleshooting steps

- [x ] Verified running the latest release of dbatools?
- [ x] Verified errors are not related to permissions?
- [ x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10 16299.192
 - PowerShell Version: 6.0

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x ] Attach output from PowerShell console (if possible/allowed)
PS C:\Users\dalehirt> import-module dbatools
Exception calling "InvokeScript" with "4" argument(s): "Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified."
At C:\Users\dalehirt\Documents\PowerShell\Modules\dbatools\0.9.188\dbatools.psm1:27 char:12
+     else { $ExecutionContext.InvokeCommand.InvokeScript($false, ([scr ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : CmdletInvocationException

Exception calling "InvokeScript" with "4" argument(s): "Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified."
At C:\Users\dalehirt\Documents\PowerShell\Modules\dbatools\0.9.188\dbatools.psm1:27 char:12
+     else { $ExecutionContext.InvokeCommand.InvokeScript($false, ([scr ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : CmdletInvocationException

Exception calling "InvokeScript" with "4" argument(s): "Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified."
At C:\Users\dalehirt\Documents\PowerShell\Modules\dbatools\0.9.188\dbatools.psm1:27 char:12
+     else { $ExecutionContext.InvokeCommand.InvokeScript($false, ([scr ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : CmdletInvocationException
### Problem to solve
Use dbatools in PowerShell 6.0

**Comment by wsmelton** [comment]
@dalehhirt Thank you for the detailed submission. However, right now it would it is a large undertaking to get the module to run under PS 6+ and not something we can invest time in at the moment.

It is on the roadmap, but right now the road is pretty long.
