### ISSUE TITLE
Start-DbaMigration using Ola hallengren backup structure

### ISSUE THREAD

**Issue by danglade** [sqlcollaborative/dbatools#3191]
## Bug Report
Hello, trying to use Start-DbaMigration using a network drive containing Ola hallengren  backup structure, but apparently is not possible using dbatools?
### General Troubleshooting steps

- [x ] Verified running the latest release of dbatools?
- [ x] Verified errors are not related to permissions?
- [ x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

**Comment by danglade** [comment]
Getting the following output VERBOSE: [Get-DbaDefaultPath][16:47:43] Attempting to connect to PVSQLDBS101
WARNING: [Restore-DbaDatabase][16:47:43] No backups passed through.
 This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other
issue

**Comment by potatoqualitee** [comment]
hey dan,
Start-DbaMigration is intended to be a live instance to instance migration. What you can do is use `Restore-DbaDatabase` and then `Start-DbaMigration -NoDatabase`

**Comment by niphlod** [comment]
@danglade : closing this, feel free to reopen if you got any doubts (or hang out on our Slack channel ^_^)
