### ISSUE TITLE
Invoke-DbaWhoIsActive fails when used with Verbose switch

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#3192]
### General Troubleshooting steps

- [ Y] Verified running the latest release of dbatools?
- [ Y] Verified errors are not related to permissions?
- [ Y] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

## Steps to Reproduce

When the command Invoke-DbaWhoIsActive is called using the Verbose switch 
eg Invoke-DbaWhoisActive -SqlInstance LensmanSB -ShowSleepingSpids 2 -Verbose

The command fails with error: Invalid query.
This is a result of the Verbose switch being evaluated as a Passed Parameter.

While there is a check that each parameter matches values in the $paramdictionary the null values are not filtered and a Null Parameter with Value of True is passed to the SQL Command

**Comment by awickham10** [comment]
Looks like you already fixed this in PR #3203. Marking this closed.
