### ISSUE TITLE
Get-DbaBackupHistory - Issue with version where Compression columns don't exist

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#3200]
SQL Server versions that do not include the Compression columns are not accounted for in the command.

Errors occur at line 524 and 525 for the 'CompressedBackupSize' not existing and then divide by zero error on calculating the `CompressionRatio`.

**Comment by potatoqualitee** [comment]
@wsmelton does this also cover that sea of red issue with sql 2005?

**Comment by niphlod** [comment]
due to https://github.com/sqlcollaborative/dbatools/commit/ad8dd13156b83fd2c87a89917fb953bd64b690cb#diff-af8edf8664b7195e4a75aefffd16de63 , I think following @wsmelton's request of having always the ratio in. let's see a quick fix

**Comment by niphlod** [comment]
@wsmelton , @potatoqualitee : would you take https://github.com/sqlcollaborative/dbatools/pull/3208 for a spin and see if it solves issues on related functions as well ?

**Comment by niphlod** [comment]
fixed via https://github.com/sqlcollaborative/dbatools/commit/a9dd6767b3586ab0f93e8b714e3f0c4aa2258fa2#diff-af8edf8664b7195e4a75aefffd16de63
