### ISSUE TITLE
Get-DbaLastBackup returns errors with striped backup sets

### ISSUE THREAD

**Issue by EmDBA** [sqlcollaborative/dbatools#3207]
When I try Get-DbaLastBackup command, it returns errors if the last backup have multiple files.

You can simply reproduce the issue like this : 

Backup-DbaDatabase -SqlInstance server\instance -Database test -FileCount 4 -BackupDirectory \\myshare
Get-DbaLastBackup -SqlInstance server\instance

Errors : 
[$error[0].log](https://github.com/sqlcollaborative/dbatools/files/1703723/error.0.log)
[pserror.log](https://github.com/sqlcollaborative/dbatools/files/1703724/pserror.log)

**Comment by potatoqualitee** [comment]
thanks so much Em!

**Comment by potatoqualitee** [comment]
We'll hopefully get that resolved soon

**Comment by niphlod** [comment]
@potatoqualitee, @EmDBA  : take #3209 for a spin

**Comment by potatoqualitee** [comment]
lookin good, adding test now 👍

**Comment by niphlod** [comment]
fixed via https://github.com/sqlcollaborative/dbatools/commit/a9dd6767b3586ab0f93e8b714e3f0c4aa2258fa2 and https://github.com/sqlcollaborative/dbatools/commit/269723d77da0df2a1b5da707c88afa84c8ae34d9
