### ISSUE TITLE
xp_fixeddrives does not return the same output in french vs English SQL server installation

### ISSUE THREAD

**Issue by pollusb** [sqlcollaborative/dbatools#3233]
When xp_fixeddrives is used, we need to take the second column instead of using the column names. Column name 'MB free' is 'Mo disponible' in French.

I found xp_fixeddrives to be used in 2 files in the module. I want to fix them to refer to the second column instead of using 'MB free'

### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): 
 - PowerShell Version: 
 - SQL Server (Edition|Version): 

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
Select-Object : Property "MB Free" cannot be found.

**Comment by niphlod** [comment]
fixed via https://github.com/pollusb/dbatools/commit/e6c11f01ee56099f1973b4d5c222852b5bbae161
