### ISSUE TITLE
Get-DbaServerRole Documentation

### ISSUE THREAD

**Issue by sqlhacker** [sqlcollaborative/dbatools#3235]
### General Troubleshooting steps

- [ X] Verified running the latest release of dbatools?
- [ X] Verified errors are not related to permissions?
- [ X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows10|10.0.16299
 - PowerShell Version: 5.1.16299.98
 - SQL Server (Edition|Version): Developer Edition | 14.0.3015

## Steps to Reproduce
 
Using Get-DbaServerRole command and was using the dbatools website and was trying to use -Role to specify sysadmin in the command. It returns an error. I brought the issue up on the Slack channel and "wsmelton" showed me that the argument is -ServerRole, not -Role. Using the correct argument returns the desired output. The website just needs to be updated to use "-ServerRole" instead of "-Role".

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
Update website documentation

**Comment by niphlod** [comment]
fixed already
