### ISSUE TITLE
Write-DBADataTable regression: no longer defaults the schema to dbo

### ISSUE THREAD

**Issue by frank687** [sqlcollaborative/dbatools#3238]
## Bug Report
Write-DbaDataTable no longer defaults the schema to dbo when not -Schema parameter is specified.

![write-dbadatatable issue](https://user-images.githubusercontent.com/25494820/36222382-b9bec234-1186-11e8-8903-272659f5a933.png)

### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 8.1
 - PowerShell Version: 5.0.10586.117
 - SQL Server (Edition|Version): SQL 2014

**Comment by awickham10** [comment]
@FriedrichWeinmann since a default is specified for $Schema do we need to call Test-Bound before we set $schemaName = $Schema?

**Comment by FriedrichWeinmann** [comment]
No, we don't, that was an error of mine and just setting it without that if-clause would fix the issue. Thanks for catching that!
Want to do the honors? Otherwise I can get to that tomorrow (not at my desktop machine right now)

**Comment by awickham10** [comment]
I can take care of it. Just waiting on a PR to be merged in. Still learning how to correctly use git.
