### ISSUE TITLE
When Restoring With Repalce from a Different Server InMemory Folder will not Overwrite

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbatools#3246]
## Bug Report

Restore a database from a different server that has an InMemory filegroup. In our particular situation we are standing up a test environment that has the same databases and it cannot overwrite the existing InMemory folders.
Restore-DbaDatabase -SqlServer "$($NewServer)" -Path $DBfolder -WithReplace -ReuseSourceFolderStructure -MaintenanceSolutionBackup -AllowContinue 

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 2012 R2
 - PowerShell Version: PowerShell 5
 - SQL Server (Edition|Version): SQL Server 2017 CU3

## Steps to Reproduce
Restore database with same name and paths from a different server to a new server where the database already exists on the new server and has an InMemory filegroup.
 - [X] Attach output from PowerShell console (if possible/allowed)

WARNING: [Test-DbaBackupInformation][18:13:20] File 
E:\Folder\DBName_InMemoryFG_01 already exists on , not owned by any database 
in ServerName, will not overwrite.

### Problem to solve
Needs the ability to overwrite the InMemory folder.  The restore deletes the other files for the database and leaves behind the InMemory folder and I'm forced to manually delete the InMemory folder rerun the restore cmdlet.

**Comment by Stuart-Moore** [comment]
Not having an in memory instance to test on, could you please provide the output from Read-DbaBackupHeader for the full backup please.

**Comment by tboggiano** [comment]
**The output of Read-DbaBackupHeader for the full backup:**

BackupName             :
BackupDescription      : FULL backups of USER_DATABASESFeb  5 2018
                         10:09:32:677AM
BackupType             : 1
ExpirationDate         :
Compressed             : 1
Position               : 1
DeviceType             : 2
UserName               : UserName
ServerName             : Server
DatabaseName           : Database
DatabaseVersion        : 869
DatabaseCreationDate   : 7/22/2016 3:44:39 PM
BackupSize             : 3718156288
FirstLSN               : 12717000022376400003
LastLSN                : 12740000005213400001
CheckpointLSN          : 12740000005206500104
DatabaseBackupLSN      : 12646000022287600078
BackupStartDate        : 2/5/2018 10:09:37 AM
BackupFinishDate       : 2/5/2018 10:12:09 AM
SortOrder              : 52
CodePage               : 0
UnicodeLocaleId        : 1033
UnicodeComparisonStyle : 196609
CompatibilityLevel     : 140
SoftwareVendorId       : 4608
SoftwareVersionMajor   : 14
SoftwareVersionMinor   : 0
SoftwareVersionBuild   : 3015
MachineName            : Server
Flags                  : 528
BindingID              : 0d5e8f5f-9a6f-4099-92c9-4bd4bd002567
RecoveryForkID         : 372ae4cd-f4d0-4e2e-a46b-915c0cb85ddd
Collation              : SQL_Latin1_General_CP1_CI_AS
FamilyGUID             : b671fcba-7afe-4621-8c17-020898727e3d
HasBulkLoggedData      : False
IsSnapshot             : False
IsReadOnly             : False
IsSingleUser           : False
HasBackupChecksums     : True
IsDamaged              : False
BeginsLogChain         : False
HasIncompleteMetaData  : False
IsForceOffline         : False
IsCopyOnly             : False
FirstRecoveryForkID    : 372ae4cd-f4d0-4e2e-a46b-915c0cb85ddd
ForkPointLSN           :
RecoveryModel          : FULL
DifferentialBaseLSN    :
DifferentialBaseGUID   :
BackupTypeDescription  : Database
BackupSetGUID          : 28eff13d-02e1-4773-b35d-0b8ab0499aea
CompressedBackupSize   : 736385024
Containment            : 0
KeyAlgorithm           : aes_256
EncryptorThumbprint    : {...}
EncryptorType          : CERTIFICATE
FileList               : {Database_Data, Database_Data1,
                         Database_Indexes1, Database_Text1...}
BackupSizeMB           : 3546
BackupSizeGB           : 3.462890625
CompressedBackupSizeMB : 702
CompressedBackupSizeGB : 0.685546875
SqlVersion             : 869
BackupPath             : c:\backup.bak

**The output of FileList Parameter:**

LogicalName          : Database_Data
PhysicalName         : C:\Database.mdf
Type                 : D
FileGroupName        : PRIMARY
Size                 : 1737490432
MaxSize              : 35184372080640
FileId               : 1
CreateLSN            : 0
DropLSN              : 0
UniqueId             : 00000000-0000-0000-0000-000000000000
ReadOnlyLSN          : 0
ReadWriteLSN         : 0
BackupSizeInBytes    : 1230766080
SourceBlockSize      : 512
FileGroupId          : 1
LogGroupGUID         :
DifferentialBaseLSN  : 12646000022287600078
DifferentialBaseGUID : 013fa6ae-e7e2-45a8-a1d5-9d38656b280a
IsReadOnly           : False
IsPresent            : True
TDEThumbprint        : {58, 40, 49, 95...}
SnapshotUrl          :

LogicalName          : Database_Data1
PhysicalName         : C:\Database_Data1.ndf
Type                 : D
FileGroupName        : Tables
Size                 : 22740992
MaxSize              : 35184372080640
FileId               : 3
CreateLSN            : 12000000003100001
DropLSN              : 0
UniqueId             : 00000000-0000-0000-0000-000000000000
ReadOnlyLSN          : 0
ReadWriteLSN         : 0
BackupSizeInBytes    : 12713984
SourceBlockSize      : 512
FileGroupId          : 2
LogGroupGUID         :
DifferentialBaseLSN  : 12646000022287600078
DifferentialBaseGUID : 013fa6ae-e7e2-45a8-a1d5-9d38656b280a
IsReadOnly           : False
IsPresent            : True
TDEThumbprint        : {58, 40, 49, 95...}
SnapshotUrl          :

LogicalName          : Database_Indexes1
PhysicalName         : C:\Database_Indexes1.ndf
Type                 : D
FileGroupName        : Indexes
Size                 : 10485760
MaxSize              : 35184372080640
FileId               : 4
CreateLSN            : 12000000004500001
DropLSN              : 0
UniqueId             : 00000000-0000-0000-0000-000000000000
ReadOnlyLSN          : 0
ReadWriteLSN         : 0
BackupSizeInBytes    : 589824
SourceBlockSize      : 512
FileGroupId          : 3
LogGroupGUID         :
DifferentialBaseLSN  : 12646000022287600078
DifferentialBaseGUID : 013fa6ae-e7e2-45a8-a1d5-9d38656b280a
IsReadOnly           : False
IsPresent            : True
TDEThumbprint        : {58, 40, 49, 95...}
SnapshotUrl          :

LogicalName          : Database_Text1
PhysicalName         : C:\Database_Text1.NDF
Type                 : D
FileGroupName        : Text
Size                 : 10485760
MaxSize              : 35184372080640
FileId               : 5
CreateLSN            : 12000000005700001
DropLSN              : 0
UniqueId             : 00000000-0000-0000-0000-000000000000
ReadOnlyLSN          : 0
ReadWriteLSN         : 0
BackupSizeInBytes    : 655360
SourceBlockSize      : 512
FileGroupId          : 4
LogGroupGUID         :
DifferentialBaseLSN  : 12646000022287600078
DifferentialBaseGUID : 013fa6ae-e7e2-45a8-a1d5-9d38656b280a
IsReadOnly           : False
IsPresent            : True
TDEThumbprint        : {58, 40, 49, 95...}
SnapshotUrl          :

LogicalName          : Database_Log
PhysicalName         : C:\Database_log.ldf
Type                 : L
FileGroupName        :
Size                 : 6452936704
MaxSize              : 35184372080640
FileId               : 2
CreateLSN            : 0
DropLSN              : 0
UniqueId             : 00000000-0000-0000-0000-000000000000
ReadOnlyLSN          : 0
ReadWriteLSN         : 0
BackupSizeInBytes    : 0
SourceBlockSize      : 512
FileGroupId          : 0
LogGroupGUID         :
DifferentialBaseLSN  : 0
DifferentialBaseGUID : 00000000-0000-0000-0000-000000000000
IsReadOnly           : False
IsPresent            : True
TDEThumbprint        :
SnapshotUrl          :

LogicalName          : Database_InMemoryFG_01
PhysicalName         : C:\InMemoryFG_01
Type                 : S
FileGroupName        : InMemoryFG
Size                 : 0
MaxSize              : 0
FileId               : 65537
CreateLSN            : 4263000022571400003
DropLSN              : 0
UniqueId             : e5067b6f-1671-4b5d-ae57-891ad3c62f20
ReadOnlyLSN          : 0
ReadWriteLSN         : 0
BackupSizeInBytes    : 2176122880
SourceBlockSize      : 512
FileGroupId          : 5
LogGroupGUID         :
DifferentialBaseLSN  : 12646000022287600078
DifferentialBaseGUID : 013fa6ae-e7e2-45a8-a1d5-9d38656b280a
IsReadOnly           : False
IsPresent            : True
TDEThumbprint        :
SnapshotUrl          :

**Comment by Stuart-Moore** [comment]
Morning, 
could you give this PR = https://github.com/sqlcollaborative/dbatools/pull/3270 - a test please. Wouldn't let me tag you in as reviewer 

Cheers
Stuart

**Comment by tboggiano** [comment]
Confirmed it works!  I was able to do a full restore of at a database with a InMemory filegroup from a different server to replace and existing database.

 

Thanks,

Tracy Boggiano

Co-Leader,  <https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Ftracyboggiano.com%2Ftripassadvdba%2F&data=02%7C01%7Cbobward%40microsoft.com%7C376a88d072634c4bb51a08d557865df3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C636511156979884371&sdata=Wru7gXkWGsN%2FC9Hicr3SvMRf8pIqfYDxbYwlzOS2rZo%3D&reserved=0> TriPass SIG Advanced DBA

Founder of  <http://wespeaklinux.com/> WeSpeakLinux.com

Database Superhero at ChannelAdvisor



Find me:
Blog <https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.databasesuperhero.com%2F&data=02%7C01%7Cbobward%40microsoft.com%7C376a88d072634c4bb51a08d557865df3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C636511156979884371&sdata=31JaTXw3c2bBfkBZbJRz4VDolk3ykTHCyWjZx%2BuMVjA%3D&reserved=0>   Twitter <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FTracyBoggiano&data=02%7C01%7Cbobward%40microsoft.com%7C376a88d072634c4bb51a08d557865df3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C636511156979884371&sdata=j7G51z0cTDTufprmPBdxNK4YGFzH%2BavbY9YZjpxGPCU%3D&reserved=0>   LinkedIn <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ftracyboggiano&data=02%7C01%7Cbobward%40microsoft.com%7C376a88d072634c4bb51a08d557865df3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C636511156979884371&sdata=f6qFYWChE8oONubZI6d1LJvRBbm7KpUmyvg0yuOa27U%3D&reserved=0>    

 

"It is never too late to be what you might have been." -- George Eliot

 <https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.pass.org%2Fsummit%2F2017%2FHome.aspx&data=02%7C01%7Cbobward%40microsoft.com%7C376a88d072634c4bb51a08d557865df3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C636511156979894380&sdata=EHOzzRcC9Ho8TJ4ZM0FMtofxBl4coR0GxtLmxMp3xjc%3D&reserved=0>  <https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.pass.org%2FCommunity%2FGetInvolved%2FVolunteers.aspx&data=02%7C01%7Cbobward%40microsoft.com%7C376a88d072634c4bb51a08d557865df3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C636511156979894380&sdata=9ylRqQdH9e1WOyCSHSJ02qm7iMYuSE3cO9K5BusQ%2FMo%3D&reserved=0>  <http://www.idera.com/lp/sql-superstars-2018>

**Comment by Stuart-Moore** [comment]
:+1: thank you

**Comment by Stuart-Moore** [comment]
Now in Dev branch
