### ISSUE TITLE
Additional parameter for Restore-DbaDatabase to map folders

### ISSUE THREAD

**Issue by chriswedgwood** [sqlcollaborative/dbatools#3273]
## Feature Request

I would like to have a parameter in Restore-DbaDatabase that allows me to specify foldermappings 
perhaps:

.PARAMETER FolderMapping
		A hashtable that can be used to map folder paths
		$FolderMapping = @{'c:\origin1'='c:\destination1';'c:\origin2'='c:\destination2';'c:\origin_log'='c:\destination_log';}

### Problem to solve
I have a scenario  where I need to restore databases that exist in multiple filegroups on multiple mount points. these databases have thousands of files so Filemappings is impractical

### Further information
I was thinking as an alternative approach to use Read-DbaBackupHeader to create a hash table to pass into  Restore-DbaDatabase as .PARAMETER FileMapping

**Comment by niphlod** [comment]
not quite sure it'd be a more powerful addition, and it'd not be that easier than passing a filemapping. 
In either case you need to builds mappings beforehand

**Comment by Stuart-Moore** [comment]
I agree with @niphlod 
Building the hash for filemapping can be just as quick:
```
$hash = @{}
Get-DbaDatabaseFile -SqlInstance Instance1 -Database db1 |  ForEach {$hash.add($_.LogicalName,$_;PhysicalName}
$hash | Export-CliXml -Path .\hash.xml
# Edit hash.xml in your editor of choice
$hash2 = Import-CliXml -Path .\hash.xml
```
Jobs a good 'un.

If you want to use the backups rather than the existing db then you can do that like this by replacing line 2 with this:
```
Read-DbaBackupHeader -SqlInstance instance1 -Path C:\backups\db1.bak | select -expandProperty Filelist | ForEach{$hash.add($_.LogicalName, $_.PhysicalName)}
```

If you keep the hash file then you can reuse it again and again.

**Comment by chriswedgwood** [comment]
Yes looking at your examples Stuart it is not necessary

happy to close :)
