### ISSUE TITLE
Export-SqlLogin CREATE USER bug when login name does not match user name

### ISSUE THREAD

**Issue by bmg002** [sqlcollaborative/dbatools#328]
**Do you want to request a *feature* or report a *bug*?** 
BUG

**What is the current behavior?** 
incorrect user is created for login of a database

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
step1 - create logins user1, user2 and user3
step2 - create user on database user2_2 for login user2
step3 - create user on database user3 for login user3
step4 - run export-sqllogin against that database to file

I ran step 4 against one of our test/dev SQL instances to get the results.  I removed some as there were 499 users on the database and even more logins.

The script (after attempting to anonymize it) looks like this:
use master
GO
IF NOT EXISTS (SELECT loginname from master.dbo.syslogins where name = ‘user1')
CREATE LOGIN [user1] WITH PASSWORD = <removed> HASHED, SID = <removed>, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF, DEFAULT_LANGUAGE = [us_english]
GO
use master
GO
Grant CONNECT SQL TO [user1]  AS [sa]
GO
use master
GO
IF NOT EXISTS (SELECT loginname from master.dbo.syslogins where name = ‘user2’)
CREATE LOGIN [user2] WITH PASSWORD = <removed> HASHED, SID = <removed>, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF, DEFAULT_LANGUAGE = [us_english]
GO
use master
GO
Grant CONNECT SQL TO [user2]  AS [sa]
GO
use [database1]
GO
CREATE USER [user2_2] FOR LOGIN [user2] WITH DEFAULT_SCHEMA=[dbo]
GO
use master
GO
IF NOT EXISTS (SELECT loginname from master.dbo.syslogins where name = 'user3')
CREATE LOGIN [user3] WITH PASSWORD = <removed>HASHED, SID = <removed>, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF, DEFAULT_LANGUAGE = [us_english]
GO
use master
GO
Grant CONNECT SQL TO [user3]  AS [sa]
GO
use [database1]
GO
CREATE USER [user2_2] FOR LOGIN [user2] WITH DEFAULT_SCHEMA=[dbo]
GO
use master
GO
IF NOT EXISTS (SELECT loginname from master.dbo.syslogins where name = user4)
CREATE LOGIN [user4] WITH PASSWORD = <removed> HASHED, SID = <removed>, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF, DEFAULT_LANGUAGE = [us_english]
GO
use master
GO
Grant CONNECT SQL TO [user4]  AS [sa]
GO
use [database1]
GO
CREATE USER [user2_2] FOR LOGIN [user2] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [role1] ADD MEMBER [user4]
GO
ALTER ROLE [role2] ADD MEMBER [user4]
GO
ALTER ROLE [role3] ADD MEMBER [user4]
GO
ALTER ROLE [role4] ADD MEMBER [user4]
GO
ALTER ROLE [role5] ADD MEMBER [user4]
GO
Grant CONNECT TO [user4]  AS [dbo]
GO

**What is the expected behavior?**
script will show create logins for user1, user2 and user3 and will show users user2_2 for login user2 and user user3 for login user3, etc

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
Powershell version is 5.0.10586.117 and the OS is Windows 7 Professional.  SQL version is SQL Server 2008 R2.
I have tested it on versions 0.8.61 and 0.8.65 of the dbatools scripts and both versions produced the same results.

I believe the issue occurs when the user and login do not match.  I tested this against a second SQL instance and as soon as the user and login names did not match, that one keeps gettign repeated.

A potentially related thing I noticed - on the second instance I tested it on, we have more databases but it seems to always use the first one.
for example - a login, login1, has a user account, user1, on database1.  user1 does not exist on database2.  login2 has a user account, login2, on database2.  The script only seems to try to create users for database1:
use master
GO
IF NOT EXISTS (SELECT loginname from master.dbo.syslogins where name = 'login1')
CREATE LOGIN [login1] WITH PASSWORD = 0x01008D07A994F76FE630E940F9EA9D3AFFC688C4A23066382D74 HASHED, SID = 0x1394C7C1C2323D47A3904A6D0E2838E7, DEFAULT_DATABASE = [database1], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF, DEFAULT_LANGUAGE = [us_english]
GO
use master
GO
Grant CONNECT SQL TO [login1]  AS [sa]
GO
use [database1]
GO
CREATE USER [user1] FOR LOGIN [login1] WITH DEFAULT_SCHEMA=[schema1]
GO
use master
GO
IF NOT EXISTS (SELECT loginname from master.dbo.syslogins where name = 'login2')
CREATE LOGIN [login2] WITH PASSWORD = 0x010078622F955953CE90C1F6CE8AFB56AFC1626CC96581F16421 HASHED, SID = 0xF6A4178744952C4F9E079F08C9CB718C, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF, DEFAULT_LANGUAGE = [us_english]
GO
use master
GO
Grant CONNECT SQL TO [login2]  AS [sa]
GO
use [database1]
GO
CREATE USER [user1] FOR LOGIN [login1] WITH DEFAULT_SCHEMA=[schema1]
GO

It never tries to connect to database2 to create the user login2 for login2.
I believe if the first issue (user does not equal login then script goes all goofy), the second issue should correct itself.

**Comment by ctrlbold** [comment]
Thanks so much for the detailed info! Your ticket has been assigned to our bombass bug killer.

**Comment by ConstantineK** [comment]
Hey @bmg002, this fix has been merged into development and is staged for the next release.
Thanks!
