### ISSUE TITLE
Copy-SqlDatabase local comp to local comp

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#329]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Copy-SqlDatabase does not support localhost to localhost, running from 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Copy-SqlDatabase -Source sql2016 -Destination sql2016\vnext -DetachAttach -Reattach -Databases test

**What is the expected behavior?**
that it works

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
Never tried it before, but me and Steve Jones are both having issues. I never test for running locally so that's the issue. Works remotely

Attempting to connect to Sql Servers..
Resolving NetBIOS names
Performing SMO version check
Checking to ensure the source isn't the same as the destination
Checking to ensure server is not SQL Server 7 or below
Checking to ensure detach/attach is not attempted on SQL Server 2000
Checking to ensure SQL Server 2000 migration isn't directly attempted to SQL Server 2012
Ensuring user databases exist (counting databases)
Ensuring destination server version is equal to or greater than source
Writing warning about filestream being enabled
WARNING: FILESTREAM enabled on SQL2016 but not SQL2016\VNEXT. Databases that use FILESTREAM will be skipped.
Checking access to remote directories
Building database list
Building file structure inventory for 1 databases

######### Database: test #########
Started: 11/22/2016 19:05:31
Copying  for test
Copying test.mdf for test
Successfully attached test to SQL2016\VNEXT
Successfully reattached test to SQL2016
Finished: 11/22/2016 19:05:34
Elapsed time: 00:00:03

Database migration finished
Migration started: 11/22/2016 19:05:31
Migration completed: 11/22/2016 19:05:34

**Comment by mshamann** [comment]
I assume it should only be able to copy from local to local/instance? 

So we wouldn't want to essentially make a duplicate of the Database on same server?

**Comment by ctrlbold** [comment]
Yeah, at this point, only instance to diff instance, not instance to same instance

**Comment by potatoqualitee** [comment]
This has been tested and fixed and even included in a pester test 👍
