### ISSUE TITLE
Backup-DbaSSASDatabase/Restore-DbaSSASDatabase

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#3290]
## Feature Request
Start with backup/restore SSAS dbs cmdlets. They're popping up here and there and should be pretty easy to implement.

**Comment by wsmelton** [comment]
I don't know the commands in SQL Server module handle back and restore for
AS pretty well already.

**Comment by Stuart-Moore** [comment]
Agree with Shawn, there's very little you can do the backup/restores so the
SMO cmdlets are pretty good. TBH the only thing we could really add is
filtering for the required backup file. SMO examples here:
backup -
https://stuart-moore.com/day-25-31-days-sql-server-backup-restore-using-powershell-backing-sql-server-analysis-services/
restore -
https://stuart-moore.com/day-26-31-days-sql-server-backup-restore-using-powershell-restoring-sql-server-analysis-services-databases/

**Comment by niphlod** [comment]
guess dbatools is better advertised than SQLPS then ^_^
