### ISSUE TITLE
[RFC] Proposal for a updated function flow on database related commands

### ISSUE THREAD

**Issue by FriedrichWeinmann** [sqlcollaborative/dbatools#3314]
# Introduction
The way dbatools currently handles commands is mostly instance-centric, since that is the original contact to the server. We have made enormous strides towards uniform experience in that regard.
However, from a usability perspective, many commands are actually more database centric.

The design goal for this RFC is to design a solution that leads to supporting this focus, without a breaking change in how the dbatools commands can be used today.

In order to address this in a comprehensive manner, we need to address:

 - Code flow: How the commands are used, the user facing front end
 - Input processing: How we understand and interpret input
 - Normalized function layout: How our functions will execute their logic internally

This proposal, tries to address usability to the end user, performance in code execution and maintainability for the average contributor.

# Situation
## a) The code flow
When you currently want to re-use a SMO _database_ connection for a chain of logically connected commands, you cannot do so in the pipeline, but need to store it in a variable and keep starting new pipelines:
```powershell
$dbs = get-dbadatabase -sqlinstance foo -database db1,db2
$dbs | set-dbadatabaseowner -...
$dbs | get-dbadatabasestate -...
```
And this assumes that the command even accepts database objects from pipeline - many (most?) only accept instances from pipeline.

## b) Input Processing
Even in instances, where database objects are accepted, a blanket object is accepted, all processing is done inside the function itself. This is untidy, often detrimental to the readability of the command and hard to provide a uniform way of handling this.
Pipeline input from both instances _and_ database objects on the other hand is hard to handle.

# Proposed solution
## a) Revised code flow
Commands dealing with database content receive two parameter sets / legal ways to use them:
```
Get-DbaDbSomething -SqlInstance <DbaInstance[]> [-Database <DbaDatabase[]>] [-ExcludeDatabase <DbaDatabase[]>
Get-DbaDbSomething -DatabaseObject <DbaDatabaseSmo[]>
```
This allows the same usage as currently through the first parameterset.
The second parameterset allows piping live SMO database objects in multiple ways (more on that in section b), to be also processed. Filtering by database name is not useful in this instance, since the individual objects already represent the action choice of the user (who would have filtered the database instances in the first call).
This allows executing code like this:
```powershell
Get-DbaDatabase -SqlInstance sql2017 -Database db1,db2 | Set-DbaDatabaseOwner -TargetLogin foo | Get-DbaDatabaseState
```

## b) Input Processing
Database input - whether from pipeline or explicitly - has always been done by setting the parameter type to `[object[]]`. This generally required input processing inside of the function. In many cases, this was skipped and simple string was assumed.

The new parameter classes `[DbaDatabase]` and `[DbaDatabaseSmo]` (https://github.com/sqlcollaborative/dbatools/pull/3302) replace this:

 - `[DbaDatabaseSmo]` will accept only live SMO objects - whether plain or as part of an input object's `Database` property - and is used for piped input.
 - `[DbaDatabase]` will accept live SMO objects, in the same way `[DbaDatabaseSmo]` does, but also accepts strings (as user convenience requires). This is used for non-piped input as part of the `SqlInstance` parameterset (the way things are currently done).

That way, all legal input will be presented in a uniform manner to the inside of the function.

## C) The new template for database processing
Example function that implements this solution:
```powershell
function Get-DbaDbSomething {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, ValueFromPipeline = $true, ParameterSetName = 'Instance')]
        [Alias("ServerInstance", "SqlServer")]
        [DbaInstance[]]$SqlInstance,
        [Parameter(ParameterSetName = 'Instance')]
        [Alias("Credential")]
        [PSCredential]$SqlCredential,
        [Parameter(ParameterSetName = 'Instance')]
        [Alias("Databases")]
        [DbaDatabase[]]$Database,
        [Parameter(ParameterSetName = 'Instance')]
        [DbaDatabase[]]$ExcludeDatabase,
        [Parameter(Mandatory = $true, ValueFromPipeline = $true, ParameterSetName = 'Database')]
        [DbaDatabaseSmo[]]$DatabaseObject,
        [Alias('Silent')]
        [switch]$EnableException
    )

    begin {
        $paramGetDbaDatabase = @{
            EnableException = $true
            WarningAction = "SilentlyContinue"
        }
        if ($SqlCredential) {$paramGetDbaDatabase["SqlCredential"] = $SqlCredential }
        if ($Database) {$paramGetDbaDatabase["Database"] = $Database }
        if ($ExcludeDatabase) {$paramGetDbaDatabase["ExcludeDatabase"] = $ExcludeDatabase }
    }
    process {
        $databases = @()
        $databases += $DatabaseObject.Database
        
        foreach ($instance in $SqlInstance) {
            try { $databases += Get-DbaDatabase -SqlInstance $instance @paramGetDbaDatabase }
            catch { Stop-Function -Message "Failure." -ErrorRecord $_ -Target $instance -Continue }
        }
        
        foreach ($database in $databases) {
            # Execute logic against database
        }
    }
}
```
# Additional thoughts
## Internal use of Get-DbaDatabase
It may be useful to decouple the use of our public `Get-DbaDatabase` function and instead to develop our own internal version, tailored to this use-case, as that would allow more flexibility in error reporting/handling.

**Comment by niphlod** [comment]
Extending on the wonderful analysis, everything started with #3164 . 

We have a lot of functions acting on databases, some accept piped objects from "sister" functions (see `*databasesnapshot*`), the vast majority of them accept input from get-dbadatabase (usually via a [Microsoft.SqlServer.Management.Smo.Database[]]$DatabaseCollection parameter, back in the days @potatoqualitee was spricing up pipelines everywhere 😍  ).
So far, the "contract" in output is just [pscustomobject]. 
`ComputerName , sqlinstance, instancename` are pretty much everywhere, while a mix of 
`dbname, database, name`, holding either a simple string or the full smo db object is present.

I tried towards something "that could be easily slipped in" , as in

_*If the input contains a sqlinstance property and a database one (but only with the full SMO db object), I will happily accept it*_

but [didn't came out right](https://github.com/sqlcollaborative/dbatools/pull/3288), due to PS input handling coupled with my inexpertise ^_^
 
The obvious benefit of the "contract" is that the "adoption" streamlines similar functions, the added benefit is being able to chain "db functions" (although the end goal is not "create the longer one-liner we can think of")

**Comment by wsmelton** [comment]
So are we going to work toward this or let it go?

**Comment by potatoqualitee** [comment]
I'm gonna say we are going to let it go 😬
