### ISSUE TITLE
Remove-DbaBackup with "PathTooLongException" error 

### ISSUE THREAD

**Issue by peturgretars** [sqlcollaborative/dbatools#332]
First I like to say that I am loving the Remove-DbaBackup command. 
The only issue I seem to be having is removing old backups from SharePoint servers. I am getting the following error on couple of the servers where I have SharePoint installed. 

The version of dbatools is 0.8.65. 

I ran the following command: 
Remove-DbaBackup -Path '\\[ServerName]\u$\Backup\' -BackupFileExtension bak -RetentionPeriod 3d -RemoveEmptyBackupFolder -CheckArchiveBit

And had the following error: 

> Get-ChildItem : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
> At C:\Users\[username]\Documents\WindowsPowerShell\Modules\dbatools\functions\Remove-DbaBackup.ps1:167 char:13 +    Get-ChildItem -Path $BaseLocation -Recurse | Where-Object ... +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : ReadError: (\\[ServerName]\u$...29ecfd1d54\FULL:String) [Get-ChildItem], PathTooLongException
>     + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand

 

Is this something that could be fixed?

**Comment by Stuart-Moore** [comment]
Unfortunately, that's a Windows limitation - [https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365247(v=vs.85).aspx]

Though it has apparently been lifted in Windows 10 Anniversary if you tweak a registry setting, not tried it personally though

One way round it may be to temporarily  mount the folder as a drive as the \[ServerName]\u$ bit counts, so by dropping it to b:\ you might save enough characters to drop the path length. 

Or I've also ended up sharing a folder further down the tree to remove some unneeded folder characters

**Comment by peturgretars** [comment]
Thank you for the reply. I think I will go with sharing a folder further down the tree for now. Not a fan of tweaking the registry in production. 

Thanks again!
