### ISSUE TITLE
New function to work with CMS - Import-DbaCMSServerFromFile

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#3320]
## Feature Request

Have function to import servers from text file or from some network discovery (AD query)

### Problem to solve

Populate new CMS with your servers list.

### Additional information

https://twitter.com/SQLSoldier/status/968654417535827973
https://blog.netnerds.net/smo-recipes/central-management-server/ (lol it was @potatoqualitee  blog post :facepalm:)

**Comment by potatoqualitee** [comment]
added earlier this summer! 🌞
