### ISSUE TITLE
dbatools not working in Pwsh 6.0

### ISSUE THREAD

**Issue by WindowsAdmin92** [sqlcollaborative/dbatools#3323]
Hi All,

Wanted to give the heads up that it looks like dbatools isn't working in 6.0. 

Did a Test-DBAConnection with several null errors and the following;
"Issue connection to SQL Server on SQLBOX\instance | Exception calling ".ctor" with "1" argument(s): "Could not load type 'Microsoft.SqlServer.Server.SqlContext' from assembly 'System.Data, Version=4.0.0.0"

Looks like the Microsoft.SqlServer.Server.SqlContext class isn't populating properly in 6.0. 

Works fine in 5.1. Just wanted to give the heads up.

**Comment by Stuart-Moore** [comment]
SMO isn't compiled for .Net core yet so dbatools won't with core/6.0 until MS release it.

Fingers crossed it'll be sooner rather than later, but until then we're stuck :(

**Comment by WindowsAdmin92** [comment]
Ah darn. Yeah, I'm seeing that a lot. The more I'm trying to write my code in 6.0, the more I'm seeing what's not compatible. 

Really cool module though! Looking forward to creating some functions and pulling some info on my anti-virus DB.
