### ISSUE TITLE
Create Pester Tests for Existing Functions 

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#3350]
There are already a substantial amount of cmdlets that do not currently have any associated pester tests. As stated in the post "Path to 1.0" https://dbatools.io/the-path-to-1-0/: 

> 'The most important things you can fix even without being a skilled developer: ScriptAnalyzer and Coverage... if it’s tested, tests describe the way the function behaves, so the more coverage a function has, the more stable it is.

 All functions need to have coverage tests to ensure a high level of stability for this module. This issue was created to put all of these tests in one location, without the need for a new issue on each test. 
This issue is intended to be worked on by multiple people. Please just be sure to assign yourself to the issue, comment on which test you are currently working on, and keep pull requests to 1-2 tests.

If your new to writing tests use some of these links to get started:
https://dbatools.io/improving-tests/
https://github.com/sqlcollaborative/dbatools/wiki#appveyor-setup
https://github.com/sqlcollaborative/dbatools-templates/blob/master/tests/Verb-Noun.Tests.ps1
https://mva.microsoft.com/en-US/training-courses/testing-powershell-with-pester-17650

This list was gathered using the following methodology. 
```
PS C:\PowerShell\Dev>  $functions = Get-ChildItem .\Dbatools\functions\
PS C:\PowerShell\Dev> $tests = Get-ChildItem .\Dbatools\tests\
PS C:\PowerShell\Dev> (diff $functions.basename $tests.basename.replace('.Tests','')).Where({$_.Si
deIndicator -eq '<='})
```

**NOTE:** This is not a comprehensive list of all the tests that need to be updated, only of new ones.
**NOTE:** Some of these may not be able to be tested fully depending on what they do
If a Test is missing please feel free to add it in alphabetical order.

List Updated **10/11/18**

- [ ] ConvertTo-DbaTimeline
- [x] Copy-DbaAgentAlert              
- [x] Copy-DbaAgentCategory           
- [x] Copy-DbaAgentJob                
- [x] Copy-DbaAgentOperator           
- [ ] Copy-DbaAgentProxyAccount    
- [ ] Copy-DbaAgentServer   
- [ ] Copy-DbaAgentSharedSchedule     
- [x] Copy-DbaCustomError             
- [ ] Copy-DbaDatabaseAssembly        
- [ ] Copy-DbaDatabaseMail     
- [ ] Copy-DbaDataCollector 
- [ ] Copy-DbaDbMail      
- [ ] Copy-DbaEndpoint                
- [ ] Copy-DbaExtendedEvent     
- [ ] Copy-DbaPolicyManagement      
- [ ] Copy-DbaQueryStoreConfig        
- [x] Copy-DbaResourceGovernor        
- [ ] Copy-DbaServerAudit             
- [ ] Copy-DbaServerAuditSpecification
- [ ] Copy-DbaSqlDataCollector        
- [ ] Copy-DbaSqlPolicyManagement     
- [ ] Copy-DbaSqlServerAgent          
- [ ] Copy-DbaSsisCatalog             
- [ ] Copy-DbaSysDbUserObject         
- [x] ~Export-DbaAvailabilityGroup~    
- [ ] Export-DbaCredential 
- [ ] Export-DbaExecutionPlan  
- [ ] Export-DbaInstance 
- [ ] Export-DbaLinkedServer
- [ ] Export-DbaRepServerSetting      
- [ ] Export-DbaScript                
- [ ] Export-DbaSpConfigure           
- [ ] Export-DbaXECsv                 
- [ ] Find-DbaAgentJob                
- [ ] Find-DbaCommand                 
- [ ] Find-DbaDbGrowthEvent           
- [x] Find-DbaDisabledIndex           
- [ ] Find-DbaLoginInGroup            
- [ ] Find-DbaStoredProcedure         
- [ ] Find-DbaTrigger                 
- [ ] Find-DbaUnusedIndex             
- [ ] Find-DbaUserObject              
- [ ] Find-DbaView                    
- [x] Get-DbaAgentAlert               
- [x] Get-DbaAgentLog    
- [ ] Get-DbaAgentProxy             
- [ ] Get-DbaAgentSchedule            
- [x] ~Get-DbaAgListener~
- [ ] Get-DbaBackupDevice             
- [ ] Get-DbaCmConnection             
- [x] Get-DbaCmObject                 
- [ ] Get-DbaConfig                   
- [ ] Get-DbaConfigValue              
- [ ] Get-DbaCpuUsage                 
- [x] Get-DbaCredential               
- [ ] Get-DbaCustomError              
- [ ] Get-DbaDatabaseAssembly         
- [ ] Get-DbaDatabaseFile             
- [ ] Get-DbaDatabaseMasterKey        
- [ ] Get-DbaDatabasePartitionFunction
- [ ] Get-DbaDatabasePartitionScheme  
- [ ] Get-DbaDatabaseSpace            
- [ ] Get-DbaDatabaseUdf              
- [ ] Get-DbaDatabaseUser             
- [ ] Get-DbaDatabaseView    
- [ ] Get-DbaDbAssembly
- [ ] Get-DbaDbEncryption
- [ ] Get-DbaDbExtentDiff
- [ ] Get-DbaDbFeatureUsage
- [ ] Get-DbaDbMail
- [ ] Get-DbaDbMailAccount
- [ ] Get-DbaDbMailConfig
- [ ] Get-DbaDbMailHistory            
- [ ] Get-DbaDbMailLog  
- [ ] Get-DbaDbMailProfile
- [ ] Get-DbaDbMailServer
- [ ] Get-DbaDbMasterKey
- [ ] Get-DbaDbMirror
- [ ] Get-DbaDbMirrorMonitor
- [ ] Get-DbaDbPartitionFunction
- [ ] Get-DbaDbPartitionScheme
- [ ] Get-DbaDbQueryStoreOption
- [ ] Get-DbaDbSpace
- [ ] Get-DbaDbTable
- [ ] Get-DbaDbTrigger
- [ ] Get-DbaDbUdf
- [ ] Get-DbaDbUser              
- [x] Get-DbaDefaultPath              
- [ ] Get-DbaDependency               
- [ ] Get-DbaDetachedDatabaseInfo
- [ ] Get-DbaDeprecatedFeature     
- [x] Get-DbaEndpoint                 
- [ ] Get-DbaEstimatedCompletionTime  
- [ ] Get-DbaExecutionPlan            
- [x] Get-DbaHelpIndex       
- [ ] Get-DbaInstanceUserOption         
- [ ] Get-DbaJobCategory              
- [x] Get-DbaLastGoodCheckDb          
- [ ] Get-DbaLinkedServer             
- [ ] Get-DbaLocaleSetting            
- [ ] Get-DbaMaintenanceSolutionLog   
- [ ] Get-DbaManagementObject
- [ ] Get-DbaMemoryUsage              
- [ ] ~Get-DbaMsdtc~ (This one we'd have to verify what is installed on Appveyor instance)                    
- [ ] Get-DbaNetworkActivity          
- [ ] Get-DbaNetworkCertificate       
- [x] Get-DbaOrphanUser               
- [ ] Get-DbaPageFileSetting    
- [ ] Get-DbaPbmCategory
- [ ] Get-DbaPbmCategorySubscription
- [ ] Get-DbaPbmCondition
- [ ] Get-DbaPbmObjectSet
- [ ] Get-DbaPbmStore      
- [ ] Get-DbaPrivilege     
- [ ] Get-DbaProductKey           
- [ ] Get-DbaQueryExecutionTime    
- [ ] Get-DbaRepServer
- [ ] Get-DbaResourceGovernor   
- [x] Get-DbaRestoreHistory    
- [ ] Get-DbaRgResourcePool
- [ ] Get-DbaRgWorkloadGroup       
- [ ] Get-DbaRoleMember   
- [ ] Get-DbaRunningJob               
- [x] Get-DbaServerAudit              
- [ ] Get-DbaServerAuditSpecification 
- [ ] Get-DbaServerInstallDate  
- [ ] Get-DbaServerTrigger      
- [ ] ~Get-DbaSpn~      
- [ ] Get-DbaSsisExecutionHistory                
- [ ] Get-DbaSqlInstanceUserOption    
- [ ] Get-DbaSqlManagementObject      
- [ ] Get-DbaSqlProductKey            
- [ ] Get-DbaSsisEnvironmentVariable  
- [ ] Get-DbaStartupParameter         
- [ ] Get-DbaTable                    
- [x] Get-DbaTcpPort                  
- [ ] Get-DbaTempdbUsage 
- [ ] Get-DbatoolsConfigValue             
- [ ] Get-DbatoolsLog                 
- [ ] Get-DbaTrigger                  
- [ ] Get-DbaWindowsLog               
- [ ] Get-DbaXEObject                 
- [ ] Get-DbaXESessionTargetFile      
- [ ] Get-DbaXESmartTarget            
- [ ] Get-DbaXEStore                  
- [ ] Import-DbaCsvToSql              
- [ ] Import-DbaSpConfigure           
- [x] Install-DbaFirstResponderKit    
- [ ] Install-DbaWatchUpdate          
- [ ] Install-DbaWhoIsActive          
- [ ] Invoke-DbaAdvancedRestore       
- [ ] Invoke-DbaDatabaseUpgrade   
- [ ] Invoke-DbaDbLogShipRecovery
- [ ] Invoke-DbaDbMirrorFailover
- [ ] Invoke-DbaDbUpgrade    
- [ ] Invoke-DbaLogShippingRecovery   
- [ ] Invoke-DbaPfRelog    
- [ ] Invoke-DbatoolsRenameHelper           
- [ ] Invoke-DbaWhoisActive           
- [ ] Invoke-DbaXEReplay              
- [ ] Measure-DbaDiskSpaceRequirement 
- [ ] Measure-DbatoolsImport
- [ ] New-DbaAgentSchedule            
- [ ] New-DbaCmConnection  
- [ ] New-DbaConnectionString           
- [ ] New-DbaDatabaseMasterKey        
- [ ] New-DbaDbUser         
- [ ] New-DbaDbMasterKey
- [ ] New-DbaDirectory          
- [ ] New-DbaScriptingOption          
- [ ] New-DbaServiceMasterKey         
- [ ] New-DbaSqlConnectionString      
- [ ] New-DbaSqlDirectory             
- [ ] New-DbatoolsSupportPackage      
- [ ] New-DbaXESession                
- [ ] New-DbaXESmartCsvWriter         
- [ ] New-DbaXESmartEmail             
- [ ] New-DbaXESmartQueryExec         
- [ ] New-DbaXESmartReplay            
- [ ] New-DbaXESmartTableWriter       
- [ ] Read-DbaBackupHeader            
- [x] Read-DbaTraceFile               
- [ ] Read-DbaTransactionLog          
- [ ] Register-DbatoolsConfig              
- [ ] Remove-DbaAgentJobStep          
- [ ] Remove-DbaAgentSchedule         
- [ ] Remove-DbaCmConnection          
- [ ] Remove-DbaDatabaseMasterKey     
- [x] Remove-DbaDatabaseSafely        
- [ ] Remove-DbaNetworkCertificate    
- [x] Remove-DbaOrphanUser            
- [ ] Remove-DbaSpn      
- [ ] Remove-DbaDbMasterKey
- [ ] Remove-DbaDbMirror             
- [ ] Remove-DbaXESmartTarget         
- [ ] Rename-DbaDatabase 
- [ ] Repair-DbaDbMirror             
- [ ] Repair-DbaOrphanUser            
- [ ] Repair-DbaServerName            
- [x] Reset-DbaAdmin (this one I'd be wary of doing or will require special treatment in the test groups)                  
- [ ] Resolve-DbaNetworkName          
- [ ] Restore-DbaBackupFromDirectory  
- [ ] Save-DbaDiagnosticQueryScript   
- [ ] Set-DbaAgentJob                 
- [ ] Set-DbaAgentJobOutputFile       
- [ ] Set-DbaAgentJobStep             
- [ ] Set-DbaAgentSchedule            
- [ ] Set-DbaCmConnection             
- [ ] Set-DbaConfig                   
- [ ] Set-DbaDatabaseOwner            
- [x] Set-DbaDbCompression   
- [ ] Set-DbaDbMirror
- [ ] Set-DbaDbOwner         
- [ ] Set-DbaJobOwner                 
- [ ] Set-DbaNetworkCertificate       
- [ ] Set-DbaPowerPlan                
- [ ] Set-DbaPrivilege                
- [ ] ~Set-DbaSpn~                      
- [ ] Set-DbaStartupParameter         
- [ ] Set-DbaTcpPort                  
- [ ] Set-DbaTempDbConfig
- [ ] Set-DbatoolsConfig    
- [ ] Show-DbaDatabaseList    
- [ ] Show-DbaDbList        
- [ ] Show-DbaServerFileSystem        
- [ ] Start-DbaMigration              
- [ ] Start-DbaXESmartTarget          
- [x] Stop-DbaProcess                 
- [ ] Stop-DbaXESmartTarget           
- [ ] Sync-DbaLoginPermission 
- [x] Test-DbaBuild    
- [x] Test-DbaCmConnection            
- [x] Test-DbaDbCompatibility
- [x] Test-DbaDeprecatedFeature  
- [x] Test-DbaDiskAllocation          
- [x] Test-DbaLinkedServerConnection
- [x] Test-DbaLoginPassword  
- [x] Test-DbaOptimizeForAdHoc        
- [x] Test-DbaPowerPlan               
- [x] ~Test-DbaSpn~                                  
- [ ] Uninstall-DbaWatchUpdate        
- [ ] Update-DbaPowerBiDataSource     
- [ ] Update-dbatools                 
- [ ] Watch-DbaUpdate

**Comment by wsmelton** [comment]
@joshcorr I've marked out some that can't have a test made due to Appveyor restrictions.

As well you might want to verify the function files with those that are exported because some of those files are not active commands. (e.g. `Start-DbaPowerBi`, the pbix file does not even exist that this points at.)

**Comment by niphlod** [comment]
Updated the body of the issue to have working links. IMHO having a single issue for all is not useful (I can't see it clearer than [BOH](https://sqlcollaborative.github.io/boh) ), but mileage may vary. Let's see how it goes.

**Comment by wsmelton** [comment]
Yeah, also worth noting that even ones with a current test only have a "skeleton" of a test so it may not have full integration and such. On those, the only way to really identify them is on the BOH for coverage.

**Comment by kwiknick** [comment]
What is the version of Pester you all have standardized on?  I could start writing some of these tests this week, but want to make sure I'm not using Pester 4.5.0 and you all are using version 3.

**Comment by niphlod** [comment]
we install from choco so it's pretty recent (what we run is `choco install pester`)

**Comment by potatoqualitee** [comment]
thanks so much @kwiknick - you may find that this list is outdated. It would also be useful to have it updated or regenerated for the tests that are missing 👍

**Comment by niphlod** [comment]
there's [BOH](https://sqlcollaborative.github.io/boh) for that (if a `get-childitem .\tests\` is too hard )

**Comment by kwiknick** [comment]
Thanks for the response.  I have to say, that BOH is pretty slick.  I'll start chipping away at a test here and there.  Thanks for the clarity on the Pester version.

**Comment by joshcorr** [comment]
Re-opening this issue as there are still a lot of tests that need to be created.

**Comment by wsmelton** [comment]
You need to create issues for each test because each commit you reference this issue with as fixed, will automatically close it again.

**Comment by wsmelton** [comment]
Or at most group them potentially with like commands (Set, Get, etc.) if that is possible.

**Comment by niphlod** [comment]
yep, but don't bother keeping this open. When you "targeted" a/some function(s), open an issue, assign it to yourself (so other won't work on the same thing) and on the PR you can reference that.

**Comment by joshcorr** [comment]
Will do @niphlod!
