### ISSUE TITLE
Command execution time

### ISSUE THREAD

**Issue by olegasdo** [sqlcollaborative/dbatools#3353]
## Feature Request

Time to time there is a need to check how much time it took for command to execute. 
And having time taken in output would be nice.
I understand, that here are other ways to achieve the result, but having it in one place will be more effective.

**Comment by niphlod** [comment]
what "command" ?

**Comment by olegasdo** [comment]
I was thinking about Backup-DbaDatabase
Maybe will be useful for other commands also.

**Comment by niphlod** [comment]
Could you elaborate a bit further on the scenario ? 
If you need to take the time of any PS function, `Measure-Command` is there already

As for the specific usecase of Backup-DbaDatabase, it's probably the "most unneeded" as with a `Get-DbaBackupHistory -Last` you get a ton on info already, included the Duration.

**Comment by Stuart-Moore** [comment]
Though Get-DbaBackupHistory is providing the output for Backup-DbaDatabase (L 454), so in this case it'd just be adding another field to the output object as the lifting has  already been done.

**Comment by niphlod** [comment]
yeah, backup-dbadatabase has already a "Duration" property.

**Comment by olegasdo** [comment]
Sorry then.
