### ISSUE TITLE
Restore-DbaDatabase Fails with Azure Credentials

### ISSUE THREAD

**Issue by lcloudsdale** [sqlcollaborative/dbatools#3356]
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?

### Version Information
 - Operating System (Windows 10): 
 - PowerShell Version: 5.1.16299.248
 - SQL Server (17.4|14.0.1000): 

### Problem to solve
I can't get the Restore-DbaDatabase to "see" the file even though I have verified it is present and executed a successful restore from the sql server instance via tsql directly.  I was hoping to run a full restore of our sql server user databases (for testing purposes) using the cmdlet.  Any help would be appreciated.

## Steps to Reproduce
~~~~
PS C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy> Restore-DbaDatabase -SqlInstance sql1 -Path https://sysbakbbgblob
.blob.core.windows.net/sys-sql-bak/GuardianCP_backup_2018_03_04_000001_9028539.bak -verbose -AzureCredential sysbakbbgbl
ob
VERBOSE: [Restore-DbaDatabase][08:12:36] Changing statement timeout to infinity
VERBOSE: [Get-DbaDefaultPath][08:12:36] Attempting to connect to LAPTOP-0O79E2V0
VERBOSE: [Restore-DbaDatabase][08:12:36] ParameterSet  = Restore
VERBOSE: [Restore-DbaDatabase][08:12:36] Unverified input, full scans -
https://sysbakbbgblob.blob.core.windows.net/sys-sql-bak/GuardianCP_backup_2018_03_04_000001_9028539.bak
VERBOSE: [Get-DbaBackupInformation][08:12:36] Testing a single file @{Length=103;
FullName=https://sysbakbbgblob.blob.core.windows.net/sys-sql-bak/GuardianCP_backup_2018_03_04_000001_9028539.bak}
VERBOSE: [Test-DbaSqlPath][08:12:36] Connecting to LAPTOP-0O79E2V0.
VERBOSE: [Get-DbaBackupInformation][08:12:36] [sql1] cannot 'see' file
https://sysbakbbgblob.blob.core.windows.net/sys-sql-bak/GuardianCP_backup_2018_03_04_000001_9028539.bak
WARNING: [Restore-DbaDatabase][08:12:36] No backups passed through.
 This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other
issue
~~~~

**Comment by wsmelton** [comment]
Can you issue the command with the parameter `OutputScriptOnly' and see if that runs via T-SQL execution for the given server?

**Comment by lcloudsdale** [comment]
Hi wsmelton,

Ran it with OutputScriptOnly (see below) and still no luck.

`PS C:\Users\Luke Cloudsdale> Restore-DbaDatabase -SqlInstance sql1 -Path https://sysbakbbgblob.blob.core.windows.net/sys-sql-bak/GuardianCP_backup_2018_03_04_000001_9028539.bak -verbose -AzureCredential sysbakbbgblob -OutputScriptOnly
VERBOSE: [Restore-DbaDatabase][09:13:45] Changing statement timeout to infinity
VERBOSE: [Get-DbaDefaultPath][09:13:45] Attempting to connect to LAPTOP-0O79E2V0
VERBOSE: [Restore-DbaDatabase][09:13:45] ParameterSet  = Restore
VERBOSE: [Restore-DbaDatabase][09:13:45] Unverified input, full scans -
https://sysbakbbgblob.blob.core.windows.net/sys-sql-bak/GuardianCP_backup_2018_03_04_000001_9028539.bak
VERBOSE: [Get-DbaBackupInformation][09:13:45] Testing a single file @{Length=103;
FullName=https://sysbakbbgblob.blob.core.windows.net/sys-sql-bak/GuardianCP_backup_2018_03_04_000001_9028539.bak}
VERBOSE: [Test-DbaSqlPath][09:13:45] Connecting to LAPTOP-0O79E2V0.
VERBOSE: [Get-DbaBackupInformation][09:13:45] [sql1] cannot 'see' file
https://sysbakbbgblob.blob.core.windows.net/sys-sql-bak/GuardianCP_backup_2018_03_04_000001_9028539.bak
WARNING: [Restore-DbaDatabase][09:13:45] No backups passed through.
 This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other
issue`

**Comment by Rici11** [comment]
I'm affected by the same exact issue.

**Comment by Rici11** [comment]
I may be mistaken, but the error could be due to the Restore-DbaDatabase calling on line 541 the following:

```
Write-Message -Level Verbose -Message "Unverified input, full scans - $($files -join ';')"
$BackupHistory += Get-DbaBackupInformation -SqlInstance $RestoreInstance -SqlCredential $SqlCredential -Path $files -DirectoryRecurse:$DirectoryRecurse -MaintenanceSolution:$MaintenanceSolutionBackup -IgnoreLogBackup:$IgnoreLogBackup
```

This is trying to populate the BackupHistory variable, however the Get-DbaBackupInformation cmdlet doesn't seem to allow Azure Credentials to be passed, so it's returning an empty result.

This later triggering a return on line 604 when an if condition catches that the BackupHistory variable is empty.

```
if ($BackupHistory.Count -eq 0) {
Write-Message -Level Warning -Message "No backups passed through. `n This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other issue"
return
}
```

**Comment by wsmelton** [comment]
Yeah, the fact it is not getting the history will also tie into why the output only option does not work.

The command was changed around to include a special type (backup object) some time back and I'm curious if that is when it actually broke. I can try and check that object type to see if it is supposed to handle the credential (thought it was). It may just be the need to update that sub-function call to accept a credential.

**Comment by potatoqualitee** [comment]
fixing this
