### ISSUE TITLE
Stored (Set-DbcConfig) SqlCredential/Credential fix

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3362]
Registry does not support `PSCredential`. Per @FriedrichWeinmann, in order to get around this, we can store the _location_ of the `Export-CliXml` but keep in mind, this will be user and machine specific. Ultimately, this is the safest and least controversial approach.

Set as bug because we need to update our docs.

**Comment by wsmelton** [comment]
Are you sure about that??

**Comment by SQLDBAWithABeard** [comment]
It used to work.  Not sure when it stopped but it worked at Bits

**Comment by potatoqualitee** [comment]
(wrong repo too)

**Comment by niphlod** [comment]
but stalebot works!
