### ISSUE TITLE
New Command - View SSIS Execution History

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#3369]
Investigate if there is a way to view SSIS package execution history from PS.

**Comment by niphlod** [comment]
if you have a SSISDB all it takes is one query, is this really needed ?

**Comment by gbargsley** [comment]
90% of our commands are just one query.  Is that the approach when determining new commands?

**Comment by wsmelton** [comment]
Sounds fine to me, the point of commands is not whether just one query will pull the information or not. It is providing the ability to pull that information across the enterprise of servers.

I recall Tim Mitchell has a good query posted somewhere that gives you about as much detail as the built in reporting does in SSMS.

**Comment by wsmelton** [comment]
There won't be much in SMO (if anything) for this so it would have to be T-SQL calls.

**Comment by potatoqualitee** [comment]
i agree that this is a useful command and the underlying number of queries does not matter. that's one of my favorite things about PowerShell is that it takes hard to remember queries and simplifies them with human readable commands

**Comment by niphlod** [comment]
okay then, I have a set of queries already pretty complete at https://github.com/niphlod/ssis_dash/ .

**Comment by potatoqualitee** [comment]
😍

**Comment by niphlod** [comment]
thank @yorek for those ^_^

**Comment by wsmelton** [comment]
Probably pull some snippets out of this as well... https://github.com/aleonard763/CatalogReports?files=1

**Comment by ChrisTuckerNM** [comment]
I've forked and begun work on this.

**Comment by ChrisTuckerNM** [comment]
Complete and in PR/Merge.  Ready to close?

**Comment by potatoqualitee** [comment]
totes!
