### ISSUE TITLE
Get-DbaRestoreHistory Performance Issues

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#3375]
## Bug Report
Get-DbaRestoreHistory takes a *long* time when running against an instance with a lot of restore history. Most of the time is spent in PowerShell, not in the SQL query that gets issued. High CPU is seen on the client while the function is executing (~50% on 2-core server). By changing `$results | Select-DefaultView` to `Select-DefaultView -InputObject $results` this issue is resolved. I will submit a PR with the change.

### General Troubleshooting steps
- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [ ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2016 Standard
 - PowerShell Version: 5.1.14393.1532
 - SQL Server (Edition|Version): 13.0.4422 Developer Edition

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by niphlod** [comment]
another pipe beaten !

**Comment by awickham10** [comment]
Sounds like this should probably be a sweeping change across all of dbatools. Pretty low risk to make the change and seems like a high reward. I found 508 instances where Select-DefaultView is being piped to.

**Comment by niphlod** [comment]
readability-wise, pipe looks good. 
Performance-wise, not so much. It's more of a PS problem than a dbatool's one, though I'd not go for rewriting things for functions that pass around 4 objects but, hey, ultimately it's up to "code style cops".

**Comment by niphlod** [comment]
(BTW: dunno the performance considerations regarding memory usage, but probably there are )

**Comment by awickham10** [comment]
We have very similar issues with Get-DbaBackupHistory but with different functions (Select-Object, Group-Object, etc.) I'm going to open up a separate issue for it, but that's at least promising that it's not specific to the Select-DefaultView function causing the issue. I'm working on a fix for it as well.

These have been fairly large result sets though (tens of thousands of rows).

**Comment by niphlod** [comment]
not every pipe can be easily switched out with -inputobject (think Group-Object) though I'm eager to see what you'll come up with: there are definitely margins of improvement, speed-wise.
