### ISSUE TITLE
Get-DbaBackupHistory Performance Issues

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#3379]
## Bug Report
Get-DbaBackupHistory takes a long time when running against an instance with a lot of backup history (my test had ~30k rows). Most of the time is spent in PowerShell, not in the SQL query that gets issued. High CPU is seen on the client while the function is executing (~50% on 2-core server). 

This appears to be related to the Group-Object and processing of the grouped output. 

### General Troubleshooting steps
- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2016 Standard
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 2017 Standard Edition

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Additional information

We may need to switch the processing done towards the end of the function to T-SQL instead of in PowerShell.

**Comment by awickham10** [comment]
I took an initial look at this. One of the major slow downs is the group object when not executing with the Raw switch. I was able to rework it so it doesn't use group by, but this means a SQL call with a subquery to generate the list of backupsetids instead of using PowerShell to determine that list.

When populating the FileList property, it is a major slow down. Each row takes ~1 second to process. By taking out that property it executes around 125 per second. Maybe including the list of files backed up should be an optional parameter? Either that or maybe we can build that list in the initial SELECT and have it in a parseable format?

**Comment by awickham10** [comment]
I think I got around the FileList performance issue by  using DataTable's Select method. PR to come soon.

**Comment by potatoqualitee** [comment]
thank you @awickham10 !

**Comment by niphlod** [comment]
I feel we already closed this a long ago. @awickham10 feel free to reopen in case the performance is still bad
