### ISSUE TITLE
Get-DbaUserLevelPermission only shows the 1st instance

### ISSUE THREAD

**Issue by tiagobalabuch** [sqlcollaborative/dbatools#3392]
### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2 / Windows Server 2016
 - PowerShell Version: 5.1.16299.251
 - SQL Server (Edition|Version): SQL Server 2012 / SQL Server 2014 / SQL Server 2016 / SQL Server 2017

## Steps to Reproduce
- Step 1 -  Set variable 
- Step 2 - run command Get-DbaUserLevelPermission with WHERE-OBJECT condition.
- $SQLList = "localhost\SQL2012","localhost\SQL2014", "localhost\SQL2016"
Get-DbaUserLevelPermission -SqlInstance $SQLList | Where-Object {$_.RoleSecurableClass -eq "sysadmin"} | Format-Table

This command only return information for the first item in the list. It is possible to check the command is connecting in all items (SQL Server instances) but the result is only for first one. 
If remove WHERE condition it works as expected. 

 - [X] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

## Feature Request
I would like to get all logins with sysadmin permission

### Additional information

![image](https://user-images.githubusercontent.com/32172209/37612570-76bceec6-2b9d-11e8-9bfc-f0022d622561.png)
![dbatools-02](https://user-images.githubusercontent.com/32172209/37612623-a13f77cc-2b9d-11e8-887c-dbb93f6a6678.png)

**Comment by ClaudioESSilva** [comment]
Thanks for the report @tiagobalabuch !
PR #3397 will fix it.
