### ISSUE TITLE
Get-DatabaseFile errors on compat level 100 databases

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#3405]
Opened as dbachecks issue by @fatherjack as first identified there and affecting Log File Size Checks.
 
https://github.com/sqlcollaborative/dbachecks/issues/409 

Moved to dbatools

Issue
This is a bug

Bug Report
General Troubleshooting steps
 Verified running the latest release of dbachecks ?
error present in 9.304

 Verified errors are not related to permissions?

 Can duplicate in new/clean PowerShell session (clean = powershell -NoProfile)?

Version Information
Operating System (Name|Version): Win 10 Pro
PowerShell Version: v5
SQL Server (Edition|Version): SQL Server 2016 13.0.4206.0 Developer Edition
Steps to Reproduce
When running Get-DbaDatabaseFile against a server with databases in 100 compatability level the following error is returned for the 100 level databases:

Get-DbaDatabaseFile -sqlinstance "$env:computername\sql2016"

Select-Object : Cannot convert System.Char to one of the
following types {System.String,
System.Management.Automation.ScriptBlock}.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.304
allcommands.ps1:25512 char:111
`+ ... g(0, 1) } | Select-Object $MbFreeColName -ExpandProperty
$MbFreeColNa ...

I have done some debugging.
The issue is due to the tsql being executed based on the version of the database. As this is a 100 level database the tsql doesnt include any volume free space information from the sys.dm_os_volume_stats and the get available_bytes column.

This is tested at line 25506 - the test is if ($result.VolumeFreeSpace)
For a 100 level database this fails so the Else code is executed but the code in the Else returns a value of e in the variable

lines 25510 - 25513 - my values debugging each line are in bold

$disks = $server.Query("xp_fixeddrives", $db.Name)
**drive MB free

C 163674**

$MbFreeColName = $disks[0].psobject.Properties.Name[1]
e
$free = $disks | Where-Object { $_.drive -eq $result.PhysicalName.Substring(0, 1) } | Select-Object $MbFreeColName -ExpandProperty $MbFreeColName
[error]
because the value 'e' doesnt relate to anything

checking different options of line 25511 ...
Line 25511 sets the value of $MbFreeColName to the result of
$disks[0].psobject.Properties.Name[1] which we know results in e.

The result of
$disks[0].psobject.Properties.Name is length

the result of
$disks[0].psobject.Properties.Name[4] is t

**Comment by fatherjack** [comment]
Have a fix for this now, just need to get connected to GitHub and sync the change for others to test
