### ISSUE TITLE
Restore-DbaDatabase keeps going on error

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3407]
`gci C:\github\appveyor-lab\singlerestore | Restore-DbaDatabase -SqlInstance $script:instance1`

from our appveyor lab repo, restore then see the blood

![image](https://user-images.githubusercontent.com/8278033/37734964-fe7528a0-2d4c-11e8-8e50-5ea01a6540f3.png)

**Comment by Stuart-Moore** [comment]
Can I have the version of $your script:instance1 please.

Is it only breaking locally or on appveyor as well?

**Comment by Stuart-Moore** [comment]
$script:instance1 even. Damp you autocorrect 🙄

**Comment by Zhunya** [comment]
Did not fail in my environment, seems this is local problem on appveyor.

**Comment by Stuart-Moore** [comment]
Is compression.bak available anywhere? Guessing it's probably been created on a new version of sql than whatever $script:instance1 is. The other backups in appveyor-lab are mainly 2008r2 as that's what appveyor provide.

reproed the issue anyway and PR #3410 in to catch incompatible versions

**Comment by Zhunya** [comment]
Trying to restore backup from 2016 to 2008 R2 instance did not give lots of red, seems problem in `compression.bak` file itself.
![image](https://user-images.githubusercontent.com/14327077/37758773-73fd623e-2dc2-11e8-91c0-1d64874979a3.png)

**Comment by Stuart-Moore** [comment]
Mine does:
![image](https://user-images.githubusercontent.com/5613670/37759090-82011ff0-2daa-11e8-8a54-67be855a245a.png)

so we'll go with the fix I've pushed up.

yours is failing at a different point to mine and cl's, we're failing at the ReadFileList call, which is happening with a null datatable, you're is failing at the intial ReadBackupHeader.

**Comment by jpomfret** [comment]
I had an instance yesterday where restore failed due to lack of disk space but my script carried on, had `-EnableException` switch on and within a try catch block. Do I have my scenario setup wrong or is this the same issue? dbatools version 0.9.305

**Comment by wsmelton** [comment]
@Stuart-Moore @Zhunya The backup @potatoqualitee is using can be found here: https://github.com/sqlcollaborative/appveyor-lab

It is where all the test files for Appveyor are kept and pulled from when Appveyor is running our test.
