### ISSUE TITLE
Repair-Orphan users does not contain Force parameter

### ISSUE THREAD

**Issue by frank687** [sqlcollaborative/dbatools#3414]
### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 8.1
 - PowerShell Version: 5.0.10586.117
 - SQL Server (Edition|Version): All

## Steps to Reproduce
`Repair-DbaOrphanUser -SqlInstance <INSTANCE>-RemoveNotExisting`

Have one of the users own a schema. You then get this warning
```WARNING: [Remove-DbaOrphanUser][14:45:14] Schema 'SCHEMA' owned by user SOMEONE have 19 underlying objects. If you want to change the schemas' owner to 'dbo' and drop the user anyway, use -Force parameter. Skipping user 'SOMEONE'.                               ```

Reissue command with -Force parameter
`Repair-DbaOrphanUser -SqlInstance <INSTANCE>-RemoveNotExisting - Force`
New Error: 
```Repair-DbaOrphanUser : A parameter cannot be found that matches parameter name 'Force'.
At line:1 char:63
+ Repair-DbaOrphanUser -SqlInstance <INSTANCE>-RemoveNotExisting -Force
+                                                               ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Repair-DbaOrphanUser], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Repair-DbaOrphanUser
```

**Comment by garethnewman** [comment]
I'll do this tonight. Can it be assigned to me?

**Comment by shaneis** [comment]
Can't assign it to you @garethnewman Are you a contributor? Think you have to hit up @potatoqualitee to do this

**Comment by garethnewman** [comment]
Well, I just started contributing - new to powershell but using these tools as a DBA so want to contribute and learn, picking up the easy bugs! :) Well consider it done, I'll do it later and push. I just don't want to pick something up if someone else solves it before me :)

**Comment by shaneis** [comment]
Ah sorry man, I meant to come across more "_looks like you don't have permission yet, let's fix that!_" rather than a "_who are you?_".
Coolio! 
Well, I can't assign it to you (**yet**) but if you need a review of your PR later on, let me know 👍

**Comment by garethnewman** [comment]
Ha ha no worries ;)

**Comment by garethnewman** [comment]
@wsmelton that invite you sent me expired I think. I seem to be able to make PRs though 👍
