### ISSUE TITLE
Import-CsvtoSql Improvements - 32-bit shell & Lumenworks

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#343]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The code is ugly and switches to 32-bit PowerShell using some crazy commands that should have used splatting anyway. But then I found out about this and this is how we should it plus splatting

http://community.idera.com/powershell/powertips/b/tips/posts/running-32-bit-code-on-the-same-machine

Also, initially, all I cared about was speed, and didn't account as much for stability. This means the CSV had to be *perfect* and couldn't use quoted stuff. I'd like to support a wider variety of CSVs and this would require a better reader like Lumenworks.

Perhaps if the first super fast method throws an exception, instead of showing a big ol message about perfect CSVs, we could show a warning saying that we're attempting a slower import, then use either OLE or LumenWorks (but at some point LumenWorks becuase Ive seen a lot of cases where OLE doesn't work, either)

I recently added /bin/LumenWorks.Framework.IO.dll to the dev directory. Perhaps if the fast one fails, we can just default to that and get rid of OLE all together? Tho I think that OLE is pretty fast, perhaps faster than Lumenworks. That's the shell that uses 32-bit.

**Comment by SharePointPog** [comment]
Where is the source code for the LumenWorks.Framework.IO.dll?

I am a newbie--just discovered this project--so I apologize if this is thew wrong place to ask this question.

I was wondering whether this project is closed or open source, and I saw that the license says GPL, which usually means that source is included, but I am too much a newbie to understand yet where to find the source. I apologize if this is the wrong place to post this question?

**Comment by potatoqualitee** [comment]
hey @SharePointPog - sorry I didn't see this. The code can be found at https://github.com/phatcher/CsvReader/tree/master/code/LumenWorks.Framework.IO

**Comment by potatoqualitee** [comment]
omg this command is like 1000 lines too long to mess with on a Sunday Funday 👎

**Comment by potatoqualitee** [comment]
Gonna just switch to bcp which microsoft has graciously allowed us to include. just need the time.
