### ISSUE TITLE
Sync-DbaSqlLoginPermission > Sync-DbaLoginPermission

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3437]
the previous command name never sat well with me. I realized today it's because it's too long and contains an unnecessary Sql. I'd like to rename it.

**Comment by wsuhoey** [comment]
Not that my opinion means that much, but I think that's fine as long as the command covers both `DOMAIN\User` logins and regular SQL logins

**Comment by potatoqualitee** [comment]
good question, it does do both 👍

**Comment by wsmelton** [comment]
I'm good

**Comment by niphlod** [comment]
+1 for me too

**Comment by potatoqualitee** [comment]
sweet thanks yall, gonna do it

**Comment by zippy1981** [comment]
I endorse the wisdom of our fearless leader.

**Comment by garethnewman** [comment]
The current name makes me think of SQL logins so I'd change it 👍

**Comment by potatoqualitee** [comment]
yall the best, thank you. will do this sometime this week/weekend
