### ISSUE TITLE
Some size math operator overloads don't make sense.

### ISSUE THREAD

**Issue by zippy1981** [sqlcollaborative/dbatools#3441]
As per slack convseration @FriedrichWeinmann the Size math overloads were put in to speed up what PowerShell was already letting happen. Moving this here for long for discussion.

Yes my opinions are very "app-dev" centric, and in powershell we like things to just magically work even if its not entirely sensible.

The following operations make sense (to me) for a user to want to do:

* public static Size operator *(Size a, double b)
* public static Size operator +(Size a, Size b)
* public static Size operator -(Size a, Size b)
*public static Size operator /(Size a, double b)

The following don't:

* public static Size operator *(Size a, Size b)
* public static Size operator /(Size a, Size b)

Pragmatically, you would never multiple bytes X bytes or divide bytes by bytes just like you'd never multiply currency by currency. Does someone actually need to do that? Is there a use case I don't understand?

If anything, I'd actually argue that those operator overloads should explicitly throw exceptions to "nicely" point out how silly the user is being.

**Comment by niphlod** [comment]
+1 on the logic.

**Comment by FriedrichWeinmann** [comment]
Those last two were slight performance upgrades for when someone compares sizes between two items and then keeps calculating with that result. In opposite to the original 4 operators (which are needed to emulate numeric behavior)  the lower two only exist to save us some time in PowerShell type coercion game in those scenarios.
They are _not_ critical, so if you want them gone, that's ok with me.

I _do_ disagree with throwing an exception though, as it would mess up working with size values in chained calculations (such as "How much space do I need?" after having determined "How many of those do I need?" both calculates on sizes), without the user understanding what is happening there.

**Comment by FriedrichWeinmann** [comment]
Yes, you will end up doing just that - powershell will simply type-coerce the size to double if we don't keep those last two operators (which is less efficient than doing it ourselves).

I think in this case, adding a verbose support will not offer benefits and be significant overhead / not fun to code. Anybody who knows enough about this to enable Verbose, already understands it and is unlikely to do it to begin with. We could easily (and with minimal effort) tie it into the logging/message system (without printing anything to the console screen) though, so it'd be available for forensics.
That requires the two debated operators though, for the ones accepting double will not know whether the original input was coerced from Size or not.

**Comment by niphlod** [comment]
@zippy1981 : I'd feel like closing this, can you take a look and, if already "handled", close ?

Thanks

**Comment by potatoqualitee** [comment]
agreed on the close 👍
