### ISSUE TITLE
Test-DbaDbVirtualLogFile doesn't test anything

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#3444]
### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

## Steps to Reproduce
Current output is more of a `Get` command, there is a current `Get-DbaDbVirtualLogFile` that returns object of all the vlfs, suggesting this one should be edited to Test something
![image](https://user-images.githubusercontent.com/981370/38029317-89365cc8-3263-11e8-800e-bcc61f93f695.png)

## Feature Request
Returns current output plus a suggestion/best practice. Perhaps dependent on current log size.

**Comment by potatoqualitee** [comment]
Yes indeed :( Check out #2407 - I think that's the most recent complaint.

**Comment by jpomfret** [comment]
Man I even did a search and didn't find that one.. my bad :D

**Comment by potatoqualitee** [comment]
np, thank you for noticing - it does indeed need to do something.
