### ISSUE TITLE
Allow scripting variables with Invoke-Sqlcmd2 and Invoke-SqlDbaCmd

### ISSUE THREAD

**Issue by PianoMatt** [sqlcollaborative/dbatools#3449]
### Problem to solve
Scripting variables allow a script to be run in different environments and change database objects in SQL scripts. 

### Additional information

Example sql script with scripting variables.
```select   max($(col1)) as $(col1)```
```from     $(db).$(schema).$(table)```
```where    $(col2) = $(value2)```

Example execution of sql script with sqlcmd utility:
```sqlcmd  -S foo -d bar -i "c:\temp\test.sql" -v col1=CREATE_DATE db=MyDB schema=MySchema table=MyTable col2=MyColumn value2=1234```

Example execution using Invoke-Sqlcmd:
```$SqlVariables = 'col1=DateColumn','db=MyDB','schema=MySchema','table=MyTable','COL2=MyColumn','value2=1234';```
```Invoke-SqlCmd -ServerInstance foo -Database bar -InputFile "c:\temp\test.sql" -Variable $SqlVariables;```

See documentation at 
[Invoke-Sqlcmd](https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps)
[sqlcmd utilty](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility)
[scripting variables](https://docs.microsoft.com/en-us/sql/relational-databases/scripting/sqlcmd-use-with-scripting-variables)

**Comment by niphlod** [comment]
scripting variables are not quoted. They're just replaced "as is" within the query. 
There's a set of things Invoke-DbaSqlQuery won't ever do (and that's one of the main reason is aptly named NOT after sqlcmd), and this is one of them.
Having the ability to run a script that connects to multiple databases without you noticing is another one.
To sum up, parsing the whole shenanigans of sqlcmd is (and probably always be) out of scope.
For this particular usecase, you'd be just as good using interpolation within Powershell to build the query upfront.

**Comment by niphlod** [comment]
closing for now. feel free to reopen if I missed something
