### ISSUE TITLE
Read only intent for Invoke-DbaSqlQuery

### ISSUE THREAD

**Issue by michalporeba** [sqlcollaborative/dbatools#3451]
## Feature Request

Ability to execute read only queries against secondary replicas

### Problem to solve

Neither `Invoke-SqlCmd` , `Invoke-SqlCmd2` nor `Invoke-DbaSqlQuery` seems to support the read only application intent at the moment. I would like to be able to choose which replica to run the query against without the need to explicitly check. 

### Additional information

I was thinking of adding `-ReadOnly` parameter to `Invoke-DbaSqlQuery`  rather than piping in filtered results from `Get-DbaAgReplica` ( or something similar which could get rather complex very soon).  `Connect-SqlInstance` and `Invoke-SqlCmd2` would have to be modified to use read only application intent. 

`Connect-DbaInstance` already implements `-ApplicationIntent` parameter.

Would it be worth adding MultiSubnetFailover to the connection string too?

**Comment by niphlod** [comment]
guess is a fix for connect-dbainstance more than any other function. 
We can't really support every param combination in each function, so if you need "detailed" parameters, your scenario will be

$conn = Connect-DbaInstance .....
Invoke-DbaSqlQuery -SqlInstance $conn

**Comment by wsmelton** [comment]
@niphlod is correct on this one. If you need a custom connection property the implemented path is to create your connection first and then pass that connection to the command. The `Connect-DbaInstance` supports both `ApplicationIntent` and `MultiSubnetFailover`. 

`Invoke-SqlCmd2` utilizes `System.Data.SqlClient` to make connections. So if you need a custom connection property for that command you would have to pass in that full connection string via `SQLConnection` parameter.

In reference to `ApplicationIntent` for `Invoke-SqlCmd`...[we tried to get it added](https://trello.com/c/deWheByZ/123-applicationintent-support) but did not get enough votes or attention. I'm not sure they still utilize Trello so if you want to submit user feedback through the new site you can prompt getting this parameter added there.

**Comment by michalporeba** [comment]
I will give it a go but I'm not sure if this will be that simple. I was hopging to be able to run a query against all of the databases in my cluster which hosts multiple AGs. The connection string has to be decided on a database level if we cannot use the correct listener with ReadOnly intent. I'll do some testing when I've got a moment and will post an update here. 

As always, thanks for your input, @niphlod, @wsmelton. Much appreciated.

**Comment by wsmelton** [comment]
There is a command in the module that will output a connection string, can't recall name. That may help in the process.

**Comment by michalporeba** [comment]
It took me a while to get annoyed enough with that parameter not being there to actually do something about it. I have created a pull request with a proposed solution. 

There is one small problem, I cannot figure out a way to easily unit test it, without requiring an AG cluster for the test. I don't think there is a way to check from the connection point of view if the connection is actually with read only intent. 

And I don't see how one could expose ConnectionContext from Invoke-DbaQuery. 

Please let me know what you think.

**Comment by michalporeba** [comment]
Since this was left open with a `Feature` tag and not closed, and in light of the comments made by @wsmelton on the PR #4893 I will try to make my case again here. 

As it was pointed out it is possible to create a new read only connection with `Connect-DbaInstance -ApplicationIntent ReadOnly` and then pass it to the `Invoke-DbaQuery`. But when you use it a lot, it becomes cumbersome, in scripts it takes too much space for something that could be more elegant to write and read. 

`Invoke-SqlCmd2` is gone, so the option of using that no longer exists. The only alternative I see is to modify `Invoke-DbaQuery` and this is using the internal `Connect-SqlInstance`. I see that the change I made  is causing problems with SQL Authentication. I'll see if that can be resolved, perhaps (my) testing improved. Or is there another way? I think that would require changing how `Invoke-DbaQuery` works, perhaps make it use `Connect-DbaInstance` instaed of `Connect-SqlInstance`? 

And is this really a feature issue still open, or should be closed as `won't implement`?

**Comment by wsmelton** [comment]
`Invoke-Sqlcmd2` is not gone, it still exist in the module. Not sure why folks think it is, but we did not create `Invoke-DbaQuery` to replace it; only to simply have a version that matches our standard and that we can expand on. `Sqlcmd2` is the original version from the repository in `sqlcollaborative/invoke-sqlcmd2`.

**Comment by michalporeba** [comment]
That problem with SQL Authentication was a line of text (not even code) which I accidentally left in the file. Sorry, I'm a bit out of practice when it comes to debugging this dbatools. But to see how would that work I have removed the changes from the `Connect-SqlInstance` and used instead `Connect-DbaInstance` in the `Invoke-DbaQuery`. It all appears to be working... can you think of any unexpected side effects? @potatoqualitee it looks to be even simpler solution than modifying connection strings, it's done in the `Connect-DbaInstance` too.

**Comment by wsmelton** [comment]
We originally had a rule that we would not use `Connect-DbaInstance` (public command) within any command.

**Comment by michalporeba** [comment]
A fascinating rule, what was the reason behind it?
