### ISSUE TITLE
New Function - Get-DbaDbPageCount

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#3455]
## Feature Request
Return page usage information by table (total pages, used pages, unused pages). This command will be used to support the command the gets written in the new command in issue #3450.

### Problem to solve
Get number of pages by database/table.

### Additional information
Name Suggestions: 
- Get-DbaDbPageCount
- Get-DbaDbTblPageCount

Parameters: 
- SqlInstance
- SqlCredential (optional) 
- Database (optional)
- Schema (optional)
- Table (optional)
- ExcludeDatabase (optional)
- IncludeSystemDBs (optional)
- EnableException (optional)

**Comment by sanderstad** [comment]
Is this what you're looking for
![image](https://user-images.githubusercontent.com/6154981/38918523-4145d09c-42ee-11e8-9f79-c1e7c72d530d.png)

![image](https://user-images.githubusercontent.com/6154981/38919050-c90032a6-42ef-11e8-8684-2dcd94c5eab0.png)
