### ISSUE TITLE
New function - Test-DbaLoginPassword

### ISSUE THREAD

**Issue by PsPsam** [sqlcollaborative/dbatools#3462]
## Feature Request

  Simply answer the question: What problem or scenario would you like to solve with dbatools?
https://github.com/sqlcollaborative/dbachecks/issues/413

To be able to make that test in dbachecks I created a test function for dba tools. I looked but was unable to find it.

This function will by default test SQL Logins for null or same password as username. The function can take in other password by parameter -SQLPass as an array or by a csv file.

The function will return information about the user that will get caught by this check.

### Problem to solve
Bad password policy!

**Comment by potatoqualitee** [comment]
@scinobe had something like this - brandon, did you hash the values then compare?

**Comment by PsPsam** [comment]
Added the PR New function - Test-DbaSqlLoginWeakPassword #3462 #3464

**Comment by PsPsam** [comment]
Missed to remove the comment out the first time in the first post

**Comment by scinobe** [comment]
There's a function :)
This query returns the matches.


$pwdhashquery = "select serverproperty('machinename') as 'ServerName',
isnull(serverproperty('instancename'),serverproperty('machinename')) as
'InstanceName',
 name as 'Login',
 is_disabled,
 create_date,
 IS_SRVROLEMEMBER('sysadmin',name) as is_sa,
 IS_SRVROLEMEMBER('dbcreator',name) as is_dbcreator,
 IS_SRVROLEMEMBER('bulkadmin',name) as is_bulkadmin,
 IS_SRVROLEMEMBER('diskadmin',name) as is_diskadmin,
 IS_SRVROLEMEMBER('processadmin',name) as is_processadmin,
 IS_SRVROLEMEMBER('securityadmin',name) as is_securityadmin,
 IS_SRVROLEMEMBER('serveradmin',name) as is_serveradmin,
 IS_SRVROLEMEMBER('setupadmin',name) as is_setupadmin
from master.sys.sql_logins
where pwdcompare(name,password_hash) = 1
order by name
option (maxdop 1);"

**Comment by PsPsam** [comment]
@scinobe @potatoqualitee i don't have the role part in the query else it looks like the same query. 
But @wsmelton and @zippy1981 had some other feedback on the PR itself that might be usefull.

**Comment by scinobe** [comment]
I think I had added the roles myself so that I could tell how big of a risk
the account posed...
