### ISSUE TITLE
new config settings

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3467]
this is in SSMS -> Connect -> Connection Properties -> Options

![image](https://user-images.githubusercontent.com/8278033/38269979-4f3b3a1a-3782-11e8-8e82-d5e1a50942c1.png)

do not fix before psconf eu ;)

**Comment by wsmelton** [comment]
Which ones are you saying you want @potatoqualitee ?

The time out is already available.

**Comment by potatoqualitee** [comment]
nice to have but not required for 1.0

**Comment by potatoqualitee** [comment]
done in MFA PR
