### ISSUE TITLE
Pipe to set-dbamaxmemory not working

### ISSUE THREAD

**Issue by OEdling** [sqlcollaborative/dbatools#3491]
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10 Enterprise 64-bit | 1709
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): SQL Server Standard/Enterprise 13.0.4466.4

## Steps to Reproduce

When using Test-DbaMaxMemory to get RecommendedMB and then using pipe to get the values to Set-DbaMaxMemory you get an error message, see attached picture.

The command I'm running is:
Test-DbaMaxMemory -SqlInstance [instance] | Set-DbaMaxMemory

 - [x] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

![image](https://user-images.githubusercontent.com/32391217/38417619-44bd4dda-3999-11e8-85ac-544e985d0614.png)

**Comment by Zhunya** [comment]
Yep, still not working, but worked some time ago...

**Comment by potatoqualitee** [comment]
This ha been fixed 👍 Thank you @ijeb  
![image](https://user-images.githubusercontent.com/8278033/48529372-0e25e080-e893-11e8-94d7-d893824a1029.png)
