### ISSUE TITLE
Get-DbaDefaultPath return an error

### ISSUE THREAD

**Issue by pollusb** [sqlcollaborative/dbatools#3494]
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [ ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Win 7 enterprise
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version):

## Steps to Reproduce

I run Get-DbaDefaultPath (0.9.318) on a SQL 2000 instance. It reports multiple errors.
It was working fine with (0.9.208) on the same instance.
here's the errors produced by the command 
```
Get-DbaDefaultPath -SqlInstance SERVER1 2> error.txt
ComputerName : SERVER1
InstanceName : MSSQLSERVER
SqlInstance  : SERVER1
Data         :
Log          :
Backup       : g:\MSSQL\BACKUP
ErrorLog     : g:\MSSQL\log
```

[error.txt](https://github.com/sqlcollaborative/dbatools/files/1885069/error.txt)

I found this in allcommands.ps1:24746

`$server.Query("SELECT *, SUSER_NAME(owner_sid) AS [Owner] FROM sys.databases")`

I replaced it with

`$server.Query("SELECT *, SUSER_NAME(sid) AS [Owner] FROM sysdatabases")`

and tested it with success both on SQL2000 and SQL2016. I don't have time right now to submit a pull-request. So I just reporting the bug and the solution hoping for someone to take over.
Thanks.

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by pollusb** [comment]
I just tested this and it's working as of 0.9.380. I think we can close this now

**Comment by potatoqualitee** [comment]
ty!
