### ISSUE TITLE
Set-DbaTcpPort should not try to connect to SQL Server instance

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#3496]
Scenario...next next install of SQL Server...SSCM has never been opened or touched. I want to set the TCP Port on the instance that I installed.
![image](https://user-images.githubusercontent.com/11204251/38450688-f8e101aa-39e7-11e8-9a6b-0f1612174c12.png)

The default for SQL Server 2012+ is to have TCPIP protocol enabled. The first thing this command does is try to connect to the instance, there is no reason to do that if all I am doing is setting the port.

Just some additional notes/observations (have not been able to verify):

```powershell
            if ($server.IsClustered) {
                Write-Message -Level Verbose -Message "Instance is clustered fetching nodes..."
                $clusternodes = (Get-DbaClusterNode -SqlInstance $server).ComputerName -join ", "

                Write-Message -Level Output -Message "$instance is a clustered instance, portchanges will be reflected on all nodes ($clusternodes) after a failover"
            }
```

Given that section of code and statement, it would lead you to believe it will update the port on all nodes of the FCI. However, I do not see code that shows it does.

**Comment by potatoqualitee** [comment]
This has been removed 👍
