### ISSUE TITLE
Backup-DBADatabase Fails to backup to URL with BackupFileName parameter specified

### ISSUE THREAD

**Issue by johnmart82** [sqlcollaborative/dbatools#3497]
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): See attached ComputerInfoOutput.txt file
 - PowerShell Version: 5.1.14393.1944
 - SQL Server (Edition|Version): Microsoft SQL Server 2017 (RTM-CU3-GDR) (KB4052987) - 14.0.3015.40 (X64)   Dec 22 2017 16:13:22   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

## Steps to Reproduce

 - [x] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)

Attached screenshot of PowerShell window that has log entries, backup command and verbose output.
![image](https://user-images.githubusercontent.com/32261850/38459181-a59e9056-3a74-11e8-82da-bde623c706a5.png)

Issue Backup-DBADatabase command that backs up to URL and uses the BackupFileName parameter, example as follows;

Backup-DbaDatabase -SqlInstance winsql-0 -AzureBaseUrl https://<StorageAccountName>.blob.core.windows.net/databasebackups/ -Type Full -Database SalesArchive -BackupFileName salesarchivebackup.bak -Verbose

This results in the following error being reported;
WARNING: [Backup-DbaDatabase][18:59:56] SQL Server cannot write to the location https:\\<StorageAccountName>.blob.core.windows.net\databasebackups

The backup does not take place.

### Problem to solve
Allow database backup file name to be specified when backing up to URL.

### Additional information
[ComputerInfoOutput.txt](https://github.com/sqlcollaborative/dbatools/files/1886642/ComputerInfoOutput.txt)

**Comment by potatoqualitee** [comment]
Ty John!

**Comment by Stuart-Moore** [comment]
Afternoon,
You need to provide the AzureCredential parameter. That's the name of the SQL Credential needed for the connection. 

The underlying SMO only supports the older style BACKUP TO URL style azure backups - https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url

**Comment by Stuart-Moore** [comment]
Hi John, did the credential bit above help out?

**Comment by Stuart-Moore** [comment]
Closing as guessing that fixed it
