### ISSUE TITLE
Remove-DbaDatabaseSafely - lost database trying to remove it `safely`

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#3500]
## Bug Report
Call function `Remove-DbaDatabaseSafely -SqlInstance SRV1 -Database DB1 -BackupFolder \\srv-backup\sql_backup\ -NoDbccCheckDb`:

Lost database.

### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [ ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10 1709
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 2008 R2

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/14327077/38486439-b8df10ec-3be5-11e8-988b-29ebc2abe834.png)

### Some additional information
`Remove-DbaDatabaseSafely` had a parameter `-BackupFolder` which is not in naming consistence with `Backup-DbaDatabase` `-BackupDirectory`

**Comment by potatoqualitee** [comment]
ill look into this asap
