### ISSUE TITLE
Get-DBABackupHistory is not correct in all cases.

### ISSUE THREAD

**Issue by artyq** [sqlcollaborative/dbatools#3504]
## Bug Report

Get-DBABackupHistory is not providing the correct information in all cases.  I believe this is due to the order by in the SQL code, which focuses on the LastLSN first, and not the last backup date.

## Steps to Reproduce

In this case, I believe the issue is occurring due to our clients requesting a copy of a prod database be restored over top of a dev database, which would have different lsn values.

You will see in my results below that it shows the last Full and Diff were in 2016, but this isn't the case

PS F:\> Get-DBABackupHistory -SQLInstance ‘MyServer’ -Database MyDB -Last

SqlInstance Database   Type         TotalSize DeviceType Start                   Duration End                    
----------- --------   ----         --------- ---------- -----                   -------- ---                    
MyServer 	MyDB 	Full        	 507.92 MB 	Disk       2016-04-17 18:55:32.000 00:00:32 2016-04-17 18:56:04.000
MyServer 	MyDB 	Differential 	24.54 MB 	 Disk       2016-04-20 18:30:11.000 00:00:04 2016-04-20 18:30:15.000 

### Problem to solve
I have some results when I modify the query to have backup_finish_date the priority.
Existing Code:

ORDER BY backupset.last_lsn   desc, backupset.backup_finish_date DESC |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BackupSetRank | Server | Database | Username | Start | End | Duration | Path | Type | MediaSetId | BackupSetID | Software | position | first_lsn | database_backup_lsn | checkpoint_lsn | last_lsn | FirstLSN | DatabaseBackupLsn | CheckpointLsn | Lastlsn | software_major_version | DeviceType | is_copy_only | last_recovery_fork_guid
1 | Contoso | MyDB | Username | 2016-04-20 18:30:11.000 | 2016-04-20 18:30:15.000 | 4 | D:\MyDB\backup_2016_04_20_183004_8088348.bak | Differential | 65674 | 65678 | Microsoft SQL Server | 1 | 58877000002311100213 | 58864000001734200038 | 58877000002311100213 | 58877000002319900001 | 58877000002311100213 | 58864000001734200038 | 58877000002311100213 | 58877000002319900001 | 11 | Disk | 0 | 82A65771-D5EB-493A-931C-B81F8D29BAD7
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

Modified (Shows my full from last night):

ORDER BY   backupset.backup_finish_date DESC,    backupset.last_lsn desc |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BackupSetRank | Server | Database | Username | Start | End | Duration | Path | Type | MediaSetId | BackupSetID | Software | position | first_lsn | database_backup_lsn | checkpoint_lsn | last_lsn | FirstLSN | DatabaseBackupLsn | CheckpointLsn | Lastlsn | software_major_version | DeviceType | is_copy_only | last_recovery_fork_guid
1 | Contoso | MyDB | Username | 2018-04-08 22:28:21.000 | 2018-04-08 22:37:43.000 | 562 | D:\MyDB\ISTD_PTBPV_2018-04-08_222821.bak | Full | 209688 | 209693 | Microsoft SQL Server | 1 | 30614000007510900045 | 30613000004377000044 | 30614000007510900045 | 30614000007513400001 | 30614000007510900045 | 30613000004377000044 | 30614000007510900045 | 30614000007513400001 | 11 | Disk | 0 | 38E0CECC-FD63-4360-B19B-06A1F28A1A12

**Comment by artyq** [comment]
You are correct, I was using 0.9.0301. I just tried 0.9.322 and it is
displaying the correct value.

However, I am noticing another problem now.  Same syntax, but now I get a
conversion error.

Exception setting "TotalSize": "Cannot convert value "31046341632" to type
"Sqlcollaborative.Dbatools.Utility.Size". Error: "Value was either too
large or too small for an Int32.""

At D:\dbatools\allcommands.ps1:22600 char:21

+ ...                    $historyObject.TotalSize = $commonFields.TotalSize

+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [],
SetValueInvocationException

    + FullyQualifiedErrorId : ExceptionWhenSetting



Exception setting "CompressedBackupSize": "Cannot convert value
"3314050728" to type "Sqlcollaborative.Dbatools.Utility.Size". Error:
"Value was either too large or too small for an Int32.""

At D:\dbatools\allcommands.ps1:22601 char:21

+ ...             $historyObject.CompressedBackupSize = $compressedBackupSi
...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [],
SetValueInvocationException

    + FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by brunobbc** [comment]
hi everyone, 
Do we have a workaround for this problem or this will be solved in the next release? 
thanks,
Bruno

**Comment by niphlod** [comment]
no workaround, surely will be fixed shortly and released within the next release

**Comment by potatoqualitee** [comment]
ping @FriedrichWeinmann and @zippy1981 - moving it here. backups are failing from Copy-DbaDatabase/Start-DbaMigration if you guys can help

**Comment by potatoqualitee** [comment]
Thanks so much for the bug report. We've fixed it in 0.9.325 and have added a regression test to ensure it does not happen again.
