### ISSUE TITLE
Read-DbaBackupHeader errors with invalid input

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3510]
Guessing it's invalid ;) It's not a fully qualified path. Was testing Read-DbaBackupHeader on Win 7 and got this error. Strangely enough, the error is different on Win10.

![image](https://user-images.githubusercontent.com/8278033/38552304-08fca248-3cbc-11e8-9482-12312f5a6754.png)

![image](https://user-images.githubusercontent.com/8278033/38552364-327c00be-3cbc-11e8-9162-7920f71bc45f.png)

**Comment by Zhunya** [comment]
RDBH need `Files` list, not plain `Path` =) I had same errors today

**Comment by potatoqualitee** [comment]
hmm if two of us did, should we Alias Files to path and make it auto detect Directory or File(s)?

**Comment by Zhunya** [comment]
Agree, and we need to write new `Test-DbaSqlPath2` which will return pscustomobject with all `xp_fileexists` properties.

**Comment by nvarscar** [comment]
I had to sacrifice one or two error handling blocks bc they were moved to the runspace execution, which has no knowledge of Write-Message/Stop-Function. I'll take a look why it's throwing on Win7 though.
PS now that I think of it, I could probably create a custom error object in the script block and do try/catch/throw inside of the block itself rather than raising a generic error returned from the SMO. I'll try to make that happen today 🦑

**Comment by niphlod** [comment]
I wouldn't go adding a new function that does what test-dbasqlpath exists. just add properties to it

**Comment by niphlod** [comment]
also, that's why we have get-dbabackupinformation. Read-DbaBackupHeader is quasi-internal.

**Comment by niphlod** [comment]
annnnd, we have get-dbafile already for listing dirs on remote servers

**Comment by nvarscar** [comment]
> also, that's why we have get-dbabackupinformation. Read-DbaBackupHeader is quasi-internal.

Yes, that's exactly the case - the recursive folder structure is being processed in GDBI, which is afterwards passed into RDBH as an array of files. However, xp_fileexist returns whether the path is a folder or not, which means that definitely can be included into the output object of test-dbasqlpath. The problem with this approach is that the function returns $true/$false if it only got one single object and all other functions are expecting that behavior. If we were to include IsFolder to the output, all other commands would have to be rewritten to use a (test-dbasqlpath).FileExists instead of just the function itself, which means at least 50 changes in the code

**Comment by Zhunya** [comment]
Time to draw a decision tree with all public functions we have for backup and restore.

**Comment by Zhunya** [comment]
>I wouldn't go adding a new function that does what test-dbasqlpath does already. just add properties to it

It's why I propose to write one more function, because current version return object only when more than one instance specified in input parameter.

**Comment by niphlod** [comment]
@Zhunya : there's already a decision tree. 
At most, param names are not that smart (goes along with an old tune of "parameter name standardization"). 
Maybe Read-DbaBackupHeader's `-Path` should be `-FilePath` to be just more obvious.

@nvarscar : lemme think about that, I may have an easy fix.

**Comment by niphlod** [comment]
BTW: even with the fix, we may not want to do checks within Read-DbaBackupHeader adding yet another roundtrip for each path passed in (worse if they use correct Get-DbaBackupInformation, which checks already) ...
Can we just abort in read-dbabackupheader if the passed path has not a dot in it ? 
It'd leave the "bug" opened only for people not reading the help AND do extensionless backups, which IMHO would be perfect.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/pull/3513 for the fix, which I still think shouldn't be applied in Read-DbaBackupHeader.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/pull/3515/files#diff-8cb9cb4d52b7c9512d3a187299a9b9f6R201 for an easy validation to slip in for sanity check

**Comment by Zhunya** [comment]
@niphlod THANK YOU!

**Comment by niphlod** [comment]
@potatoqualitee : would you give https://github.com/sqlcollaborative/dbatools/pull/3541 a try ? As for the win7 error, I don't have it handy. 
I would assume it's either PS3 not so forgiving with null values or whatnot but now that that piece is executed only if a proper file can be read, we should be safe to go

**Comment by nvarscar** [comment]
@niphlod : Will this affect non-Ola backup solutions? I'm trying to comprehend how many of users out there never use file extensions (especially Linux). This could potentially break the functionality for them, could it?

PS I'll be back next week from the vacation, hopefully will jump on top of it right away.

**Comment by niphlod** [comment]
read-dbabackupheader wants a file, not a path. if you want to read all files within a path, there's get-dbabackupinformation.

**Comment by nvarscar** [comment]
I'm taking strictly about files that don't have extensions, not folders.

**Comment by niphlod** [comment]
yup. The deal is chicken-and-egg problem. PS is slow, SMO too. Restore is already slow (for various reasons) and I'm not planning to introduce yet another slowdown.

Read-DbaBackupHeader is 99% percent of time not used directly, but via Get-DbaBackupInformation. 
Given for months nobody complained, I'm assuming 99,99% of users have backups with extensions

We cannot check both in Get-DbaBackupInformation AND in Read-DbaBackupHeader if a "string" is a file or a folder, so we just impose a sane default. 
At most we can add yet another parameter to Read-DbaBackupHeader ala `TrustPath` that plainly skips the check (i.e. to be used in functions that do their own validation before passing things to Read-DbaBackupHeader). IMHO the whole machinery to make it "safe always" is wasted if the only cornercase is extensionless backups.
