### ISSUE TITLE
Enable errors from Restore-DbaDatabase and Backup-DbaDatabase to be easily surfaced

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#3511]
### General Troubleshooting steps

- [X ] Verified running the latest release of dbatools?
- [ X] Verified errors are not related to permissions?
- [X ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System Win 10
 - PowerShell Version: Version          : 5.1.14409.1012
 - SQL Server 2016\17 EE

## Feature Request

I am using Restore-DbaDatabase within an automated process handled by the build server and I am struggling to surface restore errors. Sometimes the restore fails. Now that might be because of network, disk space, poor coding to get the file names or Orcs and Goblins playing with my 1's and 0's but I would like to know.

I know I can investigate the $error variable to find the exception and I know that I can look in Get-DbaToolslog but neither of these help me when this is run by a service account as dbatoolslog is session based and the error is tricky to locate 

Currently I have a little success with 

     $File | Restore-DbaDatabase -SqlInstance $Instance -ReuseSourceFolderStructure -IgnoreLogBackup -WithReplace -EnableException -AllowContinue 
     
     # Check dbatools log for errors
     $dbatoolsLog = Get-DbatoolsLog | Select-Object * -Last 30
     if ($dbatoolsLog.Where{$_.FunctionName -in @('Restore-DbaDatabase', 'Get-DbaBackupInformation', 'Invoke-DbaAdvancedRestore') -and $_.Level -eq 'Warning' }) {
         # Get the inner inner inner exception as this is where the real message usually sometimes maybe lies (thanks Microsoft)
         $msg = (Get-DbatoolsLog -Errors).Exceptions.InnerException.InnerException.InnerException.Message
         call to logging function $msg
         $pscmdlet.WriteVerbose($msg)
     
         ($dbatoolsLog.Where{$_.FunctionName -in @('Restore-DbaDatabase', 'Get-DbaBackupInformation', 'Invoke-DbaAdvancedRestore') -and $_.Type -ne 'Debug' }).ForEach{
             $msg = "Time - $($_.TimeStamp) ; Function = $($_.FunctionName) ; Message = $($_.Message)"
             call to logging function $msg
         $pscmdlet.WriteVerbose($msg)
         }
         call to logging function "Failed Restoring database $($Psitem.Name) onto $SQLInstance - See above entries" -DBAStackMessageType ERROR
         call to catchblock logging function which gets pscallstack -ErrorRecord $_
         Return 
     }
     else {
         $msg = "Successfully restored the database $($Psitem.Name) on $Instance"
         call to logging function $msg
         $pscmdlet.WriteVerbose($msg)
     }

with the same code in the catch block that surrounds this but this is not alwasy giving me what I want sometimes only  An exception occurred while executing a Transact-SQL statement or batch as seen in the below results from logging

> 
10/04/2018 13:46:07    1976 Failed Restoring database DBNAME onto INSTANCENAME - See above entries
10/04/2018 13:46:07    1976 An exception occurred while executing a Transact-SQL statement or batch.
10/04/2018 13:46:07    1976 Time - 04/10/2018 12:57:13 ; Function = Restore-DbaDatabase ; Message = DBNAME passed testing
10/04/2018 13:46:08    1976 Time - 04/10/2018 12:57:13 ; Function = Restore-DbaDatabase ; Message = Passing in to restore
10/04/2018 13:46:08    1976 Time - 04/10/2018 12:57:13 ; Function = Invoke-DbaAdvancedRestore ; Message = Performing restore action
10/04/2018 13:46:08    1976 Time - 04/10/2018 13:46:02 ; Function = Invoke-DbaAdvancedRestore ; Message = Failed, Closing Server connection
10/04/2018 13:46:09    1976 Time - 04/10/2018 13:46:02 ; Function = Invoke-DbaAdvancedRestore ; Message = Failed to restore DBNAME, stopping
10/04/2018 13:46:09    1976 Time - 04/10/2018 13:46:03 ; Function = Invoke-DbaAdvancedRestore ; Message = Succeeded, Closing Server connection

Is it possible to make this error easier to locate programattically or if there are better ways of getting this info programmatically please feel free to suggest

**Comment by SQLDBAWithABeard** [comment]
`Start-Job -Name Restore -ScriptBlock {Restore-DbaDatabase -SqlInstance INSTANCE -Path PATHTOBACKUP -DatabaseName Test} 
While ((Get-Job Restore).State -ne 'Completed'){
    Start-Sleep -Seconds 15
    $progress = (Get-job Restore).ChildJobs.progress[-1]
    Write-Output "Restore Job is currently performing $($Progress.Activity) and is $($Progress.StatusDescription)"
    Start-Sleep -Seconds 15
}
Write-Output "Restore Job has completed"
$job = Get-Job Restore -IncludeChildJob
if($job.Error){
    $msg = $job.Error | Out-String
Write-Output "The Restore Job completed with errors - $msg"
}
if($job.Warning){
    $msg = $job.Warning | Out-String
    Write-Output "The Restore Job completed with warnings which probably means the restore failed"
    Write-Output "$msg"
}
Get-Job Restore | Remove-Job`

Another attempt

**Comment by beargle** [comment]
Would it be a safe bet to call [Exception.GetBaseException()](https://msdn.microsoft.com/en-us/library/system.exception.getbaseexception.aspx) in setting `$ExitError`?

For example, with 0.9.325 if we've captured output of `Restore-DbaDatabase` call that failed because of insufficient space:

```PowerShell
PS> $Result = Restore-DbaDatabase ...

PS> $Result.ExitError
Restore failed for Server 'ServerInstance'.

PS> $Result.ExitError.GetBaseException()
System.Data.SqlClient.SqlError: There is insufficient free space on disk volume 'D:\' to create the database. The database requires 68719476736 additional free bytes, while only 34530353152 bytes are available.
```
This should always return the lowest level (i.e. most meaningful) SMO exception; haven't tested many other cases though.

**Comment by potatoqualitee** [comment]
beard, we made the errors much more informative. please let me know if this does not solve your needs.
