### ISSUE TITLE
Invoke-DbaDbShrink - add incremental shrink for VLDBs

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#3516]
### Problem to solve
Database shrinkage has to occur at times. I'm involved in a client project now that we are going to be NULL'n out an NTEXT column of a log table that exist in 1400+ databases on a single instance. Some databases are medium size, in MB range, while others are well into GB range. Overall total space recovered from this is estimated to be close to a TB.

Now shrinking a file that is only 100GB down to 10% free space is not a big deal, as long as the IO can keep up. However when I get to a data file that is 800GB+ a single shrink operation will take forever since the DBCC operation is single-threaded.

I came across this tip on actually looping through and incrementally shrinking a given file. So proposal is to implement a parameter, say `SizeIncrement` maybe, that will have the shrink operation utilize until it reaches the final size/percentage desired.

### Additional information

MSSQLTip: https://www.mssqltips.com/sqlservertip/3178/incrementally-shrinking-a-large-sql-server-data-file-using-powershell

**Comment by niphlod** [comment]
SizeDecrement ?!  ..... mwhahaha, parameter names are really the hardest thing out there

**Comment by wsmelton** [comment]
It was middle of the night for me when I posted...just what hit me at the time 😁 

I like `StepMB` or `StepSizeMB`, will need to tie it to a unit size.

**Comment by wsmelton** [comment]
What was wrong with the previous implementation?
