### ISSUE TITLE
Emailed: int32 issue with Backup-DbaDatabase

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3517]
"Backup Failed:  Exception setting ""TotalSize"": ""Cannot convert value ""70735508480"" to type ""Sqlcollaborative.Dbatools.Utility.Size"". Error: ""Value was either too large or too small for an Int32.""""","Debug, Warning","4/10/2018 2:26:38 PM","Backup-DbaDatabase","Warning","34450471-65a8-486a-a04b-97837c08d702",

I have no idea if it's good/okay to switch it to decimal or int64 - so tagged the C# fellas and Stuart who also seems to know C# ;)

**Comment by niphlod** [comment]
There's another one logged, hopefully the guys will raise the prio on this
one ;-)

Il mer 11 apr 2018, 10:21 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
ah ha, thank you! will close and ping there

**Comment by wsmelton** [comment]
I would guess that is tied to reworking the DbaSize type?

**Comment by MCTSQL** [comment]
just wanna say, yeah, this is a biggie; any ETA?

WARNING: [Backup-DbaDatabase][08:10:52] Backup Failed:  Exception setting "TotalSize": "Cannot convert value "42669780992" to type "Sqlcollaborative.Dbatools.Utility.Size". Error: "Value was
 either too large or too small for an Int32.""

**Comment by potatoqualitee** [comment]
agreed, @MCTSQL - trying to get it resolved. Hopefully within 24 hours.

**Comment by Stuart-Moore** [comment]
just pushed up https://github.com/sqlcollaborative/dbatools/tree/backupsize

This IS NOT 100% ready for release (mainly because Fred will have kittens if I don't tidy it up) but it's passing AppVeyor

But I can tidy it up if someone can confirm it fixes their size issue. Remember it's not 100% yet, so please use CopyOnly so nothing else get's broken.

will be back online in about an hour (19:00 UK time)

**Comment by potatoqualitee** [comment]
oh  man, that is so much more thorough than my crappy attempts. thank you. @FriedrichWeinmann - let us know and good luck on your presentation!

**Comment by potatoqualitee** [comment]
@MCTSQL - this has been resolved in 0.9.325 and have added a regression test to ensure it does not happen again.
