### ISSUE TITLE
Error during Restore-DBADatabase

### ISSUE THREAD

**Issue by artyq** [sqlcollaborative/dbatools#3518]
[Error.txt](https://github.com/sqlcollaborative/dbatools/files/1899430/Error.txt)

### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 2016 SP1 CU8

### Problem to solve

     Error restoring 20180410XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     String or binary data would be truncated.
     The statement has been terminated.
     At D:\SHS_PowershellScripts\dbatools-master\allcommands.ps1:51000 char:21
     +                     [void]$da.fill($ds)
     +                     ~~~~~~~~~~~~~~~~~~~
         + CategoryInfo          : NotSpecified: (:) [], SqlException
         + FullyQualifiedErrorId : SqlException

### Additional information

Error.txt attached.

**Comment by potatoqualitee** [comment]
thanks for letting us know @artyq . to confirm, your database name is 58 characters?

**Comment by artyq** [comment]
Crazy right?  It is actually 77 characters all together. I believe SQL Server supports 128?
About 15 of these characters come from me, as I prefix the server name and date to the db name for each restore. 
These backups are restored to another server to verify backups are working and to offload checkdb from our clients servers.
After the task is done it drops the database.

**Comment by Stuart-Moore** [comment]
That's in Invoke-SqlCmd2

Just been playing on our test sql2016 with database abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789abcdefghijklmnopqrstuvwxyz and can't repo.

@artyq would it be possible to get the whole command (anonymised is fine) you were running?

**Comment by artyq** [comment]
try
           {
             Write-Host "Restoring $Database"
             Restore-DbaDatabase -SqlInstance $MasterInstance -RestoredDatababaseNamePrefix "$Date$Instance" -Path "\\$MasterInstance\SQLBackups\Check" -ErrorAction Stop -WarningAction Stop
             #If succesful it will place an entry into the log
             Invoke-Sqlcmd2 -ServerInstance $MasterInstance -Query "
     IF EXISTS (
	     	SELECT TOP 1 *
		FROM [Restore_CheckDB].[dbo].[Log]
		WHERE ServerName = '$Instance'
			AND DatabaseName = '$Database'
		)
	UPDATE [Restore_CheckDB].[dbo].[Log]
	SET LastCheck = GetDate()
		,Restore_Status = 'Success'
		,CheckDB_Status = NULL
	WHERE ServerName = '$Instance'
		AND DatabaseName = '$Database'
     ELSE
	INSERT INTO [Restore_CheckDB].[dbo].[Log]
	VALUES (
		'$Instance'
		,'$Database'
		,GETDATE()
		,'Success'
		,NULL
		)
      "
      }

**Comment by potatoqualitee** [comment]
oh sweet, that should be easy. the issue doesn't appear to be with dbatools but with your table `[Restore_CheckDB].[dbo].[Log]` needs to have a larger datatype.

**Comment by artyq** [comment]
I see that now. :(

I feel bad for having you guys investigate something and it was on my end.

Sorry.

Arthur

**Comment by potatoqualitee** [comment]
no problem, thanks to @Stuart-Moore for asking the right questions ;)
