### ISSUE TITLE
New firewall rules command

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#3519]
I've completed the primary logic for the firewall rules command I've been working on since last December 2017. I've created this issue to start a tracked discussion on it.

I need a little help getting this prepared for my "first" PR (I use "first" in quotes because this code isn't spoon fed to me this time ;) ref: https://github.com/sqlcollaborative/dbatools/pull/2695 and I'm not sure I count that).

The code imports the `NetSecurity` module and adds new firewall rules to the `Windows Firewall with Advanced Security` application, as well as setting the Display Group for all of these newly created rules to "SQL" Group (by default) for easier management later.

Given the above, what should this new firewall command be named (not sure if it should be Add, Set, New)? I'm thinking options could be like:
Add-DbaFirewallRules
New-DbaFirewallRules
Set-DbaFirewallRules
something else?

**Comment by potatoqualitee** [comment]
Woo! alright so, all first, netsecurity is only available in Windows 8+ and Windows 2012+. generally, we try to avoid things that aren't available in windows 7. but then you'd have to use `netsh` which is less powershelly so with this set of commands, that will work. Just no need to manually import netsecurity - it will be auto imported.

You will also have to check for the OS version. You can see similar code in Watch-DbaUpdate

`if (([Environment]::OSVersion).Version.Major -lt xyz) {`

Also, command names must be singular, so you'd wanna do `Add-DbaFirewallRule` - I'd go with Add, Remove and Get 👍

**Comment by wsuhoey** [comment]
😭 I didn't even think about `Remove` or `Get` versions of the command...
Due to the NetSecurity module dependency, does that mean we can't use it for backward compatibility reasons? I don't know if I can (mentally) handle writing `netsh` equivalents; this was exhausting enough! 😨

**Comment by wsuhoey** [comment]
What about `New-DbaFirewallRule` as opposed to `Add-DbaFirewallRule`. I noticed there are only 2 `Add` commands.

Also, is having the `Remove` and `Get` commands (to "complete the set" so to speak) required to be accepted as a new command?

Would I use `if (([Environment]::OSVersion).Version.Major -lt 6` since Server 2012 R2 returns 6?

**Comment by potatoqualitee** [comment]
the issue with netsh is that it'd require text parsing which is nastier than making the whole commands less powershelly for a small subset of ppl. then if we do support win7 ,we'd have to make it match the output of the other commands.

**Comment by wsmelton** [comment]
Well considering that the `NetSecurity` does not support PowerShell remoting I don't think backward support is going to be a big issue. It is not having to support Windows 7 anyway it would be more to Window Server versions. Which that module is only available on Window Server 2012 and up...that is a lot of machines to not support but Window Server 2008 R2 goes out of support in 2020.

**Comment by wsuhoey** [comment]
I'm *very* close I think. I'm currently experiencing an issue with using `$ssispath = (Get-DbaSqlService -ComputerName $ComputerName -Type SSIS).BinaryPath`. My particular dev machine here has 3 instances of SSIS installed. As a result, `$ssispath` returns 3 items, and becomes an Object System.Array 
```[04/17/2018 11:03 AM] PS C:\WINDOWS\system32> (Get-DbaSqlService -ComputerName $ComputerName -Type SSIS).BinaryPath``` returns:
```"C:\Program Files\Microsoft SQL Server\100\DTS\Binn\MsDtsSrvr.exe"
"C:\Program Files\Microsoft SQL Server\120\DTS\Binn\MsDtsSrvr.exe"
"C:\Program Files\Microsoft SQL Server\140\DTS\Binn\MsDtsSrvr.exe"```
So down the line when I call my new `Invoke-NewFirewallRule` function, which just uses `New-NetFirewallRule` from `NetSecurity` module, it fails when it gets to the part where it is passed the path array but expects a string (single value) for `-Program` parameter.

Any ideas? I assume all ya'll need to see the full code... so where would the proper place to put that? I don't think it's PR ready yet; need this multi SSIS instance issue solved first.

**Comment by wsmelton** [comment]
@wsuhoey you can just provide a link to the branch on your fork for letting folks review code, just have to publish it to your GitHub repository.

In reference to the collection/array issue, I think that will fall under usage, documentation and or the functionality you want it to have. If the commands in NetSecurity module do not accept multiple values as inputs it would be either only allowing one value to be passed into your Invoke command, or your Invoke command handling multiple values.

So it is either

```powershell
$ssispath = (Get-DbaSqlService -ComputerName $ComputerName -Type SSIS).BinaryPath
$ssispath | foreach {Invoke-NewFirewallRule ...}

#OR

$ssispath = (Get-DbaSqlService -ComputerName $ComputerName -Type SSIS).BinaryPath
$ssispath | Invoke-NewFirewallRule

#same as: Invoke-NewFirewallRule -SomeParameter $ssispath
```

The later example means that the Invoke command processes each value passed in, say looping over those objects and calling New-NetFirewallRule for each...if that is how it needs to be done. 

I would also enforce rules around how the NetSecurity module commands function. In this case, if you cannot create one rule for multiple versions of the same executable (meaning you have 3 versions of SSIS installed, it requires 3 rules) I would not allow multiple to be passed in.

**Comment by wsuhoey** [comment]
Here's what I got:
Please see the # KNOWN ISSUE comment sections.
https://github.com/wsuhoey/dbatools/blob/development/functions/New-DbaFirewallRule.ps1

**Comment by wsuhoey** [comment]
Has anyone taken a look yet?

**Comment by wsuhoey** [comment]
I hope to have this done soon, perhaps in November after I finish my migration (using dbatools of course).

**Comment by potatoqualitee** [comment]
I really like what you've got so far and would like to include this command in 1.0 which I'm hoping will release on Feb 14 ♥ Check out this post for v3/win7

https://blogs.msdn.microsoft.com/tomholl/2010/11/07/adding-a-windows-firewall-rule-using-powershell/

You can add the base functions to the `being {}` section and add them in `process {}` !

**Comment by potatoqualitee** [comment]
code is currently in the `fw` branch https://github.com/sqlcollaborative/dbatools/tree/fw

**Comment by potatoqualitee** [comment]
i wont get to this in time for 1.0 :(

**Comment by wsuhoey** [comment]
Is backwards compat a requirement for 1.0?

**Comment by wsmelton** [comment]
No @wsuhoey these will only be using the built-in cmdlets for Window 8/2012 and up.

I've linked the draft PR that @potatoqualitee started if you want to continue from there.

**Comment by andreasjordan** [comment]
Hi @wsuhoey : Do you remember this? Would you like to work on this again?

**Comment by wsuhoey** [comment]
Hi Andreas. I still haven't had an opportunity to re-visit this. If you want to take it over feel free to do so. Hopefully the code I have thus far works for you.

**Comment by andreasjordan** [comment]
Don't know if I find time. Just had a walk through all issues and pinged some people. Maybe I start with just the firewall rules for engine, dac and browser.
