### ISSUE TITLE
Copy-SqlDatabase issue with 60GB database backup

### ISSUE THREAD

**Issue by sqldba-today** [sqlcollaborative/dbatools#3520]
### General Troubleshooting steps

- [x ] Verified running the latest release of dbatools?
- [x ] Verified errors are not related to permissions?
- [x ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): 
Windows 10 Enterprise 
 - PowerShell Version: 
PS C:\Users\jfay> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - SQL Server (Edition|Version): 
Source - SQL 2008 R2 SP3 Standard
Dest - SQL 2014 SP2 Standard
## Steps to Reproduce
Copy-SqlDatabase executed with a Source instance, a Destination instance, the BackupRestore option, A list of databases, and a NetworkShare.

My particular case was 9 databases and one failed.  The warning pasted below was the output and the file size of the three backup files match the value shown "61145549824".  The other 8 databases were under 1GB in size and worked perfectly.

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ x] Attach output from PowerShell console (if possible/allowed)
WARNING: [Backup-DbaDatabase][10:20:07] Backup Failed:  Exception setting "TotalSize": "Cannot convert value "61145549824" to type "Sqlcollaborative.Dbatools.Utility.Size". Error: "Value was either too large or too
small for an Int32.""
WARNING: [Restore-DbaDatabase][10:20:09] No backups passed through.
 This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other issue

**Comment by potatoqualitee** [comment]
Thanks so much, we are working this at the moment and hope to have a resolution ASAP
