### ISSUE TITLE
Copy-DbaCredential Maximum number of Dedicated Administrator Connections Exceeded

### ISSUE THREAD

**Issue by fvanderhaegen** [sqlcollaborative/dbatools#3522]
### Version Information
 - Operating System (Name|Version): Windows 2012 R2
 - PowerShell Version: 4.0
 - SQL Server (Edition|Version): Sql Server 2016 Enterprise SP1 CU7

## Steps to Reproduce
Everytime I execute `Copy-DbaCredential -Source 'sqltest-1' -Destination 'sqltest-2'` I get the following error in de SQL Server errorlog on the source:

> Could not connect because the maximum number of '1' dedicated administrator connections already exists. Before a new connection can be made, the existing dedicated administrator connection must be dropped, either by logging off or ending the process. [CLIENT: 127.0.0.1]

It's just like the cmdlet want to make a new connection without closing the previous one.

**Comment by fvanderhaegen** [comment]
I managed to solve the problem by adjusting allcommands.ps1 and to make sure the DAC was made by IP address and not made by dns name.

**Comment by MyKarpenko** [comment]
Getting the same error if i run Copy-DbaAgentJob -Source "xxx" -Destination "yyy"   -WhatIf
from an external server. If i run locally there is no warning

**Comment by VitalicJJ** [comment]
Also getting same error when SQL job runs [Sync-SqlInstanceObjects.ps1](https://www.sqlshack.com/synchronizing-sql-server-instance-objects-availability-group/) to synch objects between nodes in AG..
