### ISSUE TITLE
RFC: Password related C# code as a separate DLL.

### ISSUE THREAD

**Issue by zippy1981** [sqlcollaborative/dbatools#3527]
The rebirth of #1321.

## Background 

I wrote [a bunch of C# code that could create and verify SQL password hashes](https://github.com/zippy1981/dbatools/commits/new-csharp/PasswordHashinf). It all worked beautifully. It was all unit tested. **However . . .** it depended on newer versions of .NET than what the powershell DLL gets compiled to currently, and we are stuck with that version for reasons.

### Make a separate DLL and include in the project
1. I move that code to its own git repo, make a DLL
1. Give said DLL a @potatoqualitee approved OSS license.
1. Include the compile dll in the bin folder
1. Write the cmdlets that make it useful.

Unrelated things I'd do as well:
* Publish on NuGet
* Probablly add support for other password types and make the applicable beyond DbaTools

### Fix the systemic issues so my PR can be merged.

This is a hard problem at the moment. We basically wait procrastinate until we figure out how to solve it

### Make a new DbaSecurity powershell powershell module

New Module, new assumptions about system requirements. Focused purpose. We use plaster and stuff to do things "right" (or 2018 version of right) and don't try to make  it super compatiable. It will still support SQL 2000 password hashes though.

### other thing

This is where you tell me in the comments that you have a better idea.

**Comment by FriedrichWeinmann** [comment]
IT LIVEEESSSS!!!!!!!!! (again)

Kidding aside, I'd be fine with either proposed solution. Option one would require some careful dependency handling (mostly so it's clean and handled in a standardized way - maybe an internal `Test-Prerequisites -DotNet 4.6` call or something like that in the functions that use it).
