### ISSUE TITLE
Missing classifier function management for the Copy-DbaResourceGovernor command

### ISSUE THREAD

**Issue by suxstellino** [sqlcollaborative/dbatools#3528]
## Bug Report
When I migrate the resource governor settings the custom classifier function is not migrated too. The custom classifier function exists on the source server.
### Version Information
 - Operating System Windows Server 2012 R2 Standard
 - PowerShell Version: 4.0

| Name | Value |
|:--------|:-------|
| PSVersion | 4.0 |
| WSManStackVersion | 3.0 |
| SerializationVersion | 1.1.0.1 |
| CLRVersion | 4.0.30319.42000 |
| BuildVersion | 6.3.9600.18773 |
| PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0} |
| PSRemotingProtocolVersion | 2.2 |

 - SQL Server
**SOURCE**
Microsoft SQL Server 2014 (SP2-CU11) (KB4077063) - 12.0.5579.0 (X64) 
	Feb 21 2018 12:19:47 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )
**TARGET**
Microsoft SQL Server 2016 (SP1-GDR) (KB4057118) - 13.0.4210.6 (X64) 
	Dec 22 2017 15:00:27 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: )

## Steps to Reproduce
- Create a **custom classifier function** into the source server
- Execute the _Copy-DbaResourceGovernor_ command from the destination server with the following syntax:
`Copy-DbaResourceGovernor -Source SOURCESERVER -Destination TARGETSERVER`
- The cmdlet returns an error like this one: _"Exception calling 'Query' with '1' argument(s): 'Exception calling ExecuteWithResults with '1' argument(s): 'Execute with results failed for Database 'master'"_
- Printing the `$error[0]` will return the error about the missing classifier function

**Comment by wsmelton** [comment]
Right off (not having server with resource governor configured) I would take a stab that the custom objects classifier objects are out of scope for this command to handle.

The process used in all copy commands is that dependency objects are not taken into account and have to be dealt with external to a given copy command. (e.g. An Agent Job has a dependencies on a specific login for ownership, the copy job command does not go copy that login and then copy the job. It simply skips it.)

We also depend on SMO, so if the resource governor class within SMO is not aware of those custom objects we will have no way to accurately look them up regardless.

**Comment by suxstellino** [comment]
Thank you for explanation. 
And what about the [ClassifierFunction property](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.resourcegovernor.classifierfunction.aspx)?

**Comment by wsmelton** [comment]
If that will pull the full definition of the classifier function and all dependent custom objects created that will work and can be added.

**Comment by suxstellino** [comment]
I could use the `ClassifierFunction` property in order to get its definition and to create a `Dba-CopyResourceGovernorClassifierFunction` method to execute before the original one. What do you think about this?

**Comment by wsmelton** [comment]
It would be a Get command that returned the SMO object or custom objects if available. So `Get-DbaResourceGovernorClassiferFunction` would be the command, then the copy command would call that...if it simply scripting out that object to T-SQL script and running it on the source all of that code can just be put in RG copy command.

**Comment by suxstellino** [comment]
Can we convert this "bug report" into a new command tagged issue? I'd like to create the get command to put inside the RG copy or a dedicated copy command if better.

**Comment by niphlod** [comment]
sure, go ahead and create it (maybe put a reference to this issue)

**Comment by sqllensman** [comment]
This bug report was converted into request for new command. As the new command was created Issue 3548 can this now be closed?

**Comment by potatoqualitee** [comment]
yes indeed thank you, will close now

**Comment by potatoqualitee** [comment]
btw, renamed Get-DbaResourceGovernorClassiferFunction to Get-DbaRgClassiferFunction
