### ISSUE TITLE
Set-DbaDbCompression - bug when applying NONE compression

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#3532]
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5.1.14393.2125

## Steps to Reproduce
Running this does not set the compression levels of indexes to none:
`Set-DbaDbCompression -SqlInstance server1 -Database database1 -CompressionType none`

It works if you set the `CompressionType` to Row or Page, I captured the SQL being executed and when you set the DataCompression on the index to 'None' the SQL does not have the DATA_COMPRESSION option set.

You can easily reproduce this issue with the following code
```
$server = Connect-DbaInstance -SqlInstance server1
$table = $server.Databases['test'].Tables['table']
$index = $table.Indexes['CL_table']

$index.PhysicalPartitions[0].datacompression = 'Page'
$index.Rebuild()

$index.PhysicalPartitions[0].datacompression = 'Row'
$index.Rebuild()

$index.PhysicalPartitions[0].datacompression = 'None'
$index.Rebuild()
```

These are the SQL statements that were executed:
```
ALTER INDEX [CL_table] ON [dbo].[table] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
ALTER INDEX [CL_table] ON [dbo].[table] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, DATA_COMPRESSION = ROW)
ALTER INDEX [CL_table] ON [dbo].[table] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100)
```

I'm wondering if this is an issue with the SMO or if I need to handle it differently in the command.

**Comment by wsmelton** [comment]
Is NONE a valid value?

**Comment by jpomfret** [comment]
Yeah if i run the following in SSMS it works:

`ALTER INDEX [CL_table] ON [dbo].[table] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, DATA_COMPRESSION = NONE)`

**Comment by jpomfret** [comment]
This also works fine for Page and None on the table object, just not on indexes.

```
$table.PhysicalPartitions[0].DataCompression = 'page'
$table.Rebuild()

$table.PhysicalPartitions[0].DataCompression = 'none'
$table.Rebuild()
```

**Comment by jpomfret** [comment]
None is a valid option here:
https://technet.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.datacompressiontype(v=sql.105).aspx

**Comment by wsmelton** [comment]
That would actually be the old version of the docs, but None is still showing as listed.

https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.datacompressiontype.aspx

**Comment by jpomfret** [comment]
So would you agree it's a SMO bug? Is that something I should post on user voice as a suggestion? 

As far as for this command, thought on if it's None handling it for now with T-SQL?

**Comment by niphlod** [comment]
can't replicate here, 'None' works.

**Comment by jpomfret** [comment]
you confirmed the objects were actually set to none in the database? not just the results from `Set-DbaDbCompression`?

E.g. using this after?
`Get-DbaDbCompression -SqlInstance server -Database test | ogv`

**Comment by niphlod** [comment]
ah, I see, sorry for the report. it just does a rebuild with no specific data compression option, so it spends time but doing not what we'd like. Need to ping SMO guys about the bug

**Comment by jpomfret** [comment]
Yeah useful right :) haha.

Who do we ping about that? Do we have a SMO contact?

**Comment by jpomfret** [comment]
Bug posted here: https://feedback.azure.com/forums/908035-sql-server/suggestions/34080112-data-compression-smo-bug

**Comment by wsmelton** [comment]
I confirmed this is also a bug in SMO, not just the version of SMO we are running.

But do note that once they fix this @potatoqualitee we will have to update the SMO to the latest release. Some of the enumeration fixes they have done are not in our module because we are using the older version of SMO.

**Comment by wsmelton** [comment]
Well the fix from Microsoft will require that we update SMO in the module...so I would go ahead and just do the workaround...add reference to this issue within the code.
