### ISSUE TITLE
Copy-DbaAgentJob for AG nodes with slightly different job names

### ISSUE THREAD

**Issue by deeraroo** [sqlcollaborative/dbatools#3533]
### Problem to solve
I'm looking for a way to be able to apply something like:
Copy-DbaAgentJob -Destination $SecondaryServer -Source $PrimaryServer | Where-Object {$_.name -Like "ClusterName*"}

I have a two-node availability group cluster, and the naming convention of SQL Agent jobs in my organization requires the use of the Cluster Server Name at the beginning of each job for any jobs that can only be executed on the primary node, and the use of Node Server Names at the beginning of each job that must be executed on the nodes individually, regardless of cluster status. 

This causes issues with my attempts to synchronize jobs across nodes, because the Copy-DbaAgentJob function wants to copy Node 1 specific jobs to node 2, where there is already Node 2 specific jobs. 

I want to be able to execute this Copy-DbaAgentJob command to copy any jobs that do not start with $PrimaryServer (something like -ExcludeJob "$PrimaryServer*").

**Comment by niphlod** [comment]
You can specify jobs to copy via -Job and -ExcludeJob. Just build the list of names beforehand with Get-DbaAgentJob.
Something among the lines of
```
$jobs = Get-DbaAgentJob -Source $PrimaryServer
$jobsToCopy = ($jobs | Where Name -Like "Clustername*").Name
Copy-DbaAgentJob -Destination $SecondaryServer -Source $PrimaryServer -Job $jobsToCopy
```
should work.
Feel free to reopen if I didn't get the gist of your request
