### ISSUE TITLE
Get-DbaRestoreHistory empty output

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#3534]
## Bug Report
`Get-DbaRestoreHistory -SqlInstance SRV1 -Last` - gives nothing

### General Troubleshooting steps

- [ ] Verified running the latest release of dbatools? 0.9.325
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10 1709
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): 2014 

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/14327077/38853040-b185a94c-4224-11e8-9b23-8debe526e620.png)

**Comment by niphlod** [comment]
killed by "the great inputobject rewrite" plus the lack of CI tests. Easy fix, but I'd spend more time creating the test to make sure it doesn't happen again
