### ISSUE TITLE
Get-DbaAgentJobHistory - Adjust to have more readable output

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#3538]
The enumeration method used outputs information just as querying msdb. Be good to update this to format the start date and duration properties, also adding a calculated end date for completeness.

Discussed with @niphlod in Slack and he has proper logic to handle this.

**Comment by niphlod** [comment]
let's go for additional properties `StartDate, EndDate, Duration` with `[dbatime]` and `[dbatimespan]` ?
