### ISSUE TITLE
New Command - Set-DbaAgentAlert

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#3542]
Create command to set the Agent Alert status

**Comment by MikeyBronowski** [comment]
@gbargsley I see the function in the module, but wondering if that's finished?

Would be great to have chance to actually create alerts using that function.

**Comment by gbargsley** [comment]
That would typically be a separate function.  So New-DbaAgentAlert or similar.

**Comment by andreasjordan** [comment]
Maybe I have time to build that command in the (near) future. Or is someone else working on that?

**Comment by potatoqualitee** [comment]
sweet, this is done 🔥 🚒
