### ISSUE TITLE
Strange error if the backup directory does not exists.

### ISSUE THREAD

**Issue by waffel** [sqlcollaborative/dbatools#3544]
## Bug Report
Strange error if the backup directory does not exists.

If you use the option "-BackupDirectory D:\something" but the directory does not exists, you get a red error. If I understood it correct only the "yellow" message should be printed which is enough to tell the user, that the directory is not there.

`PS C:\> Backup-DbaDatabase -SqlInstance 'localhost,6201' -Databases MY -BackupDirectory D:\a -T
ype Full -BackupFileName my.bak
WARNING: [Backup-DbaDatabase][19:00:15] SQL Server cannot write to the location D:\a
New-Object : A constructor was not found. Cannot find an appropriate constructor for type System.IO.FileInfo.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.325\allcommands.ps1:671 char:25
+ ...            $file = New-Object System.IO.FileInfo($FinalBackupPath[0])
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObjectCommand` 
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Microsoft Windows 7 Enterprise, 6.1.7601, 64bit
 - PowerShell Version:  5.1.14394.1000
 - SQL Server (Edition|Version): unrelated to this issue

## Steps to Reproduce

 - [x] Attach output from PowerShell console (if possible/allowed)

## Feature Request
I think the exception should not be printed out.

Also a kind of "-Force" parameter would be somehow cool. In this case the directory should be created for the user, so the SQL server can write in.

### Problem to solve

Try to avoid the red error stack trace.

**Comment by Stuart-Moore** [comment]
While fixing the other issue for Backup (write only) I've spotted some strangeness in the path parsing that seems to have not been noticed for a while, so I'll fix this while sorting that out

**Comment by Stuart-Moore** [comment]
The -BuildPath switch was introduced as some point in the past which fixes this issue.
