### ISSUE TITLE
New Command: Get-DbaResourceGovernorClassiferFunction

### ISSUE THREAD

**Issue by suxstellino** [sqlcollaborative/dbatools#3548]
## Feature request
Provide the ability to get the Resource Governor custom classifier function, if exists. 

As described in issue #3528 (thanks to @wsmelton), `Get-DbaResourceGovernorClassiferFunction` would be the command, then the copy command would call that [...] and all of that code can just be put in RG copy command.

I see:
- [x] add `Get-DbaResourceGovernorClassiferFunction`
- [x] check rules/styles of the new command
- [x] document the new command
- [ ] add unit tests for the new command
- [x] try the `Get-Help`for the new command
- [x] change `Copy-DbaResourceGovernor`
- [ ] ~edit integration tests after the change on the copy command~

### Additional info
When an environment needs to balance custom workloads, it's possible to setup the Resource Governor with a custom classifier function which dispatches the sessions toward certain workload groups. 

### Problem to solve
The `Copy-DbaResourceGovernor` command is not considering the optional custom classifier function (a dependency object) since is copying the default workload group based architecture. The command could be improved getting the definition of that function, if exists, in order to copy between instances also the custom object which the Resource Governor is dependent on when defining more than the default workload group.

**Comment by suxstellino** [comment]
I've a set of questions about this issue I'm working on:

**scenario: source server has a classifier function and destination hasn't it**
If -Force parameter is true, I will drop and create _A function_, which potentially have the same name of the source classifier one, then I'll rebind to the resource governor. Is that right in your opinion?
If -Force is false, what do you suggest to do? I'd like to "do anything", in order to avoid any change/risk with names.

**scenario: source server hasn't a classifier function and destination has it**
How to behave in case of -Force true/false? 

**scenario: both servers has a classifier function**
How to behave in case of -Force true/false?

any suggestion will be appreciated

**Comment by niphlod** [comment]
source has, dest has, no force --> warn and exit
source has, dest has, force --> overwrite dest
source has not, dest has --> nothing to copy ;-) 
source has, dest has not --> copy irregardless of force

**Comment by suxstellino** [comment]
In 2 and 4 (when I've to create or edit the dest classifier function) another dest function can have the same name of the source function (the one to copy). 
Indeed, in 2, I've to set to NULL che classifier function property of the resource governor in order to create or alter (if already exists) the dest function and in 4, I have to create or alter (if already exists) the function based on the source name. So I'm concerned about dropping or altering a previously created function, which could be unrelated to resource governor.
We can get a weird behavior here (maybe unlikely) that potentially drops a function in the dest server introducing a bug. Do you suggest to ignore it?

**Comment by niphlod** [comment]
in 2 and 4, if you're copying, **and you're positive** (-Force), if it exist on dest you either alter or drop and recreate. 
There's nothing you can do about "preserving" the "old" function, as with -Force the user is requesting the function to not bother and overwrite.

**Comment by sqllensman** [comment]
As the pull request has been merged can this be closed?
