### ISSUE TITLE
Get-DbaServerInstallDate | ogv - attempting to sort SqlInstallDate or WindowsInstallDate columns via header click closes grid view

### ISSUE THREAD

**Issue by SQLGB** [sqlcollaborative/dbatools#3553]
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools? (0.9.325)
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2 Standard
 - PowerShell Version: 5.1.14409.1005
 - SQL Server (Edition|Version): Enterprise 2005-2017

## Steps to Reproduce

1. Call Get-DbaServerInstallDate, pass in the names of at least two servers, and output to grid:
'SqlInstance1','SqlInstance2' | Get-DbaServerInstallDate | ogv
or
'SqlInstance1','SqlInstance2' | Get-DbaServerInstallDate -IncludeWindows | ogv
or
Get-DbaServerInstallDate -SqlInstance SqlInstance1, SqlInstance2 | ogv
or
Get-DbaServerInstallDate -SqlInstance SqlInstance1, SqlInstance2 -IncludeWindows | ogv
or
$MySqlInstanceList | Get-DbaServerInstallDate | ogv
or
$MySqlInstanceList | Get-DbaServerInstallDate -IncludeWindows | ogv

2. In the resulting grid, click the header for the SqlInstallDate (or WindowsInstallDate, if requested) column.
3. The grid will immediately close rather than sorting the content by that column.

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

## Feature Request

When Get-DbaServerInstallDate results are output to grid view, allow results to be sorted by SqlInstallDate or WindowsInstallDate columns by clicking the header for either column in the grid, rather than immediately closing grid view.

### Problem to solve
See "Feature Request".

**Comment by SQLGB** [comment]
Now realizing this may not be an issue with this function, but perhaps a general PowerShell issue?  Seeing similar behavior with other functions like "Get-DbaUptime".

**Comment by wsmelton** [comment]
This is a PowerShell + Out-GridView issue that multiple commands have the problem...it is unknown to the main contributors right now what is causing it. It is not believed to be something we can fix with the module itself.
