### ISSUE TITLE
Set-DbaNetworkCertificate doesn't take pipeline output from New-DbaComputerCertificate

### ISSUE THREAD

**Issue by nocentino** [sqlcollaborative/dbatools#3565]
## Bug Report
Set-DbaNetworkCertificate doesn't take pipeline output from New-DbaComputerCertificate

### Version Information
 - Windows 2012 R2
 - PowerShell Version: 5.1.14409.1012
 - SQL Server (Edition|Version): 2017 Enteprise

## Steps to Reproduce
`New-DbaComputerCertificate -ComputerName $ComputerName -CertificateTemplate $CertTemplate -KeyLength 4096 -FriendlyName $ComputerName -Dns @($ComputerName, $ComputerNameFQDN) | Set-DbaNetworkCertificate -SqlInstance $ComputerName -EnableException`

## Output
```
Set-DbaNetworkCertificate : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
At line:5 char:185
 ... NameFQDN) | Set-DbaNetworkCertificate -SqlInstance $ComputerName -Ena ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidArgument: (@{PSPath=Micros...somedomain.local}:PSObject) [Set-DbaNetworkCertificate], ParameterBindingException
     FullyQualifiedErrorId : InputObjectNotBound,Set-DbaNetworkCertificate
```

**Comment by nocentino** [comment]
Read the code for Set-DbaNetworkCertificate, it does take pipeline input. But it's that New-DbaComputerCertificate isn't emitting anything.

**Comment by potatoqualitee** [comment]
i ran into this issue too - and was working on fixing it then got tired. it's totall an issue eh?

**Comment by nocentino** [comment]
Chrissy, I'm a fool. It works as advertised. Excellent work! :)

**Comment by potatoqualitee** [comment]
lol guess i did fix it and forgot 😂

**Comment by potatoqualitee** [comment]
ohhh i know, you specified sqlinstance twice eh

**Comment by nocentino** [comment]
...computers are hard 😔

**Comment by potatoqualitee** [comment]
i made the same mistake *pat pat*
