### ISSUE TITLE
How to manage bacpac

### ISSUE THREAD

**Issue by jasonmcboyd** [sqlcollaborative/dbatools#3567]
I do not see any way to create a .bacpac file. Is it just a matter of it not being implemented yet or am I missing something?

**Comment by potatoqualitee** [comment]
New-DbaPublishProfile then Export-DbaDacpac should do the trick, and then Publish-DbaDacpac

here are sample commands that show all of them in use

https://github.com/sqlcollaborative/dbatools/blob/master/tests/Publish-DbaDacpac.Tests.ps1

**Comment by jasonmcboyd** [comment]
Hi Chrissy, actually, I'm trying to create a .bacpac (export the schema as well the data). 

I've spent some time looking through the code and the SqlPackage.exe examples since I opened the issue and I can see that 'Export' has to be passed as the 'Action' argument to SqlPackage.exe to do this. Right now it is hard coded as 'Extract' in the Export-DbaDacpac command so it is only possible to create .dacpacs with that command as things stand now.

I can take a look at implementing an Export-DbaBacpac command if there is any interest from the community.

**Comment by wsmelton** [comment]
Yes, there is interest...a bacpac is one option for porting a database on-premise to Azure SQL since it includes the data.

So I would say this is something we should offer. However, if the only difference in the process is `Extract` or `Export` I would say we simply add an `-Action` parameter to the current export command. Or even just call it `-IncludeData` and it just passes in the appropriate value to the `SqlPackage.exe`.

**Comment by jasonmcboyd** [comment]
Modifying the existing command is certainly an option. It is a little more nuanced than simply changing the `Action` argument though. There are optional parameters than can be passed to SqlPackage.exe depending on the value of `Action`. 

Actually, it looks like all the optional parameters are currently passed in the `ExtendedProperties` parameter (or maybe `ExtendParameters`) so I suppose you could modify the existing command without too much trouble. But IMHO it would be a better user experience if those optional parameters were proper (air quotes) parameters of the cmdlet rather than lumped together in a single parameter with instructions to see the SqlPackage documentation to figure out what to mash into that one parameter. If you decide to go the route of proper (air quotes again) cmdlet arguments then I feel like separate commands for dacpacs and bacpacs make more sense - it keeps the commands small and focused on doing one thing.

**Comment by potatoqualitee** [comment]
oops! my bad. yah we could add the action

**Comment by wsmelton** [comment]
@jasonmcboyd trying to make every possible parameter that can be passed into the `SqlPackage` program a parameter in the command would be cumbersome and cause to many validations to have to be done in the function. As well if a version change causes some parameters to be invalid or add new ones it is more to maintain.

**Comment by brettmillerb** [comment]
This looks like it can be closed with PR https://github.com/sqlcollaborative/dbatools/pull/4256 being merged.
