### ISSUE TITLE
Get-DbaOrphanUser only returns a single row per database

### ISSUE THREAD

**Issue by GarthAurish** [sqlcollaborative/dbatools#3573]
## Issue
Get-DbaOrphanUser only returns a single row per database.  So if a single DB has multiple orphan users then it only counts as 1.  Question is whether this should return the full count of orphans per DB by returning @($results.user).count instead of @($results).count

### General Troubleshooting steps
- Checked latest version of Database.Tests.ps1 file has the same return value.
- Manually ran the command to show that the object can produce the exact number of orphan users per DB

### Version Information
Although code reacts the same on multiple versions of SQL Server
 - Windows 10
 - PowerShell Version: 5.1
 - SQL Server SQL Server 2008

### Steps to Reproduce
<--  
PS C:\Users\userID> $results = Get-DbaOrphanUser -SqlInstance tst-sqlserver.domain.com

PS C:\Users\userID> $results

SqlInstance              DatabaseName   User                            
-----------              ------------   ----                            
tst-sqlserver.domain.com DB1        {user1, user2, user3, user4...}
tst-sqlserver.domain.com DB2          user1
tst-sqlserver.domain.com DB3        {user1, user2, user3, user4...}

PS C:\Users\userID> @($results).count
3

PS C:\Users\userID> @($results.user).count
32

## Feature Request
I would like it to return the full number of orphan users rather than just the number of databases with orphan users

**Comment by wsmelton** [comment]
Duplicate an example:

```sql
CREATE LOGIN [orphan1] WITH PASSWORD = N'password1', CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
CREATE LOGIN [orphan2] WITH PASSWORD = N'password2', CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
CREATE LOGIN [orphan3] WITH PASSWORD = N'password2', CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
CREATE LOGIN [orphan4] WITH PASSWORD = N'password2', CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
CREATE LOGIN [orphan5] WITH PASSWORD = N'password2', CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
CREATE LOGIN [orphan6] WITH PASSWORD = N'password2', CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;


CREATE DATABASE [orphansrus] ON
    ( NAME = orphansrus_data, FILENAME = 'C:\sqlfiles\orphansrus_data.mdf' )
    LOG ON
    ( NAME = orphansrus_log, FILENAME = 'C:\sqlfiles\orphansrus_log.ldf' );
GO

USE [orphansrus];
GO
CREATE USER [orphan1] FROM LOGIN [orphan1];
CREATE USER [orphan2] FROM LOGIN [orphan2];
CREATE USER [orphan3] FROM LOGIN [orphan3];
CREATE USER [orphan4] FROM LOGIN [orphan4];
CREATE USER [orphan5] FROM LOGIN [orphan5];
CREATE USER [orphan6] FROM LOGIN [orphan6];
GO

USE [master];
GO
DROP LOGIN [orphan2];
DROP LOGIN [orphan4];
DROP LOGIN [orphan6];
GO
```

```powershell
Get-DbaOrphanUser -SqlInstance 'localhost,1414' -Database orphansrus
```

![image](https://user-images.githubusercontent.com/11204251/39415732-90d29ed4-4c0c-11e8-87bf-0c85e1316e8c.png)

The count method being used only references the parent object when you get a count.

```powershell
#so
(Get-DbaOrphanUser -SqlInstance 'localhost,1414' -Database orphansrus).Count

# Only counts the databases because that is the parent property that exists

# where as User property is an array, so passing that property to Count() will give you the desired result
(Get-DbaOrphanUser -SqlInstance 'localhost,1414' -Database orphansrus).User.Count
```

**Comment by wsmelton** [comment]
If you want details on the orphaned users then it will be `Get-DbaDbOrphanUser` and not just `Get-DbaOrphanUser`.

**Comment by GarthAurish** [comment]
Perfect thanks.  I'll choose the issue out.  Nice work by the way

**Comment by niphlod** [comment]
@wsmelton : the whole *orphan* bundle needs a little love and I'd like to target it. 
Can we put a bulleted todo-list so I/we can finalize it and ready it to be 1.0 compliant ? 
Also: I'm totally not convinced that Get-DbaOrphanUser should include the database in the name, as orphans are ONLY found "scoped" by databases.

**Comment by niphlod** [comment]
well, "refactoring and standardization" is hard, but IMHO anything containing "User" should return an object for each user, and not for every database. Users are only found in databases, so IMHO the "db/database" prefix/suffix is not needed. 

If you're pleased better with that logic (adding Db or Database prefix/suffix), anything "*user*" should be either "*dbuser*" or "*databaseuser*" but that's hardly the problem raised in this issue.

This is the only function that returns a collection within a property, which is both counter-intuitive and error-prone.
If to "correct" this behaviour we wanna reorganize the whole "*user*" vs "*dbuser*" dilemma fine, we just need to add to the work items yet another collection of things to do.
