### ISSUE TITLE
Name resolution issue with Copy-DbaCredential

### ISSUE THREAD

**Issue by EmDBA** [sqlcollaborative/dbatools#3575]
Hi,

Copy-DbaCredential doesn't work when server names includes FQDN.

Command : 
`Copy-DbaCredential -Source servername.domain.com\inst1 -Destination servername.domain.com\inst2`

Error : 
`
WARNING: [Copy-DbaCredential][11:10:01] Can't connect to registry on servername\inst1. | Connecting to remote server
tnpsqlqua01 failed with the following error message : WinRM cannot process the request. The following error with
errorcode 0x80090311 occurred while using Kerberos authentication: There are currently no logon servers available to
service the logon request.
 Possible causes are:
  -The user name or password specified are invalid.
  -Kerberos is used when no authentication method and no user name are specified.
  -Kerberos accepts domain user names, but not local user names.
  -The Service Principal Name (SPN) for the remote computer name and port does not exist.
  -The client and remote computers are in different domains and there is no trust between the two domains.
 After checking for the above issues, try the following:
  -Check the Event Viewer for events related to authentication.
  -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or
use HTTPS transport.
 Note that computers in the TrustedHosts list might not be authenticated.
   -For more information about WinRM configuration, run the following command: winrm help config. For more information,
 see the about_Remote_Troubleshooting Help topic.`

**Comment by potatoqualitee** [comment]
I am unable to reproduce the issue. The error message returned suggests kerberos issues between your workstation and the source.

![image](https://user-images.githubusercontent.com/8278033/48529315-c1daa080-e892-11e8-8e63-89623b9d6ec0.png)
