### ISSUE TITLE
Problems with restoring using Restore-DbaDatabase

### ISSUE THREAD

**Issue by dontomase** [sqlcollaborative/dbatools#3576]
### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): **Windows 7**
 - PowerShell Version: **5 build 14409**
 - SQL Server (Edition|Version): **SQL Server 2017**

### Problem to solve
I get this error when I want to restore a database with Restore-Dbadatabase and the options
-ReuseSourceFolderStructure -Withreplace 

The database is left in restricted user mode.

WARNING: [Invoke-DbaAdvancedRestore][11:17:30] Failed to restore db cosmictest2, stopping | Exception calling "SqlRestore" with "1" argument(s): "Restore failed for Server 's-dbadbt1'. "

### Additional information

If I do a outputscript I can see in that script that it tries to do a move three times for the same file. There is also double of the bak files in the second folder wich seems to be the real trouble if I remove the double files the restore works in SQLMGMSTD.

I have tried this with only specifying one folder in the -PATH but it still takes the last two bak files twice in the script

Restore-DbaDatabase -Sqlserver s-dbadbt1 -path \\Share\DbaCopy -databasename cosmictest2 -ReuseSourceFolderStructure -Withreplace

Restore-DbaDatabase -Sqlserver s-dbadbt1 -path \\Share\DbaCopy,\\Share\DbaCopy\filer -databasename cosmictest2 -ReuseSourceFolderStructure -Withreplace

If I do a backup to only one folder but the same number of files it works just fine, I still got every WITH MOVE three times but each bak file is only once.

Here is the generated script

RESTORE DATABASE [cosmictest2] FROM  DISK = N'\\Share\DbaCopy\fil1.bak',
 DISK = N'\\Share\DbaCopy\fil2.bak',
 DISK = N'\\Share\DbaCopy\fil3.bak',
 DISK = N'\\Share\DbaCopy\Filer\fil4.bak',
 DISK = N'\\Share\DbaCopy\Filer\fil5.bak',
 DISK = N'\\Share\DbaCopy\filer\fil4.bak',
 DISK = N'\\Share\DbaCopy\filer\fil5.bak' WITH  FILE = 1, 
MOVE N'cosmic' TO N'E:\CMDB2\DBDATA\PRIMARY001\Mssql\Data\Primary001.mdf', 
MOVE N'CC001' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC001.ndf', 
MOVE N'CC002' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC002.ndf', 
MOVE N'CC003' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC003.ndf', 
MOVE N'CC004' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC004.ndf', 
MOVE N'MAIN' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN002.ndf', 
MOVE N'MAIN2' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN001.ndf', 
MOVE N'MED001' TO N'E:\CMDB2\MISC\MISC001\Med\Mssql\Data\MED001.ndf', 
MOVE N'MED002' TO N'E:\CMDB2\MISC\MISC002\Med\Mssql\Data\MED002.ndf', 
MOVE N'cosmic_log' TO N'F:\CMDB2\LOG\LOG001\Mssql\Data\log001.ldf', 
MOVE N'cosmic' TO N'E:\CMDB2\DBDATA\PRIMARY001\Mssql\Data\Primary001.mdf', 
MOVE N'CC001' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC001.ndf', 
MOVE N'CC002' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC002.ndf', 
MOVE N'CC003' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC003.ndf', 
MOVE N'CC004' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC004.ndf', 
MOVE N'MAIN' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN002.ndf', 
MOVE N'MAIN2' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN001.ndf', 
MOVE N'MED001' TO N'E:\CMDB2\MISC\MISC001\Med\Mssql\Data\MED001.ndf', 
MOVE N'MED002' TO N'E:\CMDB2\MISC\MISC002\Med\Mssql\Data\MED002.ndf', 
MOVE N'cosmic_log' TO N'F:\CMDB2\LOG\LOG001\Mssql\Data\log001.ldf', 
MOVE N'cosmic' TO N'E:\CMDB2\DBDATA\PRIMARY001\Mssql\Data\Primary001.mdf', 
MOVE N'CC001' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC001.ndf', 
MOVE N'CC002' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC002.ndf', 
MOVE N'CC003' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC003.ndf', 
MOVE N'CC004' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC004.ndf', 
MOVE N'MAIN' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN002.ndf',
MOVE N'MAIN2' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN001.ndf', 
MOVE N'MED001' TO N'E:\CMDB2\MISC\MISC001\Med\Mssql\Data\MED001.ndf', 
MOVE N'MED002' TO N'E:\CMDB2\MISC\MISC002\Med\Mssql\Data\MED002.ndf', 
MOVE N'cosmic_log' TO N'F:\CMDB2\LOG\LOG001\Mssql\Data\log001.ldf', 
MOVE N'cosmic' TO N'E:\CMDB2\DBDATA\PRIMARY001\Mssql\Data\Primary001.mdf', 
MOVE N'CC001' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC001.ndf', 
MOVE N'CC002' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC002.ndf', 
MOVE N'CC003' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC003.ndf', 
MOVE N'CC004' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC004.ndf', 
MOVE N'MAIN' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN002.ndf', 
MOVE N'MAIN2' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN001.ndf', 
MOVE N'MED001' TO N'E:\CMDB2\MISC\MISC001\Med\Mssql\Data\MED001.ndf', 
MOVE N'MED002' TO N'E:\CMDB2\MISC\MISC002\Med\Mssql\Data\MED002.ndf', 
MOVE N'cosmic_log' TO N'F:\CMDB2\LOG\LOG001\Mssql\Data\log001.ldf', 
MOVE N'cosmic' TO N'E:\CMDB2\DBDATA\PRIMARY001\Mssql\Data\Primary001.mdf', 
MOVE N'CC001' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC001.ndf', 
MOVE N'CC002' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC002.ndf', 
MOVE N'CC003' TO N'E:\CMDB2\CC\CC001\Mssql\Data\CC003.ndf', 
MOVE N'CC004' TO N'E:\CMDB2\CC\CC002\Mssql\Data\CC004.ndf', 
MOVE N'MAIN' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN002.ndf', 
MOVE N'MAIN2' TO N'E:\CMDB2\DBDATA\MAIN001\Mssql\Data\MAIN001.ndf', 
MOVE N'MED001' TO N'E:\CMDB2\MISC\MISC001\Med\Mssql\Data\MED001.ndf', 
MOVE N'MED002' TO N'E:\CMDB2\MISC\MISC002\Med\Mssql\Data\MED002.ndf', 
MOVE N'cosmic_log' TO N'F:\CMDB2\LOG\LOG001\Mssql\Data\log001.ldf',  
NOUNLOAD,  REPLACE,  STATS = 10

I hope yu understand my issue :-)

Keep up the good work

Regards
Tomas

**Comment by dczarny** [comment]
I had the same issue.  I had to back down my version of dbatools back to 0.9.319

**Comment by dontomase** [comment]
Ok, thank you I will try that.
