### ISSUE TITLE
Copy-SqlLogin - Login does not appear to be migrated if destination is set to mixed mode auth

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#358]
**What is the current behavior?**
When copying a SQL login to a destination which is set to Windows Authentication only (not Mixed Mode) the login never appears to be copied. The output does not appear to make the user aware of this so it may be a bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simply use Copy-SqlLogin with -Destination set to a server which is not set to Mixed Mode, observe the output and check the destination in SSMS to verify the login is not present.

**What is the expected behavior?**
The login should be copied I believe. You can create SQL logins via SSMS and T-SQL on a server which is set to Windows Authentication only. I have not tried SMO/PowerShell though.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
I have verified this on Windows 7/PowerShell 5.0, SQL Server 2012.

**Comment by mshamann** [comment]
> Simply use Copy-SqlLogin with -Destination set to a server which is set to Mixed Mode 

I assume you mean 'Which is not set to Mixed Mode'?

**Comment by dansqldba** [comment]
Cough, yes, I meant *not* set to Mixed Mode, amended!

**Comment by ctrlbold** [comment]
:O It appears there is a Continue on line 158 that should be removed.

**Comment by mshamann** [comment]
Here?
				if ($servername -eq $userbase -or $username.StartsWith("NT "))
				{
					If ($Pscmdlet.ShouldProcess("console", "Stating $username is skipped because it is a local machine name."))
					{
						Write-Output "$username is skipped because it is a local machine name."
					}
					continue
				}

Does that mean the Write-Output should also be a Write Warning?

**Comment by dansqldba** [comment]
Yes I believe this also warrants a change to Write-Warning in my opinion... Feel free to check through the whole thing and adjust where you see fit, if you want ;)

**Comment by mshamann** [comment]
Hmm ill also add the username to the Mixed mode error.

**Comment by dansqldba** [comment]
Fixed in #365
