### ISSUE TITLE
Remove-SqlDatabaseSafely - Improve handling of offline databases

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#359]
**Do you want to request a *feature* or report a *bug*?**
Enhancement to existing function.

**What is the current behavior?**
Offline databases cause this cmdlet to throw an exception (which is caught) during the DBCC CHECKDB stage.  A more graceful detection of the database state could be introduced in the BEGIN block.

**What is the expected behavior?**
Warn the user the database is read only, or offer to bring it online perhaps?

**Comment by SQLDBAWithABeard** [comment]
fixed with cedcae1cbc8a7685de71c4ad58b20a0a978fbe30
