### ISSUE TITLE
Copy-DbaTableData issues no error/warning /information if the -Table supplied does not exist

### ISSUE THREAD

**Issue by amtwo** [sqlcollaborative/dbatools#3592]
## Bug Report
Copy-DbaTableData issues no error/warning /information if the -Table supplied does not exist. The complete lack of feedback makes it difficult to determine the source of an error if the mistake is a typo.

### General Troubleshooting steps

- [ X ] Verified running the latest release of dbatools?
- [ X ] Verified errors are not related to permissions?
- [ X ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: PSVersion 5.1.17134.1
 - SQL Server (Edition|Version): 2017

## Steps to Reproduce
Execute this line, where the servers & database exist, but the table does not.
```Copy-DbaTableData -SqlInstance PRD-SQL1 -Destination PRD-SQL2-Database MyDatabase -DestinationDatabase MyDatabaseCopy -Table dbo.ThisTableNameHasATypo -KeepIdentity -Truncate
```
The command completes, but provides zero output. The lack of output hints that nothing happened, but a more explicit warning/error as to why would be helpful (ie, "table does not exist")

**Comment by niphlod** [comment]
@sqllensman : as the most recent editor of Copy-DbaDbTableData is this still open ? I feel like it isn't but can you please check ?

**Comment by sqllensman** [comment]
The new code will return a warning if source or destination cannot be determined

**Comment by niphlod** [comment]
perfect, than this can be closed ! Thank you @sqllensman

**Comment by potatoqualitee** [comment]
thanks for the follow up, @niphlod !

**Comment by niphlod** [comment]
my new nickname will be "niph-the-hoverer".
