### ISSUE TITLE
Feature Request - Get-DbaLastBackup - Ignore Read Only, Recovering or Offline Databases

### ISSUE THREAD

**Issue by LinkOps** [sqlcollaborative/dbatools#3593]
Hi,

When running the above it doesn't exclude looking at databases that are in an unavailable state.

I have been running the following:

> Get-DbaLastBackup -SqlInstance $Server |select SqlInstance,Database,LastFullBackup,LastLogBackup

And get these constant warnings:

> WARNING: [Get-DbaLastBackup][17:51:25] The database [CitrixHQLogging] on server is not accessible. Skipping database.
> WARNING: [Get-DbaLastBackup][17:51:25] The database [CitrixHQMonitoring] on server is not accessible. Skipping database.
> WARNING: [Get-DbaLastBackup][17:51:25] The database [CitrixHQSite] on server is not accessible. Skipping database.

Could the stored procedures ignore such databases

**Comment by niphlod** [comment]
well, it's a matter of chicken and egg IMHO. If you do not pass -Database, the function assumes you want the last backup from EVERY database. 
If the function skips over without warnings, how would you accomodate the "inverse" requirement of being sure you have a fairly recent backup for all the databases ?

**Comment by LinkOps** [comment]
Fair point but one wouldn't be interested in taking a backup of a database
in a log shipped secondary as that would have fallen to the primary. Maybe
a switch for those who acknowledge the exclusion?

**Comment by niphlod** [comment]
well, exclusion can't *really* be that objective for all scenarios .... LogShipping, mirroring, failover, availability groups with backup preference just comes to mind, and I'm sure I'm forgetting something right off the bat. At that point I think another function on a higher level should enforce the logic for checking and use get-dbalastbackup only on preselected databases
