### ISSUE TITLE
Feature Request - Get-DbaAvailabilityGroup - Explode out AvailabilityReplicas, AvailabilityDatabases & AvailabilityGroupListeners

### ISSUE THREAD

**Issue by LinkOps** [sqlcollaborative/dbatools#3594]
Hi,

It is not possible to export the above data columns to CSV due to them being an array. Could they instead be listed as a semi-colon (;) separated string to enable their easier export and readability to CSV file formats

**Comment by niphlod** [comment]
an array is an object you can manipulate as you wish down the line of your powershell script. 
If we turn them to a string separated by a semi-colon that would mean that we'd LOWER the flexibility of the function. 
If you want strings from awways, the "transformation" you seek is just  a simple one-liner away, which is `$array -Join ';'` .
