### ISSUE TITLE
Get-DbaRoleMember -ExcludeDatabase does not work

### ISSUE THREAD

**Issue by pollusb** [sqlcollaborative/dbatools#3597]
### General Troubleshooting steps

- [x ] Verified running the latest release of dbatools?
- [x ] Verified errors are not related to permissions?
- [ ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): 
 - PowerShell Version: 
 - SQL Server (Edition|Version): 

## Steps to Reproduce
`Get-DbaRoleMember -SqlInstance $SqlInstance -ExcludeDatabase 'msdb','tempdb','master'`
Will return the excluded databases. 

There is a workaround of course but the point is other Functions like Get-DbaDbRole, use the ExcludedDatabase as expected.
`Get-DbaRoleMember -SqlInstance $SqlInstance | Where Database -notin 'msdb','tempdb','master'`

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by niphlod** [comment]
gotcha!
