### ISSUE TITLE
Copy-SQLDatabases

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#360]
**Do you want to request a *feature* or report a *bug*?**
Yes
**What is the current behavior?**
The -databases parameter is only returning system databases and not allowing a user database
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[Doc1.docx](https://github.com/sqlcollaborative/dbatools/files/622744/Doc1.docx)

**What is the expected behavior?**
Should list user databases
**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
powershell version 4.0.  This worked in previous versions, but getting this in 0.8.67.

I also tried to uninstall and reinstall dbatools and still got that error on separate machines.

**Comment by ctrlbold** [comment]
Oh, shit, that's bad. Gonna fix this tonight and push out a new release.

**Comment by zloeber** [comment]
Function Get-ParamSqlServerConfigs needs a mild logic change:

```foreach ($database in $server.databases)
	{
		if ($NoSystem)
		{
			if ( (-not $database.IsSystemObject) -and ($SupportDbs -notcontains $database.name))
			{
				$databaselist += $database.name
			}
		}
		else
		{
			$databaselist += $database.name
		}
	}
```
 
Great module BTW, thanks for such clear code.

**Comment by ctrlbold** [comment]
Thanks so much for both the code and the compliment 👍 I put out a new version of the module tonight. Will have it in the official release sometime next week but it's in master and has been updated in the PowerShell Gallery.
