### ISSUE TITLE
Select-DbaBackupInformation - error when no FULL with DIFF/LOG present

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#3607]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
>$gbi = Get-DbaBackupInformation -Path E:\BACKUPS -SqlInstance localhost
>$gbi | Select-DbaBackupInformation
```

## Expected Behavior

_DB1 backups list_
_DB2 backups list_
_DB3 backups list_

## Actual Behavior

_DB1 backups list_
_ERROR_
![image](https://user-images.githubusercontent.com/14327077/40000476-8c666518-5794-11e8-868c-ec6ddb193fe8.png)
_DB3 backups list_

## Environmental data

 - PowerShell: 
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
 - - SQL Server: Microsoft SQL Server 2012 (SP4-OD) (KB4091266) - 11.0.7469.6 (X64)   Feb 28 2018 17:47:20   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

**Comment by Splaxi** [comment]
I can see that the @cl made a commit 3 months back ([f0ffa50dd2a86a042d7c40d3411a7979e28054dd](https://github.com/sqlcollaborative/dbatools/commit/f0ffa50dd2a86a042d7c40d3411a7979e28054dd)) to fit the #3945 where she introduced a check around the `$full.Fullname`

I would believe that this issue has been resolved with that.

**Comment by Stuart-Moore** [comment]
I'm guessing @Zhunya is probably running in dev branch :)

What's  in $gbi? I've just done the same thing here and Fullname is
populated.  Use the -Anonymise switch if you want to hide any sensitive
contents.

**Comment by Zhunya** [comment]
Yep, always run cutting edge dbatools version, and after fixes to error message handling `Select-DbaBackupInformation` finish in right way... Closing this one as `resolved`.

**Comment by Stuart-Moore** [comment]
d'oh, should have checked when the issue was opened :)
