### ISSUE TITLE
Find-DbaLoginInGroup - Incorrect Domain returned.

### ISSUE THREAD

**Issue by CDGHy** [sqlcollaborative/dbatools#3608]
Find-DbaLoginInGroup - Incorrect Domain returned.

The code (line 88) is written to employ the first Domain Component (DC) within the DistinguishedName attribute, to represent the Domain of the user.

Because this is the Novel X500 convention, rather than the Microsoft adopted NetBIOS name resolution, this can mean that the domain is incorrect, where the attributes are different.

Grateful, if all the DC values (delimited with a period), can be run via the Get-ADDomain function, in order to obtain the Domain's NetBIOSName.

This value, would be the Domain, for the given user.

Unfortunately, my Powershell knowledge is not of a good enough standard to provide a worked example.

**Comment by awickham10** [comment]
I have this same issue. It would appear that making the below change would fix the issue.

Change
```powershell
$memberDomain = $member.DistinguishedName -Split "," | Where-Object { $_ -like "DC=*" } | Select-Object -first 1 | ForEach-Object { $_.ToUpper() -replace "DC=", '' }
```
to
```powershell
$ads.Name
```
