### ISSUE TITLE
Connect-SqlInstance and DbaInstanceParameter and re-use server connection object

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#3616]
## Steps to Reproduce

For example

```powershell

Restore-DbaDatabase -SqlInstance <[string]SqlServerName> -SqlCredentials <[object]credentialt>...

```

## Expected Behavior

Function will build connection object, and reuses it thru all other internal call to other funtions.

## Actual Behavior

Connection object lost credential somewhere between lines [390](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Restore-DbaDatabase.ps1#L390) and [541](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Restore-DbaDatabase.ps1#L541)

Look at #3613

**Comment by potatoqualitee** [comment]
@Zhunya - this should be fixed in `Connect-SqlInstance` as well as cross domain authentication. Please reopen this issue if has not been addressed.
