### ISSUE TITLE
Get-DbaAgDatabase returns more than expected

### ISSUE THREAD

**Issue by ManxMadBoy** [sqlcollaborative/dbatools#3619]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

One of our vendors uses databases for his application with names all starting with the same characters, with one just being these characters.

![afbeelding](https://user-images.githubusercontent.com/39374768/40178481-daef1104-59e1-11e8-9bdc-af3a7acbcaa8.png)

```powershell

    Get-DbaAgDatabase -SqlInstance <server> -Database ExtendedIPU
```

## Expected Behavior

I would have expected to get the details of just the ExtendedIPU database

## Actual Behavior

I get the details of all databases of which the name starts with ExtendedIPU

## Environmental data

 - PowerShell:
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server:
Microsoft SQL Server 2016 (SP1-CU7-GDR) (KB4057119) - 13.0.4466.4 (X64)   Dec 22 2017 11:25:00   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by ManxMadBoy** [comment]
Managed to reproduce this on another sql server running Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64).

**Comment by ManxMadBoy** [comment]
Pushed the wrong button. sorry....

**Comment by wsmelton** [comment]
Can you edit your issue please and add the command you are running?
