### ISSUE TITLE
Rename-dbaDatabase: Parameter Set Offline does nothing

### ISSUE THREAD

**Issue by mvillegascuellar** [sqlcollaborative/dbatools#3621]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
Rename-DbaDatabase -SqlInstance tsssqldb02\contopsadev -Database test1 -DatabaseName test2 -SetOffline
```

## Expected Behavior

Rename the database which it does, but the database is not put in offline mode

## Actual Behavior

Rename the database and leaves the database online, 

## Environmental data

 - PowerShell: 

PS>$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.17134.48
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.48
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by niphlod** [comment]
This is expected since setoffline is meant to have a meaning when you
rename the files, not just the database. Nonetheless is a good report, I'll
add a check to stop when setoffline is passed but no rename files is
passed. Thanks a lot

Il ven 18 mag 2018, 00:18 Michael Villegas <notifications@github.com> ha
scritto:
