### ISSUE TITLE
Install-DbaWatchUpdate no WhatIf parameter handling.

### ISSUE THREAD

**Issue by way0utwest** [sqlcollaborative/dbatools#3626]
### Before submitting a bug report:

- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
    Provide exact (or sanitized) code to reproduce the error
#>
```
Install-DbaWatchUpdate -WhatIf
## Expected Behavior
Return

A description of the task added, it's name, and the schedule.

## Actual Behavior
Parameter not recognized. No action from powershell shell.

## Environmental data

 - PowerShell: 
 - - SQL Server:

**Comment by wsmelton** [comment]
@way0utwest if you can let us know what version of the module you are running.

Verified that `WhatIf` support does exist in the command currently:

![image](https://user-images.githubusercontent.com/11204251/41221603-37604a24-6d2a-11e8-94e2-905b7c22d3dd.png)

**Comment by wsmelton** [comment]
Working on updating the command for `WhatIf` support, but also found out @potatoqualitee the toast notification no longer works. It seems this may have been from the Windows 10 May update...I don't have the latest version on my laptop and it is not posting any toast messages to the message center on my machine.

**Comment by way0utwest** [comment]
0.9.335
