### ISSUE TITLE
Inconsistent Tags in Commands

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#3640]
While demonstrating the Find-DbaCommand -Tag (Version 0.9.338)

I found commands with Missing or Inconsistent Tag values

The obvious examples are in the attached spread sheet

[dbatools_tags.xlsx](https://github.com/sqlcollaborative/dbatools/files/2048613/dbatools_tags.xlsx)

## Commands missing tag

Connect-DbaInstance
ConvertTo-DbaDataTable
Copy-DbaXESessionTemplate
Export-DbaPfDataCollectorSetTemplate
Export-DbaSpConfigure
Export-DbaXESessionTemplate
Find-DbaDuplicateIndex
Find-DbaInstance
Find-DbaLoginInGroup
Find-DbaSimilarTable
Find-DbaStoredProcedure
Find-DbaTrigger
Find-DbaView
Format-DbaBackupInformation
Get-DbaAvailableCollation
Get-DbaBackupInformation
Get-DbaClusterNode
Get-DbaDatabaseEncryption
Get-DbaDatabaseSpace
Get-DbaDbExtentDiff
Get-DbaDbPageInfo
Get-DbaDependency
Get-DbaLinkedServer
Get-DbaLogin
Get-DbaMaintenanceSolutionLog
Get-DbaOpenTransaction
Get-DbaPfAvailableCounter
Get-DbaPfDataCollectorSetTemplate
Get-DbaProcess
Get-DbaRunningJob
Get-DbaServerAudit
Get-DbaServerAuditSpecification
Get-DbaSpConfigure
Get-DbaSqlFeature
Get-DbaSqlInstanceProperty
Get-DbaSqlInstanceUserOption
Get-DbaSqlService
Get-DbaSsisEnvironmentVariable
Get-DbaTempdbUsage
Import-DbaPfDataCollectorSetTemplate
Import-DbaSpConfigure
Install-DbaFirstResponderKit
Install-DbaMaintenanceSolution
Install-DbaWhoIsActive
Invoke-DbaAdvancedRestore
Invoke-DbaPfRelog
Invoke-Sqlcmd2
New-DbaSqlConnectionString
New-DbaSqlDirectory
New-DbaSsisCatalog
Register-DbaConfig
Rename-DbaDatabase
Restart-DbaSqlService
Select-DbaBackupInformation
Set-DbaAgentJobOutputFile
Set-DbaCmConnection
Set-DbaDatabaseOwner
Set-DbaDatabaseState
Set-DbaMaxDop
Set-DbaPowerPlan
Set-DbaStartupParameter
Set-DbaTcpPort
Set-DbaTempDbConfiguration
Show-DbaDatabaseList
Start-DbaSqlService
Stop-DbaSqlService
Test-DbaBackupInformation
Test-DbaDatabaseCompatibility
Test-DbaDatabaseOwner
Test-DbaValidLogin
Update-DbaSqlServiceAccount

## Tags inconsistent

TagValue | UseCount
-- | --
AG | 8
AvailabilityGroup | 8
data management | 1
Database Objects | 1
disaster recovery | 1
DisasterRecovery | 28
Job Category | 4
Job Step | 6
LogShipping | 2
Log shippin | 1
Log Shipping | 1

**Comment by wsmelton** [comment]
The tags for `AG` and `AvailabilityGroup` are not going to change those are set as desired...not sure why you consider those inconsistent.

**Comment by sqllensman** [comment]
Looking at the latest release the following Commands are still without Tags

Import-DbaSpConfigure		
Install-DbaWhoIsActive				
Test-DbaLoginPassword		

Can be checked via:

Find-DbaCommand -Pattern Import-DbaSpConfigure  | Select Tags		
Find-DbaCommand -Pattern Install-DbaWhoIsActive | Select Tags		
Find-DbaCommand -Pattern Test-DbaLoginPassword  | Select Tags


Invoke-SqlCmd2 is also missing Tags but this may be  expected.
