### ISSUE TITLE
Find-DbaTable, filter capabilities

### ISSUE THREAD

**Issue by mikedavem** [sqlcollaborative/dbatools#3642]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

Get-Table is a nice feature to get quickly information table, but misses filters like wildcards (e.g. all tables that begin with tt_). Let's create a Find-DbaTable for that.

Thanks!

### Latest version of dbatools as of writing

0.9.190

**Comment by mikedavem** [comment]
Hi niphlod,

I didn't find out the **find-dbatable** neither in the website's command index nor from the follwing command 

`get-command -Module dbatools | Where-Object { $_.Name -like "Find*" } | Sort-Object`

My dbatools version = 0.9.190

**Comment by niphlod** [comment]
nothing really. Just saying that the feature request for filtering should be "fullfilled" in another function. All the other info I'm really not sure of.....get-dbatable returns the SMO object and should have all properties related to the table already. Did you already tried using `Get-DbaTable ..... | select *` ?

**Comment by mikedavem** [comment]
Ok. I got it. 

Yes, using the following command meets my need:

`Get-DbaTable -SqlInstance SRV -Database DB | Sort-Object -Property DataSpaceUsed -Descending | Select-Object Name, DataSpaceUsed -First 10`

**Comment by niphlod** [comment]
no probl, I'll go ahead and edit the request so the filtering enhancement remains logged properly

**Comment by niphlod** [comment]
not sure this can be speeded up by some internals. Get-DbaTable does the best job it can already...
