### ISSUE TITLE
Add Database Count Progress to Backup-DbaDatabase

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#3659]
---
name: Show X of X database backed up :bomb:
about: Display backup count complete

---

### Summary of new feature

I would like to see a count of X of Y backups complete.  I believe from looking at the command we have the count of databases we are going to back up.  And as a database is backed up and the next one started that counter would follow.

Example: You have 90 databases to backup.  The progress currently shows for the backup command, but I would like to see added X of 90 backups complete.

**Comment by wsmelton** [comment]
I have not looked at the command in a while but recall it did show databases completed. @gbargsley if this is still an issue please update this issue.

**Comment by gbargsley** [comment]
![image](https://user-images.githubusercontent.com/169602/45296351-64f3f000-b4c7-11e8-9245-a0a647a2c79d.png)


![image](https://user-images.githubusercontent.com/169602/45296360-6b826780-b4c7-11e8-8d12-90bc99ca0d3b.png)

![image](https://user-images.githubusercontent.com/169602/45296387-85bc4580-b4c7-11e8-974c-ae1e7d71aa8d.png)



In ISE or command line it shows percent of a backup complete, but it does not show for example mine the number of backups it is doing of the 7 total expected.

**Comment by andreasjordan** [comment]
Good idea. 
Would not work for piped input as there the process block only sees one database at a time and has no idea how many follow.
But I will have a look at it. 
As it is a backup command: What does @Stuart-Moore say?
