### ISSUE TITLE
Copy-SqlCentralManagementServer - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#366]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseApprovedVerbs|Warning|96|The cmdlet 'Parse-ServerGroup' uses an unapproved verb.
PSPossibleIncorrectComparisonWithNull|Warning|104|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|104|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|214|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|214|$null should be on the left side of equality comparisons.
PSUseDeclaredVarsMoreThanAssignments|Warning|247|The variable 'SqlCmsGroups' is assigned but never used.
PSPossibleIncorrectComparisonWithNull|Warning|275|$null should be on the left side of equality comparisons.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
