### ISSUE TITLE
Check for version with standby in Invoke-DbaLogShipping

### ISSUE THREAD

**Issue by sanderstad** [sqlcollaborative/dbatools#3662]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Expected Behavior
The expected behavior is to check if the destination server major version is greater than the current version. If the user wants a database in standby mode the major version has to be the same as the current version. A database cannot be log shipped in standby mode when the destination server major version is greater.

## Actual Behavior
The command generates an error that the backup cannot be restored in standby mode due to an upgrade.

## Environmental data

 - PowerShell: 
 - - SQL Server:

**Comment by potatoqualitee** [comment]
how's this looking @sanderstad ?
