### ISSUE TITLE
Sync-DbaLoginPermission needs output

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3665]
-verbose aint cuttin it

**Comment by andreasjordan** [comment]
You mean like in Copy-DbaAgentJob (because they are both started by Sync-DbaAvailabilityGroup)? 
I will have a look at that.

**Comment by andreasjordan** [comment]
Command is now named Sync-DbaLoginPermission
Internal function Sync-Only is not called with all parameters
More work and testing needed

**Comment by potatoqualitee** [comment]
ohh we did add a progress bar at least. i can see why i keep procrastinating this one. there's a lot of permissions to output, including jobs

**Comment by andreasjordan** [comment]
I started with refactoring the command.
What kind of output would you like to be returned?

**Comment by potatoqualitee** [comment]
Thank you! I attempted to work on this but became overwhelmed. Something similar to the output of Start-DbaMigration.
