### ISSUE TITLE
Invoke-DbaSqlQuery -AppendServerInstance 

### ISSUE THREAD

**Issue by pollusb** [sqlcollaborative/dbatools#3668]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (0.9.343)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell

PS> 'SVR1','SVR2' | Invoke-DbaSqlQuery -Query 'select 1' -AppendServerInstance

Column1 ServerInstance
------- --------------
      1 Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]
      1 Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]

```

## Expected Behavior
It should provide the ServerInstance 

## Actual Behavior
It does not provide the ServerInstance anymore

## Environmental data
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by niphlod** [comment]
@pollusb : thanks for the catch
