### ISSUE TITLE
Copy-SqlCredential - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#367]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseSingularNouns|Warning|98|The cmdlet 'Get-SqlCredentials' uses a plural noun. A singular noun should be used instead.
PSAvoidUsingPlainTextForPassword|Warning|281|Parameter '$credentials' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSPossibleIncorrectComparisonWithNull|Warning|288|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|288|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|304|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|304|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|353|$null should be on the left side of equality comparisons.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
