### ISSUE TITLE
Log shipping commands have misspelled parameter

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#3671]
Parameter `ThressAlert` should be renamed to `ThresholdAlert` in all LS commands, then alias added for the `ThressAlert`.

Not to sure how we missed this in the review.

@sanderstad

**Comment by sqllensman** [comment]
The Parameter names have been updated but in Test-DbaLogShippingStatus the data set that is returned is still having a reference to BackupThresshold and RestoreThresshold

While these could be updated to more accurately reflect the actual names from sys.sp_help_log_shipping_monitor  (backup_threshold and restore_threshold) this would be a breaking change.

**Comment by wsmelton** [comment]
You use aliasing on the parameters for temporary support of the old parameter names.

**Comment by wsmelton** [comment]
Oh you mean property names? That can be handled with the default view command, it allows you to alias the property name as `Database as DatabaseName` or some similar syntax (can't recall right now).

**Comment by sqllensman** [comment]
I guess you mean Select-DefaultView using an InputObject or similar.  I can see Get-DbaComputerSystem does smething like this so I will try creating a non breaking update that can return borh the correct names and the misspelled names

**Comment by sqllensman** [comment]
The code can be fixed while continuing to return the misspelled names using something like:

                # Set up the custom object
                # Includes mispelled properties BackupThresshold and RestoreThresshold for backward compatiability. 
                $null = $collection.Add([PSCustomObject]@{
                        ComputerName          = $server.ComputerName
                        InstanceName          = $server.ServiceName
                        SqlInstance           = $server.DomainInstanceName
                        Database              = $result.DatabaseName
                        InstanceType          = switch ($result.IsPrimary) { $true { "Primary Instance" } $false { "Secondary Instance" } }
                        TimeSinceLastBackup   = $lastBackup
                        LastBackupFile        = $result.LastBackupFile
                        BackupThreshold       = $result.BackupThreshold
                        BackupThresshold      = $result.BackupThreshold
                        IsBackupAlertEnabled  = $result.IsBackupAlertEnabled
                        TimeSinceLastCopy     = $lastCopy
                        LastCopiedFile        = $result.LastCopiedFile
                        TimeSinceLastRestore  = $lastRestore
                        LastRestoredFile      = $result.LastRestoredFile
                        LastRestoredLatency   = $result.LastRestoredLatency
                        RestoreThreshold      = $result.RestoreThreshold
                        RestoreThresshold     = $result.RestoreThreshold
                        IsRestoreAlertEnabled = $result.IsRestoreAlertEnabled
                        Status                = $statusDetails -join ","
                    })

            }

            if ($Simple) {
                return $collection | Select-Object SqlInstance, Database, InstanceType, Status
            }
            else {
                return $collection | Select-DefaultView -ExcludeProperty BackupThreshold, RestoreThreshold
            }

The default view will still return BackupThresshold and RestoreThresshold but the correct names would also be available if Select * is used

Is this what is desired?

**Comment by wsmelton** [comment]
I would just say we correct the misspelled property names...not really much use in keeping them around. It is only a breaking change if they were used to begin with and I can't recall anyone bring it up in another issue.

I'd prefer to just correct the spelling vs having two with the same value. It is something when we get to 1.0 release we likely won't remember to correct anyway.
