### ISSUE TITLE
Change the sort order for reading the logs to speed up Restore-DbaDatabase

### ISSUE THREAD

**Issue by Tonyw72** [sqlcollaborative/dbatools#3683]
When reading through the log file it takes a long time to determine where to start applying them to the backup.

Ex. Using Ola's Maintenance solution, we do weekly fulls, daily diffs and Logs every five minutes and keep 192h worth of backups online. This keeps 2 fulls, 8 diffs and 2304 log files online.
When using `Restore-DbaDatabase -SqlInstance $dest -Path $path -MaintenanceSolutionBackup ` it correctly identifies the latest FULL & DIFF, but starts looking through the logs at the very beginning :( In most cases scanning through the last 7 days worth, at least 2016 files, but if it started from the other end, it could get to the first log file to apply sooner

Another option would be to grab the second to last DIFF/FULL and use the start date of that backup to limit the quantity of log backups to scan.

using dbatools v. 9.348

**Comment by wsmelton** [comment]
But it has to scan the log files to find the LSN. It does not even read the file properties itself to know date of the file itself. Then you get into what file date property to use (last accessed, last modified, last written, created).

**Comment by wsmelton** [comment]
If you want to limit the scanning you can pull the backup history and pass that to the command. It will build an object of the files it needs for restore just from that information.

**Comment by Zhunya** [comment]
do this related to #3704 ?

**Comment by niphlod** [comment]
yeah, it's related, this as a duplicate. @Tonyw72 , look into #3704 for further updates.
