### ISSUE TITLE
Set-DbaTempDbConfiguration will not relocate files

### ISSUE THREAD

**Issue by LeedsDBA** [sqlcollaborative/dbatools#3684]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell

#Show current TempDB files:
Invoke-DbaSqlCmd -SqlInstance SqlServer01 -Query "SELECT * FROM sys.master_Files WHERE database_id=db_id('tempdb')" | FT

#Set TempDB to reside at P:\TempDB (for data AND logs):
Set-DbaTempDbConfiguration -SqlInstance SqlServer01 -DataPath P:\TempDB -LogPath P:\TempDB -DataFileSizeMB 4096 -DataFileGrowthMB 1024 -DataFileCount 4 -Verbose

```

## Expected Behavior

In this example, all of my data files live at P:\TempDB, but my log file is still on C-drive. Expected behaviour: to set TempDB config to relocate the Log files (as well as the Data files) to be at P:\TempDB

## Actual Behavior

![image](https://user-images.githubusercontent.com/4063268/41426153-bef16e8c-6ffa-11e8-8cd6-b22d2dda0fdf.png)
Throws a warning to say that the *Size* is the same - However, the location is different so would expect it to spot that and relocate. I would understand better if the function was called Set-DbaTempDbSize that it would only deal with size, but this suggests it's the whole configuration of TempDB

## Environmental data

- PowerShell

Name                           |Value                                                                                                                                                                   
----                           |-----                                                                                                                                                                   
PSVersion                      |5.1.14409.1012                                                                                                                                                          
PSEdition                      |Desktop                                                                                                                                                                 
PSCompatibleVersions           |{1.0, 2.0, 3.0, 4.0...}                                                                                                                                                 
BuildVersion                   |10.0.14409.1012                                                                                                                                                         
CLRVersion                     |4.0.30319.42000                                                                                                                                                         
WSManStackVersion              |3.0                                                                                                                                                                     
PSRemotingProtocolVersion      |2.3                                                                                                                                                                     
SerializationVersion           |1.1.0.1

- SQL Server: 

Microsoft SQL Server 2012 (SP3) (KB3072779) - 11.0.6020.0 (X64)   Oct 20 2015 15:36:27   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by wsmelton** [comment]
Confirmed this is because of this section of code

```if ($EqualCount -gt 0) {
            Stop-Function -Message "Current tempdb not suitable to be reconfigured. The current tempdb is the same size as the specified DataFileSizeMB."
            return
        }```
