### ISSUE TITLE
  Copy-SqlDatabase - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#369]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSAvoidUsingEmptyCatchBlock|Warning|237|Empty catch block is used. Please use Write-Error or throw statements in catch blocks.
PSPossibleIncorrectComparisonWithNull|Warning|377|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|377|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|512|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|512|$null should be on the left side of equality comparisons.
PSUseShouldProcessForStateChangingFunctions|Warning|531|Function ?Start-SqlFileTransfer? has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSAvoidUsingCmdletAliases|Warning|561|'where' is an alias of 'Where-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSAvoidUsingWriteHost|Warning|571|File 'Copy-SqlDatabase.ps1' uses Write-Host. Avoid using Write-Host because it might not work in all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, captured, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
PSUseShouldProcessForStateChangingFunctions|Warning|592|Function ?Start-SqlDetachAttach? has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSPossibleIncorrectComparisonWithNull|Warning|614|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|614|$null should be on the left side of equality comparisons.
PSUseOutputTypeCorrectly|Information|635|The cmdlet 'Start-SqlDetachAttach' returns an object of type 'System.String' but this type is not declared in the OutputType attribute.
PSUseOutputTypeCorrectly|Information|648|The cmdlet 'Start-SqlDetachAttach' returns an object of type 'System.String' but this type is not declared in the OutputType attribute.
PSUseOutputTypeCorrectly|Information|655|The cmdlet 'Start-SqlDetachAttach' returns an object of type 'System.String' but this type is not declared in the OutputType attribute.
PSUseDeclaredVarsMoreThanAssignments|Warning|866|The variable 'alldbelapsed' is assigned but never used.
PSUseDeclaredVarsMoreThanAssignments|Warning|872|The variable 'dbelapsed' is assigned but never used.
PSPossibleIncorrectComparisonWithNull|Warning|940|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|945|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|1048|$null should be on the left side of equality comparisons.
PSUseOutputTypeCorrectly|Information|1166|The cmdlet 'Copy-SqlDatabase' returns an object of type 'System.String' but this type is not declared in the OutputType attribute.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
