### ISSUE TITLE
Copy-SqlExtendedEvent - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#370]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSPossibleIncorrectComparisonWithNull|Warning|97|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|133|$null should be on the left side of equality comparisons.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
