### ISSUE TITLE
Unable to filter DbaDateTime data types with Powershell DateTime data types

### ISSUE THREAD

**Issue by bawedy** [sqlcollaborative/dbatools#3709]
### Before submitting a bug report:

This issue occurred on the latest stable version of DBATools and was also reproduced by Simone Bizzotto

## Steps to Reproduce

`Get-DbaLastBackup -sqlinstance sqlinstance | where-object {($_.LastFullBackup -lt (Get-date).AddDays(-1) -and $_.LastDiffBackup -lt (Get-Date).AddDays(-1)  -and $_.LastLogBackup -lt (Get-Date).AddDays(-1) )}`

## Expected Behavior

I expected the Powershell code to return databases that haven't been backed up within 24 hours on "sqlinstance"

## Actual Behavior

It seems that in this instance data type Sqlcollaborative.Dbatools.Utility.DbaDateTime can not be used for comparison against Powershell's System.DateTime data type.

> At line:2 char:19
where-object {($_.LastFullBackup -lt (Get-Date).AddDays(-1) `
CategoryInfo          : OperationStopped: (:) [], ArgumentException
FullyQualifiedErrorId : System.ArgumentException

> Object must be of type DateTime.
At line:2 char:19
where-object {($_.LastFullBackup -lt (Get-Date).AddDays(-1) `
              

> CategoryInfo : OperationStopped: (:) [], ArgumentException
FullyQualifiedErrorId : System.ArgumentException

### PowerShell:

PSVersion                              5.1.14409.1012
PSEdition                               Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                           10.0.14409.1012
CLRVersion                             4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion  2.3
SerializationVersion                1.1.0.1

 ### SQL Server: 
Microsoft SQL Server 2012 (SP3-GDR) (KB4057115) - 11.0.6260.1 (X64)   Jan  9 2018 21:31:12   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

## Workaround

Amending the code in the following way... works around the issue
`Get-DbaLastBackup -SqlInstance sqlinstance  | where-object {$(get-date $_.LastFullBackup) -lt $((get-date).Adddays(-1)) -and $(get-date $_.LastDiffBackup) -lt $((get-date).Adddays(-1)) -and $(get-date $_.LastLogBackup) -lt $((get-date).Adddays(-1))}`

**Comment by niphlod** [comment]
@FriedrichWeinmann , @zippy1981 : is this a shortcoming on Sqlcollaborative.Dbatools.Utility.DbaDateTime ?

**Comment by FriedrichWeinmann** [comment]
Ah drat, I friggin' hate that issue :(
Apologies for the hassle, PowerShell has a hardcoded comparison logic for datetime that ... requires some careful workarounds. Basically, order matters when it comes to the operators:

```powershell
Get-DbaLastBackup -sqlinstance sql2017 | where-object {((Get-date).AddDays(-1) -ge $_.LastFullBackup -and (Get-Date).AddDays(-1) -ge $_.LastDiffBackup -and (Get-Date).AddDays(-1) -ge $_.LastLogBackup )}
```

This will work without an error.
Unfortunately, given that even Bruce Payette couldn't find a way around this, the only way to remove order sensitivity from datetime comparisons is to rip out the custom types and put back default datetime (and suffer the display style pain and possibly breaking existing reports).

**Comment by bawedy** [comment]
Both, thanks very much for looking into this and for the explanation.
 I'll close the issue now

Thanks again

**Comment by zippy1981** [comment]
@FriedrichWeinmann I added some overloads and made the implicit casts explicit. I will add some pester tests later. 

https://github.com/zippy1981/dbatools/tree/testing/DateTimeBase

Then this happened:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/146930/42406792-e1bf2b64-817c-11e8-969e-bc6cdecd838a.png">

I need to overload -lt and -gt. 

Explict casts in C# work implicitly in powershell.  I believe we could also use `TypeConverterAttribute` and a custom Type converter like so:

https://msdn.microsoft.com/en-us/library/ayybcxe5.aspx

**Comment by FriedrichWeinmann** [comment]
Well ... hate to say it, but the equality test does work just fine (wasn't too specific there)
All operators that use `.CompareTo()` (such as `-gt` or `-le`) are the problem.
