### ISSUE TITLE
Copy-SqlLinkedServer - Script Analyzer Test failure   

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#371]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseSingularNouns|Warning|96|The cmdlet 'Get-LinkedServerLogins' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|253|The cmdlet 'Copy-SqlLinkedServers' uses a plural noun. A singular noun should be used instead.
PSPossibleIncorrectComparisonWithNull|Warning|264|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|264|$null should be on the left side of equality comparisons.
PSAvoidUsingEmptyCatchBlock|Warning|279|Empty catch block is used. Please use Write-Error or throw statements in catch blocks.
PSPossibleIncorrectComparisonWithNull|Warning|293|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|293|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|372|$null should be on the left side of equality comparisons.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
