### ISSUE TITLE
Add timestamp to restore-dbadatabase output

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#3718]
Request at SQLGrillen - Add the start and end times (or duration) to the restore output

Should be easy enough to add to https://github.com/sqlcollaborative/dbatools/blob/development/functions/Restore-DbaDatabase.ps1#L581

**Comment by Stuart-Moore** [comment]
Somewhere around here would be better
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Invoke-DbaAdvancedRestore.ps1#L316

Rob's link is just for WITH RECOVERY ;)

remember that you've often gotten > 1 restores per db, so you'd need to
work out what you actually want to return when (ie; for each restore (full,
diff, log), or adding a wrapper container around all the restores for each
database).
