### ISSUE TITLE
Copy-SqlLogin - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#372]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSAvoidUsingPlainTextForPassword|Warning|117|Parameter '$SourceSqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSAvoidUsingPlainTextForPassword|Warning|118|Parameter '$DestinationSqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSPossibleIncorrectComparisonWithNull|Warning|139|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|139|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|171|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|171|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|180|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|180|$null should be on the left side of equality comparisons.
PSAvoidUsingCmdletAliases|Warning|196|'Where' is an alias of 'Where-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSAvoidUsingCmdletAliases|Warning|205|'Where' is an alias of 'Where-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSPossibleIncorrectComparisonWithNull|Warning|223|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|223|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|242|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|242|$null should be on the left side of equality comparisons.
PSAvoidUsingCmdletAliases|Warning|285|'%' is an alias of 'ForEach-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSUseDeclaredVarsMoreThanAssignments|Warning|285|The variable 'passtring' is assigned but never used.
PSUseDeclaredVarsMoreThanAssignments|Warning|299|The variable 'sid' is assigned but never used.
PSAvoidUsingCmdletAliases|Warning|299|'%' is an alias of 'ForEach-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
