### ISSUE TITLE
Restore-DbaDatabase and AzureCredential

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3734]
I've received two bug reports about the same issue regarding AzureCredential. Anyone have time to take a look? Should be a straightforward fix, prolly.

````
First of all thank you for maintaining such a great module. it's really impressive !
During some tests with restore I found that restore-dbadatabase where restoring from https:// adress with -AzureCredential provided doesn't add to restore statement WITH CREDENTIAL - that's why it uanble to restore a backup.

example statement:
Restore-DbaDatabase -SqlInstance 'SQLSERVER' -Path 'https://abc.blob.core.windows.net/defc/test_backup.bak' -AzureCredential 'test_credential' -OutputScriptOnly
````

**Comment by deanwest** [comment]
@potatoqualitee I have tested the Restore-Dbadatabase on version 0.9.385 and I have been able to restore from azure blob when specifying the URL for the restore. 

![image](https://user-images.githubusercontent.com/34652355/44030040-7069dd36-9ef7-11e8-893e-dd8976c52a3f.png)

When I provide a list of URL's for to Restore-Dbadatabase, the restore process fails on Test-DBABackupInformation stating that the backup file cannot be read. 

![image](https://user-images.githubusercontent.com/34652355/44029868-d8f7cb84-9ef6-11e8-94a3-ae9c9546129b.png)

Looking at Test-DBABackupInformation, I can see that the test validates the backup file paths by using the function Test-DbaSqlPath and this function will fail every time someone passes through a URL.

Below is the test inside 

Test all backups readable  

   $allpaths = $DbHistory \| Select-Object -ExpandProperty FullName
   $allpaths_validity =   Test-DbaSqlPath -SqlInstance   $RestoreInstance -Path $allpaths
   foreach ($path in   $allpaths_validity) {
   if ($path.FileExists   -eq $false) {
   Write-Message -Message "Backup   File $($path.FilePath) cannot be read" -Level Warning
   $VerificationErrors++


I would consider myself a newbie, when it comes to powershell and cannot offer a fix. Would love to see how to fix this issue. I have an idea but do not know how to implement it.

**Below is my testing script:**

# Login into Azure
Login-AzureRmAccount 

$databasename = 'test'
$rg1 = 'ResourceGroupName'
$sourceAccName = 'StorageAccountName'
$containername = $databasename

# Get access key for the Storage account
$sourcekey1 = (Get-AzureRmStorageAccountKey -ResourceGroupName $rg1 -Name $sourceAccName).Value[0]
$sourceCtx = New-AzureStorageContext -StorageAccountName $sourceAccName -StorageAccountKey $sourcekey1

# Get the url for all the blobs in the storage account. 
$file = (Get-AzureStorageBlob -Container $containerName -Context $sourceCtx).ICloudBlob.uri.AbsoluteUri

# Restore database using the url passed through
$file | Restore-DbaDatabase -SqlInstance ServerName -useDestinationDefaultDirectories -DestinationFilePrefix _test -RestoredDatabaseNamePrefix _deantest -AzureCredential 'AzureStorageCred' -WithReplace -verbose

**Comment by niphlod** [comment]
we do also have unittest so hopefully this has been fixed and will never reoccurr
