### ISSUE TITLE
Get-DbaSqlProductKey - SqlInstances Parameter

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#3737]
### Before submitting a bug report:
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
Get-DbaSqlProductKey -SqlInstances 'Server1', 'Server2
```

## Expected Behavior
Return versions only for the default instances on Server1 and Server2. 

## Actual Behavior
If there are disabled instances on Server2 it attempts to connect to them and gets can't connect messages. If Server1 has multiple instances, it will return information for all instances not just Server1.

## Environmental data
 - PowerShell:
PSVersion                      5.1.14393.2248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - SQL Server: Multiple versions

**Comment by awickham10** [comment]
Maybe SqlInstances needs to be renamed to ComputerName and a new SqlInstance parameter needs to be added that is more in alignment with the rest of the commands.

**Comment by wsmelton** [comment]
This is a command that has never had our new standards applied so it needs a large amount of work.

**Comment by wsmelton** [comment]
Ha, it is even still using the write commands for verbose, does not use the CMS commands or object type...would almost say that needs to be completely rewritten to utilize more commands and internal functions we have available now... // @potatoqualitee
