### ISSUE TITLE
Remove-DbaDbSnapshot Force Prompting

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#3740]
### Before submitting a bug report:
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
Remove-DbaDbSnapshot -SqlInstance 'Server1' -Snapshot 'TestSnapshot' -Force -EnableException
```

## Expected Behavior
Remove snapshot, drop any connections if necessary, do not prompt to continue.

## Actual Behavior
Force now always prompts to "KillDatabase", even if using -Confirm:$false

## Environmental data

 - PowerShell:
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by awickham10** [comment]
We just updated from 0.9.342 to 0.9.360 and this changed. We were just using -Force, now we have to remove -Force and add -Confirm:$false. I'm not sure if this was expected behavior change or not.

**Comment by niphlod** [comment]
okay, behaviour definitely changed. IMHO if -Force is passed, no confirm should be needed. Also, -Confirm should just need to be used in tandem with -Whatif, as requiring to pass -Confirm:$false just looks stupid. I thought we agreed on this a long time ago, but just to confirm (pun intended): is what I just said still valid ? @potatoqualitee , @wsmelton , @FriedrichWeinmann , others ......

**Comment by potatoqualitee** [comment]
i agree that -Confirm:$false blows but ive kinda been accepting it lately. I do agree that this is an issue that needs to be better handled but i havent figured out how yet. -Force, probably should change the confirmpreference, perhaps

**Comment by wsmelton** [comment]
You have confirm because it has `SupportShouldProcess` there is no way around that because we require it for commands of this nature.

Can't you adjust the the requirement to confirm by setting the `ConfirmImpact` or something?

**Comment by potatoqualitee** [comment]
Remove is drastic and I'd prefer the confirmation stay in like Remove-DbaDatabase. However, I see how it's not as drastic as removing a database. If we do make changes, we can leave in all the confirmation support, but remove the high impact.

**Comment by potatoqualitee** [comment]
alternatively, we can make false set the confirm prefs to chill

**Comment by wsmelton** [comment]
The same could he said is I'm using remove why do I need to supply force parameter at all?

You can just confirm to false for the same effect.

**Comment by potatoqualitee** [comment]
Force is used to kill connections. $db.Drop() will fail if connections exist.

**Comment by niphlod** [comment]
right! kay then

Il giorno gio 19 lug 2018 alle ore 17:00 Chrissy LeMaire <
notifications@github.com> ha scritto:
