### ISSUE TITLE
copy-dbacredential not copying correct password in SQL Server 2016 SP2

### ISSUE THREAD

**Issue by fvanderhaegen** [sqlcollaborative/dbatools#3746]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
Copy-DbaCredential -Source $sourceInstance -Destination $destinationInstance -EnableException

## Expected Behavior

Credential are copied to the destination with correct password

## Actual Behavior
The Credential is copied to the destination but when I create a Proxy with that credential and assign it to a CmdExec-job I get following error:

Date		28/06/2018 16:43:42
Log		Job History (synctest)

Step ID		1
Server		SQLTEST-2
Job Name		synctest
Step Name		sync
Duration		00:00:00
Sql Severity	0
Sql Message ID	0
Operator Emailed	
Operator Net sent	
Operator Paged	
Retries Attempted	0

Message
Unable to start execution of step 1 (reason: Error authenticating proxy domain\myUser, system error: The user name or password is incorrect.).  The step failed.

## Environmental data

 - PowerShell:                                                                                                                                                    
PSVersion                      4.0                                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                
BuildVersion                   6.3.9600.18968                                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                                           
PSRemotingProtocolVersion      2.2 

 - SQL Server: 
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by wsmelton** [comment]
@fvanderhaegen it is documented in the help on the pre-requisites that have to be in place for this to properly decrypt the password. It is basically a best effort but in most cases we are restricted in making it work 100% of the time.

If you run it from the source machine it generally works properly as it is able to decrypt the password. (e.g. Utilizing `Invoke-Command` would allow you to remotely execute it on the local machine, pending the module being installed on the local system).
