### ISSUE TITLE
Copy-SqlSsisCatalog - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#375]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseBOMForUnicodeEncodedFile|Warning||Missing BOM encoding for non-ASCII encoded file 'Copy-SqlSsisCatalog.ps1'
PSPossibleIncorrectComparisonWithNull|Warning|163|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|163|$null should be on the left side of equality comparisons.
PSUseShouldProcessForStateChangingFunctions|Warning|191|Function ?New-CatalogFolder? has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSUseShouldProcessForStateChangingFunctions|Warning|222|Function ?New-FolderEnvironment? has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSUseShouldProcessForStateChangingFunctions|Warning|256|Function ?New-SSISDBCatalog? has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSAvoidUsingEmptyCatchBlock|Warning|504|Empty catch block is used. Please use Write-Error or throw statements in catch blocks.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
