### ISSUE TITLE
CsvSqlimport - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#376]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSShouldProcess|Warning|1|'Import-CsvToSql' calls ShouldProcess/ShouldContinue but does not have the ShouldProcess attribute.
PSAvoidUsingPlainTextForPassword|Warning|147|Parameter '$SqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSAvoidUsingPlainTextForPassword|Warning|169|Parameter '$SqlCredentialPath' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSPossibleIncorrectComparisonWithNull|Warning|185|$null should be on the left side of equality comparisons.
PSUseApprovedVerbs|Warning|235|The cmdlet 'Parse-OleQuery' uses an unapproved verb.
PSPossibleIncorrectComparisonWithNull|Warning|275|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|275|$null should be on the left side of equality comparisons.
PSAvoidUsingPlainTextForPassword|Warning|316|Parameter '$SqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSUseSingularNouns|Warning|344|The cmdlet 'Get-SqlDatabases' uses a plural noun. A singular noun should be used instead.
PSAvoidUsingPlainTextForPassword|Warning|362|Parameter '$SqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSUseSingularNouns|Warning|389|The cmdlet 'Get-SqlTables' uses a plural noun. A singular noun should be used instead.
PSAvoidUsingPlainTextForPassword|Warning|408|Parameter '$SqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSUseSingularNouns|Warning|436|The cmdlet 'Get-Columns' uses a plural noun. A singular noun should be used instead.
PSShouldProcess|Warning|436|'Get-Columns' calls ShouldProcess/ShouldContinue but does not have the ShouldProcess attribute.
PSShouldProcess|Warning|511|'Write-Schemaini' calls ShouldProcess/ShouldContinue but does not have the ShouldProcess attribute.
PSUseShouldProcessForStateChangingFunctions|Warning|589|Function ?New-SqlTable? has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSPossibleIncorrectComparisonWithNull|Warning|740|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|787|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|794|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|801|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|974|$null should be on the left side of equality comparisons.
PSUseOutputTypeCorrectly|Information|1051|The cmdlet 'Import-CsvToSql' returns an object of type 'System.String' but this type is not declared in the OutputType attribute.
PSPossibleIncorrectComparisonWithNull|Warning|1175|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|1196|$null should be on the left side of equality comparisons.
PSUseDeclaredVarsMoreThanAssignments|Warning|1226|The variable 'newrow' is assigned but never used.
PSAvoidUsingEmptyCatchBlock|Warning|1395|Empty catch block is used. Please use Write-Error or throw statements in catch blocks.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
