### ISSUE TITLE
Copy-DbaDatabase not reporting restore progress

### ISSUE THREAD

**Issue by ShaunJStu** [sqlcollaborative/dbatools#3769]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

Run Copy-DbaDatabase to copy a database from one server to another. The Backup portion does show a progress bar. The Restore portion shows a progress bar that stays at zero the entire time.

![copy-dbadatabaserestoreoutput](https://user-images.githubusercontent.com/37596496/42385144-c7701afc-80f0-11e8-91ef-ea3b7f4f5636.png)

**Comment by ShaunJStu** [comment]
I updated dbatools and the restore progress bar now displays. Note that the dbatools module version number never changed. It was 0.9.369 before I updated and 0.9.369 after I updated.

**Comment by maroliict** [comment]
We found that when running start-DbaMigration from a script (as part of an automation project),  the copy-dbadatabase does show a progress indicator which it can't (no screen). We went in the copy-dbadatabase  script and added a # in front of line 273. After this the backup as well as the restore did finish properly. 

It would come in handy if we could surpress those progress indicators.
