### ISSUE TITLE
DynamicParams - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#377]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseSingularNouns|Warning|9|The cmdlet 'Get-ParamSqlServerConfigs' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|56|The cmdlet 'Get-ParamSqlDatabases' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|203|The cmdlet 'Get-ParamSqlLogins' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|300|The cmdlet 'Get-ParamSqlServerRoles' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|348|The cmdlet 'Get-ParamSqlProcessHosts' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|390|The cmdlet 'Get-ParamSqlProcessPrograms' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|432|The cmdlet 'Get-ParamSqlSpids' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|475|The cmdlet 'Get-ParamSqlCredentials' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|521|The cmdlet 'Get-ParamSqlServerAudits' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|567|The cmdlet 'Get-ParamSqlServerServerAuditSpecifications' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|613|The cmdlet 'Get-ParamSqlBackupDevices' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|658|The cmdlet 'Get-ParamSqlServerEndpoints' uses a plural noun. A singular noun should be used instead.
PSUseDeclaredVarsMoreThanAssignments|Warning|678|The variable 'usernedponit' is assigned but never used.
PSUseSingularNouns|Warning|705|The cmdlet 'Get-ParamSqlLinkedServers' uses a plural noun. A singular noun should be used instead.
PSPossibleIncorrectComparisonWithNull|Warning|773|$null should be on the left side of equality comparisons.
PSUseSingularNouns|Warning|848|The cmdlet 'Get-ParamSqlExtendedEvents' uses a plural noun. A singular noun should be used instead.
PSPossibleIncorrectComparisonWithNull|Warning|863|$null should be on the left side of equality comparisons.
PSUseSingularNouns|Warning|991|The cmdlet 'Get-ParamSqlCmsGroups' uses a plural noun. A singular noun should be used instead.
PSPossibleIncorrectComparisonWithNull|Warning|1008|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|1021|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|1031|$null should be on the left side of equality comparisons.
PSUseSingularNouns|Warning|1048|The cmdlet 'Get-ParamSqlServerTriggers' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1095|The cmdlet 'Get-ParamSqlCustomErrors' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1142|The cmdlet 'Get-ParamSqlDatabaseAssemblies' uses a plural noun. A singular noun should be used instead.
PSAvoidUsingEmptyCatchBlock|Warning|1177|Empty catch block is used. Please use Write-Error or throw statements in catch blocks.
PSUseSingularNouns|Warning|1206|The cmdlet 'Get-ParamSqlDataCollectionSets' uses a plural noun. A singular noun should be used instead.
PSPossibleIncorrectComparisonWithNull|Warning|1224|$null should be on the left side of equality comparisons.
PSUseSingularNouns|Warning|1264|The cmdlet 'Get-ParamSqlAlerts' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1307|The cmdlet 'Get-ParamSqlOperators' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1349|The cmdlet 'Get-ParamSqlOperatorCategories' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1392|The cmdlet 'Get-ParamSqlProxyAccounts' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1436|The cmdlet 'Get-ParamSqlSharedSchedules' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1478|The cmdlet 'Get-ParamSqlJobCategories' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1520|The cmdlet 'Get-ParamSqlAlertCategories' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1562|The cmdlet 'Get-ParamSqlTargetServers' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1604|The cmdlet 'Get-ParamSqlTargetServerGroups' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1646|The cmdlet 'Get-ParamSqlJobs' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1690|The cmdlet 'Get-ParamSqlAgentCategories' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1732|The cmdlet 'Get-ParamSqlDatabaseFileTypes' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1847|The cmdlet 'Get-ParamSqlMaintenancePlans' uses a plural noun. A singular noun should be used instead.
PSUseSingularNouns|Warning|1892|The cmdlet 'Get-ParamSqlAvailabilityGroups' uses a plural noun. A singular noun should be used instead.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
