### ISSUE TITLE
Select-DefaultView impacts performance

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3771]
I'm using Select-DefaultView in another module that I'm writing and I was like "why is this call so slow?" when I switched from `Select-DefaultView` to `Select-Object`, it was 10000x faster :(

Since Select-DefaultView is something we use so much, any optimizations to it would be welcomed

**Comment by potatoqualitee** [comment]
I don't recall if Select-DbaObject will solve this, it may

**Comment by zippy1981** [comment]
![image](https://user-images.githubusercontent.com/146930/42406294-b925e0bc-8172-11e8-9a0d-af76d7e09af8.png)

**Comment by FriedrichWeinmann** [comment]
Hi Chrissy,

would you mind being a bit more specific than `10000x faster`?
Specific, measured performance results really do have their place ^^

That said: No surprise, Sherlock!
`Select-DefaultView` uses lots of `Add-Member` calls.

If all you want is to add some renamed properties, then yes, Select-Object or Select-DbaObject will far outperform it.
If it's about adding the PSStandardMembers ... sorry, that performance cost is always equally bad, no way around that call :(

**Comment by niphlod** [comment]
well, it also depends on how the call is made, remember that with a lot of results just passing down the `|` has a noticeable performance hit.

**Comment by dragonwolf83** [comment]
Is `Select-DefaultView` primary use case to set the PSTypeName and PSStandardMembers? There are some better ways to do that with a standard `Select-Object`.

`Add-Member` is likely the root cause. When you use it to add properties one-by-one, it takes a huge hit.

**Comment by potatoqualitee** [comment]
It turned out I was doing duplicate calls but still, i'd love some optimization on these commands.
