### ISSUE TITLE
  Export-SqlLogin  Script Analyzer Test failure 

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#378]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSAvoidUsingPlainTextForPassword|Warning|104|Parameter '$SqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSPossibleIncorrectComparisonWithNull|Warning|164|$null should be on the left side of equality comparisons.
PSUseDeclaredVarsMoreThanAssignments|Warning|243|The variable 'passtring' is assigned but never used.
PSAvoidUsingCmdletAliases|Warning|243|'%' is an alias of 'ForEach-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSUseDeclaredVarsMoreThanAssignments|Warning|247|The variable 'sid' is assigned but never used.
PSAvoidUsingCmdletAliases|Warning|293|'Where' is an alias of 'Where-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSUseDeclaredVarsMoreThanAssignments|Warning|298|The variable 'jobname' is assigned but never used.
PSUseDeclaredVarsMoreThanAssignments|Warning|347|The variable 'dblogin' is assigned but never used.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
