### ISSUE TITLE
Invoke-DbaSqlQuery fails to use proper Windows credentials

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#3780]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
$cred = get-credential foo\foobar
$cred
whoami
$srv = connect-dbainstance -sqlinstance bar -credential $cred
$srv.query('select suser_name()')
invoke-dbasqlquery -sqlinstance $srv -query 'select suser_name()'
invoke-dbasqlquery -sqlinstance bar -query 'select suser_name()' -Credential $cred
```

## Expected Behavior

foo\foobar all the way

## Actual Behavior

Last statement is using current user instead of credentials

```
PS C:\Users\user123> import-module C:\git\dbatools\dbatools
PS C:\Users\user123> $cred = get-credential
PS C:\Users\user123> $cred

UserName                           Password
--------                           --------
foo\foobar System.Security.SecureString


PS C:\Users\user123> whoami
foo\user123
PS C:\Users\user123> $srv = connect-dbainstance -sqlinstance bar -credential $cred
PS C:\Users\user123> $srv.query('select suser_name()')

Column1
-------
foo\foobar


PS C:\Users\user123> invoke-dbasqlquery -sqlinstance $srv -query 'select suser_name()'

Column1
-------
foo\foobar


PS C:\Users\user123> invoke-dbasqlquery -sqlinstance bar -query 'select suser_name()' -Credential $cred

Column1
-------
foo\user123
```

## Environmental data

 - PowerShell: 
Name                           Value
----                           -----
PSVersion                      5.1.15063.1088
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1088
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: Microsoft SQL Server 2008 (SP4-GDR) (KB4057114) - 10.0.6556.0 (X64) 
	Dec 28 2017 15:21:01 
	Copyright (c) 1988-2008 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (VM)

**Comment by Zhunya** [comment]
You did not specified credentials in last `invoke-dbasqlquery`

**Comment by nvarscar** [comment]
> You did not specified credentials in last invoke-dbasqlquery
That's actually a typo. Thanks for noticing - fixing it now.

**Comment by nvarscar** [comment]
Just to clarify, the issue is still there, the typo was in my initial comment, not the actual code that causes the issue.

**Comment by niphlod** [comment]
just as a sidenote for the "casual bugreader", turns out that the problem sits in connect-sqlinstance. we'll keep this open till it gets fixed
