### ISSUE TITLE
Get-DbaDiskSpace - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#379]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSAvoidUsingPlainTextForPassword|Warning|128|Parameter '$SqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSAvoidUsingWMICmdlet|Warning|182|File 'Get-DbaDiskSpace.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
PSUseDeclaredVarsMoreThanAssignments|Warning|187|The variable 'query' is assigned but never used.
PSAvoidUsingWMICmdlet|Warning|189|File 'Get-DbaDiskSpace.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
PSAvoidUsingWMICmdlet|Warning|210|File 'Get-DbaDiskSpace.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
PSUseOutputTypeCorrectly|Information|350|The cmdlet 'Get-DbaDiskSpace' returns an object of type 'System.Collections.ArrayList' but this type is not declared in the OutputType attribute.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
