### ISSUE TITLE
New Command: Get-DbaAGBackupHistory

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#3799]
Command will need to provide the ability to pull backup history from all replicas involved in the AG, irrespective of the backup preference.

Original issue: #1712

**Comment by potatoqualitee** [comment]
can you tell me how this woudl be written in theory?

**Comment by potatoqualitee** [comment]
get a list of Replicas and DBs and pipe to BackupHistory?

**Comment by wsmelton** [comment]
In theory...

You would gather the backup history for a given database, or databases for a given AG, from every replica involved (primary and all secondaries). This should be able to use the commands around the special backup history object that @Stuart-Moore created around his work. 

You then would just sort each database based on the LSN and need to find the latest full, log backups, etc. in order to build the restore path that is taken to restore each database.

**Comment by wsmelton** [comment]
I don't think you will be able to use the backup history command being that it will not take into account that backups can be stretched across multiple replicas. I recall it only handled backup history on a given instance/replica. This will require some magical parts that will build the backup object across all replicas, mainly for the log backups. Differential backups can only be taken from the primary, but full and log can be taken as copy-only from any replica in the AG.

I think you can also shortcut this by validating the backup preference of the AG; if it is set to primary only then backup history for the databases in that AG should only exist on the primary replica.

**Comment by nvarscar** [comment]
> I think you can also shortcut this by validating the backup preference of the AG; if it is set to primary only then backup history for the databases in that AG should only exist on the primary replica.

That is indeed the case, but only until next failover. New primary replica would know nothing about past backups. This is why it's important to get backup information from all replicas that could possible be a primary.

And again, this will only be possible if the caller machine has an ability to address all the members of the AG using SERVER\INSTANCE (meaning Browser or SqlAliases). But that kind of makes sense, considering that even SSMS is having these problems.

Theoretically, we could get backup history from each instance and hope that shortest restoration path is still traceable. Backup forks should be identical across the cluster, which should help with identifying the proper backup sets.
This works surprisingly well when backups are shared between two AG replicas:
```powershell
Get-DbaBackupHistory -SqlInstance AG1, AG2 -Database AG1Database1 | restore-dbadatabase -SqlInstance SERVER3 -databasename newdb -OutputScriptOnly
```
The function was able to recognize backups from both nodes and build a proper restore scenario.
So, for starters, this command might indeed just be a wrapper that "gets a list of Replicas and DBs and pipes to BackupHistory".

**Comment by wsmelton** [comment]
Yeah, it would likely be safer to just pull history from all replicas.

However on the wrapper the only problem I have with that is control of the object output. I think since this will become a more popular command it would be best to potentially duplicate, maybe, what Get-DbaBackupHistory does to a degree so that does not also break this command. {Believe me when this gets out in the wild it will become heavily used!!! 😁 }

**Comment by potatoqualitee** [comment]
i dont think this is in my lane, so won't set it for dbatools 1.0. if it ends up there, that'd be fab, but it wont be on my radar.

**Comment by andreasjordan** [comment]
Lets link #6799 here.

**Comment by wsmelton** [comment]
@andreasjordan if you believe the PR is going to resolve issues please link them from the PR itself so the issues will get closed properly.

[doc reference](https://github.blog/2013-05-14-closing-issues-via-pull-requests/#:~:text=can%20now%20close%20an%20issue%20from%20a%20Pull,automatically%20be%20closed%20when%20the%20PR%20is%20merged)
