### ISSUE TITLE
Reset-SqlAdmin - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#380]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSAvoidUsingCmdletAliases|Warning|211|'Select' is an alias of 'Select-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSAvoidUsingWMICmdlet|Warning|221|File 'Reset-SqlAdmin.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
PSPossibleIncorrectComparisonWithNull|Warning|222|$null should be on the left side of equality comparisons.
PSUseDeclaredVarsMoreThanAssignments|Warning|260|The variable 'sid' is assigned but never used.
PSPossibleIncorrectComparisonWithNull|Warning|277|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|298|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|316|$null should be on the left side of equality comparisons.
PSAvoidUsingWMICmdlet|Warning|318|File 'Reset-SqlAdmin.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
