### ISSUE TITLE
Set-DbaPowerPlan - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#381]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseShouldProcessForStateChangingFunctions|Warning|71|Function 'Set-DbaPowerPlan' has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSAvoidUsingWMICmdlet|Warning|89|File 'Set-DbaPowerPlan.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
PSPossibleIncorrectComparisonWithNull|Warning|98|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|98|$null should be on the left side of equality comparisons.
PSAvoidUsingWMICmdlet|Warning|118|File 'Set-DbaPowerPlan.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
PSUseOutputTypeCorrectly|Information|191|The cmdlet 'Set-DbaPowerPlan' returns an object of type 'System.Collections.ArrayList' but this type is not declared in the OutputType attribute.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
