### ISSUE TITLE
dbatools is loading an assembly reference of the wrong version

### ISSUE THREAD

**Issue by wain13001** [sqlcollaborative/dbatools#3816]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
<#
    Provide exact (or sanitized) code to reproduce the error
#>
Import-module dbatools

add-type -AssemblyName "Microsoft.SqlServer.Management.IntegrationServices, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91"

$ConnectionString = "Data Source = SQLServer;Initial Catalog=master;Integrated Security=SSPI"
$conn = new-object System.Data.SqlClient.SqlConnection $ConnectionString
$SSISServer = New-Object Microsoft.SQLServer.Management.IntegrationServices.IntegrationServices $conn


```

## Expected Behavior
I expect to get an SSIS Object I can then manipulate directly, instead I get an exception referencing the wrong version of SQL Server.

## Actual Behavior
I get the following exception error (referencing Version 14.0.0.0, but I'm on SQL 2014, so the highest versions I have are 12.0.0.0)

New-Object : Exception calling ".ctor" with "1" argument(s): "Could not load file or assembly 'Microsoft.SqlServer.Diagnostics.STrace, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one 
of its dependencies. The system cannot find the file specified."

If I don't do anything to bring in dbatools (import-module, get-module, use commands from dbatools, etc...) it works fine.

## Environmental data

 - PowerShell: 

Name                           Value                                                                                                                                                                              
----                           -----                                                                                                                                                                              
PSVersion                      5.1.14409.1012                                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                            
BuildVersion                   10.0.14409.1012                                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                                
SerializationVersion           1.1.0.1  

 - - SQL Server: 
Microsoft SQL Server 2014 (SP2-CU8) (KB4037356) - 12.0.5557.0 (X64) 
	Oct  3 2017 14:56:10 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Thank you for the report. I don't know enough about the way DLLs load, @FriedrichWeinmann could you provide some insight?

**Comment by FriedrichWeinmann** [comment]
Well, dbatools brings its own copy of the SIS library in version 14. You can _also_ load the older version by explicitly calling the full name as you do, but it appears to default to using the newer version.

If you forgo your Add-Type call, will it work or does it produce the same error?

**Comment by wain13001** [comment]
if I comment out the Add-Type, I still get the error so long as dbatools has any sort of reference before getting to the Integration services assignment.  Of course if I comment out both the dba tools and the add-type I get an error of no such class type found.

**Comment by wain13001** [comment]
I've discovered that so long as I add all of the SQL 2014 assemblies/import SQLPS before I reference anything with dbatools, PoSH grabs things correctly, and I have no errors.  So that's at least a functional workaround.

**Comment by nvarscar** [comment]
From [here](https://stackoverflow.com/questions/47707197/how-to-tell-new-object-is-from-which-version-of-assembly?rq=1):

> The type will be loaded from the first assembly which you load.

So I guess this is behavior by default. 

PS. SSIS is a bastard kind of dll, which only works with respective version of SSIS Server without any backward compatibility. I really dislike that decision, which not only complicates life when working with Powershell, but also prevents you from connecting to an older SSIS server from the latest SSMS. Mildlyinfuriating.

**Comment by niphlod** [comment]
having just the right executable installed on every server just to deploy packages without auto-upgrading them does not qualify as mildly..... ;-)
