### ISSUE TITLE
Set-SqlTempDBConfiguration - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#382]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseDeclaredVarsMoreThanAssigments|Warning|171|The variable 'config' is assigned but never used.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
