### ISSUE TITLE
Invoke-DbaDatabaseShrink - Math for PercentFreeSpace doesn't work per fileType

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#3820]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
    Invoke-DbaDatabaseShrink -SqlInstance server -Database db-PercentFreeSpace 50 -FileType Log
```

## Expected Behavior
I would expect the 50% freespace to apply to just the log, not the total database size. When I run the command above (log is currently 14GB and 99% free) I would expect the log to be resized to 50% free.

## Actual Behavior
No shrink since freespace is just reported for the data files and that doesn't have 50% free.
![image](https://user-images.githubusercontent.com/981370/42882965-333e6e7a-8a68-11e8-82e9-f918617c9941.png)

## Environmental data

 - PowerShell: 
![image](https://user-images.githubusercontent.com/981370/42883078-899f2188-8a68-11e8-88b4-6a1f3f3521c8.png)

 - SQL Server: 
Microsoft SQL Server 2014 (SP2-CU11) (KB4077063) - 12.0.5579.0 (X64)   Feb 21 2018 12:19:47   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by Zhunya** [comment]
This can be closed?

**Comment by potatoqualitee** [comment]
totally thank you
