### ISSUE TITLE
Get-DbaSQLService reporting no services when there are!

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#3826]
### Before submitting a bug report:

- [ x] Ensure you are able to reproduce it on the latest released version (_we release often_)
0.9.375

Also on a different machine using 364

- [X ] Verified this bug is not already reported in an issue

There is no SSRS on this machine so not  #3349

- [X ] Verified errors are not related to permissions
- [X ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

remote instance with SQL2017 default instance and anmed 2016 instance Get-DbaSQLService returns no SQL found

![sqlservice 1](https://user-images.githubusercontent.com/6729780/42940328-f9660d86-8b50-11e8-8a1b-984a2b53609b.png)
![sqlservice2](https://user-images.githubusercontent.com/6729780/42940336-fdfb81e6-8b50-11e8-8213-f894a4253f57.png)

![image](https://user-images.githubusercontent.com/6729780/42940406-3e25e4dc-8b51-11e8-836d-f933fd0c609c.png)

## Expected Behavior

The services should be displayed

## Environmental data

See above

**Comment by SQLDBAWithABeard** [comment]
Assigning Fred as CL thinks it maybe a CM issue

**Comment by potatoqualitee** [comment]
hey @FriedrichWeinmann - would you be able to take a look? we're having a few reported issues

**Comment by potatoqualitee** [comment]
this was fixed in a recent PR by @nvarscar. Please let me know if that i not the case.
