### ISSUE TITLE
Get-DbaSsisExecutionHistory, various goodies

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#3832]
### Summary of new feature
- It sorely misses a -Since to filter out old executions
- It should not use string interpolation when building the query
- It has no tests

### Proposed technical details (if applicable)

Use parameters to avoid SQL Injections

### Latest version of dbatools as of writing

0.9.376

**Comment by niphlod** [comment]
I can work on this if @ChrisTuckerNM doesn't want to chime in

**Comment by ChrisTuckerNM** [comment]
I've been hunting my next prey in issue land, I can do this one if there aren't any higher priority items that a new guy would be good for..  Thoughts?

**Comment by niphlod** [comment]
@ChrisTuckerNM : we're not LIFO nor FIFO. We're "do it if you like it" :P (to be on the safe side, tell you're working so you don't cross anyone else)

**Comment by ChrisTuckerNM** [comment]
Taking this one.
