### ISSUE TITLE
Inconsistent output for migration commands

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3837]
probably a good "Already exists on destination" across the board would do. There are descriptions other columns so we dont need to re-specify "Job already exists" 

![image](https://user-images.githubusercontent.com/8278033/43025193-8349c4e6-8c0c-11e8-8626-de14662c13ba.png)

**Comment by nvarscar** [comment]
What if in addition to unifying the Notes property, the status itself will also reflect that?  Successful/Failed/Skipped/Exists. Although, I'm not sure if Skipped is used on other occasions at all.
