### ISSUE TITLE
Read-DbaBackupHeader - Script Analyzer Test failure

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#384]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseDeclaredVarsMoreThanAssigments|Warning|126|The variable 'fl' is assigned but never used.
PSUseDeclaredVarsMoreThanAssigments|Warning|139|The variable 'version' is assigned but never used.
PSAvoidUsingPlainTextForPassword|Warning|76|Parameter '$SqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
