### ISSUE TITLE
Stop-DbaProcess - Script Analyzer Test failure

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#386]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|FileName|Line|Message
-----------|--------|-----------|------|---------
PSUseDeclaredVarsMoreThanAssignments|Warning|Stop-DbaProcess.ps1|90|The variable 'source' is assigned but never used.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
