### ISSUE TITLE
MessagesToOutput crashes Transcripts

### ISSUE THREAD

**Issue by Grzy7316** [sqlcollaborative/dbatools#3860]
## Steps to Reproduce
Run any Sql Command using InvokeDbaSqlQuery  with the -MessagesToOutput switch 

```

``` 

Invoke-DbaSqlQuery -SqlInstance $SqlServer  -Database $Database -Query $QueryString -Credential $AccessCredential -MessagesToOutput

```

##  Expected Behavior

Powershell Transcript Continues running

## Actual Behavior


The Error 
```
Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.
```

## Environmental data


 - PowerShell:
Name                           Value                     
----                           -----                     
PSVersion                      5.1.14393.2363            
PSEdition                      Desktop                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}   
BuildVersion                   10.0.14393.2363           
CLRVersion                     4.0.30319.42000           
WSManStackVersion              3.0                       
PSRemotingProtocolVersion      2.3                       
SerializationVersion           1.1.0.1                   
 - - SQL Server: <!-- SELECT @@VERSION output -->
Microsoft SQL Server 2012 (SP3-CU10-GDR) (KB4057121) - 11.0.6615.2 (X64) 
	Jan  9 2018 21:26:48 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by niphlod** [comment]
hum. what about -Verbose ?

**Comment by niphlod** [comment]
note to self. Remember https://github.com/sqlcollaborative/dbatools/issues/2722

**Comment by potatoqualitee** [comment]
So I thought that runspaces killed transcriptions, and they do, but only if the runspace is incomplete

Check out http://stevegilham.blogspot.com/2017/02/powershell-transcript-cmdlets-and.html

I'm not so sure about importing the module but it seems this singular command would be possible to fix /cc @shaneis
