### ISSUE TITLE
New Feature - Clone login with all DB-level permissions included

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#3864]
---
name: New feature - clone a certain login including all the DB-level permissions :bomb:
about: Either a new function, or a new switch in New-DbaLogin to get permissions from each database of the source login and apply them to a new login.

---

### Summary of new feature

* Right now there is no certain way of cloning user permissions fully. Sync-DbaLoginPermissions only does so on the login level, using underlying function Update-SqlPermissions, that only covers database level permissions and roles; all the object-level permissions are ignored. There is Export-DbaDbUser, which, if used together with Export-DbaDbLogin and some regex magic, might do the trick. However, I would rather have that functionality built-in into module, as this is one of the most popular questions I get: create new login A with permissions like user B.
* Options to consider:
  * `Get-DbaLogin LoginA | New-DbaLogin LoginB -IncludeDBPermissions`
  * `Copy-DbaDbPrivileges -From LoginA -To LoginB`
  * `(Export-DbaUser -Login LoginA -IncludeLoginScript) -replace 'LoginA','LoginB'`

### Proposed technical details (if applicable)

This will all come down to the following actions inside a function:
1. Get databases that source login has users in.
2. Get DB permissions script for each of the users in that list.
3. Add login creation part if necessary 
4. Replace names from LoginA to LoginB using regex.
5. Run the statements against the target server

### Latest version of dbatools as of writing

* 0.9.382

**Comment by nvarscar** [comment]
I'm ready to do the coding part, but will need help to decide what's the best approach here

**Comment by niphlod** [comment]
IMHO the less regex magic the better. I'm notoriously not good at naming convention but I'd say that this is a good candidate for:
 - new-dbalogin -Sqlinstance dest (creates a shallow login, just to be overwritten)
 - get-dbalogin -sqlinstance source
 - Set-dbalogin -sqlinstance -dest -name theshallowfrombefore
It's funny, but indeed there are a lot of steps involved, and almost all of our copy-smth just deal with an element being transferred from instances, not creating a new entity with a different name.
Maybe Get-DbaLoginTemplate -sqlinstance source -name thesourcelogin | New-DbaLogin -sqlinstance dest -name thedestlogin !?!? 
Dunno if we may have similar requests for other "Copy" but this is indeed a Copy, just with the same Source and Dest instances, but different target name.
As always, the reason why `get-verb | where name -eq 'clone'` is empy makes me wanna cry.

**Comment by LeedsDBA** [comment]
I like the approach below for what it's worth...

Get-DbaLogin LoginA | New-DbaLogin LoginB -IncludeDBPermissions

But you could run into issues if the login already exists? What to do in that scenario? Remove the login and re-add it with the permissions from the Get?

**Comment by enolke** [comment]
I have been watching this item for awhile and wanted to say I think this would be amazing and really popular if you guys got this into development again.

Thanks!

**Comment by wsmelton** [comment]
The PR is being reviewed. Should be included in next release...

**Comment by nvarscar** [comment]
I have a prototype that enables Copy-DbaLogin to clone existing logins with a different name. I just need to make another push to include object level permissions. Since that would change the function behaviour, I was going to lock it down behind a switch and hope that it would be enough to make it work for everyone.

**Comment by enolke** [comment]
Fantastic! I would love to help test when possible.

**Comment by nvarscar** [comment]
> Fantastic! I would love to help test when possible.
I created a Draft PR, feel free to test it from the source branch. FYI, object level permissions have made it too.
