### ISSUE TITLE
Export-DbaScript generating output without GO statemen

### ISSUE THREAD

**Issue by RatanGithub** [sqlcollaborative/dbatools#3867]
### Before submitting a bug report:

- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell

  Get-DbaAgentJob -SqlInstance Myinstance | Export-DbaScript -path  "c:\mypath\script.sql"

```

## Expected Behavior

The expected out put of multiple job script should have GO statement at the of each job script , which currently is not the case.

## Actual Behavior

IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_update_job @job_id = @jobId, @start_step_id = 1
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_add_jobserver @job_id = @jobId, @server_name = N'(local)'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
COMMIT TRANSACTION
GOTO EndSave
QuitWithRollback:
    IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION
EndSave:

BEGIN TRANSACTION
DECLARE @ReturnCode INT
SELECT @ReturnCode = 0
IF NOT EXISTS (SELECT name FROM msdb.dbo.syscategories WHERE name=N'[Uncategorized (Local)]' AND category_class=1)
BEGIN
EXEC @ReturnCode = msdb.dbo.sp_add_category @class=N'JOB', @type=N'LOCAL', @name=N'[Uncategorized (Local)]'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback

**END
--NO GO statement here , this will make the script fail 
DECLARE @jobId BINARY(16)**
EXEC @ReturnCode =  msdb.dbo.sp_add_job @job_name=N'syspolicy_purge_history', 
		@enabled=1, 
		@notify_level_eventlog=0, 
		@notify_level_email=0, 
		@notify_level_netsend=0, 
		@notify_level_page=0, 
		@delete_level=0, 
		@description=N'No description available.', 
		@category_name=N'[Uncategorized (Local)]', 
		@owner_login_name=N'sa', @job_id = @jobId OUTPUT

## Environmental data

 - PowerShell:  PS C:\Users\> $PSVersionTable

Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.16299.98                                    
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.16299.98                                   
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1      
  - SQL Server:  Microsoft SQL Server 2017 (RTM-CU9) (KB4341265) - 14.0.3030.27 (X64)   Jun 29 2018 18:02:47   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 16299: )

**Comment by sqllensman** [comment]
I was reviewing this Bug and it this can be done by adding a BatchSeparator variable 
.This can default to an empty string and only be added if it is non-empty

Also looking at this the examples

(1) The example
Get-DbaAgentJob -SqlInstance sql2014 | Export-DbaJob -Passthru | ForEach-Object { $_.Replace('sql2014','sql2016') } | Set-Content -Path C:\temp\export.sql

is clearly wrong and needs to use Export-DbaScript rather than Export-DbaJob

(2) The presence of the $prefix at top of script is not necessarily desirable. When used in conjunction with the -Passthru option as per the example above then it will not even be accurate as the Server from which it was created will be altered.
Other use case like checking if changes have occurred between two different dates would generate false positives as the prefix will always be changing

Would the use of a NoPrefix switch be supported to suppress outputting this.

**Comment by sqllensman** [comment]
Further testing of this command and the reported bug indicate that only reliable method to produce usable scripts for objects is to
(a) UtiliseScripting Options via New-DbaScriptingOption 
(b) Set the ScriptBatchTerminator option to true
(c) Set the FileName property

The ScriptBatchTerminator appears to only be used if the output is directed to a file

Without this the Script option in SMO appears broken as it will produce an incorrect script for something as simple as scripting a single procedure
eg

$server = 'ServerName'
$Databases = Get-DbaDatabase -SqlInstance $server -Database WideWorldImporters 
$Databases[0].StoredProcedures[0] | Export-DbaScript -Passthru

This  will add produce something like:

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE PROCEDURE [Application].AddRoleMemberIfNonexistent

Unless a Batch separator is manually added before the CREATE PROCEDURE statement the script cannot compile or run as CREATE PROCEDURE must be first statement in batch
