### ISSUE TITLE
Sync-SqlLoginPermissions - Script Analyzer Test failure

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#387]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseSingularNouns|Warning|1|The cmdlet 'Sync-SqlLoginPermissions' uses a plural noun. A singular noun should be used instead.
PSAvoidUsingPlainTextForPassword|Warning|98|Parameter '$SourceSqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSAvoidUsingPlainTextForPassword|Warning|99|Parameter '$DestinationSqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSUseSingularNouns|Warning|107|The cmdlet 'Update-SqlPermissions' uses a plural noun. A singular noun should be used instead.
PSUseShouldProcessForStateChangingFunctions|Warning|107|Function ?Update-SqlPermissions? has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSPossibleIncorrectComparisonWithNull|Warning|134|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|134|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|143|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|143|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|162|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|162|$null should be on the left side of equality comparisons.
PSAvoidUsingCmdletAliases|Warning|180|'Where' is an alias of 'Where-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSPossibleIncorrectComparisonWithNull|Warning|183|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|183|$null should be on the left side of equality comparisons.
PSAvoidUsingCmdletAliases|Warning|190|'Where' is an alias of 'Where-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.
PSPossibleIncorrectComparisonWithNull|Warning|235|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|235|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|261|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|261|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|293|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|293|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|295|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|295|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|295|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|295|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|326|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|326|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|359|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|359|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|397|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|397|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|405|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|405|$null should be on the left side of equality comparisons.
PSUseDeclaredVarsMoreThanAssignments|Warning|431|The variable 'result' is assigned but never used.
PSPossibleIncorrectComparisonWithNull|Warning|448|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|448|$null should be on the left side of equality comparisons.
PSUseDeclaredVarsMoreThanAssignments|Warning|515|The variable 'source' is assigned but never used.
PSUseDeclaredVarsMoreThanAssignments|Warning|515|The variable 'destination' is assigned but never used.
PSPossibleIncorrectComparisonWithNull|Warning|531|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|531|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|543|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|543|$null should be on the left side of equality comparisons.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
