### ISSUE TITLE
Remove-DbaDbBackupRestoreHistory

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#3873]
---
Remove-DbaDbBackupRestoreHistory :bomb:
---

### Summary of new feature

* Removes backup and/or restore history for database from `msdb` history tables

### Proposed technical details (if applicable)

* `-Type` — maybe `Backup`, `Restore` or `Both/All/Any`
* `-KeepDays` — removes data older than <specified> days, w/o delete data older than 30 days (as in most maintenance jobs)

### Latest version of dbatools as of writing

* Current module version `0.9.383`

From #3852

**Comment by potatoqualitee** [comment]
yess. tho i think perhaps it should be, and forgive me, but `Remove-DbaDbBackupRestoreHistory `

**Comment by Zhunya** [comment]
Please NO!!! not that long =)

**Comment by potatoqualitee** [comment]
LOL I'm sorry but.. History of what, its existence? Some data that needs to be trimmed? The new name is harrifyingly long but the old command name isn't accurate enough.

**Comment by Zhunya** [comment]
Done

**Comment by amon09** [comment]
A `-Batch` parameter would a good addition to prevent msdb transaction log from bloating up (Especially when system databases are on C and there is no growth limit set).

**Comment by andreasjordan** [comment]
As we only use the SMO method `$server.DeleteBackupHistory($odt)` deviding this into batches would involve getting the olders entry and calculation of suitable intermediate dates (`$odt = (Get-Date).AddDays(-$KeepDays)`) and running them in a foreach loop.
@amon09 If you really want this, reopen this issue and submit a pull request for that.
