### ISSUE TITLE
Copy-DbaAgentJob maintenance plan check has error

### ISSUE THREAD

**Issue by mdumdei** [sqlcollaborative/dbatools#3878]
Line 142 in the GitHub source for Copy-DbaAgentJob has an error - at least on my system:

  $MaintenancePlanName = $sourceServer.Query($sql).MaintenancePlanName

This fixes it:
 $MaintenancePlanName = $sourceServer.Databases.Item("msdb").Query($sql).MaintenancePlanName

Query doesn't like running against the server, wants a database.

**Comment by mdumdei** [comment]
Actually, I used:
$MaintenancePlanName = $sourceServer.Databases.Item("msdb").Query($sql).Name

**Comment by mdumdei** [comment]
n/a

**Comment by niphlod** [comment]
the query has msdb.dbo.sysmaintplan_plans so no worries about where to run it ...
