### ISSUE TITLE
Update-SqlWhoIsActive - Script Analyzer Test failure

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#388]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseShouldProcessForStateChangingFunctions|Warning|1|Function ?Update-SqlWhoIsActive? has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSAvoidUsingPlainTextForPassword|Warning|75|Parameter '$SqlCredential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
