### ISSUE TITLE
Test-DbaMaxMemory to other domain computer fails due to trying to use original domain

### ISSUE THREAD

**Issue by therealcode** [sqlcollaborative/dbatools#3882]
Version: 0.9.384

## Issue
When on **DOMAIN1** and trying to use **Test-DbaMaxMemory** on a server on **DOMAIN2** - the domain credentials supplied are ignored and it uses the domain credentials the PS session is on.

However, this works fine when using **Test-DbaPowerPlan**.

## Reproducible Example
Example from PS Session on **DOMAIN1**:
PS: `Test-DbaMaxMemory -SqlServer APP01 -Credential DOMAIN2\ADMIN_USER`
or
PS: `Test-DbaMaxMemory -SqlServer APP01 -Credential ADMIN_USER@DOMAIN2.local`

## Expected Behavior
>ComputerName  : APP01
InstanceName  : MSSQLSERVER
SqlInstance   : APP01
InstanceCount : 1
TotalMB       : 118772
SqlMaxMB      : 2147483647
RecommendedMB : 101364

## Actual Behavior

Error Returned - Regardless of which line in example was used:
`"Exception calling "Open" with "0" argument(s): "Login failed for user 'DOMAIN1\ADMIN_USER'.""
WARNING: [15:25:37][Test-DbaMaxMemory] Failure | Login failed for user 'DOMAIN1\ADMIN_USER'.`

It shouldn't be sending **DOMAIN1\ADMIN_USER** when parameter specified is **DOMAIN2\ADMIN_USER**.

## Environmental data

- PowerShell: 
PSVersion                      5.1.14393.2248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
- SQL Server: 
Microsoft SQL Server 2016 (SP2-CU2) (KB4340355) - 13.0.5153.0 (X64)   Jun 28 2018 17:24:28   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by Stuart-Moore** [comment]
You appear to be just providing usernames, you need to pass a PsCredential object:
```
$cred = Get-Credential 
Test-DbaMaxMemory -SqlServer APP01 -Credential $cred
```

**Comment by therealcode** [comment]
The above also doesn't work. It still returns the alternate domain as an error.
## Attempt With Suggested
`$cred = Get-Credential` (**DOMAIN2**\ADMIN_USER + PW on prompt)
`Test-DbaMaxMemory -SqlServer APP01 -Credential $cred`

## Result
`WARNING: [13:41:54][Test-DbaMaxMemory] Failure | Login failed for user 'DOMAIN1\ADMIN_USER'.`



## More Info
After passing my original input - a pop-up opens to enter my password. I'm aware there's a workaround by saving the cred to a variable, but figured it would be nice if this method worked the same as Test-DbaPowerPlan (where entering the pass in the pop-up afterwards works fine).

**Comment by niphlod** [comment]
prolly related to https://github.com/sqlcollaborative/dbatools/issues/1980 . for now, let's condider this still open.

**Comment by potatoqualitee** [comment]
this will work now 💯
