### ISSUE TITLE
-NoFixedRole vs -ExcludeFixedRole

### ISSUE THREAD

**Issue by pollusb** [sqlcollaborative/dbatools#3885]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

It's not a bug but parameters for Get-DbaDbRole and Get-DbaRoleMember are not consistent

### Proposed technical details (if applicable)

```powershell
PS> Get-DbaRoleMember -NoFixedRole
PS> Get-DbaDbRole -ExcludeFixedRole
```

### Latest version of dbatools as of writing

0.9.380

**Comment by potatoqualitee** [comment]
ty, Exclude is the new "no", so get-dbadbreole is accurate.

**Comment by pollusb** [comment]
Do we need to create an alias with the old parameter name?

**Comment by niphlod** [comment]
another brick in the wall : please follow https://github.com/sqlcollaborative/dbatools/issues/4128 for news
