### ISSUE TITLE
Restore-DbaDatabase does not work on SQL 2000

### ISSUE THREAD

**Issue by pollusb** [sqlcollaborative/dbatools#3886]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
Restore-DbaDatabase -SqlInstance SQL2000 -Path c:\temp\ABC.bak -DatabaseName ABC

Exception setting "DatabaseBackupLsn": "Cannot convert null to type "System.Numerics.BigInteger"."
At C:\Users\###\Modules\dbatools\0.9.380\allcommands.ps1:23941 char:17
+ ...             $historyObject.DatabaseBackupLsn = $group.Group[0].Databa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

The property 'Fullname' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\###\Modules\dbatools\0.9.380\allcommands.ps1:70268 char:17
+ ...             $full.Fullname = ($DatabaseHistory | Where-Object {$_.Typ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

You cannot call a method on a null-valued expression.
At C:\Users\###\Modules\dbatools\0.9.380\allcommands.ps1:70287 char:17
+ ...             [bigint]$LogBaseLsn = ($dbHistory | Sort-Object -Property ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

WARNING: [09:38:29][Restore-DbaDatabase] Failure | Error enumerating files
```

## Expected Behavior
restore database

## Actual Behavior
does not restore database

## Environmental data

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Microsoft SQL Server  2000 - 8.00.2066 (Intel X86)
        May 11 2012 18:41:14
        Copyright (c) 1988-2003 Microsoft Corporation
        Standard Edition on Windows NT 5.2 (Build 3790: Service Pack 2)
```

**Comment by potatoqualitee** [comment]
great to know, lemme check and repro

**Comment by Stuart-Moore** [comment]
If someone want to get MS to patch their old backup header format that would be so great :)

Back in the mists of time the headers of sql backup files contained less header than they do now. 2 of the missing ones being ones we rely on to sort out complex scenarios (DatabaseBackupLSN and RecoveryForkID). Compare Read-DbaBackupHeader output for more that are missing/different

As we can't easily test any changes for sql2000 I'd suggest we don't try and support it. Instead suggest people use Copy-DbaDatabase to move to something supported. (which will now work as I've fixed Backup-DbaDatabase for sql2k)

Maybe just put in a version check so we fail nicely?

**Comment by potatoqualitee** [comment]
Copy-DbaDatabase relies on Restore-DbaDatabase, is there a way to move the logic that makes Copy-DbaDatabase work to Restore-DbaDatabase? I know 2000 is old, but people still use it. and I'd consider Backup and Restore the core commands of the whole toolset; I wouldn't like to lose support for 2000.

**Comment by potatoqualitee** [comment]
that sounds like a good enough solution, we can warn them with the commands to run if the server is 2k and the inputobject is not backuphistoryinformation?

**Comment by Stuart-Moore** [comment]
OK. If I can get a local sql2000 instance on my laptop I'll work on it
tomorrow (film selection on the flight looks dull).

**Comment by pollusb** [comment]
@Stuart-Moore. I've worked hard to get a VM up with Win2003 and SQL2000 on Hyper-V. Now, my VM is running but I can't get access via remote-desktop because I get an activitation warning because no way of activating the software anymore. If you have any good hint on how I can get around this problem I would be very happy. 

As for Copy-DbaDatabase, you can copy from and to the same 2K instance ?

**Comment by Stuart-Moore** [comment]
Afraid I've no idea on that. Can you connect via SSMS remotely?

I ended up mocking SQL2k in the pester tests so didn't spin up an instance in the end.

I don't believe Copy-DbaDatabase supports that in general (ie; for any sql version, not just 2k), though it could be implement if the Powers That Be (@potatoqualitee) want it?

**Comment by pollusb** [comment]
I wrote a simplier version of restore-database that does not bother with dbatools internal commands. This version works great with SQL2K. Should I submit a new fonction called Restore-DbaDatabase2K ?

**Comment by pollusb** [comment]
It doesn't
```
PS> Restore-DbaDatabase -SqlInstance SQL2K -Path \\SVR\Share\backupfile.bak -OutputScriptOnly
WARNING: [13:44:45][Restore-DbaDatabase] Due to SQL Server 2000 not returning all the backup headers we cannot restore
directly. As this is an issues with the SQL engine all we can offer is the following workaround
This will use a SQL Server instance > 2000 to read the headers, and then pass them in to Restore-DbaDatabase as a
BacukupHistory object:

$BackupHistory = Get-DbaBackupInformation -SqlInstance sql2005 -Path \\backups\sql2000\ProdDb
$BackupHistory | Restore-DbaDatabse -SqlInstance sql2000 -TrustDbBackupHistory
PS> $BackupHistory = Get-DbaBackupInformation -SqlInstance SQL2K -Path \\SVR\Share\backupfile.bak
Exception setting "DatabaseBackupLsn": "Cannot convert null to type "System.Numerics.BigInteger"."
At C:\Users\T76\GD\Code\Modules\dbatools\0.9.395\allcommands.ps1:24245 char:17
+ ...             $historyObject.DatabaseBackupLsn = $group.Group[0].Databa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

**Comment by potatoqualitee** [comment]
oo, k, sounds good. can you detect and take care of it in copy-dbadatabase too?

**Comment by potatoqualitee** [comment]
also detect and inform on restore-dbadatabase please? 🙇

**Comment by Stuart-Moore** [comment]
Copy-DbaDatabase already works, adding another option gives more pathways to fix if we add something (eg; I'm vaguely looking at the copying across the same instance request).

If it's being called from within Restore-DbaDatabase, it either needs to support **ALL** the options, or warn the user if they've called it with options that aren't supported. Just informing as it does now avoids those issues, so just update the warning message (and the associated test)
