### ISSUE TITLE
[New Command] Get-DbaRepPublication

### ISSUE THREAD

**Issue by ColinDouglas92** [sqlcollaborative/dbatools#3891]
### Summary of new feature

* Displays all publications for a server. **Get-DbaRepPublication** will help a user determine what publications reside on a server. This command will also be helpful to piggyback from for future replication commands.

**Syntax**

Get-DbaRepPublication [-SqlInstance] <DbaInstanceParameter[]> [[-Database] <Object[]>] [[-SqlCredential] <PSCredential>][[-PublicationType] <Object[]>] [-EnableException]

**Returns**
Server Name, Database Name, Publication Name, Publication Type (Transactional, Merge, Snapshot)

### Proposed technical details (if applicable)

* https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.replication.replicationdatabase?view=sqlserver-2016

### Latest version of dbatools as of writing

* 0.9.385

### Additional Notes

I'm finished with this command, minus some cleanup + any recommendations. I'm using this within **Test-DbaRepLatency** (#3884), so I will submit these at the same time if approved. Please let me know if you have any questions, comments, concerns! Thanks!

**Comment by potatoqualitee** [comment]
yep, looks fab! thank you. just be sure to include our basic 3 - computername, instancename, sqlinstance plus Database, Name, Type

I think we should change Replication to Rep. what yall say? Similar to our move from Database to Db

**Comment by ColinDouglas92** [comment]
Yup, I agree with you on the name change! I'll make those edits and send these on up within the next couple days; still playing around with writing some unit tests with Pester. Thanks!

**Comment by potatoqualitee** [comment]
:bananadance:

**Comment by wsmelton** [comment]
@ColinDouglas92 in the PR if you will update the issue related to the PR it will auto close these for us. The template for PRs should include this line where you can link the PR number ` Bug fix (non-breaking change, fixes #)`, just put the number directly after that `#` character.
