### ISSUE TITLE
Extend Parameter options of Test-DbaLastBackup

### ISSUE THREAD

**Issue by marcosfreccia** [sqlcollaborative/dbatools#3893]
---
Extend parameters on Test-DbaLastBackup :bomb:
---

### Summary of new feature

* Bring the parameter ReuseSourceFolderStructure from Restore-DbaDatabase to Test-DbaLastBackup. This facilitates the restore of databases with multiple data files spanned across different disks to keep a consistent restore test.

### Proposed technical details (if applicable)
* Already implemented here: https://github.com/sqlcollaborative/dbatools/blob/development/functions/Restore-DbaDatabase.ps1

### Latest version of dbatools as of writing

* 0.9.385

**Comment by andreasjordan** [comment]
Should be only a small change, will try. 
@marcosfreccia : Still interested? Could you help with a test at your side?
