### ISSUE TITLE
Update-dbatools - Script Analyzer Test failure

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#390]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSUseShouldProcessForStateChangingFunctions|Warning|1|Function ’Update-dbatools’ has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSUseSingularNouns|Warning|1|The cmdlet 'Update-dbatools' uses a plural noun. A singular noun should be used instead.
PSAvoidUsingInvokeExpression|Warning|11|Invoke-Expression is used. Please remove Invoke-Expression from script and find other options instead.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
