### ISSUE TITLE
EnableException not showing errors 

### ISSUE THREAD

**Issue by parulsmaddar** [sqlcollaborative/dbatools#3905]
**Backup-DbaDatabase** -SqlInstance $sqlinstance -Databases $dbname -BackupDirectory $backupfolderlocation -EnableException:$true

Running the PS script with the above command in TFS (with Fail On Standard Error enabled)
##**Expected behaviour**
 Throw an exception when an incorrect argument  (e.g. sqlinstance that doesn't exist) is passed

##**Actual Behaviour**
The task gives no error and the deploy is successful.

**TFS logs:**
![2018-08-20 10_14_30-release-49 - visual studio team services](https://user-images.githubusercontent.com/25305869/44355947-dad5e000-a462-11e8-9b4f-9e5cac3972d7.png)

**TFS PowerShell Task settings:**
![tfs task](https://user-images.githubusercontent.com/25305869/44355743-3f446f80-a462-11e8-8dcb-9204d8fa9072.png)

**Comment by parulsmaddar** [comment]
Hi @potatoqualitee  , thanks for your reply. Due to some reason EnableException with -ErrorAction Stop also doesn't throw any error. However, if I use $WarningPreference = "Stop" with a try catch, then it works in the expected way and throws error.
Could there be any specific reason for this behavior?

**Comment by parulsmaddar** [comment]
It was a issue with the sleepygary version. EnableException shows the desired behaviour with v0.9.393

**Comment by potatoqualitee** [comment]
thanks for the info. ill do a new github release shortly. in general, if possible, I'd stick with syncing to the PowerShell Gallery. It's updated almost daily 👍 Sometimes multiple times per day.
