### ISSUE TITLE
get-dbabackupinformation recursing folders when it shouldn't

### ISSUE THREAD

**Issue by dbaduff** [sqlcollaborative/dbatools#3917]
in 0.9.391 on sqlserver 2016 running Get-DbaBackupInformation without the -DirectoryRecurse switch still recurses directories. 

### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
Get-DbaBackupInformation <SQL InstanceName> <URL path with subfolders>

On my system throws an error because there is a non backup file type in a subfolder. 

## Actual Behavior
"
WARNING: [16:25:45][Get-DbaBackupInformation] Failure reading backup header | The media family on device '\\PATH\SUBFOLDER\filename.txt' is incorrectly formed. SQL Server cannot process this media family.
RESTORE HEADERONLY is terminating abnormally.
"
## Environmental data

 - PowerShell: 
Name                           Value                                                                                                                       
----                           -----                                                                                                                       
PSVersion                      5.1.14393.2189                                                                                                              
PSEdition                      Desktop                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                     
BuildVersion                   10.0.14393.2189                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                             
WSManStackVersion              3.0                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                         
SerializationVersion           1.1.0.1  

 - - SQL Server: 
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)   Oct 28 2016 18:17:30   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by Zhunya** [comment]
The idea behind the scene - read anything we have in the path, get all valid SQL Server backups files and build restore chain.

**Comment by Stuart-Moore** [comment]
Hi, what is the full command line you're using? `DirectoryRecurse` only applies if you've specified `NoXpDirTree`  (documented in the comment based help)

you can hide the warnings as well,  just use `-WarningAction SilentlyContinue`, and if you want to silence them but still be able to review then add `-WarningAction SilentlyContinue -WarningVariable warnvar`. All the warnings will be in `$warnvar`

**Comment by Stuart-Moore** [comment]
Going to leave this a week to see if we get a reply, but my testing shows it's working the way CBH claims it should

**Comment by dbaduff** [comment]
Yeah, sorry. I should have checked back sooner. I thought I had included the full command. it was "Get-DBABackupInformation -SqlInstance <<servername>> -path <<URLPATH>> 

I was not using `NoXpDirTree` but here's my argument. I have a directory with backup files in it, in a subdirectory I have documents, log files, whatever. When I run the above command it recurses to the lower directory and throws an error and quits because the "something.txt" file does not have a backup header.  Further, using the `directoryrecurse` switch in this way (only valid with `NoXpDirTree`) is inconsistent with Powershell's (and maybe dbatools, I haven't looked) use of the switch.

So two changes I suggest, One; allow `DirectoryRecurse` to be used always because there will be cases where I only want the current path, and, Two; ignore non-backup file types, or maybe warn but don't kill, then I can choose to see the non-backup files or not without simply skipping them. Maybe `SilentlyContinue` accomplishes this, I haven't thought it completely through.

**Comment by Stuart-Moore** [comment]
@potatoqualitee @niphlod - the decision on recursion was take with restore v1.0 and copied across when I did 2.0. What was the reasoning behind it, and does it still stand?

**Comment by potatoqualitee** [comment]
sorry for the no response, github notifications became useless to me, i need to unwatch a few things. I have no idea at all. But if it works as in the CBH, i'm going to switch this from bug to feature request.

**Comment by andreasjordan** [comment]
@dbaduff : As this is very old, can you test with current version of dbatools? Otherwise I would close this.

**Comment by potatoqualitee** [comment]
No response and it's years old, so closing.
