### ISSUE TITLE
Restore-DbaDatabase - restore fails when database name ends with "trn"

### ISSUE THREAD

**Issue by tomekpiekos** [sqlcollaborative/dbatools#3919]
## Steps to Reproduce

```powershell

   Restore-DbaDatabase -SqlServer . -Path '\\fileserver\share\SQL Backup\SQLserver\' -DirectoryRecurse -RestoredDatabaseNamePrefix test_ -DestinationDataDirectory D:\SQLBackups\test -DestinationLogDirectory D:\SQLBackups\test -VerifyOnly -MaintenanceSolutionBackup -Debug


```

## Actual Behavior
When, during directory scan, one of database ends with "trn", script fails to execute with error:

```
DEBUG: [03:56:24][Get-XpDirTreeRestoreFile] SqlInstance SQLserver cannot access \\fileserver\share\SQL Backup\SQLserver\\wfcdb_testtrnDIFF\
SqlInstance SQLserver cannot access \\fileserver\share\SQL Backup\SQLserver\wfcdb_testtrnDIFF\
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:96099 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Get-XpDirTreeRestoreFile
```

I've found a line in Get-XpDirTreeRestoreFile.ps1 with error:
line 45:    `if (($path -like '*.bak') -or ($path -like '*trn')) {`

there should be something like ($path -like '*.trn')
and verification if $path points to file, not directory.

Example:
```powershell
if ((($path -like '*.bak') -or ($path -like '*.trn')) -and (Test-Path -Path $path -PathType Leaf)) 
```

## Environmental data

 - PowerShell:                                                                                                                                                                          
PSVersion                      5.1.14393.2430                                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                             
BuildVersion                   10.0.14393.2430                                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                                                                 
SerializationVersion           1.1.0.1   

 -  SQL Server: Microsoft SQL Server 2017 (RTM-CU9-GDR) (KB4293805) - 14.0.3035.2 (X64)   Jul  6 2018 18:24:36   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by tomekpiekos** [comment]
It seems all functions are duplicated also in allcommands.ps1
I changed line 92039 to:
    if ((($path -like '*.bak') -or ($path -like '*.trn')) -and (Test-Path -Path $path -PathType Leaf)) {
and issue has been resolved

**Comment by Stuart-Moore** [comment]
Commands are duplicates into allcommands.ps1 at build time to speed up the module import.

Modify the function file and put in a PR, we have instructions - https://github.com/sqlcollaborative/dbatools/wiki/Your-First-Pull-Request

Always good to have more people contributing code :+1:
