### ISSUE TITLE
Copy-DbaDatabase - Add "-OutputDatabaseName" variable

### ISSUE THREAD

**Issue by SQLcyclopedia** [sqlcollaborative/dbatools#3925]
---
name: Copy-DbaDatabase - name your destination database
---

### Summary of new feature
To be able to make a copy of the database on the same instance, it would be useful to be able to rename the destination database. 

### Proposed technical details (if applicable)
Add "-OutputDatabase" or "-DestinationDatabase" variable - if used, this overwrites default of same name.

### Latest version of dbatools as of writing
0.9.392

**Comment by Stuart-Moore** [comment]
Sort of looking into this. The 2 options I'm looking at are:
Single Db - replace old name with new name in all files
Multi DB - Offer the choice to prepend a string to all Db names and FileNames

**Comment by Stuart-Moore** [comment]
Got this working with BackupRestore, as a bonus can now self copy to an instance:

copy-dbadatabase -Source localhost\sql2016 -Destination localhost\sql2016 -Database copytest -NewName instancecopy -BackupRestore -NetworkShare c:\temp

Hopefully get DetachAttach working over the next couple of days

**Comment by SQLcyclopedia** [comment]
Hi Stuart,

Perhaps the title isn’t quite concise but the main aim of this thread was to produce a .bak that could be configured with a different name and/or as a schema-only copy. Is this something you’ve considered?

**Comment by Stuart-Moore** [comment]
I'm implementing exactly what you asked for in the issue

> To be able to make a copy of the database on the same instance, it would be useful to be able to rename the destination database.

You can't create a '.bak' with a different database name as you'd need to rewrite the SQL Storage engine. SQL Server takes care of that bit.  What we do other is a wide range of restoring that backup with different names, prefix or suffix via Restore-DbaDatabase. 

Schema only, that'd be and export/import thing in dbatools terms, and isn't mentioned in the originalissue.

I'll carry on with this one as it's something useful.

If you want to open a more detailed issue for your need, please do. Please make it explicit what you're asking for though.

**Comment by SQLcyclopedia** [comment]
Apologies Stuart, clearly I was hungover or half asleep writing this.

Getting confused with another issue I raised. 

This sounds great 👍🏼
