### ISSUE TITLE
Copy-DbaDatabase - add functionality to allow schema-only copy

### ISSUE THREAD

**Issue by SQLcyclopedia** [sqlcollaborative/dbatools#3926]
---
name: Copy-DbaDatabase - add functionality to allow schema-only copy
---

### Summary of new feature
Currently struggling to find an automated way to perform this task using SSMS/Powershell. Existing dbatools "Copy-DbaDatabase" command only copies database.

Performing 'Tasks > Generate Scripts > Advanced Options > Schema Only' is very manual.

Obviously we could deploy ReadyRoll project but if production schema has drifted, this isn't going to help.

### Proposed technical details (if applicable)
Create a new variable that allows just the schema to be copied - e.g. "-SchOnly"

### Latest version of dbatools as of writing
0.9.392

**Comment by sqllensman** [comment]
What exactly would be scope of this command. I have used the Export-DbaScript to script out most database objects and save the results into a Git repository.  

Are you just wanting the Database objects DDL or do you also want User permissions?

**Comment by potatoqualitee** [comment]
Yeah, I'm thinking this is out of scope as well, since we also have the Dacpac commands that can handle it, too. You can use Export-DbaScript or Export-DbaDacpac, New-DbaPublishProfile and Publish-DbaDacpac.

**Comment by SQLcyclopedia** [comment]
Not sure how I missed these Dacpac commands. 

Ending up creating a custom script using Powershell and SMOs based on:

https://www.red-gate.com/simple-talk/sql/database-administration/automated-script-generation-with-powershell-and-smo/

Will see if dacpac commands offer similar flexibility/outcome.

Thanks. Feel free to close for now.

**Comment by potatoqualitee** [comment]
thanks for the feedback! we'll be publishing an article today about the dacpac commands, check out dbatools.io/subscribe if you wanna receive it in your inbox.

**Comment by potatoqualitee** [comment]
as an fyi, you can accomplish the same as the redgate article by using `Export-DbaScript` and `New-DbaScriptingOption` You can read more here: https://dbatools.io/happy-belated-world-backup-day/

**Comment by SQLcyclopedia** [comment]
I've been unable to achieve this using the out of the box dbatool.io commands mentioned. I'm looking for more flexibility in defining the database objects to copy and outputting/deploying as part of a single build script. For example, one of my requirements is not scripting database users - these may be in a different domain to the machine deploying script to causing failures.

As I feel this would be a fairly common thing, it would be good to build into your commands.

The New-DbaScriptingOption is cool but using SMO's ScriptingOptions class, this doesn't offer exclusion of users.

The Export-DbaDacpac offers ability to add "$moreprops" but again this doesn't allow exclusion of DB users. New-DbaPublishProfile doesn't allow parameters to be established on creation and Publish-DbaDacpac relies on having 

As I see it, I have 3 options:
- similar to New-DbaScriptingOption but but using SMO's Transfer class.
- New-DbaPublishProfile - allow profile to be defined on creation
- Publish-DbaDacpac - publish properties could be passed in on the fly instead of using -PublishXml param (profile). For example:

$PublishProps = "/p:ExcludeObjectType='users'"
Publish-DbaDacpac -SqlInstance $TargetInstance -Database $TargetDatabase -Path $DacPacLocation -PublishParams $PublishProps

Either of these options would be really cool. I will see if I can spend some time on this although my powershell/coding skills are fairly limited.
