### ISSUE TITLE
Feature enhancement

### ISSUE THREAD

**Issue by jigarblakhani** [sqlcollaborative/dbatools#3928]
Requesting function called get-clusterstatus -sqlinstance

that invokes 
invoke-command -cn xxxxxx {get-clusternode} 

this is very useful when you want to run across multiple clusters hundreds in this case; after dr test fallback my cluster services were down that caused sql servcer AG to be in resolving state.

**Comment by wsmelton** [comment]
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaWsfcCluster.ps1
