### ISSUE TITLE
Find-DbaUnusedIndex documentation doesn't match code

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#3936]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

Via conversation on Twitter, learned that the documentation for this function doesn't match functionality. https://twitter.com/texasamy/status/1033095976104415232

1. Execute `get-help find-dbaunusedindex`
2. Note that help text references how much space can be saved by dropping the index, a gridview, and compression
3. Review code; none of these items are referenced in the code

## Expected Behavior

Documentation should match the features of the function.

Gridview was removed in #2975

I can't see references to removing (or adding) the compression checks and space saved in past issues. Were these planned features but not implemented? Removed at some point?

**Comment by potatoqualitee** [comment]
Goodness this one needed a rewrite
