### ISSUE TITLE
Add support for importing and exporting BACPAC packages

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#3948]
---
name: Add support for BACPAC packages :bomb:
about: Add support for the bacpac command line parameters in the SqlPackage.exe call: /Export and /Import
Can be added to the existing command as a -Type parameter, but will probably need a cmd rename

---

### Summary of new feature

Add an option to use a simpler solution (bacpac) if the task is just clone the database - without all the complications of the dacpac deployment.
I'm also seeing that bacpacs were supported even on SQL2005, so that's one more target version for the Publish command (2008SP2+).

### Proposed technical details (if applicable)

1. Add -Type parameter that allows to select between dacpac and bacpac with dacpac being default option
2. Add the following modifications to the code triggered by -Type Bacpac:
  *  /Export cmdline option to Export-DbaDacpac function 
  * [Microsoft.SqlServer.Dac.BacPackage]::Load package loader to Publish-DbaDacpac
  * [Microsoft.SqlServer.Dac.DacServices]::ImportBacpac as a substitute deployer to Publish-DbaDacpac
  * Anything else I couldn't think of
3. Rename DbaDacpac to DbaPackage and create aliases for backwards compatibility.

### Latest version of dbatools as of writing

* 0.9.397

**Comment by RichieBzzzt** [comment]
Funnily enough I was just thinking about this. I'm wondering if it would be safer to create 2 new functions as I think it would be easier to read the function without having to factor in where we would need to make the changes based on it being a dacpac or a bacpac, and whether we were importing/exporting.

As bacpacs also support data extraction on a per table basis, I wonder if we would want to test that tables exist prior to exporting bacpac, or if that would be going over the top: if the table is missing I suspect that the bacpac extraction would fail, but would the error be that the table is missing? sqlpackage tends to be a little... opaque when throwing errors.

Am happy to help out on writing functions if required!

**Comment by nvarscar** [comment]
Hey @RichieBzzzt thanks for reaching out!
I've started working on this one - you can check the current progress here - https://github.com/nvarscar/dbatools-nvarscar/blob/bac-dac-pac/functions/Export-DbaDacPackage.ps1
So far, I was able to seamlessly unite both Export and Extract functionality, as well as switch to the native SMO, which also allowed me to add -Table parameter to both Dacpac & Bacpac extractions. 
First iteration is out there, I'm planning to add a couple more things to it (support function for DacOptions and bacpac publishing). Hopefully, within next few days.
I don't like the idea of supporting both SMO and EXE, but the reality is that removing EXE support at this point would be a breaking change and I'll leave it up to @potatoqualitee to decide on that.
