### ISSUE TITLE
Install-DbaMaintenanceSolution: Issue from Slack

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3951]
Unsure if this was fixed, but I had it in my queue and wanted to make an issue
````
Hi, got this error message when running Install-DbaMaintenanceSolution. Any ideas what the problem can be?
Remove-DbaAgentJob : Cannot convert the "CommandLog Cleanup" value of type "Microsoft.SqlServer.Management.Smo.Agent.Job" to type "Microsoft.SqlServer.Management.Smo.Agent.Job[]".
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:47928 char:46
````

**Comment by wlansdowne** [comment]
Hi, I'm encountering the same overall issue from what it looks like. I'm running 'Install-DbaMaintenanceSolution' (with the -InstallJobs parameter) which runs fine.  I'm then immediately using 'Set-DbaAgentJob' and 'New-DbaAgentSchedule' to edit/schedule the created jobs.  It only works about 20% of the time without warnings whereas in most cases some or all of the commands will give warnings like this:

WARNING: [13:08:08][Set-DbaAgentJob] Something went wrong retrieving the job | Cannot convert the "CommandLog Cleanup"
value of type "Microsoft.SqlServer.Management.Smo.Agent.Job" to type "Microsoft.SqlServer.Management.Smo.Agent.Job[]"

I've attached the commands I'm running in sequence if it helps reproducing the issue.  Thank you!
[DbaMaintenanceSolution-Commands.txt](https://github.com/sqlcollaborative/dbatools/files/2340551/DbaMaintenanceSolution-Commands.txt)

**Comment by potatoqualitee** [comment]
thats useful info, thank you

**Comment by potatoqualitee** [comment]
dang, i am unable to see from the code why it wouldnt work and i cant repro. how about you @sanderstad ?

**Comment by githubsqltoolsse** [comment]
I think the first question might come from my question in slack, but that's not an issue anymore.

I figured out that If I ran the commands directly from command line or from a script with nothing else in the scripts, The commands worked. But when included as a part in my installation scripts, they didn't work. So something else in my script apparently, broke something. I also noticed that when running the scripts my path was changed from a local disk drive to SQLSERVER: and the command that changed that was INVOKE-SQLCMD. 

I changed all occurances of INVOKE-SQLCMD to INVOKE-SQLCMD2. After that, is everything working great.

**Comment by potatoqualitee** [comment]
thank you both so much for this feedback. We do not support dbatools and sqlserver/sqlps because there's essentially a conflict. 

@wlansdowne - if you can, use Microsoft's `SqlServer` module instead of `SQLPS`. They fixed a bunch of stuff and continue to develop it, unlike SQLPS.

**Comment by wlansdowne** [comment]
Hi All -

I've only been able to initially test a few times, but can report back that after completely removing references to 'SQLPS' to prevent importing the module and converting everything else over to using DBAtools equivalents I'm no longer seeing warnings like I was.  I don't believe I'd have been able to do several test runs and not encounter them, so this appears resolved/mitigated.  Should anything come up, I'll post again with further details.

Thank you to everyone for taking a look and providing feedback.  I greatly appreciate it and all your efforts on this wonderful tool!

**Comment by potatoqualitee** [comment]
excellent news. thanks so much!
