### ISSUE TITLE
standardize configuration command names

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3956]
this is nasty

![image](https://user-images.githubusercontent.com/8278033/44911638-dee9e380-ad27-11e8-856a-67163e17a1bb.png)

We should match things up, except for maybe SpConfigure

**Comment by potatoqualitee** [comment]
I vote for Config, what yall think

**Comment by wsmelton** [comment]
I'd vote for the following changes:

- `Set-DbaTempdbDbConfiguration` > `Set-DbaTempdbFile`
- `Test-DbaTempDbConfiguration` > `Set-DbaTempdbFile` (and yes `db` should be lowercase 😁 )

**Comment by potatoqualitee** [comment]
lol agreed on the lowercase, except where does that leave Get-DbaTempdbConfig. and i know it's strictly file messing right now, but gneeral config will allow us to expand if we wanna

**Comment by wsmelton** [comment]
What would you need to expand?

**Comment by wsmelton** [comment]
As of 2016 there are no trace flags to config for tempdb usage, and the file count themselves are already configured for you upon installation according to best practices. After 2012 is dropped those two commands are actually mute.

**Comment by potatoqualitee** [comment]
trace flags, potentially.  even if we don't, we'd still be left with an incomplete set. TempDbFile, TempDbFile, TempDbConfig
