### ISSUE TITLE
Restore-DbaDatabase does not apply new diff backups 

### ISSUE THREAD

**Issue by laoki** [sqlcollaborative/dbatools#3958]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell

Restore a Full Backup
Restore-DbaDatabase -SqlInstance inote215\sql17 -Path c:\temp\bkp -NoRecovery

Apply Diff Backup
Restore-DbaDatabase -SqlInstance inote215\sql17 -Path c:\temp\bkp -NoRecovery -continue

Try to apply one more diff backup
Restore-DbaDatabase -SqlInstance inote215\sql17 -Path c:\temp\bkp -NoRecovery -continue


```

## Expected Behavior

Was expecting the new diff backups to be applied.

## Actual Behavior

First diff backup is applied.
Second time running to apply a new Diff backup doesn't do anything.

Running with -verbose:
VERBOSE: [13:29:05][Read-DbaBackupHeader] Scanning file
c:\temp\bkp\AdventureWorks2017_201808291651.bak.
VERBOSE: [13:29:06][Restore-DbaDatabase] Processing DatabaseName -
VERBOSE: [13:29:06][Format-DbaBackupInformation] Starting
VERBOSE: [13:29:06][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [13:29:06][Select-DbaBackupInformation] ContinuePoints provided so setting up for a continue
VERBOSE: [13:29:06][Select-DbaBackupInformation] Filtering by DatabaseName
VERBOSE: [13:29:06][Select-DbaBackupInformation] AdventureWorks2017 in ContinuePoints, will attmept to
 continue
VERBOSE: [13:29:06][Select-DbaBackupInformation] No full or diff, so attempting to pull from Continue
informmation
VERBOSE: [13:29:06][Restore-DbaDatabase] VerifyOnly = False
VERBOSE: [13:29:06][Get-DbaDbPhysicalFile] Connecting to INOTE215\SQL17
VERBOSE: [13:29:06][Restore-DbaDatabase]  passed testing
VERBOSE: [13:29:06][Restore-DbaDatabase] Passing in to restore

## Environmental data

 - PowerShell: 
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: 
Microsoft SQL Server 2017 (RTM-CU9) (KB4341265) - 14.0.3030.27 (X64)

**Comment by Stuart-Moore** [comment]
Unfortunately Diffs don't work like that I'm afraid.

You can restore 1 and only one on top of a full. Then it's t logs only.

That's a sql server thing we can't work around.

**Comment by laoki** [comment]
Stuart,

I was able to restore the additional file using SSMS.

This is the result using get-dbarestorehistory after restoring the file using SSMS:

![image](https://user-images.githubusercontent.com/25819430/44933801-c89c5180-ad40-11e8-81f4-c95b2548651f.png)

**Comment by Stuart-Moore** [comment]
So you can. Show you where the phrase about assume comes from.

But, you don't need to. Diffs are based off a full backup and contain all
the changed pages since that backup. The last one contains the first so
you're repeating yourself restoring multiples. Just restore the latest and
save yourself a restore.

So there's no need to support this as if you'd fed all the backups in we'd
have Skipped the first diff anyway

**Comment by garethnewman** [comment]
+1 I'd like to have this, not sure how much effort will be involved though.

**Comment by Stuart-Moore** [comment]
It's done. I'm just trying to replicate another issue to put in the same
pr. If I can't do that tonight I'll push up the fix anyway for tomorrow
morning.

**Comment by garethnewman** [comment]
amazing, thanks Stuart,
