### ISSUE TITLE
Migrating Reporting Services DBs can result in an unsupported configuration

### ISSUE THREAD

**Issue by xxbiohazrdxx** [sqlcollaborative/dbatools#396]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In MSSQL, when migrating a Reporting Services DB, it is possible that the destination server will think that the DB is part of a Scale-out Configuration. As Reporting Services only supports Scale-out Configurations in Enterprise, Developer, and Evaluation editions, this can cause issues with MSSQL Standard Edition installations.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

http://www.widriksson.com/ssrs-scale-out-deployment-configuration-error/

Here is a potential fix, but since modifying the DB is probably not the best approach, a warning would be sufficient to let the user know that the issue may occur and why.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

I have only tested in my environment:

Source: Windows Server 2008R2 w/ MSSQL 2012
Destination: Windows Server 2016 w/ MSSQL 2016

I am running the latest version, and the script was run on the Destination server.

**Comment by wsmelton** [comment]
@ctrlbold Can share, but my opinion overall this would be outside of the scope to handle for application databases. Even though SSRS is part of SQL Server components it is still treated as any other application database. Trying to include a warning around this particular scenario or to note for this specific database should not be done.

However, bringing up the point of going to a lower Edition of SQL Server might be worth adding. This can affect more than just an application like SSRS, big thing is if any Enterprise only feature is being used it will break in Standard.

**Comment by xxbiohazrdxx** [comment]
Yeah my thinking is that since it is an included feature for SQL Server it would be noted but I see your side of it as well.

Either way, just letting y'all know about it

**Comment by niphlod** [comment]
I second @wsmelton POV. SSISDB would be one thing but e.g. ReportServer can be named freely: inspecting  the structure to find out is not doable.
Can we just all agree about a note on the docs about common gotchas like this one ? (i.e. "watch out for reportserver migrations")

@ctrlbold : can you be the BFDL we all like and address the common people ?

**Comment by ctrlbold** [comment]
LOL, k @niphlod, @wsmelton  ill get my brain together and take a closer look tomorrow.

Thanks for the report @xxbiohazrdxx!

**Comment by niphlod** [comment]
@ctrlbold : this is just strictly a documentation issue (or, at best, in addition to that, a proper warning). As the official BDFL please rule it out, I'll gladly address the code if needed.

**Comment by potatoqualitee** [comment]
Hey all,
Start-SqlMigration and Copy-DbaDatbase both require IncludeSupportDbs to be specified. 

Start-SqlMigration calls it this way: 

`Copy-DbaDatabase -Source $sourceserver -Destination $destserver -AllDatabases -SetSourceReadOnly:$SetSourceReadOnly -ReuseSourceFolderStructure:$ReuseSourceFolderStructure -BackupRestore -NetworkShare $NetworkShare -Force:$Force -NoRecovery:$NoRecovery -WithReplace:$WithReplace -IncludeSupportDbs:IncludeSupportDbs`

So default behavior, at least at this time (unsure if/when it's changed) has been to skip Reporting Services databases as well as distribution, and I have I have tested to ensure this is still the case and can confirm. I'd be happy to accept a pull request for a warning if the switch is specified, but believe that only having explicit exclusion is reasonable.
