### ISSUE TITLE
test-dbalastbackup -copyfile give error: Cannot convert value to type System.String..

### ISSUE THREAD

**Issue by stevenksco** [sqlcollaborative/dbatools#3960]
PS C:\WINDOWS\system32> test-dbalastbackup -sqlinstance {remote} -Destination {local} -CopyFile -database model
WARNING: [10:44:09][Test-DbaLastBackup] Failed to copy backups for model on {remote} to  - Cannot process argument transformation on parameter 'filepath'. Cannot convert value to type System.String..

The command works until I try to use Copyfile.  

thanks,

steve

**Comment by potatoqualitee** [comment]
was able to replicate, thanks, will take a llok
