### ISSUE TITLE
Test-DbaDiskAlignment - Script Analyzer Test failure

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#397]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSShouldProcess|Warning|1|'Test-DbaDiskAlignment' calls ShouldProcess/ShouldContinue but does not have the ShouldProcess attribute.
PSUsePSCredentialType|Warning|1|The Credential parameter in 'Test-DbaDiskAlignment' must be of type PSCredential. For PowerShell 4.0 and earlier, please define a credential transformation attribute, e.g. [System.Management.Automation.Credential()], after the PSCredential type attribute.
PSAvoidUsingPlainTextForPassword|Warning|93|Parameter '$Credential' should use SecureString, otherwise this will expose sensitive information. See ConvertTo-SecureString for more information.
PSShouldProcess|Warning|99|'Get-DiskAlignment' calls ShouldProcess/ShouldContinue but does not have the ShouldProcess attribute.
PSAvoidUsingWMICmdlet|Warning|119|File 'Test-DbaDiskAlignment.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
PSAvoidUsingWMICmdlet|Warning|122|File 'Test-DbaDiskAlignment.ps1' uses WMI cmdlet. For PowerShell 3.0 and above, use CIM cmdlet which perform the same tasks as the WMI cmdlets. The CIM cmdlets comply with WS-Management (WSMan) standards and with the Common Information Model (CIM) standard, which enables the cmdlets to use the same techniques to manage Windows computers and those running other operating systems.
PSPossibleIncorrectComparisonWithNull|Warning|187|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|187|$null should be on the left side of equality comparisons.
PSPossibleIncorrectComparisonWithNull|Warning|318|$null should be on the left side of equality comparisons.
PSUseDeclaredVarsMoreThanAssignments|Warning|361|The variable 'newcollection' is assigned but never used.
PSUseBOMForUnicodeEncodedFile|Warning||Missing BOM encoding for non-ASCII encoded file 'Test-DbaDiskAlignment.ps1'

**Comment by wsmelton** [comment]
To clean up some of the WMI stuff it will be better off going ahead and rewriting some of this code to also meet the new standards.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
