### ISSUE TITLE
Restore-DbaDatabase apply log backups with -FileMapping

### ISSUE THREAD

**Issue by labyrinthsystems** [sqlcollaborative/dbatools#3972]
Version 0.9.399
Have an existing database in full recovery. Using the latest full backup, restore it as a copy of that database. Use -FileMapping to provide the new physical files. Leave it in no recovery to restore transaction logs from the existing database to the newly restored database. Like log shipping. 
Issue is that -FileMapping does not seem to work with -Continue parameter as the error message says cannot use the physical files of the existing database

## Steps to Reproduce

```powershell
<#
# Restore a full backup of a database 
# Say for instance your database is called MyDB
# Restore it as MyDB2, to the same drives

# these 4 variables must be changed to suit
$db = 'MyDB2'
$filemap = @{'MyDB_Data'='D:\SQLData\MyDB2.mdf';'MyDB_log'='L:\SQLLogs\MyDB2_log.ldf'}
$pathFull = 'X:\SQLBackup\pathToFullBackup.bak'
$pathLogs = 'X:\SQLBackup\pathToLogBackups'

# This should restore the full backup as a second database in norecovery
Restore-DbaDatabase -SqlInstance localhost -Path $pathFull -DatabaseName $db -FileMapping $filemap -NoRecovery -WithReplace -MaintenanceSolutionBackup -Verbose # -OutputScriptOnly

# Now to restore transaction logs via -Continue
Restore-DbaDatabase -SqlInstance localhost -Path $pathLogs -DatabaseName $db -FileMapping $filemap -NoRecovery -MaintenanceSolutionBackup -Verbose -Continue # -OutputScriptOnly
# Cannot restore any log backups as the physical files of MyDB are in use (which we are not trying to use)

#>
```

## Expected Behavior

Transaction log backups should restore

## Actual Behavior

Error throws as if we we were trying to restore the physical files of the existing database

## Environmental data

PSVersion                      4.0                                                                                                                                
WSManStackVersion              3.0                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                    
BuildVersion                   6.3.9600.18968                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                               
PSRemotingProtocolVersion      2.2  

Microsoft SQL Server 2016 (SP1-CU10-GDR) (KB4293808) - 13.0.4522.0 (X64)   Jul 17 2018 22:41:29   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by Stuart-Moore** [comment]
Having problems replicating this one.

![image](https://user-images.githubusercontent.com/5613670/45095131-336cd480-b115-11e8-8693-34be43d55cdf.png)

```
$filemap = @{RestoreTimeClean = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL2008R2SP2\MSSQL\DATA\MapClean.mdf'; RestoreTimeClean_log = 'C:\Program Files\Microsoft SQL Server\MS
SQL10_50.SQL2008R2SP2\MSSQL\DATA\mapclean_log.ldf'}

$null = Restore-DbaDatabase -SqlInstance localhost\sql2008r2sp2 -Path C:\github\appveyor-lab\RestoreTimeClean\RestoreTimeClean.bak -WithReplace

Get-DbaDatabaseFile -SqlInstance localhost\sql2008r2sp2 -Database restoretimeclean | select LogicalName, PhysicalName

$null = Restore-DbaDatabase -SqlInstance localhost\sql2008r2sp2 -Path C:\github\appveyor-lab\RestoreTimeClean\RestoreTimeClean.bak -DatabaseName rt2 -NoRecovery -WithReplace -FileMapping $filemap
$null = Restore-DbaDatabase -SqlInstance localhost\sql2008r2sp2 -Path C:\github\appveyor-lab\RestoreTimeClean\ -DatabaseName rt2 -Continue -FileMapping $filemap
 Get-DbaDatabaseFile -SqlInstance localhost\sql2008r2sp2 -Database rt2 | select LogicalName, PhysicalName
```

Which I'm pretty sure mirrors your logic. And it's working as expected.

Thats in ps V4, I just need to try and find a PS4 box to try it on as well to confirm.

**Comment by labyrinthsystems** [comment]
Hi @Stuart-Moore ,
![20180906](https://user-images.githubusercontent.com/17836420/45171743-1c081700-b1fb-11e8-84a3-86135e7f54c0.png)
I think I'm doing the exact same as you, I can't quite believe it! I'm on dbatools version 0.9.381. 
I wouldn't rule out that I'm doing something stupid though

**Comment by Stuart-Moore** [comment]
No feedback from user since september, and I've never managed to replicate this even on PS4
