### ISSUE TITLE
Website will need major updates after this PR

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3982]
tho the amount of time it'll take to update it might be better investing in some kind of automated markdown system

**Comment by niphlod** [comment]
it'll be. let's say weekend-ish beta ready

**Comment by potatoqualitee** [comment]
Thanks so much! In the blog post, I'll let people know we have a beta site on the way to address our website being outdated ❤️  /cc @gbargsley (niph will be doing it dynamically instead of requiring your intervention)

**Comment by gbargsley** [comment]
Ok, sorry I could not be more help.

**Comment by potatoqualitee** [comment]
np. just gotta fix the .htaccess and we should be mostly set.

If there is a way to detect our current images / videos available on the dbatools site and auto inject into the docs, that'd be awesome /cc @niphlod

**Comment by niphlod** [comment]
how can images / videos be maintained by anyone ? we reached (quite long ago) the limit where there's no manpower available to keep up with the changes. Granted, compiling by hand a wordpress page makes the result nicer but we need to face the truth that having docs in both the sourcecode AND the site is unmaintainable. If we *do* want images and videos, they should be included in the inline help, via markdown.

**Comment by potatoqualitee** [comment]
It's true. A lot of our current images are very out of date 🤔

**Comment by ClaudioESSilva** [comment]
It's too strange if we add the URL (video/image) to the function help? :thinking: 
That way would render on the docs page.

**Comment by potatoqualitee** [comment]
I think we could have, similar to Author a Screenshot: and Video: in the notes

**Comment by potatoqualitee** [comment]
shawn just made a great point - that we can do text, much more managable.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-6

![image](https://user-images.githubusercontent.com/8278033/45301975-65fe3f00-b512-11e8-926f-5fc2d794ac69.png)

**Comment by niphlod** [comment]
I'm lost but whatever "suite" we may use to generate docs from inline help
basically means writing such inline help with mardown. Given markdown has
been created for the exact purpose of looking good even when not
"rendered", we can do whatever we want. Maybe for images/gif/videos we
*could* figure out a nice name for the asset to be embedded, but if we
wanna do text, no problems either.

Il lun 10 set 2018, 15:59 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by niphlod** [comment]
I think we can definitely close this, @potatoqualitee ?
