### ISSUE TITLE
Copy-dbadatabase in newest version (0.9.412) isn't associated with the module along with other commands.

### ISSUE THREAD

**Issue by CJChristensen** [sqlcollaborative/dbatools#3992]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    
*/
```

```powershell
<#
   
#>
```

## Expected Behavior
Running copy-dbadatabase should prompt you for a source and running get-help copy-dbadatabase should produce the help for the command.

## Actual Behavior

Running Copy-DbaDatabase gives you a command not recognized. Running get-help copy-dbadatabase lists that it is not associated with a module and show no help. This wasn't the only one that was broken either.  

Running get-command -module dbatools listed all of the commands and alias' and showed all of them associated with the module.

I just chose to remove the new version and roll back to 0.9.400 and I am not seeing any of the above behavior, I have not tested with any version further than 0.9.400 

## Environmental data

 - PowerShell:  5.1.17134.228
 - - SQL Server:  NA

**Comment by Stuart-Moore** [comment]
Hi @CJChristensen - unfortunately your repro code has disappeared. Could you add it please so we test it properly

**Comment by potatoqualitee** [comment]
0.9.412 hardcore bombed, my apologies- a character was missing which caused the import to fail. Please download the latest version.
