### ISSUE TITLE
The latest dbatools takes almost 4 times longer to load than 0.9.400

### ISSUE THREAD

**Issue by gwojan** [sqlcollaborative/dbatools#4012]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
function Get-ExecutionTime {
    param([int]$Id = (Get-History -Count 1).Id)

    $t = Get-History -Id $Id
    $t.EndExecutionTime - $t.StartExecutionTime
}

Import-Module dbatools

(Get-ExecutionTime).TotalSeconds
8.4268314
```

## Expected Behavior

```powershell
Import-Module dbatools -MaximumVersion 0.9.400
(Get-ExecutionTime).TotalSeconds
2.6040018

## Environmental data

<!-- Provide output of the following two commands -->

 - PowerShell:
Name                           Value                                                                                                                                
----                           -----                                                                                                                                
PSVersion                      5.1.17134.228                                                                                                                        
PSEdition                      Desktop                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                              
BuildVersion                   10.0.17134.228                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                      
WSManStackVersion              3.0                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                  
SerializationVersion           1.1.0.1

**Comment by potatoqualitee** [comment]
thanks for the report! are you starting with a fresh session each time? the second time will always run faster, even with -Force

**Comment by gwojan** [comment]
Yes. Each test is done in a brand new PowerShell session.

**Comment by potatoqualitee** [comment]
thank you, can you please use -verbose and tell me where it stalls?

**Comment by gwojan** [comment]
It appears to stall right at:

`VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.418\dbatools.psm1'.`

then zips right through exporting all the functions.

**Comment by gwojan** [comment]
FYI, I just tested v0.9.419 and the import times are consistently taking at least 10 seconds as opposed to the previous 8.5 seconds.

**Comment by potatoqualitee** [comment]
Thank you. I'm experiencing issues too. Check out `[Sqlcollaborative.Dbatools.dbaSystem.DebugHost]::ImportTime`

0.9.400
![image](https://user-images.githubusercontent.com/8278033/45614542-27183e00-ba6a-11e8-8988-90afaacfb9ab.png)

Current version
![image](https://user-images.githubusercontent.com/8278033/45614546-2c758880-ba6a-11e8-9c6d-51571c210272.png)

Our runspaces are freaking out and running ultra slow - @FriedrichWeinmann do you have any insight into this?

**Comment by potatoqualitee** [comment]
These are developer import times, which bypass allcommands.ps1, btw.

**Comment by potatoqualitee** [comment]
Windows 7 x86, though? 4.5 second import, no runspace issues :(
![image](https://user-images.githubusercontent.com/8278033/45614989-87f44600-ba6b-11e8-8df3-d7a086f2320c.png)

**Comment by gwojan** [comment]
@potatoqualitee Neat! I didn't know about `[Sqlcollaborative.Dbatools.dbaSystem.DebugHost]::ImportTime`...

With that being said I have been testing against several different servers and have not been able to reproduce the issue. I was beginning to think it was an environmental issue with my laptop which is Windows 10, 1803 so I'm glad you were able to repro it.

The servers in my tests have been WS2016 and WS2012R2.

**Comment by potatoqualitee** [comment]
thanks @gwojan - so you can only repro on windows 10 correct? so far, me too

**Comment by potatoqualitee** [comment]
wow, so from what i can see, the module is getting loaded a bunch of times within import-module

![image](https://user-images.githubusercontent.com/8278033/45679583-35815b00-bb39-11e8-8b3d-9e932b92f90e.png)

**Comment by potatoqualitee** [comment]
k, that got fixed, now back to the weird runspaces taking forever

**Comment by gwojan** [comment]
@potatoqualitee, I noticed a Twitter post that sounded like this issue might be fixed but I'm still seeing really long load times on my Windows 10 laptop with the v0.9.431 release. Any word?

**Comment by potatoqualitee** [comment]
hey there, that was for another issue. still unsure about this one. debugging it will be pretty advanced so may take some time to solve :(

**Comment by potatoqualitee** [comment]
do me a favor? run this on the fast import machines and the slow import machines, tell me what it says

`[AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.Fullname -like "Microsoft.SqlServer.XE*,*" }`

**Comment by potatoqualitee** [comment]
Should be 0.9.403 that breaks. I found the offending commit. Load time jumps from 7 seconds to timeouts.

Just not sure what to do about it, yet. It has to do with 

https://github.com/sqlcollaborative/dbatools/commit/9d8ef7a4b6272c89cb0bd0e0f331aa8946eb46b7

![image](https://user-images.githubusercontent.com/8278033/46065470-6e8d8100-c172-11e8-8466-8751d74abfc6.png)

`git reset bcbc7b7 --hard`
close ps, ipmo, 7 seconds

close ps, refresh repo

`git reset 9d8ef7a --hard`
ipmo, timeout

gonna remove all instances of Test-DbaDeprecation and see if that fixes things. Just removing the aliases from psd1 and psm1 did not work.

**Comment by potatoqualitee** [comment]
hoooh, figured it out. that was an adventure

**Comment by gwojan** [comment]
> hoooh, figured it out. that was an adventure

😄 

@potatoqualitee, do you sleep!? 😉 I didn't have Interwebz access last night because... Comcast... Sigh. I was going to do your tests first thing this morning and then I see my inbox!

I guess the only question I still have is why this only occurs on Windows 10?

**Comment by potatoqualitee** [comment]
i did not sleep much last night ;) I couldn't pull myself away; that issue and the XE issue was driving me crazy.

I actually do not know why that particular line caused the slow down, though I suspected it would be one or all of the 4 config commands. 

If I had to guess, that line threw the import into an infinite loop because of some internals that are beyond me, though @FriedrichWeinmann may know.

**Comment by gwojan** [comment]
@potatoqualitee. Ugh. With build `0.9.427` it looks like we've regressed. I'm back to 10+ second load times.

`Waiting for runspaces to finish        00:00:08.2205204 09/28/2018 09:56:53 09/28/2018 09:57:01`

**Comment by potatoqualitee** [comment]
not unexpected, it was fixed in like .439. try updating to the latest

**Comment by gwojan** [comment]
@potatoqualitee, Never mind. I screwed up. I have a function that imports the `dbatools` module and automatically restarts my transcript because `dbatools` is still killing active transcripts when it loads. My script was explicitly calling `0.9.427`. 😦
