### ISSUE TITLE
Set-DbaPrivilege does not set the privilege if no users are currently assigned that privilege

### ISSUE THREAD

**Issue by matt-darwin** [sqlcollaborative/dbatools#4017]
## Steps to Reproduce

On a server where there is a right with no users assigned (Lock Pages In Memory in my example):-
![image](https://user-images.githubusercontent.com/29404748/45436636-2c147080-b6ab-11e8-9bae-49a7c72dc6b3.png)

`Set-DbaPrivilege -Computer [Yourcomputer] -type LPIM`

## Expected Behavior

Expect the right to be assigned.

## Actual Behavior

The function appears to work, but no rights are assigned.

This is because the secedit export only contains entries for security policies that have assignments.  As such when the code from the function below runs, it finds nothing to replace:-

```
(Get-Content $tempfile) -replace "SeLockMemoryPrivilege = ", "SeLockMemoryPrivilege = *$SID," |
Set-Content $tempfile
```

In this case, for the first account being added, you might want to do something like this instead:-

```
$NewContent = @"
[Privilege Rights]
SeLockMemoryPrivilege = *$SID
"@
(Get-Content $tempfile) -replace "[Privilege Rights]", $NewContent | Set-Content $tempfile
```

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/pull/4019
