### ISSUE TITLE
Find-DbaInstance not returning anything

### ISSUE THREAD

**Issue by AlreadyPicked** [sqlcollaborative/dbatools#4023]
I'm attempting to find all SQL instances on my ActiveDirectory but started first with a fixed list of only one server in a text file and doing this: Get-Content $PSScriptRoot\servers.txt | Find-DbaInstance

Nothing is being returned and the server has 2 instances on it.

What could I be doing wrong?

Thanks.

**Comment by niphlod** [comment]
hy @AlreadyPicked , is this still valid ? sorry nobody replied here. Feel free to reopen if the issue still stands

**Comment by AlreadyPicked** [comment]
Indeed. No one replied and I still have an issue with this. I will re-open.

**Comment by potatoqualitee** [comment]
Hey @AlreadyPicked - thanks for the note. can you slap a `-Verbose` on your command and paste it here?

**Comment by AlreadyPicked** [comment]
Sure thing. Sorry, parts of it are in french. I also removed the names of the server\instance, IP address.

COMMENTAIRES : [16:02:38][Find-DbaInstance] Processing: [Server Name\Instance]
COMMENTAIRES : [16:02:59][Resolve-DbaNetworkName] Connecting to [Server Name]
COMMENTAIRES : [16:02:59][Resolve-DbaNetworkName] IP Address from [Server Name] is [IP Address]
COMMENTAIRES : [16:02:59][Resolve-DbaNetworkName] Getting computer information from dev-sql-010-v.domain.local
COMMENTAIRES : [16:02:59][Get-DbaCmObject] Configuration loaded | Cache disabled: False
COMMENTAIRES : [16:02:59][Get-DbaCmObject] [Server Name.domain.local] Retrieving Management Information
COMMENTAIRES : [16:02:59][Get-DbaCmObject] [Server Name.domain.local] Accessing computer using Cim over WinRM
COMMENTAIRES : [16:02:59][Get-DbaCmObject] [Server Name.domain.local] Accessing computer using Cim over WinRM - Failed!
COMMENTAIRES : [16:02:59][Get-DbaCmObject] [Server Name.domain.local] Accessing computer using Cim over DCOM
COMMENTAIRES : [16:02:59][Get-DbaCmObject] [Server Name.domain.local] Accessing computer using Cim over DCOM - Failed!
COMMENTAIRES : [16:02:59][Resolve-DbaNetworkName] Unable to get computer information from [Server Name]
COMMENTAIRES : [16:02:59][Resolve-DbaNetworkName] No WMI/CIM from [Server Name]. Getting HostName via .NET.Dns
COMMENTAIRES : [16:02:59][Resolve-DbaNetworkName] Resolving [Server Name.domain.local] using .NET.Dns GetHostEntry
COMMENTAIRES : [16:02:59][Get-DbaSqlService] Getting SQL Server namespace on [Server Name.domain.local]
COMMENTAIRES : [16:02:59][Get-DbaCmObject] Configuration loaded | Cache disabled: False
COMMENTAIRES : [16:02:59][Get-DbaCmObject] [Server Name.domain.local] Retrieving Management Information
COMMENTAIRES : [16:02:59][Find-DbaInstance] Computer [Server Name\Instance] could be contacted, but no trace of an SQL Instance was found. Skipping...

**Comment by potatoqualitee** [comment]
Sorry for the delay - what is the version of the sql servers that are missing?

**Comment by AlreadyPicked** [comment]
All of them. I can't get any server to respond. The one above was a SQL Server 2012 SP3.

**Comment by potatoqualitee** [comment]
i wonder if this is a french thing. @niphlod do you have any Italian servers to test?

@AlreadyPicked - can you try again? I modified the command and it _may_ have opened up more discovery possibilites. use `-ScanType All`

**Comment by AlreadyPicked** [comment]
That seems to did the trick. Tried **-ScanType All** and without, both worked.

Thanks!

**Comment by potatoqualitee** [comment]
awesome news!! thanks for your report. This was a good and necessary fix.
