### ISSUE TITLE
Export-SpConfigure does not allow path relative to instance

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#4031]
Test path does not validate that the path could be local to the instance and not on the server. We support this in other export commands and should include that in this one as well.

This would mean that the import equivalent should support it as well.

```C:\git\dbatools [development ≡] 109ms
> Export-DbaSpConfigure -SqlInstance win-sql01 -Path C:\LocalServerTemp
WARNING: [19:38:52][Export-DbaSpConfigure] Can't write to  | Cannot bind argument to parameter 'Path' because it is null.
C:\git\dbatools [development ≡] 97ms
>```

**Comment by sqllensman** [comment]
Not exactly clear on what this issue is.
I have pull request currently open to modify this function and so could incorporate necessary changes

**Comment by wsmelton** [comment]
Your PR is already merged.

The path passed in in the current command assumes it is local to the machine the script is running on and not the remote instance. (Use of Test-Path does not support remote validation.)
