### ISSUE TITLE
Backup-DbaDatabase with -CompressBackup flag, not compressing when being ran from task scheduler

### ISSUE THREAD

**Issue by cusco** [sqlcollaborative/dbatools#4035]
Hello.

I'm finding a weird situation. My command is:
`Backup-DbaDatabase -SqlInstance sqlcore -BackupDirectory "E:\bk" -Type Full -FileCount 1 -CreateFolder -Database perfMasterFile -CompressBackup`

If I run it from a power shell prompt, the backup is compressed.
If I save this to a script.ps1 and run it from task scheduler, the backup is not compressed.

I can't understand why

What other information could I provide you to help debug this?

**Comment by Stuart-Moore** [comment]
Hmm, can't repro this on command line. Using latest version of prod:
![image](https://user-images.githubusercontent.com/5613670/45618981-8e84bc80-ba6f-11e8-9640-1e3e92ce7280.png)

Could you post the entire contents of script.ps1 please. It might be loading a different version of the module than you're running on the command line

And could you confirm which version of the module you're running, just in case the bug is in Dev.

thanks

**Comment by cusco** [comment]
Hello

The script contains: 
`Backup-DbaDatabase -SqlInstance sqlcore -BackupDirectory "E:\bk" -Type Full -FileCount 1 -CreateFolder -Database perfMasterFile -CompressBackup

Remove-DbaBackup -BackupFolder "e:\bk\perfMasterFile" -RetentionPeriod 3h -BackupFileExtension trn
Remove-DbaBackup -BackupFolder "e:\bk\perfMasterFile" -RetentionPeriod 3h -BackupFileExtension bak
`

How do I check the version of the tool suit I'm using?

**Comment by Stuart-Moore** [comment]
unless you're pulling versions from git, then this should tell you what the default would be `get-module dbatools -ListAvailable`

How are you checking if the backup is compressed or not?

**Comment by cusco** [comment]
`ModuleType Version    Name
---------- -------    ----
Script     0.9.380    dbatools`

The backup ran in a power shell instance, by hand, resulted in a file of 300GB, while the same but not compressed resulted in 900GB. The nightly file is always 900ish GB. 
I haven't verified it in any other way

**Comment by Stuart-Moore** [comment]
Still trying to repo this. 
Is the test db encrypted? And is there any chance you've got multiple versions of dbatools installed? We did fix a bug a week or so around encryption and compression, so just wondering if it's a throwback to that.

**Comment by cusco** [comment]
Hello, 
The database is not encrypted. I re-installed with "Invoke-Expression (Invoke-WebRequest https://dbatools.io/in)" - using windows server 2012, both with my user, and administrator.

It updated.

The task scheduler is set to run as my user (which is a domain admin).

The output file is still around 900GB.

I'm not sure what else I can do to provide you with debugging info

**Comment by awickham10** [comment]
What's the program/script and arguments set to on the task scheduler action?

**Comment by cusco** [comment]
Hello

Action: Start a program
Program/script: powershell.exe

Add arguments (optional): C:\scripts\sql-backup\bkDbFull_perfMasterFile.ps1


image with snip below:
![image](https://user-images.githubusercontent.com/2995711/46153793-ba702100-c26b-11e8-809e-d33aa1e7bf77.png)

**Comment by awickham10** [comment]
You could setup some logging in your script. Just output the Backup-DbaDatabase output to a text file or CSV - then you could at least see if the parameter is being honored or not. It seems really odd that it wouldn't be accepting a parameter.

```powershell
Backup-DbaDatabase -SqlInstance sqlcore -BackupDirectory "E:\bk" -Type Full -FileCount 1 -CreateFolder -Database perfMasterFile -CompressBackup | Export-Csv E:\bk\log.csv -NoTypeInfo
```

**Comment by cusco** [comment]
will do, will have something tomorrow to look at

**Comment by cusco** [comment]
Hello, here is the csv output. It shows compression

`"BackupComplete","BackupFile","BackupFilesCount","BackupFolder","BackupPath","DatabaseName","Notes","Script","Verified","ComputerName","InstanceName","SqlInstance","Database","UserName","Start","End","Duration","Path","TotalSize","CompressedBackupSize","CompressionRatio","Type","BackupSetId","DeviceType","Software","FullName","FileList","Position","FirstLsn","DatabaseBackupLsn","CheckpointLsn","LastLsn","SoftwareVersionMajor","IsCopyOnly","LastRecoveryForkGUID","RecoveryModel"
"True","perfMasterFile_201809280020.bak","1","E:\bk\perfMasterFile","E:\bk\perfMasterFile\perfMasterFile_201809280020.bak","perfMasterFile","","BACKUP DATABASE [perfMasterFile] TO  DISK = N'E:\bk\perfMasterFile\perfMasterFile_201809280020.bak' WITH NOFORMAT, NOINIT, NOSKIP, REWIND, NOUNLOAD, COMPRESSION,  STATS = 1","False","SQLCORE","MSSQLSERVER","SQLCORE","perfMasterFile","PCMEDIC\tiago.geada","28/09/2018 00:20:13","28/09/2018 02:25:45","02:05:32","System.String[]","999,53 GB","956,90 GB","1,04","Full","83534","Disk","Microsoft SQL Server","System.String[]","System.Object[]","1","844291000002379200001","843305000001826400055","844306000000772800055","844327000000529600001","12","False","cc1f8a65-ef3d-43a0-9485-0af1ea66db2d",""
`

So is the backup compressed? I find it odd, because when I ran it from command line it outputted a much smaller file.

This is a big database, and on a slow disk, so it's not every day I get to run the backup by hand (I'm not awake during the time the scheduler runs)

**Comment by cusco** [comment]
it shows


TotalSize: 999,53 GB
CompressedBackupSize: 956,90 GB
CompressionRatio: 1,04


This means it is being compressed? :/

**Comment by Zhunya** [comment]
Check with RESTORE HEADER, you will see:

 CompressedBackupSize | BackupSize
------------|-------------
 222967395328 | 53444629211

**Comment by awickham10** [comment]
Yeah, I would say it is being compress but there is something within the database that is causing poor backup compression. Are you using page or row encryption in the database? The minimal amount of compression you're getting for the backup leads me to believe the data is already compressed. You'll only get a minimal amount of compression for the backup if that is the case.

**Comment by cusco** [comment]
BackupSize             : 1073242366976
CompressedBackupSize   : 1027464804060

OK, I believe it is being compressed, just a little.

I'm not using any kind of compression in the dbms.

I will double check, not sure when, if I can make a manual backup with compression and have a smaller output file.

Anyway, thank you all for your attention, and sorry to bother you what resulted to be a non-issue!


And thank you for this amazing set of tools :-)
