### ISSUE TITLE
Extend Test-DbaLastBackup pipe support [BackupHistory]

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#4048]
### Summary of new feature

* Add support for `[Sqlcollaborative.Dbatools.Database.BackupHistory]` from pipe or variable.

### Latest version of dbatools as of writing

* 0.9.431

**Comment by Stuart-Moore** [comment]
Thanks, I don't get onto slack that often so don't always see the origins of issues.

Would it be better to modify Test-DbaLastBackup to take multiple instances?

Would save adding another pathway through the function? Could be implemented as just another loop around the core db loop? Probably faster and more memory efficient than using a pipeline?
