### ISSUE TITLE
Import-DbaCsvToSql: the '++' operator works only on numbers. The operand is a 'System.String'

### ISSUE THREAD

**Issue by jrob24** [sqlcollaborative/dbatools#4052]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
    Import-DbaCsvToSql -table tablename -sqlinstance connectionstring -database DBName -Schema dbo -FirstRowColumns -csv Path\To\Csv
#>
```

## Expected Behavior

Import data into table

## Actual Behavior

I have been using this function for weeks, 10s of times a day no problem. Then today I started receiving the error "Import-DbaCsvToSql: the '++' operator works only on numbers. The operand is a 'System.String'" and now the function no longer works.

## Environmental data

 - PowerShell: 5.1.14409.1012
 - - SQL Server: 2016 SP2

**Comment by potatoqualitee** [comment]
@jrob24 - are you still having this issue? and can you repro at the command line?
