### ISSUE TITLE
Test-SqlMigrationConstraint - Script Analyzer Test failure

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#406]
We're adding Pester tests and AppVeyor to dbatools, see https://github.com/sqlcollaborative/dbatools/wiki/AppVeyor-and-Pester for more detail.

The following rules were highlighted for this function:

RuleName|Severity|Line|Message
-----------|--------|-----|---------
PSShouldProcess|Warning|1|'Test-SqlMigrationConstraint' has the ShouldProcess attribute but does not call ShouldProcess/ShouldContinue.
PSAvoidUsingWriteHost|Warning|183|File 'Test-SqlMigrationConstraint.ps1' uses Write-Host. Avoid using Write-Host because it might not work in all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, captured, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
PSAvoidUsingWriteHost|Warning|237|File 'Test-SqlMigrationConstraint.ps1' uses Write-Host. Avoid using Write-Host because it might not work in all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, captured, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.

**Comment by niphlod** [comment]
see https://github.com/sqlcollaborative/dbatools/issues/627 , aka "the issue that tracked them all"
