### ISSUE TITLE
Install-DbaWhoIsActive throws batch parser error.

### ISSUE THREAD

**Issue by githubsqltoolsse** [sqlcollaborative/dbatools#4073]
### Before submitting a bug report:

- [ x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ x] Verified this bug is not already reported in an issue
- [ ?] Verified errors are not related to permissions
- [ x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell

Install-DbaWhoIsActive -SqlInstance SESTODS030 -Database maintenance -Force -EnableException

This fails on some of our servers but works on most of them. I can also run the same command remotely from a client and it works.

```

## Expected Behavior

I expect to get WhoIsActive installed

## Actual Behavior

Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database 'maintenance'. "
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.439\allcommands.ps1:99210 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SESTODS030:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Install-DbaWhoIsActive

## Environmental data

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.14393.2515                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.14393.2515                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1 

 - PowerShell: 
 - - SQL Server: 
Microsoft SQL Server 2014 (SP2-CU12) (KB4130489) - 12.0.5589.7 (X64)   Jun  9 2018 11:17:15   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
thank you for the report.

right after it fails, can you do an `$error[0] | select *` and tell us what it says?
tks

**Comment by githubsqltoolsse** [comment]
Hi,  
That gave me some more details. (This looks interesting  .FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.BatchParser.dll')


This is the output from the command:

PSMessageDetails      :
Exception             : System.Exception: Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery fa
                        iled for Database 'maintenance'. " ---> System.Exception: Exception calling "ExecuteNonQuery" w
                        ith "1" argument(s): "ExecuteNonQuery failed for Database 'maintenance'. " ---> System.Manageme
                        nt.Automation.MethodInvocationException: Exception calling "ExecuteNonQuery" with "1" argument(
                        s): "ExecuteNonQuery failed for Database 'maintenance'. " ---> Microsoft.SqlServer.Management.S
                        mo.FailedOperationException: ExecuteNonQuery failed for Database 'maintenance'.  ---> System.IO
                        .FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.BatchParser.dll' o
                        r one of its dependencies. The specified module could not be found.
                           at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean
                        throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
                           at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean igno
                        reCase)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.GetStatements(String query, Execut
                        ionTypes executionType, Int32& statementsToReverse)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand,
                         ExecutionTypes executionType, Boolean retry)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection s
                        qlCommands, ExecutionTypes executionType, Boolean retry)
                           at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQuery(StringCollection quer
                        ies, ExecutionTypes executionType)
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands,
                         ExecutionTypes executionType)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands,
                         ExecutionTypes executionType)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext f
                        uncContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame fra
                        me)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
                           --- End of inner exception stack trace ---
                           --- End of inner exception stack trace ---
TargetObject          : SESTODS030
CategoryInfo          : NotSpecified: (SESTODS030:String) [], Exception
FullyQualifiedErrorId : dbatools_Install-DbaWhoIsActive
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.439\allcommands.ps1:
                        line 99210
                        at Install-DbaWhoIsActive<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.439
                        \allcommands.ps1: line 50972
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by awickham10** [comment]
Issue #4083 also reports a similar error re: Microsoft.SqlServer.BatchParser.dll

**Comment by potatoqualitee** [comment]
ah ha! i knew it came up recently. strange  how it's all at once now. i recall us having this issue in the past and it was unresolved cuz it seemed related to x86 but #4083 reported they're running x64. currently cant repro on win10 x64. can you try @awickham10 ?

**Comment by awickham10** [comment]
This seems like a reasonable place to start looking. I wasn't able to reproduce it either (Win10 x64 against 2019 Ubuntu).

https://social.technet.microsoft.com/wiki/contents/articles/35832.sql-server-troubleshooting-could-not-load-file-or-assembly-microsoft-sqlserver-batchparser.aspx

**Comment by EnjoyinMoss** [comment]
### Potential workaround

The first of the following two links appears to describe the Batch Parser issue.  

The second link is the download link referenced in the comments of the first.  

The fix appears to be contained within the Visual C redistributable.   Both x86 and x64 versions are available however I can only confirm working on x64 (Win Server 2008 R2).

Link 1: [https://social.technet.microsoft.com/Forums/en-US/7a71121c-83b1-49b4-ad30-3a5f20e7afbf/smo-2017-microsoftsqlserverbatchparserdll-load-error?forum=sqlsmoanddmo](url)

Link 2: [https://www.microsoft.com/en-us/download/details.aspx?id=40784](url)

Please feedback with any results.
Cheers
