### ISSUE TITLE
dbabuildreference –update WARNING: [12:39:12][Get-DbaBuildReferenceIndexOnline] Couldn't download updated index from https://sqlcollaborative.github.io/assets/dbatools-buildref-index.json

### ISSUE THREAD

**Issue by kkgrissom** [sqlcollaborative/dbatools#4086]
### Before submitting a bug report:

- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.

NONE
*/
```

```powershell
<#
   # at our site
get-dbabuildreference –update

#>
```

Download latest JSON files from web

Couldn't download updated index from
 https://sqlcollaborative.github.io/assets/dbatools-buildref-index.json

Investigation of issue:

Tracked down the issue with the DBATOOLS powershell command get-dbabuildreference –update.
Inside that code (Get-DbaBuildReferenceIndexOnline) they try a couple of things to get the file
1. First just a straight call
2. Try a default proxy setting
3. Then they just give up
Found this article and tried running the parts of the code and found the error:
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:15
+ ... ebContent = Invoke-WebRequest "https://sqlcollaborative.github.io/ass ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  + CategoryInfo         : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
  + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Looking for this error on the web found the following article:

https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel
tried parts of the code (Get-DbaBuildReferenceIndexOnline)  with this set
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

and then the code was successful in downloading that piece.

## Environmental data

 - PowerShell: 
 - - SQL Server:

**Comment by niphlod** [comment]
fixed via https://github.com/sqlcollaborative/dbatools/commit/17d1ef7f85cc7e6c00f94d730d055aa18cae01dd
