### ISSUE TITLE
Copy-DBALinkedServer does not copy network name of linked server

### ISSUE THREAD

**Issue by willtb** [sqlcollaborative/dbatools#4087]
### Before submitting a bug report:

- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

Create a linked server via the GUI or T-SQL.
Example T-SQL:
--T-SQL to run on source server
USE [master]
GO
EXEC master.dbo.sp_addlinkedserver @server = N'LINKTEST', @srvproduct=N'SQL Server'
GO
--update network name
exec sp_setnetname 'LINKTEST','SRV01'

--Check data_source differs in sys.servers
select * from sys.servers where name = 'LINKTEST'

```powershell
Copy-DBALinkedServer -Source SRVSrc -Destination SRVDest -LinkedServer LINKTEST

## Expected Behavior

--Run following T-SQL on SRVDest
--Check data_source differs in sys.servers
select * from sys.servers where name = 'LINKTEST'
<!--
Expected behaviour is that the name = LINKTEST and data_source = SRV01
-->

## Actual Behavior
<!--
The data_source column matches the name column which is incorrect.
-->

## Environmental data

<!-- Provide output of the following two commands -->

 - PowerShell: 
Name                           Value                                                                                                     
----                           -----                                                                                                     
PSVersion                      5.1.14409.1012                                                                                            
PSEdition                      Desktop                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                   
BuildVersion                   10.0.14409.1012                                                                                           
CLRVersion                     4.0.30319.42000                                                                                           
WSManStackVersion              3.0                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                       
SerializationVersion           1.1.0.1

 - - SQL Server: <!-- SELECT @@VERSION output -->
Microsoft SQL Server 2008 (SP4) - 10.0.6535.0 (X64)   Apr 17 2015 19:49:03   Copyright (c) 1988-2008 Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

**Comment by potatoqualitee** [comment]
thanks for the T-SQL - it's exactly what I needed. I'll take a look soon. hit me up if I havent addressed this in a week

**Comment by willtb** [comment]
Thanks for the quick response! I'll keep on the lookout for the update.
Don't work too hard :)

**Comment by niphlod** [comment]
@potatoqualitee : https://gph.is/1mDYMCI

**Comment by andraptor** [comment]
When @srvproduct of LinkedServer is not 'SQL Server' (something defined manually, for example 'SQL' ) and @provider = 'SQLNCLI', it fails with error: 
Issue adding linked server [SERVERNAME]. | You cannot set network name on server 'LINKEDSERVERNAME' because it is not a linked SQL Server.

This error connected to sp_setnetname SP. 
Please fix that to this error does not interrupt execution. 
A workaround for now is commenting next block in the function in allcommands.zip archive:
#if ($copyLinkedServer.Name -ne $copyLinkedServer.DataSource) {
#    $sql2 = "EXEC sp_setnetname '$($copyLinkedServer.Name)', '$($copyLinkedServer.DataSource)'; "
 #    $destServer.Query($sql2)
 #}
