### ISSUE TITLE
Test-DbaDbCompression - PercentScan and PercentUpdate fields are always NULL

### ISSUE THREAD

**Issue by cjmcneill** [sqlcollaborative/dbatools#4099]
PercentScan and PercentUpdate fields are always NULL resulting in incorrect recommendations for Compression Type. 

## Steps to Reproduce
 test-dbadbcompression SQLInstanceName | Out-GridView

## Expected Behavior
Expect to see numeric percentage values for PercentScan and PercentUpdate fields

## Actual Behavior
Always see NULL values for PercentScan and PercentUpdate fields

## Fix required
Issue is with the following statement, the join on "OBJECT_ID(tmp.TableName) = i.[object_id]" will never work as OBJECT_ID needs to be supplied SchemaName.TableName to work. I would suggest adding an object_id column to the temp table, testdbacompression, and then joining on the object_id fileds instead as shown below....

UPDATE ##testdbacompression
SET  [PercentScan] = i.range_scan_count * 100.0 / NULLIF((i.range_scan_count + i.leaf_insert_count + i.leaf_delete_count + i.leaf_update_count + i.leaf_page_merge_count + i.singleton_lookup_count), 0)
    ,[PercentUpdate] = i.leaf_update_count * 100.0 / NULLIF((i.range_scan_count + i.leaf_insert_count + i.leaf_delete_count + i.leaf_update_count + i.leaf_page_merge_count + i.singleton_lookup_count), 0)
FROM sys.dm_db_index_operational_stats(db_id(), NULL, NULL, NULL) i
INNER JOIN ##testdbacompression tmp ON OBJECT_ID(tmp.TableName) = i.[object_id]
    AND tmp.IndexID = i.index_id;

should be changed to this.....

UPDATE ##testdbacompression
SET  [PercentScan] = i.range_scan_count * 100.0 / NULLIF((i.range_scan_count + i.leaf_insert_count + i.leaf_delete_count + i.leaf_update_count + i.leaf_page_merge_count + i.singleton_lookup_count), 0)
    ,[PercentUpdate] = i.leaf_update_count * 100.0 / NULLIF((i.range_scan_count + i.leaf_insert_count + i.leaf_delete_count + i.leaf_update_count + i.leaf_page_merge_count + i.singleton_lookup_count), 0)
FROM sys.dm_db_index_operational_stats(db_id(), NULL, NULL, NULL) i
INNER JOIN ##testdbacompression tmp ON tmp.ObjectID = i.[object_id]
    AND tmp.IndexID = i.index_id;

## Environmental data
 - PowerShell: 

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: 
Microsoft SQL Server 2016 (SP1-CU7-GDR) (KB4057119) - 13.0.4466.4 (X64)   Dec 22 2017 11:25:00   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: )

**Comment by jpomfret** [comment]
Hey there,
When the PercentScan and PercentUpdate are null it should just go off of the RowEstimatePercentOriginal and PageEstimatePercentOriginal to make suggestions. Do you get no suggestions at all?

![image](https://user-images.githubusercontent.com/981370/46430455-f77a5e80-c716-11e8-81de-6723e34f4065.png)

**Comment by cjmcneill** [comment]
Hi Jess,

The issue is that the PercentScan and PercentUpdate columns are always NULL for all tables and indexes even though I know that there is activity occurring on them, see below. I think the piece of code that calculates these values and updates ##testdbacompression has an incorrect join. 

INNER JOIN ##testdbacompression tmp ON OBJECT_ID(tmp.TableName) = i.[object_id] will never work correctly as the OBJECT_ID function needs to be supplied schema.tablename instead of just tablename.

Thanks,
Chris

![image](https://user-images.githubusercontent.com/34237965/46433962-1f36ea00-c74a-11e8-92e9-45966817ac99.png)

**Comment by cjmcneill** [comment]
Hi Jess,

I looked a bit closer into this and it appears to be when tables are not in the default dbo schema that we get this issue. If tables are in dbo then OBJECT_ID(tmp.TableName) will work correctly however when they are not in the default dbo schema it won't, the full schemaname.tablename needs to be supplied to the OBJECT_ID function when objects are outside of dbo.

Thanks,
Chris

**Comment by jpomfret** [comment]
Ah you're spot on, issue is with schema's other than dbo. Fix is incoming, thanks for reporting!
