### ISSUE TITLE
Copy-SqlLogin - allow different name on destination

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#410]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Copies same name between source and destination

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

ctrlb [8:36 AM]  
i can see it, yeah, sorta like how Copy-SqlDatabase should do the same. It'd be a new param that accepts a hashtable

**Comment by mshamann** [comment]
So we take in a hash table, then match the key to the name being added, and if it matches then it use the value to make a new name. 

Should this work with only SQL Logins or for Windows Auth logins as well? 

pseudo-code looking something like:

{ adminUser: "newAdminUser" } 

If ( currentLogin = adminUser ) and ( NewParam is true ) then set currentLogin name to newAdminUser.

Sound about right?

**Comment by ctrlbold** [comment]
I'd go with If $hashtable exists and the username exists in the hashtable, then .name = new name. I think it should support both windows and sql and it's possible.

**Comment by gbargsley** [comment]
I agree with Windows and SQL logins if possible.

**Comment by gbargsley** [comment]
I can perform tests when the module is updated and ready.

**Comment by SirCaptainMitch** [comment]
This was merged in the last release.
