### ISSUE TITLE
Set-DbaLogin Slow - Get-DbaRoleMember Necessary in Output?

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#4107]
### Before submitting a bug report:
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
Set-DbaLogin -SqlInstance server1 -Login login1 -Disable
```

## Actual Behavior
The Get-DbaRoleMembership call takes a long time to complete in Set-DbaLogin. The only usage for this is in the output there is a ServerRoles property that gets populated with a list of all of the server roles the login is a member of. Is it necessary to keep this?

Some timings:
After Connection Elapsed: 162ms
After Disable Elapsed: 241ms
After Alter Elapsed: 326ms
After Get-DbaRoleMembership Elapsed: 5383ms

## Environmental data
PSVersion                      5.1.14393.2485
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2485
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Microsoft SQL Server 2016 (SP2-CU3) (KB4458871) - 13.0.5216.0 (X64)   Sep 13 2018 22:16:01   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by niphlod** [comment]
given there's AddRole and RemoveRole I'd say it's needed.

**Comment by potatoqualitee** [comment]
thanks for taking a look niph, i was about to say remove it :/ that's a huge hit. Perhaps move the roles out to commands of their own?

**Comment by niphlod** [comment]
design-wise get-dbarolemember is not a good call.
Improvements for this usecase, from "fast fix/small deal" to "slower fix/complete rewrite/premature optimization is the root of all evil":
- pass `-Database master` to it, it'll probably get waaaay more snappier, as it won't loop over all user databases
- introduce another parameter to get-dbarolemember (such as `-NoDbRole`) which skips the loop over dbs, and pass that switch here
- be fair and at _least_ call get-dbarolemember ONCE per instance

**Comment by awickham10** [comment]
I added the ```-Database master``` in PR #4117. I'll keep evaluating other performance improvements (e.g. calling only once per instance). That did make a significant difference though. Thanks @niphlod!
