### ISSUE TITLE
Invalid path error when using Export-DbaDacpac to the network share

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#4119]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
Export-DbaDacpac -SqlInstance myInstance:1234 -Database MyDBName -Path \\some\network\path

WARNING: [15:58:54][Export-DbaDacPackage] Standard output - *** Argument 'TargetFile' has an invalid value:
'Microsoft.PowerShell.Core\FileSystem::\\some\network\path\myInstance,1234-MyDBName.dacpac'.
*** The given path's format is not supported.
```

## Expected Behavior
Create file as expected

## Actual Behavior
Recent [update](https://github.com/sqlcollaborative/dbatools/commit/32fda0245779f881cc704a3f71129cc8c0e601ed#diff-85064811f8b503a68b6162c027d284cb) to the Path handling in the function broke the ability to use network path as a destination, since Resolve-Path \\nw\path | % Path returns a path including a provider. Using ProviderPath would probably be a better approach:
```
Resolve-Path \\nw\path | % ProviderPath
```

## Environmental data
 - PowerShell: 
PSVersion                      5.1.15063.1266
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1266
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by nvarscar** [comment]
@jasonmcboyd please let me know if the solution works on your end as expected - I'll PR it later.

**Comment by jasonmcboyd** [comment]
@nvarscar Looks good from my side.
