### ISSUE TITLE
Break Out Get-DbaRoleMember into Get-DbaDbRoleMember and Get-DbaServerRoleMember?

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#4128]
---
name: Break out Get-DbaRoleMember into Get-DbaDbRoleMember and Get-DbaServerRoleMember
---

### Summary of new feature
In order to get server level role members you have to execute ```Get-DbaRoleMember -SqlInstance server1 -Database master -IncludeSystemLevel```. If you don't specify ```-Database master``` you'll end up with slow performance because you'll be getting back all database level role members even though you don't want them.

### Proposed technical details (if applicable)
Split Get-DbaRoleMember out into two functions: Get-DbaDbRoleMember and Get-DbaServerRoleMember. If we want to preserve backwards compatibility we could keep Get-DbaRoleMember and just have it call those two new functions (I like this idea @jpomfret).

### Latest version of dbatools as of writing
0.9.411

**Comment by niphlod** [comment]
hum...... maybe the shortest friction path is renaming get-dbarolemember to get-dbadbrolemember, deprecate -includesystemlevel (to be removed after 1.0) and create a brand new get-dbaserverrolemember ? Also, we'd port everything to 1.0 readyness in the process, get-dbarolemember has some road to cover for 1.0 ^__^

**Comment by awickham10** [comment]
Yeah, definitely needs some 1.0 updating (messaging, test-bound, etc.). I'm happy to take this on if that is the route we're wanting to go.

**Comment by niphlod** [comment]
let's wait a day or two for the big guns to weight in, then with a plan the work can be started.

**Comment by awickham10** [comment]
Yup, sure thing.

**Comment by wsmelton** [comment]
I tried that route and was turned down but can't recall why.

**Comment by wsmelton** [comment]
Some discussion was here https://github.com/sqlcollaborative/dbatools/pull/2700#discussion_r151960785

**Comment by awickham10** [comment]
"We certainly need to examine the RoleMember function(s). The existing one can be improved, no doubt. We have to decide whether we combine or split the Database and Server Role members."

I'd say we're at a point where there is a use case to get server level role membership only and the current ```Get-DbaRoleMembership``` doesn't provide that ability. In order to provide that functionality we would have to add a ```-NoDbRole``` parameter, so now to get server level role membership you need to call ```Get-DbaRoleMembership -IncludeSystemLevel -NoDbRole``` which sure doesn't seem very straight forward/user friendly.

**Comment by wsmelton** [comment]
I'm fine with spilling them out.

**Comment by awickham10** [comment]
I put a draft out to take a look at. I'll describe some of the changes over there so the discussion is in one place.

**Comment by potatoqualitee** [comment]
Thanks much, I'm merging in some small test fixes. Can you check the one I set to skip in Set-DbaLogin, please? 

I'm glad it failed - made me take a closer look and I'm thinking that the Set-DbaLogin does too much. Should we have Add/Remove-DbaDbRole and Add/Remove-DbaDbRole ? 

`Get-DbaLogin | Add-DbaServerRole`
`Get-DbaLogin | Add-DbaDbRole` and `Get-DbaDbUser | Add-DbaDbRole`

**Comment by potatoqualitee** [comment]
i can also see why it was done - it's in the SMO

`$l.AddToRole($role)`

**Comment by awickham10** [comment]
> Thanks much, I'm merging in some small test fixes. Can you check the one I set to skip in Set-DbaLogin, please?
> 
> I'm glad it failed - made me take a closer look and I'm thinking that the Set-DbaLogin does too much. Should we have Add/Remove-DbaDbRole and Add/Remove-DbaDbRole ?
> 
> `Get-DbaLogin | Add-DbaServerRole`
> `Get-DbaLogin | Add-DbaDbRole` and `Get-DbaDbUser | Add-DbaDbRole`

I haven't forgotten this - I'll probably get a chance to look at it tomorrow.

**Comment by niphlod** [comment]
@awickham10 : has this been done ?

**Comment by awickham10** [comment]
> Thanks much, I'm merging in some small test fixes. Can you check the one I set to skip in Set-DbaLogin, please?

@potatoqualitee where did you set one to skip? I can't find what you're referring to.

**Comment by potatoqualitee** [comment]
hmmm looks like i unskipped 🤔

**Comment by awickham10** [comment]
So good to go? 🤷‍♂️ 

The last step would be removing the Get-DbaRoleMember function.

**Comment by potatoqualitee** [comment]
closed as fixed 👍
