### ISSUE TITLE
Export-SqlLogin and Update-SqlPermissions

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#413]
Is this a *feature* OR *bug*:
Bug
- Powershell Version: 
- OS Version: 
4
**Steps to Reproduce**
export-sqllogin with a user that has object level permissions set.
**Action Results**

**Expected Results**

**Additional comments**

When granting database permissions for a user, if you grant them direct access to an object, like select on a table, those permissions are not exporting.  I think the reason is that dbatools is only using the EnumDatabasePermissions and EnumMembers (loop through database roles) .  There is EnumObjectPermissions to get any object level permissions that were set.  I have put this together based on what I saw in the code for Export-Sqllogin

```powershell
 $objperms = $db.EnumObjectPermissions($UserName)
				    foreach ($objperm in $objperms)
				    {

                            $objpermstate = $null
					        $objpermtype = $null
					        $objgrantor = $null
                            $UserName = $null
                            $ObjName = $null
                            $ObjSchema = $null

					        $objpermstate = $objperm.permissionstate
					        $objpermtype = $objperm.PermissionType
					        $objgrantor = $objperm.grantor
                            $UserName = $objperm.grantee
                            $ObjName = $objperm.objectname
                            $ObjSchema = $objperm.objectschema

                            IF ($ObjName -ne $null -and $ObjSchema -ne $null)
                                {$ObjectName = "[$objSchema].[$ObjName]"}
                            ELSEIF ($ObjName -eq $null -and $ObjSchema -ne $null)
                                {$ObjectName = "[$objSchema]"}
						    ELSE
                                {$ObjectName = "[$ObjName]"}
                            

					        if ($objpermstate -eq "GrantWithGrant")
					        {
						        $objgrantwithgrant = "WITH GRANT OPTION"
						        $objpermstate = "grant"
					        }
					        else
					        {
						        $objgrantwithgrant = $null
					        }
						
					        $outsql += "$objpermstate $objpermtype ON $ObjectName TO [$username] $objgrantwithgrant AS [$objgrantor];`r`n"
  				    }
```

**Comment by wsmelton** [comment]
The 2 commands referenced are not intended to touch object-level permissions within a database. Just at a high level of a database. I think the feature you are referring to would be under [Export-Sqluser](https://trello.com/c/TMVjbWBH), which was proposed on Trello.

I can see in the wording of help though it makes the impression that this should get all the database level permissions. We may need to expand that to make it more clear: 

> Exports Windows and SQL Logins to a T-SQL file. Export includes login, SID, password, default database, default language, server permissions, server roles, **db permissions**, db roles.

**Comment by dczarny** [comment]
But both of those functions do touch database level permissions. That is part of the problem. Either the database level permission scripts need to be removed or the other object added.  This is what is causing some of the problems I have been experiencing with these functions.

Thank you,
Derek Czarny



On Sat, Dec 10, 2016 at 9:24 PM -0600, "Shawn Melton" <notifications@github.com<mailto:notifications@github.com>> wrote:


The 2 commands referenced are not intended to touch object-level permissions within a database. Just at a high level of a database. I think the feature you are referring to would be under Export-Sqluser<https://trello.com/c/TMVjbWBH>, which was proposed on Trello.

I can see in the wording of help though it makes the impression that this should get all the database level permissions. We may need to expand that to make it more clear:

Exports Windows and SQL Logins to a T-SQL file. Export includes login, SID, password, default database, default language, server permissions, server roles, db permissions, db roles.

-

**Comment by wsmelton** [comment]
Well, technically yes but not object-level permissions. If you look at the properties of a login or when you create one, the Export command is limited to the functionality of that process. It is strictly exporting the properties of the login at the server level.

![image](https://cloud.githubusercontent.com/assets/11204251/21078187/4cbb27fc-bf2c-11e6-9d7e-dda89fd1d906.png)

**Comment by dczarny** [comment]
In the export-sqllogin code I see enumdatabasemappings, a foreach database loop scripting out the database users and roles, and enumdatabasrpermissions. I am not sure if that is dead code in the routine, but it's in there.

Thank you,
Derek Czarny



On Sat, Dec 10, 2016 at 11:02 PM -0600, "Shawn Melton" <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, technically yes but not object-level permissions. If you look at the properties of a login or when you create one, the Export command is limited to the functionality of that process. It is strictly exporting the properties of the login at the server level.

[image]<https://cloud.githubusercontent.com/assets/11204251/21078187/4cbb27fc-bf2c-11e6-9d7e-dda89fd1d906.png>

-

**Comment by wsmelton** [comment]
@dczarny I'm not disputing what the command does currently. I'm trying to explain that their purpose is simply not to get the object-level permissions. That functionality should be put in another command as it has been [proposed on Trello](https://trello.com/c/TMVjbWBH).

**Comment by niphlod** [comment]
export-sqluser is in. I think that settles this issue for now.
@wsmelton : opinions ?
