### ISSUE TITLE
Backup-DbaDatabase - allow backup to null

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4140]
to assist with AG seeding per request of John Martin, but I'm also going to start working on AG commands and would like to use it.

**Comment by Stuart-Moore** [comment]
Already implemented.

**Comment by potatoqualitee** [comment]
oh yay! I looked for `$null` in the code but didn't find anyting obvious. I'll look for regular null, sorry.

**Comment by potatoqualitee** [comment]
so sorry, can you give me some hints ? I looked again and can't figure it out. I also tried some sample backups with no luck.

**Comment by Stuart-Moore** [comment]
Sorry documented it in test 🙄

 Backup-DbaDatabase -SqlInstance $script:instance1 -Database master -BackupFileName NUL

Will fix up the cbh when I get back to Nottingham.

**Comment by potatoqualitee** [comment]
thanks so much! passed the info on
