### ISSUE TITLE
Connect-DbaInstance only returns a result for the first instance if I list several

### ISSUE THREAD

**Issue by camillagaardsted** [sqlcollaborative/dbatools#4192]
The Connect-DbaInstance accepts a list of sql instances for the parameter SqlInstance according to the documentation (-SqlInstance <DbaInstanceParameter[]>), but the cmdlet only returns a result for the first instance I specify in a list of names.

Here is an example - I have two instances running on my local machine:

Connect-DbaInstance 'localhost','localhost\cgsql'  | Select instancename,edition, domaininstancename

I only get a result for the default instance localhost.

Both instances are  running and if I pipe the list instead I get the expected result:

'localhost','localhost\cgsql' | Connect-DbaInstance  | Select instancename,edition, domaininstancename
Here information for both instances are returned, since PowerShell sends each item over one at a time.

I've checked the code for Connect-DbaInstance and there is a foreach statement which is supposed to loop through all the instances and the instances are there in the $SqlInstance variable, but at the bottom of the foreach statement it just returns as soon as the first element has been processed.

foreach ($instance in $SqlInstance){ # line 2164 in allcommands.ps1 in dbatools version 0.9.475
   ...
  return $server # line 2316 in allcommands.ps1 in dbatools version 0.9.475
}

The return should be outside the foreach and of course return a list of servers.

I would like to contribute to dbatools, so feel free to assign this issue to me and I'll fix it.

**Comment by potatoqualitee** [comment]
Thank you so much for this detailed report! I've implemented the suggested fixes and have submitted a PR. It should be in master within a few hours 👍
