### ISSUE TITLE
Cannot convert argument "srv"

### ISSUE THREAD

**Issue by ruudvandebeeten** [sqlcollaborative/dbatools#4194]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
Running script below in Powershell ISE. 

```powershell
Import-Module dbatools;

[string] $InstanceName = "SOSQL25\SOSQL25A";
[string] $InstanceBackupPath = '\\path\to\backups\';
[string] $Query = "SELECT @@SERVERNAME;";


Get-DbaBackupInformation -SqlInstance $InstanceName -DatabaseName master -Path $InstanceBackupPath; 

Write-Host "First statement works";

Invoke-Sqlcmd -ServerInstance $InstanceName -Database master -Query $Query;

Write-Host "Second statement also works";

Get-DbaBackupInformation -SqlInstance $InstanceName -DatabaseName master -Path $InstanceBackupPath; 

Write-Host "Third statement fails";
```

## Expected Behavior

All the statements are ran without error.

## Actual Behavior

After running the Invoke-Sqlcmd the second Get-DbaBackupInformation returns a error, see script output below.

![error](https://user-images.githubusercontent.com/33900754/46870192-3783c480-ce2e-11e8-95a5-5410b32c95dc.PNG)

> Cannot convert argument "srv", with value: "[SOSQL25\SOSQL25A]", for "ReadBackupHeader" to type Microsoft.SqlServer.Management.Smo.Server": "Cannot convert the "[SOSQL25\SOSQL25A]" value of type "Microsoft.SqlServer.Management.Smo.Server" to type "Microsoft.SqlServer.Management.Smo.Server".

It seems that Invoke-Sqlcmd or Get-DbaBackupInformation skrews with shared variables or objects. 

When using  Invoke-Sqlcmd2 the problem does not arise. But I'm not able to change all the existing Powershell code atm. Running the script the second time, even the first statement containing Get-DbaBackupInformation fails.

## Environmental data

 - PowerShell: 
Name                           Value                                                                             
----                           -----                                                                             
PSVersion                      4.0                                                                               
WSManStackVersion              3.0                                                                               
SerializationVersion           1.1.0.1                                                                           
CLRVersion                     4.0.30319.42000                                                                   
BuildVersion                   6.3.9600.18728                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                              
PSRemotingProtocolVersion      2.2 
 - - SQL Server: Microsoft SQL Server 2016 (SP2-CU2-GDR) (KB4458621) - 13.0.5201.2 (X64)   Aug 18 2018 07:38:15   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by Stuart-Moore** [comment]
Afraid I can't replicate that:
![image](https://user-images.githubusercontent.com/5613670/46906705-9f561000-ceff-11e8-8f43-64efc05cc86e.png)

Could you rerun this with $instance.GetType() after each statement so we can see if the type changes

Neither command modifies the $InstanceName in my example, and I neither command does that anyway as far as I know.

**Comment by potatoqualitee** [comment]
Thanks so much for looking into this, Stuart!

**Comment by ruudvandebeeten** [comment]
> Afraid I can't replicate that:
> ![image](https://user-images.githubusercontent.com/5613670/46906705-9f561000-ceff-11e8-8f43-64efc05cc86e.png)
> 
> Could you rerun this with $instance.GetType() after each statement so we can see if the type changes
> 
> Neither command modifies the $InstanceName in my example, and I neither command does that anyway as far as I know.

Thank you for your reply.

$instance.GetType() does not return anything.

**Comment by potatoqualitee** [comment]
Actually, I just reread and Invoke-Sqlcmd is being run which means `SqlServer` or `SQLPS` is being loaded. Unfortunately, we do not support this configuration due to issues like this, our apologies, it's not possible to fix.

**Comment by ruudvandebeeten** [comment]
@potatoqualitee thank you for looking into the problem I'm faceing. When running the script outside of ISE the error is not occuring.

**Comment by potatoqualitee** [comment]
Happy to! I do try to avoid the ISE myself except when I have to (presentations). VS Code's host causes some issues as well. I generally try to do straight console because it's reliable.

You may run into unexpected issues in the future with the console+SqlServer too, however, I've found mixing them to be inconsistent.
