### ISSUE TITLE
Internal Command to ensure utf-8 without BOM everywhere

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#4206]
### Summary of new feature

Make an internal command that rewrites the content of a dir of .ps1 files without the utf8 BOM header. 

### Proposed technical details (if applicable)

https://gist.github.com/arebee/6d105da5fdcfcc74160b

Also, make a CI test so it doesn't happen again....

**Comment by wsmelton** [comment]
Couldn't we just take the PSSA rule and check for false?

**Comment by niphlod** [comment]
need to re-test extensively but from my recall it just whines about utf-8-nonbom when an extended ascii character is in the code. If no funny characters are around, it doesn't whine no matter the BOM, hence "no consinstency".

In any case, we ruled some time ago to NOT have bom (and we mass-rewrote everything stripping the BOM everywhere). It resurfaced not because of a "steer in directions" but for a poor default in PS, which is to generate the BOM when you pass -Encoding utf8 (and somebody redoing a mass-rewrite using either Out-File or Set-Content, which reintroduced bom).

PS core team acknowledged the mistake and seem to follow our original "rule", but there's no clear RFC stated (or nothing I can find) about the encoding of ps1 files themselves. 
We should (if we can) howl at PS core guys for a specific direction and then we'll go from there.
