### ISSUE TITLE
Show-DbaServerFileSystem not using SqlCredential parameter

### ISSUE THREAD

**Issue by LeoKurz** [sqlcollaborative/dbatools#4215]
I'm trying to use the "Show-DbaServerFileSystem" with the -SqlCredential parameter. No matter if I use a variable with a valid credential object or if I ask for if within the commandlet with "(Get-Credential)", I alwas get an error message that the user who is running the script cannot connect (because he has no rights). Obviously the commandlet doesn't use the credentials provided by the parameter.

**Comment by potatoqualitee** [comment]
Thanks for the report. The fix is now in master and the PowerShell gallery

**Comment by LeoKurz** [comment]
Wow, that was lightning fast, thank you!
__Leo
