### ISSUE TITLE
Error while running Export-dbainstance, database file is empty

### ISSUE THREAD

**Issue by sqlworldwide** [sqlcollaborative/dbatools#4236]
### Before submitting a bug report:

- [x ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x ] Verified this bug is not already reported in an issue
- [x ] Verified errors are not related to permissions
- [x ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
Run the command from local server for exporting objects of a remote SQL server. Saving scripts on a local path.
```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell

   Export-dbainstance -sqlinstance remoteServer -path D:\DR\RemoteServer
```

## Actual Behavior

6-database.sql file is empty

    Directory: D:\DR\RemoteServer

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/17/2018  10:48 AM           3801 1-sp_configure.sql
-a----       10/17/2018  10:48 AM            532 2-serverroles.sql
-a----       10/17/2018  10:48 AM              0 3-credentials.sql
-a----       10/17/2018  10:48 AM           4240 4-dbmail.sql
-a----       10/17/2018  10:48 AM           8394 5-linkedservers.sql
-a----       10/17/2018  10:48 AM              0 6-databases.sql
-a----       10/17/2018  10:51 AM          44149 7-logins.sql
-a----       10/17/2018  10:51 AM            413 8-resourcegov.sql
WARNING: [10:51:14][Get-DbaXESession] Failure | Cannot find type [Microsoft.SqlServer.Management.XEvent.XEStore]:
verify that the assembly containing this type is loaded.
-a----       10/17/2018  10:51 AM          23425 9-sqlagent.sql
Unable to find type [Microsoft.SqlServer.Replication.ReplicationServer].
At C:\Users\myaccount\Documents\WindowsPowerShell\Modules\dbatools\0.9.484\allcommands.ps1:16330 char:9
+         [Microsoft.SqlServer.Replication.ReplicationServer[]]$InputOb ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.SqlSe...plicationServer:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

-a----       10/17/2018  10:51 AM         851180 10-userobjectsinsysdbs.sql

But if I run the following I get the result.

Get-DbaDatabase -SqlInstance remoteserver|select -first 1| Export-DbaScript -Path D:\DR\RemoteServer|invoke-item

## Environmental data

Name                           Value
----                           -----
PSVersion                      5.1.16299.637
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.637
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Thanks for the request! I've updated the docs to clarify - we export the restore scripts, not db scripts. So to fix your issue, you'd have to perform a backup.

Is this the latest version of dbatools? I'm concerned about your issues with Xevents and Replication. That's something we saw in earlier versions but not in recent versions.

You mentioned something about triggers in a DM. Is that still an issue?
