### ISSUE TITLE
Fix PSScriptAnalyzerRule - PSShouldProcess

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#4243]
### Summary of new feature

There are about 11 cmdlets breaking the PSShouldProcess script analyzer rule, which could be impacting cmdlet use as well as our BOH. This rule indicates that the cmdlet should call ShouldProcess to write-output when someone uses `-whatif`

See [ShouldProcess.md](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/ShouldProcess.md) for more details

### Proposed technical details (if applicable)
Including a `if ($PSCmdlet.ShouldProcess("Target", "Operation"))` check (or something similar) around the acting code.

**Comment by niphlod** [comment]
watch out for this one, it's quite a "light" (i.e. not that smart) check on PSSA side. 
it may be very well be the case that we need to ignore the check for some functions.

**Comment by joshcorr** [comment]
Thanks for the heads up. I have implemented this one before on a few projects and I usually just wrap the section of the cmdlet that is doing the changes in the following.

```
if($PSCmdlet.ShouldProcess("Creates Database: $databaseName")){
/// Changing code
}
```

It usually writes the output and ignores the change code, but I will double check before PR. Also plan on adding some Integration Tests for these cmdlets if they don't have them already. There are a few other PSScriptAnalyzer rules that I have questions about (like if we want to ignore Incorrect Verbs, or Plural Nouns in specific cases).
