### ISSUE TITLE
Test-DbaPowerPlan - might return information from local computer when can't reach remote

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#425]
Is this a bug:

- Powershell Version: 4.0
- OS Version: 2012 R2 Standard

**Steps to Reproduce**
Run the Test-DBAPowerPlan using a `-ComputerName` that can't resolve IP address.

Will return empty on `$ipaddr`  (https://github.com/sqlcollaborative/dbatools/blob/master/functions/Test-DbaPowerPlan.ps1#L83)

Then when using empty value as variable on `Get-CimInstance -ComputerName $ipaddr` will query the local computer instead the remote. This will not return any error giving the feeling that it runned OK.

**Action Results**
Returns PowerPlan from local computer

**Expected Results**
Error saying that can't reach the remote computer, and/or do not query local computer.

**Additional comments**

**Comment by SirCaptainMitch** [comment]
Merged, closing.
