### ISSUE TITLE
SecurityProtocol for SSL issues

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4250]
Perhaps write an internal Invoke-SslRequest that wraps Invoke-WebRequest

```` powershell
$oldSslSettings = [System.Net.ServicePointManager]::SecurityProtocol
[System.Net.ServicePointManager]::SecurityProtocol = "Tls12"
Invoke-Webrequest...
[System.Net.ServicePointManager]::SecurityProtocol = $oldSslSettings
````

These commands already have the proper protocol thing:

* functions\Get-DbaBuildReference.ps1
* functions\Install-DbaFirstResponderKit.ps1
* functions\Install-DbaMaintenanceSolution.ps1

these do not and may be subject to issues in the future if SSL is used:

* functions\Install-DbaWhoIsActive.ps1
* functions\Invoke-DbaQuery.ps1
* functions\Save-DbaDiagnosticQueryScript.ps1
* install.ps1

https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

**Comment by niphlod** [comment]
I can work on it.

Il gio 18 ott 2018, 19:25 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
awesome af ty, assigned
