### ISSUE TITLE
SQL Auth in Tests

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4257]
today I was playing with SQL on Linux which requires SQL Auth. I found a bug, and it made me realize that there are probably a few commands that have sql auth bugs. So I propose we:

* Disable Silent Warning Default Parameter Value in constants.ps1
* Add sqladmin sql auth login in each of the appveyor.SQL2017.ps1, etc
* Remove the Windows user
* Set PS Default Parameter Value to Sql auth

See what fails or complains

**Comment by niphlod** [comment]
as long as you play in a branch......you can do what you want

**Comment by potatoqualitee** [comment]
lol of course, this is so i dont forget
