### ISSUE TITLE
Test for common parameters comment based help

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#429]
Since help for common parameters is autogenerated and it's a general practice to not include this in comment based help, we should have a test that fails if one or more of the common parameters is included in the comment based help under .PARAMETER.

Of course, in the .EXAMPLE sections it is allowed (recommended) to include and explain the use of common parameters.

**Comment by SQLDBAWithABeard** [comment]
f45247df80c9215f7ffcc92db1c8da2a91899e3c removes the requirement for WhatIf and Confirm from the Pester Tests

**Comment by SQLDBAWithABeard** [comment]
af279c3e62d197c6ef80d608c03a969ed8f7993a tests for help containing  .PARAMETER Confirm and  .PARAMETER Whatif

**Comment by SQLDBAWithABeard** [comment]
I will close this but @PowerDBAKlaas if there are other common parameters that you notice in the help that should be excluded please re-open
