### ISSUE TITLE
Test-DbaValidLogin - some text issues in help

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#430]
Is this a *feature* OR *bug*:
Bug

**Additional comments**

- [ ] The -SqlServer parameter section is strange wording with "SQL Server" at the beginning.  Then you should have a space after the .
- [ ] The -SqlCredential has a random "To use:" at the end of the line
- [ ] The -FilterBy should have a "Y" at the beginning of second sentence
- [ ] The -ExcludeDomains detailed help has a typo and starts with "Bu" instead of "By" and "transverse" might need to be "transverse".
- [ ] I would capitalize "Directory" in the Example 2 text
- [ ] Example 3 sample subdomain.ad.local does not match text that says mydomain

**Comment by potatoqualitee** [comment]
hey @gbargsley - can you please make this changes? ❤️
