### ISSUE TITLE
OnSuccessStepId not working in New-DbaAgentJobStep

### ISSUE THREAD

**Issue by rickloveslamp** [sqlcollaborative/dbatools#4312]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
New-DbaAgentJob -SqlInstance $myserver -Job "myTestJob"
New-DbaAgentJobStep -SqlInstance $myserver -Job "myTestJob" -StepId 1 -Subsystem TransactSql -StepName "myFirstStep" -Command "select 'oh, hello'" -OnSuccessAction GoToStep -OnSuccessStepId 2
```

## Expected Behavior
Job step should be created.

## Actual Behavior
Job step creation fails:
WARNING: [13:21:37][New-DbaAgentJobStep] Parameter OnSuccessStepId can only be used with OnSuccessAction 'GoToStep'.

## Environmental data

 - PowerShell: 
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: 
 Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64)
       Sep 14 2018 13:53:44
       Copyright (C) 2017 Microsoft Corporation
       Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by sanderstad** [comment]
I will investigate this. Seems like a check is done incorrectly.

**Comment by rickloveslamp** [comment]
I've got a pull request almost done for it. I think one of the operators needs to be switched, but also I think we only want a step ID if the action is "GoToStep", not "GoToNextStep".

**Comment by rickloveslamp** [comment]
#4313
