### ISSUE TITLE
When generating deployment report with script only option it unexpectedly exits with warning.

### ISSUE THREAD

**Issue by RichieBzzzt** [sqlcollaborative/dbatools#4314]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
Build a dacpac and have a publish xml file.

When wanting to generate a script only of the deployment report the warning "WARNING: [19:52:49][Publish-DbaDacPackage] You must at least one of GenerateDeploymentScript or GenerateDeploymentReport when using ScriptOnly"

```powershell
Import-Module C:\Users\RichardLee\source\repos\dbatools -Force
$db = "northwind"
$sql = "(localdb)\heyyo"

$dacpac = "C:\Users\RichieLee\source\repos\Northwind\bin\Debug\Northwind.dacpac"
$publishProfile  = "C:\Users\RichieLee\source\repos\Northwind\bin\Debug\Northwind.publish.xml"
$OutPath = "C:\Users\RichieLee\source\repos\dbatools\output"
# first example works
Publish-DbaDacPackage -SqlInstance $Sql -Database $db -Path $dacpac -PublishXml $publishProfile -GenerateDeploymentScript -ScriptOnly -OutputPath $OutPath 
# second example get above warning
Publish-DbaDacPackage -SqlInstance $Sql -Database $db -Path $dacpac -PublishXml $publishProfile -GenerateDeploymentReport -ScriptOnly -OutputPath $OutPath

```

## Expected Behavior
Deployment report is generated in output directory.

## Actual Behavior

"WARNING: [19:52:49][Publish-DbaDacPackage] You must at least one of GenerateDeploymentScript or GenerateDeploymentReport when using ScriptOnly"

## Environmental data

Name                           Value
----                           -----
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by RichieBzzzt** [comment]
Got the fix for this already. Will merge shortly.

**Comment by RichieBzzzt** [comment]
Thanks to @richardlhughes for finding bug!

**Comment by RichieBzzzt** [comment]
#4316 PR opened

**Comment by niphlod** [comment]
closed via https://github.com/sqlcollaborative/dbatools/commit/5bff4ece624824cca3b5de72ce041df3f460e207
