### ISSUE TITLE
inconsistently failing tests - 'don't run unless modified' group

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4332]
hey @niphlod  - there are 3 commands that fail more than others in appveyor.

Can we create a new group that says "don't test unless modified"?

Included in the group would be

Export-DbaDacPackage
New-DbaAvailabilityGroup
Remove-DbaAvailabilityGroup
Remove-DbaAgDatabase

thx

**Comment by niphlod** [comment]
hum, doable but sideloaded with niceties ... I guess we can make some sort of code that computes the hash of those functions and if it doesn't match it executes it, else it skips but ....... who then controls that tests are actually ran once in a while (and or lower-level functions plus higher-level) ? 
Also, how to compute the relevant coverage ? 
In a far distant future, we may run tests outside appveyor and push coverage "privately" but that's not going to happen soon...
We'd better find out what is wrong with either that suite or appveyor (and be wary about sudden changes, e.g. I noticed bootstrap times going up with no apparent reason)

**Comment by potatoqualitee** [comment]
yeah thats my fear - that random appveyor issues just break our commands and it's not possible to bulletproof them

**Comment by niphlod** [comment]
then it's either us doing something wrong or needing a different infrastructure ;-(

**Comment by potatoqualitee** [comment]
not for 4 command failures, no way. i expect this kind of behavior from machines with literally 2GB of ram
