### ISSUE TITLE
Fix PSUseBOMForUnicodeEncodedFile

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#4339]
### Summary of new feature

Since removing all BOM in from files in #4206 the PSScriptAnalyzer rule has been failing on a few files that still have extended characters in them. These characters should be removed or a PSScriptAnalyzer override should be put in place.

See [UseBOMForUnicodeEncodedFile.md](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/UseBOMForUnicodeEncodedFile.md) for more details

### Proposed technical details (if applicable)

Use `(Get-Content .\functions\Add-DbaComputerCertificate.ps1) -match "[\x90-\xFF]"` to find the affected lines in each file and replace it with appropriate text. In the file above the offending code is `Â¯\_(ãƒ„)_/Â¯` and it would be replaced or deleted. `¯\_(ツ)_/¯`

**Comment by niphlod** [comment]
we do not check that rule in BOH for a reason... the whole file is checked without considering if it's actual code or not. In any case, better safe than sorry.
