### ISSUE TITLE
Test-DbaConnection -  unified output for result

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#4344]
### Summary of new feature

* Report connection error into returning object, not into yellow text console.

### Proposed technical details (if applicable)

* retun unified information that can be later evaluated by code in user script

### Latest version of dbatools as of writing

* 0.9.487

![image](https://user-images.githubusercontent.com/14327077/47494558-a283c100-d85a-11e8-9665-c5102f73158f.png)

**Comment by andreasjordan** [comment]
Sometimes, things take little longer...
