### ISSUE TITLE
Fix PSUseSingluarNouns and PSUseApprovedVerbs

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#4346]
### Summary of new feature

This may take some discussion before a PR is submitted.

There quiet a few cases of plural noun cmdlets (and plural noun internal functions)
```
Clear-DbaLatchStatistics.ps1
Clear-DbaWaitStatistics.ps1
Copy-DbaLinkedServer.ps1 (Copy-DbaLinkedServers)
Find-DbaLoginInGroup.ps1 (Get-AllLogins)
Get-DbaDatabase.ps1(Invoke-QueryRawDatabases)
Import-DbaCsvToSql.ps1 (Get-Columns)
Install-DbaMaintenanceSolution.ps1 (Get-DbaOlaWithParameters)
Invoke-DbaBalanceDataFiles.ps1 (Invoke-DbaBalanceDataFiles)
Remove-DbaXESession.ps1 (Remove-XESessions)
Start-DbaXESession.ps1 (Start-XESessions)
Stop-DbaXESession.ps1 (Stop-XESessions)
Update-dbatools.ps1
```
as well as cmdlets which contain internal functions using unapproved verbs
```
Find-DbaInstance.ps1 (IP-toINT64, INT64-toIP)
Get-DbaMaintenanceSolutionLog.ps1 (process-block)
Get-DbaSpn.ps1 (Process-account)
Register-DbatoolsConfig.ps1 (Ensure-RegistryPath)
```

Not sure if we should take the same approach for these, but it could be a combination of fixing words where it makes sense and overriding the rule where it doesn't.

### Proposed technical details (if applicable)

Update the Verbs and Nouns to be valid and singular, or Include an override for the rule in that function.
`[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseSingluarNouns", "")]`
`[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseApprovedVerbs", "")]`

**Comment by joshcorr** [comment]
@cl @wsmelton and @niphlod  I would like some feed back on this one since it may be a case to case decision.

**Comment by potatoqualitee** [comment]
Happy to!
The rule I heard is that if it  can ever be singular than go single. Considering that, the following should stay plural:

> Clear-DbaLatchStatistics.ps1
>  Clear-DbaWaitStatistics.ps1
> Invoke-DbaBalanceDataFiles.ps1

This one is a proper name and should stay, too

> Update-dbatools.ps1

As for the rest, I'd like to ignore naming conventions for internal commands since they are not user facing

> Copy-DbaLinkedServer.ps1 (Copy-DbaLinkedServers)
> Find-DbaLoginInGroup.ps1 (Get-AllLogins)
> Get-DbaDatabase.ps1(Invoke-QueryRawDatabases)
> Import-DbaCsvToSql.ps1 (Get-Columns)
> Install-DbaMaintenanceSolution.ps1 (Get-DbaOlaWithParameters)
> Remove-DbaXESession.ps1 (Remove-XESessions)
> Start-DbaXESession.ps1 (Start-XESessions)
> Stop-DbaXESession.ps1 (Stop-XESessions)
>Find-DbaInstance.ps1 (IP-toINT64, INT64-toIP)
>Get-DbaMaintenanceSolutionLog.ps1 (process-block)
>Get-DbaSpn.ps1 (Process-account)
>Register-DbatoolsConfig.ps1 (Ensure-RegistryPath)

**Comment by niphlod** [comment]
same thoughts. override the check. it's not a severe finding too.

**Comment by joshcorr** [comment]
Awesome! that is exactly what I was looking for I will put all of the override rules in place and do a PR later today.
