### ISSUE TITLE
Set-DbaAgentJobStep -Job and -StepName parameters should be able to accept pipeline input and $variable input

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#4350]
---
Set-DbaAgentJobStep -Job and -StepName parameters should be able to accept pipeline input
---

### Summary of new feature

The `-Job` parameter and `-StepName` parameter of Set-DbaAgentJobStep should be able to accept pipeline input, such as piped from `Get-DbaAgentJobStep` and/or `Get-DbaAgentJob`.
They also do not accept $variable input, throwing "Cannot convert value to type System.String" errors.

For example, this does not work and I expected it to:
```
Get-DbaAgentJob -SqlInstance MYSERVER | Set-DbaAgentJobStep -Database MYDATABASE
```
This also did not work:
```
Get-DbaAgentJobStep -SqlInstance MYSERVER | Set-DbaAgentJobStep -Database MYDATABASE
```
This also did not work:
```
$agentjobs = Get-DbaAgentJob -SqlInstance MYSERVER | Select-Object -ExpandProperty Name
$agentjobsteps = Get-DbaAgentJobStep -SqlInstance MYSERVER | Select-Object -ExpandProperty Name
Set-DbaAgentJobStep -SqlInstance MYSERVER -Job $agentjobs -StepName $agentjobsteps -Database MYDATABASE
```
which throws red error:
```
Set-DbaAgentJobStep : Cannot process argument transformation on parameter 'StepName'. Cannot convert value to type System.String.
At line:1 char:70
+ ... qlInstance MYSERVER -Job $agentjobs -StepName $agentjobsteps -Databa ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-DbaAgentJobStep], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-DbaAgentJobStep
```

### Proposed technical details (if applicable)

I am not smart enough to know how to technically solve this :( :) :(
But the only way I could figure out to get this to KIND OF work (while throwing a bunch of warnings for every cartesian product possible combination) was to:
```
$agentjobs = Get-DbaAgentJob -SqlInstance MYSERVER | Select-Object -ExpandProperty Name
$agentjobsteps = Get-DbaAgentJobStep -SqlInstance MYSERVER | Select-Object -ExpandProperty Name
foreach ( $job in $agentjobs )
{
    foreach ( $jobstep in $agentjobsteps )
    {
       Set-DbaAgentJobStep -SqlInstance MYSERVER -Job $job -StepName $jobstep -Database MYDATABASE 
    }
}
```

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.
0.9.490

**Comment by sanderstad** [comment]
I want to check if this is still the case

**Comment by sanderstad** [comment]
Sorry for the delay but the function should not accept pipes from Get-DbaAgentJobStep.

The command allows to get the job steps from get-DbaAgentJobStep and get those changes and push those to other servers and jobs and eventually job steps.

![image](https://user-images.githubusercontent.com/6154981/52051986-76f92c80-2555-11e9-86bb-1a5a082c980a.png)
