### ISSUE TITLE
new command Test-EndPointOwnership

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#4353]
---
name: Test-EndPointOwnership
about: getting and testing against best practices endpoint owners

---

### Summary of new feature

make sure no endpoints are assigned to logins that could lead to problems

### Proposed technical details (if applicable)

http://www.sqlservercentral.com/articles/AlwaysOn/178777

### Latest version of dbatools as of writing

0.9.491

**Comment by potatoqualitee** [comment]
thanks. considering this i'll rewrite new-dbaendpoint to do sa by default
