### ISSUE TITLE
Add new options for 2017 for Query Store cmdlets

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbatools#4364]
---
name: Add new options for 2017 for Query Store cmdlets 
about: The following new parameters were added in 2017 MAX_PLANS_PER_QUERY and WAIT_STATS_CAPTURE_MODE.  See https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-2017 for documentation on them.

---

### Summary of new feature
All you to specify/view all options for Query Store for 2017.

### Proposed technical details (if applicable)
Update Set-DbaDbQueryStoreOption and Get-DbaDbQueryStoreOption to show these options and set them if the version is 2017 and up.
https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-2017

### Latest version of dbatools as of writing
0.9.493

**Comment by tboggiano** [comment]
Question for 2019 features I should just go ahead and add.  The new CUSTOM query capture mode.  If they are copy settings to a lower version of SQL do we want to say you can't copy settings to this version of SQL Server of display a warning saying that setting was not set and copy the other settings.

**Comment by wsmelton** [comment]
I would not add 2019 features until it is RTM.

**Comment by tboggiano** [comment]
OK.  Bummer, I'll just save that code for later then.

**Comment by wsmelton** [comment]
If it can be added in a manner that allows it to be commented out, with note "not until RTM" that would be fine by me.

**Comment by tboggiano** [comment]
This was complete awhile back, like last summer.
