### ISSUE TITLE
Error message handling

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4369]
I'm adding a lot of new things and finding that we're often back to the vague error messages.

Would it be possible to say "if this class isn't in the index, then default to the hacky way to show messages"?

![image](https://user-images.githubusercontent.com/8278033/47706214-f6125800-dc28-11e8-9d0d-81dae75ad189.png)

I had more success when I used the internal `Get-ErrorMessage` but understand the speed impact of making that default.

**Comment by potatoqualitee** [comment]
Currently, it can be fixed by adding the following to the catch

```powershell
$message = Get-ErrorMessage -Record $_
Stop-Function -Message $message -ErrorRecord $_ -Continue
```

**Comment by potatoqualitee** [comment]
oooo much better approach! ty

**Comment by Zhunya** [comment]
so much time wasted, so many questions about not having right error message asked in #dbatools.

**Comment by potatoqualitee** [comment]
i think the current fix is good enough 👍
