### ISSUE TITLE
Test-DbaValidLogin - output properties

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#437]
I like this function a lot, it's very handy. And it is very fast too in my environment. Great work.

But, the object properties should be renamed to be clearer, and consistent with other functions.

My suggestion:

ComputerName
SqlInstance (split in ComputerName and SqlInstance)
Domain
LoginName (or SAMAccountName if the AD property used)
LoginType
ExistsinAD
EnabledinAD
EnabledinSqlServer

maybe 'PasswordIsExpired' could be of interest too

I would definitely choose for two [enabled] or two [disabled] properties, even if the original is one time enabled = true, and the other one disabled = false.
This is exactly where dbatools can add value: a weak point in the MS methodology that we can make better and consistent for users.
Another option is to have [ADstatus] and [SqlStatus] as 'enabled' or 'disabled' instead of true and false

I don't know what the ADLoginDetails column is for, what I see is like a concatenation of  other properties? If they are useful there, than they can be more useful as separate properties, no?

The values of [LoginType] could remain what they are: 'Windows User', 'Windows Group',... That would be what DBA's are used to. So there's no need to manipulate those.

A general  way to go is to replace all -Detailed switches with -Simple. Default we'll always show all we have, and with -Simple we reduce the output to the essentials
 ( as a shortcut to the most probable ' | Select-Object a, b, c')

- [ ] Rename output properties
- [ ] Replace -Detailed with -Simple
- [ ] Add PasswordIsExpired
- [ ] Change Login Type values to original name

**Comment by niphlod** [comment]
all -detailed, -simple etc should instead peruse the new Select-DefaultField that @ctrlbold kindly coded for everyone

**Comment by ctrlbold** [comment]
the Select-DefaultField is useful for passing rich objects, but I don't see the opportunity for a rich object here. Do y'all?

**Comment by niphlod** [comment]
imho when more than 4 or 5 props per object are returned, it's useful also to make "stand out" default fields. I really dig e.g. what the AD cmdlets do, providing a nice summary PLUS being able to do whatever down the stream (be it just a Where, a Sort, etc) ...

**Comment by niphlod** [comment]
@PowerDBAKlaas : is this still valid ?

**Comment by PowerDBAKlaas** [comment]
There was a lot of conversation on this function, but it doesn't seem to be in this issue.
@niphlod fixed the AD properties. but
- There still is a `-Detailed` switch
- The LoginType still doesn't match the SQL naming
- There still is one 'Disabled...' vs one 'Enabled'
I can't remember what we decided in the last discussions nor where to find them.
Wasn't there a second function related to this? @wsmelton ?

**Comment by wsmelton** [comment]
I recall some part of a discussion around validating SQL Logins but not sure if that was specific to this function or creating a new one. I don't recall a discussion around the specific properties on this one.

Was it around validating a login for an instance if it had access via an AD group? Maybe that was a Test-DbaLoginAccess or something?

**Comment by PowerDBAKlaas** [comment]
yes, there it is:
PR #994 fixed issue #987 
new command issue #1395 
Now I read in those comments we would rename this one to Test-DbaADValidLogin.
although it turns out to be more like Get-DbaWindowsLoginADProperties 😏 
I would also replace "user" and "group" by "Windows User" and "Windows Group"
Will the -Detailed be wiped out in a massive rewrite, or do we do that now?

After that, it would be nice if this could work like:
`Get-DbaLogin | Get-DbaADProperties`
