### ISSUE TITLE
Fix PSAvoidUsingEmptyCatchBlock

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#4378]
### Summary of new feature

There are ~34 incidents of cmdlets breaking the PSAvoidUsingEmptyCatchBlock script analyzer rule, which could be impacting cmdlet use as well as our BOH. This rule indicates that a catch block should not be empty. In the case that it is empty it may suppress an error (which may be needed), and as a result will potentially make diagnosing why a cmdlet is not running difficult.
See [PSAvoidUsingEmptyCatchBlock.md](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/AvoidUsingEmptyCatchBlock.md) for more details

### Proposed technical details (if applicable)

Fill Catchblock with `Stop-Function` or `Write-Message` unless it seems that the try block doesn't need to be there then it should be removed.

**Comment by niphlod** [comment]
if write-message is NEEDED I think it'd be already in there. If it's empty as a way to "pass on without hiccups" a `$null = 1   #here to avoid empty catch` can be as good as it can be.

**Comment by joshcorr** [comment]
Okay, I can proceed with that for now. I still think if we have a catch block we should have a message or a termination.

**Comment by niphlod** [comment]
not really. Think "to make this happen (behaviourally), I either need to do this or that or that. In the end, I know it'll work, and I don't need to inform the user about what path I took to make that happen, as long as it happens"
```
try { dumby but fast } catch { }
if (-not($thathappened)) try { less dumby but longer } catch { }
if (-not($thathappened)) try { third time is a charmer } catch { }
if (-not($thathappened)) try { longer but shady } catch { throw "ok i give up" }
```
it surely can be ported to
```
try {
    try { dumby but fast } catch {
        try { less dumby but longer } catch {
           try { third time is a charmer } catch {
               
          }
       }
    }
catch {}
try { longer but shady } catch { throw "ok i give up" }
```
but sometime scoping is a bitch and some other times SMO is with it's lazy property evaluation (i.e. see the empty catch on Write-DbaDataTable, which is needed for Azure)

Also, we're in the business of not nagging the user if not for very serious issues .... so okay, having an empty catch is generally considered unsafe but surely there are cases where it's still perfectly acceptable ^_^

**Comment by wsmelton** [comment]
Most places we have catch blocks that are empty, we have them there for a reason....mainly we don't care if that statement/command being tried errors because we catch it in other areas.

**Comment by wsmelton** [comment]
That is main reason I recall we never cared about this PSSA rule to begin with, because empty catch blocks are used. If they are empty, you need to validate that it should be which deserves an issue per command if it is not blatantly obviously why.

**Comment by potatoqualitee** [comment]
+1 to the above, some empty catches can't be avoided

**Comment by joshcorr** [comment]
I understand that having empty catch is often unavoidable and a design choice that has been made (I am willing to comply with that design choice). Thankfully the errors are being caught other places, because the cmdlet design has been thought through. 

My concern in this issue is how do we standardize these PSSA rules. If we don't care about this rule then we should put an ignore in place with a justification, or the `$null = 1` that was suggested (I only mentioned the `Write-Message` because of my own experience writing nested try/catches and it was handy to have a reference to which catch block). Having some override for the PSSA check on these cmdlets will help us down the road. 

I am thinking of new PRs in the future (i.e. post v1) when a new contributor (who maybe doesn't catch their errors somewhere else) tries to submit a PR and before any pester tests run, PSSA runs (maybe with custom rules for dbatools specific formats) and warns them on their syntax.

**Comment by niphlod** [comment]
yeah, this line of thinking is post 1.0, but I think down the line we'll go for `$null = 1 #avoid an empty catch` because:
- we do *want* to avoid empty catch if not "necessary"
- codeanalyzer exception works on the whole file instead of a single block

This way we can enforce good behaviour and still "leave the door open". That being said, this should probably go in the styleguide.
