### ISSUE TITLE
Restart-DbaService with Type Engine gets an error

### ISSUE THREAD

**Issue by stevenksco** [sqlcollaborative/dbatools#4391]
Restart-DbaService -ComputerName<computer> -InstanceName <instance> -Type Engine

Gets this error
Get-RunspaceData : Runspace timed out at 30.0497279 seconds for the object:
ComputerName : ISD40153
ServiceName  : MSSQL$SQL2016
ServiceType  : Engine
InstanceName : SQL2016
DisplayName  : SQL Server (SQL2016)
StartName    : NT Service\MSSQL$SQL2016
State        : Running
StartMode    : Automatic
```
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.450\allcommands.ps1:97150 char:13
+             Get-RunspaceData -wait
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RunspaceData
```

**Comment by nvarscar** [comment]
Hi @stevenksco 
Could you please do the following:
1. Please post the version of dbatools module you are using: `Get-Module dbatools -ListAvailable` 
2. Try to increase the timeout by using the -Timeout parameter (default 30, will be increased to 60 in one of the upcoming releases).
