### ISSUE TITLE
How about a database refresh command?

### ISSUE THREAD

**Issue by stevenksco** [sqlcollaborative/dbatools#4392]
I refresh dev/test db from prod a lot

How about something that capture the db permissions from dev/test, backs up prod, restores prod to dev/test and applies the perms

**Comment by wsmelton** [comment]
This would be out of scope to provide a command to do the work. As already stated it is more coming up with a wrapper script that would cover your specific scenarios that you need to repeat each time. Trying to come up with one command that covers every possible scenario is not feasible.
