### ISSUE TITLE
Invoke-DbaDbMirroring complains that editions must match but they do

### ISSUE THREAD

**Issue by dbaduck** [sqlcollaborative/dbatools#4394]
### Before submitting a bug report:

- [ X ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ X ] Verified this bug is not already reported in an issue
- [ X ] Verified errors are not related to permissions
- [ X ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
    Provide exact (or sanitized) code to reproduce the error
#>
Invoke-DbaDbmirroring -Primary SQL2016A -Mirror SQL2016A\INSTANCE1 -Database TestDB
```

## Expected Behavior
It should actually mirror the databases or get past the checks.

## Actual Behavior
I tried to use a string for the instances and also a Connect-DbaInstance output as well. Same Error.

Invoke-DbMirrorValidation : Cannot process argument transformation on parameter 'Mirror'. Cannot convert value
"Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]" to type
"Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance:
Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]"
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.497\allcommands.ps1:57124 char:53
+             $validation = Invoke-DbMirrorValidation @params
+                                                     ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-DbMirrorValidation], ParameterBindingArgumentTransformationExce
   ption
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Invoke-DbMirrorValidation

WARNING: [09:43:38][Invoke-DbaDbMirroring] This mirroring configuration is not supported. Because the principal server
instance, [SQL2016A], is EnterpriseOrDeveloper Edition, the mirror server instance must also be EnterpriseOrDeveloper
Edition.

## Environmental data

Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - PowerShell: 
 - - SQL Server: 
Same on both instances
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 
	Oct 28 2016 18:17:30 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Datacenter Evaluation 6.3 <X64> (Build 14393: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
thanks for using this command! I'll take a look asap

**Comment by potatoqualitee** [comment]
My apologies for the errors, I've addressed them and should be in master/gallery within a few hours.
