### ISSUE TITLE
Publish-DbaDacPackage - Please add meaningfull error message, if sqlcmd variable is missing

### ISSUE THREAD

**Issue by chrgraefe** [sqlcollaborative/dbatools#4396]
---
name: Improve error message in Publish-DbaPackage
about: give it more meaning

---

### Summary of new feature
sqlpackage.exe gives a more detailed explanation what is going wrong.

Example
- sqlpackage.exe

> *** An error occurred during deployment plan generation. Deployment cannot continue.
> Missing values for the following SqlCmd variables:LINKED_SERVER_TO_DWH.

- Publish-DbaDacPackage
```
An error occurred during deployment plan generation. Deployment cannot continue.
In D:\Users\<<User>>\Documents\WindowsPowerShell\Modules\dbatools\allcommands.ps1:98143 Zeichen:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Publish-DbaDacPackage
```

### Latest version of dbatools as of writing
Version 0.9.411

**Comment by potatoqualitee** [comment]
Thanks for the report, @chrgraefe ! @RichieBzzzt / @nvarscar, im unsure which of you this falls under. Please let me know and I'll keep in mind for the future.

**Comment by RichieBzzzt** [comment]
Hello!

I’ve encountered this problem with returning the actual error from using the dac.dll before. 

I think Chrissy we may have to have the full exception returned. This does mean we sort of fall into the risk of returning a sea of red. But at least we will get the cause of the failure. 

I’m happy to do the work myself but wanted to raise it here first to get your thoughts on this.

**Comment by nvarscar** [comment]
Right now, the error output is pretty simple:
```
catch [Microsoft.SqlServer.Dac.DacServicesException] {
   Stop-Function -Message "Deployment failed" -ErrorRecord $_ -Continue
}
```
I wonder if there is a better way of using `Stop-Function` so that not only original error is thrown, but user also gets some useful info on the screen. Maybe, `Write-Message -Level Warning` before doing a `Stop-Function`? 
I think, if user would run `$error[0]|select *`, the error would have appeared in full, but that needs testing, which I won't be able to do for another couple of days.
PS And sorry for being late to the party, was having some vacation time.

**Comment by RichieBzzzt** [comment]
I've tried @nvarscar 's suggestion above of piping it to select * but it does not output the error. 

In another module I wrote for this, the only way I could get the exception was something like this - 
```powershell
catch {
        $e = $_.Exception
        $toThrow = $e.Message
        while ($e.InnerException) {
            $e = $e.InnerException
            $toThrow += "`n" + $e.Message
        }
    }
    finally {
        if ($ToThrow) {
            Throw $ToThrow
        }
}
```

It's not pretty, but it got the pertinent error. So to get the full error we'd have to either change ```Stop-Function```, or go rogue in this function and throw the exception something like above. Am open to alternatives.

**Comment by nvarscar** [comment]
What about `$error[0].Exception | Select *` ? 😸 
Oh and we can (and probably should) definitely do something like this, putting the proper string into the -Message parameter, all we need to do is to construct the string itself and ditch `-ErrorRecord $_`, which kind of overrides the -Message.

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann has a couple issues filed for better error messages and it's on his agenda to address this. I created an internal command, `Get-ErrorMessage`, that will be useful in the interim. I use it like this

````
} catch {
  $message = Get-ErrorMessage -Record $_
  Stop-Function -Message $message -ErrorRecord $_
}
````

**Comment by RichieBzzzt** [comment]
Hey @potatoqualitee wicked thanks that did the trick! I'll make a PR shortly.

**Comment by nvarscar** [comment]
Is this resolved now? @chrgraefe could you please confirm

**Comment by chrgraefe** [comment]
@nvarscar great! Correct error message is now visible. Much better debugging.
![image](https://user-images.githubusercontent.com/4922897/48497443-68dc1f80-e834-11e8-95cb-524959d30f16.png)

Thanks a lot

**Comment by potatoqualitee** [comment]
Fantastic news! I replaced Richie's change with a module-wide change and confirmed it worked in a number of places, but not all. Happy to see another scenario where it worked. You should see an improvement module-wide.
