### ISSUE TITLE
Connect-SqlServer fails with both \MSSQLServer and \Default

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#440]
Is this a *feature* OR *bug*:
Bug
- Powershell Version: 5.1
- OS Version: Win 10

**Steps to Reproduce**
feed 'sql1\MSSqlServer' or 'Sql2\Default' to a function that uses internal\Connect-SqlServer

**Action Results**
No connection object is returned

**Expected Results**
Since it is likely DBA's will assume either 'MSSQLServer' or 'Default' is a valid instance name, the function should accept those and return an SMO.server object for the default instance.

**Additional comments**

**Comment by ctrlbold** [comment]
I'm always happy to make things easier for people, but D: there's no other application I know of that accepts this improperly formatted name -- I just tested in SSMS. If you're in the weeds enough to even find out it's called MSSQLServer, wouldn't you know not to pass it?

**Comment by PowerDBAKlaas** [comment]
maybe,
but someone who started with the SQL: provider had to navigate to 'DEFAULT',
someone starting with dbatools will get 'MSSQLServer' back as instancename from various functions, 
someone who has experience with the registry, services or the file system knows they use 'MSSQLServer', ...
so someone starting to build solutions with dbatools and other sources might collect SqlInstance names in different forms and expect dbatools will deal with them.
Wouldn't that be the case for a lot of accidental or new DBA's?

And someone I respect very much said: " We want to be able to handle everything they throw our way."

**Comment by wsmelton** [comment]
Nope, nope, nope.

DBA 101 (and every basic level book on SQL Server) teaches any DBA that the instance ID for a default SQL Server instance shows up as `MSSQLSERVER`. `DEFAULT` is only used in SQLPS world, I've never seen any Microsoft command return that except when it is replacing `MSSQLSERVER` as the ID. It would be the same thing as someone saying we have to accept `MSSQL$MYINSTANCE`. There is no reason at all to handle that or even allow that to be passed in to this command.

If you start going down this rabbit hole what if someone has a server named `MSSQLSERVER`, for a default instance?

**Comment by ctrlbold** [comment]
I agree with Shawn here. And I'll add a caveat to my quote  "unless it engenders a terrible practice". Terrible is, of course, subjective ;) I feel as strong as Shawn here.

**Comment by SirCaptainMitch** [comment]
@ctrlbold Seems like this one is settled?

**Comment by niphlod** [comment]
trying to be a strict manager here. I take full responsibility.
@ctrlbold feel free to reopen, just in case.
