### ISSUE TITLE
Availability Group things to finish

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4403]
- [ ]  Add AG health from XE templates if not exists
- [ ]  Add missing tests (there aren't a lot)
- [x] Set commands
- [x] Sync command
- [ ] Test commands
- [x] Proper examples for New-DbaAvailabilityGroup
- [x] Autoseeding examples
- [x] The permission stuff Shawn mentioned as listed in the description of New-DbaAvailabilityGroup
- [x] The ConfirmImpact for each command is appropriate

**Comment by sqllensman** [comment]
Is there an Appyveyor environment available to test AG commands?.

**Comment by potatoqualitee** [comment]
Ish - there is a 2017 Dev instance that supports setting up simple, one node AG. but yenno, 2016 is dev edition as well. we could setup a lil something. i have disabled a couple ag tests in pester.groups.ps1 tho because they fail too often. not every time, but enough to be annoying.

**Comment by potatoqualitee** [comment]
no longer schedule for 1.0, just gonna do bug fixes for AGs, not add additional functionality
