### ISSUE TITLE
Expand-DbaTLogResponsibly - Error "Attempted to divide by zero"

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#4404]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
Execute the command without specify any database
```powershell
Expand-DbaTLogResponsibly -SqlInstance sql2012 -TargetLogSizeMB 100
```

## Expected Behavior
Run through all databases without errors.

## Actual Behavior
![image](https://user-images.githubusercontent.com/19521315/47951832-37bf3d80-df5e-11e8-9a74-7f12d3c280e5.png)

Note: Will submit a fix.
Thanks to @sql-williamd who found it

**Comment by potatoqualitee** [comment]
oh! can you do me a favor? while you're fixing htis command, can you remove the MB off of targetlogsize?

**Comment by ClaudioESSilva** [comment]
That will be a breaking change. Add an alias to the parameter?
btw, we have 3: `TargetLogSizeMB`, `IncrementSizeMB` and `ShrinkSizeMB`

**Comment by potatoqualitee** [comment]
Yes,  thank you, along with `Test-DbaDeprecation -DeprecatedOn 1.0.0 -Parameter XYZ`
