### ISSUE TITLE
Fix PSAvoidUsingPlainTextForPassword

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#4417]
### Summary of new feature

There are 13 incidents of cmdlets breaking the PSAvoidUsingPlainTextForPassword script analyzer rule, which could be impacting cmdlet use as well as our BOH. This rule indicates that a parameter of `Password` or `Credentials` should use the `[SecureString]` type and not `[String]`

```
ScriptName                    Line Extent
----------                    ---- ------
Copy-DbaCredential.ps1         116 [string[]]$Credentials
Export-DbaCmsRegServer.ps1      69 [ValidateSet("None", "PersistLoginName", "PersistLoginNameAndPassword")]...
Get-DbaBackupInformation.ps1   145 [string]$AzureCredential
Import-DbaCsvToSql.ps1         187 [object]$SqlCredential
Import-DbaCsvToSql.ps1         212 [string]$SqlCredentialPath
Invoke-DbaAdvancedRestore.ps1  120 [string]$AzureCredential
New-DbaAgentProxy.ps1          105 [parameter(Mandatory)]...
New-DbaLogin.ps1               134 [Alias("Hash", "PasswordHash")]...
New-DbaLogin.ps1               141 [string]$MapToCredential
Restore-DbaDatabase.ps1        355 [string]$AzureCredential
Set-DbaLogin.ps1               152 [object]$Password
Test-DbaLastBackup.ps1         141 [object]$DestinationCredential
Test-DbaLastBackup.ps1         153 [string]$AzureCredential
````

See [PSAvoidUsingPlainTextForPassword.md](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/AvoidUsingPlainTextForPassword.md) for more details

### Proposed technical details (if applicable)

Change the instances in these cmdlets to use `[SecureString]` or ignore them if they are not truly credentials with 
`[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingPlainTextForPassword", "")]`

**Comment by niphlod** [comment]
we exclude purposefully 

'PSUseOutputTypeCorrectly', 'PSAvoidUsingPlainTextForPassword', 'PSUseBOMForUnicodeEncodedFile'

from the BOH check. 

Here also, the heuristic from PSSA is not "top class" so triplecheck.
Final note, CodeAnalysis can take some additional params to "restrict the skip".

**Comment by joshcorr** [comment]
Most of the results from the checks do seem to be accurate (either because of an alias, or parameter name). Since these are being ignored by the BOH check I will put the `CodeAnalysis` rule in place in each script so that at some point we can enforce PSSA for new PRs to keep the minimum bar of module health high.
