### ISSUE TITLE
Copy-DbaSsisCatalog  - error when running from TFS build/release 

### ISSUE THREAD

**Issue by janeztr** [sqlcollaborative/dbatools#4419]
Hi, 

I'm running Copy-DbaSsisCatalog cmdlet from TFS (version 15.117.27024.0) release definition -  powershell task (Powershell version 5.1).
I get the following error:
` WARNING: [10:14:50][Copy-DbaSsisCatalog] There was an error connecting to the 
 source integration services. | Exception calling ".ctor" with "1" argument(s): 
 "Could not load file or assembly 'Microsoft.SqlServer.Diagnostics.STrace, 
 Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of 
 its dependencies. The system cannot find the file specified."`

But only when running from TFS. If I run from Powershell ISE works fine - same code, same machine, same user account.
Also, explicitly loading Microsoft.SqlServer.Diagnostics.STrace assembly (from TFS) raises no error. 
And other DbaTools cmdlets I use  (eg.  Start-DbaMigration, Set-DbaAgentJobStep, Set-DbaAgentSchedule)  also work fine.

**Comment by niphlod** [comment]
is the tfs shell importing some other sql "pieces", like SQLPS ?!

**Comment by janeztr** [comment]
Yes,  but  I can also reproduce the error by running only this script (in TFS release definition - Powershell task):
`$secPass = ConvertTo-SecureString $SsisDbEncryptionPass -AsPlainText -Force
Copy-DbaSsisCatalog -Source $SourceInstance -Destination $DestinationInstance -CreateCatalogPassword $secPass -Force -Verbose`
(variable declarations are omitted here)

And of course it works fine if I run it from Powershell ISE :)

**Comment by niphlod** [comment]
dbatools can't work in a session where SQLPS is already loaded so .... that's pretty much it.

**Comment by janeztr** [comment]
I don't think this is the case.
It only fails when run from TFS and as I explained in may previous post, I get the same error even when Copy-DbaSsisCatalog is the only cmdlet in script.

**Comment by niphlod** [comment]
if SQLPS is inherently and silently loaded by the TFS shell you wouldn't notice. Try an `Encode-SqlName`, if it goes through, something funny is going under the hood

**Comment by janeztr** [comment]
`Encode-SqlName : The term 'Encode-SqlName' is not recognized as the name of a c
mdlet...`  - in the case when this is the only cmdlet in the script.

But I'll have to deal with this issue. Now my own PowerShell function, which connects SSIS using SMO, fails the same way as  `Copy-DbaSsisCatalog`   - on creating SSIS server object.
When I try the same in a separate script (creating SSIS server object) it succeeds.

**Comment by wsmelton** [comment]
You will need to look at the task you are using in TFS to address the use of sqlps. I have not used it in a while but do maintain Azure DevOps releases. The PS task generally is only going to execute what you tell it to, not aware it pre-loads other modules, but I have not worked with TFS itself in a long time.

Our module does not utilize sqlps/sqlserver module and does not get along with either one of them. If you are calling a command like `Encode-SqlName` this will implicitly import the module found on your TFS agent that contains that command...the error that it is not recognized means the module with it was not found.
