### ISSUE TITLE
Publish-DbaDacPackage doesn't know the parameter -Option

### ISSUE THREAD

**Issue by chrgraefe** [sqlcollaborative/dbatools#4429]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
$options = New-DbaDacOption -Type Dacpac -Action Publish
$options.DeployOptions.DropObjectsNotInSource = $true
Publish-DbaDacPackage -SqlInstance mySqlServer -Database myDatabase -Options $options -Path C:\TEMP\myDatabase.dacpac
```

## Expected Behavior

Deployment of database

## Actual Behavior

![image](https://user-images.githubusercontent.com/4922897/48125210-74e93f80-e27e-11e8-8e1b-4d4a81952fb5.png)

in English: Parameter name "-Option" wasn't found

## Environmental data

 - PowerShell: 
PSVersion                      5.1.16299.666
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.666
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - SQL Server: Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64)   Sep 14 2018 13:53:44   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server Standard 10.0 <X64> (Build 16299: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Thank you - does it work with `-DacOption` ? if so, we can update the help

**Comment by potatoqualitee** [comment]
And add a parameter alias

**Comment by chrgraefe** [comment]
Yes -DacOption seems to work
