### ISSUE TITLE
Add-DbaAgDatabase Does not Add to Secondary Replica

### ISSUE THREAD

**Issue by gamarcon** [sqlcollaborative/dbatools#4433]
Command: `Add-DbaAgDatabase -SqlInstance Replica01 -AvailabilityGroup AGName -Database DB01 -Confirm:$false`

When opening the Dashboard, I see the message the DB is not joined to the Secondary replica and I get error message: The data synchronization state of this availability database is unhealthy.

It does not add the DB to the Secondary replica at all. Even after I ran:

Command: `Add-DbaAgDatabase -SqlInstance Replica02 -AvailabilityGroup AGName -Database DB01 -Confirm:$false`

Nothing happens. 
Adding the database manually works fine.

Other databases participate of the AG.

When opening the database on the Secondary Replica Dashboard I get error:

> This secondary database is not joined to the availability group. The configuration of this secondary database is incomplete. For information about how to join a secondary database to an availability group, see SQL Server Books Online.

And message

> The data synchronization state of this availability database is unhealthy. On an asynchronous-commit availability replica, every availability database should be in the SYNCHRONIZING state. On a synchronous-commit replica, every availability database should be in the SYNCHRONIZED state.

**Comment by gamarcon** [comment]
I attempted to run the the [Add-DbaAgDatabase] on another environment with AOAG in order to test/check if there was an issue with my servers.

Turns out that I get the exact same result: Database is added only to the Primary replica and I see the same errors on the Secondary: This secondary database is not joined to the availability group.

Adding the database manually or through SQLPS [https://docs.microsoft.com/en-us/powershell/module/sqlserver/add-sqlavailabilitydatabase?view=sqlserver-ps](url) works fine.

Any update / assistance is much appreciated.
Thanks

**Comment by potatoqualitee** [comment]
Thanks so much, I don't use AGs so I'm not really familiar with their default behavior. I'll add this in within the next 24 hours 👍  Please keep the feedback coming.

**Comment by nvarscar** [comment]
I have definitely seen that behavior in my home-grown AG scripts, though I'm still unsure what causes it. Sometimes I was getting a perfectly healthy AG, sometimes databases would not join. So I implemented something like this:
``` powershell
#Add the database to AG
Write-Verbose "Adding database $targetDatabaseName to the Availability Group $AvailabilityGroup"
$availabilityDb = New-Object -TypeName Microsoft.SqlServer.Management.Smo.AvailabilityDatabase -ArgumentList @((Connect-DbaInstance -SqlInstance $currentPrimary).AvailabilityGroups[$AvailabilityGroup], $targetDatabaseName)
$availabilityDb.Create()

# wait a few seconds before enforcing secondaries
Start-Sleep 10

#Ensuring all secondaries managed to join the AG
foreach ($s in $TargetServer) {
	if ($s -ne $currentPrimary) {
		$agDb = (Connect-DbaInstance -SqlInstance $s).AvailabilityGroups[$AvailabilityGroup].AvailabilityDatabases[$TargetDatabaseName]
		Write-Verbose "Database $s.$TargetDatabaseName is joined to $AvailabilityGroup`: $($agDb.IsJoined)"
		if (!$agDb.IsJoined) {
			Write-Verbose "Manually joining the AG $AvailabilityGroup`:  $s.$TargetDatabaseName"
			$agDb.JoinAvailablityGroup()
		}
	}
}
```
Basically, for each secondary that is not joined, call JoinAvailablityGroup() when IsJoined is $false.
Start-Sleep is there because it takes some time for the AG to finalize the sync operations after joining (could be more on highly-loaded systems), not sure yet if there is an alternative to this.

**Comment by potatoqualitee** [comment]
This is super helpful, thank you!

**Comment by potatoqualitee** [comment]
thanks for the code! i didnt realize that $ag would even have the JoinAvailablityGroup() method. Saved me a ton of time! PR will be merged once tests pass ✔
