### ISSUE TITLE
Copy-DbaDatabase - BackupRestore without a network share

### ISSUE THREAD

**Issue by Janneaa** [sqlcollaborative/dbatools#4448]
---
name: Copy-DbaDatabase - BackupRestore without a network share
about: Copy-DbaDatabase needs to be able to copy a database with the BackupRestore method without the requirement for a network share.

---

### Summary of new feature

* I think that there is a clear use case for Copy-DbaDatabase to be able to copy a database with the BackupRestore method without a network share.
* Not all server environments have network shares that are accessible by both the source and the destination database servers.
* The DetachAttach method is not always suitable, since it disrupts the production use of the source server.
* This feature would enable the use of Copy-DbaDatabase in such an environment. 

### Proposed technical details (if applicable)

* Steps
  * Create a new backup to the source server's default backup path (or use the latest existing backup)
  * Copy the backup file from the source server's UNC path to the destination server's default backup path (using BITS)
  * Restore the backup on the destination server

### Latest version of dbatools as of writing

* 0.9.504

**Comment by nvarscar** [comment]
I'm pretty sure that there are other people like me, who are not using default backup paths and who wouldn't want the command to implicitly copy a huge backup file into a default folder. Is there anything that prevents you from opening a share on a source or a destination server? You could use admin shares \\server\f$\backups as well, but you'd have to ensure that remote server has admin access to the computer to use them.
Copying backups between servers seems to me slightly out-of-scope for this command, and might better be handled with the building blocks of the Copy command: Backup-DbaDatabase->Transfer files->Restore-DbaDatabase.

**Comment by Stuart-Moore** [comment]
Yep. That sounds a better solution to me. The number of options for file
copy we could be asked for is large. So leave that bit to better specific
solutions

**Comment by potatoqualitee** [comment]
Thanks for the thorough request! However, I agree with the above this would be a Backup-DbaDatabase/copy/Restore-DbaDatabase solution.
