### ISSUE TITLE
Unnecessary Warning on Backup-DbaDatabase

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4455]
This was unexpected:

`Get-DbaDatabase -SqlInstance sql2017 -NoSystemDb | Backup-DbaDatabase -BackupDirectory \\dc\sql\test3 -Type Full`

![image](https://user-images.githubusercontent.com/8278033/48269778-b02f6e00-e438-11e8-9b30-c20fe9bd61ef.png)

**Comment by potatoqualitee** [comment]
Type log also gives warnings

![image](https://user-images.githubusercontent.com/8278033/48269930-0c928d80-e439-11e8-813f-ebd1325e1dbe.png)

**Comment by potatoqualitee** [comment]
Don't know if you noticed the commit, but I sent a lil ping on commit https://github.com/sqlcollaborative/dbatools/pull/4456/commits/78e0dcf39dd48a84d13a1c18c3a5da0a8f75282b

**Comment by potatoqualitee** [comment]
But should this occur with a fresh, brand new backup? Is it accurate? I would have thought that'd restart the fork? Was it a bad idea to silence it?

I believe the db its referencing is in an AG. Maybe it'd be helpful to skip it instead.

**Comment by Stuart-Moore** [comment]
Ah was on the bus and didn’t read the full command. Yes shouldn’t appear on
a backup, probably needs a filter on since based on the backup time. I’ll
have a look in a bit.

**Comment by potatoqualitee** [comment]
Excellent, I've hushed it in Backup for now 👍

**Comment by Stuart-Moore** [comment]
Fixed in PR #4477
