### ISSUE TITLE
Copy-DBALogin performance

### ISSUE THREAD

**Issue by elguapo79** [sqlcollaborative/dbatools#4473]
I've been running a Start-DBAMigration against a server with ~100 databases, and a similar number of logins, and when it gets to the call to Copy-DbaLogin, performance slows to a crawl, to the tune of 1 login every 5-10 minutes.  I assume this is due to the permission and roles portion of the function.  

It would be helpful if the function had a parameter to skip roles/permissions, especially for a full migration, since a restore of a backup during the migration will have all the same permissions and database roles.

**Comment by potatoqualitee** [comment]
Yuck, those are terrible speeds. Can you please run `-Verbose` and tell me where it's stalling?

**Comment by elguapo79** [comment]
Here’s the verbose logging on one of the logins:

[cid:image001.png@01D47857.38F44F10]

Jason Allen
Senior Microsoft SQL Server DBA

[ntirety_NEWidLG]

**Comment by potatoqualitee** [comment]
Unfortunately, the photo via email did not work - it was linked like cid:image001.png@01Detc

**Comment by elguapo79** [comment]
Here lets try this way
![copylogin](https://user-images.githubusercontent.com/28631696/48295623-fa214f80-e44a-11e8-9b3d-d1fb6227e8dc.png)

**Comment by potatoqualitee** [comment]
thanks that worked - check out https://github.com/sqlcollaborative/dbatools/pull/4474 see if it helps
