### ISSUE TITLE
Get-DbaPrivilege output fixes

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4478]
Not a fan of the output

![image](https://user-images.githubusercontent.com/8278033/48320069-87180480-e615-11e8-8e7b-4ea3a5b9dd3d.png)

"Privilege" can be removed from each of these colummns

LogonAsBatchPrivilege 
InstantFileInitializationPrivilege
LockPagesInMemoryPrivilege

But I need to send out a blog post letting people know about big ol breaking changes coming, then it can be updated.

**Comment by Splaxi** [comment]
Sorry if I made you look into it. I just wanted to fix the broken stuff 😆

**Comment by potatoqualitee** [comment]
LOL, it's not you, this is on the agenda for 1.0
