### ISSUE TITLE
Need to add SMO / DMO Disabled check to Connect-SqlServer

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#448]
Is this a *feature* OR *bug*:
Kind of a bug? 

**Additional comments**
If sp_configure 'SMO and DMO XPs', 0;  then SSMS bails and doesn't even try to connect. People may think that since we're command line, we can bypass a lot of the GUI stuff and thus they still won't need SMO. We should check and bail too.

![image](https://cloud.githubusercontent.com/assets/8278033/21297730/343eab40-c585-11e6-96a3-4db2e0867325.png)

**Comment by wsmelton** [comment]
Just to question one thing....the ONLY thing this feature does is enable extended stored procedures that utilize SMO for SSMS. Unless I'm mistaken this being disabled will not prevent dbatools from functioning, so why bail?

**Comment by shaneis** [comment]
@ctrlbold @wsmelton 
I have a partial fix for this in #709 although I'm not sure if we're still going that way...

Do you want me to change the code to a "Write-Message" (to appease @FriedrichWeinmann 😄 ) with something like "some dbatools commands will not work" and let it run on? Or something else?

I think we'd need to figure out what needs the SMO/DMO XPs then though if we do go down that route.

Thoughts/Comments?

**Comment by potatoqualitee** [comment]
I've since decided against this and removed it rom connect-sqlinstance cuz it just doesnt happen enough
