### ISSUE TITLE
Set-DbaPowerPlan prompts for credentials on older versions of PS

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4480]
Set-DbaPowerPlan prompts for credentials - when executed directly and when piped in.

`Test-DbaPowerPlan -ComputerName sql2016 | Set-DbaPowerPlan -PowerPlan Balanced`

![image](https://user-images.githubusercontent.com/8278033/48320513-46bb8500-e61b-11e8-9df5-761f0be5f7a2.png)

/cc @sqllensman can you take a look?

**Comment by sqllensman** [comment]
Will have a look. I have some PS4 instances

**Comment by potatoqualitee** [comment]
thanks much, Patrick!

**Comment by sqllensman** [comment]
In PowerShell 4 the calls to New-CimSession don't like a null Credential
Creating a Pull request that uses Test-Bound to create appropriate call
