### ISSUE TITLE
Remove most instances of output buffering

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4481]
A few years ago, we got into the habit of buffering results so that we could better control the output with -Detailed and -Simplified. This buffering gave the impression that the commands were running slowly.

We decided later on to heed Bruce Payette's advice to "release to the pipeline as quickly as possible". 

Here's a list of commands that _may_ need a rework. There are some valid instances of buffering in `System.Collections.ArrayList`, however.

![image](https://user-images.githubusercontent.com/8278033/48320616-26d89100-e61c-11e8-8085-d357a4da44a4.png)

**Comment by sqllensman** [comment]
I was playing with changing this as part of Set- DbaPowerPlan changes done yesterday. Actually makes code clearer
