### ISSUE TITLE
Test-SqlPath needs some TLC

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#449]
Is this a *feature* OR *bug*:
bug

**Steps to Reproduce**
Run Test-DbaLastBackup w/o adequate sysadmin (possible? I dont know) and w/o user permissions to the backup directory. 

**Action Results**
It'll say FileExists = $false. A user complained that he could totally restore using T-SQL but Run Test-DbaLastBackup bailed because it said FileExists = $false

**Expected Results**
That if a Backup can be restored, it should be able to be restored

**Additional comments**

- [ ] Add a -Backup param to Test-SqlPath
- [ ] If ($backup -eq $true) then test with RESTORE HEADERONLY instead of xp_fileexists
- [ ] Then in another PR, we'd have to add -Backup to Test-DbaLastBackup
- [ ] Add an additional check to the default Test-SqpPath -- in addition to xp_fileexists (which is controlled by SmoAndDmoXPsEnabled btw and uses the user's permissions). If xp_fileexists returns $false, then do a $testfilepath = Join-AdminUnc $server $path then Test-path $testfilepath that way.

**Comment by niphlod** [comment]
this has been - probably - resolved switching to xp_dirtree.

**Comment by potatoqualitee** [comment]
lol almost a year old now D:
