### ISSUE TITLE
"Archive may not be valid" error when running Install-DbaSqlWatch

### ISSUE THREAD

**Issue by garyhampson** [sqlcollaborative/dbatools#4491]
[dbatools_14260_message_0.log](https://github.com/sqlcollaborative/dbatools/files/2573497/dbatools_14260_message_0.log)

### Before submitting a bug report:

- [ X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ X] Verified this bug is not already reported in an issue
- [ X] Verified errors are not related to permissions
- [ X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell

PS C:\Users\Gary> Install-DbaSqlWatch -SqlInstance $SQLInstance -Force
```

## Expected Behavior

ComputerName : COMPUTERNAME-INSTANCENAME
InstanceName : MSSQLSERVER
SqlInstance  : COMPUTERNAME-INSTANCENAME
Database     : SQLWATCH
Status       : (Complete)

## Actual Behavior

WARNING: [12:31:26][Install-DbaSqlWatch] Unable to extract
C:\Users\Gary\AppData\Roaming\PowerShell\dbatools\SQLWATCH-v1.3.20\SQLWATCH_1.3.20.zip. Archive may not be valid. | The path 'C:\Users\Gary\AppData\Roaming\PowerShell\dbatools\SQLWATCH-v1.3.20\SQLWATCH_1.3.20.zip' either does not exist or is not a valid file system path.

## Environmental data

- - PowerShell: 
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 
 - - SQL Server: 
Microsoft SQL Server 2017 (RTM-CU12) (KB4464082) - 14.0.3045.24 (X64) 
	Oct 18 2018 23:11:05 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Thanks much. can you run it with a `-Verbose` and paste here?

**Comment by garyhampson** [comment]
PS C:\WINDOWS\system32> Install-DbaSqlWatch -SqlInstance $SQLInstance  -Force  -Verbose
VERBOSE: Performing the operation "Downloading latest release from GitHub" on target "DIDIERDROGBA".
VERBOSE: [15:51:40][Install-DbaSqlWatch] Checking GitHub for the latest release.
VERBOSE: GET https://api.github.com/repos/marcingminski/sqlwatch/releases with 0-byte payload
VERBOSE: received 9743-byte response of content type application/json; charset=utf-8
VERBOSE: [15:51:41][Install-DbaSqlWatch] Latest release is available at
https://github.com/marcingminski/sqlwatch/releases/download/SQLWATCH-v1.3.20/SQLWATCH_1.3.20.zip
VERBOSE: Performing the operation "Unpacking zipfile" on target "DIDIERDROGBA".
VERBOSE: [15:51:41][Install-DbaSqlWatch] Unblocking
C:\Users\Gary\AppData\Roaming\PowerShell\dbatools\SQLWATCH-v1.3.20\SQLWATCH_1.3.20.zip
VERBOSE: [15:51:41][Install-DbaSqlWatch] Extracting
C:\Users\Gary\AppData\Roaming\PowerShell\dbatools\SQLWATCH-v1.3.20\SQLWATCH_1.3.20.zip to
C:\Users\Gary\AppData\Roaming\PowerShell\dbatools\SQLWATCH-v1.3.20
WARNING: [15:51:42][Install-DbaSqlWatch] Unable to extract
C:\Users\Gary\AppData\Roaming\PowerShell\dbatools\SQLWATCH-v1.3.20\SQLWATCH_1.3.20.zip. Archive may not be valid. |
Exception calling ".ctor" with "3" argument(s): "Central Directory corrupt."
PS C:\WINDOWS\system32>

**Comment by potatoqualitee** [comment]
Shoot, I have no idea. It appears to download successfully because it unblocks successfully. What happens when you download https://github.com/marcingminski/sqlwatch/releases/download/SQLWATCH-v1.3.20/SQLWATCH_1.3.20.zip from a web browser? Can you open it?

**Comment by garyhampson** [comment]
Yes, I see the DACPACs and the PowerBI Templates. I think you can mark this as closed, as while I couldn't get it installed on the one machine I had been trying, I was just able to successfully install on the instances I built in my newly created lab environment. 🤷‍♂️

**Comment by potatoqualitee** [comment]
oh good, maybe that...machine had corruption? 😅  Thank you, will close now.
