### ISSUE TITLE
GET-DbaDbFile Error

### ISSUE THREAD

**Issue by habibhammy** [sqlcollaborative/dbatools#4492]
Hello DbaTool Team,

I'm writing to you as I'm facing a little bug on the Get-DbaDbFile command.
To be short, I'm trying to get informations about disk usage of my databases on a SQL 2000/2005/2008-R2/2012/2014 and 2017.  However, I'm getting a ScriptMethodRunTimeException error for the SQL 2000. 
Here is the command I'm running and the output I'm getting : 
Running Command :
`
PS C:\Windows\system32>  $result = Get-DbaDbFile -SqlInstance MyServerName -ExcludeDatabase { 'master', 'msdb', 'tempdb', 'model'} -Verbose
`

OutPut: In the attached File.

I do not know if it's a bug on the Dba tool side or in my code but for me any help will be appreciated.

Many Thanks.

HMH
[GET-DBbaDbFile_OutPut.txt](https://github.com/sqlcollaborative/dbatools/files/2576519/GET-DBbaDbFile_OutPut.txt)

**Comment by potatoqualitee** [comment]
Thanks, I can replicate the issue, will fix

**Comment by habibhammy** [comment]
Hello,

Sorry to come back to this topic again. But I think the issue is still not resolved. 
Actually, when trying to retrieve the Files details on a SQL 2000 the command do not retrieve infos from all databases as per the screenshot below : 
![error_screen](https://user-images.githubusercontent.com/11525159/48940326-715ce600-ef17-11e8-80e6-f307113a57b9.png)

Many thanks for the first fix by the way.

Habib

**Comment by niphlod** [comment]
ouch, we may need a 2000 around to test :D

**Comment by niphlod** [comment]
BTW @habibhammy : can you do a get-module dbatools and post the output ?

**Comment by niphlod** [comment]
is the target server by any chance a case sensitive collation ?

**Comment by niphlod** [comment]
closing this in favour of https://github.com/sqlcollaborative/dbatools/issues/4640
