### ISSUE TITLE
Support for DBCC Commands

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#4493]
---
Add Support for running Database Console Commands

---

### Summary of new feature
Currently dbatools has limited support for the various Database Console Commands
Commands like Invoke-DbaDbClone are wrappers around DBCC CloneDB and some other commands make use of commands like DBCC CHECKDB or DBCC PAGE but there is not support for the majority of available commands

The current set of documented DBCC Commands can be seen at:
https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-transact-sql?view=sql-server-2017

This lists 32 commands

For a full list of both Documented and Undocumented commands the following T-SQL statement can be run

DBCC TRACEON (2588);
GO
DBCC HELP ('?');
GO

This lists over 100 commands

All of these commands  could be run via  Invoke-DbaQuery but this gives limited command over output,
doesn't support  WHATIF or CONFIRM and can be difficult to use.

### Proposed technical details (if applicable)
As most commands are not supported by SMO the code would mostly require using embedded T-SQL but the difficulties of constructing the necessary commands can be abstracted. The use of ValidateSets on parameters can also reduce complexity.

Similar commands like DBCC CHECKDB, DBCC CHECKTABLE, DBCC CHECHALLOC etc that perform same action but at different object level could be combined into commands like Invoke-DbaDbCheckCorruption

The issue is if support should be created for
1. Limited set of DBCC Commands
2. All documented DBCC Commands excluding deprecated commands
3. All documented DBCC Commands
4. All documented DBCC Commands plus well known undocumented commands (eg DBCC Page)
5. All available DBCC Commands 

Many of the undocumented commands are either too obscure or too dangerous for general exposure so supporting all DBCC Commands would seem to be out of scope.

### Latest version of dbatools as of writing
0.9.509

**Comment by potatoqualitee** [comment]
`Invoke-DbaDbCheckCorruption` I like that!

I'm thinking 2 commands - `Invoke-DbaDbCheckCorruption` and then a Dbcc Invoker with # 2

What do you think?

**Comment by potatoqualitee** [comment]
And agreed about the ValidateSet

**Comment by sqllensman** [comment]
Would require at least three as need to distinguish Server level and Database level commands 

Invoke-DbaDbDBCC
and 
Invoke  DbaServerDBCC

**Comment by potatoqualitee** [comment]
Sounds perfect

**Comment by potatoqualitee** [comment]
done!!! 🥇 🥇 🥇 🥇
