### ISSUE TITLE
Copy-DbaLogin Add Individual Database Support

### ISSUE THREAD

**Issue by dlh275** [sqlcollaborative/dbatools#4508]
---
Copy-DbaLogin Add Individual Database Support :bomb:
Add a database parameter that will filter logins to only those found in that database.

---

### Summary of new feature

This will help support piecemeal migrations when different databases are to be migrated to different servers.  It will also keep from cluttering up the destination instances with logins not associated with the migrated database(s).

### Latest version of dbatools as of writing

0.9.509

**Comment by potatoqualitee** [comment]
Thank you for your request. This appears out of scope for the command, however, it's still possible with a couple commands.

````
$dblogins = Get-DbaDbUser -SqlInstance sql2017 -Database copiedb | Where Login | Select -Unique -ExpandProperty Login
Copy-DbaLogin -Source sql2017 -Login $dblogins -Destination sql2016
````
