### ISSUE TITLE
Rename Write-DbaDataTable

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4523]
I'm up for Write-DbaDbTableData but mabye that's too long. Let me know.

Microsoft went with Write-SqlTableData

**Comment by potatoqualitee** [comment]
ahh that's why, because we did Copy-DbaDbTableData. Maybe I'll update the name it then just make a permanent alias?

**Comment by jpomfret** [comment]
@potatoqualitee I have Copy-DbaDbTableData open right now... do you want it renamed and an alias added to address this issue?

**Comment by potatoqualitee** [comment]
yes, actually thank you but this would be Write-DbaDataTable -> Write-DbaDbTableData

**Comment by potatoqualitee** [comment]
in it, doing it now 👍
