### ISSUE TITLE
Install-DbaInstance features

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4527]
hey @reitse,
I updated the command a bit. The biggest change is remote installation. There's still a bit of work to do but we're progressing!

Here's the requested changes while they are fresh

- [ ]  Detect if non-default instance then set browser service to auto start in config
- [ ]  Replace `SQLTEMPDBFILECOUNT=""` etc with calculated results
- [ ]  Add 2016 configuration.ini
- [ ] Add collation support
- [ ] Add service account support

Branch off of the install-DbaInstance branch. You can also use the repo directly once you accept the invitation to the SQL Collaborative 🎉 

https://github.com/sqlcollaborative/dbatools/tree/Install-DbaInstance

**Comment by potatoqualitee** [comment]
consolidating to https://github.com/sqlcollaborative/dbatools/pull/5175

**Comment by reitse** [comment]
Hey Chrissy,

I saw the latest update and i shrunk about 6 feet... I didn't forget this project but just went out of time to work on it. You know the score, probably better than me... 

You closing this issue means that the code has been written? I'm sorry i've let you down.
