### ISSUE TITLE
Find-DbaInstance

### ISSUE THREAD

**Issue by chancen10** [sqlcollaborative/dbatools#4531]
Hi
Find-DbaInstance seems to give me a wrong version of the SQL server:
***************************************************************************
$a = Find-DbaInstance -ComputerName $computername -ScanType All
$a[0].BrowseReply.Version
10.50.4000.0

(Invoke-Sqlcmd -ServerInstance $a[0].BrowseReply.SqlInstance -Query 'SELECT @@VERSION').column1
Microsoft SQL Server 2008 R2 (SP3-OD) (KB3144114) - 10.50.6542.0 (X64)
        Feb 22 2016 18:07:23
        Copyright (c) Microsoft Corporation
        Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
***************************************************************************
Find-DbaInstance shows 10.50.4000.0 and Invoke-Sqlcmd shows 10.50.6542.0
Is this on purpose ? Should I use another function for pulling out the version of SQL ?

Kind regards
Kristian

**Comment by potatoqualitee** [comment]
Hey Kristian, 
Try this, see if it helps improve the results

`Find-DbaInstance ComputerName $computername -ScanType SqlConnect`

It appears that when the ScanType of All is used, the command may be finding the information from UDP, which may be reporting basic builds. 

let me know if that helps. If not, I'll update the documentation to say we do our best but specific results including version should be confirmed.

**Comment by chancen10** [comment]
Hi
If I try to use SqlConnect as scantype I get an error:
************************
$a = Find-DbaInstance -ComputerName $computername -ScanType SqlConnect
WARNING: [22:29:34][Find-DbaInstance] Invalid Scan Types specified: SqlConnect | Specify at least one of the following types: Browser, SqlService, SPN, TCPPort, Default or All. Otherwise no detection will be possible.
************************
$a = Find-DbaInstance -ComputerName $computername -ScanType default,SqlConnect
$a[0].BrowseReply.Version
10.50.4000.0
************************
I then tried to use default and SqlConnect, but then I get the wrong version.

Kind regards
Kristian

**Comment by potatoqualitee** [comment]
ohh i think someone else mentioned this, ill clean up the docs, ty

**Comment by potatoqualitee** [comment]
k try this `Find-DbaInstance -ComputerName $computername -ScanType All`

let me know the results of that. Then

can you do

````
$server = Connect-DbaInstance -SqlInstance ThatInstanceReportingTheWrongVersion
$server.ResourceVersionString
$server.Version
````

Let me know how that works

**Comment by chancen10** [comment]
ScanType All get me a wrong version
*****************
$a = Find-DbaInstance -ComputerName $computername -ScanType all
$a[0].BrowseReply.Version
10.50.4000.0
*****************
$server.ResourceVersionString
10.50.6000
$server.VersionString
10.50.6542.0
*****************
The versionstring gives the right result

Kind regards
Kristian

**Comment by potatoqualitee** [comment]
ah ha! so looking at the code, this comes from the Sql Browser Service. Your current approach is the proper one to take 👍  Or figure out what's up with the browser service, perhaps there's a sql server patch to get the right version.

Alternatively, I've just released a bugfix that allows you to use SqlConnect as a ScanType and you can try that, see if it helps.
