### ISSUE TITLE
Test all the Get- cmdlets

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#4558]
### Summary of new feature

There are a substantial number of `Get-` cmdlets that do not have a integration test. These should be written to improve the health of the module. Writing these tests may also provide easy wins with other cmdlets of similar nouns.

### Proposed technical details (if applicable)

Using before all blocks will create the items the will need to be retrieved. Run the `Get-` cmdlet. Evaluate the results with tests and then remove the items in an after all block.

### Latest version of dbatools as of writing

0.9.518

**Comment by potatoqualitee** [comment]
yes ty!

**Comment by joshcorr** [comment]
PR #4637 was related to this Issue

**Comment by joshcorr** [comment]
PR #4697 was related to this Issue

**Comment by joshcorr** [comment]
PR #4789 was related to this Issue

**Comment by joshcorr** [comment]
PR #4801 was related to this Issue

**Comment by joshcorr** [comment]
@cl Putting Back in ToDo as I will be busy the next few weeks with the Holidays and don't know how regular I can contribute. Should be back on it in January.

**Comment by jpomfret** [comment]
If my calculations are right that was the last 'Get' command that needed tests...

**Comment by potatoqualitee** [comment]
Thank you!!
