### ISSUE TITLE
Test-DbaLastBackup is not restoring user databases

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#4574]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
Test-DbaLastBackup -SqlInstance MYSERVER -Verbose
```

## Expected Behavior
User databases are expected to be test restored, and later DBCC checked.

## Actual Behavior
Only system databases were restored and DBCC checked.
I never get a `VERBOSE: [16:37:56][Test-DbaLastBackup] Looking good!` on the user dbs.

```powershell
Test-DbaPath -SqlInstance MYSERVER -Path \\ANOTHERSERVER\SHARE\PATH\DATABASENAME\```
```
Returned True

```powershell
Get-DbaBackupHistory -SqlInstance MYSERVER -Database ATestFailedDatabase-IncludeCopyOnly:$IncludeCopyOnly -Last
```
Successfully returned a Full, 1 Diff, 3 Log backups.
When that was piped to `Restore-DbaDatabase` ... `-DestinationFilePrefix $shoeprefix -RestoredDatabaseNamePrefix $shoeprefix -OutputScriptOnly` the output script was successfully executed in SSMS.

## Environmental data

 PowerShell: 
Name                           Value                                                                                                                       
----                           -----                                                                                                                       
PSVersion                      5.1.17134.228                                                                                                               
PSEdition                      Desktop                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                     
BuildVersion                   10.0.17134.228                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                             
WSManStackVersion              3.0                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                         
SerializationVersion           1.1.0.1 

SQL Server:  Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64)   Sep 14 2018 13:53:44   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
thanks 👞 !

**Comment by potatoqualitee** [comment]
pasting a cleaned verbose here
```
VERBOSE: [16:38:00][Test-DbaLastBackup] Getting recent backup history for DBNAME on SQLSVR01.
VERBOSE: [16:38:00][Get-DbaBackupHistory] Processing DBNAME
VERBOSE: [16:38:00][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [16:38:00][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [16:38:00][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [16:38:00][Get-DbaBackupHistory] Processing DBNAME
VERBOSE: [16:38:00][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [16:38:00][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [16:38:00][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [16:38:00][Get-DbaBackupHistory] Valid Differential backup 
VERBOSE: [16:38:00][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [16:38:00][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [16:38:00][Get-DbaBackupHistory] 4 result-groups found.
VERBOSE: Performing the operation "Showing results" on target "console".
SourceServer   : SQLSVR01
TestServer     : SQLSVR01
Database       : DBNAME
FileExists     : False
Size           : 1.03 GB
RestoreResult  : Skipped
DbccResult     : Skipped
RestoreStart   : 2018-11-17 16:37:57.647
RestoreEnd     : 2018-11-17 16:37:59.201
RestoreElapsed : 00:00:01
DbccStart      : 2018-11-17 16:37:59.221
DbccEnd        : 2018-11-17 16:38:00.418
DbccElapsed    : 00:00:01
BackupDates    : {11/17/2018 13:30:25, 11/17/2018 13:30:41, 11/17/2018 13:30:53, 11/17/2018 14:00:01...}
BackupFiles    : {\\NAS\LOGS\SQLSVR01\DBNAME\DBNAME_20181117133025.BAK, 
                 \\NAS\LOGS\SQLSVR01\DBNAME\DBNAME_20181117133041.DIF, 
                 \\NAS\LOGS\SQLSVR01\DBNAME\TRN\DBNAME_20181117133052.TRN, 
                 \\NAS\LOGS\SQLSVR01\DBNAME\TRN\DBNAME_20181117140000.TRN...}
```

**Comment by wsuhoey** [comment]
I just tried this again in 0.9.714 and it still seems to be an issue. Can anyone else confirm they can repro?

**Comment by wsuhoey** [comment]
I'm still able to reproduce this on 0.9.734 :(

**Comment by wsmelton** [comment]
It will be reproduced in every release until someone actually fixes this issue 😉 (as it stands no one has spent time on it).

**Comment by frank687** [comment]
I too can duplicate this issue. 

`Test-DbaLastBackup -SqlInstance SQL2014.example.com -Destination SQL2014-1 -Prefix test_ -Verbose`

[testlastbackup_Output.log](https://github.com/sqlcollaborative/dbatools/files/2728473/testlastbackup_Output.log)
[testlastbackup_Verbose.log](https://github.com/sqlcollaborative/dbatools/files/2728474/testlastbackup_Verbose.log)

**Comment by frank687** [comment]
@potatoqualitee I found a way to reproduce the issue.

Create a new database without a backup. Then restore a set of databases including this new database. Two things will occur.

1. You will not see any output about the database without a backup on the console. 
2. $restoreresult is not reset on each iteration through the loop. Since it's set to 'Skipped' all subsequent databases are skipped.

**Comment by wsmelton** [comment]
@wsuhoey can you more details; if you want to update the original post at the top is fine on what is being run, how the users databases are setup (do they all have backups, only some have backups, etc.)? The original command you provided includes no parameters to specify where to look for backups, but your test path command shows a network path. If you do not provide the path for the command to copy the backup files from it will only check the default backup path of the source server (is that set to the network path?). If it does not find any backups then the database is skipped.

**Comment by wsuhoey** [comment]
`Get-DbaDefaultPath` returns the same path `\\ANOTHERSERVER\SHARE\PATH\` (without \DATABASE).
This path is organized with sub-folders for each database after that, like this:
```
\\ANOTHERSERVER\SHARE\PATH\Database1\
\\ANOTHERSERVER\SHARE\PATH\Database2\
etc.
```
`Get-DbaLastBackup -SqlInstance MYINSTANCE | Where-Object LastFullBackup -EQ $null` returned 4 databases, which is expected in my case.

**Comment by wsmelton** [comment]
So @frank687 your PR will not address this problem because all the user databases have a backup. The only way `$restoreresult` will get set to `Skipped` is if a backup is not found. So in John's scenario it won't matter whether that variable is set to null or not.

@wsuhoey so on that source instance with the 35 databases do you get just full backups on this command or full plus diff?
```powershell
Get-DbaBackupHistory -SqlInstance MYINSTANCE -Last
```

**Comment by wsuhoey** [comment]
Just saw Shawn's question today.
Yes, `Get-DbaBackupHistory -SqlInstance MYINSTANCE -Last` returns Full, Diff, and Log backups.
