### ISSUE TITLE
SSMS introduces data masking

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4578]
https://azure.microsoft.com/en-us/blog/static-data-masking-preview/

Looks like this may be in the new SMO. If anyone wants to take this on to explore, that'd be awesome.

**Comment by nvarscar** [comment]
One thing for sure - no SMO documentation so far, but it will be oh so awesome to have it exposed to SMO.

**Comment by sanderstad** [comment]
This is probably not going to be in RTM for a while.
Especially because the functionality was removed from SSMS.
dbatools has commands for handling this. 

Closing the request

**Comment by potatoqualitee** [comment]
sounds good ty, what you did was this but better
