### ISSUE TITLE
DbaServer Rename

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4580]
The name never sat right with me. I'd like to change a few of these

![image](https://user-images.githubusercontent.com/8278033/48718811-61de5400-ec1c-11e8-873c-07a885814eb7.png)

ServerAudit -> Audit and then make a DbAudit <-- for sure
ServerAuditSpecificiation -> Audit and then make a DbAuditSpecificiation <-- for sure
ServerTrigger -> Trigger. DbTrigger already exists <-- questionable
ServerRole -> Role, then make a DbRole
ServerRoleMember -> RoleMember. DbRoleMember already exists

**Comment by csolje** [comment]
The Names reflects pretty good with what the same feature is called on the Sql Server

**Comment by potatoqualitee** [comment]
i'd still like to go forward but it turns out there are breaking changes so going to put this on hold till closer to 1.0

**Comment by shaneis** [comment]
Isn't there an inherent difference between `ServerTrigger` & `ServerRole` and `DbTrigger` & `DbRole` i.e. the former being server based and the latter being database based?

To distinguish the difference, you'd need something like `Server` in there, or maybe `Srv` for brevity.

<strike>I was going to suggest adding a switch parameter `-Server` if you want to do something server based but</strike> I'd say that's too hidden away so wouldn't be discover-able enough for PowerShell.

**Comment by potatoqualitee** [comment]
yeah, they are there for legit reasons. i guess im just iffy on the word Server? Should it be Instance? But they are called Server in SMO i think

**Comment by potatoqualitee** [comment]
and thank you!

**Comment by NakedPowerShell** [comment]
I believe that whatever you pick will be the right choice. So I can live with either Server or Instance

**Comment by garethnewman** [comment]
I prefer Instance but can live with either :)

**Comment by potatoqualitee** [comment]
thank you all, i think im leaning instance since server never sat right ❤️

**Comment by NakedPowerShell** [comment]
To ship is to choose :}

**Comment by potatoqualitee** [comment]
k going instance, doing this now
