### ISSUE TITLE
Test-DbaBuild -Latest does not return CU recommendations

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#4584]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
<#
#Running against a SQL2016 SP2CU0 instance
Test-DbaBuild -SqlInstance sql2016SP2 -Latest
#>
```

## Expected Behavior

CUTarget       : CU3 (or whatever version is the latest)

## Actual Behavior

CUTarget       :

## Additional info
If used as follows:
```powershell
<#
Test-DbaBuild -SqlInstance sql2016SP2 -MaxBehind '0CU'
#>
```
the function returns CU recommendations appropriately, so that probably could be considered as a workaround.

## Environmental data

 - PowerShell: 
PSVersion                      5.1.15063.1387
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1387
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - - SQL Server:

**Comment by ijeb** [comment]
I looked into this issue, but it seems to me it was made this way by design. So just updating the help is an option. The code is complex, so I don't change it.

#4608 solves another issue, that's easy to fix.

    .EXAMPLE
        PS C:\> Test-DbaBuild -Build "12.0.5540" -MinimumBuild "12.0.5557"

        Returns information about a build identified by "12.0.5540" (which is SQL 2014 with SP2 and CU4), which is not compliant as the minimum required
        build is "12.0.5557" (which is SQL 2014 with SP2 and CU8).

    .EXAMPLE
        PS C:\> Test-DbaBuild -Build "12.0.5540" -MaxBehind "1SP"

        Returns information about a build identified by "12.0.5540", making sure it is AT MOST 1 Service Pack "behind". For that version,
        that identifies an SP2, means accepting as the lowest compliance version as "12.0.4110", that identifies 2014 with SP1.

        Output column CUTarget is not relevant (empty). SPTarget and BuildTarget are filled in the result.

    .EXAMPLE
        PS C:\> Test-DbaBuild -Build "12.0.5540" -MaxBehind "1SP 1CU"

        Returns information about a build identified by "12.0.5540", making sure it is AT MOST 1 Service Pack "behind", plus 1 CU "behind". For that version,
        that identifies an SP2 and CU, rolling back 1 SP brings you to "12.0.4110", but given the latest CU for SP1 is CU13, the target "compliant" build
        will be "12.0.4511", which is 2014 with SP1 and CU12.

    .EXAMPLE
        PS C:\> Test-DbaBuild -Build "12.0.5540" -MaxBehind "0CU"

        Returns information about a build identified by "12.0.5540", making sure it is the latest CU release.

        Output columns CUTarget, SPTarget and BuildTarget are relevant. If the latest build is a service pack (not a CU), CUTarget will be empty.

    .EXAMPLE
        PS C:\> Test-DbaBuild -Build "12.0.5540" -Latest

        Returns information about a build identified by "12.0.5540", making sure it is the latest build available.

        Output columns CUTarget and SPTarget are not relevant (empty), only the BuildTarget is.

    .EXAMPLE
        PS C:\> Test-DbaBuild -Build "12.00.4502" -MinimumBuild "12.0.4511" -Update

        Same as before, but tries to fetch the most up to date index online. When the online version is newer, the local one gets overwritten.

    .EXAMPLE
        PS C:\> Test-DbaBuild -Build "12.0.4502","10.50.4260" -MinimumBuild "12.0.4511"

        Returns information builds identified by these versions strings.

    .EXAMPLE
        PS C:\> Get-DbaCmsRegServer -SqlInstance sqlserver2014a | Test-DbaBuild -MinimumBuild "12.0.4511"

        Integrate with other cmdlets to have builds checked for all your registered servers on sqlserver2014a.

**Comment by potatoqualitee** [comment]
thanks, @ijeb - @nvarscar would that satisfy your requirements?

**Comment by nvarscar** [comment]
Not sure that I understand the intent behind the design, but I ended up using -MaxBehind 0CU everywhere already, so whatever works for you guys.

**Comment by potatoqualitee** [comment]
@niphlod can you provide any insight? was this an oversight?

**Comment by niphlod** [comment]
gladly but if you keep closing issues how can one backtrack its todolist ? :P

**Comment by niphlod** [comment]
(I'll close this when I'll get the time to evaluate the insightfullness ^__^ )

**Comment by potatoqualitee** [comment]
lol sorry, it uhh, it closed itself

**Comment by niphlod** [comment]
ok, I think I have it. When you do -Latest, you want the really latest build available, which can be neither a SP nor a CU (i.e. an interim-fix or a security fix not included in an "official CU").
Being the latest build not a CU nor an SP, there's no "target" to address, it's just either the latest release for that SQL version or not.

**Comment by niphlod** [comment]
so, the rationale is that:
- if you want to "trust" only CUs or SPs, you use -MaxBehind
- if you want to be on the latest CU (but you don't trust any given release is not strictly a CU) use -MaxBehind '0CU'
- if you want to be on the latest release (be it either an SP, a CU or none of the above), use -Latest

**Comment by potatoqualitee** [comment]
do you see any room for improvement, niph?

**Comment by niphlod** [comment]
ahum ..... there's `*Level` and `*Target`. -Latest has "blank" `*Target`. what do you see filled that it shouldn't be ? (and/or pass a build number that reproduces the issue, maybe it's a "local" problem)

**Comment by nvarscar** [comment]
Hmm. Okay, I see what you're saying. Thanks for clarification, I was apparently mixing up Level and Target in the output. I'll be using MaxBehind then.
