### ISSUE TITLE
Get-DbaBackupHistory -sqlinstance $target -database msdb -Force results in error

### ISSUE THREAD

**Issue by stevenksco** [sqlcollaborative/dbatools#4596]
I just update-dbatools today.  I get:
Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): 
"Execute with results failed for Database 'master'. ""
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.450\allcommands.ps1:24951 char:21
+                     $fileListResults = $server.Query($fileAllSql)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException
 
New-TimeSpan : Cannot bind parameter 'Seconds' to the target. Exception setting "Seconds": "Cannot convert null to 
type "System.Int32"."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.450\allcommands.ps1:24974 char:59
+ ... an -Seconds ($group.Group.Duration | Measure-Object -Maximum).Maximum ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-TimeSpan], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.NewTimeSpanCommand
 
Attempted to divide by zero.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.450\allcommands.ps1:24978 char:25
+ ...             $ratio = [Math]::Round(($commonFields.TotalSize) / ($comp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
 
Exception setting "Start": "Cannot convert null to type "System.DateTime"."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.450\allcommands.ps1:24990 char:21
+                     $historyObject.Start = $start
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
Exception setting "End": "Cannot convert null to type "System.DateTime"."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.450\allcommands.ps1:24991 char:21
+                     $historyObject.End = $end
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.450\allcommands.ps1:25002 char:21
+ ...             $historyObject.FileList = $fileListHash[$commonFields.Bac ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex
 
Get-DbaBackupHistory -sqlinstance $target -Force also gets the error.

**Comment by Stuart-Moore** [comment]
Sorry, just catching up on this. Can you let me have the full command syntax you were using please

**Comment by Stuart-Moore** [comment]
It will have been broken for ages......

Raw!=Force

Force forces the raw SQL output via a `select *` 🤮skipping dbatools aliases
Raw returns the dbatools aliases output with aliases

Put an extra test in for `$force` so we just dump the stuff out.

PR shortly

**Comment by Stuart-Moore** [comment]
It will have been broken for ages......

Raw!=Force

Force forces the raw SQL output via a select * 🤮skipping dbatools aliases
Raw returns the dbatools aliases output with aliases

Put an extra test in for $force so we just dump the stuff out.

PR shortlyDue to my incompetence with git this was fixed in PR #4675 so will work if you pull the dev branch. Not sure when it'll get pushed into the Ps Gallery I'm afraid, but it's usually not too long.
