### ISSUE TITLE
Maybe new feature:  FailoverDetector.exe wrapper

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4601]
1. ask tigerteam if we can use FailoverDetector.exe
2. write a wrapper?

https://blogs.msdn.microsoft.com/sql_server_team/failover-detection-utility-availability-group-failover-analysis-made-easy/

**Comment by SQLDBAWithABeard** [comment]
LOL

I've done this

https://sqldbawithabeard.com/2018/11/28/gathering-all-the-logs-and-running-the-availability-group-failover-detection-utility-with-powershell/ 

https://github.com/SQLDBAWithABeard/Functions/blob/master/Invoke-SqlFailOverDetection.ps1

Probably most of the work done but this one requires V5 - should be easy enough to change

**Comment by ClaudioESSilva** [comment]
Hi!
Have used this today and for future reference, I found that the `FailoverCluster` module name was incorrect.

`Get-Module FailoverCluster` should be `Get-Module FailoverClusters - ListAvailable`

Plural: FailoverCluster**s**
And `-ListAvailable` for the case when the module is not loaded yet.

PS: I was running on Microsoft Windows Server 2016 Standard

**Comment by SQLDBAWithABeard** [comment]
Good spot on the s ! 
Yes, it was written for a specific scenario, not all bases covered!!

**Comment by potatoqualitee** [comment]
mmm too many dependencies and not xplat :(
