### ISSUE TITLE
To use ReplaceDbNameInFile you must specify DatabaseName

### ISSUE THREAD

**Issue by tjslic** [sqlcollaborative/dbatools#4606]
I am trying to use Start-DbaMigration to migrate one instance to another, but I get the following error on every database restore: To use ReplaceDbNameInFile you must specify DatabaseName

After this finishes, I can restore all the databases using Restore-DbaDatabase, but it would be good to be able to do this in one step.

**Comment by ijeb** [comment]
Some more information about the specific command run would be helpful. I don't have issues.
For example, this works fine:
Start-DbaMigration -Source sqlserver-0 -Destination sqlserver-1 -BackupRestore -SharedPath '\\sqlserver-0\Share' -WithReplace

**Comment by tjslic** [comment]
Here is the command that fails:

Start-DbaMigration -source ussbysql808\k4mazz -Destination ussbysql808\rukone -BackupRestore -SharedPath \\ussbysql808\dbatools -Force

I can then continue with the following which works fine:

Restore-DbaDatabase -SqlInstance USSBYSQL808\rukone -path \\ussbysql808\dbatools

**Comment by potatoqualitee** [comment]
The problem is at `Copy-DbaDatabase.ps1:1177`, I'll take a closer look

**Comment by ijeb** [comment]
I can't see how databasename would become null

**Comment by potatoqualitee** [comment]
also, do you use the `sqlserver` or `sqlps` module and if so, can you run start-dbamigration from a freshly opened console without loading it sqlps or sqlserver first?

**Comment by tjslic** [comment]
Thank you for this. I am still testing but it seems to be working better from a fresh console instance.

**Comment by potatoqualitee** [comment]
excellent news!
