### ISSUE TITLE
Update-DbaServiceAccount remove OldPassword

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4607]
OldPassword is optional so let's remove it. then rename NewPassword to SecurePassword.

this wil be the last breaking change for a while, @nvarscar please confirm this is cool. i'd like to do it today.

**Comment by nvarscar** [comment]
As per [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.wmi.service.changepassword?view=sqlserver-2016#Microsoft_SqlServer_Management_Smo_Wmi_Service_ChangePassword_System_String_System_String_), the ChangePassword method requires both old and new password. I'm not sure in which situations this will be used, but I would imagine this to be a requirement when a user is not a local admin and cannot simply enforce a new password.

**Comment by potatoqualitee** [comment]
ill test witht he updates as well to ensure it works
