### ISSUE TITLE
Add database to availability group (on all nodes including backup/restore/seeding)

### ISSUE THREAD

**Issue by ijeb** [sqlcollaborative/dbatools#4610]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

It's easy to create an availability group, for example
New-DbaAvailabilityGroup -Primary sqlserver-0 -Secondary sqlserver-1 -Name test-ag -ClusterType Wsfc -SeedingMode Automatic -Database db1

But after that, if I want to add db2, I have to take many actions:
Backup full/log / restore /  Add-DbaAgDatabase on all nodes.

It would be usefull to put this part of the code in a separate function. DBA's often want to remove a database from an ag and later add it again (including the seeding).

### Proposed technical details (if applicable)

New function with basically this code. Not the same as Add-DbaAgDatabase.

        # Add databases
        Write-ProgressHelper -StepNumber ($stepCounter++) -Message "Adding databases"

        $allbackups = @{
        }

        foreach ($db in $Database) {
            if ($SeedingMode -eq "Automatic") {
                if ($Pscmdlet.ShouldProcess($Primary, "Backing up $db to NUL")) {
                    $null = Backup-DbaDatabase -BackupFileName NUL -SqlInstance $Primary -SqlCredential $PrimarySqlCredential -Database $db
                }
            }

            if ($Pscmdlet.ShouldProcess($Primary, "Adding $db to $Name")) {
                $null = Add-DbaAgDatabase -SqlInstance $Primary -SqlCredential $PrimarySqlCredential -AvailabilityGroup $Name -Database $db
            }

            foreach ($second in $secondaries) {
                if ($Pscmdlet.ShouldProcess($second.Name, "Adding $db to $Name")) {
                    $primarydb = Get-DbaDatabase -SqlInstance $Primary -SqlCredential $PrimarySqlCredential -Database $db
                    $seconddb = Get-DbaDatabase -SqlInstance $second -Database $db

                    if ((-not $seconddb -or $Force) -and $SeedingMode -ne 'Automatic') {
                        try {
                            if (-not $allbackups[$db]) {
                                if ($UseLastBackup) {
                                    $allbackups[$db] = Get-DbaBackupHistory -SqlInstance $primarydb.Parent -Database $primarydb.Name -IncludeCopyOnly -Last -EnableException
                                } else {
                                    $fullbackup = $primarydb | Backup-DbaDatabase -BackupDirectory $SharedPath -Type Full -EnableException
                                    $logbackup = $primarydb | Backup-DbaDatabase -BackupDirectory $SharedPath -Type Log -EnableException
                                    $allbackups[$db] = $fullbackup, $logbackup
                                }
                                Write-Message -Level Verbose -Message "Backups still exist on $SharedPath"
                            }
                            if ($Pscmdlet.ShouldProcess("$Secondary", "restoring full and log backups of $primarydb from $Primary")) {
                                # keep going to ensure output is shown even if dbs aren't added well.
                                $null = $allbackups[$db] | Restore-DbaDatabase -SqlInstance $second -WithReplace -NoRecovery -TrustDbBackupHistory -EnableException
                            }
                        } catch {
                            Stop-Function -Message "Failure" -ErrorRecord $_ -Continue
                        }
                    }
                    $null = Add-DbaAgDatabase -SqlInstance $second -AvailabilityGroup $Name -Database $db
                }
            }
        }

### Latest version of dbatools as of writing

development branch

**Comment by ijeb** [comment]
I think changing Add-DbaAgDatabase will be a good option. It will have four options (just like the wizard in SSMS): Automatic Seeding, Full database and log backup, Join only, Skip initial data synchronization.

Current implementation is Join only.

I will make a PR.

**Comment by PreacherCmdLets** [comment]
Hi Guys, 

I am trying to add database to AG without using manual full backup / restore , I think Add-dbaAgdatabase does it for us. But i am able to no do so is this code to latest version of dbatools ?
![image](https://user-images.githubusercontent.com/27749215/68035259-49324700-fc91-11e9-921d-34e7f39c6ea8.png)

**Comment by ijeb** [comment]
What happens if you add -SeedingMode Automatic?

**Comment by andreasjordan** [comment]
Hi @PreacherCmdLets  and @ijeb , if you have still issues with Add-DbaAgDatabase or want to suggest improvements, join the discussion at https://github.com/sqlcollaborative/dbatools/issues/6724
