### ISSUE TITLE
GET-DbaDbFile Error related to issue #4492

### ISSUE THREAD

**Issue by habibhammy** [sqlcollaborative/dbatools#4640]
Hello,

Sorry to come back to this topic again. But I think the issue is still not resolved. 
Actually, when trying to retrieve the Files details on a SQL 2000 the command do not retrieve infos from all databases as per the screenshot below : 
![error_screen](https://user-images.githubusercontent.com/11525159/48940326-715ce600-ef17-11e8-80e6-f307113a57b9.png)

Many thanks for the first fix by the way.

Habib

_Originally posted by @habibhammy in https://github.com/sqlcollaborative/dbatools/issue_comments#issuecomment-441212019_

**Comment by niphlod** [comment]
BTW @habibhammy : can you do a get-module dbatools and post the output ?
is the target server by any chance a case sensitive collation ?

**Comment by habibhammy** [comment]
Yes of course. Here is the screenshot
![image](https://user-images.githubusercontent.com/11525159/48946318-94929000-ef2d-11e8-8fae-e53b3d47c170.png)

**Comment by habibhammy** [comment]
And yes the server is case sensitive 
![image](https://user-images.githubusercontent.com/11525159/48946437-0bc82400-ef2e-11e8-9413-cdf8c0873391.png)

**Comment by niphlod** [comment]
okay, gotcha.
