### ISSUE TITLE
export-dbadacpackage issue

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4646]
missing elapsed in both and weird xml name in core

![image](https://user-images.githubusercontent.com/8278033/48952268-e80ed900-ef41-11e8-84ac-d408a8cf52a0.png)

![image](https://user-images.githubusercontent.com/8278033/48952277-ecd38d00-ef41-11e8-8e7c-a181c66209df.png)

**Comment by ijeb** [comment]
I don't get a weird xml name in core.

Version tested:


PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64)   Sep 14 2018 13:53:44   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
ah ha! I'm running 6.1.0, it's probably an issue with my ps. thanks for looking into this and fixing the stopwatch issue 💯

![image](https://user-images.githubusercontent.com/8278033/49156578-f849fe00-f31d-11e8-85ec-b6807b6205b9.png)
