### ISSUE TITLE
New-PSSessionOption on Mac

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4656]
````
PS /Users/macbook> Get-DbaClientAlias -ComputerName workstationx -Credential $cred

WARNING: [13:49:34][Get-DbaClientAlias] Failure | The term 'New-PSSessionOption' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS /Users/macbook> 
````

**Comment by nvarscar** [comment]
Wait, is it not in PSCore? Docs suggest that it is: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssessionoption?view=powershell-6

**Comment by Stuart-Moore** [comment]
Doesn't appear to be in 6.1.1 
```
PS /Users/---------> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
6      1      1                      


PS /Users/---------> Gcm | ?{$_.name -like '*Pssession*'}

CommandType     Name                                               Version  
-----------     ----                                               -------    
Cmdlet          Enter-PSSession                                    6.1.1.0    
Cmdlet          Exit-PSSession                                     6.1.1.0    
Cmdlet          Export-PSSession                                   6.1.0.0    
Cmdlet          Get-PSSession                                      6.1.1.0    
Cmdlet          Import-PSSession                                   6.1.0.0    
Cmdlet          New-PSSession                                      6.1.1.0    
Cmdlet          Remove-PSSession                                   6.1.1.0
```

Looks like it should be though - https://github.com/PowerShell/PowerShell/blob/53e6ec6eadc2f363fc671e96b34ade4dda3fe8eb/src/System.Management.Automation/engine/remoting/commands/NewPSSessionOptionCommand.cs

**Comment by wsmelton** [comment]
The command `New-PSSession` does work cross platform but it is a matter of whether we have to change anything to include the SSH protocol. That is all that can be used cross-platform.

https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6

**Comment by potatoqualitee** [comment]
yah no way, i think i put this here so that we could just avoid using it in mac. i may have already addressed it andw ill need to check.

thanks stale bot!

**Comment by dreyTee** [comment]
> The command New-PSSession does work cross platform
On my linux pwsh (v 6.1.2) it does not:
`New-PSSessionOption : The term 'New-PSSessionOption' is not recognized as the name of a cmdlet, function, script file, or operable program.`
Any workaround for now?
