### ISSUE TITLE
Test-DbaPowerPlan review needed

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#466]
- don't accumulate into "$collection"
- do we want System.Collections.ArrayList instead of system.object[] ?

**Comment by niphlod** [comment]
maybe we just log a "don't store results and return always a system.object[]" with a list of affected cmdlets ?

**Comment by ctrlbold** [comment]
with a checklist? I'm down. Can you get that done this release? Otherwise, we also need to discuss how we'll be handling issues. Per command and paste a template or per change?

Did we decide it's always pscustomobject? I think that's something we need to talk about. I'm kinda diggging a DataTable.

**Comment by niphlod** [comment]
Checklist is what I thought too. 

That we don't want to wait the END {} block was set in stone IMHO, and "globally" accepted as a logic way to do things.

What SPECIFICALLY to return I dunno. Guess that's an issue (to discuss while talking about "style") by itself.

**Comment by niphlod** [comment]
OR, we already know that we need to review every command and close this.

**Comment by niphlod** [comment]
closing as we now know what will be addressed when.
