### ISSUE TITLE
Active Directory Integrated Azure auth

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4670]
ahh this is what i wanted in #4437 ! from [microsoft](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/configure-always-encrypted-using-powershell?view=sql-server-2017):

```
# Connect to your database (Azure SQL database).
$serverName = "<Azure SQL server name>.database.windows.net"
$databaseName = "<database name>"
$connStr = "Server = " + $serverName + "; Database = " + $databaseName + "; Authentication = Active Directory Integrated"
$connection = New-Object Microsoft.SqlServer.Management.Common.ServerConnection
$connection.ConnectionString = $connStr
$connection.Connect()
$server = New-Object Microsoft.SqlServer.Management.Smo.Server($connection)
$database = $server.Databases[$databaseName] 
```

We'd add this to `Connect-DbaInstance` somehow and I assume similar approaches can be used for:

![image](https://user-images.githubusercontent.com/8278033/48973715-8ab08000-f046-11e8-8742-f16674ffc7a0.png)

We can add an `Authentication` parameter _and_ also auto detect for `.database.windows.net`

So then `if (-not $Authentication -and Sqlinstance -match database.windows.net)`

**Comment by potatoqualitee** [comment]
also make sure that a user with teeny perms and no access to default db can login

**Comment by potatoqualitee** [comment]
> As you already discovered the DEFAULT_DATABASE option is not available in SQL Azure. So if you cannot change the connection string of your application in which you would normally specify the database name, you are stuck to master.

**Comment by Szeraax** [comment]
Note that if you try to manually change a user's default database from sql via `ALTER LOGIN <username> WITH DEFAULT_DATABASE = <database>`, you'll get the error:

`Msg 40517, Level 16, State 1, Line 1`
`Keyword or statement option 'default_database' is not supported in this version of SQL Server.`

If you really want to still use that user and Invoke-DbaQuery, you can execute on Master db (to create a user with no default schema and no roles):
 `CREATE USER [<username>] FOR LOGIN [<username>]`

**Comment by potatoqualitee** [comment]
detect if database.... then work from there.

> In your client connection logic, override the default timeout to be 30 seconds. The default of 15 seconds is too short for connections that depend on the internet.

**Comment by potatoqualitee** [comment]
some notes for me.. 

sqlserver module & ssms looks like they use winforms for MFA but sqlcmd uses..odbc?

![image](https://user-images.githubusercontent.com/8278033/53895298-0781cb80-4032-11e9-9e61-0d8b7063735e.png)

> SQL Server Management Studio (SSMS) uses the Microsoft .NET Framework SqlClient for execution in regular and SQLCMD mode in Query Editor. When sqlcmd is run from the command-line, sqlcmd uses the ODBC driver. Because different default options may apply, you might see different behavior when you execute the same query in SQL Server Management Studio in SQLCMD Mode and in the sqlcmd utility.

maybe we can too?

**Comment by potatoqualitee** [comment]
hell yeah, this is done, except MFA which who knows how that'll be done. that's for 1.1 or 2.0
