### ISSUE TITLE
Start-DbaAgAgentJob

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4674]
okay, so what if we had a command `Start-DbaAgAgentJob` that would be like

`Get-DbaAgentJob -SqlInstance secondary | Start-DbaAgAgentJob -AvailabiltyGroup ag1`

and it would look for whoever is primary then start it there @wsmelton

**Comment by wsmelton** [comment]
Not sure I see a purpose in it. Right off I have never come across a need to call any job in that fashion....I would still have logic in the step to call it on the proper replica.

**Comment by wsmelton** [comment]
This is generally handled from the job's perspective. Proper practice (at least by Microsoft) is to have a job step check if it's primary or not and then run the code. Not sure if this is actually in a SQL doc article or just folks reference the function you use.
