### ISSUE TITLE
Restore-Database missing a call for KillAllProcesses

### ISSUE THREAD

**Issue by Splaxi** [sqlcollaborative/dbatools#468]
Is this a *feature* OR *bug*:
BUG / Suggestion

- Powershell Version: 3.0
- OS Version: 2012

**Steps to Reproduce**
Using SMO in a project with a customer. Restoring a backup, to replace the database, while relocating the files, failed for me. 
I found that I had to call the KillAllProcesses method on the sqlserver object, and parsing the name of the database that I was about to replace.

**Action Results**

**Expected Results**

**Additional comments**

**Comment by ctrlbold** [comment]
Channel member made a good point, "Calling Server.KillAllProcesses() before performing other operations (rename DB, restore DB, etc.) on a database may not be enough.  If you're working with a highly concurrent application (lot's of current and new connection all the time) then moments before your next operation runs another connection may be opened, and screw the pooch.  Technically, the safe way to do this is to ALTER DATABASE [zzz_Test] SET SINGLE_USER WITH ROLLBACK IMMEDIATE ... <Do other operations> ... ALTER DATABASE [zzz_Test] SET MULTI_USER in the *same* transaction.  That will prevent other connections from sneaking in.  Food for thought."

This may be for a future thing. Perhaps good to integrate into v1.

**Comment by Zhunya** [comment]
I have this routine in my restore script:

        $activeConnections = $DatabaseToBeRestored.ActiveConnections
        if ($activeConnections -gt 0) {
            Handle-Output -Object "$now | Dropping active connection(s) ($activeConnections)." -ForegroundColor "Yellow"
			$srv.KillAllProcesses($restoredDatabase)
        }

**Comment by Stuart-Moore** [comment]
Is this still a bug?

Are we keeping Restore-Database now that Restore-DbaDatabase is in? A quick look and it looks like we could just use this as a wrapper back to the new functionality.

**Comment by niphlod** [comment]
@Stuart-Moore : you're the current boss of "restore-*" . If the new cmdlet hasn't this particular bug,  we can definitely remap the old cmlet to the new one and close this bug for v1.0

**Comment by Stuart-Moore** [comment]
Yep, it's belt and braced in restore-DbFromFiltered

No only do we kill the processes it goes online/offline to ensure we're
clear.

And yes, remapping it so we've only one set to maintain. Tbh, the existing
ones could even just be turned into wrappers to save breaking users current
workflows. Though for v1.0, breaking stuff shouldn't be a concern as it's
more about getting our end right.

**Comment by niphlod** [comment]
perfectly fine even if I feel myself compelled to say that restore-dbadatabase was really fast and the coolness of that mainly was trusting the db files... the new cmdlets are fast but not AS fast as that (or maybe I'm missing something there)

**Comment by Stuart-Moore** [comment]
There's now a trustDbBackupHistory switch which speeds things up a lot.

Takes pipeline from get-dbabackuphistory and then only does file existence
checking rather than header reads.

On Mon, 13 Mar 2017, 16:27 niphlod, <notifications@github.com> wrote:

perfectly fine even if I feel myself compelled to say that
restore-dbadatabase was really fast and the coolness of that mainly was
trusting the db files... the new cmdlets are fast but not AS fast as that
(or maybe I'm missing something there)

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/468#issuecomment-286161503>,
or mute the thread

**Comment by niphlod** [comment]
huh,great! 
That seals definitely the deal when trusting msdb but not on the -maintenancesolution directory and 'lastwritetime' attributes when you restore to a different instance.

**Comment by Stuart-Moore** [comment]
That could be added.

You can use it across instances though:

Get-dbabackuphistory -sqlinstance server1 -databases db1,db2 |
restore-dbadatabase -sqlinstance server2 -trustdbbackuphistory

All it needs is the file locations so doesn't matter if the orirignal
backups were done with ola, maintenance plans or whatever.

**Comment by niphlod** [comment]
yeah, it can be done a few releases down. 
Come to think of it, all it takes is extrapolating the filtering part for the files layed out by OLA and passing them down to your all-type-ingesting cmdlet ^_^

**Comment by potatoqualitee** [comment]
addressed by @Stuart-Moore 

````
internal\Restore-DBFromFilteredArray.ps1:91:                if ($Pscmdlet.ShouldProcess("Killing processes in $dbname on $SqlInstance as it exists and WithReplace specified  `n", "Cannot proceed if processes exist, ", "Database Exists
and WithReplace specified, need to kill processes to restore")) {
internal\Restore-DBFromFilteredArray.ps1:93:                        Write-Message -Level Verbose -Message "Set $DbName single_user to kill processes"
internal\Restore-DBFromFilteredArray.ps1:101:                        Write-Message -Level Verbose -Message "No processes to kill in $DbName"
````
