### ISSUE TITLE
-last not returning the last restored file correctly

### ISSUE THREAD

**Issue by devondba** [sqlcollaborative/dbatools#4688]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

Restore a full and a diff then some logs, when testing for next log to restore using Get-DbaDbRestoreHistory the last restored file isn't always shown. This means the last diff or last log can be restored again and again.

The following change to the T-SQL seems to fix the problem as it returns the max last_lsn
```sql
/*
    bs.last_lsn in  (SELECT max(last_lsn)
									FROM msdb.dbo.restorehistory rsh
									 INNER JOIN msdb.dbo.backupset bs
									 ON rsh.backup_set_id = bs.backup_set_id
									Group By rsh.destination_database_name )
*/
```

```powershell
<#
   $DBsSorted = (Get-DbaDbRestoreHistory -SqlInstance myinstance -Database $DBs -Last | Sort-Object BackupFinishDate -Desc).Database  
#>
```

## Expected Behavior

List of dbs in the order of last restored

## Actual Behavior

list is not in the correct order

## Environmental data

Name                           Value
----                           -----
PSVersion                      5.1.14393.2608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Microsoft SQL Server 2014 (SP2-CU11) (KB4077063) - 12.0.5579.0 (X64)   Feb 21 2018 12:19:47   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by devondba** [comment]
For additional info, when the SQL in the function is run it returns the full list of restored files, as expected, but the order is odd, it's not by LSN so I understand why I'm getting the results I am, hence the tweak to use the highest lsn for the latest restored file.

**Comment by devondba** [comment]
I'm trying to test the changes to the function in my local module but it doesn't seem to load the new function, what do I need to do to force it? I've tried unloading and reloading the module, logging off and one... feeling dumb :D

**Comment by devondba** [comment]
Just a quicky, in the command list on the web site it's still down as Get-DbaRestoreHistory not Get-DbaDbRestoreHistory :)

**Comment by potatoqualitee** [comment]
Thank you! website has been fixed 👍

**Comment by devondba** [comment]
Testing the SQL seems to return the desired results and I've now updated my dbatools module and it works a treat.

I'm wondering weather a combination of the last lsn with the last backup set id could be the way forward.?

More testing needed for performance too, but it seems to do the trick.

**Comment by potatoqualitee** [comment]
Excellent news! I will close the issue  and let stuart or niph respond since they are the smes 💯

**Comment by devondba** [comment]
Thanks Chrissy - There so many cool tools in this module, has to be the the most useful thing I got out of SQLBits, and that's saying something :) I'll read up on how to get a little more involved with the project. Thanks again, Martyn

**Comment by potatoqualitee** [comment]
That means the world to me, @devondba, what an honor. I love SQL Bits. Thank you 🤗

**Comment by devondba** [comment]
Hi Guys

Think this one needs to be reopened I'm afraid. 

`Get-DbaDbRestoreHistory -SqlInstance $SqlInstance -Database $Database -last`

Returns 

BackupFinishDate : 03/03/2020 07:01:45
ComputerName     : 
Database         : 
Date             : 03/03/2020 12:52:37
From             : \\\SQLBackups\\Diff\_DIFF_20200303_070123.bak
InstanceName     : MSSQLSERVER
RestoreType      : Differential
...

`Get-DbaDbRestoreHistory -SqlInstance $SqlInstance -Database $Database -since (Get-Date).AddDays(-1)`

...
Username         : username

BackupFinishDate : 03/03/2020 07:21:01
ComputerName     : computer
Database         : db
Date             : 03/03/2020 13:22:03
From             : B:\SQLBackups\inst\db\LOG\db_20200303072101.trn
InstanceName     : MSSQLSERVER
RestoreType      : Log
SqlInstance      : computer
To               : D:\SQLLogs\db_Primary.ldf
Username         : username

BackupFinishDate : 03/03/2020 07:22:02
ComputerName     : computer
Database         : db
Date             : 03/03/2020 13:22:11
From             : B:\SQLBackups\inst\db\LOG\db_20200303072201.trn
InstanceName     : MSSQLSERVER
RestoreType      : Log
SqlInstance      : computer
To               : D:\SQLLogs\db_Primary.ldf
Username         : username

but to spin it a bit more, if we look at the last 7 days then the diff comes out last in the list, which is odd as it was restored today :D

`Get-DbaDbRestoreHistory -SqlInstance $SqlInstance -Database $Database -since (Get-Date).AddDays(-7) `

...
SqlInstance      : inst
To               : D:\SQLLogs\db_Primary.ldf
Username         : user

BackupFinishDate : 03/03/2020 07:22:02
ComputerName     : inst
Database         : db
Date             : 03/03/2020 13:22:11
From             : B:\SQLBackups\isnt\db\LOG\db_20200303072201.trn
InstanceName     : MSSQLSERVER
RestoreType      : Log
SqlInstance      : inst
To               : D:\SQLLogs\db_Primary.ldf
Username         : user

BackupFinishDate : 03/03/2020 07:01:45
ComputerName     : inst
Database         : db
Date             : 03/03/2020 12:52:37
From             : \\inst\SQLBackups\isnt\db\Diff\isnt_db_DIFF_20200303_070123.bak
InstanceName     : MSSQLSERVER
RestoreType      : Differential
SqlInstance      : inst
To               : D:\SQLData\db_Primary.mdf, D:\SQLData\db2.ndf, D:\SQLLogs\db_Primary.ldf
Username         : user


for now, to get the latest, I'm using:

`Get-DbaDbRestoreHistory -SqlInstance $SqlInstance -Database $Database -since (Get-Date).AddDays(-7) | Sort-Object Date | Select -Last 1 #-Last`

which gives me the correct results :)

I'll have a look at the function once I've finished what I'm doing ;)

**Comment by wsmelton** [comment]
Please open a new issue.
