### ISSUE TITLE
Restore-DbaDatabase - No errors thrown with (mostly) bogus parameters

### ISSUE THREAD

**Issue by Beagle41** [sqlcollaborative/dbatools#4692]
### Before submitting a bug report:

- [ x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x ] Verified this bug is not already reported in an issue
- [x ] Verified errors are not related to permissions (If only I could get an error)
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
Restore-DbaDatabase -Path C:\Temp\bogus.dat -SqlInstance <good instance name> -SqlCredential $nonExistentCredential  -DatabaseName bogusDatabaseName -WithReplace
#>
```

## Environmental data

 -- PowerShell: 

 - - SQL Server:

**Comment by potatoqualitee** [comment]
I'm getting an error but it's nasty red and should be caught with pretty yellow.

![image](https://user-images.githubusercontent.com/8278033/49107718-c3d73300-f286-11e8-83ad-b43497f6414f.png)

**Comment by Beagle41** [comment]
FWIW, if I use a bogus (nonexistent) SQL Instance, I _do_ get an error.

**Comment by potatoqualitee** [comment]
thank much for the update! I'll open another issue requesting the fix for the red.
