### ISSUE TITLE
Copy-DbaServerAudit / Add FilePath parameter

### ISSUE THREAD

**Issue by rysalah** [sqlcollaborative/dbatools#4699]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature
Add parameter to specify a new file path for the audit files on the target server

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.

**Comment by rysalah** [comment]
Already Done ?!! Thx :)

**Comment by potatoqualitee** [comment]
in the gallery now 👍 it's `-Path`
