### ISSUE TITLE
Export output should be standardized

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4704]
some go to current dir by default, some go to docs

**Comment by alevyinroc** [comment]
What is the desired default output directory? Even among the functions that export to My Documents, there are different methods of determining the path. Example:

* `$home\Documents` in `Export-DbaDacPackage`
* `[Environment]::GetFolderPath("mydocuments")` in `Export-DbaDiagnosticQuery`

**Comment by potatoqualitee** [comment]
mmm i love that idea, @alevyinroc thank you

**Comment by alevyinroc** [comment]
I'm going to create a DbatoolsConfig setting called `Path.Export` and default it to `[Environment]::GetFolderPath("MyDocuments") \dbatools`.

`Export-*` will be updated to grab this config and (where currently appending subdirectories) `Join-DbaPath` the subdirectory name for the paths used to export.

**Comment by potatoqualitee** [comment]
love love love, thank you

**Comment by potatoqualitee** [comment]
hey @alevyinroc - any progress on this front? do you think you can have it done within one month for the prerelease? 🙏

**Comment by alevyinroc** [comment]
@potatoqualitee it'll be done this week

**Comment by potatoqualitee** [comment]
yessssss ty!

**Comment by alevyinroc** [comment]
My changes are in https://github.com/alevyinroc/dbatools/tree/StandardExportDir-4704 but I don't think I'm ready for a PR just yet.

Superficially...everything is standardized on what was discussed above. However, some of the functions assume you're passing in a directory, others assume a file. We should probably ask the user to only pass in a directory and then we'll cook up a filename `Export-DbaCmsRegServer.ps1` line 102 for example)

I'm going to sleep on this, discuss in Slack on Wednesday

**Comment by potatoqualitee** [comment]
We could _potentially_ do Path or FilePath. These appear to be the two PowerShell standards for Directory and File. But if we have to do just one, let's pick Path and PR to prerelease.

**Comment by wsmelton** [comment]
Andy you can do a draft PR so it is easier for code reviews.
