### ISSUE TITLE
Missing server parameter in Set-DbaAgentJobStep

### ISSUE THREAD

**Issue by sanderstad** [sqlcollaborative/dbatools#4715]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Expected Behavior
The server property needs to be set when using sub systems in the job steps like 'AnalysisCommand'. 

The New-DbaAgentJobStep is already fixed for this particular issue. 
https://github.com/sqlcollaborative/dbatools/pull/4714

**Comment by potatoqualitee** [comment]
ohh sander can you take a look? 😅
