### ISSUE TITLE
Merge MajorVersion and Version in Update-DbaInstance

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#4727]
---
name: Merge MajorVersion and Version in Update-DbaInstance
about: QoL improvement

---

### Summary of new feature

There is no reason to keep two identical parameters with different names in different paramSets. Merge them together so that ppl could use
`Update-DbaInstance -Version 2008` to only update SQL 2008.

**Comment by potatoqualitee** [comment]
hey one moment, im about to update dev
