### ISSUE TITLE
Rename Job to AgentJob

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4735]
To Get/Set-DbaAgentJobOwner

**Comment by ijeb** [comment]
Set-DbaJobOwner -> Set-DbaAgentJobOwner
Test-DbaJobOwner -> Test-DbaAgentJobOwner
Get-DbaJobOwner -- Does not exist - use Get-DbaAgentJob
Get-DbaRunningJob -- Not sure, could be Get-DbaRunningAgentJob, Get-DbaAgentJobRunning, or no change. Get-DbaAgentJobRunning would be easy to find.
