### ISSUE TITLE
odd behavior with backup/restore and Copy-SqlDatabase

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#474]
Is this a *feature* OR *bug*:
Bug
- Powershell Version: 5.0.10586.117
- OS Version: Windows 7

**Steps to Reproduce**
Run Copy-SqlDatabase from SQL 2012 box to a SQL 2016 box with BaclupRestore option
I have a database that causes the issue I can upload somewhere. (65MB)

**Action Results**
After database is backed up then restored SQL 2016 as the destination engine stops

**Expected Results**
Restore works after restore

**Additional comments**
I have a backup that crashes taken by DBATools and I have a backup taken via TSQL that does not crash.  Initially thought it was because of compat level 90 to SQL 2016, but I change source to 110 and still does not work.  I then thought it was due to the db owner not being a login on the destination server so I migrated logins and still same result, then changed to sa on source and after backup restore it still fails.  I can backup with TSQL and restore with TSQL and no issues occur.

**Comment by wsmelton** [comment]
Please do provide the database when you can. As well if you can edit your issue and include the exact command you used.

I just migrated the pubs sample database from 2012 to 2016 on my local instance and had no issues.

**Comment by ctrlbold** [comment]
Hey @gbargsley can you please provide the dbatools exception file? 2016 to 2016 works well. I've done it 100 times and can't replicate your issue.

We use copy-only backups. Can you try backing up and restoring with that? Also, try specifying -NoBackupCleanup then restoring the backup it created.

**Comment by wsmelton** [comment]
@gbargsley are you able to provide any more detail on this issue (e.g. database or requested info above)?
