### ISSUE TITLE
Copy-Dbadatabase -BackupRestore -SharedPath using other path at restore

### ISSUE THREAD

**Issue by AGregersen** [sqlcollaborative/dbatools#4744]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
Copy-DbaDatabase -Source mysourcesql -Destination mydestinationsql -Database mydatabase  -BackupRestore -SharedPath \\myserver\mybackupshare
```

## Expected Behavior

No errors

## Actual Behavior

WARNING: [08:55:54][New-DbaDirectory] Failure | xp_create_subdir() returned error 3, 'The system cannot find the path
specified.'
WARNING: [08:55:54][Copy-DbaDatabase] Failure attempting to restore mydatabase to mydestinationsql |
System.Data.SqlClient.SqlError: Cannot open backup device '\\myserver\Backup\my_deploy\mydatabase.bak'. Operating
system error 2(The system cannot find the file specified.).

To clarify it have worked with other databases, just not this one. It seems like it's getting a path from where the destination usually backup to.

## Environmental data

 - PowerShell: 
 PSVersion                      5.1.14393.2608
 PSEdition                      Desktop
 PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
 BuildVersion                   10.0.14393.2608
 CLRVersion                     4.0.30319.42000
 WSManStackVersion              3.0
 PSRemotingProtocolVersion      2.3
 SerializationVersion           1.1.0.1
 - SQL Server: 
Microsoft SQL Server 2012 (SP3-CU10-GDR) (KB4057121) - 11.0.6615.2 (X64) 
Jan  9 2018 21:26:48 Copyright (c) Microsoft Corporation Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
@AGregersen - thank you for the report, what version of dbatools are you currently using?

**Comment by AGregersen** [comment]
Hi Chrissy

Should be the latest – I updated before trying the last time, but both 0.9.704 and 0.9.519 are listed when I do the get-module dbatools -Listavailable

So it might not have been using the latest version – since I didn’t remove the older version and didn’t close the active powershell session.

And it’s amazing work you and the others are doing on this – didn’t know about it before the powershell conference earlier this year.

Cheers,
Anders

Fra: Chrissy LeMaire <notifications@github.com>
Sendt: 3. december 2018 10:57
Til: sqlcollaborative/dbatools <dbatools@noreply.github.com>
Cc: Anders Gregersen <agr@ida.dk>; Mention <mention@noreply.github.com>
Emne: Re: [sqlcollaborative/dbatools] Copy-Dbadatabase -BackupRestore -SharedPath using other path at restore (#4744)


@AGregersen<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAGregersen&data=02%7C01%7C%7Cf40b82cffe1b48a16f3e08d65905b21f%7C140275f52c6b45899efcebd77efa60aa%7C0%7C0%7C636794278328531824&sdata=jgX5Fit%2FHjZrESxmZ41KH0aVxdeNHGYjXKvEVTgAZo8%3D&reserved=0> - thank you for the report, what version of dbatools are you currently using?

**Comment by potatoqualitee** [comment]
K, that works thank you. Is it possible to run the migration again with `-Verbose` and pasting the sanitized output here? Is it repeatable every time? I've seen this issue in the past but thought we addressed it in the backup history.

**Comment by potatoqualitee** [comment]
and happy you found the tools! psconf.eu is the best 💃 we'll be there again next year

**Comment by AGregersen** [comment]
Hi Chrissy

I’m unable to run it again – the target database is in use and may not be overwritten (again).

It was repeatable every time (ignored Einstein and tried it 3 times) with the same error every time. It’s much like when you have added a backup device on a db and want to backup to a different location using SQL Management Studio.

I’m going to do it again the 16th on our primary servers and I’ll use the -verbose just in case

Fra: Chrissy LeMaire <notifications@github.com>
Sendt: 3. december 2018 11:06
Til: sqlcollaborative/dbatools <dbatools@noreply.github.com>
Cc: Anders Gregersen <agr@ida.dk>; Mention <mention@noreply.github.com>
Emne: Re: [sqlcollaborative/dbatools] Copy-Dbadatabase -BackupRestore -SharedPath using other path at restore (#4744)


K, that works thank you. Is it possible to run the migration again with -Verbose and pasting the sanitized output here? Is it repeatable every time? I've seen this issue in the past but thought we addressed it in the backup history.

**Comment by potatoqualitee** [comment]
thank you, i look forward to the verbose output 👍
