### ISSUE TITLE
Restore-DbaDatabase allows red errors

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4763]
![image](https://user-images.githubusercontent.com/8278033/49434005-8ce7ac80-f7b3-11e8-9407-34eb5894baa9.png)

**Comment by Stuart-Moore** [comment]
There’s a couple of others as well I found while poking around

Working on them, but getting some strange errors which I think is my test env being out of sync with GitHub. Need to find time to rebuild it

**Comment by devondba** [comment]
Just found this one:


The property 'PhysicalName' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.532\allcommands.ps1:22964 char:25
+ ...             $_.PhysicalName = $RestoreDir + $PathSep + $DatabaseFileP ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
WARNING: [11:40:48][Select-DbaBackupInformation] Fullname property not found. This could mean that a full backup could not be found or the command must be re-run with the -Continue switch.

**Comment by Stuart-Moore** [comment]
@devondba what did you run to produce that?

**Comment by devondba** [comment]
Hey @Stuart-Moore I'm afraid I can't recall off hand, sorry at the time I thought the error would be enough, do appologise. I'll try and have a bash at repeating it this afternoon.

**Comment by Stuart-Moore** [comment]
No problems.

I have a suspicion the fix will catch that one as well, but just want to make sure.


On 21 December 2018 at 14:19:48, devondba (notifications@github.com) wrote:

Hey @Stuart-Moore I'm afraid I can't recall off hand, sorry at the time I thought the error would be enough, do appologise. I'll try and have a bash at repeating it this afternoon.

**Comment by potatoqualitee** [comment]
Thanks so much for addressing this stuart!
