### ISSUE TITLE
Start-DbaMigration attempts to set db owner before copying logins

### ISSUE THREAD

**Issue by 1DontEx1st** [sqlcollaborative/dbatools#4764]
If all of my servers followed best practices, this probably wouldn't have been an issue, but the process was unable to set the db owner because it didn't yet exist. I can see that a fix to this might cause problems with a login's default DB, so maybe it's something that can't be fixed?

**Comment by potatoqualitee** [comment]
also check to make sure it's not doing this outside of whatif

**Comment by potatoqualitee** [comment]
the update owner code comes after the login code. either this was fixed or something's up.

![image](https://user-images.githubusercontent.com/8278033/54852931-94917980-4cee-11e9-9f15-c55aacbb7c06.png)
