### ISSUE TITLE
Get-DBAPowerPlan fails if PowerShell is not running as Admin

### ISSUE THREAD

**Issue by sql-williamd** [sqlcollaborative/dbatools#4777]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

Open PowerShell console in non-Admin mode and run the command
```powershell
  Get-DBAPowerPlan -ComputerName $MyMachine 
```

## Expected Behavior

Give me a warning that elevated permissions are needed

## Actual Behavior

A "timeout" occurs when different protocols are attempted, then it fails with the following message

```
WARNING: [00:21:47][Get-DbaPowerPlan] Can't get Power Plan Info for $MyMachine. Check logs for more details. | Multiple 
protocol connections were attempted, but no successful connections could be established with the specified computer.
```
## Environmental data

 - PowerShell: 
````
Name                           Value                                                                                      
----                           -----                                                                                      
PSVersion                      5.1.17763.134                                                                              
PSEdition                      Desktop                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                    
BuildVersion                   10.0.17763.134                                                                             
CLRVersion                     4.0.30319.42000                                                                            
WSManStackVersion              3.0                                                                                        
PSRemotingProtocolVersion      2.3                                                                                        
SerializationVersion           1.1.0.1
````

**Comment by sql-williamd** [comment]
I can get it to run on my machine when running PowerShell as administrator, non-elevated sessions fail.

This is on my laptop, I have full permissions locally

**Comment by joeywas** [comment]
I was able to reproduce this by running Get-DbaPowerPlan on a local non-admin powershell session, targetting my local computer. I'll test it against remote computers later today.

**Comment by joeywas** [comment]
Running Get-DbaPowerPlan on a local non-admin PowerShell session against a remote computer works without any issues.

Running against localhost:

PS C:\windows\system32> Get-DbaPowerPlan localhost
WARNING: [12:09:14][Get-DbaPowerPlan] Can't get Power Plan Info for localhost. Check logs for more details. | Multiple
protocol connections were attempted, but no successful connections could be established with the specified computer.
PS C:\windows\system32>

DbaTools version 0.9.710

**Comment by joeywas** [comment]
Something about permissions should probably be added to Get-DbaCmObject, which is called from Get-DbaPowerPlan. I started looking at it, but it's a bit over my head. The Get-DbaCmObject author @FriedrichWeinmann may have a suggestion on how to add permissions check that returns appropriate message.
