### ISSUE TITLE
Get-DbaDbFile should accept pipeline from Get-DbaDatabase

### ISSUE THREAD

**Issue by joeywas** [sqlcollaborative/dbatools#4783]
---
name: Get-DbaDbFile should accept pipeline from Get-DbaDatabase :bomb:
about: Get-DbaDbFile should accept pipeline from Get-DbaDatabase

---

### Summary of new feature

* We want pipeline goodness for all! Part of that is making sure Get-DbaDbFile can accept pipeline input from Get-DbaDatabase

### Proposed technical details (if applicable)

* Properties that Get-DbaDbFile would snag from the pipeline would be sqlinstance and database

### Latest version of dbatools as of writing

* 0.9.710

**Comment by Adam-Wenger** [comment]
Closing - #4788 merged this into 0.9.715
