### ISSUE TITLE
Install-DbaFirstResponderKit fails to install when run as a build or RM agent.

### ISSUE THREAD

**Issue by cool1two** [sqlcollaborative/dbatools#4800]
### Before submitting a bug report:

- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## What is the issue
shell.application should not be used, and when it is run as part of a headless agent or chef, it will not complete. I have attached changes that have been tested to work.
http://www.codewrecks.com/blog/index.php/2016/05/27/avoid-using-shell-command-in-powershell-scipts/

## Steps to Reproduce
```powershell
$s = New-PSSession LOCALHOST
Invoke-Command -Session $s -ScriptBlock {Start-Job -Name cmd1 -ScriptBlock {Install-DbaFirstResponderKit -SqlServer (hostname) -Database master}}
$done = Invoke-Command -Session $s -Command {Wait-Job -Name cmd1 -Timeout 60}
Write-Host $done.Count
```

## Expected Behavior

```sql
select count(*)
  from master.information_schema.routines 
 where routine_type = 'PROCEDURE'
 and Routine_Name like 'sp_bl%'
--------------------------------------
(No column name)
9
```
## Actual Behavior
```sql

select count(*)
  from master.information_schema.routines 
 where routine_type = 'PROCEDURE'
 and Routine_Name like 'sp_bl%'
--------------------------------------
(No column name)
0
```

## Environmental data

 - PowerShell: 
PSVersion                      5.1.14393.2608                                                                                                                    
PSEdition                      Desktop                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                           
BuildVersion                   10.0.14393.2608                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                   
WSManStackVersion              3.0                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                               
SerializationVersion           1.1.0.1    

 - SQL Server: 
Microsoft SQL Server 2016 (SP2-GDR) (KB4293802) - 13.0.5081.1 (X64)   Jul 20 2018 22:12:40   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

[Install-DbaFirstResponderKit.ps1.txt](https://github.com/sqlcollaborative/dbatools/files/2669075/Install-DbaFirstResponderKit.ps1.txt)

**Comment by niphlod** [comment]
thanks for the report. Note to self: add "shell" to things to avoid in dbatools.Tests.ps1, so this never happens again for any other module

**Comment by potatoqualitee** [comment]
did this get fixed, @niphlod ? I'm not finding `shell.application` in this command, however, I have found it in others

````
functions\Install-DbaSqlWatch.ps1:160:                $shell = New-Object -ComObject Shell.Application
functions\Install-DbaWhoIsActive.ps1:147:                    $shell = New-Object -ComObject Shell.Application
install.ps1:128:$shell = New-Object -ComObject Shell.Application
````

**Comment by potatoqualitee** [comment]
Looks like with the above two, however, the shell is only used as a failback when `Expand-Archive` does not exist

**Comment by niphlod** [comment]
I didn't do anything (still). Problem is the report is quite correct: not every place PS can run has access to Shell.Application so it should be avoided, even as a fallback. We DO have Expand-Archive and Compress-Archive in optional/functions so the fallback doesn't make sense.

**Comment by cool1two** [comment]
- Add-Type -assembly "system.io.compression.filesystem" is available on WMF 3.0 and above (Powershell V3).
- Expand-Archive is available on WMF 5.0 and above (Powershell V5).
I would suggest where Expand-Archive is the fallback and Shell.Application is the default, switching to the .Net "system.io.compression.filesystem" as the default.

Thank you for looking at my suggestion.

**Comment by wsmelton** [comment]
@potatoqualitee we include the code for `Expand-Archive` and recall the import process at one point would import those commands.

https://github.com/sqlcollaborative/dbatools/tree/development/optional

**Comment by potatoqualitee** [comment]
yeah, sorry this will not be on my radar, but anyone else is open to taking it.
