### ISSUE TITLE
UseLastBackup should imply BackupRestore

### ISSUE THREAD

**Issue by 1DontEx1st** [sqlcollaborative/dbatools#4809]
Experienced behavior: invoking Start-DbaMigration with -UseLastBackup but no -BackupRestore threw an error that I needed to specify -BackupRestore or -DetachAttach.

Expected behavior: invoking Start-DbaMigration with -UseLastBackup implies -BackupRestore (since it doesn't make sense with -DetachAttach).

**Comment by potatoqualitee** [comment]
good point, i  like it
