### ISSUE TITLE
dedicated dac shell

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4810]
basically connect using dac as seen in decrypt object and make it interactive?

**Comment by wsmelton** [comment]
Interactive?

**Comment by potatoqualitee** [comment]
Yeah I guess it wouldn't be interactive, we'd just create a `$server` object using something like `Connect-DbaDacInstance`? Then the person just keeps reusing it?

**Comment by andreasjordan** [comment]
Or just having a new switch `-DAC` for Connect-DbaInstance?
Or just be able to use `$dacServer = Connect-DbaInstance -SqlInstance 'ADMIN:SRV1'`?

**Comment by andreasjordan** [comment]
But we already #6831 ... (maybe close this as duplicate?)

**Comment by potatoqualitee** [comment]
good call!
