### ISSUE TITLE
Removing messages

### ISSUE THREAD

**Issue by mljohn11** [sqlcollaborative/dbatools#4815]
Ok, I am leveraging the DBATools to do centralize some server maintenance.  I took the Export-DBALogin, and commented out the various Write-Message lines.  
I am a complete newbie to PS, but here goes.  
Why do the messages still appear?  Do the modules need to be re-compiled??

**Comment by wsmelton** [comment]
You cannot simply edit the individual function files in the module when you are using the module from the PowerShell Gallery. The import process uses a file called `allcommands.zip` file to import all functions (internal and public). This is a single text file with over 90k lines of code.

To leverage your own customizations of the commands it would be best to clone the master branch of this repository, and then perform the changes you want. You can import the psd1 file and that will ensure all the changes you made exist in your session for the module.

If you need more information just let us know and reopen this issue.

**Comment by mljohn11** [comment]
Thank you.


We actually figured it out.  A co-worker put the pieces together.



Michael John
1019 Glen Oak Drive
Bethel Park, PA 15102
412-452-0585
