### ISSUE TITLE
Set-DbaSpn - error in documentation?

### ISSUE THREAD

**Issue by Gutgolf** [sqlcollaborative/dbatools#4819]
Hi team,

it seems that there is a tiny error in the documentation for Set-DbaSpn.

On https://docs.dbatools.io/#Set-DbaSpn it sais:

PS C:\> Set-DbaSpn -SPN MSSQLSvc\SQLSERVERA.domain.something -ServiceAccount domain\account

but it should be:

PS C:\> Set-DbaSpn -SPN MSSQLSvc/SQLSERVERA.domain.something -ServiceAccount domain\account

notice that the backslash after MSSQLSvc is now a "/".

Otherwise you get the following error in Power Shell:

WARNING: [09:06:22][Set-DbaSpn] Could not add SPN. Exception calling "CommitChanges" with "0"
argument(s): "A constraint violation occurred."

Maybe you can correct the documentation for this command

Kind Regards

**Comment by potatoqualitee** [comment]
Thanks for the report! I'll take a look today.
