### ISSUE TITLE
Copy-DbaSsisCatalog returns error about assembly not being loaded

### ISSUE THREAD

**Issue by HansVanEylen** [sqlcollaborative/dbatools#4821]
### Before submitting a bug report:

- [x ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ x] Verified this bug is not already reported in an issue
- [ x] Verified errors are not related to permissions
- [x ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
<#
    Copy-DbaSsisCatalog -Source sourceserver -Destination destinationserver
#>
```

## Expected Behavior

actual copy of the catalog folders, projects and environments

## Actual Behavior

WARNING: [14:52:41][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:41][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:41][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:41][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:41][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:41][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:41][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:42][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:42][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:42][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:42][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:42][Copy-DbaSsisCatalog] Issue creating folder | Cannot find type [.CatalogFolder]: verify that the
assembly containing this type is loaded.
WARNING: [14:52:42][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:42][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:42][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:42][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:43][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:43][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:43][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:43][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:44][Invoke-PrjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:44][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:44][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:44][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:44][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:44][Invoke-ProjectDeployment] Failed to deploy project. | You cannot call a method on a null-valued
expression.
WARNING: [14:52:44][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:44][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:44][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:44][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:44][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:45][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:45][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:45][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:45][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:45][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:45][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:45][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:46][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:46][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:46][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.
WARNING: [14:52:46][Copy-DbaSsisCatalog] Issue deploying environment | Cannot find type [.EnvironmentInfo]: verify that
the assembly containing this type is loaded.

## Environmental data

 - PowerShell: Name                           Value

----                           -----

PSVersion                      5.1.14393.2125
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2125
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - - SQL Server: 
Source server : Microsoft SQL Server 2012 (SP3-CU10-GDR) (KB4057121) - 11.0.6615.2 (X64)   Jan  9 2018 21:26:48   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)
Target server : Microsoft SQL Server 2012 (SP3-CU10-GDR) (KB4057121) - 11.0.6615.2 (X64)
                Jan  9 2018 21:26:48
                Copyright (c) Microsoft Corporation
                Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
thank you for the report!

**Comment by blinneric** [comment]
I'm having the same issue.

**Comment by gephartr** [comment]
As a workaround, add the following line to your powershell script prior to calling Copy-DbaSsisCatalog:

$ISNamespace = "Microsoft.SqlServer.Management.IntegrationServices"

**Comment by gephartr** [comment]
That is all I added to get it to work.  Looking at the code for the function it is calling "$ISNamespace.CreateFolder" and the error is '.CreateFolder' - so the issue is that $ISNamespace hasn't been set for this function.

**Comment by potatoqualitee** [comment]
that'd be awesome if that is the fix! ill take a look in a bit
