### ISSUE TITLE
get-dbasdtc  

### ISSUE THREAD

**Issue by RangaSQL** [sqlcollaborative/dbatools#4822]
PS C:\dbatools> Get-DbaMsdtc -ComputerName xyz
Method invocation failed because [Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter] does not contain a method named 'split'.
At C:\dbatools\allcommands.ps1:38730 char:57
+         $ComputerName = $ComputerName | ForEach-Object {$_.split("\")[0]} | Sele ...
+                                                         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by potatoqualitee** [comment]
Thanks for the report! I'll take a look at this today.

**Comment by RangaSQL** [comment]
Thanks...but I got the latest and it it fixed now...

Sorry for the trouble.

Cheers
Ranga

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by potatoqualitee** [comment]
excellent, glad it's fixed!
