### ISSUE TITLE
Set-DBADBCompression Not Compressing All Tables Recommended for Compression

### ISSUE THREAD

**Issue by lmarkum** [sqlcollaborative/dbatools#4823]
## Steps to Reproduce

```sql
/*
SELECT 
SCHEMA_NAME(sys.objects.schema_id) AS [SchemaName] 
,OBJECT_NAME(sys.objects.object_id) AS [ObjectName] 
,[rows] 
,[data_compression_desc] 
,[index_id] as [IndexID_on_Table]

FROM sys.partitions 
INNER JOIN sys.objects ON sys.partitions.object_id = sys.objects.object_id 
WHERE data_compression > 0 
AND SCHEMA_NAME(sys.objects.schema_id) <> 'SYS' 
ORDER BY SchemaName, ObjectName
*/
```

```powershell
<#
   Get-Date | Out-File -FilePath C:\Users\LMarkum\Desktop\AdvWorks_CompressionResults_12-14-18.txt

$Results = Test-DbaDbCompression -SQLInstance LMarkum\SQL2017 -Database Adventureworks2017 | WHERE {$_.CompressionTypeRecommendation -NotLike "?" -AND $_.CompressionTypeRecommendation -NotLike "NO_GAIN" } | Out-File C:\Users\LMarkum\Desktop\AdvWorks_CompressionResults_12-14-18.txt -Append

Set-DBADBCompression -SqlInstance LMarkum\SQL2017 -Database AdventureWorks2017 -InputObject $Results

Get-Date | Out-File -FilePath C:\Users\LMarkum\Desktop\AdvWorks_CompressionResults_12-14-18.txt -Append
#>
```

## Expected Behavior
The output of Test-DBADBCompression shows that this index, among others should be compressed. 
ComputerName                  : LMARKUM
InstanceName                  : SQL2017
SqlInstance                   : LMARKUM\SQL2017
Database                      : AdventureWorks2017
Schema                        : Person
TableName                     : BusinessEntityContact
IndexName                     : PK_BusinessEntityContact_BusinessEntityID_PersonID_ContactTypeID
Partition                     : 1
IndexID                       : 1
IndexType                     : CLUSTERED
PercentScan                   : 
PercentUpdate                 : 
RowEstimatePercentOriginal    : 92
PageEstimatePercentOriginal   : 92
CompressionTypeRecommendation : ROW
SizeCurrent                   : 64.00 KB
SizeRequested                 : 56.00 KB
PercentCompression            : 12.50
## Actual Behavior

When I run the above provided T-SQL to see what tables were compressed, I get no rows back.

## Environmental data

 - PowerShell: <! PSVersion 5.1.17134.407, PSEdition Desktop, PSCompatibleVersions 1,2,3,4, BuildVersion 10.0.17134.407, CLR Version 4.0.30319.4200, WSManStackVersion 3.0, PSRemotingProtocolVersion 2.3, Serializationversion 1.1.0.1 >
 - - SQL Server: <! Original problem occurred on Microsoft SQL Server 2008 (SP3) - 10.0.5500.0 (X64)   Sep 21 2011 22:45:45   Copyright (c) 1988-2008 Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (VM) .  I tested on  Microsoft SQL Server 2017 (RTM-CU9-GDR) (KB4293805) - 14.0.3035.2 (X64)   Jul  6 2018 18:24:36   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 17134: )  and had the same issue.>

**Comment by potatoqualitee** [comment]
Thanks for the report! We'll look into it shortly.

**Comment by jpomfret** [comment]
I'll take a look this weekend

**Comment by jpomfret** [comment]
Hey @lmarkum, I'm unable to reproduce. I think this line might be the problem, you are piping to `Out-File` so there is nothing in `$Results`. Can you check your `$Results` param and see if there is anything in it before you pass it into `Set-DbaDbCompression`.

```
$Results = Test-DbaDbCompression -SQLInstance LMarkum\SQL2017 -Database Adventureworks2017 |
WHERE {$_.CompressionTypeRecommendation -NotLike "?" -AND $_.CompressionTypeRecommendation -NotLike "NO_GAIN" } | 
Out-File C:\Users\LMarkum\Desktop\AdvWorks_CompressionResults_12-14-18.txt -Append
```

I ran the following and then checked the compression and it looks ok.
```
$res = Test-DbaDbCompression -SqlInstance $svr -Database adventureworks2017 | 
WHERE {$_.CompressionTypeRecommendation -NotLike "?" -AND $_.CompressionTypeRecommendation -NotLike "NO_GAIN" }

Set-DbaDbCompression -SqlInstance $svr -Database AdventureWorks2017 -InputObject $res -Verbose
```

Let me know what you think.

**Comment by potatoqualitee** [comment]
thanks Jess! will close as unable to repro

**Comment by lmarkum** [comment]
My apologies, I didn't see any notification about this issue from a couple of weeks ago, but I did see the notification about it being closed.  

Some of the data is compressed, as shown in the data in the file produced by out-file. So, $Results isn't empty.  I want to be able to output what the command does and in my case it isn't compressing everything, I'll look at this more closely when I get back to work on 1/2.

**Comment by jpomfret** [comment]
Sounds good @lmarkum, let me know what you find out.
