### ISSUE TITLE
Install-dbaSQLwatch Installation Errors....

### ISSUE THREAD

**Issue by RSiglin** [sqlcollaborative/dbatools#4830]
Not sure what this trying to tell me.  I’ve verified the UserID/Password for several accounts including Local SQL account with Sysadmin permissions.  Also tried an account which is a member of the servers local Admin Group.      
ComputerName : VAAACSQL84
InstanceName : MSSQLSERVER
SqlInstance  : VAAACSQL84
Database     : SQLWATCH
Status       : (Failed)

**Comment by potatoqualitee** [comment]
@koglerk can you take a look? i'm sure you'll need more information but I'm not sure how to gather more from Publish-DbaDacpac /cc @RichieBzzzt

**Comment by jpomfret** [comment]
Anyone know if this is only a problem on certain SQL versions? Ran out of time but seems to install fine on SQL 2016 but getting an error on 2017 instance?

**Comment by RichieBzzzt** [comment]
Hello @jpomfret / @RSiglin !

Do you have any error messages or logs from the failed deployment? Were you using a specific release or grabbing the latest one? Was this on anything funky like containers? 

FWIW Ive tried on my local machine that has SQL Server 2017 RTM and it works no issues, but would like to help as dacpac failures are my specialty ;-)

I've downloaded the source code and see that sqlwatch targets SQL Server 2008. This means that I should deploy to later versions (kinda like .net really), so I wonder if there is something random that may cause a failed deployment to a certain version SQL Server 2017. All conjecture ATM.

**Comment by potatoqualitee** [comment]
@RSiglin - please feel free to reopen with more info, gotta close for now since there's no info to go on. @RichieBzzzt - is there any way to get additional info about that failure? im thinking no since it's coming from sqlpackage.exe

**Comment by RichieBzzzt** [comment]
No I shouldn't think that there'd be any more info to get out. Not even sure if all info was provided in OP.
