### ISSUE TITLE
Copy-DbaCredential: Problem with named instance + Name of credential

### ISSUE THREAD

**Issue by fr4g3r666** [sqlcollaborative/dbatools#4833]
I have a problem with the command Copy-DbaCredential.
I'm able to call the command when I issue it against the default instance or when I specify the name of the server and the port of the instance, but it doesn't work to specify the named instance directly.

Works:
localhost:50235

Doesn't work:
localhost/MYINSTANCE

In addition to that, I have a credential with a name similar to this:
[REPL][Domain\User][Somthing\Some-thing]

Running the command against the instance with that credential I get the following error:
You cannot call a method on a null-valued expression.

**Comment by alevyinroc** [comment]
@fr4g3r666 can you reproduce this when using `localhost\MYINSTANCE`? The separator between server and instance name is the backslash (`\`). I can reproduce the error when using the regular slash with this and other functions, but that's not the appropriate character for referencing a named instance.

**Comment by potatoqualitee** [comment]
Cannot repro and more info needed. If you continue to have this issue, please fill out the bug report template entirely including the command you used.

![image](https://user-images.githubusercontent.com/8278033/54549030-769fde00-49a9-11e9-9735-02e374d4909f.png)
