### ISSUE TITLE
Resolve-DbaNetworName is not working properly in PS6.0+

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#4840]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
$t = Resolve-DbaNetworName -ComputerName computer -Verbose
```
![image](https://user-images.githubusercontent.com/30303784/50170855-7e6eba00-02b6-11e9-8d1f-935d847a2058.png)

![image](https://user-images.githubusercontent.com/30303784/50170974-bb3ab100-02b6-11e9-9207-f31fe11630fb.png)

## Expected Behavior
Normal mode with CIM/PSRemoting hostname verifications.
No extra output.

## Actual Behavior
Turbo mode (due to different parameter set in PS6.0 version of Test-Connection).
Ping results show up on the screen.

## Environmental data

 - PowerShell:
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by nvarscar** [comment]
Also, according to search, Test-Connection is used in multiple places. Might be worth replacing with `[System.Net.NetworkInformation.Ping]::new().Send($computer)`

![image](https://user-images.githubusercontent.com/30303784/50173059-099e7e80-02bc-11e9-86e6-4995f76c0acb.png)

**Comment by potatoqualitee** [comment]
go for it
