### ISSUE TITLE
Get-DbaBackupHistory fork check not firing automatically, and sub optimal default choice

### ISSUE THREAD

**Issue by Stuart-Moore** [sqlcollaborative/dbatools#4841]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Expected Behavior

Whenever `Get-DbaBackupHistory` is run against an instance with multiple recovery fork's history it should warn that this is the case

Should pick up the most recent recovery fork as that's what most people are expecting it to do

## Actual Behavior

Doesn't always fire

returns the last by lsn

## Notes

People should really clean up their backup history every now and then ;)

**Comment by joeywas** [comment]
Can affirm this is happening in 0.9.72.0.

Get-DbaBackupHistory -last is not returning last backups by date, which is what I expected. Maybe parameters for LastByLSN and LastByDate?

**Comment by Stuart-Moore** [comment]
With this fix or without without?

There’s parameters for [datetime]Since and [bigint]LastLsn that do that already btw


On 18 December 2018 at 22:58:46, Joseph (notifications@github.com) wrote:

Can affirm this is happening in 0.9.72.0.

Get-DbaBackupHistory -last is not returning last backups by date, which is what I expected. Maybe parameters for LastByLSN and LastByDate?
