### ISSUE TITLE
Add-DbaAgReplica does not add replica

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#4847]
I created a new AG with New-DbaAvailabilityGroup and all worked great.  I wanted to add a replica do that AG and the code runs, but does not add.

![image](https://user-images.githubusercontent.com/169602/50223081-cdbcf500-035f-11e9-834f-673d5ab7bc2b.png)

**Comment by wsmelton** [comment]
Are there any errors on the secondary or primary replica when you attempt to add it?

**Comment by gbargsley** [comment]
No errors reported. It appears to work but nothing is changed with the Ag.
