### ISSUE TITLE
[Proposal] Formally drop support for PS 3 (and PS 4 as a bonus)

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#4877]
## Proposal
Formally dropping terms and text that we support older versions of PowerShell and are only supporting PowerShell 5.1 and PS Core moving forward **after** 1.0 release.

I think once we have accomplished 1.0 that it will be a good milestone to move to the next level for this module and making it even better from all aspects of just functionality and performance. I think the first step in doing this will be dropping our restrictions for contributors around support for older versions of PowerShell.

Now this does not mean that 1.1 will not work on older versions of PS, it could be 2.0 before we have changed enough that it won't even import on PS 3.0. It is just a matter of method of providing ample warning for users is that after 1.0 we no longer will intentionally support anything lower than Windows PowerShell 5.1 and PS Core 6.1.

## Reasoning

It is time to get with the times and not allow our user base to stay in an environment that is no longer recommended by Microsoft. Microsoft came out in 2018 that you need to be running Windows PowerShell 5.1 on your environment for security. We need to stop going against that recommendation and work towards fully support and utilizing features in Windows PowerShell 5.1.

### PowerShell 3.0

PowerShell 3.0 came baked into Window Server 2008 and 2008 R2, which is an OS that officially on January 14, 2020 will be out of support. I consider Window Server 2008 to be in the same boat as Window Server 2003.

### PowerShell 4.0 - 5.0

Any OS that can run PS 4 or 5.0 can run 5.1 and should be updated as such based on security recommendations by Microsoft. There is no reason users should not be running on the last release of Windows PowerShell for Windows Server, and desktops.

## Edge Cases

In situations where we have a user base that still needs support for PS3 or even PS4/5.0 for some reason they will simply be locked into using `dbatools 1.0`. The main bank of commands utilized for dbatools I think by now are solid and cover multiple environments. Any new feature(s), command(s) or enhancement(s) will be made available in new releases but will require upgrade of PowerShell. Any release(s) after 1.0 may or may not work with PS5.0 or below but we should no longer guarantee fixing it for the older versions.

**Comment by potatoqualitee** [comment]
Hello,
thank you for the discussion topic but I don't want to abandon fellow DBAs for things out of their control. That may be us one day. And the syntax is easy enough to support.

**Comment by wsmelton** [comment]
How are we abandoning fellow DBAs?

**Comment by potatoqualitee** [comment]
The ones that are forced for whatever reason/policy are required to use PS 3/can't update to 5. Same goes for sql 2005 and to a lesser degree 2000.

**Comment by wsmelton** [comment]
Understood. However the command we have right now provide a base of support for them in those versions.

Majority of the latest command that have been added don't even support those versions of SQL Server.

There is a difference between saying we are going to remove all support and previous versions. I'm simply saying right now we are adding command around features in SQL Server that those in older OS and SQL versions can't even utilize.

**Comment by wsmelton** [comment]
Why would we be writing commands sound SQL Server 2019 and try to support the command running on an OS that can't even run the version of SQL.

**Comment by wsmelton** [comment]
I don't think y'all are seeing the user story I'm taking about here so I'll just let it go.

**Comment by potatoqualitee** [comment]
Just to clarify, supporting 2019+ is certainly on the agenda. We'll keep our SMOs updated, but our syntax backwards compat. And we'll handle "This doesnt' work on this old version of SQL Server" but using the `-MinimumVersion`
