### ISSUE TITLE
Possible bug in Import-DbaCsvToSql/Import-DbaCsv with double quote char

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#4880]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
Import-DbaCsvToSql -SqlInstance SRV1 -Database DB1 -Table tblFin -Delimiter ';' -Path E:\CVSFiles\1.csv
```
```txt
field1;field2;field3
abbcc;bbccdd;"ccddee
```

## Expected Behavior

Imports CSV file w/o errors
## Actual Behavior

WARNING: [xx:xx:xx][Import-DbaCsv] Failure | The CSV appears to be corrupt near record '498663' field '3 at position '0'. Current raw data : 'N'.

Actually, that line contains a single double quote character `"`.

**Comment by potatoqualitee** [comment]
hey oleg,
right off, that seems like malformed data to me and the parser but! I just added TrimmingOption to the branch in PR #4881 - try that and see if it helps

**Comment by potatoqualitee** [comment]
K i got it working with another option

`gci E:\csv\zh.csv | Import-DbaCsv -SqlInstance sql2017 -Database tempdb -AutoCreateTable -Delimiter ';' -Quote $null`

This will be available in the next release, due out today 👍🎄

**Comment by Zhunya** [comment]
Thank you so much!!!
