### ISSUE TITLE
Copy-DbaDbTableData -Query is not working in (v 0.9.733) version

### ISSUE THREAD

**Issue by AndulRehman1982** [sqlcollaborative/dbatools#4888]
Copy-DbaDbTableData -Query is not working in (v 0.9.733) version

**Comment by potatoqualitee** [comment]
thanks, andul! what does not working mean? can you please paste the command you are running?

**Comment by AndulRehman1982** [comment]
Dear Chrissy, thanks a lot for prompt reply. below is the command for copying the data. i will appreciate if you can make video about copying the data using queries and tables. and is there any possibility we create table automatically while using -Query while copying the table data.

## Command i am trying to copy   

Copy-DbaDbTableData -SqlInstance inst01 -Destination inst02 -Database test1 -DestinationDatabase test2 -DestinationTable '[test2].[dbo].[test]' `
-Truncate -Query "select top(100000) * from [test1].[dbo].[ReportData]" -BatchSize 1000 

Regards,
Abdul Rehman

**Comment by AndulRehman1982** [comment]
Dear Shawn,

Many thanks for the reply. i will test this and will update you.

once again bundle of thanks 😊

Regards,
Abdul Rehman

________________________________

**Comment by AndulRehman1982** [comment]
I am closing this issue.

Regards,
Abdul Rehman
