### ISSUE TITLE
v0.9.732 Invoke-SQLCMD2 Credentials parameter missing

### ISSUE THREAD

**Issue by skattie22** [sqlcollaborative/dbatools#4889]
Hi
It appears that Invoke-SQLCmd2 has been replaced by Invoke-DBAQuery
But seeing at Invoke-SQLCmd2 still exists, why oh why did the -Credential parameter get removed?
and on calling Invoke-SQLCmd2 it does not state that it is deprecated...?

**Comment by wsmelton** [comment]
`Invoke-DbaQuery` does not replace `Invoke-Sqlcmd2`. `Invoke-Sqlcmd2` is a function added to dbatools module out of convenience, and is maintained by a different individual. (We simply host it under [sqlcollaborative\invoke-sqlcmd2](https://github.com/sqlcollaborative/Invoke-SqlCmd2))

The `-Credential` parameter was not removed.

It is not being deprecated.

**Comment by skattie22** [comment]
Thanks Shawn, I don't understand why the 2 commands below are so different?
0.9.501
`Invoke-Sqlcmd2 [-ServerInstance] <String[]> [[-Database] <String>] [-Query] <String> 
    [[-Credential] <PSCredential>] [[-Encrypt]] [[-QueryTimeout] <Int32>] 
    [[-ConnectionTimeout] <Int32>] [[-As] <String>] [[-SqlParameters] <IDictionary>] 
    [[-AppendServerInstance]] [[-ParseGO]] `[<CommonParameters>]`

0.9.732
`Invoke-Sqlcmd2 [-ServerInstance] <String> [-Database] <String> [[-Query] <String>] 
    [[-CommandType] {Text | StoredProcedure | TableDirect}] [[-CommandParameters] <Array>] 
    [[-Username] <String>] [[-Password] <String>] [[-QueryTimeout] <Int32>] 
    [[-ConnectionTimeout] <Int32>] [[-InputFile] <String>] [[-As] <String>] 
    [[-CallingFunction] <String>] [[-ApplicationName] <String>] [[-ReturnStream]] 
    [<CommonParameters>]`

**Comment by potatoqualitee** [comment]
thx shawn you are right, Credential is aliased so would still work. skattie the commands are different because invoke-dbaquery adheres to our toolset conventions and has more goodies baked in 👍

**Comment by skattie22** [comment]
Thanks Chrissy, but I am comparing 2 versions of Invoke-Sqlcmd2, forget invoke-dbaquery, the 2 commands above are very different...or am I missing something?

**Comment by wsmelton** [comment]
I can't answer what the state of the command was in previous versions. Someone may have got a change in but it apparently was reverted in a later release. The 501 release was from beginning of Nov and we release a handle of times every week.

Overall the end result will be that `Invoke-Sqlcmd2` is going to be removed and no longer exist in the module. `Invoke-DbaQuery` is a new command that conforms to our standard and performs similiar (if not more) functionality. You will want to use this going forward.

If you happen to just desire to keep using Sqlcmd2 you can pull it from the [GitHub repository](https://github.com/sqlcollaborative/Invoke-SqlCmd2).
