### ISSUE TITLE
Install-DbaFirstResponderKit  SqlCredential parameter not working

### ISSUE THREAD

**Issue by goforebroke** [sqlcollaborative/dbatools#4891]
### Before submitting a bug report:

- [ x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ x] Verified this bug is not already reported in an issue
- [ x] Verified errors are not related to permissions
- [ x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

Open a powershell prompt

run the dbatools command Install-DbaFirstResponderKit and pass in a credential (windows account) that is different from the account running the powershell session.

The command successfully downloads the "FirstResponderKit", but attempts to authenticate to the sql instance with the windows account that opened the powershell session instead of the credential that is passed to the command.

```powershell
<#
    Install-DbaFirstResponderKit -SqlInstance "Server1\Instance1" -Database DBA -SqlCredential (Get-Credential) -Force
#>
```

## Expected Behavior

To authenticate to the sql instance with the specified credential

## Actual Behavior

Authentication is done with the account that is running the powershell session.

## Environmental data

 - PowerShell: 

```
PSVersion                      5.1.14393.2636
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2636
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by wsmelton** [comment]
@goforebroke just to verify can you try to use just the following command and see if it repeats the same issue?

```powershell
Connect-DbaInstance -SqlInstance "Server1\Instance1" -SqlCredential (Get-Credential)
```

**Comment by goforebroke** [comment]
@wsmelton I was able to connect and retrieve the list of properties from the instance. The issue only occurs with the DBAFirstResponderKit command.
