### ISSUE TITLE
Unable to set a ConnectionTimeout on Invoke-DbaQuery

### ISSUE THREAD

**Issue by Szeraax** [sqlcollaborative/dbatools#4900]
### Before submitting a bug report:

- [√] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [√] Verified this bug is not already reported in an issue
- [√] Verified errors are not related to permissions
- [√] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
PS > Invoke-DbaQuery -ConnectionTimeout 15 ...

```

## Actual Behavior

`Invoke-DbaQuery : A parameter cannot be found that matches parameter name 'ConnectionTimeout'.`

## Environmental data

 - PowerShell: 5.1

## Other thoughts

Looks like `Connect-SqlInstance` is what gets called by `Invoke-DbaQuery `and already has a `StatementTimeout` param that may work. 

As noted: for advanced connection options, you can use `Set-DbatoolsConfig`  or create the reusable connection with `Connect-DbaInstance`

I would expect ConnectionTimeout to be common enough that it exposed on `Invoke-DbaQuery`

**Comment by potatoqualitee** [comment]
thank you for the report! 🙇  This will be better handled by 

`Get-DbatoolsConfig *connect*`
`Set-DbatoolsConfig -FullName sql.connection.timeout -Value 30`

![image](https://user-images.githubusercontent.com/8278033/50659138-f1a54b00-0f9b-11e9-9805-99b3f8041e0d.png)

doing it this way is similar to the way it's done in SSMS

![image](https://user-images.githubusercontent.com/8278033/50659158-0386ee00-0f9c-11e9-80f5-90371a094bfb.png)

👍
