### ISSUE TITLE
Backup-DbaDatabase support for taking copy only backup from a non-readable secondary 

### ISSUE THREAD

**Issue by mqunbar** [sqlcollaborative/dbatools#4906]
Support taking a copy only backup from a non-readable secondary instance of a db in an always on availability group.

**Comment by wsmelton** [comment]
@mqunbar how are you not able to do this now?

Something like this should work:

```powershell
$params = @{
    SqlInstance = SecondaryReplica
    Database = YourAgDb
    BackupDirectory = "\\SomeNetworkShare\Backups\YourAgDb\"
    CreateFolder = $true
    Type = Full
    Initialize = $true
    CopyOnly = $true
    CompressBackup = $true
}
Backup-DbaDatabase @params
```

**Comment by mqunbar** [comment]
@wsmelton Here's the error when I try the above method:

[Backup-DbaDatabase] Backup Failed | The target database, '***', is participating in an availability group and is currently not accessible for queries. Either data movement
 is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online



However, if I use invoke-sqlcmd; I can get it to work successfully here:
Invoke-Sqlcmd -ServerInstance *** -Query "BACKUP DATABASE [$DB] TO  DISK = N'\\path\$DB.bak' WITH  COPY_ONLY, NOFORMAT, NOINIT,  NAME = N'$DB-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10;"

**Comment by mqunbar** [comment]
This works too: 

    $Server = connect-dbainstance -sqlinstance ***
    $Sql = "BACKUP DATABASE [***] TO  DISK = N'\\***\***.bak' WITH  COPY_ONLY, NOFORMAT, NOINIT,  NAME = N'***-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10;"
    $Server.Query($sql)

**Comment by Stuart-Moore** [comment]
Yep, sounds like a good option to have


On 9 January 2019 at 21:40:32, Shawn Melton (notifications@github.com) wrote:

This should be fairly easy to fix, just need to find out what line(s) in that backup command are trying to actually access the database. We may just have to put in some alternative logic if we detect it is a AG replica.

// @Stuart-Moore and/or @potatoqualitee are you ok with supporting this option?

**Comment by mqunbar** [comment]
@wsmelton 

$error[0] | select *


writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: The target database, 'xxx', is participating in an availability group and is currently not accessible for queries. Either data movement is 
                        suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read 
                        access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online. 
                        ---> System.Data.SqlClient.SqlException: The target database, 'xxx', is participating in an availability group and is currently not accessible for queries. Either 
                        data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability 
                        group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL 
                        Server Books Online.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Backup-DbaDatabase,Stop-Function
ErrorDetails          : The target database, 'xxx', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the 
                        availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or 
                        more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, <No file>: line 104661
                        at Backup-DbaDatabase<Process>, <No file>: line 2816
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

**Comment by mqunbar** [comment]
@wsmelton For my own curiosity could you explain where you track the error to? I opened the source code for the backup-dbadatabase function but the code doesn't run to line 2816. Just wondering what step I am missing.

Thanks!

**Comment by andreasjordan** [comment]
Just tried that in the current version and it works.
@mqunbar : Can you please try and tell us if it works for you?

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
