### ISSUE TITLE
Errors with Copy-DbaLogin -SyncOnly

### ISSUE THREAD

**Issue by pasqualeceglie** [sqlcollaborative/dbatools#4909]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
Create a SQL Server Agent Job with 1 step with a Powershell command with the command
`C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe  -Command "Copy-DbaLogin -Source sqlserversource -Destination sqlserverdest -SyncOnly -ExcludeLogin myreservedlogin -EnableException -Verbose"`

## Expected Behavior
Would sync login permissions, server role, database mapping, ...

## Actual Behavior
After lots of login synced correctly apprear the below error

> 
The job script encountered the following errors. These errors did not stop the script:
A job step received an error at line 1 in a PowerShell script. The corresponding line is 'C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe  -Command "Copy-DbaLogin -Source sourceinstance -Destination destinstance -SyncOnly -ExcludeLogin myreservedlogin -EnableException -verbose"'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'Exception calling "EnumServerPermissions" with "1" argument(s): "There is 
'
A job step received an error at line 1 in a PowerShell script. The corresponding line is 'C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe  -Command "Copy-DbaLogin -Source sourceinstance -Destination destinstance -SyncOnly -ExcludeLogin myreservedlogin -EnableException -verbose"'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'already an open DataReader associated with this Command which must be closed 
first."
At line:114615 char:9
+         $perms = $SourceServer.EnumServerPermissions($userName)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

'
A job step received an error at line 1 in a PowerShell script. The corresponding line is 'C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe  -Command "Copy-DbaLogin -Source sourceinstance -Destination destinstance -SyncOnly -ExcludeLogin myreservedlogin -EnableException -verbose"'. Correct the script and reschedule the job. The error information returned by PowerShell is: '    + FullyQualifiedErrorId : InvalidOperationException

'
A job step received an error at line 1 in a PowerShell script. The corresponding line is 'C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe  -Command "Copy-DbaLogin -Source sourceinstance -Destination destinstance -SyncOnly -ExcludeLogin myreservedlogin -EnableException -verbose"'. Correct the script and reschedule the job. The error information returned by PowerShell is: ' 

'
A job step received an error at line 1 in a PowerShell script. The corresponding line is 'C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe  -Command "Copy-DbaLogin -Source sourceinstance -Destination destinstance -SyncOnly -ExcludeLogin myreservedlogin -EnableException -verbose"'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'Exception calling "EnumDatabasePermissions" with "1" argument(s): "There is 

'
A job step received an error at line 1 in a PowerShell script. The corresponding line is 'C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe  -Command "Copy-DbaLogin -Source sourceinstance -Destination destinstance -SyncOnly -ExcludeLogin myreservedlogin -EnableException -verbose"'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'already an open DataReader associated with this Command which must be closed 

'
A job step received an error at line 1 in a PowerShell script. The corresponding line is 'C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe  -Command "Copy-DbaLogin -Source sourceinstance -Destination destinstance -SyncOnly -ExcludeLogin myreservedlogin -EnableException -verbose"'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'first."

## Environmental data

 - PowerShell: 
 - - SQL Server:

**Comment by wsmelton** [comment]
You will need to capture the full errors in this situation as what is provided does not provide enough information to go on. The first message you receive likely has more details on what the true error would be that is causing the failure.

Can you run this process interactively under the account running the job via SQL Agent, using the verbose flag?

**Comment by potatoqualitee** [comment]
Thank you, Shawn. I've chatted with Pasquale about the issue and believe it is because he is using a PowerShell Job step. I always avoid the ps job step because of issues like this. I 've asked him to  reapproach with cmdexec and a script as outlined here dbatools.io/agent and if he continues to run into issues, run your commands until he hits the issue again (it's inconsistent for him as well)

**Comment by pasqualeceglie** [comment]
**Tested with a credential, proxy as described in [https://dbatools.io/agent/]
and below the error description**

WARNING: [12:52:13][Update-SqlPermission] Failed to change job owner for
JobExample1 - usrTest on destinstance. | You cannot call a method on a
null-valued expression.

_Why "Copy-DbaLogin -SyncOnly" try to change jobowner?
and above all, some lines after I find this error:_

You cannot call a method on a null-valued
expression.
Exception calling "EnumServerPermissions" with "1" argument(s): "Internal
connection fatal error."
At line:114615 char:9
\+         $perms = $SourceServer.EnumServerPermissions($userName)
\+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
\+ FullyQualifiedErrorId : InvalidOperationException

Exception calling "EnumDatabasePermissions" with "1" argument(s): "There is
already an open DataReader associated with this Command which must be closed
first."
**and the following one:**
You cannot call a method on a null-valued expression.
Exception calling "EnumServerPermissions" with "1" argument(s): "There is
already an open DataReader associated with this Command which must be closed
first."
At line:114615 char:9
\+         $perms = $SourceServer.EnumServerPermissions($userName)
\+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
\+ FullyQualifiedErrorId : InvalidOperationException

Exception calling "EnumDatabaseMappings" with "0" argument(s): "Enumerate
database mappings failed for Login 'usrTest'. "

At the and of execution **usrTest** login doesn't exist on the destination instance

**Comment by potatoqualitee** [comment]
Can you confirm that you are able to repro in an interactive console? ie. by running powershell.exe and executing it there?

**Comment by potatoqualitee** [comment]
I'm hoping the answer is yes 😓

**Comment by pasqualeceglie** [comment]
Unfortunately no :-(

**Comment by potatoqualitee** [comment]
noooooooooo that's so much harder :( can you repro in another version of SQL Server Agent?

**Comment by potatoqualitee** [comment]
That is useful, thank you 👍 Not sure how to fix it yet tho

**Comment by pasqualeceglie** [comment]
But in my test environment with different instances no error occours. In prod still have errors also in ISE console.

**Comment by wsmelton** [comment]
These are between two AG replicas correct? This was noted in slack.

The agent job is running on your primary and you are trying to sync to the secondary replicas?

**Comment by pasqualeceglie** [comment]
@wsmelton, correct.

**Comment by wsmelton** [comment]
Take a look at using `Sync-DbaAvailabilityGroup` instead of the copy command. Docs page is [here](https://docs.dbatools.io/#Sync-DbaAvailabilityGroup).

**Comment by wsmelton** [comment]
And just note that PowerShell ISE will perform differently than PowerShell.exe in many ways. You may use the ISE to edit and develop, but to ensure your scripts run as expected it is best to keep with PowerShell.exe as this is how they will be executed via scheduled task, and using CmdExec steps in SQL Agent.

**Comment by wsmelton** [comment]
One example I know of on ISE is around dates it can display a date in one format in the ISE and another in PowerShell.exe: https://superuser.com/q/913259/94184

**Comment by potatoqualitee** [comment]
he was able to repro with cmdexec in sql agent which i dont get. @pasqualeceglie any chance you can update your powershell on the server causing issues? it appears this may be a server-specific bug

**Comment by pasqualeceglie** [comment]
Can the presence of orphaned users trigger these kinds of problems?

**Comment by potatoqualitee** [comment]
can you try updating your powershell, @pasqualeceglie ? since it's limited to one server, I am not sure I'll have the time to invest and would like to know if updating powershell solves the problem

**Comment by potatoqualitee** [comment]
I'm going to remove -SyncOnly from dbatools 1.0, so will add this as a breaking change. but that siltl means that Sync-DbaLoginPermission may need some loving.
