### ISSUE TITLE
Copy-DbaDatabase -Source $Database.FromServer -Destination $Database.ToServer -Database $Database.workspace -DetachAttach -Reattach

### ISSUE THREAD

**Issue by lgfritz** [sqlcollaborative/dbatools#4912]
Running the Copy-DbaDatabase with -DetachAttach -Reattach for two database(s) only, and I getting the following error message. I have already tried refreshing DBAtools. It works if I using the backup restore option.

What can I do to fix this issues.

WARNING: SQLPS or SqlServer was previously imported during this session. If you encounter weird issues with dbatools, please restart PowerShell, then import dbatools without loading SQLPS or SqlServer first.
WARNING: To disable this message, type: Set-DbatoolsConfig -Name Import.SqlpsCheck -Value $false -PassThru | Register-DbatoolsConfig
WARNING: [14:14:24][Copy-DbaDatabase] Console not elevated, but elevation is required to perform some actions on localhost for this command.
WARNING: [14:14:24][Copy-DbaDatabase] Console not elevated, but elevation is required to perform some actions on localhost for this command.

**Comment by potatoqualitee** [comment]
Sorry, we do not support sessions that have SQLPS or SqlServer loaded - it causes weird bugs. Please follow the instructions displayed by the warnings and reopen the issue if you continue to encounter issues.
