### ISSUE TITLE
Import-DbaXESessionTemplate cannot set startup state of XE session to on

### ISSUE THREAD

**Issue by ijeb** [sqlcollaborative/dbatools#4916]
### Summary of new feature

With some extended events sessions, like database_health, the startup state should normally be set to on. Otherwise the session won't start automatically after a restart.
Import-DbaXESessionTemplate cannot set this property.

### Proposed technical details (if applicable)

I can think of two solutions:
* Add a parameter StartUpState (ON or OFF) to Import-DbaXESessionTemplate.
* Add a property StartUpState to xetemplates-metadata.xml.

Or a combination of both.

Apply the state to the session after it's created according to the template.

### Latest version of dbatools as of writing

Current developer branch

**Comment by andreasjordan** [comment]
Yes, maybe it's time for a new command `Set-DbaXESession`.

But you can do it like this:
```
$xeSession = Get-DbaXESession -SqlInstance $server -Session AlwaysOn_health
if (-not $xeSession.AutoStart) {
    $xeSession.AutoStart = $true
    $xeSession.Alter()
}
```

**Comment by potatoqualitee** [comment]
> Add a parameter StartUpState (ON or OFF) to Import-DbaXESessionTemplate

I like the opt-in ease and safety of this, I'll create this now, to include updating the help
