### ISSUE TITLE
Scripts with parameters does not get the parameter value when called using Invoke-DbaSqlQuery

### ISSUE THREAD

**Issue by bootrider** [sqlcollaborative/dbatools#4918]
## Steps to Reproduce
SQL script defined to be used with parameters, in this case the parameters are NewUser and Sufix, this script is used with sqlcmd
```sql
DECLARE @dbUser nvarchar(128)
DECLARE @dbSufix nvarchar(128)  
DECLARE @Command nvarchar(2000)
SET @dbUser = '$(NewUser)'
SET @dbSufix = '$(Sufix)'
PRINT @dbSufix
```

```powershell
Invoke-DbaSqlQuery -File .\myscript.sql -SqlInstance MyDb -MessagesToOutput -SqlParameters @{ Sufix = "Maria" }
```

## Expected Behavior
It is expected the output with the value "Maria" in the console

## Actual Behavior

in the console is just printed:
$(Sufix)

## Environmental data

 - PowerShell: Name                           Value                                                                                                                              
----                           -----                                                                                                                              
PSVersion                      5.1.16299.785                                                                                                                      
PSEdition                      Desktop                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                            
BuildVersion                   10.0.16299.785                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                    
WSManStackVersion              3.0                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                
SerializationVersion           1.1.0.1    
 - - SQL Server: Microsoft SQL Server 2012 (SP3) (KB3072779) - 11.0.6020.0 (X64) 
	Oct 20 2015 15:36:27 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

**Comment by niphlod** [comment]
This is not the way parameter works, see the examples section, as in 

```
Invoke-DbaQuery -SqlInstance . -Query 'SELECT * FROM users WHERE Givenname = @name' -SqlParameters @{ Name = "Maria" }
```

**Comment by bootrider** [comment]
So..... scripts intended to be run with sqlcmd can not be used with this tool, with out a migration process

**Comment by niphlod** [comment]
No, and in fact we even changed the name even if most of the code comes
from invoke-sqlcmd2 for the exact reason that it's different from sqlcmd
and invoke-sqlcmd, which is shipped with sqlps

Il giorno mar 8 gen 2019, 17:20 Cristian Andres <notifications@github.com>
ha scritto:
