### ISSUE TITLE
Copy-DbaAgentAlert does not validate that operator exist

### ISSUE THREAD

**Issue by danglade** [sqlcollaborative/dbatools#4920]
There is no checking when adding notifications to an alert if the operator exists at destination. This will skip the alert transfer?

**Comment by wsmelton** [comment]
Logic should be added that if the operator does not exists on the destination instance the alert is to be skipped and output object updated as such.

**Comment by alevyinroc** [comment]
@mikepetrak I did some work toward this as well yesterday, haven't been able to test yet so I didn't log a PR yet. Do you want to take a look? https://github.com/alevyinroc/dbatools/commit/8a8a8daa32cca2140071b09aef63abd6db5122e2

**Comment by mikepetrak** [comment]
Sorry, @alevyinroc , I didn't see that. I scanned your commit and tested it and it looks good to me. Two of the automated tests for my commit failed, so if you log a PR and it passes that sounds good to me.

Describe : Copy-DbaAgentAlert Integration Tests
Context  : 
Name     : It Error occurred in Describe block
Result   : Failed
Message  : Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. ""

Describe : dbatools style
Context  : formatting
Name     : It Copy-DbaAgentAlert.ps1 is adopting OTSB formatting style. Please run Invoke-DbatoolsFormatter against the failing file and commit the changes.
Result   : Failed
Message  : Expected 0, but got 1.

**Comment by wsmelton** [comment]
@alevyinroc doing a compare object call over each iteration of the alerts found on an instance would degrade performance a good bit on servers that use alerts heavily.
