### ISSUE TITLE
Unit Test Context "Validate parameters" Compare Count for single matches not working

### ISSUE THREAD

**Issue by falkheiland** [sqlcollaborative/dbatools#4925]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

```powershell
((Compare-Object -ReferenceObject $knownParameters -DifferenceObject $params -IncludeEqual | Where-Object SideIndicator -eq "==").Count) | Should Be $knownParameters.Count
```

## Expected Behavior

.Count: if only one parameter exists the it should get cast as an array.

## Actual Behavior

.Count: if only one parameter exists it doesn't get cast as an array.

## Workaround

```powershell
(@(Compare-Object -ReferenceObject $knownParameters -DifferenceObject $params -IncludeEqual | Where-Object SideIndicator -eq "==").Count) | Should Be $knownParameters.Count
```

**Comment by potatoqualitee** [comment]
ah ha! thank you. @jpomfret would you be able to take a look at this? 🙇

**Comment by jpomfret** [comment]
So I took the workaround suggested and it worked well.

I did find an issue though where the current unit test was not failing if you added an extra parameter to the function so I rewrote that and submitted pr #4961. 

Let me know what you think, if you're happy with this I'll start changing the other functions to use this new improved (hopefully) unit test.

**Comment by potatoqualitee** [comment]
this looks fab, thank you @jpomfret !
