### ISSUE TITLE
Errors with Copy-DbaLogin -SyncOnly

### ISSUE THREAD

**Issue by pasqualeceglie** [sqlcollaborative/dbatools#4926]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
I have a source SQL instance with 142 windows logins. I need to sync that in another destination instance. Some of this logins are sysadmin or serveradmin, and owns Agent Job.
Sometimes the execution ends with no errors but sometimes logins are not synced on destination instance. In some cases login already exists on destination instance but are dropped (even if I've not used -Force parameter).
 
Steps in described in []https://dbatools.io/agent/
1. create a credential
2. create a proxy
3. create a job with 2 CmdExec steps:
    **step1: create missing logins on destination instance**
`PowerShell.exe  -Command "Copy-DbaLogin -Source sourceInstance -Destination destInstance  -ExcludeSystemLogins -ExcludeLogin reservedLogin -Verbose"`
    **step2: sync permissions**
`PowerShell.exe  -Command "Copy-DbaLogin -Source sourceInstance  -Destination destInstance  -SyncOnly -ExcludeLogin reservedLogin  -Verbose"`

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
    Provide exact (or sanitized) code to reproduce the error
#>
```

## Actual Behavior

WARNING: [12:52:13][Update-SqlPermission] Failed to change job owner for
JobExample1 - usrTest on destinstance. | You cannot call a method on a
null-valued expression.

_Why "Copy-DbaLogin -SyncOnly" try to change jobowner?
and above all, some lines after I find this error:_

You cannot call a method on a null-valued
expression.
Exception calling "EnumServerPermissions" with "1" argument(s): "Internal
connection fatal error."
At line:114615 char:9
\+         $perms = $SourceServer.EnumServerPermissions($userName)
\+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
\+ FullyQualifiedErrorId : InvalidOperationException

Exception calling "EnumDatabasePermissions" with "1" argument(s): "There is
already an open DataReader associated with this Command which must be closed
first."
**and the following one:**
You cannot call a method on a null-valued expression.
Exception calling "EnumServerPermissions" with "1" argument(s): "There is
already an open DataReader associated with this Command which must be closed
first."
At line:114615 char:9
\+         $perms = $SourceServer.EnumServerPermissions($userName)
\+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
\+ FullyQualifiedErrorId : InvalidOperationException

Exception calling "EnumDatabaseMappings" with "0" argument(s): "Enumerate
database mappings failed for Login 'usrTest'. "

At the and of execution **usrTest** login doesn't exist on the destination instance

## Environmental data

 - PowerShell: 
 - - SQL Server:

**Comment by potatoqualitee** [comment]
> Why "Copy-DbaLogin -SyncOnly" try to change jobowner?

Unsure, tho it seems like something reasonable to sync.

Thank you, i reopened the other one so will close this one.
