### ISSUE TITLE
ConvertTo-DbaDataTable is not converting all data (Out-DbaDataTable is)

### ISSUE THREAD

**Issue by wabby80** [sqlcollaborative/dbatools#4938]
```powershell
<#
param (
    $Instances      = ('xxxxx','xxxxxx','xxxxxx')
 )

[System.Reflection.Assembly]::LoadWithPartialName('Microsoft.SqlServer.SMO') | out-null 

$Results = @()

foreach($instance in $Instances){
    $srv = new-object ('Microsoft.SqlServer.Management.Smo.Server') $instance  

    $Q = "SELECT @@SERVERNAME AS Instance,
	Name AS DatabaseName,
	Compatibility_level,
	Collation_name,
	State_desc,
	Snapshot_isolation_state_desc,
	Is_read_committed_snapshot_on,
	Recovery_model_desc,
	Page_verify_option_desc,
	Is_trustworthy_on,
	Is_auto_shrink_on 
    FROM sys.databases 
    WHERE 1=1
    and Database_id > 4
    "

    $srv = new-Object Microsoft.SqlServer.Management.Smo.Server($instance)
    $db = New-Object Microsoft.SqlServer.Management.Smo.Database
    $db = $srv.Databases.Item('master')
        
    $result = $db.ExecuteWithResults($Q)

    if($result.Tables.Instance.Count -gt 0){
        $Results += $result.Tables
    }
}

$dtable = $Results|ConvertTo-DbaDataTable #Run this on Last version
$dtable = $Results|Out-DbaDataTable #Run this on 0.8.957 

#>
```

## Expected Behavior

All data that is in $Results to be converted and piped into $dtable

## Actual Behavior

With ConvertTo, only the first(!) server is piped over. Even thou $Results got more data.

## Environmental data

PSVersion   5.1.14393.2636
SQL 2017 CU 12

**Comment by wabby80** [comment]
I notice that 
$results.Count returns 3 
and it looks like ConvertTo only handles the dataset in pos [0], while Out- handled all dataset in the array.

**Comment by wabby80** [comment]
Workaround is to rename the out-DBADataTable to ConvertTo-DBADataTable and wrap it in a foreach. 

Question is if ConvertTo-DBADatatable is working as intended or if this is a bug.

**Comment by potatoqualitee** [comment]
this is useful, thanks @wabby80 !

**Comment by dbaduck** [comment]
This function either has to assume that the 2 tables being passed in are of the same definition or it will be far more complex to reconcile the objects.  It is true that as written today, the first of the 2 DataTables are put in the resultant Table that is output.  This could be overcome if there is a guarantee that the definitions are the same. 

The question is before anyone changes the code for this function, is whether or not this function is meant to combine tables together by pipelining 2 tables into this function.

**Comment by ClaudioESSilva** [comment]
After talking with @potatoqualitee , we think that 2 different tables (different definitions) piped should not be support (at least right now).

However the example that @wabby80 shared should work! it's the same table definition so it should work!

If you guys can give it a try would be nice :-)
