### ISSUE TITLE
Read-DbaBackupHeader - SQL 2005 backup fails with column "CompressedBackupSize" does not belong to table

### ISSUE THREAD

**Issue by dlh275** [sqlcollaborative/dbatools#4945]
## Steps to Reproduce

Attempt to read backup information from a SQL 2005 backup. WSMELTON identified the code was removed here: https://github.com/sqlcollaborative/dbatools/commit/8f99181d5457c32905d8686ebcbf9f9bff60f67c#diff-7240b60d2bff43b467f5dbf0a39e6bb7

```powershell
<#
Get-DbaBackupInformation -Path 'Z:\Temp' -SqlInstance SQL05 -DatabaseName DB -MaintenanceSolution -IgnoreLogBackup
#>
```

## Actual Behavior

WARNING: [11:26:45][Read-DbaBackupHeader] Problem found with Z:\Temp\SQL05\DIFF\db.bak. | Column 'CompressedBackupSize' does not belong to table
 Table.

## Environmental data

 - PowerShell: 0.9.734
 - - SQL Server: Microsoft SQL Server 2005

**Comment by wsmelton** [comment]
This is an easy one to fix and will try to get to this today. The initial code that addressed this issue was removed in a previous commit back in November....so just has to be put back in.

**Comment by potatoqualitee** [comment]
sho do!

**Comment by potatoqualitee** [comment]
hows this looking, @wsmelton ?

**Comment by potatoqualitee** [comment]
info for me

```
[62.48 ms] C:\github\dbatools> Get-DbaBackupInformation -Path C:\temp\db1.bak -SqlInstance sql2005
WARNING: [21:00:30][Read-DbaBackupHeader] Problem found with C:\temp\db1.bak. | Column 'CompressedBackupSize' does not belong to table Table.
```
