### ISSUE TITLE
Restore-DbaDatabase quits prematurely when dbs exist

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4949]
if i pipe in a number of databases, and the last one doesnt exist, but the first one does, restore-dbadatabase will quit instead of continuing on.

**Comment by Stuart-Moore** [comment]
Gotten most of this done. However doing so makes AllowContinue pretty superfluous, are you happy to have the parameter dropped? or would you prefer me to leave it, but throw a warning that it's disappearing in 1.0 (or some other point)

**Comment by potatoqualitee** [comment]
excellent ty! gonna do a release today
