### ISSUE TITLE
Get-DbaDbRoleMember user status Enabled/Disabled

### ISSUE THREAD

**Issue by AndulRehman1982** [sqlcollaborative/dbatools#4964]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

* Clear/concise description of what the problem is that the new feature can solve.

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.

**Comment by AndulRehman1982** [comment]
Dear Friend,

i want to get RoleMember with user/login disabled and enabled.

currently i am getting results as below.

ComputerName          InstanceName          SqlInstance           Database              Role                  UserName              Login                       IsSystemObject

i just want to add isDisabled (True/False) as output.

Please help.

Regards,
Abdul Rehman

**Comment by andreasjordan** [comment]
Hi @AndulRehman1982 - having the User SMO in the output will help you. Here an example:

```
Get-DbaDbRoleMember -SqlInstance SRV1 -Database AdventureWorks | 
    Select-Object -Property *, @{ 'l' = 'LoginIsDisabled' ; 'e' = { $_.SMOUser.Parent.Parent.Logins | Where-Object Name -eq $_.SMOUser.Login | Select-Object -ExpandProperty isDisabled  } }

```
