### ISSUE TITLE
Credentials conflict using copy-database and invoke-dbaquery

### ISSUE THREAD

**Issue by bootrider** [sqlcollaborative/dbatools#4968]
### Before submitting a bug report:

- [ x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ x] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
A powershell script objective is to copy a database from one server to another, then execute a simple query on destination server. the current user does not have permissions on the database servers, therefore a login was created in both servers, an the password stored in file as a secure string:

```powershell
$sourceServer = "ServerA"
$destServer = "ServerB"

$restoreUser = "replicationuser"
$encPass = Get-Content -Path ".\SecuredPass.spf"
$secString= $encPass  | ConvertTo-SecureString -Key (1..16)
$restoreCredential=New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $restoreUser, $secString

Copy-DbaDatabase -Source $sourceServer -Destination $destServer -Database "MyDatabase" -SourceSqlCredential $restoreCredential -DestinationSqlCredential $restoreCredential -BackupRestore -NetworkShare "\\MyShare\Databases" -WithReplace -EnableException
$sqlQuery = 'select 1+1'    
Invoke-DbaSqlQuery -Query $sqlQuery -SqlInstance $destServer -SqlCredential $restoreCredential
```

## Expected Behavior

the database copied, and have the query results

## Actual Behavior

the script runs, the database is copied, but the query execution gives the following message:
`WARNING: [15:53:29][Invoke-DbaQuery] Failure | Property LoginSecure cannot be changed or read after a connection string has been set`.

## Environmental data

 - PowerShell: 
Name                           Value
----                           -----
PSVersion                      5.1.16299.785
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.785
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - - SQL Server: 
Microsoft SQL Server 2012 (SP3) (KB3072779) - 11.0.6020.0 (X64) 
	Oct 20 2015 15:36:27 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by wsmelton** [comment]
Use of the copy command is not associated with this error, it is just an issue with the invoke command.

This bug has already been reported via #4946.
