### ISSUE TITLE
Issue involving Invoking-DbaDataMasking

### ISSUE THREAD

**Issue by MateoV97** [sqlcollaborative/dbatools#4969]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
 Invoke-DbaDbDataMasking -SqlInstance myinstance\SQL2017 -Database mydatabase -FilePath C:\Users\User\Desktop\DboJSON.json -Confirm:$false 
```

## Expected Behavior
Expected cmdlet to mask tables
```

When running the script, it will take a while to produce the error and then will perform the data masking for each table.
The error happens and appears in the console pane before each table can be data masked and it takes a while to show up.
```
## Actual Behavior
Receive error below:
The following exception occurred while trying to enumerate the collection: "An exception occurred while executing a Transact-SQL statement or batch.".
At line:57683 char:25
+                     if ($tableobject.Name -notin $db.Tables.Name) {
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
   + FullyQualifiedErrorId : ExceptionInGetEnumerator

```

 - PowerShell:                                                                                                    
PSVersion                      5.1.14393.2636                                                                                            
PSEdition                      Desktop                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                   
BuildVersion                   10.0.14393.2636                                                                                           
CLRVersion                     4.0.30319.42000                                                                                           
WSManStackVersion              3.0                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                       
SerializationVersion           1.1.0.1     

 - - SQL Server: 
Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14 (X64)   Jul 21 2018 07:47:45   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 2016 LTSB 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

**Comment by potatoqualitee** [comment]
hey Mateo! what was the solution?
