### ISSUE TITLE
Unable to pipe Get-DbaUser into Remove-DbaUser when multiple users are selected on the same database

### ISSUE THREAD

**Issue by frank687** [sqlcollaborative/dbatools#4971]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
CREATE USER USER01 WITHOUT LOGIN;
CREATE USER USER02 WITHOUT LOGIN;
```

```powershell
#Returns 2 users
get-dbadbuser -SqlInstance SQLSRV01 -Database DB01| Where-Object{ $_.Name -match "^USER(.*)" } | select Name

# Removes 1 user then errors
get-dbadbuser -SqlInstance SQLSRV01 -Database DB01| Where-Object{ $_.Name -match "^USER(.*)" } | Remove-DbaUser

#Workaround
get-dbadbuser -SqlInstance SQLSRV01 -Database DB01| Where-Object{ $_.Name -match "^USER(.*)" } | %{Remove-DbaUser -SqlInstance $_.SqlInstance -Database $_.Database -User $_.Name }

```

## Expected Behavior

Both users should be removed

## Actual Behavior

Single user is removed. 
```
An error occurred while enumerating through a collection: Collection was modified; enumeration operation may not execute..
At line:36361 char:17
+                 $users | ForEach-Object {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.SqlSe...dListEnumerator:SmoSortedListEnumerator) [], RuntimeException
    + FullyQualifiedErrorId : BadEnumeration
```

### PowerShell: 
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.2636
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2636
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### SQL Server: 
Microsoft SQL Server 2014 (SP2-CU13) (KB4456287) - 12.0.5590.1 (X64)   Aug  1 2018 01:23:36   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by sqllensman** [comment]
This issue here is that InputObject is being modified in the Pipeline
The example given can be made to work by either using.

$User = get-dbadbuser -SqlInstance SQLSRV01 -Database DB01| Where-Object{ $_.Name -match "^USER(.*)" }

$User | Remove-DbaUser

or

(get-dbadbuser -SqlInstance SQLSRV01 -Database DB01| Where-Object{ $_.Name -match "^USER(.*)" }) | Remove-DbaUser

**Comment by potatoqualitee** [comment]
This may help enumeration issues that we face. Perhaps we can generically wrap it.

https://twitter.com/Lee_Holmes/status/1105896696142155776

![image](https://user-images.githubusercontent.com/8278033/54825063-f16c4000-4cac-11e9-9ee1-0fb078be9758.png)
