### ISSUE TITLE
Test all the Find- cmdlets

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#4982]
### Summary of new feature

There are a substantial number of `Find-` cmdlets that do not have a integration test. These should be written to improve the health of the module. Current cmdelts that have 0 on codecov.io for coverage:
```
Find-DbaAgentJob 
Find-DbaCommand
Find-DbaDbGrowthEvent
Find-DbaDbUnusedIndex
Find-DbaLoginInGroup
Find-DbaStoredProcedure
Find-DbaTrigger
Find-DbaUserObject
Find-DbaView
```

### Proposed technical details (if applicable)

Using before all blocks will create the items the will need to be retrieved. Run the `Find-` cmdlet. Evaluate the results with tests and then remove the items in an after all block.

### Latest version of dbatools as of writing

0.9.743

**Comment by wsmelton** [comment]
I can't remember what object is returned or searched on the Login in a group but you might be able to use [New-MockObject](https://github.com/pester/Pester/wiki/New-MockObject) in Pester to output an object that it can search...

**Comment by potatoqualitee** [comment]
hey @joshcorr, any chance this is on your agenda within the next month? we are looking to prerelease 1.0 in april, mayybe 😅

**Comment by joshcorr** [comment]
@potatoqualitee  Yes! I will  be working on this issue in this week or next. I got distracted prepping to take a certificate.
