### ISSUE TITLE
Backup-DbaDatabase doesn't work with SQL 2000 again

### ISSUE THREAD

**Issue by pollusb** [sqlcollaborative/dbatools#4984]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
Backup-DbaDatabase -SqlInstance SQL2000 -Database AA -BackupDirectory \\Share\Folder
```

## Actual Behavior

```
WARNING: [09:37:25][Backup-DbaDatabase] Backup Failed | 'fn_dblog' : nom d'objet incorrect.
```

## Environmental data

 - PowerShell: 
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

 - - SQL Server:

**Comment by pollusb** [comment]
nom d'objet incorrect = incorrect object name

**Comment by wsmelton** [comment]
It seems like this is the culprit:

https://github.com/sqlcollaborative/dbatools/blob/cfbb6422be0ff7d8f1243b4fc8c9cfb4831c47ee/functions/Backup-DbaDatabase.ps1#L518-L519

However, I would also say that capturing those two bits of data should not cause the backup itself to fail. // @Stuart-Moore @potatoqualitee

**Comment by potatoqualitee** [comment]
i am so sorry about this, @pollusb - we were trying to assist with specific issues and broke this one. in the future, i'd like to let anyone with specific and weird copy-dbadatabase issues know that they'll need to use backup/restore. which i believe can help us better cater to older versions. ive passed on this request to stuart which can hopefully ease his burden.

**Comment by Stuart-Moore** [comment]
Fix just pushed into development branch. not sure on ETA to production, but cl should be able to advise.
