### ISSUE TITLE
Get-DbaUserPermission not working on SQL Servers with case-sensitive collation

### ISSUE THREAD

**Issue by Pietervanhove** [sqlcollaborative/dbatools#4985]
Hi,

We were trying to use the Get-DbaUserPermission but we never received any result.
After investigation, we noticed that the views were not created correctly because they contain wrong column names because we're using an instance with case sensitive collation.
We corrected the STIG.sql file so that all the views and functions were created correctly and also corrected the SQL statements in the ps1 script as well but we never got it working…

Could it be possible to help us out and verify what should be changed to make this script working on an instance with case sensitive collation?

Thanks
Best REgards
Pieter

**Comment by ijeb** [comment]
I tested the script on a case sensitive instance and made some changes to get results.

The construction with TRY and EMPTY catches is not really good. If an error occurs, the function does not stop and causes an empty result set. At this moment I don't know an example in dbatools of a better way to do this. Some feedback about errors would be make the function more reliable.

**Comment by Pietervanhove** [comment]
Just for my understanding. Does it mean that if we download the module again, you modification will apply?

Regards
Pieter

**Comment by ijeb** [comment]
It's merged into the development branch, so if you download the development branch from GitHub you will see the changes.
After some time it will usually be merged into the master branch.
