### ISSUE TITLE
Cloning databases using Transfer SMO class

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#4986]
---
name: Cloning databases using Transfer SMO class
about: Configurable cloning of databases peer-to-peer using SMO

---

### Summary of new feature

New function that uses Transfer SMO object to transfer database objects in bulk from one database to another:
https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/tasks/transferring-data?view=sql-server-2017

Possible options to support:
* Providing list of objects to copy via -InputObject and pipeline
* Specifying object -Types
* Scripting it out instead of a transfer
* Including dependencies by default
* Dropping existing objects before transfer

Possible names:
Invoke-DbaDbTransfer
Copy-DbaDbObject

### Proposed technical details (if applicable)

Similar to what we have here, but for all/specific objects
https://github.com/sqlcollaborative/dbatools/blob/745efcf7ee71c02e9ca8138b20b2113a8875ae97/internal/functions/Get-DbaSysDbUserObjectScript.ps1

### Latest version of dbatools as of writing

0.9.7xx

**Comment by wsmelton** [comment]
I would rather just have a `New-DbaDbTransfer`. This would output the SMO object itself but could support some parameters you set as inputs; then you can just call `TransferData()` or `ScriptTransfer()` methods (or as a flag parameter).

Plenty of options to set as either a hashtable passed in or individual parameters:

```
TemporaryPackageDirectory        :      
BatchSize                        : 0    
BulkCopyTimeout                  : 0    
Database                         :      
ObjectList                       : {}   
CopyAllObjects                   : True 
CopyAllFullTextCatalogs          : False
CopyAllFullTextStopLists         : False
CopyAllSearchPropertyLists       : False
CopyAllTables                    : False
CopyAllViews                     : False
CopyAllStoredProcedures          : False
CopyAllUserDefinedFunctions      : False
CopyAllUserDefinedDataTypes      : False
CopyAllUserDefinedTableTypes     : False
CopyAllPlanGuides                : False
CopyAllRules                     : False
CopyAllDefaults                  : False
CopyAllUsers                     : False
CopyAllRoles                     : False
CopyAllPartitionSchemes          : False
CopyAllPartitionFunctions        : False
CopyAllXmlSchemaCollections      : False
CopyAllSqlAssemblies             : False
CopyAllUserDefinedAggregates     : False
CopyAllUserDefinedTypes          : False
CopyAllSchemas                   : False
CopyAllSynonyms                  : False
CopyAllSequences                 : False
CopyAllDatabaseTriggers          : False
CopyAllDatabaseScopedCredentials : False
CopyAllExternalFileFormats       : False
CopyAllExternalDataSources       : False
CopyAllLogins                    : False
CopyAllExternalLibraries         : False
CopySchema                       : True 
CopyData                         : True 
DropDestinationObjectsFirst      : False
CreateTargetDatabase             : False
DestinationTranslateChar         : True 
SourceTranslateChar              : True 
UseDestinationTransaction        : False
PreserveLogins                   : False
PrefetchObjects                  : True 
PreserveDbo                      : False
DestinationLoginSecure           : True 
DestinationDatabase              :      
DestinationLogin                 :      
DestinationPassword              :      
DestinationServer                :      
TargetDatabaseFilePath           :      
TargetLogFilePath                :      
DatabaseFileMappings             : {}   
Options                          :      
```

```powershell
$params = @{
    SqlInstance = myserver
    Database = mydb
    ObjectsList = 'myproc1','myproc2','myproc3'
    DestinationDatabase = mydb2
    DestinationServer = 'server2'
    DestinationSqlCredential = $myCred  
}

New-DbaDbTransfer @params
```

Then you could go with the Invoke command that uses this one.

**Comment by wsmelton** [comment]
I think the New command would give easier control to those that would want this ability in database deployments and automation.

**Comment by nvarscar** [comment]
Agreed, New- command makes perfect sense. `New-DbaDbTransfer | Invoke-DbaDbTransfer` should be a thing. I'm also thinking about adding parameters to Invoke-DbaDbTransfer to implicitly call New-DbaDbTransfer when needed so that users would have an ability to use a single function for a single task.
