### ISSUE TITLE
Backup Failed | The SELECT permission was denied on the object 'fn_dblog', database 'mssqlsystemresource', schema 'sys'.

### ISSUE THREAD

**Issue by waffel** [sqlcollaborative/dbatools#4989]
### Before submitting a bug report:

This issue should be used to track was has to be fixed for the _Backup-DbaDatabase_ command. Talked on slack with @wsmelton about this.

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```powershell
# run as windows user which uses ntlm login into the DB and has dbo rights
Backup-DbaDatabase -SqlInstance 'localhost,6201' -Databases MYDB -BackupFileName "MYDB.bak" -BackupDirectory D:\Backup\sql -Type Full -CompressBackup

```

## Expected Behavior

Backup works also for users which has only DBA rights on the DB and filesystem which should be backuped.

## Actual Behavior

running Backup-DbaDatabase from latest dba-tools version ... and I get following error (seems someone has changed some permissions on the server, but I do not know which):

**Backup Failed | The SELECT permission was denied on the object 'fn_dblog', database 'mssqlsystemresource', schema 'sys'.**

The user I'am running is dbo of the database which I want to backup

the UI (sql server manager) can create backups with the same user

## Environmental data
 - PowerShell: 5.0.10586.117
 - SQL Server: Microsoft SQL Server 2012 (SP4-GDR) (KB4057116) - 11.0.7462.6 (X64) 
	Jan  5 2018 22:11:56 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

**Comment by Stuart-Moore** [comment]
Fix just pushed into development branch. not sure on ETA to producgtion, but cl should be able to advise.
