### ISSUE TITLE
Remove-DbaDbMail Profile and Account

### ISSUE THREAD

**Issue by dwilkie1** [sqlcollaborative/dbatools#4990]
---
name: Remove-DbaDbMail Profile and Account
about: Remove Mail Profiles & Accounts

---

### Summary of new feature
It would be useful to be able to remove profiles & accounts prior to use of the Copy-DbaDbMail cmdlet.

### Proposed technical details (if applicable)
This is how i'm handling it right now if it helps:
$profileName = 'SQL_Alerts'
$accountName = 'SQL_Alerts'

function Remove-Profile {
    param (
        $Profilename
    )
    Invoke-Sqlcmd -ServerInstance $destination `
        -Query @"
        EXECUTE msdb.dbo.sysmail_delete_profile_sp 
            @profile_name = '$Profilename' ;
"@ `
    -OutputSqlErrors $true `
    -Verbose
}

function Remove-Account {
    param (
        $AccountName
    )
    Invoke-Sqlcmd -ServerInstance $destination `
        -Query @"
        EXECUTE msdb.dbo.sysmail_delete_account_sp 
        @account_name = '$AccountName' ;
"@ `
    -OutputSqlErrors $true `
    -Verbose
}

### Latest version of dbatools as of writing

0.9.743

**Comment by MikeyBronowski** [comment]
@andreasjordan I am looking into this one. Might want to assign it to me.

**Comment by MikeyBronowski** [comment]
One question about parameter aliases. 

Get-DbaDbMailProfile cmdlet uses "Profile" which is an automatic variable in PowerShell ([$PROFILE](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.1#profile)):

https://github.com/sqlcollaborative/dbatools/blob/c8b825a5fc65031b7635202e77274765b43b2416/functions/Get-DbaDbMailProfile.ps1#L19-L20

However New-DbaDbMailProfile cmdlet uses Name for the same property:

https://github.com/sqlcollaborative/dbatools/blob/c8b825a5fc65031b7635202e77274765b43b2416/functions/New-DbaDbMailProfile.ps1#L19-L20


When writing the Remove-DbaDbMailProfile cmdlet I need to follow parameters in Get-* counterpart, but at the same time I would prefer using something different than **$profile**.  Saying that, can we add an alias to Get-DbaDbMailProfile Profile parameter, so I can use **Name** in the new command? 

```
[Alias("Name")]
[string[]]$Profile
```

What are your thoughts on that? Renaming the parameter would be a breaking change, hence the idea with the alias.

**Comment by andreasjordan** [comment]
I think we can add an alias "Name" to the parameter as we did in some other commands as well.
