### ISSUE TITLE
Get-DbaAgReplica shows duplicates

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5014]
```
 Get-DbaAgReplica -SqlInstance sql2016b -AvailabilityGroup ag1
```

**Comment by wsmelton** [comment]
Duplicates of what?

**Comment by potatoqualitee** [comment]
oops you are right, i was looking at the wrong column

![image](https://user-images.githubusercontent.com/8278033/51800193-15bb1b80-222c-11e9-958e-43995f6810fe.png)
