### ISSUE TITLE
Publish-DbaDacPackage fails if user "sa" is used

### ISSUE THREAD

**Issue by chrgraefe** [sqlcollaborative/dbatools#5021]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [ ] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

Note that we do not have the resources to make `Copy-DbaDatabase` work in every environment. Instead, we try to ensure Backup & Restore work in your enviornment.

## Steps to Reproduce

```powershell
Publish-DbaDacPackage -SqlInstance $instance -SqlCredential $sqlCredential -Database $database -Path $dacpac -PublishXml $publishXml -OutputPath $outputPath -GenerateDeploymentScript:$true -GenerateDeploymentReport:$true -Verbose:$true
```

## Expected Behavior

Deployment should happen, but it throws an error.

## Actual Behavior

This error is written to the terminal
```
VERBOSE: [21:15:50][Publish-DbaDacPackage] Dac Fx loaded.
VERBOSE: [21:15:50][New-DbaDacOption] Dac Fx loaded.
VERBOSE: Ausführen des Vorgangs "Executing Dacpac publish" für das Ziel "localhost".
WARNING: [21:15:51][Publish-DbaDacPackage] Deployment failed | Unable to connect to master or target server '##db##'. You must have a user with the same password in master or target server '##db##'.
VERBOSE: Ausführen des Vorgangs "Generating deployment report and output" für das Ziel "localhost".
```
## Environmental data

```
 - PowerShell: 
Name                           Value
----                           -----
PSVersion                      5.1.16299.820
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.820
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - - SQL Server: Microsoft SQL Server 2019 (CTP2.2) - 15.0.1200.24 (X64) 	Dec  5 2018 16:51:26 	Copyright (C) 2018 Microsoft Corporation	Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS) <X64>
```

**Comment by potatoqualitee** [comment]
thanks for the report! richie do you have time to take a look?

**Comment by RichieBzzzt** [comment]
It’ll take me a little bit of time to get a Linux install up and running, but yes hopefully I should have some time next week. 

The error thrown is a very generic one unfortunately but report is useful thanks.

**Comment by chrgraefe** [comment]
Some background if needed:
- runninng a docker instance for development purpose
- Windows 10 
- running via sqlpackage.exe does not fail with the same credentials

**Comment by wsmelton** [comment]
Just note @RichieBzzzt that this is against a SQL Server 2019 instance and CTP release. There are a million things that can be broken on that and with CTP 2.3 could be fixed or give a completely different result.

**Comment by wsmelton** [comment]
Is the database using any special features that are not supported in SQL Server on Linux? @chrgraefe Can you provide the dacpac where we can replicate the exact scenario?

**Comment by chrgraefe** [comment]
@RichieBzzzt I will check it against a 2017 instance.

**Comment by chrgraefe** [comment]
I 've tested it on a docker 2017 instance and it worked.
I will keep an eye on it, but for now I'm closing this issue
