### ISSUE TITLE
Where is the Dockerfile?

### ISSUE THREAD

**Issue by cilerler** [sqlcollaborative/dbatools#5022]
Would you please provide the **Dockerfile** of [sqlinstance](https://hub.docker.com/r/dbatools/sqlinstance/dockerfile) and [sqlinstance2](https://hub.docker.com/r/dbatools/sqlinstance2/dockerfile) _(e.g. [mssql-server-linux](https://hub.docker.com/r/cilerler/mssql-server-linux/dockerfile))_

**Comment by wsmelton** [comment]
A dockerfile was not used to build those images.

**Comment by wsmelton** [comment]
I'm working on a repository that will contain a dockerfile and docker-compose to build similar versions of the images. Once that is done it will be published under the sqlcollaborative org.
