### ISSUE TITLE
get-dbadiskspace -checksql needs some tlc

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5023]
get-dbadiskspace -checksql doenst work so well with clusters and is a bit rough around the edges

**Comment by wsmelton** [comment]
Personally I'd rather remove that code all together from that command and just make something like `Test-DbaSqlDisk` or say `Test-DbaDisk`. There are to many variations that can say a given drive is part of SQL Server (e.g. backups could be written to it when not default backup path). So we could expand an individual command to really validate whether a given disk is used by the SQL Server instance.

**Comment by potatoqualitee** [comment]
I agree with you, @wsmelton - good call

**Comment by potatoqualitee** [comment]
prerelease cuz this is breaking change
