### ISSUE TITLE
Get-DbaCmsRegServer -SqlCredential parameter not working

### ISSUE THREAD

**Issue by flyfishingdba** [sqlcollaborative/dbatools#5025]
### Before submitting a bug report:

- [X ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X ] Verified this bug is not already reported in an issue
- [X ] Verified errors are not related to permissions
- [X ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [ ] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

Note that we do not have the resources to make `Copy-DbaDatabase` work in every environment. Instead, we try to ensure Backup & Restore work in your enviornment.

## Steps to Reproduce

```powershell
<#
    Start powershell session as DOMAIN\User1 (no permissions on sql instance)
    Supply alternate credentials (DOMAIN\User1) with sql instance permissions
#>
    $cred = Get-Credential DOMAIN\User2
    Get-DbaCmsRegServer -SqlInstance <servername> -Group "Group1" -SqlCredential $cred
```

## Expected Behavior

Command authenticates with credentials passed via -SqlCredential parameter
## Actual Behavior

Command is using the credentials of the powershell session. SQL error log shows failed login for DOMAIN\User1 and the command returns an error:
```
Login failed for user 'DOMAIN\User1'. Reason: Could not find a login matching the name provided. [CLIENT: 127.0.0.1]
```
```
Exception calling "GetDescendantRegisteredServers" with "0" argument(s): "Failed to connect to server
<servername>."
At line:28602 char:21
+ ...             $servers += $groupservers.GetDescendantRegisteredServers( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ConnectionFailureException
```
## Environmental data

 - PowerShell: 
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
 - SQL Server: 
```
Microsoft SQL Server 2014 (SP2-GDR) (KB4057120) - 12.0.5214.6 (X64) 
	Jan  9 2018 15:03:12 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
```

**Comment by potatoqualitee** [comment]
🤔 i imagine this is because of the line:

$store = New-Object Microsoft.SqlServer.Management.RegisteredServers.RegisteredServersStore($server.ConnectionContext.SqlConnectionObject)

Will have to think about this one, thank you for the report

**Comment by potatoqualitee** [comment]
k fix will be included in the next release 👍
