### ISSUE TITLE
Copy-MaintenancePlan command 

### ISSUE THREAD

**Issue by baingar** [sqlcollaborative/dbatools#5028]
Although I do not personally like or encourage maintenance plans, they do exist and are being used. Would it be possible to add a new command to migrate Maintenance Plans. I have worked on something similar successfully using Powershell to extract, import, and copy the agent jobs schedule. Would love to contribute, if possible.

**Comment by wsmelton** [comment]
We looked into this one back in 2017 and there is no direct support for copying maintenance plans between servers via SMO. The T-SQL method that is used is considered a "hack" method and is cannot be consistent. So we chose not to support maintenance plans in that manner.

**Comment by baingar** [comment]
There's no way use SMO directly, but it is not necessarily a hack as it utilizes dts.runtime namespace which is not part of SMO.

**Comment by wsmelton** [comment]
That won't work with maintenance plans. If you have a method that can be cleanly tested and stable we can review it and determine if it is viable to add.

**Comment by wsmelton** [comment]
DTS dll are not packaged up with SMO, so it would require adjustments to support that namespace being added.

If you can propose what DLLs files need to be packaged and where we can get them; then work out a repeatable process to migrate maintenance plans then we can look at how we can add the feature in.

**Comment by baingar** [comment]
It'll require ManagedDTS assembly which I believe is already loaded for DBAtools install. Correct me if I'm wrong.

**Comment by wsmelton** [comment]
We do not include or load that DLL.

**Comment by baingar** [comment]
If we want to support MaintenancePlan export/import, we'll need the ManageDTS.dll loaded as part of dbatools. If yes, I would gladly contribute to the project. If it cannot be loaded with dbatools, let me know. 

Thanks.

**Comment by wsmelton** [comment]
We do not plan to support managing maintenance plans at this time.
