### ISSUE TITLE
Get-DbaMaintenanceSolutionLog - Support Linux paths needed

### ISSUE THREAD

**Issue by llmuculusll** [sqlcollaborative/dbatools#5035]
I've run MSSQL(2017) docker on a Linux(Ubuntu 18.04), on another windows machine I installed the dbatools.

## Steps to Reproduce
When I execute this command:
```powershell
<#
 Get-DbaMaintenanceSolutionLog -SqlInstance 192.168.x.x -SqlCredential sa
#>
```

## Actual Behavior
I've encountered with this error:

```
WARNING: [23:41:09][Get-DbaMaintenanceSolutionLog] Directory \\192.168.x.x\var\opt\mssql\log is not accessible
```

## Environmental data
 - PowerShell:  5.1.14393.2363
 - - SQL Server: 2017

What is the problem?

**Comment by niphlod** [comment]
well, the point here is that there's no admin shares on linux ....

**Comment by wsmelton** [comment]
Actually I think this has been fixed.

https://github.com/sqlcollaborative/dbatools/blob/049384094bd70189b659b870cfc4b467940ef7a2/functions/Get-DbaMaintenanceSolutionLog.ps1#L170-L178

**Comment by niphlod** [comment]
well, you surely won't be able to read logs from win to linux unless having an sshd daemon running on the other side or an smb config file that exports \var\
