### ISSUE TITLE
Manage database role memberships

### ISSUE THREAD

**Issue by Ayanmullick** [sqlcollaborative/dbatools#5037]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

* One should be able to manage database role mamberships thru `dbatools`

### Proposed technical details (if applicable)

*SSMS screenshot: 
![alt text](https://pbs.twimg.com/media/DyXk5GHWkAA3bsz.jpg "Logo Title Text 1")

### Latest version of dbatools as of writing

* 0.9.751.

**Comment by wsmelton** [comment]
Please be specific on what you want to manage. We already have some commands around database and server-level roles in the module. Your screenshot does not appear to have uploaded properly as well.

**Comment by Ayanmullick** [comment]
I want to add a windows user as 'db_datareader' to a specific database only.

Frank confirmed dbatools didn't have this feature yet.
https://twitter.com/osiris687/status/1091536514096480256

**Comment by Ayanmullick** [comment]
The below adds a new user to a database and adds a specific role.

`$Database = "<DbName>"`
`$Username = "<GroupName>"`
`$db=(New-Object ('Microsoft.SqlServer.Management.Smo.Server') "localhost").Databases[$Database]`

`$usr = New-Object ('Microsoft.SqlServer.Management.Smo.User') ($db,$Username)`
`$usr.Create()`

`$db.Roles['db_datawriter'].AddMember($Username) `

**Comment by ClaudioESSilva** [comment]
Hi @Ayanmullick ,

Currently, you can achieve this by running two different commands.

``` powershell
New-DbaDbUser -SqlInstance localhost -Database DB1 -Login user1
Add-DbaDbRoleMember -SqlInstance localhost -Database DB1 -Role "db_datawriter" -User user1 
```

Can you confirm this is what you are looking for?

**Comment by Ayanmullick** [comment]
Thanks for the update, @ClaudioESSilva. The `Add-DbaDbRoleMember` cmdlet wasn't there 2 years back when I was trying it.
