### ISSUE TITLE
Backup-DbaDatabase - ExcludeDatabase won't not work with piping

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#5044]
---
name: Make `ExcludeDatabase` work with piping
---

### Summary of new feature

When piping database object from one function to `Backup-DbaDatabase`, `ExcludeDatabase` won't work, because it filters only `Database`  parameter of `Backup-DbaDatabase`.

### Latest version of dbatools as of writing

* 0.9.751

**Comment by potatoqualitee** [comment]
the db should be filtered prior. ill throw in a stop-function -continue to warn that it's being skipped
