### ISSUE TITLE
Get-DbaServerRole Doesn't Include User-Created Server Roles

### ISSUE THREAD

**Issue by milesbonham** [sqlcollaborative/dbatools#5045]
### Before submitting a bug report:

- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [ ] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

Note that we do not have the resources to make `Copy-DbaDatabase` work in every environment. Instead, we try to ensure Backup & Restore work in your enviornment.

## Steps to Reproduce

```powershell

    Get-DbaServerRole -SqlInstance 'myServer'

```

## Expected Behavior

All server roles' information to be output.

## Actual Behavior

Only shipped server roles' information is output.

## Environmental data

 - PowerShell: 5.1.14393.2636
 - - SQL Server: Microsoft SQL Server 2017 (RTM-CU12) (KB4464082) - 14.0.3045.24 (X64)   Oct 18 2018 23:11:05   Copyright (C) 2017 Microsoft Corporation  Enterprise Evaluation Edition (64-bit) on Windows Server 2016 Datacenter Evaluation 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
looks like Microsoft did some improvements to that query. it now shows up

![image](https://user-images.githubusercontent.com/8278033/57193619-469ea100-6f3d-11e9-8559-187173259fc3.png)
