### ISSUE TITLE
getting started documentation typco

### ISSUE THREAD

**Issue by alhandra** [sqlcollaborative/dbatools#5048]
Hi folks,
https://dbatools.io/getting-started/ seams to have a typco
the example with Start-Migration refers to 

```
# You've probably heard about how easy migrations can be with dbatools. Here's an example 
$startDbaMigrationSplat = @{
    Source = $old
    Destination = $new
    BackupRestore = $true
    SharedPath = 'C:\temp'
    Exclude = 'BackupDevice','SysDbUserObjects','Credentials'
}
		
Start-DbaMigration @startDbaMigrationSplat -Force | Select * | Out-GridView
```

But should be instaead of BackupDevice BackupDevices

**Comment by wsmelton** [comment]
@potatoqualitee you will have to update this since that code is within the gist owned by your account.

https://gist.github.com/potatoqualitee/e8932b64aeb6ef404e252d656b6318a2#file-dbatools-getting-started-ps1-L48

**Comment by potatoqualitee** [comment]
ty @wsmelton  and @alhandra  - i have corrected it
