### ISSUE TITLE
Add the ability to output script from Set-DbaSpn and remove-dbaspn

### ISSUE THREAD

**Issue by KennyNeal** [sqlcollaborative/dbatools#5051]
Our security doesn't allow the DBAs to modify SPNs. Would it be possible to have Set-DbaSpn and remove-dbaspn output the setspn syntax so we have a script to hand off to the security team?

**Comment by niphlod** [comment]
set sets, remove removes ...... test does what you want ^_^

**Comment by KennyNeal** [comment]
Test tells me that an SPN is missing, but I don't see how to generate the
command I need to create it from there. Am I missing something?

**Comment by wsmelton** [comment]
@KennyNeal You can call `Test-DbaSpn` should have have a `RequiredSpn` or `Required` property contains the `setspn` command to call manually.

**Comment by KennyNeal** [comment]
Got it. I can piece it together from requiredspn and
instanceserviceaccount. Feel free to close this request.

**Comment by niphlod** [comment]
yep
