### ISSUE TITLE
Copy-DbaLogin  Could not load file or assembly 'Microsoft.SqlServer.BatchParser.dll'

### ISSUE THREAD

**Issue by adnanhamdussalam** [sqlcollaborative/dbatools#5077]
I am facing below warning while using the copy-dbalogin command:

PS C:\Windows\system32> Copy-DbaLogin -Source 20.2.1.2\swdb -Destination 20.2.1.34\sqlswcluster -Force

WARNING: [11:12:05][Update-SqlPermission] Failed to add SolarwindsSQL (login: SolarwindsSQL) to master on
SQLSWCLUSTER\SQLSWCLUSTER. | Could not load file or assembly 'Microsoft.SqlServer.BatchParser.dll' or one of its dependencies. The specified module could not be found.
WARNING: [11:12:05][Update-SqlPermission] Failed to add SolarwindsSQL to db_accessadmin database role in master on
 SQLSWCLUSTER\SQLSWCLUSTER. | Cannot add the principal 'SolarwindsSQL', because it does not exist or you do not have

I have install the shared components and sqlclr C:\windows\assembly on windows server 2012 X64 and X86 but still I am receiving the above error.

Kindly, guide me.

Regards,
Adnan

**Comment by adnanhamdussalam** [comment]
Hi,

My issue has been resolved by installing x64 Visual C++ Redistributable Packages for Visual Studio 2013.

PFB the link through I have installed:

https://windows-hexerror.linestarve.com/q/so46778957-Could-not-load-file-or-assembly-MicrosoftSqlServerBatchParserCliendll-File-Name
In this link click on 
To fix the issue I needed to build the project again targeting x86 platform. I then also had to install the corresponding x86 "C++ Redistributable Package"

Regards,

Adnan

**Comment by adnanhamdussalam** [comment]
Hi,

Thank God Issue has been resolved.

Regards,

Adnan

**Comment by potatoqualitee** [comment]
Thank you, Adnan! This is a fantastic solution for our users who are Googling the same issue 👍

**Comment by adnanhamdussalam** [comment]
Thank you, Chrissy!

Regards,

Adnan

**Comment by potatoqualitee** [comment]
Can you test w/o the workaround with version 0.9.811? It was released today and uses SSMS 2018's SMO.

**Comment by adnanhamdussalam** [comment]
Hi,

Unfortunately i have removed the test environment.

Regards,

Adnan
