### ISSUE TITLE
copy-dbadbtabledata causses faillure on max pool size

### ISSUE THREAD

**Issue by maroliict** [sqlcollaborative/dbatools#5080]
I am filling a table in a few servers with fake data. The data comes from WideWorldImporters and is send to one other db on the same server and two other SQL2014 and SQL2012 servers. It is doing this in a loop.
When it has ran for some time, the output changes to:
Failure |timeout expired. The timeout period elapsed prior to obtaining a connection from the pool.

For me this looks like the connections are not closed at the end of this script. 
Could you investigate?
we are using 0.9.714

**Comment by potatoqualitee** [comment]
we shall indeed. thanks for the report.

**Comment by potatoqualitee** [comment]
ive added what could be the fix. if it is not, please fill out the entire bug report: i had to guess at the parameters being used

https://github.com/sqlcollaborative/dbatools/issues/new/choose

then choose Bug Report

Thank you

**Comment by maroliict** [comment]
I Will run my script tomorrow again. Thanks.

Have fun!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Chrissy LeMaire <notifications@github.com>
Verzonden: maandag, maart 18, 2019 12:03 AM
Aan: sqlcollaborative/dbatools
CC: Rob Litjens; Author
Onderwerp: Re: [sqlcollaborative/dbatools] copy-dbadbtabledata causses faillure on max pool size (#5080)


ive added what could be the fix. if it is not, please fill out the entire bug report: i had to guess at the parameters being used

https://github.com/sqlcollaborative/dbatools/issues/new/choose

then choose Bug Report

Thank you
