### ISSUE TITLE
Script breaks when run as Scheduled Task

### ISSUE THREAD

**Issue by CoReTeX2k** [sqlcollaborative/dbatools#5084]
Hello,

we have run into a problem using dbatools to gather Information about our SQL Servers.

The PowerShell script runs just fine when ran manually, however when we run it as a scheduled task, it breaks at the following line:

$DBAConfig =  Get-DbaSpConfigure -SqlInstance "$server\$instanz"

The Transcript shows this error:

PS>TerminatingError(Copy-Item): "The process cannot access the file 'C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.757\bin\dbatools.dll' because it is being used by another process."

I tried to find the cause for this using 

Get-Process |  ? {$_.filename -like "*\dbatools.dll"}

just before that line, but got no results. 
Also i can't find anything in the function Get-DbaSpConfigure.ps1 that would tell me where it tries to access this file.

Any idea how to fix this issue? Both manual and task were run with the same user with sufficient rights.

**Comment by potatoqualitee** [comment]
hey @CoReTeX2k - can you try with the latest version? this hsould be fixed. If you continue to have problems let me know and i'll reopen this issue.
