### ISSUE TITLE
Possible bug in Add-DbaAgDatabase ?

### ISSUE THREAD

**Issue by TheRockStarDBA** [sqlcollaborative/dbatools#5086]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

Error: 

Database "test_D" might contain bulk logged changes that have not been backed up. Take a log backup on the principal database or primary database. Then
restore this backup either on the mirror database to enable database mirroring or on every secondary database to enable you to join it to the availability
group.

I checked the code - https://github.com/sqlcollaborative/dbatools/blob/master/functions/Add-DbaAgDatabase.ps1   and its suppose to take full backup
https://github.com/sqlcollaborative/dbatools/blob/master/functions/Add-DbaAgDatabase.ps1#L179

```powershell
$cred = Get-Credential -UserName sa -Message "Enter SA"
Set-DbaDbRecoveryModel -SqlInstance dbanyd02a -SqlCredential $cred -RecoveryModel Full -Database test_D 
Start-Sleep 1
Add-DbaAgDatabase -SqlInstance PrimaryServer -SqlCredential $cred -AvailabilityGroup AG01 -Database test_D -Secondary secondaryServer-SecondarySqlCredential $cred -SharedPath '\\shared\path\'  -SeedingMode Manual -EnableException  

```

## Environmental data

 - PowerShell: 

Name                           Value                                                                                                                          
----                           -----                                                                                                                          
PSVersion                      4.0                                                                                                                            
WSManStackVersion              3.0                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                
BuildVersion                   6.3.9600.18968                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                           
PSRemotingProtocolVersion      2.2                                                                                                                            
 -->

 - SQL Server:  Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64) 
	Jun 17 2016 19:14:09 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by Zelis6706** [comment]
I get the same behaviour before i take a first full backup of the database. It's the same as if u add the database in ssms wizard if you haven´t done an initial full backup. 
Is this intended behaviour or should it work without doing an initial backup?

Another possible bug is if you don´t specify a secondary it doesn't recognize the other replicas in the AG and puts the database in restricted user mode after joining the db in the AG. 

Add-DbaAgDatabase -SqlInstance instance1  -AvailabilityGroup AG1 -Database DbName
