### ISSUE TITLE
 Get-DbaRoleMember public role is missing

### ISSUE THREAD

**Issue by AndulRehman1982** [sqlcollaborative/dbatools#5087]
Dear Eng,

i am executing  Get-DbaRoleMember to get required information but i am not seeing public role in it.

please help me.

Regards,
Abdul Rehman

**Comment by AndulRehman1982** [comment]
I am ruining below command.

Get-DbaRoleMember -SqlInstance dscsql  -Database myDB  |Out-GridView 

all roles are visible except public.

i have user mapped with above databases but i didnt assign any role to it.

Regards,
Abdul Rehman

**Comment by potatoqualitee** [comment]
SSMS acts the same way as well. 

![image](https://user-images.githubusercontent.com/8278033/54857009-6e270a80-4cfd-11e9-85e8-f702007a5fb4.png)

if you have different results, please include code for me to reproduce as well as a screenshot.
