### ISSUE TITLE
Copy-DbaCredential as SQL Server agent "Console not elevated, but elevation is required"

### ISSUE THREAD

**Issue by mediafailure** [sqlcollaborative/dbatools#5088]
I'm calling Copy-DbaCredential within a cmdexec step in a SQL Server Agent job:
`    powershell.exe -ExecutionPolicy Bypass -Command "Copy-DbaCredential -Source SERVER1 -Destination SERVER2"`

The job has four steps: 
The Copy-DbaLogin and Copy-DbaAgentJob steps run perfectly. But the above step and the one for Copy-DbaLinkedServer both return this error and don't copy credentials or linked servers as intended:

> WARNING: [16:40:03][Copy-DbaCredential] Console not elevated, but elevation is required to perform some actions on localhost for this command.

I can run this myself in an elevated command prompt only, but not in a normal command prompt. Both myself and the SQL Server agent service are sysadmins on the SQL Server and admins on the server.

I'm assuming this probably isn't a bug and is down to how these commands use additional decryption techinques. I think I could use these as Scheduled Tasks running with the highest privileges but I'd like to run them all from SQL Server agent. Is there a way to do that? 

 - PowerShell: 
PSVersion                      5.1.14393.2791                                                                
PSEdition                      Desktop                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                       
BuildVersion                   10.0.14393.2791                                                               
CLRVersion                     4.0.30319.42000                                                               
WSManStackVersion              3.0                                                                           
PSRemotingProtocolVersion      2.3                                                                           
SerializationVersion           1.1.0.1 

  - SQL Server: 
Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64)   Sep 14 2018 13:53:44   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
That's a good question. Use this for powershell in agent: `powershell.exe -Verb RunAs`

**Comment by wsmelton** [comment]
SQL agent won't run the Shell in elevated session. If we are checking for elevated sessions we should remove that check.

**Comment by AndreasEDA** [comment]
Any solutions? How run this commmand within sql agent?

**Comment by potatoqualitee** [comment]
will add it to the agenda to take a look

**Comment by AndreasEDA** [comment]
Thank's. I try to run this command form sql Agent:
powershell.exe -NoProfile -ExecutionPolicy ByPass -command "Get-DbaAvailabilityGroup -SqlInstance localhost|Sync-DbaAvailabilityGroup"

It uses also the Copy-DbaCredential  cmdlet with same message:
"WARNING: [13:37:06][Copy-DbaCredential] Console not elevated, but elevation is required to perform some actions on 
localhost for this command."

Andy

**Comment by wsmelton** [comment]
At most you could try using `Start-Proces ... -RunAs` to start a new session that is elevated, but you are likely going to get various results if it fails. Meaning controlling whether the agent job itself fails properly will be lost.

**Comment by AndreasEDA** [comment]
Thank's. But wsmelton and also me din't manage to use "Start-Process" in SQL Agent. I'm still search for reason that this does not work. It would be a workaround though

**Comment by potatoqualitee** [comment]
the issue is that the command will fail if it's not running as admin, so i imagine we cant just bypass it. are you running the command using a credential? if not, can you try?

https://serverfault.com/questions/44489/run-a-sql-server-2005-job-as-administrator-on-windows-server-2008

**Comment by SQLDBAWithABeard** [comment]
OK So this has been fun :-)

I can recreate this at will I have 3 instances

SQL 2014 running on Server 2012R2
SQL2016 running on Server 2016
SQL2017 running on Server 2016

The agent job is running on the SQL 2016 instance and Agent Account is running as an AD account which is sysadmin and local admin on the instance

The job has  a CMDEXEC step

powershell.exe -ExecutionPolicy Bypass -Command "Copy-DbaCredential -Source SQL2014ser12r2  -Destination SQL2016n1   -EnableException"

Copying from 2014 to 2016 works
Copying from 2014 to 2017 works

However -
 
Copying from 2017 to 2014 works
Copying from 2016 to 2014 fails with the error

![image](https://user-images.githubusercontent.com/6729780/57713675-da254f80-766a-11e9-9b49-dd910dad763d.png)


Hmm - what is the difference ?

I went through all of the security settings I could find and ended up here

![image](https://user-images.githubusercontent.com/6729780/57712720-017b1d00-7669-11e9-9ef9-8dd620048d46.png)

Don't hate me - I spun up these old servers to see what was up :-)

So I remove HotFix KB4013429

![image](https://user-images.githubusercontent.com/6729780/57713547-9a5e6800-766a-11e9-90ee-9ed484ac7e50.png)

and low and behold

![image](https://user-images.githubusercontent.com/6729780/57713718-e90c0200-766a-11e9-8cce-5f92f1e316db.png)

Cant see what in here it is https://support.microsoft.com/en-gb/help/4013429/windows-10-update-kb4013429 

Doesnt help with the resolution

**Comment by potatoqualitee** [comment]
hahaha this is awesome! thank you :bear: that is all so specific. 

would you be able to remove the Admin Check and see if it still works? If so, then I can add a bypass param

**Comment by AndreasEDA** [comment]
I can confirm what Rob made

I made the exact same copy-DbaCredential job

Copy from 2016 to 2016 fails:

[cid:image001.png@01D50B0B.32728750]

We have the these hotfix installed:

[cid:image002.png@01D50B0B.32728750]


But Remove hotfixes is not option for me ☺

Andy

**Comment by SQLDBAWithABeard** [comment]
Yes, I am trying to update my lab to latest and try to work around this.

**Comment by potatoqualitee** [comment]
Thank you all for your help and interest. Thanks to the research, this is outside of the scope of dbatools. If anyone wants to add in a force param, then I'll accept but otherwise, this is closed.
