### ISSUE TITLE
Include the SqlInstance in the failure to connect message for Get-DbaDatabase

### ISSUE THREAD

**Issue by sqlpadawan** [sqlcollaborative/dbatools#5091]
---
name: Include sqlinstance name in Get-DbaDatabase failure to connect message
about: 

---

### Summary of new feature

When using a CMS group with Get-DbaDatabase, it would be helpful to include the SqlInstance name in the failure message.

### Proposed technical details (if applicable)

Pretty sure it wouldn't be any more than changing the message from:
Stop-Function -Message "Failure" -Category ConnectionError -ErrorRecord $_ -Target $instance -Continue

to

Stop-Function -Message "Failure to connect to $instance" -Category ConnectionError -ErrorRecord $_ -Target $instance -Continue

### Latest version of dbatools as of writing

0.9.757

**Comment by wsmelton** [comment]
This won't happen for just one command. If that is changed it will be done across every command in the module for consistency. The original call to and message on connection failure is used across the module in that manner.

**Comment by wsmelton** [comment]
Which oddly enough `Test-DbaConnection` actually shows a different message that would likely satisfy this request:

https://github.com/sqlcollaborative/dbatools/blob/06b6f89cfd022374283ae7ae963204bffa244451/functions/Test-DbaConnection.ps1#L140-L148

**Comment by potatoqualitee** [comment]
🤔 i bet this could be done with a mass replace. good call.

**Comment by wsmelton** [comment]
The other way that wouldn't require changing every command is having the target passed to write-message included in the output of the message itself.
