### ISSUE TITLE
you can try disabling this check with -IgnoreFileChecks Using COPY-DBADatabase

### ISSUE THREAD

**Issue by lgfritz** [sqlcollaborative/dbatools#5095]
I work on an PS script to refrsh coping of Databases from my Production Environment to my Test Environment. The two Environmnet are in different Domain and both domains have access to the Fileshare. The process work fine when I'm testing it in the same Environment. I'm getting the attached error message. 

Here's the error message.
you can try disabling this check with -IgnoreFileChecks

I've attached a screen shot of the error.

If possible can you reply to my e-mail account 'lgfritz@hotmial.com'

**Comment by lgfritz** [comment]
Any ideas on this issue? I'm using the 'Copy-DbaDatabase'  command and I'm gettgin the following error message. 

PS C:\Users\lfritz>         Copy-DbaDatabase -Source $Database.FromServer -Destination $Database.ToServer -Database $Database.Database_Name -BackupRestore -WithReplace -SharedPath $SourceBackupFolder -ErrorAction Stop
        echo 'Copy DB from target to source'
WARNING: [10:46:12][Copy-DbaDatabase] Error validating unc path: Exception calling "GetHostEntry" with "1" argument(s): "No such host is known"
Copy DB from target to source

PS C:\Users\lfritz> 

I know my parameters are set correct because I doing a backup of the Database on target before I try and refresh it from Production. 

Keep in mind I'm working with two different domain Production and Dev. And both environment have full access to the Fileshare.

Any help would be great.

**Comment by wsmelton** [comment]
Are you running this from one of the servers or a separate machine/desktop?

**Comment by potatoqualitee** [comment]
Greetings,
It is very unlikely that this is an error with dbatools. There is something going on with the resolution of your UNC path from the destination SQL Server. Please try using the Fully Qualified Domain Name (FQDN) of the file share (`share.ad.local` instead of `share`). And please log into your destination SQL Server and ensure you can access that share from the SQL Server service account.

**Comment by potatoqualitee** [comment]
Closing but willing to reopen if logs/screenshots prove my assumptions are incorrect.
