### ISSUE TITLE
Sync-DbaLoginPermission enumerate exception

### ISSUE THREAD

**Issue by PDLDYNAMICS** [sqlcollaborative/dbatools#5097]
**Problem:**
I am trying to run a simple sync of logins but i am getting an enumeration exception, I can see what i could change to resolve this, my user is SA on the test box so has all the permissions required 
```
The following exception occurred while trying to enumerate the collection: "An exception occurred while executing a
Transact-SQL statement or batch.".
At line:114370 char:5
+     $ownedJobs = $SourceServer.JobServer.Jobs | Where-Object OwnerLog ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
    + FullyQualifiedErrorId : ExceptionInGetEnumerator
```

**Environment**

Windows 10 running against a SQL 2014 cluster 
running on powershell.exe and powershell ISE 

 **Script** 
```powershell
$server1 = "server"
$server2 = "server1"
$creds = Get-Credential dev01
$creds1 = Get-Credential dev01

#Copy-DbaLogin -Source $server1 -Destination $server2 -SourceSqlCredential $creds -DestinationSqlCredential $creds1   
Sync-DbaLoginPermission  -Source $server1 -Destination $server2 -SourceSqlCredential $creds -DestinationSqlCredential $creds1 -Exclude dev01 -EnableException  -Login cosbi_awe
```

**Comment by wsmelton** [comment]
Please also provide the information requested in the bug issue template: 

https://github.com/sqlcollaborative/dbatools/issues/new?template=Bug_Report.md

**Comment by potatoqualitee** [comment]
Yes please do, the template requires things like restarting the session which may address this issue. Pleae reopen with proper info filled out.
