### ISSUE TITLE
Invoke-DbaDbShrink -AllUserDatabase includes system databases

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#5108]
Command executed:
`Invoke-DbaDatabaseShrink -SqlInstance ServerName -AllUserDatabases -WhatIf`

![image](https://user-images.githubusercontent.com/169602/53244408-6a598700-3670-11e9-866e-463231bf7450.png)

I ran normal without the -whatif, but I re-executed to get the screen shot.

**Comment by potatoqualitee** [comment]
thank you @sqllensman !
