### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by bobbytreed** [sqlcollaborative/dbatools#5124]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [ ] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

Note that we do not have the resources to make `Copy-DbaDatabase` work in every environment. Instead, we try to ensure Backup & Restore work in your enviornment.

## Steps to Reproduce

```sql
/*
    CREATE TABLE [dbo].[Test] (
    [Type]           INT            NULL,
    [Link]           NVARCHAR (MAX) NULL,
    [Author]         NVARCHAR (MAX) NULL,
    [Id]             INT            IDENTITY (1, 1) NOT NULL,
    [Name]           NVARCHAR (MAX) NULL,
    [Tags]           NVARCHAR (MAX) NULL,
    [Service]        INT            NULL,
    [SubService]     INT            NULL,
    [LastUpdated]    DATETIME2 (7)  NULL,
    [CodeFenceTags]  NVARCHAR (MAX) NULL,
    [SuggestionCost] INT            NULL,
    [Description]    NVARCHAR (MAX) NULL,
    [Title]          NVARCHAR (MAX) NULL,
);
*/
```

```powershell
<#
    $result = @{
 Link = "www.google.com"
 Type = 0
 LastUpdated = $(get-Date)
 Author = "Charles Dickens"
 Name = "Moby Dick"
 Title = "Monitor"
 SubService = 0
 }
[pscustomobject]$result | Write-DbaDataTable -SqlInstance $instance -Database "MyDB" -Table "Test" -Verbose -EnableException


#>
```

## Actual Behavior

```
Invalid cast from 'DateTime' to 'Int32'.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.773\allcommands.ps1:104800 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (BIRDSOFPRAY\LOCALDB#FAEBA694:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Write-DbaDataTable-->
```
Also, at times get:
```
Input string was not in a correct format.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.773\allcommands.ps1:104800 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (localhost\LOCALDB#FAEBA694:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Write-DbaDataTable
```
## Environmental data

```
 - PowerShell: <!-- 
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.316}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
-->
```
```
 - - SQL Server: <!-- 
Microsoft SQL Server Express Edition (64-bit)
Version: 13
-->
```

**Comment by bobbytreed** [comment]
As a follow up, the Invoke-BulkCopy seems to be trying to map the wrong fields of a customObject

Here I have a string: [Tags]           NVARCHAR (MAX) NULL,
and only data populated for the Tags property:

Tags           : hello
Type           : 0
Author         : 
SubService     : 
CodeFenceTags  : 
SuggestionCost : 0
Title          : 0
Service        : 
Description    : 
Link           : 

Yet the error complains about converting a string to an int

Hit Variable breakpoint on 'C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.773\allcommands.ps1:$stacktrace' (ReadWrite access)
 $bulkCopy.WriteToServer($DataTable)
Exception calling "WriteToServer" with "1" argument(s): "The given value of type String from the data source cannot be converted to type int of the specified target column."
At line:1 char:1
+ $bulkCopy.WriteToServer($DataTable)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
 
When I chose a string that can be converted to an INT, it works.

$result.Tags = "0"

Type           : 0
Link           : 0
Author         : 
Id             : 29
Name           : 
Tags           : 0
Service        : 0
SubService     : 
LastUpdated    : 
CodeFenceTags  : 
SuggestionCost : 
Description    : 
Title

**Comment by bobbytreed** [comment]
Here, I fixed it for you
            if ($Pscmdlet.ShouldProcess($SqlInstance, "Writing $rowCount rows to $Fqtn")) {
                $properties = $DataTable | Get-Member -MemberType Property
                foreach ($prop in $properties)
               {
                     $BulkCopy.ColumnMappings.Add($prop.Name, $prop.Name)
               }

                $bulkCopy.WriteToServer($DataTable)
                if ($rowCount -is [int]) {
                    Write-Progress -id 1 -activity "Inserting $rowCount rows" -status "Complete" -Completed
                }
            }

Apparently, SQL Bulk Copy requires that columns be in the same order as the Table expects them. With hashtables and thus customobjects, you cannot guaranteed a property order.  The solution should either be to use ordered hash tables, or just map the column names directly.

Obviously, extra testing should be performed, or add an ordered hashtable parameter.

**Comment by potatoqualitee** [comment]
ty, you can also create a view with the proper order but i think some mapping will help this.
