### ISSUE TITLE
Restart-DbaService documentation example should have -InstanceName not -Instance

### ISSUE THREAD

**Issue by mikepetrak** [sqlcollaborative/dbatools#5128]
The Restart-DbaService documentation at https://docs.dbatools.io/#Restart-DbaService has an example with the -Instance parameter but it should state -InstanceName:

Example: 3Copy
PS C:\> Restart-DbaService -ComputerName sql1,sql2 -Instance MSSQLSERVER

**Comment by sqllensman** [comment]
Will update this tomorrow in Presentation on GitHub at SQLSaturday Winnpeg

**Comment by mikepetrak** [comment]
Thanks, @sqllensman!
