### ISSUE TITLE
[Install-DbaSqlWatch] DACPAC failed ... Cannot bind argument to parameter 'Path' because it is an empty string.

### ISSUE THREAD

**Issue by jarole** [sqlcollaborative/dbatools#5130]
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [ ] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

## Steps to Reproduce
**Describe the bug**
SQLwatch installation from local file fails using dbatools.
```
PS C:\SQLwatch> Install-DbaSqlWatch -SqlInstance ABChostname123 -Database SQLWATCH -LocalFile sqlwatch-master.zip
```
I got this error:
```
WARNING: [15:15:31][Install-DbaSqlWatch] DACPAC failed to publish to SQLWATCH on ABChostname123. | Cannot bind argument to parameter 'Path' because it is an empty string.
```

**Windows Server (please complete the following information):**
 - OS Version: [Windows 2016 ]

**SQL Server (please complete the following information):**
 - SQL Version: [SQL Server 2016 SP1]
 - SQL Edition: [Standard]

https://github.com/marcingminski/sqlwatch/issues/78

**Comment by RichieBzzzt** [comment]
Hello!

I think I can see the problem here: looks like you have downloaded the [master branch](https://github.com/marcingminski/sqlwatch/archive/master.zip) as opposed to one of the releases. The source code does not contain the dacpac. But if you download [the latest release](https://github.com/marcingminski/sqlwatch/releases/tag/1.3.3) I think it will work, as the sqlwatch dacpac is in there.

If I'm correct in my assumptions can you try with the release and confirm here whether it worked?

**Comment by jarole** [comment]
Hello,

I have tested both, master and development, both have not work, but tommorrow I will double check again and let you know.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by RichieBzzzt** [comment]
Just to be clear, you need to go to the [release page](https://github.com/marcingminski/sqlwatch/releases) and download a release for it to work. None of the branches on the sqlwatch project have the sqlwatch dacpac. So I wouldn't expect the development branch to work. The dacpac is generated by a build of the sqlproj file, and has not been included in the source code.

**Comment by jarole** [comment]
Thank you @RichieBzzzt , much appreciated.
You are right, it is because of missing .dacpac, so downloading the right package solved my problem and created another problem :) 
But the next issue is another story, so I am closing this one.

**Comment by wsmelton** [comment]
@RichieBzzzt can you clarify why the dacpac was removed because I just used this command two weeks ago and never went to your release page to download anything.

Your commit history shows the dacpac was included in the development branch in September: https://github.com/marcingminski/sqlwatch/commit/b0f57789d493e2df47e353d13930c620d227c6bd

If the dacpac is not included anymore then we will remove this install command from the module // @potatoqualitee

**Comment by wsmelton** [comment]
I'm leaving this open until confirmation is found that the dacpac will no longer be included in the repository.

https://github.com/sqlcollaborative/dbatools/blob/ef77ab414a69a9b505f6af6ed179827c32e4010d/functions/Install-DbaSqlWatch.ps1#L188-L192

The install command was built around the dacpac being available and if it is no longer available them there is no longer a need for this command.

**Comment by RichieBzzzt** [comment]
@wsmelton You've got the wrong person, @marcingminski made that commit.

**Comment by marcingminski** [comment]
DACPACs are essentially a binary files being built by the appveyor upon pull request and get published as a release. I removed binaries from source code as they were causing versioning conflicts. The install-dba sqlwatch was designed to work with releases and we had a discussion about this back in a day.

**Comment by wsmelton** [comment]
The command is coded to pull the release. Are you saying when we download the zip file that is under the latest release tag we are supposed to still find the bacpac file?

**Comment by marcingminski** [comment]
Yes, correct. As long as it’s a release you will find everything you need there.

**Comment by wsmelton** [comment]
We are downloading the release...

```
$ReleasesUrl = "https://api.github.com/repos/marcingminski/sqlwatch/releases"
                $DownloadBase = "https://github.com/marcingminski/sqlwatch/releases/download/"

                Write-Message -Level Verbose -Message "Checking GitHub for the latest release."
                $LatestReleaseUrl = (Invoke-TlsWebRequest -UseBasicParsing -Uri $ReleasesUrl | ConvertFrom-Json)[0].assets[0].browser_download_url
```

**Comment by RichieBzzzt** [comment]
Hello @wsmelton !

As described in the [help for the function](https://github.com/sqlcollaborative/dbatools/blob/98f3185504de2536f1c7a109fec8dbbaf1a091d6/functions/Install-DbaSqlWatch.ps1#L20), if the ```localfile``` parameter is not specified then the latest version will be downloaded. This is in effect in an "if" statement a [few lines above the code](https://github.com/sqlcollaborative/dbatools/blob/98f3185504de2536f1c7a109fec8dbbaf1a091d6/functions/Install-DbaSqlWatch.ps1#L91) you pasted in your comment. As the OP is using this parameter, and were originally using a zip that was not a release, the original error makes sense.
