### ISSUE TITLE
Won't Import From UNC Path

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#5131]
## Steps to Reproduce
```powershell
Import-Module '\\someuncpath\Modules\dbatools\dbatools.psm1'
```

## Expected Behavior
Module works as advertised.

## Actual Behavior
Module fails to import with "The given path's format is not supported." errors.

@FriedrichWeinmann and I ran across this issue with PSFramework as well. When using Resolve-Path it's necessary to look at the ProviderPath property. I was able to resolve this locally by making that change in the dbatools.psm1 and bin\library.ps1 files.

https://github.com/PowershellFrameworkCollective/psframework/issues/227

**Comment by wsmelton** [comment]
Why in the world you want to run modules from a network share? Are you actually adding that UNC path to your default modules path for users?

**Comment by awickham10** [comment]
The UNC path is registered in `$env:PSModulePath` on our servers so we can "deploy" a new version to all of our servers. It's not ideal, but it works (worked).

**Comment by awickham10** [comment]
@wsmelton do you have recommendations on managing PowerShell modules across your server estate?

**Comment by wsmelton** [comment]
I would use PowerShell DSC where I am allowed.

You can see example configuration for deploying dbatools module specifically at the bottom end of [this MSSQLTips article](https://www.mssqltips.com/sqlservertip/4971/desired-state-configuration-for-sql-server--configurations/).
