### ISSUE TITLE
Get-DbaAgentOperator email address character limit

### ISSUE THREAD

**Issue by labyrinthsystems** [sqlcollaborative/dbatools#5136]
Hi, 

There seems to be a character limit of 101 on the email address. Just suggesting if this can be increased?

Thanks!

**Comment by wsmelton** [comment]
We have no control over this as it is a limitation of SMO and the view used to pull the information from msdb.

The limit on the field entry is 128 ([ref](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-notify-operator-transact-sql?view=sql-server-2017#arguments)).
The limit on the field read is 101 ([ref](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysoperators-transact-sql?view=sql-server-2017)).
