### ISSUE TITLE
RFC: Have contributions require entry on CHANGELOG.md

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#5137]
This is something I have seen a lot of Microsoft repositories do, even though they have community maintainers they want the author of the PR to add an entry (simply sentence) describing what fix the PR is addressing. [An example of PR I did for SqlServerDsc module](https://github.com/PowerShell/SqlServerDsc/pull/1208/files).

This would obviously work best if EVERYONE did it and we didn't approve a PR until this was done. We do not have to stick with any PR has to have an issue (even though proper tracking of problems is best done that way...and it just looks good for PRs to be closing issues 🚶 ), but it should not be difficult for us to simply include a header on the change log after we merge to master for a release. We can simply have a `## Next release` added and then any PR coming in after that will need to add their entry below that line.

You will see conflicts in PRs because everyone would be changing the change log file. However it is a simple fix that the author would be doing prior to having their PR merged by us.

**Comment by wsmelton** [comment]
We would update the contribution guide to account for this if all agree.

**Comment by alevyinroc** [comment]
I think if we give people a reasonable template to work from, it's a good idea.

**Comment by wsmelton** [comment]
Well we can add comments in markdown that are not printed as place markers.

We could also work out sections for a given release cycle. Examples: Doc Updates, New Commands, Bug Fixes, and then maybe include Breaking Changes.

**Comment by wsmelton** [comment]
For 1.0 release any module wide change that is breaking change will have to be put in as an issue so it can be tracked and referenced easily.

Those would be things that would go under breaking changes. Some thing that may break a given command could be iffy based on whether it was too fix a bug or not. If it was fixing a broken feature that already didn't work out is not really a breaking change to me.

**Comment by wsmelton** [comment]
Branch added on what I'm seeing added to the changelog for contributors.

We can put up a simple wiki page for this as well to reference with a redirect like `dbatools.io/change` and add it to the PR template. (Wanting to simplify that template as well.)
