### ISSUE TITLE
New-DBALogin - Bug in creating windows login

### ISSUE THREAD

**Issue by supercyberal** [sqlcollaborative/dbatools#5138]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [ ] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

Note that we do not have the resources to make `Copy-DbaDatabase` work in every environment. Instead, we try to ensure Backup & Restore work in your enviornment.

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
$cSQLInst = "SERVER\INST"
$cLoginName = "DM\weinser-adm"
$cDefaultDB = "NewDB"

# Windows Login.
New-DbaLogin -SqlInstance $cSQLInst -Login $cLoginName -DefaultDatabase $cDefaultDB -Force -Verbose
```

## Actual Behavior

VERBOSE: Performing the operation "Creating login [DM\weinser-adm] on SERVER\INST" on target "SERVER\INST".
VERBOSE: [12:59:50][New-DbaLogin] Adding as login type WindowsUser
VERBOSE: [12:59:50][New-DbaLogin] Failed to create [DM\weinser-adm] on SERVER\INST using SMO, trying T-SQL.
WARNING: [12:59:50][New-DbaLogin] Failed to add [DM\weinser-adm] to SERVER\INST. | Unclosed quotation mark after the character string '[DM\weinser-adm] FROM WINDOWS WITH  CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF'.
Incorrect syntax near '[DM\weinser-adm] FROM WINDOWS WITH  CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF'.

## Environmental data

 - PowerShell: 
 - - SQL Server:

**Comment by nvarscar** [comment]
Based on the verbose output, it seems that the login string that you have provided contains square brackets ('[login]'). The login name string should not contain those symbols.

**Comment by potatoqualitee** [comment]
agreed, cannot repro

![image](https://user-images.githubusercontent.com/8278033/54498114-08a0db80-4903-11e9-83de-93456d5d6d47.png)

I can, however,  strip the SMO part of the brackets, let's see
