### ISSUE TITLE
Set-DbaAgReplica command doesnt seems to include changes for property SessionTimeout

### ISSUE THREAD

**Issue by goodsoul1914** [sqlcollaborative/dbatools#5139]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

* Clear/concise description of what the problem is that the new feature can solve.

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.

**Comment by wsmelton** [comment]
We need a bit more detail...

**Comment by goodsoul1914** [comment]
Get-DbaAgReplica command returns SessionTimeout metric(default value 10)
this metric is changeable, but Set-DbaAgReplica command doesnt seems to have this metric, so when I run 
Set-DbaAgReplica -SqlInstance 'sql1' -Replica 'sql2' -AvailabilityGroup agSQLDB -SessionTimeout 20
I am getting "Set-DbaAgReplica : A parameter cannot be found that matches parameter name 'SessionTimeout'.
At line:1 char:123
+ ... ash-db37,61415' -AvailabilityGroup agBigDataImport -SessionTimeout 20"
MSFT page: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/change-the-session-timeout-period-for-an-availability-replica-sql-server?view=sql-server-2017
powershell command to change it:
Set-SqlAvailabilityReplica -SessionTimeout 15 `   
-Path SQLSERVER:\Sql\PrimaryServer\InstanceName\AvailabilityGroups\MyAg\AvailabilityReplicas\MyReplica

**Comment by wsmelton** [comment]
For whoever wants to tackle this one, we should enforce an error or warning to be sent if they set the timeout value less than 10 seconds, and include short link to the following: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/change-the-session-timeout-period-for-an-availability-replica-sql-server?view=sql-server-2017#Recommendations

> We recommend that you keep the time-out period at 10 seconds or greater. Setting the value to less than 10 seconds creates the possibility of a heavily loaded system missing PINGs and declaring a false failure.
