### ISSUE TITLE
Get-DbaDbFile - incorrectly accounting for pages when calculating NextGrowthEventSize 

### ISSUE THREAD

**Issue by IsItGreyOrGray** [sqlcollaborative/dbatools#5147]
The NextGrowthEventSize value returned by Get-DbaDbFile appears to be calculated incorrectly due to a double accounting for pages on non-percent growth types and by not accounting for pages on percent growth types.

## Steps to Reproduce

```sql
/**** create a temporary database for example ****/
CREATE DATABASE [SizeTestDB]
 ON  PRIMARY 
( NAME = N'SizeTestDB', FILENAME = N'C:\TempDatabase\SizeTestDB.mdf' , SIZE = 256MB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SizeTestDB_log', FILENAME = N'C:\TempDatabase\SizeTestDB_log.ldf' , SIZE = 256MB , MAXSIZE = 2048GB , FILEGROWTH = 10%)


```

```powershell
Get-DbaDbFile -sqlinstance localhost -database SizeTestDB
```

## Expected Behavior

For the .mdf, the NextGrowthEventSize should be 64 MB and for the .ldf it should be 25.6 MB

## Actual Behavior

For non-Percent growth types it looks like it may be trying to calculate pages twice. The underlying T-SQL gets the [growth] value and multiplies it by 8 initially
```sql
case mf.is_percent_growth when 1 then df.growth else df.Growth*8 end as Growth
```
...but then that result is multiplied by 8 again in the powershell
```powershell
 $nextgrowtheventadd = [dbasize]($result.Growth * 8 * 1024)
```
So the .mdf file's 64 MB (8192 pages) growth value ends up calculated to a NextGrowthEventSize of 512MB instead of the expected 64 MB. I think one of the page conversions should be removed.

For Percent growth types the underlying T-SQL gets the [growth] value and it is multiplied in Powershell against the size value which doesn't appear to be converted from pages. So the 256 MB (32768 pages) .ldf file with a 10% growth type is showing a NextGrowthEventSize of 3.20 MB instead of 25.6 MB. 

```powershell
$nextgrowtheventadd = [dbasize]($result.size * ($result.Growth * 0.01) * 1024)
```
Should be something like
```powershell
$nextgrowtheventadd = [dbasize]($result.size * 8 * ($result.Growth * 0.01) * 1024)
```

![image](https://user-images.githubusercontent.com/33128934/53755008-b677a900-3e72-11e9-9de8-f6256db218bc.png)

## Environmental data

 - PowerShell: 5.1.17134.590
 - - SQL Server: Microsoft SQL Server 2016 (SP1-CU7-GDR) (KB4057119) - 13.0.4466.4 (X64)

**Comment by potatoqualitee** [comment]
Thanks Gry, any chance you'd be able to fix this as well? Math is not my forte. If not, let me know and I'll holler to another fixer.

**Comment by IsItGreyOrGray** [comment]
Sure thing. I've created a pull request with the change.

**Comment by potatoqualitee** [comment]
awesome! thank you so much 🙇🙇
