### ISSUE TITLE
Azure SQL Database - Sign in as Azure AD Account Failure

### ISSUE THREAD

**Issue by SquirrelAssassin** [sqlcollaborative/dbatools#5148]
Haven't had alot of time but you need to add in a switch for azure databases for Azure AD creds.  I looked into the connection script and your adding in Integrated Security=True into the connection string this needs to be removed.  This should fix the The target principal name is incorrect.  Cannot generate SSPI context.

The connection string keyword Integrated Security=True is not supported for connecting to Azure SQL Database.
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication-configure

**Comment by SquirrelAssassin** [comment]
fixed in 0.9.784

**Comment by potatoqualitee** [comment]
I'm still working out a bug with context changing, please let me know if you run into issues and if so, give me a lil bit of info on what db right are assigned to that user
