### ISSUE TITLE
Restore-SqlBackupFromDirectory NoRecovery

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#516]
Is this a *feature* OR *bug*:
Bug
- Powershell Version:  4.0
- OS Version:  Windows 2012 R2

**Steps to Reproduce**
 Restore-SqlBackupFromDirectory -SqlServer TestServer -Path '\\UNCPath\Backups\TestServer$InstanceName\' -Databases TestDatabase-NoRecovery 

When trying to restore a database with and leaving it in NoRecovery by specifying the -NoRecovery parameter, the database is recovered.  When leaving off that option, it throws an error, but still recovers the database.  Also noticed that databases in full recovery mode with Differential backups and Log backups, do not get those restores.  It looks like from the output that just the full restore is being done.

**Action Results**

**Expected Results**

**Additional comments**

**Comment by dczarny** [comment]
I think I figured out the issue.  In Ola's routine, the folder that would be created for a sql server named instance would be \\UncPath\Backups\Server$NamedInstance.  That $NamedInstance seems to be the problem in the $Path variable.  How can you pass in the Server$NamedInstance path in powershell?

**Comment by dczarny** [comment]
Maybe that's not it.  The full backup gets restored, just not the Diff and Logs, so it's probably not the $Path variable.

**Comment by dczarny** [comment]
Maybe this is it.  If you restore the full database on line 240, but the database isn't restored with NoRecovery, then it won't be able to restore the Differential and Log backups either.  The thing is I don't know that its even getting into the If ($result -eq $true) or If ($diff) statements, because I don't get any message or error that it tries to restore the differential or log backups.

$result = Restore-Database $server $dbname $full "Database" $filestructure

**Comment by ctrlbold** [comment]
@dczarny awesome thanks for looking this up. hopefully it'll be fixed by next week -- i want to show it in a demo next week!

**Comment by dczarny** [comment]
I think that script would be handy in an emergency to get a bunch of databases restored in a hurry. I was actually testing it because I was trying to see if I could use it to setup log shipped.

Thank you,
Derek Czarny


________________________________
