### ISSUE TITLE
Dbatools latest version gives an error Unable to find type [DbaInstanceParameter].

### ISSUE THREAD

**Issue by eyasu127** [sqlcollaborative/dbatools#5160]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

[error.txt](https://github.com/sqlcollaborative/dbatools/files/2938099/error.txt)

i attached the error i get excuting the command $error | Export-Clixml "$env:USERPROFILE\desktop\error.xml"

**Comment by wsmelton** [comment]
This is from your system not loading the module completely.

Please try a new PowerShell session and see if you can import the module with no errors.

**Comment by eyasu127** [comment]
@wsmelton this has been occurring on and off for a long time. sometimes it works fine and the other time it doesn't work (right now it is not working). I have tried replacing the module with the latest version and import it but no luck. The import command don't throw any error. A few days ago when it occur i rebooted my system and it starts working and next time it occurred i rebooted and it didn't solve the issue. I am wondering if there is any permanent fix for that?  Thank you in advance!

**Comment by eyasu127** [comment]
In addition to the above.. i am testing it on 3 different servers and they all have the same issue.

**Comment by wsmelton** [comment]
What version of PowerShell? What version of Operating System?

In a new session run the following:

```powershell
$error.Clear()
Import-Module dbatools
$error | select *
```

**Comment by eyasu127** [comment]
the powershell version is 5.1.15063.1563 and i am using windows 10 and server 2012 R2. I ran the script. please take a look at the picture 
![image](https://user-images.githubusercontent.com/48296937/53915016-0306e400-402d-11e9-9273-cbb19046748f.png)

**Comment by eyasu127** [comment]
and i am still getting the error 
![image](https://user-images.githubusercontent.com/48296937/53915125-55e09b80-402d-11e9-88dd-33edbb7408e2.png)

**Comment by wsmelton** [comment]
What command are you trying to use?

**Comment by eyasu127** [comment]
New-DbaLogin

**Comment by eyasu127** [comment]
@wsmelton i get the below error when i import the module. At this time i use my own named session instead of running the PS as administrator

import-module : The member 'TypesToProcess' in the module manifest is not valid: Cannot find path C:\Program Files\WindowsPowerShell\Modules\dbatools\xml\dbatools.Types.ps1xml' because it does not exist.. Verify that a valid value is specified for this field in the
'C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1' file.
At line:1 char:1
+ import-module dbatools
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...s\dbatools.psd1:String) [Import-Module], ArgumentException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by wsmelton** [comment]
This is going to be environmental issue. You are missing files in the
module. They exist on the gallery but something on your side is not
downloading them all.

You can try to use Save-Module to a different location or install the
module to CurrentUser scope to see if that will let you import the module
cleanly.

**Comment by potatoqualitee** [comment]
totally agreed, fortunately, it's just that some files are missing

**Comment by eyasu127** [comment]
Hmm.. i am not sure what to say about this...i am not sure what is causing this...i did like you suggested i saved the module and imported it with out error. I then created a login using New-DbaLogin it works fine...i then tried to create a second login the error occurred again. This is becoming a mystery to me..! Please look at the error below
![image](https://user-images.githubusercontent.com/48296937/53962272-9df8d000-40b8-11e9-84f8-98b9b66361d6.png)

**Comment by wsmelton** [comment]
That error simply means the type library of not loading. You have something
removing or blocking the files. It is not specific to the module or
anything we are don't in the module itself.

**Comment by wsmelton** [comment]
All I can recommend is checking your AV or endpoint protection software running on your machine. That is generally what blocks dll files from being loaded in PowerShell.

You need to give us more details on the machine, environment and what you are doing. You stated you ran it a second time and the error occurred, was that in the same session | did you restart and then try to create a second login | did you import using the saved module or use the module version you installed from the gallery? Does it happen on another machine? Does the module work from the server itself (you noted Window Server 2012 R2)? What policies or software are in place on your Windows 10 machine?

There are to many variables for us to guess as to why the module is having problems loading in your environment. You will need to troubleshoot to nail down why that dll is not being allowed to load in your session.
