### ISSUE TITLE
Get-DbaLogin -WindowsLogins Doesn't Include Groups

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#5165]
## Steps to Reproduce
```powershell
Get-DbaLogin -SqlInstance MyServer | Select LoginType -Unique

# Output: SqlLogin, WindowsGroup, WindowsUser
```

```powershell
Get-DbaLogin -SqlInstance MyServer -WindowsLogins | Select LoginType -Unique

# Output: WindowsUser
```

```powershell
Get-DbaLogin -SqlInstance MyServer -Type Windows | Select LoginType -Unique

# Output: WindowsUser
```

## Expected Behavior
Windows groups and Windows users should be returned.

## Actual Behavior
Only WindowsUser logins are returned.

## Environmental data
 - PowerShell: 5.1.14393.2791
 - SQL Server: Microsoft SQL Server 2008 R2 (SP3-GDR) (KB4057113) - 10.50.6560.0 (X64)   Dec 28 2017 15:03:48   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

**Comment by awickham10** [comment]
I'm going to submit a PR for this in a bit, just wanted to get the issue out there.

**Comment by niphlod** [comment]
perfect. Maybe put an example on how to pipeline groups to Find-DbaLoginInGroup ^_^

**Comment by awickham10** [comment]
> perfect. Maybe put an example on how to pipeline groups to Find-DbaLoginInGroup ^_^

I could be misunderstanding your purpose but it doesn't look like that's possible? Find-DbaLoginInGroup accepts -SqlInstance from the pipeline.

So `Get-DbaLogin -SqlInstance 'MyServer' -WindowsLogins -IncludeFilter *Test* | Find-DbaLoginInGroup` would be functionally no different than `Find-DbaLoginInGroup -SqlInstance MyServer`.
