### ISSUE TITLE
Set-DbaMaxDop does not work with SQL Logins

### ISSUE THREAD

**Issue by mshamann** [sqlcollaborative/dbatools#517]
Is this a *feature* OR *bug*:
Bug 

- Powershell Version: 5 
- OS Version: Windows 10 

**Steps to Reproduce**
Attempt to set the MaxDop to a server using an SQL Login Credential, it will fail because there is no SQL credential being passed to the Test-DbaMaxdop on lines 119 - 126 

**Action Results**

Fails to connect, and stops the Set 

**Expected Results**
It sets the maxdop 

**Additional comments**

I have a PR coming for this. Just wrapping up testing.

**Comment by SirCaptainMitch** [comment]
This was merged, Closing.
