### ISSUE TITLE
tepp broken

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5171]
I checked and tepp is not disabled. please help!

![image](https://user-images.githubusercontent.com/8278033/54078104-d9ff8100-42c2-11e9-8644-2ecf5d0098d7.png)

**Comment by wsmelton** [comment]
Sad to say this has been broken for very long time. It has rarely ever worked for me from the beginning.

**Comment by FriedrichWeinmann** [comment]
And somebody removed the scripts that gather data from the import sequence ...
The latest parameter class update also broke things (currently working on that)

**Comment by potatoqualitee** [comment]
thanks for looking into this! 💯

**Comment by potatoqualitee** [comment]
@wsmelton - try it, it worked for me. note there is a 15 second delay after import.
