### ISSUE TITLE
While doing Start-DbaMigration, -SetSourceRedOnly fails if there are even inactive sessions on database

### ISSUE THREAD

**Issue by TheVladdestVlad** [sqlcollaborative/dbatools#5177]
During Start-DbaMigration, if -SetSourceReadOnly is specified, but there are still sessions on the source database, the database will not be switched to read-only before the backup starts.
Tested with the latest version on migrations from SQL Server 2005, 2008R2 and 2012 to SQL Server 2016SP2CU2.
I've put together the following command to run while dbatools attempted to put the databases in read-only so that i would avoid this issue during the migration and not end up with possible inconsistencies between the time of the backup and the actual cut-over to the new instance (time frame ranging from a few minutes to a couple of hours depending on size of the instance).
###
[KillSessionForDBMigration.txt](https://github.com/sqlcollaborative/dbatools/files/2949759/KillSessionForDBMigration.txt)

**Comment by potatoqualitee** [comment]
LOL your username is aweosme, thanks for the bug report

**Comment by TheVladdestVlad** [comment]
Thanks, i was out of username ideas so i just went with my Twitter handle 😄
