### ISSUE TITLE
Start-DbaMigration issue with DBs where the login is mapped to the dbo user of a DB

### ISSUE THREAD

**Issue by TheVladdestVlad** [sqlcollaborative/dbatools#5181]
When migrating databases and logins using Start-DbaMigration, if on the source instance a login is mapped to a database using the dbo database user instead of a dedicated database user, the mapping will be lost on the target instance and it will result in a login error since the login no longer has access to the database specified in the application's connection string.

This happens with the latest version of dbatools when migrating from SQL Server 2005, 2008, 2008R2 and 2012 to 2016SP2CU2.

I'm not sure if this is a bug, more like a result of bad database security configuration, but could it be possible for dbatools to either output a list of logins mapped to dbo in the database(s) of the source instance when execution completes or to fix the mapping on the target side by creating a dedicated database user mapped to the login and adding it to the db_owner role?

Could probably be done by building a temp LoginMapping table, inserting the results of `EXEC master..sp_msloginmappings` into it and then do a  

```sql
SELECT LoginName
            , DBName 
FROM LoginMapping 
WHERE UserName = 'dbo' 
  AND LoginName <> 'sa'
```

to build the list of logins mapped to dbo.

**Comment by wsmelton** [comment]
Just to note that any `sysadmin` will map to `dbo` user by default, that is how they explicitly get permission to every database. However, what you are seeing is an old option that is no longer allowed in newer releases of SQL Server. 

This is not a bug but an environmental configuration issue. You would need to address that prior to migrating the databases. You can find those users by using `Get-DbaDbUser` or `Get-DbaLogin` and see which ones are mapped to dbo. We can't start modifying the start command to handle every environment configuration that is possible, or allowed by older versions and not for newer.
