### ISSUE TITLE
AzureStack and alt domains

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5196]
https://docs.microsoft.com/en-us/cli/azure/manage-clouds-azure-cli?view=azure-cli-latest

check out the urls, will need to add an isAzure param or Set-DbatoolsConfig

https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-connect-ssms

**Comment by mscodebum** [comment]
finally getting back around to this, it appear that having Config for the domain suffix would be the best way to go and by default possibly set it to database.windows.net. Many individuals that use the different clouds already have to switch away from this default. Setting the AD Domain / Tenant ID may be another thing that may need to be set to that (federated) authenticaiton can complete though like other tools the default method should be username and password.

**Comment by potatoqualitee** [comment]
ouu i like that solution, thanks! will take a look sometime soon.
