### ISSUE TITLE
Please add -Listener parameter to Add-DbaAgListener

### ISSUE THREAD

**Issue by mikepetrak** [sqlcollaborative/dbatools#5207]
---
name: Feature request/idea :bomb: Please add -Listener parameter to Add-DbaAgListener
about: Please add -Listener parameter to Add-DbaAgListener

---

### Summary of new feature

Add-DbaAgListener creates the listener name based on the AvailabilityGroup parameter.
If one wants a listener name that is different than the AvailabilityGroup name or wants multiple listeners for an AvailabilityGroup, this isn't supported.

https://docs.dbatools.io/#Add-DbaAgListener
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/create-or-configure-an-availability-group-listener-sql-server?view=sql-server-2017

"You can create only one listener per availability group through SQL Server. Typically, each availability group requires only one listener. However, some customer scenarios require multiple listeners for one availability group. After creating a listener through SQL Server, you can use Windows PowerShell for failover clusters or the WSFC Failover Cluster Manager to create additional listeners."

### Latest version of dbatools as of writing

0.9.784

**Comment by wsmelton** [comment]
Duplicate. #5000

**Comment by mikepetrak** [comment]
Sorry. Thanks, @wsmelton .
