### ISSUE TITLE
Update parameter ConnectionModeInSecondaryRole to include SSMS options

### ISSUE THREAD

**Issue by mikepetrak** [sqlcollaborative/dbatools#5211]
---
name: Map -ConnectionModeInSecondaryRole to SSMS options for `Set-DbaAgReplica` & `New-DbaAvailabilityGroup`
---

### Summary of new feature

* Map the SMO options for the "ConnectionModeInSecondaryRole" parameter in Set-DbaAgReplica and New-DbaAvailabilityGroup (and any others Ag functions where it's used) to the SSMS options to make it more friendly and intuitive for most users who know the options from SSMS.

### Proposed technical details (if applicable)

From dbatools Slack channel discussion: @wsmelton : "Yeah, if you want to submit a feature @mikepetrak we can make those values map up to the selections that SSMS sees (we have done this for a few other commands). In general the options SSMS will show in wizards are not going to marry up to what SMO options are....just a UI thing in SSMS to make it more user friendly.

I think it would be a bit more friendly to adjust how we handle that particular one just because it is so commonly done via SSMS and that will be the options most users know anyway."

Here is the mapping from SMO to SSMS:

AllowNoConnections -> No
AllowReadIntentConnectionsOnly -> Read-intent only
AllowAllConnections -> Yes

As a sidenote, SSMS defaults to No and New-DbaAvailabilityGroup defaults to AllowAllConnections = Yes.

### Latest version of dbatools as of writing

0.9.784

**Comment by andreasjordan** [comment]
@potatoqualitee / @wsmelton : Why is this still open?
