### ISSUE TITLE
Remove-DbaDatabaseSafely - rewrite and standardize for 1.0 release

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#5213]
This is a dated command and needs to be rewritten to the standard we have for commands now.

In doing this it should also resolve #5210

**Comment by wsmelton** [comment]
As part of rewrite....we need to know why this is even required `runs the agent job to restore the database`

**Comment by potatoqualitee** [comment]
that was to ensure it worked, but perhaps should only be invoked with -InvokeTest or something

**Comment by wsmelton** [comment]
Ensure what worked?

**Comment by wsmelton** [comment]
Regardless of that we need to remove all of the code trying to work with the SQL Agent service....that should have been out of scope for this and is not required to just create the job and all. If the Agent service is found stopped you can simply output a message/warning that it is.

**Comment by potatoqualitee** [comment]
this was really tough the last time i tried to rewrite it. i may remove.

**Comment by potatoqualitee** [comment]
i tried and failed. asked @ClaudioESSilva to take a look.

**Comment by ClaudioESSilva** [comment]
Regarding the Job @wsmelton iirc the idea was to craete, run from there and keep it there in case of needed to "rollback".
I will come back

**Comment by potatoqualitee** [comment]
yes thgat is legit but the command is checking to see if the service is running and if not then starting it

**Comment by ClaudioESSilva** [comment]
But that make sense regarding @SQLDBAWithABeard's original idea. 
I will see what's there and we can discuss what make sense to keep/change 😃

**Comment by potatoqualitee** [comment]
yes, but since the module has evolved, that type of approach would be too broad of a scope. and it would be caught by our other DbaAgent commands. please do remove.

**Comment by potatoqualitee** [comment]
🏆 🏆 🏆 🏆 🏆 🏆 vv
