### ISSUE TITLE
duplicate command name

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5229]
can anyone help? @wsmelton  or @jpomfret perhaps?

I have a duplicate command somewhere in the psd1 or psm1 and im terrible at finding these, @gbargsley may have found it once too. i think it's some ps1 indexing that can do it.

![image](https://user-images.githubusercontent.com/8278033/54501047-08b0d380-4923-11e9-8a46-258b7c1c98d7.png)

**Comment by wsmelton** [comment]
I can work on this tonight....

**Comment by wsmelton** [comment]
This is my result @potatoqualitee 

```powershell
> $d = Import-PowerShellDataFile -Path .\dbatools.psd1
[PS 5.1] [23:07:20] [  0.0ms ][ git:development ]
 C:\git\dbatools
> $d.FunctionsToExport | Group-Object | where Count -gt 1

Count Name                      Group
----- ----                      -----
    2 New-DbaDbMailAccount      {New-DbaDbMailAccount, New-DbaDbMailAccount}
```

**Comment by wsmelton** [comment]
It is from line: 458 and 365

**Comment by potatoqualitee** [comment]
yay thank you :D will submit a PR

**Comment by potatoqualitee** [comment]
thanks for the code btw! way easier than i expected

**Comment by potatoqualitee** [comment]
need to see how @jpomfret made a test to ensure all commands have a test, then tack on this as a test as well

**Comment by wsmelton** [comment]
@potatoqualitee it is right here: sqlcollaborative/dbatools-templates#21

**Comment by wsmelton** [comment]
https://github.com/sqlcollaborative/dbatools/blob/ee4a3948b743d378dae6c388c27d189843262f8d/tests/dbatools.Tests.ps1#L140-L154
