### ISSUE TITLE
Set-DbaMaxMemory fails on SQL Login with Sql Credential

### ISSUE THREAD

**Issue by mshamann** [sqlcollaborative/dbatools#525]
Is this a *feature* OR *bug*:
Bug
- Powershell Version:  5
- OS Version: Windows 10 

**Steps to Reproduce**
Attempt to set the max memory of an SQL Instance with an SQL Login with Sysadmin privileges 

**Action Results**
Fails to connect when running Test-DbaMaxMemory

**Expected Results**
That it connects and sets the max memory

**Additional comments**
Have PR coming in to Fix this in a second.

**Comment by SirCaptainMitch** [comment]
This was merged, closing.
