### ISSUE TITLE
Test-DbaBuild - SupportedUntil dates inconsistent for 2014

### ISSUE THREAD

**Issue by flyfishingdba** [sqlcollaborative/dbatools#5259]
For SQL Server 2014 SP3, SupportedBuild is returning the Mainstream Support End Date, but earlier SPs return the Service Pack Support End Date, which is later. As a result, early SPs show as supported longer than the newest one.

## Steps to Reproduce

```powershell
PS> test-dbabuild -sqlinstance Server1 -maxbehind "1SP"


Build          : 12.0.6024
BuildLevel     : 12.0.6024
BuildTarget    : 12.0.5000
Compliant      : True
CULevel        :
CUTarget       :
KBLevel        : 4022619
MatchType      : Exact
MaxBehind      : 1SP
NameLevel      : 2014
SPLevel        : {SP3, LATEST}
SPTarget       : SP2
SqlInstance    : Server1
SupportedUntil : 9/7/2019 12:00:00 AM
Warning        :



PS> test-dbabuild -sqlinstance Server2 -maxbehind "1SP"


Build          : 12.0.5600
BuildLevel     : 12.0.5600
BuildTarget    : 12.0.5000
Compliant      : True
CULevel        : CU14
CUTarget       :
KBLevel        : 4459860
MatchType      : Exact
MaxBehind      : 1SP
NameLevel      : 2014
SPLevel        : SP2
SPTarget       : SP2
SqlInstance    : Server2
SupportedUntil : 1/14/2020 12:00:00 AM
Warning        :
```

## Expected Behavior

Newer builds should show later SupportedUntil value than older builds

## Actual Behavior

Older builds are showing later SupportedUntil value than newer builds

**Comment by potatoqualitee** [comment]
hey team, just tagging anyone that may be interested in addressing this one 👍

**Comment by jpomfret** [comment]
Should be resolved by fixing the dates in the build ref.. I can test Monday or @flyfishingdba if you can pull down PR #5294 and test it that would be awesome sauce.
