### ISSUE TITLE
Add Azure MI support to Copy-DbaDatabase/Start-DbaMigration

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5267]
https://twitter.com/JovanPop_MSFT/status/1108542165154566144

**Comment by potatoqualitee** [comment]
Get Copy-DbaDatabase to work with URLs

**Comment by sqllensman** [comment]
My workplace is currently testing a migration of around 50Tb of data across multiple instances to MI. I will probably try to get dbatools working to reduce effort for this

**Comment by Stuart-Moore** [comment]
copy-dbadatabase working with MI and URLs with PR #5322

**Comment by Stuart-Moore** [comment]
@sqllensman if you could do some scale testing that'd be great. We've only got a small test rig, so be nice to get some numbers for larger copies

**Comment by potatoqualitee** [comment]
good enough for now 👍
