### ISSUE TITLE
Add-DbaDbTable

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5272]
from someone who uses chad miller's `Add-SqlTable -ServerInstance "$svr" -Database "$dbase" -TableName "$tbl" -DataTable $dt`

i like the idea of using a datatable.

http://www.dbascript.com/add-sqltable

It's basically what -AutoCreateTable will do but also allow for a regular SMO table to be made.

**Comment by ms-217** [comment]
Following

**Comment by potatoqualitee** [comment]
add-dbadbtable will be in the `prerelease` branch by tonight but wont be released publicly until june 20
