### ISSUE TITLE
Set-DbaAgentSchedule question

### ISSUE THREAD

**Issue by goforebroke** [sqlcollaborative/dbatools#5288]
trying to follow the documentation, but cant seem to get this right...

I want to update and existing schedule to that runs daily every 30 minutes to daily every 15 minutes.

```powershell
Set-DbaAgentSchedule -SqlInstance "SQL/SQL1" -Job "My JOB" -ScheduleName "Daily" -Enabled  -FrequencyType Daily -FrequencySubdayType Minutes -FrequencySubdayInterval 15
```

but I keep getting an the following warning...

> WARNING: [14:44:46][Set-DbaAgentSchedule] The interval  needs to be higher than 1 and lower than 365 when using a daily frequency the interval.

Any help would be appreciated..

**Comment by sanderstad** [comment]
Fixed the assignment of the interval when daily is chosen.

![image](https://user-images.githubusercontent.com/6154981/56188658-602b8780-6026-11e9-944e-975df5f8ca69.png)
