### ISSUE TITLE
Set-DbaStartupParameter - Examples and bug with trace flag

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#5292]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

This command overall just needs to be reworked/reviewed for 1.0 release.

## Steps to Reproduce

```powershell
Set-DbaStartupParameter -SqlInstance myserver -TraceFlags 1117,1118 -WhatIf
```

## Bug 1

`-TraceFlags` should be singular

## Bug 2

The examples show passing in TraceFlags parameter with `-SingleUser` which is not realistic to be done. Unless I'm missing something

## Bug 3

Issuing the above command spits out this warning:

> WARNING: [10:55:51][Set-DbaStartupParameter] MasterData value must be provided

So that parameter is not validated to be provided at all, nor do I think it is required to just change trace flags.

~~## Bug 4~~

~~I don't know where this comes from but I'm running this on my localhost (dev machine) that is just a workgroup, so this may be from that fact alone. The what if output:~~

~~> What if: Performing the operation "Set variable" on target "Name: __dbatools_interrupt_function_78Q9VPrM6999g6zo24Qn83m09XF56InEn4hFrA8Fwhu5xJrs6r Value: True"~~

**Comment by wsmelton** [comment]
If you are setting or changing startup parameters why would we need a connection to the instance at all? You don't change those settings via T-SQL so there is no reason to make that connection.

**Comment by potatoqualitee** [comment]
Thanks for looking into this. Bug 4 is not a bug. You'll see that on any command that uses Test-FunctionInterrupt. It's ugly but it's necessary.

**Comment by wsmelton** [comment]
But that shouldn't be output at all then... So it is a bug... Or should be more clear.

**Comment by wsmelton** [comment]
It is not part of what if operations. So if we are injecting it on there we would remove the message.

**Comment by potatoqualitee** [comment]
you would have to ask @FriedrichWeinmann about it.
