### ISSUE TITLE
Managed Instance with TrustBackupHistory

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5297]
Unhandled exception

![image](https://user-images.githubusercontent.com/8278033/54872694-916abc00-4dc8-11e9-84a2-4560653a0ddb.png)

**Comment by Stuart-Moore** [comment]
Not an MI issue, just a general issue

That's not how TrustDbBackupHistory works. That switch is designed to work with a BackupHistory object like this:
![image](https://user-images.githubusercontent.com/5613670/54918256-a729cf80-4ef5-11e9-81d0-8ec8399ce38d.png)

It won't work just pushing in a backup file. In that case we get the history object with Read-DbaBackupHistory.

I'll shove a bigger warning if a non history object comes in.

**Comment by Stuart-Moore** [comment]
fixed with #5309
