### ISSUE TITLE
GO within a transaction causes Invoke-DbaQuery to fail

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#5311]
- [x] *Running latest release of dbatools*
- [x] Verified errors are not related to permissions
- [x] If issue is with `Copy-DbaDatabase`, replicate issue using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> Note that we do not have the resources to make `Copy-DbaDatabase` work in every environment. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data
```
ame                           Value
----                           -----
PSVersion                      5.1.15063.1631
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1631
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### dbatools Module version:
Name    : dbatools
Path    : C:\Users\xxx\Documents\WindowsPowerShell\Modules\dbatools\0.9.791\dbatools.psd1
Version : 0.9.791
```

### SQL Server: 

```sql
Microsoft SQL Server 2008 (SP4-GDR) (KB4057114) - 10.0.6556.0 (X64)
```

## Steps to Reproduce

```powershell
invoke-dbaquery -SqlInstance server1 -Query 'begin tran select 1
go
rollback tran'
```

## Expected Behavior

No errors

## Actual Behavior

Failed during execution | The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION.

**Comment by wsmelton** [comment]
The way we support the GO separator your scenario is not going to be possible to support at all.

We cannot differentiate between when a given set of statements should be executed as one statement and when it shouldn't. You basically need to remove the `GO` and don't use it at all. You cannot solve this with regex because those two keywords could be used in normal code in some fashion or another....it would not be consistent to validate and guarantee.

**Comment by nvarscar** [comment]
I'll do some testing when I have time, but theoretically, what if there was a switch -SingleTransaction that wraps all the statements into a single transaction? Technically, we don't need to modify SQL in this case, the connection object has .BeginTransaction() method. Said transaction will take care of handling multiple batches in the query.

**Comment by davesbrown** [comment]
> The way we support the GO separator your scenario is not going to be possible to support at all.
> 
> We cannot differentiate between when a given set of statements should be executed as one statement and when it shouldn't. You basically need to remove the `GO` and don't use it at all. You cannot solve this with regex because those two keywords could be used in normal code in some fashion or another....it would not be consistent to validate and guarantee.

I initially brought up this issue with @nvarscar over slack.  My particular issue was with using Redgate tools to generate the script, which can be several thousands lines long with multiple go statements along between with the BEGIN and COMMIT transaction.  Seems counter productive to script out another regex to remove the GO's for automation?  The current sqlserver module Invoke-Sqlcmd works.

**Comment by GeorgePalacios** [comment]
> I'll do some testing when I have time, but theoretically, what if there was a switch -SingleTransaction that wraps all the statements into a single transaction? Technically, we don't need to modify SQL in this case, the connection object has .BeginTransaction() method. Said transaction will take care of handling multiple batches in the query.

As a potential downside to this idea, if the script involves the use of an explicit ROLLBACK statement it could roll back the whole script rather than the statements that the user intended to roll back, due to MS odd implementation of nested transactions.

**Comment by niphlod** [comment]
Invoke-DbaQuery is not Invoke-Sqlcmd
Invoke-DbaQuery is not Invoke-SQLScript
Invoke-DbaQuery is meant to run *queries*

**Comment by potatoqualitee** [comment]
Unsure where to go with this. @niphlod says it's as designed, @nvarscar would like it work. Please revisit and update 🙏

**Comment by potatoqualitee** [comment]
Gonna take it off of 1.0 goal since solution is iffy.

**Comment by davesbrown** [comment]
> Invoke-DbaQuery is meant to run queries

Is there or plans for a dbatools script execution cmdlet?  I was not aware of Invoke-SQLScript.  Meanwhile, I'll use Invoke-Sqlcmd.

Thank you

**Comment by nvarscar** [comment]
@davesbrown if you're looking for a sql script execution framework, check out dbops module, Install-DBOSqlScript in particular.

**Comment by potatoqualitee** [comment]
Would adding that as `Invoke-DbaScript` be appropriate @nvarscar ?

**Comment by nvarscar** [comment]
@potatoqualitee That would mean shipping yet another dll (2 in fact) and some work on my end to decouple the function from the rest of the framework. As much as I would love to have all things sql to be handled by dbatools, this is probably where the borderline lays. I feel you were right back in the day encouraging me to create an independent module, cause, after all, sql deployments are a world of its own.

**Comment by potatoqualitee** [comment]
thank you for the feedback 👍 . out of curiosity, which two dlls does it use?

**Comment by nvarscar** [comment]
> thank you for the feedback 👍 . out of curiosity, which two dlls does it use?

That would be DbUp dlls, dbup-core and dbup-sqlserver.

**Comment by nvarscar** [comment]
I am actually totally fine with the way the function works right now, and opened this issue in a hope that there would be an easy fix I overlooked. Unfortunately, that doesn't seems likely anymore and, unless someone else want to spend some time on it, I would probably just close this one as 'out of scope'.

**Comment by potatoqualitee** [comment]
k sounds good, good info too for people googling similar issues
