### ISSUE TITLE
Update-Dbainstance

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5319]
This version: 12.0.5557

trying to install this version: https://support.microsoft.com/en-us/help/4482967/cumulative-update-16-for-sql-server-2014-sp2

Works when manually installing, fails on Update-DbaIntance with error 

```
internal\functions\Get-SqlServerUpdate.ps1:117:                            Stop-Function -Message "Current SP version $currentMajorVersion$currentSP is not the latest
available. Make sure to upgade to latest SP level before applying latest CU." -Continue
```
this should work, eh? Please note that upgrade is also a typo.

**Comment by nvarscar** [comment]
any chance for the -Debug output? I don't have any 2014s around :(

**Comment by potatoqualitee** [comment]
dang no :( can it be faked?

**Comment by nvarscar** [comment]
what was the original version? I'll try to mock something up

**Comment by potatoqualitee** [comment]
that was it - 12.0.5557 then i was trynna update to CU 16

**Comment by nvarscar** [comment]
oh okay, I gotchu

**Comment by nvarscar** [comment]
Mocked the exact scenario and it works when targeting CU16 specifically. Did you run it simply as `-Type CumulativeUpdate` without specifying a version? Could you provide a command line?

**Comment by potatoqualitee** [comment]
yes my apologies, i did indeed specify a version. I do wish i could have copy/pasted but i couldnt. i will close this as non repro and get much more info if it happens again. thank you for looking into it.
