### ISSUE TITLE
Getting error when trying to disable a remote computer's protocol

### ISSUE THREAD

**Issue by chirayu547** [sqlcollaborative/dbatools#5323]
### Before submitting a bug report:

**Collect output of following command and paste below:**

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.18408
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.798\dbatools.psd1
Version : 0.9.798

PS C:\Windows\system32> $test=(Get-DbaServerProtocol -ComputerName xxxx | Where-Object { $_.DisplayName = 'via' }).Disable()
Where-Object : "ProtocolDisplayName" is a ReadOnly property.
At line:1 char:71
+ | Where-Object { $_.DisplayName = 'via' }).Disabl ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Where-Object], SetValueException
    + FullyQualifiedErrorId : ReadOnlyCIMProperty,Microsoft.PowerShell.Commands.WhereObjectCommand

**Comment by StartAutomating** [comment]
I actually believe this isn't our issue at all.  It looks like | Where-Object { $_.DisplayName = 'via' } is wrong, and producing an error from the CIM cmdlets.

In PowerShell = is assignment, not equality comparison.  So that line reads "where I can set DisplayName" to via (which you never can).  To fix this, change the code to "Where-Object {$_.DisplayName -eq 'via' }.

Since this is in code calling DBATools, and not in us, I'm going to close this out.  Please try the change and you should be good to go.

**Comment by chirayu547** [comment]
Thanks James.

Maybe you should update your script comments.
EXAMPLE
    (Get-DbaServerProtocol -ComputerName sql1 | Where { $_.DisplayName =
'via' }).Disable()

**Comment by potatoqualitee** [comment]
thank you both, i have created a PR to fix the example

**Comment by StartAutomating** [comment]
Thanks for the suggestion:  I'll try to make sure answers are much more clear in the future.  Apologies for not seeing that this was an example we shipped.  Do we know of any other similar calls that may have this bad pattern?

**Comment by potatoqualitee** [comment]
> I'll try to make sure answers are much more clear in the future. Apologies for not seeing that this was an example we shipped. 

No problem, I would have assumed the same 💯  Thank you for your detailed and helpful response.

> Do we know of any other similar calls that may have this bad pattern?
Doesn't look like it but this was just a super quick scan

![image](https://user-images.githubusercontent.com/8278033/55289527-363c5900-53c8-11e9-88e7-feee7a22434f.png)

`findshit` is just a function that efficiently select strings thru my repos.
