### ISSUE TITLE
Enable/Disable Client/Server Protocol

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5327]
inspired by our example

`(Get-DbaClientProtocol -ComputerName sql2014 | 
Where-Object { $_.DisplayName -eq 'via' }).Disable()`

**Comment by andreasjordan** [comment]
Good idea. Maybe align Get-DbaClientProtocol and the new commands with Get-DbaTcpPort.

**Comment by andreasjordan** [comment]
To get an idea of how we can solve this, I've created a demo: #7358

**Comment by andreasjordan** [comment]
Demo is WMI only at the moment, will have to get into CIM...

**Comment by potatoqualitee** [comment]
is this done? or done with set?

**Comment by andreasjordan** [comment]
I'll have a look later this week.

**Comment by potatoqualitee** [comment]
yah, it's done with `-EnableProtocol` 🥳
