### ISSUE TITLE
New-DbaDiagnosticNotebook

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5328]
based off of Gianluca's wildly popular post: https://spaghettidba.com/2019/03/20/generating-a-jupyter-notebook-for-glenn-berrys-diagnostic-queries-with-powershell/

To compliment current Diagnostic commands:
![image](https://user-images.githubusercontent.com/8278033/55292543-91804280-53ec-11e9-8622-4d485da8c1bd.png)

@spaghettidba - are you interested in creating this command or would you prefer someone else take it on?

(open to a different name if anyone has a proposal)

**Comment by wsmelton** [comment]
`New-DbaDiagnosticAdsNotebook`

`AdsNotebook` = Azure Data Studio NoteBook. It makes a bit more clear, then the help we can get the ADS short url: https://aka.ms/azuredatastudio

**Comment by spaghettidba** [comment]
I can do this! Shawn's name looks ok to me.  
A few things to consider: 

1. how to accept the version as a parameter: my script accepts the path to one of the diagnostic queries, while the script to use for `Invoke-DbaDiagnosticQuery` is instead decided at runtime, based on the version of the target instance. Generating a notebook does not require a connection: can this be a straight parameter (like $TargetVersion = [2005|2008|2012|2014|2016|2016SP2|2017|2019])?

2. Do you feel like a selection helper like the one in `Invoke-DbaDiagnosticQuery` is needed? In my script I excluded database scoped queries, but I see how they could be useful for somebody.

3. Any other parameter I should add?

I tried to see how to debug dbatools when working on it locally, but I don't remember how this is done (modify allcommands.ps1? unload installed dbatools before testing?). Is there a documentation page covering this? I could not find it in the contributing guide.

**Comment by potatoqualitee** [comment]
@wsmelton - isn't this a Jupyter notebook, though? Microsoft was kind granting us the aka.ms/sqlslack url, I think if we requested a short url, adding extra wouldn't be a deciding factor. If we believe this is the first of many `Ads` commands, we could go the `DbaAds` way. I'm still not sure how to use it so don't know if there's opportunity but it kinda seems like it?'

@spaghettidba 

1. Yes, you can go one of two ways: Provide both $TargetVersion and $SqlInstance. If they use SqlInstance, then dont require a TargetVersion, otherwise, require.

2. You can skip for v1 if you like. If not, perhaps it's time to do a Get-DbaDiagnosticQuery that can feed to Out-GridView that can feed to both of your commands? Alternatively, his helper can just be busted out into an internal function so that it's shared by both if it's nto already.

3. I like the idea of DiagnosticScriptPath being optional and you figure it out based on #1 or you can make diagnosticscript pipable so they `Get-ChildItem script.sql | New-Dba...`. 

`notebookOutputPath` should probably be named FilePath unless it's a directory then that'd be Path. Also, we need the usual EnableException and wrapping of potential exceptions.  

4. Good call, we do need to add debugging info to the contributing guide. I'll take a moment to add that. If you work off of the cloned repo, it will detect `.git` and enable debugging in VS Code. allcommands.ps1 is only for end-users. Developers develop on the commands themselves in functions and internal\functions. 

If you work off of a zip file, you can extract it and create the .git folder or specify ` $script:multiFileImport = $true; $script:serialImport = $true`.

So pumped! Thanks for this 😎

**Comment by wsmelton** [comment]
The term `notebook` is not something the basic DBA or user-base we have is going to be aware of on average. It is also to generic of a Noun for me as I know the term is used as a file extension for software that has a completely different purpose than SQL Server or what a DBA might use. 

I would say we just call it `New-DbaJupyterNotebook` and make it accept an input object from anything dbatools related. Based on what Gianluca wrote you just need that preamble and then the closing braces, then dump the json in between of the data collected (spconfigure output, XEL file content, etc.).

**Comment by potatoqualitee** [comment]
I do love that idea, but, and i know this is my own peccadillo, but i dont like that name, Jupyter. I do think ADS will make notebooks totally popular and it'll become part of our vernacular. 

New-DbaAdsNotebook or New-DbaNotebook? 

I like the idea of two commands. One for generic objects and one that helps ease the diagnostics part. So Gianluca would basically wrap New-DbaAdsNotebook  and add in additional handling for diagnotebook.

OKay so

* New-DbaAdsNotebook, which is for generics and keeps options open for future potential Ads commands
* New-DbaDiagnosticNotebook, which is piled in with the other Diagnostics commands

**Comment by potatoqualitee** [comment]
hey @spaghettidba - any chance we can get this in within the next 30 days?

**Comment by potatoqualitee** [comment]
done-o-rama! 🍝
