### ISSUE TITLE
[Bug]Get-DbaComputerSystem

### ISSUE THREAD

**Issue by ggoble** [sqlcollaborative/dbatools#5336]
### PowerShell version:
Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.771\dbatools.psd1
Version : 0.9.771

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.757\dbatools.psd1
Version : 0.9.757

## Environmental data
Windows Server 2016 on EC2 instance

## Errors Received

WARNING: [11:04:30][Get-DbaComputerSystem] myEc2Instance was not found to be an EC2 instance. Verify http://169.254.169.254 is accessible on the computer.

## Steps to Reproduce

Run Get-DbaComputerSystem with **-IncludeAWS** switch on an EC2 instance.

```powershell
<#
Get-DbaComputerSystem -ComputerName <ec2instance> -IncludeAws

#>
```

## Expected Behavior

I would expect to see AmiID, IamRoleArn, InstanceId, InstanceType, AvailabilityZone, PublicHostName when using the -IncludeAws switch

## Actual Behavior

No AWS information is returned.  It appears as if the Function **Invoke-Command2** is no longer in dbatools version 0.9.771 as i couldn't find it.

**Comment by niphlod** [comment]
invoke-command2 is still there as an internal function, but I see wher the bug comes from. I'll see what I can do about it

**Comment by wsmelton** [comment]
Please update to the latest version as this was addressed in a previous PR.

**Comment by potatoqualitee** [comment]
considering the merge and @wsmelton 's response, im going to close this as fixed. if that is not the case, please let us know.
