### ISSUE TITLE
Save-DbaUpdate

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5337]
it would be awesome to have a Save-DbaUpdate that saves the updates required for a server. So specify the server, it gets the version, builds the chain until the most recent patch, searches (maybe this? https://www.catalog.update.microsoft.com/Search.aspx?q=sql+server) and saves them all to a path. 

It would also be helpful to be able to just specify the build. 

This could help with both Update-DbaInstance and Install-DbaInstance

/cc @nvarscar what do you think? i believe you have a lot of this code in your stuff.

**Comment by nvarscar** [comment]
I'm not big at parsing web content, but having an option to download the patch is definitely a great idea and can be easily integrated into Update-DbaInstance. But how do you envision it being used in the Install command?

**Comment by potatoqualitee** [comment]
oh, that's true :/ i was thinkign it'd be awesome to have something that would go from nothing to ISOs and Updates but ISOs arent really available. So scratch that.

I'm not a huge fan of parsing s well, cuz it breaks. Maybe catalog has an RSS Feed. Ugh, it's supposed to but appears to throw an error

**Comment by niphlod** [comment]
mind also that not every released CU stays downloadable forever....
