### ISSUE TITLE
Remove-DbaAgentSchedule - new parameter to target a schedule

### ISSUE THREAD

**Issue by dylan-azucena** [sqlcollaborative/dbatools#5353]
---
name: new parameter - ScheduleUid
---

### Summary of new feature

`Remove-DbaAgentSchedule` currently seems to be dependent on the name of a schedule. This makes it hard/impossible to target a single schedule to remove when there are multiple schedules with the same name. If there was a parameter `-ScheduleUid` that could be passed, the correct schedule for removal could be identified.

### Proposed technical details

For example, doing something like this:
```
$ScheduleUid = "b9d561f8-16b3-4565-90a8-96365a277fd2"
Get-DbaAgentSchedule | Where-Object {$_.ScheduleUid -eq $ScheduleUid} | Remove-DbaAgentSchedule -Force
```
currently results in removal of a random schedule with the same name as the schedule with `$ScheduleUid`. Instead I would like to be able to do:
```
Remove-DbaAgentSchedule -ScheduleUid $ScheduleUid -Force
```
And have it remove just that single schedule.

### Latest version of dbatools as of writing

0.9.803

**Comment by potatoqualitee** [comment]
Thank you for your report. We'll take a look when we get a moment.
