### ISSUE TITLE
Start-DbaXESession stopat parameter to include longer running periods

### ISSUE THREAD

**Issue by Dang3rM0us3** [sqlcollaborative/dbatools#5362]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature
dbatools command: Start-DbaXESession
At the moment the "stopat" parameter allows you to specify a moment that the XE will stop.

However due to following line 131 in the powershell code:

$time = $(($StopAt).ToString("HHmmss"))

You cannot specify the extended the event to run e.g. for several days or a week or even beyond the current day.

### Proposed technical details (if applicable)

N/A

### Latest version of dbatools as of writing

0.9.803

**Comment by potatoqualitee** [comment]
Thank you for your report. We'll take a look when we get a moment.

**Comment by potatoqualitee** [comment]
@Dang3rM0us3  do you have a proposal for what the format should be?

**Comment by potatoqualitee** [comment]
@Dang3rM0us3 hello

**Comment by potatoqualitee** [comment]
got the fix, will be released within the next day or so
