### ISSUE TITLE
Start-DbaXESession new parameter "startat"

### ISSUE THREAD

**Issue by Dang3rM0us3** [sqlcollaborative/dbatools#5363]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

Please include a new parameter e.g. "startat" that has the same funcitonality as the stopat parameter but allows you to schedule when the extended event starts.

### Proposed technical details (if applicable)

N/A

### Latest version of dbatools as of writing
0.9.203

**Comment by potatoqualitee** [comment]
Thank you for your request 👍  It's a solid one.
