### ISSUE TITLE
Get-DbaBuildReference, remove "LATEST" from buildreference

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#5379]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

Reported a few weeks ago in the channel by billm. Having the SP property returning "LATEST" is not that useful now that there is Test-DbaBuild. He proposed to remove it for "eyecandiness"

### Proposed technical details (if applicable)

Need to strip the bits from the json, the function needs minor adjustment and the buildreference site some adjustments too.

### Latest version of dbatools as of writing

0.9.804

**Comment by potatoqualitee** [comment]
Agreed
