### ISSUE TITLE
Export-DBAInstance - add "-Append" option

### ISSUE THREAD

**Issue by SvenLowry** [sqlcollaborative/dbatools#5380]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

Add the "-Append" option to Export-DBAInstance to allow the user to choose whether the scripts overwrite existing files or not

* Please provide the latest released version of dbatools module.
0.9.804

**Comment by potatoqualitee** [comment]
Good call, thanks for the request 👍

**Comment by potatoqualitee** [comment]
resolved - will be available in dbatools 1.0 in 20 says

**Comment by sqllensman** [comment]
This actually does not do anything in current code as all scripts are written to a sub directory that includes a timestamp.
Line 173: $path = Join-DbaPath -Path $Path -Child "$($server.name.replace('\', '$'))-$timenow"

The file can never exist prior to being written.

Also for  code paths where same file is being updated with additional content eg Resource Governor, Policy Management etc then Append flag is required to avoid overwriting the content

**Comment by potatoqualitee** [comment]
That is the Default behavior. But my intention was to allow them to be as specific as they'd like with Path and FilePath, which would benefit from -Append

**Comment by sqllensman** [comment]
As the code is currently written
FilePath parameter is unused
Path parameter is used to create a new Sub Directory that has SQL instance name and a timestamp.

As the SqlInstance parameter is an array, then it needs something like this to handle more than 1 instance being passed into the function.

The concept of having an Append switch would only make sense if there is also an option to create the Sub-directories without the timestamp. 

There is also a difficulty in that each file has a number prefix and it may never be certain that filename will be reused as the number may alter.



The

**Comment by potatoqualitee** [comment]
damn, i lost track of what i was doing there. thanks for reopening, ill take a closer look and fix.

**Comment by sqllensman** [comment]
I was looking at this function in terms of fixing issues with #5402 but I have difficulty in seeing how having an Append switch makes much sense or can be reliably implemented

The only reliable way that I can think of to achieve this is if all data was written to a single file. In this case you could implement Append logic but would also want to implement a NoClobber switch to ensure you are not inadvertently overwriting a file.

While this can technically be done I can't really imagine what use this would be. 
Having one file with multiple versions of configuration may be useful for some audit purpose but the same would be true of the timestamped directories

If this requirement really exists then it can be achieved by some a script that could be run afterward that concatenates and appends all of the individual files

**Comment by potatoqualitee** [comment]
Good points, thank you. @SvenLowry - how did you imagine the append would work?

**Comment by SvenLowry** [comment]
I had intended to use it to "backup" the SQL instance config - each week run Export-DBAInstance for all the SQL instances and overwrite the previous files.
Currently, If I run
`Export-DbaInstance -SQLInstance "WEBSQL2" -Path "C:\SQLConfigBackup\WEBSQL2"`
It writes out all the files, then when I run the command again, it appends the config for each file to the same file - see attached example for Server Roles.
[2-serverroles.txt](https://github.com/sqlcollaborative/dbatools/files/3330654/2-serverroles.txt)
I'd imagined that having `-Append $False` would overwrite the contents in each file, rather than append them.
The files aren't getting written to a time stamped subfolder though, they write directly into 
"C:\SQLConfigBackup\WEBSQL2"

**Comment by potatoqualitee** [comment]
Thank you very much, Sven! @sqllensman would you be able to address this request? Or does it already work. Can you try with 

`Export-DbaInstance -SQLInstance WEBSQL2 -Path C:\SQLConfigBackup\WEBSQL2 -Append:$false` Sven?

**Comment by SvenLowry** [comment]
Is the writing to a time stamped folder newer than 0.9.804? I've just updated the dbatools module to test, and it now does write out to a subfolder inside "C:\SQLConfigBackup\WEBSQL2" - e.g.: ""C:\SQLConfigBackup\WEBSQL2\WEBSQL2-06262019161051" so doing -Append:$False has no effect.

**Comment by sqllensman** [comment]
Hi @SvenLowry 

Is there any circumstance where you would actually want Append to be True? 
The default behaviour is to overwrite files which is why I am unsure if an Append flag is actually necessary.

Also, do you need an option to write to a directory without a timestamp?
For example 
```Export-DbaInstance -SQLInstance WEBSQL2 -Path C:\SQLConfigBackup -NoTimeStamp

could write the scripts into C:\SQLConfigBackup\WEBSQL2 rather than
C:\SQLConfigBackup\WEBSQL2-06262019161051

**Comment by SvenLowry** [comment]
Being able to write to a specific folder and specific files  (so the same set of files are maintained each time the script is run) is what we're looking for.

**Comment by sqllensman** [comment]
Thanks for clarification. This will require an option to exclude the timestamps and also maintain a consistent name for individual files.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
