### ISSUE TITLE
import-dbacsv and import-dbacsvtosql

### ISSUE THREAD

**Issue by SquirrelAssassin** [sqlcollaborative/dbatools#5383]
both error out with WARNING: [19:17:47][Import-DbaCsv] Error occurred while establishing connection to <servername> | The connection was not closed. The connection's current state is open.

This is when using azure sql database.  I can do normal dba write operations.

**Comment by SquirrelAssassin** [comment]
as a work around you can use the following to import csvs

      Write-DbaDataTable -SqlInstance $sqlinstance -SqlCredential $SqlCredential -Database $database -Table $table -InputObject $(import-csv -Path C:\temp\waka.csv) -AutoCreateTable

**Comment by potatoqualitee** [comment]
Thank you for your report. We'll take a look when we get a moment.

**Comment by potatoqualitee** [comment]
hello, please provide more information - what command did you type, how large is the CSV? does it happen immediately? anything else you can think that would be helpful for me to repro. thanks

**Comment by potatoqualitee** [comment]
what version of dbatools are you on? please let me know if you had issues seeing the bug report template and if so, what process did you follow to open the issue? we will likely auto-close issues that don't follow it in the future because it asks for information that is very helpful to us.

**Comment by SquirrelAssassin** [comment]
End Fix was to use convertto-dbadatatools, as far as version I update it every day with whatever is the latest.  Write-DbaDataTable -SqlInstance $SQLDatabase -SqlCredential $SqlCredential -Database $database -Table $table -InputObject (ConvertTo-DbaDataTable -InputObject $file) -AutoCreateTable -Truncate -Confirm:$false
