### ISSUE TITLE
Export-DbaUser - Object Level IfExists Permissions

### ISSUE THREAD

**Issue by TedSchnieders** [sqlcollaborative/dbatools#5385]
---
name: Export-DbaUser  - Object Level IfExists Permissions
---
### Summary of new feature

When using this Export-DbaUser generated script to restore permissions to their original state after a restore from another environment (in this case Production to Development or Quality Assurance. If the object does not exist in production after the restore this causes the script to explode.   

I think the this function is awesome and has simplified my code.  I really like this functionality and would like to continue to leverage it. 

From my perspective it works as it should accept for the fact it does not work in my  circumstances.  If it does not make sense to modify the function, I understand.  If you are aware of other functionality in dbatools that may handle this scenario better  will you please let me know.

Thank you!

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality

### Latest version of dbatools as of writing

* dbatools 0.9.804

**Comment by potatoqualitee** [comment]
Thanks much, Ted. Hopefully @ClaudioESSilva can take a look

**Comment by ClaudioESSilva** [comment]
Hi @TedSchnieders ,

I understand what you want to achieve but this is not natively supported like the `IF NOT EXISTS` that can be set using the `IncludeIfNotExists` property of the ScriptingOptions (on this command we set it,by default). 

But, as workarround (and please test it on your scenario), you can do something like this:
```powershell
$regex = '(.*)(::)(.+?(?=\sTO))(.*)'
$toReplace = "IF OBJECT_ID('`$3') IS NOT NULL`n`r `$1`$2`$3`$4"

$scriptOutputUser = Export-DbaUser -SqlInstance sql1 -Database db1 -User User1
$scriptOutputUser -replace $regex, $toReplace
```

This will convert
``` sql
GRANT SELECT ON OBJECT::[dbo].[Table] TO [TestExport]  AS [dbo];
```
into this:
``` sql
IF OBJECT_ID('[dbo].[Table]') IS NOT NULL
   GRANT SELECT ON OBJECT::[dbo].[Table] TO [TestExport]  AS [dbo];
GO
```
for all the entries you have on the script. You can fine tuning the regex for other scenarios.

NOTE: I'm not an regex expert. So probably there are better ways to write this one. 😃 But it does the job.

**Comment by potatoqualitee** [comment]
thank you for your feedback and solution claudio 🙇
