### ISSUE TITLE
Installing partially

### ISSUE THREAD

**Issue by llmuculusll** [sqlcollaborative/dbatools#5389]
---
name: Installing Partially/Selective

---

### Summary of new feature

It is very efficient that there is a native way to install specific commands of dbatools. A selective installing can help devops to install a few specific command that needed to operate some operation.
Are there any plan for this facility?

**Comment by potatoqualitee** [comment]
Unfortunately not. There is currently no way. What is the issue, memory? Import time?

**Comment by llmuculusll** [comment]
no memory neither Import time. 
I only need specific commands not other, so it is nice that I could install exactly those commands not any other commands.

**Comment by potatoqualitee** [comment]
Thanks for the response - that is not possible with powershell as far as i know. if it's a security issue, however, check out JEA or Just Enough Administration

**Comment by potatoqualitee** [comment]
Heyyy found the answer by accident.
`Import-Module -Function` and specify just the functions you want. I believe we'll be doing roles later on too, after 1.0.

![image](https://user-images.githubusercontent.com/8278033/58554377-133af380-8217-11e9-801a-7df570e6af7c.png)
