### ISSUE TITLE
FR: Get-DbaSQLPatches

### ISSUE THREAD

**Issue by hfleitas** [sqlcollaborative/dbatools#5391]
---
Name: Feature request/idea 💣 🥊 
About: Suggest a new feature or enhancement
---

### Summary of new feature
* Retrieves a list of SQL Patches (SP/CU/Hot-fixes) on a Computer and the instances on it.

### Proposed technical details (if applicable)
* https://github.com/hfleitas/Monitoring
[Get-SQLUpdates.ps1](https://github.com/hfleitas/Monitoring/blob/master/Get-SQLUpdates.ps1)

### Latest version of dbatools as of writing
* 0.9.808

**Comment by potatoqualitee** [comment]
Cool idea! Thanks so much for submitting the issue 💯
