### ISSUE TITLE
Test All DbaAgent cmdlets

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#5394]
### Summary of new feature

While working on `Find-DbaAgentJob` tests, I noticed that there are still quiet a few `*-DbaAgent*` cmdlets that have not code coverage. Tests should be written to improve the health of the module. Current cmdelts that have 0 on codecov.io for coverage:
```
Copy-DbaAgentProxy.ps1
Copy-DbaAgentSchedule.ps1 
Copy-DbaAgentServer.ps1 
New-DbaAgentSchedule.ps1 
Remove-DbaAgentJobStep.ps1 
Remove-DbaAgentSchedule.ps1 
Set-DbaAgentJob.ps1 
Set-DbaAgentJobOutputFile.ps1 
Set-DbaAgentJobOwner.ps1 
Set-DbaAgentJobStep.ps1 
Set-DbaAgentSchedule.ps1
Stop-DbaAgentJob.ps1 
```

### Proposed technical details (if applicable)

Using before all blocks, I will create the items (as needed), test the cmdlet and then remove the objects after testing. This issue will probably be broken up over several different PRs

### Latest version of dbatools as of writing

0.9.809

**Comment by joshcorr** [comment]
Added tests for `New-DbaAgentSchedule.ps1`, `Remove-DbaAgentSchedule.ps1`, and `Set-DbaAgentSchedule.ps1` in #5396

**Comment by potatoqualitee** [comment]
thanks so much, josh! your work is incredibly important for dbatools 1.0 and is super appreciated 🏆
