### ISSUE TITLE
New function: Backup-DbaServiceMasterKey

### ISSUE THREAD

**Issue by maddhatter** [sqlcollaborative/dbatools#5397]
---
name: Add `Backup-DbaServiceMasterKey` 🔐 

---

### Summary of new feature
Add a new `Backup-DbaServiceMasterKey` command, similar to the existing `Backup-DbaDbMasterKey`.

### Proposed technical details (if applicable)
SMO exposes the same Export command used in `Backup-DbaDbMasterKey` on the instance's SMK:
```powershell
$server = Connect-DbaInstance ServerA

$server.ServiceMasterKey.Export

OverloadDefinitions
-------------------
void Export(string path, string password)
```
T-SQL Command reference: https://docs.microsoft.com/en-us/sql/t-sql/statements/backup-service-master-key-transact-sql?view=sql-server-2017

### Latest version of dbatools as of writing

0.9.809

**Comment by potatoqualitee** [comment]
🎉
