### ISSUE TITLE
[Bug] Export-DbaInstance creates duplicates in userobjectsinsysdbs.sql file

### ISSUE THREAD

**Issue by asnest** [sqlcollaborative/dbatools#5402]
### Before submitting a bug report:
- [X] *Running latest release of dbatools*
- [x] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data

```
### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14393.2879
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2879
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1




### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.809\dbatools.psd1
Version : 0.9.809
```

### SQL Server: 

```sql
Microsoft SQL Server 2016 (RTM-GDR) (KB4019088) - 13.0.1742.0 (X64)   Jul  5 2017 23:41:17   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 6.3 <X64> (Build 14393: ) 
```

## Errors Received

```powershell
No errors
```

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
Export-DbaInstance -SqlInstance $server -Path $path\$server\ -Exclude Databases, ResourceGovernor
```

## Expected Behavior

receive creation objects script in systemdb's in userobjectsinsysdbs.sql file

## Actual Behavior

I'm receiving script with duplicated objects - for example creating the same table mentioned 2 times. And also I found that duplicated script doesn't have separate "GO" after it - maybe it can help to find the problem.

**Comment by asnest** [comment]
the same situation in dbmail.sql file

**Comment by potatoqualitee** [comment]
Thank you for looking into this, @sqllensman !

**Comment by potatoqualitee** [comment]
@sqllensman - you gonna take care of this? it likely won't be on my radar. the issue probably comes from the fact that it includes dependencies. so some sort of tracker would have to be implemented.

**Comment by sqllensman** [comment]
Yes. I am working on an Export-DbaDatabase command that will replace this command with a more general command. Should be done sometime this week.

**Comment by potatoqualitee** [comment]
awesome!! thank you 🙇 how did your session go?
