### ISSUE TITLE
[Bug]Test-DbaDbCompression, fails on CI instances

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#5404]
Reported on slack by k_lindberg70. 
```
version 0.9.809.  - Invalid object name '##tmpestimaterow' ,
 Invalid object name '##tmpestimatepage' and Invalid column name 'schema'
```
Fix should be straightforward

**Comment by klindberg70** [comment]
I still have an issue with this on version 0.9.811 on my case sensitive instance
WARNING: [15:21:23][Test-DbaDbCompression] Unable to query localhost\INST01 - [DBNAME] | Invalid column name 'schema'.
schema should be spelled Schema in the queries

**Comment by jpomfret** [comment]
Rut roh - looks like a project for this weekend! Thanks for reporting

**Comment by wsmelton** [comment]
This would be easier to catch if we could easily change the collation of the Appveyor instances to case sensitive.
