### ISSUE TITLE
Invoke-DbaQuery returns verbose output when "-Verbose:$false" is specified[Bug]

### ISSUE THREAD

**Issue by cfradenburg** [sqlcollaborative/dbatools#5409]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```
& {"### PowerShell version:`n$($PSVersionTable | Out-String)"; "`n### dbatools Module version:`n$(gmo dbatools -List | select name, path, version | fl -force | Out-String)"}
```

- [X] *Running latest release of dbatools*
- [X] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data

```
Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1




### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.809\dbatools.psd1
Version : 0.9.809
```

### SQL Server: 

```sql
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)
                Mar 18 2018 09:11:49
                Copyright (c) Microsoft Corporation
                Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

## Errors Received

```powershell
<# OUTPUT of $error[0] | select * #>
```

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
Invoke-DbaQuery -SqlInstance <servername> -Query "exec sys.sp_configure 'remote admin connections',1" -verbose:$false
```

## Expected Behavior

No output as when `Invoke-DbaQuery -SqlInstance dbalabsql01 -Query "exec sys.sp_configure 'remote admin connections',1"` is run

## Actual Behavior

Output is:
>VERBOSE: Configuration option 'remote admin connections' changed from 1 to 1. Run the RECONFIGURE statement to install.

**Comment by potatoqualitee** [comment]
Not so sure this is a bug. May be by design, will wait for @niphlod to weigh in.

**Comment by potatoqualitee** [comment]
I tested this and had to do some research and the explanation is very long. It's related to PowerShell itself and not this specific command. Basically the issue is with .isPresent and the way the :$false was intended to be used.

This has the explanation:

https://github.com/PowerShell/PowerShell/issues/4143#issuecomment-312279279

Unfortunately it is out of our scope.

**Comment by cfradenburg** [comment]
Chrissy,

Can you try running this and see that changes anything?  It looks like `.ContainsKey` will determine if it was explicitly passed in but not if it's true or false.  Either `.IsPresent` or explicitly pulling the value from `$PSBoundParameters` will return the expected value.

```function test-verbose {
    [CmdletBinding()]
    param (
        [string]$name
    )

    [bool]$ContainsValue = $PSBoundParameters.ContainsKey('Verbose')
    Write-Output "ContainsKey Says: $ContainsValue"

    [bool]$PresentValue = $PSBoundParameters['Verbose'].IsPresent
    Write-Output "isPresent Says: $PresentValue"

    [bool]$ValueValue = $PSBoundParameters['Verbose']
    Write-Output "Value Says: $PresentValue"
}

write-host "Testing with no parameters" -ForegroundColor Red
test-verbose -Name 'Me'

write-host "Testing with verbose" -ForegroundColor Red
test-verbose -Name 'Me' -Verbose

write-host "Testing with verbose false" -ForegroundColor Red
test-verbose -Name 'Me' -Verbose:$false```

Here's the output for me:

> Testing with no parameters
> ContainsKey Says: False
> isPresent Says: False
> Value Says: False
> Testing with verbose
> ContainsKey Says: True
> isPresent Says: True
> Value Says: True
> Testing with verbose false
> ContainsKey Says: True
> isPresent Says: False
> Value Says: False

**Comment by cfradenburg** [comment]
I just realized this may not be noticed without a mention because it's closed so...  Yoohoo, @potatoqualitee .  :-)

**Comment by potatoqualitee** [comment]
i can run it but im not sure where im supposed to go with it. do you believe this is an issue with dbatools? if so, do you have a proposal for how to resolve it? If it is an issue with dbatools, we may have to ping Fred to take a look at Write-Message.

**Comment by wsmelton** [comment]
This is coming from the internal command that handles the message event handler from SQL Server. This is because SQL Server and your procedure you are running implement PRINT statements. Maniulating verbose functionality from PowerShell will not change this as it is part of SMO.

You can try setting `$VerbosePreference` to something that makes it quiet but overall it is not causing any harm, unless you can show how it is?

**Comment by wsmelton** [comment]
Either way though both `Invoke-DbaQuery` and `Invoke-DbaAsync` (internal) are both validating whether `Verbose` parameter was passed in so there is no change required.

Use of `-Verbose:$false` as well is not the way to handle turning off verbose messages. You should utilize `$VerbosePreference` which is a built-in varable that controls verbose output for the session.

**Comment by cfradenburg** [comment]
Thanks for pointing out that I wan't actually output verbose output in my test function.  When I added that I didn't get output when I passed in `-verbose:$false`.  Setting $VerbosePreference would be a pain in my scenario and require switching it back and forth to only return verbose output from the parent script.

I think there's an issue in how test-bound is pulling the bound value.  I have a meeting so I can do some more testing in a bit.  Do we have a list of functions that depend on test-bound?  I don't want to test just Invoke-DbaQuery for verbose output and assume all else is okay.

**Comment by wsmelton** [comment]
We manipulate the streams in PowerShell from our module if you want more control over what is output I would recommend checking the configuration for our message system to see if that meets your needs. But again `-Verbose:$false` is not the right usage. There are 1,052 references being made to `Test-Bound` in the module, this has nothing to do with that function.

`Get-DbatoolsConfig -Module message`

**Comment by cfradenburg** [comment]
I'm not so sure about that.  If someone explicitly passes in `-Force:$false` what should the behavior be?  My assumption is that you would want it to behave the same as if the parameter wasn't passed in at all but that isn't what actually happens.

```
Enable-DbaAgHadr -SqlInstance <servername> -Force:$false -WhatIf
What if: Performing the operation "Changing Hadr from False to 1 for dbalabsql01" on target "dbalabsql01".
What if: Performing the operation "Force provided, restarting Engine and Agent service for dbalabsql01 on dbalabsql01" on target "dbalabsql01".
```

The issue may not be with Test-Bound but it appears that there are several places where the fact that a switch is bound is being treated the same as if it's true.  In `Enable-DbaAgHadr`:

```
            if (Test-Bound -ParameterName Force) {
                if ($PSCmdlet.ShouldProcess($instance, "Force provided, restarting Engine and Agent service for $instance on $computerFullName")) {
                    try {
                        $null = Stop-DbaService -ComputerName $computerFullName -InstanceName $instanceName -Type Agent, Engine
                        $null = Start-DbaService -ComputerName $computerFullName -InstanceName $instanceName -Type Agent, Engine
                    } catch {
                        Stop-Function -Message "Issue restarting $instance" -Target $instance -Continue
                    }
                }
            }
```

Backup-DbaDatabase has a check that fuctions the same way.  If `-CreateFolder:$false` is passed in it triggers the check:
```
if ((Test-Bound 'AzureBaseUrl') -and (Test-Bound 'CreateFolder')) {
    Stop-Function -Message 'CreateFolder cannot be specified with an Azure Backup, the container must exist and be referenced by the URL'
    return
}
```

I tested changing the `Test-Bound` check from `$BoundParameters.ContainsKey($name)` to `$BoundParameters[$name]` and it appears to properly check both switch and non-switch parameters.

```
Backup-DbaDatabase -SqlInstance <servername> -AzureBaseUrl "http://fakeaddress" -CreateFolder -WhatIf
```
That triggers the check but not passing in AzureBaseURL or `CreateFolder:$false` doesn't.

The alternative is to leave Test-Bound alone and check all references to it that use a switch to make sure they're checking the value afterwards.  Theoretically that's the safer bet but only if there's someplace that differentiates between the switch not being passed in and it being passed in as $false.  If this is something that we think needs to be fixed I can check the references to them.  Doing a search in VSCode on the development branch turns up 1,039 references instead of the 1,052 that Shawn found so I may not be seeing them all though.

**Comment by wsmelton** [comment]
You shouldn't be passing in `-verbose:$false` to begin with... As I've already stated that is not the proper use case for it, as such not something we are going to address.

**Comment by wsmelton** [comment]
That is at it pertains to the verbose parameter.

If you for the internal command causes issue with other use defined parameters then you can open a new issue with your finding.

**Comment by wsmelton** [comment]
Code shows you the references it finds using CodeLens.

If you see the internal command has an issue then open a new issue for it with your findings and it can be reviewed. We will have the author of that command chime in before making any changes to it.
