### ISSUE TITLE
[Bug] Copy-DbaAgentSchedule does not overwrite schedules that already exist, even with -Force supplied

### ISSUE THREAD

**Issue by TheFiercestCreature** [sqlcollaborative/dbatools#5412]
```
Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.810\dbatools.psd1
Version : 0.9.810

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.512\dbatools.psd1
Version : 0.9.512
```

- [ ] *Running latest release of dbatools*
- [ ] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

### SQL Server: 
```sql
Microsoft SQL Server 2017 (RTM-CU7) (KB4229789) - 14.0.3026.27 (X64)   May 10 2018 12:38:11   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

## Errors Received

The cmdlet does not throw an error

## Steps to Reproduce

```powershell
<#
   Copy-DbaAgentSchedule -Source source-server -Destination destination-server -Force
#>
```

## Description of Bug

I am testing Copy-DbaAgentSchedule as a means to keep schedules in-sync between always-on partners in HA. If a schedule is created at source, it is copied to destination fine. However, if that schedule is then amended (a new timing or similar) this schedule is skipped, even if the force switch is provided. I would expect -Force to overwrite all schedules on the destination with those from the source.

## Output of cmdlet
```
Type           Name                             Status  Notes
----           ----                             ------  -----
Agent Schedule AMS - AG01 Job                   Skipped
Agent Schedule HA Schedule                      Skipped
Agent Schedule syspolicy_purge_history_schedule Skipped
```

**Comment by potatoqualitee** [comment]
Thank you for your report. We'll take a look when we get a moment.

**Comment by TheFiercestCreature** [comment]
Also, stop me if I'm now being too demanding but it would be great if we could filter the schedules that get copied, maybe by name

**Comment by potatoqualitee** [comment]
No problem at all, please do ask. I added it in a recent PR. There is an issue with the Force - the reason it's not dropping is because the schedule is associated with a job so I added that to the notes and asked for shawn's feedback about design.

**Comment by wsmelton** [comment]
They problem with filtering by name is a schedule name is not unique the way SQL Server stores them. You can have the same name exists multiple times.

**Comment by TheFiercestCreature** [comment]
Thanks guys :)
@potatoqualitee ahh, that makes a lot of sense. Is the plan to leave the behaviour as it is?
@wsmelton, instead of name then, would you consider using schedule_uid?
