### ISSUE TITLE
Patterns for PII scan command

### ISSUE THREAD

**Issue by sanderstad** [sqlcollaborative/dbatools#5415]
This issue is meant for anyone to put in their patterns during the development of the PII scan command.

**Comment by Alex-Yates** [comment]
Here are a few for you. Mostly UK specific. :-)

UK phone numbers:
11 digits, starting with a 0. The second digit determines the type of number. (1 is a standard landline. 7 is mobile. There are others):
https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom

UK post codes:
https://stackoverflow.com/questions/164979/uk-postcode-regex-comprehensive
Example Regex provided by UK government:
([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})

UK NHS Numbers:
https://www.nhs.uk/using-the-nhs/about-the-nhs/what-is-an-nhs-number/
These actually all contain a CHECKSUM. They are all 10 digit MOD 11s. Not sure if you want to get into that level of detail or not?

IPv4 addresses:
https://www.regular-expressions.info/ip.html

IPv6 addresses:
https://stackoverflow.com/questions/53497/regular-expression-that-matches-valid-ipv6-addresses

**Comment by robertgadach** [comment]
Visa is starting to issue 19-digit codes: The pattern is 4-digits, 4-digits, 4-digits, 7-digits

- Example: 4123-1234-1234-1234567

- Regex: (4\d{3}[-| ]\d{4}[-| ]\d{4}[-| ]\d{7})|(4\d{19})

MasterCard is issuing cards in the 222100‑272099 range 

- Example: 2720-9912-3456-7899
- Regex: ^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$

**Comment by shaneis** [comment]
Personal Public Service (PPS) Numbers in Ireland (equivalent to Social Security Numbers in the states) are 7 numbers followed by 1 or 2 letters

* 1234567A
* 9876543ZY

* Regex: 
`\d{7}\w{1,2}`
or
`\b\d{7}\w{1,2}\b`

**Comment by sanderstad** [comment]
Thank you guys. I've added all of the patterns that were not already in there or had to be changed.

@Alex-Yates 
- Added the UK phone number
- Added UK zip codes
- Added the NHS number
- The IP Addresses were already in the the file

@robertgadach 
- Added the new patterns for MasterCard
- Added the new pattern for VISA

@shaneis 
There already was a regex for the PPS number that also matched those numbers 

Thanks again for your help

**Comment by potatoqualitee** [comment]
frikken 💣 , sander!

**Comment by ClaudioESSilva** [comment]
Thanks for this @sanderstad 

here so patterns from Portugal:
 
**phones numbers**
Country code: +351
9 digits starting with
 - 2 - landline
 - 9 - mobile
 - 707 - premium rate
 - 800 xxx xxx Freephone 
 - 808 xxx xxx Shared cost 
 - 809 xxx xxx Shared cost 
 - 607 xxx xxx Premium rate audio text (never saw this one)
 - 30x xxx xxx VoIP carriers

**Tax fiscal number**
9 digits Starting with
 - 1 to 3 - personal (single person) 
 - 5 - collective person ( companies) 
 - 6 - public entities
 - 90 or 91 - Condominiums, Irregular Companies, Inheritance Indivises whose successor was an individual entrepreneur;

**Postal code**
4digits-3digits
Example: 1000-103

**Comment by sanderstad** [comment]
Closing this issue. New patterns can be added later on using the JSON file
