### ISSUE TITLE
Backup-DbaDbCertificate Error: Could not load file or assembly 'Microsof t.SqlServer.BatchParser.dll' or one of its dependencies. 

### ISSUE THREAD

**Issue by RobertVirag** [sqlcollaborative/dbatools#5416]
Backup-DbaDbCertificate give an error:
WARNING: [09:12:20][export-cert] TDECert_BaselineDB from [master] on TEST\SQL1 cannot be exported. | Could not load file or assembly 'Microsof
t.SqlServer.BatchParser.dll' or one of its dependencies. The specified module could not be found.

I executed the code in Powershell ISE.
Backup-DbaDbCertificate -SqlInstance $SQL1 -Database master -Certificate $TDEDBCert -Path $Share -EncryptionPassword $cert_sec_pw

I tried to run the code in Powershell ISE (x86) as well, same error, but it seems that it has problem with SQL Server 2017 assembly:
WARNING: [09:19:00][export-cert] TDECert_BaselineDB from [master] on TEST\SQL1 cannot be exported. | Could not load file or assembly 'Microsof
t.SqlServer.BatchParser, Version=14.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file spec
ified.

It is SQL Server 2014.
Don't know if it is relevant, but Backup-DbaDbMasterKey is working fine.

**Comment by potatoqualitee** [comment]
hey @RobertVirag  - please check out the most recent release and see if you continue to have issues. if you do, restart PowerShell, reimport and retest.
