### ISSUE TITLE
Copy-DbaAgentJob job step output path not upgraded

### ISSUE THREAD

**Issue by GrahamDBA** [sqlcollaborative/dbatools#5432]
- [x] *Running latest release of dbatools*
- [x] Verified errors are not related to permissions

## Environmental data

```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
### dbatools Module version:
Name    : dbatools
Path    : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\dbatools.psd1
Version : 0.9.815
```

### SQL Server: 

```sql
Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64) 
	Jan 10 2019 18:51:38 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

```
## Errors Received

```powershell
NO ERROR but unexpected behavior.
```

## Steps to Reproduce

```powershell
<#
Copy-DbaAgentJob -Source "SQL2012\APP" -Destination "SQL2016\APP" 
#>
```

## Expected Behavior
I would expect Copy-DbaAgentJob -Source "SQL2012\APP" -Destination "SQL2016\APP" 
To modify the job step output path to be path of destination LOG path. 
EG: 13
D:\Program Files\Microsoft SQL Server\MSSQL13.APP\MSSQL\LOG\CommandLogCleanup.txt

## Actual Behavior
EG: 11
D:\Program Files\Microsoft SQL Server\MSSQL11.APP\MSSQL\LOG\CommandLogCleanup.txt

Use this TSQL to show step output path.
use msdb
go
select [Jobs].name,  step_id,step_name,output_file_name
from msdb.dbo.sysjobs [Jobs] 
				left join msdb.dbo.sysjobsteps [Steps] 
					on [Jobs].job_id = [Steps].job_id
where output_file_name is not null
order by [Jobs].name,step_id asc

**Comment by GreyOrGray** [comment]
I know this got marked To do, but could it be an optional switch?  Or maybe just check to see if files are already being output to the LOG path before updating the step? 

If my job steps suddenly swapped to using the LOG path when I was expecting them to still use the previously designated path, I'd be needing a lot more coffee.

**Comment by GrahamDBA** [comment]
Yes, but if the output path is not present on your destination SQL Server you also will have lost the output as well.
I think an option flag that says -CheckAgentJobStepOutputPath and if set to true then only gives a warning if the path is not present on the destination SQL Server.
Another option flag -SetDefaultAgentJobOutPutPath would adjust the output path to the default of the destination SQL Server.
With no warnings you can be lulled into thinking your job was migrated without fault.

**Comment by GrahamDBA** [comment]
Here is some catcher TSQL.
`use msdb
go

Declare @rc int, @SQLPath nvarchar(4000) 
Declare @Length int

exec @rc = master.dbo.xp_instance_regread
      N'HKEY_LOCAL_MACHINE',
      N'Software\Microsoft\MSSQLServer\Setup',
      N'SQLPath', 
      @SQLPath output, 'no_output'

Set @Length = (Select len(@SQLPath) )

select @SQLPath AS InstallationDirectory

select [Jobs].name,  step_id,step_name,output_file_name as [WARNING: output_file_name is set to an invalid path]
from msdb.dbo.sysjobs [Jobs] 
				left join msdb.dbo.sysjobsteps [Steps] 
					on [Jobs].job_id = [Steps].job_id
where output_file_name is not null
	and left(output_file_name,@Length)<>@SQLPath

order by [Jobs].name,step_id asc`

**Comment by GreyOrGray** [comment]
I think those are both great.  
Though, honestly, I wouldn't mind having something like -CheckAgentJobStepOutputPath defaulting to true or even having the check-and-warn baked into the function without it being optional.

**Comment by GrahamDBA** [comment]
This will show when a job output step has a path that is not the default.

-- File name : JobOutputPathWrongFixer.sql
-- Reference : https://stackoverflow.com/questions/505007/sql-server-how-to-select-the-installation-path
-- Reference : https://stackoverflow.com/questions/1024978/find-index-of-last-occurrence-of-a-sub-string-using-t-sql
-- Reference : https://sqlhints.com/2016/10/01/how-to-find-the-location-of-the-sql-server-error-log-file/

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
go
use msdb
go

-- Identifier
Declare @SQLPath nvarchar(4000) 
Declare @Length int

Select  @SQLPath =	replace(cast( SERVERPROPERTY('ErrorLogFileName') as nvarchar(4000)  ),'ERRORLOG','')

Set @Length = (Select len(@SQLPath) )
select [Jobs].name, step_id, step_name
		,[Steps].output_file_name as [WARNING: output_file_name is set to an invalid path] 
		,@SQLPath +reverse(left(reverse([Steps].output_file_name), charindex('\', reverse([Steps].output_file_name)) -1)) as [FIX: output_file_name set to a valid path]

from msdb.dbo.sysjobs [Jobs] 
				left join msdb.dbo.sysjobsteps [Steps] 
					on [Jobs].job_id = [Steps].job_id

where output_file_name is not null
 	and left( output_file_name ,@Length)<>@SQLPath

order by [Jobs].name,step_id asc

**Comment by wsmelton** [comment]
My recommendation is do not try and create all the regex that this would require to update the script output generated from a given job. It is 100% gaurenteed that unless you are migrating the same major version that the paths are not going to work, this has been existence since day one of this command. 

It should be part of a user's migration list to post-processing go through and update the path of their SQL Agent jobs to the path they want it to go to, whether that is the default path or not. We have `Set-DbaAgentJobOutputFile` that can easily be used for that process.

**Comment by wsmelton** [comment]
The culture settings of both SQL Server and the OS can cause problems for regex expressions. We have had this issue before on server names in script files.

**Comment by GrahamDBA** [comment]
Thanks, I had not found that Set-DbaAgentJobOutputFile command. I will check it out.

**Comment by GrahamDBA** [comment]
This worked for the job output path.
Set-DbaAgentJobOutputFile -SqlInstance ABCDEF -Job "Standard Clean Output File Cleanup"  -Step "Output File Cleanup"  -OutputFile "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\JOBS\OutputFileCleanup_`$(ESCAPE_SQUOTE(JOBID))_`$(ESCAPE_SQUOTE(STEPID))_`$(ESCAPE_SQUOTE(STRTDT))_`$(ESCAPE_SQUOTE(STRTTM)).txt"

**Comment by GrahamDBA** [comment]
-- Call the repair man
Select 'Set-DbaAgentJobOutputFile -SqlInstance ' + @@Servername + 
' -Job "' + [Jobs].[name] + '" ' +
' -Step "' + step_name + '" ' +
' -OutputFile "' + 
Replace(Replace(@SQLPath,'\Log\','\JOBS\') + 
reverse(left(Reverse([Steps].output_file_name), charindex('\', Reverse([Steps].output_file_name)) -1))+ '"','$(','`$(') 
as [PowerShell Fix]

From msdb.dbo.sysjobs [Jobs] 
				left join msdb.dbo.sysjobsteps [Steps] 
					on [Jobs].job_id = [Steps].job_id
where output_file_name is not null and output_file_name not like '%13%'
order by [Jobs].name, step_id asc

**Comment by GrahamDBA** [comment]
BUT, inside the job there can still be wrong paths.....eg: this log clean up job from Source: https://ola.hallengren.com
cmd /q /c "For /F "tokens=1 delims=" %v In ('ForFiles /P "D:\MSSQL11.MSSQLSERVER\MSSQL\LOG" /m *_*_*_*.txt /d -30 2^>^&1') do if EXIST "D:\MSSQL11.MSSQLSERVER\MSSQL\LOG"\%v echo del "D:\MSSQL11.MSSQLSERVER\MSSQL\LOG"\%v& del "D:\MSSQL11.MSSQLSERVER\MSSQL\LOG"\%v"

**Comment by potatoqualitee** [comment]
Thank you for the note and the code that others will be able to use if they search 👍  Will close this as solved because I agree it'd introduce problems and we have Set-DbaAgentJobOutputFile to help. If anyone would like to submit a PR that updates the description of the copy command to mention Set-DbaAgentJobOutputFile, it would be appreciated.

**Comment by GrahamDBA** [comment]
.... what is a PR?

**Comment by sqllensman** [comment]
PR = Pull Request 

https://github.com/sqlcollaborative/dbatools/wiki/Your-First-Pull-Request

**Comment by GrahamDBA** [comment]
Found: SQL Server 2016 has this output file variable: $(ESCAPE_SQUOTE(SQLLOGDIR))
