### ISSUE TITLE
Repair-DbaDbOrphanUser Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database '<MyDB>'. "

### ISSUE THREAD

**Issue by iceblack2k** [sqlcollaborative/dbatools#5437]
Hi 

Using Repair-DbaDbOrphanUser running under the SQLAgent on SQL Server side.
This error message only comes up if there is any orphan user
I got the following message

WARNING: [07:40:58][Repair-DbaDbOrphanUser] Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database '<MyDB>'. "

I am running from my computer it's working fine without any issues.

I have compared the script Repair-DbaDbOrphanUser.ps1 in both machines and it's the same.

Do you have any workaround or know the reason why?

Thanks and Regards
Antonio
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

**Comment by potatoqualitee** [comment]
Hello,
Thank you for the report. Please fill out the bug form to provide us with the information we need: https://github.com/sqlcollaborative/dbatools/issues/new?assignees=&labels=&template=Bug_Report.md&title=%5BBug%5D
