### ISSUE TITLE
[Bug] Invoke-DBADbLogShipping Secondary Monitoring issue

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#5439]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```
& {"### PowerShell version:`n$($PSVersionTable | Out-String)"; "`n### dbatools Module version:`n$(gmo dbatools -List | select name, path, version | fl -force | Out-String)"}
```

- [X] *Running latest release of dbatools*
- [X] Verified errors are not related to permissions
- [x] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

### PowerShell version:

Name                           Value                                                                                                                                                                                                   
----                           -----                                                                                                                                                                                                   
PSVersion                      5.1.14393.2879                                                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                 
BuildVersion                   10.0.14393.2879                                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                                         
WSManStackVersion              3.0                                                                                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                     
SerializationVersion           1.1.0.1                                                                                                                                                                                                 
### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.817\dbatools.psd1
Version : 0.9.817

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.517\dbatools.psd1
Version : 0.9.517

### SQL Server: 

Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64)   Jan 10 2019 18:51:38   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

## Errors Received

Invoke-DbaDbLogShipping `
-SourceSqlInstance $SourceInstance `
-DestinationSqlInstance $DestinationInstance `
-Database $SourceDB `
-BackupNetworkPath "\\$BackupPath\$SourceInstance" `
-BackupRetention 2160 `
-BackupScheduleFrequencyType Daily `
-BackupScheduleFrequencySubdayType Minutes `
-BackupScheduleFrequencySubdayInterval 5 `
-BackupScheduleStartDate $ScheduleStartDate `
-BackupScheduleStartTime 080000 `
-BackupScheduleEndTime 075959 `
-BackupThreshold 60 `
-CopyDestinationFolder "\\$DestinationInstance\TranLog_Xfer" `
-CopyRetention 2160 `
-CopyScheduleFrequencyType Daily `
-CopyScheduleFrequencySubdayType Minutes `
-CopyScheduleFrequencySubdayInterval 5 `
-CopyScheduleStartDate $ScheduleStartDate `
-CopyScheduleStartTime 080700 `
-CopyScheduleEndTime 080659 `
-RestoreScheduleFrequencyType Daily `
-RestoreScheduleFrequencySubdayType Minutes `
-RestoreScheduleFrequencySubdayInterval 5 `
-RestoreRetention 2160 `
-RestoreScheduleStartDate $ScheduleStartDate `
-RestoreScheduleStartTime 080900 `
-RestoreScheduleEndTime 080859 `
-RestoreThreshold 60 `
-SecondaryMonitorServer $DestinationInstance `
-SecondaryThresholdAlertEnabled `
-CompressBackup `
-Force `

I am running invoke-DbaLogShipping with the following parameters.  I am not wanting to turn on monitoring for the primary server, just the secondary server.  This worked in version 0.9.517.  I am also specifying the monitor server be the secondary server.  What I am seeing in the verbose output is that the sp_processlogshippingmonitorsecondary stored proc is being called.  Its being called with @monitor_server = primary server name.  I replaced the actual values with parameter names to protect environment.

## Steps to Reproduce

EXEC msdb.dbo.sp_processlogshippingmonitorsecondary @mode = 1
                    ,@secondary_server = '<$DestinationInstance>'
                    ,@secondary_database = 'DocumentStorageSolution'
                    ,@secondary_id = 'c1216088-3d46-4839-a5b1-1cdcea78ab89'
                    ,@primary_server = '<$SourceInstance>'
                    ,@primary_database = '$SourceDB'
                    ,@restore_threshold = 60
                    ,@threshold_alert = 14420
                    ,@threshold_alert_enabled = 1
                    ,@history_retention_period = 14420
                    ,@monitor_server = '<$SourceInstance>'
                    ,@monitor_server_security_mode = 1 

                UPDATE msdb.dbo.log_shipping_secondary
                SET monitor_server = '<$SourceInstance>', user_specified_monitor = 1
                WHERE secondary_id = 'c1216088-3d46-4839-a5b1-1cdcea78ab89'

**Comment by potatoqualitee** [comment]
Thank you for submitting the bug report! We'll take a look when we get a moment.

**Comment by sanderstad** [comment]
What I don't understand in this, is that the assignment of the variables should be correct.
The only time the secondary monitor will get the source instance value assigned is when the parameter "SecondaryMonitorServer" is not set in combination with -Force.

```powershell 
# Check the secondary monitor server
if ($Force -and (-not $SecondaryMonitorServer -or [string]$SecondaryMonitorServer -eq '' -or $null -eq $SecondaryMonitorServer)) {
    Write-Message -Message "Setting secondary monitor server for $destInstance to $SourceSqlInstance." -Level Verbose
    $SecondaryMonitorServer = $SourceSqlInstance
}
```

Although this check does have some redundant values, it would not assign the source instance of the secondary monitor was set.

@dczarny Can you send me the verbose output you get when you execute the command?
You can replace the values from your environment if you need to, as long as it's consistent that should not be a problem.
Maybe that way I can check what is going wrong.

**Comment by dczarny** [comment]
VERBOSE: [17:37:47][Invoke-DbaDbLogShipping] Started log shipping for <SourceSQLServer> to <DestSQLServer>
VERBOSE: [17:37:47][Invoke-DbaDbLogShipping] Connection timeout of [<SourceSQLServer>] is set to 0
VERBOSE: [17:37:47][Invoke-DbaDbLogShipping] Testing backup network path \\<BACKUPLocation>\SQLBackups\<SourceSQLServer>
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Setting backup compression to default server setting 1.
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Destination database status set to NO RECOVERY
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] History retention set to 14420
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Restore delay set to 0
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Primary monitor server security mode set to 1
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Secondary monitor server security mode set to 1
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Backup frequency interval set to EveryDay
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Backup frequency relative interval set to Unused
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Backup frequency recurrence factor set to 0
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Copy frequency interval set to EveryDay
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Copy frequency relative interval set to Unused
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Copy frequency recurrence factor set to 0
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Restore frequency interval set to EveryDay
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Restore frequency relative interval set to Unused
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Restore frequency recurrence factor set to 0
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Connection timeout of [<DestSQLServer>] is set to 0
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Testing copy destination path \\<DestSQLServer>\TranLog_Xfer
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Backup local path set to \\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>.
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Backup network path set to \\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>.
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Testing database backup network path \\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Backup job name set to LSBackup_<DBName>
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Backup job schedule name set to LSBackupSchedule_<DBName>
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Set option to initialize secondary database with full backup
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Restore data folder or restore log folder are not set. Using server defaults
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Restore data folder set to M:\Microsoft SQL Server\MSSQL\Data
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Restore log folder set to L:\Microsoft SQL Server\MSSQL\Data
VERBOSE: [17:37:48][Invoke-DbaDbLogShipping] Testing database restore data path M:\Microsoft SQL Server\MSSQL\Data
VERBOSE: [17:37:49][Invoke-DbaDbLogShipping] Testing database restore log path L:\Microsoft SQL Server\MSSQL\Data
VERBOSE: [17:37:49][Invoke-DbaDbLogShipping] Copy destination folder set to \\<DestSQLServer>\TranLog_Xfer\<DBName>.
VERBOSE: [17:37:49][Invoke-DbaDbLogShipping] Copy job name set to LSCopy_<SourceSQLServer>_<DBName>
VERBOSE: [17:37:49][Invoke-DbaDbLogShipping] Copy job schedule name set to LSCopySchedule_<SourceSQLServer>_<DBName>
VERBOSE: [17:37:49][Invoke-DbaDbLogShipping] Testing database copy destination path \\<DestSQLServer>\TranLog_Xfer\<DBName>
VERBOSE: Performing the operation "Creating copy destination folder on <DestSQLServer>" on target "<DestSQLServer>".
VERBOSE: [17:37:49][Invoke-Command2] Copy destination folder \\<DestSQLServer>\TranLog_Xfer\<DBName> not found. Trying to create it.. .
VERBOSE: [17:37:50][Invoke-DbaDbLogShipping] Restore job name set to LSRestore_<SourceSQLServer>_<DBName>
VERBOSE: [17:37:50][Invoke-DbaDbLogShipping] Restore job schedule name set to LSRestoreSchedule_<SourceSQLServer>_<DBName>
VERBOSE: Performing the operation "Backing up database [<DBName>]" on target "<SourceSQLServer>".
VERBOSE: [17:37:50][Invoke-DbaDbLogShipping] Generating full backup.
VERBOSE: [17:37:50][Invoke-DbaDbLogShipping] Backing up database [<DBName>] to \\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>
VERBOSE: [17:37:50][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [17:37:50][Backup-DbaDatabase] 1 database to backup
VERBOSE: [17:37:50][Backup-DbaDatabase] Backup database [<DBName>]
VERBOSE: [17:37:50][Backup-DbaDatabase] Creating full backup
VERBOSE: [17:37:50][Backup-DbaDatabase] Building file name
VERBOSE: [17:37:50][Backup-DbaDatabase] Building backup path
VERBOSE: [17:37:50][Backup-DbaDatabase] Devices added
VERBOSE: [17:37:53][Get-DbaBackupHistory] Processing <DBName>
VERBOSE: [17:37:53][Get-DbaBackupHistory] Executing sql query.
VERBOSE: [17:37:53][Get-DbaBackupHistory] Processing as grouped output.
VERBOSE: [17:37:53][Get-DbaBackupHistory] 1 result-groups found.
VERBOSE: [17:37:53][Invoke-DbaDbLogShipping] Backup completed.
VERBOSE: [17:37:53][Invoke-DbaDbLogShipping] Backup is located at \\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>\FullBackup_<DBName>_PreLogShipping_20190512173750.bak
VERBOSE: [17:37:53][Invoke-DbaDbLogShipping] Setting monitor server for primary server to <SourceSQLServer>.
VERBOSE: Performing the operation "Restoring database [<DBName>] to <DBName> on <DestSQLServer>" on target "<DestSQLServer>".
VERBOSE: [17:37:53][Invoke-DbaDbLogShipping] Start database restore
VERBOSE: [17:37:53][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [17:37:53][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [17:37:53][Restore-DbaDatabase] Unverified input, full scans - \\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>\FullBackup_<DBName>_PreLogShipping_20190512173750.bak
VERBOSE: [17:37:53][Get-DbaBackupInformation] Testing a single file @{Length=90; FullName=\\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>\FullBackup_<DBName>_PreLogShipping_20190512173750.bak} 
VERBOSE: [17:37:54][Get-DbaBackupInformation] Reading backup headers of 1 files
VERBOSE: [17:37:54][Read-DbaBackupHeader] Checking: @{Length=90; FullName=\\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>\FullBackup_<DBName>_PreLogShipping_20190512173750.bak}
VERBOSE: [17:37:54][Read-DbaBackupHeader] 1 unique files to scan.
VERBOSE: [17:37:54][Read-DbaBackupHeader] Checking accessibility for all the files.
VERBOSE: [17:37:54][Read-DbaBackupHeader] Scanning file \\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>\FullBackup_<DBName>_PreLogShipping_20190512173750.bak.
VERBOSE: [17:37:57][Restore-DbaDatabase] Processing DatabaseName - <DBName>
VERBOSE: [17:37:57][Format-DbaBackupInformation] Starting
VERBOSE: [17:37:57][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [17:37:57][Format-DbaBackupInformation] New DbName (String) = <DBName>
VERBOSE: [17:37:57][Format-DbaBackupInformation]  1 PhysicalName = F:\MSSQL\Data\<DBName>_Data.MDF 
VERBOSE: [17:37:57][Format-DbaBackupInformation] PhysicalName = M:\Microsoft SQL Server\MSSQL\Data\<DBName>_Data.MDF 
VERBOSE: [17:37:57][Format-DbaBackupInformation]  1 PhysicalName = L:\MSSQL\Log\<DBName>_Log.LDF 
VERBOSE: [17:37:57][Format-DbaBackupInformation] PhysicalName = L:\Microsoft SQL Server\MSSQL\Data\<DBName>_Log.LDF 
VERBOSE: [17:37:57][Select-DbaBackupInformation] Filtering by DatabaseName
VERBOSE: [17:37:57][Select-DbaBackupInformation] processing diffs
VERBOSE: [17:37:57][Select-DbaBackupInformation] Found LogBaseLsn: 10395000000102000001 and FirstRecoveryForkID: 
VERBOSE: [17:37:57][Restore-DbaDatabase] VerifyOnly = False
VERBOSE: [17:37:57][Test-DbaBackupInformation] Testing restore for <DBName>
VERBOSE: [17:37:57][Test-DbaBackupInformation] VerifyOnly = False
VERBOSE: [17:37:58][Test-DbaLsnChain] Testing LSN Chain
VERBOSE: [17:37:58][Test-DbaLsnChain] Testing LSN Chain - Type Type
VERBOSE: [17:37:58][Test-DbaLsnChain] Passed LSN Chain checks
VERBOSE: [17:37:58][Test-DbaBackupInformation] Marking <DBName> as verified
VERBOSE: [17:37:58][Restore-DbaDatabase] <DBName> passed testing
VERBOSE: [17:37:58][Restore-DbaDatabase] Passing in to restore
VERBOSE: [17:37:58][Invoke-DbaAdvancedRestore] Performing restore action
VERBOSE: [17:38:02][Invoke-DbaAdvancedRestore] Succeeded, Closing Server connection
VERBOSE: [17:38:02][Invoke-DbaDbLogShipping] Restore completed.
VERBOSE: Performing the operation "Configuring logshipping for primary database [<DBName>] on <SourceSQLServer>" on target "<SourceSQLServer>".
VERBOSE: [17:38:02][Invoke-DbaDbLogShipping] Configuring logshipping for primary database
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Setting backup compression to 1.
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Setting Threshold alert to 0.
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Configuring logshipping for primary database <DBName>.
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Executing query:

        DECLARE @LS_BackupJobId AS uniqueidentifier;
        DECLARE @LS_PrimaryId AS uniqueidentifier;
        EXEC master.sys.sp_add_log_shipping_primary_database
            @database = N'<DBName>'
            ,@backup_directory = N'\\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>'
            ,@backup_share = N'\\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>'
            ,@backup_job_name = N'LSBackup_<DBName>'
            ,@backup_retention_period = 4320
            ,@backup_threshold = 60
            ,@history_retention_period = 14420
            ,@backup_job_id = @LS_BackupJobId OUTPUT
            ,@primary_id = @LS_PrimaryId OUTPUT 
            ,@monitor_server = N'<SourceSQLServer>'
            ,@monitor_server_security_mode = 1
            ,@threshold_alert = 14420
            ,@threshold_alert_enabled = 0
                ,@ignoreremotemonitor = 1
            ,@overwrite = 1;
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Configuring monitor server for primary database <DBName>.
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Executing query:
EXEC msdb.dbo.sp_processlogshippingmonitorprimary @mode = 1
                    ,@primary_id = '6a02ce32-3bcf-4d4f-a7d9-35a1dfa5c079'
                    ,@primary_server = '<SourceSQLServer>'
                    ,@monitor_server = '<SourceSQLServer>' 
                    ,@monitor_server_security_mode = 1
                    ,@primary_database = '<DBName>'
                    ,@backup_threshold = 60
                    ,@threshold_alert = 14420
                    ,@threshold_alert_enabled = 0
                    ,@history_retention_period = 14420
                
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Updating monitor information for the primary database <DBName>.
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Executing query:

                    UPDATE msdb.dbo.log_shipping_primary_databases
                    SET monitor_server = '<SourceSQLServer>', user_specified_monitor = 1
                    WHERE primary_id = '6a02ce32-3bcf-4d4f-a7d9-35a1dfa5c079'
                
VERBOSE: [17:38:03][New-DbaLogShippingPrimaryDatabase] Finished adding the primary database <DBName> to log shipping.
VERBOSE: [17:38:03][Set-DbaAgentJob] Setting job to enabled
VERBOSE: [17:38:03][Set-DbaAgentJob] Changing the job
VERBOSE: [17:38:03][Set-DbaAgentJob] Finished changing job(s)
VERBOSE: [17:38:03][Invoke-DbaDbLogShipping] Enabling backup job LSBackup_<DBName>
VERBOSE: [17:38:03][Invoke-DbaDbLogShipping] Create backup job schedule LSBackupSchedule_<DBName>
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule to enabled
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule frequency interval to 1
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule frequency to 4
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule frequency subday type to 4
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule frequency subday interval to 5
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule start date to 2019-05-11
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule end date to 9999-12-31
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule start time to 08:04:00
VERBOSE: [17:38:03][New-DbaAgentSchedule] Setting job schedule end time to 08:03:59
VERBOSE: [17:38:03][New-DbaAgentSchedule] Adding the schedule LSBackupSchedule_<DBName> to job LSBackup_<DBName>
VERBOSE: [17:38:03][New-DbaAgentSchedule] Job schedule created with UID 75382486-8b23-46da-aa5e-d8498f79f360
VERBOSE: [17:38:03][New-DbaAgentSchedule] Finished creating job schedule(s).
VERBOSE: [17:38:03][Invoke-DbaDbLogShipping] Configuring logshipping from primary to secondary database.
VERBOSE: [17:38:04][New-DbaLogShippingPrimarySecondary] Executing query:
SELECT primary_database FROM msdb.dbo.log_shipping_primary_databases WHERE primary_database = '<DBName>'
VERBOSE: [17:38:04][New-DbaLogShippingPrimarySecondary] Configuring logshipping connecting the primary database <DBName> to secondary database <DBName> on <SourceSQLServer>.
VERBOSE: [17:38:04][New-DbaLogShippingPrimarySecondary] Executing query:
EXEC master.sys.sp_add_log_shipping_primary_secondary
        @primary_database = N'<DBName>'
        ,@secondary_server = N'<DestSQLServer>'
        ,@secondary_database = N'<DBName>' ,@overwrite = 1;
VERBOSE: [17:38:04][New-DbaLogShippingPrimarySecondary] Finished configuring of primary database <DBName> to secondary database <DBName>.
VERBOSE: Performing the operation "Configuring logshipping for secondary database <DBName> on <DestSQLServer>" on target "<DestSQLServer>".
VERBOSE: [17:38:04][Invoke-DbaDbLogShipping] Configuring logshipping from secondary database <DBName> to primary database [<DBName>].
VERBOSE: [17:38:04][New-DbaLogShippingSecondaryPrimary] Configuring logshipping making settings for the primary database.
VERBOSE: [17:38:04][New-DbaLogShippingSecondaryPrimary] Executing query:

        DECLARE @LS_Secondary__CopyJobId AS uniqueidentifier
        DECLARE @LS_Secondary__RestoreJobId	AS uniqueidentifier
        DECLARE @LS_Secondary__SecondaryId AS uniqueidentifier
        EXEC master.sys.sp_add_log_shipping_secondary_primary
                @primary_server = N'<SourceSQLServer>'
                ,@primary_database = N'<DBName>'
                ,@backup_source_directory = N'\\<BACKUPLocation>\SQLBackups\<SourceSQLServer>\<DBName>'
                ,@backup_destination_directory = N'\\<DestSQLServer>\TranLog_Xfer\<DBName>'
                ,@copy_job_name = N'LSCopy_<SourceSQLServer>_<DBName>'
                ,@restore_job_name = N'LSRestore_<SourceSQLServer>_<DBName>'
                ,@file_retention_period = 4320
                ,@copy_job_id = @LS_Secondary__CopyJobId OUTPUT
                ,@restore_job_id = @LS_Secondary__RestoreJobId OUTPUT
                ,@secondary_id = @LS_Secondary__SecondaryId OUTPUT ,@monitor_server = N'<DestSQLServer>'
                ,@monitor_server_security_mode = 1 ,@overwrite = 1;
VERBOSE: [17:38:04][New-DbaLogShippingSecondaryPrimary] Finished configuring of secondary database to primary database <DBName>.
VERBOSE: [17:38:04][Invoke-DbaDbLogShipping] Create copy job schedule LSCopySchedule_<SourceSQLServer>_<DBName>
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule to enabled
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule frequency interval to 1
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule frequency to 4
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule frequency subday type to 4
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule frequency subday interval to 5
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule start date to 2019-05-11
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule end date to 9999-12-31
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule start time to 08:07:00
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule end time to 08:06:59
VERBOSE: [17:38:05][New-DbaAgentSchedule] Adding the schedule LSCopySchedule_<SourceSQLServer>_<DBName> to job LSCopy_<SourceSQLServer>_<DBName>
VERBOSE: [17:38:05][New-DbaAgentSchedule] Job schedule created with UID ad1a146d-0e99-43c8-99cf-41ab312eed7c
VERBOSE: [17:38:05][New-DbaAgentSchedule] Finished creating job schedule(s).
VERBOSE: [17:38:05][Invoke-DbaDbLogShipping] Create restore job schedule LSRestoreSchedule_<SourceSQLServer>_<DBName>
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule to enabled
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule frequency interval to 1
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule frequency to 4
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule frequency subday type to 4
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule frequency subday interval to 5
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule start date to 2019-05-11
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule end date to 9999-12-31
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule start time to 08:10:00
VERBOSE: [17:38:05][New-DbaAgentSchedule] Setting job schedule end time to 08:09:59
VERBOSE: [17:38:05][New-DbaAgentSchedule] Adding the schedule LSRestoreSchedule_<SourceSQLServer>_<DBName> to job LSRestore_<SourceSQLServer>_<DBName>
VERBOSE: [17:38:05][New-DbaAgentSchedule] Job schedule created with UID d6e6ff2a-a171-4551-92af-66f190b6718d
VERBOSE: [17:38:05][New-DbaAgentSchedule] Finished creating job schedule(s).
VERBOSE: [17:38:05][Invoke-DbaDbLogShipping] Configuring logshipping for secondary database.
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Setting Threshold alert to 1.
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Setting disconnect users to 0.
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Configuring logshipping for secondary database <DBName> on <DestSQLServer>.
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Executing query:
EXEC master.sys.sp_add_log_shipping_secondary_database
        @secondary_database = '<DBName>'
        ,@primary_server = '<SourceSQLServer>'
        ,@primary_database = '<DBName>'
        ,@restore_delay = 0
        ,@restore_all = 1
        ,@restore_mode = 0
        ,@disconnect_users = 0
        ,@restore_threshold = 60
        ,@threshold_alert = 14420
        ,@threshold_alert_enabled = 1
        ,@history_retention_period = 14420 
        ,@ignoreremotemonitor = 1;
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Configuring monitor server for secondary database <DBName>.
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Executing query:
EXEC msdb.dbo.sp_processlogshippingmonitorsecondary @mode = 1
                    ,@secondary_server = '<DestSQLServer>'
                    ,@secondary_database = '<DBName>'
                    ,@secondary_id = 'e744b816-04a6-4e93-891f-7d2b720a63e4'
                    ,@primary_server = '<SourceSQLServer>'
                    ,@primary_database = '<DBName>'
                    ,@restore_threshold = 60
                    ,@threshold_alert = 14420
                    ,@threshold_alert_enabled = 1
                    ,@history_retention_period = 14420
                    ,@monitor_server = '<SourceSQLServer>'
                    ,@monitor_server_security_mode = 1 
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Updating monitor information for the secondary database <DBName>.
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Executing query:

                UPDATE msdb.dbo.log_shipping_secondary
                SET monitor_server = '<SourceSQLServer>', user_specified_monitor = 1
                WHERE secondary_id = 'e744b816-04a6-4e93-891f-7d2b720a63e4'
                
VERBOSE: [17:38:06][New-DbaLogShippingSecondaryDatabase] Finished adding the secondary database <DBName> to log shipping.
VERBOSE: [17:38:07][Set-DbaAgentJob] Setting job to enabled
VERBOSE: [17:38:07][Set-DbaAgentJob] Changing the job
VERBOSE: [17:38:07][Set-DbaAgentJob] Finished changing job(s)
VERBOSE: [17:38:08][Set-DbaAgentJob] Setting job to enabled
VERBOSE: [17:38:08][Set-DbaAgentJob] Changing the job
VERBOSE: [17:38:08][Set-DbaAgentJob] Finished changing job(s)
VERBOSE: [17:38:08][Invoke-DbaDbLogShipping] Completed configuring log shipping for database [<DBName>]


PrimaryInstance   : <SourceSQLServer>
SecondaryInstance : <DestSQLServer>
PrimaryDatabase   : <DBName>
SecondaryDatabase : <DBName>
Result            : Success
Comment           : 

VERBOSE: [17:38:08][Invoke-DbaDbLogShipping] Finished setting up log shipping.

**Comment by dczarny** [comment]
I had a chance to look at this, but don't know how to debug to confirm.  In the Invoke-DbaDbLogShipping.ps1 file down near line 1704, there the following code.  This looks to be in the section that is dealing with the secondary monitor server that is overriding the previous statements:

                            New-DbaLogShippingSecondaryDatabase -SqlInstance $destInstance `
                                -SqlCredential $DestinationSqlCredential `
                                -SecondaryDatabase $SecondaryDatabase `
                                -PrimaryServer $SourceSqlInstance `
                                -PrimaryDatabase $($db.Name) `
                                -RestoreDelay $RestoreDelay `
                                -RestoreMode $DatabaseStatus `
                                -DisconnectUsers:$DisconnectUsers `
                                -RestoreThreshold $RestoreThreshold `
                                -ThresholdAlertEnabled:$SecondaryThresholdAlertEnabled `
                                -HistoryRetention $HistoryRetention `
                                -MonitorServer $PrimaryMonitorServer `
                                -MonitorServerSecurityMode $PrimaryMonitorServerSecurityMode `
                                -MonitorCredential $PrimaryMonitorCredential
