### ISSUE TITLE
[Bug] Get-DBACmsRegServer is not displaying server details.

### ISSUE THREAD

**Issue by mgstegmaier** [sqlcollaborative/dbatools#5441]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```
& {"### PowerShell version:`n$($PSVersionTable | Out-String)"; "`n### dbatools Module version:`n$(gmo dbatools -List | select name, path, version | fl -force | Out-String)"}
```

- [ ] *Running latest release of dbatools* - 
- [x] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1




### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.818\dbatools.psd1
Version : 0.9.818

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.809\dbatools.psd1
Version : 0.9.809
```

### SQL Server: 

```sql
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64)   Sep  7 2018 01:37:51   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

## Steps to Reproduce

```powershell
<#
    $CMSInstance = 'C500SQLUTIL01'
$CustomerInstances = Get-DbaCmsRegServer $CMSInstance
#>
```

## Expected Behavior
It should show details about the registered server as shown in the article https://dbatools.io/cms/:
Name | Servername | Group | Description

## Actual Behavior
Only displays 2 blank columns. No details are shown about the servers, but there is a blank line for each registered server

Mode Name

![image](https://user-images.githubusercontent.com/46787066/56980327-b2e66280-6b41-11e9-965a-35be87ed3184.png)

**Comment by potatoqualitee** [comment]
thanks for the report - those are two strange columns. can you please close it out, open powershell.exe, ensure `sqlserver` or `sqlps` is not loaded then try again? we do not show mode at all.

**Comment by mgstegmaier** [comment]
That worked, thanks. I will have to be mindful of that. I don't remember
loading those modules, but I must have in my monkeying around in Visual
Studio Code.
--
Michael Stegmaier
stegmaier@gmail.com

**Comment by potatoqualitee** [comment]
excellent news! thanks again for the report
