### ISSUE TITLE
AccessToken notes

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5445]
So thinking if someone uses `New-DbaAzAccessToken` it saves their params and potentially reissues it when Connect-SqlInstance is called if specific requirements are met (like server name prolly)

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/44de9571-f50c-4959-aac1-ed3987d22689/azure-function-sql-connection-is-lost-after-some-period-of-activity?forum=AzureFunctions

> Ideally, you should call the GetAccessTokenAsync method in each function call to be sure that the token used is valid. The framework caches the last valid access token and only fetches a new one if expiry is within the next 5 minutes, so you don't have to worry about multiple requests being made.

**Comment by potatoqualitee** [comment]
This is interesting: https://serverfault.com/questions/944468/login-failed-for-user-nt-authority-anonymous-logon-on-azure-sql-with-active-di

**Comment by potatoqualitee** [comment]
Cert login: 

```
X509Certificate2 certificate;
    using (var certificateStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
    {
        certificateStore.Open(OpenFlags.ReadOnly);
        certificate = certificateStore.Certificates
            .Find(X509FindType.FindBySubjectDistinguishedName, certificateSDN, false)
            [0];
    }

    var authenticationContext = new AuthenticationContext($"https://login.microsoftonline.com/{tenantId}");
    var clientAssertionCertificate = new ClientAssertionCertificate(clientId, certificate);
    var authenticationResult = await authenticationContext.AcquireTokenAsync(resource, clientAssertionCertificate);

    return authenticationResult.AccessToken;
```

https://stackoverflow.com/questions/48560663/token-based-database-authentication-fails-with-login-failed-for-user-nt-author

**Comment by potatoqualitee** [comment]
step by step for something else that could be of use

https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi#grant-permissions-to-azure-active-directory-group

**Comment by potatoqualitee** [comment]
This could potentially show the actual issue, reconnect to master?

https://social.msdn.microsoft.com/Forums/azure/en-US/42424d1c-d2ac-4b73-8fb9-4bf64b9350b1/quotlogin-failed-for-user-quot-sqlexception-when-accessing-azure-sql-db-via-msi-with-a-ef?forum=adodotnetentityframework

**Comment by potatoqualitee** [comment]
Per https://github.com/microsoft/sqltoolsservice/issues/808#issuecomment-492243750

> If you can use .Net 4.7.2, I recommend using 'Authentication=Active Directory Interactive' in the connection string, and install a SqlAuthenticationProvider implementation to provide the token. Look up SqlAuthenticationProvider.SetProvider.

> Otherwise, the only way the ServerConnection object can assign an access token to SqlConnection objects it creates is if you pass in an IRenewableToken implementation to its constructor.
SMO sometimes creates new connections behind your back, which leads to these errors if you don't use either Interactive auth or IRenewableToken.

**Comment by wsmelton** [comment]
OK, see this is the point `IRenewableToken` is the proper way to pass in the token for SMO to make that connection....but there is not one like of documentation or examples on how that object type is to be created.

If they will just provide that we can move on with this to show users and how our new token command should be output the object.

**Comment by potatoqualitee** [comment]
I agree. I saw that @spaghettidba was doing some advanced stuff in C#, perhaps he could assist? Maybe the C# docs would be helpful to him and we could take his code and Add-Type it?

**Comment by rdtechie** [comment]
Sorry to interrupt, but is this issue the reason why I get the following error message?


I've created an Azure SQL Database. I created a SPN. I added this SPN to the database with:
```
CREATE USER [testrdisqladmin01] FROM EXTERNAL PROVIDER
EXEC sp_addrolemember 'db_owner', 'testrdisqladmin01'
```
Then I did this to test it:
```
$creds = Get-Credential
$token = New-DbaAzAccessToken -Type ServicePrincipal -Credential $creds -Tenant 'thisismyscrettenantid'
$server = Connect-DbaInstance -SqlInstance 'testrdisqlserver01.database.windows.net' -Database 'testrdisql01' -AccessToken $token -DisableException
Invoke-DbaQuery -SqlInstance $server -Query "select count(*) from systables"
```
And then it fails with:
`WARNING: [11:12:57][Invoke-DbaQuery] Failure | Login failed for user ''.`

**Comment by potatoqualitee** [comment]
interesting! i'm sure it is. thank you for that, ill take a look there too.

**Comment by potatoqualitee** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlauthenticationprovider?view=netframework-4.8

**Comment by potatoqualitee** [comment]
this is amazing for an interactive window

https://github.com/lazywinadmin/MVP/blob/master/MVP/Private/Get-MVPOAuthAutorizationCode.ps1

**Comment by potatoqualitee** [comment]
This gets a token but the token is useless

```powershell
$Authority = "https://login.windows.net/$TenantID/oauth2/token"

[Reflection.Assembly]::LoadWithPartialName("System.Web") | Out-Null
$EncodedKey = [System.Web.HttpUtility]::UrlEncode($ClientKey)

$body = "grant_type=client_credentials&client_id=$AppID&client_secret=$EncodedKey&resource=$ResourceUrl"

# Request a Token from the graph api
$result = Invoke-RestMethod -Method Post `
    -Uri $Authority `
    -ContentType 'application/x-www-form-urlencoded' `
    -Body $body
					
$token = $result.access_token
```

**Comment by potatoqualitee** [comment]
Ohh?

https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#running-the-application-using-a-service-principal

```powershell
$env:AzureServicesAuthConnectionString = "RunAs=App;AppId={xyz};TenantId={abc};AppKey={123}"
Connect-DbaInstance -SqlInstance "Data Source=tcp:psdbatools.database.windows.net;Initial Catalog=abc;Authentication=Active Directory Interactive;UID=anystring;"
```

**Comment by potatoqualitee** [comment]
can confirm! WORKSSSSSSS

![image](https://user-images.githubusercontent.com/8278033/58360561-ba233680-7e89-11e9-8eab-82b00752c7d9.png)

**Comment by wsmelton** [comment]
Does it work same way if we can't use environment variables?

**Comment by potatoqualitee** [comment]
On prem, it will with @StartAutomating 's implementation but not mine.  In azure, you do not need the env var.

**Comment by potatoqualitee** [comment]
Something to note: 

> To control the process, use a connection string passed to the AzureServiceTokenProvider constructor or specified in the AzureServicesAuthConnectionString environment variable.

So it may work if I changed it to use AzureServiceTokenProvider class

**Comment by potatoqualitee** [comment]
shawn, the command will build that environment variable. it doesnt have to be stored. would that work for you?

**Comment by wsmelton** [comment]
Does Linux support the environment variable?

**Comment by wsmelton** [comment]
I would assume it works in Linux the same way. If it does I would be curious to know how this works if the variable is already configured for use on another client application? Do we overwrite it, throw a warning that it already exist, see if it matches the one passed in?

**Comment by potatoqualitee** [comment]
yes, Linux supports environmental variables but the dlls i use arent core compat so the approach it takes uses invoke-restmethod so that works

**Comment by rdtechie** [comment]
That looks promising. So if I understand correctly there's no need to grab the token first if a SPN is used?

**Comment by potatoqualitee** [comment]
correct. check out the examples listed here: https://github.com/sqlcollaborative/dbatools/pull/5593

i also recommend .NET 4.7.2+ if you can. They made some enhancements to system.data.sqlclient that are make it faster, more reliable and awesome.

**Comment by potatoqualitee** [comment]
note that these changes are only available in the `prerelease` branch
