### ISSUE TITLE
ConvertTo-DBATable and Write-DBADbTableData not writing data to table

### ISSUE THREAD

**Issue by dczarny** [sqlcollaborative/dbatools#5446]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```
& {"### PowerShell version:`n$($PSVersionTable | Out-String)"; "`n### dbatools Module version:`n$(gmo dbatools -List | select name, path, version | fl -force | Out-String)"}
```

- [X] *Running latest release of dbatools*
- [X] Verified errors are not related to permissions
- [X] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

### PowerShell version:

Name                           Value                                                                                                                                        
----                           -----                                                                                                                                        
PSVersion                      5.1.17134.590                                                                                                                                
PSEdition                      Desktop                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                      
BuildVersion                   10.0.17134.590                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                              
WSManStackVersion              3.0                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                      

### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.819\dbatools.psd1
Version : 0.9.819

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.780\dbatools.psd1
Version : 0.9.780

### SQL Server: 

Microsoft SQL Server 2017 (RTM-CU14) (KB4484710) - 14.0.3076.1 (X64)   Mar 12 2019 19:29:19   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

## Errors Received

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: The given ColumnMapping does not match up with any column in the source or destination. ---> 
                        System.Management.Automation.MethodInvocationException: Exception calling "WriteToServer" with "1" argument(s): "The given ColumnMapping does not match up 
                        with any column in the source or destination." ---> System.InvalidOperationException: The given ColumnMapping does not match up with any column in the 
                        source or destination.
                           at System.Data.SqlClient.SqlBulkCopy.AnalyzeTargetAndCreateUpdateBulkCommand(BulkCopySimpleResultSet internalResults)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, 
                        TaskCompletionSource`1 source)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
                           at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
                           --- End of inner exception stack trace ---
TargetObject          : <ServerName>
CategoryInfo          : NotSpecified: (<ServerName>:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Write-DbaDbTableData,Stop-Function
ErrorDetails          : The given ColumnMapping does not match up with any column in the source or destination.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.819\allcommands.ps1: line 109959
                        at Write-DbaDbTableData<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.819\allcommands.ps1: line 108611
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

## Steps to Reproduce

$test = "Select name from sys.databases"
$test2 = Invoke-Sqlcmd -ServerInstance <ServerName>-Query $test | Select-Object {$_.Name} | ConvertTo-DbaDataTable

Write-DbaDataTable -SqlInstance <ServerName> -Database <DBName>-InputObject $test2 -Table "test2"

WARNING: [07:52:33][Write-DbaDbTableData] Failed to bulk import to [<DBName>].[dbo].[test2] | The given ColumnMapping does not match up with any column in the source or destination.

## Expected Behavior

Expected the table to have values from the query.  This worked correctly in 0.9.517 (last version I was using)

## Actual Behavior

Table is empty.

**Comment by potatoqualitee** [comment]
hey @dczarny  - try without the explicit ` | ConvertTo-DbaDataTable` - if that does not work, please put the output of -verbose

**Comment by dczarny** [comment]
Invoke-Sqlcmd -ServerInstance <ServerName> -Query $test | Select-Object {$_.Name}

$_.Name           
-------           
master            
tempdb            
model             
msdb              
ReportServer      
ReportServerTempDB
DBACentral        
tpch              
SSISDB

**Comment by dczarny** [comment]
Write-DbaDataTable -SqlInstance <ServerName> -Database DBACentral -InputObject $test2 -Table "test2" -ErrorAction Continue -Verbose
VERBOSE: [08:05:44][Write-DbaDbTableData] FQTN processed: [DBACentral].[dbo].[test2]
VERBOSE: [08:05:46][Invoke-BulkCopy] Importing in bulk to [DBACentral].[dbo].[test2]
WARNING: [08:05:48][Write-DbaDbTableData] Failed to bulk import to [DBACentral].[dbo].[test2] | The given ColumnMapping does not match up with any column in the source or destination
.
VERBOSE: [08:05:48][Invoke-BulkCopy] Importing in bulk to [DBACentral].[dbo].[test2]

**Comment by dczarny** [comment]
When I run this on the 0.9.517 version it works properly.  I didn't know if anything changed that maybe I needed to change what I was doing.

**Comment by wsmelton** [comment]
@dczarny you can edit a post so the context stays with it.
```
As well wrapping output in 3 single-ticks will help it be a bit more readable
```

**Comment by potatoqualitee** [comment]
`$_.Name` is a tough column name. Can you try with `| Select-Object Name`

**Comment by dczarny** [comment]
That worked.  I figured it was probably something I was doing.  I didn't know you could just list the name of the columns, I thought you had to do all that funny syntax.  I will test it out with my other scripts.  Thank you.

**Comment by potatoqualitee** [comment]
excellent!

**Comment by dczarny** [comment]
I seemed to still be having trouble with some other scripts I have when I convert the columns to just names
.  How is the ConvertTo-DbaDataTable Sorting and mapping columns to the Write-DBADbTableData?

**Comment by potatoqualitee** [comment]
you should no longer be using `ConvertTo-DbaDataTable`

**Comment by dczarny** [comment]
Oh.  What is the replacement for it?  Or is there a replacement for it?

**Comment by potatoqualitee** [comment]
no replacement, it's built in to the write

**Comment by dczarny** [comment]
Thank you.

**Comment by potatoqualitee** [comment]
@ClaudioESSilva - can you test if your fix fixes this?

**Comment by dczarny** [comment]
It did. I haven't had any issues since piping directly to it.

Thank you,
Derek Czarny

________________________________
