### ISSUE TITLE
[Bug] Update-DbaInstance uses the same folder to extract the files

### ISSUE THREAD

**Issue by garethnewman** [sqlcollaborative/dbatools#5447]
dbatools 0.9.789
powershell 5.1.14409.1018

- [ X] Verified errors are not related to permissions

When running against computers which can all see the cluster mounted volumes. It attempts to copy and extract the file to the same location causing issues such as files exist/can't cleanup.

It chooses the largest available disk for the temp location, in my case that is the same disk for more than 1 server as they can all see the cluster mounted volumes.

Being able to specify the temp location would be good, so I can just say put it in "C:\Temp" and then avoid this scenario, is this possible?

The actual function is Invoke-DbaAdvancedUpdate.ps1

"# Find a temporary folder to extract to - the drive that has most free space"

**Comment by potatoqualitee** [comment]
Thanks for the report! We'll take a look when we have a moment.

**Comment by nvarscar** [comment]
I'll look into it and either adopt your proposal or add some kind of UID to the temp folder name. Or both 🙂
Thanks for reporting!

**Comment by garethnewman** [comment]
UID sounds good, thanks @nvarscar

**Comment by garethnewman** [comment]
Thanks @nvarscar - just installing more updates and noticed the folder name had a UID and was like hmm, he did it already :dancer:
