### ISSUE TITLE
[Bug]Various functions handling return from test-bound for switches incorrectly

### ISSUE THREAD

**Issue by cfradenburg** [sqlcollaborative/dbatools#5449]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```
& {"### PowerShell version:`n$($PSVersionTable | Out-String)"; "`n### dbatools Module version:`n$(gmo dbatools -List | select name, path, version | fl -force | Out-String)"}
```

- [x] *Running latest release of dbatools*
- [x] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data

```
### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1




### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.809\dbatools.psd1
Version : 0.9.809
```

### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

## Steps to Reproduce

```powershell
Enable-DbaAgHadr <servername> -Force:$false -WhatIf
```

## Expected Behavior

> What if: Performing the operation "Changing Hadr from False to 1 for <servername>" on target "<servername>".
> WARNING: [16:13:59][Enable-DbaAgHadr] You must restart the SQL Server for it to take effect.

## Actual Behavior

> What if: Performing the operation "Changing Hadr from False to 1 for <servername>" on target "<servername>".
> What if: Performing the operation "Force provided, restarting Engine and Agent service for <servername>on <servername>" on target "<servername>".

This is just one example of this.  It can also be seen with `Invoke-DbaQuery -Verbose:$false`, `Backup-DbaDatabase -AzureBaseUrl "Blah" -CreateFolder:$false` and several others.

See #5409 where I initially reported it with Verbose output on Invoke-DbaQuery for more discussion.  A particularly relevant part is:

> I tested changing the Test-Bound check from $BoundParameters.ContainsKey($name) to $BoundParameters[$name] and it appears to properly check both switch and non-switch parameters.
> 
> `Backup-DbaDatabase -SqlInstance <servername> -AzureBaseUrl "http://fakeaddress" -CreateFolder -WhatIf`
> 
> That triggers the check but not passing in AzureBaseURL or CreateFolder:$false doesn't.
> 
> The alternative is to leave Test-Bound alone and check all references to it that use a switch to make sure they're checking the value afterwards. Theoretically that's the safer bet but only if there's someplace that differentiates between the switch not being passed in and it being passed in as $false.

The simplest fix is to make that change to Test-Bound but what's simplest isn't always best.

**Comment by potatoqualitee** [comment]
Thanks for the report 👍 . I'll ask @FriedrichWeinmann to take a look. He's at PS Summit and may not be immediately available.

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann any chance you can get to this before June 20?
