### ISSUE TITLE
Get-DbaDatabaseReport

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#545]
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/BbA18oRM

Loop over all database objects and output to word or Excel with all there extended properties and a basic summary of config (If theirs a Database Best practice add that to the output maybe)

**Additional comments**

@wsmelton 
Trying to do output to Word or Excel would require dependency on Office installation. This would effect the module on machines that do not have that installed. HTML could be used to build out something, but I would strongly be against doing something with Office. I have code that builds out HTML reports including drop down menus.

This functionality is also already found in other commands like SQL Power Doc and not sure it needs to be duplicated in dbatools. This may be more suited for dbareports module.

**Comment by potatoqualitee** [comment]
out of scope
