### ISSUE TITLE
[Bug] Sync-DbaLoginPermission with error "You cannot call a method on a null-valued expression."

### ISSUE THREAD

**Issue by AndreasEDA** [sqlcollaborative/dbatools#5452]
Hi
It is only on 2 from about 20 Servers i receive the error. On the dbatools Logfile i don't see any hints about what's going on.

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.2828
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2828
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### dbatools Module version:
Name    : DbaTools
Path    : C:\Program Files\WindowsPowerShell\Modules\DbaTools\DbaTools.psd1
Version : 0.9.817
```

- [ ] *Running latest release of dbatools*
- [X] Verified errors are not related to permissions

### SQL Server: 
Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64)   Jan 10 2019 18:51:38   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

## Errors Received
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\DbaTools\allcommands.ps1:119846 char:25
+ ...         if ($sourceRole.EnumMembers() -notcontains $dbUsername -and $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

## Steps to Reproduce
Sync-DbaLoginPermission -Source EDAVSI01152 -Destination EDAVSI01151 -EnableException
->Running on the Primary Node from availability group. Same error when i run
Sync-DbaAvailabilityGroup -Primary EDAVSI01152 -AvailabilityGroup AG1

**Comment by AndreasEDA** [comment]
[dbatools_4852_message_0.log](https://github.com/sqlcollaborative/dbatools/files/3137118/dbatools_4852_message_0.log)

Here is also the logfile. Interessting is that i can't see any errors

**Comment by AndreasEDA** [comment]
When i confirm every action the error occurs here:

Confirm
Are you sure you want to perform this action?
Performing the operation "**Grant on CONNECT SQL for EDA\gmsaMIMIReport$.**" on target "EDAVSI01151".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\DbaTools\allcommands.ps1:119846 char:25
+ ...         if ($sourceRole.EnumMembers() -notcontains $dbUsername -and $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\DbaTools\allcommands.ps1:119846 char:25
+ ...         if ($sourceRole.EnumMembers() -notcontains $dbUsername -and $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by potatoqualitee** [comment]
Solid bug report, thank you. We'll take a look.

**Comment by potatoqualitee** [comment]
got in a fix in and this will be resolved in the next release due in a day or less
