### ISSUE TITLE
Allow usage of github feature 'watch/Releases only'

### ISSUE THREAD

**Issue by mi-hol** [sqlcollaborative/dbatools#5454]
### Summary of new feature

To get notifications about new release github added the feature 'watch/Releases only'.
Currently this is not applicable for dbatools because the project stopped to be make  releases downloadable for github after release v0.9.720 in Dec2018 

### Latest version of dbatools as of writing

0.9.819

**Comment by potatoqualitee** [comment]
Hello, we now release on a regular basis to GitHub 👍🏼  Each time we release to the PowerShell Gallery, the same build script adds it here as well, so feel free to watch releases only!
