### ISSUE TITLE
Integration Tests Needed

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5464]
We have about 102 commands that need Integration tests. any chance our tests team can have these addressed within 30 days (dbatools will go 1.0 for data grillen)? Even one integration test per would be fab. I'll see what I can do about the ones that are questionable at the bottom.

- [ ] Convert-DbaLsn  
- [ ] ConvertTo-DbaDataTable
- [ ] ConvertTo-DbaTimeline
- [ ] Copy-DbaAgentProxy
- [ ] Copy-DbaAgentSchedule
- [ ] Copy-DbaAgentServer
- [ ] Copy-DbaDataCollector
- [x] Copy-DbaDbMail
- [ ] Copy-DbaDbQueryStoreOption
- [x] Copy-DbaEndpoint
- [ ] Copy-DbaPolicyManagement
- [ ] Copy-DbaServerAudit
- [ ] Copy-DbaServerAuditSpecification
- [x] Copy-DbaSysDbUserObject
- [ ] Copy-DbaXESession
- [ ] Export-DbaCredential
- [ ] Export-DbaExecutionPlan
- [x] Export-DbaInstance
- [ ] Export-DbaLinkedServer
- [ ] Export-DbaRepServerSetting
- [ ] Export-DbaScript
- [ ] Export-DbaSpConfigure
- [ ] Export-DbatoolsConfig
- [ ] Export-DbaXECsv
- [ ] Find-DbaDbGrowthEvent
- [ ] Get-DbaAgentJobHistory
- [ ] Get-DbaAgentJobOutputFile
- [ ] Get-DbaAgentJobStep
- [ ] Get-DbaDbQueryStoreOption
- [x] Get-DbaDbTable
- [ ] Get-DbaDependency
- [ ] Get-DbaMaintenanceSolutionLog
- [ ] Get-DbaPbmCategorySubscription
- [ ] Get-DbaPbmCondition
- [ ] Get-DbaPbmObjectSet
- [ ] Get-DbaPbmStore
- [ ] Get-DbaQueryExecutionTime
- [ ] Get-DbaResourceGovernor
- [ ] Get-DbaRgWorkloadGroup
- [ ] Get-DbaRunningJob
- [ ] Get-DbaServerAuditSpecification
- [ ] Get-DbaServerTrigger
- [ ] Get-DbaTempdbUsage
- [ ] Get-DbatoolsConfigValue
- [ ] Get-DbatoolsLog
- [ ] Get-DbaXEObject
- [ ] Get-DbaXESessionTargetFile
- [ ] Get-DbaXESmartTarget
- [ ] Get-DbaXEStore
- [ ] Get-XpDirTreeRestoreFile
- [ ] Import-DbaSpConfigure
- [ ] Import-DbatoolsConfig
- [x] Install-DbaWhoIsActive
- [ ] Invoke-DbaDbDecryptObject
- [ ] Invoke-DbaDbUpgrade
- [ ] Invoke-DbaPfRelog
- [x] Invoke-DbaWhoisActive
- [ ] Invoke-DbaXEReplay
- [x] Measure-DbaDiskSpaceRequirement
- [ ] Measure-DbatoolsImport
- [ ] New-DbaCmConnection
- [ ] New-DbaConnectionString
- [ ] New-DbaDbMasterKey
- [x] New-DbaDbUser
- [ ] New-DbaDirectory
- [ ] New-DbaScriptingOption
- [ ] New-DbaServiceMasterKey
- [ ] New-DbaXESession
- [ ] Read-DbaBackupHeader
- [ ] Read-DbaTransactionLog
- [ ] Register-DbatoolsConfig
- [ ] Remove-DbaAgentJobStep
- [ ] Remove-DbaAgReplica
- [ ] Remove-DbaCmConnection
- [ ] Remove-DbaDbBackupRestoreHistory
- [ ] Remove-DbaDbMasterKey
- [ ] Remove-DbaDbMirror
- [ ] Remove-DbaDbOrphanUser
- [ ] Remove-DbaNetworkCertificate
- [ ] Remove-DbaXESmartTarget
- [x] Rename-DbaDatabase
- [ ] Repair-DbaDbMirror
- [ ] Repair-DbaServerName
- [ ] Reset-DbatoolsConfig
- [ ] Resolve-DbaNetworkName
- [ ] Restore-DbaBackupFromDirectory
- [ ] Save-DbaDiagnosticQueryScript
- [ ] Set-DbaAgentJob
- [ ] Set-DbaAgentJobOutputFile
- [ ] Set-DbaAgentJobOwner
- [ ] Set-DbaAgentJobStep
- [ ] Set-DbaAgListener
- [ ] Set-DbaCmConnection
- [ ] Set-DbaDbCompatibility
- [ ] Set-DbaDbMirror
- [x] Set-DbaDbOwner
- [ ] Set-DbaEndpoint
- [ ] Set-DbaPrivilege
- [ ] Set-DbaStartupParameter
- [ ] Set-DbaTcpPort
- [ ] Set-DbaTempDbConfig
- [x] Test-DbaDiskAlignment
- [ ] Unregister-DbatoolsConfig
# Here are ones that we can't test (maybe)

## Time sensitive
Find-DbaDbUnusedIndex

## Active Directory
Find-DbaLoginInGroup
Get-DbaSpn
Remove-DbaSpn
Set-DbaSpn

## SSIS
Get-DbaSsisEnvironmentVariable
Get-DbaSsisExecutionHistory
Copy-DbaSsisCatalog

## Cluster
Get-DbaWsfcAvailableDisk
Get-DbaWsfcCluster
Get-DbaWsfcDisk
Get-DbaWsfcNetwork
Get-DbaWsfcNetworkInterface
Get-DbaWsfcNode
Get-DbaWsfcResource
Get-DbaWsfcResourceType
Get-DbaWsfcRole
Get-DbaWsfcSharedVolume

## Installations and Updates
Install-DbaInstance
Install-DbaWatchUpdate
Invoke-DbaAdvancedInstall
Invoke-DbaAdvancedRestore
Invoke-DbaAdvancedUpdate
Uninstall-DbaWatchUpdate

## No point or can't test
New-DbatoolsSupportPackage
Update-dbatools

## Async / Job based
Start-DbaXESmartTarget
Stop-DbaXESmartTarget

## GUIs
Show-DbaDbList
Show-DbaServerFileSystem
Watch-DbaUpdate

# Maybe no issues

### Availability Groups
Invoke-DbaAgFailover
Join-DbaAvailabilityGroup
Sync-DbaAvailabilityGroup

### Azure or Credentials
New-DbaAzAccessToken

### Certs
Get-DbaNetworkCertificate
Set-DbaNetworkCertificate

### Mirroring
Get-DbaDbMirror
Get-DbaDbMirrorMonitor
Invoke-DbaDbMirrorFailover

### Replication
Get-DbaRepPublication
Get-DbaRepServer
Test-DbaRepLatency

### Log shipping
Invoke-DbaDbLogShipRecovery

```
#junky script to get this info
function noint {
foreach ($file in (Get-ChildItem .\tests\*.Tests.ps1)
) { if (-not (Select-String -Pattern 'IntegrationTests' -Path $file )) { $file }}
}
noint | measure-object
```

**Comment by potatoqualitee** [comment]
heyy i did `Copy-DbaEndpoint`! (hello livestream!)

**Comment by gbargsley** [comment]
https://www.twitch.tv/videos/419722877

**Comment by potatoqualitee** [comment]
good point bot
