### ISSUE TITLE
Getting a false positive result from running "Get-DbaLastBackup"

### ISSUE THREAD

**Issue by bmwluk2012** [sqlcollaborative/dbatools#5472]
getting a false positive result from running "Get-DbaLastBackup", one of the result among the results of other SQL servers did not reflect the latest date on all the backup (i.e. full/diff/log); however, the SQL Server is using different collation (French_CI_AS) than other.  Anyone know this will causing the problem.
Indeed, I have upgraded to version 0.9.821 and run "Get-DbaLastBackup", but problem persisted, just wonder if there would any work around on this, please shed me a light.  Also, I have just tried to run a full backup on this DB and rerun "Get-DbaLastBackup", but it still reports the false result.

**Comment by bmwluk2012** [comment]
And following is the logging shows in the console when I run the command on this server only:

PS C:\Windows\system32> Get-DbaLastBackup -SqlInstance frilm-iv-ilmsql -Database FISCALITE_SWI | Out-Gridview
WARNING: [15:36:26][Get-DbaBackupHistory] Found backups from multiple recovery forks for FISCALITE_SWI on frilm-iv-ilmsql, this may affect your results
WARNING: [15:36:26][Get-DbaBackupHistory] Between 09/08/2015 19:00:00/1836000001271600038 and 09/10/2015 18:00:01/1931000000037500047  was on Recovery Fork GUID 
454b9d4d-4f56-42c2-988f-495795e991a1 (51 backups)
WARNING: [15:36:26][Get-DbaBackupHistory] Between 05/13/2015 18:29:54/1661000000349000038 and 09/06/2015 09:04:16/1836000001335900038  was on Recovery Fork GUID 
c8e50492-a579-4bc9-9b0b-699d9af41878 (2010 backups)
WARNING: [15:36:26][Get-DbaBackupHistory] Between 03/22/2019 00:00:00/6543000000026900038 and 05/03/2019 00:35:45/6693000000032700037  was on Recovery Fork GUID 
f27fe49d-464b-47bc-9ab6-cf02c39ce507 (1058 backups)
WARNING: [15:36:26][Get-DbaBackupHistory] Between 03/09/2015 18:20:57/743000000007300037 and 05/13/2015 17:47:29/1661000000349000038  was on Recovery Fork GUID b
f17c48c-82ff-4767-8248-91cff6d461fc (713 backups)
WARNING: [15:36:26][Get-DbaBackupHistory] Between 09/06/2015 10:00:00/1836000001271600038 and 09/08/2015 18:14:05/1836000001271600038  was on Recovery Fork GUID 
6e27de4d-7b8b-4423-880f-bd7047aa2948 (28 backups)
WARNING: [15:36:26][Get-DbaBackupHistory] Between 08/01/2018 04:00:00/6076000000019600038 and 03/21/2019 23:00:00/6744000000443100121  was on Recovery Fork GUID 
039d1538-80db-49b5-8ee2-dcacec6e9102 (5838 backups)
WARNING: [15:36:26][Get-DbaBackupHistory] Between 09/10/2015 19:00:01/1836000001271600038 and 08/01/2018 03:27:48/6239000000019500038  was on Recovery Fork GUID 
9b1a2c9a-901a-4742-ae98-f6f16c678d9d (26472 backups)
WARNING: [15:36:27][Get-DbaBackupHistory] Found backups from multiple recovery forks for FISCALITE_SWI on frilm-iv-ilmsql, this may affect your results
WARNING: [15:36:27][Get-DbaBackupHistory] Between 09/08/2015 19:00:00/1836000001271600038 and 09/10/2015 18:00:01/1931000000037500047  was on Recovery Fork GUID 
454b9d4d-4f56-42c2-988f-495795e991a1 (51 backups)
WARNING: [15:36:27][Get-DbaBackupHistory] Between 05/13/2015 18:29:54/1661000000349000038 and 09/06/2015 09:04:16/1836000001335900038  was on Recovery Fork GUID 
c8e50492-a579-4bc9-9b0b-699d9af41878 (2010 backups)
WARNING: [15:36:27][Get-DbaBackupHistory] Between 03/22/2019 00:00:00/6543000000026900038 and 05/03/2019 00:35:45/6693000000032700037  was on Recovery Fork GUID 
f27fe49d-464b-47bc-9ab6-cf02c39ce507 (1058 backups)
WARNING: [15:36:27][Get-DbaBackupHistory] Between 03/09/2015 18:20:57/743000000007300037 and 05/13/2015 17:47:29/1661000000349000038  was on Recovery Fork GUID b
f17c48c-82ff-4767-8248-91cff6d461fc (713 backups)
WARNING: [15:36:27][Get-DbaBackupHistory] Between 09/06/2015 10:00:00/1836000001271600038 and 09/08/2015 18:14:05/1836000001271600038  was on Recovery Fork GUID 
6e27de4d-7b8b-4423-880f-bd7047aa2948 (28 backups)
WARNING: [15:36:27][Get-DbaBackupHistory] Between 08/01/2018 04:00:00/6076000000019600038 and 03/21/2019 23:00:00/6744000000443100121  was on Recovery Fork GUID 
039d1538-80db-49b5-8ee2-dcacec6e9102 (5838 backups)
WARNING: [15:36:27][Get-DbaBackupHistory] Between 09/10/2015 19:00:01/1836000001271600038 and 08/01/2018 03:27:48/6239000000019500038  was on Recovery Fork GUID 
9b1a2c9a-901a-4742-ae98-f6f16c678d9d (26472 backups)
WARNING: [15:36:28][Get-DbaBackupHistory] Found backups from multiple recovery forks for FISCALITE_SWI on frilm-iv-ilmsql, this may affect your results
WARNING: [15:36:28][Get-DbaBackupHistory] Between 09/08/2015 19:00:00/1836000001271600038 and 09/10/2015 18:00:01/1931000000037500047  was on Recovery Fork GUID 
454b9d4d-4f56-42c2-988f-495795e991a1 (51 backups)
WARNING: [15:36:28][Get-DbaBackupHistory] Between 05/13/2015 18:29:54/1661000000349000038 and 09/06/2015 09:04:16/1836000001335900038  was on Recovery Fork GUID 
c8e50492-a579-4bc9-9b0b-699d9af41878 (2010 backups)
WARNING: [15:36:28][Get-DbaBackupHistory] Between 03/22/2019 00:00:00/6543000000026900038 and 05/03/2019 00:35:45/6693000000032700037  was on Recovery Fork GUID 
f27fe49d-464b-47bc-9ab6-cf02c39ce507 (1058 backups)
WARNING: [15:36:28][Get-DbaBackupHistory] Between 03/09/2015 18:20:57/743000000007300037 and 05/13/2015 17:47:29/1661000000349000038  was on Recovery Fork GUID b
f17c48c-82ff-4767-8248-91cff6d461fc (713 backups)
WARNING: [15:36:28][Get-DbaBackupHistory] Between 09/06/2015 10:00:00/1836000001271600038 and 09/08/2015 18:14:05/1836000001271600038  was on Recovery Fork GUID 
6e27de4d-7b8b-4423-880f-bd7047aa2948 (28 backups)
WARNING: [15:36:28][Get-DbaBackupHistory] Between 08/01/2018 04:00:00/6076000000019600038 and 03/21/2019 23:00:00/6744000000443100121  was on Recovery Fork GUID 
039d1538-80db-49b5-8ee2-dcacec6e9102 (5838 backups)
WARNING: [15:36:28][Get-DbaBackupHistory] Between 09/10/2015 19:00:01/1836000001271600038 and 08/01/2018 03:27:48/6239000000019500038  was on Recovery Fork GUID 
9b1a2c9a-901a-4742-ae98-f6f16c678d9d (26472 backups)

**Comment by wsmelton** [comment]
Please open a new issue and provide the information asked via our issue template.

**Comment by bmwluk2012** [comment]
Thank you Shawn and I have created another issue #5477 and provided the
information per the template requested.

Regards,
Ben
