### ISSUE TITLE
[Bug] Copy-DbaLogin with -SyncOnly tries to grant connect

### ISSUE THREAD

**Issue by AndreasEDA** [sqlcollaborative/dbatools#5473]
Our Audit Log shows fails granted connect.

It seems that the -SyncOnly option attempt to grant connect permissions to my own login (I'm Sysadmin on both nodes) and that fails on audit-event but in the dbatools.log it shows as success. ( Why does it attempt to grant connect that i have already?)

Name                           Value
----                           -----
PSVersion                      5.1.14393.2828
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2828
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### dbatools Module version:
Name    : DbaTools
Path    : C:\Program Files\WindowsPowerShell\Modules\DbaTools\DbaTools.psd1
Version : 0.9.819

### SQL Server: 
Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64)   Jan 10 2019 18:51:38   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) ->

### SQL Audit Error
Audit event: audit_schema_version:1
event_time:2019-05-03 07:09:47.9687891
sequence_number:1
action_id:G   
**succeeded:false**
is_column_permission:false
session_id:51
server_principal_id:272
database_principal_id:1
target_server_principal_id:272
target_database_principal_id:0
object_id:0
user_defined_event_id:0
transaction_id:782311
class_type:SR
session_server_principal_name:BBBBBBB
server_principal_name:BBBBBBBB
database_principal_name:dbo
target_server_principal_name:BBBBBBBB
target_database_principal_name:
server_instance_name:EDAVSI01141
database_name:master
schema_name:
object_name:
statement:**GRANT CONNECT SQL TO BBBBBB**

## Steps to Reproduce

```powershell

Copy-DbaLogin -Source EDAVSI01142 -Destination EDAVSI01141 -SyncOnly

Result in the dbatools.logfile

"**Grant CONNECT SQL to BBBBBBB on EDAVSI01141 successfully performed**.","Verbose, Debug","03.05.2019 09:21:10","Update-SqlPermission","DbaTools","System.Collections.Generic.List`1[System.String]","Verbose","061137b9-3836-449d-a714-77cf277a6bb5","EDAVSI01142",,"C:\Program Files\WindowsPowerShell\Modules\DbaTools\allcommands.ps1","119811","System.Management.Automation.ScriptDebugger+<GetCallStack>d__105","BBBBBBB"

It seems that this is for all loings with Sysadmin!

**Comment by potatoqualitee** [comment]
thanks for the report. it does not check to see if you already have permissions before attempting to apply them. this is the current design and will not be updated by me. I am open to PR's to change the behavior, but right now is considered as designed.

**Comment by AndreasEDA** [comment]
Hi Chrissy

Thank’s, but assigning permissions to yourself  is not allowed per MS Design:

“Cannot grant, deny, or revoke permissions to sa, dbo, entity owner, information_schema, sys, or yourself.”

So the code should first check if the permissions is himself.

Should I still make a PR?

Thank’s

**Comment by potatoqualitee** [comment]
oh certainly, if you are up for submitting the PR, i'm down for it. I'll reopen this issue so you can reference it 👍

**Comment by potatoqualitee** [comment]
fixed in a recent PR - will be released soon.
![image](https://user-images.githubusercontent.com/8278033/57523625-c2299500-7325-11e9-84fe-db530309f293.png)
