### ISSUE TITLE
[Bug] Invoke-DbaQuery doesn't change current database

### ISSUE THREAD

**Issue by asnest** [sqlcollaborative/dbatools#5486]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```
& {"### PowerShell version:`n$($PSVersionTable | Out-String)"; "`n### dbatools Module version:`n$(gmo dbatools -List | select name, path, version | fl -force | Out-String)"}
```

- [X] *Running latest release of dbatools*
- [X] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data

```
### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1




### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.822\dbatools.psd1
Version : 0.9.822

```

### SQL Server: 

```sql
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 17763: ) 
```

## Errors Received

```powershell
<# OUTPUT of $error[0] | select * #>
```

## Steps to Reproduce

```sql
select count(*) from master.sys.objects
105
select count(*) from model.sys.objects
91
```

```powershell
Invoke-DbaQuery -file c:\temp\1.sql   -SqlInstance localhost\tst1 -Database master -ErrorAction Ignore -Verbose | FT
```

file 1.sql:
```
use model
go

select count(*) from sys.objects
go
```

## Expected Behavior

I want to see output = 91, but it looks like function can't change current database

## Actual Behavior
```
VERBOSE: Changed database context to 'model'.

Column1
-------
    105
```

**Comment by sqllensman** [comment]
The problem is that when a script contains GO statements the code splits the script into multiple  batches but then executes each using the original connection parameters. Any change in database context is not preserved between batches.

This seems to be a design decision and may be difficult to alter.

**Comment by sqllensman** [comment]
It is possible to produce desired output by doing something like

$GoSplitterRegex = [regex]'(?smi)^[\s]*GO[\s]*$'

$Query =
@"
use model
go

select count(*) from sys.objects
go
"@

$scriptOutput = New-Object System.Collections.ArrayList
$database = 'master'
$server = Connect-DbaInstance -SqlInstance lensmansb -Database $database
$Pieces = $GoSplitterRegex.Split($Query)
$Pieces = $Pieces | Where-Object { $_.Trim().Length -gt 0 }
foreach ($piece in $Pieces) {
    
    $out= Invoke-DbaQuery -SqlInstance $server -Query $piece -MessagesToOutput
    $scriptOutput.Add($out) | Out-Null
}
$scriptOutput

**Comment by asnest** [comment]
Thank you for your fast response!
If it so, we cannot use this function to restore ```Export-DbaInstance``` results in part of 'login' and 'userobjectsinsysdbs' parts as I saw in some articles like https://dbatools.io/dr/

**Comment by sqllensman** [comment]
The Get-DbaDbSysUserObjectScript is problematic. 
It does not produce a file that could reliably be  used by Invoke-DbaQuery or even SSMS

I am currently trying to rewrite this as part of another raised issue for Export-DbaInstance

**Comment by potatoqualitee** [comment]
Thank you both for your feedback, I will consider this closed with workaround by Patrick

**Comment by potatoqualitee** [comment]
7 hours ago wtf

**Comment by potatoqualitee** [comment]
eventually consistent i guess 😅

**Comment by sqllensman** [comment]
While the behaviour may be as intended, the synopsis for the function states "A command to run explicit T-SQL commands or files"
The synopsis for Invoke-DbaAsync is "Runs a T-SQL script ". 

The document may need to be updated.

**Comment by asnest** [comment]
Thank you all for job you do!
I was misled with some examples.
I will rewrite my scripts with using sqlcmd (by the way, @sqllensman your script from comments works well)

**Comment by niphlod** [comment]
also, not a bug. Not exiting the database boundary is a *feature*
