### ISSUE TITLE
Test-DbaReplicationLatency

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#549]
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/4hjmza3B

**Additional comments**

Needs to be fleshed out or closed.

**Comment by potatoqualitee** [comment]
@sql-williamd you up for this still?

**Comment by sql-williamd** [comment]
@potatoqualitee sorry - totally forgot this. The trello bard is gone..... any idea what the contents of that were?

**Comment by wsmelton** [comment]
@sql-williamd trello card had no specific details. Looks like it was one @js0505 had created though so maybe he has further ideas/thoughts on it.

**Comment by potatoqualitee** [comment]
perhaps https://www.mssqltips.com/sqlservertip/2590/determine-data-latency-between-publisher-and-subscriber-in-sql-server-transactional-replication/ or https://www.mssqltips.com/sqlservertip/3598/troubleshooting-transactional-replication-latency-issues-in-sql-server/ too
