### ISSUE TITLE
[Bug] Read-DbaXEventFile dll loading

### ISSUE THREAD

**Issue by MHafiez** [sqlcollaborative/dbatools#5498]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```
& {"### PowerShell version:`n$($PSVersionTable | Out-String)"; "`n### dbatools Module version:`n$(gmo dbatools -List | select name, path, version | fl -force | Out-String)"}
```

- [x] *Running latest release of dbatools*
- [ ] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data

Name                           Value                                                                                                                                                                    
----                           -----                                                                                                                                                                    
PSVersion                      5.1.17134.590                                                                                                                                                            
PSEdition                      Desktop                                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                  
BuildVersion                   10.0.17134.590                                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                                      
SerializationVersion           1.1.0.1                                                                                                                                                                  

### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.823\dbatools.psd1
Version : 0.9.823

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.822\dbatools.psd1
Version : 0.9.822

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.821\dbatools.psd1
Version : 0.9.821

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.801\dbatools.psd1
Version : 0.9.801

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.793\dbatools.psd1
Version : 0.9.793

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.779\dbatools.psd1
Version : 0.9.779

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.775\dbatools.psd1
Version : 0.9.775

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.753\dbatools.psd1
Version : 0.9.753

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.752\dbatools.psd1
Version : 0.9.752

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.751\dbatools.psd1
Version : 0.9.751

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.737\dbatools.psd1
Version : 0.9.737

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.734\dbatools.psd1
Version : 0.9.734

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.724\dbatools.psd1
Version : 0.9.724

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.493\dbatools.psd1
Version : 0.9.493

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.491\dbatools.psd1
Version : 0.9.491

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.411\dbatools.psd1
Version : 0.9.411

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.385\dbatools.psd1
Version : 0.9.385

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.370\dbatools.psd1
Version : 0.9.370

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.333\dbatools.psd1
Version : 0.9.333

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.325\dbatools.psd1
Version : 0.9.325

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.207\dbatools.psd1
Version : 0.9.207
```
<# REPLACE WITH output OF environment one-liner #>
```

### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

## Errors Received

```powershell
<# OUTPUT of $error[0] | select * #>
```
PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
                           at CallSite.Target(Closure , CallSite , Object )
                           at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Read-DbaXEFile<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.823\allcommands.ps1: line 79497
                        at <ScriptBlock>, C:\Users\mhafiez\Desktop\Final_Local_1_24_2018\Final_Local\Trace\Export_Session_CSV_WAIT_15_mins_Export_Excel_finaWorkingl.ps1: line 18
                        at <ScriptBlock>, C:\Users\mhafiez\Desktop\Final_Local_1_24_2018\Final_Local\Trace\Export_Session_CSV_WAIT_15_mins_Export_Excel_finaWorkingl.ps1: line 17
PipelineIterationInfo : {}
## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
    Provide exact (or sanitized) code to reproduce the error
#>
```
Read-DbaXEventFile -Path $path
## Expected Behavior

New-Object : Exception calling ".ctor" with "1" argument(s): "Could not load file or assembly 'Microsoft.SqlServer.XE.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one 
of its dependencies. The system cannot find the file specified."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.823\allcommands.ps1:79468 char:21
+ ...     $enum = New-Object Microsoft.SqlServer.XEvent.Linq.QueryableXEven ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.823\allcommands.ps1:79497 char:13
+             $enum.Dispose()
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by MHafiez** [comment]
Thanks Chrissy, it worked.

**Comment by potatoqualitee** [comment]
awesome! at first i expected it would then it didnt then i almost gave up on it, then filed a bug report with microsoft. hopefully it'll work across all platforms once they respond, because i did get it to fail on one of mine 😬
