### ISSUE TITLE
Get-SQLAgentJobOutputFile

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#551]
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/RJG7zLip

**Additional comments**
https://github.com/SQLDBAWithABeard/Functions/blob/master/Get-SQLAgentJobOutPutFile.ps1

**Comment by niphlod** [comment]
we have it. Get-DbaAgentJobOutputFile
