### ISSUE TITLE
Standardize use of BatchSeparator in functions

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#5514]
### Summary of issue
There are a number of commands within dbatools that take a Parameter of BatchSeparator or equivalent. These are not handled in a consistent manner across these commands.

The various functions and there interpretation of BatchSeparator are

### Connect-DbaInstance:
Parameter: BatchSeparator
Description: A string to separate groups of SQL statements being executed. By default, this is "GO".
Default Value: Inherits the default value of GO

### Export-DbaDbTableData
Parameter: BatchSeparator
Description: Specifies the Batch Separator to use. Default is None
Default Value: ''

### Export-DbaInstance 
Parameter: BatchSeparator
Description: Batch separator for scripting output. "GO" by default.
Default Value: 'GO'

### Export-DbaLogin
Parameter: ExcludeGoBatchSeparator
Description: If specified, will NOT script the 'GO' batch separator.
Default Value: 'GO' 

### Export-DbaScript
Parameter: BatchSeparator
Description: Specifies the Batch Separator to use. Default is None
Default Value: ''

### Export-DbaUser
Parameter: ExcludeGoBatchSeparator
Description: Specifies the Batch Separator to use. Default is None
Default Value: 'GO' 

### New-DbaConnectionString
Parameter: BatchSeparator
Description: By default, this is "GO"
Default Value: Inherits the default value of GO

### Get-DbaSysDbUserObjectScript 
Internal function that explicitly adds "GO" as BatchSeparator

### Invoke-DbaAsync
Internal function used by Invoke-DbaQuery that explicitly uses GO as BatchSeparator

Finally a number of functions 

Export-DbaDbTableData
Export-DbaInstance
Export-DbaScript
Export-DbaUser

all accept a Microsoft.SqlServer.Management.Smo.ScriptingOptions object which includes the ScriptBatchTerminator property

Ideally there should be a consistent approach to how a BatchSeparator is set and handled

**Comment by potatoqualitee** [comment]
hell yes, please. default to GO. we should probably include an extrra example when we change copy-dbadbtabledata. Anyone who works on this, please PR to prerelease since it's breaking changes.

**Comment by wsmelton** [comment]
Be aware that you will have an issue with context switching using the `GO` separator in scripts that are executed with Invoke-DbaQuery...it is a known "by design" situation. So caveat might be good to include, or make this standardized via a configuration option so users can opt-in to have `GO` defaulted on all export functions.

**Comment by sqllensman** [comment]
I was planning to update descriptions in Invoke-DbaQuery to clearly document the behaviour. The current descriptions do not clearly spell this out as per issue #5486

**Comment by sqllensman** [comment]
Will standize by adding a configuration 'Formatting.BatchSeparator' in the formating.ps1 file with a default value of GO

**Comment by potatoqualitee** [comment]
ohh i love!

**Comment by wsmelton** [comment]
Ref: https://docs.microsoft.com/en-us/dotnet/api/managedbatchparser

**Comment by andreasjordan** [comment]
I think that is implemented, so I will close.
