### ISSUE TITLE
Find-DbaLongRunningQuery

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#552]
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/kK7JNqMG

**Additional comments**
@wsmelton 
"Purpose would not be to find blocking tree or anything...that you can get by calling sp_whoisactive with the right parameters. This would just be pulling session duration since start and outputting if any are over particular threshold, or just return all. More or less what you can get from whoisactive, maybe just in format to do quick checks or something."

**Comment by potatoqualitee** [comment]
Created as Get-DbaQueryExecutionTime

I think I'd actually like to add an alias for this Find-DbaLongRunningQuery. Maybe.... prolly not 🤔
