### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bret-miller** [sqlcollaborative/dbatools#5525]
## Environmental data

```
### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1




### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.821\dbatools.psd1
Version : 0.9.821
```

### SQL Server: 

```sql
Microsoft SQL Server 2008 (SP4-GDR) (KB4057114) - 10.0.6556.0 (X64)   Dec 28 2017 15:21:01   Copyright (c) 1988-2008 Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) ```

<!-- NOTE: If the above information is not provided as a minimum your issue will not be acknowledged -->

## Errors Received

<!-- Provide full output of `$error[0] | Select *` -->

```powershell
<# OUTPUT of $error[0] | select * #>
```
Update-SqlDbOwner : The term 'Update-SqlDbOwner' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Update-SqlDbOwner -Source SQL1 -Destination SQL2008 -Force
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Update-SqlDbOwner:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
#>
```
Start-DbaMigration -Source xxxx -Destination yyyy

## Expected Behavior

Expect it to work.

## Actual Behavior

Start-DbaMigration uses a function "Update-SqlDbOwner" that apparently no longer exists.

**Comment by potatoqualitee** [comment]
hey bret, can you update your dbatools, reimport and try again? the function exists still in internal. if you continue to have issues, please let me knwo and i'll reopen.

**Comment by bret-miller** [comment]
I did "Update-Module dbatools". It says, "Updated using the PowerShell Gallery".  Sure enough, I have a 0.9.826 now in addition to the 0.9.821. Neither has a function "Update-SqlDbOwner" in it.

There is a “Set-DbaDatabaseOwner” but that only applies to a single database, not copying ownership on all databases from one instance to another.

Bret Miller
GCI Tech Support
980-495-3979
[GCI_Landscape_Blue_RGB_for_signature]

**Comment by potatoqualitee** [comment]
It is an internal command that you do not see in the exported commands. Please restart your PowerShell session to import the latest version, then confirm using Get-Module dbatools.
