### ISSUE TITLE
[Bug] install-dbainstance

### ISSUE THREAD

**Issue by red8rain** [sqlcollaborative/dbatools#5526]
when executing on PS4.0, it is throwing the following error:

WARNING: [12:27:47][Invoke-DbaAdvancedInstall] Failed to copy file C:\Users\prof\AppData\Local\Temp\Configuration_*_2017.ini to C:\Users\prof\AppData\Local\Temp\Configuration_*_2017.ini on servername.fqdn
, exiting | A parameter cannot be found that matches parameter name 'ToSession'.

Also has a problem restarting the server when using the -restart switch on PS4.0.

**Comment by niphlod** [comment]
right, -tosession is not available on 4.0

**Comment by red8rain** [comment]
right.  spoke to @nvarscar on slacker and he asked me to post this as a bug since dbatools support posh 3.0+

**Comment by nvarscar** [comment]
Thanks stale bot, I'll try to finally remember to fix it.

**Comment by RikRikky** [comment]
I am using PS4.0 and having the same issue with Install-dbainstance command of DBATOOLS. did anybody find a solution?

**Comment by niphlod** [comment]
@nvarscar : I think I slipped you a piece of code back then to make sure copying works even in PS3. if you need it I can pass it to you again.

**Comment by RikRikky** [comment]
This issue doesn't occur with PS 5.0 or above ?

**Comment by niphlod** [comment]
yep, at least when originally posted the function used something PS 4 hasn't, it came only with 5.0

**Comment by RikRikky** [comment]
Did anybody successfully use Install-Dbainstance command ? even with PS 5.1 i am seeing other issues like the PS is hung at "generating configuration file", doesn't proceed further at all.

**Comment by andreasjordan** [comment]
I've used it. What does the -Verbose output say?

**Comment by RikRikky** [comment]
Not seeing any switch called Verbose in install-dbainstance.

**Comment by andreasjordan** [comment]
That's a general switch you can use with every command (powershell wide, not dbatools specific).

**Comment by RikRikky** [comment]
Got stuck once at verifying access.after ps restart, Next time got stuck at copying ini file from local to remote server. Verbose says "writing ini file to....." and prompted me for confirmation but not allowing me to click on yes as it is already in hung state

**Comment by andreasjordan** [comment]
If you don't want the confirmation, you can add `-Confirm:$false`. If you send the exact output, I can find the position in the code...

**Comment by RikRikky** [comment]
After a millionth try, finally installation is happening. Not sure why everytime the PS hangs at different stages?

**Comment by RikRikky** [comment]
When inputs for 'feature' are taken from user and concatenated with a comma separtor and passed to install-dbainstance, it throws error : cannot validate argument on parameter 'feature'. The argument "engine,replication,fulltext" does not belong to the set "default All,engine,tools,replication......" specified by the validateset attribute. Supply an argument that is in the set and try the command again. Any idea how to resolve this issue?

**Comment by RikRikky** [comment]
Some issue bcos of the double quotes which i just cant figure out.

**Comment by RikRikky** [comment]
Can anybody say why install-dbainstance command hangs everytime in various stages like sometime in "verifying access to setup file" , sometimes in writing to config file etc etc. After a millionth restart of powershell window, may be i m able to complete the installation.

**Comment by nvarscar** [comment]
@niphlod it would be great if you did that again, I can't find it anywhere.
@RikRikky perhaps, there's an antivirus that prevents certain activities? This kind of behavior (if you're not talking about waiting for confirmation) was not reported anywhere else as far as I'm aware and antivirus is the only thing that comes to my mind.

**Comment by RikRikky** [comment]
In install-dbainstance, instancepath parameter doesnt accept just the drive letter like D: or D:\ ? It throws error "illegal characters in the path"

**Comment by RikRikky** [comment]
How to provide multiple directories for multiple tempdb files in the configuration parameter ? Like D:\temp1, D:\temp2, D:\temp3, D:\temp4

**Comment by nvarscar** [comment]
> In install-dbainstance, instancepath parameter doesnt accept just the drive letter like D: or D:\ ? It throws error "illegal characters in the path"

This command passes that value to the installer as is. If the installer wouldn't work with it - there's nothing we can do about it.

> How to provide multiple directories for multiple tempdb files in the configuration parameter ? Like D:\temp1, D:\temp2, D:\temp3, D:\temp4

Based on [this doc](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver15), you need to provide directories separated by a blank space. Let me know how that goes, I'm curious. Quote:

> Specifies the directories for tempdb data files. When specifying more than one directory, separate the directories with a blank space. If multiple directories are specified the tempdb data files will be spread across the directories in a round-robin fashion.
