### ISSUE TITLE
Get-DbaAvailabilityDatabase

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#553]
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/bRmfN0Kj

**Additional comments**

Pull out information about databases in an Availability Group. Most of what is under SMO object https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.availabilitydatabase.aspx

* List of databases in AG
* Sync status
 * Utilize T-SQL to possibly grab things around latency info (similar to what dashboard might provide)

https://files.slack.com/files-pri/T1LTZ0BQV-F2K3U6W3Y/ag_dash.sql

**Comment by wsmelton** [comment]
Fixed in #1770
