### ISSUE TITLE
[Bug] Copy-DbaLogin fails with NullReferenceException when calling the internal function Copy-Login

### ISSUE THREAD

**Issue by JonasNjopOlsson** [sqlcollaborative/dbatools#5536]
- [x] *Running latest release of dbatools*
- [x] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

### Windows version:
Windows Server 2012 Datacenter

### PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.22199
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```
### dbatools Module version:
```
Name    : dbatools
Path    : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\dbatools.psd1
Version : 0.9.828
```
### SQL Server: 
```sql
Microsoft SQL Server 2012 (SP4-GDR) (KB4057116) - 11.0.7462.6 (X64) 
	Jan  5 2018 22:11:56 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)
```
## Errors Received
```powershell
Copy-DbaLogin -Verbose -Source 'SERVER1\INSTANCE1' -Destination 'SERVER2\INSTANCE1'
#####################
VERBOSE: [10:53:36][Copy-DbaLogin] Attempting Login Migration.
Object reference not set to an instance of an object.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\allcommands.ps1:12034 char:13
+             Copy-Login -sourceserver $sourceServer -destserver $destServer -Logi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException
#####################
$error[0] | Select *
#####################
PSMessageDetails      :
Exception             : System.NullReferenceException: Object reference not set to an instance of an object.
                           at System.Management.Automation.PipelineOps.CheckAutomationNullInCommandArgumentArray(Object[] objArray)
                           at System.Management.Automation.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : OperationStopped: (:) [], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Copy-DbaLogin<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\allcommands.ps1: line 12
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
#####################
```
## Steps to Reproduce
Run the following command to sync SQL logins from the first server to the second:

```powershell
Copy-DbaLogin -Verbose -Source 'SERVER1\INSTANCE1' -Destination 'SERVER2\INSTANCE1'
```

## Expected Behavior
The logins should be copied from the source instance to the target instance.

## Actual Behavior
A null reference exception is produced and no logins are copied.

## Workaround
Inside the **dbatools** module directory, edit the file **allcommands.ps1** and comment part of the line calling **Copy-Login** from within the **Copy-DbaLogin** function:

```powershell
# Commented part of line starting at "-Login"
Copy-Login -sourceserver $sourceServer -destserver $destServer # -Login $Login -Exclude $ExcludeLogin
```

**Comment by potatoqualitee** [comment]
Hey Jonas,
You gave a wonderful amount of information, thank you. Unfortunately, I am unable to reproduce this on any machine. Can you please update to the latest version, and run from powershell.exe, let me know if you continue to have issues? This seems like an issue with the host.

**Comment by potatoqualitee** [comment]
dbatools.io/clean can help you clean out all old versions

**Comment by wsmelton** [comment]
I would also recommend updating to newer version of PowerShell. I see your info shows Windows 8.1/2008 R2 which should support PS 5.1 if you are on latest SP.

**Comment by JonasNjopOlsson** [comment]
Thank you for the feedback. This seemed a rather odd behaviour to me as well so I am half expecting this to be some sort of bug related to the PowerShell version in use on these servers.

I will look into upgrading to both the latest version of dbatools and, if the problem persists, perhaps to a later version of PowerShell on the servers in question. They are production servers however so I will have to a bit careful about it.

I will report back in this issue when I have any updates.

**Comment by potatoqualitee** [comment]
thank much, please reopen or comment if you continue to encounter issues 👍
