### ISSUE TITLE
Can dbatools be installed on Server 2008 Standard?

### ISSUE THREAD

**Issue by RT1960** [sqlcollaborative/dbatools#5540]
I want to move SQL logins from SQL installed on a Server 2008 Standard box.  I want to install dbatools, but the prerequisites include WMF 5.1 and I can't find any way to install that on a 2008 server.

Can dbatools be install on Server 2008 Standard?

**Comment by potatoqualitee** [comment]
Thank you for your question! Nice timing, I just finished writing about this for dbatools in a month of lunches 👍 

Surprisingly, no. It does not work in 2008, but does work with 2008 R2. Here's a complete list for those interested.

![image](https://user-images.githubusercontent.com/8278033/57862865-58aff780-77f9-11e9-8aad-9ab77d7a1cb4.png)

Don't forget that dbatools can be installed on one machine and then manage other servers, like SQL Server Management Studio. For me, I have a centralized management server and do everything from there.

**Comment by RT1960** [comment]
Are there instructions on how this can be done?

**Comment by potatoqualitee** [comment]
It is the same syntax for local or remote. `Get-Help Copy-DbaLogin -Examples` should help.

**Comment by RT1960** [comment]
Thanks for the prompt replies!  I'll take a quick look and see how things go.

**Comment by RT1960** [comment]
Unfortunately I'm still somewhat confused about some of the syntax.  Please pardon my ignorance on this subject, I've been tasked with migrating this server as it is failing, and our dB admin left last month...and although I am an experienced server admin I am NOT a SQL admin. Ouch!
Here's my scenario:  sql01.domain.com is the old server, and newsql01.domain.com is the new.  The problem is, the HELP I ran doesn't say what to do prior to running the copy command.  
Syntax says:
Copy-DbaLogin -Source sql01 -Destination newsql01 -Login User1 -Force

How does dbatools connect to the dB on the old server (sql01)?  Do I connect to the old server dB in the Mgt Studio on the new server first?  I tried running it as is above (with correct names) and it failed.

Thanks in advance for any assistance!

**Comment by garethnewman** [comment]
Hey @RT1960 you want to find your way over to the dbatools slack over on sql server community?

It uses the powershell session (your windows login) by default, if you check the help

Get-Help Copy-DbaLogin -Full

Then you can see all the extra flags and examples.

**Comment by garethnewman** [comment]
https://dbatools.io/slack/

**Comment by wsmelton** [comment]
You can find the docs for that command online at docs.dbatools.io/#Copy-DbaLogin

You will want to use the credential parameters noted in the help if the login running the command cannot connect to both instances.

**Comment by wsmelton** [comment]
If you are getting errors you can post them here as well.

**Comment by RT1960** [comment]
I actually joined Slack, and when I clicked to submit an issue on dbatools it brought me here.  Oh well...:)

I attached to the old dB on the new server, and ran the copy command.  It did bring the user over, but the user mappings did not quite match.  But I'm thinking I need to move the databases first so that the user mappings are maintained, which I have not done yet.  Is this correct?

**Comment by wsmelton** [comment]
Yes, the copy commands have a precedence as they do not handle dependencies. 

You can actually look at `Start-DbaMigration` to get an idea but in your case the databases need to come before the logins. Once you have the databases copied over you can simply run the copy command for the logins again and use `-Force` and it will just drop/create the logins on your destination server.

**Comment by RT1960** [comment]
Hello all,

Well, the move was uneventful, at least it appeared to be.  Once copied over, I compared the users on the old server the users on the new, and they had the same user mappings to the databases, and the properties all appeared to be identical.  Unfortunately when we switched over we started receiving errors from one of the most critical logins related to our website. 

It’s hard to describe, but it from what I was seeing the account did not feel like it was associated with the new server. It was still trying to pull/update settings from the old server (even though we named the new server the same name and used the same IP), and it couldn't find the server it was attempting to contact. When I tried to change settings on the account on the new server, it would error out and say that it could not find the user; even though I was selecting the properties of the user on the new server. Basically, the account didn’t act like it was part of the new server.  I eventually took down the new server and put the old one back into production for now.  

So something didn't copy over when I moved the users, somehow.

**Comment by potatoqualitee** [comment]
If you'd like to do the login move yourself, you can use the classic Microsoft way, but I imagine you'll continue to have the same problem. What you describe does not jive with what I understand about SQL Server logins but anything is possible.

https://support.microsoft.com/en-us/help/918992/how-to-transfer-logins-and-passwords-between-instances-of-sql-server
