### ISSUE TITLE
Copy-DbaStartupProcedure

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#555]
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/HQi8bYXI

**Additional comments**
$server.EnumStartupProcedures()

**Comment by mikepetrak** [comment]
Hi @SirCaptainMitch , I clicked on the Trello link but got the following:

"Card not found.
This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams."

Thanks,
Mike
