### ISSUE TITLE
Export-DbaInstance logic error for Resource Governor script

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#5552]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```

Name                           Value
----                           -----
PSVersion                      5.1.14393.2879
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2879
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1




### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.804\dbatools.psd1
Version : 0.9.804

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.791\dbatools.psd1
Version : 0.9.791
```

- [ ] *Running latest release of dbatools*
- [ ] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data

```
<# REPLACE WITH output OF environment one-liner #>
```

### SQL Server: 

```Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64)   Jan 10 2019 18:51:38   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
/* REPLACE WITH output of @@VERSION */
```

## Steps to Reproduce

```Export-DbaInstance -SqlInstance $SqlServer -Path $DailyOutputPath ```

## Actual Behavior

It appears the output logic for Resource Governor is creating two files with different numbers.  See screen shot.
![image](https://user-images.githubusercontent.com/169602/57932152-dae2ff00-787f-11e9-9bec-d27ebe49a6a9.png)

**Comment by sqllensman** [comment]
The cause of this error is the code at Line 371

$null = Add-Content -Value "ALTER RESOURCE GOVERNOR RECONFIGURE" -Path "$Path\$stepCounter-resourcegov.sql"

This should be 
$null = Add-Content -Value "ALTER RESOURCE GOVERNOR RECONFIGURE" -Path "$Path\$fileCounter-resourcegov.sql"

The numbering of file is determined by $fileCounter and not $stepCounter.
