### ISSUE TITLE
Write-DbaDataTable - Add ability to manually set SQL data types when using -AutoCreateTable

### ISSUE THREAD

**Issue by ms-217** [sqlcollaborative/dbatools#5557]
### Summary of new feature

I need to be able to control data types and sizes used to store data for compatibility. I can currently do this by manually setting them when the table is created. However, I change columns often and manually dropping the table and redefining all the data types is very tedious and error prone. 

I want to be able to specify which columns will have which SQL data type when using the -AutoCreateTable option, as well as the size of the data type if applicable.

### Latest version of dbatools as of writing

v 0.9.829

**Comment by potatoqualitee** [comment]
can you propose how you'd see this implemented? like a hashtable?

i think we'll end up adding a new command Add-DbaDbTable that accepts a hashtable. would that be acceptable?

**Comment by ms-217** [comment]
Having an Add-DbaDbTable command with a hash table for data types would work. That would allow me to  automate the column creation process.

**Comment by potatoqualitee** [comment]
excellent, thanks for the feedback. please comment on this issue if you'd like to follow it: https://github.com/sqlcollaborative/dbatools/issues/5272
