### ISSUE TITLE
$server.Query() is lost when psm1 is loaded

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5562]
$server.Query() works when .psd1 is loaded, but breaks when .psm1 is loaded. Our developers, including myself, use psm1 to easily work with functions that have not been added to the psd1. We also use it to work with/test new internal functions.

Working development Branch

![image](https://user-images.githubusercontent.com/8278033/58013620-4551a480-7af7-11e9-8f36-78fbf23aa3dd.png)

Non-working pre-release branch

![image](https://user-images.githubusercontent.com/8278033/58013679-6b774480-7af7-11e9-9700-7b00df514361.png)

**Comment by wsmelton** [comment]
This should be working, just tested it myself @potatoqualitee 

![image](https://user-images.githubusercontent.com/11204251/58136950-ad86b000-7bf5-11e9-812f-92dd613f5842.png)

**Comment by potatoqualitee** [comment]
thanks for testing. it works a vast majority of the time but failed for me when i was deep into reloading like 800 times. i didnt copy down the error tho :/

**Comment by potatoqualitee** [comment]
excellent, tres bien baw yall 🏆
