### ISSUE TITLE
don't make ppl specify db twice

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5566]
connect... write... see how to get it down to one

**Comment by potatoqualitee** [comment]
shawn said you can just pass to write, which i forgot but there are other scenarios that require connect first 🤔  i remember exploring this then deciding against it. wish i'da documented why

**Comment by wsmelton** [comment]
What scenario would require a connect first?

Piping support it will vary whether we can formally support it or not because the input object won't have the server object included.

**Comment by potatoqualitee** [comment]
man im trynna remember. maybe that's not the case?

**Comment by wsmelton** [comment]
Azure SQL has issues around it for database context but once we get the auth stuff figured out that problem should go away 🤞

**Comment by potatoqualitee** [comment]
Maybe GetDatabaseConnection() can help!

**Comment by andreasjordan** [comment]
@potatoqualitee - What is the issue here? Maybe solved with the new Connect-DbaInstance?

**Comment by potatoqualitee** [comment]
@andreasjordan - seems we had to `Connect-DbaInstance` to `Write-DbaDataTable`, will have to check if that is still true

**Comment by potatoqualitee** [comment]
Figured it out, it's better documented here, closing this one but addressing the issue: https://github.com/sqlcollaborative/dbatools/issues/7587
