### ISSUE TITLE
Internal Function - Get-DbUser

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#557]
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/ELCyJUJe

**Additional comments**
-Database: filter by database, if user does not exist in the database output as such. Allows array of names to be passed in.
-Login: validates that login exist, if not output as such. Returns list of things like "database", "MappedUser" (this could be different from login so should return either the user).
-Roles: could allow for passing in role name and then just output true/false, or use as a switch to only output role membership.
-Permissions: [Switch] returns permissions the user has in database(s)
-Detailed: Not sure if this is required but say the Permissions is provided and this parameter as well, then output role membership, explicit permissions that are granted as well.

"Also look at options of outputting as standard table that would allow easy use for comparing. Like

$account1 = Get-SqlUser -ServerInstance MyServer -Login "BillyBob"
$account2 = Get-SqlUser -ServerInstance MyServer -Login "BillieJean"

Compare-Objects $account1 $account2"

**Comment by potatoqualitee** [comment]
@ClaudioESSilva or @PowerDBAKlaas  is this something you'd be interested in?
