### ISSUE TITLE
Internal Function - Test-DbaSqlVersion

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#558]
Is this a *feature* OR *bug*:
Enhancement 
https://trello.com/c/2BCzGtwM

**Additional comments**
Should test for supported/non supported SQL Server versions (ie. "SQL 2005 is no longer supported").

**Comment by niphlod** [comment]
we have -minimum on connect-sqlinstance . is this still needed ? 
@potatoqualitee , @SirCaptainMitch , I leave this up to you but IMHO we can close this

**Comment by potatoqualitee** [comment]
done!
