### ISSUE TITLE
Internal Function - Get-DbaDatabaseFileInfo 

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#559]
Is this a *feature* OR *bug*:
Enhancements 

https://trello.com/c/hO2MAufo

**Additional comments**
Internal function to get database file information. This is necessary from a performance standpoint, as enumerating the SMO database file collection is inefficient because every enumeration will query against all databases on the server. This will be more targeted.

Get-DbaDatabaseFileInfo
-[object]SqlServer (smo object) [set 1]
-[string[]]DatabaseName [set 1]
-[object[]]Database (SMO object, pipeline) [set 2]

Output: DBname
FileName
PhysicalName
Type
FileGroupName
SizeMB
UsedSpaceMB
MaxSize
Growth
IsPercent

**Comment by niphlod** [comment]
we have the beautiful Get-DbaDatabaseFile now. Closing
