### ISSUE TITLE
Implement usp_ssiscatalog as a command similar to WhoIsActive

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#560]
Is this a *feature* OR *bug*:
Enhancement 

https://trello.com/c/gKznAWF0

**Additional comments**

https://ssisreportingpack.codeplex.com/wikipage?title=usp_ssiscatalog

the author appears to have invested a lot of time in the help, we should keep this in mind and ensure this information can also be passed on to the user.

**Comment by potatoqualitee** [comment]
@BartekR - you interested in this at all?

**Comment by BartekR** [comment]
Definitely! I recently started investigating https://github.com/sqlcollaborative/dbareports/issues/52 so I can work both at the same time. I would gladly work on that.

**Comment by potatoqualitee** [comment]
excellent! thanks so much. Also, added you to dbatools.io/team, thanks so much for joining us, man. So happy to have you on board!

**Comment by wsmelton** [comment]
Because the codeplex project site has been archived adding the code to that stored procedure here before it is lost:

[usp_ssiscatalog.sql.txt](https://github.com/sqlcollaborative/dbatools/files/2301234/usp_ssiscatalog.sql.txt)

**Comment by wsmelton** [comment]
Looking over the source code for the referenced project and this is out of scope to just make one command like whoisactive for SSIS. There is metadata in SSIS now that I think this project was trying to cover. It has a number of dependent objects (tables, functions, procs) that would have to be deployed out to a given system and in some cases it would duplicate names that SSISDB already have (I think).

I'm going to just close this one and we can visit all the SSISDB stuff later in a different way...think the schema that SSISDB has the data this is trying to show.
