### ISSUE TITLE
Set-DbatoolsConf question

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5601]
hello fred,
any possibility you can change Set-DbatoolsConfig?

I'd like to make it persist by default. Would it be possible to rename set-dbatoolsconfig to set-dbatoolsconfig2 and i write a PS wrapper as Set-DbatoolsConfig? would it slow down things too bad? I'd like to change the behavior.

I'd prefer instead of:
Set-DbatoolsConfig -Name Import.SqlpsCheck -Value $false -PassThru | Register-DbatoolsConfig

that it would be 
Set-DbatoolsConfig -Name Import.SqlpsCheck -Value $false
which would passthru to register automatically.

And if I want it temp, then 

Set-DbatoolsConfig -Name Import.SqlpsCheck -Value $false -Temporary

thanks,
Chrissy

**Comment by potatoqualitee** [comment]
can you also alias Persistvalue to value? also make this easier? as mentioned in the other issue, this does not feel intuitive and i have no docs to help.

![image](https://user-images.githubusercontent.com/8278033/58372622-aecf1a00-7f20-11e9-867e-c9f07362270c.png)


thanks

**Comment by wsmelton** [comment]
I would not prefer or to be registered by default at all!

We use the temp setting for session level settings all the time. Registering makes it permanent.

**Comment by potatoqualitee** [comment]
nm, overruled
