### ISSUE TITLE
Internal Function - Invoke-SqlWmiCommand

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#562]
Is this a *feature* OR *bug*:
Enhancement 

**Additional comments**
This is up for discussion. The more I use this command, the more I like it. It's like Invoke-Command but it executes SQL WMI stuff.

It even has similar syntax

Invoke-ManagedComputerCommand -ComputerName $netbiosname -ArgumentList $instancename -ScriptBlock $scriptblock

It supports Credentials, and if the local SqlWmi load fails (sqlwmi managed computer between SMO ersions is super buggy), it attempts returning the object from Invoke-Command then running it there. Has worked flawlessly in two commands.
[Invoke-ManagedComputerCommand.zip](https://github.com/sqlcollaborative/dbatools/files/715341/Invoke-ManagedComputerCommand.zip)

**Comment by potatoqualitee** [comment]
done :D
