### ISSUE TITLE
[Bug] Update-DBAInstance

### ISSUE THREAD

**Issue by artyq** [sqlcollaborative/dbatools#5620]
### Environmental information

PSVersion                      5.1.14409.1018              
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.830\dbatools.psd1
Version : 0.9.830 
                                                                          

#### SQL Server: 

```sql
Microsoft SQL Server 2012 (SP4-GDR) (KB4057116) - 11.0.7462.6 (X64)   Jan  5 2018 22:11:56   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)
```

#### Errors Received

VERBOSE: [07:26:56][Get-SqlServerUpdate] 11.0.7462 on computer [Myserver.me.com] is already the latest available.

#### Steps to Reproduce

```Update-DbaInstance -Authentication Credssp -Credential $Creds -ComputerName MyServer -Path "\\MyPath\SQLPatches" -ExtractPath "C:\Temp" -Restart -Verbose```

#### Expected Behavior

To update SQL 2012 to version 11.0.7469.  As this build is listed in dbatools-buildref-index.

#### Actual Behavior

States that SQL 2012 instance is already at its latest version.

[verboselog.txt](https://github.com/sqlcollaborative/dbatools/files/3227563/verboselog.txt)

**Comment by potatoqualitee** [comment]
thanks so much!

**Comment by potatoqualitee** [comment]
any chance you'll have time before 1.0, @nvarscar ? if not, i'll take it off the todo

**Comment by nvarscar** [comment]
The command doesn't support installing custom hotfixes with default parameters, only SPs and CUs. If you want a custom KB to be installed, please use the `-KB` parameter.

**Comment by potatoqualitee** [comment]
Sweet, thanks for the response, @nvarscar 👍
