### ISSUE TITLE
[Bug] New Export PR WIll skip Export-DbaLogin tests

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5623]
it has regex and i wouldnt have time to fix. can someone else please look once the PR has come in? it's not caused by the changes in this PR, the entire integration tests were commented out from an earlier PR.

**Comment by potatoqualitee** [comment]
@sqllensman or @joshcorr  - same as before 😅  can either of you you take a look at this? thanks so much

**Comment by joshcorr** [comment]
I will grab this one.
