### ISSUE TITLE
[Bug] After my Export PR, Export-DbaScript Integration Test should be prioritized

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5624]
it has no integration tests but is an essential command.

**Comment by potatoqualitee** [comment]
Export-DbaSpConfigure would be nice as well

**Comment by potatoqualitee** [comment]
@sqllensman or @joshcorr  - can either of you you take a look at this? I have to work on my PSConf Presentation and write Chapter 8 in the next few days and won't be available much until June 8.

**Comment by sqllensman** [comment]
I will have a look for yoy.

**Comment by sqllensman** [comment]
I have presentation due on 8th June that will be based on Pre-Release branch so this is priority for me 😉

**Comment by potatoqualitee** [comment]
awesome :D conference driven development yay!

**Comment by joshcorr** [comment]
I was going to say something ealier about taking a look. @sqllensman  let me know if you need any help

**Comment by potatoqualitee** [comment]
gonna merge when done ✔️
