### ISSUE TITLE
Get-DbaActiveConnection

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#564]
Is this a *feature* OR *bug*:
Enhancement 
https://trello.com/c/ckFPu1to

**Additional comments**
http://www.johnsansom.com/dmv-query-to-identify-all-active-sql-server-sessions/

SELECT B.login_name, A.client_net_address, NoOfConnections = COUNT(*) FROM sys.dm_exec_connections A INNER JOIN sys.dm_exec_sessions B ON A.session_id = B.session_id GROUP BY login_name, client_net_address

And -Force would show all the details of each connection

"Attached Shawn's AG listener script.

$server.enumprocesses() shows stuff similar to Activity Monitor, and I wanted to make that into a command. Any suggestion on the naming? The original sql posted up there is simplified -- just the login name, net address and number of connections. Should that be -Summary? If so, what could be the regular output and what's -Detailed? Should these be diff commands?" 

[ag.zip](https://github.com/sqlcollaborative/dbatools/files/715345/ag.zip)

**Comment by niphlod** [comment]
@SirCaptainMitch : isn't Get-DbaProcess enough ? 

If yes, this need closing

cc @potatoqualitee

**Comment by potatoqualitee** [comment]
Yep,, thats a portion of the command i use! It's all extra gorgeous now, too.

![image](https://user-images.githubusercontent.com/8278033/28028445-d52635f2-659c-11e7-9622-5b032b669fc8.png)
