### ISSUE TITLE
RESOLVED! / dbatools.Types.ps1xml cannot be loaded because its operation is blocked by software restriction policies, such as those created by using Group Policy.

### ISSUE THREAD

**Issue by rubens-mosaic** [sqlcollaborative/dbatools#5640]
Hi guys,

A long, long... LONG time ago I encountered a problem that's taken me forever to resolve so I wanted to post the fix.  In a nuthsell, I was getting dbatools specific errors similar to this.  "Find-DbaCommand : The 'Find-DbaCommand' command was found in the module 'dbatools', but the module could not be loaded. For more information, run 'Import-Module dbatools'."

When I tried importing the tools, I got this error, "Import-Module : The following error occurred while loading the extended type data file: , C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.832\xml\dbatools.Types.ps1xml: The file was
skipped because of the following validation exception: File C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.832\xml\dbatools.Types.ps1xml **cannot be loaded because its operation is blocked by software restriction policies, such as those created by using Group Policy.**"

I tinkered with the Execution Policy and you guys had a lot of other great suggestions.  After a ton of troubleshooting, this is what solved my problem.  **Internet Options | Content | Certificates… dbatools was listed in the “Untrusted Publishers” tab.  When I removed it everything started working successfully.**

Screen shot also attached.

![image](https://user-images.githubusercontent.com/39064761/58579930-053aa200-821a-11e9-9ee3-016a65e66c6e.png)

Hope that helps!
Rubens

**Comment by potatoqualitee** [comment]
Thank you so much for letting googlers know! I have somenoe right now with a similar issue that i'm about to point them here, see if it helps 💯
