### ISSUE TITLE
New Command - Copy-DbaStartupTraceFlag

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#565]
Is this a *feature* OR *bug*:
https://trello.com/c/Ml9pk8I9

**Additional comments**
Use Get/Set-DbaStartupParameters to copy the non-path startup parameters (trace flags) from one instance to another.

**Comment by wsmelton** [comment]
If this is just for trace flags shouldn't it be `Copy-DbaStartupTraceFlag` ? // @potatoqualitee

**Comment by wsmelton** [comment]
Cleaning up issues...

Someone wants to tackle this can re-open it.
