### ISSUE TITLE
Greedy AG creation - again

### ISSUE THREAD

**Issue by michalporeba** [sqlcollaborative/dbatools#5650]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.316                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.316                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.832\dbatools.psd1
Version : 0.9.832

```

#### SQL Server: 
```sql
N/A
```

### Report

`New-DbaAvailabilityGroup` again pulls in all databases to a newly created availability group if no specific databases were provided. This was solved previously in #5075 

#### Errors Received

There are no errors

#### Steps to Reproduce

Run something like this
`New-DbaAvailabilityGroup -Primary mytestinstance -Name TestAG`

#### Expected Behavior

If no databases are explicitly listed no databases should be add to the newly created AG. 

#### Actual Behavior

All databases, including system databases and those already in other groups are being added to the newly created AG

**Comment by potatoqualitee** [comment]
fixing in dev and pushing out momentarily to gallery

**Comment by potatoqualitee** [comment]
Sorry about that. I believe what happened wa the PR was pushed to master and I did not notice, nor did I sync it back to Dev, so it only ever existed in master. Getting this fixed immediately then will ensure it's in `prerelease`. if you could write a regression test, that would be 🙇

**Comment by michalporeba** [comment]
I have a fix with some extra unit tests to make sure it stays fixed

**Comment by michalporeba** [comment]
You are way too fast for normal people :). Thank you. 

Let's see if my integration tests work, I cannot run them locally at the moment so I'm waiting to hear back from the build pipeline.

**Comment by potatoqualitee** [comment]
🐰 🚤  ;) Thank you!

**Comment by potatoqualitee** [comment]
now in master/gallery 💯
