### ISSUE TITLE
Get-DbaDatabaseDependencyReport

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#566]
Is this a *feature* OR *bug*:
https://trello.com/c/NzmADcyM

**Additional comments**
Logins, apps (so mix with a better version of watch-sqldblogin), jobs, etc

**Comment by potatoqualitee** [comment]
@Staggerlee011 - you were talking about this right?

**Comment by wsmelton** [comment]
I'm not sure this is still desired?

@potatoqualitee is this referring to something like code noted here: https://www.mssqltips.com/sqlservertip/2999/different-ways-to-find-sql-server-object-dependencies/ ?

**Comment by potatoqualitee** [comment]
ahh this was taken care of by `Get-DbaDependency`
