### ISSUE TITLE
Allow the Choice of IP/Name of the NIC to be used on servers with multiple NICs on all commands

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#568]
Is this a *feature* OR *bug*:
https://trello.com/c/gHVT1meS

**Additional comments**
This could be using some GUI to select the one we want, or an extra variable that accepts the suffix of the network card.

Since I have this problem, I believe that someone else can also have it
Example: Server srv1 has 3 IPs
- IP1
- IP2
- IP3

From my PC when I ping the srv1 the IP I see is IP1 but I'm only able to connect to sql server instance through IP2 so if I PING srv1.IP2 I can see the IP of IP2.

Once Resolve-NetBiosName only retrieves the server name this will be the IP1 and not the IP2 that I need.

This should be added to all $sourcenetbios variables.

Thoughts?

**Comment by potatoqualitee** [comment]
I believe this is impossible - just pass the IP eh? Not respecting the passed servername should be fixed in another ticket where we stop using ComputerNetBios and start using $instance.ComputerName
