### ISSUE TITLE
Error with Invoke-DbaQuery -SqlCredential when called from web app

### ISSUE THREAD

**Issue by mrothwell** [sqlcollaborative/dbatools#5680]
Invoke-DbaQuery is not using the SqlCredential when called from C# web app.

$SourceUsername   = 'MYDOMAIN\myAdUserName'
$SecureIntPw      = Get-Content "C:\Scripts\Security\myAdUserName.txt" | ConvertTo-SecureString
$SourceCredential = new-object -typename System.Management.Automation.PSCredential -argumentlist $SourceUserName, $SecureIntPw

$mytest = Invoke-DbaQuery -SqlInstance $BackupInstance -Database "master" -SqlCredential $SourceCredential -Query "select suser_name()" -as SingleValue
write-output "I am currently running as:  $mytest"

When I run this code from a powershell console or ISE, it returns:  "I am currently running as: MYDOMAIN\myAdUserName"
This is what I would expect, as that is the user I defined in the code.

When I run this from a webapp (C# visual studio), it returns:  "I am currently running as: MYDOMAIN\AppPoolServerName$"
MYDOMAIN\AppPoolServerName$ is the name of the Server that the C# code was published on.

Here is the C# code calling the powershell script:

var shell = PowerShell.Create();
          RunspaceConfiguration runspaceConfiguration = RunspaceConfiguration.Create();
          shell.Runspace = RunspaceFactory.CreateRunspace( runspaceConfiguration );
          shell.Runspace.Open();

          shell.AddCommand("c:\\scripts\\mytest.ps1", false);
          shell.AddParameter( "parm1",    TextBox_SourceInstance.Text);

          // Execute the script
          Collection<PSObject> results = shell.Invoke("Set-ExecutionPolicy Unrestricted -Scope Process");

Tested with the following code, but same results:

$server = Connect-DbaInstance -SqlInstance $BackupInstance -Databse master -SqlCredential $SourceCredential
$mytest = Invoke-DbaQuery -SqlInstance $server -Query "select suser_name()" -as SingleValue
write-output "I am currently running as:  $mytest"

**Comment by potatoqualitee** [comment]
This likely has to do with Kerberos delegation and double hop. I'd be interested in the solution, but C# is out of our scope and it works on PowerShell. Ultimately, however, I think this will solve your problem: https://blogs.technet.microsoft.com/askds/2008/06/13/understanding-kerberos-double-hop/

**Comment by potatoqualitee** [comment]
oh, also try sql auth. that is not subject to double hop issues.

**Comment by mrothwell** [comment]
Sql auth would require that I create a new user on every instance.  I'd rather not have to do that.

**Comment by mrothwell** [comment]
Also, it's marked as "done" in 1.0.  Is this issue fixed in 1.0 or is it considered a "non-issue" and needs to be solved via sql auth or kerberos double hop?

**Comment by potatoqualitee** [comment]
it was a troubleshooting suggestion, not an implementation suggestion. i avoid sqlauth when possible so it's basically to prove the issue is double hop and not dbatools.

as for your second request, it'll need to be solved externally unless you can prove otherwise. which i'm open to, tho I'm fairly certain this is a double hop issue.

**Comment by mrothwell** [comment]
I just tested using sql_auth, still got the same result when ran through the webapp.
So, does that prove that it's not a double hop issue?  I cant imagine it being double hop issue anyway, as it's a single hop from the server executing the powershell to the sql server.  The exact same hop as when I execute the powershell interactively.

**Comment by potatoqualitee** [comment]
that just may! can you issue a `Get-DbaProcess -SqlInstance sqlserver -Login sqluseraccount | Select-Object -Property  * -ExcludeProperty ClientNetAddress, LastQuery` and screenshot the results? Something like this:

![image](https://user-images.githubusercontent.com/8278033/59209148-ed183a80-8baa-11e9-9688-827c7d965d2c.png)

IIS running as the app pool makes it double hop. You'll find it'll login as that other user if you change the login of the app pool and do not use dbatools creds within the command.

If you can email me clemaire@gmail.com (or attach to this issue) a super basic asp.net webapp for me to repro, I can try on my own local IIS.

**Comment by wsmelton** [comment]
Chrissy, my thought was try running a command in a runspace. That is what the C# is going to to use to execute the code, it creates a runspace to execute the PowerShell thread. So it won't be a hop but loss of context.... Just spit balling.

**Comment by potatoqualitee** [comment]
i was thinking that too, and even started creating the code but then i realize that we do need that extra hop. im not sure what to make run my runspace? agent, perhaps?

**Comment by wsmelton** [comment]
Agent should work since that is within another process running...I would think that would be similar to the web app.

**Comment by mrothwell** [comment]
just checking in to see if there is anything new on this?  

Today, I tried to publish to my localhost with iis running.  My thinking was that since the web browser and the web server were on the same machine, there would be no "double hop".  No joy.  Still logging into the db as the machine rather than the user defined.

**Comment by potatoqualitee** [comment]
@mrothwell - i did not receive any sample code so didn't pursue it. i could do it in agent, but it's not as exact.

**Comment by mrothwell** [comment]
@potatoqualitee, I just sent you an email with the VS code and PS script.

In the meantime, I have been playing around with some settings and found that in IIS, I went to the app pool I'm using and changed the "identity" to use my username/password.  This seems to take care of my issue, but not really a good idea if I were to deploy this to a real IIS server and not just my PC running IIS.

**Comment by potatoqualitee** [comment]
Thanks - I still have not received the zip successfully.

>  My thinking was that since the web browser and the web server were on the same machine, there would be no "double hop".

The hop is between services. Have you explored double hop solutions like enabling kerberos delegation?

**Comment by mrothwell** [comment]
[SqlToolsTest.zip](https://github.com/sqlcollaborative/dbatools/files/3340583/SqlToolsTest.zip)

**Comment by mrothwell** [comment]
I did play around with kerberos by doing some searches.  Didn't really gain anything.  If you know of a good place to walk me through the kerberos delegation, please send it to me.

**Comment by potatoqualitee** [comment]
Thanks, zip worked here 💯  

This tutorial looks closest to what I setup

https://support.jetglobal.com/hc/en-us/articles/115009137148-Jet-Dashboard-Builder-Configuring-Windows-IIS-Double-Hop-Settings

And this tool is recommended for troubleshooting tho I never used it. The tutorial above should be adequate tho. 

https://github.com/SurajDixit/KerberosConfigMgrIIS/releases
