### ISSUE TITLE
Invoke-DbaDbLogShipping - Failure reading backup header 

### ISSUE THREAD

**Issue by PreacherCmdLets** [sqlcollaborative/dbatools#5685]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`

WARNING: [10:08:49][Get-DbaBackupInformation] Failure reading backup header | The media family on device '\\location\Test\FullBackup_Test_PreLogShipping_20190606100839.bak' is incorrectly formed. SQL 
Server cannot process this media family.
RESTORE FILELIST is terminating abnormally.
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

**Comment by PreacherCmdLets** [comment]
Both the instance is on same version and location of the .ldb & .mdf are same

**Comment by potatoqualitee** [comment]
Hello @PreacherCmdLets  - we no longer accept bug reports that do not use the bug report template. The information we request is information that helps us solve the problem. Please create a new bug report following the format. 

https://github.com/sqlcollaborative/dbatools/issues/new?assignees=&labels=%5Bbugs+life%5D&template=Bug_Report.md&title=%5BBug%5D

**Comment by PreacherCmdLets** [comment]
Thank you @potatoqualitee
