### ISSUE TITLE
Undo-DbaReplication

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#569]
Is this a *feature* OR *bug*:
https://trello.com/c/5gTpwtFV

**Additional comments**
Smashing replication? https://www.mssqltips.com/sqlservertip/2710/steps-to-clean-up-orphaned-replication-settings-in-sql-server/

I dunno, an idea. I don't work with replication.

**Comment by wsmelton** [comment]
I'm closing this one for now...once we get replication commands it will likely be covered.
