### ISSUE TITLE
Extra meta data for masking and data generation configurations

### ISSUE THREAD

**Issue by sanderstad** [sqlcollaborative/dbatools#5697]
### Summary of new feature

The configurations for the data masking and data generation are based on each other both are inherently different. Someone could make the mistake to use the wrong kind of file.

To prevent this there should be extra metadata in the configurations that makes clear what kind of file it is.

### Proposed technical details (if applicable)

1. Create extra data that shows the type of file
2. Let the commands New-DbaDataMaskingConfig and New-DbaDataGenerationConfig add the metadata 
3. Let the commands Invoke-DbaDbDataMasking and Invoke-DbaDbDataGeneration check on the metadata 

### Latest version of dbatools as of writing

0.9.834

**Comment by sanderstad** [comment]
All the configurations people made are going to need the extra metadata.
That's why it's labeled as a breaking change.

**Comment by potatoqualitee** [comment]
thank you, will be noted in the release!

**Comment by wsmelton** [comment]
Closing this, if still required please just reopen.
