### ISSUE TITLE
Test-OlaMaintenanceScriptSetup

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#570]
Is this a *feature* OR *bug*:
https://trello.com/c/LxUwlH99

**Additional comments**
"Here is a thought. Wouldn't it be nice if you could validate that the Ola Hallengren's maintenance solution is set up on all your instances you have in registered servers and that it is actually working as it should. So something like talked about here : https://sqldbawithabeard.com/2016/09/24/powershell-pester-and-ola-hallengrens-maintenance-solution/

Just thinking that this might be really cool in dbatools :) "

**Comment by potatoqualitee** [comment]
this is now in dbachecks 💯
