### ISSUE TITLE
[Bug]ConvertTo-DbaDataTable Memory Leak

### ISSUE THREAD

**Issue by JustinGrote** [sqlcollaborative/dbatools#5707]
### Environmental information

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.503
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.503
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name    : dbatools
Path    : C:\Users\JGrote\Documents\WindowsPowerShell\Modules\dbatools\0.9.834\dbatools.psd1
Version : 0.9.834
```

#### SQL Server: 

```sql
N/A (local operation)
```

### Report

 

When doing a large object array in convertto-dbadatatable, the memory is never released even if the variable is unset and GC is collected. It even persists if the module is unloaded, only way I can free the memory is to completely kill the process.

For a large dataset, my powershell process ends up consuming 6+GB of memory even though i am processing in small 100MB batches and eventually crashes.

Meanwhile if I use a simple alternative: https://gist.github.com/gravejester/3052e0e54e35bebc3257

It works fine and things clean up as expected

#### Steps to Reproduce

Create a large object array, convert it to a datatable, unset the variable, do garbage collection,

#### Expected Behavior

Memory is freed. Works with above referenced script (memory is freed as expected)

#### Actual Behavior

Memory is not freed, looks to be retained in some sort of logging runspace perhaps

**Comment by potatoqualitee** [comment]
Thanks for the report!

@FriedrichWeinmann - any chance you can take a look? I'll have no idea.

**Comment by wsmelton** [comment]
Many changes have been made to the module since this post was open. Please confirm you can duplicate this issue on the latest release and open a new issue if it continues to happen.
