### ISSUE TITLE
Test-DbaMaxMemory

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#571]
Is this a *feature* OR *bug*:
https://trello.com/c/1mC60w0J

**Additional comments**
Get-SqlMaxMemory offers suggestions, which never really sat well with me but I didn't think of Test commands at the time. By v1.0, I'd like Get to offer just the max memory and total memory and Test to have the calculated suggestion.

**Comment by SirCaptainMitch** [comment]
This might be outdated, as I have used this cmdlet already. Making the issue anyway just in case I am missing something.

**Comment by ie-zero** [comment]
@SirCaptainMitch you are not missing anything. Trello board in outdated and we should start closing the completed cards. 

The work was completed on PR #340 "Memory suggestions are offered by Test-SqlMaxMemory"

Thanks for reporting it.

**Comment by SirCaptainMitch** [comment]
@ie-zero yeah, I brought it over from the trello when I was setting us up to migrate the issues for waffle.io, I am going to close this one out.
