### ISSUE TITLE
Import-SqlToSharePoint

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#572]
Is this a *feature* OR *bug*:
https://trello.com/c/i7g95JSj

**Additional comments**
Not entirely convinced, what do you guys think? I recently had a request to delete all items from a list (-Truncate) and then add all results from a query.

Attached is the hacked together manual way. But if the columns matched it'd be more straightforward. Also we could offer a -ColumnMapper to map sql columns to SP columns.
[Import-SqlToSharePoint.zip](https://github.com/sqlcollaborative/dbatools/files/715359/Import-SqlToSharePoint.zip)

**Comment by potatoqualitee** [comment]
did this in my other module, SPReplicator
