### ISSUE TITLE
Test-DbaVirtualMemory

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#574]
Is this a *feature* OR *bug*:
https://trello.com/c/zvz5Ru1g

**Additional comments**
http://sqlblog.com/blogs/buck_woody/archive/2010/06/29/the-windows-page-file-and-sql-server.aspx

https://support.microsoft.com/en-ca/kb/2860880
https://technet.microsoft.com/en-us/library/ms187877(v=sql.105).aspx
https://blogs.technet.microsoft.com/motiba/2015/10/15/page-file-the-definitive-guide/

[pagefile.zip](https://github.com/sqlcollaborative/dbatools/files/715367/pagefile.zip)

**Comment by potatoqualitee** [comment]
get-dbapagefile is good enough
