### ISSUE TITLE
[Bug] Add-DbaAgDatabase - Conversion error

### ISSUE THREAD

**Issue by brunobbc** [sqlcollaborative/dbatools#5744]
### Report
SELECT @@VERSION 

SQL Server:
sql Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64) Mar 18 2018 09:11:49 Copyright (c) Microsoft Corporation Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 (Build 14393: ) (Hypervisor)

gmo dbatools -List | select name, path, version | fl -force | Out-String

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.834\dbatools.psd1
Version : 0.9.834

#### Errors Received

WARNING: [17:44:39][Add-DbaAgDatabase] Failure | Cannot convert the "[SVR2]" value of type
"Microsoft.SqlServer.Management.Smo.Server" to type "Microsoft.SqlServer.Management.Smo.Server".
Fin du script : 2019-06-13 5:44:39 PM

#### Steps to Reproduce

$InstanceName = $env:computername
$AvailabilityGroup = Get-DbaAvailabilityGroup -SqlInstance $InstanceName | select -ExpandProperty Name
$PrimaryServer = "SVR1"
$SecondaryServer = "SVR2"
$Database = "Test"
$SharedPath = "\\" + $PrimaryServer + "\E$\MSSQL\Backup"

$DatabaseBackupFile = $SharedPath + "\" + $Database + ".bak"
$LogBackupFile = $SharedPath + "\" + $Database + ".trn"

Backup-SqlDatabase -Database $Database -BackupFile $DatabaseBackupFile -ServerInstance $PrimaryServer -Verbose
Backup-SqlDatabase -Database $Database -BackupFile $LogBackupFile -ServerInstance $PrimaryServer -BackupAction Log -Verbose

Restore-SqlDatabase -Database $Database -BackupFile $DatabaseBackupFile -ServerInstance $SecondaryServer -NoRecovery -Verbose 
Restore-SqlDatabase -Database $Database -BackupFile $LogBackupFile -ServerInstance $SecondaryServer -RestoreAction Log -NoRecovery -Verbose

Add-DbaAgDatabase -AvailabilityGroup $AvailabilityGroup -Database $Database -Secondary $SecondaryServer -SharedPath $SharedPath -SqlInstance $PrimaryServer -UseLastBackup

#### Expected Behavior
I expect to have a DB syncronized and added to the secondary.

#### Actual Behavior

Primary Server = DB is in sycronized State and availability Database is created (Correct !!)
Secondary = DB is in restoring state and not available. 

Things to consider:
- Conversions errors when try to run ADD-DbaAGDatabase

**Comment by potatoqualitee** [comment]
Thanks for the report! I'll take a look today or tomorrow.

**Comment by potatoqualitee** [comment]
hello what is your locale? `fr-fr` ?

**Comment by potatoqualitee** [comment]
okay, this seems unrelated to the other issues we are having and seems more related to duplicate SMO loading. Please confirm if you can get this to happen if:

from powershell.exe

```
get-process *powershell* | stop-process
powershell.exe -noprofile
ipmo dbatools
<run your command>
```

This appears to be an SMO conflict, perhaps due to a manual loading of SMO or the SQLServer/SQLPS module. Loading different versions of SMO cannot be supported.

**Comment by potatoqualitee** [comment]
considering closed as my suggestion above should address the issue. if not, please let me know and i'll reopen 👍
