### ISSUE TITLE
Copy-DbaDatabase | Conversion failed

### ISSUE THREAD

**Issue by mrjohnsen** [sqlcollaborative/dbatools#5748]
Not able to use Copy-DbaDatabase with backup/restore method. Failing with "Verify service account access" and "Conversion failed when converting date and/or time from character string". I have confirmed service account permissions so there is not problem there. Here is the log:

Copy-DbaDatabase -Source sourceserver -Destination destinationserver -Database databasename -BackupRestore -Sharedpath \\destinationserver\migrate -verbose

VERBOSE: [09.57.14][Copy-DbaDatabase] Ensuring user databases exist (counting databases).
VERBOSE: [09.57.14][Copy-DbaDatabase] Performing SMO version check.
VERBOSE: [09.57.14][Copy-DbaDatabase] Checking to ensure the source isn't the same as the destination.
VERBOSE: [09.57.14][Copy-DbaDatabase] Checking to ensure server is not SQL Server 7 or below.
VERBOSE: [09.57.14][Copy-DbaDatabase] Checking to ensure detach/attach is not attempted on SQL Server 2000.
VERBOSE: [09.57.14][Copy-DbaDatabase] Checking to ensure SQL Server 2000 migration isn't directly attempted to SQL
Server 2012.
VERBOSE: [09.57.14][Copy-DbaDatabase] Warning if migration from 2005 to 2012 and above and attach/detach is used.
VERBOSE: [09.57.14][Copy-DbaDatabase] Ensuring destination server version is equal to or greater than source.
VERBOSE: [09.57.14][Copy-DbaDatabase] Writing warning about filestream being enabled.
VERBOSE: [09.57.14][Copy-DbaDatabase] Building database list.
VERBOSE: [09.57.14][Copy-DbaDatabase] Performing count.
VERBOSE: [09.57.14][Copy-DbaDatabase] Building file structure inventory for 1 databases.
VERBOSE: [09.57.14][Get-SqlFileStructure] databasename
VERBOSE: [09.57.14][Copy-DbaDatabase]
######### Database: databasename #########
VERBOSE: [09.57.14][Copy-DbaDatabase] Checking for accessibility.
VERBOSE: [09.57.14][Copy-DbaDatabase] Checking Availability Group status.
VERBOSE: [09.57.14][Copy-DbaDatabase] Started: 06/17/2019 09:57:14.
VERBOSE: Performing the operation "Backup databasename from sourceserver and restoring" on target "destinationserver".
VERBOSE: [09.57.14][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [09.57.14][Backup-DbaDatabase] 1 database to backup
VERBOSE: [09.57.14][Backup-DbaDatabase] Backup database [databasename]
VERBOSE: [09.57.14][Backup-DbaDatabase] Creating full backup
VERBOSE: [09.57.14][Backup-DbaDatabase] Building file name
VERBOSE: [09.57.14][Backup-DbaDatabase] Setting filename - 201906170957
VERBOSE: [09.57.14][Backup-DbaDatabase] Building backup path
VERBOSE: [09.57.14][Backup-DbaDatabase] Devices added
VERBOSE: [09.57.20][Get-DbaBackupHistory] Processing databasename
WARNING: [09.57.20][Backup-DbaDatabase] Backup Failed | Conversion failed when converting date and/or time from character string.
VERBOSE: [09.57.20][Copy-DbaDatabase] Backup Failed. Does SQL Server account serviceaccount have access to \\destinationserver\migrate? Aborting routine for this database.

VERBOSE: [09.57.20][Copy-DbaDatabase] Database migration finished
VERBOSE: [09.57.20][Copy-DbaDatabase] Migration started: 06/17/2019 09:57:14
VERBOSE: [09.57.20][Copy-DbaDatabase] Migration completed: 06/17/2019 09:57:20
VERBOSE: [09.57.20][Copy-DbaDatabase] Total Elapsed time: 00:00:05
Type     Name       Status Notes
----     ----       ------ -----
Database databasename Failed Backup failed. Verify service account access to \\destinationserver\migrate.

Test-DbaPath -sqlserver sourceserver -path '\\destinationserver\migrate'
True

Test-DbaPath -sqlserver destinationserver -path '\\destinationserver\migrate'
True

**Comment by potatoqualitee** [comment]
@mrjohnsen - thanks for the bug report. Unfortunately, this issue does not follow the bug report format and will be closed per #5438 

It will also be helpful to know which host you are using to run the command - ie. powershell.exe, ISE, VSCode, etc.

**Comment by potatoqualitee** [comment]
Can you please let us know your locale in the new issue as well? like `en-us`.

**Comment by potatoqualitee** [comment]
The fix is included in #5753 which will be released with dbatools 1.0 on Thursday morning 💯
