### ISSUE TITLE
Get-DbaDatabaseFreespace - Divide by zero error encountered

### ISSUE THREAD

**Issue by white-bee** [sqlcollaborative/dbatools#575]
Have  failure with Get-DbaDatabaseFreespace -SqlServer SQL777 | Format-Table

```
 WARNING: See error log *************\Documents\dbatools-exceptions.txt for more details.
 Unable to query SQL777 - REPORT_DEV
 At ************\Documents\WindowsPowerShell\Modules\dbatools\functions\Get-DbaDatabaseFreespace.ps1:195
 char:6
 +                     throw "Unable to query $($s) - $($db.name)"
 +                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: (Unable to query...REPORT_DEV:String) [], RuntimeException
     + FullyQualifiedErrorId : Unable to query SQL777 - REPORT_DEV
```

It looks like problem with 
```
,CAST((FILEPROPERTY(f.name, 'SpaceUsed')/(f.size/1.0)) * 100 as DECIMAL(15,2)) as [PercentUsed]
in underline query. 
```

in underline query and be fixed by
`,ISNULL(CAST((FILEPROPERTY(f.name, 'SpaceUsed')/NULLIF((f.size/1.0),0)) * 100 as DECIMAL(15,2)),0) as [PercentUsed]`

failure occurs on full-text index file.

**Comment by niphlod** [comment]
IMHO the proposed fix isn't the best solution. Could you please run the following query on the offending database ?

```select FILEPROPERTY(f.name, 'SpaceUsed') as spaceused, f.size 
from sys.database_files AS f```

**Comment by white-bee** [comment]
Here you go

```
spaceused   size
----------- -----------
574448      684752
2232        395504
19048       20048
574448      0

(4 row(s) affected)
```

**Comment by white-bee** [comment]
And according to [BOL](https://msdn.microsoft.com/en-us/library/ms174397.aspx) 0 should be expected 

![image](https://cloud.githubusercontent.com/assets/11417419/22127836/b6609c42-de6b-11e6-86d6-01ce9a5b5156.png)

**Comment by niphlod** [comment]
uh, gotcha, you're on 2005 ? 
But it still needs a more careful review 'cause even for snapshots and FileStream the reported data is wrong.
I'll change the title a bit to reflect this and the other bugs

**Comment by white-bee** [comment]
I am on
`Microsoft SQL Server 2012 - 11.0.5058.0 (X64) 
	May 14 2014 18:34:29 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: )`

but compatibility level for the database is SQL Server 2005

**Comment by potatoqualitee** [comment]
This was fixed by @scinobe in an earlier PR. @white-bee plesase let us know if you continue to encounter the issue in the newest release.
