### ISSUE TITLE
Disable-DBAAgentJob

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#576]
Is this a *feature* OR *bug*:
https://trello.com/c/TuMTftmf

**Additional comments**
Thinking of times when you need to copy jobs to other instances, but dont want them to run (log shipping, AG groups etc) process of using copy-job then disable, or find-dbajob then disable.

**Comment by sanderstad** [comment]
I don't think we need a new command for this. The Set-DbaAgentJob has a parameter to enable or disable a job like:
![image](https://user-images.githubusercontent.com/6154981/31379273-1318a2b0-adae-11e7-9bea-58477c0d2bb3.png)
