### ISSUE TITLE
Final Checks

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5766]
- [x]  Check that the big commands work in win7
- [x]  Check that the big commands work on sql2000
- [x]  works when imported as a regular user and not a dev
- [x]  works with core
- [x] x86
- [x]  works with strict signing policy
- [x] All commands have been imported from functions
- [x] rename sander's commands

**Comment by potatoqualitee** [comment]
Works on Linux 

![image](https://user-images.githubusercontent.com/8278033/59701404-de0e3980-91f5-11e9-9379-253761a31526.png)

**Comment by potatoqualitee** [comment]
Works as regular user import

![image](https://user-images.githubusercontent.com/8278033/59701911-de5b0480-91f6-11e9-8965-7a97673d8d6c.png)

**Comment by potatoqualitee** [comment]
works with strict signing policy

![image](https://user-images.githubusercontent.com/8278033/59701994-0d717600-91f7-11e9-9564-798ee6dde4d2.png)

**Comment by potatoqualitee** [comment]
works on old with sql2000 as well
![image](https://user-images.githubusercontent.com/8278033/59706117-0ef36c00-9200-11e9-8b71-fa7ac90cd0a4.png)

**Comment by potatoqualitee** [comment]
Thanks @ClaudioESSilva for your assistance with the command list!

**Comment by joshcorr** [comment]
Were we removing the Test-DbaDeprecatedFeature calls for any parameters that were removed?

**Comment by potatoqualitee** [comment]
yes, shit did i miss that?

**Comment by potatoqualitee** [comment]
oh good, no, test-dbadeprecation is different from Test-DbaDeprecatedFeature which tests sql server dep features. we've removed all dbatools deprecation tests
