### ISSUE TITLE
Get-DbaDatabaseGrowth

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#577]
Is this a *feature* OR *bug*:
https://trello.com/c/pUAVChjK

**Additional comments**
Refs: http://www.sqlskills.com/blogs/erin/trending-database-growth-from-backups/

With a-Chart that does something like: https://blogs.technet.microsoft.com/richard_macdonald/2009/04/28/charting-with-powershell/

Notes column to warn if there's not enough info to determine long term growht. Support for -Since with either a timespan or like Week, Month, Year. By default use all data.

Add support for -Databases dynamic param to allow for one, many or all.

**Comment by potatoqualitee** [comment]
Done!
