### ISSUE TITLE
DB Page Verification

### ISSUE THREAD

**Issue by SQLDataCloud** [sqlcollaborative/dbatools#5775]
### Summary of new feature

In the same way that Test-DbaDbCollation/Test-DbaDbCompatibility function, maybe a feature like Test-DbaDbPageVerify that would check all databases on a given instance where db page verification is set to anything other than CHECKSUM.

### Proposed technical details (if applicable)
Something along the lines of following: (sorry if this is in wrong format/process, not done this before).

```
            $db
                Write-Message -Level Verbose -Message "Processing $($db.name) on $instance."
                [PSCustomObject]@{
                   ComputerName          = $server.ComputerName
                ##   InstanceName          = $server.ServiceName
                   SqlInstance           = $server.DomainInstanceName
                  ServerLevel           = $serverversion
                   Database              = $db.name
                   PageVerification      = $db.Pageverify
```
Or possibly the following (thanks to Shane O'Neill for this, it is his code)
```
(Get-DbaDatabase -sqlinstance localhost).Where{ $_.PageVerify -ne 'CHECKSUM' }.foreach{
    [PSCUstomObject]@{
        Name = $_.name
        page = $_.PageVerify
    }
}
```

### Latest version of dbatools as of writing

0.9.834

**Comment by shaneis** [comment]
😁 Oi @keypersltd ! Don't blame me!

I don't think the `.Where({})` and the `.ForEach({})` format works on the earlier versions of PowerShell that dbatools supports so it'll need to be re-written.

That being said, I've heard this being asked for a few times lately so I like it 👍

**Comment by andreasjordan** [comment]
@potatoqualitee What do you think? Maybe I find time to create the command.

**Comment by potatoqualitee** [comment]
I'm not so sure about most `Test` commands nowadays because we moved a lot of that functionality into dbachecks. I'm leaning no. @wsmelton, what do you think?

**Comment by andreasjordan** [comment]
Oh yes, haven't thought about dbachecks - would also see it there. If someone does not what to install dbachecks, they can use the code from the original post.

**Comment by potatoqualitee** [comment]
Agreed, will close unless shawn feels strongly about it.

**Comment by wsmelton** [comment]
> we moved a lot of that functionality into dbachecks

Not sure about this statement, we have just north of 40 test commands in the module currently. Conversations I've been on at least we have never used dbachecks as the litmus deciding what Test commands we added either.

The general use of Test functions in this module is for the purpose of best practice. We include a Recommended property on most of the ones for this purpose. Those configurations that in the category of "should be set to X for best practice" are usually done via Test functions.
