### ISSUE TITLE
Add-DbaDbRoleMember

### ISSUE THREAD

**Issue by ddraillantclark** [sqlcollaborative/dbatools#5776]
### Summary of new feature

New command to add an existing Db User to a Database or Application Role of a Database.

For example, you have already created a user with this command:
`New-DbaDbUser -SqlInstance sqlserver2017 -Database DB1 -Username JohnSmith`
and you want to add him to db_owners with a command like this:
`Add-DbaDbRoleMember -SqlInstance sqlserver2017 -Database DB1 -Username JohnSmith -Role db_owner`

Current kludge/helper function using Invoke-DbaQuery is this:

```
function Add-DbaDbRoleMember {
    param(
        [String]$SqlInstance,
        [String]$Database,
        [String]$Username,
	[String]$Role
    )
    Invoke-DbaQuery -SqlInstance $SqlInstance -Database $Database "ALTER ROLE [$(Role)] ADD MEMBER [$($Username)]"
}
```

### Latest version of dbatools as of writing
 0.9.701

**Comment by potatoqualitee** [comment]
@ClaudioESSilva created this command! It will be publicly available on Thursday 💯

**Comment by ClaudioESSilva** [comment]
Just a quick note. It does not cover `Application Roles`...yet 😃 

That should be, maybe, another command. `Add-DbaDbApplicationRoleMember`.
We keep in touch!

**Comment by potatoqualitee** [comment]
thanks claudio, shall we reopen?

**Comment by ClaudioESSilva** [comment]
@ddraillantclark can you please open a new one just regarding the `Application Roles` feature?
Thank you!

**Comment by potatoqualitee** [comment]
ty 👍

**Comment by ddraillantclark** [comment]
Will do.  Thanks!
