### ISSUE TITLE
Timeout parameter for Copy-DbaDbTableData

### ISSUE THREAD

**Issue by ahmetrende** [sqlcollaborative/dbatools#5777]
Hi,

When using Copy-DbaDbTableData with -Query parameter and it takes long time (> 30 secs) it is timed out. -bulkCopyTimeOut cannot cover this issue.

We need query timeout like Invoke-dbaquery

**Comment by jpomfret** [comment]
Hey @ahmetrende - I tried to replicate this and couldn't using version '1.0.9'. Can you let me know the code you ran that you got an error?

I ran the following and moved 21million rows in 6.5 mins.
```
$params = @{
    SqlInstance = 'server1'
    Destination = 'server1'
    Database = 'database'
    DestinationDatabase = 'database'
    Table = '[dbo].[tablename]'
    Query = 'select * from database.dbo.tablename'
    DestinationTable = '[dbo].[tablename_Copy]'
    AutoCreateTable = $true
}
Copy-DbaDbTableData @params
```

**Comment by ahmetrende** [comment]
Hi @jpomfret , 
Thanks for comment. But;

If the query is complex and longer than 30 secs. It will be timed out for my examples.

I'll try again different methods. Thanks!

**Comment by jpomfret** [comment]
@ahmetrende - I didn't understand fully what you meant until I ran into the same situation. Thanks for reporting as it helped jog my memory.  I just created a PR for this, if you have a chance to test it that would be great.
Let me know if that solves your issue too.
Thanks!
