### ISSUE TITLE
Pester Tests for Developers

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5779]
- [x] Force function name to match filename
- [x] Tests.ps1 file exists per command
- [ ] Fail on `::new(` since it is not supported in PS3. But allow Certificates & aztoken because I'm not rewriting those yet.

More soon as I remember them.

**Comment by niphlod** [comment]
this is a breeze with the newest PSSA. Lemme see if the latest has still problems with formatting
