### ISSUE TITLE
Add duration to Agent Job

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#578]
Is this a *feature* OR *bug*:
https://trello.com/c/wpXLWtUJ

**Additional comments**
Again happy to rewrite using SMO wont take a mo https://github.com/SQLDBAWithABeard/Functions/blob/master/Get-SQLAgentJobDuration.ps1

**Comment by potatoqualitee** [comment]
@SQLDBAWithABeard - can you add this to Get-DbaAgentJob similar to what you're doing iwth Get-DbaDatabase?

**Comment by potatoqualitee** [comment]
Unless it's actually just `Find-DbaRunningJob`

**Comment by SQLDBAWithABeard** [comment]
Yes I can and no its not but I think I could add a switch to Get-DBAAgentJob for running jobs??

**Comment by potatoqualitee** [comment]
Find-DbaRunningJob exists and is awesome! I use it across our enterprise. You could employ it 👍

**Comment by wsmelton** [comment]
Duration should go with `Get-DbaAgentJobHistory` and it [already is as `RunDuration`](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaAgentJobHistory.ps1#L143)

**Comment by SQLDBAWithABeard** [comment]
Happy with that - should we close @potatoqualitee @wsmelton ?

**Comment by potatoqualitee** [comment]
oh cool! k closing thanks @wsmelton !

**Comment by MikeyBronowski** [comment]
Trying to get running jobs and duration. 

Below gives me the names, but there is not duration (as mentioned in this thread)
`Get-DbaRunningJob -SqlInstance $sqlserver `

That one has the duration, but seems like an overkill to get only running jobs (takes long time on busy instance and filtering does not really change that).
Get-DbaAgentJobHistory -SqlInstance $sqlserver -NoJobSteps -StartDate '2018-10-15'


The duration of actually running SQL Agent jobs can allow to catch some weird processes that didn't failed and are running longer than should.

I vote for that column in Get-DbaRunningJobs, unless there is an easy/fast way to do it with Get-DbaAgentJobHistory.
