### ISSUE TITLE
[Bug] Update-DbaInstance - Current SP version SQL2016SP2 is not the latest

### ISSUE THREAD

**Issue by garethnewman** [sqlcollaborative/dbatools#5803]
dbatools v1.0.4* updated
ps v5.1

When using Update-DbaInstance against SQL Server 2016 CU6

I got this warning:-
WARNING: [13:22:12][Get-SqlInstanceUpdate] Current SP version SQL2016SP2 is not the latest available. Make sure to upgade to latest SP level before applying latest CU.

The instance has 2016 SP2 CU6:-
Microsoft SQL Server 2016 (SP2-CU6) (KB4488536) - 13.0.5292.0

And CU7 in the share folder ready.

After installing CU7 manually and running Update-DbaInstance again I get a warning as expected when trying to use the command again:-
VERBOSE: [14:39:55][Get-SqlInstanceUpdate] 13.0.5337 on computer [ZZZZZZ] is already the latest available.

**Comment by garethnewman** [comment]
UPDATE:- tried a few other instances and get a similar message.
[Get-SqlInstanceUpdate] Current SP version SQL2014SP3 is not the latest available. Make sure to upgade to latest SP level before applying latest CU.
[Get-SqlInstanceUpdate] Current SP version SQL2016SP2 is not the latest available. Make sure to upgade to latest SP level before applying latest CU.

**Comment by GeorgePalacios** [comment]
I'll have a look - have a sneaky feeling the issue is more to do with Get-DbaBuildReference return values.

**Comment by garethnewman** [comment]
Thanks George!

**Comment by garethnewman** [comment]
Just testing some more, I ran Get-DbaBuildReference and it returns:-
Build          : 13.0.5292
NameLevel      : 2016
SPLevel        : SP2
CULevel        : CU6
KBLevel        : 4488536
BuildLevel     : 13.0.5292
SupportedUntil : 14/07/2026 00:00:00
MatchType      : Exact
Warning        :

but Update-DbaInstance returns warning:-

[Get-SqlInstanceUpdate] Current SP version SQL2016SP2 is not the latest available. Make sure to upgade to latest SP level before applying latest CU.

For this instance (when CU7 is available)

**Comment by garethnewman** [comment]
OK I found it and fixed it, but I am not sure why it stopped working.

basically this:-
if ($currentVersion.SPLevel -notcontains 'LATEST') 

I am not sure where 'LATEST' comes from at the moment. But if I compare currentSP to targetSP then that will be ok I think.

if ($currentVersion.SPLevel -ne $targetSP) 

I'll test and raise a PR if I wrap my head around the 'LATEST' thing.

**Comment by wsmelton** [comment]
The `SPLevel` is a property that comes from `Get-DbaBuildReference`

**Comment by niphlod** [comment]
Halt. We removed "latest" because test-dbabuild is the one carrying the
info already. Having it in get-dbabuildreference was redundant

Il mar 25 giu 2019, 14:41 Shawn Melton <notifications@github.com> ha
scritto:

**Comment by garethnewman** [comment]
are you happy with if ($currentVersion.SPLevel -ne $targetSP) @niphlod ?

**Comment by niphlod** [comment]
it's as good as you remember to update accordingly if test-dbabuild gets changed .... ^_^ I'd go for using test-dbabuild alltogether
