### ISSUE TITLE
Implement StrictMode

### ISSUE THREAD

**Issue by jayvdb** [sqlcollaborative/dbatools#5804]
I am surprised that dbatools codebase isnt using `Set-StrictMode` anywhere.

I think it would be helpful to surface errors in CI, and avoid bugs.

e.g. I can see that there are a few uses of `$psVersionTable.Platform`, which would cause errors on some versions of Powershell if `Set-StrictMode` is enabled because they do not have `.Platform`.  Granted the current usages of `$psVersionTable.Platform` are probably ok, or at least wont cause very bad failures.

**Comment by niphlod** [comment]
isn't checking with PSSA enough ?

**Comment by wsmelton** [comment]
We avoid most syntax and best practice bugs using Pester with PSSA. Setting strict mode has to much of an enforcing nature that would cause more pain than worth in troubleshooting. 

Majority of the bugs we have had reported over the years would not be solved by use of that command.

**Comment by wsmelton** [comment]
Appreciate the feedback but use of strict mode is not going to be implemented in this project

**Comment by jayvdb** [comment]
I believe it would have caught https://github.com/sqlcollaborative/dbatools/issues/5800
