### ISSUE TITLE
[Bug] Add-DbaAgDatabase "Could not connect to instance"

### ISSUE THREAD

**Issue by JohnCasSQL** [sqlcollaborative/dbatools#5808]
### Environmental information

```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Version : 1.0.4
```

#### SQL Server: 
```
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64) 
	Sep  7 2018 01:37:51 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )
```

## Report

Things to consider:
- Errors received are not related to permissions?
Dont believe so.  I see activity on the secondary under my sa login. 

- Have you tried the same command using powershell.exe instead of a hosted powershell instance like ISE or VS Code?

I am using the powershell under the admin command line .
I have run:
```
Get-dbaAgDatabase -SQLInstance <secondary\Instance> 
Get-dbaAgDatabase -SQLInstance <primary\Instance> 
Copy-dbaDatabase
```
These works with no issue.

- If this refers to Copy-DbaDatabase can you replace the problem with Backup-DbaDatabase and Restore-DbaDatabase?

I have tested the Backup-dbaDatabase from the primary and Restore-dbaDatabase to the secondary and both those commands work ok.

- Copy-DbaDatabase will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

copy-database does work.

#### Host used

- [x] powershell.exe

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Errors Received

I have taken out our servername\instance details.  These are correctly pointing to the secondary server:
```
Could not connect to instance <secondary\instance>
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:79716 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Add-DbaAgDatabase
```
#### Steps to Reproduce
```
$mycred=Get-Credential

PS M:\> Add-DbaAgDatabase -sqlinstance <primary\instance> -AvailabilityGroup AG-SITE09-01 -database Test -secondary <secondary\instance> -SharedPath \\<secondary>\AGSync_SITE09 -whatif -SecondarySqlCredential $Mycred -SqlCredential $Mycred -EnableException
```
#### Expected Behavior

without the -whatif:
Would expect to validate both sides, backup database  & log to shared folder, restore backup & log to secondary, add to AG.  

What did you expect to happen?
That the database would be backed up, restored to secondary and added to the AG.

#### Actual Behavior

Without the -what if, the database was added to the AG but the backup and restore did not happen.

I did capture the activity in SQL on the secondary and I did see it connect and run SQL  sucessfully.  All statements are sucessfull. 

For some reason from that point I get the error message that it cannot connect.  Can't easily see why it would get this message.

When the same details are used in the SSMS GUI there are no issues.

**Comment by wsmelton** [comment]
There does not appear to be any information provided in this issue.

If the requested information can be provided we can look more into the problem.

**Comment by JohnCasSQL** [comment]
please... I was editing it!

**Comment by GeorgePalacios** [comment]
I'll have a look at this

**Comment by GeorgePalacios** [comment]
@JohnCasSQL  I think I may have found the problem - $SQLCredential is being used to try to connect to the secondary rather than $SecondarySQLCredential - could you run the command with -verbose and post the output so I can confirm that's your problem please?

**Comment by JohnCasSQL** [comment]
Here is the $error

 $Error
Could not connect to instance <server\instance>
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:79716 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Add-DbaAgDatabase

Import-Module : Could not load file or assembly 'Microsoft.SqlServer.Replication.dll' or one of its dependencies. The
specified module could not be found.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\internal\scripts\smoLibraryImport.ps1:129 char:13
+             Import-Module $assemblyPath
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by GeorgePalacios** [comment]
@JohnCasSQL could you check your SQL Error log for the secondary server? You should see a login failure when you ran the command.

**Comment by JohnCasSQL** [comment]
Hi George, in actualy fact I do not - and I did look :), that is what led me to use the Credentials.  We have the same domain, the credential is valid at both servers.   I run profiler (dont shoot me) - I can actually see it connect on the secondary and see t-sql coming through - then the error.

**Comment by potatoqualitee** [comment]
Thank you @GeorgePalacios - I did try on my docker instance but both use the same u/p. And the hostname would probably work too.

@JohnCasSQL - can you please do `$error[1]` and so on up to 10 or whatever until you get the error that gives more detail about `Could not connect to instance`?

**Comment by JohnCasSQL** [comment]
@potatoqualitee 
@GeorgePalacios 

PS M:\> $error[1] | select *


writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: Could not connect to instance ICU-SQCBK7A001\ICU_SITE09
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Add-DbaAgDatabase,Stop-Function
ErrorDetails          : Could not connect to instance <secondary>\<instance>
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line
                        79724
                        at Add-DbaAgDatabase<Process>, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 93
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

**Comment by GeorgePalacios** [comment]
@JohnCasSQL why are you passing in a SecondaryCredential if it's a domain account that has access to both out of interest?

**Comment by JohnCasSQL** [comment]
At the start I was passing no credentials.   Then I got the error, so tried the primary for the credential, same error, then the seocndary for the credential, same error.

I just tried now withouth the 2nd credential - the error is tha same as above.   

SInce it does appear as though it is connecteing (accorrding to the SQL trace), I am wondering if the error about the not being able to connect to the 2nd instance is not quite truthful?

**Comment by JohnCasSQL** [comment]
![image](https://user-images.githubusercontent.com/52141986/60004104-515cf300-96af-11e9-8f36-b7982800157b.png)

**Comment by GeorgePalacios** [comment]
@JohnCasSQL  thanks a lot. We think we've found the problem.

**Comment by JohnCasSQL** [comment]
@GeorgePalacios I will test :)

**Comment by JohnCasSQL** [comment]
all working!  Thanks!
