### ISSUE TITLE
Backup/Restore: Encryption Stuff 

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#581]
Is this a *feature* OR *bug*:
https://trello.com/c/a10DqwHK

**Additional comments**
Simplify, with a couple commands, the process found here:

https://blogs.msdn.microsoft.com/mvpawardprogram/2014/06/02/sql-server-2014-backup-encryption/

But for all versions. So use SMO: https://msdn.microsoft.com/en-us/library/ms162206.aspx

[encryptionstuff.txt](https://github.com/sqlcollaborative/dbatools/files/715380/encryptionstuff.txt)

**Comment by potatoqualitee** [comment]
Some of this done, but we still need a way to restore encrypted backups easily / cc @Stuart-Moore

**Comment by Digger937** [comment]
I would also like to request adding backup encryption, at the very least being able to backup and encrypt a database.
