### ISSUE TITLE
Watch-DbaToolsUpdate references Install-DbaWatchUpdate instead of Install-DbatoolsWatchUpdate

### ISSUE THREAD

**Issue by garyhampson** [sqlcollaborative/dbatools#5813]
### Environmental information

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.4\dbatools.psd1
Version : 1.0.4

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [X] powershell.exe
- [X] ISE
- [X] VS Code
- [X] Other (Azure Data Studio)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

PS D:\Code\dbatoolkit\Scripts> Watch-DbatoolsUpdate
Install-DbaWatchUpdate : The term 'Install-DbaWatchUpdate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.4\allcommands.ps1:70629 char:13
+             Install-DbaWatchUpdate
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-DbaWatchUpdate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Could not compare "1.0.5" to "0.10.0.71 1.0.4". Error: "Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Version"."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.4\allcommands.ps1:70643 char:13
+         if ($galleryVersion -le $localVersion) { return }
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : ComparisonFailure
 
PS D:\Code\dbatoolkit\Scripts> GET-MODULE DBATOOLS

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.4      dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}

**Comment by potatoqualitee** [comment]
thanks for the detailed info and provided solution @garyhampson !
