### ISSUE TITLE
Get-DBADBSPACE  returns different data size values.

### ISSUE THREAD

**Issue by MarkMathiesen** [sqlcollaborative/dbatools#5816]
Function returns different size types for the the same field.  IE. one record may return in MB whereas the another returns in GB or KB.  This is inconsistent and requires more coding to accommodate the varying degrees of size.

**Comment by potatoqualitee** [comment]
Hey Mark. Sorry, we really need to blog about this (any takers?) We use a really cool data type that shows pretty human readable values, but when expanded, can give you nearly every usable value. Check it out

`Get-DbaDbSpace -SqlInstance sql2017 -Database master | Select -First 1 | Select -ExpandProperty UsedSpace`

![image](https://user-images.githubusercontent.com/8278033/60076371-accac780-9727-11e9-8f4d-245050e6f3e3.png)
