### ISSUE TITLE
Invoke-DbaDBPiiScan misses some fields in scan.

### ISSUE THREAD

**Issue by DBATergooi** [sqlcollaborative/dbatools#5818]
Powershell version:
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

DBA Tools version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.4\dbatools.psd1
Version : 1.0.4

#### SQL Server: 
Microsoft SQL Server 2016 (SP2-CU7) (KB4495256) - 13.0.5337.0 (X64)   May 16 2019 02:24:21   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

None, the command processes fine. However, it misses some fields in the scan for PII.

#### Expected Behavior

I expected it to find fields which contain personal identifiable information.

#### Actual Behavior

It skipped a number of fields which, based on the field name, i would have expected to be included.

I tried the command Invoke-DbaDBPiiScan on a Romexis test database. For the table RRM_Person, which contains all the patiend data, the following columns contain PII:

   - title
   - first_name
   - second_name
   - third_name
   - last_name
   - maiden_name
   - nickname
   - name_suffix
   - date_of_birth
   - date_of_death
   - gender
   - marital_status
   - nationality
   - occupation

However, when i study the output of the command, all i get are the following columns:

   - history_id (identified as zipcode)
   - external_id (identified as social security number)
   - other_id ( same as above)
   - updated_time (same as above)

It completely missed all PII for this table. I suspect an update in the patterns for fieldnames will fix the issue.

Regards,
M. Diehl
DBA Tergooi Ziekenhuis
dbadmin@tergooi.nl
Netherlands

**Comment by DBATergooi** [comment]
Just tried the same on a different Database (RVC Clinical Assistant), and again it misses the Name in tables with Pii in it, like patients tables, tables containing Pii about Doctors. When it does pick up a field named Name, it identifies it as a zip-code, probably based on the contents of the field.

Regards,
M. Diehl
DBA Tergooi Ziekenhuis

**Comment by sanderstad** [comment]
Because the names are not part of the know name patterns it starts to look at the content and indeed defines it as a zipcode because the ID probably looks like an US zipcode.

In added the names to the patterns in the mean time. That's not yet in production yet and needs to be tested.
