### ISSUE TITLE
Set-DbaTcpPort

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#583]
Is this a *feature* OR *bug*:
https://trello.com/c/Ibsh1cpe

**Additional comments**

[Set TCP (dynamic or static) for a SQL Server instance](http://blog.dbi-services.com/sql-server-2012-configuring-your-tcp-port-via-powershell). When using KERBEROS connections, this must me done before setting SPNs.

Last commit was "totally breaks stuff. incomplete. will return to it later." with the attached Set-DbaTcpPort. Gonna delete that branch - it's been 3 months since I attempted this command. Anyone else is free to take it on.

If you do, look into Invoke-ManagedComputerCommand in the internal folder. that helps with SQLWMI. Just sent a Scriptblock to it.

[Set-DbaTcpPort.ps1.txt](https://github.com/sqlcollaborative/dbatools/files/715382/Set-DbaTcpPort.ps1.txt)

**Comment by potatoqualitee** [comment]
done a rama :D
