### ISSUE TITLE
Importing dbatools module into Azure Automation Account

### ISSUE THREAD

**Issue by GrzegorzOpara** [sqlcollaborative/dbatools#5835]
Has anyone managed to import dbatools module into Azure Automation Account? I tried to do it in several ways, but every time the installation fails:

- different versions checked from 1.0.0 to the latest 1.0.9
- from portal using Automation Accounts -> Automation modules -> Browse Gallery
- from portal using Automation Accounts -> Automation modules -> import from file

Every time I got:

> Error importing the module dbatools. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.

As you can see the error message doesn't tell much (and obviously I am able to import it locally), thus I wonder if anyone managed to go over it somehow.

**Comment by wsmelton** [comment]
What region is your Automation Account in @GrzegorzOpara

**Comment by wsmelton** [comment]
Azure Automation in the process of importing the module to your account will validate the module in the Azure Sandbox environment. Let me see if I can pull the details of that and verify if anything changed.

**Comment by wsmelton** [comment]
Reference data, seems Azure Sandbox is now on Windows 10 build with PowerShell 5.1

```
--------------------------------
$PSVersionTable

Name                           Value                                                                                    
----                           -----                                                                                    
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1                                                                                  



.NET Framework       Product             Version                         Release PSComputerName      WindowsVersion     
--------------       -------             -------                         ------- --------------      --------------     
Client                                   4.7.03056                        461808 CLIENT              6.2.9200.0         
Full                                     4.7.03056                        461808 CLIENT              6.2.9200.0         
Client                                   4.0.0.0                                 CLIENT              6.2.9200.0         
```

**Comment by wsmelton** [comment]
Ok so it seems we do have an issue with the module changes. I've been able to successfully import 0.9.828 but importing 1.0.0 or higher breaks and will not import; no matter what region I use for the account.

I'll have to check with Microsoft on this to figure out what is going on. Our module is properly setup and written with regards to the manifest.

**Comment by GrzegorzOpara** [comment]
@wsmelton thanks a ton for the prompt reply!

I am using West Europe region and I confirm that version 0.9.828 works like a harm!

**Comment by wsmelton** [comment]
This is still broke even after @potatoqualitee removed some troublesome DLLs. I'm still waiting on response from team at Microsoft.

**Comment by potatoqualitee** [comment]
Noooooooooo 💔

**Comment by wsmelton** [comment]
Yep, not sure if no response is coming from they are involved with Inspire event this week or not. I'm seeing if I can backdoor some stuff to get more verbose output from the Azure Sandbox, see if it will tell me why it won't validate it properly.
