### ISSUE TITLE
azure function idea for dbatools

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5839]
![image](https://user-images.githubusercontent.com/8278033/60352818-f6860d00-99c8-11e9-917a-e596a04e9425.png)

perhaps some commit detector on changelog.md

**Comment by andreasjordan** [comment]
As changelog is not used anymore - shall we close?

**Comment by potatoqualitee** [comment]
I think this is a good idea for GitHub actions. I'd like to explore when I have time/motivation.

**Comment by potatoqualitee** [comment]
sweet, check it out https://github.com/sqlcollaborative/dbatools/releases.atom i'll ping @wsuhoey

**Comment by wsuhoey** [comment]
OOOOOoooooOOOOOOooooOOOooo :D
