### ISSUE TITLE
[Bug] Export-DbaUser is enumerating and displaying the current directory contents

### ISSUE THREAD

**Issue by haroldnorton** [sqlcollaborative/dbatools#5840]
When running the cmdlet, whatever folder is the current directory, the contents are being dumped to the host screen at the end.

**Comment by sqllensman** [comment]
The code has following statement at end of function

Get-ChildItem -Path $script:pathcollection.Path

This does not seem correct.
Should be using
Get-ChildItem -Path $FilePath and only calling this if $Passthru is not specified
