### ISSUE TITLE
Get-DbaErrorLogin listed on commands page but apparently does not exist

### ISSUE THREAD

**Issue by SQLGB** [sqlcollaborative/dbatools#5844]
### Environmental information
PSVersion                      5.1.14409.1018                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                
BuildVersion                   10.0.14409.1018                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                                                

### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.11\dbatools.psd1
Version : 1.0.11

1033             en-US            English (United States)     

#### SQL Server: 

Microsoft SQL Server 2016 (SP2-CU2-GDR) (KB4458621) - 13.0.5201.2 (X64)   Aug 18 2018 07:38:15   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 

us_english

#### Host used

- [ ] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Steps to Reproduce
Browse https://dbatools.io/commands/ find Get-DbaErrorLogin and click on it, or run "get-command Get-DbaErrorLogin" in PowerShell.

#### Expected Behavior
Help page or summary for valid command.

#### Actual Behavior
404 Function not found (web) and "get-command : The term 'Get-DbaErrorLogin' is not recognized as the name of a cmdlet..." in PowerShell.  Suspect this is a result of a find/replace operation gone wrong (command name very similar to "Get-DbaErrorLog".

**Comment by potatoqualitee** [comment]
indeed that is true, thank you. i have updated the page 💯

**Comment by SQLGB** [comment]
@potatoqualitee FYI, same issue for these 8 commands:

Test-DbaDbDataGeneratorConfiguration
Get-DbaInstanceRole
New-DbaInstanceRole
Remove-DbaInstanceRole
Select-DbaObject
Get-DbaInstanceRoleMember
Find-DbaUnusedIndex
Set-DbatoolsConfig

**Comment by SQLGB** [comment]
Minor correction - these two are apparently found via get-command, but the online help pages don't exist...

Select-DbaObject
Set-DbatoolsConfig

**Comment by potatoqualitee** [comment]
Thanks so very much, @SQLGB I am unsure how I'm going to get the cmdlet help into there. @niphlod can you offer any suggestions? It exists in Get-Help, can we smash it into the json? @ClaudioESSilva would you be able to take a look at the webpage?

**Comment by potatoqualitee** [comment]
ping @niphlod

**Comment by niphlod** [comment]
Assign this to me, I'll take a look ASAP

Il mar 9 lug 2019, 11:27 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
thanks niph!

**Comment by niphlod** [comment]
Keep this up bot

Il dom 8 set 2019, 13:00 stale[bot] <notifications@github.com> ha scritto:
