### ISSUE TITLE
[Bug] Import-DbaCsv Imports header row by default

### ISSUE THREAD

**Issue by Nullh** [sqlcollaborative/dbatools#5853]
#### PowerShell version:

```
Name                           Value                                                                                     
----                           -----                                                                                     
PSVersion                      5.1.16299.967                                                                             
PSEdition                      Desktop                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                   
BuildVersion                   10.0.16299.967                                                                            
CLRVersion                     4.0.30319.42000                                                                           
WSManStackVersion              3.0                                                                                       
PSRemotingProtocolVersion      2.3                                                                                       
SerializationVersion           1.1.0.1        
                                                                           
```

#### dbatools Module version:

```

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.12\dbatools.psd1
Version : 1.0.12

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.0\dbatools.psd1
Version : 1.0.0

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.834\dbatools.psd1
Version : 0.9.834

```

#### SQL Server: 
```sql
Microsoft SQL Server 2019 (CTP3.1) - 15.0.1700.37 (X64)   Jun 19 2019 12:44:55   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS) <X64>
-- Also
Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64)   Sep 14 2018 13:53:44   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)
```

### Report

Import-DbaCsv imports the first row of data, even if it's header data. 

The help for the -NoHeaderRow flag specifies it should use the first row of the import file as a header row by default, but behaviour is the same if this flag is specified or not.

The same behaviour happens if you use the -AutoCreateTable flag or of importing into an existing table with or without data.

#### Host used

- [x] powershell.exe
- [x] ISE
- [x] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Errors Received

No error message thrown.

#### Steps to Reproduce

1. Create an empty database called 'test'
2. Generate test data **with a header row**. Example provided in **Test Data csv contents**
3. Save credentials to the db server if necessary using Get-Credential
3. Call the following command `Import-DbaCsv -Path .\<testdata>.csv -SqlInstance <sql instance> -SqlCredential <credential> -Database test -Table newdata -Schema dbo -AutoCreateTable`

#### Expected Behavior

Output should be:

ComputerName  : localhost
InstanceName  : MSSQLSERVER
SqlInstance   : 3d2bce194210
Database      : test
Table         : newdata
Schema        : dbo
RowsCopied    : 4
Elapsed       : 120.54 ms
RowsPerSecond : 8336
Path          : C:\...\MOCK_DATA.csv

Table test.dbo.newdata should contain the 1000 data rows and not import the header row.

|id	|first_name	|last_name	|email	|gender	|ip_address|
|---   |---                  |---                   | ---          |---           |---            |
|1	|Kerk	|Colerick	|kcolerick0@miitbeian.gov.cn	|Male	|114.236.181.132|
|2	|Roma	|Corse	|rcorse1@newyorker.com	|Male	|123.90.174.61|
|3	|Bari	        |Callaby	|bcallaby2@geocities.com	|Female	|113.32.169.45|
|4	|Napoleon	|Belfelt	|nbelfelt3@answers.com	|Male	|43.219.160.11|

#### Actual Behavior

ComputerName  : localhost
InstanceName  : MSSQLSERVER
SqlInstance   : 3d2bce194210
Database      : test
Table         : newdata
Schema        : dbo
RowsCopied    : 5
Elapsed       : 120.54 ms
RowsPerSecond : 8336
Path          : C:\...\MOCK_DATA.csv

The header row is also imported

|id	|first_name	|last_name	|email	|gender	|ip_address|
|---   |---                  |---                   | ---          |---           |---            |
|id	|first_name	|last_name	|email	|gender	|ip_address|
|1	|Kerk	|Colerick	|kcolerick0@miitbeian.gov.cn	|Male	|114.236.181.132|
|2	|Roma	|Corse	|rcorse1@newyorker.com	|Male	|123.90.174.61|
|3	|Bari	        |Callaby	|bcallaby2@geocities.com	|Female	|113.32.169.45|
|4	|Napoleon	|Belfelt	|nbelfelt3@answers.com	|Male	|43.219.160.11|

#### Test Data csv contents

Generated with [Mockaroo](https://mockaroo.com/)

```
id,first_name,last_name,email,gender,ip_address
1,Kerk,Colerick,kcolerick0@miitbeian.gov.cn,Male,114.236.181.132
2,Roma,Corse,rcorse1@newyorker.com,Male,123.90.174.61
3,Bari,Callaby,bcallaby2@geocities.com,Female,113.32.169.45
4,Napoleon,Belfelt,nbelfelt3@answers.com,Male,43.219.160.11
```

**Comment by Nullh** [comment]
I guess the root problem is that I have no way of importing a csv file with column headers without also importing the headers.

**Comment by Nullh** [comment]
Looks like there's not been any changes to LumenWorks.Framework.IO 4, so guessing it's not that. 
Logic around populating $FirstRowHeader looks fine too!

Thought I'd test this and it look like the -Delimiter parm isn't working right either. If I switch commas to semicolons in my test file and set the delimiter to ';' everything comes in as a single column. I'm guessing the parameters being added to $PSBoundParameters aren't being passed to LumenWorks.Framework.IO.Csv.CsvReader but I'm not sure how to resolve that  😓

**Comment by rliebau** [comment]
I am experiencing the same issue on 1.0.12. I upgraded directly from 0.9.834. This function was working properly on 0.9.834.

**Comment by Nullh** [comment]
For ref looking like commit [8d237c659eaf56acb06f4052690cf9e679d1593b](https://github.com/sqlcollaborative/dbatools/commit/8d237c659eaf56acb06f4052690cf9e679d1593b#diff-99eb8e9a00ab259773527d850773db43) might be the change that's causing the problem.

**Comment by Nullh** [comment]
Just realised I’m an idiot that can’t read Powershell! xD
Looks like the properties added to the $reader object aren’t being passed to the Csvreader constructor. Having a crack at making that work!

**Comment by Nullh** [comment]
For some reason any constructor in CsvReader that used encoding didn't seem to work! 
Rather than have a go at fixing LumenWorks.Framework.IO.Csv.CsvReader I've moved encoding to the creation of the System.IO.StreamReader object, which seems to solve the encoding problem. Then I could just pass our vars to the CsvReader constructor and was able to run imports with a combination of vars properly.

**Comment by Nullh** [comment]
Pulled the latest update and the header row is now only imported if I use the -NoHearRow arg. Also fixed the problem with the delimiter arg not being recognised, so closing.
