### ISSUE TITLE
New-DbaAvailabilityGroup - add option to force IPs in endpoint urls

### ISSUE THREAD

**Issue by dylan-azucena** [sqlcollaborative/dbatools#5859]
### Summary of new feature

Currently, `New-DbaAvailabilityGroup` will create replicas in an availability group with host names instead of IP addresses, even if IP addresses are supplied as `-Primary` and `-Secondary`. Using IP addresses is desirable in cases where you don't want to rely on dns or hostname consistency. 

### Proposed technical details (if applicable)

T-SQL allows creating an availability group with replicas that have IPs as endpoint_url, e.g.:
``` SQL
create availability group AG_Lab
    with (
        cluster_type = none
    )

    for replica on N'primary' with (
        endpoint_url = N'tcp://10.x.x.x:5022',
        availability_mode = asynchronous_commit,
        seeding_mode = automatic,
        failover_mode = manual
    )
go
alter availability group AG_Lab add replica
on N'secondary' with (
	endpoint_url = N'TCP://10.x.x.x:5022',
	availability_mode = asynchronous_commit,
	seeding_mode = automatic,
	failover_mode = manual
)
go
```
It would be nice if a flag in `New-DbaAvailabilityGroup` could determine whether to use supplied IP's rather than hostnames.

### Latest version of dbatools as of writing

1.0.12

**Comment by andreasjordan** [comment]
Just worked on that topic today: #6802
