### ISSUE TITLE
Rename-DbaDatabase -FileName -Preview incorrectly renames files with -preview

### ISSUE THREAD

**Issue by Doessing** [sqlcollaborative/dbatools#5861]
-Preview
Shows the renames without performing any operation (recommended to find your way around this function parameters ;-) )

I ran this command:
Get-DbaDatabase -SqlInstance Sql2017 -Database MDG | Rename-DbaDatabase -DatabaseName "<DBN>-backup" -FileName "<FNN>-backup" -Move -Preview | Select-Object *

After fidling around with the correct settings - running the command multiple times always with the -Preview parameter set, i now have a database file named "MDG_log-backup-backup-backup-backup-backup"
only the log file has gotten this weird name. The database files are all just MDG_Data-backup

One this, i only notices this after running the final change without -preview.

**Comment by niphlod** [comment]
can you consistently reproduce ?
looking at the code there's `if (!$Preview) {` in all the right places...
BTW: "I now have a datatabase file named ......" >> you have the physical name of the file changed or the logical file name ?
