### ISSUE TITLE
Build ref

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5864]
do we not support hotfixes and if not, can we?

it's messing with my sexy new command 😅

![image](https://user-images.githubusercontent.com/8278033/60717184-73f9d200-9f21-11e9-9774-d606719f228e.png)

**Comment by wsmelton** [comment]
I'm not sure I follow. If you are referring to 4494351 not being in the build file it is because no one has added it.

**Comment by potatoqualitee** [comment]
oh, i did not see hotfixes on /builds so figured hotfixes were not a part of the setup

**Comment by niphlod** [comment]
We do have hotfixes, they're the ones not marked as rtm or SP or CU

Il ven 5 lug 2019, 12:59 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
ah kk ty!
