### ISSUE TITLE
[Bug] Get-DbaSchemaChangeHistory fails in instances with case-sensitive collations

### ISSUE THREAD

**Issue by jaredfaulkner** [sqlcollaborative/dbatools#5875]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                       
----                           -----                                                                                                       
PSVersion                      5.1.18362.145                                                                                               
PSEdition                      Desktop                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.18362.145}                                                                    
BuildVersion                   10.0.18362.145                                                                                              
CLRVersion                     4.0.30319.42000                                                                                             
WSManStackVersion              3.0                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                         
SerializationVersion           1.1.0.1                                                                                                     

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.15\dbatools.psd1
Version : 1.0.15

```

#### SQL Server: 
```sql
Microsoft SQL Server 2014 (SP3-CU3) (KB4491539) - 12.0.6259.0 (X64)   Apr  1 2019 22:19:54   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```
#### Host used

- [x ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "Query" with "1" argument(s): "Exception 
                        calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'tempdb'. "" ---> 
                        System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults" with "1" 
                        argument(s): "Execute with results failed for Database 'tempdb'. " ---> 
                        Microsoft.SqlServer.Management.Smo.FailedOperationException: Execute with results failed for Database 'tempdb'.  
                        ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a 
                        Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: Invalid column name 'objecttype'.
                        Invalid column name 'databasename'.
                        Invalid column name 'starttime'.
                        Invalid column name 'Sessionloginname'.
                        Invalid column name 'NTusername'.
                        Invalid column name 'applicationname'.
                        Invalid column name 'eventclass'.
                        Invalid column name 'eventclass'.
                        Invalid column name 'eventclass'.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object 
                        execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(StringCollection sqlCommands)
                           at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteWithResults(StringCollection query)
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteWithResults(StringCollection sqlCommands)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteWithResults(StringCollection sqlCommands)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, 
                        Exception exception)
                           at <ScriptBlock>(Closure , FunctionContext )
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, 
                        Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior 
                        errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo 
                        invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                           at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action 
                        action)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior 
                        errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo 
                        invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, 
                        Object[] args)
                           at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior 
                        errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
                           at System.Management.Automation.PSScriptMethod.InvokeScript(String methodName, ScriptBlock script, Object this, 
                        Object[] arguments)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.PSScriptMethod.InvokeScript(String methodName, ScriptBlock script, Object this, 
                        Object[] arguments)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ScriptMethodRuntimeException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaSchemaChangeHistory<Process>, C:\Program 
                        Files\WindowsPowerShell\Modules\dbatools\1.0.15\allcommands.ps1: line 31947
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```



#### Steps to Reproduce

The query in the text for the cmdlet does not use the case sensitive column names for the cross-applied trace file columns, causing the cmdlet to fail when run on case-sensitive collations (such as Latin1_General_BIN).

#### Expected Behavior


#### Actual Behavior

**Comment by jaredfaulkner** [comment]
The following case-sensitive version of the query in $Sql resolves the issue for me:
```sql
SELECT  SERVERPROPERTY('MachineName') ComputerName
      , ISNULL(SERVERPROPERTY('InstanceName'), 'MSSQLSERVER') InstanceName
      , SERVERPROPERTY('ServerName') SqlInstance
      , tt.DatabaseName DatabaseName
      , tt.StartTime DateModified
      , tt.SessionLoginName LoginName
      , tt.NTUserName UserName
      , tt.ApplicationName ApplicationName
      , CASE tt.EventClass
             WHEN '46' THEN 'Create'
             WHEN '47' THEN 'Drop'
             WHEN '164' THEN 'Alter'
        END DDLOperation
      , s.name + '.' + o.name Object
      , o.type_desc ObjectType
FROM    sys.objects o
        INNER JOIN sys.schemas s ON
            s.schema_id = o.schema_id
        CROSS APPLY (
    SELECT  *
    FROM    ::fn_trace_gettable('$($TraceFile.path)',default)
    WHERE   ObjectID = o.object_id
) tt
WHERE   tt.ObjectType NOT IN ( 21587 )
        AND tt.DatabaseID = DB_ID()
        AND tt.EventSubClass = 0;
```

**Comment by potatoqualitee** [comment]
hayle yeah, thank you for the solution, jared! are you interested in submitting the Pull Request, perchance?
