### ISSUE TITLE
Copy-DbaDatabase Add Destination Folder Parameter

### ISSUE THREAD

**Issue by imyourdba** [sqlcollaborative/dbatools#5888]
### Summary of new feature

I was using Copy-DbaDatabase recently and needed to restore to a different drive letter than was the default in the instance configuration.  I ended up using the command, then detaching the database, moving the files and then reattaching.  It would be nice to have a parameter to allow us to provide the restore path to be used.

### Proposed technical details (if applicable)

It would be the equivalent of the "MOVE N'logicalName' TO N'F:\MSSQL\Blah.mdf'" where the folder section would be the input of the parameter.

**Comment by wsmelton** [comment]
For advanced restores where you need to modify how a given database is restored we recommend using `Backup-DbaDatabase` and `Restore-DbaDatabase` in place of the Copy command. The Restore command supports providing a file mapping hashtable for custom locations for data and log files (aka the move clause).

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
