### ISSUE TITLE
[Bug] Grant-DbaAgPermission doesn't perform GRANT

### ISSUE THREAD

**Issue by JanK-Orb** [sqlcollaborative/dbatools#5889]
### Environmental information

```powershell
#### PowerShell version

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.17763.503                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.17763.503                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1 

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.9\dbatools.psd1
Version : 1.0.9
```

#### SQL Server: 

```sql
Microsoft SQL Server 2017 (RTM-CU15) (KB4498951) - 14.0.3162.1 (X64)   May 15 2019 19:14:30   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) 
```

### Report
A bug: 
line 114 :     if ($perm -contains "CreateAnyDatabase") {     
At this point $perm is undefined, parameter should be named $Permission

Could also consider changing the ALTER statement by wrapping the $ag parameter with [] to allow non-alphanumeric characters in AG names.
ALTER AVAILABILITY GROUP [$ag] GRANT CREATE ANY DATABASE

#### Host used

- [ ] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ x] Still buggy in powershell.exe

#### Errors Received
Actually, a lack of error is one way to observe the issue.  (Though the command does not currently execute the Grant at all as it exits the if at line 114)

#### Steps to Reproduce
Execute  Grant-DbaAgPermission with a -SqlInstance that doesn't exist.

Grant-DbaAgPermission -SqlInstance foo -Type AvailabilityGroup -AvailabilityGroup myAg -Permission CreateAnyDatabase 

Also, executing the command with a real  -SqlInstance doesn't actually execute the GRANT

#### Expected Behavior
When executing with a wrong -SqlInstance , an error message :  "Error occurred while establishing connection to ..."

When executing with a correct -SqlInstance, a GRANT is executed.

#### Actual Behavior
GRANT isn't executed with a correct SqlInstance 
No error when wrong SqlInstance is specified

**Comment by JanK-Orb** [comment]
Please note that once this issue is fixed, we'll no longer enter our `elseif ($Login)`  at line 129, and we'll not populate `$InputObject` with the list of accounts passed in. That means the entire section starting at line 144, `foreach ($account in $InputObject) {` will no longer execute.

**Comment by potatoqualitee** [comment]
Thanks for the report, @JanK-Orb ! Any chance you would be able to fix this issue? I will not have time until at least next week.

**Comment by LowlyDBA** [comment]
_shakes fist at stale bot_

This is very much still a bug :( 

I'm happy to make the quick-fix. 

Would ya'll like/need additional tests around this? If so, I may not have the bandwidth to go that deep for a few weeks.
