### ISSUE TITLE
Help community write a persuasive paper for recalcitrant potential adopters 

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5899]
> List out all of the @psdbatools tweets where people say they have saved hours of time using your modules as references in the docs, you will have a whole fleet of 👍

**Comment by wsmelton** [comment]
This seems like an Microsoft Flow thing that could be done....or some AI stuff: dbatools.cool (like the powershell.cool Beard did).

**Comment by potatoqualitee** [comment]
haha! that'd be awesome

https://twitter.com/i/web/status/1150911040076443648

> dbatools is recommended in the Microsoft Press title Microsoft SQL Server 2017 Administration Inside Out. A Microsoft employee wrote the foreword. It is recommended once again in the upcoming Microsoft Press title Microsoft SQL Server 2019 Administration Inside Out.

Need to add that and Snover's quote to /secure
https://github.com/sqlcollaborative/dbatools/issues/5897

**Comment by potatoqualitee** [comment]
https://twitter.com/SirWill/status/1150918379579985922

**Comment by potatoqualitee** [comment]
haha what, no
