### ISSUE TITLE
Copy-SqlDatabase - Missing "-Database" parameter?

### ISSUE THREAD

**Issue by strictmachine0** [sqlcollaborative/dbatools#590]
Is this a *feature* OR *bug*:
Bug? Not sure if this is different in the newest version or if I'm doing something wrong.
- Powershell Version: 4.0
- OS Version:  Windows Server 2012 R2

**Steps to Reproduce**
`Copy-SqlDatabase -Source sqlserver2008 -Destination sqlserver2014 -Database AdventureWorks -BackupRestore -NetworkShare //server/share`

**Action Results**
Here's the error output after running that command:

`Get-ParamSqlDatabases : A parameter cannot be found that matches parameter name 'NoSystem'.`
`At C:\temp\dbatools\dbatools-master\functions\Copy-SqlDatabase.ps1:176 char:116`
`+ ... eSqlCredential -NoSystem } }`
    `+ CategoryInfo          : InvalidArgument: (:) [Get-ParamSqlDatabases], ParameterBindingException`
    `+ FullyQualifiedErrorId : NamedParameterNotFound,Get-ParamSqlDatabases`

`Copy-SqlDatabase : A parameter cannot be found that matches parameter name 'database'.`
`At line:1 char:67`
`+ Copy-SqlDatabase -Source sqlserver2008 -Destination sqlserver2014 -database Adve ...`
    `+ CategoryInfo          : InvalidArgument: (:) [Copy-SqlDatabase], ParameterBindingException`
    `+ FullyQualifiedErrorId : NamedParameterNotFound,Copy-SqlDatabase`

**Expected Results**
Copy the database specified with -database

**Additional comments**
In the help for Copy-SqlDatabase I don't see the -Database parameter anymore but I see that it's still listed in one of the examples.

**Comment by SirCaptainMitch** [comment]
Have you tried -Databases?

**Comment by strictmachine0** [comment]
Yes, I tried -Databases as well and got the same error.

**Comment by niphlod** [comment]
@strictmachine0 : can you please confirm the version of your installed dbatools ? it seems that you have two conflicting releases (old ones have an internal function that does NOT have -Nosystem as a parameter and the copy-sqldatabase you call is newer and includes it)

**Comment by strictmachine0** [comment]
You are correct.  I cleared out dbatools and reinstalled and now it works as expected with the -Database parameter.  Thank you.

The -Database parameter isn't listed in the help for copy-sqldatabase (but is used in the first example).  Also, it doesn't appear to tab complete -Database as an option when typing out the command.  I just thought I'd mention it as it caused me some confusion when it wasn't working for me.

![copy-sqldatabase-tabcomplete](https://cloud.githubusercontent.com/assets/6772425/22155037/a47a1e76-def3-11e6-8e62-a2ebbc23fcc6.png)

**Comment by ctrlbold** [comment]
The NoSystem bug should have been fixed a few versions ago. Please update to the newest one to ensure it works ( or let us know if it doesnt). 

Unless Test is an actual server, the above command will not work. Until we move to the new way of doing dynamic parameters, -Databases will only appear once PS can login to your Source destination to load up the list of names. If you continue to have issues, please send us the results of Test-SqlConnection -SqlServer <your source server>

**Comment by ctrlbold** [comment]
Closing issue -- please ensure you can login to the source and the databases param will appear
