### ISSUE TITLE
Get-DbaBuildReference -> Get-DbaBuild

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5901]
Motion to add a perma alias to Get-DbaBuildReference and rename it to Get-DbaBuild.

Anyone remember why we kept `Reference` ?

**Comment by wsmelton** [comment]
I recall the discussion we had was sound...but for the life can't recall what it was anymore.

I'm ok with doing the permanent alias and renaming it to just `Get-DbaBuild`.

Maybe @niphlod remembers?

**Comment by niphlod** [comment]
vaguely the fact that you can also pass something that is not strictly a build number and get results back.
Though we do have Test-DbaBuild so in the end..... I'm ok with aliasing.

**Comment by andreasjordan** [comment]
There is not much discussion here - @potatoqualitee should we close this and leave it like it is?

**Comment by wsmelton** [comment]
Leave, still a todo item.

**Comment by potatoqualitee** [comment]
Still agree with myself 😅  Also, kudos for adding aliases to our docs, @niphlod !
