### ISSUE TITLE
[Bug]: Infinite loop when not masking unique columns in a table where HasUniqueIndex is true

### ISSUE THREAD

**Issue by simonmckenzie** [sqlcollaborative/dbatools#5906]
### Environmental information

```powershell
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.18362.113                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.18362.113                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.21\dbatools.psd1
Version : 1.0.21




```

```powershell
LCID             Name             DisplayName
----             ----             -----------
3081             en-AU            English (Australia)
```

#### SQL Server: 
```sql
Microsoft SQL Server 2008 (SP4) - 10.0.6000.29 (X64)   Sep  3 2014 04:11:34   Copyright (c) 1988-2008 Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 18362: ) 
```

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

Script uses all memory on system, then terminates

#### Steps to Reproduce

```sql
CREATE TABLE ReproTable
(
	UniquePrimaryKey uniqueidentifier NOT NULL,
	OneColumn varchar(50) NULL,
	CONSTRAINT [PK_ReproTable] PRIMARY KEY CLUSTERED 
	(
		[UniquePrimaryKey] ASC
	)
)

INSERT INTO ReproTable
        (UniquePrimaryKey, OneColumn)
VALUES 
	(NEWID(), 'TestValue'),
	(NEWID(), 'TestValue2')
```

```powershell
New-DbaDbMaskingConfig -SqlInstance LOCALHOST\TESTING08 -Database DBName -Path "C:\temp" -Table ReproTable
```

_delete the primary key from the set of columns to be masked_

Final config file:

```json
{
    "Name":  "DBName",
    "Type":  "DataMaskingConfiguration",
    "Tables":  [
                   {
                       "Name":  "ReproTable",
                       "Schema":  "dbo",
                       "Columns":  [
                                       {
                                           "Name":  "OneColumn",
                                           "ColumnType":  "varchar",
                                           "CharacterString":  null,
                                           "MinValue":  25,
                                           "MaxValue":  50,
                                           "MaskingType":  "Random",
                                           "SubType":  "String2",
                                           "Format":  null,
                                           "Deterministic":  false,
                                           "Nullable":  true,
                                           "Composite":  null
                                       }
                                   ],
                       "HasUniqueIndex":  true
                   }
               ]
}
```

```powershell
Invoke-DbaDbDataMasking -SqlInstance LOCALHOST\TESTING08 -Database DBName -Path 'c:\temp\LOCALHOST$TESTING08.DBName.DataMaskingConfig.json'
```

#### Expected Behavior

I expected masking to be run on the one column I specified
#### Actual Behavior

The code got stuck in an infinite loop, finally ending when it used all the memory in the system.

The problem is in this loop:
```powershell
while (($uniqueValues | Select-Object -Property ($rowValue | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name)) -match $rowValue) {
```
Within the loop, `$rowValue` is only updated if the index column has a defined mask. If it doesn't, no changes are made and the while loop just loops forever.

To prevent entry into this loop, it's necessary to change `HasUniqueIndex` in the config file to `false` - this isn't very intuitive to me, and I'm sure others will/have had the same problem.

It seems the `HasUniqueIndex` field should actually be computed at runtime based on the set of columns to be masked.

**Comment by sanderstad** [comment]
I'm not sure why this happens at your instance. After running the steps this was my result

![image](https://user-images.githubusercontent.com/6154981/61705048-5613d600-ad45-11e9-8084-c9240e709334.png)

**Comment by simonmckenzie** [comment]
I wish I knew! I just did a clean run (running version `1.0.23` this time) , following my repro steps, and it still happened. Is there any more diagnostic information you need from me?

![screenshot of invoke plus memory usage](https://user-images.githubusercontent.com/17579442/61754546-f413a900-adf6-11e9-9d87-ea66d0a2583c.png)

**Comment by simonmckenzie** [comment]
This is marked as "need more info" - is there any info which I can give to you in order to aid investigation?

**Comment by ChrisUnwin** [comment]
I have also had this same problem - out of memory exception because I didn't change true to false on HasUniqueIndex when I'm not masking the PK from the set of tables to be masked.

Version Info:

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Using VSCode, dbatools version 1.0.51 on Windows 10 Enterprise (1903)

**Comment by jeremytbrun** [comment]
We have this same exact issue. As soon as we set _HasUniqueIndex_ to false it worked like a charm.
