### ISSUE TITLE
[Bug] Very slow masking performance with large tables

### ISSUE THREAD

**Issue by simonmckenzie** [sqlcollaborative/dbatools#5907]
### Environmental information

```powershell
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.18362.113                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.18362.113                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.21\dbatools.psd1
Version : 1.0.21




```

```powershell
LCID             Name             DisplayName
----             ----             -----------
3081             en-AU            English (Australia)
```

#### SQL Server: 
```sql
Microsoft SQL Server 2008 (SP4) - 10.0.6000.29 (X64)   Sep  3 2014 04:11:34   Copyright (c) 1988-2008 Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 18362: ) 
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

Very slow performance when trying to mask tables of reasonable size (~6K items)

#### Steps to Reproduce

```sql
CREATE TABLE ReproTable
(
	UniquePrimaryKey uniqueidentifier NOT NULL,
	OneColumn varchar(50) NULL,
	CONSTRAINT [PK_ReproTable] PRIMARY KEY CLUSTERED 
	(
		[UniquePrimaryKey] ASC
	)
)

INSERT INTO ReproTable
    (UniquePrimaryKey, OneColumn)
VALUES 
	(NEWID(), 'TestValue')
GO 6000
```

```powershell
New-DbaDbMaskingConfig -SqlInstance LOCALHOST\TESTING08 -Database DbName -Path "C:\temp" -Table ReproTable
```

```powershell
Invoke-DbaDbDataMasking -SqlInstance LOCALHOST\TESTING08 -Database DbName -Path 'c:\temp\LOCALHOST$TESTING08.DbName.DataMaskingConfig.json'
```

#### Expected Behavior

It won't take that long to mask 6000 rows
#### Actual Behavior

It takes about an hour!

The slow point is here:

```powershell
#Handle rows already being System.Data.DataRow
if ($object.GetType().FullName -eq 'System.Data.DataRow') {
    
    $datatable.Merge($object.Table)
    $datatable = $datatable.DefaultView.ToTable($true)

    continue
}
```

If I instrument this code (see below), it can be seen that there are two slow points:
 1. The same 6000 rows are being continually merged into the `$datatable` object. It seems that it would be better to simply add a new row than to merge the whole table.
 2. The call to `$datatable.DefaultView.ToTable($true)` is very slow - I don't have context to know why it's used, but is it necessary? This will clone the whole `DataTable` into a new `DataTable`.

Output from instrumented code:

| Merge time (ms) |  ToTable time (ms) |  Destination rows |  Source rows | 
|-----------------|--------------------|-------------------|--------------| 
| 4.1688          |  254.3316          |  0                |  6000        | 
| 4.6994          |  670.6086          |  6000             |  6000        | 
| 4.5249          |  511.3207          |  6000             |  6000        | 
| 4.425           |  672.2758          |  6000             |  6000        | 
| 4.9664          |  611.3895          |  6000             |  6000        | 

Instrumented code:
```powershell
#Handle rows already being System.Data.DataRow
if ($object.GetType().FullName -eq 'System.Data.DataRow') {
    
    $destinationRowCount = $dataTable.Rows.Count
    $mergeTime = Measure-Command {$datatable.Merge($object.Table)}

    $toTableTime = Measure-Command {$datatable = $datatable.DefaultView.ToTable($true)}

    # Merge time, ToTable time, Destination rows, Source rows
    Add-Content 'c:\temp\timings.csv' "$($mergeTime.TotalMilliseconds), $($toTableTime.TotalMilliseconds), $destinationRowCount, $($object.Table.Rows.Count)"

    continue
}
```

Thank you!

**Comment by simonmckenzie** [comment]
I have vague memories of working with `DataSets`, and perhaps a faster way would be to create a new row in the destination table, set the `ItemArray`, then call `AcceptChanges` on it, something like this:

```powershell
            #Handle rows already being System.Data.DataRow
            if ($object.GetType().FullName -eq 'System.Data.DataRow') {
                    $datarow = $datatable.NewRow()
                    $datarow.ItemArray = $object.ItemArray
                    $datatable.Rows.Add($datarow)
                    $datarow.AcceptChanges()

                    continue
            }
```

Here's where it is in GitHub: https://github.com/sqlcollaborative/dbatools/blob/cd7a897cf042666e3bdbd18b6fdefb77dd4991fd/functions/ConvertTo-DbaDataTable.ps1#L307

**Comment by wsmelton** [comment]
Performance issues are subjective to many environmental configurations that we will never be able to fully duplicate. I don't have a 2008 instance handy to try your example but on SQL Server 2017 Linux container it runs in 5.1 seconds.

**Comment by simonmckenzie** [comment]
That's surprising and disappointing! The slow lines identified here don't even touch the database - is this going to be related to the version of the .NET framework in use?

**Comment by wsmelton** [comment]
Not likely because I ran the test on the same build of PowerShell and Windows 10 you provided. The only difference is SQL Server from my view, but I don't know what hardware specs your server is on.

`Measure-Command` will add overhead in order to calculate the timing. So not sure how much that is messing with your results. You might add something like:

```powershell
#Handle rows already being System.Data.DataRow
if ($object.GetType().FullName -eq 'System.Data.DataRow') {
    
    $destinationRowCount = $dataTable.Rows.Count
    $watchme =  [system.diagnostics.stopwatch]::StartNew()
    $datatable.Merge($object.Table)
    $watchme.Elapsed

    $watchme =  [system.diagnostics.stopwatch]::StartNew()
    $datatable = $datatable.DefaultView.ToTable($true)
    $watchme.Elapsed

    continue
}
```

**Comment by simonmckenzie** [comment]
Hi @wsmelton, I tried using your recommendation, and the results are similar:

| Merge time (ms) |  ToTable time (ms) |  Destination rows |  Source rows | 
|-----------------|--------------------|-------------------|--------------| 
|                 |                    |                   |              | 
| 4.2399          |  250.8369          |  0                |  6000        | 
| 3.9563          |  531.819           |  6000             |  6000        | 
| 3.9952          |  467.9382          |  6000             |  6000        | 
| 4.2519          |  476.7805          |  6000             |  6000        | 
| 4.3462          |  522.2433          |  6000             |  6000        | 
| 6.0522          |  559.031           |  6000             |  6000        | 
| 4.4134          |  567.906           |  6000             |  6000        | 
| 4.415           |  484.2967          |  6000             |  6000        | 


Code:
```powershell
#Handle rows already being System.Data.DataRow
if ($object.GetType().FullName -eq 'System.Data.DataRow') {
                    
    $destinationRowCount = $dataTable.Rows.Count

    $destinationRowCount = $dataTable.Rows.Count
    $watchme = [system.diagnostics.stopwatch]::StartNew()
    $mergeTime = $watchme.Elapsed
    
    $watchme =  [system.diagnostics.stopwatch]::StartNew()
    $datatable = $datatable.DefaultView.ToTable($true)
    $toTableTime = $watchme.Elapsed
    
    # Merge time, ToTable time, Destination rows, Source rows
    Add-Content 'c:\temp\timings.csv' "$($mergeTime.TotalMilliseconds), $($toTableTime.TotalMilliseconds), $destinationRowCount, $($object.Table.Rows.Count)"

    continue
}
```

**Comment by sanderstad** [comment]
@simonmckenzie I will look into it. Like @wsmelton says, it has to be something in either your SQL server configuration or SQL server version.
