### ISSUE TITLE
issue trying to get start-dbamigration to run

### ISSUE THREAD

**Issue by pattere** [sqlcollaborative/dbatools#5909]
I am not a big powershell user.  But, I am working with dbatools to test it for some upcoming SQL server migrations.  I am starting with the line below on a test server:
```
start-dbamigration -source sql2012 -destination sql2019 -backuprestore -sharedpath Z:\ -whatif
```

* I do have open connections to both database servers, the local one, and the on to be migrated, in SSMS.
* Where Z:\ is a mapped drive to a backup location on the server to be migrated.  With a sub-directory for each database's backups.  ie Z:\db1, Z:\db2, etc.  Could that be causing an issue?
* I have also tried the using the FQDN of the server: `\\servername\d$\mssqlbu\backup\`

I am receiving the message:
```
What if: Performing the operation "Set variable" on target "Name: __dbatools_interrupt_function_78Q9VPrM6999g6zo24Qn83m09XF56InEn4hFrA8Fwhu5xJrs6r Value: True".
The network path was not found
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.22\allcommands.ps1:80163 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Connect-DbaInstance
```
* I am not clear if the cmdlet is not finding the location set for Z:, or if it is having an issue with the code in the module.

**Comment by wsmelton** [comment]
A shared path needs to be a UNC share. A mapped drive cannot be seen across two different SQL Server instances.

As well, use of the admin share `\\servername\D$` will not work if the service account for SQL Server (both instances) has access to it as well. You will need to utilize a network share that both service accounts for SQL Server can physically access and read/write to them.

**Comment by potatoqualitee** [comment]
Shawn is correct. If Z is mapped, it's only mapped for the account that created it. Once you've got permissions set properly for the network share, then you'd need to run a `Test-DbaPath` using the credentials of the SQL Server service accounts to ensure they've got access.
