### ISSUE TITLE
Test-DbaLastBackup Size should be summed 

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#591]
Is this a *feature* OR *bug*:
bug

**Steps to Reproduce**
 Test-DbaLastBackup -SqlServer localhost
when localhost has backed up to multiple files

**Action Results**
{ 1.1, 1.1, 1.1 }

**Expected Results**
3.3
**Additional comments**
the rest of the multi file support works

**Comment by Stuart-Moore** [comment]
Pull request submitted to fix this - https://github.com/sqlcollaborative/dbatools/pull/612

**Comment by SirCaptainMitch** [comment]
Looks like this was merged, can it be closed?

**Comment by ctrlbold** [comment]
Yes, merci :)
