### ISSUE TITLE
Make Expand-DbaDbLogFile question clearer (or remove)

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#5912]
### Summary of new feature

If the `TargetLogSize` parameter passed into `Expand-DbaDbLogFile` matches the suggested target log size, don't prompt the user for an override.

Example:

```
PS C:\> Expand-DbaDbLogFile -SqlInstance $SQL16 -Database Movies -ShrinkLogFile -ShrinkSize 16 -TargetLogSize 1024 -IncrementSize 1024;
Choose increment value for database 'Movies':
The input value for increment size was 1024MB. However the suggested value for increment is 1024MB.
Do you want to use the suggested value of 1024MB insted of 1024MB
[Y] Yes [N] No [?] Help (default is "Yes"):
```

### Proposed technical details (if applicable)

Perform an additional test in the `if` block starting on line 418 to check that the suggested and requested log sizes are different. If they are not different, don't prompt the user.

Also, I'm contractually obligated to point out that "instead" is misspelled here :)

### Latest version of dbatools as of writing

1.0.22

**Comment by wsmelton** [comment]
Why do we even make a suggestion? I don't think the command should have that logic at all, it goes more into a test command.
