### ISSUE TITLE
Issue with Write-DbaDbTableData for Azure SQL DBs

### ISSUE THREAD

**Issue by IdrisArslanian** [sqlcollaborative/dbatools#5915]
We recently updated Dbatools and all of a sudden, the function Write-DbaDbTableData started telling us the Azure SQL DB we were previously writing to no longer exists.  When we reverted to version 0.9.818, it worked as before.  Have the relevant compare section screenshot:
![image](https://user-images.githubusercontent.com/4398552/61481963-145ae800-a95f-11e9-9920-3fd543bea9dc.png)

**Comment by wsmelton** [comment]
I may be over reading but that compare screenshot has the same code it, it was just wrapped in a try catch block.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if this is still an issue with the current version.
