### ISSUE TITLE
update-dbainstance verbose should be warn

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5916]
"is already the latest available" should be a warn instead of verbose so that the person can know why the updater quit

**Comment by sirsql** [comment]
@potatoqualitee do you mean the following in Get-SqlInstanceUpdate?
`Write-Message -Message "$($currentVersion.Build) on computer [$($computer)] is already the latest available." -Level Verbose`

**Comment by wsmelton** [comment]
@sirsql that is the right one.
