### ISSUE TITLE
Add-DbaAgDatabase - Add Wait switch based on Sync status

### ISSUE THREAD

**Issue by jomi50** [sqlcollaborative/dbatools#5917]
### Summary of new feature
I am running a synchronous AlwaysOn cluster and when I use Add-DbaAgDatabase the command returns sucessfully even when the secondary databases SynchronizationState is still NotSynchronizing/Initializing. I do not really want to continue with my skript until the database is in sync and a "-wait" switch (cherry on top would be a wait timeout) would make live easier. 

### Proposed technical details (if applicable)

Working on it, if I find a way I will update the request.

### Latest version of dbatools as of writing

1.0.22

**Comment by wsmelton** [comment]
I would expect default behavior to actually wait for the good state to be returned, so I would see this as a bug. However I would see it beneficial to have it tied to a parameter like `-Wait` until it sees that good state. Some builtin commands for PS do this similar behavior. The timing will vary between environments greatly based on hardware, network bandwidth and such; so having it featured against a parameter I think would be an welcomed addition.
