### ISSUE TITLE
Option to pass compatibility to Get-DbaDbCompatibility as an integer. 

### ISSUE THREAD

**Issue by ttoennies** [sqlcollaborative/dbatools#5919]
Get-DbaDbCompatibility returns compatibility as a string while Set-DbaDbCompatibility needs an integer.  Please consider adding a switch to Get-DbaDbCompatibility so that an integer could be returned which allow us to write a command such as this:

$Comp = Get-DbaDbCompatibility -SqlInstance psqlb7sm102 -Database master 

Set-DbaDbCompatibility -SqlInstance psqlb7sm102 -Database MyUserDB -TargetCompatibility $Comp 

Essentially setting the compatibility of a user database to the version of the server.  

Thank you.

**Comment by ttoennies** [comment]
Get-DbaDbCompatibility returns compatibility as a string while Set-DbaDbCompatibility needs an integer.  Please consider adding a switch to Get-DbaDbCompatibility so that an integer could be returned which allow us to write a command such as this:

$Comp = Get-DbaDbCompatibility -SqlInstance psqlb7sm102 -Database master 

Set-DbaDbCompatibility -SqlInstance psqlb7sm102 -Database MyUserDB -TargetCompatibility $Comp 

Essentially setting the compatibility of a user database to the version of the server.  

Thank you.

**Comment by wsmelton** [comment]
I see it as stating that Set command needs to support the string value returned by the get command to support proper piping.

The set command has the conversion code already in it we just don't allow the property and type correctly.

**Comment by ttoennies** [comment]
The documentation suggests that the Set command needs the value as an integer; so how would the piping work?

This command:

Get-DbaDbCompatibility -SqlInstance server01 -Database master | Set-DbaDbCompatibility -SqlInstance server01 -Database userdb

produces this error:

Set-DbaDbCompatibility : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not 
match any of the parameters that take pipeline input.

While this command: 

$comp = Get-DbaDbCompatibility -SqlInstance server01 -Database master 

Set-DbaDbCompatibility -SqlInstance server01 -Database UserDB -TargetCompatibility $comp

Produces this error:

Set-DbaDbCompatibility : Cannot process argument transformation on parameter 'TargetCompatibility'. Cannot convert the "@{ComputerName=server01; 
SqlInstance=server01; Database=master; Compatibility=Version130}" value of type "System.Management.Automation.PSCustomObject" to type "System.Int32".

It seems like the error is exactly the problem I'm trying to avoid.

**Comment by wsmelton** [comment]
The Set command has to be rewritten.

**Comment by ttoennies** [comment]
I know you stated that the Set command needs to be rewritten... but it seems like changing the Get command is less problematic... here is an option to consider. 

function Get-DbaDbCompatibility {
    <#
    .SYNOPSIS
        Displays the compatibility level for SQL Server databases.
    .DESCRIPTION
        Get the current database compatibility level for all databases on a server or list of databases passed in to the function.
    .PARAMETER SqlInstance
        The target SQL Server instance or instances.
    .PARAMETER SqlCredential
        SqlCredential object used to connect to the SQL Server as a different user.
    .PARAMETER Database
        The database or databases to process. If unspecified, all databases will be processed.
    .PARAMETER InputObject
        A collection of databases (such as returned by Get-DbaDatabase)
    .PARAMETER WhatIf
        Shows what would happen if the command were to run
    .PARAMETER OutputFormat
        The format of the Compatibility value.  Passing 'string' will return Versionxyz, where xyz is the 2 or 3 digit Compatibility value.  
        Passing 'int' returns just the 2 or 3 digit number
    .PARAMETER Confirm
        Prompts for confirmation of every step. For example:
        Are you sure you want to perform this action?
        Performing the operation "Update database" on target "pubs on SQL2016\VNEXT".
        [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
    .PARAMETER EnableException
        By default, when something goes wrong we try to catch it, interpret it and give you a friendly warning message.
        This avoids overwhelming you with "sea of red" exceptions, but is inconvenient because it basically disables advanced scripting.
        Using this switch turns this "nice by default" feature off and enables you to catch exceptions with your own try/catch.
    .NOTES
        Tags: Compatibility, Database
        Author: Garry Bargsley, http://blog.garrybargsley.com/
        Website: https://dbatools.io
        Copyright: (c) 2018 by dbatools, licensed under MIT
        License: MIT https://opensource.org/licenses/MIT
    .LINK
        https://dbatools.io/Get-DbaDbCompatibility
    .EXAMPLE
        PS C:\> Get-DbaDbCompatibility -SqlInstance localhost\sql2017
        Displays database compatibility level for all user databases on server localhost\sql2017
    .EXAMPLE
        PS C:\> Get-DbaDbCompatibility -SqlInstance localhost\sql2017 -Database Test
        Displays database compatibility level for database Test on server localhost\sql2017
    .EXAMPLE
        PS C:\> $Comp = Get-DbaDbCompatibility -SqlInstance localhost\sql2017 -Database master -OutputFormat int
        PS C:\> Set-DbaDbCompatibility -SqlInstance localhost\sql2017 -Database UserDB -TargetCompatibility $Comp
        Sets the compatibility of a database to the Compatibility of its Instance
    #>
    [CmdletBinding()]
    param (
        [DbaInstanceParameter[]]$SqlInstance,
        [PSCredential]$SqlCredential,
        [string[]]$Database,
        [parameter(ValueFromPipeline)]
        [Microsoft.SqlServer.Management.Smo.Database[]]$InputObject,
        [string]$OutputFormat,
        [switch]$EnableException
    )
    process {
        if (Test-Bound -not 'SqlInstance', 'InputObject') {
            Write-Message -Level Warning -Message "You must specify either a SQL instance or pipe a database collection"
            continue
        }

        if ($SqlInstance) {
            $InputObject += Get-DbaDatabase -SqlInstance $SqlInstance -SqlCredential $SqlCredential -Database $Database
        }

        foreach ($db in $InputObject) {
            $server = $db.Parent
            $ServerVersion = $server.VersionMajor
            Write-Message -Level Verbose -Message "SQL Server is using Version: $ServerVersion"

            if ($OutputFormat -eq "int") { 
                $Comp = [int]($db.CompatibilityLevel -replace "Version","")/10
                }
            else {

                $Comp = $db.CompatibilityLevel

            }


            [PSCustomObject]@{
                ComputerName  = $server.ComputerName
                InstanceName  = $server.ServiceName
                SqlInstance   = $server.DomainInstanceName
                Database      = $db.Name
                Compatibility = $Comp
            }
        }
    }
}

**Comment by wsmelton** [comment]
We need to keep the data intact as SMO outputs it just for reference. Another property may be added like `CompatibilityNum` or something, but it is best to handle the Set command to know how to translate it for pipeline support. The set command itself is already mapping the "Version10" pattern to a numeric value, it just not do that for the input object.

**Comment by garethnewman** [comment]
It seems it expects and Smo.Database object, so this for example works:-

`Get-DbaDatabase -SqlInstance localhost\dev2016 -Database master | Set-DbaDbCompatibility -SqlInstance localhost\dev2016 -Database testdb`

I am a noob at this but I think Get-DbaDbCompatibility is outputting a custom object, so I would think Get-DbaDbCompatibility needs to change to output a normal Smo.Database object? Then Set will work with that object.

If I am wrong, and someone can explain what needs to change then I am happy to have a look this weekend.

**Comment by andreasjordan** [comment]
@ttoennies 
Please have a look at my proposed changes in #7349. Will they meet your requirements?

**Comment by ttoennies** [comment]
Yes, this looks like a great solution.  Thank you!
