### ISSUE TITLE
Watch-DbaDbLogin not working due to incorrect module reference for cms

### ISSUE THREAD

**Issue by mmaagk642** [sqlcollaborative/dbatools#5920]
### Environmental information

                                                                                                                                                                          
PSVersion                      5.1.14393.3053                                                                                                                                                                            
PSEdition                      Desktop                                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                   
BuildVersion                   10.0.14393.3053                                                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                                       
SerializationVersion           1.1.0.1      

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.22\dbatools.psd1
Version : 1.0.22

#### SQL Server: 

Microsoft SQL Server 2017 (RTM-CU15-GDR) (KB4505225) - 14.0.3192.2 (X64)   Jun 15 2019 00:45:05   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
/* REPLACE WITH output of @@VERSION */
```



### Report

<!--
Things to consider:
- Errors received are not related to permissions? No
- Have you tried the same command using powershell.exe instead of a hosted powershell instance like ISE or VS Code? Yes
- If this refers to Copy-DbaDatabase can you replace the problem with Backup-DbaDatabase and Restore-DbaDatabase?
- Copy-DbaDatabase will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.
--> 
I am getting a warning when trying to run watch-dbadblogin function. I have this running in task scheduler every hour to pull logins, and i haven't seen a lot of data lately, and was wondering why...so I ran the command in powershell directly, and I am getting a warning that

WARNING: [12:27:40][Watch-DbaDbLogin] The CMS server, dbaman\cms, was not accessible. | The term 'Get-DbaRegServerName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

My cms instance is up and i can see it and connect to it. I went into the function code and made sure it was referencing the right function name, which is get-dbaregserver, and it is. so I am not sure why it keeps giving me this warning and then not running. I had an old version on there, so i blew that one away, i have tried running the rename helper function and it came back clean. uninstalled dbatools completely and updated to the most recent version. I am still getting the error. Please reference line 98 of Watch-DbaDbLogin fm for incorrect reference to fm that pulls info from cms server.

#### Host used

- [ X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe


#### Steps to Reproduce

<!--
If you have confirmed this issue can be reproduced, please provide the exact steps (T-SQL, PowerShell, ext)
-->
Watch-DbaDbLogin -SqlInstance dbaman -Database DatabaseLogins -Table DBLogins -SqlCms dbaman\cms
#### Expected Behavior

<!--
What did you expect to happen?
-->Run through each server and capture login info from each server and populate DBLogins table in my DatabaseLogins database

#### Actual Behavior

<!--
What happened?
-->It shows a warning and then nothing happens:

WARNING: [14:02:04][Watch-DbaDbLogin] The CMS server, dbaman\cms, was not accessible. | The term 'Get-DbaRegServerName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by mmaagk642** [comment]
Hey guys, can i get an update on this? it is really affecting my ability to log logins from my servers and now that it is over a month without any login info, i would like to see if there was a timeline in getting it fixed.

**Comment by wsmelton** [comment]
We've been tied up with work projects and personal life.

If you would like to fix it yourself you are more than welcome to submit a PR. If you want to just fix it locally find and replace `Get-DbaRegServerName` for `Get-DbaRegServer`.

**Comment by mmaagk642** [comment]
Thanks Shawn. I seen the issue and replaced it in the watch-dbadblogin fm and it still wasn’t working. Bit I can dig through the rest of the files and find it and fix it. Thanks for getting back to me so quickly.
