### ISSUE TITLE
Get-DbaDbMirror minimal permissions

### ISSUE THREAD

**Issue by habibhammy** [sqlcollaborative/dbatools#5922]
Hi DBATOOLS Community,

I'm facing a little issue on the Get-DbaDbMirror command and I would like your help on it. 

The issue is permission related. Actually, I've developed a SQL Statistic tool based on PS module and when deploying the InfoSec team in my company pushed us to use granular permissions for the service account running the statistics instead of just granting sysadmin role. Therefore I've been through you code and granted SELECT permissions on all the SYS views that are involved in the commands I'm using. However, it seems I've missed some because when I run this command with my account ( which is sysadmin) on a secondary mirror SQL Server i'm getting infos about the mirrored databases and the primary partner but not with the service account.

So far I've granted the below permissions : 

Select on Master Database on  SYS.DATABASE_MIRRORING_WITNESSES, SYS.DATABASES and on other views and functions related to GET-DBADBFILE command.

Here is the out come of the command : 

- Running under My SYSADMIN Account : 
![image](https://user-images.githubusercontent.com/11525159/61715223-ee698500-ad5c-11e9-9ce2-e0f129a486e2.png)

- Running under the service account : 
![image](https://user-images.githubusercontent.com/11525159/61715325-296bb880-ad5d-11e9-8c0f-9834d122a9b4.png)

Thanks a lot for you help in advance. 😃

**Comment by habibhammy** [comment]
Hi,

Sorry to raise this subject again. Can you please give me some help? 

Many Thanks.

@potatoqualitee   @niphlod   @wsmelton    @joshcorr

**Comment by sirsql** [comment]
@habibhammy  - Couple of questions:

- Have you attempted to not output the information to the variable to see if this throws a specific error?
 - Have you attempted to run profiler on the target with it filtered to the account you are using in an attempt to see what errors get thrown (using with RPC starting/RPC ending, Errors in profiler selection). This might provide more detail on what permissions you are having trouble with.

**Comment by joshcorr** [comment]
I would add...
Have you tried running these two lines of code from `Get-DbaDbMirror` under the reduced credentials?

```
$dbs = Get-DbaDatabase -SqlInstance $instance -SqlCredential $SqlCredential
$partners = $dbs | Where-Object MirroringPartner
```

**Comment by habibhammy** [comment]
Hi all, 

Thanks for your suggestions.

@sirsql for your questions :
1-Have you attempted to not output the information to the variable to see if this throws a specific error? 
==> yes and no error is coming.
2-Have you attempted to run profiler on the target with it filtered to the account you are using in an attempt to see what errors get thrown (using with RPC starting/RPC ending, Errors in profiler selection). This might provide more detail on what permissions you are having trouble with.
==> Actually yes, I've tried to verify with the SQL Profiler and see if some exceptions are thrown but the only one I can get are :  

> Cannot drop the table '#SVer' because it does not exist or you do not have permission. 

For me it's normal as I'm not seeing any CREATE #SVER before the error !  For references here is the script catched by the trace for this error attached [SQLTrace.txt](https://github.com/sqlcollaborative/dbatools/files/3457485/SQLTrace.txt)

> The database "XXXX" cannot be opened. It is acting as a mirror database. 

For me it's also normal as we are querring the secondary node of a mirror server.

@joshcorr  for your question:
Actually I've already granted permissions on the database_mirroring_witeness sys view to the service account and this script is successfully executed on the server.
But for the code : 
`$dbs = Get-DbaDatabase -SqlInstance $instance -SqlCredential $SqlCredential
$partners = $dbs | Where-Object MirroringPartner
`  
when running under the service account the $parteners variable is empty while $dbs is not.

**Comment by joshcorr** [comment]
Okay, could you drop the object you are getting for $dbs (and redact it if needed). Think we are having issues with the filter on this cmdlet with the `Where-Object`. Looking at it in my own area as well to confirm.

**Comment by habibhammy** [comment]
@joshcorr Here is the $dbs object I'm getting with the service account.
[dbs_var.xlsx](https://github.com/sqlcollaborative/dbatools/files/3460375/dbs_var.xlsx)

**Comment by joshcorr** [comment]
Looks like the `MirroringPartner` stuff is NULL because of permissions..

Looking at [Microsoft Docs](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-mirroring-transact-sql?view=sql-server-2017) for the `sys.database_mirroring` objects
```
To see the row for a database other than master or tempdb, you must either be the database 
owner or have at least ALTER ANY DATABASE or VIEW ANY DATABASE server-level permission or 
CREATE DATABASE permission in the master database. To see non-NULL values on a mirror database,
you must be a member of the sysadmin fixed server role.
```

**Comment by joshcorr** [comment]
@habibhammy Any word on if this resolved your issue?

**Comment by habibhammy** [comment]
Hi,

Sorry for not coming back on this before. I had a lot of workload and I did not had time to test it. 

So thanks a lot @joshcorr for your lead. Actually, the **VIEW ANY DATABASE** Permission resolved the problem for me.

Many Thanks.
