### ISSUE TITLE
[Question] Can we use New-DbaDatabase to create a database with multiple data file in Primary group ?

### ISSUE THREAD

**Issue by hanksithebest** [sqlcollaborative/dbatools#5925]
I have tested the different parameters but it's failed.

for example, i would like to create a database DB1 with db101.mdf and db102.ndf  with same file group Primary. but it looks failed 

Do your guys have any clue for that ?

**Comment by hanksithebest** [comment]
I think the only way to fix this is to create database with TSQL......

**Comment by wsmelton** [comment]
Yes the command should support creating a database with multiple files in both primary and secondary file group. However the way it is written does not allow for the primary file group to have multiple, but also has a bug on creating multiple files in a secondary file group (it doesn't actually create the file group).

If you want to submit a bug report with the details required someone can take a look at it.

**Comment by hanksithebest** [comment]
> Yes the command should support creating a database with multiple files in both primary and secondary file group. However the way it is written does not allow for the primary file group to have multiple, but also has a bug on creating multiple files in a secondary file group (it doesn't actually create the file group).
> 
> If you want to submit a bug report with the details required someone can take a look at it.

I would like to try to adjust the code , could you tell me where i need to change ? i found function new-dbadatabase in all_commands.ps1 and new-dbadatabase.ps1 .  i tried debug and it lead me to all_commands.ps1 , then should i change the code in all_commands.ps1 only ?

**Comment by wsmelton** [comment]
You can check out [contributing guide](https://dbatools.io/contribute) if you would like to submit a PR to address the bug.

We combine all the function ps1 files into all_commands.ps1 for the version of the module that we publish to the PowerShell Gallery. To debug the code would be easiest to pull down the repository and work on the individual function file itself.
