### ISSUE TITLE
Test-DbaLastBackup fails against multiple DBs

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#5927]
### Environmental information

```
PSVersion                      5.1.18362.145
```

Dbatools version:
```
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.23\dbatools.psd1
Version : 1.0.23
```

#### SQL Server: 
```
Microsoft SQL Server 2016 (SP2-CU7-GDR) (KB4505222) - 13.0.5366.0 (X64) 
	Jun 15 2019 08:22:25 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: )
```
#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
Stop-Function : [MyInstance] cannot access U:\SQLBackups\MSSQL13.CTX\MSSQL\Backup.                                                                
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.23\allcommands.ps1:68415 char:21                                                                     
+ ...             Stop-Function -Message "$destserver cannot access $CopyPa ...                                                                                 
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                         
+ CategoryInfo          : NotSpecified: (:) [Write-Error], Exception                                                                                            
+ FullyQualifiedErrorId : dbatools_Test-DbaLastBackup,Stop-Function    
```

#### Steps to Reproduce

`Test-DbaLastBackup -SqlInstance MyInstance -Database DB1,DB2 -Verbose`

#### Expected Behavior
Last backups for DB1 & DB2 are restored & tested

#### Actual Behavior
First database is restored and tested. Second database is not, with the following warning message produced:

```
WARNING: [12:45:36][Test-DbaLastBackup] [MyInstance] cannot access U:\SQLBackups\MSSQL13.CTX\MSSQL\Backup
```

**Comment by sirsql** [comment]
I am unable to reproduce this issue. Is it possible that some permissions may have been altered on the specific backup folder or files?

TSQL
```
create database test;
create database test2;
GO

backup database test to disk = 'test.bak' with format, init;
backup database test2 to disk = 'test2.bak' with format, init;
```
PS
`test-dbalastbackup  -SqlInstance localhost -Database Test,Test2 -verbose`

**Comment by alevyinroc** [comment]
@sirsql can you try against a remote instance, not `localhost`?

**Comment by wsmelton** [comment]
Your error or warning message shows a named instance, but command to test does not. Can you clarify whether this works on either or is only having issues on named instance?

The only difference with this command being executed locally or remote is how the path is dealt with... If you are using a local path as your message shows I would expect that to have a problem. The remote destination installed can't see a local path.

**Comment by alevyinroc** [comment]
It definitely fails on named instances. I haven't been able to complete a test against a default instance yet because SMO falls over with the number of databases on that one. Still working on that.

**Comment by alevyinroc** [comment]
@wsmelton I've been trying but `connect-dbainstance` (SMO, really) doesn't get along with the instance due to the number of databases on it so everything else kind of fails. I've made some attempts at making `connect-dbainstance` work better here but haven't succeeded yet

**Comment by potatoqualitee** [comment]
how many dbs, Andy??

**Comment by alevyinroc** [comment]
This morning, I'm sitting at 8847.

Here's the query that (I presume) SMO is running and timing out on. I'm 95% sure it has to do with the `defaultInitFields`.

``exec sp_executesql N' create table #tempbackup (database_name nvarchar(128), [type] char(1), backup_finish_date datetime) insert into #tempbackup select database_name, [type], max(backup_finish_date) from msdb..backupset where [type] = ''D'' or [type] = ''L'' or [type]=''I'' group by database_name, [type] create table #tmp_db_hadr_dbrs (group_database_id uniqueidentifier, synchronization_state tinyint, is_local bit) declare @HasViewPermission int select @HasViewPermission = HAS_PERMS_BY_NAME(null, null, ''VIEW SERVER STATE'') if (@HasViewPermission = 1) begin insert into #tmp_db_hadr_dbrs select group_database_id, synchronization_state, is_local from master.sys.dm_hadr_database_replica_states end create table #tmp_db_ars (replica_id uniqueidentifier, group_id uniqueidentifier) create table #tmp_db_ags (group_id uniqueidentifier, name sysname) if (@HasViewPermission = 1) begin insert into #tmp_db_ars select replica_id, group_id from master.sys.availability_replicas insert into #tmp_db_ags select group_id, name from master.sys.availability_groups end SELECT dtb.name AS [Name], dtb.collation_name AS [Collation], dtb.compatibility_level AS [CompatibilityLevel], dtb.create_date AS [CreateDate], dtb.database_id AS [ID], CAST(has_dbaccess(dtb.name) AS bit) AS [IsAccessible], dtb.is_fulltext_enabled AS [IsFullTextEnabled], CAST(case when dtb.name in (''master'',''model'',''msdb'',''tempdb'') then 1 else dtb.is_distributor end AS bit) AS [IsSystemObject], CAST(( case LOWER(convert( nvarchar(128), DATABASEPROPERTYEX(dtb.name, ''Updateability''))) when ''read_write'' then 1 else 0 end) AS bit) AS [IsUpdateable], (select backup_finish_date from #tempbackup where type = @_msparam_0 and db_id(database_name) = dtb.database_id) AS [LastBackupDate], (select backup_finish_date from #tempbackup where type = @_msparam_1 and db_id(database_name) = dtb.database_id) AS [LastDifferentialBackupDate], (select backup_finish_date from #tempbackup where type = @_msparam_2 and db_id(database_name) = dtb.database_id) AS [LastLogBackupDate], ISNULL(suser_sname(dtb.owner_sid),'''') AS [Owner], dtb.is_read_only AS [ReadOnly], dtb.recovery_model AS [RecoveryModel], (dtb.is_published*1+dtb.is_subscribed*2+dtb.is_merge_published*4) AS [ReplicationOptions], case when dtb.collation_name is null then 0x200 else 0 end | case when 1 = dtb.is_in_standby then 0x40 else 0 end | case dtb.state when 1 then 0x2 when 2 then 0x8 when 3 then 0x4 when 4 then 0x10 when 5 then 0x100 when 6 then 0x20 else 1 end AS [Status], CAST(DATABASEPROPERTYEX(dtb.name, ''Version'') AS int) AS [Version], dtb.is_broker_enabled AS [BrokerEnabled], ISNULL(DB_NAME(dtb.source_database_id), N'''') AS [DatabaseSnapshotBaseName], CAST(case when dmi.mirroring_partner_name is null then 0 else 1 end AS bit) AS [IsMirroringEnabled], dtb.is_trustworthy_on AS [Trustworthy], (select count(*) from master.dbo.sysprocesses p where dtb.database_id=p.dbid) AS [ActiveConnections], dbrs.synchronization_state AS [AvailabilityDatabaseSynchronizationState], ISNULL(ags.name, '''') AS [AvailabilityGroupName], dtb.containment AS [ContainmentType], CAST(dtb.is_encrypted AS bit) AS [EncryptionEnabled], dtb.name AS [DatabaseName2] FROM master.sys.databases AS dtb LEFT OUTER JOIN sys.database_mirroring AS dmi ON dmi.database_id = dtb.database_id LEFT OUTER JOIN #tmp_db_hadr_dbrs AS dbrs ON dtb.group_database_id = dbrs.group_database_id and dbrs.is_local = 1 LEFT OUTER JOIN #tmp_db_ars AS ars ON dtb.replica_id = ars.replica_id LEFT OUTER JOIN #tmp_db_ags AS ags ON ars.group_id = ags.group_id WHERE ( case when dtb.collation_name is null then 0x200 else 0 end | case when 1 = dtb.is_in_standby then 0x40 else 0 end | case dtb.state when 1 then 0x2 when 2 then 0x8 when 3 then 0x4 when 4 then 0x10 when 5 then 0x100 when 6 then 0x20 else 1 end =@_msparam_3) ORDER BY [Name] ASC drop table #tempbackup drop table #tmp_db_hadr_dbrs drop table #tmp_db_ars drop table #tmp_db_ags ',N'@_msparam_0 nvarchar(4000),@_msparam_1 nvarchar(4000),@_msparam_2 nvarchar(4000),@_msparam_3 nvarchar(4000)',@_msparam_0=N'D',@_msparam_1=N'I',@_msparam_2=N'L',@_msparam_3=N'1'	`

**Comment by potatoqualitee** [comment]
LOL dannnnnnnnnnnng! 8847, I love it. K, I'll whip up a PR real quick.

**Comment by wsmelton** [comment]
The default init fields is not the only issue you will come across when you start tracing on a large instance @alevyinroc . I have a client server with half that in database count (sitting around 4k last I touched it) and using basic SMO outside of our module is just not possible.

**Comment by wsmelton** [comment]
So to clarify are we saying the finals actually didn't work against named instance, or instances with a lot of databases?
