### ISSUE TITLE
[Bug] New-DbaAzAccessToken - Non-Existent switch in E.g for Connect-DbaInstance when using AzAccessToken.

### ISSUE THREAD

**Issue by abjoseph** [sqlcollaborative/dbatools#5933]
### Environmental information

```powershell
LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

#### SQL Server: 

```sql
Not Relevant
```

```sql
Not Relevant
```

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```
C:\Users\john.doe> Connect-DbaInstance -SqlInstance myserver.database.windows.net -Database mydb -AccessToken     Connect-DbaInstance : A parameter cannot be found that matches parameter name 'AccessToken'.
At line:1 char:79
+ ... SqlInstance myserver.database.windows.net -Database mydb -AccessToken
+                                                              ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-DbaInstance], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Connect-DbaInstance
```

#### Steps to Reproduce

1. Install-Module dbatools -RequiredVersion 1.0.23
2. Try running the below command"

```C:\Users\john.doe> Connect-DbaInstance -SqlInstance myserver.database.windows.net -Database mydb -AccessToken```

#### Expected Behavior

I would be prompted that AccessToken needs a value.

#### Actual Behavior

Powershell returned an error stating that the -AccessToken switch does not exist.

#### Additional Information

The latest version of `Connect-DbaInstance` at the master branch [here](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Connect-DbaInstance.ps1) indeed does not have a param/switch for AccessToken.

Yet, the following example [here](https://github.com/sqlcollaborative/dbatools/blob/653f7afcd0b36bfbd0c2f2c14582ae39d852638f/functions/New-DbaAzAccessToken.ps1#L72) for `New-DbaAzAccessToken` shows what should supposedly be a parameter for AccessToken.

**Comment by abjoseph** [comment]
@potatoqualitee Are any updates on this item as I've noticed that the automated bot has marked it stale and will eventually change it to closed.

**Comment by wsmelton** [comment]
What is the issue again?

The `AccessToken` parameter was removed from `Connect-DbaInstance` so we can update the example in `New-DbaAzAccessToken`.
