### ISSUE TITLE
Build Reference Updates

### ISSUE THREAD

**Issue by usoxster** [sqlcollaborative/dbatools#5946]
How often does the build reference get updated?
I need to apply the latest SQL 2016 & 2017 updates but it appears dbatools-buildref-index.json needs to include the following:
Thanks!

2016:
        {
            "Version": "13.0.5382",
            "KBList": "4510807"
        },
        {
            "Version": "13.0.5426",
            "KBList": "4505830"
        }

2017:
        {
            "Version": "14.0.3208",
            "KBList": "4510083"
        },
        {
            "Version": "14.0.3223",
            "KBList": "4508218"
        }

**Comment by wsmelton** [comment]
This information was already added in #5942

**Comment by wsmelton** [comment]
Regarding how often the file is updated; it is updated as we get around to it and then as releases are pushed to the gallery.
