### ISSUE TITLE
[Bug] URL from docs website to GitHub code not correct for the configuration commands

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#5948]
The https://docs.dbatools.io web site has the link on the bottom that points to here (GitHub) this works perfectly for all commands except for the ones within `Configuration` [folder](https://github.com/sqlcollaborative/dbatools/tree/development/functions/configuration)

For this commands the url points to:
https://github.com/sqlcollaborative/dbatools/tree/development/functions/

but it should be:
https://github.com/sqlcollaborative/dbatools/tree/development/functions/configuration

**Comment by wsmelton** [comment]
Huh, why do we have those in a separated folder?

**Comment by ClaudioESSilva** [comment]
Good question @wsmelton .

I also found that `Set-DbatoolsConfig` is not showing up on the docs website

![image](https://user-images.githubusercontent.com/19521315/62569225-49839780-b886-11e9-8fbc-e4ce21154846.png)

**Comment by wsmelton** [comment]
Yeah, the set command not showing up is known issue. That command is a cmdlet so the help is in the dbatools library itself. The way we build the data for `Find-DbaCommand` is not picking up the help due to the scoping issues.

**Comment by ClaudioESSilva** [comment]
I was to slow editing my previous entry 😄

**Comment by wsmelton** [comment]
That ps1 file is just for importing the cmdlet. The code and help for it exists within the dbatools.dll file.

**Comment by wsmelton** [comment]
This has been fixed.
