### ISSUE TITLE
[Bug] New-DbaAzAccessToken broken in PS 6+

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#5966]
### Environmental information

```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18362 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



#### dbatools Module version:

Name    : dbatools
Path    : C:\Users\Shawn Melton\Documents\PowerShell\Modules\dbatools\1.0.30\dbatools.psd1
Version : 1.0.30

Name    : dbatools
Path    : C:\Users\Shawn Melton\Documents\PowerShell\Modules\dbatools\1.0.28\dbatools.psd1
Version : 1.0.28



```
### Report

Command fails to run on PowerShell 6.2
#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

 System.Management.Automation.PSArgumentException: Cannot find type [PSObjectIRenewableToken]: verify that the assembly containing this type is loaded.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : InvalidType: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_New-DbaAzAccessToken,Stop-Function
ErrorDetails          : Cannot find type [PSObjectIRenewableToken]: verify that the assembly containing this type is loaded.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\git\dbatools\internal\functions\flowcontrol\Stop-Function.ps1: line 229
                        at New-DbaAzAccessToken<Process>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 256
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

PSMessageDetails      : 
Exception             : System.Management.Automation.PSArgumentException: Cannot find type [PSObjectIRenewableToken]: verify that the assembly containing this type is loaded.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : 
CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-DbaAzAccessToken<Process>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 247
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.InvalidOperationException: Cannot add type. Compilation errors occurred.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : 
CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-DbaAzAccessToken<Begin>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 165
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: (9,40): error CS0103: The name 'PowerShell' does not exist in the current context
                                            PowerShell psCmd = PowerShell.Create().AddScript(@"param($this)
                                                               ^
                        
TargetObject          : (9,40): error CS0103: The name 'PowerShell' does not exist in the current context
CategoryInfo          : InvalidData: ((9,40): error CS010\u2026the current context:CSDiagnostic) [Add-Type], Exception
FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-DbaAzAccessToken<Begin>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 165
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: (9,21): error CS0246: The type or namespace name 'PowerShell' could not be found (are you missing a using directive or an assembly reference?)
                                            PowerShell psCmd = PowerShell.Create().AddScript(@"param($this)
                                            ^
                        
TargetObject          : (9,21): error CS0246: The type or namespace name 'PowerShell' could not be found (are you missing a using directive or an assembly reference?)
CategoryInfo          : InvalidData: ((9,21): error CS024\u2026ssembly reference?):CSDiagnostic) [Add-Type], Exception
FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-DbaAzAccessToken<Begin>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 165
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: (7,52): error CS0012: The type 'DateTimeOffset' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
                                    public class PsObjectIRenewableToken : IRenewableToken {
                                                                           ^
                        
TargetObject          : (7,52): error CS0012: The type 'DateTimeOffset' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
CategoryInfo          : InvalidData: ((7,52): error CS001\u2026=cc7b13ffcd2ddd51'.:CSDiagnostic) [Add-Type], Exception
FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-DbaAzAccessToken<Begin>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 165
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: (5,26): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
                                    using System.Management.Automation.Runspaces;
                                                 ^
                        
TargetObject          : (5,26): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
CategoryInfo          : InvalidData: ((5,26): error CS023\u2026ssembly reference?):CSDiagnostic) [Add-Type], Exception
FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-DbaAzAccessToken<Begin>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 165
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: (3,26): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
                                    using System.Management.Automation;
                                                 ^
                        
TargetObject          : (3,26): error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
CategoryInfo          : InvalidData: ((3,26): error CS023\u2026ssembly reference?):CSDiagnostic) [Add-Type], Exception
FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-DbaAzAccessToken<Begin>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 165
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

Full error stack from first, initial error:
```

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Cannot find type [PSObjectIRenewableToken]: verify that the assembly containing this type is loaded. ---> System.Management.Automation.PSArgumentException: Cannot find type [PSObjectIRenewableToken]: verify that the assembly containing this type is loaded.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : InvalidType: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_New-DbaAzAccessToken,Stop-Function
ErrorDetails          : Cannot find type [PSObjectIRenewableToken]: verify that the assembly containing this type is loaded.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\git\dbatools\internal\functions\flowcontrol\Stop-Function.ps1: line 229
                        at New-DbaAzAccessToken<Process>, C:\git\dbatools\functions\New-DbaAzAccessToken.ps1: line 256
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

**Comment by andreasjordan** [comment]
Hi @wsmelton - is this still a problem or can we close it?

**Comment by andreasjordan** [comment]
Another question: As we now have the solution with the parameter -AccessToken in Connect-DbaInstance, maybe remove that function from dbatools?

**Comment by wsmelton** [comment]
This command is used by `Connect-DbaInstance` so it won't be removed. This can be closed as we do not support PowerShell 6 now.
