### ISSUE TITLE
[Bug] SqlCredential doc needs updating across the board

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5967]
we now offer more than just windows and sql.

**Comment by wsmelton** [comment]
We do?

**Comment by potatoqualitee** [comment]
yes, we offer MFA in azure, sillz

**Comment by wsmelton** [comment]
I don't think that would be more than just adding examples. A credential is still a credential.... Or maybe I need to see what you mean by updating the docs :grinning:

**Comment by potatoqualitee** [comment]
![image](https://user-images.githubusercontent.com/8278033/63079157-ebb61600-bf3d-11e9-8a40-ec35eb774bf5.png)

>     .PARAMETER SqlCredential
>        Login to the target instance using alternative credentials. Windows and SQL Authentication supported. Accepts credential objects (Get-Credential)

Perhaps something like

> Login to the target instance using alternative credentials. Accepts credential objects (Get-Credential). Windows Authentication, SQL Server Authentication, Active Directory - Password, and Active Directory - Integrated are all supported. For MFA support, please use Connect-DbaInstance.
