### ISSUE TITLE
[Bug] dbainstanceparameter no longer supports .\instance

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5968]

**Comment by wsmelton** [comment]
It seems (the way I'm reading) to be from a period being provided that it is local, and switches it to use NP protocol, based on the warning I get:
```
[10] > Get-DbaDatabase -SqlInstance '.\sql17'
WARNING: [10:15:13][Get-DbaDatabase] Error occurred while establishing connection to NP:.\sql17\sql17 | A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
```


https://github.com/sqlcollaborative/dbatools/blob/653f7afcd0b36bfbd0c2f2c14582ae39d852638f/bin/projects/dbatools/dbatools/Parameter/DbaInstanceParameter.cs#L260-L265

**Comment by potatoqualitee** [comment]
The issue I think, arose from another request where i asked if the weird WSUS named pipes format could be supported.

There's a duplication of the name

I think the fix is easy, I just haven't had the concentration to fix
![image](https://user-images.githubusercontent.com/8278033/63046893-96ddb580-bed3-11e9-9ad4-dce1b559e021.png)

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann can you please take a look at this and fix? I think a lot of people use `.\instance`

**Comment by potatoqualitee** [comment]
i could never figure this one out :(
