### ISSUE TITLE
Show-SqlWhoIsActive sqltext without XML formatting tags

### ISSUE THREAD

**Issue by BartekR** [sqlcollaborative/dbatools#597]
Is this a *feature* OR *bug*: feature

When showing "sqltext" column it could have SQL code without <?query ?> elements. They are helpful in SSMS, but maybe not that much in Show-SqlWhoIsActive? An option maybe?

**Comment by niphlod** [comment]
easily solvable via `Invoke-DbaWhoIsActive -SqlInstance foo -FormatOutput 0 | Out-GridView`
