### ISSUE TITLE
[Bug] Error when using (Connect-DBAInstance).JobServer through Azure Release agent

### ISSUE THREAD

**Issue by GeorgePalacios** [sqlcollaborative/dbatools#5970]
#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.26\dbatools.psd1
Version : 1.0.26

```powershell
LCID             Name             DisplayName                                                                                                                            
----             ----             -----------                                                                                                                            
2057             en-GB            English (United Kingdom)    
```

#### SQL Server: 

```sql
Microsoft SQL Server 2014 (SP3-CU3-GDR) (KB4505422) - 12.0.6293.0 (X64)   May 25 2019 22:45:08   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

```sql
us_english
```

### Report

 

I've been tracking this issue for a few weeks now and am at a loss as to how to move this forward.

For a bit of background we're using Azure Pipeline Release Agents on a Windows VM that is on-premise to run certain automation tasks - in this case we're trying to roll out some new Agent jobs.

I've tracked down the offending code to calling the JobServer collection from the object returned from Connect-DbaInstance. This **only errors when run in an Azure Release agent**

I did manage to reproduce the error a few weeks ago, but this has now stopped working.

This is preventing us using the get-dbaagentjob command in Azure pipelines full stop. The interesting part here is that the code within get-dbaagentjob calls (Connect-DbaInstance).JobServer.Jobs, yet the error is still produced.

$ErrorActionPreference = "Continue" makes no difference.

Using the pipeline option to Ignore the LASTERRORCODE variable makes no difference.

I have managed to find an issue that seems to be related [here](https://feedback.azure.com/forums/908035-sql-server/suggestions/34488658-smo-script-bug-cannot-drop-table-sver) but I can't even see how to confirm that the error on the above page is the one I am receiving.

The code that seems to be being run by the pipeline is:

```
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\vstsagent\A11\_work\_temp\8429f15c-a279-4980-ab9e-7a43f5a7f161.ps1'"
```

I would appreciate any help on how to track this error down further at this stage. Even if this ends up being a pipeline issue rather than a DBATools issue, it would be helpful to document this behaviour and any workarounds.

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Errors Received

2019-08-14T10:07:19.4080494Z format-default : An exception occurred while executing a Transact-SQL 
2019-08-14T10:07:19.4081360Z statement or batch.
2019-08-14T10:07:19.4081522Z     + CategoryInfo          : NotSpecified: (:) [format-default], ExecutionFai 
2019-08-14T10:07:19.4081620Z    lureException
2019-08-14T10:07:19.4081902Z     + FullyQualifiedErrorId : Microsoft.SqlServer.Management.Common.ExecutionF 
2019-08-14T10:07:19.4082021Z    ailureException,Microsoft.PowerShell.Commands.FormatDefaultCommand
2019-08-14T10:07:19.4082107Z  

#### Steps to Reproduce

```Powershell
Import-Module DBATools

$i = Connect-DbaInstance -SQLInstance "Server,port"

$i.JobServer

```

OR

```Powershell
Import-Module DBAtools

get-dbaagentjob -sqlinstance "Server,port"
```

#### Expected Behavior

Return the JobServer details

#### Actual Behavior

Returns an error only in the pipeline

**Comment by potatoqualitee** [comment]
Hey George,
I've seen conversations like this before where everything works except jobs.

https://twitter.com/jdanton/status/1148408925558992896

It's always a permissions issue. Try it with a super admin, and see what you get.

**Comment by GeorgePalacios** [comment]
Thanks Chrissie - it was permissions after all. The error messages did not indicate this in any way which is why we were confused.
