### ISSUE TITLE
Features missing: Install-DbaInstance additional support for client-side tools and Analysis Service

### ISSUE THREAD

**Issue by rishidang200** [sqlcollaborative/dbatools#5971]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

Issue: Features missing in Install-DBAinstance. CONN & BC are not there in feature type also unable to install analysis services. Please help.

**Comment by wsmelton** [comment]
We currently do support installation of SSAS. Client Tools I'm not seeing support for that, but I also do not install those on servers (may just be me).

**Comment by rishidang200** [comment]
Thanks, Shawn. I am able to install CONN & BC after modifying some of the functions and JSON files.
It gives an option to select the SSAS feature, however, It gets failed with error : 
You must provision the system with at least one system administrator (even after running command using sysadmin)

**Comment by wsmelton** [comment]
If you have the code to adjust support for client tool installation then you are more than welcome to submit it in a PR for review.

On SSAS, requires system administrator account be provided for the server. This is not sysadmin in SQL Server instance.

**Comment by rishidang200** [comment]
Thanks, Shawn. I shall submit it soon. However, for the installation of SSAS, I am providing system admin account.
