### ISSUE TITLE
dbatools cannot connect to WinRM over HTTPS

### ISSUE THREAD

**Issue by rngrr** [sqlcollaborative/dbatools#5972]
Hello,

Out DBA's are having issues running Update-DBAInstance against servers where WinRM only listens on HTTPS. They receive following error:

PS C:\> Update-DbaInstance -ComputerName <Redacted FQDN> -Path <Redacted NetworkShare> -Version SQLXX -Credential Domain\Username -Whatif

WARNING: [09:14:31][Update-DbaInstance] Error while looking for SQL Server installations on <Redacted FQDN> |
Connecting to remote server <Redacted FQDN> failed with the following error message : The client cannot
connect to the destination specified in the request. Verify that the service on the destination is running and is
accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most
commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze
 and configure the WinRM service: "winrm quickconfig". For more information, see the about_Remote_Troubleshooting Help
topic.

dbatools server:
==========

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\> (Get-Module dbatools -ListAvailable).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      20     -1

sql server:
======

OS: Win 2012 R2
SQL: SQL Server 2014 Web Edition (64-bit)

PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\> winrm e winrm/config/listener
Listener
    Address = *
    Transport = HTTPS
    Port = 5986
    Hostname = <Redacted FQDN>
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint = 66200320BB820CA97..........
    ListeningOn = <IP Addresses>

PS C:\>

Not sure if dbatools is supported to connect to WinRM HTTPS.

**Comment by rngrr** [comment]
Wireshark points to dbatools connecting to 5985 by default (which is http winrm port). if you have both http (5985) and https (5986) - it will work. If you only have https (5986) - it won't work, because it is not even attempting.

**Comment by potatoqualitee** [comment]
@ClaudioESSilva - i think you added support for something similar. was it this? if not, would you be able to add it?

**Comment by ClaudioESSilva** [comment]
Hey @rngrr,

From your description it seems that you need to use the PsRemote option `-UseSSL`.

You can do a test by running a simple remote command using New-PsSession

``` powershell
$PsSession = New-PSSession -ComputerName "your Instance" -UseSSL
Invoke-Command -Session $PsSession -Script Block {dir} 
```

The native way to test it is to get the current development brach (we have added this option as a configuration but not yet in the gallery) , import the module and run
``` powershell
Set-DbaToolsConfig -Name 'psremoting.pssession.usessl' -Value $true
```
This will make the internal `Invoke-Command2` function to use the `- UseSSL` parameter when using the remote commands. 

And try to run the `Update-DbaInstance` again

If it fails try this together with the FQDN (if you are not using it yet) 

Let us know about the result.

**Comment by wsmelton** [comment]
@ClaudioESSilva your feature addition was published to the Gallery already. It is available in 1.0.31+ builds.

**Comment by ClaudioESSilva** [comment]
Thanks for the correction!

**Comment by potatoqualitee** [comment]
Will close as fixed - just gotta download the newest version and use the recommended approach. Thanks all!

**Comment by rngrr** [comment]
It works like a charm!!

I tried on 1.0.20 and it worked! 

Thank you so much.
