### ISSUE TITLE
Run Show-WhoIsActive without sysadmin privileges

### ISSUE THREAD

**Issue by BartekR** [sqlcollaborative/dbatools#598]
Is this a *feature* OR *bug*: enhancement

Show-WhoIsActive requires sysadmin to run. While it's OK for installation it's a bit frustrating when I can run sp_WhoIsActive using SSMS (granted privileges for an account) and can't using Show-WhoIsActive.

**Comment by potatoqualitee** [comment]
now no admin requirements 💃
