### ISSUE TITLE
[Bug] Import-Module fails to import dbatools when it is a RequiredModule in the manifest

### ISSUE THREAD

**Issue by pauby** [sqlcollaborative/dbatools#5989]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14409.1005                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14409.1005                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

#### dbatools Module version:

Name    : dbatools
Path    : C:\Users\<USER>\Documents\WindowsPowerShell\Modules\dbatools\0.9.834\dbatools.psd1
Version : 0.9.834
```

Note the dbatools version installed is the one that works for me. I have tried 1.0.0, 1.0.32 and 1.0.34 that don't work.

#### SQL Server: 
This isn't related to SQL Server.

### Report

I have a very bizarre issue with dbatools that I'm struggling to understand. I have two modules - module_a and module_b. module_a has module_b as a `RequiredModule` in the manifest. module_b has dbatools as a `RequiredModule` in the module manifest (so they are chained together in that respect).

If I install dbatools, versions up to 0.9.834, it imports without issue if I run `Import-Module module_a` (which in turn imports `module_b` which in turn imports `dbatools` through the `RequiredModules` key in the manifests). If I install any version of dbatools from 1.0.0 onwards (tried 1.0.0, 1.0.32, 1.0.34) and run `Import-Module module_a` I get the following error:

```
Import-Module : Could not import
C:\Users\<USER>\Documents\WindowsPowerShell\Modules\dbatools\1.0.0\bin\smo\Microsoft.SqlServer.BatchParser.dll :
Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'Microsoft.SqlServer.BatchParser.dll' or one of its dependencies. The specified module could not be found."
At C:\Users\<USER>\Documents\WindowsPowerShell\Modules\dbatools\1.0.0\internal\scripts\smoLibraryImport.ps1:132 char:17
+                 [Reflection.Assembly]::LoadFrom($assemblyPath)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

At line:1 char:1
+ ipmo module_b
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

I get the same if I run `Import-Module module_b`.

If I remove dbatools from the `RequiredModules` in module_b and add the following to the top of module_b.psm1:

```
$dbatools_serialimport = $true
Import-Module dbatools
```

And then run `Import-Module module_b` it does import. But `Import-Module module_a` still fails with the same error.

As an aside, after importing using `Import-Module module_b` and then running `get-dbatoolsconfig -name serialimport` I get:

```
Module: import

FullName            Value Description
--------            ----- -----------
import.serialimport False Enabling this will cause the module to perform import in a serial manner, not parallelizin...
```

I would expect the `value` to be True?

I can raise an issue for this but I thought I'd bring it here as it's so weird I think it's something straightforward.

Note that the sqlps or sqlserver module are not being imported anywhere ([asked to confirm by wsmelton](https://sqlcommunity.slack.com/archives/C1M2WEASG/p1566424916002900?thread_ts=1566415314.483500&cid=C1M2WEASG))

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

Error is shown in the Report above.

#### Steps to Reproduce

Steps shown in Report above.

#### Expected Behavior

I expected dbatools to import normally.

#### Actual Behavior

See Report above - dbatools fails to import at any other version beyond 0.9.834.

**Comment by pauby** [comment]
@wlansdowne Post code between three backticks - so 3 backticks, newline, post your code, newline, 3 backticks.

**Comment by wsmelton** [comment]
If this is still an issue can you verify that `Visual C++ Redistributable Packages for Visual Studio 2013` is installed on the machine? We have seen some folks install this and it magically fixes it...just adding it here as I do not know that it is a be-all fix.
