### ISSUE TITLE
[Feature] Ability to set permissions on a custom server-level role or database role

### ISSUE THREAD

**Issue by jmwithers1986** [sqlcollaborative/dbatools#6004]
First, i would like to say big thanks all those involved in DBATOOLS! 

I've used quite a few of the different commands now but i seem to of come across one that doesn't exist. 

I used New-DbaDbRole to create a custom database role but i can't see a parameter or another command to assign permissions to that role i.e. GRANT EXECUTE TO db_executor.

Instead, I had to use SQLCMD::
Invoke-Sqlcmd -ServerInstance $Instance -Database $Database -Query "GRANT Execute TO db_executor"

Have i missed a DBATOOLS command that should be used or is there not one?

**Comment by jmwithers1986** [comment]
First, i would like to say big thanks all those involved in DBATOOLS! 

I've used quite a few of the different commands now but i seem to of come across one that doesn't exist. 

I used New-DbaDbRole to create a custom database role but i can't see a parameter or another command to assign permissions to that role i.e. GRANT EXECUTE TO db_executor.

Instead, I had to use SQLCMD::
Invoke-Sqlcmd -ServerInstance $Instance -Database $Database -Query "GRANT Execute TO db_executor"

Have i missed a DBATOOLS command that should be used or is there not one?

Many thanks,
Jay.

**Comment by wsmelton** [comment]
@jmwithers1986 at this time we do not have any commands for setting permissions on a given role/login/user.

**Comment by jmwithers1986** [comment]
Shame, I'll have to use SQLCMD for now.
Keep up the good work!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wsmelton** [comment]
Why would you need to use `Invoke-Sqlcmd`? Note that using dbatools and sqlserver module together will give you various issues on our module, they do not play well together in the same session.

You can always use `Invoke-DbaQuery` to run one-off queries or SQL files.
