### ISSUE TITLE
-force would be useful for Restore-DbaDatabase

### ISSUE THREAD

**Issue by schittli** [sqlcollaborative/dbatools#6007]
**Thanks a lot for this really great PowerShell Module!,**
while T-SQL still behaves like a decades-old technology, dbatools brings a refreshing breeze into the SQL Server world.
I hope that you are paid by Microsoft, because dbatools brings a great product improvement, which is essential when choosing a modern DB Server.

### Summary of new feature

Because most PowerShell commands support `-force`, I guess it would be in its spirit to support this parameter in `Restore-DbaDatabase` so that it just tries to reach the intended goal:
```
Restore-DbaDatabase -force …
```
For example, it should automatically try to delete Snapshots.

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.
```
λ  [String](Get-Module -Name dbatools | select -ExpandProperty Version)
1.0.35
```

**Comment by wsmelton** [comment]
While this is true implementing `Force` parameter in restore command itself is difficult to implement. When you look at all the operations we handle in doing the restore and the various situations that can prevent any of those operations from completing; becomes a large task to maintain and ensure consistency. Not exactly simply like overwriting a file or just dropping a snapshot.

**Comment by schittli** [comment]
Thank you very much for your appraisal of this suggestion!
