### ISSUE TITLE
copy-sqldatabase bug: withreplace not working properly

### ISSUE THREAD

**Issue by mbourgon** [sqlcollaborative/dbatools#601]
### Is this a *feature* OR *bug*:
bug

### System Details

- Operating system name and version:
Windows 7 SP1
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      3.0                                                                                     
WSManStackVersion              3.0                                                                                     
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                     4.0.30319.42000                                                                         
BuildVersion                   6.2.9200.16481                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0}                                                                         
PSRemotingProtocolVersion      2.2                                                                                     
```

- Output of dbatools version:

```
Sorry, throws the error "item with the same key has already been added".  I used the Invoke-expression install on 1/27/2017
```

- SQL Server version for source/target
2008R2 / 2016SP1

### Steps to Reproduce
On the source server (2008 R2):

CREATE DATABASE [Cube_Query_History] ON  PRIMARY 
( NAME = N'Cube_Query_History', FILENAME = N'F:\SQL_Data\Cube_Query_History.mdf' , SIZE = 50176KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'Cube_Query_History_log', FILENAME = N'F:\SQL_Logs\Cube_Query_History_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 102400KB )
GO

On the target server (2016sp1), I created a stub database:
CREATE DATABASE [Cube_Query_History]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cube_Query_History', FILENAME = N'K:\SQL_Data\Cube_Query_History.mdf' , SIZE = 50176KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'Cube_Query_History_log', FILENAME = N'L:\SQL_Logs\Cube_Query_History_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 102400KB )
GO

We then ran the copy-sqldatabase, using -withreplace, and got this error:

### Action Results
(note there is no F on the target server)
System.Management.Automation.MethodInvocationException: Exception calling "SqlRestore" with "1" argument(s): "Restore failed for Server 'my-tar-get-server'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Restore failed for Server 'my-tar-get-server'.  ---> Microsoft.SqlServer.Management.Smo.SmoException: System.Data.SqlClient.SqlError: Directory lookup for the file "F:\SQL_Data\Cube_Query_History.mdf" failed with the operating system error 3(The system cannot find the path specified.).

### Expected Results
Restore the database to K/L

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by ctrlbold** [comment]
Really great bug report, @mbourgon! Thank you. It'll be super helpful.

I'm not sure how you got the dbatools version error, but **Get-Module dbatools** should work. If not, try **Get-Module dbatools | Select \* **

**Comment by ctrlbold** [comment]
I'm gonna try to get this one in by today's release, too

**Comment by mbourgon** [comment]
Any luck? (We're migrating 10+ servers in the next two weeks, this would make life simpler)  MANY MANY MANY thanks!

**Comment by ctrlbold** [comment]
Still working on it. Was hoping it'd be a quick fix but it's all complex. Will keep you updated

**Comment by mbourgon** [comment]
Sorry to hear. Thanks!

**Comment by ctrlbold** [comment]
Check out this branch! I'll get some testers (if you can, that'd be nice) but the fix should be in the release coming out tomorrow https://github.com/sqlcollaborative/dbatools/tree/copy-sqldatabase-fix-withreplace

**Comment by mbourgon** [comment]
Woohoo! We'll test it out today!

**Comment by ctrlbold** [comment]
If you do it before the proper release, you can download a zip with it here: https://github.com/sqlcollaborative/dbatools/archive/copy-sqldatabase-fix-withreplace.zip

**Comment by ctrlbold** [comment]
Passed our tests :) Please let us know how it goes for you! this bugfix is now in the development branch
