### ISSUE TITLE
Add a table name filter to the Set-DbsDbCompression and Test-DbsDbCompression

### ISSUE THREAD

**Issue by ggoncz** [sqlcollaborative/dbatools#6015]
### Summary of new feature

I have to regularly compress more than 100 databases. In a database I can compress everything but in the other DB I can compress only the objects where the name of the tables begin with a string ('XYZ%') so I can't compress the whole database. A new parameter would be fine to filter the table names.

### Proposed technical details (if applicable)

I modified the Test-DbsDbCompression and the Set-DbaDbCompression. I added a new filter parameter and some new lines. I attached my modified scripts. Maybe you can use my codes.

### Latest version of dbatools as of writing

1.0.40

[functions.zip](https://github.com/sqlcollaborative/dbatools/files/3579325/functions.zip)

**Comment by jpomfret** [comment]
Sweet - I like this idea, I'll take a look :)

**Comment by andreasjordan** [comment]
Is this maybe already implemented?
