### ISSUE TITLE
[Bug] Locale usage with Invoke-DbaDbDataMasking not taken into account after first run

### ISSUE THREAD

**Issue by JFD01** [sqlcollaborative/dbatools#6017]
### Environmental information

```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14393.3053
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3053
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### dbatools Module version:

Name    : dbatools
Path    : C:\PSRepo\dbatools\dbatools.psm1
Version : 1.0.38
```

```powershell
LCID             Name             DisplayName
----             ----             -----------
1036             fr-FR            Français (France)
```

#### SQL Server: 

```sql
Microsoft SQL Server 2016 (SP2-CU4) (KB4464106) - 13.0.5233.0 (X64)   Nov  3 2018 00:01:54   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
Français
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

None

#### Steps to Reproduce

Invoke-DbaDbDataMasking -SqlInstance SERVER\INST_NAME -Database DB -FilePath C:\Temp\DataMaskingConfig.json -Confirm:$false -Locale it

=> you get masked italian email adresses / names

2nd run : I change Locale from it (Italy) to fr (France)

Invoke-DbaDbDataMasking -SqlInstance SERVER\INST_NAME -Database DB -FilePath C:\Temp\DataMaskingConfig.json -Confirm:$false -Locale fr

=> you still get masked italian email adresses / names instead of french ones

#### Expected Behavior

Getting french email adresses / names on 2nd run

#### Actual Behavior

Got italian email adresses / names instead of french ones on 2nd run

#### Workaround

Restart Powershell and run Invoke-DbaDbDataMasking -Locale fr at first run

**Comment by potatoqualitee** [comment]
but but... @sanderstad do you have time to work on this?
