### ISSUE TITLE
[Bug] Download from GitHub not detected by import

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#6022]
We have set where we only look for `.git` directory when having the module bypass use of `allcommands` file. Downloading the module from GitHub now won't include the `.git` folder, it only has `.github`.

Import process should include looking for this directory as well unless there is are reason we are not?

https://github.com/sqlcollaborative/dbatools/blob/de150c789285f82678cd87ba5558b0d93c9a32e5/dbatools.psm1#L179-L185

**Comment by potatoqualitee** [comment]
Great question! In the last Twitter poll, 20% of our audience said they use the zip for normal installs. .git is there when you clone the directory, which is why we check specifically for that. Otherwise, we'd slow down 20% of installs by searching for github.

**Comment by SQLGB** [comment]
@wsmelton @potatoqualitee Does this mean that ```allcommands``` **is** now used when downloading and importing the development branch (unless you manually add a ```.git``` directory)?  If so, it might explain the situation I had while reviewing and commenting on https://github.com/sqlcollaborative/dbatools/issues/6003 last week.

**Comment by wsmelton** [comment]
It has always been used @SQLGB as we have only ever had it look for `.git` when we implemented the all commands file. You don't get that `.git` folder unless you do `git clone`.
