### ISSUE TITLE
Security Benchmarks commands

### ISSUE THREAD

**Issue by g-kannan** [sqlcollaborative/dbatools#6027]
### Summary of new feature
We were able to get the CIS benchmarks results mostly through individual dbatools commands. Please check if it would be worth adding a separate section for Security benchmarks. Few auditors have tools to generate report(eg. CIS CAT Pro) though they dont have the flexibility like PowerShell.

### Proposed technical details (if applicable)
https://www.cisecurity.org/benchmark/microsoft_sql_server/
http://www.itsecure.hu/library/image/CIS_Microsoft_SQL_Server_2016_Benchmark_v1.0.0.pdf

Attached our script prepared using few other modules for taking these benchmarks. 
[CIS_SQLServer.txt](https://github.com/sqlcollaborative/dbatools/files/3587807/CIS_SQLServer.txt)

### Latest version of dbatools as of writing
1.0.21

**Comment by wsmelton** [comment]
@g-kannan you can check sqlcollaborative/dbachecks as CIS is being implemented in that module for building reports and performing the scans.

This project is being used to directly track that progress. https://github.com/sqlcollaborative/dbachecks/projects/1
