### ISSUE TITLE
A new switch to turn off the user friendly size display in Get-DbaDbCompression

### ISSUE THREAD

**Issue by ggoncz** [sqlcollaborative/dbatools#6031]
### Summary of new feature

I'm using the Get-DbaDbCompression script to collect the data from 200 SQL databases but I can't use the "user friendly" SizeCurrent column easily. With this current values I have to convert these data to bytes all the time.

### Proposed technical details (if applicable)

Could you please add a new switch to turn off this automatic conversation? It would be very useful when I save the list to a DB or and spreadsheet.

### Latest version of dbatools as of writing

1.0.40

**Comment by potatoqualitee** [comment]
Hey ggoncz,
Thanks for the report! I need to write a blog post about this. So sorry you've been doing it the hard way. Here is how to easily work with our special type `dbasize`:

https://github.com/sqlcollaborative/dbatools/issues/5817

**Comment by potatoqualitee** [comment]
Basically it's this, but that post has code you can copy/paste.

![image](https://user-images.githubusercontent.com/8278033/64610349-563c6380-d3cf-11e9-8b92-78d108ba9c08.png)

**Comment by ggoncz** [comment]
Thanks :)
