### ISSUE TITLE
Restore-DbaDatabase: Post-Restore Script

### ISSUE THREAD

**Issue by Chago2016** [sqlcollaborative/dbatools#6035]
### Summary of new feature

Add a new parameter to Restore-DbaDatabase to execute a T-SQL script after a database is successfully restored.  This would be very helpful when restoring databases to different environments.  E.g., Restore a production version of a database to a development server.  Post-restore, execute a T-SQL script that removes production users and creates new ones applicable to the new environment.

### Proposed technical details (if applicable)

N/A

### Latest version of dbatools as of writing

1.0.39

**Comment by wsmelton** [comment]
Is there a reason you cannot just call `Invoke-DbaQuery` after the Restore command completes?

**Comment by Chago2016** [comment]
> Is there a reason you cannot just call `Invoke-DbaQuery` after the Restore command completes?

No reason I can't use that.  Just thought integrating the query execution might be a good idea.

**Comment by wsmelton** [comment]
I have not seen anyone requiring a post-script use in restore processes as it stands right now. I think adding in execution of post-scripts should be part of the user's scripting process and steps. Adding in a post-script functionality would add in complexity that I don't think is worth the effort, at least right now.

Closing this but if interest is gathered for this feature (by thumbs up) then we can reconsider it down the road.

**Comment by Chago2016** [comment]
Totally understand.  Thank you for addressing the suggestion.
