### ISSUE TITLE
Restore-DbaDatabase Add Keep_Replication parameter

### ISSUE THREAD

**Issue by ggsince88** [sqlcollaborative/dbatools#6039]
### Summary of new feature

It would be great to have WITH KEEP_REPLICATION as a parameter for Restore-DbaDatabase. I am doing multiple restores from PROD backups to a TEST environment where keeping the replication configuration would be useful. 

### Proposed technical details (if applicable)

This would be similar to how MS SQL server powershell module [Restore-SqlDatabase](https://docs.microsoft.com/en-us/powershell/module/sqlserver/restore-sqldatabase?view=sqlserver-ps) would work. The parameter is called -KeepReplication. 

### Latest version of dbatools as of writing

dbatools 0.9.809

**Comment by potatoqualitee** [comment]
Great idea! Thank you. @Stuart-Moore, @nvarscar, @sql-williamd  would any of you have time within the next few weeks to add this?

thanks much
