### ISSUE TITLE
Copy-DbaDatabase - Prevent -Force option dropping the databases if -source and -destination are same

### ISSUE THREAD

**Issue by hpiili** [sqlcollaborative/dbatools#6050]
### Summary of new feature

* If user by accident executes Copy-DbaDatabase -source INSTANCE -destination INSTANCE -Force, where source and destination are the same, this tool will drop the source databases.

I am proposing that this tool should check that source and destination cannot be equal.

### Latest version of dbatools as of writing

* 1.0.46

**Comment by wsmelton** [comment]
I'll disagree with adding this feature. We can't account for "accidents" in use of PowerShell, that is why we have `-WhatIf` in the commands. User's should be validating the command is going to do what they think it will.

As well, we cannot assume that when the source and destination are same that they do not desire the original database to be dropped.

**Comment by hpiili** [comment]
I understand you point.
There are some options that in combination do not make any sense in my opinion and cause havoc.

-Source INSTANCE1 -Destination INSTANCE2 -Force and -AllDatabases are defined
and INSTANCE1 = INSTANCE2 
and -NewName is empty

It would be nice to protect ordinary chums like me from ourselves.
