### ISSUE TITLE
[Bug] export-dbalinkedserver not working in a sql clustered instance

### ISSUE THREAD

**Issue by cookiemonsterdba** [sqlcollaborative/dbatools#6053]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                                                          
----                           -----                                                                                                                                                                                          
PSVersion                      5.1.14409.1005                                                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                        
BuildVersion                   10.0.14409.1005                                                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                                                        




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.47\dbatools.psd1
Version : 1.0.47

```

```powershell
# Replace with output of Get-Culture
```
LCID             Name             DisplayName                                                                                                                                                                                 
----             ----             -----------                                                                                                                                                                                 
1030             da-DK            Danish (Denmark) 

#### SQL Server: 

```sql
Microsoft SQL Server 2014 (SP2-CU10-GDR) (KB4052725) - 12.0.5571.0 (X64) 
	Jan 10 2018 15:52:08 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

```

```sql
us_english
```

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Steps to Reproduce

Windows Cluster with 2 nodes. 1 sql server instance.

Export-DbaLinkedServer -SqlCredential $cred -SqlInstance $sqlname -Verbose -credential $cred -Debug . Same issue with Export-dbacredential.

Exporting the linked servers for a clustered instance

VERBOSE: [09:23:53][Export-DbaLinkedServer] Getting NetBios name for servername.
DEBUG: 12854 | [09:23:53][Export-DbaLinkedServer] Getting NetBios name for servername.
VERBOSE: [09:23:53][Export-DbaLinkedServer] Checking if Remote Registry is enabled on servername.
DEBUG: 12857 | [09:23:53][Export-DbaLinkedServer] Checking if Remote Registry is enabled on servername.
DEBUG: 76937 | [09:23:53][Invoke-Command2] Creating new Default session [dbatools_Default_04b58717-1c2b-4d9f-9c03-73671a03555b] for servername
WARNING: [09:23:53][Export-DbaLinkedServer] Can't connect to registry on servername. | Connecting to remote server servername failed with the following error message : WinRM cannot process the request. The following error with 
errorcode 0x80090322 occurred while using Kerberos authentication: An unknown security error occurred.

**Comment by LeSnowTiger** [comment]
Hey Cookiemonsterdba.

I had the same problem. I could fix it with the following:

1. Connecto to Server
2. Execute the following im Powershell:
`winrm get winrm/config `
3. Check the IPv4 and IPv6 Filter. For us it needed to be "*"
4. Open the local GPO Editor (mmc.exe -> File -> Add Snap In)
5. Set "Allow remote server management trough WinRM" to "Not Configured"
6. Restart the WinRM Service
7. Run in powershell:
`winrm quickconfig`
8. Test the connection local with:
`Test-WSMan -ComputerName localhost`
9. Try to run the dba command again.

**Comment by sqllensman** [comment]
The issues with both Export-DbaLinkedServer and Export-DbaCredential are due to trying to make Remote Registry connections to the ClusterName rather than the current host
Currently the following code is used

```
                        Write-Message -Level Verbose -Message "Getting NetBios name for $instance."
                        $sourceNetBios = Resolve-NetBiosName $server
```

We then use Invoke-Command2 to read registry on  $sourceNetBios 

As  $sourceNetBios  will be the cluster name rather than a physical Server this fails

Changing code to 

```
                        Write-Message -Level Verbose -Message "Getting NetBios name for $instance."
                        if ($server.IsClustered) {
                            $sourceNetBios = $server.ComputerNamePhysicalNetBIOS
                        } else {
                            $sourceNetBios = Resolve-NetBiosName $server
                        }
```

will allow the calls to try connecting to the current active host

**Comment by potatoqualitee** [comment]
@wsmelton - i was thinkng when i finally get back into things, ill probably disable stalebot and reopen all of these since like jan 1, which is enough time after 1.0. wha tyou think?

**Comment by wsmelton** [comment]
I wouldn't open all of them, at least unless they still exists as a bug.

If the original author or someone hasn't confirmed it still exists I would believe they can be left closed.

**Comment by cookiemonsterdba** [comment]
Hola!
Sorry for late reply. Well I was not able to make it work in the cluster at least (no problem on single instances) using netbios or anything, so but I just skipped the failing parts of exportdbainstance, which if I recall properly was anything trying to use registry & cluster netbios name such as linked servers a couple of other subtasks.
Thanks for your great effort on best automation pw for sql ever ;)
Alfonso

Enviado desde Yahoo Mail para iPhone


El domingo, julio 26, 2020, 5:28 p. m., Shawn Melton <notifications@github.com> escribió:




I wouldn't open all of them, at least unless they still exists as a bug.

If the original author or someone hasn't confirmed it still exists I would believe they can be left closed.

**Comment by andreasjordan** [comment]
Hi @cookiemonsterdba : Are you still around here? I will try to set up a cluster and try to solve this.

**Comment by andreasjordan** [comment]
I've taken that proposed change from @sqllensman , but changed Resolve-NetBiosName to affect all commands using Resolve-NetBiosName at once.

**Comment by cookiemonsterdba** [comment]
Hola!
Thanks… I can try the patch in one of my clusters
SaludosAlfonso


Enviado desde Yahoo Mail para iPhone


El lunes, junio 14, 2021, 10:26 a. m., Andreas Jordan ***@***.***> escribió:




I've taken that proposed change from @sqllensman , but changed Resolve-NetBiosName to affect all commands using Resolve-NetBiosName at once.

**Comment by andreasjordan** [comment]
I even have a workaround for you that should work right now without waiting for the new release of dbatools:
```
$server = Connect-DbaInstance -SqlCredential $cred -SqlInstance $sqlname
$server.ComputerName = $server.ComputerNamePhysicalNetBIOS
Export-DbaLinkedServer -SqlInstance $server
```
