### ISSUE TITLE
Change the steam icon to a robot on dbatools.io front page

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#6054]
👍

**Comment by wsmelton** [comment]
"steam icon"?

>

**Comment by garyhampson** [comment]
The graphic above "automation is awesome" is very similar to the logo for Steam. https://store.steampowered.com/

**Comment by garethnewman** [comment]
This has been fixed - I have no idea how to PR it :D

**Comment by potatoqualitee** [comment]
thanks so much ! will close now
