### ISSUE TITLE
Add 2019 versions to the build ref

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#6059]
### Summary of new feature
Not sure if this is a new feature/enhancement or a bug. There is no 2019 versions in the build ref yet. Can this be added? Got the below off of http://sqlserverbuilds.blogspot.com/#sql2019x.
(This can be assigned to me if they can be added... 😄 

https://sqlcollaborative.github.io/builds

- 15.0.1900.47 - Microsoft SQL Server 2019 Release Candidate Refresh for Big Data Clusters only (RC1.1)
- 15.0.1900.25 - Microsoft SQL Server 2019 Release Candidate 1 (RC1)
- 15.0.1800.32 - Microsoft SQL Server 2019 Community Technology Preview 3.2 (CTP 3.2)
- 15.0.1700.37 - Microsoft SQL Server 2019 Community Technology Preview 3.1 (CTP 3.1)
- 15.0.1600.8 - Microsoft SQL Server 2019 Community Technology Preview 3.0 (CTP 3.0)
- 15.0.1500.28 - Microsoft SQL Server 2019 Community Technology Preview 2.5 (CTP 2.5)
- 15.0.1400.75 - Microsoft SQL Server 2019 Community Technology Preview 2.4 (CTP 2.4)
- 15.0.1300.359 - Microsoft SQL Server 2019 Community Technology Preview 2.3 (CTP 2.3)
- 15.0.1200.24 - Microsoft SQL Server 2019 Community Technology Preview 2.2 (CTP 2.2)
- 15.0.1100.94 - Microsoft SQL Server 2019 Community Technology Preview 2.1 (CTP 2.1)
- 15.0.1000.34 - Microsoft SQL Server 2019 Community Technology Preview 2.0 (CTP 2.0)

**Comment by wsmelton** [comment]
Because it is not production we have not added it.

**Comment by potatoqualitee** [comment]
does it need to be in production to be added? I think if it's useful for anyone's current environment, we can add. tho i can also see how that could introduce mess to the build website

**Comment by wsmelton** [comment]
No, that is just the decision we made while back during CTP. It would have required constantly updating that based on when they released CTPs. Since it is RC, I'm find with just adding those, but not the CTP releases.

**Comment by wsmelton** [comment]
Although, @niphlod would have to verify if RC can be added. Not sure if it would pick it up properly.

**Comment by jpomfret** [comment]
I saw some 2017 pre-RTM builds on this page, that's why I wondered if it would be time to add 2019, or if you wait til RTM.

![image](https://user-images.githubusercontent.com/981370/65525338-57848a80-debd-11e9-9098-c2e0f38c679f.png)

**Comment by jpomfret** [comment]
Sweet! 

(That will make my presentation demo look better next week - so I appreciate it 😄). I'll assign it to myself and get them added to the json later today!
