### ISSUE TITLE
[Bug] Get-DbaRegisteredServer Does Not Exclude Sub-Groups

### ISSUE THREAD

**Issue by SQLNerd** [sqlcollaborative/dbatools#6070]
### Environmental information

There was no output from the command.

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
Microsoft SQL Server 2016 (SP2-CU8) (KB4505830) - 13.0.5426.0 (X64) 
	Jul 21 2019 21:16:47 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

### Report

 
There's no way to exclude subgroups when using Get-DbaRegisteredServer. The attached Zip file includes a screenshot of the relevant area of my CMS and the Trial_n.txt files show the PowerShell sessions where I try 2 different ways to exclude the subgroups. In both cases, the subgroups are returned.

The sessions are clean launches of PowerShell.exe.

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

No errors.

#### Steps to Reproduce

See Trial_1.txt and Trial_2.txt in the attached Zip file.

#### Expected Behavior

I expected to get *one* result, EHRDB-Train-L.

#### Actual Behavior
The command returned 3 results: the desired item plus the servers in the subgroup.

[Bug_Report.zip](https://github.com/sqlcollaborative/dbatools/files/3654582/Bug_Report.zip)

**Comment by awickham10** [comment]
It looks like this is happening when -Group and -ExcludeGroup are combined. When using -ExcludeGroup by itself using Training\%Nodes is excluded without an issue. I'll take a look at it.
