### ISSUE TITLE
SSMS Installer

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbatools#6073]
### Summary of new feature
Module to install SSMS on a computer

* Clear/concise description of what the problem is that the new feature can solve.
Install SSMS on a computer

### Proposed technical details (if applicable)
Have installer on a network share and install to a remote computer quietly with or without a restart

* e.g. Blog post reference that shows example code or functionality
Blog forthcoming probably next week

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.

**Comment by wsmelton** [comment]
I see this as more of a sore to deal with than a time saving command for users to utilize. The installer for SSMS is not always smart enough to deal with dependencies, especially when you go from major versions (e.g. 17 to 18).

Overall though I would consider this out of scope because you should not be deploying desktop applications to production servers. The module is more for SQL Server management and not necessarily around the application tools....we technically want you to use this module over using SSMS 😁 .

The flags though are very basic, and limited. When you are running the installer from CLI you will have to read the log back to really determine why a given installation failed or hit an issue.

![image](https://user-images.githubusercontent.com/11204251/65785927-230e0a00-e11b-11e9-8cbf-cc177f557c37.png)

**Comment by tboggiano** [comment]
I assume we would keep this to the newer versions of SSMS.  But this something you don't want to feel free to close out.  I only threw out as an idea because I did have to write something to do this in my environment for desktop machines.  So I thought I would see if there was interest in having it avaialble in dbatools or not.

**Comment by wsmelton** [comment]
Well in order to support installation the command will have to properly handle errors thrown by the installer, or at most read back in the install log to provide some information on why it may have just stopped for no visible reason.

**Comment by garethnewman** [comment]
personally I'd like to see this, it may not be the most used command but it would be useful for some. If it gets approved I'll happily create it.

**Comment by potatoqualitee** [comment]
Seems a few ppl want this. I'm curious as to if Install-KbUpdate can install it.

**Comment by potatoqualitee** [comment]
Which meannnsss that it would be Invoke-DscResource, and that the command would require PS 5.1 on the remote. Wait, but would you even want that if it installs as system? Probably not.

**Comment by wsmelton** [comment]
DSC has issues with the installer. It won't actually install on systems I've tried.

**Comment by wsmelton** [comment]
Why would you use kb install command?

**Comment by Liturgist** [comment]
PowerShell already has many `Install-*` commands. Why can PowerShell not install SSMS and other applications yet? We have to go to a NuGet server for PowerShell, a PyPI for Python, standalone .msi or .exe for other applications, or <other>. Doesn't Microsoft Software Center (Systems Center) install applications? Any chance of some consolidation here?

**Comment by wsmelton** [comment]
Powershell does not have native install commands for software, never has.

**Comment by tboggiano** [comment]
I have a way to install this using powershell, we would just need away to read for errors like Shawn mentioned when I first opened the issue if the kb installer doesn't work.  That's the reason I opened the ticket is because I wrote a way to install it and uninstaller so you install say 18.x and uninstall 17.x.  I would be more than happy to put what I have into dbatools format for a starting point.

**Comment by dzsquared** [comment]
This might be a nice use case for winget: https://docs.microsoft.com/en-us/windows/package-manager/winget/

`winget install ssms`

**Comment by wsmelton** [comment]
That will only be for Windows 10, not servers.

**Comment by dzsquared** [comment]
> That will only be for Windows 10, not servers.

argh, I keep forgetting the Win10 vs ServerOS restriction about winget.

**Comment by potatoqualitee** [comment]
Yeah, upon second thought, I think this is better suited to be handled by choco or winget
