### ISSUE TITLE
Start-DbaMigration DBMail AccountName - SMTPServer

### ISSUE THREAD

**Issue by Ash-chch** [sqlcollaborative/dbatools#6084]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools
Hi there,

I recently used Start-DbaMigration to migrate everything except databases from SQL 2012 to SQL 2017. It has done the job very well however I noticed that for all DBMail account profiles, it put "localhost" for SMTP Server Address instead putting actual SMTP server value as in source server.

Can you please advise if it is expected behavior or I am missing anything.

Regards,
Ash

**Comment by wsmelton** [comment]
Could not answer that completely, only to say we do not hard code any values in the code. So we would not be putting `localhost` unless it was picked up on your source server.

**Comment by Ash-chch** [comment]
> Could not answer that completely, only to say we do not hard code any values in the code. So we would not be putting `localhost` unless it was picked up on your source server.

I see ok. Then its strange because we use smtp server for all dbmail profiles and it was converted to localhost for all of them. I tested on one more server and same result. so value assignment is not working properly.

**Comment by wsmelton** [comment]
If you see it doing something that is believed to be a bug you can create a new issue and provide the details we have in the template.
