### ISSUE TITLE
[Bug] Invoke-DbaQuery doesn't handle binary data correctly 

### ISSUE THREAD

**Issue by devondba** [sqlcollaborative/dbatools#6088]
#### SQL Server: 
Microsoft SQL Server 2014 - 12.0.2000.8 (X64) 	Feb 20 2014 20:04:26 	Copyright (c) Microsoft Corporation	Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: ) (Hypervisor)	

### Report

Whilst using Invoke-DbaQuery I have found it doesn't return binary data correctly. Rather than getting the data from the column I'm passed a translated version ie and when exported to csv (export-csv) "System.Byte[]" is returned instead.

I appreciate the function doesn't use Invoke-Sqlcmd and it's based on Invoke-Sqlcmd2 but I wonder if the limitation is similar. With Invoke-Sqlcmd [-MaxCharLength <Int32>] and [-MaxBinaryLength <Int32>] have a limit set to 4,000 characters and 1,024 bytes respectively, I'm guessing that the internal query in use operates in a similar way.

https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps

I've changed my code to use Invoke-Sqlcmd with the character and binary lengths defined and it works perfectly. There are other subtle issues that aren't quite right so I'd like to use Invoke-DbaQuery instead if this can be addressed:

                        $QueryArgs = @{
                                        ServerInstance = $Server
                                        database = $DBName
                                        InputFile = $s.FullName
                                        AbortOnError = $True
                                        MaxCharLength = ([int]::MaxValue)
                                        MaxBinaryLength = ([int]::MaxValue)
                                        }
                        $ExportArgs = @{
                                        Path = $OutputRoot + '\' + $s.BaseName + '.csv'
                                        NoTypeInformation = $True
                                        }

                        Invoke-Sqlcmd @QueryArgs | Export-Csv @ExportArgs

I've tried getting to grips with what is happening in the function but can't work out how to fix I'm afraid. Running the query directly through Invoke-DbaAsync returns the same issue:

function Invoke-DbaAsync {...
}

#Connection for sql
$connDbaInstanceParams = @{
                    SqlInstance   = "myinstance"
                    Database      = "master"
                }

$server = Connect-DbaInstance @connDbaInstanceParams
$conncontext = $server.ConnectionContext

#set filepath
$filePath = "myquery"
$QueryfromFile = [System.IO.File]::ReadAllText("$filePath")

Invoke-DbaAsync -SQLConnection $conncontext -Query $QueryfromFile |  Export-Csv "C:\temp\statementtocsvtest.txt"

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [X] Other (please specify) - SSIS package

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

The code runs but returns an incorrect result set, well, with omitted columns, rather than the full set of data.

#### Steps to Reproduce

Simply run a select against a table with binary data and the issue will be reproduced.

#### Expected Behavior

the actual binary data to be returned.

#### Actual Behavior

"System.Byte[]"

**Comment by niphlod** [comment]
Please bot keep this open

Il gio 19 dic 2019, 04:42 stale[bot] <notifications@github.com> ha scritto:
