### ISSUE TITLE
[Bug] Export-DbaUser Path parameter does not write to a file provided

### ISSUE THREAD

**Issue by seanwhitepc** [sqlcollaborative/dbatools#6090]
#### PowerShell version:

Name                           Value                                                                                                                                                                         
----                           -----                                                                                                                                                                         
PSVersion                      5.1.17763.592                                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                       
BuildVersion                   10.0.17763.592                                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                                                                       

#### dbatools Module version:

Name    : dbatools
Path    : (Purposefully removed)\WindowsPowerShell\Modules\dbatools\1.0.49\dbatools.psd1
Version : 1.0.49

#### SQL Server: 
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 17763: ) 

#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```
```

#### Steps to Reproduce

Run:
`Export-DbaUser -SqlInstance localhost -Path "C:\Other\localhost-users.sql"`

#### Expected Behavior

A single .sql file called "localhost-users.sql" to be created that contains T-SQL to create all users associated with the databases on that SQL Server instance.

#### Actual Behavior

Multiple files created with individual timestamps following the default naming pattern in the directory "localhost-users.sql".  Each subsequent file contains the exact same SQL as the previous file, but with SQL to create the "next" user and so on until the last file:

    Directory: C:\other\localhost-users.sql

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        10/3/2019  12:32 PM            577 <computer name>-20191003123256-user.sql
-a----        10/3/2019  12:32 PM            690 <computer name>-20191003123257-user.sql
-a----        10/3/2019  12:32 PM            758 <computer name>-20191003123257-user.sql
-a----        10/3/2019  12:32 PM           5037 <computer name>-20191003123257-user.sql
-a----        10/3/2019  12:32 PM           8202 <computer name>-20191003123258-user.sql
-a----        10/3/2019  12:32 PM           8664 <computer name>-20191003123258-user.sql
-a----        10/3/2019  12:32 PM           8930 <computer name>-20191003123258-user.sql
-a----        10/3/2019  12:32 PM           9058 <computer name>-20191003123258-user.sql
```

(Some information obscured as this is an issue on a work computer)

**Comment by wsmelton** [comment]
I believe you want to use `FilePath` to get everything into one file.

**Comment by seanwhitepc** [comment]
The documentation for Export-DbaUser has examples with `-Path` pointing to a single file:
https://docs.dbatools.io/#Export-DbaUser

> Example: 1
> `PS C:\> Export-DbaUser -SqlInstance sql2005 -Path C:\temp\sql2005-users.sql`
> Exports SQL for the users in server "sql2005" and writes them to the file "C:\temp\sql2005-users.sql"

Further, `-FilePath` returns the following error:
```
PS C:\Windows\System32\WindowsPowerShell\v1.0> Export-DbaUser -SqlInstance localhost -FilePath "C:\other\localhost-users
.sql"
Out-File : Access to the path 'C:\other\localhost-users.sql' is denied.
At (Removed intentionally)\WindowsPowerShell\Modules\dbatools\1.0.49\allcommands.ps1:14465
char:24
+ ...      $sql | Out-File -Encoding UTF8 -FilePath $FilePath -Append:$Appe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand



    Directory: C:\other\localhost-users.sql


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        10/3/2019  12:32 PM            577 <computer name>-20191003123256-user.sql
-a----        10/3/2019  12:32 PM           5037 <computer name>-20191003123257-user.sql
-a----        10/3/2019  12:32 PM           9058 <computer name>-20191003123258-user.sql
```
Running the above command as an Administrator results in the same exception.

If it should be `-FilePath` the examples should be updated to reflect this.

**Comment by wsmelton** [comment]
Yeah, there are a whole slew of issues with that export to file. I do not get an error though, it simply generates a file that is not valid; when I provide a path name it does not honor the file name.

The Path defaults to a configured path in the module configuration `Get-DbatoolsConfig path.dbatoolsexport`....believe this is something that was implemented few months ago but can't recall by who right off.

Which when I call this command by default, it fails but with a false error:

```
[ 19.0ms ][ PS 5.1 ][ 16:49:32 ][ git:development ] C:\git\dbatools                                                                              [3] > Export-DbaUser -SqlInstance 'localhost,1411' -Database sysdb                                                                               WARNING: [16:49:49][Test-ExportDirectory] Path (C:\Users\Shawn Melton\Documents\DbatoolsExport) must be a directory                              WARNING: [16:49:49][Get-DbaDatabase] Error occurred while establishing connection to localhost,1411 | The target principal name is incorrect.    Cannot generate SSPI context.
```

Provide it a full file to the Path parameter though it does not honor what I provided:

```
[ 65.0ms ][ PS 5.1 ][ 16:51:22 ][ git:development ] C:\git\dbatools                                                                              [8] > Export-DbaUser -SqlInstance 'localhost,1411' -Database sysdb -Path c:\temp\myscript.sql -SqlCredential $containerCred                                                                                                                                                                                                                                                                                                                            Directory: C:\temp\myscript.sql                                                                                                                                                                                                                                                                                                                                                                                                                Mode                LastWriteTime         Length Name                                                                                            ----                -------------         ------ ----                                                                                            -a----       2019-10-03   4:51 PM            412 localhost,1411-20191003165130-user.sql
```
