### ISSUE TITLE
[Bug] Resolve-DbaNetworkName - some commands are missing credential and try catch.

### ISSUE THREAD

**Issue by garethnewman** [sqlcollaborative/dbatools#6121]
Some commands are missing credential and try catch when using Resolve-DbaNetworkName.

To quote Shawns feedback on another command:-

"Need to provide the Credential parameter and variable. As well, need to wrap this in a try/catch block and add the -EnableException parameter so the catch block is properly called. This ensures error output is captured properly by the logging system, in the event the underlying function is hosed up by some other change/commit."

**Comment by wsmelton** [comment]
Not it is not a blanket statement that every command will utilize the `-EnableException`. It depends on internal or public function use.
