### ISSUE TITLE
Update-SqlPermissions error

### ISSUE THREAD

**Issue by grazea** [sqlcollaborative/dbatools#6123]
Hi,

Im trying to sync the logins and permissions from primary replica to secondary replica using these functions - Copy-DbaLogin and Sync-DBALoginPermission but I'm getting this error. I have already checked that the SMO has been loaded. Need to check if you encountered this issue:

WARNING: [10:35:50][Update-SqlPermissions] Failed to Deny UNSAFE ASSEMBLY to xxx on xxx. | Exception calling "Deny" with "3" argument(s): "Deny failed for Server 'xxx'. "
New-Object : Cannot find an overload for "ServerPermissionSet" and the argument count: "1".
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:96594 char:24
+ ...  $permSet = New-Object Microsoft.SqlServer.Management.Smo.ServerPermi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
WARNING: [10:35:50][Update-SqlPermissions] Failed to Grant CONNECT SQL to xxx on xxx. | Exception calling "Grant" with "3" argument(s): "Grant failed for Server 'xxx'. "
New-Object : Cannot find an overload for "DatabasePermissionSet" and the argument count: "1".
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:96816 char:28
+ ...  $permSet = New-Object Microsoft.SqlServer.Management.Smo.DatabasePer ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by wsmelton** [comment]
In an AG some permissions won't be updated because of the nature of an AG (read-only ability for some objects on secondaries).

Try using Sync-DbaAvailabilityGroup: https://docs.dbatools.io/#Sync-DbaAvailabilityGroup

**Comment by grazea** [comment]
Thanks for the response but the permission that is trying to sync in the secondary replica are the securable permissions from the system databases.

**Comment by wsmelton** [comment]
So you are working with a login that has no access to any user database, at all?

**Comment by grazea** [comment]
Hi, this has been resolved after i deployed the latest dbatools to 1.0.54. seems the older version has a bug.

**Comment by wsmelton** [comment]
Do you know what version that was?
