### ISSUE TITLE
Install-DbaWhoIsActive with -LocalFile parameter deletes the local file

### ISSUE THREAD

**Issue by tstrileckis** [sqlcollaborative/dbatools#6126]
### Summary of new feature

I was testing out the Install-DbaWhoIsActive cmdlet and using the -LocalFile parameter.  The stored procedure already existed on the target server, so it was updated, but the local file was then deleted.  I understand why you would want to delete it if it was the downloaded zip file.  Is there a way to have it not delete the local file if you use the -LocalFile parameter?
Thank you

### Latest version of dbatools as of writing

I'm using version 1.0.50 of dbatools module.

**Comment by joshcorr** [comment]
Working on making this cmdlet Cross Platform, and could easily add this feature change in on my next PR. I honestly don't know why we are cleaning the script up at the end. I looked at similar `Install-` functions and they are only cleaning up `.zip` and not the uncompressed files.
