### ISSUE TITLE
Test-DbaConnection - PSRemoting

### ISSUE THREAD

**Issue by ksl28** [sqlcollaborative/dbatools#6148]
### Summary of new feature

When running "Test-DbaConnection -SQLinstance <server>", it checks if PSremoting is accessible (PSRemotingAccessible).  
We often connect to SQL servers, that are either in another domain or not accessible for PSRemoting, and we know this from the beginning.  
But it seems there isnt an option, to disable the PSRemotingAccessible check, so the cmdlet takes a long time, just to time out.  

**Measure command:**  
To a server with PSRemotingAccessible working:  
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 534
Ticks             : 5340054
TotalDays         : 6,18061805555556E-06
TotalHours        : 0,000148334833333333
TotalMinutes      : 0,00890009
TotalSeconds      : 0,5340054
TotalMilliseconds : 534,0054  

To a server with PSRemotingAccessible NOT working:  
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 43
Milliseconds      : 205
Ticks             : 432051498
TotalDays         : 0,000500059604166667
TotalHours        : 0,0120014305
TotalMinutes      : 0,72008583
TotalSeconds      : 43,2051498
TotalMilliseconds : 43205,1498  

### Proposed technical details (if applicable)

Provide an optional parameter like "-SkipPSRemoting", that skips the PSRemotingAccessible check.
Command could look like: "Test-DbaConnection -SqlInstance $SourceServer -SqlCredential $SourceLogin -SkipPSRemoting"  

### Latest version of dbatools as of writing

Version: 1.0.58

**Comment by andreasjordan** [comment]
Will work on this when #7334 is merged.
