### ISSUE TITLE
Copy-SqlDatabase: Instance – Instance Clarification 

### ISSUE THREAD

**Issue by KenCarterCahaba** [sqlcollaborative/dbatools#615]
### Is this a *feature* OR *bug*:
Clarification of feature set actually

### System Details
Interested in using Copy-SqlDatabase.ps1 to mirror production data from a live database instance to a test instance on the same server.  However, looking at the parameters I don't see how this is possible as it appears to lack the necessary controls to target the copy back to the same server from which the instance was copied from or perhaps identify the target destination where the output is to be sent.  

Is my assessment accurate and this indeed is not a capability of the script at this time? Or is it possible and I am simply missing the proper syntax. If not currently a feature, could it be a possible future?

**Comment by wsmelton** [comment]
You are all set for that scenario....dbatools version 0.8.692

![image](https://cloud.githubusercontent.com/assets/11204251/22479895/143ec738-e7b5-11e6-9831-2b4a1b044fa6.png)
