### ISSUE TITLE
Import-DbaCsv add parameter for simple progress messages

### ISSUE THREAD

**Issue by DanielEms2** [sqlcollaborative/dbatools#6150]
### Summary of new feature

It would be great to add a -SimpleProgress parameter that writes a message after each imported batch.  The visual progress bar looks great (and it can be turned off with the -NoProgress parameter), but if the import fails, there is no record of where the failure occurred.

### Proposed technical details (if applicable)

There's an old script by @potatoqualitee that has the functionality I'm describing.

[https://gallery.technet.microsoft.com/scriptcenter/Import-Large-CSVs-into-SQL-216223d9](https://gallery.technet.microsoft.com/scriptcenter/Import-Large-CSVs-into-SQL-216223d9)

![superfast](https://user-images.githubusercontent.com/50877976/67300631-462e9e00-f4bc-11e9-931a-92f12cff5a12.PNG)

### Latest version of dbatools as of writing

1.0.59

**Comment by wsmelton** [comment]
This output should be available using the parameter `-NotifyAfter`. Check the docs here for reference: https://docs.dbatools.io/#Import-DbaCsv
