### ISSUE TITLE
[Bug] Missing output when using -detailed in Get-DbaLogin

### ISSUE THREAD

**Issue by HaBuc** [sqlcollaborative/dbatools#6153]
#### PowerShell version:

PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.60\dbatools.psd1
Version : 1.0.60

#### Culture
LCID             Name             DisplayName
3079             de-AT            German (Austria)

#### SQL Server: 
Microsoft SQL Server 2016 (SP2-CU8) (KB4505830) - 13.0.5426.0 (X64)   
Jul 21 2019 21:16:47   Copyright (c) Microsoft Corporation  Enterprise Edition
Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### Report

When using the option -detailed in Get-DbaLogin the following error is received for each login.

> Exception calling "Replace" with "2" argument(s): "String cannot be of zero length.
Parameter name: oldValue"
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.60\allcommands.ps1:29183 char:21
                     $query = $loginProperty.Replace('', "$loginName")
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
Exception calling "ExecuteWithResults" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.60\allcommands.ps1:29184 char:21
 ...             $loginProperties = $server.ConnectionContext.ExecuteWithR ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

	
Reason is the line 29183 in allcommands.ps1. The replace statement doesn't work, so the following SQL query gives NULL results.

Current line is: 
`$query = $loginProperty.Replace('', "$loginName")`

Should be somthing like:
`$query = $loginProperty.Replace("''" , "'$loginname'")`
 
#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

This is the last error only due to the fact that the query is malformed. The reason is due to the replace statement in Line 29183 of allcommands.ps1. (see above)

> PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults"
                        with "1" argument(s): "Object reference not set to an instance of an object." --->
                        System.NullReferenceException: Object reference not set to an instance of an object.
                           at
                        Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(StringCollection
                        sqlCommands)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at
                        System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception
                        exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : NullReferenceException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaLogin<Process>, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\1.0.60\allcommands.ps1: line 29184
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

#### Steps to Reproduce

Run:
`Get-DbaLogin -SqlInstance <SomeInstance> -Login <Somelogin> -detailed`

#### Expected Behavior

Added properties mentioned in -detailed description.

#### Actual Behavior

Added properties are empty.

**Comment by wsmelton** [comment]
Could run the following and let me know what is returned on your machine?

```powershell
$loginProperty = "SELECT
                            LOGINPROPERTY ('<#LoginName#>' , 'BadPasswordCount') as BadPasswordCount ,
                            LOGINPROPERTY ('<#LoginName#>' , 'BadPasswordTime') as BadPasswordTime,
                            LOGINPROPERTY ('<#LoginName#>' , 'DaysUntilExpiration') as DaysUntilExpiration,
                            LOGINPROPERTY ('<#LoginName#>' , 'HistoryLength') as HistoryLength,
                            LOGINPROPERTY ('<#LoginName#>' , 'IsMustChange') as IsMustChange,
                            LOGINPROPERTY ('<#LoginName#>' , 'LockoutTime') as LockoutTime,
                            CONVERT (varchar(514),  (LOGINPROPERTY('<#LoginName#>', 'PasswordHash')),1) as PasswordHash,
                            LOGINPROPERTY ('<#LoginName#>' , 'PasswordLastSetTime') as PasswordLastSetTime"
$loginProperty.Replace('<#LoginName#>','sa')
```

**Comment by wsmelton** [comment]
Ok so the issue is with the module that is being used to generate the `allcommands.ps1`. Reviewing the `HelpOut` module that we use it is stripping out command blocks due to this line of code:

```
                    # Then output the file content, stripped of block comments.
                    $fileContent -replace '\<\#(?<Block>(.|\s)+?(?=\#>))\#\>', ''
```
