### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Rob-S** [sqlcollaborative/dbatools#6158]
#### PowerShell version:

Name                           Value                                                                                                                                                                              
----                           -----                                                                                                                                                                              
PSVersion                      5.1.17763.134                                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                            
BuildVersion                   10.0.17763.134                                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                                                                            

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Version : 1.0.60

#### SQL Server: 
(Invoke-Sqlcmd 'SELECT @@VERSION')[0].ToString()
WARNING: Using provider context. Server = 10.11.4.248.
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) 
	Aug 19 2014 12:21:34 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

### Report

Commands using the default syntax, presumably to process the current database object provided by the SQLSERVER provider context, do not work. For example, Remove-DbaLogin does not remove the Login. The same is true for most other commands which have more than one ParameterSet. For Backup-DbaDatabase, use of the first syntax is shown as being valid by Get-Help but is actually invalid, being prevented by code rather than by PowerShell parameter checking.

#### Host used

- [ ] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

(none)

#### Steps to Reproduce

For various commands where there is more than one allowable syntax, change the current provider context to the appropriate database object and then execute the command shown in the first syntax diagram displayed by Get-Help. For example (see attached screen capture):
$cred = Get-Credential 'DOMAIN\username'
cd SQLSERVER:\SQL\127.0.0.1\DEFAULT\Logins\somelogin
Remove-DbaLogin -SqlCredential $cred -Verbose

#### Expected Behavior

Executing command in first syntax diagram should execute the command against the database object provided by the current SQLSERVER provider context. If the command does not support using the provider context, as is the case for Backup-DbaDatabase, then Get-Help should not display the first syntax diagram, so that it shows only the two remain allowable syntax diagrams: the one with -SqlInstance and the one with -InputObject.

#### Actual Behavior

In most cases, nothing happens. For example, Remove-DbaLogin does not remove the Login. Backup-DbaDatabase displays an error message. In the case of Backup-DbaDatabase, if the functionality of the first syntax displayed by Get-Help -Name 'Backup-DbaDatabase' (to backup the current database) has been removed, then the 'Default' ParameterSet should be removed from the command, so that Get-Help only displays the two valid syntax patterns and PowerShell's syntax checking displays the error message rather than having to check for "if (-not $SqlInstance -and -not $InputObject)" in the code.

![Screen Shot 2019-10-24 at 4 36 19 PM](https://user-images.githubusercontent.com/323132/67529304-5b085e80-f681-11e9-9033-177ef24ffa30.png)
![Screen Shot 2019-10-24 at 4 30 03 PM](https://user-images.githubusercontent.com/323132/67529309-5f347c00-f681-11e9-855f-2719a628e9d9.png)

**Comment by wsmelton** [comment]
We do not, nor will we, support input of the SQLSERVER provider to any command in our module.

**Comment by wsmelton** [comment]
If you found this documented somewhere that our team owns the content to (doc reference, dbatools.io) please let us know and we will update it.

**Comment by wsmelton** [comment]
There is a warning that is provided when our module is imported if sqlps or sqlserver module is detected. That is sufficient to note our support.

There is no reason for us to try and update our code base for every function to simple output a message that something is not supported. Reading the comment based help state plainly how each parameter is to be used and what value it accepts.

**Comment by Rob-S** [comment]
I would suggest removing the 'Default' parameter set then, especially since it's the first syntax listed by Get-Help. Then PowerShell would enforce the parameter syntax checking. No need to add a message that the syntax displayed by Get-Help is not supported, since PowerShell would not 1) display the syntax as valid syntax, nor 2) allow the syntax to be used.

**Comment by wsmelton** [comment]
`Backup-Database` is not our command, if you see issues with commands around sqlserver module then you should direct issues toward that project.

Again, we are not modifying any of our code to support use with or around the `sqlserver` or `sqlps` modules.
