### ISSUE TITLE
Failure in Copy-SqlLinkedServer due to case sensitivity?

### ISSUE THREAD

**Issue by SArmistead** [sqlcollaborative/dbatools#617]
bug:

Case sensitivity difference between **ORA**OLEDB.Oracle provider on source server and **Ora**OLEDB.Oracle on destination. Both instances are case insensitive.

### System Details

- Operating system name and version:

Windows 7 Enterprise, SP1

- Output from `$PSVersionTable`:

Name                           Value                                                                                                     
----                           -----                                                                                                     
PSVersion                      4.0                                                                                                       
WSManStackVersion              3.0                                                                                                       
SerializationVersion           1.1.0.1                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                           
BuildVersion                   6.3.9600.16406                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                      
PSRemotingProtocolVersion      2.2 

- Output of dbatools version:

Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      693    -1  

- SQL Server version for source/target

Source - SQL Server 2012 SP3 with CU3
Destination - SQL Server 2012 SP3 with CU5

### Steps to Reproduce

Source instance must have Linked Server provider identified as "ORAOLEDB.Oracle".
Destination server must have it defined as "OraOLEDB.Oracle" (Note the case difference)

PS D:\> Copy-SqlLinkedServer -Source VNDVWSQL01P\PRD1 -Destination VNDVWSQL22P\PRD22 -LinkedServers REVCHAIN_LINK_EPC_RO
Getting NetBios name for VNDVWSQL01P\PRD1
Checking if remote access is enabled on VNDVWSQL01P\PRD1
Checking if Remote Registry is enabled on VNDVWSQL01P\PRD1
Collecting Linked Server logins and passwords on VNDVWSQL01P\PRD1
Starting migration
WARNING: VNDVWSQL22P\PRD22 does not support the ORAOLEDB.Oracle provider. Skipping REVCHAIN_LINK_EPC_RO.
Linked Server migration finished

### Action Results
**WARNING: VNDVWSQL22P\PRD22 does not support the ORAOLEDB.Oracle provider. Skipping REVCHAIN_LINK_EPC_RO.**

### Expected Results
REVCHAIN_LINK_EPC_RO successfully copied

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by wsmelton** [comment]
Being that this is at the provider level it really has nothing to do with the function/command. 

As you noted:

> Source instance must have Linked Server provider identified as "ORAOLEDB.Oracle". 
> Destination server must have it defined as "OraOLEDB.Oracle" (Note the case difference)

The only way to duplicate this is to have Oracle Client driver installed where the case is different for the provider name. I'm not sure you can even force that to happen, at least from the last time I had to install that client. I would take a guess this is passed purely on the version of the Oracle Client.

**Comment by potatoqualitee** [comment]
Interesting! I didn't realize this - we're using `$server.Settings.OleDbProviderSettings.Name.Contains`

````
PS C:\github\dbatools> $server.Settings.OleDbProviderSettings.Name.Contains("Search.CollatorDSO")
True
PS C:\github\dbatools> $server.Settings.OleDbProviderSettings.Name.Contains("Search.CollatoRDSO")
False
````

@wsmelton - we need to replace that line with `$destserver.Settings.OleDbProviderSettings.Name -contains $provider`

**Comment by wsmelton** [comment]
Done.
