### ISSUE TITLE
Add DBA-RegServer is getting an error message about activedirectorytenant

### ISSUE THREAD

**Issue by kmramsey** [sqlcollaborative/dbatools#6170]
### Environmental information

Version Information
                                                                                                                              
PSVersion                      5.0.10586.117                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                             
BuildVersion                   10.0.10586.117                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                                             

#### dbatools Module version:

Name    : dbatools
Path    : C:\windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\dbatools.psd1
Version : 1.0.9

#### SQL Server: 
Microsoft SQL Server 2014 (SP3-CU2) (KB4482960) - 12.0.6214.1 (X64) 
	Feb  2 2019 01:10:18 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

#### Host used

- [ X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: The property 'ActiveDirectoryTenant' cannot be found on this object. Verify that the property exists and can be set. ---> 
                        System.Management.Automation.RuntimeException: The property 'ActiveDirectoryTenant' cannot be found on this object. Verify that the property exists and can be set.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Add-DbaRegServer,Stop-Function
ErrorDetails          : The property 'ActiveDirectoryTenant' cannot be found on this object. Verify that the property exists and can be set.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\allcommands.ps1: line 79739
                        at Add-DbaRegServer<Process>, C:\windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\allcommands.ps1: line 848
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```
#### Steps to Reproduce
```
#Run the following powershell commands
Add-DbaRegServerGroup -SqlInstance 'MyMachine,myport' -Group IderaMonitoredInstances -Name IderaMonitoredInstances -Description "CMS designed to allow you to run commands on all idera monitored instances." 
Connect-DbaInstance   -SqlInstance 'MyMachine,myport'  | Add-DbaRegServer -Group IderaMonitoredInstances -ServerName 'MyMachine,myport' -Name IderaMonitoredInstances -Description "CMS designed to allow you to run commands on all idera monitored instances."
```
#### Expected Behavior

I expected it to add a server to the reg server group.

#### Actual Behavior
VERBOSE: [14:57:41][Get-DbaRegServerGroup] Processing IderaMonitoredInstances
VERBOSE: [14:57:41][Get-DbaRegServerGroup] Added IderaMonitoredInstances
VERBOSE: [14:57:41][Add-DbaRegServer] ID: 8)
WARNING: [14:57:41][Add-DbaRegServer] Failed to add MyMachine,myport on  | The property 'ActiveDirectoryTenant' cannot be found on this object. Verify that the property exists and can be set.

**Comment by wsmelton** [comment]
I get a completely different error. Can you update to the latest version of the module (1.0.64) and see if you get the following as well?

```
[18] pwsh [6.2.3] > Connect-DbaInstance -SqlInstance 'localhost\sql17'  | Add-DbaRegServer -Group IderaMonitoredInstance
s -ServerName 'dba1' -Name IderaMonitoredInstances -Description "CMS designed to allow you to run commands on all idera
monitored instances." -Verbose
VERBOSE: [17:24:18][Add-DbaRegServer] Parsing local
VERBOSE: [17:24:18][Add-DbaRegServer] String group provided
VERBOSE: [17:24:18][Get-DbaRegServerGroup] Processing IderaMonitoredInstances
VERBOSE: [17:24:18][Get-DbaRegServerGroup] Added IderaMonitoredInstances
VERBOSE: [17:24:18][Add-DbaRegServer] ID: )
VERBOSE: Performing the operation "Adding IderaMonitoredInstances" on target "Local Registered Servers".
WARNING: [17:24:18][Add-DbaRegServer] Failed to add dba1 on Local Registered Servers | Format of the initialization stri
ng does not conform to specification starting at index 0.
```

**Comment by wsmelton** [comment]
The test fails with the same error that I get above as well.

**Comment by wsmelton** [comment]
Ah disregard those last two...forgot I was in PS and not Windows PS. In Windows PS 5.1 I get a different result, but not the expected behavior.

`Add-DbaRegServerGroup` never adds the group on my local instance.

```
[16] PS [5.1.18362.145] > Connect-DbaInstance -SqlInstance 'localhost,1411' -SqlCredential $containerCred  | Add-DbaRegS
erver -Group IderaMonitoredInstances -ServerName 'dba1' -Name IderaMonitoredInstances -Description "CMS designed to allo
w you to run commands on all ideramonitored instances." -Verbose
VERBOSE: [17:35:09][Add-DbaRegServer] Parsing local
VERBOSE: [17:35:09][Add-DbaRegServer] String group provided
VERBOSE: [17:35:09][Get-DbaRegServerGroup] Processing IderaMonitoredInstances
VERBOSE: [17:35:09][Add-DbaRegServer] String group provided
VERBOSE: [17:35:09][Get-DbaRegServerGroup] Added all root server groups
VERBOSE: [17:35:09][Get-DbaRegServerGroup] Filtering for id 1. Id 1 = default.
VERBOSE: [17:35:09][Get-DbaRegServerGroup] Processing IderaMonitoredInstances
VERBOSE: [17:35:09][Get-DbaRegServerGroup] Added IderaMonitoredInstances
VERBOSE: [17:35:09][Add-DbaRegServer] ID: )
VERBOSE: Performing the operation "Adding IderaMonitoredInstances" on target "Local Registered Servers".
VERBOSE: [17:35:09][Get-DbaRegServer] Filtering by name for IderaMonitoredInstances
VERBOSE: [17:35:09][Get-DbaRegServer] Filtering by servername for dba1
```

The above shows it ran but nothing is ever added, nor does it error.

**Comment by kmramsey** [comment]
Interesting.  I upgraded to 1.60 of dbatools and got "Format of the initialization stri
ng does not conform to specification starting at index 0."

Then I upgraded to 1.64 and I still got "Format of the initialization stri
ng does not conform to specification starting at index 0."

Then I looked at the code for that function... I don't think there has been a change since 1.09.

Did you check in SSMS to see if that server was added to the CMS?

**Comment by kmramsey** [comment]
I was talking with WSMelton over at slack and he asked that I include some more details I figured out.
Keith Ramsey 9:50 AM
Something is odd about that regserver stuff.  I think there are is pre-req or something that I don't fully understand.

So I tried things on a newer machine that didn't have SQL Server on it as a service
wouldn't run.
So I downloaded the SQLSERVER module from powershell gallery, it worked
It did NOT have the sqlps module present either
then, I tried putting the SQLSERVER module on a different machine, and it wouldn't work again.
But that machine has older versions of SSMS on it, and 18.3, and sqlps.
make sense?
wsmelton 10:19 AM
Wouldn't work meaning it erred?
Keith Ramsey 10:32 AM
yeah
new messages
wsmelton 10:52 AM
Installed the sqlserver module but didn't import?
Keith Ramsey 10:57 AM
I just put the module in place, then imported it.
then that machine I mentioned, which only had SSMS, worked
So I'm guessing if you had a BLANK machine, with nothing but dbatools and the SQLSERVER module, the commands would work
wsmelton 11:08 AM
Well that likely means we are missing a dependent dll. At least first guess.
If you can add those details to the issue I'll get Chrissy to check.
