### ISSUE TITLE
Add database to availability group (on all nodes including backup/restore/seeding

### ISSUE THREAD

**Issue by PreacherCmdLets** [sqlcollaborative/dbatools#6174]
Hi Guys,

I am trying to add database to AG without using manual full backup / restore , I think Add-dbaAgdatabase does it for us. But i am able to no do so is this code to latest version of dbatools ?
![image](https://user-images.githubusercontent.com/27749215/68053984-48160f80-fcbb-11e9-90f5-bd077a7e6f4f.png)

- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

**Comment by wsmelton** [comment]
You have to perform an full backup prior to adding a database to the AG. We don't perform that to for you on the command.

**Comment by SQLDBAWithABeard** [comment]
HI, you need have a full backup of a database before you can add it to an Availability Group @PreacherCmdLets 
This is the same output as in SSMS
![image](https://user-images.githubusercontent.com/6729780/68998217-709b2d80-08a7-11ea-9553-30edf407e05e.png)

**Comment by wsmelton** [comment]
The command should be taking the backups for you:

https://github.com/sqlcollaborative/dbatools/blob/51bc5eaf989c49f6aced69aa0d840c6d9562cdb7/functions/Add-DbaAgDatabase.ps1#L220-L239
