### ISSUE TITLE
[Bug] Restore-DbaDatabase stops current transcript

### ISSUE THREAD

**Issue by gory31270** [sqlcollaborative/dbatools#6177]
### Environmental information

PS C:\Users\Administrator> $(get-host).version

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Version : 1.0.50

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
Microsoft SQL Server 2008 R2 (SP3-GDR) (KB4057113) - 10.50.6560.0 (X64)   Dec 28 2017 15:03:48   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Steps to Reproduce

start-transcript -path $path
        Get-ChildItem $BackupPath | Restore-DbaDatabase `
        -SqlInstance $Instance `
        -SqlCredential $Credential `
        -UseDestinationDefaultDirectories `
        -WithReplace
stop-transcript

#### Expected Behavior

to be able to log the restore-dbadatabase command to a log file

#### Actual Behavior

Error when stopping transcript:
Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.
At line:1 char:1
+ Stop-Transcript
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Stop-Transcript], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.StopTranscriptCommand

**Comment by wsmelton** [comment]
https://github.com/sqlcollaborative/dbatools/blob/cd7a897cf042666e3bdbd18b6fdefb77dd4991fd/readme.md#using-start-transcript

Please note we have no control over whether the transcript command starts or stops. We do not manipulate it on our module. There are known bugs with the transcripts commands that are out of our control.

**Comment by gory31270** [comment]
Thanks for the quick feedback, sorry for opening an already known issue.
Keep up the great work.
