### ISSUE TITLE
[Bug] Failures in Start-Migration due to batch separation

### ISSUE THREAD

**Issue by erikdarlingdata** [sqlcollaborative/dbatools#6178]
### Environmental information

Sorry, that command doesn't return anything for me, but here's some output I can get from running parts separately:

```
PSVersion 5.1.18362.145
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.66\dbatools.psd1
Version : 1.0.66
```

#### SQL Server: 

```sql
Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64)   Jul 12 2019 17:43:08   
Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 18362: ) 
(Hypervisor) 
```

```sql
us_english
```

### Report

 

When running `Start-Migration`, I got this error:

```
WARNING: [09:51:33][Copy-DbaInstanceTrigger] Issue creating trigger on destination | 'CREATE TRIGGER' must be the first
 statement in a query batch.
```

It looks like two items fail because of missing batch separators. 

![image](https://user-images.githubusercontent.com/2136037/68130899-2b135380-feea-11e9-83a1-df38ad2a57a4.png)

![image](https://user-images.githubusercontent.com/2136037/68130935-38c8d900-feea-11e9-988d-55553a56f522.png)

#### Host used

- [X ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

See above.

#### Steps to Reproduce

Create in master database:

```
USE master;

CREATE VIEW [dbo].[ThirdPartyView] AS
SELECT *
FROM sys.databases;
```

Create wherever:

```
CREATE   TRIGGER [database_name_check] ON ALL SERVER
      FOR CREATE_DATABASE
AS
      BEGIN
            SET NOCOUNT ON; 

            DECLARE @event_data XML; 
			SET @event_data = EVENTDATA();
			SELECT @event_data
            IF ((SELECT @event_data.value('(/EVENT_INSTANCE/LoginName)[1]', 'NVARCHAR(255)') ) =  'NADABRUTO\edarl'
			     AND (SELECT @event_data.value('(/EVENT_INSTANCE/DatabaseName)[1]', 'NVARCHAR(255)') ) NOT LIKE  '%Stack%')
						BEGIN
							RAISERROR('NO CAN DO, BUCKAROO', 0, 1) WITH NOWAIT;
							ROLLBACK;
						END

      END;
```

Then try to run something like this: `Start-DbaMigration -Source NADABRUTO\SQL2017 -Destination NADABRUTO\SQL2019 -Exclude Databases`

#### Expected Behavior

Should copy objects without error.

#### Actual Behavior

Did not copy objects.

**Comment by SQLDBAWithABeard** [comment]
The trigger I can recreate and is due to the logic here 

https://github.com/sqlcollaborative/dbatools/blob/51bc5eaf989c49f6aced69aa0d840c6d9562cdb7/functions/Copy-DbaInstanceTrigger.ps1#L166-L167
````
                        $sql = $sql -replace "CREATE TRIGGER", "`nGO`nCREATE TRIGGER"
                        $sql = $sql -replace "ENABLE TRIGGER", "`nGO`nENABLE TRIGGER"
````

because @erikdarlingdata  has more than one space between CREATE and TRIGGER :-)

@wsmelton - happy for me to PR with 

`$sql = $sql -replace "CREATE ", "`nGO`nCREATE "`

Are there any issues I would be missing there?

@erikdarlingdata  I cant reproduce with the view :-(

**Comment by erikdarlingdata** [comment]
Hm. I'll see if there's anything else about the view that makes it special when I get back home. Thanks Rob!

**Comment by andreasjordan** [comment]
Hi @erikdarlingdata - just provided a pull request for that.

**Comment by erikdarlingdata** [comment]
@andreasjordan WOOHOO! Thank you!
