### ISSUE TITLE
[Bug] Restore-DbaDatabase on Azure SQL Managed Instance using Azure default backup path

### ISSUE THREAD

**Issue by jfowler-volant** [sqlcollaborative/dbatools#6182]
Trying to do a restore from blob storage to a Azure SQL Managed Instance, nothing crazy.

Running this command:

`Restore-DbaDatabase -SqlInstance $target -Path "https://$blobStorageAccount.blob.core.windows.net/$containerName/$sourceDatabase.bak" -WithReplace
`
Gives the following error:

```
"Cannot convert value "https://wasdpeus2aprsmi2426.blob.core.windows.net/managedserver-97a8e9db-de82-4f7c-b521-2a04fb660cee/data/ae35a7c2-753c-4ffd-aaec-ea400836102d_1.mdf" to type "System.IO.FileInfo". Error: "The given path's format is not supported."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.67\allcommands.ps1:18215 char:21
+                     $Pname = [System.Io.FileInfo]$_.PhysicalName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastConstructorException
 "

```
This appears to be the path for the Microsoft-managed automatic backup storage.  The SAS token credential is already created in the database, and I can do the restore successfully from SSMS with normal RESTORE DATABASE command.

**Comment by jkrilov-mri** [comment]
I'm seeing the same error on one backup, but a different db backup is working fine. Using SQL MI.
