### ISSUE TITLE
[Bug] Invoke-DbaQuery -File throw error

### ISSUE THREAD

**Issue by githubsqltoolsse** [sqlcollaborative/dbatools#6184]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      4.0                                                                                     
WSManStackVersion              3.0                                                                                     
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                     4.0.30319.42000                                                                         
BuildVersion                   6.3.9600.19170                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                    
PSRemotingProtocolVersion      2.2                                                                                     




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Version : 1.0.67




```

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
Microsoft SQL Server 2012 (SP4-OD) (KB4091266) - 11.0.7469.6 (X64)   Feb 28 2018 17:47:20   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

### Report

 
When I run Invoke-DbaQuery with the -File parameter I got "Method invocation failed because [System.Uri] does not contain a method named 'New'" Error. The sql in the file can be as simple as "SELECT @@Version".

MyCommand: Invoke-DbaQuery -SqlInstance MyServer\MyInstance -File .\Test.sql

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```


PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: Method invocation failed because [System.Uri] do
                        es not contain a method named 'New'.
                           at CallSite.Target(Closure , CallSite , RuntimeType , Object )
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : MethodNotFound
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-DbaQuery<Begin>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:
                         line 46446
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

Create a file in the directory you are running the code. 
Name the file Test.sql. 
In the file type SELECT @@Version
Run the Command Invoke-DbaQuery -SqlInstance MyServer\MyInstance -File .\Test.sql

#### Expected Behavior

Output of Version info.
#### Actual Behavior

Get error message, followed by Version info.

**Comment by wsmelton** [comment]
URI class cannot handle relative paths so the full path should be provided for now.

I'll let others comment if we should support it or not as it will simply require adding a few lines of code to support it. I'm fine with requiring the full path as providing a relative path is commonly only done in interactive sessions.

**Comment by paschott** [comment]
I'll admit that I tend to use relative paths semi-often in scripting, especially if writing up a script that is designed to run through the scripts in that same folder or something closely related.  I used it with the sqlserver module invoke-sqlcmd cmdlet and it worked just fine with relative paths.

If it's just a couple of lines of code and easy to support, I'd like the abillity to use relative or full paths for the file input.

**Comment by alhandra** [comment]
Hi guys, one simple solution would be to wrap the new::uri call with a conversion of relative path to full path such as a call similar to (Get-Item -Path ".\").FullName to get the full path of current directory.

**Comment by wsmelton** [comment]
@alhandra that actually won't work in this case due to the way the command is written. That URI call has to also handle a URL being passed in for Azure Blob files.

**Comment by alhandra** [comment]
how about something like 
`
if ($uri.startsWith(".")) {
 $uri =Join-Path (Get-Item -Path ".").FullName $uri -Resolve
 }
`

**Comment by beargle** [comment]
Was #6287 the fix for this issue? Not seeing it in development branch, but wasn't sure if it was just missed or intentionally pulled from release.

Looks like adding the `Resolve-Path` call would resolve, I've just run into the same error with `1.0.92`.

**Comment by wsmelton** [comment]
No. That alone won't fix it.

**Comment by paschott** [comment]
As far as I know this is still an issue w/ the latest dbatools. I can work around it with a full file path, but can't use a relative path to run files.

**Comment by SQLDBAWithABeard** [comment]
Yup, was just hit here with a developer - Can we add info to the user for the resolution?

**Comment by paschott** [comment]
> Yup, was just hit here with a developer - Can we add info to the user for the resolution?

I ended up declaring a variable and specifying full paths for the function to work, but it's definitely not consistent with most other areas of PowerShell that I use where I can just use a relative path and the function figures out those details.  There's no resolution yet - just workarounds. :/

**Comment by niphlod** [comment]
I can take a look at it in a few hours, seems rather an overlook than a dealbreaker ^_^
