### ISSUE TITLE
[Bug] Copy-DbaLogin example should be added for LoginRenameHashtable

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#6188]
### Report

An example is needed in `Copy-DbaLogin` to show how you can use the parameter `-LoginRenameHashtable`

**Comment by jpomfret** [comment]
Hey @wsmelton 

There is an example for the rename, but just one login? Did you want this expanded?

https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-DbaLogin.ps1#L116

**Comment by wsmelton** [comment]
Yeah, didn't catch seeing it there. Be good to show that with splatting to draw attention to it as well :wink:

**Comment by jpomfret** [comment]
Added some splatting ;)
