### ISSUE TITLE
[Bug] Get-DbaLastBackup unnecessarily skips database when IsAccessible equals false

### ISSUE THREAD

**Issue by bgehem** [sqlcollaborative/dbatools#6192]
#### PowerShell version:
Name                           Value
----                           -----
PSVersion                      5.1.14393.3053
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3053
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.68\dbatools.psd1
Version : 1.0.68

#### SQL Server: 
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### Report
Get-DbaLastBackup unnecessarily skips database when IsAccessible equals false. All the properties required are available when IsAccessible equals false. Removing this check would allow users with view server state permission to execute this cmdlet.

I Checked the required properties using Connect-DbaInstance against SQL Server 2008 and 2017: 
Connect-DbaInstance -SqlInstance ************* | Select -ExpandProperty Databases | Select Name, Createdate, RecoveryModel, IsAccessible

Name                CreateDate          RecoveryModel IsAccessible
----                ----------          ------------- ------------
ac**********        19-9-2013 11:02:26         Simple        False
Im**********        19-9-2013 11:01:52         Simple        False
ma**********        8-4-2003 09:13:36          Simple         True
mo**********        8-4-2003 09:13:36          Simple        False
ms**********        9-7-2008 16:46:27          Simple         True
RD**********        19-9-2013 11:02:08         Simple        False
te**********        27-10-2019 02:13:32        Simple         True

Also Get-DbaDbBackupHistory doesn't check or require IsAccessible to be true.

#### Host used
- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received
WARNING: [09:16:29][Get-DbaLastBackup] The database [utldba] on server SQLTALL-02\DBA is not accessible. Skipping
database

#### Steps to Reproduce
Execute Get-DbaLastBackup against a database that is not accessible to the user with view server state permission.

#### Expected Behavior
Get-DbaLastBackup should report on databases that are not accessible to the user with view server state permission.

#### Actual Behavior
Get-DbaLastBackup emits a warning and skips the database.

**Comment by wsmelton** [comment]
What is your proposed method to access your information when the database is not accessible via SMO?

**Comment by bgehem** [comment]
> What is your proposed method to access the information when the database is not accessible via SMO?
The information is already there whether IsAccessible is true or false. A lot of properties in the SMO database class are available when IsAccessible is false. IsAccessible probably doesn't mean the database is completely inaccessible via SMO.

**Comment by wsmelton** [comment]
In our testing it does. Please provide an example of you have found otherwise.

**Comment by bgehem** [comment]
Here you go:
[DBAToolsTest6192.ps1.txt](https://github.com/sqlcollaborative/dbatools/files/3846972/DBAToolsTest6192.ps1.txt)

[DBAToolsTest6192output.txt](https://github.com/sqlcollaborative/dbatools/files/3846968/DBAToolsTest6192output.txt)

**Comment by wsmelton** [comment]
Where in your code did you make the database unavailable, or where `IsAccessible` returns false....you can also put your code directly in comment so we don't have to download files.

**Comment by bgehem** [comment]
> Where in your code did you make the database unavailable, or where `IsAccessible` returns false....you can also put your code directly in comment so we don't have to download files.

I didn't make it unavailable. The login doesn't have access to the database. Hence, IsAccessible is false.

If you want to know if the database is **InAccessable** I think you need to look at Database.Status
[database.status](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.database.status?view=sql-smo-140.17283.0)
[smo.databasestatus](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.databasestatus?view=sql-smo-140.17283.0)

**Comment by wsmelton** [comment]
Status won't show the proper value to know if it is truly inaccessible. IsAccessible may return a false positive when you are dealing with permissions, but when the database is not accessible that is the only method in SMO to truly know it is not...

![image](https://user-images.githubusercontent.com/11204251/68868603-6f0e1180-06bd-11ea-9ac1-381db974e5a3.png)

Again, we have tested this in multiple scenarios of mirroring and Availability Groups and use of the `IsAccessible` is the most reliable method in SMO.

**Comment by bgehem** [comment]
You missed a _d_ in your last statement. Databasename is **restoreddb1**

I tested and the properties for Get-DbaLastBackup are available in Normal Standby, Restoring and "Offline, AutoClosed", all with IsAccessible equals false I'll try testing other states when I have time.

**Comment by wsmelton** [comment]
Correct, but being able to pull properties from a given database is still blocked...

![image](https://user-images.githubusercontent.com/11204251/68873419-3e31da80-06c5-11ea-92a0-ea700f188caf.png)

**Comment by wsmelton** [comment]
Initially basic, testing specific to `Get-DbaLastBackup` does not show it is accessing anything within the database to retrieve this information so we can likely remove it. We need to have that verified on an AG environment to double-check.

**Comment by bgehem** [comment]
Thanks! 
I did some digging: The value of the `Database.IsAccessible` property is determined by calling the [HAS_DBACCESS](https://docs.microsoft.com/en-us/sql/t-sql/functions/has-dbaccess-transact-sql?view=sqlallproducts-allversions) function.
