### ISSUE TITLE
[Bug] Test-DbaDbCompatibility unnecessarily skips database when IsAccessible equals false

### ISSUE THREAD

**Issue by bgehem** [sqlcollaborative/dbatools#6193]
#### PowerShell version:
Name                           Value
----                           -----
PSVersion                      5.1.14393.3053
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3053
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.68\dbatools.psd1
Version : 1.0.68

#### SQL Server: 
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### Report
Test-DbaDbCompatibility unnecessarily skips database when IsAccessible equals false. All the properties required are available when IsAccessible equals false. Removing this check would allow users with view server state permission to execute this cmdlet.

I Checked the required properties using Connect-DbaInstance against SQL Server 2008 and 2017: 
Connect-DbaInstance -SqlInstance ***** | Select -ExpandProperty Databases | Select Name, IsAccessible, CompatibilityLevel | ft

Name   IsAccessible CompatibilityLevel
----   ------------ ------------------
master         True         Version140
model         False         Version140
msdb           True         Version140
tempdb         True         Version140
u*****        False         Version140

#### Host used
- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received
No error or warning. Databases are skipped silently

#### Steps to Reproduce
Execute Test-DbaDbCompatibility against a database that is not accessible to the user with view server state permission.

#### Expected Behavior
Test-DbaDbCompatibility should report on databases that are not accessible to the user with view server state permission.

#### Actual Behavior
Databases are skipped silently

**Comment by wsmelton** [comment]
What is your proposed method to access the database when it is not accessible via SMO?

**Comment by wsmelton** [comment]
We utilize SMO in this command and when the property is false there is no possible way to read the database properties via SMO.

https://github.com/sqlcollaborative/dbatools/blob/821c2e423fd2439b8d99a8e0a9248fe9c4c92d9c/functions/Test-DbaDbCompatibility.ps1#L81

While T-SQL DMVs could gather the information we have no plans to put a "backup" method into every command at this time.

**Comment by bgehem** [comment]
I think this is very similar to #6192 

Test-DbaDbCompatibility uses database properties Name and CompatibilityLevel. Both are available in at least Normal, Standby, Restoring and "Offline, AutoClosed", all with IsAccessible equals false.
