### ISSUE TITLE
New Feature: Set-DbaLinkedServer

### ISSUE THREAD

**Issue by BilliousBT** [sqlcollaborative/dbatools#6196]
### Summary of new feature

Ability to change the various attribute of the linked servers that are returned by the Get-DbaLinkedServer command.

For example the ability to change the user, password and target of a linked server.

### Latest version of dbatools as of writing

1.0.68

**Comment by ChrisWoods1977** [comment]
Not specifically stated in the original feature request: Ability to just create a new linked server.

**Comment by wsmelton** [comment]
That would be separate issue..

**Comment by wsmelton** [comment]
That is already stated in the referenced issue.

**Comment by lancasteradam** [comment]
As discussed [here ](https://github.com/sqlcollaborative/dbatools/pull/7392#issuecomment-851578750) the "set" workflow does not seem to be allowed by SMO.

**Comment by andreasjordan** [comment]
So I will close this now.
