### ISSUE TITLE
[Bug] Invoke-DbaQuery documentation is confusing about it's purpose

### ISSUE THREAD

**Issue by Jaykul** [sqlcollaborative/dbatools#6208]
#### PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
ALSO 
```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
#### dbatools Module version:
```
Name    : dbatools
Path    : C:\Users\joel\Documents\PowerShell\Modules\dbatools\1.0.71\dbatools.psd1
Version : 1.0.71

Name    : dbatools
Path    : C:\Users\joel\Documents\PowerShell\Modules\dbatools\1.0.67\dbatools.psd1
Version : 1.0.67

Name    : dbatools
Path    : C:\Users\joel\Documents\PowerShell\Modules\dbatools\1.0.22\dbatools.psd1
Version : 1.0.22
```

#### SQL Server: 

```
Microsoft SQL Azure (RTM) - 12.0.2000.8
   Oct 12 2019 22:46:48
   Copyright (C) 2019 Microsoft Corporation
```

### Report

I'm going to rant a little, the TLDR is that the docs for this function need work.

Running `Get-Help Invoke-DbaQuery -Full` tells me:
```
SYNOPSIS
    A command to run explicit T-SQL commands or files.
DESCRIPTION
    This function is a wrapper command around Invoke-DbaAsync, which in turn is based on Invoke-SqlCmd2.

    It was designed to be more convenient to use in a pipeline and to behave in a way consistent with the rest of our functions.
```

However, this `Invoke-DbaAsync` command is a private/internal function and as someone who avoids SQL when possible, I have some distant memories of `Invoke-SqlCmd2` from poshcode.org days, but I have no idea why you're mentioning it, since it's not included in this module.  

I initially had doubts that this could be _more convenient to use in a pipeline_, because the parameter docs all say that _none_ of the parameters accept pipeline input -- not even the one named `InputObject`!  I later found from the examples that the parameter docs are wrong, and that I can pipe in databases or servers to run a query against.

At first I imagined I could run `sqlcmd` scripts that we used to use with Invoke-SqlCmd this way, but then I found closed bugs indicating that although you support "or files" you don't mean scripts, you mean files with single stand-alone queries in them, so I can't create a database, add a GO and then `use` that database, add another GO, and operate on that database. 

The description for this command **needs** to indicate 
1. What sort of files are supported
2. How it interacts with the GO statement
3. That the GO statement can be configured manually by using Connect-DbaInstance
4. That this always calls Connect-DbaInstance at least once (even if you pass it the output of Connect-DbaInstance)
8. A related Link to Connect-DbaInstance

I have more to say about Connect-DbaInstance, but I'll file that in an actual behavior bug.

#### Host used

- [x ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

**Comment by wsmelton** [comment]
> A related Link to Connect-DbaInstance

I don't believe this is necessary because everyone of our commands end up using `Connect-DbaInstance`.

> That this always calls Connect-DbaInstance at least once (even if you pass it the output of Connect-DbaInstance)

Our library has internal code within the dll that handles whether `SqlInstance` is being passed an SMO server object (e.g. `Connect-DbaInstance`) or just a string server name. We declare every `SqlInstance` as `DbaInstanceParameter` type for this purpose.

> That the GO statement can be configured manually by using Connect-DbaInstance

You will need to clarify what you mean by this because that is not the purpose of the command. In the invoke command we simply parse the GO as a batch separator because SMO treats as such.

> `Invoke-Sqlcmd2` being mentioned

`Invoke-DbaAsync` was written based on what Invoke-SqlCmd2 did, for the most part, and code added for it to work with dbatools functionality.

**Comment by Jaykul** [comment]
Re. `GO` When I investigated problems with multi-statement scripts, I found #5486 already closed -- further investigation showed that the [BatchSeparator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.common.serverconnection.batchseparator?view=sql-smo-140.17283.0#Microsoft_SqlServer_Management_Common_ServerConnection_BatchSeparator) can be configured (but only using `Connect-DbaInstance`), and Invoke-DbaAsync _does not_ follow the BatchSeparator, being hard-coded to `GO`...

I'm not saying _all_ of that needs documenting. But the fact that it _does_ split on "GO" is only documented on the `Query` parameter and the fact that _the command splits them_ and running each separately (meaning that changing databases has no effect) is not documented. Finally, they are describes as a "batch" in the documentation of the Query parameter, but the `BatchSeparator` parameter on `Connect-DbaInstance` is _ignored_, which is a bit confusing.

Also confusing is the documentation of `EnableException` which actually criticises the design of the module, saying that it is "inconvenient because it basically disables advanced scripting" (which I'm tempted to agree with, by the way). I really wish the default treatment for exceptions was configurable via `Set-DbaToolsConfig` so that I didn't have to pass this to every command.

**Comment by niphlod** [comment]
Docs could be clearer, of course ...... Probably you're missing that Invoke-DbaQuery CAN use a connection with SMO but DOES NOT use its methods to run it. 
SMO can't use parametrized queries (which is quite "the deal" of invoke-dbaquery). For everything that doesn't need parameters, feel free to use ".Query()" on the SMO connection itself, it surely is more in line with, e.g., invoke-sqlcmd (no, not invoke-sqlcmd2 whose name was quite a source of these kind of troubles).
As said before, Invoke-DbaQuery is not really tailored for batches or loooong SQL Scripts. But for a few GOs we accomodated them. Invoke-DbaQuery is reaaally good for queries.
So, no, it doesn't parse queries the way SMO query do, nor can "hop" databases with, e.g., "use dbname".
As for the EnabledException bit, feel free to reword it, but it's basically on every public function dbatools has. The gist of it is that we're nice by default (i.e. to interactive users) and programs can very well add a switch.
You can totally use Powershell standard $PSDefaultParameterValues if you want to save characters.

**Comment by Jaykul** [comment]
For us it's not about saving characters, it's about policing all the developers who write deployment scripts -- and are most certainly not going to remember to set that switch (which we _need_ to have set so that deployments fail if SQL scripts fail) ...
