### ISSUE TITLE
[Bug] Connect-DbaInstance creates new connections even when we already have a connection

### ISSUE THREAD

**Issue by Jaykul** [sqlcollaborative/dbatools#6211]
#### PowerShell version:

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
#### dbatools Module version:
```
Name    : dbatools
Path    : C:\Users\joel\Documents\PowerShell\Modules\dbatools\1.0.72\dbatools.psd1
Version : 1.0.72
```

#### SQL Server: 

```
Microsoft SQL Azure (RTM) - 12.0.2000.8
   Oct 12 2019 22:46:48
   Copyright (C) 2019 Microsoft Corporation
```

### Report

Because of #6210 we are trying to call `Invoke-DbaQuery` with a connection pre-created by calling `Connect-DbaInstance` so that we can then `Disconnect` it after, but this doesn't work and we _still_ run out of connections in the pool.

After reading and re-reading the source we narrowed it down to the fact that line 421 is the only way (with an Azure database) to escape creating a new connection:

https://github.com/sqlcollaborative/dbatools/blob/ce04da16798e9b4019d03ac6934b8d7a7d141ca8/functions/Connect-DbaInstance.ps1#L420-L423

So unless I explicitly specify `-Database master` it will create a new connection every time, and use _that_ connection instead of the one that I gave it. 

To summarize the problems with this:
1. Given that in Azure there's no support for `default_database` for users, `Connect-DbaInstance` should assume that if `-Database` is not specified, then it's _master_.
2. `Connect-DbaInstance` needs to add note properties on the connections it returns to indicate whether it's returning what was passed in or a copy it created. Otherwise, there's no way for a caller to detect they have created a new connections -- and since this is used by every function in dbaTools, none of them can do the right thing.
3. Because of this, any query run using `Connect-DbaInstance` and `Invoke-DbaQuery` without _explicitly_ specifying the same `-Database` on both is creating two connections unecessarily. (And will leak a connection, due to #6210)

Once this is all fixed, the documentation needs to explain that you're doing this differently for Azure SQL databases, because it's not obvious. Users need to know that even if they specify the `-Database` explicitly, each distinct database _must_ create a new connection and therefore a new connection pool (users who are new to Azure SQL may need an explanation that you can't switch databases in a connection or query (which is suggested in [Microsoft's docs on connection pool fragmentation](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling#pool-fragmentation-due-to-many-databases) or set default_database on users). Currently, it _looks_ like I can call `Invoke-DbaQuery` multiple times against different databases with the same $DbaInstance from a Connect-DbaInstance call, and then close it:

```PowerShell
$DbaInstance = Connect-DbaInstance -SqlInstance $InstanceName -SqlCredential $Credential
Invoke-DbaQuery -SqlInstance $DbaInstance -Query $CreateDbQuery -Database master
Invoke-DbaQuery -SqlInstance $DbaInstance -Query $CreateTableQuery -Database $DbName
$DbaInstance.ConnectionContext.Disconnect()
```

But in reality **each** of those queries created it's own connection (and, currently, leaked it), meaning there was **no value** in creating the connection myself the way I did!

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred                           because all pooled connections were in use and max pool size was reached. ---> System.Exception: Timeout expired.  The timeout period                           elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool                          size was reached. ---> System.Management.Automation.MethodInvocationException: Exception calling "Connect" with "0" argument(s):                                "Failed to connect to server TCP:ausc1-frg9sqlwttqrx.database.windows.net,1433." --->
                        Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server
                        TCP:ausc1-frg9sqlwttqrx.database.windows.net,1433. ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed                          prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size                             was reached.
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry,                                DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory                                 connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect(WindowsIdentity impersonatedIdentity)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at Connect-DbaInstance<Process>(Closure , FunctionContext )
                           --- End of inner exception stack trace ---
                           --- End of inner exception stack trace ---
TargetObject          : ausc1-frg9sqlwttqrx.database.windows.net
CategoryInfo          : NotSpecified: (ausc1-frg9sqlwttqrx.database.windows.net:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaQuery,Stop-Function
ErrorDetails          : Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled                          connections were in use and max pool size was reached.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.72\allcommands.ps1: line 81869
                        at Invoke-DbaQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.72\allcommands.ps1: line 46563
                        at <ScriptBlock>, <No file>: line 2
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

```PowerShell
$DbaInstance = Connect-DbaInstance -SqlInstance $Db.SqlInstance -SqlCredential $Db.SqlCredential -MaxPoolSize 2
Invoke-DbaQuery -SqlInstance $DbaInstance -Query "SELECT @@Version"
Invoke-DbaQuery -SqlInstance $DbaInstance -Query "SELECT @@Version"
$DbaInstance.ConnectionContext.Disconnect()
```

#### Expected Behavior

It should run both queries using the same connection from the connection pool, and then disconnect

#### Actual Behavior

Each query creates another connection, exhausting the connection pool.

#### Steps to Reproduce

```PowerShell
Clear-DbaConnectionPool
$DbaInstance = Connect-DbaInstance -SqlInstance $Db.SqlInstance -SqlCredential $Db.SqlCredential -MaxPoolSize 2
$DbaInstance = Connect-DbaInstance -SqlInstance $DbaInstance 
$DbaInstance = Connect-DbaInstance -SqlInstance $DbaInstance 
$DbaInstance.ConnectionContext.Disconnect()
```

#### Expected Behavior

The first call should connect to the database, and the others should merely confirm the connection

#### Actual Behavior

Each call creates another connection, exhausting the connection pool.

**Comment by potatoqualitee** [comment]
Thanks so much for the report. This is my work but I'm out of commission for a while, any chance you'd be interested in fixing this one, Joel? 🙇

**Comment by Jaykul** [comment]
Sure @potatoqualitee

**Comment by Jaykul** [comment]
The current logic reuses the input connection as long as the databases are the same.  I think it should **also** be checking the username, but I'm not sure. What would we check for in cases when it's token auth? It looks like on Azure, you always have to pass SqlCredentials, so we always have a username, but in the case of token auth, I'm not sure the user name is on the connection object we're outputting. Anyone know? Maybe it's safe to ignore that and assume they wouldn't be passing a connection they didn't mean for us to use ... I'll try a few things tomorrow

**Comment by Jaykul** [comment]
Fwiw (as you've probably figured out), I may never get to this. We had to remove dbatools from our dependencies at work because of this (after I spent _too much_ time trying to fix it without success). I may come back to it in my free time, but don't count on it, because I'm just frustrated at this point.

**Comment by potatoqualitee** [comment]
💔 sorry it didn't work out

**Comment by glennsarti** [comment]
Okay, so I've just hit this issue as well, but it manifested itself in a very different way ...

I was using an Azure AD App Registration to connect and query a DB. So the usual App Client ID, Client Secret (Password) and TenantID

When using the following:

``` powershell
$connectionParams = @{
  'SqlInstance' = $ServerDetails.FQDN
  'Database' = 'master'
  'DisableException' = $true
  'AuthenticationType' = 'AD Universal with MFA Support'
  'SqlCredential' = New-Object System.Management.Automation.PSCredential ...
  'Tenant' = '<GUID>'
}

Write-Host "---- Creating DB connection"
$connection = Connect-DbaInstance @connectionParams -Verbose
Write-Host "---- Running Query"
$result = $connection | Invoke-DbaQuery -Database 'master' -Query 'SELECT GETDATE() as Test' -Verbose
Write-Host $result.Test
```

I got the following good output

``` text
---- Creating DB connection
VERBOSE: [13:46:39][Connect-DbaInstance] Creating renewable token
VERBOSE: [13:46:39][Connect-DbaInstance] Connecting to Data
Source=TCP:xxxxx.database.windows.net,1433;Initial Catalog=master;Persist Security
Info=True;MultipleActiveResultSets=False;Connect
Timeout=30;Encrypt=True;TrustServerCertificate=False;Application Name="dbatools PowerShell module -
dbatools.io"
VERBOSE: [13:46:39][Connect-DbaInstance] Connecting to Azure: xxxxx.database.windows.net
---- Running Query
3/07/2020 05:46:41
```

BUT If remove the `-Database 'master'` from the `Invoke-DbqQuery` call

So PowerShell
``` powershell
$connectionParams = @{
  'SqlInstance' = $ServerDetails.FQDN
  'Database' = 'master'
  'DisableException' = $true
  'AuthenticationType' = 'AD Universal with MFA Support'
  'SqlCredential' = New-Object System.Management.Automation.PSCredential ...
  'Tenant' = '<GUID>'
}

Write-Host "---- Creating DB connection"
$connection = Connect-DbaInstance @connectionParams -Verbose
Write-Host "---- Running Query"
$result = $connection | Invoke-DbaQuery -Query 'SELECT GETDATE() as Test' -Verbose
Write-Host $result.Test
```

I get the following bad output

```
---- Creating DB connection
VERBOSE: [13:50:30][Connect-DbaInstance] Creating renewable token
VERBOSE: [13:50:30][Connect-DbaInstance] Connecting to Data
Source=TCP:xxxx.database.windows.net,1433;Initial Catalog=master;Persist Security
Info=True;MultipleActiveResultSets=False;Connect
Timeout=30;Encrypt=True;TrustServerCertificate=False;Application Name="dbatools PowerShell module -
dbatools.io"
VERBOSE: [13:50:30][Connect-DbaInstance] Connecting to Azure: xxxx.database.windows.net
---- Running Query
VERBOSE: [13:50:31][Connect-DbaInstance] Connecting to Data
Source=TCP:xxxx.database.windows.net,1433;Initial Catalog=master;Persist Security
Info=True;MultipleActiveResultSets=False;Connect
Timeout=30;Encrypt=True;TrustServerCertificate=False;Application Name="dbatools PowerShell module -
dbatools.io"
VERBOSE: [13:50:31][Connect-DbaInstance] Connecting to Azure: xxxx.database.windows.net
WARNING: [13:50:32][Invoke-DbaQuery] Failure | Login failed for user ''.
```

1.  It's creating a new connection

2. It's not creating the new connection correctly

3. It returns a `Login failed for user ''` which sent me wasting many, many hours of my time 😢

With such an obtuse error, it definitely feels like at least some documentation needs to be updated.

Also note calling `$connection.Query('SELECT GETDATE() as Test')` worked perfectly fine in both scenarios, so the original connection is (probably) perfectly fine

**Comment by glennsarti** [comment]
Whoops forgot to add

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.113    DbaTOols                            {Select-DbaObject, Set-DbatoolsConfig, A...
```

**Comment by wsmelton** [comment]
We removed the dlls that supported MFA I recall do I don't believe the option you are trying should even work...

This command will be something we will try to address in the next few months.

**Comment by wsmelton** [comment]
Collected PRs that touched or changed the `Connect` command, some of these pre-date 1.0 release. There may be info in why we did certain things in the code as well.

#6210 #5625 #5593 #4612 #4435 #4426 #3812 #3758 #3547 #3253 #2876 #3074 #2685 #2567 #2186 #2089 #2084 #2049 #2023 #1964 #1870 #1860 #1786 #1766 #1763

**Comment by andreasjordan** [comment]
I hope all problems from this issue can be addressed by using the new features of https://docs.dbatools.io/#Connect-DbaInstance explained in examples 17 and 18:

Example: 17
PS C:\> Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true
PS C:\> $sqlcred = Get-Credential sqladmin
PS C:\> $server = Connect-DbaInstance -SqlInstance sql2014 -SqlCredential $sqlcred
PS C:\> Invoke-DbaQuery -SqlInstance $server -Query "select 1 as test"
Use the new code path for handling connections. Especially when you have problems with connection pooling, try this.
We also have added additional -Verbose and -Debug output to help us understand your problem if you open an issue related to connections.
For additional information about how the new code path works, please have a look at the code: https://github.com/sqlcollaborative/dbatools/blob/development/functions/Connect-DbaInstance.ps1
If you like to use the new code path permanently, register this config:

PS C:\> Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true -Passthru | Register-DbatoolsConfig
As we would like to use the new code path as a default in the future, please give feedback if you are using it in your environment.

Example: 18
PS C:\> Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true
PS C:\> $azureCredential = Get-Credential -Message 'Azure Credential'
PS C:\> $azureAccount = Connect-AzAccount -Credential $azureCredential
PS C:\> $azureToken = (Get-AzAccessToken -ResourceUrl https://database.windows.net).Token
PS C:\> $azureInstance = "YOURSERVER.database.windows.net"
PS C:\> $server = Connect-DbaInstance -SqlInstance $azureInstance -AccessToken $azureToken
PS C:\> Invoke-DbaQuery -SqlInstance $server -Query "select 1 as test"
Connect to an Azure SQL Database or an Azure SQL Managed Instance with an AccessToken.
Note that the token is valid for only one hour and cannot be renewed automatically.
This is only available in the new code path for handling connections (see example above).


So I will close this for now, but you can reopen it if you have further questions.

**Comment by wsmelton** [comment]
Experimental features of not a fix for use of the command.

If they fix it then make them default or remove the use of experimental. Invoke command also handles connections different and not aware any changes have been made to that command.

Once the experimental features or no longer experimental then gross can be closed a fixed.

**Comment by potatoqualitee** [comment]
This is finally fixed in dev! 🥳  will release to PS Gallery in 5 days, after testing
