### ISSUE TITLE
[Bug] SQL 2019 AG Deployment adds master db - New-DbaAvailabilityGroup

### ISSUE THREAD

**Issue by marcosfreccia** [sqlcollaborative/dbatools#6213]
### Environmental information

```powershell
Parent                         : de
LCID                           : 1031
KeyboardLayoutId               : 1031
Name                           : de-DE
IetfLanguageTag                : de-DE
DisplayName                    : German (Germany)
NativeName                     : Deutsch (Deutschland)
EnglishName                    : German (Germany)
TwoLetterISOLanguageName       : de
ThreeLetterISOLanguageName     : deu
ThreeLetterWindowsLanguageName : DEU
CompareInfo                    : CompareInfo - de-DE
TextInfo                       : TextInfo - de-DE
IsNeutralCulture               : False
CultureTypes                   : SpecificCultures, InstalledWin32Cultures, FrameworkCultures
NumberFormat                   : System.Globalization.NumberFormatInfo
DateTimeFormat                 : System.Globalization.DateTimeFormatInfo
Calendar                       : System.Globalization.GregorianCalendar
OptionalCalendars              : {System.Globalization.GregorianCalendar}
UseUserOverride                : True
IsReadOnly                     : False
```

#### SQL Server: 

```sql
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
```

```sql
us_english
```

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received
We deploy whole SQL Server installation and Availability Groups deployment using PowerShell. Some of the scripts are pure SMO, some are dbatools such as: Install-DbaInstance, New-DbaAvailabilityGroup, etc..

When deploying a two replica SQL Server 2019 Availability Groups, we get in the end of the deployment, master database added to AG, even though we never specified.

#### Steps to Reproduce

We are just executin the following command.

```
            $Params = @{
                Primary = $PrimaryInstance
                Secondary = $PrimaryInstance
                Name = $ListenerName
                ClusterType = "Wsfc"
                SeedingMode = "Automatic"
                FailoverMode = "Automatic"
                Confirm = $false
                IPAddress = $Ip 
                SubnetMask = $SubnetMask

            }

New-DbaAvailabilityGroup @Params
```

#### Expected Behavior

A new availability groups created without any database added to it.

#### Actual Behavior

master database gets added, and we cannot remove it from SSMS. You can see in the PowerShell deployment screen below, where it says trying to add master.
![image](https://user-images.githubusercontent.com/29305097/69243737-f539c480-0ba3-11ea-8d76-ed185ca58b2f.png)

**Comment by wsmelton** [comment]
Please put a title on the issue.

I'd also not that we have not fully tested with 2019. I recall seeing something about master and msdb being able to add to an AG in 2019.

**Comment by marcosfreccia** [comment]
My bad! I hit the save button to fast..

**Comment by andreasjordan** [comment]
If think this is fixed in the last version - now no database should be added if -Database is not provided. @marcosfreccia can you please retry?
