### ISSUE TITLE
Make Set-DbaStartupParameter accept a collection of SQL Server instances

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#6214]
### Summary of new feature

Unlike many (most?) functions, `Set-DbaStartupParameter` does not accept a list of `SQLInstance`s to operate against. When configuring multiple instances, this would come in very handy. Presently, one has to wrap the function in a `foreach` loop.

### Proposed technical details (if applicable)

Implement a loop internal to the function to iterate over the list of passed-in `SqlInstance`s and set the startup parameter on each instance.

### Latest version of dbatools as of writing

1.0.72

**Comment by wsmelton** [comment]
Do we have other set functions that allow multiple? I thought we kept it to single object process.

**Comment by alevyinroc** [comment]
We have quite a few `Set-` functions that take a collection of instances or computer names. `Set-DbaDbOwner`, `Set-DbaDbCompression`, `Set-DbaLogin`, Set-DbaTempDbConfig`, `Set-DbaSpConfigure`, and `Set-DbaPrivilege` for example
