### ISSUE TITLE
[Bug] Get-DbaService returning service Update-DbaServiceAccount does not support (Power BI Report Server)

### ISSUE THREAD

**Issue by rscottcovington** [sqlcollaborative/dbatools#6217]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                                                            
----                           -----                                                                                                                                                                                            
PSVersion                      5.1.14393.2969                                                                                                                                                                                   
PSEdition                      Desktop                                                                                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                          
BuildVersion                   10.0.14393.2969                                                                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                                                                  
WSManStackVersion              3.0                                                                                                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                                                                                              
SerializationVersion           1.1.0.1                                                                                                                                                                                          




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.68\dbatools.psd1
Version : 1.0.68

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.52\dbatools.psd1
Version : 1.0.52

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.5\dbatools.psd1
Version : 1.0.5

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.4\dbatools.psd1
Version : 1.0.4




```

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

### Report

 
Get-DbaService returns a PowerBIReportServer service but when piped to Update-DbaServiceAccount, it cannot update the password because it uses SMO and that cannot update the service.

#### Host used

- [ X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```


PSMessageDetails      : 
OriginInfo            : ************REMOVED SERVER NAME********
Exception             : System.Management.Automation.RemoteException: You cannot call a method on a null-valued expression.
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 10
PipelineIterationInfo : {}

```

#### Steps to Reproduce

Example command:
Get-DbaService -ComputerName ServerName1 |where {$_.startmode -like 'auto*' -and $_.startname -eq "DOMAIN\User1"}|Update-DbaServiceAccount -SecurePassword $SecurePassword
#### Expected Behavior

Either ignore the PowerBIReportServer service or use another means to reset the password (other than SMO).
#### Actual Behavior
Get-DbaService returns a PowerBIReportServer service but when piped to Update-DbaServiceAccount, it cannot update the password.

**Comment by rscottcovington** [comment]
Adding an additional issue with Get-DbaService: 
WARNING: [08:16:56][Get-DbaService] No services found in relevant namespaces on SERVER-NAME-REMOVED. Please note that this function is available from SQL 2005 up.

This command was executed on a SQL 2012 server as follows:
Microsoft SQL Server 2012 (SP4-GDR) (KB4057116) - 11.0.7462.6 (X64)   Jan  5 2018 22:11:56   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by rscottcovington** [comment]
Regarding the secondary issue.  Discovered that the error "WARNING: [08:16:56][Get-DbaService] No services found in relevant namespaces..." was the result of a corrupted Configuration Manager.  Executing this on the server resolved the issue and allowed the function to work properly: mofcomp "C:\Program Files (x86)\Microsoft SQL Server\110\Shared\sqlmgmproviderxpsp2up.mof”.

**Comment by wsmelton** [comment]
So once you resolved the error do you get the same result?

Do you get the same result on the latest release of the module, 1.0.73.

**Comment by rscottcovington** [comment]
Once I ran mofcomp the warning message in get-dbaservice was resolved.  If I knew how to “break” SMO in a similar manner, I could run more tests but I haven’t found how to duplicate the issue – yet.

Just loaded the most current version of dbatools and I get the same error for Test-DbaManagementObject when executed on a server where SQL server isn’t installed.


Scott Covington
AHB Database Administrator / BSIS
Application Hosting Branch (AHB)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[cid:image019.png@01D1F3DD.03F365E0]


*** Please note that SQL 2012 Dev/Test/Train/UAT will be shut down October 31, 2019, Staging on November 30, 2019 and finally production on Dec 31, 2019.  Please plan accordingly to migrate your database(s)***

**Comment by rscottcovington** [comment]
Found another server where its broken:

[cid:image001.png@01D5A50E.305BDEB0]

I did this by running Get-dbaservice and identifying occurences of this output:

WARNING: [10:27:03][Get-DbaService] No services found in relevant namespaces on server.cdc.gov. Please note that this function is available from SQL 2005 up.

So, for the purpose I was trying to use Test-DbaManagementObject for, I can achieve the result by using Get-dbaservice.

Scott Covington
AHB Database Administrator / BSIS
Application Hosting Branch (AHB)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[cid:image019.png@01D1F3DD.03F365E0]


*** Please note that SQL 2012 Dev/Test/Train/UAT will be shut down October 31, 2019, Staging on November 30, 2019 and finally production on Dec 31, 2019.  Please plan accordingly to migrate your database(s)***

**Comment by potatoqualitee** [comment]
I also encountered the same issue. My issue had to do with the firewall but I've also had to rebuild the MOF. Just not sure how to differentiate between a broken SMO and no SMO 🤔

**Comment by potatoqualitee** [comment]
btw, cool as hell to be used at the CDC!! 😁😁😁😁🥳🥳🥳🥳

**Comment by rscottcovington** [comment]
According to Shawn Melton, the Test-DbaManagementObject looks for this file:

C:\Windows\assembly\GAC_MSIL\Microsoft.SqlServer.Smo is present or not.

I submitted a bug report because it gets an error when SMO isn’t on the remote server.

Although not perfect, I think the logic that Test-DbaManagementObject and Get-DbaService could be combined to offer a better solution.

Get-DBAService returns an informational message when SMO is broken “WARNING: [11:23:49][Get-DbaService] No services found in relevant namespaces on...” and Test-DbaManagementObject checks for the existence of a file.  So…

Check for the file (return informational message if it’s not there or version info if it is)
Check for SQL services with SMO and return informational message like it currently does if its not able to enumerate them (the issue I reported where its returning a non-SQL service would need to be corrected though).

Make sense?

Scott Covington
AHB Database Administrator / BSIS
Application Hosting Branch (AHB)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[cid:image019.png@01D1F3DD.03F365E0]


*** Please note that SQL 2012 Dev/Test/Train/UAT will be shut down October 31, 2019, Staging on November 30, 2019 and finally production on Dec 31, 2019.  Please plan accordingly to migrate your database(s)***

**Comment by rscottcovington** [comment]
I ran some code that captured the servers in our environment that were returning the warning from Get-DbaService and then I executed this to fix it:

foreach ($s in $servers)
{
invoke-command -computer $s.server -scriptblock{
$file=gci -path "c:\Program Files (x86)\Microsoft SQL Server" -recurse -filter "sqlmgmproviderxpsp2up.mof"| % { $_.FullName }
$command = "mofcomp `"$file`""
iex $command}
}


Scott Covington
AHB Database Administrator / BSIS
Application Hosting Branch (AHB)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[cid:image019.png@01D1F3DD.03F365E0]


*** Please note that SQL 2012 Dev/Test/Train/UAT will be shut down October 31, 2019, Staging on November 30, 2019 and finally production on Dec 31, 2019.  Please plan accordingly to migrate your database(s)***

**Comment by potatoqualitee** [comment]
Ohh a Repair Mof command would be useful! I needed to look up the syntax just today.

**Comment by wsmelton** [comment]
Ok but as it pertains to the original bug report in this issue....the piping between `Get-DbaService and Update-DbaServiceAccount` works?

A new issue can be created if you want to submit a request feature to have a command around testing with the MOF for SMO is corrupt or not.

**Comment by wsmelton** [comment]
#6218

**Comment by rscottcovington** [comment]
No, it still doesn’t behave correctly. Get-dbaservice returns a non-sql service that update-dbaservice cannot handle.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wsmelton** [comment]
Can you provide the full output of `Get-DbaService ... -Verbose` so we can see what detail it is picking up of that PBI Service?

**Comment by rscottcovington** [comment]
1st Command executed:
Get-DbaService -ComputerName $server |where {$_.startmode -like 'auto*' -and $_.startname -eq "$account"}

Results:
ComputerName : ************
ServiceName  : PowerBIReportServer
ServiceType  : SSRS
InstanceName : PBIRS
DisplayName  : Power BI Report Server
StartName    : **************
State        : Running
StartMode    : Automatic

I just now noticed that the ServiceType=’SSRS’ even though its not REALLY SSRS – it’s PowerBI.

2nd Command executed:
Get-DbaService -ComputerName $server |where {$_.startmode -like 'auto*' -and $_.startname -eq "$account"}|Update-DbaServiceAccount -SecurePassword $SecurePassword

Results:
WARNING: [12:55:12][Update-DbaServiceAccount] Cannot find type [Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer]: verify that the assembly containing this type is loaded.

ComputerName : ************
ServiceName  : PowerBIReportServer
State        : Running
StartName    : **************
Status       : Failed
Message      : Cannot find type [Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer]: verify that the assembly containing this type is loaded.



Scott Covington
AHB Database Administrator / BSIS
Application Hosting Branch (AHB)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[cid:image019.png@01D1F3DD.03F365E0]


*** Please note that SQL 2012 Dev/Test/Train/UAT will be shut down October 31, 2019, Staging on November 30, 2019 and finally production on Dec 31, 2019.  Please plan accordingly to migrate your database(s)***
