### ISSUE TITLE
Copy-DBADatabase Writes backup files but then says it fails

### ISSUE THREAD

**Issue by imimmortl** [sqlcollaborative/dbatools#6224]
#### PowerShell version:

```
Name                           Value                                                  
----                           -----                                                  
PSVersion                      5.1.14393.953                                          
PSEdition                      Desktop                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                
BuildVersion                   10.0.14393.953                                         
CLRVersion                     4.0.30319.42000                                        
WSManStackVersion              3.0                                                    
PSRemotingProtocolVersion      2.3                                                    
SerializationVersion           1.1.0.1                                                
#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.72\dbatools.psd1
Version : 1.0.72
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.52\dbatools.psd1
Version : 1.0.52
```
#### SQL Server: 

Source Version: Microsoft SQL Server 2008 (SP1) - 10.0.2531.0 (X64)   Mar 29 2009 10:11:52   Copyright (c) 1988-2008 Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (VM) 

Destination Version: Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### Report

Was trying to  use `Copy-DbaDatabase` switched to `Backup-DbaDatabase` and received the same error message.

#### Host used
- [ ] ISE
- [ ] Still buggy in powershell.exe

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Exception: The multi-part identifier ".backupset.backup_finish_date" could not be bound. ---> System.Data.SqlClient.SqlException: The multi-part identifier ".backupset.backup_finish_date" could not be bound.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], Exception
FullyQualifiedErrorId : dbatools_Backup-DbaDatabase
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.52\allcommands.ps1: line 81312
                        at Backup-DbaDatabase<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.52\allcommands.ps1: line 1528
                        at <ScriptBlock>, C:\Users\TMDaniels\OneDrive - Hospital Sisters Health System\PS_Scripts\ServerMove\ServerMove.ps1: line 8
PipelineIterationInfo : {}
```

#### Steps to Reproduce

This is able to be reproduced between several different servers, only giving the one as an example.

#### Expected Behavior

Database Backup

#### Actual Behavior

Error Message thrown.

**Comment by potatoqualitee** [comment]
🤔  no idea, @Stuart-Moore any idea?

**Comment by wsmelton** [comment]
@imimmortl Please update your post with the command(s) you tried to actually run.

**Comment by imimmortl** [comment]
This is the command: Copy-DbaDatabase -Source "ilxdb-server0" -Destination "ilxdb-server1" -BackupRestore -Database "testdb" -SharedPath \\ilxdb-ssis01\BACKUPTEMP -SourceSqlCredential $cred -DestinationSqlCredential $cred -Force

**Comment by imimmortl** [comment]
Is there anything else I could provide to help with debugging the issue?  If someone would like me to help duplicate I can be available.

**Comment by Stuart-Moore** [comment]
Sorry, been away for a bit.
That error is actually being raise by the call to Get-DbaDbBackupHistory in Backup-DbaDatabase.

Could you let me know what happens if you try this please (swapping in your correct values if the above were obfuscated):
`Get-DbaDbBackupHistory -SqlInstance ilxdb-server0 -SqlCredential $cred -Database testdb -Last`

**Comment by imimmortl** [comment]
Thanks for getting back to my Stuart.  I think I may have found the issue.  The error that I am getting back is:
Exception calling "ExecuteWithResults" with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.52\allcommands.ps1:21509 char:25
+ ...             $results = $server.ConnectionContext.ExecuteWithResults($ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ExecutionFailureException

On line 21488 right before the execute line above there is the following:
                        $sinceSqlFilter = "AND .backupset.backup_finish_date >= CONVERT(datetime,'$($Since.ToString("yyyy-MM-ddTHH:mm:ss"))',126)"


I believe the leading "." in backupset is what is leading to the issues.  Please check if this is still in the current code base.

**Comment by Stuart-Moore** [comment]
It's fixed in the most recent version, and appears to have been fixed since the function was renamed from Get-DbaBackupHistory to Get-DbaDbBackupHistory. Rename makes tracing the changes awkward. Could you try with the latest version 1.0.77 and let me know if the issue is fixed please

**Comment by wsmelton** [comment]
@Stuart-Moore just FYI... you can track the changes much easier from local copy of the repo. The history changes break in GitHub when we rename files but the local git history log still has it all together.

**Comment by imimmortl** [comment]
Yes it is working on the new build.  Thanks for all the help!
