### ISSUE TITLE
Password parameter names not aligned for Backup-DbaDbCertificate and Restore-DbaDbCertificate

### ISSUE THREAD

**Issue by garyhampson** [sqlcollaborative/dbatools#6225]
Backup-DbaDbCertificate has 
`[-EncryptionPassword] <SecureString>]`
`[-DecryptionPassword <SecureString>]`

whereas Restore-DbaDbCertificate has 
`[-EncryptionPassword] <SecureString>]` 
`[-SecurePassword] <SecureString>]`

In looking at the parameter definitions, it seems they are both used for the same purpose.

> -DecryptionPassword
> A string value that specifies the system path to decrypt the private key.

> -SecurePassword
> Secure string used to decrypt the private key.

**Comment by wsmelton** [comment]
The parameters in the command are correct and match up, this is simply the documentation does not...at least the way I find the commands right now.

**Comment by wsmelton** [comment]
So this one is a bit off in parameters but also the documentation for each does not match up. Restore command has the SecurePassword parameter but the documentation does not present that parameter and shows it as DecryptionPassword. It does have an alias for the later though so technically they do match up, just not directly.
