### ISSUE TITLE
Documentation for Get-DbaNetworkCertificate is incorrect

### ISSUE THREAD

**Issue by ddraillantclark** [sqlcollaborative/dbatools#6231]
The documentation for Get-DbaNetworkCertificate appears to be incorrect. It indicates that it "gets computer certificates [...] that are candidates for using with SQL Server's network encryption", when in fact this command gets the certificate that is currently used for network encryption on each SQL instance on the target ComputerName.

**Comment by potatoqualitee** [comment]
thank you @ddraillantclark that is indeed a bad copy/paste job on my part.
