### ISSUE TITLE
[Bug] Invoke-DbaQuery -File throws error on Windows

### ISSUE THREAD

**Issue by chadbaldwin** [sqlcollaborative/dbatools#6235]
NOTE: I looked around for release notes, and couldn't find anything regarding this. So I don't know if this is just the syntax we need to use from now on, of if this is actually a bug? If I missed something, then my apologies.

Regarding Invoke-DbaQuery, related to the changes made for #6145
This issue may also be a duplicate of #6184, but I can't tell
It appears this started happening at commit id a890034

### Environmental information
```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.19035.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19035.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.74\dbatools.psd1
Version : 1.0.74
```

### Report
On Windows 10, in any version of Powershell (Windows Powershell, PS Core 6, PS Core 7)

I receive the following error when using the following syntax:
`Invoke-DbaQuery -SqlInstance SERVER -Database Database_Name -File .\SqlFileName.sql;`

This is the error I receive:
```
Exception calling ".ctor" with "1" argument(s): "Invalid URI: The format of the URI could not be determined."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.74\allcommands.ps1:46426 char:29
+                             $uri = [uri]::New($item)
+                             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UriFormatException
```

If I change the syntax to this, then it runs without problems:
`Invoke-DbaQuery -SqlInstance SERVER -Database Database_Name -File (Get-Item .\SqlFileName.sql);`

If I revert the changes from commit a890034, then I'm able to use that syntax again.

**Comment by wsmelton** [comment]
It is a duplicate issue.
