### ISSUE TITLE
Export-DbaScript -NoPrefix without -Append parameter keeps appending to file instead of rewrite

### ISSUE THREAD

**Issue by flygovic** [sqlcollaborative/dbatools#6237]
### Problem

When trying to script SQL Agent Jobs to file without Prefix using Export-DbaScript -NoPrefix, it omits default behavior (overwriting file) and every next run appends content to end of file instead of rewriting it.

### Version used
```
PS C:\Windows\system32> Get-Module dbatools -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Script     1.0.75     dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Start-DbaMigration, Copy-DbaDatabase...}
```

### Steps to reproduce

Execute this part of code for YourSQLServer instance once, then do it again and check one Job script file in your FilePath folder
```
# export all jobs

$jobs = Get-DbaAgentJob -SqlInstance YourSQLServer
foreach ($job in $jobs) { 
    $job | Export-DbaScript -NoPrefix -FilePath D:\project-path\Jobs\$($job.name).sql
}
```

Please do check if this is bug in behavior, as I am trying to use this steps to version all Jobs and need to have changes overwritten every time i run above script

Thanks,

**Comment by andreasjordan** [comment]
This was fixed some versions ago:

![image](https://user-images.githubusercontent.com/66946165/125947783-ec3fde8d-f920-4c79-ba25-8e942d119a99.png)


So I will close this.
