### ISSUE TITLE
test-dbadbcompatibility returns false positive for sql 2019

### ISSUE THREAD

**Issue by prvpgroce** [sqlcollaborative/dbatools#6238]
test-dbadbcompatibility fails every db check for compatibility against sql 2019 instances. the sql instance returns the wrong value 'Version150' and '150'

ComputerName          : SERVER1
InstanceName          : INST1
SqlInstance           : SERVER1\INST1
ServerLevel           : Version150
Database              : tempdb
DatabaseCompatibility : 150
IsEqual               : False

Its a problem with sql 2019 i am not sure if it can be fixed in this function?

**Comment by wsmelton** [comment]
150 is the compatibility number for a database in SQL Server 2019.

**Comment by wsmelton** [comment]
The details requested in our template were not provided. Please open a new issue and provide those details after you have confirmed the issue still exists.

It works as expected for my 2019 instance:
![image](https://user-images.githubusercontent.com/11204251/71494336-082b5e80-280c-11ea-82dc-9075bbe97568.png)
