### ISSUE TITLE
Rename-DbaDatabase: rename applied multiple times on log file

### ISSUE THREAD

**Issue by Skodaddy** [sqlcollaborative/dbatools#6240]
Hello,

it seems the rename is applied multiple times to the filename of the log file if the database contains more than 1 data file.

Initial filenames:
test_gert22_primary.mdf
test_gert22_dat01.ndf
test_gert22_idx01.ndf
test_gert22_log.ldf

command:
$Db_OldName = "test_gert22"
$Db_NewName = "gert22_test"
Rename-DbaDatabase -SqlInstance $Instance_Source -Database $Db_OldName -DatabaseName $Db_NewName -LogicalName "DBN_LGN" -FileName "DBN_FNN" -ReplaceBefore -Move -force

new filename:
gert22_test_primary.mdf
gert22_test_dat01.ndf
gert22_test_idx01.ndf
gert22_testgert22_testgert22_test_log.ldf

**Comment by wsmelton** [comment]
Please create a new issue and provide the details requested in our template.
