### ISSUE TITLE
[Bug] Rename-DbaDatabase: rename applied multiple times on log file

### ISSUE THREAD

**Issue by Skodaddy** [sqlcollaborative/dbatools#6241]
#### PowerShell version:

Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
PSVersion                      5.1.14393.3053                                                                                                                                                            
PSEdition                      Desktop                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                   
BuildVersion                   10.0.14393.3053                                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                                                   

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Version : 1.0.38

#### SQL Server: 

Microsoft SQL Server 2016 (SP2-CU8) (KB4505830) - 13.0.5426.0 (X64)   Jul 21 2019 21:16:47   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

#### Host used

- [ ] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received
No Errors

#### Steps to Reproduce
$Instance_Source = "SQLSERVER\INSTANCE"
$Db_OldName = "test_gert22"
$Db_NewName = "gert22_test"

Rename-DbaDatabase -SqlInstance $Instance_Source -Database $Db_OldName -DatabaseName $Db_NewName -LogicalName "DBN_LGN" -FileName "DBN_FNN" -ReplaceBefore -Move

(DBN, LGN and FNN need to be between bigger than/smaller than)

#### Expected Behavior
Rename of filenames to applied filter DBN_FNN
test_gert22_primary.mdf  -->gert22_test_primary.mdf
test_gert22_dat01.ndf  -->gert22_test_dat01.ndf
test_gert22_idx01.ndf -->gert22_test_idx01.ndf
test_gert22_log.ldf  --> gert22_test_log.ldf

#### Actual Behavior
Logfile rename happens multiple times, it seems this depends on the number of data files that are in the database. In this case 3 data files, so name gets applied 3 times to filename of log
Rename of filenames to applied filter DBN_FNN
test_gert22_primary.mdf  -->gert22_test_primary.mdf
test_gert22_dat01.ndf  -->gert22_test_dat01.ndf
test_gert22_idx01.ndf -->gert22_test_idx01.ndf
test_gert22_log.ldf  --> gert22_testgert22_testgert22_test_log.ldf

**Comment by nvarscar** [comment]
To me, it looks related to #5036 
My attempt to fix this ( #5085 ) was not approved for merge, so I wonder if anyone else has any ideas.

**Comment by andreasjordan** [comment]
@Skodaddy - As #5036 is now solved, can you please retest with the latest version?

**Comment by potatoqualitee** [comment]
Considering closed, if that is not the case, please let us know and we can reopen
