### ISSUE TITLE
[Bug] Calling Add-DbaAgDatabase from primary replica fails to add the database to the secondary replica

### ISSUE THREAD

**Issue by tristanbarcelon** [sqlcollaborative/dbatools#6242]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                                            
----                           -----                                                                                                                                                                            
PSVersion                      5.1.17763.771                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                          
BuildVersion                   10.0.17763.771                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                  
WSManStackVersion              3.0                                                                                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                                                                              
SerializationVersion           1.1.0.1                                                                                                                                                                          

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.75\dbatools.psd1
Version : 1.0.75

```

```powershell
LCID             Name             DisplayName                                                                                                                                                                   
----             ----             -----------                                                                                                                                                                   
1033             en-US            English (United States)                                                                                                                                                       
```

#### SQL Server: 
```sql
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) 
```

```sql
us_english
```

### Report

I am using Add-DbaAgDatabase cmdlet either through powershell or powershell ISE with the following parameters set:
SqlInstance = Server01
Availability Group = ag-test1
Database = testing
Secondary = Server02
SeedingMode = Manual
SharedPath = \\mybackupserver\sqlbackups\Server01\AG
EnableException
Verbose

but it keeps failing as though the sql server service account does not have the permission to access the shared path. I've confirmed that the sql server service account does have permission when I used Invoke-DBAQuery to backup testing database to shared path. Server01 and Server02 are the primary and secondary replicas, respectively.

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Exception: Could not join testing to SecondaryNode
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], Exception
FullyQualifiedErrorId : dbatools_Add-DbaAgDatabase
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, 
                        C:\Program Files\WindowsPowershell\Modules\dbatools\1.0.75\allcommands.ps1: 
                        line 81878
                        at Add-DbaAgDatabase<Process>, 
                        C:\Program Files\WindowsPowershell\Modules\dbatools\1.0.75\allcommands.ps1: 
                        line 167
                        at Publish-Dacpac, <No file>: line 317
                        at <ScriptBlock>, <No file>: line 73
PipelineIterationInfo : {}

```

#### Steps to Reproduce

```powershell
Add-DbaAgDatabase -SqlInstance Server01 -AvailabilityGroup agtest1 -Database testing -Secondary Server02 -SeedingMode Manual -SharedPath '\\mybackupserver\sqlbackups\Server01\AG' -EnableException -Verbose
```

#### Expected Behavior

Based on my understanding of [add-DbaAgDatabase documentation](https://docs.dbatools.io/#Add-DbaAgDatabase), I would have expected the database to be backed up to and restored from `\\mybackupserver\sqlbackups\Server01\AG` successfully and the testing database to be joined to availability group.

#### Actual Behavior

No backup files are created in `\\mybackupserver\sqlbackups\Server01\AG` even though I'm successfully able to backup the db to that path by issuing a BACKUP DATABASE to DISK query using Invoke-DBAQuery. Furthermore, the database is left in the availability group even though it is not present on the secondary replica. I've included some of the verbose log messages from Add-AgDatabase.

VERBOSE: [11:59:36][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [11:59:36][Backup-DbaDatabase] 1 database to backup
VERBOSE: [11:59:36][Backup-DbaDatabase] Backup database [testing]
VERBOSE: [11:59:36][Backup-DbaDatabase] Creating full backup
VERBOSE: [11:59:36][Backup-DbaDatabase] Building file name
VERBOSE: [11:59:36][Backup-DbaDatabase] Setting filename - 201912101159
VERBOSE: [11:59:36][Backup-DbaDatabase] Building backup path
WARNING: [11:59:37][Backup-DbaDatabase] SQL Server cannot check if \\mybackupserver\sqlbackups\Server01\AG exists.
You can try disabling this check with -IgnoreFileChecks
VERBOSE: [11:59:37][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [11:59:37][Backup-DbaDatabase] 1 database to backup
VERBOSE: [11:59:37][Backup-DbaDatabase] Backup database [testing]
VERBOSE: [11:59:37][Backup-DbaDatabase] Creating log backup
VERBOSE: [11:59:37][Backup-DbaDatabase] Building file name
VERBOSE: [11:59:37][Backup-DbaDatabase] Setting filename - 201912101159
VERBOSE: [11:59:37][Backup-DbaDatabase] Building backup path
WARNING: [11:59:37][Backup-DbaDatabase] SQL Server cannot check if \\mybackupserver\sqlbackups\Server01\AG exists.
You can try disabling this check with -IgnoreFileChecks
VERBOSE: [11:59:37][Add-DbaAgDatabase] Backups still exist on \\mybackupserver\sqlbackups\Server01\AG
VERBOSE: Performing the operation "restoring full and log backups of [testing] from [Server01]" on target
"Server02".
VERBOSE: [11:59:37][Restore-DbaDatabase] Changing statement timeout to infinity
WARNING: [11:59:37][Restore-DbaDatabase] No backups passed through.
 This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other issue

**Comment by wsuhoey** [comment]
Please give this bug a proper title.

**Comment by tristanbarcelon** [comment]
Hi @wsuhoey , ahh yes, sorry for the mixup. thank you.

**Comment by wsmelton** [comment]
> the database is left in the availability group even though it is not present on the secondary replica

Are you expecting us to roll back changes made on the primary if the whole thing fails?

> I'm successfully able to backup the db to that path by issuing a BACKUP DATABASE to DISK query using Invoke-DBAQuery

Can you do a backup using `Backup-DbaDatabase` though? We do not use the invoke command to take backups in any of our commands.

**Comment by tristanbarcelon** [comment]
Hi @wsmelton. If the main purpose for Add-DbaAgDatabase is to add the database to availability group and seed the database in the secondary nodes manually, then the expectation is to remove it from the availability group if any of the steps fail. If Add-DbaAgDatabase is skipping the addition of database to availability group when it already exists, then there might not be any need to roll back.

Is Backup-DbaDatabase cmdlet used directly within Add-DbaAgDatabase and is that the reason you're suggesting I use it directly? I implemented a workaround temporarily since I needed to have a working solution that handles creation of a new db in the primary, add it to the availability group, and manually seed on the seconary.

My workaround involved using sqlserver module to: back up database and log on the primary, restore the database and log on the secondary, and finally add the database to the availability group on primary and secondary.

**Comment by wsmelton** [comment]
> If the main purpose for Add-DbaAgDatabase is to add the database to availability group and seed the database in the secondary nodes manually, then the expectation is to remove it from the availability group if any of the steps fail.

We will not support this until SQL Server Management Studio (SSMS) does/or will. As-is there is no clean way of knowing when any error in the process occurs, which is the primary reason you don't see rollback support in SSMS.

> Is Backup-DbaDatabase cmdlet used directly within Add-DbaAgDatabase and is that the reason you're suggesting I use it directly? 

Yes, because backing up using Invoke command is not the same as using our Backup command.

> My workaround involved using sqlserver module

Our module does not work well with the sqlserver module in the same session, you will get different results and we do not test or verify our commands in conjunction with that module.

As you noted you already performed a workaround, does that mean you can no longer duplicate this issue? My initial assumption is this is all environmental. We have other users that use the Add command using the network share as you show in your steps to reproduce and I have not seen others hit this error. I do not have a lab setup at the moment to verify it myself. I will leave this issue open unless others can confirm the issue as well.

**Comment by BradCowell** [comment]
I also am having the same issue (see attached text doc).  I think the problem is with line 241 in Add-DbaAgDatabase:

$replicadb = Get-DbaAgDatabase -SqlInstance $secondaryInstance -Database $db.Name -AvailabilityGroup $ag.Name

I believe this always returns null, which causes an exception on line 253.

This seemed to work fine when the secondary replica's seeding mode was set to Manual, but breaks when set to Automatic.

[Bug Report.txt](https://github.com/sqlcollaborative/dbatools/files/4013154/Bug.Report.txt)
