### ISSUE TITLE
Get-DbaBuildReference how long before latest CU get updated?

### ISSUE THREAD

**Issue by edwillis777** [sqlcollaborative/dbatools#6248]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

How long does it take for the latest CU to get into Get-DbaBuildReference? Example SQL Server 2017 CU18 is out but does not update when I run Get-DbaBuildReference

**Comment by wsmelton** [comment]
Based on releases. We have no set schedule for timing.
