### ISSUE TITLE
DbaServicePrincipalName

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#625]
### Is this a *feature* OR *bug*:
feature

@drewfurgiuele - we're using waffle.io to organize our timeline for upcoming releases. We have 

Upcoming milestone - rickdiculous - Feb 14  - https://github.com/sqlcollaborative/dbatools/milestone/9
Final Milestone - showmewhatyougot - Feb 28 - https://github.com/sqlcollaborative/dbatools/milestone/11

snowball is all for stuart's stuff 👍 

Please pick a deadline and assign this issue to a milestone. Merci!

**Comment by drewfurgiuele** [comment]
Initial coding done; ready to branch and put code in and commit!

**Comment by drewfurgiuele** [comment]
I got my branch all pushed. Need to do the following:

1. Allow for multiple values in some parameters
2. Add -WhatIf to changes
3. Add comments and examples
