### ISSUE TITLE
Allow AzureCredential to pass from Add-DbaAgDatabase to Restore-DbaDatabase

### ISSUE THREAD

**Issue by markfennell** [sqlcollaborative/dbatools#6250]
### Summary of new feature

If databases are backed up to blob storage, the Add-DbaAgDatabase fails with the following warning.
WARNING: [14:22:49][Add-DbaAgDatabase] Failure | A URL to a backup has been passed in, but no credential can be found to access it

This could be circumvented if -AzureCredential could be passed from the Add-DbaAgDatabase to the Restore-DbaDatabase.

### Proposed technical details (if applicable)

I'm not expert enough, but it seems like it could be as simple as adding the AzureCredential parameter to the Add-DbaAgDatabase and passing it to the restore command.

### Latest version of dbatools as of writing

v 1.0.75

**Comment by potatoqualitee** [comment]
thanks, will ask @Stuart-Moore to address

**Comment by wsmelton** [comment]
This would require adjusting just the `Add-DbaAgDatabase` command. The calls to the Backup command simply need to allow for passing in a few items:

- AzureCredential
- AzureBaseUrl

Then the restore will need to allow for the AzureCredential to be passed as well for restoring it from Azure Storage.

**Comment by Stuart-Moore** [comment]
Are you using SAS or Storage Key auth for the blob store? Former should work as we look up the credential name based on the URL

**Comment by markfennell** [comment]
We're currently using a storage key and creating the credential using the New-DbaCredential command as follows.

$CredentialKey = Get-AzStorageAccountKey -ResourceGroupName "SomeResourceGroup" -AccountName "mySQLBackups" 

$CredentialKey = $CredentialKey.Value[0]

New-DbaCredential -Identity "CredentialNameHere" -Name "AzureStorageBackup" -SqlInstance "$($nodeName)\$($sqlInstance)" -SqlCredential $mycreds -SecurePassword (ConvertTo-SecureString $CredentialKey -AsPlainText -Force)

**Comment by Stuart-Moore** [comment]
OK, in that case we'd have to a new paramter to pass that in. SAS is SOOOOO much nicer as we can do that automagically in the backgound :)

The nicer way to handle the URL would be to make Path accept URLs as well as filesystem paths. I though I'd already done that, but apparently not. I'll have a look and see how much work it would be.
