### ISSUE TITLE
Remove-DBADbOprhanUser not removing windows users

### ISSUE THREAD

**Issue by skattie22** [sqlcollaborative/dbatools#6259]
### Environmental information
```
#### PowerShell version:
Name                           Value                                                                               
----                           -----                                                                               
PSVersion                      5.1.17134.858                                                                       
PSEdition                      Desktop                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                             
BuildVersion                   10.0.17134.858                                                                      
CLRVersion                     4.0.30319.42000                                                                     
WSManStackVersion              3.0                                                                                 
PSRemotingProtocolVersion      2.3                                                                                 
SerializationVersion           1.1.0.1                                                                             

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.75\dbatools.psd1
Version : 1.0.75

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.73\dbatools.psd1
Version : 1.0.73

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.25\dbatools.psd1
Version : 1.0.25
```
```
#### SQL Server: 
Microsoft SQL Server 2016 (SP2-CU10) (KB4524334) - 13.0.5492.2 (X64) 
	Oct  4 2019 19:14:08 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor)

#### Host used
- [ ] powershell.exe
- [ ] ISE

#### Errors Received
None - no orphan users were found on database

#### Steps to Reproduce
`remove-dbadborphanuser -sqlinstance "My_SQL_Instance" -database "My_Database" -verbose`
```
#### Expected Behavior

```
SELECT * FROM sys.database_principals dbp
WHERE NOT EXISTS (SELECT 1 FROM sys.server_principals sys WHERE 
				dbp.name = sys.name COLLATE Database_Default)
				AND dbp.type NOT IN ('S','R')
```

produces a bunch of users type_desc = "WINDOWS_USER" and "WINDOWS_GROUP"
These are orphaned users which I would expect to be deleted

Looking into the module, it appears to expect $db.Users Login to be Blank, but it isn't, it contains the same value as the Name

`$db.Users | Where-Object { $_.Login -eq "" -and ($_.ID -gt 4) -and ($User -contains $_.Name) -and (($_.Sid.Length -gt 16 -and $_.LoginType -in @([Microsoft.SqlServer.Management.Smo.LoginType]::SqlLogin, [Microsoft.SqlServer.Management.Smo.LoginType]::Certificate)) -eq $false) }`

What did you expect to happen?
The windows orphan users to be deleted
I tried with an SQL orphaned user and it deleted fine

#### Actual Behavior
Only SQL orphaned users were removed, not Windows users

**Comment by Coreythesaurus** [comment]
Im running into the same thing

**Comment by tlangh15** [comment]
This fix only works for Windows Users, this should also include Windows Groups in the LoginType check.

``
$users += $db.Users | Where-Object { ($_.Name -notin $server.Logins.Name) -and ($_.ID -gt 4) -and ($User -contains $_.Name) -and ($_.Sid.Length -gt 16 -and $_.LoginType -eq [Microsoft.SqlServer.Management.Smo.LoginType]::WindowsUser) }
``

to

``
$users += $db.Users | Where-Object { ($_.Name -notin $server.Logins.Name) -and ($_.ID -gt 4) -and ($User -contains $_.Name) -and ($_.Sid.Length -gt 16 -and $_.LoginType -in @([Microsoft.SqlServer.Management.Smo.LoginType]::WindowsUser, [Microsoft.SqlServer.Management.Smo.LoginType]::WindowsGroup)) }
``
