### ISSUE TITLE
[Bug] Get-DbaBuildReference should pass -UseBasicParsing to Invoke-TlsWebRequest

### ISSUE THREAD

**Issue by atringle-sherweb** [sqlcollaborative/dbatools#6260]
### Environmental information

```
#### PowerShell version:
Name                           Value
----                           -----
PSVersion                      5.1.14393.3383
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3383
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### dbatools Module version:
Name    : dbatools
Version : 1.0.27

#### SQL Server: 
Any version as command has nothing to do with SQL version.

### Report
Get-DbaBuildReferenceIndex may not work and error when run from server core machine or with GMSA as it relies on Internet Explorer. 
The underlying Invoke-TlsWebRequest should use the parameter -UseBasicParsing

#### Host used

- [x ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received
>> TerminatingError(Invoke-WebRequest): "The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. "
WARNING: [06:00:15][Get-DbaBuildReferenceIndexOnline] Couldn't download updated index from https://sqlcollaborative.github.io/assets/dbatools-buildref-index.json
WARNING: [06:00:15][Get-DbaBuildReferenceIndex] Index is stale, last update on: 2019-07-17T00:00:00, try the -Update parameter to fetch the most up to date index

#### Steps to Reproduce
Try Get-DbaBuildReferenceIndex -Update using GMSA on a server core.
I assume this bug would occur on any server with powershell 6, running server core, or using a gmsa.

#### Expected Behavior
Get-DbaBuildReferenceIndex should work

#### Actual Behavior
Due to server core nature and fact that the invoke's within Get-DbaBuildReferenceIndexOnline do not use the parameter -usebasicparsing. The command will fail because its relying on Internet Explorer.

**Comment by wsmelton** [comment]
Be aware this only applies to Windows PowerShell and should validate as such before using the parameter.

The internal command is where this would be required changes.

**Comment by atringle-sherweb** [comment]
Powershell 6-7 also support -UseBasicParsing for backwards compatibility so in theory no validation is required as adding the parameter would support all powershell verisons.

From: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7 

-UseBasicParsing
This parameter has been deprecated. Beginning with PowerShell 6.0.0, all Web requests use basic parsing only. This parameter is included for backwards compatibility only and any use of it has no effect on the operation of the cmdlet.

As for the internal command I agree that its a better patch all, i just did not know if it would affect something else that may rely (for whatever reason) on internet explorer parsing.

**Comment by wsmelton** [comment]
PowerShell 6+ does not require it.

**Comment by atringle-sherweb** [comment]
Yes exactly, my point was more that they left it there for backwards compatibility so that scripts would not need any validation added.

**Comment by niphlod** [comment]
I'll happily do it in today or tomorrow. I'll throw in a $PSVersionTable.PSVersion.Major -lt 6 so we're all happy.

**Comment by wsmelton** [comment]
We have added `Test-PsVersion` for this as well to test for range of versions.

**Comment by niphlod** [comment]
unfortunately inspecting `@Args` is not possible. You can play with `$Args`, but then if an option is passed without the param name it breaks.

Proxy functions aren't so easy when you need to deal with parameters, and the only things I can find online require to build the caller with the same params as the callee (which is not what we want)

I feel the only solution is doing the logic in each command that uses Invoke-TlsWebRequest.

**Comment by wsmelton** [comment]
There is no reason to test for args. The internal command simply validates the version of PS it is running under and uses that parameter because as we move away from Windows PowerShell we no longer need that parameter. And at some point PowerShell 7+ could take the parameter out (not very likely, but it could happen).

You can simply add this to the Invoke-TlsWebRequest:

```powershell
    if (Test-PsVersion -Minimum 6) {
        Invoke-WebRequest @Args
    } else {
        Invoke-WebRequest @Args -UseBasicParsing
    }
```
Unless I'm missing something?

**Comment by niphlod** [comment]
There's no simple way to test if usebasicparsing has been already passed or
not...

Il ven 27 dic 2019, 16:03 Shawn Melton <notifications@github.com> ha
scritto:

**Comment by wsmelton** [comment]
You don't need to test for it.

**Comment by wsmelton** [comment]
We should not be passing the parameter from any command but only testing for the version of PS to know if we need to pass it in the internal command. The code snippet provided is what it would look like in the Invoke-TlsWebRequest.

The problem comes in things like PowerShell 7 and future versions remove the backward compatibility.

**Comment by niphlod** [comment]
Summing up all calls to Invoke-TlsWebRequest needs to have the snippet added (or NEED to avoid using -UseBasicParsing).
IMHO it's the same thing but at this point I'm more inclined to force that flag in Invoke-TlsWebRequest and change all occurrences of calls to Invoke-TlsWebRequest removing it.
This is the only way we can "stash" the complexity away a little bit.
