### ISSUE TITLE
 Find-DbaInstance -ComputerName $server  -scantype all did not give correct port number

### ISSUE THREAD

**Issue by hshica** [sqlcollaborative/dbatools#6265]
### Environmental information
script running windows 10, sql db versions vary from 2008 to 2017

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.14393.3383                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14393.3383                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1          

LCID             Name             DisplayName                                                                                                                            
----             ----             -----------                                                                                                                            
1033             en-US            English (United States)     

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [ ] powershell.exe
- [X ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Expected Behavior

the sql instance port number is incorrect as they all show as 0

**Comment by wsmelton** [comment]
Please provide the details asked in the template.

Once that is done we can reopen the issue.
