### ISSUE TITLE
[Bug] Export-DbaUser outputs USE <DB> regardless of ScriptingOptions

### ISSUE THREAD

**Issue by iampeterdaniels** [sqlcollaborative/dbatools#6271]
Apologies for not filling out the form below.  Line 213 of functions/Export-DbaUser.ps1 is:

`$outsql += "USE [" + $db.Name + "]"`

This negates any ScriptingOptions.IncludeDatabaseContext passed to the function via the -ScriptingOptionsObject param. It even negates the default option set on line 194:

`$ScriptingOptionsObject.IncludeDatabaseContext = $false`

I believe this line 213 should be replaced with something like

`if ($ScriptingOptionsObject.IncludeDatabaseContext) {
    $outsql += "USE [" + $db.Name + "]"
}`

### Environmental information

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [x] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

**Comment by wsmelton** [comment]
Why would you want to create users script without the use statement?

**Comment by iampeterdaniels** [comment]
To apply the generated script to a different DB

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
