### ISSUE TITLE
Set-DbaTempDbConfig allow array of strings as input for DataPath

### ISSUE THREAD

**Issue by areis422** [sqlcollaborative/dbatools#6272]
Starting with the SQL 2016 installer, you can specify multiple paths to have the TempDB data files dropped in, in a round robin fashion.

This cmdlet should be able to do the same. Ex: given the following:

12 data files (-DataFileCount 12)
12GB total size (-DataFileSize 12288)
3 Paths: (-DataPath @('G:\Path','H:\Path','I:\Path'))
    G:\Path
    H:\Path
    I:\Path

Each path should end up with 4 x 1GB files for TempDB.

**Comment by wsmelton** [comment]
The installer allows you to do this in 2016 and above.

Any version of SQL allows you to move data files to any drive you want.

**Comment by areis422** [comment]
Bump
