### ISSUE TITLE
Get-DbaHideInstance

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbatools#6276]
### Summary of new feature

- There are commands to enable and disable this feature but no command to check the status before doing so.  Plus we writing a test in dbachecks for CIS and this would give dbachecks a way to check the setting without having to put a lot of code into dbachecks.

* Clear/concise description of what the problem is that the new feature can solve.

### Proposed technical details (if applicable)

- Use the same code in either Disable-DbaHideInstance or Enable-DbaHideInstance except don't change the values, just display them.

### Latest version of dbatools as of writing

* 1.0.79

**Comment by potatoqualitee** [comment]
yes thank you. please feel free to base it off of `Get-DbaForceNetworkEncryption`. There's also an Enable and Disable. 

For others who are concerned about the naming and how specific the commands are: I totally understand that it's very specific but these flags are unusual and there will only ever be two: ForceNetworkEncryption and HideInstance

![image](https://user-images.githubusercontent.com/8278033/71749494-ee29f580-2e75-11ea-8e9e-ce14d84f8aa5.png)

If I could go back in time, I may have done Flag but ForceNetworkEncryption has been out there for a while and this works.
