### ISSUE TITLE
Cannot add type. The assembly 'Microsoft.SqlServer.Management.DacEnum

### ISSUE THREAD

**Issue by korbenz** [sqlcollaborative/dbatools#6284]
### Environmental information

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

#### dbatools Module version:

Name    : dbatools
Path    : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\dbatools.psd1
Version : 0.9.25

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

Microsoft SQL Server 2014 (SP3-CU4) (KB4500181) - 12.0.6329.1 (X64) 
	Jul 20 2019 21:42:29 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

Can't connect to VS-TSQL9\PROD2014: System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
     Exception calling "Connect" with "0" argument(s): "Failed to connect to server VS-TSQL9\PROD2014." Cannot add type. The assembly 'Microsoft.SqlServer.Management.DacEnum, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' could not be found. Cannot add type. The assembly 'Microsoft.SqlServer.Management.Dac, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' could not be found. Cannot add type. The assembly 'Microsoft.SqlServer.Management.Common, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' could not be found. Cannot add type. The assembly 'Microsoft.SqlServer.Smo, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' could not be found.

#### Steps to Reproduce

simple use of the command Copy-DbaAgentJob.

#### Expected Behavior

to copy SQL job from instance source to instance destination

#### Actual Behavior

nothing, above error is received

**Comment by potatoqualitee** [comment]
Can you please confirm this is an issue with our latest version? Your version is highly out of date. We are now on 1.0.81

**Comment by korbenz** [comment]
Hello,

I am currently trying to update the version.
Will let you know.

Thanks !

Le mer. 8 janv. 2020 à 11:29, Chrissy LeMaire <notifications@github.com> a
écrit :

**Comment by potatoqualitee** [comment]
Note that we removed a lot of aliases in 1.0 so if you have some scripts, back them up then do `Get-ChildItem *.ps1 | Invoke-DbatoolsRenameHelper` to change all of the old names to the updated names.

**Comment by korbenz** [comment]
updated to newer version --> fixed
thanks for helping.

**Comment by potatoqualitee** [comment]
Great news!
