### ISSUE TITLE
[Bug] Invoke-Dbaquery - Exception calling ".ctor" with "1" argument(s): "Invalid URI: The format of the URI could not be determined." 

### ISSUE THREAD

**Issue by alhandra** [sqlcollaborative/dbatools#6285]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.18362.145                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.18362.145                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.81\dbatools.psd1
Version : 1.0.81

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.52\dbatools.psd1
Version : 1.0.52




```

```powershell
# Replace with output of Get-Culture
```

LCID             Name             DisplayName
----             ----             -----------
2070             pt-PT            Portuguese (Portugal)

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```
Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS) <X64>

```sql
/* REPLACE WITH output of @@LANGUAGE */
```
us_english
#### Host used

- [x ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ x] Still buggy in powershell.exe

#### Errors Received
Invoke-DbaQuery -File .\SQLOPS_AttachDETACH.sql -SqlInstance localhost -SqlCredential $cred
Exception calling ".ctor" with "1" argument(s): "Invalid URI: The format of the URI could not be determined."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.81\allcommands.ps1:46595 char:29
+                             $uri = [uri]::New($item)
+                             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UriFormatException

```


PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Invalid URI: The format of the URI could not be determined." ---> System.UriFormatException: Invalid URI: 
                        The format of the URI could not be determined.
                           at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
                           at CallSite.Target(Closure , CallSite , Type , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Type , Object )
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : UriFormatException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-DbaQuery<Begin>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.81\allcommands.ps1: line 46595
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

1 - run Invoke-DbaQuery -File example_file.sql -SqlInstance localhost 
try on version 1.0.52 and the latest 
#### Expected Behavior

no exception to be raised

#### Actual Behavior
an exception was raised

the code still executed but we got an exception

**Comment by potatoqualitee** [comment]
oh, no not sure how a `::new()` got past us with `$uri = [uri]::New($item)`. @wsmelton or @niphlod can you fix? this is not 3.0 compat

**Comment by potatoqualitee** [comment]
(this may have also been fixed in a newer version, we are on 1.0.81)

**Comment by alhandra** [comment]
actually it's not working on the latest version.
 I have tested that this is really broken on 1.0.81 and was working on 1.0.52

**Comment by potatoqualitee** [comment]
Oh! thank you fo the clarification

**Comment by wsmelton** [comment]
We have an issue open on this to address.

**Comment by wsmelton** [comment]
It is not supposed to call that unless it is on correct PS version.

The use of New is not the issue, even with PS3. It is use of URI in general does not support relative paths, you have to pass the full path to the command.

**Comment by wsmelton** [comment]
#6184

**Comment by potatoqualitee** [comment]
ahh would a good solution be to ensure that the path doesnt start with a '.\' ?

**Comment by wsmelton** [comment]
That are we have to just build the absolute path...which is why I want to see who voted it up.

Only a few folks have hit it because the examples for that parameter show a full path.

**Comment by sigreiner** [comment]
Just a quick note that I'm hitting that bug with version 1.0.101.

**Comment by joshs-STCU** [comment]
Also hitting the bug in 1.0.113...

**Comment by wsmelton** [comment]
This issue is closed as we are not addressing it at this time.

The proper use is to provide the full path of the file.
