### ISSUE TITLE
Find-DbaLoginInGroup putting wrong domain name with login

### ISSUE THREAD

**Issue by TJDBA** [sqlcollaborative/dbatools#6286]
We have a scenario where we have users in 2 different domains and the older users have 2 different SamAccountName values. For example in one domain they are FirstName.LastName and in the other domain they are FirstIntialLastName. (domain1\john.smith & domain2\jsmith)

It looks like it is because _$memberDomain = $ads.Name_ doesn't rotate so it using the wrong domain and ends up looking like 
Domain1\john.smith
Domain1\jsmith

**Comment by awickham10** [comment]
Do you think that line could be changed to ```$member.Context.Name```?

**Comment by TJDBA** [comment]
I made that change on the snippet I'm testing with (see below) and it mostly works. It displays the correct domain but leaves the .net on one of them:
domain1\john.smith
domain2.net\jsmith

For me, this is acceptable since I'm just using this for reporting right now, but I could see how it might be problematic if someone was trying to build scripts around it. 

```
$results = Get-ADGroupMember -Server celdc1 -Identity "DatabaseAdministrators" -Recursive | Where-Object name -like '*loparco*'
$ads = New-Object System.DirectoryServices.AccountManagement.PrincipalContext('Domain', 'celestial')
$group = [System.DirectoryServices.AccountManagement.GroupPrincipal]::FindByIdentity($ads, 'DatabaseAdministrators');
$group

Add-Type -AssemblyName System.DirectoryServices.AccountManagement
$output = @()
foreach ($member in $group.Members) {
    $memberDomain = $member.Context.Name#$ads.Name
 #   if ($member.StructuralObjectClass -eq 'group') {
 #       $fullName = $memberDomain + "\" + $member.SamAccountName
 #       if ($fullName -in $discard) {
 #           Write-Message -Level Verbose -Message "skipping $fullName, already enumerated"
 #           continue
 #       } else {
 #           $subgroups += $fullName
 #       }
 #   } else {
    $member.SamAccountName
        $output += [PSCustomObject]@{
            SqlInstance        = $server.Name
            InstanceName       = $server.ServiceName
            ComputerName       = $server.ComputerName
            Login              = $memberDomain + "\" + $member.SamAccountName
            DisplayName        = $member.DisplayName
            MemberOf           = $AdGroup
            ParentADGroupLogin = $ParentADGroup
  #      }
    }
}
```

**Comment by awickham10** [comment]
Looks like it's the FQDN instead of the NetBIOS name for the domain. I'm thinking that may just be the way Active Directory works, but I can't test that 😢 sorry. I can put in a PR to make the change.

**Comment by TJDBA** [comment]
I just talked to a couple of my domain admins and they said FQDN shouldn't make in the scenarios we could think up. 
Thank you for your help.
