### ISSUE TITLE
Backup-DbaDatabase doesn't raise error

### ISSUE THREAD

**Issue by CrystalPalace** [sqlcollaborative/dbatools#6288]
Hello,

I'm  actually writing a script for backup my databases on my server, and i noticed that if the command "backup-dbadatabase" was called with wrong parameters it did not raise an error (see example). 

Is this an expected behavior?
How can I fix this?

```
PS C:\Users\XXX> Backup-DbaDatabase -SqlInstance MyComputer -Database DBnotExist -FilePath D:\DB_BACKUP\WrongPath\WrongDB.bak -Type Full -Verify -EnableException
PS C:\Users\XXX> $?
True
```

**PowerShell**

PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**dbatools**

1.0.52     dbatools                            PSGallery            The community module that enables SQL Server Pros to automate database development and server administration

**Comment by Stuart-Moore** [comment]
Should it raise an error? It's completed what you've asked it to do without problems

An error would be raised if it couldn't connect to the specified instance or it couldn't write to the filepath

Returning a $null record has been the standard for years so I don't want to break that and then break a lot of other people's scripts/workflows.

Have added a warning when no database match the request as parth of another fix. Use the WarningVariable parameter to test, ie;
```
Backup-DbaDatabase -SqlInstance local\sql2016 -Database 404NotFound -WarningVariable WarnVar
if ($null -ne $WarnVar){
# Cope with no output
} 
```

You could also just check the ouput if you can't upgrade to the dev version for a bit.:
```
$Backup = Backup-DbaDatabase -SqlInstance local\sql2016 -Database 404NotFound 
if ($null -eq $Backup){
# No backup done, cope appropriately
}
```

**Comment by CrystalPalace** [comment]
The command don't raise any error or warning.
It's a incorrect database name and it's impossible to write to the FilePath because it doesn't exist.
I will check the output as you told me.

**Comment by Stuart-Moore** [comment]
It'll now output a warning if you update to the latest dev version

**Comment by potatoqualitee** [comment]
Thank you, Stuart 🙇
