### ISSUE TITLE
Add-DbaDbRoleMember 

### ISSUE THREAD

**Issue by eseckinger** [sqlcollaborative/dbatools#6293]
It appears that the -Confirm flag is not working correctly. It is prompting even without the flag being used.

**Comment by potatoqualitee** [comment]
hey @eseckinger - some commands do require `-Confirm:$false` to bypass confirm. That one probably has a confirmimpact of high which is why you are seeing it by default. how do we determine what is low, medium or high? we just guess 😅  i agree that High seems a bit unnecessary.

**Comment by eseckinger** [comment]
Thank you for letting me know.  I did try this.
Add-DbaDbRoleMember -SqlInstance $sqlInstance -SqlCredential $mycreds  -Database $db.Name -Role $sqlRole -User $appuser -Confirm:false .  
and it is still occurring
