### ISSUE TITLE
Use "last backup" oriented commands when there is a third party backup source (like CommVault or Veeam)

### ISSUE THREAD

**Issue by DBAdminDB** [sqlcollaborative/dbatools#6300]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

Hi, 
first I want to thank you all for your good and hard work.

I am guessing that the parameter "last backup" (for example "UseLastBackup" in copy-dbadatabase) takes the last backup from the DMV: backupmediafamily 
and i was wondering what if there is a third party backup tool like CommVualt that stores the backup path in the Physical_backup_device column like this "{38F8W73UF:7SDF9E8DF:SDF8D8UEJ}"
or any other non standard name,
or not even third party backup tools but somebody who backed up the database to NUL, so there is no physical path to take the backup from,
would it generate an error or it will try to restore from this path?

**Comment by awickham10** [comment]
I tried this out and got the below. You'll get some warnings when it runs that the path isn't accessible and a return object with a Status column indicating it failed.

![image](https://user-images.githubusercontent.com/7840633/72348770-1cdf7180-36a9-11ea-899f-385ba8edc07a.png)

**Comment by DBAdminDB** [comment]
@awickham10  cool, thank you
