### ISSUE TITLE
[Bug] Invoke-DBAQuery -File AbsolutePath throw error

### ISSUE THREAD

**Issue by ochoto** [sqlcollaborative/dbatools#6303]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      4.0                                                                                     
WSManStackVersion              3.0                                                                                     
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                     4.0.30319.36543                                                                         
BuildVersion                   6.3.9600.19170                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                    
PSRemotingProtocolVersion      2.2                                                                                     




#### dbatools Module version:


Name    : dbatools
Path    : C:\ps\modules\dbatools\dbatools.psd1
Version : 1.0.82




```

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

### Report

 

When I run  Invoke-DbaQuery -File AbsolutePath I get "Method invocation failed because [System.Uri] does not contain a method named 'New'."

Invoke-DbaQuery -sqlinstance localhost -File "C:\ps\sql\test.sql"

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```


PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: Method invocation failed because [System.Uri] 
                        does not contain a method named 'New'.
                           at CallSite.Target(Closure , CallSite , RuntimeType , Object )
                           at Invoke-DbaQuery<Begin>(Closure , FunctionContext )
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : MethodNotFound
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-DbaQuery<Begin>, C:\ps\modules\dbatools\allcommands.ps1: line 46638
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

Create a file in the directory "c:\sql" named "test.sql"
In the file type: "SELECT @@Version"

Run the Command: Invoke-DbaQuery -SqlInstance MyServer\MyInstance -File C:\sql\test.sql

#### Expected Behavior

Query is run without exceptions thrown

#### Actual Behavior

The following exception is thrown and query is executed:

Method invocation failed because [System.Uri] does not contain a method named 'New'.
At C:\ps\modules\dbatools\allcommands.ps1:46601 char:29
+                             $uri = [uri]::New($item)
+                             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Column1
-------
Microsoft SQL Server 2012 (SP4-OD) (KB4091266) - 11.0.7469.6 (X64) ...

**Comment by wsmelton** [comment]
#6184 duplicate
