### ISSUE TITLE
How to request Slack invitation?

### ISSUE THREAD

**Issue by win32nipuh** [sqlcollaborative/dbatools#6306]
I have entered my email  here
https://dbatools.io/slack/
as it is described, clicked submit and receive the message:
"Unknow error: token_revoked"

How to receive the invitation ?

**Comment by potatoqualitee** [comment]
Thanks for the post, i need to update the link to be a wildcard https://aka.ms/sqlslack should work until I do. Please let me know if you have any issues.

**Comment by potatoqualitee** [comment]
I have updated the link to be *dbatools.io/slack* but it's likely cached for you so please use the aka link 👍

**Comment by win32nipuh** [comment]
Thanx, it works now :-)
