### ISSUE TITLE
copy-login with -force

### ISSUE THREAD

**Issue by DBAdminDB** [sqlcollaborative/dbatools#6313]
Hi,

When i run the command copy-dbalogin -source<dbname1> -Destination <dbname2> -Login sql -Force
i get the following massage:
![image](https://user-images.githubusercontent.com/58941976/72533974-bad86500-387e-11ea-8793-53ca41b1fdf4.png)
only failed with no more information...

what i did is this:
i had 2 sql logins, one on each server, i've changed the password of this login on dbname1 and wanted to sync it on dbname2, but its not working... how can i debug it?

**Comment by DBAdminDB** [comment]
I've found out why this is happening...

its because the user was connected... maybe add option to sync -force with killing all sessions of this user...

**Comment by wsmelton** [comment]
We have a command to kill sessions of users prior to running the copy command. That would be the proper process to use for this situation.

**Comment by wsmelton** [comment]
Actually, hold on. We have a switch for this already in the command. You can use the Force with KillActiveConnection and that will kill connections on the destination.

Check the help for more details.

**Comment by DBAdminDB** [comment]
nice, what if i want to run this command when someone changed their password?
in order to keep to sync on, you know...

**Comment by wsmelton** [comment]
The copy command will push the pwd used in source to destination.
