### ISSUE TITLE
Start-DbaAgentJob does not run against multiple servers when comma delimited list passed in

### ISSUE THREAD

**Issue by GLoeffler14** [sqlcollaborative/dbatools#6318]
### Environmental information
Name                           Value                                                                                                                                                                                                   
----                           -----                                                                                                                                                                                                   
PSVersion                      5.1.14393.3053                                                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                 
BuildVersion                   10.0.14393.3053                                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                                         
WSManStackVersion              3.0                                                                                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                     
SerializationVersion           1.1.0.1 

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.83\dbatools.psd1
Version : 1.0.83

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.81\dbatools.psd1
Version : 1.0.81

#### SQL Server: 
Microsoft SQL Server 2016 (SP2-CU7-GDR) (KB4505222) - 13.0.5366.0 (X64)   Jun 15 2019 08:22:25   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

### Report
When using a CDL of servers, only the last one passed in gets executed.
Start-DbaAgentJob -sqlinstance IP1, IP2 -sqlcredential $DCred -job "LSCopy_QDW-Preview_Test"
--above only runs on IP2.
Start-DbaAgentJob -sqlinstance IP1, IP2 -sqlcredential $DCred -job "LSCopy_QDW-Preview_Test"
-- above only runs on IP1

I have verified the job exists on both server.  Command can be run individually with 1 server, but not with multiple

#### Host used
- [XXXX ] ISE

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [XXXX ] Still buggy in powershell.exe

#### Errors Received

no errors.  output just shows the job successful on last server passed in.

#### Steps to Reproduce
run command below adding correct info
Start-DbaAgentJob -sqlinstance <input multiple instances> -sqlcredential <creds here> -job "job name here"

#### Expected Behavior
Job should run on all servers in the CDL

#### Actual Behavior

only runs on last server listed
![image](https://user-images.githubusercontent.com/59977920/72644201-7f9d6b00-393e-11ea-8bb6-021f489763b5.png)

**Comment by wsmelton** [comment]
So you are starting that you basically have this being run as a full example:

```powershell
$dest1 = 'server1'
$dest2 = 'server2'
$DCred = Get-Credential
Start-DbaAgentJob -SqlInstance $dest1,$dest2 -SqlCredential $DCred -Job "LSCopy_QDW-Preview_Test"
```

I am updating the test in order to validate two servers are working properly.

**Comment by GLoeffler14** [comment]
that is correct.  only the last $Dest gets run.  I can switch the order and do $Dest2,$Dest1 and then only $Dest1 gets run
