### ISSUE TITLE
Get-DbaBackupHistory, case sensitivity issues

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#632]
### Is this a *feature* OR *bug*:

Bug

---

Query has lots of column names that are not correct, and in an instance that is case-sensitive it goes into exception

**Comment by ctrlbold** [comment]
Interesting! Never even considered that. Ugh, we'll have to get a CS server to test all of our manual SQL queries.

**Comment by ctrlbold** [comment]
Fixed by @niphlod in #634
