### ISSUE TITLE
version 1.0.40

### ISSUE THREAD

**Issue by DBAdminDB** [sqlcollaborative/dbatools#6323]
Hi,

I have a client which has very very strict access to their network, I've tried to get the newest version in but the deny my request...

i found version 1.0.40 inside the network, and I want to create sync between 2 AlwaysOn servers - sync jobs, logins and permissions.

would it be problematic to use 1.0.40 for this job?  there are known bugs in this version regarding to sync-dbavailabilitygroup?

**Comment by wsmelton** [comment]
You can test in that environment as we cannot tell you whether it will work or not for your setup.

You can search issues for that command to see if anything has been reported.
