### ISSUE TITLE
[BUG] - New-DbaAvailabilityGroup SeedingMode cannot be found on this object

### ISSUE THREAD

**Issue by jphillips-dev** [sqlcollaborative/dbatools#6324]
When trying to create 3 Microsoft SQL Server 2016 clusters on the most recent version of dbatools I noticed this issue where I get this error: 

WARNING: [08:47:51][New-DbaAvailabilityGroup] The property 'SeedingMode' cannot be found on this object. Verify that the property exists and can be set.

I'm using New-DbaAvailabilityGroup and giving values for the primary, secondary, name, database, seedingmode and shared path, backup priority, database health trigger and confirm. I am setting the seedingmode to "Manual".

**Comment by wsmelton** [comment]
Please provide the information requested in the bug template in a new issue.
