### ISSUE TITLE
function to sync status of jobs (enabled\disabled)

### ISSUE THREAD

**Issue by DBAdminDB** [sqlcollaborative/dbatools#6325]
Hi,

there is a command that I could run every hour that would enable and disable jobs on secondary based on the status of the corresponding jobs on the primary replica?

thanks in advance :)

**Comment by wsmelton** [comment]
You can check out all the documentation on each command by going to [docs.dbatools.io](https://docs.dbatools.io) and it includes full text search. You can type in a few of those key words and it will show you all the commands we have available matching that text in the help.

There should be a few commands that you can use to accomplish the requirements you stated.
