### ISSUE TITLE
Connect-DbaInstance displays sensitive Information.

### ISSUE THREAD

**Issue by Alcasczar** [sqlcollaborative/dbatools#6328]
When you have $VerbosePreference = 'Continue'
Connect-DbaInstance will display sensitive information (Login and Password) in the verbose Output.

```
$AZServer = (Connect-DbaInstance -SqlInstance "azure-sql-server.windows.net" -Database $AZDatabase -MaxPoolSize 10 -SqlCredential $AzureAdminCreds)

#Output.....
VERBOSE: [11:47:07][Connect-DbaInstance] Data Source=TCP:azure-sql-server.windows.net,1433;Initial Catalog=DWdb;User 
ID=sqluser;Password=password;Max Pool Size=10;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;
TrustServerCertificate=False;Application Name="dbatools PowerShell module - dbatools.io"

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0.0    CredentialTools                     {Export-Credential, Get-MyCredential}
Script     1.0.85     dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by nvarscar** [comment]
Culprit (found by @niphlod): https://github.com/sqlcollaborative/dbatools/blob/master/functions/Connect-DbaInstance.ps1#L488

Potential solution would be to reconstruct the connection string using `[System.Data.SqlClient.SqlConnectionStringBuilder]` and replace the password.

Login probably should stay the same, as it is an important debug info.

**Comment by wsmelton** [comment]
Yeah, we need to just remove that line.

**Comment by nvarscar** [comment]
That is an option too :D 
Or lowering the verbosity level to Debug or something. I could see this being used in troubleshooting connection issues.

**Comment by wsmelton** [comment]
Well in reality it is the cost of using a password in your connection (user/pwd). Either way that information still gets logged by PowerShell itself and saved to the Event Logs. 

If you want to test and find that `SqlConnectionStringBuilder` will keep that secure even from the security log I'm ok with adding it as well.

**Comment by wsmelton** [comment]
As well, even if you do not output verbose information the messaging system in our module still captures that information. Can't recall if we still write all of that to a session log or not though.
