### ISSUE TITLE
[Bug] Set-DbaPrivilege showing verbose message

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#6330]
![image](https://user-images.githubusercontent.com/11204251/72861232-498e1d00-3c97-11ea-88d4-6c41356b2075.png)

Note: There is no -Verbose switch provided and preference is set to silent for the session, yet still shows that one verbose message for some reason.

**Comment by nvarscar** [comment]
This one comes all the way from Get-DbaPrivilege:
https://github.com/sqlcollaborative/dbatools/blob/d3d9bf6570087b6748d01abce4b5c190e0d8269c/functions/Set-DbaPrivilege.ps1#L90
Not sure why explicit verbose is needed there.

**Comment by andreasjordan** [comment]
I don't see this message in the current version - so I will close this.
