### ISSUE TITLE
Bug - Backup-DbaDatabase command

### ISSUE THREAD

**Issue by hayriozler** [sqlcollaborative/dbatools#6333]
If you want to backup database with Backup-DbaDatabase like below paramters. as I understand the backup command calls automaticlly Get-DbaBackupHistory and this command try to connect SQL server with Windows authentication, but parent command I was try to connect with SQl Authentication and if the User does not have permission to connect server it is generating error.

Backup-DbaDatabase -SqlCredential $Cred  -SQLInstance $information.ProdServerName -Database $information.ProdDatabaseName -BackupDirectory $tmpProdBackupPath -BackupFileName $backupfileName -Type Full -CopyOnly -IgnoreFileChecks | Out-Null

you can find my env. details as below 

![image](https://user-images.githubusercontent.com/3032035/72904130-b7395800-3d2e-11ea-8b68-6adb18d8a956.png)

**Comment by wsmelton** [comment]
I believe this has been fixed in newer releases. Please test those and if the issue still exists, create a new issue with replication steps and info asked in our template.
