### ISSUE TITLE
Automate sp_pressure_detector

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#6339]
This is something I’d like for myself. 

Works best with DAC so do DAC by default then -NoDac option maybe?

Connect via DAC. Also, figure out a way to show this with an even number of columns. Looks like there are multiple selects so we will have to  either make a ton of columns or! Have a Column name for the groups of results then the results themselves 

https://github.com/erikdarlingdata/DarlingData/blob/master/sp_pressure_detector/sp_pressure_detector.sql

Oh also follow the PS naming convention. 

MemoryPressure for group name 
deqmg.session_id = SessionId

**Comment by wsmelton** [comment]
Dac is not common use, allowed, or even enabled on most environment so I would not recommend it as default.

**Comment by wsmelton** [comment]
On column stuff, I'd think a format file would help to deal with those... Maybe.
