### ISSUE TITLE
Execution policy

### ISSUE THREAD

**Issue by yosiisof** [sqlcollaborative/dbatools#6344]
Hi

I have set the dbatools in the modules folder, I've set the execution policy to both currentuser and localmachine to allsigned, and all other scopes are set to undefined.

When i try to import dbatools, i get the same error as if i didnt set the execution policy at all...

What could i do to solve this problem?

**Comment by potatoqualitee** [comment]
what is the error? what is the dbatools version?

**Comment by yosiisof** [comment]
> what is the error? what is the dbatools version?

How can i check the version?
I cant copy the error, but to summarize its dbatools.types.ps1xml is not digitally signed. You cannot run this script on the current system

**Comment by potatoqualitee** [comment]
instead of the version, when did you download it and where did you get it from? what tutorial did you follow? there's a chance that you got it from a source that does not match up with the digital singing. 

the only way to get the real package is from the PS Gallery (and chocolately which uses the ps gallery)

you can use bypass to avoid the error but it's better to figure out why yours isnt digitally signed.

**Comment by yosiisof** [comment]
We got it from dbatools.io site, we used the github (.zip) file

**Comment by potatoqualitee** [comment]
K i need to update those docs. You will follow the offline install.

https://dbatools.io/offline/

Which is basically use `Save-Module dbatools -Path C:\temp` from your online computer then move it to your offline computer. That has the properly signed files. GitHub messages with filehashes once it's committed but www.powershellgallery.com where save-module gets its modules does not.

**Comment by yosiisof** [comment]
> instead of the version, when did you download it and where did you get it from? what tutorial did you follow? there's a chance that you got it from a source that does not match up with the digital singing.
> 
> the only way to get the real package is from the PS Gallery (and chocolately which uses the ps gallery)
> 
> you can use bypass to avoid the error but it's better to figure out why yours isnt digitally signed.



> K i need to update those docs. You will follow the offline install.
> 
> https://dbatools.io/offline/
> 
> Which is basically use `Save-Module dbatools -Path C:\temp` from your online computer then move it to your offline computer. That has the properly signed files. GitHub messages with filehashes once it's committed but [www.powershellgallery.com](http://www.powershellgallery.com) where save-module gets its modules does not.

If ill use the nkpcg, how do i import it properly?

**Comment by potatoqualitee** [comment]
do you still need assitance?
