### ISSUE TITLE
[Bug] Invoke-DbaDbMirroring -WithReplace Ignored, DB restored to default folder (Unclassified)

### ISSUE THREAD

**Issue by CharlesGroleau** [sqlcollaborative/dbatools#6347]
#### Steps to Reproduce
Invoke-DbaDbMirroring -Primary sqlsever2016 -Mirror sqlserver2017 -Database SomeDB -SharedPath "\someshare\here" -Force

Db is restore to default location instead of source db location
Source = c:\sql\data\folder\db.mdf
Restore at destination C:\sql\data\unclassified\db.mdf

#### Expected Behavior
DB restored in the same folder structure then the source

#### Actual Behavior
DB restored in the default folder.

**Comment by CharlesGroleau** [comment]
-ReuseSourceFolderStructure needs to be added to line 

$null = $allbackups | Restore-DbaDatabase -SqlInstance $currentmirrorinstance -SqlCredential $currentmirrorSqlCredential -WithReplace -NoRecovery -TrustDbBackupHistory -EnableException

**Comment by CharlesGroleau** [comment]
The issue persist

**Comment by andreasjordan** [comment]
Would it help you, if you had the chance to do the backup-restore-part yourself prior to executing Invoke-DbaDbMirroring and have a parameter -UseExistingDatabase that would just check for the database to be in restoring state at the mirror and do all the rest? Then you could use your own parameter set for Backup-DbaDatabase and Restore-DbaDatabase.

**Comment by wsmelton** [comment]
The command should handle restoring to the same path as primary and then warn if those paths do not exists. This is the documented practice to use with mirroring configurations.

**Comment by CharlesGroleau** [comment]
> Would it help you, if you had the chance to do the backup-restore-part yourself prior to executing Invoke-DbaDbMirroring and have a parameter -UseExistingDatabase that would just check for the database to be in restoring state at the mirror and do all the rest? Then you could use your own parameter set for Backup-DbaDatabase and Restore-DbaDatabase.

Yes, it would also help with databases with high activity that cause the mirror activation to fail.

**Comment by potatoqualitee** [comment]
thank you @CharlesGroleau, we are looking into this

**Comment by andreasjordan** [comment]
> > Would it help you, if you had the chance to do the backup-restore-part yourself prior to executing Invoke-DbaDbMirroring and have a parameter -UseExistingDatabase that would just check for the database to be in restoring state at the mirror and do all the rest? Then you could use your own parameter set for Backup-DbaDatabase and Restore-DbaDatabase.
> 
> Yes, it would also help with databases with high activity that cause the mirror activation to fail.

Hi @CharlesGroleau , I just checked the code - and this is already implemented. Could you please test? Just do a restore with norecovery on the mirror side. With availability groups, you have to also do one log backup/restore, I'm not sure about mirroring. So maybe try both. Then start the InvokeDbaDbMirroring and it should find the database on the mirror and skip the backup restore part. But don't use "-Force" as this will delete the database on the mirror side.

**Comment by CharlesGroleau** [comment]
I confirmed it's a good work around. Tested it
