### ISSUE TITLE
[Bug] Copy-DbaDbTableData errors on PowerShell Core 6

### ISSUE THREAD

**Issue by ElliotMajor** [sqlcollaborative/dbatools#6349]
### Environmental information

```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.18363 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



#### dbatools Module version:

Name    : dbatools
Path    : C:\Users\me\Documents\PowerShell\Modules\dbatools\1.0.90\dbatools.psd1
Version : 1.0.90

Name    : dbatools
Path    : C:\Users\me\Documents\PowerShell\Modules\dbatools\1.0.88\dbatools.psd1
Version : 1.0.88
```

#### SQL Server: 

```sql
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 18363: ) 

Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64)   Apr 29 2016 23:23:58   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: ) (Hypervisor) 
```
### Report

Below command errors on Powershell Core 6
Copy-DbaDbTableData -SqlInstance servername1 -Database database1 -DestinationDatabase database2 -Table table1

Runs fine on Powershell 5

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [x] Other (please specify) pwsh.exe

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```

ErrorRecord                 : (9,56): error CS0246: The type or namespace name 'SqlBulkCopy' could not be found (are you missing a using directive or an assembly reference?)
                                              public static int RowsCopiedCount(this SqlBulkCopy bulkCopy)
                                                                                     ^
                              
WasThrownFromThrowStatement : False
Message                     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: (9,56): error CS0246: The type or namespace name 'SqlBulkCopy' could not be found (are you missing a using directive or an assembly reference?)
                                              public static int RowsCopiedCount(this SqlBulkCopy bulkCopy)
                                                                                     ^
                              
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : 
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087

```

#### Steps to Reproduce

Only repoduced internally, not between instances

Use Copy-DbaDbTableData on PS 6 specifying 
-SqlInstance
-Database
-DestinationDatabase
-Table

#### Expected Behavior

Expected to have table1 contents copied from database1 to database 2

#### Actual Behavior

Error given

**Comment by jaxnoth** [comment]
I don't believe Powershell 6 fully supports the system.data.sqlclient namespace at this time. The successor microsoft.data.sqlclient isn't fully fleshed out yet as a replacement either.

**Comment by wsmelton** [comment]
We take care of that in our module already. We package the SqlClient for dotnetcore.

**Comment by wsmelton** [comment]
Think we have another issue that was opened on that error...not sure if we already fixed it or not.

**Comment by wsmelton** [comment]
If this is not fully supported @jaxnoth the import needs to be modified for PS core to not include the command.

**Comment by wsmelton** [comment]
The code in the function will have to be adjusted to account for SqlBulkCopy not working right now in PowerShell 6+. I thought it worked in PS 7 but can't remember now.

We do not handle importing based on PS Core version so the function will need to have an alternative method for doing the work in PS Core 6+ (we have an internal function that can be used to validate the version of PS being used).

**Comment by jaxnoth** [comment]
I verified that sqlbulkcopy is not supported in .net core at this time. The copy functions would need to be removed from ps 6 versions or an alternative created.

**Comment by wsmelton** [comment]
Note not all the copy functions, just this one. We do not handle importing based on PS version, that is handled at the function level. So it will require using something other than SQLBulkCopy if PS 6/7 is detected.

**Comment by jaxnoth** [comment]
I was mistaken. The .net core does support it but the documentation doesn't reference it.  I found the bug in code on lines 226 and 229.  I'll run a new PR for this.
