### ISSUE TITLE
Set-DbaDatabaseCollation

### ISSUE THREAD

**Issue by schoemandre** [sqlcollaborative/dbatools#635]
### Is this a *feature* OR *bug*:
It would be useful to have Set-DbaDatabaseCollation to set the db Collation for all DB's on the instance

### System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```

- SQL Server version for source/target

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by niphlod** [comment]
follow this instead https://github.com/sqlcollaborative/dbatools/issues/2356
