### ISSUE TITLE
Copy-DbaDatabase -SharedPath - Error validating unc path

### ISSUE THREAD

**Issue by sam-bryant** [sqlcollaborative/dbatools#6370]
It appears that the -SharedPath property on Copy-DbaDatabase doesn't work for DFS unc paths.  I thought about attempting my first pull request on this project, but I wasn't sure how you would like this handled.  

$shareServer = ($SharedPath -split "\\")[2]
$hostEntry = ([Net.Dns]::GetHostEntry($shareServer)).HostName -split "\."

### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                                                                 
----                           -----                                                                                                                                                                                                 
PSVersion                      5.1.17134.858                                                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                               
BuildVersion                   10.0.17134.858                                                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                                                                               




#### dbatools Module version:


Name    : dbatools
Path    : C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.71\dbatools.psd1
Version : 1.0.71

Name    : dbatools
Path    : C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.34\dbatools.psd1
Version : 1.0.34

Name    : dbatools
Path    : C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.26\dbatools.psd1
Version : 1.0.26

Name    : dbatools
Path    : C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.22\dbatools.psd1
Version : 1.0.22

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.34\dbatools.psd1
Version : 1.0.34

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.823\dbatools.psd1
Version : 0.9.823

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.754\dbatools.psd1
Version : 0.9.754

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.715\dbatools.psd1
Version : 0.9.715

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.330\dbatools.psd1
Version : 0.9.330

```

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```


writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Error validating unc path: Exception calling "GetHostEntry" with "1" argument(s): "No such host is known"
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Copy-DbaDatabase,Stop-Function
ErrorDetails          : Error validating unc path: Exception calling "GetHostEntry" with "1" argument(s): "No such host is known"
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.71\allcommands.ps1: line 81869
                        at Copy-DbaDatabase<Process>, C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.71\allcommands.ps1: line 5442
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```

#### Steps to Reproduce

Copy-DbaDatabase -Source $Source -Destination $Destination -Database $Databases -BackupRestore -SharedPath "__DfsUncPath__"

#### Expected Behavior

Backup the database to the path provided.

#### Actual Behavior

WARNING: [14:30:49][Copy-DbaDatabase] Error validating unc path: Exception calling "GetHostEntry" with "1" argument(s): "No such host is known"

**Comment by wsmelton** [comment]
How would you propose to handle it because there is no way to know a UNC path provided is for a DFS share. The UNC path is just like any other file server path you would use as well.

**Comment by sam-bryant** [comment]
From my quick review of the code it is just trying to validate the path is valid.  Here are the options that come to mind for me:

- Perform a Test-Path.
  - I have seen some issues with Test-Path on UNC paths before.  I found a post that proposed doing [System.IO.Directory]::Exists($Path) instead.
- Removing the validation on the path altogether and allowing the backup process to fail if it can't access the path.

Thoughts?

**Comment by wsmelton** [comment]
Validation has to be done, it is repeated in some fashion in the restore command regardless and is best to do this before attempting the operations...saves effort and time on the users part.

Test-Path will give you false positives because the user can be running it from a remote system that won't have access to that share, but the SQL Server does. This is why we are only validating that the host is real and returns something, otherwise we spit the warning out that we will still try to run.

https://github.com/sqlcollaborative/dbatools/blob/cf5fa757a8bf83ef7ca352aeb815c46b4c6ebed5/functions/Copy-DbaDatabase.ps1#L832-L845

**Comment by wsmelton** [comment]
The point of the issue would be to resolve how line 834 and 835 are failing for you on a DFS share?

**Comment by sam-bryant** [comment]
You mention the warning and still trying to run.  I am finding that this is stopping the function.  Is that supposed to be happening?  I wouldn't mind the warning if it continued on.

**Comment by wsmelton** [comment]
You would have to show the full command or determine it on your system. I don't use or have DFS built out so I can't test it myself.

What is the DFS share you are provided? What is the value returned if you call that share using this `(<DFS Share you are using> -split "\\")[2]`

**Comment by wsmelton** [comment]
So if we are throwing an error for the try/catch, but within that we simply throw a verbose message that we will still try...the catch does not need to stop the function either.

So this:

```powershell
if ($SharedPath.StartsWith('\\')) { 
         try { 
             $shareServer = ($SharedPath -split "\\")[2] 
             $hostEntry = ([Net.Dns]::GetHostEntry($shareServer)).HostName -split "\." 
  
             if ($shareServer -ne $hostEntry[0]) { 
                 Write-Message -Level Verbose -Message "Using CNAME records for the network share may present an issue if an SPN has not been created. Trying anyway. If it doesn't work, use a different (A record) hostname." 
             } 
         } catch { 
             Stop-Function -Message "Error validating unc path: $_" 
             return 
         } 
     } 
```

Should be adjusted to be this:

```powershell
if ($SharedPath.StartsWith('\\')) { 
         try { 
             $shareServer = ($SharedPath -split "\\")[2] 
             $hostEntry = ([Net.Dns]::GetHostEntry($shareServer)).HostName -split "\." 
           } catch { 
                Write-Message -Level Warning -Message "Using CNAME records for the network share may present an issue if an SPN has not been created. Trying anyway. If it doesn't work, use a different (A record) hostname." 
         } 
     } 
```

@potatoqualitee you have any issue with that?

**Comment by cmrichardson** [comment]
I opened a feature request ...
Invoke-DbaDbMirroring - Option to backup to local backup folder and copy #6416
https://github.com/sqlcollaborative/dbatools/issues/6416
There are a number of dbatools cmdlets I can't use in the organisation I work for because I can't get -SharedPath share locations to work - the reason for this is because it's IT Policy not to domain join any of their SQL Server host servers - for security lockdown purposes.  The other reason is that they use Localadmin for the SQL Server services (I don't agree with this but it's a legacy issue).  In any case, I would love to see an option included into the relevant cmdlets such that server to server copies could be done from a folder local to the source server to a share.  In this way, under just about any circumstances, it would be possible to get files/backups from one server to another.
