### ISSUE TITLE
[Bug] "DetachAttach Force" with same Instance

### ISSUE THREAD

**Issue by espootin2** [sqlcollaborative/dbatools#6375]
We tried to transfer a database, but due to an error in the DNS (caused by renaming servers) source and destination IPs have been the same.

$source = 'sqlcsvr24win'              #-> [Same IP in DNS]
$destination = 'sqlcsvr24win_new'     #-> [Same IP in DNS]

Copy-DbaDatabase -Source $source -Destination $destination -Database db8 -DetachAttach -force

when we had used with the force parameter, the database files were completely deleted and then we got an error.

#### Errors Received

```powershell
WARNING: [00:26:42][Dismount-SqlDatabase] Issue setting database to single-user. | User does not have permission to alter database 'db8'
, the database does not exist, or the database is not in a state that allows access checks.
ALTER DATABASE statement failed.
WARNING: [00:26:42][Dismount-SqlDatabase] Issue detaching database. | The database 'db8' does not exist. Supply a valid database name. T
o see available databases, use sys.databases.
```
[
![dbatools](https://user-images.githubusercontent.com/43667538/75137901-2537bd00-56e9-11ea-8090-ef95fb816bd0.png)
](url)

#### Expected Behavior
Maybe it would make sense to verify if $source @@servername != $destination @@servername

**Comment by wsmelton** [comment]
It is unfortunate the use case you hit but I do not see this as a bug in the command.

We can't implement matching on the server name because that prevents use cases where databases are copied between named instances on the same server.

**Comment by espootin2** [comment]
Yes, you're right but it's possible to compare the combination @@ServerName and @@InstanceName .

I think it's dangerous when a user due to an error in the DNS or name in code(e.g. parameter error), it's going to delete Databases files from Source.
