### ISSUE TITLE
Remove-DbaBackup should probably be renamed to Find-DbaBackup

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#638]
Then we can just do Find-DbaBackup | Remove-Item 

Or perhaps we need a Remove-DbaItem that tries Remove using account then uses xp_delete_file.

Or perhaps Remove-DbaBackup should be a wrapper around Find-DbaBackup

1.0 milestone

**Comment by niphlod** [comment]
That's something I really wanted but I find myself costantly bashing around the fact that deleting a single file is not possible in older versions....Anyway I can work on it with a copy of a copy of a copy of a copy of a backup of a copy of a backup of a copy of my backup files. ^_^

**Comment by potatoqualitee** [comment]
not sure where we're at with this 🤔 @cjsommer you have any suggestions?

**Comment by cjsommer** [comment]
I must have missed this issue when it was opened. I actually kind of like the thought of having a Find-DbBackup. We could still keep the Remove-DbaBackup, but as suggested just have it as a wrapper around it. Will give this some more thought.

**Comment by niphlod** [comment]
I'll do this ASAP. Proposal is to do just a find- what does whatever is doing now without the remove part. The original function should be deprecated and just left as a placeholder
