### ISSUE TITLE
Restore-DbaDatabase not working right

### ISSUE THREAD

**Issue by MuruArumugam** [sqlcollaborative/dbatools#6381]
I am trying to restore database in SQL server 2016(I have got SSMS 17.9 installed) using dbatools version 0.9.773. 
Environment variable i set to dabtools that has got SMO version 14.0...

I am getting below error

WARNING: [08:31:58][Restore-DbaDatabase] Failure | [A]Microsoft.SqlServer.Management.Smo.RelocateFile cannot be cast to [B]Microsoft.SqlServer.Management.Smo.RelocateFile. Type A originates from 'Microsoft.SqlS
erver.SmoExtended, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' in the context 'Default' at location 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.SqlServer.SmoExtended\13.0.0.0__89845dcd8080cc
91\Microsoft.SqlServer.SmoExtended.dll'. Type B originates from 'Microsoft.SqlServer.SmoExtended, Version=14.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' in the context 'LoadFrom' at location 'C:\
Program Files\WindowsPowerShell\Modules\dbatools\0.9.773\bin\smo\Microsoft.SqlServer.SmoExtended.dll'.

I tried to load SMO assembly manually in my script(below command) but no luck

 [Reflection.Assembly]::Load("Microsoft.SqlServer.Smo, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91")

Not sure what I should do to by pass GAC assembly or get latest version that is 14.0...

Thanks for your work and support to the community.

**Comment by wsmelton** [comment]
PowerShell does not support loading multiple versions of assemblies in the same session. You will have to remove that from your script.

Our module loads SMO utilizing the version of SMO we package in our module.

**Comment by potatoqualitee** [comment]
hey @MuruArumugam , this is something we'd like to follow up on as we just updated our versions of SMO but we cannot accept this issue without the template info. Please recreate the issue with the requested information in the bug issue template https://github.com/sqlcollaborative/dbatools/issues/new?assignees=&labels=&template=Bug_Report.md&title=%5BBug%5D
