### ISSUE TITLE
[Bug]Restore-DbaDatabase sometimes generates duplicate RESTORE TRN entries

### ISSUE THREAD

**Issue by mikedavem** [sqlcollaborative/dbatools#6385]
### Environmental information

```
#### PowerShell version:
Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.17763.771                                                                                
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.17763.771                                                                               
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1                                                                                      

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.92\dbatools.psd1
Version : 1.0.92

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.73\dbatools.psd1
Version : 1.0.73
```

```powershell
LCID             Name             DisplayName                                                                               
----             ----             -----------                                                                               
4108             fr-CH            French (Switzerland)
```
#### SQL Server: 

```sql
Microsoft SQL Server 2017 (RTM-CU14) (KB4484710) - 14.0.3076.1 (X64)   Mar 12 2019 19:29:19   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
us_english
```

### Report
For some databases (not all) I tried to restore, the Restore-DbaDatabase with RestoreTime option generates duplicate entries leading to message:  **backup cannot be restored because no files are ready to rollforward**

Using the -OutputScriptOnly parameter confirms the 2 last entries NORECOVERY + RECOVERY are on the same TRN backup files.
 
 

#### Host used

- [X] powershell.exe
- [X] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

**backup cannot be restored because no files are ready to rollforward**

#### Steps to Reproduce

```
$RestoreTime = Get-Date('03:00 26/02/2020')

Restore-DbaDatabase `
                -SqlInstance ag-xxx-xxx `
                -DatabaseName xxxx `
                -Path '\\fileshare\SQLBackupProd\AAG_AG-XXXX\XXXX' `
                -DestinationFilePrefix 'restore' `
                -UseDestinationDefaultDirectories `
                -WithReplace `
                -RestoreTime $RestoreTime `
                -SqlCredential $credential -OutputScriptOnly
```

```sql
RESTORE LOG [xxxx] FROM  DISK = N'\\fileshare\SQLBackupProd\AAG_AG-XXX\xxxx\xxxx_20200226024501.TRN' WITH  FILE = 1,  MOVE N'xxxx' TO N'D:\XXXX\Data\restorexxxx.mdf',  MOVE N'xxxx_log' TO N'L:\XXXX\Logs\restorexxxx_log.ldf',  NORECOVERY,  NOUNLOAD,  STATS = 10,  STOPAT = N'02/26/2020 03:00:00'
RESTORE LOG [xxxx] FROM  DISK = N'\\fileshare\SQLBackupProd\AAG_AG-XXX\xxxx\xxxx_20200226030000.TRN' WITH  FILE = 1,  MOVE N'xxxx' TO N'D:\XXXX\Data\restorexxxx.mdf',  MOVE N'xxxx_log' TO N'L:\XXXX\Logs\restorexxxx_log.ldf',  NOUNLOAD,  STATS = 10,  STOPAT = N'02/26/2020 03:00:00'
RESTORE LOG [xxxx] FROM  DISK = N'\\fileshare\SQLBackupProd\AAG_AG-XXX\xxxx\xxxx_20200226030000.TRN' WITH  FILE = 1,  MOVE N'xxxx' TO N'D:\XXXX\Data\restorexxxx.mdf',  MOVE N'xxxx_log' TO N'L:\XXXX\Logs\restorexxxx_log.ldf',  NOUNLOAD,  STATS = 10,  STOPAT = N'02/26/2020 03:00:00'
```

#### Expected Behavior

To avoid 2 last duplicate entries and warning message

#### Actual Behavior

Duplicate entries generated leading to the aforementioned warming message

**Comment by bertvanlandeghem** [comment]
I think the problem is in Select-DbaBackupInformation. This function returns the last trn file twice when RestoreTime == BackupStartTime == BackupEndTime. I have this phenomenon on very small transaction log backups on a very fast system.

https://github.com/sqlcollaborative/dbatools/blob/96a76674d2e9fca8863eecdbe79c50af8f49a09d/functions/Select-DbaBackupInformation.ps1#L221

`$FilteredLogs = $DatabaseHistory | Where-Object { $_.Type -in ('Log', 'Transaction Log') -and $_.Start -le $RestoreTime -and $_.LastLSN -ge $LogBaseLsn -and $_.FirstLSN -ne $_.LastLSN } | Sort-Object -Property LastLsn, FirstLsn`

Should be 

`$FilteredLogs = $DatabaseHistory | Where-Object { $_.Type -in ('Log', 'Transaction Log') -and $_.Start -lt $RestoreTime -and $_.LastLSN -ge $LogBaseLsn -and $_.FirstLSN -ne $_.LastLSN } | Sort-Object -Property LastLsn, FirstLsn`

(-le replaced by -lt)

A few lines later, the following code uses -ge to determine the Last Log Backup

```
# Get Last T-log
$lastLog = $DatabaseHistory | Where-Object { $_.Type -in ('Log', 'Transaction Log') -and $_.End -ge $RestoreTime -and $_.DatabaseBackupLSN -eq $Full.CheckpointLSN } | Sort-Object -Property LastLsn, FirstLsn | Select-Object -First 1
```
So when the backup start time is equal to the backup end time and the RestoreTime is equal to both, this bug happens.  When changing the code as said above, the problem is not present.  I will try to submit a pull request in the coming days.
