### ISSUE TITLE
Get-DbaRoleMember Offline and Non-Readable Databases

### ISSUE THREAD

**Issue by flyfishingdba** [sqlcollaborative/dbatools#640]
### Is this a *feature* OR *bug*:
Bug

### System Details

- Operating system name and version: Windows 10 Pro
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

- Output of dbatools version:

Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      694    -1
0      8      692    -1

- SQL Server version for source/target
2016/2014/2008R2

### Steps to Reproduce
Set any database on target instance to offline
Execute Get-DbaRoleMember against instance with offline database

### Action Results
Get-DbaRoleMember throws an error when any database is inaccessible (offline or non-readable secondary Availability Group replica database)

### Expected Results
Function cleanly handles inaccessible databases

### Attached Logs or any exception errors

The following exception occurred while trying to enumerate the collection: "Unable to cast object of type
'System.DBNull' to type 'System.String'.".
At C:\Users\user\Documents\WindowsPowerShell\Modules\dbatools\functions\Get-DbaRoleMember.ps1:141 char:25
+                 foreach ($dbrole in $dbroles)
+                                     ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
    + FullyQualifiedErrorId : ExceptionInGetEnumerator

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by PowerDBAKlaas** [comment]
Thank you @flyfishingdba  and @ctrlbold !
