### ISSUE TITLE
[Bug]-last not returning the last restored file correctly (Get-DbaDbRestoreHistory)

### ISSUE THREAD

**Issue by devondba** [sqlcollaborative/dbatools#6400]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.3471                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.3471                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.51\dbatools.psd1
Version : 1.0.51

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.34\dbatools.psd1
Version : 1.0.34

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.803\dbatools.psd1
Version : 0.9.803

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.753\dbatools.psd1
Version : 0.9.753




```

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
Microsoft SQL Server 2014 (SP3-CU4) (KB4500181) - 12.0.6329.1 (X64) 
	Jul 20 2019 21:42:29 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Steps to Reproduce

All the code is shown below, It appears there's something with the internals of how the table being used is populated meaning that the differential backup can have a later id even though it was restored earlier...most odd. 

Restore a full
Restore a diff
Restore a number of logs

check last restore info, for some dbs it will be incorrect.

#### Expected Behavior

I expected the last restored file to be shown but instead the last restored differential was shown. 

#### Actual Behavior

Get-DbaDbRestoreHistory -SqlInstance $SqlInstance -Database $Database -last

Returns

BackupFinishDate : 03/03/2020 07:01:45
ComputerName :
Database :
Date : 03/03/2020 12:52:37
From : \\SQLBackups\Diff_DIFF_20200303_070123.bak
InstanceName : MSSQLSERVER
RestoreType : Differential
...

Get-DbaDbRestoreHistory -SqlInstance $SqlInstance -Database $Database -since (Get-Date).AddDays(-1)

...
Username : username

BackupFinishDate : 03/03/2020 07:21:01
ComputerName : computer
Database : db
Date : 03/03/2020 13:22:03
From : B:\SQLBackups\inst\db\LOG\db_20200303072101.trn
InstanceName : MSSQLSERVER
RestoreType : Log
SqlInstance : computer
To : D:\SQLLogs\db_Primary.ldf
Username : username

BackupFinishDate : 03/03/2020 07:22:02
ComputerName : computer
Database : db
Date : 03/03/2020 13:22:11
From : B:\SQLBackups\inst\db\LOG\db_20200303072201.trn
InstanceName : MSSQLSERVER
RestoreType : Log
SqlInstance : computer
To : D:\SQLLogs\db_Primary.ldf
Username : username

but to spin it a bit more, if we look at the last 7 days then the diff comes out last in the list, which is odd as it was restored today :D

Get-DbaDbRestoreHistory -SqlInstance $SqlInstance -Database $Database -since (Get-Date).AddDays(-7)

...
SqlInstance : inst
To : D:\SQLLogs\db_Primary.ldf
Username : user

BackupFinishDate : 03/03/2020 07:22:02
ComputerName : inst
Database : db
Date : 03/03/2020 13:22:11
From : B:\SQLBackups\isnt\db\LOG\db_20200303072201.trn
InstanceName : MSSQLSERVER
RestoreType : Log
SqlInstance : inst
To : D:\SQLLogs\db_Primary.ldf
Username : user

BackupFinishDate : 03/03/2020 07:01:45
ComputerName : inst
Database : db
Date : 03/03/2020 12:52:37
From : \inst\SQLBackups\isnt\db\Diff\isnt_db_DIFF_20200303_070123.bak
InstanceName : MSSQLSERVER
RestoreType : Differential
SqlInstance : inst
To : D:\SQLData\db_Primary.mdf, D:\SQLData\db2.ndf, D:\SQLLogs\db_Primary.ldf
Username : user

for now, to get the latest, I'm using:

Get-DbaDbRestoreHistory -SqlInstance $SqlInstance -Database $Database -since (Get-Date).AddDays(-7) | Sort-Object Date | Select -Last 1 #-Last

which gives me the correct results :)

I'm looking into the function and playing around with different methods of getting the correct result so I'll update shortly.

(https://github.com/sqlcollaborative/dbatools/issues/4688)

**Comment by wsmelton** [comment]
Please add a title.

**Comment by wsuhoey** [comment]
I noticed you have lots of older versions of the module installed. Is there a particular reason you are keeping the older versions? If not, please see dbatools.io/cleanup.
