### ISSUE TITLE
https://dbatools.io/secure/ (aka Security Team Conversation) has critical error

### ISSUE THREAD

**Issue by arsqldba** [sqlcollaborative/dbatools#6403]
The link is listed in chapter 2 of "Learn dbatools in a month of lunches".
The page loads the following content in multiple browsers:
talking to your security team about powershell and dbatools
POSTED ON SEPTEMBER 26, 2018 BY CHRISSY LEMAIRE
There has been a critical error on your website.

Learn more about debugging in WordPress.

**Comment by wsmelton** [comment]
Thanks. The site is having issues and was announced on twitter under the [psdbatools](https://twitter.com/psdbatools) account this morning.
