### ISSUE TITLE
Running Invoke-DbaQuery inside transcript closes transcript

### ISSUE THREAD

**Issue by jaxnoth** [sqlcollaborative/dbatools#6404]
#### PowerShell version:

Name                           Value                                                                                                   
----                           -----                                                                                                   
PSVersion                      5.1.18362.628                                                                                           
PSEdition                      Desktop                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                 
BuildVersion                   10.0.18362.628                                                                                          
CLRVersion                     4.0.30319.42000                                                                                         
WSManStackVersion              3.0                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                     
SerializationVersion           1.1.0.1                                                                                                 

#### dbatools Module version: 

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101

#### SQL Server: 
Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64)   Jul 12 2019 17:43:08   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### Report

Invoke-dbaquery inside a transcript closes the transcript and prevents further statements from being included it the transcript.  We traced this to Invoke-dbaasync but were unable to find a fix that would make everything work well.  This may be a duplicate of issues #6210 and 6176 or may just have a similar underlying cause.

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

ErrorRecord                 : An error occurred stopping transcription: The host is not currently transcribing.
WasThrownFromThrowStatement : False
Message                     : An error occurred stopping transcription: The host is not currently transcribing.
Data                        : {}
InnerException              : System.Management.Automation.PSInvalidOperationException: An error occurred stopping transcription: The
                              host is not currently transcribing. ---> System.Management.Automation.PSInvalidOperationException: The
                              host is not currently transcribing.
                                 at System.Management.Automation.Host.PSHostUserInterface.StopTranscribing()
                                 at Microsoft.PowerShell.Commands.StopTranscriptCommand.BeginProcessing()
                                 --- End of inner exception stack trace ---
                                 at Microsoft.PowerShell.Commands.StopTranscriptCommand.BeginProcessing()
                                 at System.Management.Automation.Cmdlet.DoBeginProcessing()
                                 at System.Management.Automation.CommandProcessorBase.DoBegin()
TargetSite                  : Void Throw()
StackTrace                  :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                 at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
HelpLink                    :
Source                      : mscorlib
HResult                     : -2146233087

#### Steps to Reproduce

Start-Transcript test.log
$params = @{
    SqlInstance      = 'localhost'
    Database         = 'tempdb'
    MessagesToOutput = $true
    Verbose          = $True
}
Invoke-DbaQuery -Query 'SELECT NULL' @params
Stop-Transcript

#### Expected Behavior

No error when executing stop-transcript.

#### Actual Behavior

![image](https://user-images.githubusercontent.com/29409499/76013971-d1965200-5ee6-11ea-899f-7cfb3ba099fe.png)

**Comment by wsmelton** [comment]
This is a known and not something we can fix. Transcript system in Windows PowerShell has various issues with many modules, one being ours for sure.

**Comment by jaxnoth** [comment]
I did find that this has been corrected in powershell 7 except when calling a stored procedure with no output.
