### ISSUE TITLE
[Bug] The cluster type of availability group only supports EXTERNAL failover mode

### ISSUE THREAD

**Issue by jphillips-dev** [sqlcollaborative/dbatools#6407]
### Environmental information

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101

#### SQL Server: 

Microsoft SQL Server 2019 (RTM-CU1) (KB4527376) - 15.0.4003.23 (X64)   Dec  6 2019 14:53:33   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Steps to Reproduce

  New-DbaAvailabilityGroup -Primary $AReplica -Secondary $BReplica,$CReplica -Name $AvailabilityGroup `
  -Database $Database `
  -SeedingMode Manual -SharedPath $sharedPath `
  -BackupPriority $ABBackupPriority `
  -DatabaseHealthTrigger:$true `
  -Confirm:$false

#### Expected Behavior

The Availability Group would be created.

#### Actual Behavior

WARNING: [10:18:47][New-DbaAvailabilityGroup] An exception occurred while executing a Transact-SQL statement or batch. | The cluster type of availability group [AGName] only supports EXTERNAL failover mode.  Verify that the specified availability group cluster type is correct, then retry the operation.

**Comment by pehiggin** [comment]
I have just reproduced this issue using dbatools 1.0.119 using new-dbaavailabilitygroup
-dbatools version: 1.0.119
-client os: windows 10 enterprise
-sql version: 2017 (14.0.3076.1)

Error occurs when running:
New-DbaAvailabilityGroup -Confirm:$false -Primary sqla -name aog_a -Secondary sqlb

**Comment by andreasjordan** [comment]
Hi @pehiggin , can you provide the output of the command when run with `-Verbose`?

**Comment by wsmelton** [comment]
Please create a new issue and provide all the details asked in our template.

**Comment by pehiggin** [comment]
![image](https://user-images.githubusercontent.com/47417994/93229222-425bd800-f76e-11ea-8292-dff46b1dc977.png)

Hi Andreas, this is now resolved by using **-clustertype wsfc**

The default it was using was "external" as per the screenshot. I think that's a feature a newer feature of availability groups that they don't need to be in the same cluster
