### ISSUE TITLE
[Bug] - Problems with New-DbaConnectionString?

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#6409]
Sup with all this?

![image](https://user-images.githubusercontent.com/8278033/76171035-9f574f80-6187-11ea-8b33-bf3040030559.png)

![image](https://user-images.githubusercontent.com/8278033/76171043-ac743e80-6187-11ea-803d-64379ce6c985.png)

thought i was figuring out an issue with PS7 but it turns out to be `New-DbaConnectionString` though weirdly, PS5.1 works while PS7 does not

![image](https://user-images.githubusercontent.com/8278033/76171069-cb72d080-6187-11ea-81dc-7fa2ac2b0a81.png)

![image](https://user-images.githubusercontent.com/8278033/76171067-c746b300-6187-11ea-8b3c-f5ea798927ae.png)

**Comment by wsmelton** [comment]
Likely going to be something with this line: https://github.com/sqlcollaborative/dbatools/blob/1cf5a4db5fde49172682a5f168a95044868a94a7/functions/New-DbaConnectionString.ps1#L280

You use `TrimStart()` there but then use `Split()` to get the username.

https://github.com/sqlcollaborative/dbatools/blob/1cf5a4db5fde49172682a5f168a95044868a94a7/functions/New-DbaConnectionString.ps1#L283

I'd change the first to use the same process.

**Comment by SQLDBAWithABeard** [comment]
Yup - I get the same too

![image](https://user-images.githubusercontent.com/6729780/76201874-deb78780-61eb-11ea-94a2-78b867573dee.png)
