### ISSUE TITLE
Find-DbaDbIndex - New function to search indexes by DB, Schema, Table, Index, Column

### ISSUE THREAD

**Issue by SQLJana** [sqlcollaborative/dbatools#6418]
Creating this new issue to reference in my pull request for a new function described in the subject.

**Comment by wsmelton** [comment]
How does this differ from using `Get-DbaHelpIndex`?

**Comment by wsmelton** [comment]
The PR you submitted, as I've skimmed over seems to be duplicate work to what we already have in Get command.

**Comment by SQLJana** [comment]
Internally, this function uses Get-DbaHelpIndex.  This is more for searching and locating indexes whereas the existing function is when you know exactly what you want and get it. Could have an overlap but the searchabily is what this functions brings.

**Comment by wsmelton** [comment]
So why not just expand the functionality in the Get command?

**Comment by wsmelton** [comment]
You can just as easily allow the a given parameter in a get function to accept wildcards.  So there is no reason to utilize multiple parameters like `-SchemaName` and `-SchemaNameMatchType`, just have one parameter `SchemaName` and accept wildcards. They they pass in `myschema*` versus just `myschema`, handle that accordingly to whether it does a wildcard search. We use this pattern in other functions.

**Comment by SQLJana** [comment]
I certainly agree with using the existing coding pattern for search consistency using wildcards and getting rid of *MatchType parameters but I think that making the changes to the original to support all the search features (plus additional search features in the future like matching all/any given array of input index column names instead of just one right now) will make it too complicated to maintain, the way it currently is.

**Comment by wsmelton** [comment]
I don't.

Right now please close the PR until decision is made in the issue.

I'll let Chrissy and others weigh in to see which we want to end up going.

Just an FYI, before going through all the work it is best to get input from an issue prior to submitting a PR immediately after.

**Comment by SQLJana** [comment]
Ok. I will close the PR. I am new to the ways of dbatools process and am learning but will get input prior to starting new work in the future.
