### ISSUE TITLE
Add joinonly flag to Add-DbaAgDatabase

### ISSUE THREAD

**Issue by klindberg70** [sqlcollaborative/dbatools#6420]
### Summary of new feature
Add a joinonly flag to be used if the database is already restored to the secondary replica.

### Proposed technical details (if applicable)
Same functionality as join only in SSMS GUI

Add-SqlAvailabilityDatabase -Path "SQLSERVER:\sql\sql01\inst01\AvailabilityGroups\AG01" -database db1

### Latest version of dbatools as of writing
1.0.97

**Comment by andreasjordan** [comment]
Hi @klindberg70 , maybe you want to join the discussion: https://github.com/sqlcollaborative/dbatools/issues/6724
