### ISSUE TITLE
export-dbacertificate

### ISSUE THREAD

**Issue by wondisha** [sqlcollaborative/dbatools#6428]
PS C:\Users\Administrator> Export-DbaCertificate -SqlServer DESKTOP-833QAHA -Path 'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\mycert202003190825232523.cer'
Get-ParamSqlDatabases : The term 'Get-ParamSqlDatabases' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:85 char:9
+         Get-ParamSqlDatabases -SqlServer $sqlserver -SqlCredential $S ...
+         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ParamSqlDatabases:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Connect-SqlServer : The term 'Connect-SqlServer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:91 char:19
+         $server = Connect-SqlServer $SqlServer $SqlCredential
+                   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-SqlServer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Cannot index into a null array.
At line:117 char:17
+ ...             $certs = $server.Databases['master'].Certificates | where ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Stop-Function : The term 'Stop-Function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:121 char:17
+                 Stop-Function -Message "No certificates found to expo ...
+                 ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Stop-Function:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Stop-Function : The term 'Stop-Function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:125 char:17
+                 Stop-Function -Message "Path should be a UNC share."  ...
+                 ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Stop-Function:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Write-Message : The term 'Write-Message' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:128 char:13
+             Write-Message -Level Verbose -Message "Exporting Certific ...
+             ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-Message:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\mycert202003190825232523.cer
You cannot call a method on a null-valued expression.
At line:167 char:9
+         $server.ConnectionContext.Disconnect()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by potatoqualitee** [comment]
Please fill out the form properly - we are unable to help without the information that we need. Those are super old command names that have since changed since dbatools 1.0. please update your dbatools.
