### ISSUE TITLE
Powershell Core Multisubnetfailover 

### ISSUE THREAD

**Issue by Tottenham84** [sqlcollaborative/dbatools#6430]
In powershell 5.1 we use "Get-DbaAgReplica -SqlInstance $AGName" to get the primary and secondary replica's in our environment. However, when we try with powershell  6 or 7 we sometimes have timeouts when connecting to the AGName. This was tested in Powershell 6 and 7 with the same result. This may be something with the driver used in Powershell Core compared to Powershell 5, but I was hoping that there would be a fix for it, so that I can continue to use dbatools with Powershell 7. 

A slight workaround I was using was connect-dbainstance with the -MultiSubnetFailover switch to get the primary replica, but later down the line commands like backup-dbadatabase calls connect-sqlinstance that doesn't have the multisubnetfailover flag, so I again have the same issue.

Thank you,
Justin

PS D:\> foreach($Server in $Servers){
>>     $AGName = $Server.serverName
>>     Write-Host "Getting Replicas for $($AGName)"
>>     Get-DbaAgReplica -SqlInstance $AGName
>> }
Getting Replicas for TheCmAG01
Name                 Role      ConnectionState RollupSynchronizationState
----                 ----      --------------- --------------------------
TheCmCL01SQ01        Secondary Connected       Synchronized
TheCmCL01SQ02        Primary   Connected       Synchronized
Getting Replicas for TheCmAG02
WARNING: [16:48:09][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheEmAG01
TheEmCL01SQ1         Secondary Connected       Synchronized
TheEmCL01SQ2         Primary   Connected       Synchronized
Getting Replicas for TheAmAG01
TheAmCL01SQ01        Secondary Connected       Synchronized
TheAmCL01SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG02
TheAmCL02SQ01        Secondary Connected       Synchronized
TheAmCL02SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG03
TheAmCL03SQ01        Secondary Connected       Synchronized
TheAmCL03SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG04
TheAmCL04SQ01        Secondary Connected       Synchronized
TheAmCL04SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG05
TheAmCL05SQ01        Secondary Connected       Synchronized
TheAmCL05SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG06
TheAmCL06SQ01        Secondary Connected       Synchronized
TheAmCL06SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG07
WARNING: [16:48:35][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG08
TheAmCL08SQ01        Secondary Connected       Synchronized
TheAmCL08SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG09
WARNING: [16:48:57][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG10
WARNING: [16:49:18][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG11
WARNING: [16:49:39][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG12
TheAmCL12SQ01        Secondary Connected       Synchronized
TheAmCL12SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG13
WARNING: [16:50:01][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG14
TheAmCL14SQ01        Secondary Connected       Synchronized
TheAmCL14SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG15
WARNING: [16:50:22][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG16
WARNING: [16:50:43][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG17
WARNING: [16:51:04][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG18
TheAmCL18SQ01        Secondary Connected       Synchronized
TheAmCL18SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG19
TheAmCL19SQ01        Secondary Connected       Synchronized
TheAmCL19SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG20
TheAmCL20SQ01        Secondary Connected       Synchronized
TheAmCL20SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG21
WARNING: [16:51:46][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG22
WARNING: [16:52:07][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG23
TheAmCL23SQ01        Primary   Connected       Synchronized
TheAmCL23SQ02        Secondary Connected       Synchronized
Getting Replicas for TheAmAG24
TheAmCL24SQ01        Secondary Connected       Synchronized
TheAmCL24SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG25
AUODRCL25SQ3         Secondary Connected       Synchronizing
TheAmCL25SQ01        Secondary Connected       Synchronized
TheAmCL25SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG26
AUODRCL26SQ3         Secondary Connected       Synchronizing
TheAmCL26SQ01        Secondary Connected       Synchronized
TheAmCL26SQ02        Primary   Connected       Synchronized
Getting Replicas for TheAmAG27
WARNING: [16:52:52][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for TheAmAG28
TheAmCL28SQ1         Secondary Connected       Synchronized
TheAmCL28SQ2         Primary   Connected       Synchronized
Getting Replicas for MUVPRAG01
MUVPRCL01SQ01        Secondary Connected       Synchronized
MUVPRCL01SQ02        Primary   Connected       Synchronized
Getting Replicas for MUVPRAG02
WARNING: [16:53:14][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.
Getting Replicas for MUVPRAG03
WARNING: [16:53:56][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.

**Comment by wsmelton** [comment]
Please provide the content we ask for in the template.
