### ISSUE TITLE
Trying to update dbatools to 102 but getting error -skippublishercheck

### ISSUE THREAD

**Issue by wondisha** [sqlcollaborative/dbatools#6431]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                     
----                           -----                                                     
PSVersion                      5.1.18362.628                                             
PSEdition                      Desktop                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                   
BuildVersion                   10.0.18362.628                                            
CLRVersion                     4.0.30319.42000                                           
WSManStackVersion              3.0                                                       
PSRemotingProtocolVersion      2.3                                                       
SerializationVersion           1.1.0.1                                                   




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101




```

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)   Oct 28 2016 18:17:30   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 18362: ) 

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received
PS C:\Users\Administrator> Export-DbaCertificate -SqlServer DESKTOP-833QAHA -Path 'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\mycert202003190825232523.cer'
Get-ParamSqlDatabases : The term 'Get-ParamSqlDatabases' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:85 char:9

    Get-ParamSqlDatabases -SqlServer $sqlserver -SqlCredential $S ...
    ~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : ObjectNotFound: (Get-ParamSqlDatabases:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
Connect-SqlServer : The term 'Connect-SqlServer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:91 char:19

    $server = Connect-SqlServer $SqlServer $SqlCredential
              ~~~~~~~~~~~~~~~~~
CategoryInfo : ObjectNotFound: (Connect-SqlServer:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
Cannot index into a null array.
At line:117 char:17

... $certs = $server.Databases['master'].Certificates | where ...
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : NullArray
Stop-Function : The term 'Stop-Function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:121 char:17

            Stop-Function -Message "No certificates found to expo ...
            ~~~~~~~~~~~~~
CategoryInfo : ObjectNotFound: (Stop-Function:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
Stop-Function : The term 'Stop-Function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:125 char:17

            Stop-Function -Message "Path should be a UNC share."  ...
            ~~~~~~~~~~~~~
CategoryInfo : ObjectNotFound: (Stop-Function:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
Write-Message : The term 'Write-Message' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:128 char:13

        Write-Message -Level Verbose -Message "Exporting Certific ...
        ~~~~~~~~~~~~~
CategoryInfo : ObjectNotFound: (Write-Message:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\mycert202003190825232523.cer
You cannot call a method on a null-valued expression.
At line:167 char:9

    $server.ConnectionContext.Disconnect()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull

#### Expected Behavior

Easily able to upgrade to 102 and execute the command export-dbacertificate without an issue
#### Actual Behavior

Have tried the dbatools slack group with this issue and other people also faced same issue on 102

**Comment by wsmelton** [comment]
@wondisha `Export-DbaCertificate` is not a command in our module anymore.

**Comment by wondisha** [comment]
How about the error for updating dbatools to version 102?

Wondi Wolde
AWS certified SQL DBA

**Comment by wsmelton** [comment]
You make no reference to that in your post, only the title.

**Comment by wsmelton** [comment]
`Install-Module dbatools -SkipPublisherCheck` is required for the 1.0.102 release due to an issue we had when the module was published.

**Comment by wondisha** [comment]
Version 102 installed thnx,problem solved
