### ISSUE TITLE
when installing 1.0.102 I get the following error The version '1.0.102' of the module 'dbatools' being installed is not catalog signed

### ISSUE THREAD

**Issue by jensenjk** [sqlcollaborative/dbatools#6433]
### Environmental information

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

**Comment by jensenjk** [comment]
The version '1.0.102' of the module 'dbatools' being installed is not catalog signed. Ensure that the version '1.0.102' of the module 'dbatools' has the c
atalog file 'dbatools.cat' and signed with the same publisher 'CN=dbatools, O=dbatools, L=Vienna, S=Virginia, C=US' as the previously-installed module 'dbatools' with version '1.0.101' under
 the directory 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101'.

**Comment by potatoqualitee** [comment]
im gonna try to redo this, maybe the release was messed up. ill try now

**Comment by jensenjk** [comment]
Download works now.

But still having problems updating the buildreference


PS C:\WINDOWS\system32> get-dbabuildreference -update
WARNING: [08:57:15][Get-DbaBuildReference] You need to choose at least one parameter.
