### ISSUE TITLE
get-dbabuiltreference  -update not longer update's local repository but[ returns error

### ISSUE THREAD

**Issue by jensenjk** [sqlcollaborative/dbatools#6434]
### Environmental information

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [ ] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

get-dbabuildreference -Update

#### Expected Behavior

Get local repository updated with new releases

#### Actual Behavior

Error : WARNING: [13:57:13][Get-DbaBuildReference] You need to choose at least one parameter.

**Comment by jensenjk** [comment]
PS C:\Windows\system32> get-dbabuildreference -Update
WARNING: [13:57:13][Get-DbaBuildReference] You need to choose at least one parameter.

**Comment by wsmelton** [comment]
Please complete the template.

**Comment by jensenjk** [comment]
Oh, seems the latest 2019 CU3 build has not been added to the build reference table
![image](https://user-images.githubusercontent.com/11940382/77338263-647a1d80-6d2a-11ea-8ba8-b516b9617795.png)

**Comment by wsmelton** [comment]
Correct, have not gotten around to updating the build file with new releases yet.

**Comment by jensenjk** [comment]
When can it be expected to be up todate?

**Comment by wsmelton** [comment]
Once it is submitted as a pull request, merged and then a release is done.
