### ISSUE TITLE
Test-DbaBuild 13.0.5237 is not recognized as a correct version

### ISSUE THREAD

**Issue by muthukkumarankaliyamoorthy** [sqlcollaborative/dbatools#6456]
WARNING: [17:51:12][Test-DbaBuild] 13.0.5237 is not recognized as a correct version.

Got this warning, I hope this need to be added in the build list.

**Comment by wsmelton** [comment]
It is not listed here as a build number:

https://support.microsoft.com/en-us/help/3177312/sql-server-2016-build-versions

**Comment by wsmelton** [comment]
I'm unable to find valid documented KB for that build number.

If you will provide the details we can update the build ref file and reopen this issue.

**Comment by muthukkumarankaliyamoorthy** [comment]
I have server which is running on 13.0.5237, not sure why it is not listed in MS site. Pls let me know, if you want me to share any details or run any code..

**Comment by wsmelton** [comment]
We need the kb article the pertains to the build number.

**Comment by muthukkumarankaliyamoorthy** [comment]
Build	NameLevel	SPLevel	CULevel	KBLevel	BuildLevel	SupportedUntil	MatchType	Warning	Compliant	MinimumBuild	MaxBehind	SPTarget	CUTarget	BuildTarget
13.0.5237	2016	SP2	CU4	4464106	13.0.5233	2026-07-14 00:00:00.0000000	Approximate	13.0.5237 not found, closest build we have is 13.0.5233	0	NULL	0CU	SP2	CU12	13.0.5698

**Comment by wsmelton** [comment]
That is not what we need.

If you state that your instance of SQL Server is on build 13.0.5237, what patch did you install to get it to that build? We need the KB article number that it came from in order to update our data file.
