### ISSUE TITLE
[Bug] Repair-DbaDbOrphanUser ignores -RemoveNotExisting switch

### ISSUE THREAD

**Issue by IcyCooldrink** [sqlcollaborative/dbatools#6459]
### Environmental information

```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101

```

#### SQL Server:

```sql
Microsoft SQL Server 2014 (SP3-GDR) (KB4532095) - 12.0.6118.4 (X64)   Dec 12 2019 21:46:15   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

#### Host used

- [ X ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

No errors received.

#### Steps to Reproduce

Repair-DbaDbOrphanUser -SqlInstance <instance> -Database <database> -RemoveNotExisting

#### Expected Behavior

When executed with -WhatIf, output looks to be what was expected.

What if: Performing the operation "Mapping user 'user'" on target "database".
What if: Performing the operation "Remove-DbaDbOrphanUser" on target "database".

#### Actual Behavior

Orphaned user mapped successfully.

Used the following:
Get-DbaDbOrphanUser -SqlInstance <instance> -Database <database>

Returns items I expected to have been removed.

-EnableException comes back clear.

Manually executed:
Remove-DbaDbOrphanUser -SqlInstance <instance> -Database <database>

Works as I would have expected.

**Comment by jpomfret** [comment]
Confirmed this bug - I have a fix for it. Looking at adding a pester test to make sure we don't break it again.

**Comment by andreasjordan** [comment]
@jpomfret Can you have a look at this?
