### ISSUE TITLE
Add -ReuseSourceFolderStructure parameter to ADD-DBAAgDatabase

### ISSUE THREAD

**Issue by unclebiguns** [sqlcollaborative/dbatools#6464]
### Summary of new feature

Currently when using manual seeding with Add-DBAAgDatabase you can only use the destination default folders for data and log files.  Adding this flag, which is in Restore-DbaDatabase, would allow Add-DBAAgDatabase to have the same functionality as Restore-DbaDatabase

### Proposed technical details (if applicable)

In the event that there are multiple locations for data and/or log files currently you can't use Add-DBAAgDatabase with manual seeding as all files will go the default locations on the destination server.  By adding this parameter you can match the source file folders, just like autoseed does.  The change in the cmdlet would be to check if teh parameter was included and then add it to the Restore-DbaDatabase call.  

### Latest version of dbatools as of writing

1.0.104

**Comment by wsmelton** [comment]
I would see this being handled by I call `Restore-DbaDatabase` and apply the restore to each replica...but think we would have to add functionality to `Add-DbaAgDatabase` to handle a join only scenario (don't think it does now).
