### ISSUE TITLE
[Bug]incorrect eventtype description in Get-DbaSuspectPage

### ISSUE THREAD

**Issue by Jonathan-Quilter** [sqlcollaborative/dbatools#6471]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                                    
----                           -----                                                                                                                                                                    
PSVersion                      5.1.14393.3471                                                                                                                                                           
PSEdition                      Desktop                                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                  
BuildVersion                   10.0.14393.3471                                                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                                      
SerializationVersion           1.1.0.1                                                                                                                                                                  

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.90\dbatools.psd1
Version : 1.0.90

#### SQL Server:
```sql
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64)   Aug 19 2014 12:21:34   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```
### Report
The error description output from Get-DbaSuspectPage is incorrect for eventtype 1
reference [suspect_pages table](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/manage-the-suspect-pages-table-sql-server) shows that:

eventtype value 1 has an error description of "823 error caused by an operating system CRC error or 824 error other than a bad checksum or a torn page (for example, a bad page ID)" - it specifically excludes Torn page.

eventtype value 3 has an error description of "Torn page"

The results of Get-DbaSuspectPage returns EventType "823 or 824 or Torn Page" when the eventtype value is 1 and EventType "Torn Page" when eventtype value is 3

This is misleading and will cause confusion when cross-referencing Get-DbaSuspectPage results to Microsoft official documentation.

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [x ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Steps to Reproduce

execute Get-DbaSuspectPage against a server that has records in the msdb..suspectpages table

#### Expected Behavior

eventtypes with value of 1 should show "Error 823 or 824"

#### Actual Behavior

eventtypes with value of 1 should show "Error 823 or 824 or Torn Page"

**Comment by wsmelton** [comment]
Event type 1 is a warning message, it does not mean you have exact suspect pages logged or not. Therefore it can be 1 of 3 items listed. I see no reason to change this as it is based on what is documented.

**Comment by jpomfret** [comment]
Docs aren't super clear which way round this is... but I feel like it's saying its 823 or 824 - not torn page or checksum.
Then checksum and torn page are covered by event_type of 2 or 3? 

![image](https://user-images.githubusercontent.com/981370/78996007-93223180-7b3b-11ea-875a-ed7705baf87d.png)

**Comment by Jonathan-Quilter** [comment]
It will indeed return what that TSQL does.

The problem that I see is in the text supplemented for the event_type. (Actually there are a couple of issues).
1 - the text from the books online page shows that event_type value of 1 is "823 error caused by an operating system CRC error or 824 error **other than a bad checksum or a torn page** (for example, a bad page ID)"
2 - is Bad Checksum
3 - is Torn page

The other issue is that the output from the function is conflating database table column names and output property names. 
**SQL Server**
event_type is the column name and contains int values
error description is the text interpretation of those values
**Get-DbaSuspectPage**
eventtype is the error description
the eventtype (int value) is lost which in my opinion is a loss to functionality as you can no longer do integer comparisons to process the results further
