### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by daksh17** [sqlcollaborative/dbatools#6485]
[issue_dba_tool.txt](https://github.com/sqlcollaborative/dbatools/files/4521036/issue_dba_tool.txt)

### Environmental information

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

**Comment by daksh17** [comment]
please find attachment with all information

**Comment by wsmelton** [comment]
Please do not simply attach a file. Provide the information requested in the issue post itself.
