### ISSUE TITLE
Publish-DbaDacPackage When you use -ScriptOnly flag only works with -GenerateDeploymentScript

### ISSUE THREAD

**Issue by pjlorenzo** [sqlcollaborative/dbatools#6487]
https://github.com/sqlcollaborative/dbatools/blob/6f9a5add0e3c787bb237bc22c7e702f1599bf097/functions/Publish-DbaDacPackage.ps1#L155

if ((Test-Bound -ParameterName ScriptOnly) -and (Test-Bound -Not -ParameterName GenerateDeploymentScript) -and (Test-Bound -Not -ParameterName GenerateDeploymentScript)) {
            Stop-Function -Message "You must at least one of GenerateDeploymentScript or GenerateDeploymentReport when using ScriptOnly"
            return
        }

**Comment by wsmelton** [comment]
Your post is only stating a fact that is true and by design.

**Comment by nvarscar** [comment]
Please use the provided template. Otherwise it's not clear what this issue is about.
