### ISSUE TITLE
Example for Set-DbaAgentSchedule is invalid

### ISSUE THREAD

**Issue by Splaxi** [sqlcollaborative/dbatools#6492]
It seems that the #5372 broke one of the examples in `Set-DbaAgentSchedule`

The mentioned PR changed line 144:
https://github.com/sqlcollaborative/dbatools/pull/5372/files#diff-4a86ad0a8ad50cb0bbbbb00ddcbdc11dR144

from: 
```
[object[]]$FrequencyInterval
```

to:
```
[int]$FrequencyInterval,
```

Being doing that, it invalidated the following example:

https://github.com/sqlcollaborative/dbatools/blob/f397ebf1cf23e83da6fd29e4f3dcc18df73e7086/functions/Set-DbaAgentSchedule.ps1#L106-L109

After the update, I don't know if the example can be replicated or not - but I can share that the example doesn't work.

At the moment I'm not capable enough (sorry!) to understand whether the example can be rewritten or it simply is impossible to achieve with the latest code.

**Comment by wsmelton** [comment]
@sanderstad Will have to respond on the change made...
