### ISSUE TITLE
SYNC-DBAAVAILABILITYGROUP - update-sqlpermission does not take into account secondary databases

### ISSUE THREAD

**Issue by DBAdminDB** [sqlcollaborative/dbatools#6493]
because of it, the update-sqlpermission takes a lot of time to finish, because it is trying to update the permissions on the secondary databases which are read-only or not readable, and because of it, the process gets timeout after some time, but with a lot of logins and a lot of databases, this could lead to run time of *one day*... 

searching for secondary databases and excluding them in the update-sqlpermission could be useful..

or am I doing something wrong?

**Comment by andreasjordan** [comment]
Hi @DBAdminDB ,

this code should take care of that:
https://github.com/sqlcollaborative/dbatools/blob/5cd29095b0847a1ca97d3b3da58674b88d12d612/internal/functions/Update-SqlPermission.ps1#L211-L214
https://github.com/sqlcollaborative/dbatools/blob/5cd29095b0847a1ca97d3b3da58674b88d12d612/internal/functions/Update-SqlPermission.ps1#L299-L302

Can you run the command with `-Verbose` and tell me if you see these verbose messages?

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if this is still an issue with the current version.
