### ISSUE TITLE
[Bug] Get-DbaRegistryRoot issue with authentication

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#6503]
### Environmental information
Windows Server 2019
SQL Server 2019

### Report

```
Exception             : System.Exception: [lab-sql-02] Connecting to remote server lab-sql-02 failed with the following error message : A
                        specified logon session does not exist. It may already have been terminated. For more information, see the
                        about_Remote_Troubleshooting Help topic.
                         Other Possible Cause:
                          -The domain or computer name was not included with the specified credential, for example: DOMAIN\UserName or
                        COMPUTER\UserName.
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```
Exception             : System.Exception: [lab-sql-02] Connecting to remote server lab-sql-02 failed with the following error message : A
                        specified logon session does not exist. It may already have been terminated. For more information, see the
                        about_Remote_Troubleshooting Help topic.
                         Other Possible Cause:
                          -The domain or computer name was not included with the specified credential, for example: DOMAIN\UserName or
                        COMPUTER\UserName.
```
#### Steps to Reproduce

1. PS Remote into a domain computer as a domain login
1. Call `Get-DbaRegistryRoot -ComputerName $TargetServer -EnableException`

#### Expected Behavior

Returns the object

#### Actual Behavior

It didn't

**Comment by andreasjordan** [comment]
Stumbled across this again. I'm not sure I understand it correctly. You have three servers, SRV1, SRV2 and SRV3. You start PowerShell in SRV1, run an `Enter-PSSession -ComputerName SRV2` to get to SRV2 and there you have dbatools installed and run `Get-DbaRegistryRoot -ComputerName SRV3` to get the information about the instances installed on SRV3.
If so, maybe a double-hop problem?

**Comment by wsmelton** [comment]
Would not have been a double-hop issue, WinRm gives a different error for those.
