### ISSUE TITLE
Update-Dbatools failed; Now can't run any commands

### ISSUE THREAD

**Issue by FreedToFly** [sqlcollaborative/dbatools#6504]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

Dbatools was working, but I tried to update it by running Update-Dbatools which failed and told me to Import Dbatools. I couldn't see how to do that so ended up trying to uninstall and then I did a manual install.

Now if I run any dbatools command, I get for example this message: The 'Get-DbaUptime' command was found in the module 'dbatools', but the module could not be loaded. For more information, run 'Import-Module dbatools'.

If I run Import-Module dbatools I get the following:
Import-Module : The following error occurred while loading the extended type data file: , C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\dbatools\xml\dbatools.Types.ps1xml: The file was skipped because of the following validation exception: File C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\dbatools\xml\dbatools.Types.ps1xml cannot be loaded. The file C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\dbatools\xml\dbatools.Types.ps1xml is not digitally signed. You cannot run this script on the current system.

Get-Module dbatools -ListAvailable returns a single row which tells me my version is 1.0.107

It was suggested on Slack that I raise a new issue here. I hope someone can help me to fix dabtools.  Kind regards...

**Comment by FreedToFly** [comment]
Anyone have any ideas how I can fix this?

**Comment by andreasjordan** [comment]
Hi @FreedToFly is this still an issue?

**Comment by wsmelton** [comment]
@FreedToFly the update command we package with the module should only be used if you installed the module using the install script. If you are using the proper method for online installation from the PowerShell Gallery (`Install-Module`) this command should not be used.

If the version of the module on your machine is not importing properly I would recommend deleting it completely and then doing a new installation to pull the latest version.

If this is still causing problems please open a new issue and provide details on how you have installed the module.
