### ISSUE TITLE
error generating dacpac - filename incorrect

### ISSUE THREAD

**Issue by rajaster** [sqlcollaborative/dbatools#6522]
RUn:

# Prepare extraction properties string
$exportProperties = "/p:IgnorePermissions=True /p:IgnoreUserLoginMappings=True" # Ignore permissions definition

Export-DbaDacPackage -SqlInstance . -Database "AdventureWorks2017" -Path "C:\MyDACs" -ExtendedProperties $exportProperties

Error:

PS C:\Windows\system32> # Prepare extraction properties string
$exportProperties = "/p:IgnorePermissions=True /p:IgnoreUserLoginMappings=True" # Ignore permissions definition

Export-DbaDacPackage -SqlInstance . -Database "AdventureWorks2017" -Path "C:\MyDACs" -ExtendedProperties $exportProperties

WARNING: [09:53:59][Export-DbaDacPackage] Standard output - *** Argument 'TargetFile' has an invalid value: 'C:\MyDACs\NP:.-20200509095358-dacpackage.dacpac'.
*** The given path's format is not supported.

i've not been able to find any solution to this issue and i've tried passing the filename as a parameter etc. the example i've used was just to create a dacpac from any random database the begin with.

i am using the latest repository for dbatools and ran Update-Module dbatools before beginning.

**Comment by andreasjordan** [comment]
Sorry, has been lost from sight. Is this still a problem with the current version?

**Comment by rajaster** [comment]
I've no idea.. I completed the project last year and not tried again.
