### ISSUE TITLE
Fix help for Publish-DbaDacPackage - Windows Auth (not integrated) not supported

### ISSUE THREAD

**Issue by grandwazoo666** [sqlcollaborative/dbatools#6526]
I am passing windows credentials (DOMAIN\username) via PSCrdential object to Publish-DbaDacPackage in -SqlInstance parameter, but it's still using integrated windows authentication to connect to SQL instance. SQL server log has this entry:

05/11/2020 09:13:51,Logon,Unknown,Login failed for user 'XXXXXX\XXXXXX$'. Reason: Could not find a login matching the name provided. [CLIENT: XX.XX.XX.XX]

**Comment by nvarscar** [comment]
DacServices object requires a connection string to initialize, unfortunately, it is impossible to use custom Windows credentials in such scenario.

**Comment by grandwazoo666** [comment]
I figured as much, but can you update your documentation then? It says "Login to the target instance using alternative credentials. Windows and SQL Authentication supported. Accepts credential objects (Get-Credential)". It is misleading!
