### ISSUE TITLE
Import-DbaCsv Powershell. Warning [Import-DbaCsv] Failure | The CSV appears to be corrupt near record. How to solve the problem?

### ISSUE THREAD

**Issue by stefanoey** [sqlcollaborative/dbatools#6527]
I'm trying to import csv files to SQL Server Management Studio using Import-DbaCsv on powershell. There is a warning saying that the csv appears corrupt.

The csv's have the following format:

"AAA" "BBB" "CCC"
"A"  "B" 123

**Comment by nvarscar** [comment]
Are you specifying the space symbol as delimiter? Please share the full command line you're using.

**Comment by wsmelton** [comment]
If the issue still exists on the latest release please create a new issue and provide the requested details.

**Comment by allenheydari2019** [comment]
Issue is still there. I am having the same problem.
