### ISSUE TITLE
Updating local repository

### ISSUE THREAD

**Issue by jensenjk** [sqlcollaborative/dbatools#6534]
Using get-dbabuildreference -update to update local repository does not work anymore getting
PS C:\WINDOWS\system32> get-dbabuildreference -update
WARNING: [10:47:51][Get-DbaBuildReference] You need to choose at least one parameter.

There currently is a CU3 update to SQL 2019 which is not detected by dbatools UpdateDbInstance

**Comment by wsmelton** [comment]
`"15.0.4023"` build for SQL Server 2019 CU3 exists now in the build ref file.
