### ISSUE TITLE
TerminatingError System Error during Copy-Login[Bug]

### ISSUE THREAD

**Issue by tom-boone** [sqlcollaborative/dbatools#6535]
### Environmental information

Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.108\dbatools.psd1
Version : 1.0.108

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

#### Host used

- [x ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Steps to Reproduce

VERBOSE: Performing the operation "Adding SQL login SQLGROUP" on target "SERVER".
VERBOSE: [14:30:18][Copy-Login] Attempting to add SQLGROUP to SERVER.
VERBOSE: [14:30:18][Copy-Login] Setting SQLGROUP SID to source username SID.
VERBOSE: [14:30:18][Copy-Login] Setting login language to us_english.
VERBOSE: [14:30:18][Copy-Login] Set SQLGROUP defaultdb to master.
VERBOSE: [14:30:18][Copy-Login] Adding as login type WindowsGroup
VERBOSE: [14:30:18][Copy-Login] Setting language as us_english
PS>TerminatingError(): "System error."
VERBOSE: Performing the operation "Adding SQL login SQLGROUP2" on target "SERVER".
VERBOSE: [14:30:18][Copy-Login] Attempting to add SQLGROUP2 to SERVER.
VERBOSE: [14:30:18][Copy-Login] Setting SQLGROUP2  SID to source username SID.
VERBOSE: [14:30:18][Copy-Login] Setting login language to us_english.
VERBOSE: [14:30:18][Copy-Login] Set SQLGROUP2 defaultdb to master.
VERBOSE: [14:30:18][Copy-Login] Adding as login type WindowsGroup
VERBOSE: [14:30:18][Copy-Login] Setting language as us_english
PS>TerminatingError(): "System error."

**Comment by wsmelton** [comment]
This is as it says, a system error. That is something your local system or PowerShell is spitting out.

What is the actual behavior of the login being executed? Did it complete? Did the login or Windows Group actually get copied to the destination server?

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if this is still an issue with the current version.
