### ISSUE TITLE
Add DisableOnDestination to Sync-DbaAvailabilityGroup

### ISSUE THREAD

**Issue by agentbp** [sqlcollaborative/dbatools#6540]
### Summary of new feature

Add the DisableOnDestination switch within the Copy-DbaAgentJob portion of Sync-DbaAvailabilityGroup

### Proposed technical details (if applicable)
Add the lines outlined in red, I wasn't smart enough to deploy locally and test, but hopefully the below images communicate the general idea.

![image](https://user-images.githubusercontent.com/30202484/82258746-662a2100-9928-11ea-89ba-a4d59abb2a9f.png)

![image](https://user-images.githubusercontent.com/30202484/82258769-717d4c80-9928-11ea-8849-5e1b2345ac1e.png)

### Latest version of dbatools as of writing

1.0.68

**Comment by andreasjordan** [comment]
@potatoqualitee - I would like to have your feedback on this.

**Comment by potatoqualitee** [comment]
yep, seems good to me!
