### ISSUE TITLE
[Bug] dbatools.io/commands Data Masking appears twice

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#6541]
#### Errors Received

[dbatools.io/commands](url) site:

![data masking](https://user-images.githubusercontent.com/28710553/82265569-20675b80-991c-11ea-94b1-4b4199215b50.png)

#### Steps to Reproduce

Data Masking appears twice in the Categories section.
In the orange highlighted one, the anchor link doesn't work;
in the yellow highlighted one, the anchor link does work.

#### Expected Behavior

Only 1 entry for Data Masking

#### Actual Behavior

Two (one duplicate) entry, and one anchor not working.

**Comment by MikeyBronowski** [comment]
That should be fixed now.

**Comment by wsmelton** [comment]
Seems stale bot is messing up now, it should not have labeled this in 14 days. :(
