### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by naruto3650** [sqlcollaborative/dbatools#6544]
### Environmental information
I am trying to use a shared path on the -path but it won't work. 

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```
SQL 2016

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [X ] powershell.exe
- [X ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received
Invalid Path

#### Steps to Reproduce
run export-dbalogin with the shared path \\servernamexx\folderxx\serverxx.sql

#### Expected Behavior
place the account on a shared folder. 

place the account on a shared folder. 
#### Actual Behavior
error filepath invalid. also on the website there are no sample of this working on remote.

**Comment by naruto3650** [comment]
waiting for reply

**Comment by nvarscar** [comment]
Path `\servernamexx\folderxx\serverxx.sql` is an invalid network path, hence you're getting the error - the path misses double backslash at the start.
