### ISSUE TITLE
Export-DbaSysDbUserObject is not being exported as public function

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#6561]
Hi!

I'm not sure if this is an intended behavior or something that escape us before.

The `Export-DbaSysDbUserObject` is not being exported as public function.

Should we include it as public function?

**Comment by wsmelton** [comment]
I was just never added to module manifest to be exported. So yes, psm1 and psd1 should be adjusted to properly export it.

**Comment by andreasjordan** [comment]
Is now public, so I close this.
