### ISSUE TITLE
question on integrating DBAtools

### ISSUE THREAD

**Issue by AnilkumarDBA** [sqlcollaborative/dbatools#6562]
Hi, 

We are developing a tool to automate certain implementation in SQL Server. We have checked that by importing DBAtools from Powershell, we can run command (available only in dbatools) from Power shell without any issues.

Question is, can we integrate dbatools in out tool that we are going to sell to our customers ? 

Appreciate your insightful response. Thank you.

**Comment by wsmelton** [comment]
We license our module under MIT License, you can view that information [here](https://github.com/sqlcollaborative/dbatools/blob/development/LICENSE).

**Comment by AnilkumarDBA** [comment]
> We license our module under MIT License, you can view that information [here](https://github.com/sqlcollaborative/dbatools/blob/development/LICENSE).

Thank you for your response !!
