### ISSUE TITLE
[Bug]Get-DBALastBackup - Getting wrong last backup

### ISSUE THREAD

**Issue by PioBalistoy** [sqlcollaborative/dbatools#6565]
### Environmental information

PowerShell version:
Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Version : 1.0.108

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
SELECT @@VERSION
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

 powershell.exe

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

WARNING: [20:35:15][Get-DbaDbBackupHistory] Found backups from multiple recovery forks for C8 on USAWSCTRPRDDB1, this may affect your results
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 02/27/2020 12:58:55/2866030000002540200057 and 02/27/2020 13:10:20/2866030000002540200057 C8 was on Recovery Fork GUID
f0ebafdd-872f-41b2-90df-15a02478d5d3 (1 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 05/05/2020 06:25:43/2999086000001564700023 and 05/11/2020 09:40:07/3029850000001269900037 C8 was on Recovery Fork GUID
74357f03-f6d7-47a2-8883-1d0160c97e43 (9 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 02/26/2020 16:48:06/2970799000003953800298 and 02/26/2020 17:06:22/2970799000003953800298 C8 was on Recovery Fork GUID
dd2cedde-f43c-42d9-9575-534d81ac6b36 (1 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 02/28/2020 08:24:05/2971413000004403100193 and 05/04/2020 09:16:23/3000979000002662300134 C8 was on Recovery Fork GUID
51fcf27b-6535-4c32-9b8a-79203c8e66a8 (8 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 05/12/2020 08:10:05/2999086000001564700023 and 05/15/2020 06:02:20/3012135000002710300207 C8 was on Recovery Fork GUID
6641b400-4dd6-4b96-a0de-8b079b4d90f2 (9 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 05/22/2020 00:57:31/3001919000038795800290 and 06/01/2020 03:09:06/3027252000000982100227 C8 was on Recovery Fork GUID
52ebc80d-5da4-4b92-aebb-9f9aba73afc1 (228 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 02/26/2020 15:01:40/2970348000000001600075 and 05/21/2020 21:58:19/3001905000407060300209 C8 was on Recovery Fork GUID
7e518eb8-b281-409b-9064-b271d9b13a91 (4 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Found backups from multiple recovery forks for C8 on USAWSCTRPRDDB1, this may affect your results
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 02/27/2020 12:58:55/2866030000002540200057 and 02/27/2020 13:10:20/2866030000002540200057 C8 was on Recovery Fork GUID
f0ebafdd-872f-41b2-90df-15a02478d5d3 (1 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 05/05/2020 06:25:43/2999086000001564700023 and 05/11/2020 09:40:07/3029850000001269900037 C8 was on Recovery Fork GUID
74357f03-f6d7-47a2-8883-1d0160c97e43 (9 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 02/26/2020 16:48:06/2970799000003953800298 and 02/26/2020 17:06:22/2970799000003953800298 C8 was on Recovery Fork GUID
dd2cedde-f43c-42d9-9575-534d81ac6b36 (1 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 02/28/2020 08:24:05/2971413000004403100193 and 05/04/2020 09:16:23/3000979000002662300134 C8 was on Recovery Fork GUID
51fcf27b-6535-4c32-9b8a-79203c8e66a8 (8 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 05/12/2020 08:10:05/2999086000001564700023 and 05/15/2020 06:02:20/3012135000002710300207 C8 was on Recovery Fork GUID
6641b400-4dd6-4b96-a0de-8b079b4d90f2 (9 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 05/22/2020 00:57:31/3001919000038795800290 and 06/01/2020 03:09:06/3027252000000982100227 C8 was on Recovery Fork GUID
52ebc80d-5da4-4b92-aebb-9f9aba73afc1 (228 backups)
WARNING: [20:35:15][Get-DbaDbBackupHistory] Between 02/26/2020 15:01:40/2970348000000001600075 and 05/21/2020 21:58:19/3001905000407060300209 C8 was on Recovery Fork GUID
7e518eb8-b281-409b-9064-b271d9b13a91 (4 backups)
#### Expected Behavior
Checking on msdb base on backupset yields the correct last backup get-dbabackuphistory also lists out all the later full backups. But get-dbalastbackup is not changing.

**Comment by wsmelton** [comment]
Multiple recovery forks will effect what the command outputs, as the warning states.

**Comment by andreasjordan** [comment]
@PioBalistoy can you please retest with latest version? Should be fixed now.
