### ISSUE TITLE
Install-DbaSqlWatch broken in PowerShell 7 

### ISSUE THREAD

**Issue by kaysauter** [sqlcollaborative/dbatools#6567]
### Summary of new feature

* I've tried to install Install-DbaSqlWatch with PowerShell 7.1 which didn't work. This is IMHO not a bug, but rather a new feature as it does work with PowerShell 6 just fine.

**Comment by wsmelton** [comment]
Please provide how it didn't work, that actually is a big because most all of our module had worked fine in PS 7.

**Comment by kaysauter** [comment]
Oh, I wasn't aware of that. But here is what I did and what it returned: 
`❯ Install-DbaSqlWatch -SqlInstance DevEnv -Database SQLWATCH`                                           

`WARNING: [06:18:27][Publish-DbaDacPackage] Could not load profile. | Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

The very same code worked in PS 6.

**Comment by wsmelton** [comment]
What version of Visual Studio/SSDT do you have installed on your machine?

**Comment by kaysauter** [comment]
Versions: 

- VS Community Edition 2019. I didn't have SSDT at that point. 
- SQL Server 2019 Dev Edtion CU4.

**Comment by wsmelton** [comment]
Can you install SSDT and see if this error still occurs?

We do not package that DLL with our module, the Dac commands depend on VS/SSDT being on the machine you plan on using the command on.

**Comment by kaysauter** [comment]
Well, after I've used PowerShell 6, it worked. Hence, it is already installed. But let me try it again next few days. I'll create a fresh vm extra for this. 😊
I'll let you know what I've found.

**Comment by wsmelton** [comment]
90% chance it working in PowerShell 6 is pure luck because we don't test against PowerShell 6 versions...if I recall we really didn't aim for it to work in that version either because SMO didn't at the time.

The version of the DLL error is showing is not coming from a DLL we package for DAC with our module, we only work on 15.0 version and have not upgraded to the latest SMO.

![image](https://user-images.githubusercontent.com/11204251/83765556-f06cc780-a640-11ea-9b53-dfb329707057.png)

**Comment by wsmelton** [comment]
Does it work in Windows PowerShell?

**Comment by kaysauter** [comment]
Hm, reading this I wonder if my memory serves me well. I just checked on my computer (not VM) here and saw that it was probably PS 5 not 6 as I thought to be.
Please bear with me, I'll do some tests with all documentations and screenshots in the next few days. Then I will try to find out what really works and what not. If you want, let me know what else I should test during that time!

**Comment by kaysauter** [comment]
I will do tests tonight or tomorrow. Please let me know what else I can test (can also be another tool part of dbatools) 😁 My premise: I'll do a fresh VM setup with a fresh SQL Server Dev Edition. Will provide screenshots.

**Comment by kaysauter** [comment]
So I've just checked with which version of PoSh I've installed SQLWATCH - it's indeed PoSh 5. I apologize for any circumstances and confusion I may have created with my first post. 
![image](https://user-images.githubusercontent.com/31820087/83949220-bb1fcf80-a822-11ea-88c6-732dd0c6a491.png)
The version I've used two days ago:
![image](https://user-images.githubusercontent.com/31820087/83949272-0934d300-a823-11ea-9fcf-4fd95df45443.png)

As promised, I'm setting up a new instance and will post my results also for PoSh in a couple of hours.

**Comment by kaysauter** [comment]
Here's the screenshot for PS 7: 
![image](https://user-images.githubusercontent.com/31820087/83954754-45305e00-a84c-11ea-8433-d04c3b21132b.png)

and here the screenshot for PS 6: 
![image](https://user-images.githubusercontent.com/31820087/83955521-0b635580-a854-11ea-88e6-332d42a0211f.png)

**Comment by kaysauter** [comment]
On the same computer, just minutes later, with PS 5:
![image](https://user-images.githubusercontent.com/31820087/83955658-7f522d80-a855-11ea-869e-003e9045d4fb.png)

**Comment by wsmelton** [comment]
The probability is we simply need to update the command to not execute in PowerShell as the DLLs I don't believe support that version. Especially since it seems to work correctly in Windows PowerShell.

Will have to see if this can be verified in some manner...

**Comment by kaysauter** [comment]
Yes, I think so too. I'll look into it as soon I can. However, I guess since this would be my first code I'd work on here for dbatools, I'd need some time for this. If this is an easy task / quick fix, let me know so that I won't spend too much time on this. 😄

**Comment by wsmelton** [comment]
We don't have how that is managed on this module documented right now so we will take care of it.

**Comment by seadba** [comment]
hello, is there a status for this - i get the same on 7/6   - thanks

**Comment by wsmelton** [comment]
If someone wants to contribute a PR for it we are more than welcome to review.

**Comment by andreasjordan** [comment]
Hi @kaysauter can you give me an update on this?

**Comment by kaysauter** [comment]
> Hi @kaysauter can you give me an update on this?

Hi @andreasjordan my understanding is that someone of the dbatools team will take care of it - see answer by @wsmelton on Jun 8 2020. So, I'm not involved in fixing this. Sorry.
Kind regards, Kay

**Comment by andreasjordan** [comment]
Hi Kay, 

you know, June 2020 is one year ago. So "someone of the dbatools team" will maybe take care of this issue in 2022 or so...
At the moment I don't have PS7 installed, so I can not test this. But if you can run the command with `-Verbose` and provide the output ... we maybe get closer to fixing it.

But if you personally are fine with the command not working on PS7 - sorry for bothering you, will just leave this issue as is.

Viele Grüße
Andreas

**Comment by wsmelton** [comment]
The command cannot be used in PowerShell 7. To properly fix this will require changing how we import commands as we likely have others that fall into this category and the way we import does not account for use with .NET vs dotnet Core with PowerShell 7. We focus only on platform (Windows vs Linux) in our import process.
