### ISSUE TITLE
[Bug] Restore-database within runspace

### ISSUE THREAD

**Issue by Johnfox1991** [sqlcollaborative/dbatools#6568]
### Environmental information

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.112\dbatools.psd1
Version : 1.0.112

#### SQL Server:

```sql
/* Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows 10 Enterprise LTSC 2019 10.0 <X64> (Build 17763: ) (Hypervisor)  */
```

#### Host used

- [X ] powershell.exe
- [ ] ISE
- [X ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: To use ReplaceDbNameInFile you must specify DatabaseName
TargetObject          :
CategoryInfo          : InvalidArgument: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_<ScriptBlock>,Stop-Function
ErrorDetails          : To use ReplaceDbNameInFile you must specify DatabaseName
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 5
PipelineIterationInfo : {0, 1}
#### Steps to Reproduce

running this command to restore database in PowerShell works fine...
Restore-DbaDatabase -SqlInstance localhost\sqlexpress -Path C:\databasebackups\Automation_Full_202006032007.bak -DatabaseName "Automation" -ReplaceDbNameInFile -Verbose

running within a runspace errors "To use ReplaceDbNameInFile you must specify DatabaseName"

**Comment by wsmelton** [comment]
Please provide working example code to reproduce the error within a runspace as you experienced.

**Comment by wsmelton** [comment]
Additional information around reproducing this error is missing. If it is still found to exists in the latest version please open a new issue and provide all details requested.

**Comment by lancasteradam** [comment]
The Restore-DbaDatabase seems to work fine in a runspace with that parameter. Sample code is below:

`<#
    Sample runspace invocation of Restore-DbaDatabase for https://github.com/sqlcollaborative/dbatools/issues/6568    
    This script is based on Chrissy LeMaire's article at https://blog.netnerds.net/2016/12/runspaces-simplified/
#>
# function to start the runspace with the backup command
function StartBackupRunspace {
    Param 
    (
        $Pool
    ,   $Instance
    ,   $BackupFile
    ,   $DBName
    )
    
    $scriptblock = {
        Param (
            $Instance
        ,   $BackupFile
        ,   $DBName
        )
        
        Restore-DbaDatabase -SqlInstance $Instance -Path $BackupFile -DatabaseName $DBName -ReplaceDbNameInFile -Verbose
    }
    
    $runspace = [PowerShell]::Create()
    $runspace.RunspacePool = $Pool        
    $null = $runspace.AddScript($scriptblock)
    $null = $runspace.AddArgument($Instance)
    $null = $runspace.AddArgument($BackupFile)
    $null = $runspace.AddArgument($DBName)    
    
    return [PSCustomObject]@{ Pipe = $runspace; Handle = $runspace.BeginInvoke() }
}

$pool = [RunspaceFactory]::CreateRunspacePool(1, [int]$env:NUMBER_OF_PROCESSORS+1)
$pool.ApartmentState = "MTA" # multi-threaded apartment state
$pool.Open()
$runspaces = $results = @()

# start the threads
$totalBackupsToRestore = 2
$runspaces += StartBackupRunspace $pool "instance_name" "backup_file" "db_name"
$runspaces += StartBackupRunspace $pool "instance_name" "backup_file" "db_name"

# wait for completion
while ($runspaces.Handle.IsCompleted -notcontains $true) {}

# cleanup
foreach ($runspace in $runspaces ) {
    $results += $runspace.Pipe.EndInvoke($runspace.Handle)
    $runspace.Pipe.Dispose()
}

$pool.Close() 
$pool.Dispose()

# sample analysis of final results
foreach ($result in $results) {
    Write-Output "The restore for $($result.Database) on $($result.ComputerName)\$($result.InstanceName) has completed with the following results:"
    $result
}

if ($results.count -ne $totalBackupsToRestore) {
    Write-Output "$($results.count) backups completed successfully"
}`
