### ISSUE TITLE
[Bug] Simple fix needed for display message in Copy-DbaDatabase

### ISSUE THREAD

**Issue by MCTSQL** [sqlcollaborative/dbatools#6570]
The latest version of CopyDbaDatabase, line 1401, is referencing an incorrect variable:

Issue:
CopyDbaDatabase: Line 1401:
if ($Pscmdlet.ShouldProcess($destinstance, "Updating BrokerEnabled on $dbName")) {

Solution:
# $dbName should be changed to $DestinationdbName

**Comment by dbaduck** [comment]
I have fixed this one. Simple change.
