### ISSUE TITLE
Possible bug, or improvement in Get-DbaUserPermission

### ISSUE THREAD

**Issue by WizardDBA** [sqlcollaborative/dbatools#6571]
Hi guys good afternoon 

I've run this particular script against a server of a client where all the databases have the first character of the name a number as example 4PEOPLE. This script basically ignores all the databases on that server.

Example:
Get-DbaUserPermission -SqlInstance SQLDEV -Database 4PEOPLE -ExcludeSystemDatabase | Out-GridView

**Comment by wsmelton** [comment]
What does it mean "ignores"...please provide requested details if you consider this a bug.

All that command does is execute this script: https://github.com/sqlcollaborative/dbatools/blob/development/bin/stig.sql

**Comment by WizardDBA** [comment]
I know the script stig.sql, ignores means it doesn't do nothing, empty output/result set.

I've tested in my local machine that has multiple databases and i've created a new one with name 4Test and it scans all the other db's except that one.

**Comment by andreasjordan** [comment]
Just provided a fix for that...
