### ISSUE TITLE
[Bug] Reset-DbaAdmin not doing something in output messages

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#6585]
Not sure why but running command locally on a server where you pass in the server name (same output as `$env:computername`) and it fails...I use `localhost` and it goes through properly. I'm not sure where this is at but adding issue as note to look at more later...

This is on Window Server 2019 non-desktop.

![image](https://user-images.githubusercontent.com/11204251/84548603-9bc5ee00-accb-11ea-89c2-2ccc667e56b8.png)

**Comment by andreasjordan** [comment]
Should be fixed with #6695.
