### ISSUE TITLE
Get-DbaProductKey incorrect key on sqlserver 2019

### ISSUE THREAD

**Issue by ChrMaa** [sqlcollaborative/dbatools#6587]
hi,

in dbatools v1.0.112 there is an error in 
Get-DbaProductKey -ComputerName localhost
on a Sql-Server 2014 i get a correct key
on a Sql-Server 2019 i get an incorrect key

Sincerely Chris

**Comment by wsmelton** [comment]
Please provide more detail, what do you mean by "an incorrect key"...what errors are you receiving? Can locate the product key for your 2019 instance in the registry (see path reference below that we look at in the function).

Ref line of code with the path set for the 2019 key:

https://github.com/sqlcollaborative/dbatools/blob/6ea349c5371903eb84e43fb7a2437a87a2e8872d/functions/Get-DbaProductKey.ps1#L128-L131

**Comment by ChrMaa** [comment]
I am getting no error message, in fact the message i receive looks completly as it is expected. Except the product key is completly different to the one used when i installed the Sql server(In the attached picture marked in red). This is reproducible and the case on all Sqlserver 2019 that i tested it on. An encoded product key can be found in the registry.
![Get-DbaProductKey](https://user-images.githubusercontent.com/49569866/84640638-3dcb1d80-aefa-11ea-8767-a0cbbb909785.PNG)

**Comment by wsmelton** [comment]
What path did you find the correct key at in the registry?

**Comment by ChrMaa** [comment]
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL15.MSSQLSERVER\Setup 
note: the key is only in an encoded form

**Comment by wsmelton** [comment]
Nothing much we can do about it being encoded that I'm aware. It may be change made with 2019 to not make it readable anymore.

@gbargsley I recall added it, did you find in your environment the value is readable?

**Comment by ChrMaa** [comment]
$a = Get-ItemProperty -Path "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL15.MSSQLSERVER\Setup" using this command i can read all values as i can see them in the registry using "regedit". So i would assume it should be readable.

**Comment by gbargsley** [comment]
I am not sure what value you are looking at that is "readable".  But the function decodes the DigitalProductID registry key into the actual formatted CD-Key.  You might be looking at the wrong registry key that you feel is readable.  While ProductID if that is what you are referring to is readable it is not the CD-Key for the software install.

![image](https://user-images.githubusercontent.com/169602/84699346-f69f5580-af16-11ea-875e-b23bd58dac2b.png)

![image](https://user-images.githubusercontent.com/169602/84699432-1df62280-af17-11ea-971a-f193e9c952fc.png)

**Comment by ChrMaa** [comment]
I have installed 3 Versions of the SQL Server(2014, 2017 and 2019) on a Testsystem (Windows Server 2019) using the command 

`Install-DbaInstance 
-SqlInstance localhost 
-Version $Version 
-ProductID $Productkey 
-AuthenticationMode 'Mixed' 
-SaCredential $SaCred 
-Feature Default, ReportingServices, IntegrationServices 
-PerformVolumeMaintenanceTasks:$True 
-Restart:$True 
-Confirm:$False 
-InstancePath $InstancePath
-BackupPath $BackupPath
-DataPath $DataPath 
-LogPath $LogPath 
-TempPath $TempPath
-Configuration @{ 
    SQLCOLLATION  = 'Latin1_General_CI_AS' 
    UPDATEENABLED = 'True'
}
`

when i then use the command "get-dbaproductkey -ComputerName localhost" i get the following as a result:

ComputerName : _ComputerName_
InstanceName : SQL2014
SqlInstance  : _ComputerName_\SQL2014
Version      : SQL Server 2014 RTM
Edition      : Standard Edition (64-bit)
Key          : **Shows Key used in Installation**

ComputerName : _ComputerName_
InstanceName : SQL2017
SqlInstance  : _ComputerName_\SQL2017
Version      : SQL Server 2017 RTM
Edition      : Standard Edition (64-bit)
Key          : **Shows something that looks like a Key but not the one that was used in Installation**

ComputerName : _ComputerName_
InstanceName : SQL2019
SqlInstance  : _ComputerName_\SQL2019
Version      : SQL Server 2019 RTM
Edition      : Standard Edition (64-bit)
Key          : **Shows something that looks like a Key but not the one that was used in Installation**

Only for the SQL Server 2014 I get the Product Key that i used in the Installation for the other two Versions I get Something that looks like a key but not the one that was used to install the version of the SQL Server. The two incorrect Keys are also different to each other.
Do you get the Product key you used for installation on your system?

**Comment by gbargsley** [comment]
That is not really something I can speak to.  There is a process that decodes the DigitalProductID and makes a readable CD-Key.  If something has changed with 2017 and 2019, I would not really be able to troubleshoot that process as I don't understand what it is doing.

**Comment by ChrMaa** [comment]
I also installed a SQL Server 2016 the same way. The DigitalProductID is also not the one used in the installation. 
I have then installed the chocolatey package "produkey.portable" via the command `choco install produkey.portable`. Using this program i can retrieve the readable and decoded CD-Key used in the installation for all the SQL Server versions I tested the command `get-dbaproductkey -ComputerName localhost` on.
 At this point i would assume from the version Sql Server 2014 on the encoding has changed and therefore the command `get-dbaproductkey -ComputerName localhost` is not working for newer Versions.

**Comment by wsmelton** [comment]
Was this test performed on varying OS versions as well to confirm it is not having an affect as well?

**Comment by ChrMaa** [comment]
All the SQL Servers that I mentioned above are installed on the same Windows Server 2019. I have i have a diffrent SQL Server 2014 installed on a Windows Server 2012 where the decoding works correct.

**Comment by wsmelton** [comment]
For my test machine, the registry key `DigitalProductID` we try to find the license key under for my 2019 instance does not exist. Based on the code we are masking that information and just if nothing is returned stating "we can't decode it".

**Comment by andreasjordan** [comment]
How can we work on this?

**Comment by potatoqualitee** [comment]
I'm not sure they are licensing it the same way anymore -- I am unable to get a Product Key for Enterprise 2019 to even test.

![image](https://user-images.githubusercontent.com/8278033/121877905-694e3700-cd0b-11eb-90ea-3fd3e384eb1b.png)

We may have to just stop support at 2017.

**Comment by andreasjordan** [comment]
Does 2014 show this key? 82YJF-9RP6B-YQV9M-VXQFR-YJBGX
If so, I might have the answer...

**Comment by andreasjordan** [comment]
I've installed some versions with product keys and can confirm that the command does not show the correct keys for SQL 2016 and newer. So I would suggest to change the code to test for the version and stop on 2016 and newer. 
This product was already mentioned in this issue: http://www.nirsoft.net/utils/product_cd_key_viewer.html
If someone wants to contact the developer to ask for help, feel free - but as it is closed source we might not get help.

**Comment by niphlod** [comment]
did someone forked us without telling back ? @andreasjordan can you try this https://gist.github.com/mtrimarchi/f56e3865bad8c4578def6d2c5586a1e6/revisions

**Comment by niphlod** [comment]
found also:
- https://github.com/virajds/VBS_and_PowerShell/blob/20e31fa1088780ed5e3db8782d9e4e26e70ecc5d/PowerShell/Get-SQLserverKeyV2.ps1
- https://github.com/MEM-Zone/sccm-zone.com/blob/b3acfd7e833f5aef383b63671c39c40ee01715a2/Reporting/Software/SW%20SQL%20Server%20Products/HWI%20EXT%20SQL%20Server%20Products.mof

**Comment by andreasjordan** [comment]
Sorry, @niphlod - it does not work.
The first link uses "$basepath\130\Tools\...", but there is not product key in that branch.
The second link just uses the code we currently use.
The third link uses the path like the first one.

I installed a developer edition and a standard edition with product key of sql server 2019. The difference in registry is clearly the "DigitalProductID", that probably still holds the Key - but not base24 encoded but with some other encoding. 

I have used this key: PMBDC-FXVM3-T777P-N4FY8-PKFF4
Source: https://www.codetd.com/en/article/7919976

The registry value is: 1b 11 00 00 00 00 ac 84 00 a7 d3 62 f2 f3 0b 00

So maybe someone can play with that...

**Comment by andreasjordan** [comment]
Our current implementation returns: 8T4GB-D6YJ8-H43HX-VFWGM-43PPF (which is definitly wrong)

**Comment by andreasjordan** [comment]
Opened a pull request to add a warning. Or do we want the command to fail for newer versions?

**Comment by potatoqualitee** [comment]
yeah you can just set a notification that is a warning that says "Command does not support xyz", thank you 🙇🏼

**Comment by andreasjordan** [comment]
Now it looks like this:
![image](https://user-images.githubusercontent.com/66946165/123793862-80338280-d8e2-11eb-9674-533a6567688f.png)

**Comment by potatoqualitee** [comment]
perfect!

**Comment by goodrichbl** [comment]
@andreasjordan a bit late on this, but I ran into same issue with SQL 2016+ product key decode nearly 2 years ago and after a few days of searching ran into a blog/forum post that seems to work for the SQL 2016+ keys I've tried it on.  Sorry I have no documentation of where the original post was from, but here is the "de-code" c# code it contained...

                bool isNKey = ((regBinary[14] / 0x6) & 0x1) != 0;

                if (isNKey)
                    regBinary[14] = Convert.ToByte((regBinary[14] & 0xF7));

                string regBinaryOutput = "";

                int last = 0;
                for (int i = 24; i >= 0; i--)
                {
                    int k = 0;
                    for (int j = 14; j >= 0; j--)
                    {
                        k = (k * 256) ^ regBinary[j];
                        regBinary[j] = Convert.ToByte(k / 24);
                        k = k % 24;
                    }
                    regBinaryOutput = charsArray[k] + regBinaryOutput;
                    last = k;
                }

                string regBinarypart1 = regBinaryOutput.Substring(1, last);
                string regBinarypart2 = regBinaryOutput.Substring(1, regBinaryOutput.Length - 1);
                if (isNKey)
                {
                    if (last == 0)
                        regBinaryOutput = "N" + regBinarypart2;
                    else
                        regBinaryOutput = regBinarypart2.Insert(regBinarypart2.IndexOf(regBinarypart1) + regBinarypart1.Length, "N");
                }

**Comment by andreasjordan** [comment]
That is basically the code we use. Only difference is this `isNKey`. It changes the resulting key - but does not return the correct key.

**Comment by goodrichbl** [comment]
Interesting..  It has returned the correct key for the SQL 2016+ product keys that we've tried.  I just confirmed also that it returned the correct key for the  registry value you noted on June 16 above.  "The registry value is: 1b 11 00 00 00 00 ac 84 00 a7 d3 62 f2 f3 0b 00"  and it returned PMBDC-FXVM3-T777P-N4FY8-PKFF4 as expected.  Is there a different one you tried that it's failing on?

**Comment by andreasjordan** [comment]
Oh, just played a bit with plain PowerShell. Maybe I made a mistake. Do you have only the C# code or PowerShell code also?

**Comment by goodrichbl** [comment]
Only in C# currently, but I'll update and give it a try in PS and post results (good or bad) on here afterwards.

**Comment by goodrichbl** [comment]
Sorry busy meeting day, but here is a quick and dirty PS script to demo the decode modifications from either registry or hard-coded numeric array values (sample contains your June 16 encoded values).  Let me know if this works or if you experience other issues, as it is possible it is not 100% accurate.  As previously stated, I did not create the modifications and just used what someone else posted as a workaround for SQL 2016+ since MS changed the encoding from that version forward for some reason.  Anyway, hope this helps.

$fromReg = 1

if ($fromReg -eq 1) {
    $localmachine = [Microsoft.Win32.RegistryHive]::LocalMachine
    $defaultview = [Microsoft.Win32.RegistryView]::Default
    $reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey($localmachine, $defaultview)
    $key = "SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL15.MSSQLSERVER\Setup"
    $encodedData = $reg.OpenSubKey($key).GetValue("DigitalProductID")
    $reg.Close()
}
else {
    $encodedData = 27,17,0,0,0,0,172,132,0,167,211,98,242,243,11,0
}

try {
    $binArray = ($encodedData)[0..66]
    $productKey = $null

    $charsArray = "B", "C", "D", "F", "G", "H", "J", "K", "M", "P", "Q", "R", "T", "V", "W", "X", "Y", "2", "3", "4", "6", "7", "8", "9"

    $isNKey = ([math]::truncate($binArray[14] / 0x6) -band 0x1) -ne 0;
    if ($isNKey) {
        $binArray[14] = $binArray[14] -band 0xF7
    }

    $last = 0

    for ($i = 24; $i -ge 0; $i--) {
        $k = 0
        for ($j = 14; $j -ge 0; $j--) {
            $k = $k * 256 -bxor $binArray[$j]
            $binArray[$j] = [math]::truncate($k / 24)
            $k = $k % 24
        }
        $productKey = $charsArray[$k] + $productKey
        $last = $k
    }

    if ($isNKey) {
        $part1 = $productKey.Substring(1, $last)
        $part2 = $productKey.Substring(1, $productKey.Length-1)
        if ($last -eq 0) {
            $productKey = "N" + $part2
        }
        else {
            $productKey = $part2.Insert($part2.IndexOf($part1) + $part1.Length, "N")
        }
    }

    $productKey = $productKey.Insert(20, "-").Insert(15, "-").Insert(10, "-").Insert(5, "-")
} catch {
    $productkey = "Cannot decode product key."
}

Write-Host $productKey

**Comment by andreasjordan** [comment]
It works! PR will follow. Thank you very much.
