### ISSUE TITLE
Add a flag for Remove-DbaBackup to Keep the most recent full/diff backup

### ISSUE THREAD

**Issue by paschott** [sqlcollaborative/dbatools#6590]
### Summary of new feature

* Add a "KeepLatest" type flag that would look for files matching the pattern, but if the most recent of all of the files in that path falls within the specified time range, do not delete the most recent of those files found.  If the most recent file falls outside of that time range, delete as normal.

### Proposed technical details (if applicable)

* I've encountered several cleanup routines that remove the files and there's no account for whether all backups have been successful or not. That leads to removing the last full backup file and not being able to recover.

* Check for existence of newer files matching that pattern in the specified path.
* If newer files are found or the "KeepLatest" flag is not passed, proceed with the delete as normal.
* If no newer files are found and the "KeepLatest" flag is passed in, do not remove the most recent file of that type.

### Latest version of dbatools as of writing

* 1.0.113

**Comment by wsmelton** [comment]
Be aware the intent of this command was strictly to act just like the cleanup backup task from maintenance plans in SQL Server. It has no logic at all to consider backup chain and I don't believe it really needs it.

I see this as also being a bit to dangerous to maintain as it puts the ownership of how backups are deleted on us, and that should be on the user (it's their data). Use of `Get-DbaDbBackupHistory` could be utilized to get the backup files they wish to remove and then simply pass those to the remove command to clean them up.

**Comment by paschott** [comment]
That's why I was thinking a flag might be an option. That doesn't put the ownership on anyone who maintains this code. It's up to the user who chose that option - same as any option that a user chooses that is potentially destructive.  The flag would default to false - so would behave as it always has. If passed in, it would ignore that most recent file when doing a delete, but it would have to be explicitly passed in to do so.

**Comment by wsmelton** [comment]
> If passed in, it would ignore that most recent file when doing a delete, but it would have to be explicitly passed in to do so.

This is not the definition of "keep the most recent full/diff backup? Just the most recent file(s) found on the drive with the specified extension.

**Comment by paschott** [comment]
Well, yes - it would look at the most recent file of that specified extension and explicitly not delete that one.  If it happens to not fall in the files that we'd otherwise look at, it's ignored.  If it overlaps with that range, it would be removed.

So - I want to delete all backups older than 14d, but make sure I have the latest backup.
1. Find that "most recent" backup - in this case, it's 4 days old.
2. Run the delete for all files > 14d, but that 4 day old file isn't in the set. I'm "safe" to delete all of those files.

Case 2:
1. Find my most recent backup. It happens to be 15 days old.
2. Pass in the command to delete all files older than 14 days.
  In this case, that 15 day old "most recent" file of that type would not be removed, but any other files matching the pattern and older than 14 days would be.

Looking at the Remove-DbaBackup command, it uses Find-DbaBackup to get a list of files to operate on. So for this to work in that framework, I'd need to find that most recent file matching the pattern and then exclude that from the Remove-Item call if it shows up.

I'm thinking this would be something like:
if ($KeepLatest) { $fileToKeep = #code that gets the most recent file matching that pattern in the path }
Remove-Item loop would ignore that file when stepping through the file list found by Find-DbaBackup.

**Comment by wsmelton** [comment]
What pattern are you referring to? The only thing we do in the Find command is a `Get-ChildItem` and filter on the file extension:

https://github.com/sqlcollaborative/dbatools/blob/5d6ecaf565d8286af3ee4a8335993441e6f9d2fa/functions/Find-DbaBackup.ps1#L166-L167

As well are you referring to changing the logic in `Find-DbaBackup` or within `Remove-DbaBackup`

**Comment by paschott** [comment]
I'm thinking of adding a flag to Remove-DbaBackup that would allow for keeping the latest.

That might mean an additional call to Find-DbaBackup to get that most recent file matching the pattern passed in, ignoring the date.  Then when going through the foreach loop that does the Remove-Item, bypass the entry that is the most recent one for a given path.

And of course, typing that I can see where this is a bit more complex with the "Recurse" flag in the mix. I still think the idea itself is valid - to not delete the "most recent" file in a given folder, but that's definitely harder when working across many folders because I'd want to make sure that the most recent file is not deleted in each folder, not just overall.  I still think that's doable with some sort of array containing those "most recent" files, but I can see the extra complexity in getting that for each folder.

**Comment by wsmelton** [comment]
I'll let others vote, but on average I would see users that want to keep that backup that is 15 days old to simply use a retention of 15d instead of 14d....most are familiar with this from using maintenance plans and other cleanup processes that depend on the date of a file (modified or last "touched").

**Comment by paschott** [comment]
I don't think I'm explaining this well. I don't have a problem with deleting backups that are in the range specified as a normal course, but this is more of a safety check of "make sure a backup has happened _since_ that time" so I don't just have a process that cleans up all old backups without making sure there is a newer one that I can use.  I've had too many cases where the process deletes those old backups, but something had gone wrong, often silently, that resulted in no newer successful backup.  In that case, the automatic cleanup based on just the days removed that most recent full backup because it was older than the given timeframe.

Normally, no issues with removing all files older than a certain date, but I'm looking for a way to ensure that I have that one good full/diff backup to use - even if it's one I'd have normally have purged based on age.

**Comment by paschott** [comment]
Thinking this over a little more, I had forgotten about the idea of striped backups, multiple folders, nested folders, and such, which all make this a lot more complex than I'd originally considered.  I still think this is valuable to have an option to force keeping that most recent (set of) files in order to make sure that we have that set to restore from, I can also see where this is much more complex than my first thoughts on it.

**Comment by potatoqualitee** [comment]
Yeah, it can get complex and ultimately, I tried but I just don't think this is within the scope of the command. I'd recommend a mix of Find-DbaBackup and Remove.
