### ISSUE TITLE
Set-DbaSpConfigure doesn't handle multiple SqlInstances correctly

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6591]
This:

    foreach ($instance in $SqlInstance) {
                $InputObject += Get-DbaSpConfigure -SqlInstance $SqlInstance -SqlCredential $SqlCredential -Name $Name
            }

Should be changed to that:

    foreach ($instance in $SqlInstance) {
                $InputObject += Get-DbaSpConfigure -SqlInstance $instance -SqlCredential $SqlCredential -Name $Name
            }

To work correctly when $SqlInstance is an array of Instances. 

Sample input:

    $SqlInstances = 'SRV1', 'SRV2'
    Set-DbaSpConfigure -SqlInstance $SqlInstances -Name CostThresholdForParallelism -Value 52

Sample output:

```
ComputerName  : {SRV1, SRV2, SRV1, SRV2}
InstanceName  : {MSSQLSERVER, MSSQLSERVER, MSSQLSERVER, MSSQLSERVER}
SqlInstance   : {SRV1, SRV2, SRV1, SRV2}
ConfigName    : CostThresholdForParallelism
PreviousValue : 51
NewValue      : 52

ComputerName  : {SRV1, SRV2, SRV1, SRV2}
InstanceName  : {MSSQLSERVER, MSSQLSERVER, MSSQLSERVER, MSSQLSERVER}
SqlInstance   : {SRV1, SRV2, SRV1, SRV2}
ConfigName    : CostThresholdForParallelism
PreviousValue : 50
NewValue      : 52

ComputerName  : {SRV1, SRV2, SRV1, SRV2}
InstanceName  : {MSSQLSERVER, MSSQLSERVER, MSSQLSERVER, MSSQLSERVER}
SqlInstance   : {SRV1, SRV2, SRV1, SRV2}
ConfigName    : CostThresholdForParallelism
PreviousValue : 51
NewValue      : 52

ComputerName  : {SRV1, SRV2, SRV1, SRV2}
InstanceName  : {MSSQLSERVER, MSSQLSERVER, MSSQLSERVER, MSSQLSERVER}
SqlInstance   : {SRV1, SRV2, SRV1, SRV2}
ConfigName    : CostThresholdForParallelism
PreviousValue : 50
NewValue      : 52
```

**Comment by wsmelton** [comment]
Notes for contributor that handles this issue:

The logic for this function should be adjusted to match the standard of our commands.

There for each loop is not required but could be used in a different manner. 

Please look at other commands in the module to get an idea what logic we use.
