### ISSUE TITLE
Get-dbaNetworkCertificate and Set-dbaNetworkCertificate fail silently remote connections

### ISSUE THREAD

**Issue by montereyharris** [sqlcollaborative/dbatools#6592]
When trying to connect to remote SQL server to work with network certificate the cmdlets fail silently. 
I am currently try to access a SQL server remotely to change the certificate and then confirm that the change completed. 
It works fine when dbatools is installed locally on SQL server and script is run locally but fails silently when it is remote. 

Here is basic logic:

$instanceName = 'sometestsqlserver'

Set-DbaNetworkCertificate -SqlInstance $instanceName -Thumbprint ($cert.thumbprint)

Get-DbaNetworkCertificate -ComputerName $instanceName

**Comment by wsmelton** [comment]
The command requires the `-Credential` parameter to be provided if the user context of the PowerShell session does not have permission to remotely access the server. A remote WMI call is being made in this function to configure it.

If the issue still exists within the latest version please create a new issue and provide all the requested details in our template.
