### ISSUE TITLE
Add a NoteProperty to Get-DbaComputerSystem that utilizes Test-PendingReboot

### ISSUE THREAD

**Issue by mmaagk642** [sqlcollaborative/dbatools#6595]
This would help when trying to install or update sql instances to know whether or not a restart is required first. This could be a check added to install-dbainstance or update-dbainstance as well, but would be a nice add to get-dbacomputersystem. For example, if you run install-dbainstance, it could check by utilizing test-pendingreboot and come back and say a restart is required before install or something along those lines.

**Comment by wsmelton** [comment]
This is already done in the install and update command.

**Comment by mmaagk642** [comment]
Hi Shawn, this request was more for get-dbacomputersystem as a check. Not so much when running or trying to run the install or update. Thanks for the update and you’re right as I write this I have seen that when doing installs and updates. I’d just like to see it in the get Command as well listed above.
