### ISSUE TITLE
Copy-DbaDatabase -DetachAttach switch is using \\SqlSERVER\M$\MSSql... without domain name causing access issue

### ISSUE THREAD

**Issue by shaddy02** [sqlcollaborative/dbatools#6600]
I found an issue here with the -detachAttach switch. It doesn't take into consideration the domain name of the server when accessing the directories. Eg. \\server\serverFolder\user_dbdata\data instead of \\server.domain.com\serverFolder\user_dbdata\data

Causing this error: 
![image](https://user-images.githubusercontent.com/11272807/85172306-01672c80-b22e-11ea-9b24-069b57f47c89.png)

DetachAttach methos doesn;t allow using SharedPath instead File copies are performed over administrative shares (\\server\x$\mssql

**Comment by andreasjordan** [comment]
Hi @shaddy02 : Can you run `Resolve-DbaNetworkName -ComputerName XYZ` with `XYZ` as the computer name only like in the wrong UNC path? Then tell me, which of the output information would be correct as to build the UNC path with.

**Comment by wsmelton** [comment]
@andreasjordan best fix for this is to stop using remote paths and do calls locally to the server (`Invoke-Command2` calls). That removes the need to do any type of looking or check on UNC paths. We do local checks of this nature in  other commands I recall instead of remote UNC or the admin share.

Which I'm sure to do this will require restructuring a good bit of how the command works. It could be evaluated as well to see if we have more commands that do the heavy lifting with database files than when we originally wrote this command.

**Comment by andreasjordan** [comment]
The UNC path is needed for the `Start-BitsTransfer` which is propably way faster that copying over PSSession. And we would need to open a session from the destination to the source server. We can not be sure that this works as good as opening a session from the server with dbatools to both the source and destination.

I think the actual implementation works for most cases, so I would not rewrite the code to use PSSession to copy. Either we find a good way to use the full computername here or we close this as "will not fix".

**Comment by wsmelton** [comment]
Unless it has changed, the use of Starts-BitsTransfer is not that efficient considering if a user runs the command from their local workstation the network path of copying a file from a source to target, the file still has to traverse the client workstation. Versus if you copy a file from, locally, the source instance (via Invoke-Command2) directly to the target instance that will enhance the performance greatly and cause less network traffic.

The Bits transfer's only advantage is it has restart ability if the network hiccups during the transfer. Supporting the use of copying the file over PSSession would also provide the ability to support copying files to SQL Server on Linux, which right now cannot be done in this command.

**Comment by wsmelton** [comment]
We can create a new issue I guess or maybe discussion to find out what interest there are in supporting various scenarios.

If the PR you have for this fixes this specific issue, then let it ride and leave the command as-is until interest matches the effort required. I have not seen anyone really bring up our limited support for SQL + Linux.

**Comment by andreasjordan** [comment]
I'm a bit afraid to break things for other users if we now use the full name.  And I don't know which of DNSHostEntry, FQDN or FullComputerName would be the best to use. Can you have a look at the PR?

**Comment by wsmelton** [comment]
I don't have access to customer environments anymore to see what property returns what. Using FQDN vs DNS name can vary based on how their AD and DNS works. I've hit some environments where FQDN for a UNC path did not work and had to use just the server name.

Considering no one else has reported the issue I would hold of making any changes until this is upvoted to indicate it actually needs to be fixed. That is why a number of our issues are left open, unless there is details that prove this is not purely environmental there is no direct need to fix it immediately.

**Comment by niphlod** [comment]
JM2C, the "correcter" version is indeed FullComputerName. 
Hard (time sensitivity being an issue) to resolve, but it works also on disjoint domains.

As for the "best method for transfer"..... I hope anyone doing -DetachAttach does it from either the source or the destination, not from a jump server.
As for copying big files over PSSession (does it really work when transferring files from Windows to Linux ? I didn't realize that) do not even start: at least from windows to windows Copy-Item -FromSession and -ToSession are forced to wrap binaries in base64 chunks that get injected in envelopes that are chunked to a fixed size (so even tinkering with MaxEnvelopeSize on the winrm side doesn't do any good) and there's the whole dance about http+soap+eventual encryption on each envelope.

**Comment by andreasjordan** [comment]
Ok, just found a good workaround, so I will close the pull request.

If we first create the server SMO, we can change the property ComputerName to the FullComputerName:
```
$null = New-DbaDatabase -SqlInstance SRV1\SQL2017 -Name test01
$source = Connect-DbaInstance -SqlInstance SRV1\SQL2017
$source.ComputerName = (Resolve-DbaNetworkName -ComputerName $source).FullComputerName
Copy-DbaDatabase -Source $source -Destination SRV2\SQL2017 -Database test01 -DetachAttach -Reattach -Verbose
```
VERBOSE: [17:45:39][Start-SqlFileTransfer] Copying \\SRV1.Company.Pri\C$\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\test01.mdf for test01.
VERBOSE: [17:45:39][Start-SqlFileTransfer] Copying \\SRV1.Company.Pri\C$\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\test01_log.ldf for test01.

Will leave this open for some days and hope @shaddy02 can test that.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
