### ISSUE TITLE
New-DbaAvailabilityGroup should enable and start the AlwaysOn_health extended event session

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6603]
### Summary of new feature

Quote from the [dokumentation](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-extended-events):
"The alwayson_health extended events session is created automatically when you create the availability group, and captures a subset of the availability group related events. This session is preconfigured as a useful and convenient tool to help you get started quickly while troubleshooting an availability group. The Create Availability Group Wizard automatically starts the session on every participating availability replica configured in the wizard."

So I think it would be nice to do this configuration with New-DbaAvailabilityGroup

### Proposed technical details (if applicable)

I use this line of code to do this:

    Get-DbaXESession -SqlInstance $SqlInstances -Session AlwaysOn_health | ForEach-Object -Process { $_.AutoStart = $true ; $_.Alter() ; $_ | Start-DbaXESession }

### Latest version of dbatools as of writing

I currently use Version 1.0.113.

**Comment by wsmelton** [comment]
This would be something tied to a switch but will not be default to enable.

We are simply performing what SMO does to create an AG. An additional configuration of this nature should be done via parameter switch, with the default action of false not enabling that session.

If the session does not exists, it should ignore and just through warning stating as much.
