### ISSUE TITLE
Get-DbaDbBackupHistory and AgCheck Switch

### ISSUE THREAD

**Issue by amon09** [sqlcollaborative/dbatools#6606]
I'm wondering why is `AgCheck` switch not `NoAgCheck` instead in the `Get-DbaDbBackupHistory` cmdlet.

`Get-DbaDbBackupHistory -SqlInstance 'listener_name' -AgCheck:$false | select sqlinstance -Unique` does availability group checks and
`Get-DbaDbBackupHistory -SqlInstance 'listener_name' -AgCheck:$true | select sqlinstance -Unique`  does not... which is very confusing

**Comment by andreasjordan** [comment]
Lets link #6799 ([Get-DbaAgBackupHistory] - New command for the availability group functionality of Get-DbaDbBackupHistory) here and maybe close this if we have decided on the pull request.

**Comment by wsmelton** [comment]
The new command does not solve this issue.

**Comment by andreasjordan** [comment]
As -AgCheck is deprecated I will close this.
