### ISSUE TITLE
[Bug] Grant-DbaAgPermission - creation of login failing (Cannot bind argument to parameter 'SqlInstance' because it is null)

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6613]
This code throws the error:
```
$null = Grant-DbaAgPermission -SqlInstance $server -Login $serviceAccount -Type Endpoint -Permission Connect
WARNING: [14:52:40][Grant-DbaAgPermission] Failure | Cannot bind argument to parameter 'SqlInstance' because it is null.
```

Here is the responsible code (starting line 124):
```
            if ($perm -contains "CreateAnyDatabase") {
                try {
                    $server = Connect-SqlInstance -SqlInstance $instance -SqlCredential $sqlcredential
                } catch {
[...]
                }
[...]
            } elseif ($Login) {
                $InputObject += Get-DbaLogin -SqlInstance $instance -SqlCredential $SqlCredential -Login $Login
                foreach ($account in $Login) {
                    if ($account -notin $InputObject.Name) {
                        try {
                            $InputObject += New-DbaLogin -SqlInstance $server -Login $account -EnableException
                        } catch {
                            Stop-Function -Message "Failure" -ErrorRecord $_ -Target $instance
                            return
                        }
                    }
                }
            }
```

The failing commandlet is "New-DbaLogin -SqlInstance $server -Login $account -EnableException" because the variable $server is only set in the other branch of the outer if. It should use $instance instead, like the Get-DbaLogin some line above.

**Comment by andreasjordan** [comment]
Different aspect, same code: 
Please make sure, the "} elseif ($Login) {" is correct. I think it should be an if instead of an elseif to be able to create new logins even if the permissions contain CreateAnyDatabase.

**Comment by andreasjordan** [comment]
There is the same code in Revoke-DbaAgPermission.
Why to you try to add a login when you want to revoke permissions???

**Comment by wsmelton** [comment]
Reference for contributor who addresses this issue:

`$server` is the correct variable to be using on the child function calls, the logic needs to be adjusted to make one call to `Connect-SqlInstance` and then reuse that connection.
