### ISSUE TITLE
[Bug] Cannot force the member with name "PSStandardMembers" and type "MemberSet" to be added

### ISSUE THREAD

**Issue by Don-StCyr** [sqlcollaborative/dbatools#6615]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                              
----                           -----                                                              
PSVersion                      5.1.14393.3471                                                     
PSEdition                      Desktop                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                            
BuildVersion                   10.0.14393.3471                                                    
CLRVersion                     4.0.30319.42000                                                    
WSManStackVersion              3.0                                                                
PSRemotingProtocolVersion      2.3                                                                
SerializationVersion           1.1.0.1                                                            
```

#### dbatools Module version:

```
Name    : DBATools
Path    : C:\Program Files\WindowsPowerShell\Modules\DBATools\DBATools.psd1
Version : 1.0.113
## I also have another system running 1.0.88 and it is doing the same
```

#### SQL Server:

```sql
Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64)   Jun 15 2019 00:26:19   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

### Report

My script is executing via a Task Scheduler job

I am getting this error: System.InvalidOperationException: Cannot force the member with name "PSStandardMembers" and type "MemberSet" to be added. A member with that name and type already exists, and the existing member is not an instance extension.

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [x] Other (please specify)

Via Scheduled Job in Task Scheduler

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

<!--
Run this command and paste below:
```

```
PSMessageDetails      : 
Exception             : System.InvalidOperationException: Cannot force the member with name 
                        "PSStandardMembers" and type "MemberSet" to be added. A member with that 
                        name and type already exists, and the existing member is not an instance 
                        extension.
TargetObject          : [XXXxxUpdate]
CategoryInfo          : InvalidOperation: ([XXXXxxUpdate]:PSObject) [Add-Member], 
                        InvalidOperationException
FullyQualifiedErrorId : CannotRemoveTypeDataMember,Microsoft.PowerShell.Commands.AddMemberCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Select-DefaultView<Process>, C:\Program 
                        Files\WindowsPowerShell\Modules\DBATools\allcommands.ps1: line 79821
                        at Get-DbaDatabase<Process>, C:\Program 
                        Files\WindowsPowerShell\Modules\DBATools\allcommands.ps1: line 21531
                        at Invoke-DbaDiagnosticQuery<Process>, C:\Program 
                        Files\WindowsPowerShell\Modules\DBATools\allcommands.ps1: line 46089
                        at <ScriptBlock>, <No file>: line 3
PipelineIterationInfo : {1, 1}
```

#### Steps to Reproduce

```
## In the Powershell ISE
cls
$error.Clear()
$qs = "Avg Task Counts"
foreach ($q in $qs){
    $results = Invoke-DbaDiagnosticQuery -SqlInstance "localhost" -Database "XXXxx" -QueryName "Server Memory" -EnableException
    }
$error.Count   ## = 1
$error

## In Powershell.exe
cls
$error.Clear()
$qs = "Avg Task Counts"
foreach ($q in $qs){
    $results = Invoke-DbaDiagnosticQuery -SqlInstance "localhost" -Database "XXXxx" -QueryName $q -EnableException
    }
$error.Count    ## = 1
$error

## In CMD Line Powershell:
cls
$error.Clear()
$qs = "Avg Task Counts"
foreach ($q in $qs){
    $results = Invoke-DbaDiagnosticQuery -SqlInstance "localhost" -Database "XXXxx" -QueryName $q -EnableException
    }
$error.Count    ## = 0  ##NOT SURE WHY THIS IS DIFFERENT?!
$error
```

#### Expected Behavior

No extra errors in my log file, no errors like:
"Add-Member : Cannot force the member with name "PSStandardMembers" and type "MemberSet" to be 
added. A member with that name and type already exists, and the existing member is not an 
instance extension."

#### Actual Behavior

Each execution adds this line in the log file:
"System.InvalidOperationException: Cannot force the member with name "PSStandardMembers" and type "MemberSet" to be added. A member with that name and type already exists, and the existing member is not an instance extension."

**Comment by Don-StCyr** [comment]
Grr. I hope the "Errors Received", "Steps to Reproduce", etc are just hidden...

**Comment by wsmelton** [comment]
Please provide more details on what your script is doing or provide the script itself.

**Comment by wsmelton** [comment]
No additional information was provided. Please create a new issue and provide all details requested for reproducing the error.
