### ISSUE TITLE
DbaMigration - odd behavior. Complain can't do backup but backup is being made

### ISSUE THREAD

**Issue by deJagerF** [sqlcollaborative/dbatools#6617]
Greetings
I am using the following (server folder names masked
$params = @{
 Source = "PR\H"
 Destination = "PR\H"
 SharedPath = "\\PR\migration_share"
 BackupRestore = $true
 Force = $true
 WithReplace = $true
 }

Start-DbaMigration @params -Verbose

I see the following in the output window
WARNING: [09:06:29][Backup-DbaDatabase] Backup Failed | Cannot bind argument to parameter 'SqlInstance' because it is null.
VERBOSE: [09:06:29][Copy-DbaDatabase] Backup Failed. Does SQL Server account U\Mr have access to \\P\migration_share? Aborting routine for this database.

However I have confired that that account has full acces to the folder and I can see the backup files in that folder

### Environmental information

```powershell
# Replace with output of Get-Culture
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU8) (KB4505830) - 13.0.5426.0 (X64)   Jul 21 2019 21:16:47   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [ ] ISE

**Comment by Stuart-Moore** [comment]
If it's creating the backup file then it could be ould be an issue with permissions, we've seen this before if the SQL instance has write permissions but not read permissions. This isn't that uncommon for security reasons

Try reading the headers of the created backup file. Either with T-SQL `RESTORE HEADERONLY FROM DISK='\path\file'` or the dbatools command `Read-DbaBackupHeader`

**Comment by deJagerF** [comment]
Greetings

This is what I get (certain info masked)
Hope this helps

\Windows\system32> Read-DbaBackupHeader -SqlInstance "PRHFHEDDBN01\HEDAAG" -Path '\\PRHCBTNS90\migration_share\dbatools_202006240859-1-of-3.bak'


BackupName             : 
BackupDescription      : 
BackupType             : 1
ExpirationDate         : 
Compressed             : 1
Position               : 1
DeviceType             : 2
UserName               : U\43
ServerName             : P\H
DatabaseName           : dbatools
DatabaseVersion        : 852
DatabaseCreationDate   : 2020/06/23 10:48:03 AM
FirstLSN               : 34000000121000247
LastLSN                : 34000000358400001
CheckpointLSN          : 34000000358100001
DatabaseBackupLSN      : 34000000273900220
BackupStartDate        : 2020/06/24 8:59:38 AM
BackupFinishDate       : 2020/06/24 8:59:38 AM
SortOrder              : 52
CodePage               : 0
UnicodeLocaleId        : 1033
UnicodeComparisonStyle : 196609
CompatibilityLevel     : 130
SoftwareVendorId       : 4608
SoftwareVersionMajor   : 13
SoftwareVersionMinor   : 0
SoftwareVersionBuild   : 4001
MachineName            : PR1
Flags                  : 1536
BindingID              : 815c4881-689b-4e34-90dc-a3b2a1ded34d
RecoveryForkID         : 8fd9776f-1c7b-4aeb-a08f-6223a4ada90b
Collation              : SQL_Latin1_General_CP1_CI_AS
FamilyGUID             : 8fd9776f-1c7b-4aeb-a08f-6223a4ada90b
HasBulkLoggedData      : False
IsSnapshot             : False
IsReadOnly             : False
IsSingleUser           : False
HasBackupChecksums     : False
IsDamaged              : False
BeginsLogChain         : False
HasIncompleteMetaData  : False
IsForceOffline         : False
IsCopyOnly             : True
FirstRecoveryForkID    : 8fd9776f-1c7b-4aeb-a08f-6223a4ada90b
ForkPointLSN           : 
RecoveryModel          : FULL
DifferentialBaseLSN    : 
DifferentialBaseGUID   : 
BackupTypeDescription  : Database
BackupSetGUID          : 8a7353b3-b635-421d-83e9-8d5dea7fc23e
Containment            : 0
KeyAlgorithm           : 
EncryptorThumbprint    : 
EncryptorType          : 
FileList               : {@{LogicalName=dbatools_PRIMARY; PhysicalName=D:\MSSQL\Data\dbatools_PRIMARY.mdf; Type=D; FileGroupName=PRIMARY; Size=104857600; 
                         MaxSize=35184372080640; FileId=1; CreateLSN=0; DropLSN=0; UniqueId=38ed29cb-3860-412e-bc3c-9695e8f03b20; ReadOnlyLSN=0; ReadWriteLSN=0; 
                         BackupSizeInBytes=3670016; SourceBlockSize=512; FileGroupId=1; LogGroupGUID=; DifferentialBaseLSN=34000000273900220; 
                         DifferentialBaseGUID=2e81ec08-91d4-48e0-aef6-eab464c789c9; IsReadOnly=False; IsPresent=True; TDEThumbprint=; SnapshotUrl=; RowError=; 
                         RowState=Unchanged; Table=Table; ItemArray=System.Object[]; HasErrors=False}, @{LogicalName=dbatools_Log; 
                         PhysicalName=L:\MSSQL\dbatools_Log.ldf; Type=L; FileGroupName=; Size=104857600; MaxSize=2199023255552; FileId=2; CreateLSN=0; DropLSN=0; 
                         UniqueId=8d854b6d-9a46-4f8a-aeba-5b45f0e3d0af; ReadOnlyLSN=0; ReadWriteLSN=0; BackupSizeInBytes=0; SourceBlockSize=512; FileGroupId=0; 
                         LogGroupGUID=; DifferentialBaseLSN=0; DifferentialBaseGUID=00000000-0000-0000-0000-000000000000; IsReadOnly=False; IsPresent=True; 
                         TDEThumbprint=; SnapshotUrl=; RowError=; RowState=Unchanged; Table=Table; ItemArray=System.Object[]; HasErrors=False}}
SqlVersion             : SQL Server 2016
BackupPath             : \\P\migration_share\dbatools_202006240859-1-of-3.bak
BackupSize             : 7,24 MB
CompressedBackupSize   : 840,14 KB

**Comment by andreasjordan** [comment]
Sorry, has been lost from sight. Is this still a problem?
