### ISSUE TITLE
Update-DbaInstance Installing CU5 for SQL2019 fails, store needs update

### ISSUE THREAD

**Issue by ChrMaa** [sqlcollaborative/dbatools#6624]
Calling Update-DbaInstance fails, store needs an update

    Verzeichnis: C:\tmp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       25.06.2020     14:28      632044864 SQLServer2019-KB4552255-x64.exe

Update-DbaInstance -ComputerName LOCALHOST -KB 4552255 -Restart -Path C:\tmp -Confirm:$false -verbose

...
AUSFÜHRLICH: [08:51:07][Resolve-DbaBuild] Looking for KB 4552255
AUSFÜHRLICH: [08:51:07][Resolve-DbaBuild] We have 0 builds in store for this Release
WARNUNG: [08:51:07][Resolve-DbaBuild] No info in store for this Release

**Comment by wsmelton** [comment]
The build file was updated on 26 June.

You can update the local index of your system, by running `Get-DbaBuildReference -Update`.
