### ISSUE TITLE
Is dbaTools fully functional on SQL Server 2019 (wintel)?

### ISSUE THREAD

**Issue by Kismet110** [sqlcollaborative/dbatools#6628]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

**Comment by wsmelton** [comment]
The commands in the module should function against a SQL Server 2019 instance. If you find any that are not please submit an issue reporting.
