### ISSUE TITLE
[Bug]Get-DbaDbSpace -AutoGrowth reports wrong numeric value in case is_percent_growth = 1

### ISSUE THREAD

**Issue by mkley** [sqlcollaborative/dbatools#6639]
### Environmental information

<!--
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
PowerShell Version        : 5.1.14409.1018
dbatools latest installed : 1.0.112
Culture of OS             : en-US

#### SQL Server:

Microsoft SQL Server 2017 (RTM-CU20) (KB4541283) - 14.0.3294.2 (X64)   Mar 13 2020 14:53:45   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

us_english

### Report

The property "AutoGrowth" of function Get-DbaDbSpace gives wrong numeric value in case is_percent_growt = 1.
The problem is caused by the following T-SQL code: 
,CAST((f.growth/128.0) AS FLOAT) AS [GrowthMB]  (line 99)

It should be replaced by something like this: 
IIF(f.is_percent_growth = 1, CAST(f.growth AS VARCHAR(10)) +' %', CAST((f.growth/128) AS VARCHAR(10))+ ' MB' ) AS my_growth

You will understand this when reading Microsoft´s documentation about column growth of sys.database_files view:
https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-files-transact-sql?view=sql-server-ver15

#### Host used

- [X ] powershell.exe
- [X ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

If you have a db file with default auto-growth 10 %, Get-DbaDbSpace should provide 10 %.

#### Steps to Reproduce

See above.

#### Expected Behavior

If you have a db file with default auto-growth 10 %, Get-DbaDbSpace should provide 10 %

#### Actual Behavior

If you have a db file with default auto-growth 10 %, Get-DbaDbSpace provides 80.00 KB as result.

**Comment by mkley** [comment]
All my environmental informations I entered carefully are gone, therefore close this issue. Site drives me crazy!

**Comment by wsmelton** [comment]
You have to remove the comment notations. This is the open comment syntax `<!--` and then the closing one is `-->`
