### ISSUE TITLE
Incorrect version returned

### ISSUE THREAD

**Issue by sitrl** [sqlcollaborative/dbatools#6640]
The last cumulative patch sql server 2017 is CU21 no. 14.0.3335.7.
The following command return the version CU20, wrong!!!

Details:

Get-DbaBuildReference -Build "14.0.3335.7"

Build          : 14.0.3335.7
BuildLevel     : 14.0.3294
CULevel        : CU20  --> corrisponding to CU21 and NOT CU20!!!!!
KBLevel        : 4541283
MatchType      : Approximate
NameLevel      : 2017
SPLevel        : RTM
SupportedUntil : 12.10.2027 00:00:00
Warning        :

**Comment by wsmelton** [comment]
Please reference this documentation on how the build file works...

https://github.com/sqlcollaborative/dbatools/wiki/Asset-Update-Process

**Comment by wsmelton** [comment]
Latest CU for 2017 was added last night...
