### ISSUE TITLE
[Bug] Recently, Get-DbaDbTable takes a full five to seven minutes to run in a large database

### ISSUE THREAD

**Issue by brianary** [sqlcollaborative/dbatools#6646]
### Environmental information

```
PowerShell Version        : 5.1.18362.145
dbatools latest installed : 1.0.114
Culture of OS             : en-US
```

#### SQL Server:

```
Microsoft SQL Server 2012 (SP4-GDR) (KB4532098) - 11.0.7493.4 (X64)
        Dec 24 2019 19:33:24
        Copyright (c) Microsoft Corporation
        Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
```

```
us_english
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

No errors.

#### Steps to Reproduce

In our database (> 800 GB, > 50,000 columns across > 1,800 tables), this command now takes at five or more minutes to run:

```powershell
Get-DbaDbTable -SqlInstance $server -Database $database -Table $tablename
```

#### Expected Behavior

Previous versions (I'm not really sure how far back) were near instantaneous in the same database.

#### Actual Behavior

It's too slow to use conveniently.

**Comment by wsmelton** [comment]
Please provide more detail on what it is doing to your instance while running compared to earlier versions (tracing output, XE session, etc.). As well if you can show what version of the module works properly for you so we know where to look at what changed after that specific version will be helpful.

**Comment by brianary** [comment]
Version 1.0.0 runs the same command in under two seconds. I'll write a script that does a binary search to try and find when it changed.

**Comment by brianary** [comment]
The inability to unload DLLs to uninstall a module makes scripting this nontrivial. I have determined that `Get-DbaDbTable` doesn't work at all in 1.0.56 and 1.0.57.

**Comment by brianary** [comment]
I was able to test using this:

```powershell
<#
.Synopsis
    Binary search to find the version where a module fails a test.

.Parameter Condition
    A test that returns true or false.

.Parameter ModuleVersion
    The module version piped in.

.Inputs
    Microsoft.PowerShell.Commands.PSRepositoryItemInfo from Find-Module

.Example
    Find-Module dbatools -AllVersions |Find-FailingModuleVersion.ps1 {(Measure-Command {Get-DbaDbTable -SqlInstance '(localdb)\ProjectsV13' -Database AdventureWorks2016 -Table Production.Product}).TotalSeconds -lt 40}
#>

#Requires -Version 5
[CmdletBinding()] Param(
[Parameter(Position=0,Mandatory=$true)][scriptblock] $Condition,
[Parameter(Mandatory=$true,ValueFromPipeline=$true)][psobject] $ModuleVersion
)
Begin {[psobject[]]$versions = @()}
Process {$versions += $ModuleVersion}
End
{
    if($versions.Count -eq 0) {return}
    [int]$i = $versions.Count/2
    $name,$v = $versions[$i].Name,$versions[$i].Version
    if(!(Test-Path "~/.$name" -Type Container)) {mkdir "~/.$name"}
    if(!(Test-Path "~/.$name/$v" -Type Leaf))
    {
        Write-Verbose "Checking $name $v"
        Start-Process (Get-Process -Id $PID).Path '-NoLogo','-NoProfile','-NonInteractive','-Command',
            "`"& {Install-Module '$name' -RequiredVersion '$v' -Scope CurrentUser -Force; & { $Condition } |Out-File '~/.$name/$v' ascii}`"" -NoNewWindow -Wait
    }
    $from,$thru = switch((Get-Content "~/.$name/$v" -ReadCount 1))
    {
        True
        {
            Write-Host '✓' -ForegroundColor Green -NoNewline
            Write-Host " $name $v : pass"
            0,($i-1)
        }
        False
        {
            Write-Host '✗' -ForegroundColor Red -NoNewline
            Write-Host " $name $v : fail"
            ($i+1),($versions.Count-1)
        }
        default
        {
            Write-Host '⁉' -ForegroundColor Red -NoNewline
            Write-Host " $name $v : inconclusive"
            0,($versions.Count-2)
        }
    }
    if(Get-Module $name -ListAvailable |where Version -eq $v) {Uninstall-Module $name -RequiredVersion $v -Force}
    if($from -gt $thru) {return}
    $versions[$from..$thru] |& $PSCommandPath $Condition
}
```

**Comment by brianary** [comment]
Version 1.0.92 takes about ten seconds, 1.0.93 takes about five minutes.

**Comment by wsmelton** [comment]
@jshall made the change to this command then between those two versions: https://github.com/sqlcollaborative/dbatools/commit/fec9f06b0eb655491668db966529061d9cae4479#diff-71667a3299bb061a21c366787b1066bc

@brianary 
If you can in your environment test out taking out that `$db.Tables.Refresh($true)` in the `Get-DbaDbTable` command it will confirm whether this is the culprit or not.

**Comment by brianary** [comment]
Confirmed. That's it. Commenting it out (both _Get-DbaDbTable.ps1_ and _allcommands.ps1_) drops the time under ten seconds. In the short term, a switch param that disables (on enables) that would help a lot, as a workaround.

**Comment by nvarscar** [comment]
That refresh is definitely going to hurt the performance of the command. If the user needs refreshed set of tables, they can trigger the refresh manually.
