### ISSUE TITLE
[Bug] Documentation: Invoke-DbaQuery

### ISSUE THREAD

**Issue by JeffRush** [sqlcollaborative/dbatools#6650]
Documentation for Invoke-DbaQuery states "See examples for detail" on -MessagesToOutput switch, however none of the listed examples use that switch.

Seen in both dbatools.io documentation and Get-Help Invoke-DbaQuery -Full

**Comment by wsmelton** [comment]
Is this to report a missing example, or do you think the parameter document is sufficient? (Meaning it is a switch so an example is not going to show anything of use other than it being provided in the example call of the command.

> Use this switch to have on the output stream messages too (e.g. PRINT statements). Output will hold the resultset too.

**Comment by JeffRush** [comment]
Either a missing example or thinking the phrase 'see examples for detail' should be removed. It was just funny that I think it only uses that phrase on one item and happens to be one that isn't actually present in any of the examples.
