### ISSUE TITLE
Support Simple Data Protection by Clearing Table Content or Column Content

### ISSUE THREAD

**Issue by headspeak** [sqlcollaborative/dbatools#6652]
### Summary of new feature

The functions "New-DbaDbMaskingConfig" and "Invoke-DbaDbDataMasking" are great to protect user data. But I don't find a way to simply clear (update / set value NULL) the content of column or hole table.
It would be more flexible if the value could be Null or a fixed value which could be defined by parameter.

### Proposed technical details (if applicable)

UPDATE table_name
SET column1 = 'NULL', column2 = value2, ...
WHERE condition;

### Latest version of dbatools as of writing

Tested / Read Version 1.0.99 an 1.0.144

**Comment by sanderstad** [comment]
If we're going to implement this, using the UPDATE statement like proposed is going to a RBAR process which would not be good for the performance.

It would be better to do this set based for the entire column in one go.

The "Actions" in the data masking work set based changing values for an entire column. 

Maybe add another functions to actions like this:

```JSON
{
    "Name": "AdventureWorks2017",
    "Type": "DataMaskingConfiguration",
    "Tables": [
        {
            "Name": "AWBuildVersion",
            "Schema": "dbo",
            "Columns": [
                {
                    "Name": "Database Version",
                    "ColumnType": "nvarchar",
                    "CharacterString": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                    "MinValue": 12,
                    "MaxValue": 25,
                    "MaskingType": "Random",
                    "SubType": "String2",
                    "Format": null,
                    "Deterministic": false,
                    "Nullable": false,
                    "KeepNull": true,
                    "Composite": null,
                    "Action": {
                        "Category": "Column",
                        "Type": "Nullify"
                    }
                }
            ]
        }
    ]
}
```

This could also make it possible to set a certain value which can remove the static value from the row by row updates.
