### ISSUE TITLE
extract OLEDB provider options

### ISSUE THREAD

**Issue by alhandra** [sqlcollaborative/dbatools#6661]
### Summary of new feature
extract oledb providers options

### Proposed technical details (if applicable)

retrieve the needed information via sp_MSset_oledb_prop and then make data available in:
1 - Export-DbaInstance
2 - Get-OledbProviderOptions

For example for oledb provider the option allow_in_process needs to be set

### Latest version of dbatools as of writing
1.0.114

**Comment by wsmelton** [comment]
Is this for exporting linked servers? Or settings that are part of SQL Server somewhere?

Preference is to find this info via SMO first over TSQL.

**Comment by alhandra** [comment]
Hi shawn,It can used by linked server but formally it can also be used with openquery also Regards,-- Hugo Alhandraalhandra@mail.comOn 13/07/20, 18:16 Shawn Melton <notifications@github.com> wrote:

   
  Is this for exporting linked servers? Or settings that are part of SQL Server somewhere? 
  Preference is to find this info via SMO first over TSQL.

**Comment by potatoqualitee** [comment]
Thanks for using `Export-DbaInstance` 🥳  I found the SMO reference and added a command + support for Export-DbaInstance. It will be included in the next release sometime this week.
