### ISSUE TITLE
Export-DbaLogin -ScriptingOptionsObject

### ISSUE THREAD

**Issue by lostsole** [sqlcollaborative/dbatools#6664]
### Summary of new feature

Add Scripting option to enable or add the function as standard,  Check for objects existences. at database level
$options = New-DbaScriptingOption
$options.TargetServerVersion = "Version140"
$options.IncludeIfNotExists = $true
Export-DbaLogin.ps1 -SqlInstance .\DEV01 -FilePath C:\!TreverLocalFiles\Source_Login2017_2.sql -Append -ScriptingOptionsObject $options

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality
Output example of what it does:
`USE master
IF NOT EXISTS (SELECT loginname FROM master.dbo.syslogins WHERE name = 'AD\trevor') CREATE LOGIN [AD\trevor] ......
...
...
USE [TEST]

GO
CREATE USER [AD\trevor] FOR LOGIN [AD\trevor] WITH DEFAULT_SCHEMA=[dbo]
`

What it should do for the database level:
`IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'AD\trevor]')
CREATE USER [AD\trevor]] FOR LOGIN [AD\trevor]] WITH DEFAULT_SCHEMA=[dbo]
GO`

### Latest version of dbatools as of writing

DBAtools 1.0.114 I am using

**Comment by nvarscar** [comment]
Export-DbaLogin doesn't use the scripting engine and it would be hard/impossible to switch to SMO scripting from the way the command is written now without impacting the users.
You can still use
```powershell
Get-DbaLogin ... | Export-DbaScript -ScriptingOptionsObject $options
```
if you need that behaviour.

**Comment by lostsole** [comment]
Hmm, Ok, so I have test that but it does not include the database level users and grants

The get-dbalogin does not include database level logins and grants.

so I guess the Export-DBALogin needs to be updated to add the `IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'***')` When it outputs the same way the it does for the Server level logins

**Comment by nvarscar** [comment]
I was wrong in my assumption that the function doesn't use scripting. It does - but only for users and only to create them. Perhaps, this call could be made using more sane default scripting options that would check for existence by default. That could be PR'ed in, I can't see how it makes things worse.

Also, you can use Export-DbaUser to extract database-level permissions, including role grants, which does support passing the scripting options in.

**Comment by lostsole** [comment]
Thanks,  I did some debugging/testing and found that if This is added( I did this when I was debugging with PowerShell ISE
I manually ran this when debug window landed on line 460 for Export-dbalogins.ps1

`$options = New-DbaScriptingOption;
$options.TargetServerVersion = "Version140";
$options.IncludeIfNotExists = $true;`

After this was run I ran this command to see if the results was what I was looking for:
Original line:
`$server.Databases[$dbName].Users[$dbUserName].Script()`
Changed to this in debug window
`$server.Databases[$dbName].Users[$dbUserName].Script($Options)`

And when I look at the debug window I see : 
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'AD\trevor')
CREATE USER [AD\trevor] FOR LOGIN [AD\trevor] WITH DEFAULT_SCHEMA=[dbo]

PS: still learning how to fork and setup a development environment for DBAtools.io with VSCode and git

**Comment by nvarscar** [comment]
Since you already know where the code can be modified, you're welcome to submit a PR for this feature :) 
Check out these guidelines: 
https://github.com/sqlcollaborative/dbatools/wiki/Your-First-Pull-Request
http://dbatools.io/contribute

**Comment by andreasjordan** [comment]
Hi @lostsole - are you still working on this? Do you need any help with the PR?

**Comment by potatoqualitee** [comment]
Looks like this has been resolved 👍🏼  https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaLogin.ps1#L499
