### ISSUE TITLE
[Bug] Copy-DbaLogin overwrites the OutFile file instead if appending

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#6666]
#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Steps to Reproduce

Copy-DbaLogin -Source $instance -SourceSqlCredential $creds -ExcludeSystemLogins -OutFile "C:\temp\logins.sql"

#### Expected Behavior
file contains all logins
#### Actual Behavior

file contains last login only

**Comment by andreasjordan** [comment]
That's because the "Export-DbaLogin" in executed inside the "foreach ($loginObject in $loginsCollection)" loop but should executed before (or better: instead of) the loop, right?
Are you working the changes?

**Comment by nvarscar** [comment]
That's exactly it :) 
And yes, I'll PR this in when I have a chance.
