### ISSUE TITLE
[Bug] Invoke-QueryRawDatabases and Microsoft.SqlServer.Management.Smo.Server running query on multiply databases

### ISSUE THREAD

**Issue by mooock** [sqlcollaborative/dbatools#6667]
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
The core team may close bug reports that do not follow our provided template.

The information we ask for helps to better troubleshoot the report. We release frequently and often, this information helps to resolve the issue more efficiently.
-->

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received
[Get-DbaDatabase]07/15/2020 19:11:02 - Script failed System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: [19:11:02][Invoke-QueryRawDatabases] Failure | Method invocation failed because [Microsoft.SqlServer.Management.Smo.Server] does not contain a method named 'Query'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

#### Steps to Reproduce
If you have confirmed this issue can be reproduced, please provide the exact steps (T-SQL, PowerShell, ext)
Its a bit random, when we receive this error, and i also found a workaround to fix the issues, maybe its not a real bug, but more a design flaw in the script we
used.

a quick summary how this issue happens.
Did a get-database and extracted about 40 databases from the SQL instance

used the invoke-dbaquery with this simple script
            $query = "
            select t.name AS TableName,c.name As ColumnName
            FROM sys.columns c
            INNER JOIN sys.tables t on t.object_id = c.object_id
            and t.type = 'U'
            AND c.name not like 'sys_%'
            AND t.name not like 'l_%'
            AND t.schema_id = SCHEMA_ID('dbo')
            "

used a foreach with [PSCUSTOMOBJECT]
Count = (Invoke-dbaquery $query).count

This could work, and also did sometimes for a while, but sudden stopped running with the above errors. It was very hard to get any sort of output of the error
but did write exceptions to file, and this only happend when running this script from a schedule.
I tried to run the command with Powershell.exe, .Dot ."" & "{}" and also put the script inside a function. 

I could not reproduce it from a ISE, but when running over time it happend a lot of time randomly. so maybe it could be something to do with Garbage collection. or because its running on the SQL server itself
The SQL should have sufficent memory so i don't expect it to run low on memory, as it has 1TB Memory and 40GB free memory.

I did another approach where i instead changed the SQL query to retreive a list of all databases and counts, and then from powershell do a look op, so it only
runs the query once instead of 40 times. in the pscustomobject.

also it could look like it does not load or unload the sql assembly when having many requests. 

I spend about 4 days trying to troubleshoot this. but my knowledge about the internal components  of DBAtools was limited

The query that seems to have fixed the issue is this 

$query = "EXECUTE sp_MSforeachdb
@precommand = 'DROP TABLE IF EXISTS ##Results; CREATE TABLE ##Results
( [Database Name] nvarchar(128),
[Count] INT
)',
@command1 = '
USE [?]
IF ''?'' <> ''master'' AND ''?'' <> ''model'' AND ''?'' <> ''msdb'' AND ''?'' <> ''tempdb''
BEGIN
    INSERT INTO ##Results
    SELECT
        DB_NAME() AS [Database Name],
        count(*) AS [Count]
    FROM sys.columns c
    INNER JOIN sys.tables t on t.object_id = c.object_id
    AND t.type = ''U''
    AND c.name not like ''sys_%''
    AND t.name not like ''l_%''
    AND t.schema_id = SCHEMA_ID(''dbo'')
END
',
@postcommand = 'SELECT * FROM ##Results; DROP TABLE IF EXISTS ##Results;'
GO
"

This seems to work without errors
($Columnscounts | where 'Database_Name' -eq $databasename).count

Before it was this an didnt work correctly
Invoke-dbaquery -sqlinstance localhost -query $query -database $_.databasename

#### Expected Behavior
Return the output without errors

#### Actual Behavior
randomly throw the above error when running from a schedule.

**Comment by nvarscar** [comment]
It looks to me that you're using some kind of custom wrapper around Invoke-DbaQuery to query multiple databases. You haven't posted the full code here so I can only assume what's going on behind the scenes. Here's some suggestions: 

Never import sqlps/sqlserver module in your session (or use any command from that module) before running dbatools. It doesn't play nicely with dbatools. Judging by the error you're getting ("[Microsoft.SqlServer.Management.Smo.Server] does not contain a method named 'Query'."), that's probably what's going on there.

Consider using -EnableException switch instead of changing the WarningPreference, this would be the intended way of handling terminating errors.

The following could help you to track down the issues you're encountering (replace 0 with the relevant error id):
```powershell
$error[0] | Select-Object *
$error[0].Exception  | Select-Object *
$error[0].Exception.InnerException  | Select-Object *
```

PS RE assemblies, Powershell only loads an assembly once upon module import. However, multiple modules might import multiple assemblies, so again, make sure you're not using sqlserver module commands, or any other modules that could import SQL Server SMO libraries.

**Comment by wsmelton** [comment]
> "[Microsoft.SqlServer.Management.Smo.Server] does not contain a method named 'Query'."

This message would indicate that our library did not load properly (`dbatools.dll`). That is where the `Query()` method is added to the SMO Server object.

**Comment by nvarscar** [comment]
Or it did, but then a different smo lib overloaded the classes. 🤔

**Comment by mooock** [comment]
we are using something called Splunk, where it has the ability to to schedule tasks using powershell, and it is also using Cron jobs, so it might be you are right about it could be using some kind of wrapper, that ether overloads something or drops the dll file before the job is done, today where i thought everything was good, the errors was in the log again over a period. on monday i will try to outrule more stuff where i will try using the windows task scheduler instead and output the data to CSV and then use the splunk to only use build in powershell commands. it could be that issue happens when working with dll files.

do you have any experience if it could be related to garbage collection dropping the module? its not that the out is large in any kind. but just read something about powershell and it automatic garbage collector.

i also put up more error logging i will read out over the weekend. i added the error[0] | select * with all the dba tools commands

**Comment by wsmelton** [comment]
@nvarscar SMO does not have a Query() method on any of the classes. The query method we have is basically just a wrapper type we are adding during import in our types. Could have sworn we did this in the dll library though.

Ref: https://github.com/sqlcollaborative/dbatools/blob/development/xml/dbatools.Types.ps1xml

**Comment by nvarscar** [comment]
I never disagreed with that 🙂

**Comment by wsmelton** [comment]
It could be that Splunk is not importing things properly based on the errors. 

I'm not sure if we have other uses that tried to use the module in Splunk or not that may be able to help.

**Comment by nvarscar** [comment]
The dbatools module adds custom methods upon import that are added to SMO "Microsoft.SqlServer.Management.Smo.Server" and "Microsoft.SqlServer.Management.Smo.Database" classes, and `.Query()` is one of them. If you see this error, it means that the custom methods are no longer present when calling said classes. It could happen due to the following reasons:
* dbatools module import failure - but that would mean that you'd get that error right of the bat, and not in the middle of a loop
* some other module is loading a different version of SMO that has now overridden the ones imported by dbatools, and which no longer have the custom methods.

$error debug command would help you to find the exact line of code where it breaks.

**Comment by mooock** [comment]
The only commands i use is.
Get-DbaDbSpace
Invoke-DbaQuery
Get-DbaDatabase

and combine them with some Microsoft queries to diagnose to store information from SQL about different metrics, so its not any advanced script.

but the scheduler will be running some of the commands at the same time. where it might be loading the modules multiply times. i start each script with import dbatools, and have 7 ps scripts running a query each with output to a PSCUSTOMOBJECT. 

is there any command i can do in each script to verify if the dbatools dll are loaded while the script runs. thinking of doing a test and output to a file, to see when stuff goes wrong

**Comment by mooock** [comment]
> The dbatools module adds custom methods upon import that are added to SMO "Microsoft.SqlServer.Management.Smo.Server" and "Microsoft.SqlServer.Management.Smo.Database" classes, and `.Query()` is one of them. If you see this error, it means that the custom methods are no longer present when calling said classes. It could happen due to the following reasons:
> 
> * dbatools module import failure - but that would mean that you'd get that error right of the bat, and not in the middle of a loop
> * some other module is loading a different version of SMO that has now overridden the ones imported by dbatools, and which no longer have the custom methods.
> 
> $error debug command would help you to find the exact line of code where it breaks.

Thanks for all the value information. i really was stuck to day, and didn't know what next to try to get to the end of this issue.

would it make sense to maybe unload the module after each script? just to try something out

**Comment by nvarscar** [comment]
Unloading a module won't really help because the libs can't be unloaded without restarting the powershell process.

> some Microsoft queries to diagnose to store information from SQL about different metrics

Is it SQL queries or Powershell code?

> is there any command i can do in each script to verify if the dbatools dll are loaded while the script runs

You can validate if dbatools classes are loaded by trying to use one of the classes it comes with
```
[Sqlcollaborative.Dbatools.Utility.DbaTime]'11:00'
[Sqlcollaborative.Dbatools.Configuration.ConfigurationHost]::Configurations
```

**Comment by mooock** [comment]
The Queries are done as i wrote.
where i do  $Query01 = "T-SQL"
Invoke-dbaquery $query01
some of the queries output a single output about memory and such. other do output of memory related, but everything as T-SQL. and one was used with get-dbadatabase and a foreach using invoke-dbaquery $query -database $_.database.

but from all your experience it could seems like its more a problem with how the splunk wrapper runs the modules. as i was not able to get the errors just from a ISE even by running the scripts multiply times.

**Comment by mooock** [comment]
Hallo again. this morning i got a lot more from the logs, after adding your suggestions for logging. and also found the part of how Splunk is executing scripts.

I have added the two scripts the log shows, It looks like the splunk is just using a Invoke-Expression when looking at line 840, and for my script its just the get-databases that fails, and might be because of the assembly is not loaded correctly. 

[Get-DbaDatabase]07/18/2020 02:00:05 - Script failed @{PSMessageDetails=; Exception=System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: [02:00:05][Invoke-QueryRawDatabases] Failure | Method invocation failed because [Microsoft.SqlServer.Management.Smo.Server] does not contain a method named 'Query'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Get-Databasestats<Begin>(Closure , FunctionContext ); TargetObject=; CategoryInfo=OperationStopped: (:) [Write-Message], ActionPreferenceStopException; FullyQualifiedErrorId=ActionPreferenceStop,Sqlcollaborative.Dbatools.Commands.WriteMessageCommand; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.114\allcommands.ps1: line 83550
at Invoke-QueryRawDatabases, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.114\allcommands.ps1: line 21644
at Get-DbaDatabase<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.114\allcommands.ps1: line 21647
at Get-Databasestats<Begin>, C:\Program Files\SplunkUniversalForwarder\etc\apps\Netcompany\Bin\Get-Databasestats.ps1: line 53
at <ScriptBlock>, C:\Program Files\SplunkUniversalForwarder\etc\apps\Netcompany\Bin\Get-Databasestats.ps1: line 102
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1
at executeJob, C:\Program Files\SplunkUniversalForwarder\bin\splunk-powershell-common.ps1: line 840
at <ScriptBlock>, <No file>: line 36; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
[Powershell scripts.zip](https://github.com/sqlcollaborative/dbatools/files/4945912/Powershell.scripts.zip)

**Comment by mooock** [comment]
I can see from the log i added to the script, that i starts failing a lot of times, and suddenly it starts to work everytime.
[DBstatsDebug.txt](https://github.com/sqlcollaborative/dbatools/files/4945965/DBstatsDebug.txt)

It could look like its using PSexec to execute the scripts, as i found an article were this was mentioned. I will try to do some similar tests with psexec to see if i can reproduce the issue

If splunk is running as system user, do this:

 psexec -i -s '"%SystemRoot%\System32\Windows\PowerShell\v1.0\powershell.exe -file "C:\Program Files\SplunkUniversalForwarder\bin\scripts\RESENDREQUEST.ps1"'
If splunk is running as another user, do this:

runas /noprofile /env /user:domain\username '"%SystemRoot%\System32\Windows\PowerShell\v1.0\powershell.exe -file "C:\Program Files\SplunkUniversalForwarder\bin\scripts\RESENDREQUEST.ps1"'
