### ISSUE TITLE
Copy-dbaSsisCatalog

### ISSUE THREAD

**Issue by wondisha** [sqlcollaborative/dbatools#6675]
I was trying to export SSIS package from one server to another,Have different folders but I only need to move one project and run 
"Copy-dbaSsisCatalog -Source sql01 -destination SQL02 -project XYZ -whatif",
While I need to copy only XYZ ,but the whatif result shows me that it creates all the folders and deplying ,why it doesnt take only what I need.

**Comment by wsmelton** [comment]
Please provide the WhatIf output that you are referencing.

Do note that the we no longer have any primary contributors that work with SSIS to maintain this command. It has a few other issues and high probability it will be removed in future versions.

**Comment by wondisha** [comment]
> Please provide the WhatIf output that you are referencing.
> 
> Do note that the we no longer have any primary contributors that work with SSIS to maintain this command. It has a few other issues and high probability it will be removed in future versions.

**Comment by wondisha** [comment]
The Whatif out put was.I have more than projects on SSIS catalog and needed only one project to copy but it copies all the projects to the destination,anyway I did it with visual studio .thanks
