### ISSUE TITLE
[Bug] Reset-DbaAdmin Cannot connect to WMI on  or SQL Service does not exist. Check permissions, firewall and SQL Server running status.

### ISSUE THREAD

**Issue by suankan** [sqlcollaborative/dbatools#6678]
### Environmental information

```
PowerShell Version        : 5.1.14393.3471
dbatools latest installed : 1.0.114
Culture of OS             : en-US
```
#### SQL Server:

```sql
select @@VERSION
Microsoft SQL Server 2016 (SP2-CU13) (KB4549825) - 13.0.5820.21 (X64)   May 22 2020 07:24:35   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
select @@LANGUAGE
us_english
```

### Report

I've created a new EC2 instance based on AMI ami-051d2ff051ccdb96e

RDP'ed on the server as Administrator.

Installed latest dbatools via:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Install-Module dbatools
```

Open Windows PowerShell.

Then tried to execute `Reset-DbaAdmin`:

```
PS C:\Users\Administrator> Reset-DbaAdmin -SqlInstance $env:computername -Login sa
Please enter a new password for sa: **********
WARNING: [05:58:09][Reset-DbaAdmin] Cannot connect to WMI on  or SQL Service does not exist. Check permissions,
firewall and SQL Server running status. | The argument is null or empty. Provide an argument that is not null or empty,
 and then try the command again.
```

#### Host used

Freshly installed Windows Server 2016 Datacenter + Microsoft SQL Server 2016.

#### Errors Received

A bit different error is shown if I use param `-EnableException`

```
PS C:\Users\Administrator> Reset-DbaAdmin -SqlInstance $env:computername -Login sa -EnableException
Please enter a new password for sa: **********
The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.114\allcommands.ps1:83574 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (EC2AMAZ-RNG27SM:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Reset-DbaAdmin
```

And this is what I see in `$Error[0] | select *`:

```
PS C:\Users\Administrator> $Error[0] | select *


PSMessageDetails      :
Exception             : System.Exception: The argument is null or empty. Provide an argument that is not null or
                        empty, and then try the command again. --->
                        System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on
                        parameter 'ComputerName'. The argument is null or empty. Provide an argument that is not null
                        or empty, and then try the command again. --->
                        System.Management.Automation.ValidationMetadataException: The argument is null or empty.
                        Provide an argument that is not null or empty, and then try the command again.
                           at System.Management.Automation.ValidateNotNullOrEmptyAttribute.Validate(Object arguments,
                        EngineIntrinsics engineIntrinsics)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                        parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                        funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
                           --- End of inner exception stack trace ---
TargetObject          : EC2AMAZ-RNG27SM
CategoryInfo          : InvalidData: (EC2AMAZ-RNG27SM:String) [], Exception
FullyQualifiedErrorId : dbatools_Reset-DbaAdmin
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.114\allcommands.ps1:
                        line 83574
                        at Reset-DbaAdmin<Process>, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\1.0.114\allcommands.ps1: line 60707
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

The similar error to what I'm getting is mentioned in this issue #6023. 

I first left my comment there, but that issue is closed and seems not getting attention.

#### Steps to Reproduce

See the first paragraph in Report section.

#### Expected Behavior

`Reset-DbaAdmin`  should successfully do its operation 

OR 

if there is some error with parameter `-SqlInstance` it should indicate the reason clearly so that the user would be able to pass a correct parameter.

#### Actual Behavior

`Reset-DbaAdmin` fails and throws unclear error.

**Comment by andreasjordan** [comment]
Have a look at the error message: "Cannot connect to WMI on  or SQL Service does not exist."
The code says: "Cannot connect to WMI on $hostName or SQL Service does not exist."
So $hostName is not set. The failing command is probably "Get-Service -ComputerName $ipaddr -ErrorAction Stop" because $ipaddr is maybe not set aswell.

Here is the code block for reference:

```
    try {
        if ($hostName -eq $env:COMPUTERNAME) {
            $instanceServices = Get-Service -ErrorAction Stop | Where-Object {
                $_.DisplayName -like "*($instanceName)*" -and $_.Status -eq "Running"
            }
            $sqlservice = Get-Service -ErrorAction Stop | Where-Object DisplayName -eq "SQL Server ($instanceName)"
        } else {
            $instanceServices = Get-Service -ComputerName $ipaddr -ErrorAction Stop | Where-Object {
                $_.DisplayName -like "*($instanceName)*" -and $_.Status -eq "Running"
            }
            $sqlservice = Get-Service -ComputerName $ipaddr -ErrorAction Stop | Where-Object DisplayName -eq "SQL Server ($instanceName)"
        }
    } catch {
        Stop-Function -Message "Cannot connect to WMI on $hostName or SQL Service does not exist. Check permissions, firewall and SQL Server running status." -ErrorRecord $_ -Target $instance
        return
    }

    if (-not $instanceServices) {
        Stop-Function -Message "Couldn't find SQL Server instance. Check the spelling, ensure the service is running and try again." -Target $instance
        return
    }

```

The commandlet doesn't have verbose output, so there are two steps: Include verbose output and see where the root cause is.

Maybe here:

```
        foreach ($instance in $SqlInstance) {
            $stepcounter = 0
            $baseaddress = $instance.ComputerName
            # Get hostname

            if ($baseaddress.IsLocalHost) {
                $ipaddr = "."
                $hostName = $env:COMPUTERNAME
                $baseaddress = $env:COMPUTERNAME
            }
```
Because $baseaddress.IsLocalHost is $null because there is no such property. The property is at the $instance-Object, so "if ($baseaddress.IsLocalHost) {" has to be changed to "if ($instance.IsLocalHost) {".

**Comment by andreasjordan** [comment]
Sorry for the wild comment, I just typed while testing...

**Comment by wsmelton** [comment]
This would be around DNS issue because we attempt to resolve the IP and get things like FQDN. 

If you are running this command on the localhost, simply use `localhost` instead of trying to pass in the actual hostname. This will prevent it from trying to use WMI/remote calls to perform the work.

**Comment by andreasjordan** [comment]
Ok, I've set up my lab again, so I could test that:

`Reset-DbaAdmin -SqlInstance localhost` works as Shawn said. And if you change `$baseaddress.IsLocalHost` to `$instance.IsLocalHost` you can even use the computer name like in `Reset-DbaAdmin -SqlInstance $env:computername`

If you want to use it remotely, there are more bugs in this commandlet...

You have to change `$hostName = (Get-WmiObject -Class Win32_NetworkAdapterConfiguration -Filter IPEnabled=TRUE -ComputerName $ipaddr -ErrorAction Stop).PSComputerName` to `$hostName = (Get-WmiObject -Class Win32_NetworkAdapterConfiguration -Filter IPEnabled=TRUE -ComputerName $ipaddr -ErrorAction Stop)[0].PSComputerName` because (at least in my lab) Get-WmiObject returns two objects.

And `$tcp.Connect($hostName, 135)` has to changed to `$tcp.Connect($baseaddress, 135)` because $hostName is not yet filled at this moment.

**Comment by wsmelton** [comment]
This command looks like it has not been updated to our newer functions. It should not be using `Get-WmiObject` as we centralized calls to that with `Get-DbaCmObject`.

**Comment by andreasjordan** [comment]
@wsmelton Do you want to fix the command or should I try?

**Comment by andreasjordan** [comment]
@wsmelton Just found this in line 93:
`[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingWMICmdlet", "", Justification = "Using Get-WmiObject for client backwards compatibilty")]
`
Should this be removed when changing from `Get-WmiObject` to `Get-DbaCmObject` or is this a hint that we should not do this change?

**Comment by wsmelton** [comment]
That is to suppress warnings for PSSA with our test and when PSGallery analyzes our module.
