### ISSUE TITLE
edit the return value of bogus

### ISSUE THREAD

**Issue by headspeak** [sqlcollaborative/dbatools#6682]
### Summary of new feature

Editing the return value of bogus give us the possibility to adapt the result value to special conditions. 

### Proposed technical details (if applicable)

i.e. MAC address:
MACs could be written in 4 formats:
   112233445566
   11:22:33:44:55:66
   11-22-33-44-55-66
   1122.3344.5566

The current result of bogus is 
   11:22:33:44:55:66

If we could edit the result than we can tranform the format.

i.e. hostname:
hostnames in companies are typically build-up of location-id and device-number. (London12345)
By editing a result of bogus it will be possible to alter only the device-number by copy the location-id of the original value into the new value.

i.e. IP-address:
Bogus gives a random IP-address back. It is not possible to limit by an IP-range.
By editing an IP-address it will be possible to overwrite unwanted IP classes, i.e. class A+B
123.123.444.555 => 111.111.444.555

### Latest version of dbatools as of writing

1.0.115

**Comment by sanderstad** [comment]
@headspeak please check the PR below. I believe this will solve your problem
https://github.com/sqlcollaborative/dbatools/pull/6723
