### ISSUE TITLE
Unable to use Copy-DbaDBTableData with Query when referencing a view

### ISSUE THREAD

**Issue by brovoldt** [sqlcollaborative/dbatools#6685]
### Environmental information
PowerShell Version        : 5.1.18362.752
dbatools latest installed : 1.0.114
Culture of OS             : en-US

#### SQL Server:
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) 

us_english

### Report
When trying to use Copy-DbaDbTableData with the Query parameter I get an error saying it can't find the "table" (It is referring to a view) that is in the query but if I run an invoke-DbaQuery with the same query it works.

Unable to use a view as the source table in the Copy-DbaDbTableData Cmdlet 

The table that is listed in the TABLE parameters below (CommandLog) is in the database however it is not used in the processing and is ignored because the QUERY parameter is used however if the TABLE parameter is removed the command will not run at all.

    $UpdatecopyParms = @{
        SqlInstance              = "Server01"
        Destination              = "Server01"
        Database                 = "TestDB"
        Query                    = "SELECT * FROM dbo.vSource"                
        Table                    = "CommandLog"
        DestinationDatabase      = "TestDb"
        DestinationTable         = "Dest_Table"
        BatchSize                = 10000        
        Truncate                 = $True

    }

Copy-DbaDbTableData @updatecopyParms -verbose

Invoke-dbaquery -sqlinstance Server01 -database TestDB -query "SELECT * FROM dbo.vSource"
The Verbose messages look like it should work but I am not sure why it is saying invalid object for the view that is used in the query

#### Host used

- [ ] powershell.exe
- [X] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

VERBOSE: Performing the operation "Truncating table [TestDB].[dbo].[Dest_Table]" on target "[Server01]".
VERBOSE: Performing the operation "Copy data from Query" on target "[Server01]".
VERBOSE: Performing the operation "Writing rows to [TestDB].[dbo].[Dest_Table]" on target "[Server01]".
WARNING: [15:21:57][Copy-DbaDbTableData] Something went wrong | Invalid object name 'dbo.vSource'.
$error[0] | select *

writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: Invalid object name 'dbo.vSource'. ---> System.Data.SqlClient.SqlException: Invalid object name 'dbo.vSource'.
                           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
                           at System.Data.SqlClient.SqlDataReader.get_MetaData()
                           at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)  
                           at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader  
                        ds, Boolean describeParameterEncryptionRequest)
                           at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean&
                        usedCache, Boolean asyncWrite, Boolean inRetry)
                           at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
                           at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
                           at System.Data.SqlClient.SqlCommand.ExecuteReader()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : Server01
CategoryInfo          : NotSpecified: (Server01:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Copy-DbaDbTableData,Stop-Function
ErrorDetails          : Invalid object name 'dbo.vSource'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.114\allcommands.ps1: line 83582
                        at Copy-DbaDbTableData<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.114\allcommands.ps1: line 7217
                        at <ScriptBlock>, <No file>: line 15
PipelineIterationInfo : {0, 1}

#### Steps to Reproduce

*******************SQL SCRIPT***************************

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Source_Feed]') AND type in (N'U'))
DROP TABLE [dbo].[Source_Feed]
GO

CREATE TABLE [dbo].[Source_Feed](
	[Id] [int] NOT NULL,
	[Column1] [nvarchar](50) NULL,
	[Column2] [nvarchar](50) NULL,
	[Value] [float] NULL,
 CONSTRAINT [PK_Source_Feed] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)) ON [PRIMARY]
GO

INSERT INTO dbo.Source_Feed (Id,
                             Column1,
                             Column2,
                             Value)
VALUES (1, N'ABC', N'ABC', 1234.25),
(2, N'DEF', N'DEF', 8594.00),
(3, N'GHI', N'GHI', 4124.12)
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Dest_Table]') AND type in (N'U'))
DROP TABLE [dbo].[Dest_Table]
GO

CREATE TABLE [dbo].[Dest_Table](
	[DestId] [int] NOT NULL,
	[Data] [nvarchar](50) NULL,
	[Value] [float] NULL,
 CONSTRAINT [PK_Dest_Table] PRIMARY KEY CLUSTERED 
(
	[DestId] ASC
)) ON [PRIMARY]
GO

CREATE OR ALTER VIEW [dbo].[vSource]
As
SELECT Id DestId,
       Column1 Data,
       Value
FROM dbo.Source_Feed
WHERE Id IN (1,2)
GO

SELECT *
FROM dbo.vSource

*************************************************************

******* Powershell Script *******

    $UpdatecopyParms = @{
        SqlInstance              = "Server01"
        Destination              = "Server01"
        Database                 = "TestDB"
        Query                    = "SELECT * FROM dbo.vSource"                
        Table                    = "CommandLog"
        DestinationDatabase      = "TestDb"
        DestinationTable         = "Dest_Table"
        BatchSize                = 10000        
        Truncate                 = $True

    }

Copy-DbaDbTableData @updatecopyParms -verbose

Invoke-dbaquery -sqlinstance Server01 -database TestDB -query "SELECT * FROM dbo.vSource"

*********************************************************************

VERBOSE: Performing the operation "Truncating table [TestDB].[dbo].[Dest_Table]" on target "[Server01]".
VERBOSE: Performing the operation "Copy data from Query" on target "[Server01]".
VERBOSE: Performing the operation "Writing rows to [TestDB].[dbo].[Dest_Table]" on target "[Server01]".
WARNING: [15:19:44][Copy-DbaDbTableData] Something went wrong | Invalid object name 'dbo.vSource'.

DestId Data   Value
------ ----   -----
     1 ABC  1234.25
     2 DEF     8594

#### Expected Behavior

I was expecting the data to be copied from the View query to the Destination Table 

#### Actual Behavior

The existing data in the destination table was truncated but no data was moved.

**Comment by jaxnoth** [comment]
You should use Copy-DbaDbViewData for this purpose

**Comment by lancasteradam** [comment]
@brovoldt, the reason for the "Invalid object name 'dbo.vSource'" is that the default connection is to the master db. That is why in the help documentation for the -Query param it mentions to use a 3-part object name. For example, in your scenario above it would be changed to:

Query = "SELECT * FROM TestDB.dbo.vSource"

Let us know if that allows you to move forward.

It makes sense for the default connection to be the -Database param that is passed in rather than a default connection to the master db. It's part of the natural flow of thought when formulating the command line to assume that -Database would be the default source db in use for the -Query param. I'm submitting a PR with that suggested change.

**Comment by andreasjordan** [comment]
I will close this as "no bug" / "works as designed", but you can reopen it if you have further questions.
