### ISSUE TITLE
Get- Test- Set-DbaSpn should be renamed

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#669]
Since those functions are filtering only the SQL related SPN's, 
they should be named
Get- Set- Test-DbaSqlSpn

**Comment by ctrlbold** [comment]
Thanks @PowerDBAKlaas -- Pitt will actually be expanding in the future per dbatools.io/schwifty

**Comment by PowerDBAKlaas** [comment]
adding SSAS, SSIS and SSRS is great, but also SQL, widely defined.

Like Get-DbaSQLService also includes those services, but excludes everything outside the "sql collection".
To make clear a user shouldn't expect all SPN's, but the specific SQL ones.

**Comment by ctrlbold** [comment]
There are plans to go outside of the SQL world as well. Set/Remove currently support non-SQL SPNs, Get will eventually, but Test will likely always be for SQL only (could be wrong, @drewfurgiuele knows more) but that one won't be renamed because it'd be the only one of the bunch.
