### ISSUE TITLE
pii-pattern could not handle regex "not"

### ISSUE THREAD

**Issue by headspeak** [sqlcollaborative/dbatools#6690]
### Environmental information
```powershell
PowerShell Version        : 5.1.14393.3471
dbatools latest installed :
Culture of OS             : de-DE

Development branch is not installed by PowerShellGet:
Get-Module -ListAvailable

[...]
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.115    dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Start-DbaMigration,...
Script     0.4.0      powershell-yaml                     {ConvertTo-Yaml, ConvertFrom-Yaml, cfy, cty}
Script     21.1.18121 sqlserver                           {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvail...
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)   Oct 28 2016 18:17:30   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows 10 Enterprise 2016 LTSB 6.3 <X64> (Build 14393: ) 
```

```sql
us_english
```

### Report

If you use an own pattern.json to not replace not only NULL but also a special string then the regex pattern with "not" is ignored.
i.e. "((?!Napa).)*"

#### Host used

- [ x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

- [ ] Still buggy in powershell.exe

#### Errors Received

non

#### Steps to Reproduce

1. Database: AdventureWorks2014

2, new pattern file: pii-NOTpattern.json

[
    {
        "Name": "NotName",
        "Category": "Personal",
        "Country": "All",
        "CountryCode": "All",
        "Pattern": "((?!Napa).)*",
        "Description": "",
        "MaskingType": "Internet",
        "MaskingSubType": "Mac"
    }
]

3. new PS script: NOTpatternTest.ps1

$Instance = [System.Net.Dns]::GetHostName() #Hostname
$DB = "AdventureWorks2014"

$MyPath =  $PSScriptRoot
$NotPattern = "$MyPath\pii-NOTpattern.json"

# Table Column
$mask = New-DbaDbMaskingConfig `
  -SqlInstance $Instance -Database $DB -Path $MyPath `
  -ExcludeDefaultPattern -PatternFilePath $NotPattern `
  -Table Address `
  -ExcludeDefaultKnownName 
Invoke-DbaDbDataMasking `
  -SqlInstance $Instance -Database $DB -FilePath $mask `
  -Column AddressLine1 `
  -Confirm:$false

#### Expected Behavior

I expect that NULL and all cells containing "Napa" will be ignored and not replaced.

#### Actual Behavior

Cells containing "Napa" are replaced.

**Comment by sanderstad** [comment]
The point for this command is to find data that matches the regex strings. 

As far as I know there is not an easy option to know if a regex contains a not or not and generate an if statement based on that outcome.
