### ISSUE TITLE
extend test-dbaLastBackup with -MaxTransferSize -BufferCount 

### ISSUE THREAD

**Issue by Fiander** [sqlcollaborative/dbatools#6694]
I am using the function test-dbaLastBackup to test my backups 24/7 on a test server. And without these changes the server is slow.
These changes allow me to use -maxtransfersize 4128768 -buffercount = 100 settings for the restore action, and by this gain 50% in restore speed.

the parameters should only be for passtrough, and for testing of the parameters sanity the underlaying Restore-DbaDatabase is responsible

**Comment by wsmelton** [comment]
Are you asking for those parameters to be added to the command?

**Comment by Fiander** [comment]
Actually I just wanted to ask if it would be a good idea...
But English is not my native language, so i think i forgot to ask.
