### ISSUE TITLE
[Bug] Function Get-DbaAgentJob - unexcepted behavior with few job steps

### ISSUE THREAD

**Issue by i7slegend** [sqlcollaborative/dbatools#6699]
#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP1-CU5) (KB4040714) - 13.0.4451.0 (X64)   Sep  5 2017 16:12:34   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
us_english
```

### Report

https://github.com/sqlcollaborative/dbatools/blob/a1c053f8a1d1cf9a16a14909f015430cc75415c4/functions/Get-DbaAgentJob.ps1#L123

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Steps to Reproduce

Create job with few (2 or more) steps for database. Next need to call function Get-DbaAgentJob with param $Database which contains name in created early job. Function doesn't return excepted behavior - not include this job.

#### Expected Behavior

Return jobs which contains DatabaseName = $Database

#### Actual Behavior

Doesn't return job if it has 2 or more steps because "-in" operator excepted next params order:
1) value what need to find
2) array

But JobSteps.DatabaseName can be array too.

**Comment by i7slegend** [comment]
Don't see what $Database is array.
JobSteps.DatabaseName can be array (Object[]) too.
Problem not of the operator "-in"...

I suggest something like:
```powershell
$_.JobSteps.DatabaseName | Where-Object { $Database -contains $_ }
```

**Comment by wsmelton** [comment]
`$Database` is the parameter in the command itself, which is declared as a string array.
