### ISSUE TITLE
DbaSpn Features for v1.1

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#670]
### Is this a *feature* OR *bug*:
feature

- Is it possible to check for delegation in the get? should it? We should in Test.
- User reports that he works at place with hosted database servers and their ISP gives them "server101013df5" so they make CNAMEs like sqldev01 to make connecting more human friendly, while DNS management stays... manageable. They add SPNs to support this setup, and it works. CNAMEs generally fail otherwise. @niphlod does that line up with what you figured out?
- A NoDelegation switch to skip delegation for whatever reason, then a section on Set and Remove webpages about this along with links to why it's the recommended from Microsoft.

**Comment by niphlod** [comment]
@ctrlbold : if an SPN is set on the A record that matches the server running SQL Server, connecting to a CNAME of that A results in a kerberos connection, without setting the SPN to the CNAME itself.

**Comment by potatoqualitee** [comment]
all done
