### ISSUE TITLE
[Bug] Powershell Install-dbaMaintenanceSolution parameters don't work

### ISSUE THREAD

**Issue by janszedc** [sqlcollaborative/dbatools#6703]
PowerShell Version        : 5.1.18362.752
dbatools latest installed : 0.9.834
Culture of OS             : en-US

#### SQL Server:

SQL Server 2017 14.0.1000.169

us_english

#### Host used

- [ X ] powershell.exe
- [ X ] ISE
- [ ] VS Code
- [ ] Other (please specify)

- [ X ] Still buggy in powershell.exe

#### Errors Received

No errors... everything completes, but parameters are not applied in the jobs.

[09:17:10][Install-DbaMaintenanceSolution] Installing on server localhost, database Server_Info.
[09:17:10][Install-DbaMaintenanceSolution] Installing MaintenanceSolution.sql.
[09:17:10][Install-DbaMaintenanceSolution] Installation complete.

#### Steps to Reproduce

Simply try and run the install command with any parameters and it will not create the job using anything but the default values.

#### Expected Behavior

I expected it to create the jobs with the parameters specified.

#### Actual Behavior

Jobs were created with default values.

**Comment by tonyfountain** [comment]
I would try this with the latest version of DBATools... you're quite a few versions behind.

**Comment by janszedc** [comment]
> I would try this with the latest version of DBATools... you're quite a few versions behind.

Updated to version 1.0.115... same issue persists.

**Comment by wsmelton** [comment]
Please provide steps to replicate the issue you are having along with verbose console output.

**Comment by janszedc** [comment]
> Please provide steps to replicate the issue you are having along with verbose console output.

#SQL Instance to install Server_Info on
$SQLServer = "localhost"

#Specify a backup path for OLAs maintenance scripts
$OlaBackupLocation = "C:/"
$OlaCleanupTime = 72

#Specify the datafile & logfile path for the DB
$DataFilePath = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Server_Info.mdf'
$LogFilePath = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Server_Info_log.ldf'

#Install OLA Maintenance Solution
Install-DbaMaintenanceSolution -SqlInstance $SQLServer -Database 'Server_Info' -BackupLocation $OlaBackupLocation -CleanupTime $OlaCleanupTime -InstallJobs -ReplaceExisting

The end result: 
![image](https://user-images.githubusercontent.com/49908138/89293296-b2355980-d62b-11ea-87c3-77326eb45caa.png)

**Comment by wsmelton** [comment]
Please remove the file name from both of these paths:

```
$DataFilePath
$LogFilePath
```

They should only point to the folder location you want the MDF and LDF wrote to.

**Comment by janszedc** [comment]
> Please remove the file name from both of these paths:
> 
> ```
> $DataFilePath
> $LogFilePath
> ```
> 
> They should only point to the folder location you want the MDF and LDF wrote to.

Removed and reran, but those params aren't even used in the installation script I pasted.

**Comment by janszedc** [comment]
> I don't write my backups to the root system drive, but yes the command does work properly for me.
> 

Okay so if I run it in a WIndows Powershell session like you it does work, but if I run it in the ISE or a Powershell 7 window it does not work.  That is unfortunate.  I wonder if it will run properly in an Azure Runbook... going to test now.

**Comment by wsmelton** [comment]
Azure Automation runbooks don't support PowerShell 7 so it should work fine.

**Comment by tonyfountain** [comment]
Would this:
`$OlaBackupLocation = "C:/"`
versus this
`$OlaBackupLocation = "C:\"`
make any difference?

**Comment by wsmelton** [comment]
@janszedc I have no issues with PowerShell 7 using the same command provided. It creates the jobs properly.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if this is still an issue with the current version.

**Comment by conseilit** [comment]
Hi Andreas

Same issue here.
Parameters are NULL, running the command from VSCode (Powershell and PowerShell Integrated) and also from PowerShellIse.

Install-DbaMaintenanceSolution -SqlInstance xxxxxx -Database "_DBA" -CleanupTime 504 -InstallJobs -LogToTable -ReplaceExisting

PowerShell 5.1
Dbatools 1.0.153

Using the profiler, all parameters have default values but the default database.

![image](https://user-images.githubusercontent.com/35958968/120789096-6b590e80-c531-11eb-9b60-8e2a0d07d13e.png)

Regards,
Christophe

**Comment by andreasjordan** [comment]
Sorry @conseilit , can you please go into more detail what the problem is?

**Comment by andreasjordan** [comment]
Maybe you have an old version of the script in the local cache. Please use `-Force` to get the latest version from github.

**Comment by conseilit** [comment]
Hum, strange, the Maintenance Solution Repo has not changed for 5 months. And i'm creating many instances / month using teh same ps1 script ....

By the way, using the -Force solves the issue.
Thanks
