### ISSUE TITLE
[Bug] Ghost command: New-DbaDbMailServer function does not exist, need to remove from psd1 and psm1

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#6718]
### Environmental information

PowerShell Version        : 5.1.18362.752
dbatools latest installed : 1.0.115
Culture of OS             : en-US

#### Host used

- [ ] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

`The term 'New-DbaDbMailServer' is not recognized as the name of a cmdlet...` error.

#### Steps to Reproduce

![image](https://user-images.githubusercontent.com/28710553/89461378-b5f6d800-d720-11ea-8ec7-aebd115fa717.png)

ISE shows `New-DbaDbMailServer` as an available command.

See this github search query.
The result is `New-DbaDbMailServer` appears here in the psd1 and psm1, but this function does not exist in the `/functions/` folder.

https://github.com/sqlcollaborative/dbatools/search?q=New-DbaDbMailServer&unscoped_q=New-DbaDbMailServer

The only other reference to `New-DbaDbMailServer` is in this PR:

https://github.com/sqlcollaborative/dbatools/pull/5099

#### Expected Behavior

The command to either be available, or to not even be shown as an option since not real.

#### Actual Behavior

Ghost command shows as a possibility, so trying to run it results in the `The term 'New-DbaDbMailServer' is not recognized as the name of a cmdlet...` error.

**Comment by wsmelton** [comment]
That was put into the PSM1 for preparing a future command that contributor had discussed provided...but never happened.

**Comment by niphlod** [comment]
can be closed, the ghost command has been removed :D
