### ISSUE TITLE
Get-DbaBackupInformation matches database with wrong backup zip file

### ISSUE THREAD

**Issue by DarrenTurrell** [sqlcollaborative/dbatools#6720]
When collecting information about backup files in a directory that also contains a zipped backup file the command will randomly match the zipped backup to any database.
Command run:
Get-DbaBackupInformation -SqlInstance $InstanceName -Path $DefaultPath -DatabaseName $DatabaseName -Anonymise | select -Property database, path

Output from command run x 3, the issue appears in the third run:
PS C:\Users\username> Get-DbaBackupInformation -SqlInstance $InstanceName -Path $DefaultPath -DatabaseName $DatabaseName -Anonymise | select -Property database, path
WARNING: [15:06:34][Read-DbaBackupHeader] Problem found with G:\SQL_Backup\DbName_20190708.zip
. | The media family on device 'G:\SQL_Backup\DbName_20190708.zip' is incorrectly formed. SQL 
Server cannot process this media family.
RESTORE HEADERONLY is terminating abnormally.

Database                         Path                              
--------                         ----                              
7d25b05713be1f3c2053a26133b516cd {896f9417e712f91600ea4f775e74a892}
7d25b05713be1f3c2053a26133b516cd {e4f903cf36e8cf6a043d6f24f66d6e88}
7d25b05713be1f3c2053a26133b516cd {5de8f81183938ad468cc2d70a1ed070d}

PS C:\Users\username> Get-DbaBackupInformation -SqlInstance $InstanceName -Path $DefaultPath -DatabaseName $DatabaseName -Anonymise | select -Property database, path
WARNING: [15:06:38][Read-DbaBackupHeader] Problem found with G:\SQL_Backup\projvppmr_20190708.zip
. | The media family on device 'G:\SQL_Backup\projvppmr_20190708.zip' is incorrectly formed. SQL 
Server cannot process this media family.
RESTORE HEADERONLY is terminating abnormally.

Database                         Path                              
--------                         ----                              
7d25b05713be1f3c2053a26133b516cd {896f9417e712f91600ea4f775e74a892}
7d25b05713be1f3c2053a26133b516cd {e4f903cf36e8cf6a043d6f24f66d6e88}
7d25b05713be1f3c2053a26133b516cd {5de8f81183938ad468cc2d70a1ed070d}

PS C:\Users\username> Get-DbaBackupInformation -SqlInstance $InstanceName -Path $DefaultPath -DatabaseName $DatabaseName -Anonymise | select -Property database, path
WARNING: [15:06:42][Read-DbaBackupHeader] Problem found with G:\SQL_Backup\projvppmr_20190708.zip
. | The media family on device 'G:\SQL_Backup\projvppmr_20190708.zip' is incorrectly formed. SQL 
Server cannot process this media family.
RESTORE HEADERONLY is terminating abnormally.

Database                         Path                              
--------                         ----                              
7d25b05713be1f3c2053a26133b516cd {896f9417e712f91600ea4f775e74a892}
7d25b05713be1f3c2053a26133b516cd {7dec74e342b06ad98b8807d23e80598b}
7d25b05713be1f3c2053a26133b516cd {5de8f81183938ad468cc2d70a1ed070d}

If no database name is specified more results come back and the random zip file moves from database to database. The zip file is a zipped up copy of one of the backups and bares the database name.zip

DbaTools verion 1.0.85
Windows 10

**Comment by nvarscar** [comment]
The issue does not conform to the template, which is one of the reasons why it's unclear what is that you want the command to do here (expected results). I, for one, can't fathom why do you want to get backup information from zip files, which clearly won't be understood by SQL Server.

**Comment by DarrenTurrell** [comment]
Apologies, this is my first use of github I didn't know there was a template. I have made a faux pas.
I don't want to get backups from the zip file,  it was left in the folder by someone else and confuses the tool. I have added code in my script to look for zip files in the folder and throw a warning if it finds them, I wanted you to be aware of the issue though.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nvarscar** [comment]
In this case, this is an expected behaviour. The function is not able to distinct backup files from any other files and if you want to exclude particular files from being processed, you can use `Get-ChildItem` to filter out unneeded files and passing the results to the command:
```powershell
$files = Get-ChildItem my\folder -Recurse -File | Where-Object Name -notlike '*.zip'
Get-DbaBackupInformation ... -Path $files
```

**Comment by wsmelton** [comment]
Yeah @DarrenTurrell SQL Server doesn't actually require a file extension. You can actually take a full backup and put zip as the extension.

So we do not validate file extension for that purpose. We assume any file could be a backup.

**Comment by DarrenTurrell** [comment]
Thank you all.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
