### ISSUE TITLE
[Discussion] Add-DbaAgDatabase + New-DbaAvailabilityGroup / SeedingMode + SharedPath + UseLastBackup

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6724]
As I mentioned some time ago, I would like to revise the commands for availability groups because I see potential for improvement.
This issue will focus on the parameters SeedingMode, SharedPath and UseLastBackup of Add-DbaAgDatabase and (because it is used there) New-DbaAvailabilityGroup).

I will describe different scenarios below:

1. Manual seeding over a shared path:
Parameters needed: SeedingMode = Manual, SharedPath.
Tests: Is SharedPath accessible from primary and all secondaries?
Actions: Full + log backup at primary, restore at secondaries. Try to join database to availablity group.

2. Manual seeding using already taken backup(s):
Parameters needed: SeedingMode = Manual, SharedPath, UseLastBackup.
2.1 Possible implementation A: Only use already taken backup(s), fail if more backups would be needed.
Tests: Is SharedPath accessible from all secondaries?
Actions: Restore database from shared path (full [+ diff]? + log). Try to join database to availablity group.
2.2 Possible implementation B: Use already taken backup(s), create additional log backup if needed.
Tests: Is SharedPath accessible from primary and all secondaries?
Actions: Restore database from shared path (full [+ diff]? + log). Try to join database to availablity group. If there is a message that the database is too far behind (message_id 1408 or 1409), take a log backup at primary and restore at secondaries.

3. Automatic seeding:
Parameters needed: SeedingMode = Automatic.
Tests: Is instance version 2016 or newer?
Actions: Try to join database to availablity group.

4. Automatic seeding using already taken backup(s):
Parameters needed: SeedingMode = Automatic, SharedPath, UseLastBackup.
Tests: Is instance version 2016 or newer? Is SharedPath accessible from all secondaries?
Actions: Restore database from shared path (full [+ diff]? + log). Try to join database to availablity group.

General test in all scenarios: Is the database in full recovery mode?

There may be more scenarios and I'm sure I've forgotten some aspects, so let's start with the discussion ...

**Comment by wsmelton** [comment]
It #2 will also require validating the last backup is located in the SharedPath, if not it then has to be copied. I would assume the better path is to simply depend on the path of the last backup and not worry about SharedPath at all.

On #4 SQL Server will take the backups for you so why would we need to double that because we can't force SQL Server to use them?

**Comment by andreasjordan** [comment]
On (2): What if I don't have a shared path? I could take the backups on the primary, copy them to the secondary or mount the san storage to the secondary and then let Add-DbaAgDatabase do the restore - then I don't have a valid backup history to use. But maybe that leads to a new scenario (5) "Just join the database to the availability group after the user had taken care of backup and restore". That may also be used by someone who uses a professional backup solution to do backup and restores. And this scenario is possible with the SSMS Wizard.

On (4): Does SQL Server takes a real backup during automatic seeding? It sure transfers all pages from primary over to the secondary via the link between the endponts. The "mixed mode" is described here: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/automatic-seeding-secondary-replicas I quote: 'Combine backup and restore with automatic seeding: It is possible to combine the traditional backup, copy, and restore with automatic seeding. In this case, first restore the database on a secondary replica including all available transaction logs. Next, enable automatic seeding when creating the availability group to "catch up" the secondary replica's database [...]'

**Comment by wsmelton** [comment]
(2) that would be my general assumption as well, and in most environments, I took care of backup/restore process myself and then just joined the database to the AG. The Add command should take care of just joining, but recall we did have a few issues that popped up where it was not working correctly.

(4) Keywords are "it is possible", doesn't mean it would be done. If you propose to have AutomaticSeeding be one of two things:
1. Automatic Seeding - just join the replica and set seed mode to automatic
2. Automatic Seeding - do manual seeding first, join replica, and then enable automatic seeding mode.

How will you differentiate between each scenario with the parameters, **, and** make it clear to the user what the process is?

**Comment by andreasjordan** [comment]
I have another scenario: Manual seeding without providing the parameter SharedPath. Should that continue to work?

**Comment by wsmelton** [comment]
Depends on what other parameters are provided.

**Comment by andreasjordan** [comment]
> Depends on what other parameters are provided.

`Add-DbaAgDatabase -SqlInstance $instance -AvailabilityGroup $agname -Database $dbname`

**Comment by andreasjordan** [comment]
> On (2): What if I don't have a shared path? I could take the backups on the primary, copy them to the secondary or mount the san storage to the secondary and then let Add-DbaAgDatabase do the restore - then I don't have a valid backup history to use. But maybe that leads to a new scenario (5) "Just join the database to the availability group after the user had taken care of backup and restore". That may also be used by someone who uses a professional backup solution to do backup and restores. And this scenario is possible with the SSMS Wizard.

There is already an open issue for the scenario (5):
https://github.com/sqlcollaborative/dbatools/issues/6420 (Add joinonly flag to Add-DbaAgDatabase)

**Comment by wsmelton** [comment]
This would equate to join only...

```
Add-DbaAgDatabase -SqlInstance $instance -AvailabilityGroup $agname -Database $dbname
```

**Comment by andreasjordan** [comment]
> This would equate to join only...
> 
> ```
> Add-DbaAgDatabase -SqlInstance $instance -AvailabilityGroup $agname -Database $dbname
> ```

At the moment, this would run backup and restore using the default backup path:

https://github.com/sqlcollaborative/dbatools/blob/5e988826581f05cbfcc281bbbea52930a325ef72/functions/Add-DbaAgDatabase.ps1#L231-L233
https://github.com/sqlcollaborative/dbatools/blob/5e988826581f05cbfcc281bbbea52930a325ef72/functions/Add-DbaAgDatabase.ps1#L239

With default instance parameters:

```
PS C:\Users\Administrator> Add-DbaAgDatabase -SqlInstance $PrimaryInstance -AvailabilityGroup $AgName -Database AdventureWorks -Verbose
VERBOSE: Performing the operation "Adding availability group [AdventureWorks] to SRV1\SQL2016" on target "SRV1\SQL2016".


ComputerName         : SRV1
InstanceName         : SQL2016
SqlInstance          : SRV1\SQL2016
AvailabilityGroup    : TestAg
Replica              : SRV1
Name                 : AdventureWorks
SynchronizationState : Synchronized
IsFailoverReady      : True
IsJoined             : True
IsSuspended          : False

VERBOSE: [18:52:17][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [18:52:17][Backup-DbaDatabase] 1 database to backup
VERBOSE: [18:52:17][Backup-DbaDatabase] Backup database [AdventureWorks]
VERBOSE: [18:52:17][Backup-DbaDatabase] Creating full backup
VERBOSE: [18:52:17][Backup-DbaDatabase] Building file name
VERBOSE: [18:52:17][Backup-DbaDatabase] Setting filename - 202008091852
VERBOSE: [18:52:17][Backup-DbaDatabase] Building backup path
VERBOSE: [18:52:17][Backup-DbaDatabase] Devices added
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] Fetching history from replicas for db AdventureWorks
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] AvailabilityGroup TestAg has no listener, so skipping fetching history from replicas for db AdventureWorks
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] Processing AdventureWorks
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] Executing sql query on [SRV1\SQL2016].
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: [18:52:18][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [18:52:18][Backup-DbaDatabase] 1 database to backup
VERBOSE: [18:52:18][Backup-DbaDatabase] Backup database [AdventureWorks]
VERBOSE: [18:52:18][Backup-DbaDatabase] Creating log backup
VERBOSE: [18:52:18][Backup-DbaDatabase] Building file name
VERBOSE: [18:52:18][Backup-DbaDatabase] Setting filename - 202008091852
VERBOSE: [18:52:18][Backup-DbaDatabase] Building backup path
VERBOSE: [18:52:18][Backup-DbaDatabase] Devices added
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] Fetching history from replicas for db AdventureWorks
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] AvailabilityGroup TestAg has no listener, so skipping fetching history from replicas for db AdventureWorks
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] Processing AdventureWorks
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] Executing sql query on [SRV1\SQL2016].
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [18:52:18][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: [18:52:18][Add-DbaAgDatabase] Backups still exist on 
VERBOSE: Performing the operation "restoring full and log backups of [AdventureWorks] from [SRV1\SQL2016]" on target "".
VERBOSE: [18:52:18][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [18:52:18][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [18:52:18][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [18:52:18][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [18:52:18][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [18:52:18][Restore-DbaDatabase] Processing DatabaseName - 
VERBOSE: [18:52:18][Format-DbaBackupInformation] Starting
VERBOSE: [18:52:18][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [18:52:18][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Data.mdf 
VERBOSE: [18:52:18][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Data.mdf 
VERBOSE: [18:52:18][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Log.ldf 
VERBOSE: [18:52:18][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Log.ldf 
VERBOSE: [18:52:18][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Data.mdf 
VERBOSE: [18:52:18][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Data.mdf 
VERBOSE: [18:52:18][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Log.ldf 
VERBOSE: [18:52:18][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Log.ldf 
VERBOSE: [18:52:18][Select-DbaBackupInformation] processing diffs
VERBOSE: [18:52:18][Select-DbaBackupInformation] Found LogBaseLsn: 40000000071200001 and FirstRecoveryForkID: 
VERBOSE: [18:52:18][Restore-DbaDatabase] VerifyOnly = False
VERBOSE: [18:52:18][Test-DbaBackupInformation] Testing restore for AdventureWorks
VERBOSE: [18:52:18][Test-DbaBackupInformation] VerifyOnly = False
VERBOSE: [18:52:18][Test-DbaLsnChain] Testing LSN Chain
VERBOSE: [18:52:18][Test-DbaLsnChain] Testing LSN Chain - Type Type
VERBOSE: [18:52:18][Test-DbaLsnChain] Passed LSN Chain checks
WARNING: [18:52:18][Test-DbaBackupInformation] Backup File C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\Backup\AdventureWorks_202008091852.bak cannot be read by SRV2\SQL2016. Does the service
 account (COMPANY\SQLServer) have permission?
WARNING: [18:52:18][Test-DbaBackupInformation] Backup File C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\Backup\AdventureWorks_202008091852.trn cannot be read by SRV2\SQL2016. Does the service
 account (COMPANY\SQLServer) have permission?
VERBOSE: [18:52:18][Test-DbaBackupInformation] Verification errors  = 2 - Has not Passed
VERBOSE: [18:52:18][Restore-DbaDatabase]  passed testing
WARNING: [18:52:18][Restore-DbaDatabase] Database AdventureWorks failed testing,  skipping
VERBOSE: [18:52:18][Restore-DbaDatabase] Passing in to restore
VERBOSE: Performing the operation "Joining availability group [AdventureWorks] to SRV1\SQL2016" on target "SRV1\SQL2016".
VERBOSE: [18:52:22][Add-DbaAgDatabase] Error joining database to availability group | Database 'AdventureWorks' does not exist. Make sure that the name is entered correctly.
VERBOSE: [18:52:25][Add-DbaAgDatabase] Error joining database to availability group | Database 'AdventureWorks' does not exist. Make sure that the name is entered correctly.
VERBOSE: [18:52:28][Add-DbaAgDatabase] Error joining database to availability group | Database 'AdventureWorks' does not exist. Make sure that the name is entered correctly.
VERBOSE: [18:52:32][Add-DbaAgDatabase] Error joining database to availability group | Database 'AdventureWorks' does not exist. Make sure that the name is entered correctly.
```

(Ups, there is a bug in the first VERBOSE message)


But if I change the default backup path, it works:

```
$instance = Connect-DbaInstance -SqlInstance $PrimaryInstance
$instance.BackupDirectory = '\\WIN10\SQLServerBackups\'
$instance.Alter()
```

```
PS C:\Users\Administrator> Add-DbaAgDatabase -SqlInstance $PrimaryInstance -AvailabilityGroup $AgName -Database AdventureWorks -Verbose
VERBOSE: Performing the operation "Adding availability group [AdventureWorks] to SRV1\SQL2016" on target "SRV1\SQL2016".


ComputerName         : SRV1
InstanceName         : SQL2016
SqlInstance          : SRV1\SQL2016
AvailabilityGroup    : TestAg
Replica              : SRV1
Name                 : AdventureWorks
SynchronizationState : Synchronized
IsFailoverReady      : True
IsJoined             : True
IsSuspended          : False

VERBOSE: [18:59:55][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [18:59:55][Backup-DbaDatabase] 1 database to backup
VERBOSE: [18:59:55][Backup-DbaDatabase] Backup database [AdventureWorks]
VERBOSE: [18:59:55][Backup-DbaDatabase] Creating full backup
VERBOSE: [18:59:55][Backup-DbaDatabase] Building file name
VERBOSE: [18:59:55][Backup-DbaDatabase] Setting filename - 202008091859
VERBOSE: [18:59:55][Backup-DbaDatabase] Building backup path
VERBOSE: [18:59:55][Backup-DbaDatabase] Devices added
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] Fetching history from replicas for db AdventureWorks
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] AvailabilityGroup TestAg has no listener, so skipping fetching history from replicas for db AdventureWorks
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] Processing AdventureWorks
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] Executing sql query on [SRV1\SQL2016].
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: [18:59:56][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [18:59:56][Backup-DbaDatabase] 1 database to backup
VERBOSE: [18:59:56][Backup-DbaDatabase] Backup database [AdventureWorks]
VERBOSE: [18:59:56][Backup-DbaDatabase] Creating log backup
VERBOSE: [18:59:56][Backup-DbaDatabase] Building file name
VERBOSE: [18:59:56][Backup-DbaDatabase] Setting filename - 202008091859
VERBOSE: [18:59:56][Backup-DbaDatabase] Building backup path
VERBOSE: [18:59:56][Backup-DbaDatabase] Devices added
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] Fetching history from replicas for db AdventureWorks
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] AvailabilityGroup TestAg has no listener, so skipping fetching history from replicas for db AdventureWorks
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] Processing AdventureWorks
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] Executing sql query on [SRV1\SQL2016].
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [18:59:56][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: [18:59:56][Add-DbaAgDatabase] Backups still exist on 
VERBOSE: Performing the operation "restoring full and log backups of [AdventureWorks] from [SRV1\SQL2016]" on target "".
VERBOSE: [18:59:56][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [18:59:56][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [18:59:56][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [18:59:56][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [18:59:56][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [18:59:56][Restore-DbaDatabase] Processing DatabaseName - 
VERBOSE: [18:59:56][Format-DbaBackupInformation] Starting
VERBOSE: [18:59:56][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [18:59:56][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Data.mdf 
VERBOSE: [18:59:56][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Data.mdf 
VERBOSE: [18:59:56][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Log.ldf 
VERBOSE: [18:59:56][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Log.ldf 
VERBOSE: [18:59:56][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Data.mdf 
VERBOSE: [18:59:56][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Data.mdf 
VERBOSE: [18:59:56][Format-DbaBackupInformation]  1 PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Log.ldf 
VERBOSE: [18:59:56][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AdventureWorks2016_Log.ldf 
VERBOSE: [18:59:56][Select-DbaBackupInformation] processing diffs
VERBOSE: [18:59:56][Select-DbaBackupInformation] Found LogBaseLsn: 40000000085600001 and FirstRecoveryForkID: 
VERBOSE: [18:59:56][Restore-DbaDatabase] VerifyOnly = False
VERBOSE: [18:59:56][Test-DbaBackupInformation] Testing restore for AdventureWorks
VERBOSE: [18:59:56][Test-DbaBackupInformation] VerifyOnly = False
VERBOSE: [18:59:56][Test-DbaLsnChain] Testing LSN Chain
VERBOSE: [18:59:56][Test-DbaLsnChain] Testing LSN Chain - Type Type
VERBOSE: [18:59:56][Test-DbaLsnChain] Passed LSN Chain checks
VERBOSE: [18:59:56][Test-DbaBackupInformation] Marking AdventureWorks as verified
VERBOSE: [18:59:56][Restore-DbaDatabase] AdventureWorks passed testing
VERBOSE: [18:59:56][Restore-DbaDatabase] Passing in to restore
VERBOSE: [18:59:57][Invoke-DbaAdvancedRestore] Performing restore action
VERBOSE: [18:59:59][Invoke-DbaAdvancedRestore] Succeeded, Closing Server connection
VERBOSE: [18:59:59][Invoke-DbaAdvancedRestore] Performing restore action
VERBOSE: [18:59:59][Invoke-DbaAdvancedRestore] Succeeded, Closing Server connection
VERBOSE: Performing the operation "Joining availability group [AdventureWorks] to SRV1\SQL2016" on target "SRV1\SQL2016".
ComputerName         : SRV2
InstanceName         : SQL2016
SqlInstance          : SRV2\SQL2016
AvailabilityGroup    : TestAg
Replica              : SRV2
Name                 : AdventureWorks
SynchronizationState : Initializing
IsFailoverReady      : False
IsJoined             : True
IsSuspended          : False
```

So the question is: What is the desired behavior?

**Comment by wsmelton** [comment]
We need to draw a line where if they provide a database and nothing else it should equate to join only.

The only other way around that is if we just create a command for joining the DB only...but that seems a bit redundant and what I think Chrissy was trying to accomplish in the add command.

Alternative would be have a parameter to make it more explicit.. which I think would make it more clear as well. Something like `Add-DbaAgDatabase ... -Database mydb -Join` or `Add-DbaAgDatabase ... -Database mydb -JoinOnly`? I'm fond of the former, looks better and less typing to me. 

Maybe we have Join and include alias of JoinOnly to just have bit more "this is what it means".

**Comment by andreasjordan** [comment]
I thought about it and came up with the following idea: We analyze the situation to find out what to do.

So basically only three paramters are needed; SqlInstance (the primary), Database and AvailabilityGroup.
With SqlInstance and AvailabilityGroup we can get all secondaries (the code is there). In the following I will asume it is only one secondary.
With Database we can check the status of that database on the secondary:
1. If it is there and not in restoring state: fail
2. If it is there and in restoring state: try to join to AG. With automatic seeding this should just always work, with manual seeding the database is maybe to far behind. But that would be the "-Join" or "-JoinOnly" case, without the need for that parameter.
3. If the join fails in manual seeding because of missing log records or if the database is not there on the secondary: Is the default backup path of the primary a network share and does the secondary have access that share (do we have code for that?)? Then run a log backup (missing records) or full and log backup (no database there) and restore and retry the join.

Even if a SharedPath is provided, these steps should run before starting the backup.

If UseLastBackup is provided and the database is not there at the secondary, then get the last backup and restore that on the secondary. But then continue with step 2.
If UseLastBackup is provided and the database is already there at the secondary, I would probably just fail. I would not want to delete the database. We could only continue with step 2, but that would ignore the parameter.

**Comment by andreasjordan** [comment]
Because @potatoqualitee is the original author: Should we wait with the redesign until she has time to join the discussion?

**Comment by potatoqualitee** [comment]
Thank you both. When designing the commands, I basically went based off of SSMS and SMO as I don't have any real world experience with AGs.

I'm always open to accepting changes needed by others but also realize I can be a bit too enthusiastic. I appreciate @wsmelton's moderation and thought 😇 I'm also favoring the `-JoinOnly` param. One concern I do have is that I try to stay with Microsoft's enumeration values and SeedingMode does not have a `SharedPath` value. 

@andreasjordan, these suggestions look like they come from real-world experience. Can you briefly describe the scenarios that prompted the proposal for each?

**Comment by andreasjordan** [comment]
I just pushed some updates to my repo for demos: https://github.com/andreasjordan/demos

I plan to write some blog posts (https://blog.ordix.de/categories/microsoft-sql-server/) about setting up Always On with dbatools. And then I was stopped by some bugs in the commands, so I analysed the code and started to open issues and pull requests.

We have some customers using or planing to use Always On - so I want to show them how easy this is with dbatools.

**Comment by andreasjordan** [comment]
I just finished my demo: https://github.com/andreasjordan/demos/blob/master/AlwaysOn_MultiInstance/02_setup_availability_group___in_small_steps.ps1

**Comment by andreasjordan** [comment]
Just finished a big step in my demo. Divided it into four parts, all filenames start with "02_setup_availability_group_demo_", location is still https://github.com/andreasjordan/demos/tree/master/AlwaysOn_MultiInstance

**Comment by andreasjordan** [comment]
Most of my ideas are now part of #7407, so I will close this.
