### ISSUE TITLE
Add-DbaAgDatabase does not work with non deafult port.

### ISSUE THREAD

**Issue by shaddy02** [sqlcollaborative/dbatools#6731]
### Environmental information

```
PowerShell Version        : 5.1.18362.752
dbatools latest installed : 1.0.115
Culture of OS             : en-US
```

#### SQL Server:

```sql
/* Microsoft SQL Server 2019 (RTM-CU4) (KB4548597) - 15.0.4033.1 (X64)   Mar 14 2020 16:10:35   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) */
```

```sql
/* us_english */
```

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Steps to Reproduce

Run following dbatools command:
```
Add-DbaAgDatabase -SqlInstance $inst1 -AvailabilityGroup AG1 -Database Test -Confirm -SeedingMode Manual -Secondary $inst2 -Verbose -SharedPath \\My\Shared\Path
```

#### Expected Behavior

1. Join Test Database on Primary to AG.
2. Take full and Tail-Log Backup and restore the datbabase with  no recovery on secondary.
3. Join database on secondary to AG.

#### Actual Behavior

Got this error:
```
WARNING: [12:45:01][Get-DbaDbBackupHistory] Error occurred while establishing connection to AG1_LSN1 | The system cannot find the file specified

This is because on line 327 the listener is connecting using default port only. I am using non-default port for the listeners. 
```

**Comment by andreasjordan** [comment]
The issue was discussed on slack.

Get-DbaDbBackupHistory does not work if availability group listener does not use default port.

https://github.com/sqlcollaborative/dbatools/blob/784387f8a066d69fb9c3dba92a3a0468858b4ff7/functions/Get-DbaDbBackupHistory.ps1#L319-L327

**Comment by andreasjordan** [comment]
I will have a look at this tomorrow.

**Comment by wsmelton** [comment]
This has already been reported via #6502 and #6604 

If you believe this is a more unique use-case, please update your post with the reasoning and reopen the issue.

**Comment by andreasjordan** [comment]
Here are some ideas: https://github.com/sqlcollaborative/dbatools/issues/6604#issuecomment-671782948
