### ISSUE TITLE
oh-my-posh reports failure after certain commands

### ISSUE THREAD

**Issue by krokofant** [sqlcollaborative/dbatools#6735]
I wouldn't say this is an issue with dbatools but I would like to get some thoughts on how to reason about this issue.

Running this on PowerShell 7.0.3 on Windows 10.

oh-my-posh checks for errors based on the newly reported errors inside of `$global:error` and a command like Test-DbaMaxMemory throws and catches these errors, but they're still listed in `$global:error`.

Since I very much dislike the command line reporting a failure while everything seems to work okay, how should this be solved? 
Should the error check be changed in oh-my-posh? Are these errors that could be mitigated in dbatools?

```powershell

  ~  $global:error.Count
0

  ~  Test-DbaMaxMemory -SqlInstance localhost

ComputerName     : Foo
InstanceName     : SQLEXPRESS
SqlInstance      : Foo\SQLEXPRESS
InstanceCount    : 1
Total            : 32504
MaxValue         : 4096
RecommendedValue : 25336



 ⨯  ~  $global:error

Exception: C:\Users\krokofant\Documents\PowerShell\Modules\dbatools\1.0.115\allcommands.ps1:83628
 Line |
83628 |          throw $records[0]
      |          ~~~~~~~~~~~~~~~~~
      | Invalid namespace


MethodInvocationException: C:\Users\krokofant\Documents\PowerShell\Modules\dbatools\1.0.115\allcommands.ps1:20739
 Line |
20739 |  …      else { $connection.QueryCimDCOMInstance($cred, $Query, "WQL", $N …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Exception calling "QueryCimDCOMInstance" with "4" argument(s): "Invalid namespace "


Import-Module: C:\Users\krokofant\Documents\PowerShell\Modules\dbatools\1.0.115\internal\scripts\libraryimport.ps1:120
Line |
 120 |              Import-Module $assemblyPath
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load file or assembly 'Microsoft.SqlServer.ServiceBrokerEnum, Version=15.2.0.0,
     | Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The system cannot find the file specified.


  ~ 
```

**Comment by wsmelton** [comment]
Our module does not fully support (nor has it been tested) on PowerShell 7.0.3.  SMO library includes DLLs that are not going to be supported by Microsft in PowerShell 6+ so our module is not going to fully support PowerShell 6+ as well. 

You can run some commands though and they still will hit exceptions but the try/catch blocks are doing what they are meant to in your case and supressing them from writing to the console. We, however, cannot prevent `$global:error` from capturing them though. In that regard PowerShell is doing what it should be doing.
