### ISSUE TITLE
[Bug] - Get-DbaRegisteredServer not returning any result from laptop

### ISSUE THREAD

**Issue by eliassal** [sqlcollaborative/dbatools#6738]
### Environmental information

```
PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.113
Culture of OS             : fr-FR
```

#### SQL Server:

```sql
1- Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)  
2 - Microsoft SQL Server 2016 (SP2-CU10) (KB4524334) - 13.0.5492.2 (X64)   Oct  4 2019 19:14:08   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)   
```

```sql
us_english 
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

When I execute 
Get-DbaRegisteredServer -SqlInstance "SQL2K12" -Group "Production"
NO error on my laptop, I get an empty table, when I execute on the server itself  I get a table filled with the names of the 3 servers

#### Steps to Reproduce

On my laptop, part of the domain as the sql with windows auth, part of  my win login is part of sysadmin I get an empty table

#### Expected Behavior

Get a table with the name of the registered server in the CMS server

#### Actual Behavior

From laptop, table returned is empty

**Comment by gregsauer83** [comment]
I have the same issue. Did you ever find a solution?

**Comment by eliassal** [comment]
Hi gregsauer83, I completely forgot this, I just fired powershell, and all of a sudden it worked correctly :-), thanks to remind me, don't really know what happened

**Comment by wsmelton** [comment]
@gregsauer83 if you have an issue with the command please open a new issue and provide all the requested details.
