### ISSUE TITLE
DBAtools installed through Offline method does not support Update-DbaInstance

### ISSUE THREAD

**Issue by Prabhadevi06** [sqlcollaborative/dbatools#6740]
Get the following error message with the DBAtools that is installed via offline method by downloading the zip and renaming it to DBAtools while trying to patch the SQL server using Update-DbaInstance

WARNING: [16:48:14][Update-DbaInstance] Error while looking for SQL Server installations on azsu-d-db-125.azure.uk.centricaplc.com | C
onnecting to remote server azsu-d-db-125.azure.uk.centricaplc.com failed with the following error message : The WinRM client sent a re
quest to an HTTP server and got a response saying the requested HTTP URL was not available. This is usually returned by a HTTP server 
that does not support the WS-Management protocol. For more information, see the about_Remote_Troubleshooting Help topic.

**Comment by wsmelton** [comment]
@Prabhadevi06 that error is not associated with you installing the module using an offline method. 

Based on the DNS name you have in your error if that server lives in Azure they do not allow HTTP requests to be made over WinRM. That message is telling you why the command cannot be used.
