### ISSUE TITLE
WARNING: [07:12:13][Get-DbaBuildReferenceIndexOnline] Couldn't download updated index from https://sqlcollaborative.github.io/assets/d batools-buildref-index.json

### ISSUE THREAD

**Issue by Prabhadevi06** [sqlcollaborative/dbatools#6741]
We get this issue while trying to update CU14 .Any solutions .The server is behind firewall so cannot access the link.

PS C:\Users\> Get-DbaBuildReference -Build 13.0.5026 -CumulativeUpdate CU13 -Kb KB4549825 -MajorVersion "Microsoft SQL Server 2016" -ServicePack SP2 -SqlCredential Prv-devi0p1 -SqlInstance AZSU-D-AP-125 -Update
WARNING: [07:12:13][Get-DbaBuildReferenceIndexOnline] Couldn't download updated index from https://sqlcollaborative.github.io/assets/d
batools-buildref-index.json
WARNING: [07:12:13][Get-DbaBuildReferenceIndex] Index is stale, last update on: 2020-07-01T00:00:00, try the -Update parameter to fetc
h the most up to date index
WARNING: [07:12:13][Get-DbaBuildReference] Build, Kb, MajorVersion, SqlInstance are mutually exclusive. Please choose one or the other
. Quitting.

**Comment by wsmelton** [comment]
Is there a question or issue.

The warning is by design.

**Comment by Prabhadevi06** [comment]
This is the issue we face while patching the sql servers with CU14

**Comment by wsmelton** [comment]
We cannot offer any fix in that situation. We ship the file with the module so the next release of the module will have the latest version of the file included. I believe we have already added that cu reference.

The only other option is to download the file manually and overwrite the file on your server.

**Comment by wsmelton** [comment]
The path of the local file can be found using this command:

Get-DbatoolsConfigValue -Name 'assets.sqlbuildreference'
