### ISSUE TITLE
Update-DBAInstance

### ISSUE THREAD

**Issue by rscottcovington** [sqlcollaborative/dbatools#6742]
### Environmental information

PowerShell Version        : 5.1.14393.3471
dbatools latest installed : 1.0.115
Culture of OS             : en-US

#### SQL Server:

Microsoft SQL Server 2017 (RTM-CU21) (KB4557397) - 14.0.3335.7 (X64)   Jun 12 2020 20:39:00   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

us_english
#### Host used

- [X ] powershell.exe
- [X ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X ] Still buggy in powershell.exe

#### Errors Received

 
                        System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server DSTV-VTKS-XC7.cdc.gov failed with the following error message : WinRM cannot process 
                        the request. The following error with errorcode 0x80090322 occurred while using Kerberos authentication: An unknown security error occurred.  
                         Possible causes are:
                          -The user name or password specified are invalid.
                          -Kerberos is used when no authentication method and no user name are specified.
                          -Kerberos accepts domain user names, but not local user names.
                          -The Service Principal Name (SPN) for the remote computer name and port does not exist.
                          -The client and remote computers are in different domains and there is no trust between the two domains.
                         After checking for the above issues, try the following:
                          -Check the Event Viewer for events related to authentication.
                          -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.
                         Note that computers in the TrustedHosts list might not be authenticated.
                           -For more information about WinRM configuration, run the following command: winrm help config. For more information, see the about_Remote_Troubleshooting Help topic.
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : OpenError: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Update-DbaInstance,Stop-Function
ErrorDetails          : Connecting to remote server xxxxxxx.cdc.gov failed with the following error message : WinRM cannot process the request. The following error with errorcode 0x80090322 occurred 
                        while using Kerberos authentication: An unknown security error occurred.  
                         Possible causes are:
                          -The user name or password specified are invalid.
                          -Kerberos is used when no authentication method and no user name are specified.
                          -Kerberos accepts domain user names, but not local user names.
                          -The Service Principal Name (SPN) for the remote computer name and port does not exist.
                          -The client and remote computers are in different domains and there is no trust between the two domains.
                         After checking for the above issues, try the following:
                          -Check the Event Viewer for events related to authentication.
                          -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.
                         Note that computers in the TrustedHosts list might not be authenticated.
                           -For more information about WinRM configuration, run the following command: winrm help config. For more information, see the about_Remote_Troubleshooting Help topic.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 83636
                        at Update-DbaInstance<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 74735
                        at <ScriptBlock>, <No file>: line 24
PipelineIterationInfo : {0, 1}

#### Steps to Reproduce

Create an HTTP SPN in Active Directory as follows: HTTP/servername.domain domain\serviceaccountname
Create a list of servers for $servers that DO NOT contain the domain name
Update-DbaInstance -ComputerName $Servers -Path $patchpath -Credential $cred  -Restart -ExtractPath $extractpath

#### Expected Behavior
Expected behavior is a patched server.
The command above works on servers that do NOT have an HTTP SPN in Active Directory. I would expect that we could make this work with servers that also have an HTTP SPN.  Although I have not been able to prove this, I am hopeful that a solution might be to allow Update-DbaInstance an option that would stop Resolve-DbaNetworkName from resolving the server name to servername+domain.  

#### Actual Behavior

WINRM errors related to the HTTP SPN.  When we drop the SPN, Update-DbaInstance works.

**Comment by wsmelton** [comment]
You can attempt this method @rscottcovington ...don't have an environment set up to test.

In your session run the following:

```
Set-DbatoolsConfig -Fullname commands.resolve-dbanetworkname.bypass -Value $true
```

Description of this setting:

```
[5] > Get-DbatoolsConfig -FullName commands.resolve-dbanetworkname.bypass | select FullName, Description | fl


FullName    : commands.resolve-dbanetworkname.bypass
Description : Use input exactly as stated instead of attempting to resolve
```

**Comment by rscottcovington** [comment]
I found that by removing -extractpath, it works.  We would rather have some control over which drive the files go to but it doesn’t seem to work that way when we set this: Set-DbatoolsConfig -Fullname commands.resolve-dbanetworkname.bypass -Value $true .

Scott Covington
Database Administrator
Infrastructure Services Branch (ISB)
Digital Services Office (DSO)
Office of the Chief Information Officer (OCIO)
Office of the Chief Operating Officer (OCOO)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[Title: Digital Services Office (DSO) within the Office of the Chief Information Officer (OCIO) within the Office of the Chief Operating Officer (OCOO)]


To contact the ISB Database personnel: Please submit a ticket<mailto:isbservices@cdc.gov?subject=ISB%20Database%20Admin> to the ISB Help Desk.
*** Please note that SQL 2012 will be shut down early in CY 2020.  Please plan accordingly to migrate your database(s)***



From: Covington, Scott (CDC/OCOO/OCIO)
Sent: Monday, August 17, 2020 1:32 PM
To: 'sqlcollaborative/dbatools' <reply@reply.github.com>
Subject: RE: [sqlcollaborative/dbatools] Update-DBAInstance (#6742)

Thank you!  That looked like it was going to work but then this occurred:

Extraction failed with exit code 112, try specifying a location instead using -ExportPath
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:83628 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Invoke-DbaAdvancedUpdate


Update-DbaInstance : A parameter cannot be found that matches parameter name 'ExportPath'.
At line:1 char:88
+ ... vers -Path $patchpath -Credential $cred  -Restart -ExportPath $extrac ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-DbaInstance], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-DbaInstance

Scott Covington
Database Administrator
Infrastructure Services Branch (ISB)
Digital Services Office (DSO)
Office of the Chief Information Officer (OCIO)
Office of the Chief Operating Officer (OCOO)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[Title: Digital Services Office (DSO) within the Office of the Chief Information Officer (OCIO) within the Office of the Chief Operating Officer (OCOO)]


To contact the ISB Database personnel: Please submit a ticket<mailto:isbservices@cdc.gov?subject=ISB%20Database%20Admin> to the ISB Help Desk.
*** Please note that SQL 2012 will be shut down early in CY 2020.  Please plan accordingly to migrate your database(s)***

**Comment by wsmelton** [comment]
That would be something I think @nvarscar may be able to look into, not sure why the export path is coming up as an error.

**Comment by nvarscar** [comment]
`ExportPath` is a typo and I submitted a PR to fix that.
As for the extraction issue, does `$extractpath` exist on the remote machine and is accessible?

**Comment by rscottcovington** [comment]
Yes, the path is valid and the user has access.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nvarscar** [comment]
The error code seems to suggest that you might not have enough disk space to complete the archive extraction.

> Error code 112 is a Microsoft return code that means the following:
ERROR_DISK_FULL
112 (0x70)
There is not enough space on the disk.
Check the disk space on the machine reporting a 112 error to ensure there is enough space available to complete the deployment.

**Comment by rscottcovington** [comment]
Thank you – that was the issue (disk was short on space).

Before you close the ticket, perhaps someone might consider adding the solution to the WinRM issue I was having to the error output?


Set-DbatoolsConfig -Fullname commands.resolve-dbanetworkname.bypass -Value $true

Thanks for all the support!

Scott Covington
Database Administrator
Infrastructure Services Branch (ISB)
Digital Services Office (DSO)
Office of the Chief Information Officer (OCIO)
Office of the Chief Operating Officer (OCOO)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[Title: Digital Services Office (DSO) within the Office of the Chief Information Officer (OCIO) within the Office of the Chief Operating Officer (OCOO)]


To contact the ISB Database personnel: Please submit a ticket<mailto:isbservices@cdc.gov?subject=ISB%20Database%20Admin> to the ISB Help Desk.
*** Please note that SQL 2012 will be shut down early in CY 2020.  Please plan accordingly to migrate your database(s)***

**Comment by nvarscar** [comment]
Name resolution is based on requests to DNS, and proper computer name is required for the WinRM connections. Name resolution does a reverse lookup of the hosts IP and in a situation when it has multiple A records in the DNS it could lead to picking the wrong option. See 
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Resolve-DbaNetworkName.ps1#L158
I don't think SPN has anything to do with it, it's probably a DNS record issue. If you want to further debug this issue you could run `Resolve-DbaNetworkName servername -Debug` to see how exactly the resolution happens.

**Comment by rscottcovington** [comment]
We proved that an HTTP SPN was the issue because it worked fine when it was dropped from AD.  When it was added back, the WINRM issue came back.

Scott Covington
Database Administrator
Infrastructure Services Branch (ISB)
Digital Services Office (DSO)
Office of the Chief Information Officer (OCIO)
Office of the Chief Operating Officer (OCOO)
Centers for Disease Control and Prevention (CDC)
zwy9@cdc.gov<mailto:zwy9@cdc.gov> | 770-488-5907 office | 470-277-1551 cell | 404-248-4287 fax

[Title: Digital Services Office (DSO) within the Office of the Chief Information Officer (OCIO) within the Office of the Chief Operating Officer (OCOO)]


To contact the ISB Database personnel: Please submit a ticket<mailto:isbservices@cdc.gov?subject=ISB%20Database%20Admin> to the ISB Help Desk.
*** Please note that SQL 2012 will be shut down early in CY 2020.  Please plan accordingly to migrate your database(s)***

**Comment by nvarscar** [comment]
In this case, this seems to be a known Powershell Remoting problem, as described here: https://social.technet.microsoft.com/Forums/windows/en-US/a4c5c787-ea65-4150-8d16-2a19c569a589/enterpssession-winrm-cannot-process-the-request-kerberos-authentication-error-0x80090322?forum=winserverpowershell
It has nothing to do with dbatools at this point, so I'm closing the issue.
