### ISSUE TITLE
[Bug] Get-DbaPermission missing ownership in output

### ISSUE THREAD

**Issue by WHinDenver** [sqlcollaborative/dbatools#6744]
### Environmental information

 
PowerShell Version        : 5.1.14393.3471
dbatools latest installed : 1.0.115
Culture of OS             : en-US

#### SQL Server:

```sql
/* Microsoft SQL Server 2016 (SP2-CU13) (KB4549825) - 13.0.5820.21 (X64)   May 22 2020 07:24:35   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)  */
```

```sql
/* us_english */
```

#### Host used

- [x ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

 Module Get-DbaPermission does not include the owner of the database in its output.  The owner of a database has CONTROL on the database, and therefor should be listed.

#### Steps to Reproduce
create database testdatabase; 
select db.[name], SUSER_SNAME(db.owner_sid),'CONTROL DATABASE' as Permission from sys.databases db where db.name = 'testdatabase'

#### Expected Behavior
I expected to see the database owner listed in the report with CONTROL DATABASE permission

#### Actual Behavior
The owner of the database is not included in the result set

**Comment by wsmelton** [comment]
Please provide the command you are running with parameter examples.

**Comment by WHinDenver** [comment]
get-dbapermission -SqlInstance myserver -database mydatabase -IncludeServerLevel

**Comment by WHinDenver** [comment]
SQL objects have explicit and implicit permissions.  Explicit permissions are granted permissions.  Implicit permissions resolve from ownership.  These permissions can easily be overlooked, but they are very relevant to an auditor or the business owner.

Object ownership grants CONTROL on the object for the owner principal.   Anything non-default in this regard belongs in the result set.

Within a database, objects ownership can be (but usually isn't) transferred to a principal other than the schema.  This can be discovered in sys.all_objects.principal_id

Database ownership is in sys.databases.owner_sid

Schema ownership is in sys.schemas.principal_id

Server principal ownership is in sys.server_principals.owning_principal_id

Any discovered objects should be listed with CONTROL for the owning principal id.

Thanks,
WH

**Comment by wsmelton** [comment]
We welcome your PR to update the query used in the function.
