### ISSUE TITLE
DBATools installed through offline method get error with Index not updated 

### ISSUE THREAD

**Issue by Prabhadevi06** [sqlcollaborative/dbatools#6752]
S C:\Windows\system32> Get-ChildItem -Recurse C:\temp\dbatools | Unblock-File 

 

Import-Module C:\temp\dbatools

 

PS C:\Windows\system32> Get-DbaBuildReference -MajorVersion 2016 -ServicePack 2 -Update
WARNING: [21:25:11][Get-DbaBuildReferenceIndex] Index is stale, last update on: 2020-07-01T00:00:00, try the -Update p
arameter to fetch the most up to date index

 

Build          : 13.0.5026
BuildLevel     : 13.0.5026
CULevel        : 
KBLevel        : 4052908
MatchType      : Exact
NameLevel      : 2016
SPLevel        : SP2
SupportedUntil : 7/14/2026 12:00:00 AM
Warning        : 

 

 

PS C:\Windows\system32> Get-DbaBuildReference -MajorVersion 2016 -CumulativeUpdate 14 -Update
WARNING: [21:25:49][Get-DbaBuildReferenceIndexOnline] Couldn't download updated index from https://sqlcollaborative.gi
thub.io/assets/dbatools-buildref-index.json
WARNING: [21:25:49][Get-DbaBuildReferenceIndex] Index is stale, last update on: 2020-07-01T00:00:00, try the -Update p
arameter to fetch the most up to date index

 

Build          : 13.0.5820
BuildLevel     : 13.0.5820
CULevel        : CU13
KBLevel        : 4549825
MatchType      : Approximate
NameLevel      : 2016
SPLevel        : SP2
SupportedUntil : 7/14/2026 12:00:00 AM
Warning        : 

Have tried to download and save the latest version dbatools.1.0.115 but still get the errors with Index not updated .Could you please help us with the steps to fix this issue.

**Comment by wsmelton** [comment]
We will have a release going out by the end of the week. 

If you need an updated index file prior to that you can download it directly from this repository under bin directory.
