### ISSUE TITLE
[Bug]Copy-DbaDbTableData not copying data to a new table

### ISSUE THREAD

**Issue by daniel-merchant** [sqlcollaborative/dbatools#6753]
### Environmental information
PowerShell Version        : 5.1.14393.3471
dbatools latest installed : 1.0.115
Culture of OS             : en-GB

#### SQL Server:
```sql
Microsoft SQL Server 2016 (SP2-CU13) (KB4549825) - 13.0.5820.21 (X64)   May 22 2020 07:24:35   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
us_english
```

### Report
Running copy-dbadbtabledata from a table in one database with SET options to a table in a different database with different schema creates the table and errors, but does not copy the table data.
The copy completes successfully if run a second time.

#### Host used
- [x] powershell.exe
- [x] ISE
- [x ] VS Code
- [ ] Other (please specify)
- [x] Still buggy in powershell.exe

#### Errors Received
WARNING: [09:25:56][Copy-DbaDbTableData] Unable to determine destination table: [dbo].[test1_archive] | Cannot find the object "dbo.test1" because it does not exist or you do not have permissions.

#### Steps to Reproduce
Two databases on the same SQL server DB1 and DB2, DB1 with a table named test1 with a set option e.g. lock escalation.  DB1 without a table named test1.
```sql
CREATE DATABASE DB1
GO
CREATE DATABASE DB2
go
USE DB1
GO
CREATE TABLE test1 (column1 int)
go
ALTER TABLE test1  SET (LOCK_ESCALATION = AUTO)
INSERT INTO test1 (column1) VALUES (1)
INSERT INTO test1 (column1) VALUES (2)
GO
```

We want to copy data from table test1 on DB1 into a new table called test1_archive on DB2:

```powershell
$params = @{
    SqlInstance         = "SQL01"
    Destination         = "SQL01"
    Database            = "DB1" 
    Table               = "[dbo].[test1]"
    DestinationTable    = "[dbo].[test1_archive]"
    DestinationDatabase = "DB2"
    AutoCreateTable     = $true 
    Query               = "SELECT * FROM [DB1].[dbo].[test1] where column1 < 10" 
    }

    Copy-DbaDbTableData @params 
```

#### Expected Behavior
Expect a new table dbo.test1_archive to be created on database DB2 and populated with the 2 records that exist in dbo.test1 table on database DB1 satisfying the query statement.

#### Actual Behavior
The PowerShell Function fails with error  Cannot find the object "dbo.test1" because it does not exist.
The new table dbo.test1_archive is created successfully on DB2, but it is empty and the data copy has not run.

#### Root Cause & Suggested Resolution
This issue is caused because when the table creation script is generated by the command in copy-dbadbtabledata:
```powershell
$tablescript = $sqltable | Export-DbaScript -Passthru | Out-String
```
it includes the SET options on the table in an ALTER statement:

```sql
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[test1](
        [column1] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[test1] SET (LOCK_ESCALATION = AUTO)
GO
```

The REGEX commands further down the script do a replace on the table name changing dbo.test1 to dbo.test1_archive for the CREATE statement, but NOT the ALTER statement.
In this instance the table create script that is actually run is:
```sql
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[test1_archive](
        [column1] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[test1] SET (LOCK_ESCALATION = AUTO)
GO
```

This causes an error creating the new table because this SQL script is running an ALTER TABLE command on database DB2 for a table that does not exist in that database (dbo.test1).

My workaround was to add an additional REGEX statements for alter commands on the table creation.  I am really not a REGEX expert but if this looks good, I am happy to submit a PR with this change.  It worked for my scenario at least.
```powershell
$rX = "(ALTER TABLE \[$([regex]::Escape($sqltable.Schema))\]\.\[)$([regex]::Escape($sqltable.Name))(\])"
$tablescript = $tablescript -replace $rX, "`$1$($newTableParts.Name)`$2"
```
```powershell
$rX = "(ALTER TABLE \[)$([regex]::Escape($sqltable.Schema))(\]\.\[$([regex]::Escape($newTableParts.Name))\])"
$tablescript = $tablescript -replace $rX, "`$1$($newTableParts.Schema)`$2"
```powershell

Apologies for the lengthy explanation.  I hope this makes sense, this is such a useful function.  :-)

**Comment by andreasjordan** [comment]
I just altered the regex, that should help.
