### ISSUE TITLE
DBATools require continuous internet proxy to be enabled 

### ISSUE THREAD

**Issue by Prabhadevi06** [sqlcollaborative/dbatools#6755]
Hi 

Based on the queries from our Security team ,We  Would want to know if the Internet proxy enabling on servers for DBAtools online installation is one time process (OR )do we need to enable the internet proxy for any other updates or releases that will be released in the DBAtools Module .Please advise if the module needs to be updated whenever there will be updates released as we need to confirm this to our Security team to enable the proxy as our servers are behind firewalls.

The DBAtools will be used for SQL server patching and other Automation processes.

**Comment by wsmelton** [comment]
There is no set schedule on when we do releases at this time. We have a PRs to complete and then we will get a release published.
