### ISSUE TITLE
[Bug] Add-DbaAgDatabase - parameter UseLastBackup does not work if last backup is a full backup

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6765]
This is the relevant code:
https://github.com/sqlcollaborative/dbatools/blob/7b2cb9e80b4d75b093871c7a85d85717a3a5b228/functions/Add-DbaAgDatabase.ps1#L223-L229

If the parameter UseLastBackup is not provided, a full and a log backup are taken to be restored at the secondaries. And yes, a log backup is necessary, just restoring the last full backup is not enough to join the database to the availability group with manual seeding.

If the parameter UseLastBackup is provided, the backups are determined with `Get-DbaDbBackupHistory`. But in case the last backup taken was a full backup, the command only returns this full backup - and the join would fail.
It would be necessary to first find the last log backup and then a backup path including this log backup.

Maybe we need a new parameter for `Get-DbaDbBackupHistory` called something like LastBackupChainForAgJoin to push that algorithm to `Get-DbaDbBackupHistory`.
Or we allow the user to provide an array of `Get-DbaDbBackupHistory` objects. So the user can implement this algorithm.

Or we just check if there is a log backup part of `$allbackups[$db]` and fail the command if not, giving the user the advice to run a log backup first.

**Comment by wsmelton** [comment]
Option 3 is the shortest path. I'd prefer this command not to get into any logic of trying to figure out backup chains. If the backups are not in place then the user needs to handle it.

> Or we allow the user to provide an array of Get-DbaDbBackupHistory objects. So the user can implement this algorithm.

Not sure I follow this one. Why would the user just not restore the database on their own at this point?

**Comment by andreasjordan** [comment]
I agree with you: If the command fails because the last backup is a full backup, the user can just do the restore himself.
And I also think that just checking and failing would be totally ok. And it would only add code to prevent failure and not change or add any logic.
Should I try and submit the code?

**Comment by wsmelton** [comment]
Go ahead.
