### ISSUE TITLE
TempDB is been created with the 2nd query

### ISSUE THREAD

**Issue by tefod-zz** [sqlcollaborative/dbatools#6779]
Hi,
i created differenct functions for initing the connection, creating a tempdb and query some data.
Init:
`$init = Connect-DbaInstance -SqlInstance $server -ConnectTimeout 7200 -LockTimeout 7200`

tempdb:
`Invoke-DbaQuery -SqlInstance $init -Query $qCreateTmpDB -As PSObject -QueryTimeout 1800`

querydata:
`$myresult = Invoke-DbaQuery -SqlInstance $init -Query $Query -As PSObject`

Question: 
~~If I do this commands succesively in the command line, everything is well.~~(Edit: even here, tempdb is deleted)
I put them in three powershell functions. Unfortunately on the 2nd query the tmpdb is been deleted immediately. 
How i can keep the connection alive respectively how I can make a 2nd query where the first instance/connection is not been lost (=tempdb deleted) - in different functions.

Thanks.
Regards...

**Edit/Solution:** Reason for the issue was the wrong data type for the SqlInstance which has been passed to the functions. 
It must be'Microsoft.SqlServer.Management.Smo.SqlSmoObject'

**Comment by wsmelton** [comment]
Not at a machine but you should be able to try explicitly opening the connection on your `$init` object.

Then after your second query, close the connection.

**Comment by tefod-zz** [comment]
I guess, you mean `$init.ConnectionContext.Connect()`
respectively `$init.ConnectionContext.Disconnect()`
Just tried - whatever I try, with the 2nd query the tempdb is been delete. 
`WARNING: [06:57:17][Invoke-DbaQuery] [rexisservicebi.roche.com] Failed during execution | Invalid object name '##MyTempTable'.`
Its only not deleted, if put everything together in one query. In addition if I create the tempdb with HeidiSQL or SMSS - its been kept and my 2nd query runs flawlessly.

Reason for this:
temptable is been created to concat some strings from another table _(FOR XML PATH(''))_ and make an index on this temptable (takes up to 3min). The 2nd query shall run as batch for specific amount of rows where columns from the tempdb is been joined to the resuld. It should not be deleted, hence the 2nd queries is been repeated for another batch.

**Comment by andreasjordan** [comment]
Please try to use a non pooled connection with `-NonPooledConnection`:
```
$init = Connect-DbaInstance -SqlInstance $server -ConnectTimeout 7200 -LockTimeout 7200 -NonPooledConnection
```

**Comment by tefod-zz** [comment]
@andreasjordan thank you very much. Just tried. Does not work unfortunately.
2 = function for creating the temporary table ##FaultMaterial
3 = is getting data - with execution, it seems that #FaultMaterial is been deleted

working variants:
- i put 2 & 3 into one query, but for each query I waste time of 3min for creating ##FaultMaterial
- i create ##FaultMaterial with SMSS or HeidiSQL (disadvantage; i cant automate my tasks)

![1](https://user-images.githubusercontent.com/3308645/92066846-27b75580-eda3-11ea-98cf-d6107cc08c9b.png)
![2](https://user-images.githubusercontent.com/3308645/92066854-2b4adc80-eda3-11ea-8248-0e6021bbf2c6.png)
![3](https://user-images.githubusercontent.com/3308645/92066857-2dad3680-eda3-11ea-803e-b43d6864db7d.png)

**Comment by andreasjordan** [comment]
Sorry to say - I can not reproduce the problem. If you could provide a full functional example (with a setup skript to build and fill all tables), then I can try this on my maschine.

**Comment by tefod-zz** [comment]
Yep - ur right. I was also not able to reproduce the issue during the preparation a clean script for you.
I figured out, that it was related to the functions I use. 
After 4h of trying i found accidently (😄) the cause.
Even the NonPooledConnection is not necessary.

I passed the wrong data type for the SqlInstance to the different functions.  
Instead of 'Microsoft.SqlServer.Management.Smo.SqlSmoObject' I used 'string'.
I dont know why, but this lead to the erase of the TempTable with the 2nd query (get the data).
I am just wondering, why its connecting to the server.

`Param
    (
        [Parameter(Mandatory=$true)]
            [Microsoft.SqlServer.Management.Smo.SqlSmoObject]$Connection
    )
}`

Thank you very much.

**Comment by andreasjordan** [comment]
When you use global temp tables (##FaultMaterial) you can use pooled connections as the table is visible for everybody. If you use local temp tables (#FaultMaterial) you probably need a non-pooled connection to have one session for all the statements.

**Comment by andreasjordan** [comment]
If it works now, please close this issue.

**Comment by andreasjordan** [comment]
I'm glad I could help you.
