### ISSUE TITLE
[Bug] Get-DbaEndpoint - wrong Fqdn on docker (update: and on special network setup)

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6786]
I need your help to analyse an issue I have with availability groups on docker.

The problem is that the Fqdn (full qualified domain name) of the mirroring endpoint returned by Get-DbaEndpoint is not suitable for Add-DbaAgReplica.

I used this demo: https://www.sqlservercentral.com/articles/sql-server-alwayson-with-docker-containers

```
$credential = New-Object -TypeName PSCredential -ArgumentList "sa", (ConvertTo-SecureString -String 'MssqlPass123' -AsPlainText -Force)
$instance = Connect-DbaInstance -SqlInstance localhost:2500, localhost:2600 -SqlCredential $credential

$instance.Name
$instance.ComputerName
$instance.DomainInstanceName
$instance.NetName
(Get-DbaEndpoint -SqlInstance $instance -Type DatabaseMirroring).Fqdn
```

This gives me:
```
localhost,2500
localhost,2600
localhost
localhost
db1
db2
db1
db2
TCP://galloper:5022
TCP://galloper:5022
```

galloper is the name of my laptop. I need `TCP://db1:5022` and `TCP://db2:5022`.

If you use https://dbatools.io/docker/ the first two lines must change to:
```
$credential = New-Object -TypeName PSCredential -ArgumentList "sqladmin", (ConvertTo-SecureString -String 'dbatools.IO' -AsPlainText -Force)
$instance = Connect-DbaInstance -SqlInstance localhost:1433, localhost:14333 -SqlCredential $credential
```

Maybe there is a way to setup my laptop or my docker environment, that the correct Fqdn is returned.

**Comment by wsmelton** [comment]
You have to run the code from within the container, the article referenced is doing the same thing. Our code is running `[System.Net.Dns]::GetHostEntry` and since you run this from your local laptop it will always resolve the `localhost` value returned by SMO to your machine and not the container.

Containers cannot be "remotely" managed for everything like physical VM because you are binding to your local machine to connect to those containers.

**Comment by andreasjordan** [comment]
Okay, this could work - but do we have dbatools inside the container? The goal is to test the dbatools commands related to availability groups against linux systems with SQL Server.

At https://dbatools.io/docker/ @potatoqualitee says: "Next, we’ll setup a sample availability groups. Note that since it’s referring to “localhost”, you’ll want to execute this on the computer running Docker." And that's what I did.

When I change the endpoint of the replica bevor creating the availability group, it works.

**Comment by wsmelton** [comment]
We do not publish a container with the module included...YET 😉 

I do have VS Code Codespaces and Dev Containers configured in the devcontainers branch if you would like to test using that mechanism. This method will put the module on the container (dbatools1).

**Comment by andreasjordan** [comment]
Oh yes, I read about that (on twitter?) - will try that tomorrow.

**Comment by andreasjordan** [comment]
I just realized that this will be a problem at one client where we want to set up a dedicated network for the communication inside the availability group.

Let me explain the planned setup: One network (say 10.0.0.x) as public network for admin work and client connections, a separate network (say 192.168.0.x) just for the two cluster nodes with the SQL Server instances. We plan to create endpoints to listen on 192.168.0.x:5022 while the instances listen on 10.0.0.x:1433.
In the SQL to setup the availability group we would say: 
“CREATE AVAILABILITY GROUP […] FOR REPLICA ON […] WITH (ENDPOINT_URL = N'TCP://192.168.0.x:5022', […]"
Now there is no way to do this with New-DbaAvailabilityGroup, as the URL is dynamically build inside of Get-DbaEndpoint. We would need a parameter -EndpointUrl as an alternative for -Endpoint at Add-DbaAgReplica to get the correct replica smo. The difficult part would be to change New-DbaAvailabilityGroup as we need a parameter that takes all the endpoint URLs and passes them to the corresponding Add-DbaAgReplica.

Maybe this is just an edge case that dbatools are not made for. Then this is just for documentation and I’ll use SQL at that client.

**Comment by wsmelton** [comment]
If you create those endpoints prior to calling `New-DbaAvailabiltyGroup` then you simply pass the name of that endpoint(s) to `-Endpoint` and it should work fine.

**Comment by andreasjordan** [comment]
Sorry, no. The Fqdn is not part of the endpoint object in SQL Server. The Fqdn is dynamically created at runtime of `New-DbaAvailabiltyGroup`.

**Comment by wsmelton** [comment]
> The Fqdn is dynamically created at runtime of New-DbaAvailabiltyGroup

It should not do this then and lookup the configured endpoint for the instance.

**Comment by andreasjordan** [comment]
> > The Fqdn is dynamically created at runtime of New-DbaAvailabiltyGroup
> 
> It should not do this then and instead lookup the configured endpoint for the instance.

Let me repeat this one more time: "The Fqdn is not part of the endpoint object in SQL Server"

**Comment by wsmelton** [comment]
> The problem is that the Fqdn (full qualified domain name) of the mirroring endpoint returned by Get-DbaEndpoint is not suitable for Add-DbaAgReplica.

Since there is some level of confusion the way you wrote up this issue please close it and properly follow our template for bug reports. Clearly state what issue you found with `Get-DbaEndpoint`.
