### ISSUE TITLE
Functions around sql agent operators 

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbatools#6790]
While I was making my presentation related to dbatools and dbachecks I had to use SMO to do the following, I'd like to create functions in dbatools for them.

- New-DbaAgentOperator - create new operator
- Copy-DbaAgentOperator - copy to another instance
- Set-DbaAgentOperator - change properties of an existing operator

**Comment by wsmelton** [comment]
We already have [Copy-DbaAgentOperator](https://docs.dbatools.io/#Copy-DbaAgentOperator).

All for the other two commands though 🥳
