### ISSUE TITLE
Import-DbaCsv - rework header parsing

### ISSUE THREAD

**Issue by MarkIannucci** [sqlcollaborative/dbatools#6791]
> The use of split needs to be taken out of the process as a whole. There should be better methods for handling this that don't depend upon string manipulation.

_Originally posted by @wsmelton in https://github.com/sqlcollaborative/dbatools/issues/6763#issuecomment-681973627_

**Comment by MarkIannucci** [comment]
I was doing some more thinking on an approach that may be able to remove the use of split.  I haven't tested this out, but we may be able to pass `$firstline` to [ConvertFrom-Csv](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-csv?view=powershell-5.1) which should be able to remove `-split` from `Import-DbaCsv`

What I'm unsure of with that approach is that we're still using `Get-Content` and I can't tell if we're concerned about the performance implications of Get-Content'ing a large file too.  

@wsmelton , rest of the internet, what do you think?

**Comment by wsmelton** [comment]
Yeah getting the complete file is out of question. The method used to get the first lines will work, it is how that is being processed that needs to be worked on.

In the end of it hinders performance them we will just leave it as-is.

**Comment by MarkIannucci** [comment]
I'm working on an implementation of static columns similar to [the approach mentioned by sk280](https://github.com/sqlcollaborative/dbatools/issues/6676#issuecomment-677988372) a couple of days ago.  The code I'm writing will handle numeric situations as well.  As I do that work, I'll look at switching from `Get-Content` to using a stream reader to read the first line and then passing that to `ConvertFrom-Csv`

In terms of performance measurement, how does dbatools prefer to see that?  Is [Measure-Command](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/measure-command?view=powershell-7) sufficient?

**Comment by wsmelton** [comment]
This issue is not related in any way to the issue you referenced.

**Comment by wsmelton** [comment]
Please restrict your PR to just addressing this issue and not mixing the two as the changes required for both will be hard to review and determine what affected (if any) performance it has.

**Comment by MarkIannucci** [comment]
I reviewed ConvertFrom-CSV to see if I could use it in this case and I did not find a way to break the first line into a sequence of objects using it.  I also looked at using a stream reader in [this commit].(https://github.com/MarkIannucci/dbatools/commit/f75a4f825b1db3b1beffde4203df1d1331b157a6).  The output from measure command showed no difference when reading a 2.9 GB file stored locally on my nvme:

![image](https://user-images.githubusercontent.com/16762974/92070420-33862600-ed69-11ea-9dc5-dcd07c9e139d.png)

![image](https://user-images.githubusercontent.com/16762974/92070461-4698f600-ed69-11ea-8a1e-51a27fa81d73.png)
