### ISSUE TITLE
[Bug] Start-DbaMigration refers to nonexisting flag in help topics: -ExcludeBackupCleanup

### ISSUE THREAD

**Issue by ValentinMirosh** [sqlcollaborative/dbatools#6792]
### Environmental information

Name  : Culture of OS
Value : en-US

Name  : dbatools latest installed
Value : 1.0.115

Name  : PowerShell Version
Value : 5.1.18362.752

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

Microsoft SQL Server 2012 (SP1) - 11.0.3156.0 (X64)   May  4 2015 18:48:09   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor) 

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [y ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

PS C:\WINDOWS\system32> Start-DbaMigration -Source sqlserver1 -Destination sqlserver2 -BackupRestore -ExcludeBackupCleanup -SharedPath \\ourshare\Backups\

Start-DbaMigration : A parameter cannot be found that matches parameter name 'ExcludeBackupCleanup'.
At line:1 char:79
+ ... destination gen19sqlsbox -BackupRestore -ExcludeBackupCleanup -Shared ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-DbaMigration], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Start-DbaMigration

PS C:\WINDOWS\system32>

**Comment by ValentinMirosh** [comment]
We have tried to use dbatools for migration (Start-DbaMigration) and wanted to keep backups created in process, 
but looks like flag -ExcludeBackupCleanup does not work :

PS C:\WINDOWS\system32> Start-DbaMigration -Source sqlserver1 -Destination sqlserver2 -BackupRestore -ExcludeBackupCleanup -SharedPath \\ourshare\Backups\
Start-DbaMigration : A parameter cannot be found that matches parameter name 'ExcludeBackupCleanup'.
At line:1 char:79
+ ... destination gen19sqlsbox -BackupRestore -ExcludeBackupCleanup -Shared ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-DbaMigration], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Start-DbaMigration
PS C:\WINDOWS\system32>

And without -ExcludeBackupCleanup the command does migration well.
I use Version '1.0.115' of module 'dbatools' and didn't find ExcludeBackupCleanup in source file excepts one comment only, no actual usage.
Maybe it was excluded or not added else, maybe it exists in an previous version that we can use.
Thanks ahead.

**Comment by nvarscar** [comment]
Seems like this came from the `$NoBackupCleanup` parameter description in Copy-DbaDatabase and was then mistakenly replaced as ExcludeBackupCleanup during one of the mass-rename activities. It should probably be simply removed from help.

**Comment by ValentinMirosh** [comment]
We want to keep backups created in process and I hoped that this parameter will start to work with developers help instead of be just excluded :)

**Comment by nvarscar** [comment]
You can still use `Copy-DbaDatabase -NoBackupCleanup` for that purpose and exclude Databases from Start-DbaMigration.

**Comment by nvarscar** [comment]
I'm reopening the issue so that we could fix the docs
