### ISSUE TITLE
Return all scanned Pattern from a single field

### ISSUE THREAD

**Issue by SajalBagchi** [sqlcollaborative/dbatools#6801]
### Summary of new feature
Function : Invoke-DbaDbPiiScan

* Current function Invoke-DbaDbPiiScan returns only one row per field(column), for the very first hit it finds in Jason file. For example, If we have a column with data belonging to multiple PII categories (like SSN, Email, Credit Cards), it would be good to return the details for each category as a separate output (3 output for above example). It could return duplicate records so making it an optional parameter could be an idea for this.

### Proposed technical details (if applicable)

* Probably an inner loop with output should do and adding this feature as an optional parameter

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.
1.0.115

**Comment by wsmelton** [comment]
What function are you referring to? Please update the title.

**Comment by SajalBagchi** [comment]
The issue is still there, a table column with both ipv6 and ipv4 address only returns ipv4 as hit hits first in jason file and ipv6 was not reported at all
