### ISSUE TITLE
Some issues with Add-DbaAgReplica and New-DbaAvailabilityGroup

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6803]
While working on #6802 I found some issues:

https://github.com/sqlcollaborative/dbatools/blob/096fb37a13819a49cde834178d08858b82ef09b5/functions/Add-DbaAgReplica.ps1#L98
SqlInstance accepts more than one instance, but that is not possible as there are other parameters that need individual values per replica:
https://github.com/sqlcollaborative/dbatools/blob/096fb37a13819a49cde834178d08858b82ef09b5/functions/Add-DbaAgReplica.ps1#L100
https://github.com/sqlcollaborative/dbatools/blob/096fb37a13819a49cde834178d08858b82ef09b5/functions/Add-DbaAgReplica.ps1#L114
So SqlInstance should be changed to accept only one element.

https://github.com/sqlcollaborative/dbatools/blob/096fb37a13819a49cde834178d08858b82ef09b5/functions/Add-DbaAgReplica.ps1#L121-L124
No, we need both.
We need SqlInstance as the instance for the new replica (we cannot get that from the availability group in InputObject) and we need the availability group in InputObject for the constructor of Smo.AvailabilityReplica.
Or we need a new parameter AvailabilityGroup - what I would prefer so that the command does not need InputObject.

https://github.com/sqlcollaborative/dbatools/blob/096fb37a13819a49cde834178d08858b82ef09b5/functions/New-DbaAvailabilityGroup.ps1#L255
ReadonlyRoutingConnectionUrl has to be different on every replica, so this has to be an array like my new parameter EndpointUrl. In the current implementation, this parameter just does not work and cannot be used.

**Comment by wsmelton** [comment]
InputObject is used to support piping commands together.

**Comment by andreasjordan** [comment]
First of all: I know what InputObject is for - I'm not that new to PowerShell.

But I notice that I have expressed myself misleadingly:
"Or we need a new parameter AvailabilityGroup - what I would prefer so that the command does not need InputObject." 

At the moment, InputObject is necessary, either by piping in from an AG-object or having a parameter -InputObject like here:
https://github.com/sqlcollaborative/dbatools/blob/096fb37a13819a49cde834178d08858b82ef09b5/functions/New-DbaAvailabilityGroup.ps1#L441-L457

What I wanted to say: Having InputObject optional, so be able to say:
```
Add-DbaAgReplica -SqlInstance $newReplica -AvailabilityGroup MyAG
```

But now - writing this - I realize, that I have not thought far enough. With only having the name of the AG we have no way of getting the object because we would still need SqlInstance of one replica. And as -AvailabilityGroup is always just the name of the AG in other commands it would not be good to expect an object here.

That said, we only need to change the test so that it tests both individualy. Because we need both: SqlInstance and InputObject.

**Comment by wsmelton** [comment]
Please create separate issues for each command and do not combine.

**Comment by wsmelton** [comment]
We need issues to be created that are specific. Combining multiple things into one issues dealing with multiple commands is not good management and makes it harder to close PRs. As PRs should not are multiple commands.
