### ISSUE TITLE
[Bug] Setting Agent Schedules and Steps do not function as expected

### ISSUE THREAD

**Issue by pagerwho** [sqlcollaborative/dbatools#6809]
### Environmental information

```powershell
PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.116
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19042: ) (Hypervisor) 
```

```sql
us_english
```

### Report
Using dbatools version 1.0.116 the following issues are observed:

1. Set-DbaAgentSchedule was observed to be unable to update an existing schedule by name to a monthly schedule when provided the parameter -FrequencyType "Monthly" and a FrequencyType with a numeric value (1-31).

Set-DbaAgentSchedule -SqlInstance localhost -Job 'Multi-Step Job' -Schedule 'Monthly Schedule' -FrequencyType Monthly -Disabled -FrequencyRecurrenceFactor 1 -StartDate 20200907 -StartTime 000000 -EndDate 99991231 -EndTime 000000 -FrequencyInterval 3

Running sp_help_job on local instance shows the following for the schedule:

![image](https://user-images.githubusercontent.com/14897050/92351904-d7920900-f0aa-11ea-986d-93bf48bf0d8a.png)

Alternatively running Get-DbaAgentSchedule -SqlInstance localhost -Schedule 'Monthly Schedule' shows:

![image](https://user-images.githubusercontent.com/14897050/92351948-fabcb880-f0aa-11ea-87f2-b22aa8befdb0.png)

2. Set-DbaAgentSchedule and New-DbaAgentSchedule were outputting informational text to the console without context when -Verbose was not passed.

New-DbaAgentSchedule -SqlInstance localhost -Job 'Multi-Step Job' -Schedule 'Monthly Schedule' -FrequencyType Monthly -Disabled -FrequencyRecurrenceFactor 1 -StartDate 20200907 -StartTime 000000 -EndDate 99991231 -EndTime 000000 -FrequencyInterval 1

![image](https://user-images.githubusercontent.com/14897050/92351652-402cb600-f0aa-11ea-893f-c7c4ddbf1fe7.png)

3. Set-DbaAgentJobStep and New-DbaAgentJobStep failed to create a job step when 'AppendToTableLog' was provided in the -Flag parameter.

New-DbaAgentJobStep -SqlInstance localhost -Job 'Job Step Test' -StepId 1 -StepName 'Test Step' -Subsystem TransactSql -Command "SELECT 1" -Database "master" -Flag AppendToTableLog,AppendToJobHistory

![image](https://user-images.githubusercontent.com/14897050/92351285-3ce4fa80-f0a9-11ea-92cf-222ec5da296f.png)

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

**Comment by pagerwho** [comment]
I have a pull request ready for these bugs.

**Comment by wsmelton** [comment]
Please provide steps to reproduce.

**Comment by pagerwho** [comment]
Please have a look at the updated bug report, if you need any additional details to test this let me know.

**Comment by wsmelton** [comment]
I don't see what version of the module you are using?

**Comment by pagerwho** [comment]
Updated, dbatools version is 1.0.116.
