### ISSUE TITLE
Get-DbaAvailabilityGroup not displaying host name

### ISSUE THREAD

**Issue by cmuncan** [sqlcollaborative/dbatools#6813]
### Summary of new feature
There is a warning message when the host is not known but the only thing that it says is 

`WARNING: [11:36:29][Get-DbaAvailabilityGroup] Failure. | No such host is known`

Would it not be possible to echo the value of the host that is attempted being connected to so that you at least get that information output?

### Latest version of dbatools as of writing
current version - 1.0.115

**Comment by andreasjordan** [comment]
This is the connection failing:
```
$server = Connect-SqlInstance -SqlInstance $instance -SqlCredential $SqlCredential -MinimumVersion 11
```

`$instance` is the `$SqlInstance` that you provided to the command. What is your `$SqlInstance`?

**Comment by andreasjordan** [comment]
Good point. Meanwhile you find the info in `$Error[0].TargetObject`.

**Comment by cmuncan** [comment]
I understand that it is the $instance in the case below that would be causing this, but what about when I have an array of 100 instances?  The error is generic and does not specify the particular instance in question which is what I would need.

`$server = Connect-SqlInstance -SqlInstance $instance -SqlCredential $SqlCredential -MinimumVersion 11`

**Comment by andreasjordan** [comment]
Often there is a message: "Error occurred while establishing connection to $instance"

Will open a pull request soon ...

**Comment by wsmelton** [comment]
@cmuncan please complete a bug issue and provide the requested details.

The error message you are seeing is coming from SQL Server and not our command. So we do not have the direct ability to interject values in that string.

**Comment by andreasjordan** [comment]
Sorry, but the "Failure" is definitly from dbatools and can be more detailed. Only "No such host is known" is not from dbatools.
