### ISSUE TITLE
Connect-DbaInstance to docker containers / Trying to get Get-DbaEndpoint to work with docker

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6814]
I did some research today.
I have a lab with virtual maschines WIN10 (windows 10, i run dbatools there locally) and SRV1 (windows server 2016 core)
I have a laptop with docker and these two containers: https://dbatools.io/docker/

I run this on WIN10:

```
$DbaInstance = [DbaInstance[]]('.\SQL2017', 'localhost\SQL2017', 'WIN10\SQL2017', 'WIN10.Company.Pri\SQL2017', 'SRV1\SQL2017', 'SRV1.Company.Pri\SQL2017')
$DbaInstance | Format-Table
$doesNotWork, $DbaInstance = $DbaInstance  # First entry must be deleted
Connect-DbaInstance -SqlInstance $DbaInstance | Format-Table -Property Name, ComputerName, ComputerNamePhysicalNetBIOS, NetName, Platform

<# Output:

ComputerName      InstanceName Port NetworkProtocol IsLocalHost FullName                  FullSmoName               SqlComputerName     SqlInstanceName SqlFullName                
------------      ------------ ---- --------------- ----------- --------                  -----------               ---------------     --------------- -----------                
.\SQL2017         SQL2017         0              NP       False .\SQL2017\SQL2017         NP:.\SQL2017\SQL2017      [.\SQL2017]         [SQL2017]       [.\SQL2017\SQL2017]        
localhost         SQL2017         0             Any        True localhost\SQL2017         localhost\SQL2017         [localhost]         [SQL2017]       [localhost\SQL2017]        
WIN10             SQL2017         0             Any        True WIN10\SQL2017             WIN10\SQL2017             [WIN10]             [SQL2017]       [WIN10\SQL2017]            
WIN10.Company.Pri SQL2017         0             Any        True WIN10.Company.Pri\SQL2017 WIN10.Company.Pri\SQL2017 [WIN10.Company.Pri] [SQL2017]       [WIN10.Company.Pri\SQL2017]
SRV1              SQL2017         0             Any       False SRV1\SQL2017              SRV1\SQL2017              [SRV1]              [SQL2017]       [SRV1\SQL2017]             
SRV1.Company.Pri  SQL2017         0             Any       False SRV1.Company.Pri\SQL2017  SRV1.Company.Pri\SQL2017  [SRV1.Company.Pri]  [SQL2017]       [SRV1.Company.Pri\SQL2017] 

Name                      ComputerName ComputerNamePhysicalNetBIOS NetName Platform
----                      ------------ --------------------------- ------- --------
localhost\SQL2017         WIN10        WIN10                       WIN10   NT x64  
WIN10\SQL2017             WIN10        WIN10                       WIN10   NT x64  
WIN10.Company.Pri\SQL2017 WIN10        WIN10                       WIN10   NT x64  
SRV1\SQL2017              SRV1         SRV1                        SRV1    NT x64  
SRV1.Company.Pri\SQL2017  SRV1         SRV1                        SRV1    NT x64  

#>
```

I run this against the docker containers:
```
$cred = New-Object -TypeName PSCredential -ArgumentList "sqladmin", (ConvertTo-SecureString -String 'dbatools.IO' -AsPlainText -Force)
$DbaInstance = [DbaInstance[]]('localhost', 'localhost:1433', 'localhost:14333')
$DbaInstance | Format-Table
Connect-DbaInstance -SqlInstance $DbaInstance -SqlCredential $cred | Format-Table -Property Name, ComputerName, ComputerNamePhysicalNetBIOS, NetName, Platform

<# Output:

ComputerName InstanceName  Port NetworkProtocol IsLocalHost FullName        FullSmoName     SqlComputerName SqlInstanceName SqlFullName
------------ ------------  ---- --------------- ----------- --------        -----------     --------------- --------------- -----------
localhost    MSSQLSERVER   1433             Any        True localhost       localhost       [localhost]     [MSSQLSERVER]   [localhost]
localhost    MSSQLSERVER   1433             Any        True localhost:1433  localhost,1433  [localhost]     [MSSQLSERVER]   [localhost]
localhost    MSSQLSERVER  14333             Any        True localhost:14333 localhost,14333 [localhost]     [MSSQLSERVER]   [localhost]

Name            ComputerName ComputerNamePhysicalNetBIOS NetName    Platform
----            ------------ --------------------------- -------    --------
GALLOPER        localhost    dockersql1                  dockersql1 NT x64  
localhost,1433  localhost    dockersql1                  dockersql1 NT x64  
localhost,14333 localhost    dockersql2                  dockersql2 NT x64  

#>

```

Should that look like this?
* Platform for docker is "NT x64"
* The full qualified computer name is only in Name in the smo, not in ComputerName

In Get-DbaEndpoint there is this code:
https://github.com/sqlcollaborative/dbatools/blob/8db18ace16c3d23615f88673565b02eaf8a9856d/functions/Get-DbaEndpoint.ps1#L86-L95

Why is there a test `$instance.ComputerName -match '\.'` if ComputerName just never has a domain and so no dot in there?

Ok, Ok, a little bit unsorted, I apologize.

**Comment by wsmelton** [comment]
> Platform for docker is "NT x64"

This is a bug with SMO, already a closed issue discussing this because it won't be fixed by Microsoft.

**Comment by andreasjordan** [comment]
Update for the docker part, because I left out HostPlatform, which shows the expected value: 

```
$cred = New-Object -TypeName PSCredential -ArgumentList "sqladmin", (ConvertTo-SecureString -String 'dbatools.IO' -AsPlainText -Force)
$DbaInstance = [DbaInstance[]]('localhost', 'localhost:1433', 'localhost:14333')
$DbaInstance | Format-Table
Connect-DbaInstance -SqlInstance $DbaInstance -SqlCredential $cred | Format-Table -Property Name, ComputerName, ComputerNamePhysicalNetBIOS, NetName, Platform, HostPlatform

<# Output:

ComputerName InstanceName  Port NetworkProtocol IsLocalHost FullName        FullSmoName     SqlComputerName SqlInstanceName SqlFullName
------------ ------------  ---- --------------- ----------- --------        -----------     --------------- --------------- -----------
localhost    MSSQLSERVER   1433             Any        True localhost       localhost       [localhost]     [MSSQLSERVER]   [localhost]
localhost    MSSQLSERVER   1433             Any        True localhost:1433  localhost,1433  [localhost]     [MSSQLSERVER]   [localhost]
localhost    MSSQLSERVER  14333             Any        True localhost:14333 localhost,14333 [localhost]     [MSSQLSERVER]   [localhost]



Name            ComputerName ComputerNamePhysicalNetBIOS NetName    Platform HostPlatform
----            ------------ --------------------------- -------    -------- ------------
GALLOPER        localhost    dockersql1                  dockersql1 NT x64   Linux       
localhost,1433  localhost    dockersql1                  dockersql1 NT x64   Linux       
localhost,14333 localhost    dockersql2                  dockersql2 NT x64   Linux       

#>
```

**Comment by potatoqualitee** [comment]
hmm, perhaps we should change platform to hostplatform in our output, which is controlled by a file in the xml folder. I'll take a look tonight.

**Comment by wsmelton** [comment]
I would just include the additional property. In the Windows world, the `platform` is a valid value to show x64/x86 properly.

**Comment by wsmelton** [comment]
#6038

As well, that property change was already done it seems in #6291

**Comment by andreasjordan** [comment]
All commands use HostPlatform - so that is ok, I just used the wrong property.

**Comment by andreasjordan** [comment]
I just wonder about the use of ComputerName in Get-DbaEndpoint. Because there you are testing for the dot, but it will never appear there, right?

**Comment by andreasjordan** [comment]
What do you think about this way to detect docker?

```
$cred = New-Object -TypeName PSCredential -ArgumentList "sqladmin", (ConvertTo-SecureString -String 'dbatools.IO' -AsPlainText -Force)
$instance = Connect-DbaInstance -SqlInstance localhost -SqlCredential $cred 
if ( ([DbaInstance]$instance).IsLocalHost -and $instance.ComputerNamePhysicalNetBIOS -ne $instance.ComputerName ) {
    "I think we are on docker, because IsLocalHost is '$(([DbaInstance]$instance).IsLocalHost)' and ComputerNamePhysicalNetBIOS '$($instance.ComputerNamePhysicalNetBIOS)' is different from ComputerName '$($instance.ComputerName)'"
}

```

**Comment by wsmelton** [comment]
Do we really need to support Docker in this manner?

**Comment by wsmelton** [comment]
In the sense that containers deployed in a production environment as pods for AKS or AWS ECS would likely resolve properly.

**Comment by andreasjordan** [comment]
Good question. Let me explain the background. I wanted to use dbatools to setup availability groups in a windows cluster. I found some issues and wanted to improve the commands. The commands are designed for all types of availability groups, the code looks like they should be supported on linux as well. So I wanted to have an environment to test the changes to not break functionality. So I thought about docker. That's why we are here in the first place.

Then I tested this: https://dbatools.io/docker/
I think when this is on the main page of dbatools - it should work. And it does not at the moment. It fails on my maschine and Chrissy reports the same problems. So we should make this work again.

I think that running availability groups outside a windows cluster is an edge case - and we can just not test that. But that would be your decision. I would be really happy to test all the AG commands just on a windows cluster.

On the other hand if you build a good test environment for the AG commands that include pods would be great.

**Comment by wsmelton** [comment]
I think this is something to solve on the Docker side and not directly within our module because there is no viable way to know you are hitting a Linux machine that is a container or Ubuntu 18.04 sitting in AKS. At least from SQL Server's perspective.

I can play with our devcontainer branch and see if I can get something more viable to use with the network setup of a container. I think some DNS magic can be done where it will be resolvable from your local machine but I'll have to check.

The other thing to consider is if we publish our module as a microservice for Docker then all the commands are issued within the network of the container and it looks like any other network with DNS and such. The whole 'localhost,xxxx' goes away.

**Comment by andreasjordan** [comment]
Thanks for investigating this. But keep in mind that there is https://dbatools.io/docker/ out there that says: "You can build an AG with docker - just follow my instructions". Either we get this to work again by changing dbatools, add a "you have to change your network setting / use this docker-compose file / ..." section to the article or delete the article from the webpage.
By the way @potatoqualitee : The "Cleaning up" does not clean up the network - you might want to add that.
And look at the comment from SWARN SINGH on JUNE 8, 2020...

**Comment by wsmelton** [comment]
> But keep in mind that there is https://dbatools.io/docker/ out there that says: "You can build an AG with docker - just follow my instructions". 

That blog post does not make that statement **at all**. It is just a T-SQL Tuesday post from 2019 where Chrissy provided what she learned using the module with containers and provided the steps that she followed.

> delete the article from the webpage

It is a blog post, we don't publish articles like SQL Server Central or IT Today. There is absolutely no reason to take it down as it provides folks a way to see how someone got involved using containers. It's from 2019, things change. Bloggers are not just going to delete their content because something is outdated or could be done differently, that is the process of learning and the way users can see it. We have blog posts from commands that no longer exist or have been completely rewritten; not all of them are pointed at a short URL but we are not going to delete the content of authors just because it may be out of date.

The use of `docker run` is the most common method you will find on almost every blog post in the SQL Community out there where writers are introducing folks to Docker. There are a ton of folks using this method because it is the fastest way to get started, and the easiest to explain in a blog post. However, `docker-compose` is a best practice and provides a more consistent method of building and tearing down what you create with containers. It is growing in popularity, as it should, more and more but folks will still write about using an interactive shell to creating containers. Use of compose and dockerfile files is a stepping stone on how to learn more about how containers are deployed in production environments and with Kubernetes. (That was the purpose of building [this](https://github.com/sqlcollaborative/dbatools/blob/devcontainer/.devcontainer/devcontainer.json). 

Once the branch is finalized and Microsoft allows us access to GitHub Codespaces. I will work on cleaning up things and finalize it all to be published to dev branch. A wiki or blog post will be written up and then we will move that short URL to point to the current content.

**Comment by wsmelton** [comment]
> I just wonder about the use of ComputerName in Get-DbaEndpoint. Because there you are testing for the dot, but it will never appear there, right?

Referencing this:

https://github.com/sqlcollaborative/dbatools/blob/d822f66e496ca478a7da727d2813337576f0946d/functions/Get-DbaEndpoint.ps1#L86-L87

We support the nomenclature of `.` to stand for localhost or the local computer name as SSMS does. So users can pass in `.\myinstance` or just `.` in our commands. I believe that is where that test is coming from. You will see in the output of our DbaInstance type that if you use either of these then `IsLocalHost` will be set to true.

**Comment by wsmelton** [comment]
Referencing the example, my opinion is it is not needed within the `Connect-DbaInstance` function. It is guessing that it will be consistent across the board and not something we can be 100% on. Working with Docker Desktop, there are plenty of commands in our module that are not going to act or work 100% accurately. It is the nature of using that specific development tool.

VS Code provides support for users to remote to containers and puts their scripting experience within the container network. Features of this nature are better suited for providing the right environment for our module to be tested or "played with" when it comes to Docker Desktop.

**Comment by andreasjordan** [comment]
I wanted to try the dot-style, but I don't get it to work, Can you test this on your maschine?
```
[DbaInstance]$SqlInstance = '.\SQL2017'
$SqlInstance.ComputerName  # Output: .\SQL2017
$instance = Connect-DbaInstance -SqlInstance $SqlInstance
```
I get this:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. 
(provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)


But this works:
```
$instance = Connect-DbaInstance -SqlInstance 'localhost\SQL2017'
$instance.ComputerName  # Output: WIN10
```

**Comment by andreasjordan** [comment]
I don't want to implement the docker-test in Connect-DbaInstance, only in Get-DbaEndpoint.

**Comment by wsmelton** [comment]
`Connect-DbaInstance` as a whole has issues and there are various parts of our type logic that are not handling the dot properly. I don't use the nomenclature and not sure we have many that do.

> I don't want to implement the docker-test in Connect-DbaInstance, only in Get-DbaEndpoint.

Oh, either way, it is the same option for the Get function as well.

**Comment by andreasjordan** [comment]
With the current development branch and the new EndpointUrl paramater, I can setup docker AG again:

```
$cred = New-Object -TypeName PSCredential -ArgumentList "sqladmin", (ConvertTo-SecureString -String 'dbatools.IO' -AsPlainText -Force)

$DbaInstance = [DbaInstance[]]('localhost', 'localhost:14333')
$DbaInstance | Format-Table
$server = Connect-DbaInstance -SqlInstance $DbaInstance -SqlCredential $cred
$server | Format-Table -Property Name, ComputerName, ComputerNamePhysicalNetBIOS, NetName, HostPlatform

# New: Get the endpoint URLs, but use NetName
$endpointUrl = foreach ($srv in $server) { 'TCP://' + $srv.NetName + ':' + (Get-DbaEndpoint -SqlInstance $srv -Type DatabaseMirroring).Port }
$endpointUrl

$params = @{
    Primary = "localhost"
    PrimarySqlCredential = $cred
    Secondary = "localhost:14333"
    SecondarySqlCredential = $cred
    Name = "test-ag"
    Database = "pubs"
    ClusterType = "None"
    SeedingMode = "Automatic"
    FailoverMode = "Manual"
    Confirm = $false
    EndpointUrl = $endpointUrl   # New: Use custom endpoint URLs
 }

# execute the command
New-DbaAvailabilityGroup @params

# New: check the result
Get-DbaAgDatabase -SqlInstance $server -AvailabilityGroup test-ag -Database pubs | ft
```

Output is:
![image](https://user-images.githubusercontent.com/66946165/93015880-4f859500-f5bd-11ea-8511-f5af9cac26e1.png)

**Comment by potatoqualitee** [comment]
I'd like to get it to work without the endpointurl. Tonight, I'll be working on `New-DbaEndpoint` and will try to figure out the best approach that works automatically. I imagine I will have to make slight modifications to `Connect-DbaInstance` or one of the EndPoint commands.
