### ISSUE TITLE
Connect-Dbainstance - Error Record / Message to include hostname

### ISSUE THREAD

**Issue by FriedrichWeinmann** [sqlcollaborative/dbatools#6817]
### Summary of new feature

Currently, connection errors via Connect-DbaInstance often do not show what instance it failed to connect to.
This in return means it is not passed on to Stop-Function and shown to the user.

This in turn is a potential issue when processing dozens of instances as it leaves the user wondering, which of them failed.

### Proposed technical details (if applicable)

Have Stop-Function pick up on those cases and automatically modify the message if the message text is only "Failure" and the error record generated from Connect-DbaInstance.

Could change the message from:

```text
Failure. | The Network path could not be found.
```

to:

```text
[server\instance] Connection Failure. | The Network path could not be found
```

### Notes

Would be happy to implement that this weekend.
Do we want to do this?

(No relevant technical drawbacks, central change, need only touch Stop-Function)

**Comment by wsmelton** [comment]
We have more functions using just `-Message "Failure."` then not so it would not take much work for me to go through and update them.

**Comment by potatoqualitee** [comment]
sweet, this is great

**Comment by wsmelton** [comment]
@potatoqualitee do we go ahead and change the 235 references I found to not have the `-Message "Failure."` and would you prefer it be done after Fred implements the change?

**Comment by andreasjordan** [comment]
Maybe together with the change from Connect-SqlInstance to Connect-DbaInstance (#7319)

**Comment by andreasjordan** [comment]
@FriedrichWeinmann Have you had time to work on this? Can I help?
