### ISSUE TITLE
dbatools.io - Connect-DbaInstance - requirements for connection using local user

### ISSUE THREAD

**Issue by ojmucianski** [sqlcollaborative/dbatools#6826]
Dear enthusiast!

I am trying to find out what are the requirements to establish a connection to a remote computer using local NT user (local to the target machine). I have no problem to connect via AD user or the MSSQL login, but when I attempt to do the same using the local user I am getting an error:
The user name or password is incorrect.
```

    At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.78\allcommands.ps1:81899 char:9
    +         throw $records[0]
    +         ~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [], Exception
        + FullyQualifiedErrorId : dbatools_Connect-DbaInstance
```
   which sadly points me nowhere. Unfortunately there is nothing on the official documentation website which would detail what do I need to set up on the OS level to allow such a connection. I bought the only official book I found on this topic "Learn dbatools in a Month of Lunches", but no luck there either.
Few words on my setup. Both client and remote machine are windows based, I can connect to the client using the RDC and they are not domain joined.
What I am looking for are requirements/setup needed in order to allow local NT users to work in this scenario.
My PS looks simply like this:

`    Connect-DbaInstance -SqlInstance 'test_instance' -SqlCredential 'test_instance\test_user'`

**Comment by wsmelton** [comment]
`SqlCredential` accepts a credential object (PSCredential). So to accomplish what you want would be doing one of these two options:

```
#interactive method with prompt
Connect-DbaInstance -SqlInstance YourRemoteComputer -SqlCredential (Get-Credential 'YourRemoteComputer\testuser')
```

The above will provide a prompt to enter the password for that Windows Local User.

```
#programatically
$cred = [pscredential]::New("YourRemoteComputer\testuser",(ConvertTo-SecureString -String "YourLocalUserPassword" -AsPlainText -Force))
Connect-DbaInstance -SqlInstance YourRemoteComputer -SqlCredential $cred
```

**Comment by ojmucianski** [comment]
Thank you for your answer, but I am afraid this is not the end of story:
![image](https://user-images.githubusercontent.com/8027448/92760836-f8977a00-f388-11ea-8060-447ca027f45a.png)

as I stated before, it picks up the correct object for the credential type, it fails somewhere further way (I am sure of both user and pass being correct, I have just created them).

**Comment by wsmelton** [comment]
If you are working with a WORKGROUP setup, create that same test user on your local machine (one where PowerShell session is running) with the same password. Then retest the connection.

**Comment by ojmucianski** [comment]
It didn't help, but thanks to it I found that I also can't open the PS session locally on the remote machine as the Test_User, even after adding it to the local admin group. Based on that I feel even more that this is down to the policy setup (and where I am testing it is a quite restricted place). I will spend some more time on the investigation of that and will pass my results here.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
