### ISSUE TITLE
Connect-DbaInstance - Support making DAC connection

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#6831]
Something I think @FriedrichWeinmann will need to assist with is allowing our `DbaInstance` parameter to handle `admin:$instance` so we can allow our connect command to make the DAC connection into SQL Server.

Currently, our type is borking because it can't parse it:

![image](https://user-images.githubusercontent.com/11204251/92834765-03a9d480-f3a0-11ea-9924-08de31b30034.png)

Once that is done then we can easily adjust the settings for the connection to handle making that DAC connection to the instance. Some of the leg work for this is being done via #6828

**Comment by FriedrichWeinmann** [comment]
Happy to update that.
How exactly should I parse that notation however?

Is that `<hostname>:<Instancename>` ?

**Comment by wsmelton** [comment]
The "admin:" I would think should indicator that the fact connection is desired. I don't know if we maybe add a property for this?

Anything after that would be your normal host and/or instance name.

**Comment by FriedrichWeinmann** [comment]
Alright, so basically I'll be parsing everything after the colon as the actual input and the leading 'admin:' changes the input-type to 'DAC' or somesuch, which Connect-DbaInstance will respect?
Can definitely do that :)
Today.

**Comment by potatoqualitee** [comment]
Thanks so much to you both 🥳

**Comment by wsmelton** [comment]
Well they are exceptions that what is on the left on the colon is used.

"tcp:" vs "np:" whitch I think is being handled either on the type or by connect command, can't remember.

**Comment by potatoqualitee** [comment]
(lol you made your theme sparkle, nice, @wsmelton !)

**Comment by andreasjordan** [comment]
@FriedrichWeinmann - Is this already implemented?

**Comment by wsmelton** [comment]
No, requires a change to our library code.
