### ISSUE TITLE
Export-DbaInstance - capability to customize export folder name

### ISSUE THREAD

**Issue by jeffchulg** [sqlcollaborative/dbatools#6833]
### Summary of new feature

* Clear/concise description of what the problem is that the new feature can solve.
Incapacity to customize export folder name in Export-DbaInstance. 
We can provide a path, but the function will create a subfolder with fixed naming convention, that does not necessarily matches what user could be willing.

For instance, I would like to be able to set date format to YYYY-MM-DD_H24-MI-SS or no date at all...

### Proposed technical details (if applicable)

Basic export folder name should be the name of the instance.

We could add  parameters that will allow customization of output folder in provided `-Path` parameter.

For instance:

- `-GeneratedFolderNamesPrependText`
- `-GeneratedFolderNamesAppendText` (if empty or null, would be set to match current behavior)

With this, we would be able to customize at will the name of generated sub-folders.

* e.g. Blog post reference that shows example code or functionality

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.
1.0.115

**Comment by niphlod** [comment]
mmmhhh, with these kind of things everyone is going to have their preferred format.... can't you just 
```
$thepath = .\whatever
foreach($s in $instances) {
      export-dbainstance -sqlinstance $s -Path $thepath
      move-item $thepath -destination $whereyouwant
}
```
?

**Comment by jeffchulg** [comment]
The problem for me is with subfolders, I thought about your alternative, but it's more like DIY that professional programming.

I was about to propose a parameter which defines formats with tags, but it's maybe a little too complex compared to being able to append and prepend text around the instance name. With the ability to append and prepend, we could set the date of the format we want, append it or prepend it. If one manages multiple servers for multiple companies, he could append the name of the company etc...

**Comment by niphlod** [comment]
> but it's more like DIY that professional programming.

IMHO dbatools does not aim to be a complete solution, but instead to be a set of tools to build your solution upon. 
5 lines wrapper is hardly "DIY", I'd call it "simple and effective".

**Comment by jeffchulg** [comment]
Yes, but it's creating a folder AND subfolder, then you should locate the subfolder, move it to the expected name then delete the higher level folder, so it's more than 5 lignes (you have to do a Get-ChildItem), and it is unnecessary work if the tool is flexible.

**Comment by jeffchulg** [comment]
And, I forgot, my solution is:

2 lines for parameters
2 conditional assignments to the value of a variable

it would not be a change that requires a lot of time, and a lot of programming... almost a 5-lines change

**Comment by niphlod** [comment]
> almost a 5-lines change

yeah, for "yours" . Then someone chimes in and wants "his"... that's why IMHO export-dbainstance should stay simple and let wrappers do the customizations. Would a return object filled with the file paths help ?
kinda allowing
```
$res = Export-DbaInstance ...
move-item $res.Files -destination .\whatever
```

**Comment by jeffchulg** [comment]
The need for a loop is still there (one move-item per export... and we have to extract back the instance name from folder name)

The only will that would not match is the one not to have the instance name in generated sub-folder:

`$GeneratedFolderNamesPrependText + "InstanceName" + $GeneratedFolderNamesAppendText`

One would provide "his" willing text for appending and prepending....

**Comment by wsmelton** [comment]
Why is a need for a loop a problem?

**Comment by wsmelton** [comment]
At most I'm in agreement to control the date format, that command should be pulling this from our configuration anyway (e.g. formatting.uformat) as that allows the user to fully have control over it.

**Comment by niphlod** [comment]
does an `Export-` script allow for a return object ? if so, returning our usual `sqlinstance, computername ...... Exportedfiles` should suffice for any related questions to "where did my files go?"

**Comment by wsmelton** [comment]
No our export functions, with the exception of the instance one, dumps the content to the console. They all just call `Export-DbaScript` within them and the output of that is sent to the console.

**Comment by potatoqualitee** [comment]
Export-DbaInstance returns Get-ChildItem which means it can be piped to Move-Item 👍 

![image](https://user-images.githubusercontent.com/8278033/93030685-2862ae00-f625-11ea-9b3d-c2ff285c1273.png)

No idea why it's not naming it 1, 2, 3 but that's another issue.

**Comment by jeffchulg** [comment]
Yes, it works.... for ONE instance... what if you call it like: `<list> | Export-DbaInstance ` and you want to move the result of `Export-DbaInstance` into a different folder per instance? You need a loop like @niphlod said.

So, this discussion is a loop too....

**Comment by jeffchulg** [comment]
> 
> 
> Why is a need for a loop a problem?

In my opinion, there is a loop inside Export-DbaInstance, why nesting the call inside another loop? What if your code is about 10 nested loops, just to achieve something that could be done in the most inner part, in a simple manner? That's why I told about "DIY"...

**Comment by wsmelton** [comment]
The command does need to honor our configuration for date format on the folder and we will address that part of this issue. Implementing additional parameters to control the folder naming is out of scope.
