### ISSUE TITLE
Reset-DbaAdmin New Login issue

### ISSUE THREAD

**Issue by ChrisWoods1977** [sqlcollaborative/dbatools#6834]
When I run the following:
Reset-DbaAdmin -sqlinstance $newserver -Login domain\group -Force -verbose

I get this error:
WARNING: [16:03:40][Invoke-ResetSqlCmd] Failure | Cannot use ALTER LOGIN with the ENABLE or DISABLE argument for a Windows group. GRANT or REVOKE the CONNECT SQL permission instead.
WARNING: [16:03:40][Reset-DbaAdmin] Couldn't enable login.

It sounds like the process is:
Once the service is restarted, the following tasks are performed:
Login is added if it doesn't exist
If login is a Windows User, an attempt is made to ensure it exists
If login is a SQL Login, password policy will be set to OFF when creating the login, and SQL Server authentication will be set to Mixed Mode.
Login will be enabled and unlocked
Login will be added to sysadmin role
If failures occur at any point, a best attempt is made to restart the SQL Server.

I was curious if that could be enhanced so if the Login didn't previously exist, then it doesn't try to enable and unlock it since it is obviously not locked/disabled if it was just added. Then we could use windows groups with this great tool.

**Comment by potatoqualitee** [comment]
hey Chris, the information provided in our bug template helps save us time. We're happy to look at the issue, but please reopen using the bug template.
