### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cfradenburg** [sqlcollaborative/dbatools#6841]
### Environmental information

PowerShell Version        : 5.1.18362.752
dbatools latest installed : 1.0.119
Culture of OS             : en-US

#### SQL Server:

```sql
N/A
```

```sql
N/A
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Management.Automation.ItemNotFoundException: Cannot find path
                        'C:\Users\t1cf230330so\AppData\Local\Temp\SQL-Server-First-Responder-Kit-main' because it does
                        not exist.
                           at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean
                        allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider,
                        CmdletProviderContext context)
                           at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path,
                        CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                           at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String
                        path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider&
                        providerInstance)
                           at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String
                        path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider,
                        CmdletProvider& providerInstance)
                           at System.Management.Automation.LocationGlobber.GetChildNamesInDir(String dir, String
                        leafElement, Boolean getAllContainers, CmdletProviderContext context, Boolean
                        dirIsProviderPath, PSDriveInfo drive, ContainerCmdletProvider provider, String&
                        modifiedDirPath)
                           at System.Management.Automation.LocationGlobber.GenerateNewPSPathsWithGlobLeaf(List`1
                        currentDirs, PSDriveInfo drive, String leafElement, Boolean isLastLeaf,
                        ContainerCmdletProvider provider, CmdletProviderContext context)
                           at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean
                        allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider,
                        CmdletProviderContext context)
                           at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path,
                        CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                           at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String
                        path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider&
                        providerInstance)
                           at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String
                        path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider,
                        CmdletProvider& providerInstance)
                           at System.Management.Automation.SessionStateInternal.CopyItem(String[] paths, String
                        copyPath, Boolean recurse, CopyContainers copyContainers, CmdletProviderContext context)
                           at Microsoft.PowerShell.Commands.CopyItemCommand.ProcessRecord()
TargetObject          : C:\Users\t1cf230330so\AppData\Local\Temp\SQL-Server-First-Responder-Kit-main
CategoryInfo          : ObjectNotFound: (C:\Users\t1cf23...ponder-Kit-main:String) [Copy-Item], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Install-DbaFirstResponderKit<Begin>, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\1.0.119\allcommands.ps1: line 39644
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

#### Steps to Reproduce

Install-DbaFirstResponderKit -SqlInstance <InstanceName> -Database <DatabaseName '\\Path\To\FirstResponderKit.zip'

#### Expected Behavior

I expected the First Responder Kit to install

#### Actual Behavior

I got the error above and the install failed. PR with fix to follow

**Comment by wsmelton** [comment]
The command you provided for steps to reproduce is not a proper command. What is the PR to fix here?

**Comment by wsmelton** [comment]
As well the file name you provided, `FirstResponderKit.zip`, is not the format provided by Brent. Where did you download this file from?

**Comment by wsmelton** [comment]
I'm not able to replicate using the proper command with the file downloaded from the GitHub repo:

![image](https://user-images.githubusercontent.com/11204251/93126989-bc1e9380-f692-11ea-9f13-7c5ad69ed18c.png)

**Comment by andreasjordan** [comment]
@cfradenburg : See here: https://github.com/sqlcollaborative/dbatools/pull/6647#commitcomment-40624968

The file you get from the mailing list direct download has a different format and can not be used. You have to download the file from Github like the command does. See source code for url.

**Comment by cfradenburg** [comment]
Apparently I updated dbatools to the latest version but neglected to re-import it. After closing out of Powershell and opening it again it works.
