### ISSUE TITLE
[Bug] Set-DbaAgentJob - error setting `OperatorEmail` w/o `EmailLevel`

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#6847]
### Environmental information

```powershell
PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.119
Culture of OS             : ru-RU
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)
                Feb 15 2020 01:47:30
                Copyright (c) Microsoft Corporation
                Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

```sql
us_english
```

### Report

Cannot set operator e-mail on a job w/o specifying notification level

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```powershell
WARNING: [18:41:57][Set-DbaAgentJob] Something went wrong changing the job | The specified '@notify_level_email' is invalid (valid values are: 1, 2, 3).
```

#### Steps to Reproduce

```powershell
Get-DbaAgentJob -SqlInstance srv-sql-vm04 -Category 'SomeCategory' | Where-Object {$_.OperatorToEmail -eq ''} | Set-DbaAgentJob -EmailOperator 'OperatorEmail'
```

#### Expected Behavior

Set notification level to similar as in SSMS `onError`

#### Actual Behavior

Warning received, operator not set.

**Comment by Zhunya** [comment]
This can be a feature request if considered as not a bug

**Comment by wsmelton** [comment]
It would be a bug but we would just throw the warning the variable is missing and the user should provide it.
