### ISSUE TITLE
[Bug] https://dbatools.io/functions/ 404

### ISSUE THREAD

**Issue by MikeyBronowski** [sqlcollaborative/dbatools#6850]
#### Steps to Reproduce
When I am on https://docs.dbatools.io/# the top menu bar shows links to "commands" which is https://dbatools.io/functions/ and that returns error 404.

#### Expected Behavior
the main page https://dbatools.io has link to "commands" but it points to https://dbatools.io/commands/ which is working ok

#### Actual Behavior
https://dbatools.io/functions/ returns error 404.

cc: @potatoqualitee

**Comment by wsmelton** [comment]
So this is coming from the rendering of our docs site is adding the `/` on the end of the URL. `https://dbatools.io/functions/` is the URL that will not work but `https://dbatools.io/functions` redirects properly.

**Comment by wsmelton** [comment]
I tried removing that forward slash [here](https://github.com/sqlcollaborative/docs/commit/c781019e0205f3e8517888bddb58f7c3a5610ea2) but I think the rendering on that page is adding it back by GitHub.

One way of fixing that @potatoqualitee is we add a `functions` folder on the site and then redirect it from there as well.

// @niphlod

**Comment by MikeyBronowski** [comment]
Same thing here (404):
[](https://sqlcollaborative.github.io/builds).
The commands link goes to the \functions which return 404.

**Comment by jpomfret** [comment]
Hey @MikeyBronowski - it looks like this is now resolved, would you agree?

**Comment by MikeyBronowski** [comment]
Yeah. Looks good
