### ISSUE TITLE
Update-DbaServiceAccount - Allow for not restarting services

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#6853]
### Summary of new feature

When service accounts are managed by PIM systems (Thycotic, BeyondTrust, etc.) offer the ability to rotate the passwords in Active Directory, and in conjunction push out those passwords to dependency resources. In most situations when SQL Server service account is being managed the need is to update the password **but not** restart the service. The password change would be done when security needs it, and then DBAs will handle restarting the service during a scheduled maintenance window.

### Proposed technical details (if applicable)

A parameter that supports backward compatibility to how the command current works that simply offers the option to not restart the service.

Parameter name: `-NoRestart`

This parameter will be utilized to have the command not restart the agent service even if the password for the database engine is updated.

**Comment by nvarscar** [comment]
The only way of changing passwords/accounts that I'm aware of, is using the ManagedComputer [Service](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.wmi.service?view=sqlserver-2016) class, which would also automatically restart the services in question and doesn't have an option to skip the restart. Unless there is another way of changing passwords, I'm afraid, the feature cannot be implemented.

**Comment by wsmelton** [comment]
The `ChangePassword()` method will not auto restart the service. The current implementation of the command is only restarting the Agent service because we are telling it. Issue the command as-is to update a password for SQL Server and it does not get restarted.

**Comment by wsmelton** [comment]
I use this for a dependency script in Secret Server to rotate the SQL Server and Agent account so it won't restart the service. Then the DBA can apply the restarts during a provided window later in the workflow or maintenance.

```powershell
$params = $args
$Target = $params[0]
$Domain = $params[1]
$PrivUser = $params[2]
$PrivPwd = ConvertTo-SecureString -String $params[3] -AsPlainText -Force
$ServiceName = $params[4]
$ServicePwd = ConvertTo-SecureString -String $params[5] -AsPlainText -Force

<# Create credential for each account type #>
$privCred = [pscredential]::new("$domain\$PrivUser",$PrivPwd)
$serviceCred = [pscredential]::new('Ignore this value',$ServicePwd)

Invoke-Command -ComputerName $Target -Credential $privCred -ScriptBloc {
    [pscredential]$cred = $using:serviceCred
    [System.Reflection.Assembly]::LoadWithPartialName('Microsoft.SqlServer.SqlWmiManagement')> $null
    $sqlwmiLocal = New-Object 'Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer'

    $targetService = $sqlwmiLocal.Services | Where-Object Name -eq $using:ServiceName
    if ($targetService) {
        try {
            $targetService.ChangePassword('ignore this value',$cred.GetNetworkCredential().Password)
            $targetService.Alter()
        } catch {
            throw "Error updating the service password on $($using:Target) for service $($targetService.Name): $($_.Exception)"
        }
    } else {
        throw "Service $($using:ServiceName) not found on $($using:Target)."
    }
}
```
