### ISSUE TITLE
[Bug] Copy-DbaLogin - Database Explicit Securables not Copied

### ISSUE THREAD

**Issue by seanwhitepc** [sqlcollaborative/dbatools#6857]
#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

None

#### Steps to Reproduce

```powershell
Copy-DbaLogin -Source SOURCE -Destination DESTINATION -Login DOMAIN\LOGIN
```

#### Expected Behavior

Login with associated server-roles, Login's explicit securables, user-mappings, user-memberships, and user's explicit securables are copied.

#### Actual Behavior

Login with associated server-roles, Login's explicit securables, user-mappings, and user-memberships are copied.
User's explicit securables are **NOT** copied.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```
PowerShell Version        : 5.1.17763.1432
dbatools latest installed : 1.0.111
Culture of OS             : en-US
```

#### SQL Server:

On both SOURCE and DESTINATION:

```sql
Microsoft SQL Server 2014 - 12.0.2000.8 (X64) 
	Feb 20 2014 20:04:26 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
```

On both SOURCE and DESTINATION:

```sql
us_english
```

**Comment by wsmelton** [comment]
You are referring to object-level permissions within a user database?

**Comment by seanwhitepc** [comment]
That is correct.  The following screenshot shows an explicit SELECT permission granted to a View in a user-database.  This was not copied over.

![image](https://user-images.githubusercontent.com/49993626/93509651-e495d000-f8d4-11ea-97b3-ebe476b18e96.png)

**Comment by wsmelton** [comment]
That is not a bug as the user-level data is not known by the login, the user-level permission is within the database.

**Comment by seanwhitepc** [comment]
The documentation needs to be updated to reflect this then:

> SQL Server 2005 & newer: Migrates logins with SIDs, passwords, defaultdb, server roles & securables, **_database permissions & securables_**, login attributes (enforce password policy, expiration, etc.)

**Comment by wsmelton** [comment]
- Database permissions are at it relates to role level (e.g. what you can see on the properties window of a given login in SSMS).
- Securable are inherited from copying the SID from source to destination.

**Comment by niphlod** [comment]
cough .... while it's true that it's always good to remember that a login is different from a user, @seanwhitepc did you try with 
 `-ObjectLevel`?

**Comment by seanwhitepc** [comment]
@niphlod 

I tried with that parameter now

```powershell
Copy-DbaLogin -Source SOURCE -Destination DESTINATION -Login DOMAIN\LOGIN -ObjectLevel -NewSid
```

And it throws the following error:

```
Copy-DbaLogin : A parameter cannot be found that matches parameter name 'ObjectLevel'.
At line:1 char:95
+ ... env:computername -Login DOMAIN\LOGIN -ObjectLevel -NewSid
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-DbaLogin], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Copy-DbaLogin
```

Out of curiosity, I tried `-ObjectLevel` with `Export-DbaLogin` and got the same error.

**Comment by niphlod** [comment]
hum, seems strange, https://github.com/sqlcollaborative/dbatools/blob/master/functions/Copy-DbaLogin.ps1#L177 and https://github.com/sqlcollaborative/dbatools/blob/master/functions/Export-DbaLogin.ps1#L183

**Comment by seanwhitepc** [comment]
Things get stranger.  I get a completely different error if I run it in ISE:

```powershell
Import-Module -Name dbatools

Copy-DbaLogin -Source SOURCE -Destination DESTINATION -Login DOMAIN\LOGIN -ObjectLevel -NewSid -Force
```

And this is the error:
```
Type                            Name                     Status     Notes
----                              ----                          ------     -----
Login - WindowsUser DOMAIN\LOGIN     Successful      
Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database 'DATABASE'. "
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.119\allcommands.ps1:82856 char:21
+                     $destDb.ExecuteNonQuery($userScript)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FailedOperationException
```

I updated my version of dbatools just to make sure it wasn't something to do with an older version.

**Comment by niphlod** [comment]
try a verbose to see where it stops ..... it seems to come from the update-sqlpermission bit

**Comment by seanwhitepc** [comment]
@niphlod 

Here's the output of the same command, but with `-verbose` in ISE:

```
VERBOSE: [14:30:05][Get-DbaLogin] Getting last login times
VERBOSE: [14:30:05][Get-DbaLogin] Processing [DOMAIN\LOGIN] on SOURCE
VERBOSE: [14:30:05][Copy-DbaLogin] Force was used and DOMAIN\MY_ACCOUNT not found in logins list but an explicit Login or ExcludeLogin was specified, so
 we trust you won't drop the group that allows DOMAIN\MY_ACCOUNT access. Proceeding.
VERBOSE: [14:30:05][Copy-DbaLogin] Attempting Login Migration.
VERBOSE: [14:30:05][Copy-Login] Attempting to migrate DOMAIN\LOGIN
VERBOSE: [14:30:05][Copy-Login] Force was specified. Attempting to drop DOMAIN\LOGIN on DESTINATION.
VERBOSE: [14:30:06][Copy-Login] Successfully dropped DOMAIN\LOGIN on DESTINATION.
VERBOSE: [14:30:06][Copy-Login] Attempting to add DOMAIN\LOGIN to DESTINATION.
VERBOSE: [14:30:06][New-DbaLogin] Setting DOMAIN\LOGIN default database to master
VERBOSE: [14:30:06][New-DbaLogin] Setting DOMAIN\LOGIN language to us_english
VERBOSE: [14:30:06][New-DbaLogin] Adding as login type WindowsUser
VERBOSE: [14:30:06][New-DbaLogin] Successfully added DOMAIN\LOGIN to DESTINATION.
VERBOSE: [14:30:06][Get-DbaLogin] Getting last login times
VERBOSE: [14:30:06][Get-DbaLogin] Processing [DOMAIN\LOGIN] on DESTINATION

VERBOSE: [14:30:07][Update-SqlPermission] Grant CONNECT SQL to DOMAIN\LOGIN on DESTINATION successfully performed.
VERBOSE: [14:30:10][Export-DbaUser] Validating users on database [DATABASE]
Type                Name                     Status     Notes
----                ----                     ------     -----
Login - WindowsUser DOMAIN\LOGIN Successful      
Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database 'DATABASE'. "
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.119\allcommands.ps1:82856 char:21
+                     $destDb.ExecuteNonQuery($userScript)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FailedOperationException
```

In powershell.exe, the same `A parameter cannot be found that matches parameter name 'ObjectLevel'.` error is returned.

**Comment by nvarscar** [comment]
You should update your module to `1.0.116` and use -ObjectLevel, which would take care of object-level user permissions

**Comment by seanwhitepc** [comment]
@nvarscar 's comment is correct.  I'm using 1.0.124 and using `-ObjectLevel`, it correctly migrated the User's specific Securables.

I'm closing this.
