### ISSUE TITLE
Get-DbaDbView is rather slow, even when specifying the DB and View[Bug]

### ISSUE THREAD

**Issue by iampeterdaniels** [sqlcollaborative/dbatools#6858]
#### Host used

- [ X] powershell.exe (pwsh 7 shell)
- [ ] ISE
- [X ] VS Code (pwsh 7 - debugger and integrated cmd line)
- [ ] Other (please specify)

#### Errors Received
NONE - performance issue

#### Steps to Reproduce
Note that this SQL Instance has 200+ DBs on it.
`Get-DbaDbView -SqlInstance <MyInstance> -Database <MyDB> -view <ExistngViewName>`

#### Expected Behavior

Faster than 2 minutes and 23 seconds

#### Actual Behavior

Runs in 2 minutes and 23 seconds. 👍 

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```
PowerShell Version        : 5.1.19041.1 (This is strange because the vscode IDE shows 7.0 in the bottom corner)
dbatools latest installed : 1.0.116
Culture of OS             : en-US

I also tried it in:
PowerShell Version        : 7.0.3  
dbatools latest installed : 1.0.116
Culture of OS             : en-US

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```
Microsoft SQL Server 2012 (SP3-CU10) (KB4025925) - 11.0.6607.3 (X64)   Jul  8 2017 16:43:40   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```sql
/* REPLACE WITH output of @@LANGUAGE */
```
us_english

**Comment by wsmelton** [comment]
How many views are in each database?

**Comment by niphlod** [comment]
my thought exactly, was asking in Slack. I took a test on a 2k view db and it returned in 4 secs. I just assigned this to me (waiting for the count) because the messaging is a little wonky and needs a bit of love.

**Comment by wsmelton** [comment]
Also please run Get-DbaDatabase on that server and let us know the time.

**Comment by niphlod** [comment]
> Also please run Get-DbaDatabase on that server and let us know the time.

ALTER wsmelton SET MINDREADING ON
![image](https://user-images.githubusercontent.com/122119/93540353-b4d9dd00-f953-11ea-8bf1-640df4f01784.png)

**Comment by iampeterdaniels** [comment]
I ran `Get-DbaDatabase -SqlInstance <MyInstance> -Database <MyDB>`
5 seconds.

**Comment by iampeterdaniels** [comment]
772 User DBs on the instance.  Avergae # of views = 48.  Max # of views = 577.

**Comment by wsmelton** [comment]
@iampeterdaniels we need just `Get-DbaDatabase -SqlInstance <MyInstance>` time for this instance.

**Comment by wsmelton** [comment]
> 772 User DBs on the instance.

Once you get an instance with upward of 600+ databases you will see a guaranteed performance hit with commands on our module. There is not much we can do about that and is in general accounted from the use of SMO. In the latest version of SMO there should be some improvements on performance around enumeration but that is a grueling process to go through at this time, so will be a while before we get to the latest release. It pretty falls in SSMS has issues with Object Explorer loading and expanding the Databases folder, our module will have some issue as well.

The only glaring thing to me in this specific command @niphlod is the call to `Refresh($true)`:

https://github.com/sqlcollaborative/dbatools/blob/b889f05efefa2273000340bf6b712bed6819f06d/functions/Get-DbaDbView.ps1#L130-L132

![image](https://user-images.githubusercontent.com/11204251/93556246-ed6ebc00-f93d-11ea-81b7-4e1fa6a6f493.png)

A rough test with a raw version of the command (taking out the internal calls that I know are not an issue). @iampeterdaniels can you pull our dev branch down and run a test with that call to `Refresh()` there and then a run with it commented out?

**Comment by iampeterdaniels** [comment]
> @iampeterdaniels we need just `Get-DbaDatabase -SqlInstance <MyInstance>` time for this instance.

12 seconds

**Comment by iampeterdaniels** [comment]
Understood on the underlying SMO issues, @wsmelton, as well as the major refactoring required to update code to latest version.  I appreciate all that this team/community does.

**Comment by wsmelton** [comment]
We can at most right now take out that call to Refresh() @niphlod ? I don't see any reason to have that there as it was removed from another command for tables somewhere, can't recall which one now. Reading through it I don't see why that was added to "make sure" the list was current, we don't make changes to any objects so there is no reason it won't be current to the last connection made.

**Comment by niphlod** [comment]
yeah I will remove it and fix the oddities in the messaging system, but I really can't grasp why on an instance with 200 dbs that take 12 seconds to filter out listing views is so slow (2 additional minutes) on @iampeterdaniels 's side. Even on a 8k views with wordy views my lapdog takes 6 seconds, with or without the refresh. Did not test with PS7 yet (I'm on 5) but it's the only thing different from my setup to his.

**Comment by iampeterdaniels** [comment]
OK.  I hope this hasn't been a wild goose chase.  I just remoted (ps session) into a host in the same datacenter as the SqlInstance and the same command comes back in 5 seconds.  Before, I was going over VPN and probably across multiple gateways.
