### ISSUE TITLE
Enable-DbaTraceFlag persistent

### ISSUE THREAD

**Issue by camillagaardsted** [sqlcollaborative/dbatools#6859]
Hi dbatools!

I love this module for powershell.

I used the cmdlet Enable-DbaTraceFlag recently, and I just wondered how it's possible to set a trace flag permanently, so it's also there after a restart of the sql server service. I figured out it can be set in the registry e.g.

New-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL14.ENT2017\MSSQLServer\Parameters' -Name SQLArg4 -Value '-T6534'

so I suggest to add a persistent parameter to Enable-dDbaTraceFlag cmdlet that will use this logic. I'll be happy to help implementing this for the traceflag dbatools cmdlets.

Regards

Camilla

**Comment by wsmelton** [comment]
You would use `Set-DbaStartupParameter` for persisting the trace flags.

Ref: https://docs.dbatools.io/#Set-DbaStartupParameter
