### ISSUE TITLE
[Bug] Copy-DbaLogin - login not copied due to non existing default database

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#6860]
This is a BUG or FEATURE REQUEST

### Report

Login not copied due to not existence of a default database.

#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

#### Errors Received

```powershell
Type             Name  Status Notes
----             ----  ------ -----
Login - SqlLogin <Login> Failed
```

#### Steps to Reproduce

```powershell
Get-DbaLogin -SqlInstance <sourceSqlInstance> -Login <LoginName> | Copy-DbaLogin -Destination <destinationSqlInstance> -Force
```
or
```powershell
> Copy-DbaLogin -Source <sourceSqlInstance> -Destination <destinationSqlInstance> -Login <loginName>
```

#### Expected Behavior

- State in `Notes` property - `Default database <dbName> not exists on <destinationSqlInstance>`
or
- Login copy successfull but in `Notes` - `Default database changed from <previousDefaultDbName> to master`

#### Actual Behavior

We receive just `Failed` w/o any intel why it's failing

### Environmental information

```powershell
PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.119
Culture of OS             : ru-RU
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU14) (KB4564903) - 13.0.5830.85 (X64)
                Jul 31 2020 18:47:07
                Copyright (c) Microsoft Corporation
                Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)
```
```sql
us_english
```

**Comment by MikeyBronowski** [comment]
I looked into this and seems the issue (at least in my case) is in **New-DbaLogin** (which is called within Copy-DbaLogin)
Some testing took me to this line (all lines prior that is processed OK)
https://github.com/sqlcollaborative/dbatools/blob/f19e8248310602d15eaf5f2fd35aa22e478be956/functions/New-DbaLogin.ps1#L451

My query returned an error in SSMS, but nothing in PowerShell
```
Msg 15010, Level 16, State 1, Line 1
The database 'Mikey' does not exist. Supply a valid database name. To see available databases, use sys.databases.
```

Verbose gives:

```
VERBOSE: [23:17:07][Get-DbaLogin] Getting last login times
VERBOSE: [23:17:07][Get-DbaLogin] Processing [ToMove] on localhost,1433
VERBOSE: [23:17:07][Copy-DbaLogin] Attempting Login Migration.
VERBOSE: [23:17:07][Copy-Login] Attempting to add ToMove to localhost,14333.
VERBOSE: [23:17:07][New-DbaLogin] Setting ToMove SID
VERBOSE: [23:17:07][New-DbaLogin] Setting ToMove default database to Mikey
VERBOSE: [23:17:07][New-DbaLogin] Setting ToMove2 language to us_english
VERBOSE: [23:17:07][New-DbaLogin] Adding as login type SqlLogin
VERBOSE: [23:17:07][New-DbaLogin] Failed to create ToMove on localhost,14333 using SMO, trying T-SQL.

Type             Name    Status Notes
----             ----    ------ -----
Login - SqlLogin ToMove Failed     
```


@Zhunya - I have tried this (from Example) to copy the login - there is a DefaultDatabase parameter in New-DbaLogin command
Get-DbaLogin -SqlInstance <sourceSqlInstance> -Login <LoginName> | New-DbaLogin -SqlInstance <destinationSqlInstance> -DefaultDatabase tempdb
