### ISSUE TITLE
Add an option to filter Copy-Only backups from Get-DbaLastBackup

### ISSUE THREAD

**Issue by paschott** [sqlcollaborative/dbatools#6864]
### Summary of new feature

Add an option to filter on Copy-Only backups in the Get-DbaLastBackup function.

### Proposed technical details (if applicable)

Add a switch/parameter of some sort that will allow including all backups, copy-only backups, or non-copy-only backups - especially for the "Full" backup history.  This should allow for a way to see if the "last backup" chain seems to be okay without needing to check/verify all backups.

### Latest version of dbatools as of writing

1.0.119

**Comment by niphlod** [comment]
there's Get-DbaDbBackupHistory for that. Get-DbaLastBackup does not verify any "robustness" of the chain. 
This function mirrors what SMO does.
If you need precision, use Get-DbaDbBackupHistory

**Comment by paschott** [comment]
That's not quite the same thing. Get-DbaDbBackupHistory gets everything. I don't really want that in most cases, but a high level overview of "My last full seems to match my last diff, seems to match my last log".  If I have some copy-only job running between the actual full/diff, it doesn't give me a good overview of whether that backup chain looks right or not.  I also may not know where that full backup was stored if it was done through some 3rd party backup tool.

**Comment by niphlod** [comment]
> Get-DbaDbBackupHistory gets everything

not really, it gets what you want, including being able to filter out copyonly, virtualdevices, etc.

What Get-DbaDbLastBackup does is not filter out anything, as SMO does, to make sure SOME backup has been taken.
If you do copy-only and you don't put them away and you wanna check your history of file-based backup without copyonly, just use

 `Get-DbaDbBackupHistory -Last -DeviceType Disk`

Quote from the code of Get-DbaDbLastBackup :
`SMO's (and this) report the last backup of this type irregardless of the chain`

**Comment by wsmelton** [comment]
Just noting that all `Get-DbaLastBackup` does is call `Get-DbaDbBackupHistory` ...so adding in additional properties to note it is a copy-only backup can be done. We simply include `-IncludeCopyOnly` on every call.

The raw object we return includes `is_copy_only` so adding a property to the output object is reasonable; then the user has a property to filter with `Where-Object`.
