### ISSUE TITLE
Error when Restoring database, due to Test-DbaBackupInformation] Trying to restore  from multiple sources databases

### ISSUE THREAD

**Issue by LeonardRutkowski** [sqlcollaborative/dbatools#6869]
when restoring a database, I am receiving the error, Test-DbaBackupInformation] Trying to restore DATABASE from multiple sources databases. The .bak file restores ok, but when adding .trn files, I am gettng the warning message.  Looking at the header for the 2 files, I see the database name in the .bak file is mixed and lower case, DatabaseName, for example. Looking at the .trn file, it is all uppercase, DATABASENAME.  Looking at the Test-DbaBackupInformation, I see that there is a comparison. My input database name is mixed case. The below code does an -eq.  I believe this is causing the issue.  Suggestion would be to uppercase or lowercase both variables so comparison would be equal.

          #Test we're only restoring backups from one database, or hilarity will ensure
            $DbHistory = $InternalHistory | Where-Object { $_.Database -eq $Database }
            if (( $DbHistory | Select-Object -Property OriginalDatabase -Unique ).Count -gt 1) {
                Write-Message -Message "Trying to restore $Database from multiple sources databases" -Level Warning
                $VerificationErrors++

**Comment by Stuart-Moore** [comment]
are the backups from the same database? I mean the *exact* same database, not just 2 databases with the same name? 

Or are you using a 3rd party backup? and what collation is master running under? Which SQL, Powershell and OS versions are you running on as well please.

I've never seen SQL Server do that, as it uses the value from master.sys.databases which shouldn't be changing. The code has been the same for 3 years, so would have expected to see this before this if it was widespread.

eq isn't the issue, it's the unique on the select. Try these:

```
'one' -eq 'One'
'one','One' | select-object -unique
```

To see how that works.

**Comment by andreasjordan** [comment]
I have see the problem with different cases in my training classes a few years ago. I can not exactly remember but I think the user input was used for the insert in the msdb tables and probably for the header as well.

**Comment by andreasjordan** [comment]
Would it be possible to use the database GUID instead of the name?

**Comment by LeonardRutkowski** [comment]
We are using a native backup, using a stored procedure that is similar to the Ola Hallogren stored procedure's.  Maybe I can clarify why the header information for the database dump is different than the header information in the log file.  We use log shipping for our production databases. We have a job that will create the log shipping, when we want to initialize or re-initialize.  There is a table we keep, that is a list of the databases to be log shipped, during this process. It uses the database name in this table to for the SQL to set up for log shipping.  In this table, the database in question was in all caps. When it set up the log ship backup tran job, it used the name of the database from this table, all in upper case. The tran log header database name is all upper case. The full backup job uses the database name, from sys.databases, and it is mixed case.  My work around was to update the log ship table to be mixed case, and re-initialize log shipping for that database.  So the original comparison of DatabaseName -eq DATABASENAME would then be DatabaseName -eq DatabaseName, thus 'fixing' the problem, without changing source code.

**Comment by Stuart-Moore** [comment]
Sorry for slow responses, busy finalising stuff for SQLBits this week

DB GUID is no good as it's not included in the backup headers and that's the basis of the whole stack.

replacing the select with this: 
```
$DbHistory | Select-Object -Property @{ Name="test"; expression = {$_.OriginalDatabase.ToUpper() }} -Unique
```

Should fix it. 

Will need testing. And it may well error further along the pipeline so it might be a bit of a whack-a-mole thing.

**Comment by LeonardRutkowski** [comment]
Not sure what $DBHistory is, but as long as you upper case both sides of the compare, then that should work. $DBHistory being the full backup and the transaction log dumps? If so, I would think that will work.

**Comment by Stuart-Moore** [comment]
As mentioned, it's not the `-eq` at fault, its the `-unique` on `Select-0bject'.

I've added a patch in https://github.com/sqlcollaborative/dbatools/tree/fix6869

Could you take it for a spin please and confirm it fixes your issue before I merge it into the main branch

**Comment by LeonardRutkowski** [comment]
Thank you for the fix. Unfortunately, to test this, I would need to reverse my 'fix', run backups, then attempt to restore it somewhere.  If I get a chance, I will try and do this. We were restoring earlier, to test DR, and that is how we found the issue.
