### ISSUE TITLE
Copy-DbaDatabase: Parameter set cannot be resolved using the specified named parameters

### ISSUE THREAD

**Issue by hunsbct** [sqlcollaborative/dbatools#6873]
Apologies if this is a stupid question. I'm still pretty new to Powershell so I'm not too familiar with troubleshooting errors just yet.

I am trying to perform a Copy-DbaDatabase between two machines that are not domain joined. As a result, the -BackupRestore method will not work because I can't find a way to establish a shared folder accessible to the SQL Server service accounts on both PCs. Test-DbaConnection works and I can access the source PC via SQL Server Management Studio (the destination is my local workstation).

I was hoping that the -DetachAttach method would work but I am getting this error:

```
Copy-DbaDatabase : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Copy-DbaDatabase `
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-DbaDatabase], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Copy-DbaDatabase
```

The original command is as follows:

```
Copy-DbaDatabase `
-Source source-pc `
-SourceSqlCredential $sourcecred `
-Destination localhost\mssqlserver `
-Database DBName `
-DetachAttach `
-NewName "NewDBName" `
-WithReplace
```

Seems like I'm missing a parameter or have something ordered incorrectly, but after combing through documentation and examples I can't determine what I'm missing. Any tips?

**Comment by niphlod** [comment]
not sure about what paramset rule you're breaking but .... detach/attach will require that the source server is able to transfer files to the destination one (using admin shares, if they're available)

**Comment by hunsbct** [comment]
That was it! Removing -WithReplace solved the issue. Thanks so much for the very quick reply.
