### ISSUE TITLE
405 Not Allowed

### ISSUE THREAD

**Issue by francesco1119** [sqlcollaborative/dbatools#6886]
FYI: I cannot subscribe to your newsletter on your website: 405 Not Allowed

Thank you

**Comment by wsmelton** [comment]
Thanks for the issue @francesco1119, that subscribe option is no longer supported since the site was moved to GitHub hosting.

FYI @potatoqualitee the subscribe page is still pointed at WordPress content, that's why the 405 is being returned.

**Comment by francesco1119** [comment]
Update: the subscribe page is still there and users are still hitting the 405 error. 
Just provide an alternative like an RSS feed or other subscribe method
