### ISSUE TITLE
[Bug]Remove-DbaAgentSchedule deletes wrong schedule

### ISSUE THREAD

**Issue by mwsutherland** [sqlcollaborative/dbatools#6890]
### Report
The `Remove-DbaAgentSchedule` cmdlet has multiple issues, one of which is the bug I am reporting:
1. You can't specify to remove schedule X from job Y by schedule name, you have to specify to delete a schedule by UID (and that doesn't work, as we will see below)
2. It assumes every unique schedule has a unique name or, to put it another way, it assumes all schedules with the same name are a common shared schedule. There is no requirement in SQL Server for this to be the case. If you have 30 jobs with unique schedules all named "daily" and you `Remove-DbaAgentSchedule -Schedule daily`, you will remove them all.
3. **In that same situation, if you get the UID of the specific 'daily' schedule you want to remove and `Remove-DbaAgentSchedule -ScheduleUid $Uid`, it will remove a single schedule named 'daily', but not necessarily the one with the UID you specified.**
4. I have not looked deeply into it since I don't use shared schedules, but, because of issue 1, there doesn't seem to be a way to remove a shared schedule from a specific job without removing it from all jobs which use it. (I'm assuming a shared schedule has a single UID across all jobs).

**Issue 3 is the bug I'm reporting.** Issues 1 and 2 are here to provide context as to why I need to remove by UID, but I think they are also issues, even if not bugs. 4 is a bonus (non-bug) issue in case someone wants to do a serious revamp of this cmdlet.

#### Host used

- [x] powershell.exe
- [ ] ISE
- [x] VS Code
- [ ] Other (please specify)

#### Errors Received
No error reported, just incorrect results.

#### Steps to Reproduce
Script attached to demonstrate. Rename to testcase.ps1
[testcase.txt](https://github.com/sqlcollaborative/dbatools/files/5300345/testcase.txt)

#### Expected Behavior
Correct job schedule removed.

#### Actual Behavior
Incorrect job schedule removed. 
I included my output when running testcase.ps1 as a comment in the file.

### Environmental information

PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.119
Culture of OS             : en-US

Note: The changes in pull request #6874 are applied, otherwise we would be getting an error and removing nothing.

#### SQL Server:

Microsoft SQL Server 2019 (RTM-CU7) (KB4570012) - 15.0.4063.15 (X64) 
	Aug 15 2020 10:48:11 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

us_english

**Comment by mwsutherland** [comment]
Poking around a bit more, I see that you can make multiple schedules on a single job with the same name, so I think the fundamental flaw is using name to identify schedules in any way. I haven't looked, but this flaw could exist in other schedule-related cmdlets as well. Maybe removing by UID can be fixed without resolving this fundamental issue or maybe an overhaul is the only solution.

**Comment by andreasjordan** [comment]
Oh yes, a lot of issues with this command. Will do a complete rewrite, may take some days...

**Comment by andreasjordan** [comment]
I opened the pull request (as a draft) - you can have a look at the proposed code if you like: #7430.
