### ISSUE TITLE
[Bug] Connect-DbaInstance assumes MFA method when azure.tenantid is in dbatoolsconfig

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#6896]
#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
PSMessageDetails      :
Exception             : System.Exception: When using AD Universal with MFA Support, database must be specified.
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], Exception
FullyQualifiedErrorId : dbatools_Connect-DbaInstance
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Git\dbatools\internal\functions\flowcontrol\Stop-Function.ps1: line 221
                        at Connect-DbaInstance<Process>, C:\Git\dbatools\functions\Connect-DbaInstance.ps1: line 498
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce
A long time ago:
`Set-DbatoolsConfig -FullName azure.tenantid -Value 'guidheremaybename' -Passthru | Register-DbatoolsConfig`  
  
Now:  
`Connect-DbaInstance -ConnectionString 'Data Source=TCP:uheresmyserverc.database.windows.net,1433;Initial Catalog=SomeDB;User Id=SomeWriterUser;Password=I**************************f; Persist Security Info=True;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False;Application Name=dbatools PowerShell module -dbatools.io' -Debug`  
  
and:  
`Connect-DbaInstance -SqlInstance 'uheresmyserverc.database.windows.net' -DisableException -Database 'SomeDB' -SqlCredential $SomeWriterUser -Debug`
  
and:  
`Connect-DbaInstance -SqlInstance 'uheresmyserverc.database.windows.net' -DisableException -Database 'SomeDB' -SqlCredential $ITWriter -Verbose -AppendConnectionString 'User ID=SomeWriterUser;Password =I**************************f;'`  
  
#### Expected Behavior

![image](https://user-images.githubusercontent.com/22813386/94821041-6de2f180-0401-11eb-9129-bae7b36147c1.png)

#### Actual Behavior

![image](https://user-images.githubusercontent.com/22813386/94820513-d7163500-0400-11eb-86b8-02b15e0e6637.png)  
  
If there's a tenant Id in dbatoolsconfig and it's not added as a parameter at execution, `Connect-DbaInstance` will retrieve it.  
If we choose sql authentication it will not be used because further logic in the function decides we want to use MFA because `-Tenant` is not $null.  
In all 3 versions above the User and Password are ignored because of this.  
  
Workaround by @andreasjordan : add `-Tenant $null`

### Environmental information

```powershell
PowerShell Version        : 5.1.19041.1
dbatools latest installed : 1.0.121
Culture of OS             : nl-BE
```

#### SQL Server:

  
Az Sql Managed Instance  
```sql
 Windows Server 2019 Datacenter
```

**Comment by andreasjordan** [comment]
Hi @potatoqualitee 

this is the code that fires, but should not be fired, as we have a complete connection string that works:

```
                if ($Tenant -or $AuthenticationType -eq "AD Universal with MFA Support") {
                    if ($Thumbprint) {
                        Stop-Function -Message "Thumbprint is unsupported at this time. Sorry, some DLLs were all messed up."
                        return
                    }

                    $appid = Get-DbatoolsConfigValue -FullName 'azure.appid'
                    $clientsecret = Get-DbatoolsConfigValue -FullName 'azure.clientsecret'

                    if (($appid -and $clientsecret) -and -not $SqlCredential) {
                        $SqlCredential = New-Object System.Management.Automation.PSCredential ($appid, $clientsecret)
                    }

                    if (-not $azurevm -and (-not $SqlCredential -and $Tenant)) {
                        Stop-Function -Message "When using Tenant, SqlCredential must be specified."
                        return
                    }

                    if (-not $Database) {
                        Stop-Function -Message "When using AD Universal with MFA Support, database must be specified."
                        return
                    }

                    if (-not $SqlCredential) {
                        Stop-Function -Message "When using Tenant, SqlCredential must be specified."
                        return
                    }
                    Write-Message -Level Verbose -Message "Creating renewable token"
                    $accesstoken = (New-DbaAzAccessToken -Type RenewableServicePrincipal -Subtype AzureSqlDb -Tenant $Tenant -Credential $SqlCredential)
                }
```

Besides the checks, this is the task of the code block:

```
$appid = Get-DbatoolsConfigValue -FullName 'azure.appid'
$clientsecret = Get-DbatoolsConfigValue -FullName 'azure.clientsecret'
$SqlCredential = New-Object System.Management.Automation.PSCredential ($appid, $clientsecret)
$accesstoken = (New-DbaAzAccessToken -Type RenewableServicePrincipal -Subtype AzureSqlDb -Tenant $Tenant -Credential $SqlCredential)
```

So getting appid and clientsecret to build a credential and use this to get an access token.
In what cases is this needed?
Should the parameter Tenant really trigger that?

**Comment by potatoqualitee** [comment]
Thanks for looking @andreasjordan. Access Tokens are needed by MFA. I'm not aware of any way around it.

**Comment by wsmelton** [comment]
@PowerDBAKlaas why do you have Tenant set in the configuration? I don't really consider this a bug being that if you set the Tenant ID in our configuration, that is the intent to utilize it without exception.

If you do not want to use it consistently and have to mix in using SQL Logins then the best path is to remove it from our configuration.

**Comment by wsmelton** [comment]
The workaround is either using `-Tentant $Null` or clear the configuration if it is no longer desired to use for the connection process.

**Comment by PowerDBAKlaas** [comment]
@wsmelton I'm using those workarounds now, but I feel I shouldn't have to do that.
There are two basic principles ignored here:
- execution time params should always overwrite configs and defaults: if the command params say it's using sql authentication, it should not be altered to other auth types
- config values should not be aimed at one use case; a tenant id is "the id of the tenant", not "the tenant id to force MFA for connect-dbainstance" .

Assume you want to mix query results with Azure resource data, e.g. Az SQL MI service tier. I would gladly use the dbatoolsconfig azure.tenantid with Connect-AzAccount.
Furthermore, if the config value was set once upon a time, it's very hard to find out that is the reason of the failing sql authentication.

BTW has anyone succeeded in authorizing with MFA? Microsoft docs say it's only possible via SSMS and sqlpackage

**Comment by andreasjordan** [comment]
Hi @PowerDBAKlaas : Using AccessToken is on its way: #7316 
And please use the new code path in Connect-DbaInstance, see Example 17 at https://docs.dbatools.io/#Connect-DbaInstance
Feedback for that is highly welcome.

I will close this for now, but you can reopen it if you have further questions.

**Comment by potatoqualitee** [comment]
@PowerDBAKlaas - I'm revisiting this functionality now and that is as designed. Tenant uses SqlCredential for clientid and secret, as all 3 are required when the connection is not coming from azure. We do have a `-Tenant` flag that you can use in lieu of using configs, otherwise you will indeed have to set Tenant to null.

I'm looking into MFA now 🥳
