### ISSUE TITLE
Restore-DbaDatabase - parameter for backups with passwords

### ISSUE THREAD

**Issue by SQLGeordie** [sqlcollaborative/dbatools#6903]
### Summary of new feature

If a backup file is password protected, there is no parameter to pass in for the password for restore

### Proposed technical details (if applicable)

Example:
Restore database AdventureWorksDW from disk='D:\test.bak' With **Password = 'pwd1'**

Restore-DbaDatabase -server $Server -path "$FullBackupFilePath" -DatabaseName $DatabaseName **-Password $Password**

### Latest version of dbatools as of writing

1.0.123

**Comment by Stuart-Moore** [comment]
Working on it.

As the feature is deprecated in SMO I'm just going to implement the restore bits for now.

**Comment by Stuart-Moore** [comment]
That's all in the restorepasswd branch now.  would you mind taking it for a 'real world' test drive before I merge it in.

**Comment by Stuart-Moore** [comment]
And it turns  out I'd picked up on an old version of SMO on that dev machine. Unfortunately that means we can't do it now as it was deprecated, and removed in 160.2004021.0 completely.

Sorry about that :(
