### ISSUE TITLE
Get-DbaProductKey throws error on SQL Server 2005

### ISSUE THREAD

**Issue by tonyfountain** [sqlcollaborative/dbatools#6907]
Receive error when running Get-DbaProductKey against a SQL Server 2005 instance.  However the documentation states that SQL Server 2005 is supported.  The following error is received:
```
WARNING: [23:52:51][Get-DbaProductKey] Error occurred while establishing connection to @{ComputerName=<redacted>; InstanceName=MSSQLSERVER; SqlInstance=<redacted>; Hive=HKLM; Path=Software\Microsoft\Microsoft SQL Server\MSSQL.1; RegistryRoot=HKLM:\Software\Microsoft\Micro
soft SQL Server\MSSQL.1}.SqlInstance | SQL Server version 10 required - [<redacted>] not supported.
```

#### Host used

- [ ] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: SQL Server version 10 required - [<redacted>] not supported. ---> System.Exception: SQL Server version 10 required - [<redacted>] not supported.
                           --- End of inner exception stack trace ---
TargetObject          : <redacted>
CategoryInfo          : ConnectionError: (<redacted>:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Get-DbaProductKey,Stop-Function
ErrorDetails          : SQL Server version 10 required - [<redacted>] not supported.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.123\allcommands.ps1: line 84120
                        at Get-DbaProductKey<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.123\allcommands.ps1: line 32574
                        at <ScriptBlock>, <No file>: line 17
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

Run Get-DbaProductKey against a SQL Server 2005 version.  In this case 9.00.5057.

#### Expected Behavior

I expected the product key information to be returned.

#### Actual Behavior

Errored out reporting that instance is not supported, at least version 10 is required.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.14393.3471
dbatools latest installed : 1.0.123
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2005 - 9.00.5057.00 (X64)   Mar 25 2011 13:33:31   Copyright (c) 1988-2005 Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.2 (Build 9200: ) 
```

```sql
us_english
```

**Comment by ClaudioESSilva** [comment]
Hi @tonyfountain,

The documentation (if you are referring to the [line 4](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaProductKey.ps1#L4) ) is wrong.

I say this because if you take a look at [line 185](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaProductKey.ps1#L185), the minimum version required is `10` which means SQL Server 2008.

Will update the `SYNOPSIS` and close this issue.
Thanks!
