### ISSUE TITLE
[Bug] .ToString("yyyy-MM-dd HH:mm:ss") is not "culture safe" and ":" can be converted to "."

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6909]
I open this issue to discuss a general solution for converting datetimes into strings.

We found this here: https://github.com/sqlcollaborative/dbatools/issues/6452

I used VSCode and searched the code for "yyyy-MM-ddTHH:mm:ss" and found this in:
* Get-DbaDbBackupHistory
* Get-DbaDbMailHistory
* Get-DbaDbMailLog
* Get-DbaDbRestoreHistory

I used VSCode and searched the code for "yyyy-MM-dd HH:mm:ss" and found this in:
* Export-DbaExecutionPlan
* Get-DbaExecutionPlan
* Get-DbaRandomizedValue
* Invoke-DbaDbDataMasking

@niphlod came up with `.ToString("yyyy-MM-ddTHH:mm:ss", [System.Globalization.CultureInfo]::InvariantCulture)`.

Are there other ideas?

**Comment by andreasjordan** [comment]
The link to the documentation:
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.timeseparator

**Comment by niphlod** [comment]
The uninternationally-savvy kids set the culture on the entire process and live with it, but we chose not to force it  ..... wherever we do a tostring specifying the culture we want (or, the invariantculture for better) is the only way.

**Comment by potatoqualitee** [comment]
If the change is agreed upon (i'm not savvy enough in this arena), please create 1 PR for all commands. I would like @niphlod's approval because of his background. @FriedrichWeinmann is also an ideal candidate.

**Comment by niphlod** [comment]
we already switched from 120 to 126 (the "T" made the difference) for some other "culture issue", and we thought we fixed for good.
Surely this doesn't break anything. If anything else more comes up, we'll fix it down the line.
I just have a small doubt about [System.Globalization.CultureInfo]::InvariantCulture not being compatible with PS3, but I'm fairly confident it works.
so +1 for me.

**Comment by andreasjordan** [comment]
I will try to find time for this this afternoon. If someone else wants to take over, please let me know.
