### ISSUE TITLE
Get-DbaBackupHistory - Add option to ignore copy_only backups

### ISSUE THREAD

**Issue by Stuart-Moore** [sqlcollaborative/dbatools#691]
### Is this a *feature* OR *bug*:

Feature

Currently Get-DbaBackupHistory includes copy_only backups by default. This causes an issue when the output is piped into Restore-DbaBackup as it grabs the copy_only one as the most recent and then doesn't pick up logs/etc as it's a new Recovery Fork

Proposing we add an IgnoreCopyOnly switch to the function which appends is_copy_only=0 to the sql query.

**Comment by ctrlbold** [comment]
OHHH good idea! Yes please.
