### ISSUE TITLE
[Bug]When using Find-DbaInstance on a named named instance of sql 2012\windows 2012, it returns a port value of 0. The port value is in the TCP Dynamic Port field. What parameter do I need to use? Btw great cmdlet's. Thanks

### ISSUE THREAD

**Issue by DBAgnew** [sqlcollaborative/dbatools#6913]
#### Host used

- [ ] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
replace THIS text WITH the OUTPUT of -- $ERROR[0] | SELECT *
```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

**Comment by DBAgnew** [comment]
PowerShell Version        : 5.1.18362.752
dbatools latest installed : 
Culture of OS             : en-US

SQL Server version will vary from 2008 R2 - 2019.  Over 150 servers.

**Comment by wsmelton** [comment]
Please open a new issue and provide all the details requested in our template.
