### ISSUE TITLE
Test-DbaLastBackup - Add -IgnoreDiffBackup option

### ISSUE THREAD

**Issue by SQLGB** [sqlcollaborative/dbatools#6914]
### Summary of new feature

Add an -IgnoreDiffBackup option to allow differential backups to be ignored when testing the last backup to support use cases where differential is not desired in test scenario.  An -IgnoreLogBackup option already exists, but there is no option to ignore diff backups like there is with Restore-DbaDatabase.

### Proposed technical details (if applicable)

A new parameter -IgnoreDiffBackup and the logic to support the changed behavior.

### Latest version of dbatools as of writing

1.0.124

**Comment by Stuart-Moore** [comment]
PR in for this if you'd like to take it for a test drive

**Comment by SQLGB** [comment]
Cool, thanks!
