### ISSUE TITLE
Find-DbaCommand

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#692]
This new command will be a speedier version to search dbatools commands (e.g. with tags, help text, etc) because get-help performance is sloooowww

**Comment by ctrlbold** [comment]
Yes, I'd love this. 

Can you please add support for auto populated tags? I just added Jason Shirk's TabExpansion++ to the Development branch. The only thing you would need to do its

- Add an array parameter called Tag to your params

```
[CmdletBinding()]
	Param (
		[string]$Whatever
		[string()]$Tag
	)
```

- Update [development\internal\dynamicparams\tag.ps1](https://github.com/sqlcollaborative/dbatools/blob/development/internal/dynamicparams/tag.ps1) to actually do the population (right now there's just two fake tags)
