### ISSUE TITLE
dbatools.io cmdlets hang in task manager

### ISSUE THREAD

**Issue by ccastillo-id** [sqlcollaborative/dbatools#6923]
I have made a GUI in SAIPEN that utilizes a login page for users. it accepts 2 text boxes, username and password and a button to execute. I have re-build the GUI step by step and have found out when I close out the GUI the EXE stays alive in Task Manager. The cmdlets I have been using are

Connect-DbaInstance
Test-DbaConnection
Write-DbaDbDataTable
Invoke-DbaQuery

when I use these cmdlets something and I close out the GUI it does not kill the process in Task manager.

**Comment by andreasjordan** [comment]
I have seen PowerShell ISE staying alive after I use dbatools. This is because there are still smo objects with connections to the instance in the background. 
Do you reuse the output of Connect-DbaInstance in the other commands? Then this should be the only connection. Maybe try to close it with `.ConnectionContext.SqlConnectionObject.Close()`.

**Comment by ccastillo-id** [comment]
thanks for the response Andreas. I just added this to my Connect-DbaInstance variable and the EXE still exists in the Task Manager

```
$buttonLogin_Click = {
	if ($maskedtextboxUserName.Text -ne "" -or $maskedtextboxPassword.Text -ne "")
	{
		Login-IDCreds -Username $maskedtextboxUserName.Text -Password $maskedtextboxPassword.Text
		$checkLogin = Connect-DbaInstance -SqlInstance $sqlInstance -SqlCredential $creds
		
		if ($checkLogin -ne $null)
		{
			$labelStatus.Text = "Connection successful"
			$checkLogin.ConnectionContext.SqlConnectionObject.Close()
		}
		else
		{
			$labelStatus.Text = "Connection unsuccessful"
		}
	}
	else
	{
		$labelStatus.Text = "Please make sure all textboxes are populated"
	}
}

function Login-IDCreds
{
	param (
		[string]$Username,
		[string]$Password
	)
	# Store login info into global creds variable
	$securePw = $Password | ConvertTo-SecureString -AsPlainText -Force
	$Global:creds = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $Username, $securePw
}
```

PS... this is the only code I have in my codebase. I have segregated it to only test this login.

**Comment by ccastillo-id** [comment]
I have the entire codebase here if needed
https://github.com/senorezi/DbaTools_GuiHang

**Comment by andreasjordan** [comment]
Sorry to say, but I can not help here. My suggestion is to use the process explorer (https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to see if it is maybe not unloading the dlls.
I tested with PowerShell ISE and the Az module: I just load the module and then close the ISE. All dlls are unloaded and the process is stopped.
I tested with PowerShell ISE and dbatools module: I just load the module and then close the ISE: No dlls are unloaded and the process stays in the background.
@potatoqualitee : Do you know about this issue with dbatools that the ISE process stayes in the background?
So it's not about the connections but maybe the module itself.
But to be clear: It's just a problem with PowerShell ISE, not with powershell.exe. But your exe might have the same problem as the ISE.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.

**Comment by potatoqualitee** [comment]
@andreasjordan - what do you think about Disconnect-DbaInstance? Tho I'm not sure it's even possible with connection pooling.

**Comment by andreasjordan** [comment]
Sometimes I do some tests - but I have not found a way that works. Last idea: It's a dbatools background task - maybe @FriedrichWeinmann has an idea.

**Comment by potatoqualitee** [comment]
What if we kept a $script:connected = @{} hashmap in psm1, add to it in Connect-DbaInstance and then Disconnect sends those explicit closes? I used to have hangs but I haven't in a long time.
