### ISSUE TITLE
Restore-DbaBackup - add switch to skip TLOG restore

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#693]
### Is this a *feature* OR *bug*:

*feature*

### Expected Results

Restore database with only FULL/DIFF backup files, some times, for test environments fast restores more useful.

**Comment by Stuart-Moore** [comment]
Putting in an IgnoreLogBackup switch should be pretty easy. Will just need to shortcut out a test in one of the sub functions.

I'll see if I can get it in today before I do the final push. If not it'll be something to add post 'go live'

**Comment by Stuart-Moore** [comment]
That's in and working for me. Do you want to take it for a test drive and I'll close the issue?

**Comment by Zhunya** [comment]
Downloaded changes just 10 minits ago, will give it a tru in a moment

**Comment by Zhunya** [comment]
`PS C:\Users\user> Restore-DbaBackup -SqlServer SRV1 -Path '\\SRV2\SQLBackup\SRV3\DB1' -DatabaseName DB1_test -Verbose -MaintenanceSolutionBackup -IgnoreLogBackup
VERBOSE: Restore-DbaBackup : Paths passed in
VERBOSE: Restore-DbaBackup : Ola Style Folder
VERBOSE: Get-OlaHRestoreFile - Starting
VERBOSE: Get-OlaHRestoreFile - Checking Path
VERBOSE: Get-OlaHRestoreFile - Checking we have a FULL folder
VERBOSE: Get-OlaHRestoreFile - We have a FULL folder, scanning
VERBOSE: Get-OlaHRestoreFile - We have a LOG folder, scanning
VERBOSE: Get-OlaHRestoreFile - We have a DIFF folder, scanning
VERBOSE: Get-FilteredRestoreFile - Starting
VERBOSE: Get-FilteredRestoreFile - Read File headers (Read-DBABackupHeader)
VERBOSE: Connecting to SRV1
VERBOSE: Get-FilteredRestoreFile - **822 Files to filter**
VERBOSE: Get-FilteredRestoreFile - 1 database to process
VERBOSE: Get-FilteredRestoreFile - Find Newest Full backup
VERBOSE: Get-FilteredRestoreFile - Got a Full backup, now to find diffs if they exist
VERBOSE: Get-FilteredRestoreFile - we have at least one diff so look for tlogs after the last one
VERBOSE: Get-FilteredRestoreFile - Database in simple mode or IgnoreLogBackup is true, skipping Transaction logs
VERBOSE: Get-FilteredRestoreFile - Returning Results to caller
VERBOSE: Restore-DbaBackup -  dbs to restore
VERBOSE: Restore-DbaBackup - Starting FileSet
VERBOSE: Test-DbaLsnChain - Testing LSN Chain
VERBOSE: Test-DbaLsnChain - Passed LSN Chain checks
VERBOSE: Test-DbaRestoreVersion - RestoreVersion is 10
VERBOSE: Restore-DBFromFilteredArray - Starting
WARNING: Restore-DBFromFilteredArray - **DB1_test exists**, must use WithReplace to overwrite
WARNING: See error log C:\Users\strutinskyad\Documents\dbatools-exceptions.txt for more details.
VERBOSE: Database **DB1_test restored**
`

May we run some checks first, in this situation check database existence first, it takes a long time to read 822 files

**Comment by Stuart-Moore** [comment]
We can if a databasename is passed in. But if multiple db backups are passed in, then we don't know the db names until we've scanned all the files.

**Comment by Stuart-Moore** [comment]
Pushed that fix up now.
