### ISSUE TITLE
error when i run Get-DbaDbEncryption command

### ISSUE THREAD

**Issue by eiqie** [sqlcollaborative/dbatools#6932]
PS C:\Windows\system32> Get-DbaDbEncryption -SqlInstance mshofsql001 -Database SQLInventoryManagerRepository
Where-Object : Cannot bind argument to parameter 'FilterScript' because it is null.
At C:\Users\MYS599-admin\Documents\WindowsPowerShell\Modules\dbatools\allcommands.ps1:23561 char:117
+ ... ies | Where-Object( { $psitem.name -eq 'EncryptionAlgorithm' }).value
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Where-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WhereObjectCommand

**Comment by nvarscar** [comment]
This is simply an incorrect PS syntax. You can't use Where-Object like that. Proper syntax would be
```
... ies | Where-Object { $_.name -eq 'EncryptionAlgorithm' }
```
