### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by keithmauerman** [sqlcollaborative/dbatools#6945]
Somehow sometime i had installed dbatools on onedrive and when i try to install it on my laptop i am getting a error stating its already installed on onedrive ? how do i uninstall it off of onedrive?

**Comment by nvarscar** [comment]
You can use the cleanup script shipped with the module. Read more in the following article: http://dbatools.io/clean

**Comment by keithmauerman** [comment]
I am getting this error     And when I attempt to install dbatools   Sent from Mail for Windows 10 From: Kirill KravtsovSent: Tuesday, October 27, 2020 11:26 PMTo: sqlcollaborative/dbatoolsCc: keithmauerman; AuthorSubject: Re: [sqlcollaborative/dbatools] installing error (#6945) You can use the cleanup script shipped with the module. Read more in the following article: http://dbatools.io/clean—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
