### ISSUE TITLE
Test-DbaSpn returns wrong result from Azure IAAS SQL Server

### ISSUE THREAD

**Issue by PowerDBAKlaas** [sqlcollaborative/dbatools#695]
### Is this a *feature* OR *bug*:
bug

### System Details

- Operating system name and version:
Windows 10 Enterprise 10.0.14393

- Output from `$PSVersionTable`:
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

- Output of dbatools version:
0.8.707

- SQL Server version for source/target
all SQL2016

### Steps to Reproduce
Test-DbaSpn -ComputerName SQLOnAzure

### Action Results

[InstanceServiceAccount] returns "NT Service\MSSQLSERVER"
which is wrong, the service definitely runs under a domain account

[RequiredSPN] is empty
which results in an error from Set-DbaSpn when piped through

This happens on all 3 SQL Servers in Azure IAAS,
and on none of 16 SQL Servers on premise, 2 physical + 14 on VMWare

### Expected Results

[InstanceServiceAccount] should return the correct Account
[RequiredSpn] should return an SPN

**Comment by PowerDBAKlaas** [comment]
@drewfurgiuele any news on this?

**Comment by drewfurgiuele** [comment]
Sorry @PowerDBAKlaas I was out sick yesterday; I will be working on this in the coming weekend.

**Comment by wsmelton** [comment]
SPNs in Azure SQL are not treated the same as on-premise because Azure manages the DNS objects, and you are using AzureAD. So I don't think we can fully support this using setspn unless there is code available in Azure's API that can be used. Which will cause external resources.

**Comment by potatoqualitee** [comment]
how should we handle this knowing what @wsmelton has told us?

**Comment by PowerDBAKlaas** [comment]
I think it should warn or return $null or 'unknown', but never return wrong results.

**Comment by awickham10** [comment]
Is this still an issue? I was able to run this with no issue in 0.9.197.

**Comment by PowerDBAKlaas** [comment]
I can't test this anymore. don't have access to those servers any longer.

**Comment by awickham10** [comment]
My test scenario was an IaaS VM in Azure, installing SQL Server, and joining to a traditional AD domain. Does that match up with what you were doing?

**Comment by PowerDBAKlaas** [comment]
Yes, that must be quite the situation I had.
