### ISSUE TITLE
DBATools - Remove time from Export-DBAScript 

### ISSUE THREAD

**Issue by KavzB16** [sqlcollaborative/dbatools#6952]
Hi there,

Is it possible to remove the timestamp when Export-DBAScript is used? I would just like to use the Server Name and Date. 

For example this is what I want to Export:
![image](https://user-images.githubusercontent.com/32731974/97855441-69ad3b00-1d03-11eb-9787-35c6d90e3922.png)

This is what my Output File is named (I would like to not have the timestamp):
![image](https://user-images.githubusercontent.com/32731974/97855658-be50b600-1d03-11eb-9d31-c3d827203b82.png)

Please let me know if this is possible and how I would go by achieving this.

Regards,

**Comment by niphlod** [comment]
use `-FilePath` if you want a specific name for your file, `-Path` lets choose the filename part to dbatools.

**Comment by KavzB16** [comment]
I have used -FilePath but if I have multiple Servers in my $ServerList - they all go into one file, I would like it to be separate files for each server. So there is no way I can change that default -FilePath naming?

**Comment by nvarscar** [comment]
you can loop through your servers instead and control the filenames:
```
foreach ($server in $serverlist) {
  Get-DbaAgentJob -SqlInstance $server | Export-DbaScript -Path ".\$server-script.sql" -Append
}
```

**Comment by KavzB16** [comment]
Hey @nvarscar , thanks for that, I will try that!

**Comment by KavzB16** [comment]
@nvarscar , I have tried what you have suggested.
Seems to work perfectly, thank you very much!
