### ISSUE TITLE
Copy-dbalogin - How could we make this to use multiple streams/paths for coping faster

### ISSUE THREAD

**Issue by lostsole** [sqlcollaborative/dbatools#6953]
### Summary of new feature

To speed up the coping of Logins from one server to another, buy using multiple streams/paths

### Proposed technical details (if applicable)

My client has over 1000 Logins, we are migrating from one server to another this  Copy-dbalogin take 2 hrs to complete.  If there was a way to create multiple Steams/paths to run the copy over at the same time.

Something like an option to split into 3 (# can be change) stream/paths running at the same time, buy sort order, divide the number of user by 3 the start those 3 stream/paths at the same , spin up 3 sub PowerShell commands to run .  So that it can copy the logins over faster.

### Latest version of dbatools as of writing

1.0.124

**Comment by niphlod** [comment]
get the logins, split into arrays of your choosing and pass them to the `-Login` parameter

**Comment by lostsole** [comment]
Then to run them at the same time?( with out manually opening new PowerShell Windows to run the commands) and then send the info back so that the info is merged back together.

**Comment by niphlod** [comment]
this just depends on how you want to do things, either via -asjob or runspaces (in which case, either PoshRSJobs or [Invoke-Parallel](https://github.com/sqlcollaborative/dbatools/blob/master/internal/functions/flowcontrol/Invoke-Parallel.ps1) will do the job)

**Comment by lostsole** [comment]
Ok if I understand this ,
I have for example:
`Import-Module dbatools
#for Con
$MyInst= "SQLOldInst"
$Mlist=Get-DbaLogin -SqlInstance $MyInst
#Copy-DbaLogin -Source $localsourceInstance -Destination $localDestinationInstance -Verbose
$loginsCollection0 = @();
$loginsCollection1 = @();
$loginsCollection2 = @();
$loginsCollection3 = @();
foreach($v1 in $Mlist) {
if ($v1.name -like "0*") {
$loginsCollection0 += $v1;
} elseif ($v1.name -like "A*") {
$loginsCollection1 += $v1;
} elseif ($v1.name -like "B*") {
$loginsCollection2 += $v1;
} else {
$loginsCollection3 += $v1;
}
$loginsCollection0 | Copy-DbaLogin -Destination "NEWSqlInst"
$loginsCollection1 | Copy-DbaLogin -Destination "NEWSqlInst"
$loginsCollection3 | Copy-DbaLogin -Destination "NEWSqlInst"
$loginsCollection3 | Copy-DbaLogin -Destination "NEWSqlInst"`

The part that I don't understand is how to use the Invoke-Parallel to run those 4 commands at the same time with this command.

**Comment by lostsole** [comment]
That didn't format very well

**Comment by lostsole** [comment]
Ok So this is what I got, but Not sure if I am using it correctly:

`
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\DBATools\1.0.124\internal\functions\flowcontrol\Invoke-Parallel.ps1'
    $Mlist=Get-DbaLogin -SqlInstance $localsourceInstance;
    #https://gallery.technet.microsoft.com/scriptcenter/Split-an-array-into-parts-4357dcc1
    $loginsCollectionArray= Split-array -inArray $Mlist -parts 6;
    1..6 | Invoke-Parallel -RunspaceTimeout 60 -ScriptBlock {
        "Starting $_"
        #Start-Sleep -Seconds $_
        "If you see this, we didn't timeout $_"
        if ($_ -eq 1) {
        Write-Host "Copy-logins part 0"
        $loginsCollectionArray[0] | Copy-DbaLogin -Destination $localDestinationInstance
        }
        if($_ -eq 2) {
        Write-Host "Copy-logins part 1"
        $loginsCollectionArray[1] | Copy-DbaLogin -Destination $localDestinationInstance
        }
        if($_ -eq 3){
        Write-Host "Copy-logins part 2"
        $loginsCollectionArray[2] | Copy-DbaLogin -Destination $localDestinationInstance
        }
        if($_ -eq 4){
        Write-Host "Copy-logins part 3"
        $loginsCollectionArray[3] | Copy-DbaLogin -Destination $localDestinationInstance
        }
        if($_ -eq 5){
        Write-Host "Copy-logins part 4"
        $loginsCollectionArray[4] | Copy-DbaLogin -Destination $localDestinationInstance
        }
        if($_ -eq 6){
        Write-Host "Copy-logins part 5"
        $loginsCollectionArray[5] | Copy-DbaLogin -Destination $localDestinationInstance
        }
`

**Comment by lostsole** [comment]
Get this error for the above code:
Get-RunspaceData : Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\DBATools\1.0.124\internal\functions\flowcontrol\Invoke-Parallel.ps1:528 char:17
+                 Get-RunspaceData
+                 ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], RuntimeException
    + FullyQualifiedErrorId : NullArray,Get-RunspaceData

**Comment by lostsole** [comment]
Error fixed, was missing -ImportVariables in  Invoke-Parallel -RunspaceTimeout 60 -ScriptBlock
fixed : Invoke-Parallel -RunspaceTimeout 60 -ImportVariables -ScriptBlock {}, 

now I just need to see what other errors are comming up.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
