### ISSUE TITLE
[Bug] Get-DbaDbBackupHistory returns an exception on T-SQL statement/batch

### ISSUE THREAD

**Issue by chandrabe** [sqlcollaborative/dbatools#6955]
#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
Exception calling "ExecuteWithResults" with "1" argument(s): "An exception occurred while executing a Transact-SQL
statement or batch."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.127\allcommands.ps1:22199 char:25
+ ...             $results = $server.ConnectionContext.ExecuteWithResults($ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ExecutionFailureException
```

#### Steps to Reproduce

I was trying to get a DB Backup against a SQL 2008 R2 and both Get-DbaDbBackupHistory and Backup-DbaDatabase returns the above error

Command executed in Powershell:
```
Get-DbaDbBackupHistory -SqlInstance xxx -SqlCredential xxx -Database xxxxx -Last
```

#### Expected Behavior

The backup is done without error or we can get the backup history without error.

#### Actual Behavior

The backup is actually done but the command returns an error at the end probably while checking the backup happened correctly.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.17763.1490
dbatools latest installed : 1.0.127
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (Intel X86) 
	Apr  2 2010 15:53:02 
	Copyright (c) Microsoft Corporation
	Enterprise Edition on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (WOW64) (Hypervisor)

```

```sql
us_english
```

**Comment by andreasjordan** [comment]
The failing SQL is this:

```
SELECT
    database_name,
    MIN(database_backup_lsn) as 'FirstLsn',
    MAX(database_backup_lsn) as 'FinalLsn',
    MIN(backup_start_date) as 'MinDate',
    MAX(backup_finish_date) as 'MaxDate',
    last_recovery_fork_guid 'RecFork',
    count(1) as 'backupcount'
FROM msdb.dbo.backupset
WHERE database_name='$($db.name)'
GROUP by database_name, last_recovery_fork_guid
```

Can you insert your database name an run the query? 
Is this maybe a case issue? Is your instance case sensitive?

Maybe there is more info in the $Error[0] - can you provide this?

**Comment by wsmelton** [comment]
> Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (Intel X86)

Is it possible you can patch this system to the latest SP for 2008 R2 and verify the issue still exists?

As well, if you call the backup command using `-Debug` it will output the query it is trying to run against your instance. You can take that and run it in SSMS/ADS and maybe get a better idea of the error/syntax issue we might be hitting.

The query that gets called when our backup command calls `Get-DbaDbBackupHistory` if based on this section of code:

https://github.com/sqlcollaborative/dbatools/blob/387283e05ff3bc099db7942269d13f97e9a510d2/functions/Get-DbaDbBackupHistory.ps1#L529-L629

**Comment by wsmelton** [comment]
@Stuart-Moore may know off the top what this could be erroring on?

I recall the timestamps in the backup tables had to be patched in 2008 R2 and 2012 when the US was changing when DST was going to be in effect. Not sure if that is the issue here or not.

**Comment by Stuart-Moore** [comment]
All the appveyor tests are run against 2008r2, so I'd have thought we'd have seen any issues unless it is a patching issue

@chandrabe , could you please confirm the collation for your msdb/sql instance just in case that's causing an issue

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
