### ISSUE TITLE
[Bug] Copy-DbaDbTableData does not connect to target database explicitly

### ISSUE THREAD

**Issue by swedishstyle** [sqlcollaborative/dbatools#6956]
#### Host used

- [x ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
WARNING: [14:16:22][Copy-DbaDbTableData] Error occurred while establishing connection to | Resource ID : 2. The session limit for the database is 640 and has been reached. See 'http://go.microsoft.com/fwlink/?LinkId=267637' for assistance.
```

#### Steps to Reproduce
```
#Get list of db tables - this command is then run in parallel, as the source contains several thousand databases

foreach ($table in $db.Tables.Name) {           
    $copytabparams = @{
        SqlInstance = "$SrcSrv"
        Destination = "$TgtSrv"
        DestinationSqlCredential = $cred
        Database = "$SRCDB"
        DestinationDatabase = "$DESTDB"
        Table = "[dbo].[$table]"
        DestinationTable = "[$SRCDB].[$table]"
        KeepIdentity = $true
        KeepNulls = $true
        BatchSize = 100000
        AutoCreateTable = $true
        NotifyAfter = 100000
    }  
    
    Copy-DbaDbTableData @copytabparams -Verbose
}
```

#### Expected Behavior
Copy-DbaDbTableData should make a connection to $DESTDB

#### Actual Behavior
Copy-DbaDbTableData connects to the default database (in this case, master). This exhausts resource limits in Azure very quickly if parallel processing is used, due to strict limits on connections to master.

I've tracked it down to a specific line in the Copy-DbaDbTableCopy code: 309

The code is currently: 
```
$destServer = Connect-SqlInstance -SqlInstance $destinationserver -SqlCredential $DestinationSqlCredential
```

A simple change:
```
$destServer = Connect-SqlInstance -SqlInstance $destinationserver **-Database $DestinationDatabase** -SqlCredential $DestinationSqlCredential 
```

I've attempted to simply create a custom version of the cmdlet with that change, but with all the other bits and pieces hanging off it, would be much simpler to fix at the source :)

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

PowerShell Version        : 5.1.19041.546
dbatools latest installed : 1.0.128
Culture of OS             : en-AU

#### SQL Server:

```sql
Source: Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64)   Jan 23 2020 21:00:04   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19041: ) (Hypervisor) 

Target (Azure SQL DB): Microsoft SQL Azure (RTM) - 12.0.2000.8   Sep 11 2020 22:32:15   Copyright (C) 2019 Microsoft Corporation 
```

```sql
Source: us_english

Target: us_english
```

**Comment by andreasjordan** [comment]
Yes, that could be improved - as far as I see it. But maybe @niphlod can have a look if this change would have any siede effects.
Meanwhile you can change the allcommands.ps1 at your site - that is the file that is run at Import-Module. Depending on the version the line should be at around line 7100 to 7200.

**Comment by swedishstyle** [comment]
Thanks @andreasjordan - I was unaware of allcommands.ps1. In my early testing, adding the destination database param seems to have solved our issue, but I will need to do further testing to 100% confirm.

**Comment by swedishstyle** [comment]
@andreasjordan - unfortunately during testing, this has not seemed to solve my particular issue. I would suggest that parameter should be there regardless, but it looks like there'll have to be a different workaround for my solution.

I'm guessing something in the Connect-SqlInstance cmdlet is tripping me up, but I don't have time to dig into it at the moment

**Comment by andreasjordan** [comment]
First of all, try to use Connect-DbaInstance instead of Connect-SqlInstance as Connect-SqlInstance is only a wrapper. And in Connect-DbaInstance there is a new experimental code path that hopefully solves some problems - maybe yours as well. You can activate that by `Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true`.

**Comment by wsmelton** [comment]
In reference to Azure SQL connection, this is a known issue.

Ref: #6211

**Comment by wsmelton** [comment]
To support Azure SQL as a destination I would believe this section would have to change:

https://github.com/sqlcollaborative/dbatools/blob/a691a9b1338121e11a8872250649ae5fdc9b5507/functions/Copy-DbaDbTableData.ps1#L307-L319

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
