### ISSUE TITLE
[Bug] Install-DbaInstance: Setting AGTSVCSTARTUPTYPE causes installation failure when ACTION = "PrepareFailoverCluster"

### ISSUE THREAD

**Issue by modsqlguy** [sqlcollaborative/dbatools#6960]
### Report

When using Install-DbaInstance with ACTION = "PrepareFailoverCluster" in the -Configuration hashtable, the installation will fail. Although untested, I suspect it will also fail if the ACTION is set to "InstallFailoverCluster", "AddNode", or "CompleteFailoverCluster". I'm receiving the following error: The setting 'AGTSVCSTARTUPTYPE' is not allowed when the value of setting 'ACTION' is 'PrepareFailoverCluster'.
#### Host used

- [ ] powershell.exe
- [ ] ISE
- [x ] VS Code
- [ ] Other (please specify)

#### Errors Received

```

  Overall summary:
  Final result:                  Failed: see details below
  Exit code (Decimal):           -2068578299
  Exit facility code:            1204
  Exit error code:               5
  Exit message:                  The setting 'AGTSVCSTARTUPTYPE' is not allowed when the value of setting 'ACTION' is 'PrepareFailoverCluster'.
  Start time:                    2020-11-05 11:40:26
  End time:                      2020-11-05 11:41:04
  Requested action:              PrepareFailoverCluster
```

#### Steps to Reproduce

$Credential = Get-Credential -credential $env:UserDomain\$env:UserName
$SaCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "sa", (Get-Content "C:\Windows\Temp\sa.txt" | ConvertTo-SecureString)
$EngineCredential = Get-Credential -Message "Enter username and password for SQL Server Service Account:" 
$AgentCredential = Get-Credential  -Message "Enter username and password for SQL Server Agent Service Account:" 
$Configuration = @{
    ACTION = "PrepareFailoverCluster"
    INSTALLSHAREDDIR = "L:\Program Files\Microsoft SQL Server"
    INSTALLSHAREDWOWDIR = "L:\Program Files(x86)\Microsoft SQL Server"
    AGTSVCSTARTUPTYPE = "Disabled"
 }

Install-DbaInstance `
  -SqlInstance "WDB02", "WDB03"  `
  -Version "2019" `
  -InstanceName "MSSQLSERVER" `
  -SaCredential $SaCredential `
  -Credential $Credential `
  -Authentication "CredSSP" `
  -Configuration $Configuration `
  -Path "C:\Windows\Temp\SQLServer2019-DEV-x64-ENU" `
  -Feature "Default" `
  -AuthenticationMode "Mixed" `
  -InstancePath "L:\Program Files\Microsoft SQL Server" `
  -DataPath "F:\SQL_Data" `
  -LogPath "G:\SQL_Logs" `
  -TempPath "L:\SQL_TempDB" `
  -BackupPath "\\BackupShare"`
  -ProductID "00000-00000-00000-00000-00000"  `
  -EngineCredential $EngineCredential `
  -AgentCredential $AgentCredential `
  -Restart:$true `
  -WhatIf:$false `
  -Confirm:$false `
  -Verbose:$true 

#### Expected Behavior
Two nodes of a Windows Failover Cluster 'prepared' to become nodes of a SQL Server Failover Cluster simultaneously.

#### Actual Behavior
Error message in C:\Program Files\Microsoft SQL Server\150\Setup Bootstrap\Log\Summary.txt

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

PowerShell Version        : 5.1.18362.1110
dbatools latest installed : 1.0.128       
Culture of OS             : en-US

#### SQL Server:

Install not completed

**Comment by andreasjordan** [comment]
Have you read the section "Prepare Failover Cluster Parameters" at https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt ? AGTSVCSTARTUPTYPE is not listed there - so the error message is correct. 

> Although untested, I suspect it will also fail if the ACTION is set to "InstallFailoverCluster", "AddNode", or "CompleteFailoverCluster"

I would give "ACTION = InstallFailoverCluster" on the first node and then "ACTION = AddNode" on the socond node a try. 
Do you need to first prepare the cluster and then complete it? Or do you just want to install the whole cluster with only one command?

**Comment by nvarscar** [comment]
The problem here is that the default configuration map built inside the function already contains AGTSVCSTARTUPTYPE member even if you don't explicitly specify it. So, no matter what you do, the ini file would end up having AGTSVCSTARTUPTYPE in it. 
The workaround right now would be to use `-ConfigurationFile` parameter that would accept a pre-configured ini file. In this case, the function would simply ship the file to the remote server and use it as is.

I'll try to reproduce your scenario in my lab and perhaps would come up with a solution.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.

**Comment by conseilit** [comment]
Hi
I've the same issue with version 1.1.95.
The action is InstallFailoverCluster and the same error is returned.
The setting 'AGTSVCSTARTUPTYPE' is not allowed when the value of setting 'ACTION' is 'InstallFailoverCluster'.

I tried to update the ps1 file to remove the two parameters, for SQL Server and for the SQL Agent, the problem still occurs.

**Comment by andreasjordan** [comment]
Can you provide all parameters that you use with Install-DbaInstance?
Any maybe have a look at: https://github.com/dataplat/dbatools/discussions/7447

**Comment by conseilit** [comment]
Yes, I've seen the 7447 page. 

$paramsInstallFailoverCluster = @{
    SaveConfiguration     = 'D:\InstallScripts'
    ComputerName          = $SQL1
    InstanceName          = $clusterSqlInstance
    
    Configuration      = @{
        ACTION                     = 'InstallFailoverCluster'
        FAILOVERCLUSTERNETWORKNAME = $clusterSqlName
        FAILOVERCLUSTERDISKS       = "DataSQL"
        FAILOVERCLUSTERGROUP       = "SQL Server ($clusterSqlInstance)"
        FAILOVERCLUSTERIPADDRESSES = "IPv4;DHCP;Cluster Network 1;"
        INSTALLSQLDATADIR          = "C:\ClusterStorage\Volume1"
    }


    Version               = $clusterSqlVersion
    SQLCOLLATION          = 'Latin1_General_CI_AS'
    Feature               = 'Engine'
    AuthenticationMode    = 'Mixed'

    SaCredential          = $saCred
    AdminAccount          = $CurrentUser.UserName
    Credential            = $InstallCred

    EngineCredential      = $sqlServiceCredential
    AgentCredential       = $sqlServiceCredential
    Path                  = '\\formation\sources'
    UpdateSourcePath      = '\\formation\sources'
    Restart               = $true
    Confirm               = $false
}

The main difference with page 7447 is the use of a CSV volume and  DHCP. No fancy stuff.

**Comment by andreasjordan** [comment]
Are you sure running the lastest release?

This is the relevant code:

```
            if (Test-Bound -ParameterName ConfigurationFile) {
                try {
                    $config = Read-IniFile -Path $ConfigurationFile
                } catch {
                    Stop-Function -Message "Failed to read config file $ConfigurationFile" -ErrorRecord $_
                }
            } elseif ($Configuration.ACTION) {
                # build minimal config if a custom ACTION is provided
                $config = @{
                    $mainKey = @{
                        INSTANCENAME = $instance
                        FEATURES     = $featureList
                        QUIET        = "True"
                    }
                }
                # To support failover cluster instance:
                if ($Configuration.ACTION -in 'AddNode', 'RemoveNode') {
                    $config.$mainKey.Remove('FEATURES')
                }
            } else {
                # determine a default user to assign sqladmin permissions
                if ($Credential) {
                    $defaultAdminAccount = $Credential.UserName
                } else {
                    if ($env:USERDOMAIN) {
                        $defaultAdminAccount = "$env:USERDOMAIN\$env:USERNAME"
                    } else {
                        if ($computer.IsLocalHost) {
                            $defaultAdminAccount = "$($resolvedName.ComputerName)\$env:USERNAME"
                        } else {
                            $defaultAdminAccount = $env:USERNAME
                        }
                    }
                }
                # determine browser startup
                if ($instance -eq 'MSSQLSERVER') { $browserStartup = 'Manual' }
                else { $browserStartup = 'Automatic' }
                # build generic config based on parameters
                $config = @{
                    $mainKey = @{
                        ACTION                = "Install"
                        AGTSVCSTARTUPTYPE     = "Automatic"
                        BROWSERSVCSTARTUPTYPE = $browserStartup
                        ENABLERANU            = "False"
                        ERRORREPORTING        = "False"
                        FEATURES              = $featureList
                        FILESTREAMLEVEL       = "0"
                        HELP                  = "False"
                        INDICATEPROGRESS      = "False"
                        INSTANCEID            = $instance
                        INSTANCENAME          = $instance
                        ISSVCSTARTUPTYPE      = "Automatic"
                        QUIET                 = "True"
                        QUIETSIMPLE           = "False"
                        SQLSVCSTARTUPTYPE     = "Automatic"
                        SQLSYSADMINACCOUNTS   = $defaultAdminAccount
                        SQMREPORTING          = "False"
                        TCPENABLED            = "1"
                        UPDATEENABLED         = "False"
                        X86                   = "False"
                    }
                }
            }
```

So AGTSVCSTARTUPTYPE is only set, if $Configuration.ACTION is not set. 

So I assume that you are not running the correct code. What does `Get-Module dbatools` return?

**Comment by conseilit** [comment]
That's correct.



![image](https://user-images.githubusercontent.com/35958968/169244423-cb44eb48-438f-4f71-9392-1479a30083c8.png)


Looking at the summary.txt file, the action is set. And also the startup type.
User Input Settings:
  ACTION:                        InstallFailoverCluster
  AGTDOMAINGROUP:                <empty>
  AGTSVCACCOUNT:                 Conseilit\gMSAprevoir
  AGTSVCPASSWORD:                <empty>
  ASBACKUPDIR:                   Backup
  ASCOLLATION:                   Latin1_General_CI_AS
  ASCONFIGDIR:                   Config
  ASDATADIR:                     Data
  ASLOGDIR:                      Log
  ASPROVIDERMSOLAP:              1
  ASSERVERMODE:                  TABULAR
  ASSVCACCOUNT:                  <empty>
  ASSVCPASSWORD:                 <empty>
  ASSVCSTARTUPTYPE:              Automatic
  ASSYSADMINACCOUNTS:            <empty>
  ASTEMPDIR:                     Temp
  COMMFABRICENCRYPTION:          0
  COMMFABRICNETWORKLEVEL:        0
  COMMFABRICPORT:                0

**Comment by andreasjordan** [comment]
I just this morning installed a failover cluster at a client - so "works on my maschine". So I'm out of ideas at the moment.

**Comment by conseilit** [comment]
I'm also very confused.
Finally, I succeed to install the FCI, but not with gMSA, not the deal here.
I’ve added the following lines of code just after the check to support the FCI.

                 if ($Configuration.ACTION -in 'PrepareFailoverCluster', 'InstallFailoverCluster') {
                    $config.$mainKey.Remove('AGTSVCSTARTUPTYPE')
                    $config.$mainKey.Remove('SQLSVCSTARTUPTYPE' )
                } 

But something weird … On a previous try, the summary.txt file reported the wrong Service Account. The one of a previous try. As if there were a kind of cache somewhere. So, I’m wondering if my update was the reason of success.

V1.1.95 was the only one installed. I’m going to remove everything on my jumbox, reboot, reinstall dbaTools and try again.

I will keep you posted.
Thanks for the help, Andreas.
