### ISSUE TITLE
Get-DbaLastBackup Shows Wrong Last Backup Timestamp on AlwaysOn Replicas 

### ISSUE THREAD

**Issue by MaxNulls** [sqlcollaborative/dbatools#6964]
This is a 4 node always on cluster and the the backups are done on the primary only. The report is for a database in the primary node. The result shows wrong last backup time.

![Capture2323](https://user-images.githubusercontent.com/71079622/98688527-f1fd9280-2338-11eb-852b-b1133151cfa0.png)

**Comment by andreasjordan** [comment]
Do you use the latest version of dbatools?

**Comment by MaxNulls** [comment]
Hi, is there a command to check version? Thanks.

**Comment by andreasjordan** [comment]
Get-Module -Name dbatools -ListAvailable

**Comment by MaxNulls** [comment]
> Get-Module -Name dbatools -ListAvailable

Thank you, I am on 1.0.97

**Comment by andreasjordan** [comment]
Can you upgrade to 1.0.130? There was a fix for that problem a few versions ago.

**Comment by MaxNulls** [comment]
> Can you upgrade to 1.0.130? There was a fix for that problem a few versions ago.

I apologize for asking this but can you please give me the command to upgrade? I appreciate the help.

**Comment by andreasjordan** [comment]
It depends a bit on how you installed the module. If you installed it with `Install-Module dbatools` from the PSGallery, you just need to execute `Update-Module dbatools` from an elevated powershell session. Do this in a new powershell session where the old version is not loaded yet.

**Comment by MaxNulls** [comment]
Thanks, I was able to update it. 
That did fix the issue, I appreciate your help. thank you!

**Comment by andreasjordan** [comment]
I'm glad I could help.
