### ISSUE TITLE
DBATools - is it possible to export Summary Log File after using Update-DbaInstance

### ISSUE THREAD

**Issue by KavzB16** [sqlcollaborative/dbatools#6967]
Good day,

After I run a patch using `-Update-DbaInstance`, is it possible with DBATools to export the Summary Log File to another location.
Please view the picture with the highlighted file:
![image](https://user-images.githubusercontent.com/32731974/98820783-4d15af00-2437-11eb-8d3b-6e6bcc60303d.png)

Thanks and Regards

**Comment by niphlod** [comment]
something among the lines of 
```
$server = Connect-DbaInstance "localhost"
$commonLogDir = Get-ChildItem -Path "C:\Program Files\Microsoft SQL Server\$($server.Major)0\Setup Bootstrap\Log" -Directory

$lastSetupFolder = $commonLogDir | Sort-Object Name | Select-Object -Last 1

Get-ChildItem $lastSetupFolder.FullName | Where-Object Name -Like "Summary_*"
```

should work

**Comment by KavzB16** [comment]
Hi @niphlod , that worked perfectly, thank you!
