### ISSUE TITLE
Update-DbaInstance Progress Bar not working?

### ISSUE THREAD

**Issue by KavzB16** [sqlcollaborative/dbatools#6974]
Hi there,

I was busy patching some servers this weekend with the following script:
`foreach ($ServerName in $ServerList)
{Update-DbaInstance -ComputerName $ServerName -Path $PATCH -Credential $cred -Version $version -Restart | Out-File -FilePath $FILENAME1 -APPEND}`

Is it because I am `|Out-File`, as I need to export the Success/Failure File?

I noticed that the progress bar did not do anything although I was informed when it was extracting and installing.

The progress bar did work when the machines had to reboot though, is there anything else I need to add to the script to get the bar to work?

Regards

**Comment by nvarscar** [comment]
Maybe try to capture the output in the variable? I'm not sure how the progress bars would be affected when piping is involved.
Also, the command supports multithreading, are you intentionally updating servers one by one?

**Comment by KavzB16** [comment]
Hey @nvarscar , I have removed the piping, doing a test run and I see that the progress bar still does not indicate how far along the installation is, is there another way to get progress? Yes I am intentionally updating servers one by one as this was the request from management. As you can see in the pic below, the progress bar does not give an indication.

`Update-DbaInstance -ComputerName $ServerName -Path $FILENAME -Credential $cred -Version $version -Restart `

![image](https://user-images.githubusercontent.com/32731974/99902180-81edf580-2cc4-11eb-9b9d-0625f84243fd.png)

**Comment by KavzB16** [comment]
Is there another way to get the progress of the install, such as in the PowerShell Console?

**Comment by wsmelton** [comment]
The patch installation progress itself is what you are looking for?

@nvarscar this would be an option if we allowed users to pass `qs` but it blocks passing this to the arguments list parameter because we seem to use `/quiet` in our call.

If we allowed the use of `qs` in some fashion that would provide a visual UI of the patch installation...

![image](https://user-images.githubusercontent.com/11204251/100555866-f8aa6600-3263-11eb-8d15-290de9195cd8.png)

**Comment by KavzB16** [comment]
Hey @wsmelton, yes sir that is exactly what I am talking about, You would be able to see the extraction happening, if you are on the Server you are patching, if you are doing it remotely (patch from a CMS Server) then you do not see the progress bar move in PS, then when the patch installs, there is also no progress bar, the only time the progress bar does work is when the machine reboots.

Would there be another way to get progress in the mean time or would we have to wait for your above mentioned fix to be implemented?

**Comment by nvarscar** [comment]
@wsmelton this would work for a local session, but won't for remote ones. On top of that, I would rather not add anything interactive to the command, just in case.

@KavzB16 Update-DbaInstance is a wrapper for SQL Server setup, it has no knowledge of the installation progress. The progress bar in question was implemented to show you the current stage of the whole process, not the setup progress.

**Comment by KavzB16** [comment]
@nvarscar, so since it is a wrapper, my understanding is that we will only know where the current stage is such as extracting and installing but there will be no progress indicator, please correct me if I am wrong?

**Comment by nvarscar** [comment]
Yes, that is correct.

**Comment by KavzB16** [comment]
Thank you!
