### ISSUE TITLE
Restore-DbaBackup Name

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#698]
@PowerDBAKlaas and I were talking about the name of the command after I accidentally called it Restore-DbaDatabase

### Should it be renamed from Restore-DbaBackup to Restore-DbaDatabase

I proposed that perhaps not if it can restore more than a database

![image](https://cloud.githubusercontent.com/assets/8278033/22791398/85f822f8-eee9-11e6-97fe-4cdda126ed3d.png)

Klaas countered that the syntax is RESTORE DATABASE in T-SQL.

Microsoft also named their cmdlet Restore-SqlDatabase.

Please discuss and resolve prior to tomorrow's release if at all possible!

**Comment by Stuart-Moore** [comment]
Perfectly happy either way.

 TBH, I've tried tab completing Restore-DbaDa many times while working on it.

**Comment by ctrlbold** [comment]
yeah, it feels more natural to me -- that's what my brain referred to it as, naturally. Let's go with Restore-DbaDatabase. Thank you 💃

**Comment by ctrlbold** [comment]
Thanks for fix! will update psd1
