### ISSUE TITLE
[Bug] Set-DbaLogin is performing no action

### ISSUE THREAD

**Issue by firthro** [sqlcollaborative/dbatools#6986]
#### Host used

- [ ] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Steps to Reproduce

```powershell
Set-DbaLogin -SqlInstance 'sintinfsqlw001.sg.schroders.com' -Login sa -Disable -WhatIf
```
#### Expected Behavior

I expect it to disable logins, or rename etc
-SqlInstance 'instancename' -Login sa -Disable

#### Actual Behavior

Nothing happens at all, a WHatif returns nothing either.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script
Set-DbaLogin -SqlInstance 'instancename.fqdn' -Login sa -Disable -WhatIf

```powershell
PowerShell Version        : 5.1.14393.3866
dbatools latest installed : 1.0.84
Culture of OS             : en-
```

#### SQL Server:
```
Microsoft SQL Server 2017 (RTM-CU22) (KB4577467) - 14.0.3356.20 (X64)   Aug 20 2020 22:33:27   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

```sql
us_english
```

**Comment by ClaudioESSilva** [comment]
Hi @firthro, can you please edit your submission and fulfil the details?

Thanks

**Comment by MikeyBronowski** [comment]
Seems related to #6336
