### ISSUE TITLE
[Bug] Restore-DbaDatabase honoring the VerifyOnly switch with OutputScriptOnly

### ISSUE THREAD

**Issue by MCTSQL** [sqlcollaborative/dbatools#6987]
#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
replace THIS text WITH the OUTPUT of -- $ERROR[0] | SELECT *
```

#### Steps to Reproduce

```
$SqlCredential=Get-Credential;
$SqlInstance='SqlInstance';
$Path='Path';
$DatabaseName='DatabaseName';
Restore-DbaDatabase -SqlCredential $SqlCredential -SqlInstance $SqlInstance -Path $Path -DatabaseName $DatabaseName -VerifyOnly -OutputScriptOnly;
```

#### Expected Behavior
Expected:

`RESTORE VERIFYONLY FROM DISK = 'Path\DatabaseName.bak'`

#### Actual Behavior
Actual:

```
RESTORE DATABASE [DatabaseName] FROM  DISK = N'DatabaseName.bak' WITH  FILE = 1,  MOVE N'DatabaseName' TO N'<DataPath>\DatabaseName.mdf',  MOVE N'DatabaseName_log' TO N'<LogPath>\DatabaseName_log.ldf',  NOUNLOAD,  STATS = 10
```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.17763.1490
dbatools latest installed : 1.0.128
Culture of OS             : en-US
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```
Not Applicable

```sql
/* REPLACE WITH output of @@LANGUAGE */
```
Not Applicable

**Comment by MCTSQL** [comment]
-also verified this is still happening in dbatools v1.0.131

**Comment by wsmelton** [comment]
SMO does not provide the option to script out the verify statement, so from that, the command does not support it. We need to add a check for this where a warning is thrown that these two parameters cannot be used together (-VerifyOnly and -OutputScriptOnly).

https://github.com/sqlcollaborative/dbatools/blob/a691a9b1338121e11a8872250649ae5fdc9b5507/functions/Invoke-DbaAdvancedRestore.ps1#L327-L340

**Comment by Stuart-Moore** [comment]
Added a check, it both are specified function will return an explanatory message and exit

Have updated CBH to reflect this
