### ISSUE TITLE
Few bugs - Restore-DbaBackup

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#699]
Awesome command! Can't wait!

- [x] I believe that Restore-DbaBackup is supposed to restore to the default directory. It is not.

![image](https://cloud.githubusercontent.com/assets/8278033/22791566/1f966046-eeea-11e6-930a-54d3edfbf824.png)

I think this i using the default directory from the original server.  My localhost uses E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL

- [x] It did not catch that in the failure and said it restored successfully
- [x] There should be a status or notes column that reports the status of successful restores. All Write-Outputs should be Write-Verbose
- [ ] If the person is running this against localhost, do they need RunAs permissions? if so, please catch ".", "localhost" or $env:computername  and write-warning then exit.

- [x] We have moved away from red errors and now use Warnings. Please catch this error and inform the user using Warning that they must use -WithReplace (or Force? Does this command support force?). Perhaps check to see if it exists and withrepalce is not specified.
![image](https://cloud.githubusercontent.com/assets/8278033/22791810/d8e925f6-eeea-11e6-95ee-61d96bbaa0a7.png)

Output looks nice, Except the write output

(for those of you interested)

![image](https://cloud.githubusercontent.com/assets/8278033/22791912/3aff4fcc-eeeb-11e6-9145-4eb5d2d8a8da.png)

**Comment by Zhunya** [comment]
Stuart is working on issue with default directory.
New idea - reuse files if -Withreplace specified (no other parameters like -Destination* or -DefaultDBLocation)

**Comment by ctrlbold** [comment]
Thanks @Zhunya! @Stuart-Moore - have a lot of these checks/functions in copy-sqldatabase that you may wanna check out

**Comment by Stuart-Moore** [comment]
I was going with the defaults T-SQL restore action, which is to restore the db to the path it was backed up from.

Zhunya's request was for a switch that indicated to default to the target servers default paths? Does that work? I think leaving the default as it is is better.  I'm sure a lot of shops are like mine where dev-test-prod have very similar fs layouts because of this.

Will tidy up the write and throw stuff.

There would have been an extra message if it had been completed. But that doesn't look good so I'll fix it up.

As far as I know they don't need RunAs. As long as they can connect to the SQL instance then it should then run as the SQL Server account.

No force, it's WithReplace.

**Comment by Zhunya** [comment]
> I think leaving the default as it is is better.
Yes, its ok, but having one switch for target server default path for data and log files will save our time

> need RunAs
I'm always RunAs other user a Powershell console for all administrative work with SQL Server, its for security reasons

**Comment by Stuart-Moore** [comment]
Last push should hopefully have fixed all these concerns.

It's a single switch to use both server defaults.

I'm just off to watch a comedian doctor so I'll pick things back up later
I'd there's any feedback

**Comment by ctrlbold** [comment]
I most definitely wouldn't want this not to have an easy button by default. Ease of use is something that people are huge fans of with Copy-SqlDatabase -- no thinking, just works out of the box.  

If your heart is set on reusing the source structure by default, we could attempt reusing the source directory, but we'd have to ensure the destination directory exists, and if not, rebuild file structure to use destination default.  I kinda like that. 

@ClaudioESSilva, @PowerDBAKlaas, and @Stuart-Moore -- if we end up doing that, should Copy-SqlDatabase be changed to do test reuse structure and if it doesnt exist then use defaults? Or would people prefer defaults database dirs always? I'd like the behavior to match in both.

**Comment by Stuart-Moore** [comment]
So go with Sql standard, but offer a parachute?

Don't think that would be too had to do (famous last words). I'll grab more coffee and have a look. Hardest bit will be working out where to do it as as don't get the source path reliably until post file scan.

**Comment by PowerDBAKlaas** [comment]
@Stuart-Moore I feel this calls for another flow chart. 😄  The other one is really helpful.

I assume the options are:
- Keep the file locations as they were on the source. Directories may not exist on the destination. Should we create them? Worse, Drives may not exist. (This is SQL Server's default, but the least preferrable from my point of view)
- Use the destination default directories. This should always work, but restricts to one data and one log directory, which may impact DB performance and logic. (Is this the -Easy option?)
- User assigned directories. Does this allow for more than one? If I have 4 data files and I want 3 to be on one drive and the 4th on another, how can we do that? Would it be better to offer DestinationLocation per file? (This is the complicated one, but the one that brings you fame.)

@ctrlbold is it realistic to use the same logic in Restore-DbaDatabase and Copy-SqlDatabase? It would certainly be user friendly.

**Comment by Stuart-Moore** [comment]
But that means visio 🤕 😉 

3 actually exists, just not well surfaced as it requires the user to build a hashtable:

$RestoreLocation = @{'DataFile1' = 'c:\datadir\datafile1.mdf'; 'DataFile2'='d:\datadir\datafile2.mdf'; etc}

Restore-DbaDatabase -path \\server\backups -sqlserver Server16 -FileMapping $RestoreLocation

I was hoping to find time to make building that hashtable easier for users, but that's not happened. Every file has to be specified, and that includes files that appear during the backups. So I wanted to have a split in the restore process that popped up a dialogue of some sorts and they could enter values. power users would have discovered it and worked it out 

2 can be used now by using -UseDestinationDefaultDirectories

I could offer -UseSourceDirectories as well

Then it would just be a case of picking which one is the default.

**Comment by PowerDBAKlaas** [comment]
ha, that's already great versatility

for ad hoc use or for less experienced users, making an interactive solution is very handy, but that should not be inside a function, but in a script.
I think the hashtable solution is great for now, and maybe later we can have a script that prompts for parameters and options and calls the function(s) accordingly.

**Comment by Stuart-Moore** [comment]
So which one do we want to be default, source or destination? Or do we wait for @ctrlbold to make the decision?

And I'm not sure what was mean by RunAs? Are we just talking about someone having to elevate their own session, or something with the function to do the elevation? Are there any examples in other functions?

**Comment by PowerDBAKlaas** [comment]
I'd think to choose the one with the least risk as default, wouldn't that be destination?

I'm sure "RunAs" means check if the user has elevated permission first if that's necessary.
I don't think we have that in use yet, but there's a trello card for it, and yesterday I added a link there to a function by Boe Prox that does the check.
https://trello.com/c/GUmAahmH/142-if-a-command-requires-admin-on-localhost-we-need-a-check

**Comment by Stuart-Moore** [comment]
OK, I'll sort that out next

There's nothing in this functionality that needs 'admin' as such. As long as they're running an account which can access the backup files they want, and can provide credentials to Sql Server to do the same then they're good to go.

**Comment by Stuart-Moore** [comment]
Going to work this based on this table:
|         | FileMapping | DestinationDefault | SourceLocations | DestinationDataDirectory | DestinationLogDirectory |
|---------|-------------|--------------------|-----------------|--------------------------|-------------------------|
|         |      y      |          n         |        n        |             n            |            n            |
| Default |      n      |          y         |        n        |             n            |            n            |
|         |      n      |          n         |        y        |             n            |            n            |
|         |      n      |          n         |        n        |             y            |            n            |
|         |      n      |          n         |        n        |             y            |            y            |

So that's DestinationDefault is the default with nothing else provided
If anything doesn't match those usage patterns then I'll write-warning and exit

**Comment by Stuart-Moore** [comment]
New parameters ordering is now down.

Not happy with the coding style, but working out a proper logical comparison was getting complex for maintenance

**Comment by Stuart-Moore** [comment]
All of this was fixed prior to Snowball going live I believe?

**Comment by ctrlbold** [comment]
Sure was!

**Comment by ctrlbold** [comment]
@Stuart-Moore - that table is awesome. dbatools.io supports markdown. would you be able to add it to the Restore-DbaDatabase page?
