### ISSUE TITLE
spin up copy of database shell for restore

### ISSUE THREAD

**Issue by cmuncan** [sqlcollaborative/dbatools#6990]
### Summary of new feature

typically when creating a new database from scratch, we just base it off of a pre-existing database.  for example, we have db_d1, db_d2, db_d3 and now we want to create db_d4, normally we right-click on a database that will be used as the shell and pick Script Database as -> CREATE To -> New Query Editor Window

![image](https://user-images.githubusercontent.com/67800960/100161764-18b2e180-2e80-11eb-8692-5037c9f29820.png)

We then make a few minor changes, like changing the dbname from db_d3 to db_d4 in our case.  Also update the file names from *db_d3* to *db_d4*

![image](https://user-images.githubusercontent.com/67800960/100161939-6af40280-2e80-11eb-8f72-cec3fe706d99.png)

then we can just run the script as is and we get a valid empty shell of a database.  I think this is similar to `Invoke-DbaDbClone` but I think the file location is what I am looking for too.  Or how does `Invoke-DbaDbClone` handle the file name(s)?

### Latest version of dbatools as of writing
current...I am always at current

**Comment by wsmelton** [comment]
`Invoke-DbaDbClone` is not for the purpose of creating new databases. It utilizes `DBCC CLONEDATABASE` feature in certain versions of SQL Server.

**Comment by wsmelton** [comment]
As the documentation states the file names are handled internally by SQL Server, not something we would control from our command:

> All files in the target database will inherit the size and growth settings from the model database. The file names for the destination database will follow the source_file_name _underscore_random number convention. If the generated file name already exists in the destination folder, DBCC CLONEDATABASE will fail.

If you are looking for something more custom I would look at `Export-DbaScript`. I believe it could be used to generate the create script for the database and then using regex would allow you to manipulate the path or other values of that script.

You might also take a look at Sander's module: [dbaclone](https://github.com/sqlcollaborative/dbaclone) as it might have more features to your liking.
