### ISSUE TITLE
Restore-DbaDatabase - Add new parameter "-DbOwner" to switch login context before restore

### ISSUE THREAD

**Issue by relsna** [sqlcollaborative/dbatools#6992]
### Summary of new feature

Add a new parameter to Restore-DbaDatabase that would switch context to another login before the Restore.

**Scenario:**
I have hundreds of databases in Availability Groups.

- The version is 2014, so there's no Automatic Seeding.

- Plus, there are no shared folders that can be used between instances.

- The requirement is that all databases must have "sa" as the database owner

So my procedure to automate adding a database (like a new SharePoint "ContentDB") to an existing availability group is basically the following in T-SQL:

1. Backups on the primary replica
2. Copy backups files to the secondary replica
3. On secondary: **EXECUTE AS LOGIN = 'sa' + RESTORE.... WITH Norecovery.**
4. Add database to AG

The "EXECUTE AS LOGIN" makes sure the database on the secondary replica is not restored using my domain account.
I can't afford to do a failover to the secondary after a database is added to the AG.

Using dbatools it doesn't seem possible to perform a restore using another login context like it is in T-SQL.

**New parameter?**
I would have loved to have a "-DbOwner" parameter on Restore-DbaDatabase to do this.

Would it be feasible to add such a feature?

Obviously, Set-DbaDbOwner can't alter a database in Restoring state.

```
PS C:\> Set-DbaDbOwner -SqlInstance $Instance -Database $Db -TargetLogin 'sa' -Verbose

WARNING: [16:39:40][Set-DbaDbOwner] Database [$Db] is not accessible. Skipping.
```

I hope that makes sense. Thanks.

### Latest version of dbatools as of writing

1.0.133

**Comment by niphlod** [comment]
is sa on the destination disabled ? because if it isn't, you could just connect to the dest with sa credentials instead of your own.
That being said, I totally get the usecase, although I'm not so sure on how to achieve that with SMO restore.
pinging @Stuart-Moore , aka the god of restore, as I feel there's nothing native in microsoft.sqlserver.management.smo.restore for this and we may have to tinkle with the generated script within Invoke-DbaAdvancedRestore, then surface the new parameter up to all functions using it.

**Comment by relsna** [comment]
> is sa on the destination disabled ? because if it isn't, you could just connect to the dest with sa credentials instead of your own.
Most of the time sa is enabled, but what do you mean ? I can't run a PowerShell script with sa credentials right ?
I understand it's not an easy feature to add. For this usecase I can either stay with my PowerShell script that generate T-SQL (execute with login = 'sa'... restore) so without dbatools. Or I could have an Agent Job to change the owner after a Failover occurs.

**Comment by wsmelton** [comment]
Is there any reason you cannot simply pass in the SqlCredential when you call `Restore-DbaDatabase`? That would be the proper way of doing this from PowerShell's perspective.

`Restore-DbaDatabase -SqlInstance YourReplica -SqlCredential $yourSaAccount ...`

**Comment by wsmelton** [comment]
We use SMO `Microsoft.SqlServer.Management.Smo.Restore` class for restore processing and there is no viable option for us to add in an `EXECUTE AS LOGIN` statement to that object. 

If the use of the `-SqlCredential` is not an option and you still need to use the `EXECUTE AS` statement I would recommend using this process:

1. Backups on the primary replica
1. Copy backups files to the secondary replica
1. Call `Restore-DbaDatabase` using the `-OutputScriptOnly` parameter. 
1. Insert the `EXECUTE AS LOGIN = 'sa'` statement into the script output (at the start)
1. Call the T-SQL code on replica

Something like this should work:

```powershell
$script= Restore-DbaDatabase ... -OutputScriptOnly
$script = "EXECUTE AS LOGIN = 'sa';`n" + $script
Invoke-DbaQuery ... -Query $script
```
```

**Comment by nvarscar** [comment]
The use-case is absolutely valid, there is no other way to change the DB owner on a secondary AG database. There is also a workaround:
```powershell
$server = Connect-DbaInstance -SqlInstance ...
Invoke-DbaQuery -SqlInstance $server -Query "EXECUTE AS LOGIN = 'sa'"
Restore-DbaDatabase -SqlInstance $server ...
```

But it would be nice to add this to the command so that this connection dance won't be necessary.

**Comment by Stuart-Moore** [comment]
Doesn't work like that. The SMO connector appears to issue a default REVERT after each query:

![image](https://user-images.githubusercontent.com/5613670/101370392-5a408500-38a1-11eb-94df-7beb63f9645c.png)

As you can see, the only way it works when the EXECUTE AS is in the same query. This can't be done with an SMO restore as there is no way of issuing the EXECUTE AS as part of the restores.

The only way to get around this would be to run the first part of the restore as a script rather than as the current SMO.restore call, so that's what I did. Pester  test included to ensure it doesn't get undone in future

**Comment by nvarscar** [comment]
Perhaps I'm missing a crucial part: the WITH NO REVERT statement.
https://docs.microsoft.com/en-us/sql/t-sql/statements/execute-as-transact-sql?view=sql-server-ver15#using-with-no-revert

**Comment by relsna** [comment]
Thank you all for your feedback, I didn't try the workarounds you guys proposed yet but I will do for sure.
Thank you @Stuart-Moore for working on the issue.
Would it be possible to have the "sa" account name as a parameter?
In some places where I do consulting they rename all their sa accounts to something like "SA_NOT_USED" for example. In this case, the login is also disabled but it still works fine with EXECUTE AS LOGIN.
Another way to do it would be to retrieve the name querying sys.syslogins as the SA account always has the same SID. I don't if it's better like this.

**Comment by wsmelton** [comment]
To allow passing in a login name @Stuart-Moore I'd think it best to validate the login exists. Not sure if the error returned if it did not would be clear?

**Comment by Stuart-Moore** [comment]
@nvarscar that doesn't work:
![image](https://user-images.githubusercontent.com/5613670/101607428-8290c680-39fc-11eb-89f5-02c40b48c403.png)
![image](https://user-images.githubusercontent.com/5613670/101608849-26c73d00-39fe-11eb-82ef-1be481e73d11.png)
Appears SMO does an implicit revert after each query, so combining them into a single query statement makes sure it works

**Comment by nvarscar** [comment]
@Stuart-Moore Okay, so this one works. I'm not sure if there were changes to invoke/query methods (those are custom methods provided by dbatools), but it seems they use their own connection now, at least I can't explain it any other way.

```powershell
[220.0ms] Users/kkravtsov> Invoke-DbaQuery -SqlInstance $c -Query 'EXECUTE AS login = ''sa'' WITH NO REVERT;'
[104.0ms] Users/kkravtsov> Invoke-DbaQuery -SqlInstance $c -Query 'SELECT SUSER_NAME()'

Column1
-------
sa

[ 49.0ms] Users/kkravtsov> Invoke-DbaQuery -SqlInstance $c -Query 'EXECUTE AS login = ''testlogin'' WITH NO REVERT;'
[ 33.0ms] Users/kkravtsov> Invoke-DbaQuery -SqlInstance $c -Query 'SELECT SUSER_NAME()'

Column1
-------
testlogin

[ 30.0ms] Users/kkravtsov> Invoke-DbaQuery -SqlInstance $c -Query 'EXECUTE AS login = ''sysadmin'' WITH NO REVERT;'
WARNING: [15:36:34][Invoke-DbaQuery] [localhost] Failed during execution | Cannot execute as the server principal because the principal "sysadmin" does not exist, this type of principal cannot be impersonated, or you do not have permission.
```
