### ISSUE TITLE
[Bug] Set-DbaDbOwner - SMO is not updated by .SetOwner method

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7010]
As Set-DbaDbOwner just uses $db.SetOwner($TargetLogin) to update the owner, let's test directly with the SMO:

```
$db = New-DbaDatabase -SqlInstance SRV1 -Name Test01
$db.Owner
$db.SetOwner('sa')
$db.Owner
$db.Refresh()
$db.Owner
```

![image](https://user-images.githubusercontent.com/66946165/100921671-2b12c800-34dd-11eb-937a-336cb8b1eb5e.png)

So my questions are:
Is this a bug in the SMO and should be fixed there? I think yes.
Should we meanwhile add a `$db.Refresh()` after the `$db.SetOwner($TargetLogin)`? I think yes.

What do the others think?

**Comment by niphlod** [comment]
We try to avoid .refresh() because it's an expensive call, usually .

Il mer 2 dic 2020, 20:34 Andreas Jordan <notifications@github.com> ha
scritto:

**Comment by andreasjordan** [comment]
I know.

I found this bug while working on this demo: 
https://github.com/andreasjordan/demos/blob/master/AlwaysOn_DatabaseOwner/01_database_owner.ps1

```
$SqlInstances = 'SRV1', 'SRV2'
$server = Connect-DbaInstance -SqlInstance $SqlInstances

$null = Set-DbaDbOwner -SqlInstance $server[0] -Database $DatabaseName -TargetLogin $credAdmin3.UserName
Get-DbaDatabase -SqlInstance $server -Database $DatabaseName | Format-Table -Property SqlInstance, Name, Owner         # Ups, not updated - but maybe its only the SMO...
Get-DbaDatabase -SqlInstance $SqlInstances -Database $DatabaseName | Format-Table -Property SqlInstance, Name, Owner   # Yes, that's a bug...
# Let's refresh the SMO (like hitting F5 in SSMS):
$server[0].Databases[$DatabaseName].Refresh()
Get-DbaDatabase -SqlInstance $server -Database $DatabaseName | Format-Table -Property SqlInstance, Name, Owner         # Ok, now the correct info is there
```

I like the idea of reusing one server SMO for every call - but I frequently run into problems like this.

**Comment by niphlod** [comment]
groan, so yes, let's add it and put a comment in referring to this issue so we remember it's due to a SMO bug ^_^

**Comment by andreasjordan** [comment]
Where can we open an issue with the SMO?

**Comment by niphlod** [comment]
huh, personally I don't know but I do know some of our "big guns" know how .... @potatoqualitee , @wsmelton  ?

**Comment by wsmelton** [comment]
The `Refresh()` method will show up on a number of objects in SMO, it does not refresh the connection and retrieve the object all over again. You have to look at what type of object is being passed out by SMO. For `New-DbaDatabase` it is just a `Microsoft.SqlServer.Management.Smo.ScriptNameObjectBase` type, which the `Refresh()` method on that object does nothing around making another call to SQL Server. It is "refreshing" the object in the current session of PowerShell and that is it.

I see this working as expected:

![image](https://user-images.githubusercontent.com/11204251/101024695-16185200-353a-11eb-9ec5-885f793338ef.png)

**Comment by wsmelton** [comment]
If you would like to submit a bug on SMO those are submitted here: https://github.com/microsoft/sqltoolsservice/issues

**Comment by andreasjordan** [comment]
Please have a look:

![image](https://user-images.githubusercontent.com/66946165/101026089-bf7d3900-3576-11eb-9526-aa80b3202e91.png)

It only works if you don't reuse the SMO from Connect-DbaInstance.

**Comment by wsmelton** [comment]
Quick fix is to simply add `$db.Alter()` after the `SetOwner()` is called.

**Comment by andreasjordan** [comment]
No, that does not help:

![image](https://user-images.githubusercontent.com/66946165/101051847-3a018500-3586-11eb-9fe8-8c5869d3a77a.png)

**Comment by wsmelton** [comment]
Wrong object. I've added it to the function call for the Database Class which is what the Set-DbaDbOwner command manipulates and it properly refreshes the object.

**Comment by andreasjordan** [comment]
Sorry, I don't understand you.

**Comment by wsmelton** [comment]
A side note on the issue you submitted to that repository. Our module is not using the latest version of SMO we are a major version behind still on 150, not 160. Just FYI to be aware of there.

Adding the `Alter()` method performs less intrusive steps than doing the `Refresh()` but both options do work properly. I would prefer we use `Alter()` though to make sure the command does not become unusable in large environments.

```powershell
[PS 5.1] [10:40:19] > C:\git\dbatools\functions
 [1] > ipmo ..\dbatools.psd1
[PS 5.1] [10:42:20] [ 30.0 s ] C:\git\dbatools\functions
 [2] > $db = New-DbaDatabase -SqlInstance lab-sql-01 -SqlCredential $labSqlAdminCred -Database SetOwner
[PS 5.1] [10:43:39] [  1.4 s ] C:\git\dbatools\functions
 [3] > $db.Owner          
sqladmin
[PS 5.1] [10:43:50] [ 13.0ms ] C:\git\dbatools\functions
 [4] > $db.SetOwner('sa') 
[PS 5.1] [10:43:56] [ 17.0ms ] C:\git\dbatools\functions
 [5] > $db.Owner
sqladmin
[PS 5.1] [10:44:01] [  4.0ms ] C:\git\dbatools\functions
 [6] > $db.Refresh()
[PS 5.1] [10:44:05] [ 25.0ms ] C:\git\dbatools\functions
 [7] > $db.Owner  
sa
[PS 5.1] [10:44:09] [ 13.0ms ] C:\git\dbatools\functions
 [8] > $db.SetOwner('sqladmin')
[PS 5.1] [10:44:21] [ 16.0ms ] C:\git\dbatools\functions
 [9] > $db.Alter()
[PS 5.1] [10:44:24] [274.0ms ] C:\git\dbatools\functions
 [10] > $db.owner
sqladmin
[PS 5.1] [10:44:26] [ 15.0ms ] C:\git\dbatools\functions
```

**Comment by andreasjordan** [comment]
Ok, not my day today: It works on your maschine - but not on my maschine....

**Comment by andreasjordan** [comment]
@wsmelton thanks for helping me here. After I updated the command, it works on my maschine as well. Will open a PR now...
