### ISSUE TITLE
[Bug] Copy-DbaLogin Error 

### ISSUE THREAD

**Issue by kathygibson96** [sqlcollaborative/dbatools#7025]
[dbatools_1872_message_0.zip](https://github.com/sqlcollaborative/dbatools/files/5662523/dbatools_1872_message_0.zip)

### Report

I am migrating logins from a standalone Win2016/SQL2016 Server to 2 new Win2019/SQL2019 servers that will be configured as AG replicas.  I am windows admin and sql sysadmin on all boxes.  I migrated all the server related entries (including logins) for the 1st server without issue, but migration of the 2nd server is consistently throwing errors and I can't get past migrating the logins.

For debugging I changed my call to Copy-DbaLogin to just migrate 1 user.
`Copy-DbaLogin -Source $SQLSource -Destination $SQLTarget -Login dspnetuser -ExcludePermissionSync -Force`

#### Host used

- [x] ISE

#### Errors Received

```
Type             Name       Status Notes
----             ----       ------ -----
Login - SqlLogin dspnetuser Failed   
```

#### Steps to Reproduce

I am migrating logins from a standalone Win2016/SQL2016 Server to 2 new Win2019/SQL2019 servers that will be configured as AG replicas.  I am windows admin and sql sysadmin on all boxes.  I migrated all the server related entries (including logins) for the 1st server without issue, but migration of the 2nd server is consistently throwing errors and I can't get past migrating the logins.

For debugging I changed my call to Copy-DbaLogin to just migrate 1 user.
`Copy-DbaLogin -Source $SQLSource -Destination $SQLTarget -Login dspnetuser -ExcludePermissionSync -Force`

#### Expected Behavior

The login and it's associated password would be copied to the target server.

#### Actual Behavior

Nothing ... the command failed.

### Environmental information

```powershell
PowerShell Version        : 5.1.14393.3866
dbatools latest installed : 1.0.133
Culture of OS             : en-US
```
#### SQL Server:

```sql
Source - Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64)   Nov 27 2019 18:09:22   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
Target - Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
Source - us_english
Target - us_english
```

**Comment by kathygibson96** [comment]
I tried to fill out the template as best I could, but the information that I put in for some of the categories didn't show up in the preview panel.  Pls let me know if I should go over to slack,  Thx for helping me with this.

**Comment by wsmelton** [comment]
Pertinent details from attached logs...

```
"Attempting to add dspnetuser to localhost,6500.","Verbose, Debug","12/8/2020 5:37:43 PM","Copy-Login","dbatools","System.Collections.Generic.List`1[System.String]","Verbose","38766ff5-1a5b-47e8-b573-6a9688b90679","SIDEWINDER1B",,"C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1","8633","System.Management.Automation.ScriptDebugger+<GetCallStack>d__108","GAFOC\gibsonk"
"Failed to create login dspnetuser on SIDEWINDER1B,6500. | Cannot find an overload for ""Login"" and the argument count: ""2"".","Debug, Warning","12/8/2020 5:37:43 PM","New-DbaLogin","dbatools","System.Collections.Generic.List`1[System.String]","Warning","38766ff5-1a5b-47e8-b573-6a9688b90679","SIDEWINDER1B",,"C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1","55976","System.Management.Automation.ScriptDebugger+<GetCallStack>d__108","GAFOC\gibsonk"
"Failed to add dspnetuser to localhost,6500. | Cannot find an overload for ""Login"" and the argument count: ""2"".","Debug, Warning","12/8/2020 5:37:43 PM","Copy-Login","dbatools","System.Collections.Generic.List`1[System.String]","Warning","38766ff5-1a5b-47e8-b573-6a9688b90679","SIDEWINDER1B","SIDEWINDER1B,6500","C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1","8653","System.Management.Automation.ScriptDebugger+<GetCallStack>d__108","GAFOC\gibsonk"
```

```
<LST>
          <Obj RefId="3">
            <TN RefId="3">
              <T>Sqlcollaborative.Dbatools.Message.DbatoolsException</T>
              <T>System.Object</T>
            </TN>
            <ToString>Failed to add dspnetuser to localhost,6500. | Cannot find an overload for "Login" and the argument count: "2".</ToString>
            <Props>
              <S N="Message">Failed to add dspnetuser to localhost,6500. | Cannot find an overload for "Login" and the argument count: "2".</S>
              <Nil N="Source" />
              <Nil N="StackTrace" />
              <Nil N="TargetSite" />
              <I32 N="HResult">-2146233088</I32>
              <Nil N="HelpLink" />
              <Obj N="Data" RefId="4">
                <TN RefId="4">
                  <T>System.Collections.ListDictionaryInternal</T>
                  <T>System.Object</T>
                </TN>
                <DCT />
              </Obj>
              <Obj N="InnerException" RefId="5">
                <TNRef RefId="3" />
                <ToString>Cannot find an overload for "Login" and the argument count: "2".</ToString>
                <Props>
                  <S N="Message">Cannot find an overload for "Login" and the argument count: "2".</S>
                  <Nil N="Source" />
                  <Nil N="StackTrace" />
                  <Nil N="TargetSite" />
                  <I32 N="HResult">-2146233088</I32>
                  <Nil N="HelpLink" />
                  <Obj N="Data" RefId="6">
                    <TNRef RefId="4" />
                    <DCT />
                  </Obj>
                  <S N="InnerException">Cannot find an overload for "Login" and the argument count: "2".</S>
                  <S N="ExceptionTypeName">System.Exception</S>
                  <Obj N="ExceptionData" RefId="7">
                    <TN RefId="5">
                      <T>System.Collections.Hashtable</T>
                      <T>System.Object</T>
                    </TN>
                    <DCT />
                  </Obj>
                  <Nil N="CategoryInfo" />
                  <Nil N="ErrorDetails" />
                  <Nil N="FullyQualifiedErrorId" />
                  <Nil N="InvocationInfo" />
                  <Nil N="ScriptStackTrace" />
                  <Nil N="TargetObject" />
                  <Nil N="FunctionName" />
                  <DT N="Timestamp">0001-01-01T00:00:00</DT>
                  <G N="Runspace">00000000-0000-0000-0000-000000000000</G>
                  <Nil N="ComputerName" />
                </Props>
              </Obj>
              <S N="ExceptionTypeName">System.Exception</S>
              <Obj N="ExceptionData" RefId="8">
                <TNRef RefId="5" />
                <DCT />
              </Obj>
              <Obj N="CategoryInfo" RefId="9">
                <TN RefId="6">
                  <T>System.Management.Automation.ErrorCategoryInfo</T>
                  <T>System.Object</T>
                </TN>
                <ToString>InvalidOperation: (SIDEWINDER1B,6500:String) [], Exception</ToString>
                <Props>
                  <S N="Category">InvalidOperation</S>
                  <S N="Activity"></S>
                  <S N="Reason">Exception</S>
                  <S N="TargetName">SIDEWINDER1B,6500</S>
                  <S N="TargetType">String</S>
                </Props>
              </Obj>
              <Nil N="ErrorDetails" />
              <S N="FullyQualifiedErrorId">dbatools_Copy-Login</S>
              <Nil N="InvocationInfo" />
              <Nil N="ScriptStackTrace" />
              <S N="TargetObject">SIDEWINDER1B,6500</S>
              <S N="FunctionName">Copy-Login</S>
              <DT N="Timestamp">2020-12-08T17:37:43.5133468-05:00</DT>
              <G N="Runspace">38766ff5-1a5b-47e8-b573-6a9688b90679</G>
              <S N="ComputerName">SIDEWINDER1B</S>
            </Props>
          </Obj>
        </LST>
```

**Comment by kathygibson96** [comment]
Thx for looking at this.

Can you explain why it’s not working?  I’m migrating 2 servers and on the 1st server everything worked straight up, but on this one I’m seeing the problem :  Cannot find an overload for ""Login"" and the argument count: ""2"".".

I was hoping this would mean something to you.

Again target machines are Win2019/SQL2019 in all cases (source, target) I am winadmin on the box and sysadmin for sql server on the box.

I have also verified the the –whatif flag generates the correct output and I have manually scripted a login from the source, pasted it into SSMS and created it under my A/D login which are the credentials I’m running my cmdlet under in PS ISE.

Any insights you could provide would be most helpful.

Thx
Kathy

**Comment by kathygibson96** [comment]
As I've moved ahead investigating this, I'm more convinced that this is an environment problem, but because I'm new to PS I can't find the problem.  Just to recap, I have 1 win2019/sql2019 ent vm that all the scripts run on and another where I'm having the problem.  It also extends to copying jobs over as well as logins.  I've identified that windows and PS are the same version on both machines.  I've looked at the execution policies and they are the same.  I even made the execution policy on the misbehaving machine 'unrestricted'.  I looked at the code for the dbatools PS functions and that appears to be consistent between the 2 machines as well.  I'm going to move on to learning how to debug in PS to see if that sheds any light on the issue.

**Comment by kathygibson96** [comment]
ok ... I've go this figured out and fixed.  I actually learned how to debug in PS, so it was good to learn that.  Anyway, this was an environment issue.  I had to install a new SqlServer module (contains the smo assemblies).  Then at the top of my cmdlet I put an Import-Module -Name dbatools statement.  This makes sure that the SqlServer module and the dbatools module are available for my use.  But to summarize, the cause of the problem was definitely an out of data SqlServer module.

**Comment by wsmelton** [comment]
Our module will issue a warning if the `sqlserver` module is imported along with ours. They do not play well together and using a newer version of SMO in your session may not give expected results.

Our module is packaged with SMO, you can find them under the `bin` folder of the module. Just as an FYI.

**Comment by kathygibson96** [comment]
Thanks for responding on this.  I did see that warning because initially I had an import-module statement for both SqlServer and dbatools, but removed the one for SqlServer.

As for making sure that I'm using the SqlServer module that's consistent / compatible with dbatools.  Once I had debugged the problem down to the creation of a new login on my target system I new that I had an environment problem.  I'm not sure why the smo assemblies weren't loaded properly when I installed dbatools, but putting a new version of SqlServer on the machine was the fix.  Here's a picture of all my currently installed modules.

Version              Name                                Repository           Description                                                                             
-------              ----                                ----------           -----------                                                                             
1.0.133              dbatools                            PSGallery            The community module that enables SQL Server Pros to automate database development an...
1.4.7                PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a new way to discover and install software packa...
2.2.5                PowerShellGet                       PSGallery            PowerShell module with commands for discovering, installing, updating and publishing ...
21.1.18230           SqlServer                           PSGallery            This module allows SQL Server developers, administrators and business intelligence pr...

Have a great weekend!

**Comment by wsmelton** [comment]
Our module does not acknowledge or use any installed version of SMO that you may put on the machine. We [explicitly import and reference](https://github.com/sqlcollaborative/dbatools/blob/development/bin/library.ps1) only the version of SMO that is packaged with the module.

It is not that you can make the sqlserver module consistent with or compatible with our module. The SMO shipped with sqlserver is never referenced within our module. (It is a time consuming task to update SMO with our module at this state with so many commands.) The main item that conflicts with our module that I've observed is with the formats and types in that module, and those can cause conflicts with dbatools. I've only ever seen it affect the output of our commands, it should have no way of conflicting with the operation itself.

If you are utilizing our module with a more complex process the simply need is to ensure you are not referencing any command that is part of the sqlserver module; this ensures it won't get loaded by PowerShell into the session.

What environmental issue did you find while debugging that lead you to needing a newer version of SMO?

**Comment by kathygibson96** [comment]
It's very interesting that you mentioned I shouldn't access the smo directly, because I do have code that does that for the purposes of configuring DBMail and setting some server level options.  I'm going to look at removing those references today and replacing them with dbatools calls.

As to what specifically went wrong?  Many of the dbatools calls were throwing errors and some weren't, (copying job categories and operators worked just fine).

Copying logins was a the first place that I started seeing red in the output.  The error happened in the dbatools code when it attempted to create a login on the target machine using the smo.  That error was:  **Cannot find an overload for "Login" and the argument count: "2".**.   I'm attaching a copy of my configuration cmdlet for you to look at, but the next thing on my list is to remove the direct call to the smo because I don't want to clash with modules that dbatools is already loading.
[DS_SQLConfig.zip](https://github.com/sqlcollaborative/dbatools/files/5696607/DS_SQLConfig.zip)

**Comment by wsmelton** [comment]
> It's very interesting that you mentioned I shouldn't access the smo directly

I did not make that statement.

The script you are using does not need to reference any command utilized by sqlserver module. Doing this will cause PowerShell to load the sqlserver module.

**Comment by kathygibson96** [comment]
So ... leave everything in the cmdlet as is?  There's just the one import at the top --> Import-Module -Name dbaTools.

If I need to create an $smo object then I can and it will load the dbatools version because I imported it specifically?

I'm also in Slack today if that's easier for you.  Thx for helping.

**Comment by wsmelton** [comment]
So things I'd see in your script to convert to dbatools:

- Client aliases - `Get-DbaClientAlias`/`New-DbaClientAlias`
- Configuring settings like Min/Max Memory and the others can be done using `Set-DbaSpConfigure` (This basically sets anything under Configuration class I recall)
- We have some Test functions as well around testing DOP and Memory to output recommended value
- I would remove the use of `> $null` as this can cause some issues to be hidden.
- Our commands override the normal error stream so if you want them to properly error out (sometimes give you more details on failures) add use of the `-EnableException`
 
_Your script does give an idea that `Test-DbaDbMail` would be a cool command, something that lets you send that test email you are doing to verify configuration is in place._ // @potatoqualitee

**Comment by kathygibson96** [comment]
Thx v much.

Will do!
