### ISSUE TITLE
Import-DbaCsv -lineBreak

### ISSUE THREAD

**Issue by GrabASalad** [sqlcollaborative/dbatools#7026]
Please provide a custom Line break option for this fabulous tool as some of our data doesn't come with '`r`n' and currently I have to replace it in the text programmatically before invoking the import which is slow.  

Excellent work team
Grab A Salad

**Comment by potatoqualitee** [comment]
LOL, salad is the best 🥗 . I'll check to see if the DLL we use supports explicit linebreaks

**Comment by potatoqualitee** [comment]
So I'm reading through the code and this will likely be the part

```
$reader = New-Object LumenWorks.Framework.IO.Csv.CsvReader(
                (New-Object System.IO.StreamReader($Path, [System.Text.Encoding]::$Encoding)),
                $FirstRowHeader,
                $Delimiter,
                $Quote,
                $Escape,
                $Comment,
                [LumenWorks.Framework.IO.Csv.ValueTrimmingOptions]::$TrimmingOption,
                $BufferSize,
                $NullValue
            )
```

From [the StreamReader docs](https://msdn.microsoft.com/en-us/library/system.io.streamreader.readline(v=vs.110).aspx), it says that:

> A line is defined as a sequence of characters followed by a line feed ("\n"), a carriage return ("\r"), or a carriage return immediately followed by a line feed ("\r\n")

What is your type of linebreak? Is it possible that altering the `-Encoding` would help?

**Comment by potatoqualitee** [comment]
Yeah, I think Encoding will address the issue. 

https://docs.microsoft.com/en-us/visualstudio/ide/encodings-and-line-breaks?view=vs-2019

Please test with that and let us know if that doesn't address your issue. If so, I'll reopen this issue.
