### ISSUE TITLE
Write-DbaDbTableData - Improvements for InputObject of type [System.Data.DataRow[]]

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7027]
First of all some code to test:
```
$server = Connect-DbaInstance -SqlInstance SRV1\SQL2016
$query = "SELECT name, create_date FROM sys.databases"

$ds = Invoke-DbaQuery -SqlInstance $server -Query $query -As DataSet
$dt = Invoke-DbaQuery -SqlInstance $server -Query $query -As DataTable  
$dr = Invoke-DbaQuery -SqlInstance $server -Query $query -As DataRow
$ps = Invoke-DbaQuery -SqlInstance $server -Query $query -As PSObject

$ds | Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -AutoCreateTable -Verbose  # One Invoke-BulkCopy per Table
$dt | Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -Verbose                   # One Invoke-BulkCopy per Row
$dr | Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -Verbose                   # One Invoke-BulkCopy per Row
$ps | Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -Verbose                   # One Invoke-BulkCopy per Table

Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -InputObject $ds -Verbose  # One Invoke-BulkCopy per Table
Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -InputObject $dt -Verbose  # One Invoke-BulkCopy per Table
Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -InputObject $dr -Verbose  # One Invoke-BulkCopy per Row
Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -InputObject $ps -Verbose  # One Invoke-BulkCopy per Table

Invoke-DbaQuery -SqlInstance $server -Query $query -As DataSet   | Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -Verbose  # One Invoke-BulkCopy per Table
Invoke-DbaQuery -SqlInstance $server -Query $query -As DataTable | Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -Verbose  # One Invoke-BulkCopy per Table
Invoke-DbaQuery -SqlInstance $server -Query $query -As DataRow   | Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -Verbose  # One Invoke-BulkCopy per Row
Invoke-DbaQuery -SqlInstance $server -Query $query -As PSObject  | Write-DbaDbTableData -SqlInstance $server -Database tempdb -Table MyTable -Verbose  # One Invoke-BulkCopy per Table
```

Some relevant lines of code:
https://github.com/sqlcollaborative/dbatools/blob/a0b7d9166e5ac2404a08dc11da5fe0b5ea7d7e5a/functions/Write-DbaDbTableData.ps1#L553

https://github.com/sqlcollaborative/dbatools/blob/a0b7d9166e5ac2404a08dc11da5fe0b5ea7d7e5a/functions/Write-DbaDbTableData.ps1#L586-L587

https://github.com/sqlcollaborative/dbatools/blob/a0b7d9166e5ac2404a08dc11da5fe0b5ea7d7e5a/functions/Write-DbaDbTableData.ps1#L606-L608

The terms "Single valid table" and "Multiple valid tables" are not correct and missleading here. Because DataRow is a valid type, every single row is handled as a table with one row. So for every row, a seperate BulkInsert is send to the instance (yes, I have proved that with profiler).

I have excluded DataRow from the valid types and then the rows are send to the steppable pipeline. That way there is only one BulkInsert at the very end. But inside of ConvertTo-DbaDataTable this code is used:
https://github.com/sqlcollaborative/dbatools/blob/a0b7d9166e5ac2404a08dc11da5fe0b5ea7d7e5a/functions/ConvertTo-DbaDataTable.ps1#L308-L312

I don't know if this is better.

Maybe we only update the documentation and tell users to ensure that a DataSet is used or a DataTable is send to the command via -InputObject or to use PSObjects.

**Comment by andreasjordan** [comment]
Not directly related, but should be improved:

https://github.com/sqlcollaborative/dbatools/blob/a691a9b1338121e11a8872250649ae5fdc9b5507/functions/Write-DbaDbTableData.ps1#L636-L638

As $steppablePipeline is set in the begin block the if is always true and so Invoke-BulkCopy is run even if there is nothing in that pipeline.
We should better use:
```
        #region ConvertTo-DbaDataTable wrapper
        $dataTable = $steppablePipeline.End()
        if ($dataTable[0].Rows.Count -gt 0) {

```

**Comment by wsmelton** [comment]
>  So for every row, a seperate BulkInsert is send to the instance (yes, I have proved that with profiler).

I wonder if this is what causes issues on Azure SQL with it using all connections 🤔

**Comment by andreasjordan** [comment]
> > So for every row, a seperate BulkInsert is send to the instance (yes, I have proved that with profiler).
> 
> I wonder if this is what causes issues on Azure SQL with it using all connections 🤔

No I don't think so, because "Connect-DbaInstance" and "New-Object Data.SqlClient.SqlBulkCopy" are both part of the begin block.

**Comment by andreasjordan** [comment]
Let's link this here: #7009 - because this should be addressed as well.

**Comment by andreasjordan** [comment]
I ran a first test: The $datatable.Merge($object.Table) in ConvertTo-DbaDataTable should be avoided in any case - it has a very bad performance. So DataRows should never be passed to ConvertTo-DbaDataTable.
