### ISSUE TITLE
Start-DbaMigration for RDS

### ISSUE THREAD

**Issue by durgaganeshpolisetti** [sqlcollaborative/dbatools#7028]
### Summary of new feature

* is it posiable to use AWS RDS instance as destination for Start-DbaMigration function.

### Proposed technical details (if applicable)

* e.g. take on prem backup to s3 arn then restore to rds using end point

**Comment by wsmelton** [comment]
The main purpose of `Start-DbaMigration` is for on-premise migrations or at most VM to VM (Azure VM/AWS EC2). There are no plans to support migrations to cloud PaaS offerings.

AWS RDS for SQL Server does not support the use of SMO for the restore process and utilizes specific commands proprietary to AWS.
