### ISSUE TITLE
[Bug] Invoke-DbaDiagnosticQuery does not return any results for SQL 2019

### ISSUE THREAD

**Issue by atultandon1981** [sqlcollaborative/dbatools#7029]
#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
ComputerName     : xxxxx
InstanceName     : xxxx
SqlInstance      : xxxxx\xxx01
Number           : 0
Name             : 
Description      : 
DatabaseSpecific : False
Database         : 
Notes            : Empty Result for this Query
Result           : 

PSMessageDetails      : 
Exception             : System.InvalidOperationException: Cannot force the member with name "PSStandardMembers" and type "MemberSet" to be added. A member with that name and type already 
                        exists, and the existing member is not an instance extension.
TargetObject          : [CDCAdmin]
CategoryInfo          : InvalidOperation: ([CDCAdmin]:PSObject) [Add-Member], InvalidOperationException
FullyQualifiedErrorId : CannotRemoveTypeDataMember,Microsoft.PowerShell.Commands.AddMemberCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Select-DefaultView<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 81519
                        at Get-DbaDatabase<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 21830
                        at Invoke-DbaDiagnosticQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 47019
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {1, 1}
```

#### Steps to Reproduce

`Invoke-DbaDiagnosticQuery -SqlInstance SQL2019`

#### Expected Behavior

This should run all the defined diagnostic queries against the SQL instance . It works well with SQL 2017 or below versions

#### Actual Behavior

Return no results

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script
```
PowerShell Version        : 5.1.14393.3866
dbatools latest installed : 
Culture of OS             : en-AU
```

#### SQL Server:
```
Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64)
```

```sql
Language
us_english
```

**Comment by wsmelton** [comment]
@atultandon1981 I'm not able to replicate this issue. 

This is SQL Server 2019 (on Linux and `en-US`).
![image](https://user-images.githubusercontent.com/11204251/102020417-b4789480-3d3e-11eb-901a-67e9ffe289e7.png)

I'm not able to test on an OS with `en-AU` package installed to know if that may have anything to do with it.

Can you try issuing your command with `-Verbose` or possibly `-Debug` as well to see if any additional output gives an idea of what is going wrong?

**Comment by atultandon1981** [comment]
Hi Shaw,

Thanks for looking into this. Just a question, is there there any setting
or configuration that needs to be on to for this command to work. I manage
around 400 SQL instance and some reason it's not working for newly
installed 2019 instance . I wonder if there is any setting that need to be
on for that ?
Regards
Atul

**Comment by wsmelton** [comment]
No settings or configurations are used in the command.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
