### ISSUE TITLE
Get-SSRSObject cmdlet

### ISSUE THREAD

**Issue by chadbaldwin** [sqlcollaborative/dbatools#7036]
Someone on the Slack community channel saw this script I shared and asked if I could create a feature request and share the script in case you'd be able to use it for a future cmdlet.

The idea of a Get-SSRSObject cmdlet seems like it could be really nice. With parameters to choose the object type, and name glob filters, etc.

### Summary of new feature

* A cmdlet that has the ability to pull all of or a specific SSRS object directly from the ReportServer database.

### Proposed technical details (if applicable)

I recently needed to figure this out using powershell, so this is the script I came up with. It is currently only configured to export report RDL files, but it could be adapted to other objects as well.

```lang-powershell
$query = "SELECT c.[Path], c.Content FROM dbo.[Catalog] c WHERE c.[Type] = 2"
$data = Invoke-DbaQuery -SqlInstance SERVERNAME -Database ReportServer -Query $query
$data | % {
    $reportName = ".$($_.Path).rdl";
    $reportDir = $reportName | Split-Path;
    $null = New-Item -Path $reportDir -ItemType Directory -Force;
    [System.Text.Encoding]::UTF8.GetString($_.Content) | Set-Content -Path $reportName -NoNewline
}
```

### Latest version of dbatools as of writing

* 1.0.5

**Comment by wsmelton** [comment]
We generally point folks to the module written for SSRS and Power BI that the Microsoft team for that product maintains:

https://github.com/microsoft/ReportingServicesTools

Is this covering something that is not available on that module?

**Comment by marclancy** [comment]
Yes, the reportingservicestools module covers downloading items from a report server.

For a particular item: `Out-RsCatalogItem` or `Out-RsRestCatalogItem`	
For all items in a folder: `Out-RsFolderContent` or `Out-RsRestFolderContent`  

The two REST commands will also download items that are not reports, datasources or datasets (eg PowerBI reports or Excel files)

The module is very actively maintained so definitely post there if you see something that is missing.

**Comment by wsmelton** [comment]
I do not see enough need to try and cover functionality in dbatools that the SSRS module should be (or already is) more than capable of handling. 

Closing.
