### ISSUE TITLE
we need command for sql patching for sql cluster or always on 3 node cluster

### ISSUE THREAD

**Issue by Hal1987** [sqlcollaborative/dbatools#7039]
### Summary of new feature

* Clear/concise description of what the problem is that the new feature can solve.

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.

**Comment by Hal1987** [comment]
we would like to have a powershell command for sql patching alaways on , please consider this

**Comment by wsmelton** [comment]
Please review our documentation at docs.dbatoools.io. We have the command `Update-DbaInstance` available for installing and patching SQL Server.

In reference to patching Availability Groups or Failover Cluster Instances that process can be derived specifically for your environment and methods.
