### ISSUE TITLE
[Bug] - Restore-DbaDatabase progress bar not showing

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7044]
I ran the following commands from the dev branch and it looked like it was just sitting and not processing, but verbose was showing action

```powershell
Backup-DbaDatabase -SqlInstance localhost -Path C:\temp\sql -ExcludeDatabase tempdb, master, msdb -Type Full
Backup-DbaDatabase -SqlInstance localhost -Path C:\temp\sql -ExcludeDatabase tempdb, master, msdb -Type Diff
Backup-DbaDatabase -SqlInstance localhost -Path C:\temp\sql -ExcludeDatabase tempdb, master, msdb -Type Log
Backup-DbaDatabase -SqlInstance localhost -Path C:\temp\sql -ExcludeDatabase tempdb, master, msdb -Type Log
Backup-DbaDatabase -SqlInstance localhost -Path C:\temp\sql -ExcludeDatabase tempdb, master, msdb -Type Log

# this one is problematic
Get-ChildItem -Path C:\temp\sql | Restore-DbaDatabase -SqlInstance localhost -WithReplace -Verbose # and without verbose
```

![image](https://user-images.githubusercontent.com/8278033/102701556-6c82d180-4258-11eb-8c73-f21a8b391b64.png)

After it put together the chain, the progress bar did work

**Comment by Zhunya** [comment]
I saw this progress progressing but on huge amounts of files...

**Comment by wsmelton** [comment]
I would not consider this a bug because it is a result of using runspaces to scan files in a folder path.

There are ways to have the progress bar work with runspaces but you get into .NET and having to build out with WPF to make it work. (A lot of .NET code to maintain.)

Example: https://gallery.technet.microsoft.com/New-ProgressBar-8468da5c

**Comment by Stuart-Moore** [comment]
Yep, what the gents above say. You may get a moving bar if you're restoring more than 10-20 files as it'll do >2 loops through the runspaces.

**Comment by Zhunya** [comment]
Think this might be closed as resolved.

**Comment by potatoqualitee** [comment]
yes indeed this is fixed 👍🏼
