### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Hummer311** [sqlcollaborative/dbatools#7047]
#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [x] pwsh.exe

#### Errors Received

```
The powershell.exe host closes without any error.
```

#### Steps to Reproduce

```
Get-DbaService 
```

#### Expected Behavior

Running the same command from the pwsh hosts on the same machine from the same account 
generates the expected output, without closing the session. 
For sake of brevity, I ran the command showing only some properties:
```
PS C:\Windows\System32> Import-Module dbatools -Version 1.0.135
PS C:\Windows\System32> Get-DbaService | Select-Object ServiceName,State

ServiceName                State
-----------                -----
SQLServerReportingServices Running
MSSQLFDLauncher            Stopped
MSSQLSERVER                Running
MSSQLServerOLAPService     Running
SQLBrowser                 Stopped
SQLSERVERAGENT             Running

PS C:\Windows\System32>
```

#### Actual Behavior

```
C:\WINDOWS\system32>powershell -noprofile
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> Import-Module dbatools -Version 1.0.135
PS C:\WINDOWS\system32> Get-DbaService | Select-Object ServiceName,State

C:\WINDOWS\system32>
```

### Environmental information

```powershell
PowerShell Version        : 5.1.19041.610
dbatools latest installed : 1.0.135
Culture of OS             : en-US
```

#### SQL Server:

```sql
SELECT @@VERSION
Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19042: ) (Hypervisor) 
```

```sql
SELECT @@LANGUAGE
us_english
```

**Comment by Hummer311** [comment]
Here's a clip showing the behaviour

https://user-images.githubusercontent.com/690711/102790548-97ae1380-4373-11eb-95f0-5eb70bd92ca5.mp4

**Comment by wsmelton** [comment]
Our module does not control the PowerShell session itself. We have no way of "exiting" from that process in Windows within our code.

I would look at the environmental configuration. If the process closed on an exception it should be logged in the operational log for PowerShell or the application/system log for Windows at least.

**Comment by Hummer311** [comment]
HI! Thanks for your reply! And thanks for your suggestions. 

With the help of one of my colleague, we used gflags.exe (one of the Debugging Tools of the Windows SDK) and it seems the issue is related to BitDefender simply terminating powershell.exe. 

![image](https://user-images.githubusercontent.com/690711/102809505-19139f00-4390-11eb-9418-146971c87672.png)

**Comment by wsmelton** [comment]
Thank you for posting. First I've heard of that effect occurring.
