### ISSUE TITLE
[Connect-DbaInstance] Failure | Unable to load adalsql.dll (Authentication=ActiveDirectoryPassword). Error code: 0x2.[Bug]

### ISSUE THREAD

**Issue by SquirrelAssassin** [sqlcollaborative/dbatools#7048]
The fix to the below issue is to place adalsql.dll in the System32 folder.... guessing that azure automation runs in x86 context.

- Download the ADAL msi https://www.microsoft.com/en-us/download/details.aspx?id=48742 (choose ENU\x64\adalsql.msi)
- Type: msiexec.exe /a “[Path to downloaded file]\adalsql.msi”/qb TARGETDIR=”[Export directory]” <- make sure the folder is empty
- Copy the [Export directory]\Windows\system32\adalsql.dll to C:\Windows\system32 folder.

ISSUE:
Try to use dbatools on a azure hybrid worker ... it will fail with the below ... even with the latest version installed and set-executionpolicy unrestricted
```
[Connect-DbaInstance] Failure | Unable to load adalsql.dll (Authentication=ActiveDirectoryPassword). Error code: 0x2.
```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

doesnt matter

#### SQL Server:

Azure SQL

**Comment by wsmelton** [comment]
We removed support of this last year because the full being packaged with the module effected user's experience in VS Code.

**Comment by SquirrelAssassin** [comment]
sounds like a ticket should have been opened with MS to fix vs code instead.

**Comment by wsmelton** [comment]
Not much use as it is likely an extension in Code that caused the issue. So many could be also using the DLL as well.

It was not popular enough at the time to work out the full issue in the module. As of now I'm not aware of many trying to use the module for this auth type.
