### ISSUE TITLE
Copy-DbaLogin - Exception thrown on Update-SqlPermissions (Case sensitive use case)

### ISSUE THREAD

**Issue by lostsole** [sqlcollaborative/dbatools#7052]
#### Host used
SQL Server 2014
Instances Collation: Latin1_General_BIN   <---
Version: dbatools 1.0.124

- [x ] powershell.exe
- [x ] ISE
- [ ] VS Code
- [ ] Other (please specify)

Command run: 
Copy-DbaLogin -Source PWN2014\DEV01 -Destination VWNDEV2014\DEV2014;
Both the sources and Destination instances are set with this collation:Instances Collation: Latin1_General_BIN

#### Errors Received
```
WARNING: [17:24:18][Update-SqlPermission] Failed to Grant CONNECT SQL to BCCCLEG bcccleg on VWNDEV2014\DEV2014. | 
Cannot find the login 'BCCCLEG bcccleg', because it does not exist or you do not have permission.
WARNING: [17:24:48][Update-SqlPermission] Failed to Grant CONNECT SQL to BCJUMAI bcjumai on VWNDEV2014\DEV2014. | 
Cannot find the login 'BCJUMAI bcjumai', because it does not exist or you do not have permission.
Caught an exception:
Exception Type: System.Management.Automation.RuntimeException
Exception Message: Index operation failed; the array index evaluated to null.
Update-SqlPermission : Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.124\allcommands.ps1:8282 char:25
+ ...             Update-SqlPermission -SourceServer $sourceServer -SourceL ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-SqlPermission], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex,Update-SqlPermission
```
I keep getting this error but not sure how to figure this one out, almost like dbatools is not using case sensitive.
the Server instances has 4 users that are the same, but there are over 900 users that are migrated.
BCCCLEG and bcccleg
BCJUMAI and bcjumai

**Comment by wsmelton** [comment]
> Cannot find the login 'BCCCLEG bcccleg'

Do those logins really have a space in the login name?

**Comment by wsmelton** [comment]
@lostsole this collation, `Latin1_General_BIN`, is case sensitive so it is SQL Server not finding them because they do not match. 

In that collation, `BCCCLEG` and `bcccleg` are not the same login.

**Comment by lostsole** [comment]
When I script out the 2 logins there is no spaces:
CREATE LOGIN [bcccleg] ...
CREATE LOGIN [BCCCLEG] ...

Correct the 2 Logins are different, 

But these users Keep coming up when I am migrating the Instances,  The client has lots of Instances for all the testers..

I just ran this and this is the message I got:
Copy-DbaLogin -Source PWN2014\DEV01 -Destination VWNDEV2014\DEV2014 -Login BCCCLEG -force -verbose;
`VERBOSE: [19:39:28][Get-DbaLogin] Getting last login times
VERBOSE: [19:39:28][Get-DbaLogin] Processing [BCCCLEG] on PWN2014\DEV01
VERBOSE: [19:39:28][Get-DbaLogin] Processing [bcccleg] on PWN2014\DEV01
VERBOSE: [19:39:29][Copy-DbaLogin] Force was used and DOMAIN\BKADMIN not found in logins list but an explicit Login or ExcludeLogin was specified, so we trust you won't drop the group that allows DOMAIN\BKADMIN access. Pr
oceeding.
VERBOSE: [19:39:29][Copy-DbaLogin] Attempting Login Migration.
VERBOSE: [19:39:29][Copy-Login] Attempting to migrate BCCCLEG
VERBOSE: [19:39:29][Copy-Login] Force was specified. Attempting to drop BCCCLEG on gpdbtrain.
VERBOSE: [19:39:30][Copy-Login] Successfully dropped BCCCLEG on gpdbtrain.
VERBOSE: [19:39:30][Copy-Login] Attempting to add BCCCLEG to gpdbtrain.
VERBOSE: [19:39:30][New-DbaLogin] Setting BCCCLEG SID
VERBOSE: [19:39:30][New-DbaLogin] Setting BCCCLEG default database to DYNAMICS
VERBOSE: [19:39:30][New-DbaLogin] Setting BCCCLEG language to us_english
VERBOSE: [19:39:30][New-DbaLogin] Adding as login type SqlLogin
VERBOSE: [19:39:30][New-DbaLogin] Successfully added BCCCLEG to VWNDEV2014.
VERBOSE: [19:39:30][Get-DbaLogin] Getting last login times
VERBOSE: [19:39:30][Get-DbaLogin] Processing [BCCCLEG] on VWNDEV2014
VERBOSE: [19:39:30][Get-DbaLogin] Processing [bcccleg] on VWNDEV2014

WARNING: [19:39:31][Update-SqlPermission] Failed to Grant CONNECT SQL to BCCCLEG bcccleg on VWNDEV2014\DEV2014. | Cannot find the login 'BCCCLEG bcccleg', because it does not exist or you do not have permission.	`

**Comment by andreasjordan** [comment]
I had a look at the code and the root problem is, that on this line, New-DbaLogin returns both logins, "BCCCLEG" and "bcccleg":

https://github.com/sqlcollaborative/dbatools/blob/546f8919ccd52ad82e078336697cb868bf4febcb/functions/Copy-DbaLogin.ps1#L366

Why? Because of the Get-DbaLogin at the end of New-DbaLogin. This does a "$serverLogins = $serverLogins | Where-Object Name -in $Login" and thus does not care about the case sensitivity of the database and returns both logins.

This is a problem at this line:
https://github.com/sqlcollaborative/dbatools/blob/546f8919ccd52ad82e078336697cb868bf4febcb/functions/Copy-DbaLogin.ps1#L380

There, two logins where passed to Update-SqlPermission, where "$newLoginName = $DestLogin.Name" results in $newLoginName beeing an array of the two login names, which does not work well at "$DestServer.PSObject.Methods[$permState].Invoke($permSet, $newLoginName, $grantWithGrant)".

I don't see a quick fix without breaking a lot of other use cases which need case insensitivity. Sorry.

**Comment by andreasjordan** [comment]
Maybe this does work in most cases:

Change
https://github.com/sqlcollaborative/dbatools/blob/546f8919ccd52ad82e078336697cb868bf4febcb/functions/Get-DbaLogin.ps1#L205
to

```
if ($server.Collation -match '_CI_') {
    $serverLogins = $serverLogins | Where-Object Name -in $Login    
} else {
    $serverLogins = $serverLogins | Where-Object Name -cin $Login
}
```

But some of the other authors should have a look at this first...
@potatoqualitee / @wsmelton / @SirCaptainMitch / @SQLDBAWithABeard

**Comment by lostsole** [comment]
So dbatools could have this issues with any SQL Server that use Collation that is case sensitive. So basically all objects, if the objects have the same name with different cases.
Would you have to have similar code in the other functions to test for the Server Collation like in the Update-SqlPermission?
--Love DBA tools--
Thanks for the quick find, I will wait to see what the others have to say.

**Comment by andreasjordan** [comment]
We have the same problem in all Get- commands that use the same strategy. Get-DbaAgentJob is one of them, I don't know about others.
The question is: How often is this the case out there. Why do you have these logins with same name but different cases?

**Comment by lostsole** [comment]
That is true, the client I work with never migrated the database before to new servers, They always did an in place upgrade.  This is the first time I have encountered the issue myself with dbatools,  
They have 40 instances with about 40 DB per instances , basically a clone of Prod for all the different developers and Environments.
Just this one issues that showed up for the migration, Pain when the Automation job failed for this issues. So now I just need to have a workaround for my automation script so that it does error on these duplicate users wit the same name.
Then I can deal with the duplicate users at the end.

**Comment by andreasjordan** [comment]
My only idea is to rename the users and after the migration rename them back.

**Comment by niphlod** [comment]
definitely a paint point. -Cin is the solution, at the cost of dbatools being "less usable" because then you'd have to pass correct casing everywhere. Pivoting on Collation is the best of both worlds.

**Comment by wsmelton** [comment]
I see the bug as simply being the logins not being passed in properly to `Update-SqlPermission`.

@lostsole if your process is for syncing lower environments to production then I would recommend renaming all the logins in those lower environments to match the same casing as production. We can utilize PowerShell operators for case-insensitive comparisons, but that does not fix the underlying configuration differences between those SQL Server instances; SQL Server still sees them as different logins.

**Comment by wsmelton** [comment]
I would think @andreasjordan the fix to deal with this type of use case and not break others is to simply loop over the logins instead of trying to pass them in with one variable. That way if we come across two of the same (at different casing) then it won't matter?

**Comment by andreasjordan** [comment]
@wsmelton : Good idea. Coded that - have a look.
