### ISSUE TITLE
Copy-DbaDbTableData isn't passing credentials to calls to Invoke-DbaQuery

### ISSUE THREAD

**Issue by MCTSQL** [sqlcollaborative/dbatools#7057]
There are 4 calls to Invoke-DbaQuery within Copy-DbaDbTableData, currently lines 376, 385, 405, 449.
These 4 calls are missing input parameter credentials, causing the calls to default to the current user's permissions instead of using the passed-in credentials of $SqlCredential and $DestinationSqlCredential.

**Comment by wsmelton** [comment]
The credentials are passed as they should be when the server objects are created via Connect-SqlInstance:

Server variable https://github.com/sqlcollaborative/dbatools/blob/7b0e4127c3d42b828be3ee4be3c3637c820fe073/functions/Copy-DbaDbTableData.ps1#L305

Destserver variable https://github.com/sqlcollaborative/dbatools/blob/7b0e4127c3d42b828be3ee4be3c3637c820fe073/functions/Copy-DbaDbTableData.ps1#L355

Please create a new issue and provide the details requested in our template. Including the steps to reproduce will help determine where any issue may be exactly.
