### ISSUE TITLE
New function: Update-DbaMaintenanceSolution

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#7072]
### Summary of new feature

Presently, `Install-DbaMaintenanceSolution` supports installing from scratch and replacing an existing installation. In the case of replacing an existing solution, the `CommandLog` table is dropped and re-created. This may present a problem for environments where this table is used for auditing, long-term monitoring of maintenance activity, etc.

**Proposed:** Create a new function, `Update-DbaMaintenanceSolution`, which drops the currently-installed stored procedures and replaces them with the new version, but does not drop the `CommandLog` table or drop/create/alter any of the jobs that are installed.

### Latest version of dbatools as of writing

1.0.136

**Comment by wsmelton** [comment]
Optimal method of to stop having install command drop a currently existing table. It should throw a warning and do nothing.

The procedures already support updating before all the scripts do for Ola is "alter procedure". 

This was discussed in detail in #6457
