### ISSUE TITLE
copy-DBAdbTableData in Parallel Timeout

### ISSUE THREAD

**Issue by saxet77** [sqlcollaborative/dbatools#7073]
Hi,

Try your great cmdlet copy-DBDbTableData on a 210M rows tables in parallel (x2) into a heap table do to accelerate the process, but I get a timeout error on the second connection after 4 min and I don't understand why ? 
Seems te bulkCopyTimeout parameter set on 5000 sec 

The Error:

WARNING: [08:14:17][Copy-DbaDbTableData] Something went wrong | The wait operation timed out

Following my 2 script executed from 2 ISE (Change real name information)

Session 1
----------
$params = @{
  SqlInstance = 'Server1'
  Destination = 'Server1'
  Database = 'DB_SOURCE'
  DestinationDatabase = 'DB_STAGING'
  Table = '[dbo].[Table]'
  DestinationTable = '[dbo].[TableStaging]' 
  KeepIdentity = $true
  KeepNulls = $true
  Truncate = $true
  BatchSize = 10000
  AutoCreateTable = $false
  Query = "SELECT * FROM [DB_SOURCE].[dbo].[Table] WHERE [ID] <= 189346505"
  NoTableLock = $True
  bulkCopyTimeout = 5000
}
Copy-DbaDbTableData @params

Session 2
----------
$params = @{
  SqlInstance = 'Server1'
  Destination = 'Server1'
  Database = 'DB_Source'
  DestinationDatabase = 'DB_STAGING'
  Table = '[dbo].[Table]'
  DestinationTable = '[dbo].[TableStaging]' 
  KeepIdentity = $true
  KeepNulls = $true
  Truncate = $false
  BatchSize = 10000
  AutoCreateTable = $false
  Query = "SELECT * FROM [DB_SOURCE].[dbo].[Table] WHERE [ID] > 189346505"
  NoTableLock = $True
  bulkCopyTimeout = 5000
}
Copy-DbaDbTableData @params

Any idea ??

Fred

**Comment by wsmelton** [comment]
Please open a new bug report and provide the details requested in our template.
