### ISSUE TITLE
Remove-DbaDbMirror examples and code seems wrong

### ISSUE THREAD

**Issue by keithmauerman** [sqlcollaborative/dbatools#7082]
the examples on documentation and in code all show Set-DbaDbMirror -SqlInstance localhost and no mention of using remove-dbadbmirror. Please check into it and advise

**Comment by niphlod** [comment]
code seems to do "the right thing" , see https://github.com/sqlcollaborative/dbatools/blob/master/functions/Remove-DbaDbMirror.ps1#L87 . It's just examples that are referring to another function, prolly a copy/paste mistake.

**Comment by keithmauerman** [comment]
agreed but can we get the examples correct?

**Comment by wsmelton** [comment]
A PR is welcomed to help update those with verified examples @keithmauerman
