### ISSUE TITLE
Set-DbaLogin - add validation for -Unlock to ensure a password was provided and provide a -Force option

### ISSUE THREAD

**Issue by lancasteradam** [sqlcollaborative/dbatools#7088]
### Report
Set-DbaLogin - add validation for -Unlock to ensure either a password was provided or -Force was specified

While working on #7004 it was noticed that when -Unlock is used without a password that no error message is returned and the login is still locked.

A possible fix can be seen here:  https://github.com/sqlcollaborative/dbatools/pull/7087/files/7127b1c70d9ad43de2d5fa412ab4e9ea485f57f5#diff-419523c18ac6bcaa3c3134c4b1996958ae756dbd7a59abec0193bfb8dc804381R217

Based on the discussion below it was decided that allowing the -Force to switch on/off the password policy would be an acceptable solution. This enables DBAs to unlock an account without changing the password. 

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

![Set-DbaLogin - Unlock param validation](https://user-images.githubusercontent.com/68036988/104858865-e8634e80-58d6-11eb-98a0-4dd4b031910b.png)

#### Steps to Reproduce
Get-DbaLogin -SQLInstance $server -Locked

Set-DbaLogin -SqlInstance $server -Login SQLUser1 -Unlock

$securePassword = ConvertTo-SecureString -String 'strong password' -AsPlainText -Force
Set-DbaLogin -SqlInstance $server -Login SQLUser1 -Unlock -Password $securePassword

#### Expected Behavior
The command should return an error that indicates the caller did not provide a password, which is required to do the unlock.
The command should allow the use of -Force to unlock a login without specifying the password.

#### Actual Behavior
No error is returned and the caller must check the result set to see that the login is still locked.

### Environmental information
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : latest from the development branch
Culture of OS             : en-US

#### SQL Server:
Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64)   Nov  2 2020 18:35:09   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 18363: ) (Hypervisor) 

us_english

**Comment by wsmelton** [comment]
Do we also provide the ability to do this without having to change the password?

**Comment by lancasteradam** [comment]
Unfortunately that isn't possible due to the syntax for the alter login command. The unlock is associated with the 'password_option' of the syntax:  https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-login-transact-sql?view=sql-server-ver15#syntax

There is the known workaround of turning on/off the policy enforcement to unlock a login, but I don't recommend putting that into the command. https://www.mssqltips.com/sqlservertip/2758/how-to-unlock-a-sql-login-without-resetting-the-password/

The benefit of the [proposed change](https://github.com/sqlcollaborative/dbatools/pull/7087/files/7127b1c70d9ad43de2d5fa412ab4e9ea485f57f5#diff-419523c18ac6bcaa3c3134c4b1996958ae756dbd7a59abec0193bfb8dc804381R217) is that by doing the param validation it will prevent a user from thinking "the command returned without error so the login must be unlocked". 

Let me know if you agree with that proposal and I can upload the param validation change as well as the integration tests related to locked logins for Get-DbaLogin and Set-DbaLogin.

**Comment by wsmelton** [comment]
> There is the known workaround of turning on/off the policy enforcement to unlock a login, but I don't recommend putting that into the command. https://www.mssqltips.com/sqlservertip/2758/how-to-unlock-a-sql-login-without-resetting-the-password/

I would recommend we add this option, because it is done in practice, and offering the ability for admins to unlock an account in circumstances that the password can't be changed would be beneficial.

**Comment by wsmelton** [comment]
> Unfortunately that isn't possible due to the syntax for the alter login command. The unlock is associated with the 'password_option' of the syntax: https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-login-transact-sql?view=sql-server-ver15#syntax

SMO does not allow it based on that method used (we don't use T-SQL for this command that I recall). If they do not provide the password a warning can be provided that to unlock either provide a secure password or the `-Force` parameter.

We do not currently use `-Force` in this command and this would offer the ability to provide a sensible workaround when they don't want to change the password but need to unlock it. It also requires that they know how the Force command is being used (which most end up reading the docs for that reason 😁 ). As long as down the road we don't come up with a second use for Force we should be good.

**Comment by lancasteradam** [comment]
ok, thanks for the feedback. I'll look into these.
