### ISSUE TITLE
[Bug] Get-DbaPermission tests failure

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#7101]
The test is unstable and continues to fail in Appveyor runs due to recent changes that were made to it.

@lancasteradam can you look at this section of the test that you added? The context block is failing most commonly on test runs in Appveyor with PRs now:
```
Describe : Get-DbaPermission Integration Tests
Context  : Ensure implicit permissions are included in the result set
Name     : It the dbo user and db_owner users are returned in the result set with the CONTROL permission
Result   : Failed
Message  : Expected 2, but got $null.
```

https://github.com/sqlcollaborative/dbatools/blob/2329ce5720adb7c59e73ff232804b3d8cfaa348d/tests/Get-DbaPermission.Tests.ps1#L112-L126

**Comment by lancasteradam** [comment]
yes, I'll take a look

**Comment by lancasteradam** [comment]
@wsmelton, is there a way I can debug this in the appveyor environment? I've tested on my local machine with SQL 2016, 2017, and 2019 and it works fine. I think the problem may be in the BeforeAll section.

**Comment by wsmelton** [comment]
There was a way to temporarily access the VM that appveyor is running the test on... But I've never tried it.
