### ISSUE TITLE
Get-DdaRegServer | Move-DbaRegServer InputObject does not contain ParentServer property after calling Get-RegServerParent

### ISSUE THREAD

**Issue by dvenardos** [sqlcollaborative/dbatools#7112]
dbatools version 1.0.137
PS C:\Users\dvenardos.REALSOFTWARE> Get-DbaRegServer -SqlInstance vssqlcms01\sql17 -ServerName vsOfficeTSDB -Group Unclassified | Move-DbaRegServer -Group Test
WARNING: [20:53:49][Move-DbaRegServer] Test not found on 

---------------
The object returned from the internal function Get-RegServerParent is not null, but does not have the ParentServer property, therefore, the group is not found even though it exists on the server.
---------------

PS C:\Users\dvenardos.REALSOFTWARE> Get-DbaRegServerGroup -SqlInstance vssqlcms01\sql17 | ft

ComputerName InstanceName SqlInstance      Name         DisplayName  Description ServerGroups RegisteredServers                                     
------------ ------------ -----------      ----         -----------  ----------- ------------ -----------------                                     
VSSQLCMS01   SQL17        VSSQLCMS01\SQL17 All Servers  All Servers              {}           {vsAlliantDev17\sql17, vsConfig02\sql16, vsOfficeTSDb}
VSSQLCMS01   SQL17        VSSQLCMS01\SQL17 Test         Test                     {}           {}                                                    
VSSQLCMS01   SQL17        VSSQLCMS01\SQL17 Unclassified Unclassified             {}           {vsOfficeTSDb}          

---------------------
PS C:\Users\dvenardos.REALSOFTWARE> Get-DbaRegServer -SqlInstance vssqlcms01\sql17 | ft

Name                 ServerName           Group        Description Source                    
----                 ----------           -----        ----------- ------                    
dvenardos\sql16      dvenardos\sql16                               Central Management Servers
vsAlliantDev17\sql17 vsAlliantDev17\sql17 All Servers              Central Management Servers
vsConfig02\sql16     vsConfig02\sql16     All Servers              Central Management Servers
vsOfficeTSDb         vsOfficeTSDb         All Servers              Central Management Servers
vsOfficeTSDb         vsOfficeTSDb         Unclassified             Central Management Servers

---------
PS C:\Users\dvenardos.REALSOFTWARE> $rs = Get-DbaRegServer -SqlInstance vssqlcms01\sql17 -ServerName vsOfficeTSDB -Group Unclassified

PS C:\Users\dvenardos.REALSOFTWARE> $rs

Name         ServerName   Group        Description Source                    
----         ----------   -----        ----------- ------                    
vsOfficeTSDb vsOfficeTSDb Unclassified             Central Management Servers

PS C:\Users\dvenardos.REALSOFTWARE> $parentserver = Get-RegServerParent -InputObject $rs

PS C:\Users\dvenardos.REALSOFTWARE> $parentserver

ComputerName                           : VSSQLCMS01
InstanceName                           : SQL17
SqlInstance                            : VSSQLCMS01\SQL17
AnalysisServicesServerGroup            : ServerGroup[@Name='AnalysisServicesServerGroup']
AnalysisServicesServerGroupName        : AnalysisServicesServerGroup
AzureDataStudioConnectionStore         : 
CentralManagementServerGroup           : 
CentralManagementServerGroupName       : CentralManagementServerGroup
DatabaseEngineServerGroup              : ServerGroup[@Name='DatabaseEngineServerGroup']
DatabaseEngineServerGroupName          : DatabaseEngineServerGroup
DisplayName                            : Central Management Servers
IntegrationServicesServerGroup         : ServerGroup[@Name='IntegrationServicesServerGroup']
IntegrationServicesServerGroupName     : IntegrationServicesServerGroup
IsLocal                                : False
KeyChain                               : RegisteredServersStore
ReportingServicesServerGroup           : ServerGroup[@Name='ReportingServicesServerGroup']
ReportingServicesServerGroupName       : ReportingServicesServerGroup
ServerGroups                           : {AnalysisServicesServerGroup, DatabaseEngineServerGroup, IntegrationServicesServerGroup, 
                                         ReportingServicesServerGroup...}
SqlServerCompactEditionServerGroup     : ServerGroup[@Name='SqlServerCompactEditionServerGroup']
SqlServerCompactEditionServerGroupName : SqlServerCompactEditionServerGroup

PS C:\Users\dvenardos.REALSOFTWARE> $rs.ParentServer

**Comment by dvenardos** [comment]
It is really weird, it is like PowerShell is making a deep copy of the object passed into Get-RegServerParent.
PS C:\Users\dvenardos.REALSOFTWARE> $rs = Get-DbaRegServer -SqlInstance vssqlcms01\sql17 -ServerName vsOfficeTSDB -Group Unclassified

PS C:\Users\dvenardos.REALSOFTWARE> $parentserver = Get-RegServerParent -InputObject $rs -Verbose
VERBOSE: Assigned InputObect to Parent.
VERBOSE: ParentCount = 0.
VERBOSE: Assigned InputObect to Parent.
VERBOSE: ParentCount = 1.
VERBOSE: Assigned InputObect to Parent.
VERBOSE: ParentCount = 2.
VERBOSE: Returning Input Object

PS C:\Users\dvenardos.REALSOFTWARE> $rs -eq $parentserver
False

PS C:\Users\dvenardos.REALSOFTWARE> $PSVersionTable

Name                           Value                                                                                                                       
----                           -----                                                                                                                       
PSVersion                      5.1.17763.1490                                                                                                              
PSEdition                      Desktop                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                     
BuildVersion                   10.0.17763.1490                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                             
WSManStackVersion              3.0                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                         
SerializationVersion           1.1.0.1  

--------------------------------
function Get-RegServerParent {
    [cmdletbinding()]
    param (
        [object]$InputObject
    )
    process {
        $parentcount = 0
        do {
            if ($null -ne $InputObject.Parent) {
                $InputObject = $InputObject.Parent
                Write-Verbose 'Assigned InputObect to Parent.'
            }
            Write-Verbose "ParentCount = $parentcount."
        }
        until ($null -ne $InputObject.ServerConnection -or $parentcount++ -gt 10)
        
        
        if ($parentcount -lt 10) {
            Write-Verbose 'Returning Input Object'
            $InputObject
        }
    }
}

$rs = Get-DbaRegServer -SqlInstance vssqlcms01\sql17 -ServerName vsOfficeTSDB -Group Unclassified
$parentserver = Get-RegServerParent -InputObject $rs -Verbose

$rs -eq $parentserver

**Comment by lancasteradam** [comment]
@dvenardos, I've updated the documented example for Move-DbaRegServerGroup. It should read:

Get-DbaRegServerGroup -SqlInstance sql2017 -Group HR\Development| **Move-DbaRegServerGroup** -NewGroup Web

I also double checked on my local instance and these commands worked fine:

Get-DbaRegServer -SqlInstance localhost -Name 'localhost\SQL2017' | Move-DbaRegServer -Group Web
Get-DbaRegServerGroup -SqlInstance localhost -Group HR\Dev| Move-DbaRegServerGroup -NewGroup Web

Note that for both Move-DbaRegServer and Move-DbaRegServerGroup they do not support local registered servers or groups. The registered servers and groups must be in a central management server.

**Comment by dvenardos** [comment]
@lancasteradam, it may be because I have two instances of vsOfficeTSDB which is why I am specifying the group in the Get-DbaRegServer call. If I leave the group parameter it doesn't fail until it tries to complete the move.

Get-DbaRegServer -SqlInstance vssqlcms01\sql17 -ServerName vsOfficeTSDB | Move-DbaRegServer -Group Test

WARNING: [15:22:13][Move-DbaRegServer] Failed to move vsOfficeTSDb to Test on VSSQLCMS01\SQL17 | Violation of UNIQUE KEY constraint 'UQ_sysmanagement_unique
_server_name_per_group'. Cannot insert duplicate key in object 'dbo.sysmanagement_shared_registered_servers_internal'. The duplicate key value is (8, vsOffi
ceTSDb).
The statement has been terminated.
Name         ServerName   Group        Description Source                    
----         ----------   -----        ----------- ------                    
vsOfficeTSDb vsOfficeTSDb Test                     Central Management Servers
vsOfficeTSDb vsOfficeTSDb Unclassified             Central Management Servers

**Comment by lancasteradam** [comment]
@dvenardos, I see what you mean. With that constraint 'UQ_sysmanagement_unique
_server_name_per_group' it does impose uniqueness per group. You could try using the -Group param for Get-DbaRegServer and that might help. Another thought is that if you have a unique naming convention then that should allow the registered servers to be moved around more easily.

**Comment by dvenardos** [comment]
@lancasteradam, that is the defect that I am reporting. When I use the command below I get the reported error.
Get-DbaRegServer -SqlInstance vssqlcms01\sql17 -ServerName vsOfficeTSDB -Group Unclassified | Move-DbaRegServer -Group Test

**Comment by lancasteradam** [comment]
@dvenardos, thanks for clarifying that. I was able to duplicate the problem so I'm looking into it.
