### ISSUE TITLE
Restore-DbaDatabase -sqlInstance parameter

### ISSUE THREAD

**Issue by darren-abbott** [sqlcollaborative/dbatools#7114]
The documentation for Restore-DbaDatabase states that the -sqlInstance parameter is "The target SQL Server instance or instances" which I read as it implying that it can accept multiple instances in a list, to restore a backup to multiple servers in one command.  However, entering more than one instance makes the command fail.  Doesn't look like the code loops through a list of instances so maybe the doc needs amending or the code needs adjusting?

**Comment by lancasteradam** [comment]
@darren-abbott, thanks for mentioning this. I've submitted a PR to fix the documentation. The -SqlInstance param only accepts a single instance for this command.
