### ISSUE TITLE
[Bug] PowerShell 7 and Publish-DbaDacPackage => Could not load file or assembly Microsoft.Build, Version=15.1.0.0

### ISSUE THREAD

**Issue by alvipeo** [sqlcollaborative/dbatools#7116]
$PSVersionTable.PSVersion (Windows 10 x64)

Major  Minor  Patch  PreReleaseLabel BuildLabel
----- | ----- | ----- | --------------- ----------
7      1      1

I took the script from here - [using dacpac functions to clone sql server databases](https://dbatools.io/clone/). Go to **Full Script**.

When running it I get the following exception:
> [path...]PowerShell\Modules\dbatools\1.0.137\allcommands.ps1:87345
 Line |
87345 |          throw $records[0]
      |          ~~~~~~~~~~~~~~~~~
      | Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral,
      | PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

**Comment by alvipeo** [comment]
I just checked, it works for:
> PSVersion                      5.1.19041.610

**Comment by andreasjordan** [comment]
Sorry to say, but not all commands work on PowerShell 7. So I will close this for now, but you can reopen it if you have further questions.

**Comment by potatoqualitee** [comment]
try now  @alvipeo, we changed the libraries a lot in v1.1.0
