### ISSUE TITLE
Get-DbaOrphanUser returns also users of type 'SQL User without login'

### ISSUE THREAD

**Issue by fvanderhaegen** [sqlcollaborative/dbatools#7118]
#### Host used

- [x] powershell.exe
- [ ] ISE
- [x] VS Code
- [ ] Other (please specify)

#### Errors Received

```
No errors
```

#### Steps to Reproduce

Execute Get-DbaDbOrphanUser on a database that contains an user of type 'SQL User without login'

#### Expected Behavior

Users of that type shouln't be listed in the resultset.
Such users can be used in the context of 'Execute as'

#### Actual Behavior

The users appear in the resultset

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
PowerShell Version        : 5.1.14393.3383
dbatools latest installed : 1.0.116
Culture of OS             : nl-BE

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU15) (KB4577775) - 13.0.5850.14 (X64)   Sep 17 2020 22:12:45   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

```sql
us_english
```

**Comment by lancasteradam** [comment]
@fvanderhaegen, so far I'm not able to duplicate this issue using the latest dbatools code.
![Get-DbaDbOrphanUser](https://user-images.githubusercontent.com/68036988/106371760-26bc2d00-631d-11eb-98c7-ec42e7a67556.png)


Could you provide more details on how to setup the scenario? You could provide the output of this query:

```
SELECT 
	len(a.sid) AS SidLength 
,	a.name AS UserName
,	a.principal_id
,	a.type
,	a.authentication_type
,	b.name AS LoginName
FROM 
	sys.database_principals a 
LEFT JOIN 
	sys.server_principals b 
		ON a.sid = b.sid
WHERE 
	a.name IN ('enter db user name1', 'enter db user name 2');
```

Or run these commands:

```
$server = Connect-DbaInstance -SqlInstance "enter instance name"
$db = $server.Databases | Where-Object Name -eq "enter db name here"
$db.Users | Where-Object Name -eq "enter db user name here" | Select-Object *
```

**Comment by fvanderhaegen** [comment]
@lancasteradam: this are the results of the requested t-sql command:

SidLength UserName   principal_id type  authentication_type LoginName
----------- ------------- ------------- ----- ---------------------- -------------
16             MyUser        5                  S       1                               NULL

This is a printscreen out of ssms:
![image](https://user-images.githubusercontent.com/23452667/106426031-2a5acb80-6465-11eb-98d5-1f4ed7cd7686.png)

**Comment by fvanderhaegen** [comment]
Apparently something was wrong with my installation of dbatools.
When I removed the module (+ reboot) and did a clean install the user didn't reappear in the result of Get-DbaDbOrphanUser.
