### ISSUE TITLE
BUG: Get-DbaSpn

### ISSUE THREAD

**Issue by forensicsguy20012004** [sqlcollaborative/dbatools#713]
### Is this a *feature* OR *bug*:
bug

Latest version release of dbatools

result of Get-DbaSpn

> ComputerName : Myserver.domain.net
InstanceName : MSSQLSERVER
SqlProduct : SQL Server 20xx Enterprise Edition (64-bit)
InstanceServiceAccount : NT SERVICE\MSSQLSERVER
RequiredSPN: MSSQLSvc/Myserver.domain.net:port
IsSet : False
Cluster : False
TcpEnabled : True
Port : MyPort
DynamicPort : False
Warning : None
Error : SPN missing

However with setspn -l Myserver:

> MSSQLSvc/Myserver.domain.net:Port
MSSQLSvc/Myserver.domain.net
Since my SQL is running at [NT SERVICE\MSSQLSERVER], Get-DbaSpn does not show a valid SPN but the old school setspn -l does show a valid SPN.

Looks like something that just needs to be investigated a little bit further. Either way...AWESOME WORK.

I made comment of this same issue on: https://github.com/sqlcollaborative/dbatools/issues/685. I think you could probably close this issue if you address what I found in https://github.com/sqlcollaborative/dbatools/issues/685

thanks

**Comment by forensicsguy20012004** [comment]
Thank you

**Comment by ctrlbold** [comment]
Let me know if that works for you! It's now in the dev branch.
