### ISSUE TITLE
[Bug] Repair-DBAOrphanUser with RemoveNotExisting returns error on Windows Logins

### ISSUE THREAD

**Issue by gpollokoff** [sqlcollaborative/dbatools#7130]
#### Host used

- [X ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Incorrect syntax near '\'. ---> System.Data.SqlClient.SqlException: Incorrect syntax near '\'.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
                           --- End of inner exception stack trace ---
TargetObject          : [EDW_NSAD_DM]
CategoryInfo          : NotSpecified: ([EDW_NSAD_DM]:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Remove-DbaDbOrphanUser,Stop-Function
ErrorDetails          : Incorrect syntax near '\'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1: line 86001
                        at Remove-DbaDbOrphanUser<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1: line 59753
                        at Repair-DbaDbOrphanUser<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1: line 61838
                        at <ScriptBlock>, C:\DBA\PowershellScripts\debug.ps1: line 1
PipelineIterationInfo : {0, 1}


```

#### Steps to Reproduce
Execute the following:

Repair-DbaDbOrphanUser -SqlInstance sql1 -Users 'domain\group name' -Database dbname -RemoveNotExisting

#### Expected Behavior

Expected group to be removed from database as it is no longer a valid login.

#### Actual Behavior

Error occurs indicating Incorrect syntax near '\'

Note: Executing Remove-DbaDbOrphanuser does work, sort of.  It seems to attempt to remove the user twice - the first attempt succeeds as expected and the second attempt throws an error because the login no longer exists.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.133
Culture of OS             : en-US

#### SQL Server:

```sql
Microsoft SQL Server 2012 (SP4-GDR) (KB4583465) - 11.0.7507.2 (X64) 
	Nov  1 2020 00:48:37 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

```

```sql
us_english
```

**Comment by lancasteradam** [comment]
@gpollokoff, could you provide more details on the setup of the orphaned user and also run the command with -Verbose? I tried duplicating the issue with an orphaned windows user and an orphaned windows group and the error did not occur.

Looking at the code it seems the "Incorrect syntax" error possibly came from the drop user statement from Remove-DbaDbOrphanUser. There may be a path through the code where the brackets around the user name "[domain\user]" are not present and it results in the syntax error.

**Comment by gpollokoff** [comment]
Here is the setup:
1.  Create windows user login
USE [master]
GO
CREATE LOGIN [LOE\sluser-win] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO

2.  Create database user from login
  USE [DBAAdmin]
GO
CREATE USER [LOE\sluser-win] FOR LOGIN [LOE\sluser-win]
GO
USE [DBAAdmin]
GO
ALTER ROLE [db_datareader] ADD MEMBER [LOE\sluser-win]
GO
USE [DBAAdmin]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [LOE\sluser-win]
GO

3.  Drop login.
USE master
GO
DROP LOGIN [LOE\sluser-win]

Now the user account exists in database but is no longer a valid server
login.

4.  Execute powershell command
Repair-DbaDbOrphanUser -SqlInstance mddbsqladmin1 -Database dbaadmin -Users
'loe\sluser-win' -RemoveNotExisting -Verbose
VERBOSE: [08:53:03][Repair-DbaDbOrphanUser] Validating users on database
'[DBAAdmin]'.
VERBOSE: [08:53:04][Repair-DbaDbOrphanUser] Orphan users found
VERBOSE: Performing the operation "Remove-DbaDbOrphanUser" on target
"DBAAdmin".
VERBOSE: [08:53:04][Repair-DbaDbOrphanUser] Calling
'Remove-DbaDbOrphanUser'.
VERBOSE: [08:53:04][Remove-DbaDbOrphanUser] Call origin:
Repair-DbaDbOrphanUser.
VERBOSE: [08:53:04][Remove-DbaDbOrphanUser] Orphan users found.
VERBOSE: [08:53:06][Remove-DbaDbOrphanUser] User loe\sluser-win does not
own any schema. Will be dropped.
WARNING: [08:53:06][Remove-DbaDbOrphanUser] Failure | Incorrect syntax near
'\'.

Also, note that if I bracket the user name in the command (
Repair-DbaDbOrphanUser -SqlInstance mddbsqladmin1 -Database dbaadmin -Users
'[loe\sluser-win]' -RemoveNotExisting -Verbose ) this is the result
VERBOSE: [09:10:13][Repair-DbaDbOrphanUser] Validating users on database
'[DBAAdmin]'.
VERBOSE: [09:10:14][Repair-DbaDbOrphanUser] No orphan users found on
database '[DBAAdmin]'.





Thank you,

Gordon

**Comment by lancasteradam** [comment]
Thanks @gpollokoff  for that additional info. I've added a PR with a proposed fix.
