### ISSUE TITLE
Get-DbaDependency gets stuck in loop when InputObject has a circular reference.

### ISSUE THREAD

**Issue by SamWalkerRxSense** [sqlcollaborative/dbatools#7139]
### Report

Get-DbaDependency gets stuck in loop when InputObject has a circular reference.

#### Host used
Name             : Visual Studio Code Host
Version          : 2020.6.0
InstanceId       : 447ac6de-6823-4100-86ee-ae7ba383d496
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.EditorServices.Services.PowerShellContext.EditorServicesPSHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

#### Errors Received
None.  The command is stuck in loop.

#### Steps to Reproduce
Create a couple inter dependent tables.
```
CREATE TABLE [dbo].[TableA](
	[TableAId] [int] NOT NULL,
	[TableBId] [int] NULL,
 CONSTRAINT [PK_TableA] PRIMARY KEY CLUSTERED 
(
	[TableAId] ASC
))
GO
CREATE TABLE [dbo].[TableB](
	[TableBId] [int] NOT NULL,
	[TableAId] [int] NOT NULL,
 CONSTRAINT [PK_TableB] PRIMARY KEY CLUSTERED 
(
	[TableBId] ASC
))
GO
ALTER TABLE [dbo].[TableA]  WITH CHECK ADD  CONSTRAINT [FK_TableA_TableB] FOREIGN KEY([TableBId])
REFERENCES [dbo].[TableB] ([TableBId])
GO
ALTER TABLE [dbo].[TableA] CHECK CONSTRAINT [FK_TableA_TableB]
GO
ALTER TABLE [dbo].[TableB]  WITH CHECK ADD  CONSTRAINT [FK_TableB_TableA] FOREIGN KEY([TableAId])
REFERENCES [dbo].[TableA] ([TableAId])
GO
ALTER TABLE [dbo].[TableB] CHECK CONSTRAINT [FK_TableB_TableA]
GO
```
Execute these
```
$tablea = Get-DbaDbTable -SqlInstance localhost -Database CircRef -table "tablea"
$tableA | Get-DbaDependency
## this is where it gets stuck
```
#### Expected Behavior
When descending the dependency tree and parent object is detected as a child
Then include child object in output and ascend dependency tree and continue to traverse the remaining siblings and children.

#### Actual Behavior
Command gets stuck with no output.

### Environmental information
```poweshell
PowerShell Version        : 7.1.0
dbatools latest installed : 1.0.135
Culture of OS             : en-US
```

#### SQL Server:

```sql
select @@VERSION
-- Microsoft SQL Server 2016 (SP1-GDR) (KB4505219) - 13.0.4259.0 (X64)   Jun 15 2019 19:20:12   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 19042: ) (Hypervisor) ```
select @@LANGUAGE
-- us_english
```

**Comment by lancasteradam** [comment]
Thanks @SamWalkerRxSense for the detailed report on this issue.
