### ISSUE TITLE
Copy-LinkedServer as SQL Server agent "Console not elevated, but elevation is required" and Export-LinkedServer "Can't connect to registry on [remoteServer]

### ISSUE THREAD

**Issue by Kevin-S-Lewis** [sqlcollaborative/dbatools#7146]
I think I have found a way round not requiring local admin on the local or remote server when using either of these two commands Copy-LinkedServer or Export-LinkedServer. I am also unsure as to why "Test-ElevationRequirement -ComputerName" is included within the Copy-LinkedServer when its not in Export-LinkedServer.

I would like a bypass option for Test-ElevationRequirement within the command Copy-LinkedServer. This was similarly discussed but not implemented here for Copy-DbaCredential: https://github.com/sqlcollaborative/dbatools/issues/5088, I am hopeful that the method of workaround would also be effective with this command (it uses the same underlying internal function Get-DecryptedObject after all.

Environment tested: Two nodes of an availability group server, lets call them Fred and Wilma. The SQL Engine and SQL Agent accounts run as standard domain accounts (FLINTSTONE\svcDinoEng, FLINTSTONE\svcDinoAgent), do not have local admin permissions to the operating system but are named sysadmins within the SQL instances. These are both default instances of SQL 2016 running on Windows 2016 and both have dbatools module at 1.0.134, 

If a SQL Agent job is created on Fred running the operating system command (N.B. This is just for test and a very poor usage example i.e assumes DBATools is installed, and assumptions are dangerous):

`powershell.exe -command Export-DbaLinkedServer -SqlInstance Wilma-Path c:\temp`

The expected return message is:

`Executed as user: FLINTSTONE\svcDinoAgent. WARNING: [09:46:00][Export-DbaLinkedServer] Can't connect to registry on Wilma. | Connecting to remote server   Wilma failed with the following error message : Access is denied. For more information, see the   about_Remote_Troubleshooting Help topic.  Process Exit Code 0.  The step succeeded.`

The docs say that local admin at this point is required, there are also workarounds for the other two commands to say that a credential is required (as SQL Agent can't raise an elevated command).. what about if we didn't do that - either because you're going down the route of Managed Service Accounts that can't be used as a stored credential within SQL Server, or you're following the Microsoft best practice of not running SQL Services under local admin accounts..

My method:
On each node (Wilma and Fred): 

1. Open the registry and grant the service account running the commands read permission on the following key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL<version>.<Instance Name>\Security
2. With an elevated PowerShell prompt run the following and add the service account running the commands read and execute permissions:
`Set-PSSessionConfiguration Microsoft.PowerShell -ShowSecurityDescriptorUI `
3. Test

Proposal: Add ByPassElevation variable to the commands that use Get-DecryptedObject and Test-ElevationRequirement. Those that are happy to give local admin everywhere can do so, those that are more restricted can follow the workaround method. 

Clearly more testing required, but I have also done the same with a Managed Service Account running under a scheduled task which has performed the same behaviour.

**Comment by potatoqualitee** [comment]
Interesting, we can add a dbatools config value to skip the requirement and then add it to `Test-ElevationRequirement`
