### ISSUE TITLE
[Bug] Get-DbaAgReplica -SqlInstance Dave -EnableException

### ISSUE THREAD

**Issue by Kevin-S-Lewis** [sqlcollaborative/dbatools#7168]
### Report

Get-DbaAgReplica with the EnableException parameter does not bubble the errors as expected and instead outputs as warnings.

#### Host used

powershell.exe

#### Errors Received

No error bubbled as Get-DbaAgReplica does not pass EnableException value through to Get-DbaAvailabilityGroup. Should Get-DbaAgReplica use the additional "-EnableException:$EnableException" when calling Get-DbaAvailabilityGroup?

#### Steps to Reproduce

Code to run:  Get-DbaAgReplica -SqlInstance Dave -EnableException

#### Expected Behavior

Error to be thrown stating: **The network path was not found**

#### Actual Behavior

Warning thrown stating: **WARNING: [11:01:38][Get-DbaAvailabilityGroup] Failure. | The network path was not found**

### Environmental information

PowerShell Version        : 5.1.19041.610
dbatools latest installed : 1.0.139
Culture of OS             : en-GB

#### SQL Server:

Microsoft SQL Server 2017 (RTM-GDR) (KB4583456) - 14.0.2037.2 (X64)   Nov  2 2020 19:19:59   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro for Workstations 10.0 <X64> (Build 19042: ) (Hypervisor) 

us_english

**Comment by lancasteradam** [comment]
@Kevin-S-Lewis, thanks for mentioning this. I've uploaded a PR with a proposed fix. As a workaround in the interim you could use a pipeline command like this:

`Get-DbaAvailabilityGroup -SqlInstance host1 -EnableException | Get-DbaAgReplica`
