### ISSUE TITLE
Inoke-DbaQuery with multiple result sets

### ISSUE THREAD

**Issue by BMS-DZPB** [sqlcollaborative/dbatools#7176]
Hey all:)

I'm struggling to get this working...

Executing a Stored Procedure with Inoke-DbaQuery which returns multiple result sets with at least one row each.
I'm only receiving the e first set as output...

`$test | Invoke-DbaQuery -Database master -Query '[POB_Dataload].[GetAllServiceUser]' -CommandType StoredProcedure`

Best

Matthias

**Comment by andreasjordan** [comment]
Have a look at the parameter -As

**Comment by BMS-DZPB** [comment]
Wow, that was quick and exactly what I needed!
Thanks @andreasjordan :)

Stupid me didn't see the solution right in front of my eyes...

**Comment by andreasjordan** [comment]
No problem, glad I could help.
