### ISSUE TITLE
Issue with Start-DBAMigration task

### ISSUE THREAD

**Issue by Kurama2121** [sqlcollaborative/dbatools#7179]
Trying to use the Start-DBAMigration task but it fails in a few places. I have attached the script output and the different logs requested from the report issues page. Let me know what else you need. 

This is the full text of the command im trying to run

**Comment by lancasteradam** [comment]
@Kurama2121, can you retry using Powershell 5.1? The usage of Powershell 7 might be a factor here.

Also, when creating a bug report please use the [template](https://github.com/sqlcollaborative/dbatools/issues/new?assignees=&labels=bugs_life&template=Bug_Report.md&title=%5BBug%5D) to fill out the required sections and don't attach any files with company-specific error output. I recommend you immediately edit your posting above and remove the file attachments for security reasons.

Kind regards,
Adam

**Comment by Kurama2121** [comment]
It worked, thank you. Sorry thought powershell 7 was preferred.
