### ISSUE TITLE
[Bug] Set-DbaDbQueryStoreOption command is not Excluding the System Database MSDB when executed

### ISSUE THREAD

**Issue by vkayar7** [sqlcollaborative/dbatools#7184]
#### Host used

- [ ] powershell.exe
- [ 1] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
I've not received any Error but the command (Enable Set-DbaDbQueryStoreOption) option is executing against system database MSDB as ExcludedDatabases option is only excluding master,model and tempdb only missing MSDB. QueryStore can't be enabled on any system databases.
```

#### Steps to Reproduce
Set-DbaDbQueryStoreOption -SqlInstance ServerName -AllDatabases -State ReadWrite -CaptureMode AUTO -MaxPlansPerQuery 200 -MaxSize 1024 -StaleQueryThreshold 30 -CleanupMode AUTO -FlushInterval 900 -CollectionInterval 60 -WaitStatsCaptureMode ON -EnableException

#### Expected Behavior
Exclude all the system Databases and run against all the User databases.

#### Actual Behavior

This is the partial result where it's saying that QueryStore is enabled on MSDB database. Even though message says enabled, it's not enabled which is expected behavior on System Database.

Database                              : msdb
ActualState                           : ReadWrite
DataFlushIntervalInSeconds            : 900
StatisticsCollectionIntervalInMinutes : 60
MaxStorageSizeInMB                    : 1024
CurrentStorageSizeInMB                : 0
QueryCaptureMode                      : Auto
SizeBasedCleanupMode                  : Auto
StaleQueryThresholdInDays             : 30

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.128
Culture of OS             : en-US
#### SQL Server:

```sql
/* Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64)   Oct 31 2020 02:43:57   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) */
```

```sql
/* us_english */
```

**Comment by lancasteradam** [comment]
@vkayar7, thanks for reporting this issue. I recommend for security purposes that you edit the bug description and remove the ComputerName and SqlInstance values under the "Actual Behavior" section.

Kind regards,
Adam

**Comment by niphlod** [comment]
Ahem .... QueryStore can be enabled against MSDB... https://www.sqlskills.com/blogs/erin/sql-server-query-store-default-settings/ . So the function is working as intended ...

**Comment by niphlod** [comment]
btw, big thanks to @lancasteradam who's contributing like crazy 🕺 👏

**Comment by vkayar7** [comment]
@niphlod sorry my bad, I was not knowing that and it's not visible on SSMS so I thought it's same for MSDB as other System Db's. Closing the bug.

**Comment by lancasteradam** [comment]
Thanks @niphlod, much appreciated! It makes sense that msdb would be usable in QueryStore given the general query patterns against it. I'll close the PR.
