### ISSUE TITLE
Issue with Test-DbaSPN

### ISSUE THREAD

**Issue by LeonardRutkowski** [sqlcollaborative/dbatools#7185]
The Test-DbaSPN generation of the SPN seems to be incorrect, for the RequiredSPN variable.
The SPN for the instance name is correct, but the one for the port is incorrect.
MSSQLSvc/computername.domain.local:instancename - this is correct
 MSSQLSvc/#partialcomputername#portnumber.domain.local:portnumber - this is incorrect.
Should be: MSSQLSvc/computername.domain.local:portnumber
I'm using this is a pipeline to Set-DbaSPN.

btw, overall, great job. Love these tools, and they have been a great tool. Have tools I wrote, and used previously for configuring my SQL instances, but this goes beyond that.

**Comment by lancasteradam** [comment]
@LeonardRutkowski, based on the description it seems that the instance name is also contained within the computer name. For example, 'SQL2016' is in two places in this string:

MSSQLSvc/STAGINGSQL2016.dbatools.io:SQL2016

The code does a string replacement of the instance name and replaces it with the port number, so as an example with port 54000 the result would be:

MSSQLSvc/STAGING54000.dbatools.io:54000

I've uploaded a PR with a proposed fix as noted above. If you would like to try out those minor code changes you can use the approach described here https://github.com/sqlcollaborative/dbatools/pull/7165#issuecomment-786956488

**Comment by LeonardRutkowski** [comment]
Hi Adam,
Your fix seems to have resolved the issue. I am currently using version 141, so I'm assuming the fix will be in the next, or future version.
I wasn't sure how to do the instructions you mentioned in 7165, so I updated the code from the PR into the 141 installed ps1 file.

Thanks for the quick assist.

Regards,
Leonard Rutkowski
Database Administrator
***@***.******@***.***>
Work: 704-749-2762
Mobile: 704-207-5009

**Comment by LeonardRutkowski** [comment]
FYI,
We are currently installing SQL 2019, so you may want to update the SQL version switch, but this isn't affecting me, at the moment.

Regards,
Leonard Rutkowski
Database Administrator
***@***.******@***.***>
Work: 704-749-2762
Mobile: 704-207-5009

**Comment by lancasteradam** [comment]
@LeonardRutkowski, great catch on that SQL 2019 display string, thanks for that. I added that piece to the PR. I recommend you edit your replies [here](https://github.com/sqlcollaborative/dbatools/issues/7185) to remove the text starting from your email signature to the end of the postings for security/privacy reasons.
