### ISSUE TITLE
[Bug] New-DbaAgentJob -Force option drops schedule?

### ISSUE THREAD

**Issue by cmuncan** [sqlcollaborative/dbatools#7194]
Attempting to use the `New-DbaAgentJob`.  the process I currently have is:

1. Create new operator 'New-DbaAgentOperator -Force'
2. Create new schedule 'New-DbaAgentSchedule -Force'
3. Create new job 'New-DbaAgentJob -Force'

If neither of the 3 exist, then it works without issue.

If however the job initially existed, the `New-DbaAgentJob with -Force` appears to drop the schedule too when it should not.

```
$connectedInstance = Connect-DbaInstance -SqlInstance $instance

New-DbaAgentOperator    -SqlInstance $connectedInstance -Operator $OperatorEmail -EmailAddress $OperatorEmail -WhatIf:$WhatIf -Verbose:$Verbose -Force -PagerDay EveryDay

$connectedInstance | New-DbaAgentSchedule -Schedule $AgentSchedule -StartDate $JobScheduleDate.ToString("yyyyMMdd") -StartTime $JobScheduleDate.ToString("HHmmss") -Force

$connectedInstance | New-DbaAgentJob -Job $AgentJob -Schedule $AgentSchedule -OwnerLogin "disabled_sa" -EmailOperator $OperatorEmail -EmailLevel "Always" -WhatIf:$WhatIf -Verbose:$Verbose -Force

```

Error I receive is:

`WARNING: [16:28:15][New-DbaAgentJob] Something went wrong creating the job | The specified @name ('CHG________ :: emailo@domain.com ::') already exists.`

Shouldn't the -Force flag recreate the job if it already exists?

#### Host used

- [ ] powershell.exe
- [X] ISE
- [X] VS Code
- [ ] Other (please specify)

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.141
Culture of OS             : en-US
```

**Comment by lancasteradam** [comment]
@cmuncan, I recommend you remove your email address from the posting above (in the error message output).

Yes, "New-DbaAgentJob -Force" will drop the schedule when the existing job is removed. This is consistent with the default behavior in SSMS for unused schedules.

While troubleshooting this I noticed that pre-connected instances lead to caching issues with job schedules that have been deleted from the server. Even after calling Refresh() on the SMO server object it still held a reference to a deleted schedule. You'll see in the example code below I don't call Connect-DbaInstance prior to the other commands, but instead pass in the server info so that each command can obtain a fresh connection.

Example working code:

**Option 1**
```
$InstanceName = "localhost"
$OwnerLogin = "enter job owner here"
$OperatorEmail = "enter email address here"
$EmailLevel = "Always"
$WhatIf = $false
$Verbose = $true
$AgentScheduleName = "dbatools_test_schedule1"
$JobScheduleDate = "20210316"
$JobScheduleTime = "140000"
$AgentJobName = "dbatools_test_job1"

$newOperator = New-DbaAgentOperator -SqlInstance $InstanceName -Operator $OperatorEmail -EmailAddress $OperatorEmail -WhatIf:$WhatIf -Verbose:$Verbose -Force -PagerDay EveryDay
$newSchedule = New-DbaAgentSchedule -SqlInstance $InstanceName -Schedule $AgentScheduleName -StartDate $JobScheduleDate -StartTime $JobScheduleTime -Force
$newAgentJob = New-DbaAgentJob -SqlInstance $InstanceName -Job $AgentJobName -Schedule $AgentScheduleName -OwnerLogin $OwnerLogin -EmailOperator $OperatorEmail -EmailLevel $EmailLevel -WhatIf:$WhatIf -Verbose:$Verbose -Force
```

**Option 2**
```
$InstanceName = "localhost"
$OwnerLogin = "enter job owner here"
$OperatorEmail = "enter email address here"
$EmailLevel = "Always"
$WhatIf = $false
$Verbose = $true
$AgentScheduleName = "dbatools_test_schedule1"
$JobScheduleDate = "20210316"
$JobScheduleTime = "140000"
$AgentJobName = "dbatools_test_job1"

$newOperator = New-DbaAgentOperator -SqlInstance $InstanceName -Operator $OperatorEmail -EmailAddress $OperatorEmail -WhatIf:$WhatIf -Verbose:$Verbose -Force -PagerDay EveryDay
$schedule = Get-DbaAgentSchedule -SqlInstance $InstanceName -Schedule $AgentScheduleName
if ($null -eq $schedule) {
    $schedule = New-DbaAgentSchedule -SqlInstance $InstanceName -Schedule $AgentScheduleName -StartDate $JobScheduleDate -StartTime $JobScheduleTime -Force
}

$existingAgentJob = Get-DbaAgentJob -SqlInstance $InstanceName -Job $AgentJobName
if ($existingAgentJob) {
    $removedAgentJob = Remove-DbaAgentJob -SqlInstance $InstanceName -Job $AgentJobName -KeepUnusedSchedule -WhatIf:$WhatIf -Verbose:$Verbose
}
$newAgentJob = New-DbaAgentJob -SqlInstance $InstanceName -Job $AgentJobName -Schedule $AgentScheduleName -OwnerLogin $OwnerLogin -EmailOperator $OperatorEmail -EmailLevel $EmailLevel -WhatIf:$WhatIf -Verbose:$Verbose
```

**Comment by cmuncan** [comment]
> @cmuncan, I recommend you remove your email address from the posting above (in the error message output).

Thank you I've removed it.  Oops

> While troubleshooting this I noticed that pre-connected instances lead to caching issues with job schedules that have been deleted from the server. Even after calling Refresh() on the SMO server object it still held a reference to a deleted schedule. You'll see in the example code below I don't call Connect-DbaInstance prior to the other commands, but instead pass in the server info so that each command can obtain a fresh connection.

I noticed this also and that was my solution too to do 1 Connect-DbaInstance and then pass that to each call with `-SqlInstance`.

**Comment by cmuncan** [comment]
misunderstanding of how it all hangs together.  after it was explained.  fully understand now and closing the request
