### ISSUE TITLE
Issue with Invoke-DbaQuery looping and variables

### ISSUE THREAD

**Issue by Cparks1996** [sqlcollaborative/dbatools#7197]
I seem to be running into trouble when I am looping through an array ($vmnames) which is just a list of server names from my Azure environment.

foreach ($vmname in $vmnames)
{
    invoke-dbaquery -SqlInstance $sqlInstance -Database $databasename -SqlCredential $cred -SqlParameters @{ vmname = $vmname} `
    -Query "delete from dbo.AzureAvailableServers where [Server Name] = @vmname"
}

The error that I'm getting is: "Failed during execution | No mapping exists from object type Microsoft.Azure.Commands.Compute.Models.PSVirtualMachineList to a known managed provider native type"

**Comment by niphlod** [comment]
Try a .toString() on the value of sqlparams, it seems that the "native"
value type is a tad bit too exotic


Il mar 16 mar 2021, 21:44 Cparks1996 ***@***.***> ha scritto:

**Comment by Cparks1996** [comment]
Well that resolved that issue but then I get:

"Failure | Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool."

I thought that if I ran "Clear-DbaConnectionPool" that would resolve it but no luck.

**Comment by Cparks1996** [comment]
Also I will note that a colleague of mine recommended I use the dbatools module instead of sqlserver so I am still new to how this all works on the backend and what the certain error messages mean and how to troubleshoot.

**Comment by andreasjordan** [comment]
> which is just a list of server names from my Azure environment.

Can you please prove that? It should be a list of strings, but it seems to be something different.

`$vmnames[0].GetType()`

**Comment by Cparks1996** [comment]
Each instance in the array is a string I just checked. I also was not referencing the .Name property in my -SqlParameters flag which was throwing it. 

I think I have everything resolved now.

**Comment by niphlod** [comment]
perfect, if so close the issue ;-)
