### ISSUE TITLE
Encountering error stating "The given ColumnMapping does not match up with any column in the source or destination."

### ISSUE THREAD

**Issue by cvillegashak** [sqlcollaborative/dbatools#7206]
### Report

Write-DbaDbTableData with -AutoCreateTable or without it as well halfway through leads to an error stating: "The given ColumnMapping does not match up with any column in the source or destination." There isn't much as far as details past this and when I review the table and output it should be writing the entire datatable. Even using a -WhatIf I can see that the command should succeed.

#### Host used

- [x] powershell.exe
- [x] ISE
- [x] VS Code
- [ ] Other (please specify)

#### Errors Received
writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: The given ColumnMapping does not match up with any column in the source or destination. ---> System.Management.Automation.MethodInvocationException:
                        Exception calling "WriteToServer" with "1" argument(s): "The given ColumnMapping does not match up with any column in the source or destination." --->
                        System.InvalidOperationException: The given ColumnMapping does not match up with any column in the source or destination.
                           at System.Data.SqlClient.SqlBulkCopy.AnalyzeTargetAndCreateUpdateBulkCommand(BulkCopySimpleResultSet internalResults)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)  
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
                           at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at Invoke-BulkCopy(Closure , FunctionContext )
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
                           --- End of inner exception stack trace ---
TargetObject          : ----
CategoryInfo          : NotSpecified: (----:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Write-DbaDbTableData,Stop-Function
ErrorDetails          : The given ColumnMapping does not match up with any column in the source or destination.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.140\allcommands.ps1: line 87504
                        at Write-DbaDbTableData<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.140\allcommands.ps1: line 78899
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

#### Steps to Reproduce

1. Use Invoke-DbaQuery -As DataTable to gather any form of data and store it into a variable.
2. Test the variable to determine that the data is correctly formatted and stored as a correct object.
3. Use the command Write-DbaDbTableData -SqlInstance -Database -InputObject - Table -AutoCreateTable with the appropriate params filled in.

#### Expected Behavior

A table to be created with all of the rows put into the database correctly.

#### Actual Behavior

Halfway through encounter an error stating: "The given ColumnMapping does not match up with any column in the source or destination."

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.140
Culture of OS             : en-US

#### SQL Server:

Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64) 
	Oct 31 2020 02:43:57 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor)

us_english

**Comment by lancasteradam** [comment]
@cvillegashak, so far I'm not able to duplicate the problem. Do you have more specific steps to duplicate the problem?

I tried the following:

```
# This completes very quickly because the DataSet usage is optimized for the bulk copy. See the InputObject param documentation in Write-DbaDbTableData.
$random = Get-Random
$tableName = "MyTestData_$random"
$query = "SELECT [CityID]
      ,[CityName]
      ,[StateProvinceID]
  FROM [WideWorldImporters].[Application].[Cities]"
$dataset = Invoke-DbaQuery -SqlInstance localhost -Database WideWorldImporters -Query $query -As DataSet
Measure-Command { $dataset | Write-DbaDbTableData -SqlInstance localhost -Database WideWorldImporters -Table $tableName -AutoCreateTable }

# This will take several minutes to complete because a DataTable is being used. See the InputObject param documentation in Write-DbaDbTableData.
$random = Get-Random
$tableName = "MyTestData_$random"
$dataTable = Invoke-DbaQuery -SqlInstance localhost -Database WideWorldImporters -Query $query -As DataTable
Measure-Command { $dataTable | Write-DbaDbTableData -SqlInstance localhost -Database WideWorldImporters -Table $tableName -AutoCreateTable }
```

Have you considered using the [Copy-DbaDbTableData](https://docs.dbatools.io/#Copy-DbaDbTableData) command? It allows a query to be used and is simpler and more efficient.

**Comment by cvillegashak** [comment]
Hey Adam! Thanks so much for the response. Yep, that’s what I ended up doing and it worked like a charm. ☺ This issue can be closed.


[http://webdownload.hunton.com/esignature/HAKLogo.png]
Christian Villegas
Enterprise Systems Engineer
cvillegas@HuntonAK.com<mailto:cvillegas@HuntonAK.com>
p
404.888.4201
m
404.416.6035

Hunton Andrews Kurth LLP
Bank of America Plaza, St 4100
600 Peachtree Street, N.E.
Atlanta, GA 30308
HuntonAK.com<http://www.huntonak.com/?utm_source=esighunton&utm_medium=email&utm_campaign=esigtracking>

**Comment by lancasteradam** [comment]
@cvillegashak, that is great to hear. Just an fyi, for security precaution you should edit your previous reply on GitHub and remove the info starting from your email signature to the end of your post:  https://github.com/sqlcollaborative/dbatools/issues/7206#issuecomment-820666649

This is one of the drawbacks to using the email reply feature. It's safer to open the page in GitHub and enter the reply directly so that email signatures and other details are not inadvertently posted.

**Comment by cvillegashak** [comment]
Done. Thanks for the heads up! :)
