### ISSUE TITLE
[Bug] Get-DbaServerRoleMember - Update of $login.Role not correct

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7214]
This code:

```
            foreach ($role in $roles) {
                $members = $role.EnumMemberNames()
                foreach ($member in $members) {
                    $l = $server.Logins | Where-Object { $_.Name -eq $member }
                    if ($l) {
                        Add-Member -Force -InputObject $l -MemberType NoteProperty -Name Role -Value $role.Name
                    }
                }
            }
```

will set the property only to the last role in the loop. So the information is not correct if the login is member of more than one role.

Is it really necessary to change the login object here? I discovered the function by chance and actually find it quite nice, but it should then better be integrated directly into Get-DbaLogin and contain an array of the roles.

Get-DbaDbRoleMember has the same problem.

**Comment by andreasjordan** [comment]
Here is the link to the code:
https://github.com/sqlcollaborative/dbatools/blob/bad1bca39ae535130b70d87f9c297d3f5cde3a9a/functions/Get-DbaServerRoleMember.ps1#L150-L160

I thought about it and now I probably understand the reason. Objects of type Login are to be returned so that they can be piped to other commands. In addition, however, the information about the role in which the login is a member should also be returned. 
But this property is not only (temporarily) stored for the output, but permanently in the object. So in the object of the login the last role "remains" and is output with subsequent outputs with Get-DbaLogin.
I think this is not desired, because this information is incomplete (if you are a member of more than one role).
But how can this be prevented?
Can we remove the property after the output with Select-DefaultView?

@awickham10 / @potatoqualitee : Can you please have a look?

**Comment by awickham10** [comment]
> Can we remove the property after the output with Select-DefaultView?

That makes sense to me. Permanently modifying $server.Logins seems like an unintended side effect. Another option could be cloning the object instead of adding then removing properties. I'll let @potatoqualitee weigh in. If she's good with it are you going to make that change or would you like me to?

**Comment by andreasjordan** [comment]
Just changed it to output a PSCustomObject. That should work well.

**Comment by andreasjordan** [comment]
I'll try to organize my thoughts a bit: We are dealing with two different types of SMOs here: logins and roles. However, the return of the command is a list of all the mappings between SMOs of these two types. Thus, if a login is a member of two roles, the login SMO is returned twice, with only one role in each case in the Role property. So each of these two returned SMO is false, because it contains only one of the two roles. In addition, the login SMO is permanently changed and contains the one last processed role beyond the runtime of the command, i.e. incorrect (incomplete) information.
The problem lies in the fact that the members of multiple roles can be output. If only one role could be processed, then the returned object would not need the additional Role property and we could actually return the original SMOs. But for this we can use `$role.EnumMemberNames()`, which is also used inside the command.

**Comment by potatoqualitee** [comment]
That does make sense. Perhaps we can add a column like SMOLogin and SMORole? If agreed, I'm happy to merge after changes 👍🏼

**Comment by andreasjordan** [comment]
That is a good idea. I will try this.

**Comment by andreasjordan** [comment]
It works, please have a look.

**Comment by potatoqualitee** [comment]
ur the best 💯 !
