### ISSUE TITLE
[Bug] Get-DbaLogin - Parameter Login has wrong type

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7215]
Declaration is `[object[]]$Login,`, but usage is `$serverLogins = $serverLogins | Where-Object Name -in $Login` - so the only possible type is a `[string[]]`.

Please correct me if I'm wrong.

There are other commands, that declare `[object[]]$Login,`...

**Comment by SQLDBAWithABeard** [comment]
Hiya, Thank you for examining the code and raising a question. This is stated in the guidelines for parameters as a requirement for all parameters.

https://github.com/sqlcollaborative/dbatools/wiki/standards#parameters

Is this causing any issues?

**Comment by andreasjordan** [comment]
I have tried to use Get-DbaServerRoleMember and passed a complete Login object into parameter -Login - as it is also of type [object]. Get-DbaServerRoleMember passed this just forward to Get-DbaLogin inside.

My code that returns nothing:

```
$login = Get-DbaLogin -SqlInstance SRV1 -Login sa
Get-DbaServerRoleMember -SqlInstance SRV1 -Login $login
```

My code that works fine:

```
$login = Get-DbaLogin -SqlInstance SRV1 -Login sa
Get-DbaServerRoleMember -SqlInstance SRV1 -Login $login.Name
```

When we don't use [object[]] but [string[] for the -Login parameters, that would be more obvious.

**Comment by andreasjordan** [comment]
And where in the guidelines is the [object[]] requirement exactly?

**Comment by SQLDBAWithABeard** [comment]
Yes, that is definitely a bug but in Get-DbaServerRoleMember not accepting the login object correctly. 

The guidelines say all parameters should accept multiple objects. It's maybe a little vague.

**Comment by andreasjordan** [comment]
Maybe it's only the documentation. In other commands (like Get-DbaAgentJobHistory), the documentation says "The name of the XXX", in Get-DbaServerRoleMember and in Get-DbaLogin it only says "The login(s) to process."
But in Get-DbaLastBackup also the documentation says "Specifies one or more database(s) to process" for [object[]]$Database, later using it in `Where-Object Name -In $Database`. 

Are there any commands that test for smo object vs. string? I only have found commands that use the name as a string.

My personal suggestion would be to change the documentation and add "The name of", but also change the type to [string[]], as a name can only be a string.

**Comment by SQLDBAWithABeard** [comment]
Thank you @andreasjordan
