### ISSUE TITLE
[Bug] Invoke-DbaDbShrink - Issue with handling larger db files due to Int32 data type.  Needs to be Int64.

### ISSUE THREAD

**Issue by davidgulotta** [sqlcollaborative/dbatools#7226]
In current form, unable to handle DB files over the capacity of Int32.

**Comment by jpomfret** [comment]
Thanks for the bug report @davidgulotta - in future please don't remove the bug report template from the issue - it's really useful when fixing issues to have as much information about the scenario as possible. 

Thanks @lancasteradam for more excellent bug squashing work!
