### ISSUE TITLE
Add functionality to Remove-DbaLogin to also remove mapped users in databases

### ISSUE THREAD

**Issue by ben-thul** [sqlcollaborative/dbatools#7228]
### Summary of new feature

Currently, calling `Remove-DbaLogin` will leave orphaned users in databases, requiring a second step to remove (now orphaned) users from any databases that login was in. I would like a parameter on `Remove-DbaLogin` that, if passed, would remove any user mapped to the login to be dropped to also be dropped.

### Proposed technical details (if applicable)

* User discovery would be done using the `EnumDatabaseMappings()` method on the login object (to cover the case where the user name and the login name don't match)
* Actual user removal would be delegated to `Remove-DbaDbUser`.
* Thinking of having the actual parameter take a validated set of something like "Normal","Forced" which would control whether `-Force` is passed to `Remove-DbaDbUser`.

### Latest version of dbatools as of writing

1.0.141

**Comment by andreasjordan** [comment]
I like this idea. I you need someone to review the code, let me know.

**Comment by ben-thul** [comment]
Thanks, @andreasjordan. Looking for greenlight from a project maintainer before proceeding. Once I have that, I'll make sure to mention this issue in the PR which should link it here.

**Comment by jpomfret** [comment]
Sounds like a good idea to me - only think I'm not sold on is having the param take normal\forced to control force on underlying `Remove-DbaDbUser` - I can see why we'd want it, just not sure on that implementation. 

Saying that though, I don't have a better idea at the moment, I'll think on it - but overall love the feature!

**Comment by wsmelton** [comment]
If you go by our normal convention from previous years (no clue if we still enforce this now) then `Remove-DbaLogin` would not be in scope to have it call `Remove-DbaUser`. The default answer is the module's intent is for providing the tools to create the needed scripts for DBAs (or the whoever wears the hat) to perform management needs. This would fall into we have the two remove commands that can be used by anyone to create their scripts to their environment requirements. 

The remove orphan users command was also created to clean those up as well. I don't know if we could try and support the two commands be piped together. The Input object code may have a slight issue that it won't know the databases to check for the login, but we may need to adjust the output of that remove login command to list them and make it easier.

I would not agree with having the two commands combined though. At most an Invoke command could be generated but I think that is overkill for this need.

**Comment by potatoqualitee** [comment]
I agree with Shawn, this really feels like a two-command scenario. It does seem like people want it, however. So if it can be done well and the PR contains tests, I'm open to a few of us reviewing it and agreeing if it's an ideal implementation. Until then, I'm going to close this issue but if anyone submits a PR, feel free to still reference the issue.
