### ISSUE TITLE
Appveyor rerun of failed jobs

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7229]
We have like 10 jobs that run per each commit. Sometimes a single job will fail because the runner was overloaded. If you run it again, it'll work.

I'd like to set up something that re-runs failed jobs up to 3 times.

Then we can get something beautiful like this, that I did manually. 

![image](https://user-images.githubusercontent.com/8278033/113508817-781dae00-9552-11eb-8ec4-55996bd3c805.png)

Each of these were X's and just needed 1 or 2 jobs re-run per. It's called Rebuilding an incomplete job step.

**Comment by niphlod** [comment]
lemme see what I can throw at it

**Comment by jpomfret** [comment]
This would be amazing ❤️

**Comment by niphlod** [comment]
something is ready ^_^

**Comment by potatoqualitee** [comment]
haha niph gave it to me but i was not motivated. I need to find this again, sorry for the delay Simone!

**Comment by andreasjordan** [comment]
Fixed by #7569?

**Comment by niphlod** [comment]
hopefully, it solves the same problem from within instead of from outside.

**Comment by potatoqualitee** [comment]
It does! I have 3 reported failures with just one test! So it tries it again 🥳
