### ISSUE TITLE
[Bug] Invoke-Command2 - $runspaceId not used in session name

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7231]
While investigating some issues with commands that use Invoke-Command2, I had a look at the names of the PSSessions and was   surprised that the names did not contain the RunspaceId.

The name is generated here:
https://github.com/sqlcollaborative/dbatools/blob/80a5c1cd7fd5b501df30760f9cfacc1e62c5be91/internal/functions/Invoke-Command2.ps1#L80-L84

The following underline is interpreted as part of the name of the variable, so `_$runspaceId_` should be `_$($runspaceId)_` to adopt the syntax of the other parts.

**Comment by andreasjordan** [comment]
Sorry to say, @kozloski : #7149 has introduced this bug...

**Comment by nvarscar** [comment]
Woops. Yeah, this needs to be fixed.

**Comment by andreasjordan** [comment]
Have my lab back online and will code that today...
