### ISSUE TITLE
Enable "-WarningAction SilentlyContinue" for commands that work remote like Set-DbaPrivilege

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7232]
I would like to call `Set-DbaPrivilege -ComputerName $computerName -Type IFI -WarningAction SilentlyContinue` to suppress the warning "WARNING: [...] already has Instant File Initialization Privilege on [...]".

The command uses Invoke-Command2 and inside the scriptblock there are lines with `Write-Warning` - so there might not be an easy solution.

Is there a general interest in this feature?

**Comment by wsmelton** [comment]
This would require removing the use of the messaging system for the most part because it manipulates the streams in PowerShell. You can try redirecting the stream but not sure that works with exactly either because of the message system in the module.

```powershell
Set-DbaPrivilege ... 3>$null
```

**Comment by andreasjordan** [comment]
What about not having this message as a warning? Is it really a warning that this feature is already enabled?
So I now think that the solution in this special command is to move the message from WARNING to VERBOSE.
For a more general solution: Maybe my implementation of getting messages from the scriptblock in Set-DbaNetworkConfiguration is a good role model?

**Comment by wsmelton** [comment]
Yeah I'd say in ScriptBlocks we only use verbose messages to allow user to still control that side.

**Comment by andreasjordan** [comment]
Then I'll open a PR to change WARNING to VERBOSE.

Then later on we can discuss changing all the verbose messages inside of script blocks to just collect them in an array and pass it out. Then we can use our message framework to display them.

**Comment by wsmelton** [comment]
There is not very easy and clean way to capture verbose messages. They are not treated the same as error and warning messages.
