### ISSUE TITLE
Add SQLServerVersions to Install-DbaFirstResponderKit

### ISSUE THREAD

**Issue by Ant-Green** [sqlcollaborative/dbatools#7242]
### Summary of new feature

Brent provides a SQLServerVersions.sql script as part of the first responder kit which we use in order to ensure we have installed the latest patches for SQL as part of yet another way to comply with CIS checks etc.

This script is missed as it doesn't start "sp_" in the FRK repo so the $sqlScripts param doesn't get the script populated.

What are the thoughts of adding this in even as an optional -Install switch, or by just creating it as part of the solution anyway along with the blitz scripts

### Proposed technical details (if applicable)
[switch]InstallSqlServerVersionsTable

if ($InstallSqlServerVersionsTable) {
$sqlscripts += "SQLServerVersions.sql"
}

Or
                # Install/Update each FRK stored procedure
                $sqlScripts = Get-ChildItem $LocalCachedCopy -Filter "sp_*.sql"
                $sqlScripts += "SQLServerVersions.sql"
### Latest version of dbatools as of writing

* 1.0.142

**Comment by niphlod** [comment]
nothing against even if we have our own buildreference

**Comment by Ant-Green** [comment]
Thanks it's as a double, triple check we do as part of the CIS standards that all builds should have the latest SP/CU and as it's all driven by T-SQL, we utilise the table provided in the FRK.

What option would be preferred, optional install switch or just bundle the script into the full release?

**Comment by niphlod** [comment]
right now it installs everything and there isn't a "what-to" selector so I'd go for full, if that's the only thing missing
