### ISSUE TITLE
CodeCov Hack - We were not compromised

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7245]
We have some codecov code in our repo but it was disabled long ago. 

@niphlod can you triple check with me?

https://github.com/sqlcollaborative/dbatools/blob/development/tests/appveyor.pester.ps1#L167

**Comment by niphlod** [comment]
AFAIK only the bash uploader was involved, and we do not use it. We generate the coverage data and upload it via pure powershell.

**Comment by andreasjordan** [comment]
Can this be closed?

**Comment by potatoqualitee** [comment]
yep!
