### ISSUE TITLE
Could not connect because the maximum number of ''1'' dedicated administrator connections already exists

### ISSUE THREAD

**Issue by RangaSQL** [sqlcollaborative/dbatools#7265]
Get-DbaAvailabilityGroup -SqlInstance ListnerName | Sync-DbaAvailabilityGroup

I use the above command to sync AlwaysOn nodes. "ListnerName" is the always-On listener. The commands works great, but see this message in the sql log everytime this is run.

Could not connect because the maximum number of ''1'' dedicated administrator connections already exists

**Comment by andreasjordan** [comment]
Can you run command with -Verbose to get an idea there this happens?
You could also use -Exclude to exclude some of the objects from the sync to find out which objects cause this.
Probably its "LinkedServers" or "Logins" who need the DAC.

**Comment by andreasjordan** [comment]
See #6372 for the root cause of this. Will close this here as a duplicate.
