### ISSUE TITLE
[Bug] Write-DbaDbTableData Transaction was deadlocked on tempdb table

### ISSUE THREAD

**Issue by mkellerman** [sqlcollaborative/dbatools#7266]
Docker container with PowerShell 7.1.3 (linux), dbatools 1.0.137, and python3 3.8.5.

My workflow consists of using python to collect data, produce a json file, and have Powershell massage the data, and push it to SQL Server.

After establishing a connection to SQL Server, I first clone the destination table in [tempdb] using a guid to randomize the temp destination table:
```powershell
$Query = "SELECT * INTO [tempdb].dbo.[${Table}_${Guid}] FROM [${Database}].dbo.[${Table}] WITH (NOLOCK) WHERE 1=2;"
Invoke-DbaQuery -SqlInstance $SqlInstance -Database $Database -Query $Query -EnableException
```

Then I Write-DbaDbTableData to the temp table:
```powershell
Write-DbaDbTableData -SqlInstance $SqlInstance -InputObject $InputObject -Database 'tempdb' -Table "${Table}_${Guid}" -EnableException -NoTableLock -Verbose
```

Then I MERGE the temp table into the actual destination table:
```powershell
$Query = @"
    MERGE [${Database}].dbo.[${Table}] as [t]
    USING [tempdb].dbo.[${Table}_${Guid}] as [s]
        ON $(($MergeOn | ForEach-Object { "[s].[$_] = [t].[$_]" }) -Join ' and ')  
    WHEN MATCHED THEN
        UPDATE SET $(($DestinationColumns | ForEach-Object { "[t].[$_] = [s].[$_]" }) -Join ', ')  
    WHEN NOT MATCHED BY TARGET THEN 
        INSERT ($(($DestinationColumns | ForEach-Object { "[$_]" }) -Join ', '))
        VALUES ($(($DestinationColumns | ForEach-Object { "[s].[$_]" }) -Join ', '));
"@
Invoke-DbaQuery -SqlInstance $SqlInstance -Database $Database -Query $Query -EnableException
```

And then a quick cleanup:
```powershell
$Query = "DROP TABLE [tempdb].[dbo].[${Table}_${Guid}];"
Invoke-DbaQuery -SqlInstance $SqlInstance -Database $Database -Query $Query -EnableException
```

This workflow is running with a Jenkins Job, running every 5 minutes.

I periodically (once per ~200 runs) get this error during the Write-DbaDbTableData.
```
VERBOSE: [00:10:02][Write-DbaDbTableData] FQTN processed: [tempdb].[dbo].[messages_95d38ddb-d389-4b10-ba2c-f944f2c05c6e]
PS>TerminatingError(): "Transaction (Process ID 55) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction."
PS>TerminatingError(): "Transaction (Process ID 55) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction."
PS>TerminatingError(): "Transaction (Process ID 55) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction."
```

It baffles me how there could be a lock on the temp table, as it is generated right before the the Write begins. Nothing else is reading/querying the temp table.

Am I doing something wrong? Is my workflow right? *Help!*

I've attached a copy of my Dockerfile:
[Dockerfile.txt](https://github.com/sqlcollaborative/dbatools/files/6381476/Dockerfile.txt)

**Comment by niphlod** [comment]
Are you sure it doesn't deadlock on the merge that comes after ? it is quite bonkers indeed that a randomly generated tempdb table gets deadlocked on inserting data.

**Comment by mkellerman** [comment]
100% sure. When it works, I see an additional verbose msg for Invoke-BulkCopy.

VERBOSE: [13:42:31][Write-DbaDbTableData] FQTN processed: [tempdb].[dbo].[tg_message_media_af41c603-be15-4f79-b34f-ba75be1eefec]
VERBOSE: [13:42:31][Invoke-BulkCopy] Importing in bulk to [tempdb].[dbo].[tg_message_media_af41c603-be15-4f79-b34f-ba75be1eefec]

And we are talking about inserting a few rows ( between 1 and 100 ).

**Comment by andreasjordan** [comment]
Some ideas:
* Don't use `-NoTableLock`
* Use a non pooled connection: `$server = Connect-DbaInstance -SqlInstance $SqlInstance -NonPooledConnection ; Write-DbaDbTableData -SqlInstance $server ...`

**Comment by andreasjordan** [comment]
@mkellerman Do you have a chance to try my ideas?

**Comment by mkellerman** [comment]
Not yet. I added some pauses in my script, and that has stopped the issue from occurring. I'll remove them and test.

-NoTableLock was added later on, but it was having those errors prior to be adding it. 

Will retest and get back to you. Thanks

**Comment by Vanguard-52236** [comment]
Please close this issue. We have unfortunatly moved away from using dbatools. Thank you for all your help.

**Comment by mkellerman** [comment]
Please close this issue. We have unfortunatly moved away from using dbatools. Thank you for all your help.
