### ISSUE TITLE
[Bug] Get-DbaDbOrphanUser returns fake positives for windows logins when login and user name don't match

### ISSUE THREAD

**Issue by zikato** [sqlcollaborative/dbatools#7268]
#### Host used

- [X ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```

```

#### Steps to Reproduce

Create login from Windows
Create Database with a user from login (user must have a different name than login)
Run `Get-DbaDbOrphanUser`

#### Expected Behavior

Show no orphaned users.
Function Get-DbaDbOrphanUser should check user - login mapping via SID and not name

#### Actual Behavior

Shows orphaned user

**Comment by jpomfret** [comment]
Hey @zikato are you able to test that PR for me please?

**Comment by zikato** [comment]
I can try (probably tomorrow though). Is it just cloning the PR, importing the module from PR instead of my normal modules and running it?

**Comment by jpomfret** [comment]
I usually do this to pull a specific PR\branch down into a local branch, check that out and then import the psd1 from the git repo.
```
git fetch upstream pull/7268/head:pr7268
git checkout pr7268
Import-Module .\dbatools.psd1 -force
```
Let me know if you need any help.

**Comment by zikato** [comment]
I still had some false positives, I think it's case sensitive - because it returned "orphaned" users that had different casing between login and user.

Is there a reason why it's not mapped using SID? Or why does the login created from Windows have special treatment from the other logic?
