### ISSUE TITLE
The Ability to Change file names when using New-DbaDatabase

### ISSUE THREAD

**Issue by AEaston99** [sqlcollaborative/dbatools#7273]
### Summary of new feature
To be able to change the file names in the New-DbaDatabase. Preferably as a parameter on the script.
* Clear/concise description of what the problem is that the new feature can solve.
The issue is that, not being able to set the file names means that we cannot follow our company's naming convention.
For example, in my company we have a very large estate. And I am designing a script to create new databases for us. It will be using dbatools were possible. Currently we have _data01 for data files and _log01 for log files.
### Proposed technical details (if applicable)
As you can see here it looks like _PRIMARY is hard coded.
![image](https://user-images.githubusercontent.com/60107806/117006572-84776100-ace0-11eb-96fa-08bb3264ec2b.png)
As you can see here it looks like _Log is hard coded.
![image](https://user-images.githubusercontent.com/60107806/117006766-bbe60d80-ace0-11eb-9bb8-855dfe675cd9.png)

### Latest version of dbatools as of writing
1.0.141 of the module dbatools

**Comment by andreasjordan** [comment]
I like this feature.

I had a look at the code and it is not very flexible. Maybe we can add a parameter that takes an array of hashtables that host the information like in the CREATE DATABASE command? This way the user has full contol over the filename, but on the other hand has to build the filenames beforehand.
Just an idea...

If you need help, let me know.

**Comment by AEaston99** [comment]
I don't want to over complicate this. I'm not 100% sure what you mean here.
Would a string value parameter not work? 
As the first time it is used here is  `$logname = $dbName + "_Log"` on line 303
Could this not be changed to `$logname = $dbName + "_" + $SQLLogName` for example
with then [String]$SQLLogName being a parameter?

**Comment by andreasjordan** [comment]
Yes, a string value parameter would work. But you need two, one for data an one for log, don't you?

I can not guarantee that it will be merged, but go ahead and open a pull request.
