### ISSUE TITLE
[Bug] Export-DbaDbRole Not Including Roles For Multiple Databases Specified With -ExcludeFixedRole

### ISSUE THREAD

**Issue by seanwhitepc** [sqlcollaborative/dbatools#7275]
#### Host used

- [X] powershell.exe
- [X] ISE
- [X] VS Code
- [ ] Other (please specify)

#### Errors Received

No errors.

#### Steps to Reproduce

`Export-DbaDbRole -SqlInstance InstanceGoesHere -Database Databases,Go,Here -ExcludeFixedRole  -FilePath ".\Instance.DatabaseRoles.sql"`

#### Expected Behavior

The file "Instance.DatabaseRoles.sql" would have the user-created database roles for the databases "Databases", "Go", and "Here" in one file.

#### Actual Behavior

The file "Instance.DatabaseRoles.sql" only has the database roles for one database.  (Which database it is looks to be not be related to the order specified.  In actuality, I passed 6 databases in, and only the roles for the 3rd database ended up in the file.)

Including `-Append` outputs all user database roles.
**Not** including `-ExcludeFixedRole` includes all user database roles, along with system ones.

### Environmental information

```
PowerShell Version        : 5.1.19041.906
dbatools latest installed : 1.0.145
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64) 
	Nov  2 2020 18:35:09 
	Copyright (C) 2019 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)
```

```sql
us_english
```

**Comment by andreasjordan** [comment]
Hi,
I think this is the expected behavior.

Have a look at the documentation:

> -FilePath
> Specifies the full file path of the output file. If left blank then filename based on Instance name, Database name and date is created.
> If more than one database or instance is input then this parameter should normally be blank.

The content of every database is written to the same file. So you want to add `-Append` or use `-Path` instead of `-FilePath`.

**Comment by andreasjordan** [comment]
I will close this as "no bug" / "works as designed", but you can reopen it if you have further questions.
