### ISSUE TITLE
[Bug] Restore-DbaDatabase - SMO not updated

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7278]
This problem is not limited to this command, but applies to all commands that do not perform the change by means of SMO but by SQL.
The problem occurs only when the SMO is reused.

To show this, I use this code:

```
$instance = 'SRV1'
$server = Connect-DbaInstance -SqlInstance $instance
$null = Restore-DbaDatabase -SqlInstance $server -Path '\\WIN10\SQLServerBackups\AdventureWorks2016.bak' -DatabaseName AdventureWorks
if (Get-DbaDatabase -SqlInstance $server   -Database AdventureWorks) { 'Database found' } else { 'No database found' }
if (Get-DbaDatabase -SqlInstance $instance -Database AdventureWorks) { 'Database found' } else { 'No database found' }
$server.Databases.Refresh()
if (Get-DbaDatabase -SqlInstance $server   -Database AdventureWorks) { 'Database found' } else { 'No database found' }
$null = Get-DbaDatabase -SqlInstance $server -Database AdventureWorks | Remove-DbaDatabase -Confirm:$false
```

![image](https://user-images.githubusercontent.com/66946165/117181336-663f5d00-add5-11eb-81df-f7824a135082.png)

So I create a server SMO `$server` and use it for Restore-DbaDatabase and Get-DbaDatabase. This way Get-DbaDatabase does not create a fresh new SMO but trusts the state of  `$server`. But because the restore was started by `$null = $server.ConnectionContext.ExecuteNonQuery($script)` (line 320 of Invoke-DbaAdvancedRestore) the SMO was not updated.

When I use Get-DbaDatabase with `$instance` then I get a fresh new SMO which fetches a fresh list of databases.
To be able to reuse the SMO, the restore command must update the list of databases with `$server.Databases.Refresh()`.

Because there might be multiple calls of Invoke-DbaAdvancedRestore I would suggest update the SMO at the end of Restore-DbaDatabase. 

What do you think, @Stuart-Moore ?

**Comment by andreasjordan** [comment]
To not update the SMO if it was newly created inside of Restore-DbaDatabase (when $SqlInstance is just a string and not an SMO) and thus would be destroyed a few milliseconds later anyway, we could probably test like this:
```
if ($RestoreInstance.Equals($SqlInstance) { $RestoreInstance.Databases.Refresh() }
```

**Comment by Stuart-Moore** [comment]
Yes, 320 is a hack as SMO doesn't support everything people want dbatools to suppor so we end up having to script it instead
That sounds like a good plan. For a lot of people they won't notice the small overhead over the restore. 


It you shove it at the end of the Restore-DbaDatabase 'wrapper' then it will be called in all cases, even if we add new ones. Or, you could just target the scripted ones in Invoke-DbaAdvancedRestore

**Comment by andreasjordan** [comment]
Ok, I'll open a PR for that.

**Comment by andreasjordan** [comment]
Putting it at the end worked well.
