### ISSUE TITLE
[Bug] Connect-DbaInstance - SMO is reused even if -NonPooledConnection is used

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7279]
The behavior can be shown very well at the command Install-DbaMaintenanceSolution, because it absolutely needs a connection with the option NonPooledConnection (to reuse a temp table).

I use this code:
```
$instance = 'SRV1'
$serverPooled = Connect-DbaInstance -SqlInstance $instance
Install-DbaMaintenanceSolution -SqlInstance $serverPooled -InstallJobs -ReplaceExisting
$serverNonPooled = Connect-DbaInstance -SqlInstance $instance -NonPooledConnection
Install-DbaMaintenanceSolution -SqlInstance $serverNonPooled -InstallJobs -ReplaceExisting
```

![image](https://user-images.githubusercontent.com/66946165/117185833-8c1b3080-adda-11eb-9a4b-6d7f74e754de.png)

In a first step I will update the new code path of Connect-DbaInstance to test for -NonPooledConnection when reusing an SMO and then not reusing it but building a new one. I am not yet sure what the options are, as I must "clone" the SMO with the authentication information and just change `.ConnectionContext.NonPooledConnection` to `$true`. I anybody has ideas - you're welcome to help.

**Comment by jpomfret** [comment]
Hey @awickham10 - does this help your issues with temp tables?

**Comment by potatoqualitee** [comment]
I'll ping @awickham10 on twitter! I'm curious too and know that I hadn't checked my notifications in a long time.

**Comment by awickham10** [comment]
No dice.

![image](https://user-images.githubusercontent.com/7840633/122938587-e21f4580-d340-11eb-8d91-51c1525509ff.png)

**Comment by andreasjordan** [comment]
Do you use the new code path? `Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true`

Do you use the option `-NonPooledConnection` with `Connect-DbaInstance`?

**Comment by awickham10** [comment]
I did not. Here's another attempt. I set experimental, registered it, restarted PowerShell instance, verified experimental still set, connected with `-NonPooledConnection`. 

First try - invalid object even though AutoCreateTable was specified
```
$processes | select Id, ProcessName | Write-DbaDataTable -SqlInstance $smo -Database 'DBA' -Table '#Processes' -AutoCreateTable
WARNING: [10:11:59][Write-DbaDbTableData] Failed to bulk import to [DBA].[dbo].[#Processes] | Invalid object name '#Processes'.
Database name 'DBA' ignored, referencing object in tempdb.
Database name 'DBA' ignored, referencing object in tempdb.
```

Second try - oh it does exist?
```
$processes | select Id, ProcessName | Write-DbaDataTable -SqlInstance $smo -Database 'DBA' -Table '#Processes' -AutoCreateTable
WARNING: [10:12:01][Write-DbaDbTableData] Failed to create table [DBA].[dbo].[#Processes] | There is already an object named '#Processes' in the database.
```

Third try - didn't specify AutoCreateTable, but it doesn't exist
```
$processes | select Id, ProcessName | Write-DbaDataTable -SqlInstance $smo -Database 'DBA' -Table '#Processes'
WARNING: [10:12:08][Write-DbaDbTableData] Table does not exist and automatic creation of the table has not been selected. Specify the '-AutoCreateTable'-parameter to generate a suitable table.
```

**Comment by andreasjordan** [comment]
Ok, thanks. I'll have a look.

**Comment by potatoqualitee** [comment]
Thank you @andreasjordan 🥳

**Comment by andreasjordan** [comment]
The short answer is: Write-DbaDataTable does not work with temp tables....

**Comment by awickham10** [comment]
> The short answer is: Write-DbaDataTable does not work with temp tables....

Haha yes... see [this line](https://github.com/sqlcollaborative/dbatools/blob/982d4eb3cad9e1b095c0fcbad415e0174f93df8f/functions/Write-DbaDbTableData.ps1#L522
). Write-DbaDbDataTable establishes a new connection for the bulk copy instead of using the SMO connection.

I proposed [this change](https://github.com/sqlcollaborative/dbatools/pull/7009/commits/a52287c8ce4b96849371e3edcd622e66525e3b81) as a solution but eventually closed it.

**Comment by andreasjordan** [comment]
Yes, see #6618 where I had a similar idea.

**Comment by andreasjordan** [comment]
The other problem is, that `$smo.Databases['tempdb'].Tables` does not show me the temp table...

**Comment by andreasjordan** [comment]
@awickham10 : I don't have time to day to look into that deeper. So can you please open a new issue for Write-DbaDbDataTable not working this temp tables? Then I can have a look in the next days if I find a solution.
But I have found: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/afa06d0a-c81a-405c-b7f2-51dbbef2ca3d/accessing-temporary-tables-using-smo?forum=sqlsmoanddmo

**Comment by awickham10** [comment]
Done! Thanks @andreasjordan.

https://github.com/sqlcollaborative/dbatools/issues/7459
