### ISSUE TITLE
[Bug] Install-DbaFirstResponderKit LocalFile

### ISSUE THREAD

**Issue by goforebroke** [sqlcollaborative/dbatools#7281]
#### Host used

- [X ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
Copy-Item : Cannot find path 'C:\Users\YOURUSERNAME\AppData\Local\Temp\SQL-Server-First-Responder-Kit-main because if does not exist
```

#### Steps to Reproduce

Install-DbaFirstResponderKit -SqlInstance "SQL1" -Database DBALocal -LocalFile C:\temp\SQL-Server-First-Responder-Kit-main.zip

#### Expected Behavior

Expect command to unzip first responder kit files to C:\Users\YOURUSERNAME\AppData\Local\Temp\SQL-Server-First-Responder-Kit-main

#### Actual Behavior

Command unzips files to root of temp..

C:\Users\YOURUSERNAME\AppData\Local\Temp

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

PowerShell Version         : 5.1.14393.4350
dbatools latest installed : 1.0.127
Culture of OS                  : en-US 

#### SQL Server:

N/A

**Comment by andreasjordan** [comment]
Hi, where did you get the zipfile from?
It looks like it's the zipfile your get from Brent directly. 
The difference is: The zipfile the command downloads from GitHub has all files inside a directory called "SQL-Server-First-Responder-Kit-$Branch", the zipfile from Brent has all files in the root directory of the zipfile.

To get the correct file from GitHub use:
```
Invoke-WebRequest -Uri "https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/archive/main.zip" -OutFile 'C:\temp\SQL-Server-First-Responder-Kit-main.zip' -UseBasicParsing
```

**Comment by goforebroke** [comment]
You are correct, I downloaded from Brent directly. Once I downloaded from the correct location, I installed without any issues
