### ISSUE TITLE
Export-DbaCredential returning credential_id instead of credential_identity when choosing to exclude password

### ISSUE THREAD

**Issue by SicilianNajdorf** [sqlcollaborative/dbatools#7282]
#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
replace THIS text WITH the OUTPUT of -- $ERROR[0] | SELECT *
```

#### Steps to Reproduce

Export-DbaCredential -SqlInstance server -ExcludePassword -FilePath mypath\cred.txt

#### Expected Behavior

In the result, WITH IDENTITY = should show the name of the credential - Basically the value of the credential_identity column in sys.credentials

In the result, WITH IDENTITY shows the value of credential_id in sys.credentials which is an arbitrary number. 

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.17134.858
dbatools latest installed : 1.0.145
Culture of OS             : en-ZA
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64)   Oct 31 2020 02:43:57   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
us_english
```

**Comment by niphlod** [comment]
note to self/fixer, when you need the password we go and take credential_identity from sys.credentials, while without password we take $server.Credentials.Id. We should instead pick $server.Credentials.Name .

**Comment by SicilianNajdorf** [comment]
I'm no expert but are you referring to this column?

![image](https://user-images.githubusercontent.com/82165401/117309683-f091ca80-ae82-11eb-9280-785357de58c4.png)

**Comment by niphlod** [comment]
ahem, not really.
this
![image](https://user-images.githubusercontent.com/122119/117313063-d9a0a780-ae85-11eb-9a38-36c09b430abc.png)

which, under the gui, triggers this

`CREATE CREDENTIAL [cred_name] WITH IDENTITY = N'cred_identity', SECRET = N'pass1'`

maps to this
![image](https://user-images.githubusercontent.com/122119/117313123-e8875a00-ae85-11eb-9121-0281249b62cd.png)

**Comment by SicilianNajdorf** [comment]
That's what I mean - I think.
The value in credential_identity is what's missing from the exported script...

![image](https://user-images.githubusercontent.com/82165401/117321757-b679f600-ae8d-11eb-873f-f225b3c8d499.png)


The SAS key one is missing SHARED ACCESS SIGNATURE and the credential for page blobs is missing the name in the identity field. 

Forgive me if all this is a long winded way of saying what you already said :)

**Comment by niphlod** [comment]
as long as it's confirmations, it's all ok :D 
but even if they weren't, it's always best to triplecheck.
