### ISSUE TITLE
[Bug] Export-DbaDbRole - wrong variable / wrong assignment

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7285]
Just by looking at the code, this looks wrong:

https://github.com/sqlcollaborative/dbatools/blob/c99e522842badabb98d41159dd98b11a8a8110ba/functions/Export-DbaDbRole.ps1#L329-L336

Line 331: The variables `$roleName` and `$userName` are not assigned in the code and should be replaced by those in line 333.
Line 333: This might need a `+` to use `+=` as in line 331.

@sqllensman : Can you please have a look?

**Comment by andreasjordan** [comment]
@potatoqualitee : Should we wait to feedback from the author or should I try to fix this?

**Comment by potatoqualitee** [comment]
udabess
