### ISSUE TITLE
Install-DbaInstance / Invoke-DbaAdvancedInstall - Get complete content of summary.txt

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7299]
### Summary of new feature

Until changed in January 2020 via #6308 / #6309, `$output.Log` contained the complete content of the summary.txt. This was changed to improve content of output on failures. I understand this and agree here, but with this feature request I want to focus on the output on success.
There I would like to have the complete content of summary.txt to be able to save it on the local maschine as a complete documentation of the install process.

### Proposed technical details (if applicable)

https://github.com/sqlcollaborative/dbatools/blob/f6dd5fb1fd75073ff59c0fe7fd7afd7b4b0b31e2/functions/Invoke-DbaAdvancedInstall.ps1#L151-L167

I would add a property `LogFileContent` to `$output`.

https://github.com/sqlcollaborative/dbatools/blob/f6dd5fb1fd75073ff59c0fe7fd7afd7b4b0b31e2/functions/Invoke-DbaAdvancedInstall.ps1#L124-L131

Inside of Get-SqlInstallSummary, I would add `ExitMessage` to store what is currently in `Content` (`Get-Content -Path $summaryPath | Select-String "Exit Message"`) and change `Content` back to the complete content of summary.txt.

https://github.com/sqlcollaborative/dbatools/blob/f6dd5fb1fd75073ff59c0fe7fd7afd7b4b0b31e2/functions/Invoke-DbaAdvancedInstall.ps1#L252-L255

I would change `$summary.Content` to `$summary.ExitMessage` so that the value of this propety is the same as today.
I would set `$output.LogFileContent` to `$summary.Content`.

I would not output this new property as a default, so the output would not change for the user.

@nvarscar : What do you think?
@wsmelton : As the author of the change in January 2020: Would this change be ok for you?

I would provide a pull request if you agree.

**Comment by wsmelton** [comment]
The change on my PR was actually made to clean up success because the content when successful has no benefit.

Unless the content has changed now?

**Comment by nvarscar** [comment]
`Summary` is misleading, you'd expect a short message in a Summary property, not a few KB of text. `LogFileContent` is great, go ahead with the change.

**Comment by wsmelton** [comment]
Many terms we have can be considered misleading but in terms of SQL Server those that do installs know what that summary file would contain. Calling it SummayLog to be more clear if needed.

Calling it log something, which log will it be? We could be providing the details, summary, or any number of other logs that exists in that bootstrap folder.

Just saying.

**Comment by nvarscar** [comment]
SummaryLog is also ok, doesn't make much of a difference to me. You can also use `Add-Member -Type AliasProperty` to maintain backwards compatibility when you're renaming a property.
