### ISSUE TITLE
[Bug] Install-DbaInstance / Invoke-DbaAdvancedInstall - $output.Log is not a string but a PSObject with match result

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7300]
Because of this:

https://github.com/sqlcollaborative/dbatools/blob/f6dd5fb1fd75073ff59c0fe7fd7afd7b4b0b31e2/functions/Invoke-DbaAdvancedInstall.ps1#L131

the property Log is not the string we are interested in ("  Exit message:                  A computer restart is required. You must restart this computer before installing SQL Server.") but a MatchInfo object.
So just displaying $output.Log does not show anything:

![image](https://user-images.githubusercontent.com/66946165/117549484-e9adb800-b03a-11eb-96a7-91e2c0043bce.png)

My standard trick is to use ConvertTo-Json to see all the content at once - and there it is.

We should add ` | Select-Object -ExpandProperty Line` to just get the matched strings.

@nvarscar : Can you have a look? I can open a pull request if you agree.

**Comment by nvarscar** [comment]
Yeah we definitely should have a string there. Please open a PR if you're willing to :)

**Comment by andreasjordan** [comment]
That would be a breaking change because `$output.Log` would change the type. If someone now uses `$output.Log.Line` to get the string, that would fail. As `Log` is missleading in my eyes, I would like to add `$output.ExitMessage` and put the string there.
Then I see two possibilities:
* Remove `$output.Log`. 
* Still fill `$output.Log` like before (with the MatchInfo object) and maybe remove it later.

What do you think? I would prefer the first one.

**Comment by andreasjordan** [comment]
Ok, I've updated the branch and opened the pull request.
