### ISSUE TITLE
[Bug] Install-DbaInstance / Invoke-DbaAdvancedInstall - No test for pending reboot because of file rename

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7301]
I tried to install an instance and the install failed with: "A computer restart is required. You must restart this computer before installing SQL Server." which was not detected by Test-PendingReboot because it was a PendingFileRenameOperations, but here the `-PendingRename` is missing:

https://github.com/sqlcollaborative/dbatools/blob/f6dd5fb1fd75073ff59c0fe7fd7afd7b4b0b31e2/functions/Invoke-DbaAdvancedInstall.ps1#L180

Maybe we should add this parameter here as well:

https://github.com/sqlcollaborative/dbatools/blob/f6dd5fb1fd75073ff59c0fe7fd7afd7b4b0b31e2/functions/Invoke-DbaAdvancedInstall.ps1#L180

@nvarscar : Please have a look. Again: I can open the pull request if you like.

**Comment by nvarscar** [comment]
This is a feature requested in #6412 - to skip the pending file rename check. This might have been an issue on a user's end last time, but there's no way to tell since it was so long ago. If you want this re-enabled, I'd suggest locking it behind a dbatools config value.

**Comment by andreasjordan** [comment]
What about changing Test-PendingReboot to Test-DbaPendingReboot and export the command. Then I could run it before the install command and use the parameters that fit for my case?

**Comment by nvarscar** [comment]
I think the last time the discussion around it was that this functionality should not be something that we offer to the users, but since you have a real life use case, maybe it's time to revisit it. This should be a decision coming from maintainers, but if anyone asked me, I'd be fine with opening up this utility function to the public. 
Meanwhile, you can use the code from said function to check for file renames outside of the dbatools call.

**Comment by andreasjordan** [comment]
@potatoqualitee : What do you think?

**Comment by nvarscar** [comment]
In fact, I think @niphlod has a point: this might as well be controlled by a switch in both Update-DbaInstance and Install-DbaInstance. Something like `-NoPendingRenameCheck`. If that's how we agree it should work then we should re-enable that check by default and let users control it.

**Comment by andreasjordan** [comment]
To get an overview, here some code fragments:

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Install-DbaInstance.ps1#L166-L167

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Install-DbaInstance.ps1#L278

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Install-DbaInstance.ps1#L449-L459

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Invoke-DbaAdvancedInstall.ps1#L38-L40

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Invoke-DbaAdvancedInstall.ps1#L99

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Invoke-DbaAdvancedInstall.ps1#L179-L196

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Invoke-DbaAdvancedInstall.ps1#L302-L325

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Update-DbaInstance.ps1#L66-L68

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Update-DbaInstance.ps1#L200

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Update-DbaInstance.ps1#L429-L437

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Invoke-DbaAdvancedUpdate.ps1#L15-L17

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Invoke-DbaAdvancedUpdate.ps1#L74

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Invoke-DbaAdvancedUpdate.ps1#L96-L112

https://github.com/sqlcollaborative/dbatools/blob/98d48909d1853e34f73d31bb3399ec3598151985/functions/Invoke-DbaAdvancedUpdate.ps1#L204-L226

So we test for penting reboot:
* at start of Install-DbaInstance and stop if $restartNeeded -and (-not $Restart -or $computer.IsLocalHost)
* at start of Invoke-DbaAdvancedInstall and reboot if $restartNeeded -and $Restart
* at end of Invoke-DbaAdvancedInstall and reboot if ($installResult.ExitCode -eq 3010 -or $restartNeeded) -and $Restart
* at start of Update-DbaInstance and stop if $restartNeeded -and (-not $Restart -or ([DbaInstanceParameter]$resolvedName).IsLocalHost
* at start of Invoke-DbaAdvancedUpdate and reboot if $restartNeeded -and $Restart
* at end of Invoke-DbaAdvancedUpdate and reboot if ($updateResult.ExitCode -eq 3010 -or $restartNeeded) -and $Restart


Just found: The documentation for `-Restart` is not correct at Update-DbaInstance as the reboot is not done always but only if needed.

The switch `-PendingRename` is never used.

If we want to add a new switch like `-NoPendingRenameCheck`, we would have to pass that to the Invoke-DbaAdvanced* commands as well.

If #6412 was just an edge case - maybe we should again think of a config parameter. But one that suppresses the file rename check, so that normaly the file rename check runs. And if #6412 is reopend, the config parameter can be used. And we can remove the switch `-PendingRename` as it is never used. This would only change Test-PendingReboot and not 3 commands and a lot of documentation and tests. If we agree on the name of the config parameter, I would be willing to code that and open a pull request.

**Comment by nvarscar** [comment]
> The switch -PendingRename is never used.

That's intended.

> If #6412 was just an edge case - maybe we should again think of a config parameter. 

I can't prove (or disprove) that it was an edge case, even though it looks like one. And just because it's less code change, it doesn't mean that it's a better user experience. Switches are exposed to the user, while config parameters you need to know about and look into source code to be able to make use of them. If you really want this to be a config parameter, you can code it in as a switch with a default value extracted from a config parameter.

**Comment by andreasjordan** [comment]
To be clear: I want this to be a config parameter to not introduce more command parameters. I see your point in having a new switch parameter to all the commands. If you are willing to code that, please do that. I'm not willing to do that because I don't have enought time. If you are happy with the current implementation, we can just close this issue. I have learned a lot about how the command works and can work around this issue in my labs (I see this more a lab issue that a produtzion issue), so I'm fine.

**Comment by nvarscar** [comment]
Sure, no pressure. I initially thought you wanted to contribute, but I can (and will, at some point) do that on my own too :)
