### ISSUE TITLE
[RPC] Rewrite the dbatools library into PowerShell class

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#7302]
### Summary of new feature

Convert the dbatools library (contents of `dbatools.dll`) into a PowerShell Class. This would include converting the tests in the VS project into formal Pester tests as well (believe this is doable without much fuss/work).

### Proposed technical details (if applicable)

Use of PowerShell classes would mean the formal support of dbatools would be moved to Windows PowerShell 5.0+ and PowerShell ("core"). Our written support is to cover Windows PowerShell 3.0 and above, when a few items that have creeped into the module may or may not work in that version of PS already. I have not actually tried using PS 3.0/4.0 in years so not really sure what is broken now or not, but do expect some things might be.

- I believe converting to PowerShell Class will give more mobility in maintaining it going forward. (aka, not require knowing full on C# 😉 )
- No more working about compiled versions of the library for dotnet/.NET support between Windows PowerShell and PowerShell (PS classes are natively supported as of Windows PowerShell 5.0). It would be a simply adjustment to the import to ensure those class PS1 files are loaded properly.

**Comment by nvarscar** [comment]
As someone who used Powershell classes as a basis for a module, it's doable, but a bit painful. There are quite a few limitations with PS classes, including not being able to use them in command line after module import, not being able to assign such classes to function parameters, interfaces can be inherited one at a time, events support is non-existent, and so on.
C# lib makes it easier to use, yet there are definitely compilation difficulties, which, at this point, should just be a part of our pipeline.
I'm currently working on integrating C# code into dbops pipeline, perhaps I would eventually be able to improve how our internal lib is handled.

**Comment by wsmelton** [comment]
They can be assigned to function parameters.

**Comment by nvarscar** [comment]
> They can be assigned to function parameters.

Yeah, as long as they are defined in one file. If you dotsource-load your classes, they are no longer recognized. Here's an example: https://gist.github.com/nvarscar/2b14868fec577b5c1ecab70b4df06da4

> It can but requires knowing how to work with them and controlling how they are imported.

Seems like this can be achieved using "Using module" command. I doubt anyone knows about this :D  I definitely didn't. Thanks for the link btw. But also, from the very same article:

> The Using statement isn't documented and it isn't (yet) well known, so users are quite likely to use Import-Module or #Requires, or rely on module auto-loading, and then be frustrated because the class isn't imported. Or, more likely, they won't even know that the class exists until they hit a feature that requires it.

**Comment by wsmelton** [comment]
> Yeah, as long as they are defined in one file. 

Believe me 😉 it does not require one file it is all in how you import them for your module.

https://github.com/thycotic-ps/thycotic.secretserver/blob/453e552d913ff507ea088052b73b8a804e9006cb/src/Thycotic.SecretServer.psm1#L1-L19

**Comment by wsmelton** [comment]
> Seems like this can be achieved using "Using module" command. I doubt anyone knows about this :D I definitely didn't. Thanks for the link btw. But also, from the very same article:

Yes, it would be a breaking change to migrate this to a PowerShell class. In that breaking change will require the users to learn something knew 🥳

**Comment by potatoqualitee** [comment]
So sorry, this is not something I'm open to. I just talked on a Legacy Code podcast about being proud of supporting PS3 ;) 

I am aware of people who still have to use PS3 and I don't want to abandon them for PS Classes, which have been described as "painful" and "half-baked".

I very much enjoy coding for 5.1+ and do so in all of my other modules, but cannot budge on dbatools, at least for 1.x.

We may be able to revisit this and 5.1+ in the far future (5 years?) but at this point, I am not comfortable upping the requirements.
