### ISSUE TITLE
Get-DbaRegServer -Debug:$false Triggers Debug Messages

### ISSUE THREAD

**Issue by RandyInMarin** [sqlcollaborative/dbatools#7312]
I'm using $DebugPreference = 'Continue' to debug my script.  I can't suppress debug messages from the cmdlets called by Get-DbaRegServer.  It might be something with how Write-Message is used instead of Write-Debug.  This issue might not be isolated to just these cmdlets.  It likely to applies to verbose and information level messages.  The issue applies to both 5.1 and 7.1 versions of PowerShell.  

$DebugPreference = 'SilentlyContinue'
Get-DbaRegServer -SqlInstance 'cmsserver' -Group 'DISABLED', 'IGNORE'
<#
No debug messages as expected
#>

$DebugPreference = 'SilentlyContinue'
Get-DbaRegServer -SqlInstance 'cmsserver' -Group 'DISABLED', 'IGNORE' -Debug:$false
<#
Unexpected debug messages
DEBUG: 2274 | [15:05:55][Connect-DbaInstance] Starting process block
...
DEBUG: 34152 | [15:05:56][Get-DbaRegServerGroup] Processing IGNORE
#>

$DebugPreference = 'Continue'
Get-DbaRegServer -SqlInstance 'cmsserver' -Group 'DISABLED', 'IGNORE'
<#
Debug messages as expected
#>

$DebugPreference = 'Continue'
Get-DbaRegServer -SqlInstance 'cmsserver' -Group 'DISABLED', 'IGNORE' -Debug:$false
<#
Unexpected debug messages
DEBUG: 2274 | [15:05:55][Connect-DbaInstance] Starting process block
...
DEBUG: 34152 | [15:05:56][Get-DbaRegServerGroup] Processing IGNORE
#>

**Comment by wsmelton** [comment]
Please use the proper issue template.

If you do not want the debug messages to show up do not specify the debug parameter and you will not see them.

**Comment by RandyInMarin** [comment]
With cmdletbinding, it is legal to set the value of a common parameter switch.  For example, "-debug", "-debug:$true", and "-debug:$false" are all legal syntax.  However, these are not treated correctly.  

I normally debug only my script.  I use "-debug:$false" on a 3rd party cmdlets unless I am specifically debugging the 3rd party cmdlet.  If coded properly, a cmdlet will honor the value passed.  As it is now, I can't use the common parameters because of the bug...or feature.  As a work around, I have to set the preferences just before and after each call to DBATools cmdlets if I want to control the preferences.  

It is an interesting and old topic.  I wish I had more time to explore it.  There is a twist for modules.  

https://devblogs.microsoft.com/scripting/weekend-scripter-access-powershell-preference-variables/ 
https://stackoverflow.com/questions/4301562/how-to-properly-use-the-verbose-and-debug-parameters-in-a-custom-cmdlet/20830886#20830886
https://developer42.wordpress.com/2017/02/04/powershell-suggestion-simplify-write-verbose-in-modules/
https://stackoverflow.com/questions/2775357/how-does-a-cmdlet-know-when-it-really-should-call-writeverbose/20828118#20828118 

BTW, when I clicked on new issue, I did not get a template, so perhaps I'm doing this incorrectly.

**Comment by RandyInMarin** [comment]
FYI  I just clicked new issue again and got the template list.  I have no idea how it got skipped the last time.

**Comment by wsmelton** [comment]
That is part of the logging system we have in the module. You can create a bug report if you would like for this but not sure how fast we will be able to address it.

**Comment by RandyInMarin** [comment]
I will create a bug report.  If the logging is in one place, then at least it's not a function by function fix.  Thanks.
