### ISSUE TITLE
[Bug] Install-DbaMaintenanceSolution returns Success when target database does not exist

### ISSUE THREAD

**Issue by nanoDBA** [sqlcollaborative/dbatools#7314]
### Report
Install-DbaMaintenanceSolution returns a successful result when the target database does not exist.

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```


PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Install-DbaMaintenanceSolution<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.147\allcommands.ps1: line 
                        41137
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}



```

#### Steps to Reproduce
Assign a database that does not exist for the **Database** parameter.
```
Install-DbaMaintenanceSolution -SqlInstance localhost -Database AdminDB -LogToTable -Verbose
```
```
Install-DbaMaintenanceSolution -SqlInstance localhost -Database AdminDB -LogToTable -Verbose -ReplaceExisting
```

#### Expected Behavior

Results should not indicate a Success.

#### Actual Behavior

```
Install-DbaMaintenanceSolution -SqlInstance localhost -Database AdminDB -LogToTable -Verbose
``` 
returns no errors, and a successful result.

```
Install-DbaMaintenanceSolution -SqlInstance localhost -Database AdminDB -LogToTable -Verbose -ReplaceExisting
``` 
returns the error 'You cannot call a method on a null-valued expression.', and returns a successful result .

```
ComputerName    InstanceName SqlInstance Results
------------    ------------ ----------- -------
SQL01A          MSSQLSERVER  localhost   Success
```
### Environmental information

```

PowerShell Version        : 5.1.14393.3471
dbatools latest installed : 1.0.147
Culture of OS             : en-US




```

#### SQL Server:

```
Microsoft SQL Server 2019 (RTM-CU5) (KB4552255) - 15.0.4043.16 (X64)
      Jun 10 2020 18:25:25
      Copyright (C) 2019 Microsoft Corporation
      Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
```

```
us_english
```
![image](https://user-images.githubusercontent.com/10198778/118172189-14f92400-b3fa-11eb-9fdb-9033920a6e54.png)

**Comment by andreasjordan** [comment]
Please have a look at #7280 and #7283 - already merged so will be part of next release.
Should fix your issue as well - but we can keep this open until next release of dbatools.

**Comment by nanoDBA** [comment]
@andreasjordan That's fantastic - thank you!

**Comment by andreasjordan** [comment]
Please update to 1.0.148 and test.

**Comment by nanoDBA** [comment]
Bug persists in new version.
![image](https://user-images.githubusercontent.com/10198778/118536570-e345cd00-b719-11eb-97b9-663e73e26420.png)

**Comment by nanoDBA** [comment]
Bug seems to persist in new version.
![image](https://user-images.githubusercontent.com/10198778/118536946-56e7da00-b71a-11eb-9420-72f9f88ce070.png)

**Comment by nanoDBA** [comment]
Tested again with PowerShell 7.1.3 - same result.
![image](https://user-images.githubusercontent.com/10198778/118538073-b7c3e200-b71b-11eb-8884-db92f5192b63.png)

**Comment by andreasjordan** [comment]
Will look at this early tomorrow morning.

**Comment by andreasjordan** [comment]
Found the reason, will open a pull request shortly.
