### ISSUE TITLE
[Bug] Watch-DbaXESession - Cannot Convert XEStore To DbaInstanceParameter

### ISSUE THREAD

**Issue by mattcargile** [sqlcollaborative/dbatools#7317]
### Report

When cmdlet is used like Example 1 ( `Watch-DbaXESession -SqlInstance sql2017 -Session system_health` ) I receive an error like the below. I've run the cmdlet in this fashion on remote servers and on localhost. 
```
Get-DbaXESession : Cannot process argument transformation on parameter 'SqlInstance'. 
Cannot convert value "XEStore(Server='localhost')" 
    to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". 
Error: "Cannot convert value "XEStore (Server='localhost')" 
    to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". 
Error: "Failed to interpret input as Instance: XEStore Server='ghsmsvmssis1')"" 
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.147\allcommands.ps1:79139 char:57
+ ...               $status = Get-DbaXESession -SqlInstance $server -Session $sessionname
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-DbaXESession], 
           ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-DbaXESession
```
#### Workaround
I am able to work through this by piping the session object from `Get-DbaXESession`

```powershell
Get-DbaXESession -SqlInstance localhost -Session system_health | Watch-DbaXESession
```

#### Host used

- [x] powershell.exe
- [x] ISE
- [x] VS Code
- [x] wt.exe ( powershell.exe )

#### Errors Received

```
PSMessageDetails      :
Exception             : 
System.Management.Automation.ParameterBindingArgumentTransformationException: 
Cannot process argument transformation on parameter 'SqlInstance'.
Cannot convert value "XEStore (Server='localhost')" 
to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". 
Error: "Cannot
convert value "XEStore (Server='localhost')" 
to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". 
Error: "Failed to interpret
input as Instance: XEStore (Server='localhost')"" 
---> System.Management.Automation.ArgumentTransformationMetadataException: 
Cannot convert
value "XEStore (Server='localhost')" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". 
Error: "Cannot convert value
"XEStore (Server='localhost')" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". 
Error: "Failed to interpret input as
Instance: XEStore (Server='localhost')"" ---> System.Management.Automation.PSInvalidCastException: 
Cannot convert value "XEStore
(Server='localhost')" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". 
Error: "Cannot convert value "XEStore
(Server='localhost')" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". 
Error: "Failed to interpret input as Instance:
XEStore (Server='localhost')"" ---> System.Management.Automation.PSInvalidCastException: 
Cannot convert value "XEStore
(Server='localhost')" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". 
Error: "Failed to interpret input as Instance:
XEStore (Server='localhost')" ---> System.Management.Automation.PSArgumentException: 
Failed to interpret input as Instance: XEStore
(Server='localhost')
   at Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter..ctor(Object Input) in
D:\Code\Github\dbatools\bin\projects\dbatools\dbatools\Parameter\DbaInstanceParameter.cs:line 636
   at lambda_method(Closure , Object )
   at System.Management.Automation.LanguagePrimitives.ConvertViaConstructor.Convert(Object valueToConvert, 
   Type resultType, Boolean recursion,
PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   --- End of inner exception stack trace ---
   at System.Management.Automation.LanguagePrimitives.ConvertViaConstructor.Convert(Object valueToConvert, 
   Type resultType, Boolean recursion,
PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, 
   Type resultType, Boolean recurse, PSObject
originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, 
   Type resultType, Boolean recursion, IFormatProvider
formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.LanguagePrimitives.ConvertScalarToArray(Object valueToConvert, 
   Type resultType, Boolean recursion, PSObject
originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   --- End of inner exception stack trace ---
   at System.Management.Automation.LanguagePrimitives.ConvertScalarToArray(Object valueToConvert, 
   Type resultType, Boolean recursion, PSObject
originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, 
   Type resultType, Boolean recurse, PSObject
originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, 
   Type resultType, Boolean recursion, IFormatProvider
formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, 
   Object inputData, Boolean
bindingParameters, Boolean bindingScriptCmdlet)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, 
   Object inputData, Boolean
bindingParameters, Boolean bindingScriptCmdlet)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, 
   CompiledCommandParameter
parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, 
   Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : InvalidData: (:) [Get-DbaXESession], ParameterBindingArgumentTransformationException
FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-DbaXESession
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Watch-DbaXESession<Process>, 
C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.147\allcommands.ps1: 
    line 79139
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce

Run the below.
`Watch-DbaXESession -SqlInstance localhost -Session system_health`

#### Expected Behavior

I expect continuous event output.

#### Actual Behavior

I received an error.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.147
Culture of OS             : en-US
```

#### SQL Server:
Occurs on the below versions
```sql
Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64)
                Aug 15 2017 10:23:29
                Copyright (c) Microsoft Corporation
                Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> 
                (Build 9600: ) (Hypervisor)
```
```sql
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)
                Feb 15 2020 01:47:30
                Copyright (c) Microsoft Corporation
                Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> 
                (Build 14393: ) (Hypervisor)
```

```sql
Microsoft SQL Server 2017 (RTM-CU21) (KB4557397) - 14.0.3335.7 (X64)
                Jun 12 2020 20:39:00
                Copyright (C) 2017 Microsoft Corporation
                Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> 
                (Build 14393: ) (Hypervisor)
```

All with the same language.
```sql
us_english
```

**Comment by mattcargile** [comment]
After looking at it a little bit more. I **think** the issue may be related to the `$server` variable being reset in the `foreach` loop on line 79082 in the allcommands.ps1 file. Or maybe `Get-DbaXeSession` isn't able to process the `$xesession.Parent`.

Here is a link to the function ps1 file.
[https://github.com/sqlcollaborative/dbatools/blob/de024aaa616fe37de7c8eedb796a2352ab08529a/functions/Watch-DbaXESession.ps1#L89](url)

**Comment by wsmelton** [comment]
Does it work if you don't use `localhost` and the actual server's hostname instead?

**Comment by wsmelton** [comment]
This may not be something we can properly support and instead need to require a session be provided. Based on how the XEStore works

https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.xevent.xestore?view=sql-smo-150

> Parent is not something that is kept local, it is implied from the keychain The concept of a parent is really about the hiearchy up and under the root if we only do this via parents then we will not be able to instantiate objects with only lightweight SfcKeyChain sets

**Comment by mattcargile** [comment]
> Does it work if you don't use `localhost` and the actual server's hostname instead?

It doesn't work if I use the hostname either.

**Comment by mattcargile** [comment]
> This may not be something we can properly support and instead need to require a session be provided. Based on how the XEStore works
> 
> 
> 
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.xevent.xestore?view=sql-smo-150
> 
> 
> 
> > Parent is not something that is kept local, it is implied from the keychain The concept of a parent is really about the hiearchy up and under the root if we only do this via parents then we will not be able to instantiate objects with only lightweight SfcKeyChain sets

Hmm. I don't quite understand that XEStore class. Isn't there a way to just pass in the SqlInstance name instead on failed line where it starts with $status instead of XEStore.Parent? I may misunderstand the way the function is working though.

**Comment by wsmelton** [comment]
The `Microsoft.SqlServer.Management.XEvent.Session` namespace has the Parent property that is the proper instance name. If you pass in the `SqlInstance` then we are building an XEStore object:

https://github.com/sqlcollaborative/dbatools/blob/de024aaa616fe37de7c8eedb796a2352ab08529a/functions/Watch-DbaXESession.ps1#L82-L86

Purely on the class documentation it does not appear the `Microsoft.SqlServer.Management.XEvent.XEStore` property for `Sessions` that we output at the end of the above block is the same type. That is likely where the issue is but without debugging could not say how that can be fixed right off.

**Comment by andreasjordan** [comment]
Just a wild guess, but with #7284 we introduced a `.Clone()` at the end of `$SqlConn = $server.ConnectionContext.SqlConnectionObject` to prevent some problems with another command. Maybe that would help here as well.

**Comment by andreasjordan** [comment]
From the message `Cannot convert value "XEStore(Server='localhost')" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]"` I would think that $server is not a Server SMO as expected but of type "XEStore". So line `$server = $xesession.Parent` is ok for piped in output from Get-DbaXESession, but not from the code if lines 82 to 86.
My lab is down as it is weekend, but we could use Get-DbaXESession instead of the lines 82 to 86 and see if that works. Only drawback: Get-DbaXESession does more work than needed here.

**Comment by andreasjordan** [comment]
One last thing: As the errror is raised trom the ctahc block, it would be interesting where the error originally happend. Prpbably line 117 with `$server.ConnectionContext.ConnectionString`.

**Comment by andreasjordan** [comment]
I added some debug messages and they show that the parent of $xesession is of type "Microsoft.SqlServer.Management.XEvent.XEStore" and not a Server SMO as expected.

**Comment by andreasjordan** [comment]
The .Parent is added here:
https://github.com/sqlcollaborative/dbatools/blob/048a3d8dd9d343125e6c474ce095924c5bbd5f39/functions/Get-DbaXESession.ps1#L106

So I think we should use Get-DbaXESession inside of Watch-DbaXESession to handle piped input the same way as parameter input. Will open a pull request for that.
