### ISSUE TITLE
[Bug] CmdletBinding common parameter preference switch values ignored

### ISSUE THREAD

**Issue by RandyInMarin** [sqlcollaborative/dbatools#7318]
### Report

The value of some "cmdletbinding common parameter" preference switches are ignored when passed to a cmdlet.  For example, "-debug", "-debug:$true", and "-debug:$false" are all legal syntax, but are all treated as $true and debug message are emitted.  

Setting $WarningPreference = 'SilentlyContinue' is treated as Inquire.  Passing -WarningAction:SilentlyContinue is also treated as Inquire, but it does correctly override $WarningPreference.

FYI There is a minor spelling error in the output "VERBOSE: A version ***missmatch*** between the dbatools library loaded"  (This should be a warning?)

#### Host used

- [ x] powershell.exe
- [ x] ISE
- [ x] VS Code
- [ ] Other (please specify)

#### Errors Received

```
DEBUG: My script debug
VERBOSE: My script verbose
My script information
VERBOSE: Found library, trying to copy & import
VERBOSE: Loading module from path 'C:\Users\xxxx\xxxx\Documents\PowerShell\Modules\dbatools\1.0.148\bin\netcoreapp2.1\dbatools.dll'.
VERBOSE: Importing cmdlet 'Select-DbaObject'.
VERBOSE: Importing cmdlet 'Set-DbatoolsConfig'.
VERBOSE: Importing cmdlet 'Write-Message'.
VERBOSE: Total duration: 00:00:00.0034410
VERBOSE: A version missmatch between the dbatools library loaded and the one expected by
_...I'm skipping some output..._
DEBUG: [12:04:26][Start-DbaRunspace] Starting runspace: dbatools-maintenance
VERBOSE: Exporting function 'Import-ModuleFile'.
VERBOSE: Exporting function 'Write-ImportTime'.
_...I'm skipping a some output..._
VERBOSE: Exporting alias 'Attach-DbaDatabase'.
DEBUG: 436 | [12:04:27][Connect-DbaInstance] Starting process block
_...I'm skipping a some output..._
DEBUG: 1353 | [12:04:27][Connect-DbaInstance] We return server with server.Name = 'xxxx'
DEBUG: 96 | [12:04:27][Get-DbaRegServerGroup] Processing DISABLED
DEBUG: 123 | [12:04:27][Get-DbaRegServerGroup] Added DISABLED
DEBUG: 96 | [12:04:27][Get-DbaRegServerGroup] Processing IGNORE

Name        ServerName               Group    Description                                                                            Source
----        ----------               -----    -----------                                                                            ------
xxxx      xxxx         DISABLED xxxx - Development - SQL2016 - Windows Server 2016 - 2/24/2020             Central Management Servers

...

There are over 800 lines of VERBOSE and DEBUG output.

```

#### Steps to Reproduce

Replace or remove CMSSERVER, DISABLED, and INGORE as appropriate in the call to Get-DbaRegServer.

Remove-Module DBATools # this will generate extra messages when the module is imported by calling Get-DbaRegServer
Clear-Host
$DebugPreference = 'Continue'
$VerbosePreference = 'Continue'
$InformationPreference = 'Continue'
$ProgressPreference = 'Continue'
$WarningPreference = 'Stop'
Write-Debug 'My script debug'
Write-Verbose 'My script verbose'
Write-Information 'My script information'
Get-DbaRegServer -SqlInstance 'SQLDBAPROD' -Group 'DISABLED', 'IGNORE' -EnableException -Debug:$false -Verbose:$false -InformationAction:SilentlyContinue -WarningAction:SilentlyContinue

If you specify an invalid server, the execution will inquire re a continue rather than silently continuing.  

#### Expected Behavior

I expected no debug or verbose messages from the cmdlet.  I also do not expect an inquiry to continue.

#### Actual Behavior

I get over 800 lines of debug and verbose messages from the cmdlet.  I also get an inquiry to continue.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```

PowerShell Version        : 5.1.19041.610
dbatools latest installed : 1.0.148
Culture of OS             : en-US

PowerShell Version        : 7.1.3
dbatools latest installed : 1.0.148
Culture of OS             : en-US
#### SQL Server:

Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

us_english

**Comment by RandyInMarin** [comment]
Links of interest, maybe.  

It is an interesting and old topic. I wish I had more time to explore it. There is a twist for modules.

https://devblogs.microsoft.com/scripting/weekend-scripter-access-powershell-preference-variables/
https://stackoverflow.com/questions/4301562/how-to-properly-use-the-verbose-and-debug-parameters-in-a-custom-cmdlet/20830886#20830886
https://developer42.wordpress.com/2017/02/04/powershell-suggestion-simplify-write-verbose-in-modules/
https://stackoverflow.com/questions/2775357/how-does-a-cmdlet-know-when-it-really-should-call-writeverbose/20828118#20828118

**Comment by andreasjordan** [comment]
If it comes to messages, I think @FriedrichWeinmann is the one to involve here. Very interesting topic, I will follow here, but can not contribute.

**Comment by FriedrichWeinmann** [comment]
Dang, all of my crimes revealed ...
It's been four years now, will need to investigate, which I lack the time for today. Scheduling a time slot tomorrow.

**Comment by andreasjordan** [comment]
Maybe this is related: #7232

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann we were able to solve a couple other problems, but this one seems beyond all of us. Would you have time to take a look this weekend?

Thank you 🙇🏼

**Comment by potatoqualitee** [comment]
We're doing a 1.1.0 release next Monday and would love to have this fixed. I cleaned up the version mismatch thing btw so that won't be in the module anymore. Also, I upgraded the library to Visual Studio 2019

**Comment by JPRuskin** [comment]
I may be wrong (sorry if so), but (for debug, at least) would it work to change this line:

https://github.com/sqlcollaborative/dbatools/blob/90474c562c7696c8957c38e8becbb4ca408f53a8/bin/projects/dbatools/dbatools/Commands/WriteMessageCommand.cs#L348 

`WriteMessageCommand` is setting `_isDebug` using `.ContainsKey("Debug")` (which evaluates to true when `-Debug:$false` is used) rather than the value of the bound parameter?

Seem to be doing a similar thing for Verbose [here](https://github.com/sqlcollaborative/dbatools/blob/90474c562c7696c8957c38e8becbb4ca408f53a8/bin/projects/dbatools/dbatools/Commands/WriteMessageCommand.cs#L483).

It seems to me that changing those to something like:
```
&& _callStack.ElementAt(_callStack.Count() - 2).InvocationInfo.BoundParameters.ContainsKey("Verbose")) && _callStack.ElementAt(_callStack.Count() - 2).InvocationInfo.BoundParameters["Verbose"]
```
would sort it (but my syntax is awful so I apologise)?

**Comment by potatoqualitee** [comment]
Thank you, @JPRuskin ! That was so kind of you. If I don't hear back from Fred, I'll try it out this weekend after a pot or two of coffee 😅

**Comment by potatoqualitee** [comment]
I believe this has been addressed by @JPRuskin's changes 👍🏼  We'll be releasing to the PowerShell Gallery in a couple days. Got a few more days of testing.
