### ISSUE TITLE
We should really remove Connect-SqlInstance and replace it with Connect-DbaInstance

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7319]
This is the only code inside of Connect-SqlInstance:

https://github.com/sqlcollaborative/dbatools/blob/de024aaa616fe37de7c8eedb796a2352ab08529a/internal/functions/Connect-SqlInstance.ps1#L58-L75

For already created SMOs (`$SqlInstance.InputObject.GetType().Name -eq 'Server'`) to Azure (`$SqlInstance.InputObject.DatabaseEngineType -eq "SqlAzureDatabase"`) it does test for `$AzureUnsupported` and would fail. Inside of Connect-DbaInstance, this is only done in the new code path, not in the old one. So we would have to address this.
Here is the reference to the new code path:
https://github.com/sqlcollaborative/dbatools/blob/de024aaa616fe37de7c8eedb796a2352ab08529a/functions/Connect-DbaInstance.ps1#L821-L823

For all other cases it just starts Connect-DbaInstance with the bound parameters and sets `-ClientName (Get-DbatoolsConfigValue -FullName 'sql.connection.clientname')` which is the default there anyway (`[string]$ClientName = (Get-DbatoolsConfigValue -FullName 'sql.connection.clientname')`).
Problem here: Connect-SqlInstance has a parameter `[switch]$NonPooled`, Connect-DbaInstance calls it `[switch]$NonPooledConnection` (without an alias - as far as I see). So this would be a bug, right?

**Comment by wsmelton** [comment]
> Problem here: Connect-SqlInstance has a parameter [switch]$NonPooled, Connect-DbaInstance calls it [switch]$NonPooledConnection (without an alias - as far as I see). So this would be a bug, right?

It would have been around 4 years ago, but use of that parameter was removed from the functions we had it in. You should not find any function calling it with the internal or public function.

**Comment by andreasjordan** [comment]
Let me do a little bit of research for you:
https://github.com/sqlcollaborative/dbatools/blob/048a3d8dd9d343125e6c474ce095924c5bbd5f39/functions/Get-DbaDbExtentDiff.ps1#L90
https://github.com/sqlcollaborative/dbatools/blob/048a3d8dd9d343125e6c474ce095924c5bbd5f39/functions/Install-DbaMaintenanceSolution.ps1#L303

But I have to correct myself: As "-NonPooled" is recognized as a short form of "-NonPooledConnection", everything works just fine. I would only consider it a bad design.

**Comment by wsmelton** [comment]
Please ensure you are looking at current code because the use of that parameter is not used anywhere.

**Comment by andreasjordan** [comment]
> Please ensure you are looking at current code. The first one does not exists.

Links were generated from current development branch and the GitHub website. So this is actual code. You will find these lines in your allcommands.ps1 as well.

And please don't let us talk about the technical details of NonPooledConnection here. We don't have any issues related to that at the moment.

**Comment by andreasjordan** [comment]
About Connect-SqlInstance: I would really like to hear arguments for this function.

**Comment by wsmelton** [comment]
They are no arguments for or against it. We simply never made the full jump to get rid of it because there was no real need to have the Azure support parameter in the public function, at least with the same functionality. That is only reason it is still around.

Make the change in the public function to have the Azure support parameter supported as close as we can in a PR first. This will let us do the changes to the internal call in batches and more easily review the test failures.

I wonder if it might be useful to move that flag to our configuration? That may be cheaper and safer way to implement it?

We have done mass PR change before in things like this and it's the hardest thing to review with our tests.

The other thing will be to make sure if we are doing any special tests for the internal function's test and move those as well to the public function's test.

**Comment by andreasjordan** [comment]
Ok, will work on that after #7316 is merged.

**Comment by potatoqualitee** [comment]
i recall trying to move away from it and there was some reason that we didn't. but i can't recall the problem at this moment. so please be open to changing back to sqlinstance in the remote future 😅

**Comment by andreasjordan** [comment]
Chrissy and Shawn, can you please have a look at #7323 ? I need a decision on that before I can continue to work on this.

**Comment by andreasjordan** [comment]
A suggestion: I would like to start with a small group of commands and change from Connect-SqlInstance to Connect-DbaInstance for these. For this I propose all Get-DbaDa* commands. What do you say @potatoqualitee @wsmelton ?
