### ISSUE TITLE
[Bug] Connect-DbaInstance - Test for AzureUnsupported not working

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7323]
While moving the test for AzureUnsupported from Connect-SqlInstance to Connect-DbaInstance, I found out that the test is currently not working correctly.

The test is only working, if $SqlInstance is already a Server SMO. 

Test is possible with Get-DbaLogin and Set-DbaLogin. Both commands use -AzureUnsupported in the connect, but Get-DbaLogin is working against an Azure Instance, only Set-DbaLogin is failing. But to be precise: Not Set-DbaLogin is failing but a Get-DbaLogin from inside of the command, because this command is started with an already build Server SMO.

I can fix this, but this would result in Get-DbaLogin to fail on Azure - even if it is working ok with Azure (with my Azure SQL Database).
So: Should I fix this?

These commands use -AzureUnsupported:
* Backup-DbaDatabase
* Get-DbaDefaultPath
* Get-DbaLogin
* Set-DbaLogin
* Get-DbaUserPermission
* Get-DbaXESession
* New-DbaCustomError
* Remove-DbaCustomError

**Comment by wsmelton** [comment]
So one step I think would be good to take first @potatoqualitee is to get on the latest version of SMO. Previously we have been told by tools team that SMO does not know much about Azure SQL in most classes that I recall. This [Overview of SMO](https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/overview-smo) shows Applies To now with Azure SQL checked. Is there a chance the newer versions have added features to cover more of Azure SQL now?

I think it would good to have a priority of getting SMO updated to the latest, and then we can determine if that supported flag might not be needed anymore. Especially if SMO gives a cleaner error to indicate as much.

**Comment by jpomfret** [comment]
Here's the reference to update SMO @potatoqualitee.

@andreasjordan - SMO is now updated in development after #7352

**Comment by andreasjordan** [comment]
@wsmelton said:
> I think it would good to have a priority of getting SMO updated to the latest, and then we can determine if that supported flag might not be needed anymore. Especially if SMO gives a cleaner error to indicate as much.

In #6299 @potatoqualitee asid:
> we should actually catch that error prior if possible, too.

I think we should still use the AzureUnsupported flag to fail a command as soon as it tries to connect to Azure, regardless of a good error message from the SMO.

Concerning this issue the question is:
Should Get-DbaLogin still have the AzureUnsupported flag?
To be clear: At the moment, the flag is not active (because of this bug) and the command works fine. 
Fixing the bug without removing the flag would stop Get-DbaLogin from working with azure.
So I would like to include the removal of the AzureUnsupported flag from Get-DbaLogin into #7324.

**Comment by andreasjordan** [comment]
As the test for AzureUnsupported is working in the new code path of Connect-DbaInstance and we are about to use the new code path as default in a few weeks, I see no benefit in changing the old code path.
So I will close this.
