### ISSUE TITLE
[Bug] Repair-DbaInstanceName does not work in SQL 2019

### ISSUE THREAD

**Issue by rfeldman1** [sqlcollaborative/dbatools#7332]

**Comment by andreasjordan** [comment]
Let me first copy some info from slack:

Rita Feldman  20:05 Uhr
Repair-DbaInstanceName does not seem to work in SQL 2019 CU10. The function tries to rename a SQL instance but it renames it to the old name.  The following are the log messages:
DEBUG: 205 | [18:18:59][Repair-DbaInstanceName] sp_dropserver 'OLDINSTANCENAME'
DEBUG: 214 | [18:19:00][Repair-DbaInstanceName] sp_addserver 'OLDINSTANCENAME', local
DEBUG: 231 | [18:19:00][Repair-DbaInstanceName] Stopping SQL Services for the MSSQLSERVER instance
DEBUG: 233 | [18:19:02][Repair-DbaInstanceName] Starting SQL Services for the MSSQLSERVER instance.
DEBUG: 242 | [18:19:04][Repair-DbaInstanceName] NEWMACHINENAME successfully renamed from OLDINSTANCENAME to OLDINSTANCENAME.
I tried to trace the issue in Repair-DbaInstance and it looks like in the following code the new name is not determined properly ($SqlInstanceName variable)
$nametest = Test-DbaInstanceName $server -EnableException | Select-Object *
$oldserverinstancename = $nametest.ServerName
$SqlInstancename = $nametest.SqlInstance
This is the snapshot of the $nametest variable:
ComputerName  : NEWMACHINENAME
ServerName    : OLDINSTANCENAME
InstanceName  : MSSQLSERVER
SqlInstance   : OLDINSTANCENAME
RenameRequired : True
Updatable     : True
Warnings      : N/A
Blockers      : N/A
For some reasons SqlInstance property has an old name despite the fact the RenameRequired property is set to true as it should. Does anyone else experience this issue? If only happens on SQL 2019 CU10. I tried it with dbatools versions 1.0.148 and earlier.

Andreas Jordan  21:21 Uhr
![image](https://user-images.githubusercontent.com/66946165/118762793-1782d000-b877-11eb-8abc-d0549343d83f.png)
Just installed 2019, 2017, 2016 on SRV1 and then renamed the computer to SRV1A.
Only 2016 has the new name in SqlInstance.
Source of this SqlInstance is $server.DomainInstanceName
Lets lay out some code:
RenameRequired = $serverInstanceName -ne $sqlInstanceName
$serverInstanceName is based on $server.ComputerName for default instances and additial $server.InstanceName for named instances
$server.ComputerName is an added property based on how you connect, so it is the new name.
So $serverInstanceName is the new name.
$sqlInstanceName is the result of $server.Query("SELECT @@servername AS ServerName").ServerName
So $sqlInstanceName is the old name.

alevyinroc:andylevy:  21:39 Uhr
does @@SERVERNAME match SERVERPROPERTY('SERVERNAME')?

Andreas Jordan  21:40 Uhr
The root problem is that $server.DomainInstanceName is not consistent across versions. SQL2016 shows the new ComputerName, SQL2017 and SQL2019 show the new ComputerName.
![image](https://user-images.githubusercontent.com/66946165/118762931-51ec6d00-b877-11eb-85e2-b96b94cd7992.png)
@@SERVERNAME is always old, SERVERPROPERTY is "auto-updating on computer rename" in 2016.
$server.DomainInstanceName is used as $serverInfo.SqlInstance in Test-DbaInstanceName and then as $SqlInstancename (the new name) in Repair-DbaInastanceName.
That worked until 2016, no more in 2017 and 2019...

Rita Feldman  22:36 Uhr
Thank you @Andreas Jordan.  I added a new issue https://github.com/sqlcollaborative/dbatools/issues/7332.  I did not noticed the same problem on SQL 2017.  I will try to reproduce it on SQL 2017.

Rita Feldman  00:21 Uhr
@Andreas Jordan I did not see the issue with SQL instance rename on SQL 2017.  Repair-DbaInstanceName properly renames SQL server instance name.

**Comment by andreasjordan** [comment]
Can you run this and provide the output?
```
Connect-DbaInstance -SqlInstance NEWMACHINENAME | Format-List -Property ComputerName, ComputerNamePhysicalNetBIOS, DomainInstanceName, Name, NetName
```

**Comment by rfeldman1** [comment]
This is the output where DCALCPSG001 is a new machine name and 02WORKPROC02 is an old machine name.

ComputerName                : DCALCPSG001
ComputerNamePhysicalNetBIOS : DCALCPSG001
DomainInstanceName          : 02WORKPROC02
Name                        : DCALCPSG001
NetName                     : DCALCPSG001

**Comment by andreasjordan** [comment]
Thanks, I think I have fix for that. Will update the pull request soon.

**Comment by rfeldman1** [comment]
That's awesome!  Thank you for such a prompt response to this issue!

**Comment by andreasjordan** [comment]
If you are able to install this branch you can test: https://github.com/sqlcollaborative/dbatools/tree/7332_RepairDbaInstanceName
Otherwise you would have to wait until @potatoqualitee merges and releases a new version.

**Comment by rfeldman1** [comment]
@andreasjordan, I've tested https://github.com/sqlcollaborative/dbatools/tree/7332_RepairDbaInstanceName and it's working perfectly.  Thank you again for the prompt fix.  Do you know when it will be incorporated into an official release?

**Comment by andreasjordan** [comment]
Thanks for the feedback. Will probably take some days but not weeks to build a new version.
