### ISSUE TITLE
[Bug] Repair-DbaInstanceName - test for Warnings not correct

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7337]
Test-DbaInstanceName fills the property Warnings with "N/A" if there are no warnings:

```
            if ($null -ne $rs -or $rs.Count -gt 0) {
                if ($rs.State -eq 'Running') {
                    $rstext = "$ssrsService must be stopped and updated."
                } else {
                    $rstext = "$ssrsService exists. When it is started again, it must be updated."
                }
                $serverInfo.Warnings = $rstext
            } else {
                $serverInfo.Warnings = "N/A"
            }
```

But Repair-DbaInstanceName tests for empty string or $null:

```
            if ($nametest.Warnings.length -gt 0) {
```

So: Do we want to change Test-DbaInstanceName to send $null or do we want to change Repair-DbaInstanceName to test for "N/A"?

**Comment by andreasjordan** [comment]
@potatoqualitee Can you decide?

**Comment by potatoqualitee** [comment]
Please change Repair-DbaInstanceName to test for "N/A" 👍🏼 

Sorry I hadn't checked my notifications for months 😬
