### ISSUE TITLE
[Bug] Link in documentation of Invoke-DbaQuery not valid

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7359]
This link is dead: http://powershell.org/wp/forums/topic/dealing-with-dbnull/
It's part of the parameter documentation for `-As` in `Invoke-DbaQuery`.

**Comment by NReilingh** [comment]
I wonder if this is the intended content at a new location? https://forums.powershell.org/t/dealing-with-dbnull/2328/2

**Comment by andreasjordan** [comment]
Yes, could be. If you plan to update more of the documentation then change this link as well.
