### ISSUE TITLE
[Feature] when two instances of PowerShell are running Set-DbaDbCompression the script fails

### ISSUE THREAD

**Issue by alexsinkevich** [sqlcollaborative/dbatools#7374]
#### Host used

- [ ] powershell.exe
- [x ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Could not complete cursor operation because the table schema changed after the cursor was declared. ---> 
                        System.Data.SqlClient.SqlException: Could not complete cursor operation because the table schema changed after the cursor was declared.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, 
                        Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           --- End of inner exception stack trace ---
TargetObject          : [Client-AlexTestRenamed]
CategoryInfo          : NotSpecified: ([Client-AlexTestRenamed]:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Test-DbaDbCompression,Stop-Function
ErrorDetails          : Could not complete cursor operation because the table schema changed after the cursor was declared.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.141\allcommands.ps1: line 87807
                        at Test-DbaDbCompression<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.141\allcommands.ps1: line 73647
                        at Set-DbaDbCompression<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.141\allcommands.ps1: line 67195
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

When  using Set-DbaDbCompression in two different PowerShell windows and I get error like they interfere with each other, so one of the sessions fails, even though they are doing the compression on different databases.
#### Expected Behavior

I would expect both of the running session will successfully complete the compression.
#### Actual Behavior

one one instance of PowerShell i got this:
Set-DbaDbCompression -SqlInstance myServer -Database AlexTest -CompressionType Recommended -PercentCompression 30 #-MaxRunTime 60
WARNING: [10:30:45][Get-DbaBuildReferenceIndex] Index is stale, last update on: 2021-04-07T00:00:00, try the -Update parameter to fetch the most up to date index
WARNING: [10:30:49][Test-DbaDbCompression] Unable to query myServer  - [AlexTest] | Invalid object name '##TestDbaCompression'.

on another instance of powershell i got similar error:
PS D:\Tools\AccountRefresh> Set-DbaDbCompression -SqlInstance myServer  -Database AlexTestRenamed -CompressionType Recommended -PercentCompression 30 #-MaxRunTime 60
WARNING: [10:30:30][Get-DbaBuildReferenceIndex] Index is stale, last update on: 2021-04-07T00:00:00, try the -Update parameter to fetch the most up to date index
WARNING: [10:30:49][Test-DbaDbCompression] Unable to query myServer  - [-AlexTestRenamed] | Could not complete cursor operation because the table schema changed 
after the cursor was declared.
### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.17763.1852
dbatools latest installed : 1.0.141
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-CU10) (KB5001090) - 15.0.4123.1 (X64)   Mar 22 2021 18:10:24   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 
```

```sql
us_english
```

**Comment by alexsinkevich** [comment]
@niphlod   from DBATools slack channel had mentioned this:
the table is on tempdb, so ....... it blocks. https://github.com/sqlcollaborative/dbatools/blob/90474c562c7696c8957c38e8becbb4ca408f53a8/functions/Test-DbaDbCompression.ps1#L289

**Comment by niphlod** [comment]
yeah, I can take care of it in the next few days

**Comment by andreasjordan** [comment]
Thanks for the info. So the question is: Can we move from global temp tables to temp tables? Or: Do we generally want to allow two sessions to run Test-DbaDbCompression in parallel?

Have you tried to seperate Test-DbaDbCompression from Set-DbaDbCompression? So first running both Test-DbaDbCompression one after the other and saving the result in a variable (or even a file with `| ConvertTo-Json`) and then using this as -InputObject with the two Set-DbaDbCompression running in parallel?

**Comment by niphlod** [comment]
the easiest fix just to be sure dbatools is not the culprit is not using fixed names for temp tables. 
the thing is, sp_estimate_data_compression_savings was not made to run parallel. 
If you have large enough dbs, and the queries take some time to run, it creates an inter-lock on

```
select @sample_compressed_desired = used_page_count      from tempdb.sys.dm_db_partition_stats      where object_id = @sample_table_object_id and index_id = @sample_index_id
select @sample_compressed_current = used_page_count      from tempdb.sys.dm_db_partition_stats     where object_id = @sample_table_object_id and index_id = @sample_index_id
```

with one blocking the other. One of the two gets terminated by the deadlock monitor.
So no, you can't parallel-compress if you wanna rely on estimates (-CompressionType Recommended), which calls Test-DbaDbCompression, which in turn calls sp_estimate_data_compression_savings.

You need to collect estimates beforehand and serially (Test-DbaDbCompression), then you can run compression in parallel (Set-DbaDbCompression).

Example 4 shows how to pipe in precompiled estimates

```
$testCompression = Test-DbaDbCompression -SqlInstance ServerA -Database DBName
Set-DbaDbCompression -SqlInstance ServerA -Database DBName -InputObject $testCompression
```

**Comment by alexsinkevich** [comment]
I believe with running it this way, we will just switch the blocking from Set-DbaDbCompression to Test-DbaDbCompression running in parallel, won't we?

**Comment by niphlod** [comment]
nope, if you run test-dbacompression on all of your dbs serially 


```
# serial estimate
$testCompression = Test-DbaDbCompression -SqlInstance ServerA -Database DBName1, DBName2
# save it for all
$testCompression | Export-Clixml some\path\to.xml
```

then you can run your "usual" parallel, just doing in one process
```
# parallel 1
$testCompression = Import-Clixml some\path\to.xml
Set-DbaDbCompression -SqlInstance ServerA -Database DBName1 -InputObject $testCompression
```

and in the other
```
# parallel 2
$testCompression = Import-Clixml some\path\to.xml
Set-DbaDbCompression -SqlInstance ServerA -Database DBName2 -InputObject $testCompression
```

**Comment by alexsinkevich** [comment]
that is actually a problem, as the databases refresh requests (followed by compression) are coming at different time, sometimes in parallel, and ideally the process should be able to handle it

**Comment by niphlod** [comment]
Go tell Microsoft about it...we can't really touch their sprocs. If you're
responding to external events that you can't manage, you need to implement
a singleton and queue at least the part that fetches the reccomendations.

Il mar 25 mag 2021, 19:39 alexsinkevich ***@***.***> ha
scritto:

**Comment by niphlod** [comment]
the more I think of it the more I like the way it is. 
We *could* check if the temp table is there before starting, but it could potentially end in a waiting loop, and nobody wants to wait potentially forever. 
And that's a job for a higher level function, or a "dbasolution" project (it's maybe 4 lines of code on top of what's readily available).
Wanna keep simple and don't wanna think about managing singletons and queues (or writing checks for concurrency) ? 
Just loop till it doesn't bomb out.

**Comment by alexsinkevich** [comment]
haha, feature, not a bug. that is funny.

anyways, I have tried using the following two scripts in parallel and the results were the same
script 1:

$SQLInstance  = 'MyServer'
$DBName = 'MyDB1'

$testCompression = Test-DbaDbCompression -SqlInstance $SQLInstance  -Database $DBName
Set-DbaDbCompression -SqlInstance $SQLInstance  -Database $DBName -InputObject $testCompression -CompressionType Recommended -PercentCompression 30

output  of script 1:
WARNING: [17:16:45][Get-DbaBuildReferenceIndex] Index is stale, last update on: 2021-04-07T00:00:00, try the -Update parameter to fetch the most up to date index
WARNING: [17:18:27][Test-DbaDbCompression] Unable to query MyServer - [MyDB1] | Invalid object name '##TestDbaCompression'.

Script 2:
$SQLInstance  = 'MyServer'
$DBName = 'MyDB2'

$testCompression = Test-DbaDbCompression -SqlInstance $SQLInstance  -Database $DBName
Set-DbaDbCompression -SqlInstance $SQLInstance  -Database $DBName -InputObject $testCompression -CompressionType Recommended -PercentCompression 30

output of script 2:
WARNING: [17:16:35][Get-DbaBuildReferenceIndex] Index is stale, last update on: 2021-04-07T00:00:00, try the -Update parameter to fetch the most up to date index
WARNING: [17:18:27][Test-DbaDbCompression] Unable to query MyServer - [MyDB2] | Could not complete cursor operation because the table schema changed after the cursor was declared.

**Comment by alexsinkevich** [comment]
maybe if that temp table is a local table (not a global temp table) it might work? i am willing to test

**Comment by niphlod** [comment]
not a bug of dbatools, it's a "bug" of sp_estimate_data_compression_savings , which we have no control upon.
we may add a feature of dbatools, if we wanna go around it.

back to you:
Did I get correctly that you're running in two separate shells, but at the same time
```
$testCompression = Test-DbaDbCompression -SqlInstance $SQLInstance -Database $DBName
```

**Comment by niphlod** [comment]
btw, if you wanna hop on the Slack channel the conversation may be speedier

**Comment by niphlod** [comment]
note for the reader: solution on looping was provided via Slack. if it works, we may add an example to clarify parallel usage.

**Comment by alexsinkevich** [comment]
The looping did not work :(

**Comment by niphlod** [comment]
back to slack and drawing board
