### ISSUE TITLE
[Feature] Update-DbaTools - Cleanup switch

### ISSUE THREAD

**Issue by mattcargile** [sqlcollaborative/dbatools#7379]
### Summary of new feature

Add a `-Clean` switch which would run something like the below script. It would be nice to have it all happen in one command as opposed to have to run the two commands and open multiple powershell sessions. 

```powershell
& "$((Get-InstalledModule dbatools).InstalledLocation)\cleanup.ps1"
```

### Proposed technical details (if applicable)

See above. [Link ](https://tkwj.com/2020/04/clean-up-your-dbatools) discussing how to use. [Link](https://github.com/sqlcollaborative/dbatools/blob/development/cleanup.ps1) to the code.

Not sure if there is some technical limitation of doing all the work in one cmdlet. I know I have to open a new powershell session after I run `Update-Dbatools` in order for the above script to run appropriately in order to "clear" the older version.

### Latest version of dbatools as of writing

`1.0.153`

**Comment by potatoqualitee** [comment]
hey matt -- please test this code https://github.com/sqlcollaborative/dbatools/pull/7633

**Comment by mattcargile** [comment]
Thanks Chrissy! I'm wondering how best I should test this. 

One concern is that `cleanup.ps1` requires dbatools to _not_ be loaded. When `Update-Module` is running, dbatools would be loaded. 

Additionally, once I pull down the `clean` branch, I won't be able to update to a future version because I am on a newest version? 

Lastly, would a run of `Update-Dbatools` from the cloned `clean` branch update my branch or the module install within my `Program Files\WindowsPowershell\Modules` directory?

**Comment by mattcargile** [comment]
It worked great! No issues. My concerns weren't warranted.

**Comment by potatoqualitee** [comment]
sweet, good to hear! i couldnt test at all bc i dont have it i installed and i didnt want it to delete my repo. I'll merge 😄
