### ISSUE TITLE
[Feature] Get-DbaBackupInformation - Add Size property to FileList

### ISSUE THREAD

**Issue by RobinPhilipThomas** [sqlcollaborative/dbatools#7380]
### Summary of new feature

Add the file `Size` to the `FileList` property of the command.

### Proposed technical details (if applicable)

Currently the `FileList` property is collected using `Read-DbaBackupHeader` but when the `FileList` property is built it only includes the `LogcalName, `PhysicalName` and `Type`. Feature request would be adding the `Size` to that array.

![image](https://user-images.githubusercontent.com/11204251/124664879-aa9cb700-de71-11eb-9ff4-95f83f71b685.png)

### Latest version of dbatools as of writing

v 1.0.152

**Comment by andreasjordan** [comment]
It is returned, but it is not part of the default properties.

**Comment by andreasjordan** [comment]
Hi @RobinPhilipThomas , can you please give feedback if you need more help on this? If not, please close the issue.

**Comment by wsmelton** [comment]
A few notes on addressing this request that would have to be done.

- [Read-DbaBackupHeader](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Read-DbaBackupHeader.ps1) needs to have the Size parameter modified to type `[DbaSize]` so it can display a readable size and include the unit.

This is done here: https://github.com/sqlcollaborative/dbatools/blob/08b9fbafbd749be5d1ae5827cb26c490f21d4e9c/functions/Read-DbaBackupHeader.ps1#L141-L166

- `Get-DbaBackupInformation` then can have the Size property added here:

https://github.com/sqlcollaborative/dbatools/blob/08b9fbafbd749be5d1ae5827cb26c490f21d4e9c/functions/Get-DbaBackupInformation.ps1#L317
