### ISSUE TITLE
How should restore-dbadatabase work with subfolders in -path

### ISSUE THREAD

**Issue by lauraberanek** [sqlcollaborative/dbatools#7387]
From the help for restore-dbadatabase (https://docs.dbatools.io/Restore-DbaDatabase) it says this:
-Path
Path to SQL Server backup files. Paths passed in as strings will be scanned using the desired method, default is a non recursive folder scan Accepts multiple paths separated by ',' Or it can consist of FileInfo objects, such as the output of Get-ChildItem or Get-Item. This allows you to work with your own file structures as needed

With the testing I am doing, I am seeing that it IS recursive.  I have full backups in a subfolder and tlog backups in the parent folder (i.e. d:\backups and d:\backups\fulls) and it is scanning both folders in get-dbabackupinformation and restore-dbadatabase.  For the -path parameter, I only specify d:\backups and it is restoring the full backup from d:\backups\fulls.  I do not understand why it is doing it when it says the default is non-recursive.  Why is it scanning and restoring from d:\backups\Fulls when I only specify d:\backups?

I can deal with it either way.  I just want to understand how it is programmed to work and does the help align with what it is doing?

I am using version 1.0.145 of dbatools and powershell version 5.

Thanks!

**Comment by andreasjordan** [comment]
As I have no time to solve this today, I will write down what I've done so far:

`Restore-DbaDatabase` uses `Get-DbaBackupInformation` to expand the `$Path` into all the individual files used to do the restore.
The line that is hit normally is:
`$bh = Get-DbaBackupInformation -SqlInstance $RestoreInstance -Path $file`
Where `$file` is `$Path` if you only use one string in `$Path`.

Here clearly the `$DirectoryRecurse` switch is missing, maybe also the `$XpDirTree` is missing and should be added.

`Get-DbaBackupInformation` has the parameters `$DirectoryRecurse` and `$NoXpDirTree` to control the behavior.
Normally it uses `Get-XpDirTreeRestoreFile -Path $f -SqlInstance $server` to get the files. Only if `$NoXpDirTree` is set, it uses `Get-ChildItem` to resolve them locally.

`Get-XpDirTreeRestoreFile` has the parameter `$NoRecurse` to control the behavior. But this switch is only used when `$MaintenanceSolution` is used.

So I think this is a bug and I will tag it as one. I would like to have @Stuart-Moore have a look at it as he designed all the backup/restore commands. 
If we agree on what the fix would be, I can then code it and open a pull requst.

If you are running the command on the sql server or if the files are on a network share that it accessable both from you computer and from the sql server, you can use `Get-DbaBackupInformation` with `-NoXpDirTree` to get the files and then pass them `Restore-DbaDatabase`.

**Comment by lauraberanek** [comment]
Thank you!

**Comment by lauraberanek** [comment]
In case it helps, I will share a little more what I am doing.  I am receiving full backups nightly and tlog backups every 15 minutes from a vendor.  I have a powershell script that copies the files from their SFTP site and saves them to a network drive.  I have a folder for tlogs and a folder for fulls (I started having them all in one and then split them out because restore-dbadatabase was failing).  I had thought by splitting them out, it then would not recurse to the fulls backup folder and I would not get the error.  The error message I get is "Cannot open backup device '<backup file name>'. Operating system error 32(The process cannot access the file because it is being used by another process.)   Downloading the daily full backup takes about 6 hours to download.  During that time, restore-dbadatabase needs to run (but it doesn't need the full backups as it is only applying tlogs).  So Ideally, I would like the process of only applying tlogs to not recurse to the fulls backup folder so the full backup can download and not interfere with restore-dbadatabase.  When I would need to restore starting with a full backup, I would then like to use the recurse parameter(s) that would force restore-dbadatabase to recurse in to the full backup folder so it can find the full backup to start with for the restore.

One thing to note, I have tried adding the -WarningAction SilentlyContinue parameter to suppress the warning that the file is in use.  This does sometimes seem to work. However, for some reason it is sometimes an error rather than a warning.  I am not sure why that is.

Thanks!

Thanks!

**Comment by andreasjordan** [comment]
What about having the two directories side by side? For including the full backup you can use both directories with Restore-DbaDatabase, as the Path parameter accepts an array of paths.

**Comment by lauraberanek** [comment]
Yes, I definitely can do that.  That is actually my backup plan and maybe that is what I should do.  I just wanted to understand why this wasn't working since the DirectoryRecurse parameter sounded like it would work for me when wanting to start by restoring the full backup.

**Comment by Stuart-Moore** [comment]
@potatoqualitee @wsmelton  Executive decision time I'm afraid

Would you like me to:
a) Make reality match the documentation
b) Make the documentation match reality?

Option a may well affect users with existing scripts, and as this is the first time it's been raised I'm assuming most people haven't noticed or have just worked around it

**Comment by potatoqualitee** [comment]
I'm leaning make docs match reality, how about you?

**Comment by andreasjordan** [comment]
I also would vote for "b = just change the documentation".

**Comment by potatoqualitee** [comment]
✔️  sweet, let's do that.

**Comment by Stuart-Moore** [comment]
great, just double checking reality before comitting

**Comment by Stuart-Moore** [comment]
PR in to fix this - https://github.com/sqlcollaborative/dbatools/pull/7580 - could you read through the new help section and see if it matches up with how you see the command working just to sense check it please

**Comment by potatoqualitee** [comment]
Thank you @Stuart-Moore !
