### ISSUE TITLE
[Bug] Copy-DbaDbTableData hangs SELECT query when script is 'cancelled' in Powershell ISE

### ISSUE THREAD

**Issue by janszedc** [sqlcollaborative/dbatools#7397]
#### Host used

- [ ] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

No errors.

#### Steps to Reproduce

Copy-DbaDbTableData -SqlInstance stage -Destination dev -Database myDB -Table myPartitionedTable

#### Expected Behavior

Clicking 'stop' in the ISE should kill the SELECT query

#### Actual Behavior

The SELECT query remained on the server for 10+ days despite the ISE showing the query/script successfully cancelled

#### SQL Server:

```sql
Microsoft SQL Server 2017 (RTM-CU22) (KB4577467) - 14.0.3356.20 (X64)   Aug 20 2020 22:33:27   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) 
```

```sql
us_english
```

**Comment by wsmelton** [comment]
We do not control the functionality of the stop button in the PowerShell ISE. You can potentially have the same behavior using CTRL+C in a PowerShell session.

This command as well does a bulk copy of data so killing the command does not guarantee the transaction is killed. This is the nature of PowerShell working with SQL Server. We have `Get-DbaProcess` and `Stop-DbaProcess` for you to manage those sessions and be able to easily kill them if you need/want.
