### ISSUE TITLE
export-dbaRegServer generate filename with datetime format mmddyyyyHHmmss

### ISSUE THREAD

**Issue by ALZDBA** [sqlcollaborative/dbatools#7400]
Please use [Sqlcollaborative.Dbatools.Utility.DbaDateTime](Get-Date)
( **yyyyMMddHHmms**) so the the result file name will be sortable according to its date-time part in the name.

https://github.com/sqlcollaborative/dbatools/blob/51648dfa8a8e009ecade69bec50a19ea939a803a/functions/Export-DbaRegServer.ps1#L95

**Comment by andreasjordan** [comment]
I'm a fan of ISO dates - so yes from my side. 
@potatoqualitee : Do you think this will be a breaking change because people might have build own logic around the filename? If I have your ok, I will provide a pull request for that.

**Comment by SQLDBAWithABeard** [comment]
I wasnt certain that the class gives a filename suitable value in my brief searching, If not then I think an ISO date format makes sense

**Comment by andreasjordan** [comment]
DbaDateTime has no nice method to get the iso format, so I just changed the format a bit and moved the year up front.

**Comment by andreasjordan** [comment]
Now I use the dbatools config value "formatting.uformat".
