### ISSUE TITLE
Missing Version in Build Reference

### ISSUE THREAD

**Issue by rscottcovington** [sqlcollaborative/dbatools#7418]
#### Host used

- [ ] powershell.exe
- [x ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
WARNING: [09:36:53][Test-DbaBuild] 14.0.3391 is not recognized as a correct version
```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

PowerShell Version        : 5.1.14393.4402
dbatools latest installed : 1.0.153
Culture of OS             : en-US

#### SQL Server:

Microsoft SQL Server 2017 (RTM-CU24) (KB5001228) - 14.0.3391.2 (X64)   Apr 28 2021 10:32:18   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
us_english

**Comment by rscottcovington** [comment]
Apparently I didn't fill in the template correctly as all the info didn't show up.  
Executing: $Results+=Test-DbaBuild -SqlInstance $s -latest -Update
Checked latest json file and it has incorrect info for SQL 2017 CU24.  Should be version 14.0.3391.2 but it shows 14.0.3390.

**Comment by niphlod** [comment]
will do a PR shortly to fix.
