### ISSUE TITLE
Get/Set-DbaPrivilege commands

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7433]
Right now, we export settings to file then import the file from command line. Lee Holmes offers a much cleaner way to do this in his 🔥  blog post:

https://www.leeholmes.com/adjusting-token-privileges-in-powershell/

**Comment by andreasjordan** [comment]
But this is enabling the privilege for a process. We want to grant the privilege to an account. I think this is something different.

**Comment by wsmelton** [comment]
This won't persist to the machine's policy, it is a session-based token @potatoqualitee You can set the tokens and then run `whoami /priv` to see that for your session in PowerShell. Open another session or `Start-Job` process and the privilege won't exist. 

This won't remove us still having to use `secpool` utility in Windows sadly.

**Comment by wsmelton** [comment]
It might be good for a `Set-DbaProcessPrivilege` command though 🤔

**Comment by potatoqualitee** [comment]
Yeah, this is against a process like yall said. I asked Lee if it's possible for an AD account and will see what he says.
