### ISSUE TITLE
Support SqlParameter class for Invoke-DbaAsync SqlParameters argument

### ISSUE THREAD

**Issue by i7slegend** [sqlcollaborative/dbatools#7434]
### Summary of new feature

* Support initiliaze class sqlparameter as stored procedure parameter. It's can be useful to execute a stored procedure which returns result via output variable. 

### Proposed technical details (if applicable)

* https://docs.microsoft.com/ru-ru/dotnet/api/system.data.sqlclient.sqlparameter?view=dotnet-plat-ext-5.0
* https://docs.microsoft.com/ru-ru/dotnet/api/system.data.sqlclient.sqlparametercollection.add?view=dotnet-plat-ext-5.0#System_Data_SqlClient_SqlParameterCollection_Add_System_Data_SqlClient_SqlParameter_

Something like:
```
CREATE OR ALTER PROC [dbo].[my_proc]
    @json_result nvarchar(max) output
AS
BEGIN
  set @json_result = (
      select 'sample' as 'example'
      for json path, without_array_wrapper
  );
END
```

```
$QueryParameters = @{}

$outputParameter = New-Object System.Data.SqlClient.SqlParameter -Property @{
    ParameterName = "@json_result";
    SqlDbType = [System.Data.SqlDbType]::NVarChar;
    Size = -1;
    Direction = [System.Data.ParameterDirection]::Output;
};

$QueryParameters.Add("json_result", $outputParameter) # some unnecessary line

Invoke-DbaQuery -SqlInstance $sqlInstance -Database test -CommandType StoredProcedure -Query "my_proc" -SqlParameters $QueryParameters > $null

$outputParameter
```

### Latest version of dbatools as of writing

* 1.0.156

**Comment by potatoqualitee** [comment]
I like that, thank you for the suggestion. We'll be working on Invoke-DbaQuery soon and this seems like a great addition.
