### ISSUE TITLE
Find-DbaLoginInGroup: Include DB Users with no SQL Server Login

### ISSUE THREAD

**Issue by mscirri** [sqlcollaborative/dbatools#7443]
### Summary of new feature

Find-DbaLoginInGroup does not account for DB Users with no SQL Server Login.  I would like this function to be updated to account for these objects. 

### Proposed technical details (if applicable)

I tried to do this myself at first, without realizing how many of the required functions are not exposed.  Below is my version of the function with the new code clearly marked.  I have attached the PS1 file with this new code.
[function Find-DbaLoginInGroupWithDBOnlyUsers.txt](https://github.com/sqlcollaborative/dbatools/files/6664613/function.Find-DbaLoginInGroupWithDBOnlyUsers.txt)

### Latest version of dbatools as of writing

1.0.153

**Comment by niphlod** [comment]
would you make a practical example ? Find-DbaLoginInGroup from the description basically unrolls AD groups defined on the instance to know what specific users have access. In what sense then "does not account for DB Users with no SQL Server Login" ?

**Comment by mscirri** [comment]
Sure thing.   Here is the scenario that I faced.

I have a server with 3 logins:

1. MEESEEKS\mscirri  (Windows User)
2. MEESEEKS\Data_Analytics  (Windows Security Group)
3. MEESEEKS\Operations  (Windows Security Group)


That server has a single database with 4 users:

1. MEESEEKS\mscirri  (Windows User)
2. MEESEEKS\Data_Analytics  (Windows Security Group)
3. MEESEEKS\Operations  (Windows Security Group)
4. MEESEEKS\Finance  (Windows Security Group)


When I run `Find-DbaLoginInGroup -SqlInstance $permissionsSqlServerName | Format-Table -AutoSize`  I get the following output:

```
SqlInstance   Login                DisplayName           MemberOf                          ParentADGroupLogin
-----------   -----                -----------           --------                          ------------------  
MYSERVER     MEESEEKS\jsmith       Joe Smith             MEESEEKS\Data_Analytics           MEESEEKS\Data_Analytics
MYSERVER     MEESEEKS\njones       Nathan Jones          MEESEEKS\Data_Analytics           MEESEEKS\Data_Analytics
MYSERVER     MEESEEKS\mbaker       Matthew Baker         MEESEEKS\Finance                  MEESEEKS\Finance
MYSERVER     MEESEEKS\tmorris      Tyler Morris          MEESEEKS\Finance                  MEESEEKS\Finance
```


The results do not account for the Windows Security Group "MEESEEKS\Finance", which is a user on the database, but does not have a SqlServer login.

**Comment by niphlod** [comment]
the whole point is testing Logins, not Users ... also, I *think* that if MEESEEKS\Finance isn't defined as login, you wouldn't get it as a result, so the thing you get back doesn't match what I'd expect. I'd think MEESEEKS\Finance is like an orphan user, added to the db at some point but later on was removed as a login. What am I missing here ?

**Comment by mscirri** [comment]
Oh, I messed up my example.   "Finance" was supposed to be operations.  I have corrected it

**Comment by mscirri** [comment]
So there are use cases where you would setup a DB user and not give them a SQL Server login.  This is just one article I fund but there seems to be a few:  https://blog.learningtree.com/sql-server-users-without-logins/

If there is a function that does the exact same thing for these types of database users, then I am fine just making another call and  merging my results.   Get-DbaDbOrphanUser would just give me group name, in my example above "MEESEEKS\Finance" and I would still have to do something else to see who is granted access via that group.   That is why I think for a full audit adding this feature would be a bonus.

**Comment by niphlod** [comment]
ok, now it aligns with what I'd expect. That being said, back to the drawing board .... MEESEEKS\Finance is a user, not a login. 
Why would you expect Find-DbaLoginInGroup to catch up on that ?
The base point of Find-DbaLoginInGroup is to unroll who has access to and why. 
In you case, do users belonging to MESEEKS\Finance have access to the database ?

**Comment by mscirri** [comment]
They do.    I see your point with how the function is named that it is not intuitive to think that it would include these database users.    Does it make more sense to request an update to Get-DbaDbOrphanUser to (optionally) walk the Active Directory chain to get the individual User accounts in the same manner that Find-DbaLoginInGroup does?   Is there another way to do this with existing functionality that I am missing?   Currently I am getting around it by exporting data from Active Directory in a SQL table and then doing some matching .   It all works, but it ain't pretty. :)

**Comment by niphlod** [comment]
I normally prune every orphan right off the bat. 
Are you saying that MEESEEKS\Finance defined on the db as a user but not as a login grants access no matter what to the db ?

**Comment by mscirri** [comment]
Right, but if it is not a true orphan and it was done like that for a reason, then I have to leave it and be able to audit the access granted to the users in that group.  If in the end I can just trim that all down that would be great, but for now, I need to understand who has access to what in my environment for compliance purposes.

I am not sure I understand your question.

**Comment by niphlod** [comment]
find-dbaloginingroup tells you who has access WHEN YOU RUN IT. If MEESEEKS\Finance is an orphan, users of it do not have access till someone adds MEESEEKS\Finance as login. If this is true, then Find-DbaLoginInGroup is running as expected. If we all agree on the fact that till AD groups aren't logins no access is granted, we can move on and find whatever is needed to support your usecase, which if the above is true, is "who WOULD have access if that user wasn't an orphan?" which is exactly the reason why orphans gets pruned regularly. 
Moreover, there's really no way to tell if a db user is a group or a login, from the SQL perspective of things that detail is stored along with the login, not the user.

**Comment by mscirri** [comment]
OK. I see what you are saying.   And if you cannot tell if the user is a Windows Group or Windows User without a server login then my little code addition won't work and this thing would need a LOT more effort to meet the objective.  

But I still go back to the intentional creation of a database user with no server Login.   It is not always indicative of a user that needs to be pruned. I go back to a response from Michael Hotek to a question  about these types of users.   Seems like there is a legitimate use-case for them.  

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/7d129880-048c-4834-a72e-c31ead4897cb/database-user-without-login?forum=sqlsecurity

=================================================
"When you execute CREATE USER <name> WITHOUT LOGIN, you get a user in the database that will NOT have a login associated to it.  This is intentional and by design.  This is NOT an orphaned user.  

When you create a user without a login, there is no path that allows a login to be mapped to that particular user in the database.  The only way to "utilize" this particular user in the database is through impersonation.  Again this is BY DESIGN.  Loginless users were added in SQL Server 2005 as a replacement to application roles.  The main reasons behind this were that you did not need to embed a password into an application and you also did not suddenly have multiple people coming into your SQL Server all with the same "login".  By utilizing loginless users, the user's of an application login to the SQL Server using THEIR login credentials (NOT a generic login), so that you can audit activity to a given login.  Once they change context to the application database, you can issue an EXECUTE AS command to change their user context thereby giving them the authority they need within the application. "

**Comment by niphlod** [comment]
yup, but this means that you need to inspect what runs on the db to know if it's a proper and valid orphan or not. 
impersonation is a whole concept outside the scope of dbatools, and, again, an audit there has to be made on the application rather than on the db.
Once again, the culprit is the fact that you're relying on an app+sql behaviour you know of, that sql (and dbatools) doesn't. 
That is a user, and that's it. How your app uses impersonations and execute as, it's the deal you wanna audit.
And, BTW, using that loginless advanced feature with groups .... I'd expect to have it nothing to do with the actual AD group. 
Sql would have to scour AD every time the context changes rather that at connection time for things like "is the user member of this group, hence can read the data?" .

**Comment by mscirri** [comment]
That is a fair assessment.   I will close this request.
