### ISSUE TITLE
[Bug] Write-DbaDbDataTable does not work in latest version

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#7448]
### Report
I have a process that runs database validation using Test-DbaLastBackup to test restores and dbcc.  I moved this to a new server recently and installed the latest version of dbatools (1.0.155).  The process started failing on the Write-DbaDbTableData command that I have at the end of my process to store the results to a database table.

I did some research and found if I force the last known good version for this process that uses dbatools (1.0.128) my process executes as expected and completes without issue.

The error reflects column mapping and I did some looking on GitHub and found that Write-DbaDbTableData did have a code change referring to column mapping recently.

I attempted to look at the code, but did not have a lot of time to spend, but my parameters should not hit this section from my review.

#### Host used

- [ ] powershell.exe
- [ X] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
replace THIS text WITH the OUTPUT of -- $ERROR[0] | SELECT *
```

#### Steps to Reproduce

Code executed:
`Write-DbaDbTableData -SqlInstance $adminServer -Database DatabaseValidation -InputObject $results -Table ValidationResults`

The $results object is populated from running:
`Test-DbaLastBackup -SqlInstance $($prodServer.ServerName) -Destination $adminServer -ExcludeDatabase $excludeDBList -Prefix 'Validation_' -DataDirectory 'Q:\Validation_Data' -LogDirectory 'Q:\Validation_Log' -MaxTransferSize 3145728 -BufferCount 2000  -Verbose`
#### Actual Behavior

![image](https://user-images.githubusercontent.com/169602/122427688-f0dbb600-cf56-11eb-9845-3e4e8bb3aff3.png)

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.14393.4402
dbatools latest installed : 1.0.155
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-CU10) (KB5001090) - 15.0.4123.1 (X64)   Mar 22 2021 18:10:24   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
us_english
```

**Comment by andreasjordan** [comment]
Can you check if the structure of $results changed? Maybe use `-Database tempdb` and `-AutoCreateTable` and compare the two tables.

**Comment by andreasjordan** [comment]
Do you remember this change?https://github.com/sqlcollaborative/dbatools/commit/6bfef61aff21ad3f7c73967f0eb801a603b05e7b#

It added an output column...

**Comment by gbargsley** [comment]
You are indeed correct.  I added that output, and my table did not like it.  Thanks for the help.
