### ISSUE TITLE
[Bug] Export-DbaScript with -NoPrefix Append always

### ISSUE THREAD

**Issue by m4ss1m0g** [sqlcollaborative/dbatools#7451]
#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

#### Errors Received
Launching export multiple time when using `-NoPrefix` on `Export-DbaScript` the command always append to file

#### Steps to Reproduce

```
$options = New-DbaScriptingOption
$item = Get-DbaDbTable -SqlInstance $SqlInstance -Database $Database -Table Whatever
$item | Export-DbaScript -ScriptingOptionsObject $options -FilePath $OutPath -NoPrefix
# Again
$item | Export-DbaScript -ScriptingOptionsObject $options -FilePath $OutPath -NoPrefix
```

#### Expected Behavior
The output are the same

#### Actual Behavior
The DDL is listed twice

### Environmental information
PowerShell Version        : 7.1.3
dbatools latest installed : 1.0.160
Culture of OS             : it-IT

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64) 	Nov  6 2020 16:50:01 	Copyright (C) 2019 Microsoft Corporation	Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: ) (Hypervisor)
```

```sql
us_english
```
### Notes
I think the problem is in this [line](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Export-DbaScript.ps1#L289)

``` powershell
$ScriptingOptionsObject.AppendToFile = (($null -ne $prefix) -or $appendToScript )
```

**Comment by andreasjordan** [comment]
Oh, there are some other issues around using `-ScriptingOptionsObject` like not saving `$soAppendToFile = $ScriptingOptionsObject.AppendToFile` before changing it.
Will try to provide a fix in the next hours or days (if no one else wants to do this).

**Comment by andreasjordan** [comment]
The line under "Notes" is not hit, because `$scriptBatchTerminator` will be false...
