### ISSUE TITLE
Write-DbaDbTableData kills number of connections to Azure SQL DB running in Azure Automation Runbooks

### ISSUE THREAD

**Issue by jstexasdba** [sqlcollaborative/dbatools#7461]
Write-DbaDbTableData kills (sky rockets) the number of connections to Azure SQL DB running in Azure Automation Runbooks. This ultimatly gives error: 

> Azure sandboxes are limited to 1,000 concurrent network sockets.

 It does not seem to be closing the connections of the bulk insert. This is in a non-hybrid environment.

**Comment by andreasjordan** [comment]
Can your share the powershell code you use?

**Comment by jstexasdba** [comment]
`$endAddDays = -2

    Write-Output "Run started"
    # Authenticate with your Automation Account
    $VaultName = "keystore"
    $credential = Get-AutomationPSCredential -Name 'AutomationAccount'

    $destinationserver = Get-AutomationVariable -Name "ProdServer" #Imports the SQL Server Name from the Automation variable.
    $Database = Get-AutomationVariable -Name "ProdDB"
    $waiverstable = 'testtable'
    
    $stringKey = 'ec529d4062586d297dc50585b10061e6','3ddead6b3cead075d78ec431abd507d5',	'ff37135d59300034872e9cbd7746cb18',	'e1dc157e0f5de973dddd436bc971d334',	'91319f35cc3d90407f3b0da58a969311',	'e039b989f79300cef45b8f9ea576d956',	'74539685f2fbd0d7492bb6b8c1ae0e3f',	'f0e2d637d9768d5174ca02688c28aded',	'4184490c190ab4ee177cd7f68007124e',	'93fabbe1daaceef7854754104fdafec2',	'1e86ca426dc7abc5faaa7d220bdcc700',	'aa56914fd23cc02163bfea5b433efb2e',	'db3416c0a20d36434f6d868ffc799069',	'f32b5030cc560350be03851d3fb17af3',	'92607c41aafbd95d79689cabe5f5dbca',	'5e8ea878121ce119f3aefe6f0bbe7f94',	'de9e2377c4222e5c20b204c48cc3f19f',	'28ba3ab1170c913ef08d5f978fa1d55a'
    $location='city1','city2','city3','city4','city5','city6','city7','city8','city9','city10','city11','city12','city13','city14','city15','city16','city17','city18'
    $stringkeyenumerator = $stringKey.getenumerator()
    $locationenumerator = $location.getenumerator()

    while ($stringkeyenumerator.MoveNext() -and $locationenumerator.MoveNext()) {
        Write-Output "Importing SmartWaivers for $location."
        
        $string = $stringkeyenumerator.current 
        $loc = $locationenumerator.current

        $uri = 'https://api.com/v4'

        $startdate = (get-date).AddDays($endAddDays).ToString("yyyy-MM-ddT00:00:00")
        $enddate = (get-date).AddDays($endAddDays).ToString("yyyy-MM-ddT23:59:59")

        $headers = @{
            'sw-api-key' = $string
            'rest_limit' = 100
        }
        $headers | ConvertTo-Json | Write-Host

        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::tls12 #, tls11, tls"
        $results = Invoke-RestMethod -Method Get -Uri $uri -Headers $headers -Body @{limit = 100 ; fromDts = $startdate; toDts = $enddate } | Select-Object -ExpandProperty waivers
        Start-Sleep -Milliseconds 500

        # Get File URI list
        foreach ($waiverId in $results.waiverId) {
            #while ($apiCount -le $apiLimit) {
#            if ($apiCount -ne $apiLimit) {
                Start-Sleep -Milliseconds 500
                $waiverlisturi = "https://api.com/v4/$waiverId"
                Invoke-RestMethod -Method Get -Uri $waiverlisturi -Headers $headers | 
                Select-Object @{label = 'location'; Expression = { $loc } }, @{label = 'WaiverDate'; Expression = { $startdate } } -ExpandProperty waiver |
                Select-Object location, guardian, 
                @{label = 'CreatedOn'; Expression = 'CreatedOn' },
                @{label = 'Participantswaiverid'; Expression = 'waiverid' },
                @{label = 'Participantsemail'; Expression = 'email' },
                @{label = 'marketingAllowed'; Expression = 'marketingAllowed' },
                @{label = 'kiosk'; Expression = 'kiosk' } -ExpandProperty Participants |
                Select-Object location, CreatedOn, Participantswaiverid,
                Participantsemail,
                marketingAllowed,
                kiosk,
                @{label = 'ParticipantsFirstName'; Expression = 'firstname' },
                @{label = 'ParticipantsMiddleName'; Expression = 'middlename' },
                @{label = 'ParticipantsLastName'; Expression = 'lastname' },
                @{label = 'Participantsdob'; Expression = 'dob' },
                @{label = 'ParticipantsisMinor'; Expression = 'isMinor' },
                @{label = 'Participantsgender'; Expression = 'gender' },
                @{label = 'Participantsphone'; Expression = 'phone' } -ExpandProperty guardian -ErrorAction Ignore |
                Select-Object -Unique location, CreatedOn, ParticipantsFirstName,
                ParticipantsMiddleName,
                ParticipantsLastName,
                Participantsdob,
                ParticipantsisMinor,
                Participantsgender,
                Participantsphone,
                Participantsemail,
                marketingAllowed,
                kiosk,
                @{label = 'GuardianFirstName'; Expression = 'firstname' }, 
                @{label = 'GuardianMiddleName'; Expression = 'middlename' }, 
                @{label = 'GuardianLastName'; Expression = 'lastname' },
                @{label = 'GuardianPhone'; Expression = 'phone' },
                @{label = 'GuardianRelationship'; Expression = 'relationship' } | Write-DbaDbTableData -SqlInstance $destinationserver -SqlCredential $credential -Database $Database -Table $waiverstable -AutoCreateTable
                get-help Clear-DbaConnectionPool -full
                Write-Host "The API has been used [$apiCount] times, against the limit of [$apiLimit] on waiverid $waiverId for startdate of $startdate to end date of $enddate" -ForegroundColor Yellow -BackgroundColor DarkBlue
                $apiCount++
            }
        
        }`

**Comment by andreasjordan** [comment]
I can reproduce the issue with this code:

```
$azCred = Get-Credential
$azInstance = 'xxx.database.windows.net'
$azDatabase = 'yyy'
$process = Get-Process | Select-Object -First 5 | Select-Object -Property Id, Processname
foreach ($i in 1..100) {
    $process | Write-DbaDbTableData -SqlInstance $azInstance -SqlCredential $azCred -Database $azDatabase -Table process -AutoCreateTable
    $i
}
```

But with the new version from #7460 there is no issue anymore.

**Comment by andreasjordan** [comment]
With the latest commit I added a new verbose message:
```
Write-Message -Level Verbose -Message "Creating SqlBulkCopy object"
```

This should tell you, if you really use the new version.

**Comment by jstexasdba** [comment]
Your branch?

**Comment by andreasjordan** [comment]
Yes, this branch: https://github.com/sqlcollaborative/dbatools/tree/WriteDbaDbTable_Improvements

**Comment by jstexasdba** [comment]
FYI, I had to click on view JSON to get that message as the job stayed in suspended mode.

**Comment by andreasjordan** [comment]
The change is not merged and not released. You can only use it if you are able to get a specific branch from GitHub. 
I don't work with Azure Automation, so I can not tell you if or how that would work.
But I just opened the pull request for review. Maybe @potatoqualitee  has time to review, merge and release.

**Comment by andreasjordan** [comment]
The new release is 1.0.163 and includes the fix for your problem - hopefully it helps.

**Comment by potatoqualitee** [comment]
yep, that should work! if it doesn't, please feel free to reopen this issue 🥳

**Comment by jstexasdba** [comment]
I updated the module to the current dev version and running the test code Andreas wrote in a runbook, I am still seeing the same thing. 😥

**Comment by andreasjordan** [comment]
There are two things you can play with:

You can first connect with `$server = Connect-DbaInstance -SqlInstance XX -SqlCredential YY -Database ZZ` and then use `$server` as `-SqlInstance` in `Write-DbaDbTableData`. You don't need `-SqlCredential` there, because `$server` is a connected server SMO.

And you can use the new code path inside of `Connect-DbaInstance` with adding this line once in your script: `Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true`.

Other that that, I don't have an idea. Can you show the problem outside of Runbooks with just plain PowerShell 5.1?

**Comment by jstexasdba** [comment]
That did the trick!

**Comment by andreasjordan** [comment]
Great to hear that. Thanks for the info.

**Comment by potatoqualitee** [comment]
Which solution worked for you @jstexasdba ?
