### ISSUE TITLE
[Bug] Get-DbaService - false error no services found in relevant namespaces

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#7470]
#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
 No services found in relevant namespaces on <server name>. Please note that this function is available from SQL 2005 up.
```

#### Steps to Reproduce

1. Run `Get-DbaService` either in the context of an account or passing Credential
2. Ensure the account or credential used does not have valid permissions to the target endpoint

#### Expected Behavior

Provide more clear message of why services were not found.

#### Actual Behavior

We claim no services were found but in reality, the logic in the command is flawed.

We create collection variables:

https://github.com/sqlcollaborative/dbatools/blob/eb515c5ef82354b28ece0b3eaa2e72ff46e05b42/functions/Get-DbaService.ps1#L153-L154

But if the namespaces do not actually have anything we still continue processing an empty variable:

https://github.com/sqlcollaborative/dbatools/blob/eb515c5ef82354b28ece0b3eaa2e72ff46e05b42/functions/Get-DbaService.ps1#L183

Which we immediately jump down to the error message since `$services` is empty:

https://github.com/sqlcollaborative/dbatools/blob/eb515c5ef82354b28ece0b3eaa2e72ff46e05b42/functions/Get-DbaService.ps1#L261-L265

### Fix

This section of code from what I can tell is where the issue arises:

https://github.com/sqlcollaborative/dbatools/blob/eb515c5ef82354b28ece0b3eaa2e72ff46e05b42/functions/Get-DbaService.ps1#L166-L184

The foreach loop for `$services` needs to be within the `if ($namespaces)` because that is the only way we have service(s) to work on.  Everything down to line 256 should be in that `if` block, and then an `else` be used to output a cleaner message such as:

```powershell
} else {
    Stop-Function -Message "Unable to capture namespaces on $Computer. Please verify the account used has proper permissions to query for SQL Server services."
}
```

**Comment by andreasjordan** [comment]
Oh, thanks, I have only tested the positive case. Do you have time to provide a pull request? If not give me a sign and I will try to find some time this week.

**Comment by andreasjordan** [comment]
I had a look and I think this is not so easy. First of all the general design of the command is not optimal. 
But the main problem is that this call can fail for different reasons:

```
$namespaces = Get-DbaCmObject -ComputerName $resolvedComputerName -Credential $Credential -Namespace root\Microsoft\SQLServer -Query "Select Name FROM __NAMESPACE WHERE Name Like 'ComputerManagement%'" -EnableException | Sort-Object Name -Descending
```

If I use an account that has no rights, I get: 

```
WARNING: [15:57:04][Get-DbaService] Failed to get SQL Server namespaces on SRV2. | Windows authentication was used, but is known to not work!
```

If I query a server that has no SQL Server installed, I get:
```
WARNING: [16:00:54][Get-DbaService] Failed to get SQL Server namespaces on DOM1. | The WS-Management service cannot process the request. The CIM namespace root/
microsoft/sqlserver is invalid. 
```

So I would like to test the connection first with:
```
$null = Get-DbaCmObject -ComputerName SRV1 -Namespace root\Microsoft -ClassName __NAMESPACE
```

We could also use `Test-DbaCmConnection` but the result is not an easy true/false - so I would need some help in using it the correct way.

If this is successful, we can assume all failures to get the namespaces as "there is no instance, so silently ignore this computer and move on".
