### ISSUE TITLE
[Bug] PSRemoting.PsSession.UseSSL not working with Get-DbaCmObject

### ISSUE THREAD

**Issue by fabiopennisi** [sqlcollaborative/dbatools#7473]
#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
```
No error, but unexpected behaviour.
```

#### Steps to Reproduce

1. You'll need a server behind a firewall, configure WinRM HTTPS on that server
2. Punch a hole in the firewall to allow traffic from the client (where dbatools is installed) to the destination server - port 5986 for WinRM https. Make sure traffic is NOT allowed on port 5985 - default winrm http - THIS IS IMPORTANT!
3. In dbatools configure the PSRemoting.PsSession.UseSSL value to $true - You can use:
Set-DbatoolsConfig -FullName 'PSRemoting.PsSession.UseSSL' -Value $true -Register -Verbose -EnableException
4. On the client (where dbatools is installed) run powershell and validate winrm is listening on https. You can use commands such as:
$ComputerName = "your destination host"
Test-NetConnection -ComputerName $ComputerName -Port 5986 -Verbose
Test-WSMan -ComputerName $ComputerName -UseSSL -Port 5986 -Verbose
Invoke-Command -ComputerName $ComputerName -UseSSL -Port 5986 -ScriptBlock {Get-WMIObject Win32_ComputerSystem}
5. Now try test the CimRM connection using this code (remember to check that the result returns CimRM = Success):
Test-DbaCmConnection -ComputerName $ComputerName -Type CimRM -Verbose | Select-Object *
6. Now try Get-DbaCmObject -ComputerName $ComputerName -ClassName Win32_ComputerSystem -verbose

#### Expected Behaviour

The result should immediately return with "CimRM over WinRM - Success"
You should also be able to see the traffic was allowed on 5986 on the firewall. 

#### Actual Behaviour

You will see "CimRM over WinRM - Failure" You may also see attempts on DCOM, but this should also fail considering we have not allowed this traffic on the firewall. You will see all traffic blocked on the firewall too. In addition to this issue, it may also be beneficial if the "Cim over WinRM" message contained the UseSSL value for clarity.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
```
PowerShell Version        : 5.1.14393.2828
dbatools latest installed : 
Culture of OS             : en-AU
```

#### SQL Server:

Not applicable

**Comment by andreasjordan** [comment]
The author of that command is @FriedrichWeinmann , will ping him on Slack.

**Comment by wsmelton** [comment]
That configuration was added for a different purpose and is not implemented for CMI queries. It is only used with the `Invoke-Command2` which all that configuration does is set the call to `New-PSSession` to use the parameter `-UseSSL` (not unique to dbatools usage).

Fix for this should be fairly simple by just adding a check for that config to the `Invoke-Command` call's parameter:

https://github.com/sqlcollaborative/dbatools/blob/d988eb7c8aef1e91af794cd3df7aa8c04b1702ee/functions/Get-DbaCmObject.ps1#L431-L443

We handle this in the [Invoke-Command2](https://github.com/sqlcollaborative/dbatools/blob/development/internal/functions/Invoke-Command2.ps1) already and the best path is probably to change this function to call that instead of the `Invoke-Command`. At least that is what I think could be done // @potatoqualitee

**Comment by andreasjordan** [comment]
@fabiopennisi can you the test the branch of the linked pull request?

**Comment by fabiopennisi** [comment]
Hey guys,

Thanks so much for looking at this.

I'm a little confused at the moment, hoping you can please bear with me,
I'll eventually get there...

If I may, I'm going to go back a step to explain what I'm trying to achieve.

Our Sql Servers are mostly behind firewalls. They've been configured with
WinRM HTTPS (port 5986). The relevant firewall rules are in place to allow
traffic from particular servers (where dbatools is installed) to our SQL
Servers. We utilise a few dbatools commands to gather information from our
sql servers.

One very important cmdlet we use is Get-DbaComputerSystem. As you know, it
and many others rely on Get-DbaCmObject, which is why I flagged this as our
"pain point". It seems that at present, there is no way to call
Get-DbaCmObject and force WinRM traffic to use WinRM HTTPS 5986 instead of
the default WinRM HTTP (port 5985). Originally I was hoping we could
somehow get the CimRM region of code in the Get-DbaCimObject to allow
traffic on HTTPS based on a flag. Shawn has kindly put forward some changes
for PowerShellRemoting, however once they're in, I'm not sure how I'll then
call cmdlets like Get-DbaComputerSystem and ensure it forces SSL (WinRM
HTTPS on 5986) or not (uses default WinRM HTTP on 5985).

Do I need to configure
the computermanagement.type.disable.powershellremoting = $false and then
disable the equivalent CimRM and CimDCOM configurations? And then also how
do I call commands to signify when to use SSL or not?

In addition, I'm not sure how to test the pull request (sorry). Is there
some documentation I can follow so that I can grab a copy and test it out?

Thanks again so much for helping out.

Cheers

**Comment by fabiopennisifmg** [comment]
I see, by setting Set-DbaToolsConfig -Name 'psremoting.pssession.usessl' -Value $true, the underlying Invoke-Command2 will will automatically add the -UseSSL parameter. So I understand what Shawn was saying about that - makes sense. 

If you can still please answer my questions above; about how I'll get the underlying Get-DbaCmObject to use the PowerShellRemoting region of code (assuming it's the config settings I mentioned above) and also more importantly, how I go about testing the pull request. Thanks so much.

**Comment by potatoqualitee** [comment]
Thank you,the fix is now in the gallery!

**Comment by wsmelton** [comment]
> by setting Set-DbaToolsConfig -Name 'psremoting.pssession.usessl' -Value $true

@fabiopennisi in the latest release this will apply to `Get-DbaCmObject` now as well.
