### ISSUE TITLE
[Bug] Get-ObjectNameParts does not parse 'database..table'

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7479]
![image](https://user-images.githubusercontent.com/66946165/124161048-3c38ad00-da9d-11eb-9900-3a1f263b2edc.png)

The regex is not able to work with ".." as a replacement for ".dbo." - and a fix is not that easy with just the regex I think.

Are there any reasons against using PARSENAME?
https://docs.microsoft.com/de-de/sql/t-sql/functions/parsename-transact-sql

**Comment by andreasjordan** [comment]
@niphlod - do you have an idea?

**Comment by niphlod** [comment]
'..' is a bad idea overall, but parsename is definitely not smarter than regex. should be doable but I'd need a few testcases

**Comment by andreasjordan** [comment]
And PARSENAME needs a connection to an instance - and we don't have that here.

**Comment by andreasjordan** [comment]
Maybe use the $fixChar idea again: Replace ".." by ".$fixChar2." and then later test $chema for beeing $fixChar2 and in that case set it to "dbo" and remove $fixChar2 from database and table.

**Comment by niphlod** [comment]
the point here is that I don't know how functions depending on this are able to accept a schema as `''` vs `$null` vs `dbo` . 
whoever passes dbname..tablename should get back "dbo" as schema no matter what, taunting us requesting to return `''` or `$null` is ... unacceptable ?

if that's the case, the regex can't do anything to match, as there's nothing to match, so....

```
$splitName = [regex]::Matches($t, "(\[.+?\])|([^\.]+)").Value
if ($t -like '*..*') {
    $shortcut = $true
}

$dotcount = $splitName.Count
.....

    default {
        $parsed = $false
    }
}

if ($shortcut) {
    $dbName = $schema
    $schema = 'dbo'
}
```

should be "the fix".
But mind that supporting lazy typewriters needs to have a stopgap somewhere ;-)

**Comment by andreasjordan** [comment]
Have a look at my pull request. I could not resist shortening the existing code a bit...

**Comment by niphlod** [comment]
seems longer than needed, and less readable ... why the whole [regex]::Unescape("\u$($hexStr)") ?
that being said, this function needs tests asap.

**Comment by andreasjordan** [comment]
Haven't seen that - will shorten again. And I will try to add some tests.

**Comment by niphlod** [comment]
on top of the usual suspects, `dbo.[Table_.1]`, `[db.name].dbo.[Table_.1]` and `[dbname]..[Table_.1]`

**Comment by ben-thul** [comment]
Implying that the schema for 'db..obj' should be dbo isn't correct - it should be the default schema of the executing user.

```
USE tempdb;
GO
IF SCHEMA_ID('foo') IS NULL
	EXEC('CREATE SCHEMA foo;');
GO
IF USER_ID('FooUser') IS NULL
CREATE USER FooUser WITHOUT LOGIN WITH DEFAULT_SCHEMA = foo;
GRANT SELECT ON schema::foo TO FooUser;
GO
DROP TABLE IF EXISTS dbo.bar;
DROP TABLE IF EXISTS foo.bar;
go
CREATE TABLE dbo.bar (a VARCHAR(100));
INSERT INTO dbo.bar (a) VALUES ('dbo');
CREATE TABLE foo.bar (a VARCHAR(100));
INSERT INTO foo.bar (a) VALUES ('foo');
GO
SELECT *
FROM tempdb..bar;
GO

EXECUTE AS USER = 'FooUser'
GO
SELECT *
FROM tempdb..bar;
GO
REVERT```

**Comment by niphlod** [comment]
I knew supporting '..' was going to be a PITA ^_^

**Comment by andreasjordan** [comment]
Oh, missed that. But $schema could not be set to $null because this would be later changed to "[]" - right?
So what to do? Send a warning that we set the schema to "dbo" (which would be correc t in 99% of the cases)?

**Comment by niphlod** [comment]
nope. should raise a warning that ".." is not supported.

**Comment by niphlod** [comment]
alternatively, review all down-level usage to see how they manage an empty schema (i.e. `''`).
Aaaand, on the top of my head, add a test even for `foo.[test..table]` and `foo..[test..table]` . 
Because on the "warning" route, it doesn't suffice to look for `..` .

**Comment by andreasjordan** [comment]
Ok, maybe step by step:
* At the moment "database..table" is parsed wrong - so we can only make it better.
* We have to do some magic to detect ".." - I propose the same magic as for "]]".
* We have to decide on what Get-ObjectNameParts should return as property Schema. Choices are $null or "dbo", $null would be correct, "dbo" better than it is now.
