### ISSUE TITLE
[Bug]Add-DbaAgDatabase does not honor SqlCredential

### ISSUE THREAD

**Issue by JoeAtMsft** [sqlcollaborative/dbatools#7481]
Add-DbaAgDatabase was recently re-written and the re-write does not honor the passed in SqlCredential parameter.  
https://github.com/sqlcollaborative/dbatools/commit/c864b791ad360d954a93edc065c691e117714a2e

When Add-DbaAgDatabase calls Test-DbaAvailabilityGroup, it should pass along the SqlCredential parameter if one was passed into Add-DbaAgDatabase at runtime.

This change breaks automation scenarios where dba tools is running under an account that does not have access to SQL.

**Comment by andreasjordan** [comment]
Thanks for finding this, fix is on it's way...

**Comment by andreasjordan** [comment]
@JoeAtMsft - New version is released...

**Comment by JoeAtMsft** [comment]
@andreasjordan, thanks for the quick turnaround!
