### ISSUE TITLE
Import-DbaCSV doesn't create table by default or documentation is wrong. 

### ISSUE THREAD

**Issue by kaysauter** [sqlcollaborative/dbatools#7491]
### Report
According to documentation in the first example here https://docs.dbatools.io/#Import-DbaCsv, 

```PowerShell
Import-DbaCsv -Path C:\temp\housing.csv -SqlInstance sql001 -Database markets
```

is supposed to create a table, "Since a table name was not specified". However it seems that this is not the case and the documentation explains for -AutoCreateTable the following:

| Alias                |
| --------------- | ----- |
| Required         | false |
| Pipeline           | false |
| Default Value  | False |

So it says that it is not required and default value is False. Either I get something wrong or there is some contradiction here thus something in those lines could be wrong. In my opinion however, there is a documentation bug. Once this is confirmed, I'll do a PR if this is wished.

#### Host used

Used PowerShell in ADS. PowerShell 

Major  | Minor  | Patch  7   |   1   |   3

also tested it with 

Windows Terminal Preview:
PowerShell Version        : 5.1.19041.1023
dbatools latest installed : 1.0.168
Culture of OS             : de-CH

#### Errors Received

WARNING: [15:04:08][Import-DbaCsv] Table or view 'NewTableName' does not exist and AutoCreateTable was not specified

### Environmental information

PowerShell Version        : 7.1.3
dbatools latest installed : 1.0.168
Culture of OS             : de-CH

Windows Terminal Preview:
PowerShell Version        : 5.1.19041.1023
dbatools latest installed : 1.0.168
Culture of OS             : de-CH

#### SQL Server:

Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64) 	Nov  2 2020 18:35:09 	Copyright (C) 2019 Microsoft Corporation	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: )

Language:
us_english

**Comment by andreasjordan** [comment]
Thanks for the issue. Yes, the first example is missing the `-AutoCreateTable`. Maybe have a look at the other examples as well - maybe there are more bugs. Would be nice If you can provide a pull request.

**Comment by kaysauter** [comment]
If you've got any suggestions on tests I should do, let me know. I'm currently updating dbatools for PoSh 5 to test that as well.

**Comment by kaysauter** [comment]
Just a small question though: the PR should be for documentation for for the the PoSh code within dbaTools?

**Comment by andreasjordan** [comment]
For the documentation inside of the command. The website is based on that. So pull againt this repo here.

**Comment by andreasjordan** [comment]
As I said in the liked pull request: I now think this is no bug. Can we close this?

**Comment by kaysauter** [comment]
@andreasjordan if you're asking me, I'm ok with that.
