### ISSUE TITLE
Test-DBATempDbConfig

### ISSUE THREAD

**Issue by BoHu1977** [sqlcollaborative/dbatools#7500]
The Test-DBATempDbConfig command checks if trace flag 1118 is set. But for SQL Server 2016 and onwards versions this trace flags is not longer required. But if you run the cmdlet it will show in the output, if the SQL server is 2016 or above, that you have te set the trace flag.

Is it possible for SQL Server 2016 and above the output will show that the trace flage is set correctly. 
Below a example on SQL server 2019:
ComputerName   : SQL2019
InstanceName   : MSSQLSERVER
SqlInstance    : SQL2019
Rule           : TF 1118 Enabled
Recommended    : True
CurrentSetting : False
IsBestPractice : False
Notes          : KB328551 describes how TF 1118 can benefit performance. SQL Server 2016 has this functionality enabled
                  by default.

The CurrentSetting and IsBestPractive should give the value True.

**Comment by andreasjordan** [comment]
Whoever works on this, please see https://github.com/sqlcollaborative/dbatools/issues/6509 also.

**Comment by andreasjordan** [comment]
Was fixed with #7356.
