### ISSUE TITLE
[Get-DbaDbUdf] filtering on object name and schema name without using Where-Object

### ISSUE THREAD

**Issue by MikeyBronowski** [sqlcollaborative/dbatools#7504]
### Summary of new feature

* Clear/concise description of what the problem is that the new feature can solve.

Currently, the Get-DbaDbUdf command returns all the objects, unless we filter out by database (Database, ExcludeDatabase) or system objects (ExcludeSystemUdf).

There is no way to filter it by name or schema name other than Where-Object. There are more functions like that.

Examples where we filter by object name or schema:
* allows three-part names search in an object parameter)
Get-DbaDbView (-View)
Get-DbaDbTable (-Table)

*  (uses Schema and Synonym parameters
Get-DbaDbSynonym (-Schema, - Synonym)

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality
Approach from one of the functions above.

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.
1.0.169

**Comment by andreasjordan** [comment]
Maybe we can take all the Get-DbaDb* commands, have a look and propose one pattern for all of them. It would be really nice if similar commands have similar interfaces.
Do you see one or two commands that have a very good design?

**Comment by MikeyBronowski** [comment]
I will have a look, but definitely, one pattern would be great. At the moment it is a mixture of different approaches, so while we are going to unify Remove-* functions it would be great to do it with the relevant Get-* as well.

There were recently created new functions for Synonyms/Sequences/Schemas. Maybe that's a start, as probably there were most recent discussions on those.

**Comment by andreasjordan** [comment]
I copied the functionality from Get-DbaDbSynonym as implementing 3-part-names is more complex.
Please have a look at the pull request and give feedback.

**Comment by MikeyBronowski** [comment]
Looks good to me :) Should we follow that template for other Get-Dba* commands, so this works nicely with Remove-Dba* cmdlts?
