### ISSUE TITLE
[Bug] Copy-DbaLogin - KillActiveConnection parameter help incorrect

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#7506]
### Report

Unless I'm reading this wrong, we state that `-Force` has to be used with `KillActiveConnection`:

https://github.com/sqlcollaborative/dbatools/blob/08b9fbafbd749be5d1ae5827cb26c490f21d4e9c/functions/Copy-DbaLogin.ps1#L63-L64

Checking where that parameter hits though we are not checking if `-Force` was provided.

https://github.com/sqlcollaborative/dbatools/blob/08b9fbafbd749be5d1ae5827cb26c490f21d4e9c/functions/Copy-DbaLogin.ps1#L321-L331

Notice in the verbose message if active connections are found we also state the use of `-Force`.

I do not really see a need to tie this parameter to Force, so believe we can update the documentation. // @potatoqualitee ?

**Comment by potatoqualitee** [comment]
Agreed, it doesn't need to be tied to force

**Comment by wsmelton** [comment]
Fix for this issue is removing the reference to `-Force` in the verbose and parameter CBH.
