### ISSUE TITLE
Update-DbaInstance Authentication error

### ISSUE THREAD

**Issue by AdieBe** [sqlcollaborative/dbatools#7512]
#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Access is denied ---> System.Management.Automation.RemoteException: Access is denied
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : PermissionDenied: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Update-DbaInstance,Stop-Function
ErrorDetails          : Access is denied
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.153\allcommands.ps1: line 89206
                        at Update-DbaInstance<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.153\allcommands.ps1: line 79601
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```

#### Steps to Reproduce
```
Update-DbaInstance -ComputerName target_host -Version CU11 -Path \\localhost\SQL_Patches -Credential domain\account -Authentication Kerberos -ExtractPath C:\Temp -Restart
```

#### Expected Behavior
I expected that my account would be used top successfully authenticate to access the files in the local share.
The account I am using to authenticate is a local admin account, and was used to create the share.

The reason I included a Credential and Authentication parameter on the command is that this seems to be required, if I dont include this I also receive "access denied" messages

#### Actual Behavior

```
WARNING: [13:35:32][Update-DbaInstance] Failed to enumerate files in -Path | Access is denied
```
this error is reproducible on request.
 
### Environmental information
```
PowerShell Version        : 5.1.17763.1490
dbatools latest installed : 1.0.153
Culture of OS             : en-US
```

#### SQL Server:
```
@@VERSION:  
Microsoft SQL Server 2019 (RTM-CU6) (KB4563110) - 15.0.4053.23 (X64) 
Jul 25 2020 11:26:55 
Copyright (C) 2019 Microsoft Corporation
Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

@@LANGUAGE :  us_english
```

**Comment by andreasjordan** [comment]
If -Path is a network share, the access is tested from the machine executing the command. Please use a "normal" local Path starting with a drive letter - then the test is skipped.

**Comment by andreasjordan** [comment]
@AdieBe - are you still around? Have you tried a "normal" local path?

**Comment by AdieBe** [comment]
@andreasjordan  yes I am still around - the server I reported this on has since been manually updated, so I will need to find another server to test this on. Please bear with me for a day or 2 on this, thanks.

**Comment by AdieBe** [comment]
well this is annoying - now all my servers have been patched for this time around (not using dbatools, just the standard installer).
I don't have that many...
I'll most likely need to wait till the next round of applying CU's patching in 2 months to try this out again.
If this issue should be closed in the meantime, please let me know.

**Comment by andreasjordan** [comment]
I will close this now, but you can just reopen it if you face the problem again.
