### ISSUE TITLE
[Bug] Need to remove instances of ::new()

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7513]
Hopefully this can be replaced with `ArgumentList`
![image](https://user-images.githubusercontent.com/8278033/124781436-b062cd00-df43-11eb-894d-c77e42adb02f.png)

**Comment by wsmelton** [comment]
Why is there a need to remove these references? I can tell you the use of that in `Invoke-DbaQuery` has no replacement using a parameter like `-ArgumentList`.

Is there some reason this syntax needs to be removed?

**Comment by potatoqualitee** [comment]
yeah, it isn't supported by psv3 but so far, the other format works!

![image](https://user-images.githubusercontent.com/8278033/125191732-3df43480-e244-11eb-8d1d-5e881b1e93be.png)
