### ISSUE TITLE
Connect-DbaInstance - Use SqlCredential to login as a service principal

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7518]
Starting with 1.0.170, it is again possible to connect to an Azure SQL Database with a service principal.
At the moment, the code uses `-Tenant` to get the tenant id and `-SqlCredential` to get the service principal id and the secret.
When using `Connect-DbaInstance` directly, it is no problem to add `-Tenant`, but using other commands that use `Connect-DbaInstance` internally, they only use `-SqlInstance` and `-SqlCredential`. Then the config `azure.tenantid` has to be used because it is the default for `-Tenant`. This is maybe not the best way, because the config name looks like a general information and not a default for all connections - see #6896.

What about storing the tenant id and the service principal id together as the `UserName` of the credential? They are both guids and we can use `|` to separate them.
We already check the username for `\\` and `@` to find out if it is an active directory account. So we could also check for `|` to know that we have to get a token from Azure using `New-DbaAzAccessToken`.

So an example code would look like:
```
$tenantId = "3f03bfac-9d26-4690-8cda-783e205cb9a3" 
$clientId = "d58773f3-0acf-4760-83d3-7616a5ed9881"
$clientSecret = ConvertTo-SecureString "PutTheSecretHere" -AsPlainText -Force
$azureCredential = [PSCredential]::new("$tenantId|$clientId", $clientSecret)
Invoke-DbaQuery -SqlInstance myAzureDatabaseServer.database.windows.net -SqlCredential $azureCredential -Database myAzureDatabase -Query "SELECT foo FROM bar"
```

Feedback is welcome.

**Comment by wsmelton** [comment]
How will you know you need to use a token and the tenant to connect to every Azure SQL service? If I'm in a federated Azure AD I can login to Azure SQL using `domain\username` or `username@domain` format as well. What decides which way to go?

**Comment by andreasjordan** [comment]
If you have a username and password - everything works like before.

Only if you don't have that but only an ID-Secret-Combination for a service principal - then you have to get a token. I just want to change the way to get this token.

**Comment by potatoqualitee** [comment]
I am hesitant to change something that we've had since 1.0 and would prefer keeping it as is.

Storing the tenant is useful and requires a very intentional registration to make it permanent. I disagree with Klaas' objection and believe the end-user should null it out either in the config or in the params. Alternatively, we can take advantage of `AuthenticationType` and add `SqlAuthentication` and `WindowsAuthentication` but that'd be another step for the end user, though perhaps adding it can help provide clarification.

**Comment by potatoqualitee** [comment]
Alternatively, we can evaluate $SqlCredential.UserName for GUID format and if Tenant config + GUIDy Username, then use an AccessToken. If Tenant is a bound parameter, always use SqlCredential for a token.

COPILOT IS SO AWESOME. It just suggested this for me

![image](https://user-images.githubusercontent.com/8278033/125096004-0450eb80-e0d5-11eb-97a7-f2a857730983.png)


```
# check if SqlCredenteial username is a GUID 
if ($SqlCredential.UserName -match "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$") {
```
