### ISSUE TITLE
Connect-DbaInstance - changing format of $SqlCredential.UserName

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7525]
While working on https://github.com/sqlcollaborative/dbatools/discussions/7490#discussioncomment-990420 I wondered why we change "DOMAIN\user" to "user@DOMAIN". 

I just copied that from the old code path to the new code path. The old path says:
https://github.com/sqlcollaborative/dbatools/blob/b52e18d5f25d932b1d785589a6ffa0b4fd402541/functions/Connect-DbaInstance.ps1#L1391-L1418

Because in my tests, it works even if we use "DOMAIN\user".

Does anybody know?

**Comment by potatoqualitee** [comment]
I'm having a hard time remember the specifics, but it may be that it helped with LDAP or SQL on Linux.

**Comment by wsmelton** [comment]
Ldap and Azure SQL.

**Comment by potatoqualitee** [comment]
So true, some parts of Azure SQL required it too and I like things uniform.

![image](https://user-images.githubusercontent.com/8278033/125203575-3438f400-e279-11eb-96db-92fb3c550061.png)

This conversion does not impact PowerShell Core, btw. Here is the code w/o any transformations, still failing.

**Comment by potatoqualitee** [comment]
Weirdly, non-core SMO does not return any TrueLogin

![image](https://user-images.githubusercontent.com/8278033/125203630-7f530700-e279-11eb-869c-099a05d587bc.png)

**Comment by potatoqualitee** [comment]
Ugh, so close

```
$conn = New-Object -TypeName System.Data.SqlClient.SqlConnection "Initial Catalog=tempdb;Server=sql2012"
$cred.Password.MakeReadOnly()
$sqlcred = New-Object System.Data.SqlClient.SqlCredential $cred.username, $cred.password
$conn.Credential = $sqlcred
$conn.Open()
```

![image](https://user-images.githubusercontent.com/8278033/125205368-2176ed00-e282-11eb-8682-58f40946c00a.png)

**Comment by andreasjordan** [comment]
This is only for SQL Logins not for integrated security:
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcredential
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.credential

**Comment by potatoqualitee** [comment]
Doh! That makes sense

**Comment by potatoqualitee** [comment]
Ahh, turns out this is a limitation of .NET and impersonation is not supported until a super high SMO version ( 161.42121.15-msdata) that it will be pretty hard to get to since I have limited understanding of SMo and how to keep the library smaller the way sqlserver does

https://github.com/microsoft/sqlmanagementobjects/issues/6

**Comment by andreasjordan** [comment]
So that is the root cause for #7514.

**Comment by potatoqualitee** [comment]
Yep, we'll have to catch an attempt to use another cred + Core and stop function, letting them know it wont be supported for  a whiel

**Comment by wsmelton** [comment]
That SMO version is pretty old, from August of last year. The latest release of SMO is `161.46367.54`.

**Comment by andreasjordan** [comment]
As my initial question (Why do we change "DOMAIN\user" to "user@DOMAIN"?) was answered ("LDAP and Azure SQL"), I will close this.
Please put all the information about using windows logins with PowerShell Core here, as this is the related issue: #7514.
