### ISSUE TITLE
[Bug] Test-DbaWindowsLogin searches by SAMAccountName string instead of ObjectSID

### ISSUE THREAD

**Issue by carpewil** [sqlcollaborative/dbatools#7528]
#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
replace THIS text WITH the OUTPUT of -- $ERROR[0] | SELECT *
```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

**Comment by carpewil** [comment]
No error was received, just false-positive results in a few cases where SAMAccountName had changed in AD

**Comment by niphlod** [comment]
@carpewil : can you please elaborate a bit on the topic ? Are you having laying around the same samaccountname with different SIDs ?

**Comment by carpewil** [comment]
@niphlod Obviously you cannot have multiple accounts with the same SAMAccountName at the same time. Let me provide a couple of situations where the cmdlet provided false positives for orphaned SQL logins. The first was with an AD user account. Our naming convention for SAMAccountName uses a portion of the users last name and a portion of the first name. We have a developer who got married a couple of years after starting with company. When her last name changed after her marriage it triggered a process that also changed her SAMAccountName to match. Her account was not deleted and recreated. Therefore the objectSID stayed the same. So let's say her original SAMAccountName was DOMAIN\SMITSUS and that it was changed to DOMAIN\JONESUS after her marriage. Her AD account had been added as a SQL login on a couple of SQL instances using her original SAMAccountName of DOMAIN\SMITSUS. Even after her SAMAccountName changed DOMAIN\JONESUS the SQL logins continued to function because SQL actually stores the objectSID of the account. However, when I ran the cmdlet it searched for the string value of SMITSUS against DOMAIN and did not find a match indicating it was orphaned. If it had searched for the objectSID instead it would have found her account even though the SAMAccountName value had changed. 
I also had a scenario with an AD security group that had been setup as a SQL login on multiple instances. Let's call it DOMAIN\DEV_ADMINS. We had decided to deprecate the use of the security group because it's use had not followed best practice. But we could not just get rid of the group overnight due to its extended use in the past. We therefore renamed the group in AD to indicate it was Deprecated (DOMAIN\DEV_ADMINS - Deprecated). When running the cmdlet it searched DOMAIN for the literal value of DEV_ADMINS, which I didn't find and therefore said the SQL login was orphaned even though the group still existed and the SQL login still functioned. 
Hope this helps better explain things.

**Comment by niphlod** [comment]
Yeah, gotcha, perfectly clear, thanks a lot for taking the time to explain
your scenario.


Il mer 14 lug 2021, 12:17 carpewil ***@***.***> ha scritto:

**Comment by carpewil** [comment]
I had found a SQL function that converted the varbinary value that SQL stores for the Windows (AD) SID back to a valid AD objectSID value. I took it and cobbled together the PS function below to convert the value to an AD objectSID which can then be used to for the account lookup instead of the SAMAccountName string value. Im sure there's a more efficient way to write this. But hopefully it helps.

Function SQLSID2ADSID {
    param(
    [Parameter(
        Position=0,
        Mandatory=$true,
        ValueFromPipeline=$true)
    ]
    [Byte[]]$Bin)

    # Convert the varbinary value to a Hex string
$HexStr = -join ($Bin | foreach { "{0:X2}" -f $_ })

    # Test to make sure its a valid value, SID value that corresponds to an AD SID and not for a SID for SQL account
    If ($HexStr.Length % 4 -ne 0) {
        Return "Error: Invalid Value $HexStr.ToString()"
    }

    # Conver the string to an array
    $HexArr =  $HexStr -split '(..)' -ne ''

    # First part of Windows SID value, 'S-1'
    [string]$StringID = "S-" + [uint32]$HexArr[0]

    # Append second part of Windows SID value, 'S-1-5'
    $val = 0
    For ($i=2; $i -le 7; $i++) {
        $val = $val + [uint32]$HexArr[$i]
    }
    $StringID = $StringID + "-" + $val

    # Now it gets tricky because the remaining parts are stored in reverse order
    # Prep some variables we'll use to parse through the rest of the hex array
    [int]$j = 8
    [int]$x = $HexArr.Length - 1
    $RevArr = @()

    # There are 5 remaining sections of the Windows SID
    # Each section of the SID is made of 4 elements of the hex array
    # We string together the elements into their own array, $RevArr
    For ($j=1; $j -le 5; $j++) {
        $HexVal = $null
        For ($i=1; $i -le 4; $i++) {
            $HexVal = $HexVal + $HexArr[$x]
            $x = $x - 1
        }
        $RevArr += [uint32]"0x$HexVal"
    }

    # Now process the new array in reverse order and concatenate
    # the values onto the Windows SID
    For ($i = $RevArr.Length - 1; $i -ge 0; $i--){
        $StringID = $StringID + "-" + $RevArr[$i]
    }

    Return $StringID
}

#Connect to the SQL instance and get a SQL SID value
$Conn = New-Object System.Data.SqlClient.SqlConnection
$Conn.ConnectionString = "Integrated Security=true;Server=mytestpc;Database=master;"
$Command = New-Object System.Data.SqlClient.SqlCommand
$Command.CommandText = "SELECT sid FROM sys.server_principals WHERE principal_id = 259"
$Command.Connection = $Conn
$TableListSA = New-Object System.Data.SqlClient.SqlDataAdapter $Command.CommandText, $Conn.ConnectionString
$TableListSA.SelectCommand = $Command
$TableListDS = New-Object System.Data.DataSet
$TableListSA.Fill($TableListDS) | Out-Null
$Row = $TableListDS.Tables[0].Rows[0]

#Pass the SQL SID value to the function
$ADSID = SQLSID2ADSID $Row["sid"]

#Display the results
$ADSID
________________________________

**Comment by niphlod** [comment]
theoretically this is already done by SMO, but thanks for the input in case it'll be a problem

**Comment by niphlod** [comment]
hi @carpewil , would you give https://github.com/sqlcollaborative/dbatools/pull/7668 a try ?

**Comment by carpewil** [comment]
Wasn't 100% certain what I needed to do so let me explain the steps I took.
Using your link I opened the raw text file for the Test-DbaWindowsLogin function, copied it and pasted into the Test-DbaWindowsLogin.ps1 file on my machine. I then imported the dbatools module and ran the following along with results:

PS C:\WINDOWS\system32> Test-DbaWindowsLogin -SqlInstance MYINSTANCE -Login "DOMAIN\MYGROUP"
WARNING: [09:05:20][Test-DbaWindowsLogin] AD Searcher Error for MYGROUP on [MYINSTANCE]


DisabledInSQLServer : False
Domain              : DOMAIN
Enabled             :
Found               : False
LockedOut           :
Login               : MYGROUP
PasswordExpired     :
PasswordNotRequired :
Server              : MYINSTANCE
Type                : Group


Looks like it's still not finding the renamed group. It looks like the hang up for me maybe on line 159:
$u = Get-DbaADObject -ADObject "$domain\$SIDForAD" -Type User -IdentityType Sid -EnableException

Couple of things with this. First, I do not have a Get-DbaADObject cmdlet (The term 'get-dbaadobject' is not recognized as the name of a cmdlet...) nor do I see it listed in the Command Index. Second possible issue, I noticed that you have hardcoded the -Type parameter as "User". Since I dont have the cmdlet Im just guessing here, but what happens when Im testing for the existence of an AD security group (which I am)?

________________________________

**Comment by niphlod** [comment]
line 253 searches for group, line 159 for users . Get-DbaADObject is an internal function, you can find it under the internals folder.

BTW, replacing the function code works but only if you have a .git folder in the module path. dbatools speeds things up with allcommands.ps1 otherwise. If a .git folder is found where dbatools.psd1 lives, allcommands.ps1 is discarded and the whole source code is loaded. This slows down the import process performance wise, but it's the way to allow testing modified functions.

**Comment by carpewil** [comment]
Is it just the existence of a .git folder thats needed? Or do I need to have something in the .git folder?
________________________________

**Comment by niphlod** [comment]
just the folder

**Comment by potatoqualitee** [comment]
You can also download this zip: https://github.com/niphlod/dbatools/archive/refs/heads/fix/7528.zip and `import-module ./dbatools.psd1`

**Comment by carpewil** [comment]
Not working.
Tried this:
PS C:\Users\myprofile\Downloads\dbatools-fix-7528> Import-Module ./dbatools.psd1
Import-Module : The specified module './dbatools.psd1' was not loaded because no valid module file was found in any
module directory.
At line:1 char:1
+ Import-Module ./dbatools.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (./dbatools.psd1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Then tried manually copying the contents of "dbatools-fix-7528" to a new and empty "C:\Program Files\WindowsPowerShell\Modules\dbatools". Had to set my Execution policy to Unrestricted because the files were not signed, but still got this error:
Resolve-Path : Cannot find path 'C:\WINDOWS\system32\bin' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\bin\library.ps1:82 char:39
+                     $script:DllRoot = Resolve-Path -Path bin
+                                       ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\system32\bin:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

Import-Module : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:1
+ Import-Module dbatools
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Import-Module], CmdletInvocationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ImportModul
   eCommand

________________________________

**Comment by niphlod** [comment]
hey @carpewil , would you be available to hop on slack and have a quick chat so we can try and solve the issue ?

**Comment by carpewil** [comment]
Sorry for the delayed response. Been a very busy last several days. I’ll have to setup an account on Slack, but that’s fine. Please let me know a good time. I’m in Central time zone

Please pardon crafty autocorrects from my “smartphone”
________________________________

**Comment by potatoqualitee** [comment]
greets! has anything been tested? i'd like to merge soon. thanks 🙇🏼

**Comment by carpewil** [comment]
Good morning. My apologies but I was never able to figure out how to get the update installed properly. And Simone and I were never able to link up on a time to do a Slack chat session. You guys seemed to zero in on the issue I was talking about and you obviously know a whole lot more about Powershell than myself. So I have no doubts you were able to test for my scenarios with user and group objects who’s SAMAccountName had changed. So please feel free to roll with what you’ve got.
On a related note, if I may be so bold as to suggest an enhancement. Now that you are testing for the SID value, it would seem you could create a new cmdlet that could check for anomalies in SQL logins like I’ve described and rename them at the SQL login level to keep them consistent with AD as well as at the database user level as an option. Just a thought.

Please pardon crafty autocorrects from my “smartphone”
________________________________
