### ISSUE TITLE
[Bug] Reset-DbaAdmin - On Remote Execs Could Not Resolve IP And AddressList.IPAddressToString

### ISSUE THREAD

**Issue by mattcargile** [sqlcollaborative/dbatools#7529]
### Report

Remote executions of this cmdlet fail with below.
`WARNING: [23:50:27][Reset-DbaAdmin] Could not resolve SqlServer IP or NetBIOS name | The specified operator requires both the -Property and -Value parameters. Provide values for both
parameters, and then try the command again.` [I think this issue was introduced on Line 197 made within this commit. ](https://github.com/sqlcollaborative/dbatools/commit/a1c053f8a1d1cf9a16a14909f015430cc75415c4#diff-eed4f75ea03b159e4ff89eeaf5f2b1da83e01ef580174d66f81689ebd175a22aR197-R200) I think the issue was the removal of the `$_` within the `Where-Object` block.

Additionally, on line [196](https://github.com/sqlcollaborative/dbatools/blob/b52e18d5f25d932b1d785589a6ffa0b4fd402541/functions/Reset-DbaAdmin.ps1#L196), where `$hostentry` is defined, the method call to `GetHostEntry` returns `IPHostEntry` [class](https://docs.microsoft.com/en-us/dotnet/api/system.net.iphostentry?view=net-5.0) on _my_ machine which doesn't immediately include the `IPAddressToString`. I had to retrieve it from `AddressList`.

#### Workaround
`Install-Module dbatools` locally and run `Reset-DbaAdmin -SqlInstance localhost -Login 'Domain\User' -WhatIf`.

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: The specified operator requires both the -Property and -Value 
parameters. Provide values for both parameters, and then try the command again.
                        ---> System.Management.Automation.PSArgumentException: The specified operator requires 
both the -Property and -Value parameters. Provide values for both
                        parameters, and then try the command again.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord 
                           errorRecord)
                           --- End of inner exception stack trace ---
TargetObject          :
CategoryInfo          : InvalidArgument: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Reset-DbaAdmin,Stop-Function
ErrorDetails          : The specified operator requires both the -Property and -Value parameters. 
Provide values for both parameters, and then try the command again.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, 
C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.170\allcommands.ps1: line 89813
                        at Reset-DbaAdmin<Process>, 
C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.170\allcommands.ps1: line 64807
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

Run `Reset-DbaAdmin -SqlInstance $RemoteServer -Login 'Domain\User' -WhatIf`

#### Expected Behavior

Add Domain\User as `sa` to $RemoteServer

#### Actual Behavior

Failure happens.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.170
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) 
	Aug 22 2017 17:04:49 
	Copyright (C) 2017 Microsoft Corporation
	Express Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
```

```sql
us_english
```

**Comment by andreasjordan** [comment]
Long time ago... - I probably have not tested this very well.

I think we can just use Resolve-DbaNetwokName to replace a lot of lines...

But I found other issues, so this will take some time. Will better test this now.

**Comment by andreasjordan** [comment]
Ok, the "other issues" where in my environment. Opened a pull request.

**Comment by mattcargile** [comment]
Thanks! I did find when I ran the command locally, I couldn't get the DOMAIN\Group assignment to work either. I had to use a DOMAIN\User. Here is the output. Not sure if I should open another report or not.

![image](https://user-images.githubusercontent.com/74641867/125338177-80397680-e315-11eb-9179-61e026a80f2e.png)

Here is the applicable `$Error`.

```powershell
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Cannot use ALTER LOGIN with the ENABLE or DISABLE argument for a Windows group. GRANT or REVOKE the CONNECT SQL permission instead. ---> System.Data.SqlClient.SqlException: Cannot use ALTER LOGIN with the ENABLE or DISABLE argument for a Windows group. GRANT or REVOKE the CONNECT SQL permission instead.
                           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
                           at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
                           at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-ResetSqlCmd,Stop-Function
ErrorDetails          : Cannot use ALTER LOGIN with the ENABLE or DISABLE argument for a Windows group. GRANT or REVOKE the CONNECT SQL permission instead.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.168\allcommands.ps1: line 89741
                        at Invoke-ResetSqlCmd, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.168\allcommands.ps1: line 64684
                        at Reset-DbaAdmin<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.168\allcommands.ps1: line 64956
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

**Comment by andreasjordan** [comment]
I will look at that tomorrow. No need to open a new issue.

But google says "it's by design": https://www.google.com/search?q=cannot+use+alter+login+with+the+enable+or+disable+argument+for+a+windows+group

So we would have to catch the error and use a workaround.

**Comment by andreasjordan** [comment]
Ok, @mattcargile - please open a new issue about DOMAIN\Group. Does not need to be very detailed, just copy you comment with the screenshot.
