### ISSUE TITLE
Invoke-DbaQuery - SqlInstance Position 0 For ParameterSetNames

### ISSUE THREAD

**Issue by mattcargile** [sqlcollaborative/dbatools#7544]
### Summarize Functionality

I discussed a little bit about this in the dbatools slack and I was encouraged by @andreasjordan to create this feature request and, of course, I would love to see this as a feature.

From using many of the cmdlets, I enjoy being able to using SqlInstance/ComputerName as the default first non explicitly defined parameter with a position equal to 0. When I attempt this with a call like `Invoke-DbaQuery localhost -Query 'SELECT @@VERSION'`, I receive the below error.

```powershell
A positional parameter cannot be found that accepts argument 'localhost'.
    + CategoryInfo          : InvalidArgument: (:) [Invoke-DbaQuery], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Invoke-DbaQuery
```

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

I believe this can be accomplished by defining the `Position = 0` parameter property for each of the three `ParameterSetName`s which are Query, File, and SMO. The discovery of this solution was found at [this link](https://blog.simonw.se/powershell-functions-and-parameter-sets/). [Powershell Help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.1#position-argument) does say Position is automatic, though, when you define one `Position` explicitly, [it appears](https://www.powershellstation.com/2017/10/04/specifying-powershell-parameter-position/) that it disables the functionality for the other parameters altogether. I don't think Positional parameters ever worked because of `ParameterSetName` so it shouldn't impact current user's usage of the script.

So, I _think_ this can be accomplished by replacing 

https://github.com/sqlcollaborative/dbatools/blob/8206756dedc86b91d4ef1ca97925bab8abb53419/functions/Invoke-DbaQuery.ps1#L124-L125 
with the below.

```powershell
        [parameter(ValueFromPipeline)]
        [Parameter(ParameterSetName = 'Query', Position = 0)]
        [Parameter(ParameterSetName = 'File', Position = 0)]
        [Parameter(ParameterSetName = 'SMO', Position = 0)]
        [DbaInstance[]]$SqlInstance,
```

I'm not sure how the `ValueFromPipeline` property should be handled like if it should be included in all of Parameter definitions that follow it. I believe it would fall into `__AllParameterSets` if left as is.

**Comment by potatoqualitee** [comment]
This seems reasonable 👍🏼
