### ISSUE TITLE
[Bug] - Add-DbaAgDatabase's new use of  Test-DbaAvailabilityGroup is too aggressive

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbatools#7574]
### Verified issue does not already exist?

Yes

### What error did you receive?

Availability Group AG_MyDatabase not found on replica [server_b].

### Steps to Reproduce

```powershell
New-DbaAvailabilityGroup -Primary server_a -Secondary server_b -Name AG_MyDatabase -Database MyDatabase -SeedingMode Automatic -FailoverMode Automatic -ClusterType Wsfc -Confirm:$false -Verbose -EnableException   
```

### Are you running the latest release?

Yes

### Other details or mentions

Module Version: 1.0.173

----

It looks like the issue is when `Test-DbaAvailabilityGroup` is called by `Add-DbaAgDatabase` via `New-DbaAvailabilityGroup` to verify the state. The secondary replica in my case is joining the AG properly (every time after it has errored I checked immediately and it was joined), but I think this is checking if the secondary replica is joined *slightly* too fast and thus unnecessarily erroring out:

https://github.com/sqlcollaborative/dbatools/blob/c3d927ea7e7013f13ad6014ccaf29a4b7b8376d2/functions/Test-DbaAvailabilityGroup.ps1#L218-L229

The same command/params/database/instances were all working correctly on version 1.0.136.

I think it may need an artificial wait like the others from the same [PR](https://github.com/sqlcollaborative/dbatools/pull/7407)?

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.6
PSEdition                      Core
GitCommitId                    7.2.0-preview.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64)  
2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit)

**Comment by andreasjordan** [comment]
Hi @LowlyDBA , thanks for reporting this. Will take care of it. Do you have a workaround? Like first building the AG without databases and than run `Add-DbaAgDatabase` after some seconds?

**Comment by andreasjordan** [comment]
Best fix would be to change Add-DbaAgReplica to wait for a successful join before returning.

**Comment by andreasjordan** [comment]
It seems not a matter of time but of missing SMO refresh. Because the SMO generated by New-DbaAvailabilityGroup is reused with Add-DbaAgDatabase and thus Test-DbaAvailabilityGroup - an up to date status of the SMO is important.

**Comment by LowlyDBA** [comment]
That makes sense! Thanks for diagnosing. I was checked out after spending
all day thinking it was something on my infrastructure's end 😅
