### ISSUE TITLE
Write-DbaDataTable ignores when Database is in $connstring

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7587]
### Verified issue does not already exist?

Yes

### What error did you receive?

```
WARNING: [14:36:55][Write-DbaDbTableData] You must specify a database or fully qualified table name.
```

### Steps to Reproduce

```powershell
[682ms] C:/github/dbatools❯ $connstring = "Server=dbatoolstest.database.windows.net; Authentication=Active Directory Service Principal; Database=test; User Id=GUID; Password=xyz"
[682ms] C:/github/dbatools❯ Get-ChildItem -File | Write-DbaDataTable -SqlInstance $connstring -Table new
WARNING: [14:36:55][Write-DbaDbTableData] You must specify a database or fully qualified table name.
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                 
----                           -----                                                                                 
PSVersion                      5.1.19041.1023                                                                        
PSEdition                      Desktop                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                               
BuildVersion                   10.0.19041.1023                                                                       
CLRVersion                     4.0.30319.42000                                                                       
WSManStackVersion              3.0                                                                                   
PSRemotingProtocolVersion      2.3                                                                                   
SerializationVersion           1.1.0.1                                                                               

### SQL Server Edition and Build number

Azure

**Comment by potatoqualitee** [comment]
Oh! That's what I meant here: https://github.com/sqlcollaborative/dbatools/issues/5566 Closing that one since this has more info

**Comment by mattcargile** [comment]
I was just looking at this. I was passing in output from `Connect-DbaInstance` into `-SqlInstance`. And the aforementioned cmdlet wasn't picking up the `-Database` parameter passed in through `Connect-DbaInstance`.

Thanks for the report.

**Comment by potatoqualitee** [comment]
Should be fixed once my PR gets merged 🥳  I'll test with your use-case as well.

**Comment by mattcargile** [comment]
Thanks. I was wondering for the [if block](https://github.com/sqlcollaborative/dbatools/blob/7954aed2054ba708c9eae8e7dd7b151dc3142574/functions/Write-DbaDbTableData.ps1#L215) on `Write-DbaDbTableData`, how is `$server` derived? Does it come from the `[DbaInstanceParameter]`?
