### ISSUE TITLE
Connect-DbaInstance - warning is too chatty

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7588]
### Verified issue does not already exist?

No

### What error did you receive?

`Additional parameters are passed in, but they will be ignored`

### Steps to Reproduce

```powershell
 Get-ChildItem -File | Write-DbaDataTable -SqlInstance $connstring -AutoCreateTable -Table testtbl
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

$PSVersionTable | clip lol

### SQL Server Edition and Build number

Azure

**Comment by potatoqualitee** [comment]
So the way I'm testing -- `-Database` is being passed in. I can see why it'd be helpful to accommodate anyone who wants to simplify and use `-Database` instead of keeping it in the connstring. Perhaps we can accommodate.

**Comment by andreasjordan** [comment]
What do you have in `$connstring`?

**Comment by potatoqualitee** [comment]
Connstring has Database, then to get around a parsing issue, I have to force `$PSBoundParameter.Database`. I can see just ignoring in the warning or readjusting the db.

**Comment by andreasjordan** [comment]
Ok, will try later today.

**Comment by potatoqualitee** [comment]
I'm done with my PR, I'll take are of this request 👍🏼
