### ISSUE TITLE
Update-DbaInstance doesn't have an option to use -UseSSL

### ISSUE THREAD

**Issue by MikeLa1234** [sqlcollaborative/dbatools#7598]
### Summarize Functionality

 I can not use Update-DbaInstance on Windows 2019 servers.  Additional security is configured that requires WinRM to connect with the UseSSL option.   There is no option available in Update-DbaInstance to do this currently.

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by nvarscar** [comment]
We should introduce -UseSSL switch to our internal `Invoke-Command2` function and expose this switch in Update/Install-DbaInstance commands.

**Comment by andreasjordan** [comment]
`Invoke-Command2` has `-UseSSL`, which has a default from `Get-DbatoolsConfigValue -FullName 'PSRemoting.PsSession.UseSSL' -Fallback $false`.

So @MikeLa1234 - you can try setting this config with:
```
Set-DbatoolsConfig -FullName 'PSRemoting.PsSession.UseSSL' -Value $true
```

This will live in your session only. To persist it, use:
```
Set-DbatoolsConfig -FullName 'PSRemoting.PsSession.UseSSL' -Value $true -PassThru | Register-DbatoolsConfig
```

**Comment by potatoqualitee** [comment]
I believe that @andreasjordan's solution is the proper solution for all commands that require SSL, and that we should not add an extra param to `Update-DbaInstance`. I'm open to change, but will close this one as solved.
