### ISSUE TITLE
Get-DbatoolsError

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7611]
### Summarize Command's Functionality'

Instead of asking people to do `$error[0]`, we can offer `Get-DbatoolsError` and default to `[0]` or, my fav `Select-Object -First 1`

Then offer `-All`, `-First`, `-Skip`, and `-Last`

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by wsuhoey** [comment]
What if we need a few more errors? For example `$error[1]` and `$error[2]`, how would we handle that?
Would `-First` and `-Last` have a numerical parameter along with them? like `-First 3` or `-Last 3` to get the first 3 (oldest) errors in the stack and the last 3 (most recent) errors?

**Comment by potatoqualitee** [comment]
Right, @wsuhoey! -First 3 -Skip 1 etc. or -All then post process.
