### ISSUE TITLE
Error when running 'invoke-dbaquery' in Powershell 7.1.3

### ISSUE THREAD

**Issue by leetrobotz** [sqlcollaborative/dbatools#7627]
### Verified issue does not already exist?

Yes

### What error did you receive?

WARNING: [15:08:38][Invoke-DbaQuery] [Prod2] Failed during execution | Cannot find an overload for "SqlCommand" and the argument count: "2".

InvalidOperation: C:\Program Files\PowerShell\Modules\dbatools\1.1.1\allcommands.ps1:90205
 Line |
90205 |          throw $records[0]
      |          ~~~~~~~~~~~~~~~~~
      | Cannot find an overload for "SqlCommand" and the argument count: "2".

### Steps to Reproduce

From Powershell 7.1.3 on Windows 10 Enterprise 20H2 with dbatools v1.1.1

execute the following:
invoke-dbaquery -sqlinstance Prod2 -query "select @@version"

### Are you running the latest release?

Yes

### Other details or mentions

The sequence 'invoke-dbaquery -sqlinstance Prod2 -query "select @@version" executes successfully in PS v5.1.19041 on this same machine.
We were trying to use invoke-dbaquery to avoid an issue with the Sqlserver cmdlet 'invoke-sqlcmd' between 7.1.3 and 5.1, where it doesn't respect the -disablevariables switch in 7.1.3, research led us to 'invoke-sqlcmd2' which was incorporated/modified into the current 'invoke-dbaquery'.

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     1.1.1                 dbatools

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64)
        Nov  2 2020 18:35:09
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Hey @leetrobotz -- I think something may  be up with your machine. I cannot repro your issue. 

![image](https://user-images.githubusercontent.com/8278033/127239930-5ac38c7c-7780-40a0-b1a4-d045274cfd69.png)

Oh, but I also don't use the `SqlServer` module. It does conflict with our own. Make sure you close your pwsh session and only import dbatools so that there won't be a library conflict between us and `SqlServer`.

**Comment by potatoqualitee** [comment]
gonna close this because im prettttttty sure it's sqlserver. if you continue to have issues, i'll reopen.

**Comment by leetrobotz** [comment]
Argh, I swear I tested that. We were back and forth on disabling our profiles and installing/importing/upgrading/removing modules all afternoon.
I tried it again in a clean Powershell this morning and it works fine. Sorry.

**Comment by potatoqualitee** [comment]
great news for us 😊
