### ISSUE TITLE
Import-DbaCsv not honoring column names for automatic mapping

### ISSUE THREAD

**Issue by paschott** [sqlcollaborative/dbatools#7630]
### Verified issue does not already exist?

Yes

### What error did you receive?

No errors received, just wrong results

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Import-DbaCsv -Path c:\test\test1.csv -sqlinstance localhost -database TestImports -Table TestCsvImport -AutoCreateTable
#  Verify results
Import-DbaCsv -Path c:\test\test1.csv -sqlinstance localhost -database TestImports -Table TestCsvImport -Truncate
#  Columns/data still in expected order
Import-DbaCsv -Path c:\test\test2.csv -sqlinstance localhost -database TestImports -Table TestCsvImport -Truncate
 ## Test2 is the same data, but columns re-ordered.
 # When reviewing the data here, the data shows in ordinal position rather than in appropriately mapped columns

### Are you running the latest release?

Yes

### Other details or mentions

When I ran this using dbatools v1.0.104 the column mapping worked as expected.  This isn't working in v1.0.173 or v1.1.*

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

Verified in v7.1.3 and v5.1

### SQL Server Edition and Build number

SQL 2019 CU11

**Comment by potatoqualitee** [comment]
Thanks for the report and detail! Looks like [a lot of work has been done on the command](https://github.com/sqlcollaborative/dbatools/commits/development/functions/Import-DbaCsv.ps1) since 1.0.4, this may take a lil bit to resolve.

**Comment by potatoqualitee** [comment]
jk, found it! the fix will be in tomorrow's release 👍🏼
