### ISSUE TITLE
Change default location backup, data, and log

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbatools#7646]
### Summarize Command's Functionality'

Change the default locations for backups, data, and logs

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

Here is a sample script for backups:

Add-Type -AssemblyName "Microsoft.SqlServer.Smo"
$server = New-Object Microsoft.SqlServer.Management.Smo.Server($env:ComputerName)
$server.Properties["BackupDirectory"].Value = $BackupDirectory
$server.Alter()

**Comment by potatoqualitee** [comment]
Sounds good. this would be `Get-DbaDefaultPath`

**Comment by tboggiano** [comment]
I started on my cloned repo under branch 7646, I can only get it change the backup directory which is a bummer but the outline is there if someone can figure the rest out.

**Comment by potatoqualitee** [comment]
I'll take a look, thank you!

**Comment by potatoqualitee** [comment]
Looks like it requires a restart before it shows up 👍🏼

**Comment by tboggiano** [comment]
I thought it might be something like that but I looked at configured vs running values and they were no different.  And warning ErrorLog is a read only property, so we may need to leave it out or find a different way to edit it.

**Comment by potatoqualitee** [comment]
ohh i wondered! that is done using set parameter. i didnt test that one, ill remove it.

**Comment by tboggiano** [comment]
Yeah I was trying to set all the ones that were in the same Get command

**Comment by potatoqualitee** [comment]
just removed and added a note to use Set-DbaStartupParameter for error log

**Comment by tboggiano** [comment]
👍
