### ISSUE TITLE
No Get-DbaBuildReference alias for Get-DbaBuild in latest releases

### ISSUE THREAD

**Issue by bigbearzhu** [sqlcollaborative/dbatools#7664]
### Verified issue does not already exist?

No

### What error did you receive?

Get-DbaBuildReference : The 'Get-DbaBuildReference' command was found in the module 'dbatools', but the module could
not be loaded. For more information, run 'Import-Module dbatools'.

### Steps to Reproduce

Run `Get-DbaBuildReference`

### Are you running the latest release?

Yes

### Other details or mentions

In doc for Get-DbaBuild, https://docs.dbatools.io/Get-DbaBuild, Get-DbaBuildReference is an alias for Get-DbaBuild.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Not relevant

### SQL Server Edition and Build number

Not relevant.

**Comment by potatoqualitee** [comment]
Please download the latest update! but also, something seems up with your import and i'd still like to know the details if you can share.

**Comment by bigbearzhu** [comment]
Thanks I think 1.1.6 has got the issue fixed!

This is the import log for 1.1.5 when I ran `Import-Module dbatools -Verbose`. It has `Update-DbaBuildReference` alias but not the `Get-DbaBuildReference`.
[dbatools.log](https://github.com/sqlcollaborative/dbatools/files/6919812/dbatools.log)
