### ISSUE TITLE
Write-DbaDataTable iterating row by row; not inserting input as a set

### ISSUE THREAD

**Issue by kensorensen2001** [sqlcollaborative/dbatools#7669]
### Verified issue does not already exist?

Yes

### What error did you receive?

No Error, but poor INSERT performance. Instead of inserting the input as a set, it is inserting to the target table row by row. This can be verified with a SQL trace, and running a count on the target table while the PS1 script executes.

I first found this with dbatools version 1.0.164, but also repro'd with version 1.1.6.

[RABR_POC.ps1.txt](https://github.com/sqlcollaborative/dbatools/files/6918941/RABR_POC.ps1.txt)
[Get-DBAToolsLog.txt](https://github.com/sqlcollaborative/dbatools/files/6918942/Get-DBAToolsLog.txt)

Sorry, not including New-DbatoolsSupportPackage - I don't have the wherewithal to scrub this output.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
1. Set up a target SQL server database.
2. set up this query if you want to run COUNT while the script runs:
SELECT COUNT(*)
FROM dbo.RowByRow_POC WITH (NOLOCK)
Set up a SQL trace if you like.

2. Clean up the extension of the attached ps1 script.
3. Run it.  This script tries two different syntax schemes. Both insert one record at a time

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

$PSVersionTable

Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      5.1.19041.610                                                                                                                 
PSEdition                      Desktop                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                       
BuildVersion                   10.0.19041.610                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                               
WSManStackVersion              3.0                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                           
SerializationVersion           1.1.0.1 

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU25) (KB5003830) - 14.0.3401.7 (X64)   Jun 25 2021 14:02:48   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Hey Ken,
Thanks for taking the time to file this issue. I noticed that you used AutoCreateTable which uses varchar(max) galore. Here's ah example for piping Get-ChildItem -File

![image](https://user-images.githubusercontent.com/8278033/127911137-ef39ebf2-9a4a-489f-a428-bfba62a8d3f1.png)

This ensures you can write with no issue but is really slow. Nevertheless, I'll take a look to see what could be the problem.

**Comment by potatoqualitee** [comment]
When I run the following with a SQL trace:

`Write-DbaDataTable -SqlInstance localhost -Database tempdb -Table files -InputObject $files`

I only get two insert bulk hits for 2k rows -- starting and completing.

![image](https://user-images.githubusercontent.com/8278033/127913293-45b6e85d-61f6-4fd9-956f-b62fa8623359.png)

It is a bit slow to convert to a datatable (before it hits the db) but we've optimized that to the best of our ability.

**Comment by kensorensen2001** [comment]
Thanks for the updates!  I'm aware of the issue with autocreate; in our case we already have the tables instantiated.

What kind of conversion time are you seeing for the marshaling and prep for the insert?  Still, that doesn't get at why we are seeing our process create a bulk insert for *each* record.  

Did the ps1 script I attached work as a single batch for you?

**Comment by potatoqualitee** [comment]
It makes sense that it does it row by row if you pipe it in, we do document that it's convenient but slow. The best way to improve speed is by using `-InputObject` which you did in the second command. Since the batch size is 50000, I imagine it'll make a bulk insert call every 50k rows.

**Comment by potatoqualitee** [comment]
gonna close this issue as i cannot repro with the recommended method, all others are slow as expected. happy to continue talking about it, however.

**Comment by kensorensen2001** [comment]
Did find a resolution for this in the documentation: https://docs.dbatools.io/Write-DbaDbTableData  example 2.  It show the extraction of the data using Invoke-Query *-As DataSet*.  To get this to work I set the column names and datatypes delivered by Invoke-Query to match EXACTLY (including case sensitivity of column names) those of the target table.

Thanks for your help with this!
