### ISSUE TITLE
Using IP Address for WinRM/PowerShell Remoting Results in Errors (Test-DbaPowerPlan)

### ISSUE THREAD

**Issue by rayterrill** [sqlcollaborative/dbatools#767]
### Is this a *feature* OR *bug*:

Feature modification?

### System Details

- Operating system name and version:

Win7.

- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Output of dbatools version:

PS C:\WINDOWS> (Get-Module dbatools -ListAvailable).Version

```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      902    -1
```

- SQL Server version for source/target

SQL2014.

### Steps to Reproduce

```
PS C:\WINDOWS> Test-DbaPowerPlan -ComputerName MYMACHINE
Get-CimInstance : The WinRM client cannot process the request. Default
authentication may be used with an IP address under the following conditions:
the transport is HTTPS or the destination is in the TrustedHosts list, and
explicit credentials are provided. Use winrm.cmd to configure TrustedHosts.
Note that computers in the TrustedHosts list might not be authenticated. For
more information on how to set TrustedHosts run the following command: winrm
help config.
At line:95 char:21
+ ... erplans = $(Get-CimInstance -ComputerName $ipaddr -classname Win32_Po ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (root\cimv2\power:Win32_PowerPl
   an:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x803381bb,Microsoft.Management.Infrastr
   ucture.CimCmdlets.GetCimInstanceCommand
    + PSComputerName        : 10.10.10.10

WARNING: Can't connect to WMI on MYMACHINE
```

### Action Results

Error caused by Get-CIMInstance using IP address.

### Expected Results

Using an IP address for WinRM only works if you have HTTPS configured (not the default, requires additional configuration) or have added the hosts to your TRUSTED HOSTS (which disables mutual auth). Maybe go back to using hostname?

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by potatoqualitee** [comment]
This now works! 

![image](https://user-images.githubusercontent.com/8278033/28501477-a6bc3622-6fdc-11e7-8aaa-7cdafadf8e09.png)
