### ISSUE TITLE
Get-DbaInstanceInstallDate does not return a date for some instances

### ISSUE THREAD

**Issue by RandyInMarin** [sqlcollaborative/dbatools#7675]
### Verified issue does not already exist?

Yes

### What error did you receive?

A date failed to return without error.  

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
#Requires -Version '7.0'
#Requires -Module @{ ModuleName = 'DbaTools'; ModuleVersion = '1.1.6' }
Get-DbaInstanceInstallDate -SqlInstance 'xxxx\xxxx' -IncludeWindows

ComputerName       : xxxx
InstanceName       : xxxx
SqlInstance        : xxxx\xxxx
SqlInstallDate     :
WindowsInstallDate : 2020-01-15 14:02:19.000

### Are you running the latest release?

Yes

### Other details or mentions

I have DBATools 1.1.6.  The install for 1.1.7 fails to download at this time.  

Out of a 110 instances, only 3 fail to return an install date.  All three are from builds by the same vendor.  They might have done the image sysprep method for the install.  Anyway, the query "SELECT * FROM sys.server_principals WHERE sid = 0x010100000000000512000000" fails to return anything.  The other method "SELECT schemadate FROM sysservers" for versions prior to 9 does work.  

It appears that if the first attempt does not return a value for version 9+ cases, the second method should be used.  

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Thanks for the report! can you please test with this code from a fresh powershell session?

https://github.com/sqlcollaborative/dbatools/archive/refs/heads/Get-DbaInstanceInstallDate.zip

**Comment by potatoqualitee** [comment]
Hey Randy, sorry, I merged and deleted the branch by the time you ran it. 

I added

```
    if (-not $sqlInstallDate -or $sqlInstallDate -is [System.DBNull]) {
        Write-Message -Level Verbose -Message "Trying again to get Install Date for: $instance"
        $sql = "SELECT schemadate FROM sysservers"
        [DbaDateTime]$sqlInstallDate = $server.Query($sql, 'master', $true).create_date
    }
```

Can you run with `Verbose` and tell me if you see `Trying again to get Install Date for: $instance`

**Comment by RandyInMarin** [comment]
Hi Chrissy, verbose does show that it is trying again.  Changing create_date to schemadata might be all that's needed.  The following works for me.  

`(Invoke-DbaQuery -SqlInstance 'ODDSERVER' -Database 'master' -Query 'SELECT schemadate FROM sysservers').schemadate` 

I wonder if "Set-StrictMode -Version Latest" might help in development.

**Comment by potatoqualitee** [comment]
oops! no wonder it didn't work. that change makes sense. Thank you
