### ISSUE TITLE
Connexion Issues unless FQDN name is used

### ISSUE THREAD

**Issue by habibhammy** [sqlcollaborative/dbatools#7679]
### Verified issue does not already exist?

Yes

### What error did you receive?

Hi Team,

I discovered lately that we are facing issues with the latest DBATOOLS versions (starting from v1.1.0).
Actually, I have a statistic Powershell script that runs every month. The script connects to each SQL server and get statistics over the hosted databases in it. However, the script is failing with all the latest versions since v1.1.0. We are getting connection errors from all the dbatools command such as [Get-DbaDatabase] [Get-DbaDbFile] [Get-DbaAvailabilityGroup] [Get-DbaRegServer]... After some checks it seems that those commands are working only when FQDN is used. The script is still working perfectly with older versions. 
The error message comes like : 

PS C:\new SQl Stats> Get-DbaDatabase -SqlInstance 'MOCKSERVERNAME' -EnableException
The target principal name is incorrect
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.0\allcommands.ps1:90200 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (MOCKSERVERNAME:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Get-DbaDatabase
 
In first place I though it was related to the latest changes on the Connect-DbaInstance command so I've run this command passed in the releases description to switch to the old connection model but it did not resolve the issue.
The PS command : Set-DbatoolsConfig -FullName sql.connection.legacy -Value $true

Many Thanks all for your help

### Steps to Reproduce

```powershell
Get-DbaDatabase -SqlInstance 'MOCKSERVERNAME'
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

We are using Powershell V 5.1.17763.1971  and .Net Framework V4.7.03190

### SQL Server Edition and Build number

All SQL version for SQL2000 to SQL 2019

**Comment by potatoqualitee** [comment]
Thanks for the issue, @habibhammy ! I just created this discussion to explain what's going on.

https://github.com/sqlcollaborative/dbatools/discussions/7680

Fortunately, this error is new and expected as Microsoft changed their settings to be more secure, but the fix can be quick and easy.
