### ISSUE TITLE
Get-DbaRegServerGroup does not parse a group path

### ISSUE THREAD

**Issue by RandyInMarin** [sqlcollaborative/dbatools#7685]
### Verified issue does not already exist?

Yes

### What error did you receive?

There are no errors returned, but nothing is returned when a group path uses a single backslash to separate the group names. 

The desired group is returned when a group path uses a double backslash to separate group names.  I don't think this is expected.  

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

```
#Requires -Version '7.0'
#Requires -Module @{ ModuleName = 'DbaTools'; ModuleVersion = '1.1.9' } # Install-Module -Name dbatools

#Add a "Test" group to CMS.  Add SubTest1 and SubTest2 groups to the Test group.

#Note: I added \ in this post to get the right number of \ to display.  Pesky escapes are hard to display correctly.    

Get-DbaRegServerGroup SQLCMS -Group 'Test' |
    %{write-debug ("1. Test: Name = {0}" -f $_.name) -debug}

Get-DbaRegServerGroup SQLCMS -Group 'Test' |
    Select-DbaObject -ExpandProperty ServerGroups |
    %{write-debug ("2. Test|ServerGroups: Name = {0}" -f $_.name) -debug}

Get-DbaRegServerGroup SQLCMS  -Group 'Test\SubTest1' |
    %{write-debug ("3. Test\SubTest1: Name = {0}" -f $_.name) -debug}

Get-DbaRegServerGroup SQLCMS -Group 'Test\SubTest2' |
    %{write-debug ("4. Test\SubTest2: Name = {0}" -f $_.name) -debug}

Get-DbaRegServerGroup SQLCMS -Group 'Test\\\\SubTest1' |
    %{write-debug ("5. Test\\\\SubTest1: Name = {0}" -f $_.name) -debug}

Get-DbaRegServerGroup SQLCMS  -Group 'Test\\\\SubTest2' |
    %{write-debug ("6. Test\\\\SubTest2: Name = {0}" -f $_.name) -debug}

Results:

DEBUG: 1. Test: Name = Test
DEBUG: 2. Test|ServerGroups: Name = SubTest1
DEBUG: 2. Test|ServerGroups: Name = SubTest2
DEBUG: 5. Test\\\\SubTest1: Name = SubTest1
DEBUG: 6. Test\\\\SubTest2: Name = SubTest2
```

### Are you running the latest release?

Yes

### Other details or mentions

I see regex \\\\ escapes in the code which are required.  Then there's $split = $currentgroup.Split('\\\\') that's not regex.  Just one little character....

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by RandyInMarin** [comment]
Hi.  My double \ got escaped in the above.  I'll try escaping them.  

Get-DbaRegServerGroup SQLDBAPROD -Group 'Test\\\\SubTest1' |
%{write-debug ("5. Test\\\\SubTest1: Name = {0}" -f $.name) -debug}
Get-DbaRegServerGroup SQLDBAPROD -Group 'Test\\\\SubTest2' |
%{write-debug ("6. Test\\\\SubTest2: Name = {0}" -f $.name) -debug}

I see regex \\\\ escapes in the code which are required. Then there's $split = $currentgroup.Split('\\\\') that's not regex. Just one little character....

**Comment by RandyInMarin** [comment]
That worked.  Sorry for the noise.  I'll try to edit the original test.

**Comment by potatoqualitee** [comment]
Thank you for the report! Sure enough, the original method works in Windows PS but not PS Core. I've submitted a fix 👍🏼
