### ISSUE TITLE
Export-DbaDbRole - Normalize Export File Line Endings

### ISSUE THREAD

**Issue by mattcargile** [sqlcollaborative/dbatools#7689]
### Summarize Functionality

Convert `$prefix` to use `` `r`n `` line endings like the SQL Server uses and like the `$BatchSeperator` uses within the lines below.
https://github.com/sqlcollaborative/dbatools/blob/3359ca3afd5792bd957a12d625a43c35eaca96f3/functions/Export-DbaDbRole.ps1#L370-L379

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

See above. Use `` `r`n `` instead of `` `n `` for the `$prefix` definition. 

This functionality works for `Export-DbaDbUser`. This feature would prevent the below message when opening the `.sql` file within SQL Server Management Studio.

![image](https://user-images.githubusercontent.com/74641867/128536429-eccd9f6e-038a-4b42-b3c9-f55ecd8a526c.png)

**Comment by yzorg** [comment]
consider $Eol = [System.Environment]::NewLine, then "$BatchSeparator$Eol"

**Comment by andreasjordan** [comment]
Searching the code for "`r" shows more that 20 other files which should be updated also.

**Comment by potatoqualitee** [comment]
sweet, that `$eol` snippet is helpful. I couldn't figure out which one would resolve that issue. @andreasjordan would you like to do the batch?

**Comment by andreasjordan** [comment]
Yes, will do that. Do we call the variable `$eol` for end of line?

**Comment by potatoqualitee** [comment]
thank you so much! that sounds great
