### ISSUE TITLE
Could not install lastest CU for SQL 2019 (2019SP0CU12) using Update-DbaInstance

### ISSUE THREAD

**Issue by SahFari** [sqlcollaborative/dbatools#7702]
### Verified issue does not already exist?

No

### What error did you receive?

Hi,
Could not install lastest CU for SQL 2019 (2019SP0CU12) using Update-DbaInstance. 

We got this message: [Get-SqlInstanceUpdate] Couldn't find an exact build match with specified parameters while updating SQL2019

However, CU12 is listed as the lastest CU for 2019 on https://sqlcollaborative.github.io/builds.

I had downloaded latest CU: SQLServer2019-KB5004524-x64.exe

### Steps to Reproduce

Set-DbatoolsConfig -Name Path.SQLServerUpdates -Value '\\...\_Microsoft\SQL Server installationsmedia\SQL Server SP & CU\'

$Patch_path = (Get-DbatoolsConfigValue -Name 'Path.SQLServerUpdates')

$ListOfServers = "SQLLAB1", "SQLLAB2"

Update-DbaInstance -ComputerName $ListOfServers -version 2017SP0CU25, 2019SP0CU12 -Path $Patch_path -Restart -Confirm:$true -ExtractPath "C:\temp" -Credential ...
 

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

PSVersion                      5.1.19041.1023                                                                                                                                  
PSEdition                      Desktop                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                         
BuildVersion                   10.0.19041.1023                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                             
SerializationVersion           1.1.0.1    

### SQL Server Edition and Build number

Installed version: CU10 (15.0.4123.1) - KB5001090

**Comment by andreasjordan** [comment]
You might need to update your local build reference with `Update-DbaBuildReference`: https://docs.dbatools.io/Update-DbaBuildReference

**Comment by SahFari** [comment]
Aha, Thank you! Will test that next week, when we are going to upgrade dev environment! 

Kind Regard,
/Fari

**Comment by andreasjordan** [comment]
Ok, I will close this now. If you still have problems next week, you can reopen it.
