### ISSUE TITLE
[Bug] ScriptOnly cannot create file due to colon after protocol name in file path

### ISSUE THREAD

**Issue by EitanBlumin** [sqlcollaborative/dbatools#7704]
### Verified issue does not already exist?

Yes

### What error did you receive?

If the target SQL instance is specified as ".", then it returns error message:

```
Cannot convert value "NP:." to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: NP:."
At C:\Users\**********\Documents\WindowsPowerShell\Modules\dbatools\1.1.9\allcommands.ps1:59403 char:25
+                         $server = [dbainstance]$instance
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastConstructorException
```

If connecting to an instance via TCP, then there's no error message. But the generated script file is still not created.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference

$SourceSqlInstance = '.'
$TargetSqlInstance = "mssql-srv.database.windows.net" # also fails when using "." due to "Failed to parse instance name: NP:." error

$SourceDB = "DemoDB"
$TargetDB = "DemoDB_2"

$PublishFile = "C:\Temp\$SourceSqlInstance-$SourceDB-$(Get-Date -f "yyyyMMdd_hhmmss").dacpac"

Export-DbaDacPackage -SqlInstance $SourceSqlInstance -Database $SourceDB -Type Dacpac -Verbose -FilePath $PublishFile

Publish-DbaDacPackage -SqlInstance $TargetSqlInstance -Database $TargetDB -Type Dacpac -Path $PublishFile -Verbose -ScriptOnly

# (the file is not actually created)
```

### Are you running the latest release?

Yes

### Other details or mentions

The error appears to be happening due to line 263 in `Publish-DbaDacPackage`, which attempts to extract a "clean" instance name from the connection string. However, this results in the instance name containing the protocol name as well (for example `TCP:` or `NP:`).

https://github.com/sqlcollaborative/dbatools/blob/development/functions/Publish-DbaDacPackage.ps1#L263

Since this "clean" instance is being concatenated to the publish script file name, the OS is unable to create it, because its name contains a colon `:`, which is an illegal filename character.

A possible solution for this would be to add one more `.Replace` call in line 264, to replace any colons with something else:

https://github.com/sqlcollaborative/dbatools/blob/development/functions/Publish-DbaDacPackage.ps1#L264

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name  |                         Value                                                                                                                                                                 
----        |                   -----                                                                                                                                                                 
PSVersion     |                 5.1.19041.1023                                                                                                                                                        
PSEdition      |                Desktop                                                                                                                                                               
PSCompatibleVersions        |   {1.0, 2.0, 3.0, 4.0...}                                                                                                                                               
BuildVersion               |    10.0.19041.1023                                                                                                                                                       
CLRVersion                 |    4.0.30319.42000                                                                                                                                                       
WSManStackVersion   |           3.0                                                                                                                                                                   
PSRemotingProtocolVersion   |   2.3                                                                                                                                                                   
SerializationVersion         |  1.1.0.1                                                                                                                                                               

### SQL Server Edition and Build number

This is on my personal workstation, but the same symptoms were experienced with an Azure SQL Database as well:

```
Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64) 
	Nov  2 2020 18:35:09 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19043: )
```

**Comment by andreasjordan** [comment]
Thanks for the bug report. As $cleaninstance is used to build the filename, I changed that variable. $instance has to stay untouched, as it is later transfered back to a [DbaInstance].

**Comment by andreasjordan** [comment]
Ups, now I see that you also reported a problem in converting $instance back to [DbaInstance]. So the pull request will not solve that problem. Will see what I can do...

**Comment by andreasjordan** [comment]
Now I added a very dirty Replace to make it work. But the command should be completly rewritten - are you interested, @EitanBlumin ?
