### ISSUE TITLE
Invoke-PolicyEvaluation : Value cannot be null

### ISSUE THREAD

**Issue by github523321** [sqlcollaborative/dbatools#7710]
### Verified issue does not already exist?

Yes

### What error did you receive?

Invoke-PolicyEvaluation : Value cannot be null.

### Steps to Reproduce

# Doesn't work for dbatools policy:

$dbapolicies = Get-DbaPbmPolicy -SqlInstance $cmsServer -Category $cmsPolicyCategoryName  
$dbapolicy = $dbapolicies[0]
Invoke-PolicyEvaluation -Policy $dbapolicy -TargetServerName "dbserver.domain.com" -AdHocPolicyEvaluationMode Check

Name                           Category          Created                Enabled
----                           --------          -------                -------
DB_AutoClose                   RunAllPolicies    2/28/2019 11:24 AM     False  

Invoke-PolicyEvaluation : Value cannot be null.
Parameter name: policy
At line:1 char:1
+ Invoke-PolicyEvaluation -Policy $dbapolicy -TargetServerName "dbserver...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-PolicyEvaluation], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.SqlServer.Management.PowerShell.InvokePolicyEvaluationCommand

# Works with "GCI" policy:

Import-Module sqlps
$policies = Get-ChildItem -Path $cmsPolicyPath
$policy = $policies[0]
Invoke-PolicyEvaluation -Policy $policy -TargetServerName "dbserver.domain.com" -AdHocPolicyEvaluationMode Check

Name                           Category          Created                Enabled
----                           --------          -------                -------
DB_AutoClose                   RunAllPolicies    2/28/2019 11:24 AM     False  

   ID Policy Name                    Result Start Date         End Date           Messages              
   -- -----------                    ------ ----------         --------           --------              
    1 DB_AutoClose                   True   8/10/2021 12:22 PM 8/10/2021 12:22 PM       

### Are you running the latest release?

Yes

### Other details or mentions

This ticket was ignored when I created it earlier.

That didn't fix the problem!!!!!!!!!!!

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

yes

### SQL Server Edition and Build number

yes

**Comment by sanderstad** [comment]
Issue has nothing to do with dbatools. Closing it
