### ISSUE TITLE
Connect-DbaInstance returns a reference to a DLL which does not exist

### ISSUE THREAD

**Issue by kthurberNCI** [sqlcollaborative/dbatools#7712]
### Verified issue does not already exist?

Yes

### What error did you receive?

Error connecting to [localhost\SQLEXPRESS]: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x86.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Installed SQL Express with instance name localhost\SQLExpress
Created database IA within SSMS
Ran the following command
Install-Module dbatools

Tried to connect to a database as follows:
Connect-DbaInstance -SqlInstalce "localhost\SQLExpress" -Database "IA"

Received error indicated above running version 1.1.10
Version 1.0.145 seems to work fine.

Looked into it, and file Microsoft.Data.SqlClient.SNI.x86.dll is not present on the computer after install.  This file may have been left out inadvertently, or it may have been mistakenly referenced.  Should it have been Microsoft.Data.SqlClient.SNL.x64.dll?

### Are you running the latest release?

Yes

### Other details or mentions

The old version correctly connects to my database.

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.17763.1971                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.17763.1971                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Please try release 1.1.11 and let me know if that works for you

**Comment by kthurberNCI** [comment]
I am not running an x86 machine, but I'll try 1.1.11 now.  Thank you for checking this for me.

**Comment by kthurberNCI** [comment]
Release 1.1.11 does the trick.  Thank you!
