### ISSUE TITLE
Issue with Connect-DbaInstance

### ISSUE THREAD

**Issue by habibhammy** [sqlcollaborative/dbatools#7716]
### Verified issue does not already exist?

Yes

### What error did you receive?

Hi Dbatools,

We are facing recently a weird issue ( since the V1.1.0 release). Actually, the "Connect-DbaInstance" command is not working anymore unless we explicitly specify the FQDN of the servers. 

PS C:\> Connect-DbaInstance -SqlInstance server.domain.org

ComputerName Name                      Product              Version   HostPlatform IsAzure IsClustered ConnectedAs         
------------ ----                      -------              -------   ------------ ------- ----------- -----------         
server  server.domain.org Microsoft SQL Server 15.0.4138 Windows      False   False       DOMAIN\Account

PS C:\> Connect-DbaInstance -SqlInstance server
The target principal name is incorrect
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.0\allcommands.ps1:90200 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (server:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Connect-DbaInstance
 

### Steps to Reproduce

```powershell
PS C:\> Connect-DbaInstance -SqlInstance server.domain.org

ComputerName Name                      Product              Version   HostPlatform IsAzure IsClustered ConnectedAs         
------------ ----                      -------              -------   ------------ ------- ----------- -----------         
server  server.domain.org Microsoft SQL Server 15.0.4138 Windows      False   False       DOMAIN\Account

PS C:\> Connect-DbaInstance -SqlInstance server
The target principal name is incorrect
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.0\allcommands.ps1:90200 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (server:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Connect-DbaInstance
 
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                              
----                           -----                                                                                                                                              
PSVersion                      5.1.17763.1971                                                                                                                                     
PSEdition                      Desktop                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                            
BuildVersion                   10.0.17763.1971                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                                            

### SQL Server Edition and Build number

All versions from SQL 2000 to SQL 2019.

**Comment by potatoqualitee** [comment]
Hey @habibhammy - thanks for the report. This is expected behavior as Microsoft has made a change with default certificates. Please check out https://github.com/sqlcollaborative/dbatools/discussions/7680 for more information.

**Comment by habibhammy** [comment]
Hi @potatoqualitee , 
Thanks a lot for your answer. 
However, How can this also be the case for the servers were the SSL is not enabled and where no certificate was issued?

Many Thanks.

**Comment by potatoqualitee** [comment]
If it doesn't have a certificate, that's something that we'll have to explore. They may have made more strict changes to Kerberos as well. Can you let me know if `Test-DbaSpn` shows that Kerberos is setup properly? Can you also test with `Set-DbatoolsConfigValue -FullName 'sql.connection.trustcert' -Value $true` and let us know what happens when you change that value?

@andreasjordan can you think of anything that would cause this to happen?

**Comment by habibhammy** [comment]
Hi @potatoqualitee,

The Test-DbaSPN command on the server shows : 
~~~
  PS C:\> Test-DbaSpn
  cmdlet Test-DbaSpn at command pipeline position 1
  Supply values for the following parameters:
  ComputerName[0]: Server
  ComputerName[1]: 
  
  
  Cluster                : False
  ComputerName           : Server.Domain.org
  DynamicPort            : False
  Error                  : SPN missing
  InstanceName           : MSSQLSERVER
  InstanceServiceAccount : DOMAIN\Service_Account
  IsSet                  : False
  Port                   : 
  RequiredSPN            : MSSQLSvc/Server.Domain.org
  SqlProduct             : SQL Server 2014 Enterprise Edition (64-bit)
  TcpEnabled             : True
  Warning                : None
  
  Cluster                : False
  ComputerName           : Server.Domain.org
  DynamicPort            : False
  Error                  : None
  InstanceName           : MSSQLSERVER
  InstanceServiceAccount :  DOMAIN\Service_Account
  IsSet                  : True
  Port                   : 1433
  RequiredSPN            : MSSQLSvc/Server.Domain.org:1433
  SqlProduct             : SQL Server 2014 Enterprise Edition (64-bit)
  TcpEnabled             : True
  Warning                : None
~~~

For the second command I'm getting an error : 
~~~
PS C:\> Set-DbatoolsConfigValue -FullName 'sql.connection.trustcert' -Value $true
Set-DbatoolsConfigValue : The term 'Set-DbatoolsConfigValue' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Set-DbatoolsConfigValue -FullName 'sql.connection.trustcert' -Value $ ...
    + CategoryInfo          : ObjectNotFound: (Set-DbatoolsConfigValue:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
~~~
 Just for reference  I tried this with version V1.1.8
~~~
PS C:\> Get-InstalledModule

Version    Name                                Repository           Description                                                                                                   
-------    ----                                ----------           -----------                                                                                                   
1.1.8      dbatools                            https://www.power... The community module that enables SQL Server Pros to automate database development and server administration  
21.1.18256 SqlServer                           https://www.power... This module allows SQL Server developers, administrators and business intelligence professionals to automat...
~~~

**Comment by andreasjordan** [comment]
It's just `Set-DbatoolsConfig`.

**Comment by habibhammy** [comment]
Hi @andreasjordan , @potatoqualitee ,

Indeed after running the command to disable the trust certificate, the connect command restart working.
~~~
PS C:\> Set-DbatoolsConfig -FullName 'sql.connection.trustcert' -Value $true

PS C:\> Connect-DbaInstance -SqlInstance 'Server'

ComputerName   Name           Product              Version   HostPlatform IsAzure IsClustered ConnectedAs         
------------   ----           -------              -------   ------------ ------- ----------- -----------         
Server Server Microsoft SQL Server 14.0.3401 Windows      False   False       DOMAIN\account
~~~
