### ISSUE TITLE
Export-DBAUser does not contain permissions granted to a user created database role

### ISSUE THREAD

**Issue by jeffrey-yao** [sqlcollaborative/dbatools#7722]
### Verified issue does not already exist?

No

### What error did you receive?

No error shown, but the permission grant/deny t-sql is not generated.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
To replicate the issue, we assume our localhost has a sql server default instance (any version above 2012 will do) 
use TempDB
create role Test_role;
create table dbo.t (id int);
grant select, delete to object::dbo.t to [Test_role];

Now we can do the PowerShell part

import-module dbatools
$svr = 'localhost';
$pth = 'c:\temp\permission.sql';

export-dbauser -server $svr -database tempdb -filepath $pth;

After you open $pth in notepad, you will only find the following t-sql for Test_role

USE [tempdb]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'Test_role' AND type = 'R')
CREATE ROLE [Test_role]
GO

But there is no such t-sql

grant select, delete to object::dbo.t to [Test_role];

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                    
----                           -----                                                                                                                                                                    
PSVersion                      5.1.17763.1971                                                                                                                                                           
PSEdition                      Desktop                                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                  
BuildVersion                   10.0.17763.1971                                                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                                      
SerializationVersion           1.1.0.1      

### SQL Server Edition and Build number

sql server 2012 to sql server 2019 all tested

**Comment by andreasjordan** [comment]
I think this is by design. Only directly granted permissions are exported.
To export the permissions granted to a database role, we have `Export-DbaDbRole`.

@potatoqualitee please reopen if I'm wrong.
