### ISSUE TITLE
Invoke-DbaQuery SqlCredential param with windows credential not honored

### ISSUE THREAD

**Issue by paschott** [sqlcollaborative/dbatools#7725]
### Verified issue does not already exist?

Yes

### What error did you receive?

No error, but when I used a query of "SELECT SUSER_SNAME()" I got my current creds instead of the ones I'd passed in.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
$cred = get-credential #to get alternate creds
Invoke-DbaQuery -SqlInstance servername -Query "SELECT SUSER_SNAME()" -SqlCredential $cred

# This returns my currently logged in user.

Connect-DbaInstance -SqlInstance servername -SqlCredential $cred
# This returns my credentials as expected

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

7.1.4

### SQL Server Edition and Build number

Irrelevant, but was going against a SQL 2014 server with the latest CU.

**Comment by paschott** [comment]
Tested w/ v1.0.104 on PS v5.1 and the command worked as expected.

Tested w/ v 1.0.173 on PS 7.1.4 - command returned current creds instead of my passed in credentials.
Tried with v 1.1.2 on PS v5.1 in a new session and the command returned my current credentials instead of the credentials passed in.

**Comment by wsmelton** [comment]
#7514

**Comment by andreasjordan** [comment]
I can confirm for PS 7.1.4 and the current dev branch:
![image](https://user-images.githubusercontent.com/66946165/129674868-ac8abacf-0e5b-4b7a-bb6b-3eb95b5e0bab.png)

**Comment by andreasjordan** [comment]
Same with 5.1:
![image](https://user-images.githubusercontent.com/66946165/129675230-a5838100-abe3-4abf-b77b-9fccf7a94264.png)

**Comment by andreasjordan** [comment]
This seems to be another SMO issue:
```
$winCred = Get-Credential -Message WindowsLogin -UserName COMPANY\SQLServer
$server = Connect-DbaInstance -SqlInstance srv1 -SqlCredential $winCred
$server.ConnectionContext.ExecuteScalar("SELECT SUSER_SNAME()")
$server.ConnectionContext.Copy().ExecuteScalar("SELECT SUSER_SNAME()")
$server.ConnectionContext.Copy().GetDatabaseConnection('tempdb').ExecuteScalar("SELECT SUSER_SNAME()")
```
![image](https://user-images.githubusercontent.com/66946165/129676377-8146b8c0-cfee-4244-a46e-2fd46d65f506.png)

So `.GetDatabaseConnection('tempdb')` switches the context back:
https://github.com/sqlcollaborative/dbatools/blob/2e7d71fe1fcab3eb73e3c2da34f57d9c254b5694/functions/Invoke-DbaQuery.ps1#L356

**Comment by andreasjordan** [comment]
Root cause might be here:
https://github.com/sqlcollaborative/dbatools/blob/2e7d71fe1fcab3eb73e3c2da34f57d9c254b5694/internal/functions/Invoke-DbaAsync.ps1#L168

Only the ConnectionContext is aware of the different windows credential it uses, the SqlConnectionObject is not as it only has a ConnectionString with "Integrated Security=True".

I just don't know why it worked in v1.0.104...

**Comment by andreasjordan** [comment]
Oh, connection pooling causes the issue. It works with a nonpooled connection:

```
$winCred = Get-Credential -Message WindowsLogin -UserName COMPANY\SQLServer
$serverPooled = Connect-DbaInstance -SqlInstance srv1 -SqlCredential $winCred
$serverNonPooled = Connect-DbaInstance -SqlInstance srv1 -SqlCredential $winCred -NonPooledConnection
Invoke-DbaQuery -SqlInstance $serverPooled -Query "SELECT SUSER_SNAME()" -As SingleValue
Invoke-DbaQuery -SqlInstance $serverNonPooled -Query "SELECT SUSER_SNAME()" -As SingleValue
```
![image](https://user-images.githubusercontent.com/66946165/129679537-a10d9f87-6186-4c13-8b46-71864003428b.png)

**Comment by andreasjordan** [comment]
Maybe we should always force a non pooled connection when using a windows credential in Connect-DbaInstance?
Or have a config parameter for that switch in Connect-DbaInstance to set non pooled connections globally?
I don't see the point in connection pooling with our dbatools commands anyway. Where is the big benefit?

@potatoqualitee - What do you think?

**Comment by potatoqualitee** [comment]
Thanks for looking into this, Andreas. @jpomfret and @awickham10 were big into the connection pooling part and will have more insight

**Comment by wsmelton** [comment]
Connection pooling benefits that it reuse the connection to the same instance from the same machine.

Azure SQL this is very important because you exhaust the allowed resources for connections very easily if you don't.

The more connections an application causes the more resources from SQL that are consumed.

**Comment by andreasjordan** [comment]
Ok, sounds valid.
So only force non pooled connection in Invoke-DbaQuery when using windows credentials?

**Comment by wsmelton** [comment]
By default? I would say no.

If folks want to use PowerShell 7+ with this command for a different Windows Credential, just make a connection first and pass that to the Invoke command. Technically that is how it has always worked previously.

**Comment by andreasjordan** [comment]
The problem is NOT related to PS7 only, it is also a problem with PS5.1 - I have tested that.

**Comment by wsmelton** [comment]
I'm not aware of all the changes that have been made to the connect command. It worked previously in PS5.1 with no issues at all so the changes need to be evaluated to what was modified; unless this is an issue directly with SqlClient that we are using now.

**Comment by andreasjordan** [comment]
Ok, tested with the legacy code path - and there are no problems. So I will have a closer look.

**Comment by andreasjordan** [comment]
I think I have found the root cause: In the old code path, we do an explicit `$server.ConnectionContext.Connect()`. This changed `$server.ConnectionContext.SqlConnectionObject.State` from `Closed` to `Open`. So the `SqlConnectionObject` is connected and Invoke-DbaQuery has no problems.

But I will have to see what the downsides are. Give me some hours...

**Comment by andreasjordan** [comment]
Oh, I've written about that in the code:
https://github.com/sqlcollaborative/dbatools/blob/2e7d71fe1fcab3eb73e3c2da34f57d9c254b5694/functions/Connect-DbaInstance.ps1#L936-L953

So we can not add `$server.ConnectionContext.Connect()` back in or we loose connection pooling. So I think we need to have a non pooled connection just for the cases where the command uses the `SqlConnectionObject`, as Invoke-DbaQuery does.

But we can talk about testing for a windows credential and only have a non pooled connection in that case. Or we can see if we can rewrite Invoke-DbaQuery to not work with the `SqlConnectionObject` - but that would take some time.
