### ISSUE TITLE
Set-DbaAgentOperator when changing email at least changes all the operators not just the one specify

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbatools#7730]
### Verified issue does not already exist?

No

### What error did you receive?

N/A

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Will change every operator, when I wrote this I only had one operator, so didn't text for multiple operators.
$server = "SQL01"
$OperatorName = "DBA"
$EmailAddress = "mail@mail.com"

Set-DbaAgentOperator -SQLInstance $server -Operator $operatorName -EmailAddress $EmailAddress

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

VS Code (terminal), VS Code (integrated terminal)

### PowerShell Host Version

![image](https://user-images.githubusercontent.com/26776763/129967480-73a6092a-60bc-474b-9731-6002081071c2.png)

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-CU17) (KB5001092) - 13.0.5888.11 (X64)   Mar 19 2021 19:41:38   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: )

**Comment by andreasjordan** [comment]
So you will provide a fix for that? Then it would help if you assign yourself and remove the "triage required" tag to let others know that.

**Comment by tboggiano** [comment]
Yes I will provide a fix, I'll work on over the next couple of days, maybe tonight. let figure out how to edit labels.

**Comment by andreasjordan** [comment]
No problem, have done that for you.
