### ISSUE TITLE
Allow setting read-only routing list through Set-DbaAgReplica

### ISSUE THREAD

**Issue by ben-thul** [sqlcollaborative/dbatools#7732]
### Summarize Functionality

Looking through the list of options in [the docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-availability-group-transact-sql?view=sql-server-ver15), and comparing it with the list of options for Set-DbaAgReplica, the only one missing seems to be READ_ONLY_ROUTING_LIST.

I'd like to add a new parameter (`ReadOnlyRoutingList`?) that would allow this to be set.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

The AvailabilityReplica SMO object has a `SetLoadBalancedReadOnlyRoutingList()` method that allows this to be set. As the name of the method implies, it also allows for the setting of a load balanced read-only routing list (introduced in SQL 2016).

The method takes as a parameter a `[List[IList[string]]]`, which isn't the most straightforward thing to create. I have code working locally that will allow an array of arrays to be used as the parameter value. Something like this:

```
$r | Set-DbaAgReplica -ReadOnlyRoutingList ('foo', 'bar'), 'baz';
```

which would be equivalent to:

```
alter availability group myAG
   modify replica baz (
      primary_role (
         read_only_routing_list = (('foo', 'bar'), 'baz')
      )
   );
```

**Comment by andreasjordan** [comment]
If you say "I have code working locally", can you provide the code or open a pull request to change the command?

**Comment by ben-thul** [comment]
I can. I've had a bad experience here opening a PR w/o first having a discussion in an Issue that results in "I approve this conceptually". Was trying to avoid that this time around.

**Comment by ben-thul** [comment]
@andreasjordan - I've logged a draft PR and linked this with that.

**Comment by potatoqualitee** [comment]
I'll be updating this, and testing the code as well. I've removed the second example, as I don't see the difference between the two. If there is a functional difference, please let me know and we can add it back.

**Comment by ben-thul** [comment]
> I'll be updating this, and testing the code as well. I've removed the second example, as I don't see the difference between the two. If there is a functional difference, please let me know and we can add it back.

The examples are subtly different. One creates a routing list with two elements, the second creates a routing list with one element (which itself has two elements). The difference in behavior between the two from an AG standpoint is that in the first example, all r/o requests will go to the first replica in the list if it's available. If it's not, they'll go to the second replica. In the second example, requests will be routed to the two replicas in a round robin fashion.

**Comment by potatoqualitee** [comment]
interesting! please feel free to add it back with that explanation in the example text
