### ISSUE TITLE
Get External Resources Definitions from Synapse SQL Serverless 

### ISSUE THREAD

**Issue by immsgbb** [sqlcollaborative/dbatools#7736]
### Verified issue does not already exist?

Yes

### What error did you receive?

 I am trying to get the Data Source and File Format Definitions from synapse serverless with dbatools. But i am getting this error (Please check screenshot) and i have no clue for it. I couldn't find any example for this from documentation.

I don't know if there is another command for getting the DATA_SOURCE and FILE_FORMAT Definitions. I am using dba script command but the only option i can think of getting it is through WithDependencies

![image](https://user-images.githubusercontent.com/78602306/130441031-3a03d9b6-b599-4241-b2c3-6a781379d607.png)

Here is the error message with -verbose and -debug option.

VERBOSE: [13:21:44][Export-DbaScript] Exporting [dbo].[call_center_tpcds]
DEBUG: [13:21:44][Export-DbaScript] Exporting [dbo].[call_center_tpcds]
An exception occurred while executing a Transact-SQL statement.
![dbatools-Issue](https://user-images.githubusercontent.com/78602306/130441357-5b754381-e84f-4e10-b2ae-37a130659b20.png)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
 $options = New-DbaScriptingOption
 $options.WithDependencies = $true
 $script = Get-DbaDbTable -SqlInstance "$synapseSqlName.database.windows.net" -Database "stg" -SqlCredential $login | Export-DbaScript -ScriptingOptionsObject $options -Passthru | Out-String

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Azure (RTM) - 12.0.2000.8   Jul 22 2021 15:37:44   Copyright (C) 2019 Microsoft Corporation

**Comment by wsmelton** [comment]
I would not really expect this to function for Azure Synapse service.

**Comment by mattcargile** [comment]
Does `(Get-DbaDbTable -SqlInstance "$synapseSqlName.database.windows.net" -Database "stg" -SqlCredential $login).Script()` work?

**Comment by immsgbb** [comment]
@mattcargile Yes it works but it is still giving me only external table definitions and not giving me Data Sources and Files Formats.

**Comment by mattcargile** [comment]
> @mattcargile Yes it works but it is still giving me only external table definitions and not giving me Data Sources and Files Formats.

What about the method `EnumScript` or passing in `ScriptingOptions` directly into the `Script` method?

**Comment by wsmelton** [comment]
The script method, no matter how you use it, does not know about Azure-specific properties on the objects such as file formats and the data source. Those don't exist in SMO.

**Comment by immsgbb** [comment]
But according to this documentation these objects are available as SMO.

Microsoft.SqlServer.Management.Smo Namespace | Microsoft Docs<https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo?view=sql-smo-160>

**Comment by immsgbb** [comment]
@mattcargile both script and EnumScript functions are failing. Do we have documentation of these functions somewhere ?

**Comment by mattcargile** [comment]
I only looked at Microsoft docs and Get-Member output. Not much there. 

I guess you could attempt to reverse engineer SSMS to see how that app generates the code.

**Comment by potatoqualitee** [comment]
hey @immsgbb - that is indeed out of scope for us, as none of us are familiar with Syntapse and SMO appears to be causing that error.

I'd suggest asking over at https://github.com/microsoft/sqlmanagementobjects then letting us know here how we can help. They find it most useful when you build script using pure SMO and PowerShell (not referencing dbatools directly)
