### ISSUE TITLE
TrustServerCertificate for all cmdlets that check TLS certificate

### ISSUE THREAD

**Issue by steixeira-stan** [sqlcollaborative/dbatools#7738]
### Summarize Functionality

The Connect-DbaInstance cmdlet has a TrustServerCertificate parameter.  However, other cmdlets do not.  An example is Find-DbaInstance.  Executing this cmdlet against a server when the client using the dbatools module doesn't have the certificate results in a trusted certificate error.  While it's best practice to have that certificate and trust it, that is not always possible.

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by steixeira-stan** [comment]
Actually, it may have been the Get-DbaInstanceProperty cmdlet I ran into this issue on, but any cmdlet that explicitly connects to an instance would ideally have a TrustServerCertificate parameter/option.

**Comment by potatoqualitee** [comment]
Hey @steixeira-stan, this can be set globally using `Set-DbatoolsConfig`

`Set-DbatoolsConfig -FullName sql.connection.trustcert -Value $true -Register`
