### ISSUE TITLE
Import issue after upgrading to v.1.1.14

### ISSUE THREAD

**Issue by lowlydba** [sqlcollaborative/dbatools#7754]
### Verified issue does not already exist?

No

### What error did you receive?

```powershell
VERBOSE: Loading module from path '/Users/lowlydba/.local/share/powershell/Modules/dbatools/1.1.14/dbatools.psd1'.
VERBOSE: Loading 'TypesToProcess' from path '/Users/lowlydba/.local/share/powershell/Modules/dbatools/1.1.14/xml/dbatools.Types.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path '/Users/lowlydba/.local/share/powershell/Modules/dbatools/1.1.14/xml/dbatools.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module dbatools.
VERBOSE: Loading module from path '/Users/lowlydba/.local/share/powershell/Modules/dbatools/1.1.14/dbatools.psm1'.
Resolve-Path: /Users/lowlydba/.local/share/powershell/Modules/dbatools/1.1.14/bin/library.ps1:82:39
Line |
  82 |                      $script:DllRoot = Resolve-Path -Path bin
     |                                        ~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path '/Users/lowlydba/code/xxx/bin' because it does not exist.

Import-Module: Cannot bind argument to parameter 'Path' because it is null.
```

Similar issue (secondary problem) as in #7528

### Steps to Reproduce

After downloading v 1.1.14

```powershell
Import-Module dbatools -Force
```

### Are you running the latest release?

Yes

### Other details or mentions

Importing worked as of version 1.0.156

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

N/A

**Comment by potatoqualitee** [comment]
Thanks for the report! Fixing now
