### ISSUE TITLE
New-DbaAvailabilityGroup no longer works as expected

### ISSUE THREAD

**Issue by ekholve** [sqlcollaborative/dbatools#7775]
### Verified issue does not already exist?

Yes

### What error did you receive?

If initial backup is not taken prior to New-DbaAvailabilityGroup command:

_WARNING: [16.24.25][New-DbaAvailabilityGroup] Failed to add databases to Availability Group. | Error connecting to [CLUS01N02\INS01]: All replicas are configured to use automatic seeding, but the
 database [MasterBAG] was never backed up. Please backup the database or use manual seeding._

This matter can be easily worked around with Backup-DbaDatabase in the script but should not be needed according to command document:

_Performs backup to NUL if seeding mode is automatic_

When initial backup was taken and New-DbaAvailabilityGroup command used again then there seems to be a problem with grant create any database.

Not sure if below will ever stop to finally give an error output?
_VERBOSE: [16.33.12][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized.
VERBOSE: [16.33.12][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized._

### Steps to Reproduce

#Variables as follows:
$Primary = "CLUS01N01\INS01"
$Secondary = "CLUS01N02\INS01"
$AgName = "INS01_MasterBAG"
$DbName = "MasterBAG"

-------------------------------------------------------
**dbatools: 1.1.15 when no prior initial backup from MasterBag**

PS C:\Windows\system32> New-DbaAvailabilityGroup -Primary $Primary -Secondary $Secondary -Name $AgName -Database $DbName -SeedingMode Automatic -Basic -Confirm:$false -ClusterType wsfc -Verbose

_VERBOSE: [16.24.22][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.24.22][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [16.24.22][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.22][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.24.22][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [16.24.22][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.22][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.24.22][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [16.24.23][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.24.23][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: Performing the operation "Setting up availability group named INS01_MasterBAG and adding primary replica" on target "CLUS01N01\INS01".
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Get-DbaEndpoint] Getting endpoint hadr_endpoint on CLUS01N01\INS01
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Get-DbaLogin] Getting last login times
VERBOSE: [16.24.23][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N01\INS01
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Get-DbaLogin] Getting last login times
VERBOSE: [16.24.23][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N01\INS01
VERBOSE: Performing the operation "Adding cluster permissions for availability group named INS01_MasterBAG" on target "CLUS01N01\INS01".
VERBOSE: [16.24.23][New-DbaAvailabilityGroup] WSFC Cluster requires granting [NT AUTHORITY\SYSTEM] a few things. Setting now.
VERBOSE: Performing the operation "Adding replica to availability group named INS01_MasterBAG" on target "CLUS01N02\INS01".
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Get-DbaEndpoint] Getting endpoint hadr_endpoint on CLUS01N02\INS01
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Get-DbaLogin] Getting last login times
VERBOSE: [16.24.23][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N02\INS01
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.23][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.24][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.24][Get-DbaLogin] Getting last login times
VERBOSE: [16.24.24][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N02\INS01
VERBOSE: Performing the operation "New-DbaAvailabilityGroup" on target "Joining CLUS01N02\INS01 to INS01_MasterBAG".
VERBOSE: [16.24.24][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: Performing the operation "Seeding mode is automatic. Adding CreateAnyDatabase permissions to availability group." on target "CLUS01N01\INS01".
VERBOSE: Performing the operation "Adding databases to Availability Group." on target "CLUS01N01\INS01".
VERBOSE: [16.24.24][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.24][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.25][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.25][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.24.25][Test-DbaAvailabilityGroup] Database [MasterBAG] will use automatic seeding on replica CLUS01N02\INS01. The replica is already configured accordingly.
VERBOSE: [16.24.25][Test-DbaAvailabilityGroup] Database [MasterBAG] will need a backup first. This is ok if one of the other replicas uses manual seeding.
WARNING: [16.24.25][New-DbaAvailabilityGroup] Failed to add databases to Availability Group. | Error connecting to [CLUS01N02\INS01]: All replicas are configured to use automatic seeding, but the
 database [MasterBAG] was never backed up. Please backup the database or use manual seeding.
VERBOSE: [16.24.25][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.24.25][Connect-DbaInstance] authentication method is 'local integrated'_

-------------------------------------------------------
**dbatools: 1.1.15 with initial backup from MasterBag using Backup-DbaDatabase -SqlInstance $Primary -Database $DbName -FilePath NUL first**

PS C:\Windows\system32> New-DbaAvailabilityGroup -Primary $Primary -Secondary $Secondary -Name $AgName -Database $DbName -SeedingMode Automatic -Basic -Confirm:$false -ClusterType wsfc -Verbose

_VERBOSE: [16.33.10][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.33.10][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.33.10][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.33.10][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [16.33.10][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [16.33.10][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: Performing the operation "Setting up availability group named INS01_MasterBAG and adding primary replica" on target "CLUS01N01\INS01".
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Get-DbaEndpoint] Getting endpoint hadr_endpoint on CLUS01N01\INS01
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Get-DbaLogin] Getting last login times
VERBOSE: [16.33.10][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N01\INS01
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.10][Get-DbaLogin] Getting last login times
VERBOSE: [16.33.10][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N01\INS01
VERBOSE: Performing the operation "Adding cluster permissions for availability group named INS01_MasterBAG" on target "CLUS01N01\INS01".
VERBOSE: [16.33.10][New-DbaAvailabilityGroup] WSFC Cluster requires granting [NT AUTHORITY\SYSTEM] a few things. Setting now.
VERBOSE: Performing the operation "Adding replica to availability group named INS01_MasterBAG" on target "CLUS01N02\INS01".
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.11][Get-DbaEndpoint] Getting endpoint hadr_endpoint on CLUS01N02\INS01
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.11][Get-DbaLogin] Getting last login times
VERBOSE: [16.33.11][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N02\INS01
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.11][Get-DbaLogin] Getting last login times
VERBOSE: [16.33.11][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N02\INS01
VERBOSE: Performing the operation "New-DbaAvailabilityGroup" on target "Joining CLUS01N02\INS01 to INS01_MasterBAG".
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: Performing the operation "Seeding mode is automatic. Adding CreateAnyDatabase permissions to availability group." on target "CLUS01N01\INS01".
VERBOSE: Performing the operation "Adding databases to Availability Group." on target "CLUS01N01\INS01".
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.11][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.12][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.12][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.12][Test-DbaAvailabilityGroup] Database [MasterBAG] will use automatic seeding on replica CLUS01N02\INS01. The replica is already configured accordingly.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Test for prerequisites returned 1 databases that will be joined to the Availability Group INS01_MasterBAG.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Step 1/5: Setting seeding mode if needed.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Setting seeding mode to Automatic.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Step 2/5: Running backup and restore if needed.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Step 3/5: Add the database to the Availability Group on the primary replica.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Object of type AvailabilityDatabase for MasterBAG will be created. State of AvailabilityDatabase for MasterBAG on is not yet known.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Object of type AvailabilityDatabase for MasterBAG is created. State of AvailabilityDatabase for MasterBAG is Creating.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Method Create of AvailabilityDatabase for MasterBAG is executed. State of AvailabilityDatabase for MasterBAG is Existing.
VERBOSE: [16.33.12][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.12][Add-DbaAgDatabase] Step 4/5: Add the database to the Availability Group on the secondary replicas.
VERBOSE: [16.33.12][Add-DbaAgDatabase] State of AvailabilityDatabase for MasterBAG on replica CLUS01N02\INS01 is not yet known.
VERBOSE: [16.33.12][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [16.33.12][Add-DbaAgDatabase] State of AvailabilityDatabase for MasterBAG on replica CLUS01N02\INS01 is Existing.
VERBOSE: [16.33.12][Add-DbaAgDatabase] Step 5/5: Wait for the database to finish joining the Availability Group on the secondary replicas.
VERBOSE: [16.33.12][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized.
VERBOSE: [16.33.12][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized.
VERBOSE: [16.33.13][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized.
VERBOSE: [16.33.13][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized._

Endlessly?

-----------------------------------------------------------
**Finally for the reference: dbatools 1.0.140 works without problems**

PS C:\Windows\system32> New-DbaAvailabilityGroup -Primary $Primary -Secondary $Secondary -Name $AgName -Database $DbName -SeedingMode Automatic -Basic -Confirm:$false -ClusterType wsfc -Verbose

VERBOSE: Performing the operation "Setting up availability group named INS01_MasterBAG and adding primary replica" on target "CLUS01N01\INS01".
VERBOSE: [16.06.31][Get-DbaEndpoint] Getting endpoint hadr_endpoint on CLUS01N01\INS01
VERBOSE: [16.06.31][Get-DbaLogin] Getting last login times
VERBOSE: [16.06.31][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N01\INS01
VERBOSE: [16.06.31][Get-DbaLogin] Getting last login times
VERBOSE: [16.06.31][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N01\INS01
VERBOSE: Performing the operation "Adding cluster permissions for availability group named INS01_MasterBAG" on target "CLUS01N01\INS01".
VERBOSE: [16.06.31][New-DbaAvailabilityGroup] WSFC Cluster requires granting [NT AUTHORITY\SYSTEM] a few things. Setting now.
VERBOSE: Performing the operation "Adding replica to availability group named INS01_MasterBAG" on target "CLUS01N02\INS01".
VERBOSE: [16.06.31][Get-DbaEndpoint] Getting endpoint hadr_endpoint on CLUS01N02\INS01
VERBOSE: [16.06.31][Get-DbaLogin] Getting last login times
VERBOSE: [16.06.31][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N02\INS01
VERBOSE: [16.06.31][Get-DbaLogin] Getting last login times
VERBOSE: [16.06.31][Get-DbaLogin] Processing [DOMAIN\SVC_CLUS01_INS01] on CLUS01N02\INS01
VERBOSE: Performing the operation "New-DbaAvailabilityGroup" on target "Joining CLUS01N02\INS01 to INS01_MasterBAG".
VERBOSE: Performing the operation "Seeding mode is automatic. Adding CreateAnyDatabase permissions to availability group." on target "CLUS01N01\INS01".
VERBOSE: Performing the operation "Seeding mode is automatic. Adding CreateAnyDatabase permissions to availability group." on target "CLUS01N02\INS01".
VERBOSE: [16.06.32][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [16.06.32][Backup-DbaDatabase] 1 database to backup
VERBOSE: [16.06.32][Backup-DbaDatabase] Backup database [MasterBAG]
VERBOSE: [16.06.32][Backup-DbaDatabase] Creating full backup
VERBOSE: [16.06.32][Backup-DbaDatabase] Building file name
VERBOSE: [16.06.32][Backup-DbaDatabase] Building backup path
VERBOSE: [16.06.32][Backup-DbaDatabase] Devices added
VERBOSE: [16.06.33][Get-DbaDbBackupHistory] Processing MasterBAG
VERBOSE: [16.06.33][Get-DbaDbBackupHistory] Executing sql query on [CLUS01N01\INS01].
VERBOSE: [16.06.33][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [16.06.33][Get-DbaDbBackupHistory] 1 result-groups found.

ComputerName               : CLUS01N01
InstanceName               : INS01
SqlInstance                : CLUS01N01\INS01
LocalReplicaRole           : Primary
AvailabilityGroup          : INS01_MasterBAG
PrimaryReplica             : CLUS01N01\INS01
ClusterType                : Wsfc
DtcSupportEnabled          : False
AutomatedBackupPreference  : Primary
AvailabilityReplicas       : {CLUS01N01\INS01, CLUS01N02\INS01}
AvailabilityDatabases      : {MasterBAG}
AvailabilityGroupListeners : {}

### Are you running the latest release?

Yes

### Other details or mentions

If I stop the execution and run below query in SQL Server Management Studio, the Automatic Seeding kicks in and database is created and synchronized.

ALTER AVAILABILITY GROUP [INS01_MasterBAG]
    GRANT CREATE ANY DATABASE
GO

Discussion thread about the matter:
https://sqlcommunity.slack.com/archives/C1M2WEASG/p1631533476261500

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.2090                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.2090                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU10) (KB5001090) - 15.0.4123.1 (X64)   Mar 22 2021 18:10:24   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by andreasjordan** [comment]
Thanks for reporting this. I'm just about to setup the lab for this and will come back to you soon.

"Performs backup to NUL if seeding mode is automatic" is a leftover in the documentation, I will remove or rephrase this.

**Comment by andreasjordan** [comment]
Ok, found the bug and have a fix. Will open a pull request shortly.

**Comment by ekholve** [comment]
Excellent! Thanks a lot for your help on this matter.

**Comment by ReeceGoding** [comment]
@andreasjordan  Does the documentation for `-SeedingMode` also need updating? Nothing in there stresses that `SeedingMode = "Automatic"` will fail if the database has never been backed up. If anything, the "_This method does not require you to backup and restore a copy of the primary database on the replica_" part softly suggests that you don't need a backup.

**Comment by andreasjordan** [comment]
Thanks for pinging me - will look at this in the next week. If I don't respond in 7 days - ping me again!

**Comment by ReeceGoding** [comment]
#9786 is hopefully unrelated.
