### ISSUE TITLE
Sync-DbaLoginPermission fails on instances with read-only databases at destination

### ISSUE THREAD

**Issue by scottrcaldwell** [sqlcollaborative/dbatools#7788]
### Verified issue does not already exist?

Yes

### What error did you receive?

PSMessageDetails      :
Exception             : System.Exception: Failed to update database "DatabaseName" because the database is read-only. ---> Microsoft.Data.SqlClient.SqlException: Failed to update database "DatabaseName" because the
                        database is read-only.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
                           --- End of inner exception stack trace ---
TargetObject          : BI_ETL
CategoryInfo          : NotSpecified: (BI_ETL:String) [], Exception
FullyQualifiedErrorId : dbatools_Sync-DbaLoginPermission
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.15\internal\functions\flowcontrol\Stop-Function.ps1: line 252
                        at Sync-DbaLoginPermission<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.15\functions\Sync-DbaLoginPermission.ps1: line 152
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

### Steps to Reproduce

Execute the following command. In this case, the source instance and destination instance have identical databases where some databases are read-write and some are read-only. The destination instance is used for DR.

Sync-DbaLoginPermission -Source SourceInstance -Destination DestinationInstance

### Are you running the latest release?

Yes

### Other details or mentions

This error does not occur in 1.0.137

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.14393.4583
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.4583
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-CU17) (KB5001092) - 13.0.5888.11 (X64)   Mar 19 2021 19:41:38   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: )

**Comment by andreasjordan** [comment]
I have testet with version 1.0.137 and get errors with that version as well, if I have read-only databases.
But I don't know what your expectations are. I can not change permissions on a read only database, so the destination database must not be read-only.
Maybe it helps if you run the command with `-Verbose` and provide the output. This way I can see which step fails, because `Sync-DbaLoginPermission` uses the internal command `Update-SqlPermission` which has a lot of steps.

**Comment by andreasjordan** [comment]
Hi @scottrcaldwell - I will close this for now, but we can reopen if you still want to work on this.
