### ISSUE TITLE
Unable to import module in local azure function session

### ISSUE THREAD

**Issue by Szeraax** [sqlcollaborative/dbatools#7790]
### Verified issue does not already exist?

Yes

### What error did you receive?

ERROR: Could not import C:\Users\...\AppData\Local\AzureFunctions\AzureFunction\ManagedDependencies\210918024623427.r\dbatools\1.1.18\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll :
MethodInvocationException: C:\Users\...\AppData\Local\AzureFunctions\AzureFunction\ManagedDependencies\210918024623427.r\dbatools\1.1.18\internal\scripts\libraryimport.ps1:140
Line 140 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)
|                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Exception calling "LoadFrom" with "1" argument(s): "An attempt was made to load a program with an incorrect format. (0x8007000B)"

### Steps to Reproduce

Set managed dependency in requirements.psd1 to include: `dbatools = '1.*'`

Set run.ps1 in your function to `Import-module dbatools`

start the host, execute the function.

### Are you running the latest release?

Yes

### Other details or mentions

Using pwsh 7.1.4 on win10 x64. 

have not testing deploying to azure and running there. Have not tested skipping the managed dependancy and using function module loading.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

AzureSql is what I'll connect to when I get to that phase...

**Comment by Szeraax** [comment]
I've now tested it in the azurefunction\Modules\dbatools folder instead of managed dependency and it also fails to import the module.

**Comment by Szeraax** [comment]
Removing this line from the file allows the module to import: https://github.com/sqlcollaborative/dbatools/blob/development/internal/scripts/libraryimport.ps1#L60 under managed dep and Modules folder for the azure functions host.

**Comment by wsmelton** [comment]
That library is required for the XE functions to operate.

What Azure Functions runtime are you using for your deployment?

**Comment by Szeraax** [comment]
Local.settings.json:

"FUNCTIONS_EXTENSION_VERSION": "~3",

**Comment by potatoqualitee** [comment]
is there an environmental variable or something that i can check to avoid that import on azure functions? like shawn mentioned, there will be loss of functionality for XE commands

**Comment by wsmelton** [comment]
@Szeraax I'm assuming you are trying to run this locally or is this function already deployed to the worker instance?

Can you provide your `local.setting.json` so we can try and replicate it?

**Comment by Szeraax** [comment]
I've been unable to reproduce this issue in my homelab compared to my work
computer, which uses lots of stuff like software restriction policies. Even
using the default local.settings.json doesn't work in my work environment
under a new project. I'm going to close this issue and will re-open if I am
able to reproduce locally. Thank you all!
