### ISSUE TITLE
Stop-DbaService (Get-DbaService) Silent parameter

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#7810]
### Verified issue does not already exist?

Yes

### What error did you receive?

\Modules\dbatools\1.1.21\allcommands.ps1:74955
 Line |
74955 |              $InputObject = Get-DbaService @serviceParams
      |                                            ~~~~~~~~~~~~~~
      | A parameter cannot be found that matches parameter name 'Silent'.
VERBOSE: Performing the operation "Stopping Service" on target "".

ObjectNotFound: \Modules\dbatools\1.1.21\allcommands.ps1:91756
 Line |
91756 |          throw $records[0]
      |          ~~~~~~~~~~~~~~~~~
      | No SQL Server services found with current parameters.

### Steps to Reproduce

```powershell
Stop-DbaService -InstanceName $server -Type Agent -Verbose EnableException
```

### Are you running the latest release?

Yes

### Other details or mentions

@niphlod mentioned in Slack that `stop-dbaservice code is wrong when enableexception is passed`

also:

https://github.com/sqlcollaborative/dbatools/blob/master/functions/Stop-DbaService.ps1#L108

https://github.com/sqlcollaborative/dbatools/blob/master/functions/Get-DbaService.ps1#L217

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64) 
	Jul 19 2021 15:37:34 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Thanks @wsuhoey ! @nvarscar can you take a look at this as well? Man, `Silent`, what a throwback!

**Comment by potatoqualitee** [comment]
i found the issue, will submit a fix
