### ISSUE TITLE
Get-DbaConfig questions

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#782]
﻿### Is this a *feature* OR *bug*:

feature

### System Details

Can we make the temp path [System.IO.Path]::GetTempPath() instead of $env:temp? It's more reliable (Remove-Item fails with $env:temp, ridiculous)

Also, where is this stored? If it's in the dbatools dir itself, that'd be an issue for my crappy install.ps1 (umm i guess that needs a rewrite too)

**Comment by FriedrichWeinmann** [comment]
Updated and done
