### ISSUE TITLE
Add-DbaAgDatabase Method Invocation Failure

### ISSUE THREAD

**Issue by bwiggins10** [sqlcollaborative/dbatools#7831]
### Verified issue does not already exist?

Yes

### What error did you receive?

PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: Method invocation failed because [System.Object[]] does not contain a method 
                        named 'op_Division'.
                           at System.Management.Automation.ParserOps.CallMethod(IScriptExtent errorPosition, Object target, String methodName, 
                        PSMethodInvocationConstraints invocationConstraints, Object[] paramArray, Boolean callStatic, Object valueToSet)
                           at System.Management.Automation.ParserOps.ImplicitOp(Object lval, Object rval, String op, IScriptExtent errorPosition, String 
                        errorOp)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          : op_Division
CategoryInfo          : InvalidOperation: (op_Division:String) [], RuntimeException
FullyQualifiedErrorId : MethodNotFound
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Add-DbaAgDatabase<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.22\allcommands.ps1: line 350
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

### Steps to Reproduce

Ran the following:

Add-DbaAgDatabase -SqlInstance Instance1 -Secondary Instance2 -AvailabilityGroup AGName -Database DBName 
-SeedingMode Automatic

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

5.1.14393.4583

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64)   Jul 19 2021 15:37:34   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.03761

**Comment by andreasjordan** [comment]
Thanks for reporting, will have a look.

**Comment by andreasjordan** [comment]
For a workaround, you can disable the reporting of the seeding operation with:
```
Set-DbatoolsConfig -FullName commands.add-dbaagdatabase.report.seeding -Value $false
```
