### ISSUE TITLE
LogShipping Error

### ISSUE THREAD

**Issue by Nkansas** [sqlcollaborative/dbatools#7839]
### Verified issue does not already exist?

Yes

### What error did you receive?

Hi,

I've implented Log Shipping in 2 servers (SRVSQL023 - SRVSQL024, both have SQL2016 SP3).
But, I still have errors : no synchronization in the secondary server. 
Do I miss something by executing scripts ? 

![image](https://user-images.githubusercontent.com/25858346/136160714-0207bd24-e4db-4ad4-b556-c19df1f4f4f1.png)
![image](https://user-images.githubusercontent.com/25858346/136160934-e7fe76e4-ad25-4c67-aa27-0f0e5dab1681.png)
![image](https://user-images.githubusercontent.com/25858346/136161194-6748a751-f68f-4b48-afc5-6d487aa11776.png)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Other details or mentions

Same errors occur when using SQL Server 2019 SP1.

![image](https://user-images.githubusercontent.com/25858346/136161528-f6cf77fe-b113-4bef-82cb-4d57ca36d8a9.png)

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

$params = @{
SourceSqlInstance = 'SRVSQL023\SQL2016'
DestinationSqlInstance = 'SRVSQL024\SLQBIS'
Database = 'Bagneux'
BackupNetworkPath = '\\SRVSQL024\Log_Shipping_SQL'
CompressBackup = $true
GenerateFullBackup = $true
SecondaryDatabaseSuffix = '_DR'
BackupScheduleFrequencyType = 'daily'
BackupScheduleFrequencyInterval = 1
CopyScheduleFrequencyType = 'daily'
CopyScheduleFrequencyInterval = 25
RestoreScheduleFrequencyType = 'daily'
RestoreScheduleFrequencyInterval = 30
CopyDestinationFolder='\\SRVSQL024\Log_Shipping_SQL'
Force = $true
}

### SQL Server Edition and Build number

SQL 2016 SP3
SQL 2019 SP1

### .NET Framework Version

Framework 4.6.2

**Comment by andreasjordan** [comment]
Thanks @devondba for your detailed answer. I will close this for now as @Nkansas does not seem to have additional questions. But we can reopen if needed.
