### ISSUE TITLE
New-DbaRgResourcePool - examples don't work straightaway 

### ISSUE THREAD

**Issue by MikeyBronowski** [sqlcollaborative/dbatools#7842]
### Verified issue does not already exist?

Yes

### What error did you receive?

CC: @LowlyDBA as the author of #7794

The two examples won't work - they prompt for adding mandatory parameters

```
    .EXAMPLE
        PS C:\> New-DbaRgResourcePool -SqlInstance sql2016 -ResourcePool "poolAdmin"

        Creates a new resource pool named "poolAdmin" for the instance sql2016.

    .EXAMPLE
        PS C:\> New-DbaRgResourcePool -SqlInstance sql2012\dev1 -ResourcePool "poolDeveloper" -SkipReconfigure

        Creates a new resource pool named "poolDeveloper" for the instance dev1 on sq2012.
        Reconfiguration is skipped and the Resource Governor will not be able to use the new resource pool
        until it is reconfigured.
```

```
New-DbaRgResourcePool -SqlInstance $s1 -ResourcePool "poolAdmin"
cmdlet New-DbaRgResourcePool at command pipeline position 1
Supply values for the following parameters:
MaximumCpuPercentage: 

New-DbaRgResourcePool -SqlInstance $s1 -ResourcePool "poolDeveloper" -SkipReconfigure
cmdlet New-DbaRgResourcePool at command pipeline position 1
Supply values for the following parameters:
MaximumCpuPercentage:
```

Even though I provide the parameters I still get the warning
`New-DbaRgResourcePool -SqlInstance $s1 -ResourcePool DeadPool -MaximumCpuPercentage 90 -MaximumMemoryPercentage 90`

The warning does not say what parameter is that for.
```
WARNING: [17:00:02][New-DbaRgResourcePool] Failure | Error connecting to [localhost,1433]: The 0 argument is less
 than the minimum allowed range of 1. Supply an argument that is greater than or equal to 1 and then try the comm
and again.
```the 

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
See above

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                            
----                           -----                                                                            
PSVersion                      5.1.19041.1237                                                                   
PSEdition                      Desktop                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                          
BuildVersion                   10.0.19041.1237                                                                  
CLRVersion                     4.0.30319.42000                                                                  
WSManStackVersion              3.0                                                                              
PSRemotingProtocolVersion      2.3                                                                              
SerializationVersion           1.1.0.1                                                                          

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64)   Nov 30 2018 12:57:58   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)

### .NET Framework Version

.NET Framework 4.8.4420.0

**Comment by LowlyDBA** [comment]
The first two issues are from a lack of default values - addressed in the above PR. The second one is coming from the `Set-` function that had an improper range for `MaxIOPSPerVolume` defined - also fixed in the PR.
