### ISSUE TITLE
VS Code + PS Ext's Integrated Terminal no longer loads dll file

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#7865]
### Verified issue does not already exist?

Yes

### What error did you receive?

![image](https://user-images.githubusercontent.com/11204251/137594934-6b966dcc-8245-47a6-926c-6e16d0a47583.png)

Import-Module: The specified module 'C:\git\dbatools\bin\dbatools.dll' was not loaded because no valid module file was found in any module directory.

### Steps to Reproduce

Start debugging session or open PowerShell Integrated Console in VS Code using PS 7.1.5
```powershell
ipmo .\dbatools.psd1
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

### SQL Server Edition and Build number

N/A

### .NET Framework Version

```
.NET 5.0.11
```

**Comment by wsmelton** [comment]
Switch Ext to use Windows PowerShell and it imports with no issues.

**Comment by wsmelton** [comment]
PR on folder restructuring it cleared up but couldn't figure out which path update fixed it.

**Comment by andreasjordan** [comment]
Hi @wsmelton - is this fixed now? I can not reproduce the issue.

**Comment by wsmelton** [comment]
Does not seem to happen in PS 7.2.1, and latest version of Insiders + Ext for me.

**Comment by potatoqualitee** [comment]
woo!
