### ISSUE TITLE
Get-DbaDatabase  + Azure [ bug report ]

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7869]
### Summarize Functionality

I can't submit a bug report anymore. Not sure what is going on. It never allows me to click Submit New Issue.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

Get-DbaDatabase -SqlInstance $server
WARNING: [21:13:07][Invoke-QueryRawDatabases] Failure | Error connecting to [dbatoolstest.database.windows.net]: You cannot call a method on a null-valued
expression.

**Comment by andreasjordan** [comment]
Can you still reproduce this?

**Comment by potatoqualitee** [comment]
let' see: https://ci.appveyor.com/project/sqlcollaborative/dbatools/builds/41959307

**Comment by potatoqualitee** [comment]
nope, can't repro any longer 👍🏼
