### ISSUE TITLE
Invoke-DbaQuery - allow header row if empty result set returned

### ISSUE THREAD

**Issue by paschott** [sqlcollaborative/dbatools#7877]
### Summarize Functionality

Sometimes we need to generate a file that includes a header row of the columns that would be present, even if there is no data to accompany them. I'd like to see a parameter allowing that as an option to the Invoke-DbaQuery function.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

Invoke-DbaQuery will generate headers if there is at least one row of data returned, but doesn't return any headers when there is no data. The same query in SSMS will return header information.

I think an extra parameter or switch something like "-AlwaysGenerateHeaders" might suffice to generate header information even if there is no other data returned.

**Comment by niphlod** [comment]
it's not really a matter of what we do, rather that PS pipeline has nothing able to represent a zero-length results "with headers only" (which translates to a collection of properties, whose "names" are what you're looking for). 
`"" | Select col1, col2, col3, col4, col5`  may SEEM to achieve what you want, but would be indistinguishable from a result with a single row with all values empty.
You can retrieve the column names from the "richer" datatable object though

```
$result = Invoke-DbaQuery -SqlInstance .... -Query "select 1 as a, 2 as b where 1=0" -as DataTable
$cols = $x.Columns
$allcols = $cols | % { $_.ColumnName }
##E.g. generating an header for a CSV file, empty
("" | select $allcols | ConvertTo-Csv -NoTypeInformation)[0]
```

**Comment by wsmelton** [comment]
Yeah this is a limitation of objects in PowerShell.
