### ISSUE TITLE
BUG: ConvertTo-DbaTimeLine - ABC.html:47 Uncaught ReferenceError: google is not defined

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#7906]
### Verified issue does not already exist?

Yes

### What error did you receive?

Uncaught SyntaxError: Invalid or unexpected token
Uncaught ReferenceError: google is not defined
    at ABC.html:47

Line 47 in resulting HTML - google.charts.load('43', {'packages':['timeline']});

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference

Get-DbaAgentJobHistory -SqlInstance SRVSQL -StartDate '2021-10-28 00:00' -EndDate '2021-10-29 00:00' -ExcludeJobSteps | ConvertTo-DbaTimeline | Out-File E:\Temp\SQLSRV_AgentJobs.html

```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                              
----                           -----                                                                                                                                                                              
PSVersion                      5.1.19041.1237                                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                            
BuildVersion                   10.0.19041.1237                                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                                                                            

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)   Aug  7 2021 01:20:37   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) 

### .NET Framework Version

.NET Framework 4.8 | 528040

(code above did not work, got error - `Method invocation failed because [System.Runtime.InteropServices.RuntimeInformation] does not contain a method named 'get_FrameworkDescription'.`)

**Comment by andreasjordan** [comment]
This is most likely a problem with the googe code, as "Uncaught SyntaxError: Invalid or unexpected token" is from loader.js, which is loaded by "<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>", which is exacly as documented here: https://developers.google.com/chart/interactive/docs/gallery/timeline

So we can not do anything about it. Maybe @marcingminski has more info?

**Comment by marcingminski** [comment]
Hi, This has not been "touched" for a few years so there is a chance that Google changed their framework and it broke. I was not aware of it but I will take a look at it this weekend.

**Comment by alevyinroc** [comment]
@marcingminski have you had a chance to check on this? I'm experiencing this with the current version of dbatools as of 2021-12-01

**Comment by andreasjordan** [comment]
Hi @marcingminski - any new information?

**Comment by marcingminski** [comment]
Hi, just tested this, installed the latest dbatools version 1.1.44, ran the following:

```
Get-DbaAgentJobHistory -SqlInstance sql-2 -StartDate '2021-12-15 00:00' -EndDate '2021-12-19 23:59' -ExcludeJobSteps | ConvertTo-DbaTimeline | Out-File C:\temp\DbaAgentJobHistory.html -Encoding ASCII
```

and it worked with no issues, I am able to see the charts so unable to reproduce the error. Can you please attach your HTML file so I can debug yours? Thanks.

Here's mine, just change the extension from txt to HTML:
[DbaAgentJobHistory.html.txt](https://github.com/sqlcollaborative/dbatools/files/7758305/DbaAgentJobHistory.html.txt)

**Comment by andreasjordan** [comment]
Thanks @marcingminski for your help. I think it was an encoding problem. I have a HTML-file that throws the error. But after converting it to ANSI with Notepad++, it works.

So ` -Encoding ASCII` seems to be the key here.

@Zhunya can you try that?

**Comment by alevyinroc** [comment]
`Out-File -encoding UTF8` also works. Thanks for the tip @andreasjordan!

**Comment by Zhunya** [comment]
Thank you all, all works now!
