### ISSUE TITLE
Example 3 for Find-DbaInstance does not work in PowerShell Core (v7.1.4)

### ISSUE THREAD

**Issue by jrobiii** [sqlcollaborative/dbatools#7913]
### Verified issue does not already exist?

Yes

### What error did you receive?

Find-DbaInstance: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

### Steps to Reproduce

```powershell
# Example number 3 from https://docs.dbatools.io/Find-DbaInstance
Get-ADComputer -Filter "*" | Find-DbaInstance

Find-DbaInstance: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

Find-DbaInstance: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

Find-DbaInstance: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
```

### Are you running the latest release?

Yes

### Other details or mentions

`Get-AdComputer -Filter '*' ` does return a valid computer object for each computer in the domain.  

If I use the following script it seems to work:
```powershell
(Get-AdComputer -Filter '*').Name | Find-DbaInstance
```

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) - 15.0.4178.1 (X64)   Sep 23 2021 16:47:49   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET 5.0.9

**Comment by andreasjordan** [comment]
I just installed PowerShell Core 7.1.5 and there it works. If you can still reproduce the issue, please reopen.
