### ISSUE TITLE
Add Modify Date to Get-DbaAgentJob

### ISSUE THREAD

**Issue by fabiopennisifmg** [sqlcollaborative/dbatools#7930]
### Summarize Functionality

Add existing ModifyDate property (in Microsoft.SqlServer.Management.Smo.Agent) to Get-DbaAgentJob

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

Simple change required in Get-DbaAgentJob cmdlet.

Line 157 of Get-DbaAgentJob.ps1 (tack on new property)
$defaults = 'ComputerName', 'InstanceName', 'SqlInstance', 'Name', 'Category', 'OwnerLoginName', 'CurrentRunStatus', 'CurrentRunRetryAttempt', 'IsEnabled as Enabled', 'LastRunDate', 'LastRunOutcome', 'HasSchedule', 'OperatorToEmail', 'DateCreated as CreateDate', 'DateLastModified as ModifyDate'

**Comment by andreasjordan** [comment]
The property you are looking for is part of the returned object - just not part of the default properties to display. I personally think that the DateLastModified is not needed so often to put it in the defaults.

**Comment by fabiopennisifmg** [comment]
Hey, yes indeed, it's actually in there, sorry my bad. Yeah agreed, no need to add it to defaults. Cheers
