### ISSUE TITLE
Install-dbaFirstresponderkit not updating scripts

### ISSUE THREAD

**Issue by Kurama2121** [sqlcollaborative/dbatools#7936]
### Verified issue does not already exist?

Yes

### What error did you receive?

I updated the dbatools module and then ran the install-dbaFirstresponderkit and it shows as updated in the powershell module, but when I went to check their versions they were still the old version of the code. I ran the scripts manually from brents github and they updated fine.

### Steps to Reproduce

Install-Module DBAFirstResponderKit -Sqlinstance xxxxx

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.2183                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.2183                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) - 15.0.4178.1 (X64)   Sep 23 2021 16:47:49   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

Above command didnt work in ps

**Comment by andreasjordan** [comment]
An old version is still in the local cache. To update the cache, use `-Force` or use the command https://docs.dbatools.io/Save-DbaCommunitySoftware

**Comment by Kurama2121** [comment]
Thank you, didnt realize the force would do that.
