### ISSUE TITLE
Dead link in the documentation

### ISSUE THREAD

**Issue by reitse** [sqlcollaborative/dbatools#7938]
### Verified issue does not already exist?

No

### What error did you receive?

404 when clicking on the http://docs.dbatools.io/Invoke-DbaWhoisActive link on the commands page.

### Steps to Reproduce

website: go to commands, search for Invoke-DbaWhoIsActive and click on the link.

The link goes to http://docs.dbatools.io/Invoke-DbaWhoisActive, it should be http://docs.dbatools.io/Invoke-DbaWhoIsActive.

### Other details or mentions

n/a

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

not applicable

### SQL Server Edition and Build number

n/a

### .NET Framework Version

n/a

**Comment by andreasjordan** [comment]
Thanks for reporting this. As the webpage "https://dbatools.io/commands/" is not generated automatically: @potatoqualitee - can you do the change manually?

**Comment by wsmelton** [comment]
The documentation now resides under sqlcollaborative/web and anyone can submit a PR to address dead links.
