### ISSUE TITLE
Write-DbaDbTableData failing with TIMESPAN values

### ISSUE THREAD

**Issue by habibhammy** [sqlcollaborative/dbatools#7943]
### Verified issue does not already exist?

Yes

### What error did you receive?

HI All,

I need your help please.
I'm developping a PS Script that is doing some statistics and monitoring on the SQL infra in my company... 
I'm trying to copy the jobs history to a centrale datawarehouse from the source server.
I'm doing a select on the source server and getting the database in the below sql types : 
`
[Job_ID] [varchar](150) NOT NULL,
[Run_Status] [tinyint] NOT NULL,
[Run_DateTime] [datetime] NOT NULL,
[Duration] [time](7) NOT NULL
`
The variable $JobsHistory contains the result : 
`
$GetJobsHistoryQuery = "SELECT jh.[Job_ID], j.[Server_Name], [Run_Status], [Run_DateTime], [Duration]
                             FROM [dbaDB].[dbo].[Job_History] jh 
                             INNER JOIN [dbo].[Job_Inventory] j ON j.Job_ID = jh.Job_ID"

        $JobsHistory= @()

        TRY {
            $JobsHistory += Invoke-DbaQuery -SqlInstance $TargetServer -Database $TargetDatabase -Query $GetJobsHistoryQuery -EnableException
        }CATCH {
            $Exception = $_.Exception.Message  
            $FunctionError =  "Catched Error Details : " + "`r`n" + "Function:"  + "`t"   + "Copy-ServerJobsHistory" +  
                        "`r`n" + "Job Name :"    + "`t`t" + $servername +   
                        "`r`n" + "Error:"     + "`t`t" + $Exception + "`r`n ******************** `r`n"

            Write-Host " ERROR 35 : Cannot retreive Jobs History from the server [$TargetServer] `r`n $FunctionError"
            Add-Content -Path $Logfile -Value " ERROR 35 : Cannot retreive Jobs History from the server [$TargetServer] `r`n $FunctionError"
            Break;
        }
`

However, When I'm trying to insert this data on the central datawarehouse: 
`
$TempTableName ="[dbo].[TmpTable_$($TargetServer)_Job_History]"
        TRY {
            $JobsHistory | Write-DbaDbTableData -SqlInstance $MainServer -Database tempdb -Table $TempTableName -AutoCreateTable -EnableException
        }CATCH {
            $Exception = $_.Exception.Message  
            $FunctionError =  "Catched Error Details : " + "`r`n" + "Function:"  + "`t"   + "Copy-ServerJobsHistory" +  
                        "`r`n" + "Job Name :"    + "`t`t" + $servername +   
                        "`r`n" + "Error:"     + "`t`t" + $Exception + "`r`n ******************** `r`n"

            Write-Host " ERROR: Cannot BULK Insert Jobs History To [tempdb] in $MainServer `r`n $FunctionError"
            Add-Content -Path $Logfile -Value " ERROR : Cannot BULK Insert Jobs History To [tempdb] in $MainServer `r`n $FunctionError `r`n $FunctionError"
            Break;
        }
`
 I'm getting the below error: 
`
[17:05:04][Copy-ServerJobsHistory] Failed to bulk import to [tempdb].[dbo].[TmpTable_BFCSQL2-PIVOT.corp.colas.com_Job_History] | L'objet doit implémenter IConvertible.
`
After some checks It seems the error is comming from the `[Duration] [time](7)` value.
Actually, the table created by the command has below column type : 
`
	[Job_ID] [nvarchar](max) NULL,
	[Server_Name] [nvarchar](max) NULL,
	[Run_Status] [int] NULL,
	[Run_DateTime] [datetime2] NULL,
	[Duration] [nvarchar](max)  NULL
`
And we can clearly see that the [Duration] type is not the same anymore.
For the moment I have a work around, as I'm creating the table before hand.
However, can this issue be corrected ?

I've also done some code checks to help and I think that the issue should quickly be resolved by changing the key/value table `$PStoSQLTypes` and set the line `'TimeSpan'              = 'nvarchar(30)';` as `'TimeSpan'              = 'Time(7)';`

Many Thanks.

### Steps to Reproduce

As described in  the previous session. 

1. Create an array of TimeSpan values.
2. Call the command Write-DbaDbTableData as below 
```powershell
$array | Write-DbaDbTableData -SqlInstance $MainServer -Database tempdb -Table $TempTableName -AutoCreateTable -EnableException
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.17763.2183                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.17763.2183                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                                                      

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3740.0

**Comment by niphlod** [comment]
hum, .net timespan can also be GREATER than 24 hours, which is the max value for time(7), hence not the correct type. 
You'd be much better off extracting starttime and doing a dateadd to it with the duration to extract the "endtime", so you can account for durations greater than 24 hours

**Comment by habibhammy** [comment]
hmmmm I fully understand your point. 
But for me it is ok if I could import the data as nvarchar to the SQL server database .... 
The problem is that SQL Server is refusing the match TimeSpan<==>NVarChar ....

Also many be I'm wong in my analysis and that the error is not linked to this ... 
Can you please double check :D 

```powershell
[17:05:04][Copy-ServerJobsHistory] Failed to bulk import to [tempdb].[dbo].[TmpTable_BFCSQL2-PIVOT.corp.colas.com_Job_History] | L'objet doit implémenter IConvertible.
`

**Comment by andreasjordan** [comment]
The `-AutoCreateTable` feature is not meant to be perfect but only a quick option for typical cases. If you want to improve it, feel free to code that and open a pull request.
So I will close this for now, but we can reopen and label it as a feature request if you want to work on that.
