### ISSUE TITLE
Restore-DbaDatabase - WithReplace combined with ReuseSourceFolderStructure does not respect destination folder structure

### ISSUE THREAD

**Issue by cpurules** [sqlcollaborative/dbatools#7959]
### Verified issue does not already exist?

Yes

### What error did you receive?

`WARNING: [20:39:58][New-DbaDirectory] Failure | xp_create_subdir() returned error 3, 'The system cannot find the path 
specified.'`

### Steps to Reproduce

Consider a backup file AdventureWorks.bak for a database AdventureWorks on server Server1, which has 3 data files in the following locations:
- AdventureWorks (PRIMARY filegroup, rows) -> S:\Data\AdventureWorks.mdf
- AdventureWorks_Log (log) -> L:\Log\AdventureWorks.ldf

Server1 default directories:
- Data  -> S:\Data\
- Log -> L:\Log\

Consider a second SQL Server that is otherwise identical, but the S: and L: drives are actually the D: and E: drives
- Data -> D:\Data\
- Log -> E:\Log\

Execute the below PowerShell, with variables adjusted as necessary

```
# DUMMY VARIABLES #
$TargetInstance = 'Server2'
$TargetDBName = 'AdventureWorks'
$TargetFilePath = 'AdventureWorks.bak'

# Restore Command
Restore-DbaDatabase     -SqlInstance $TargetInstance `
                            -DatabaseName $TargetDBName `
                            -Path $TargetFilePath `
                            -WithReplace `
                            -ReplaceDbNameInFile `
                            -ReuseSourceFolderStructure `
                            -WarningAction Stop `
                            -verbose
```

Expected behavior: the database is restored and the data files reside in the appropriate location on the appropriate drive, i.e.:
AdventureWorks -> D:\Data\AdventureWorks.mdf
AdventureWorks_Log -> E:\Log\AdventureWorks.ldf

Actual behavior: the database fails to restore with the above error message

### Are you running the latest release?

Yes

### Other details or mentions

Please see #7956 for more context.  I cannot re-open the issue as it was closed.  This is very closely related albeit not exactly the same.

The combination of `-WithReplace` and `-ReuseSourceFolderStructure` worked fine for backup files that are on the same server.  However the above command piece (in reproduction steps) is part of a general backup/restore script that is used across many servers which may have inconsistent drive names, folder structures, etc.

If I am restoring a backup file from another server that has a **different directory structure** (namely the drive letters are different), then the restore will fail if I use `-ReuseSourceFolderStructure`.  The command is the same as my original report, just with the added `-ReuseSourceFolderStructure` parameter per our discussion in #7956 

So it seems that the combination of `-WithReplace` and `-ReuseSourceFolderStructure` may not actually be using the destination folder structure as mentioned in the [docs](https://docs.dbatools.io/Restore-DbaDatabase), namely the note at the end, but rather continuing to use the source folder structure:

```
-ReuseSourceFolderStructure
By default, databases will be migrated to the destination Sql Server's default data and log directories. You can override this by specifying -ReuseSourceFolderStructure. The same structure on the SOURCE will be kept exactly, so consider this if you're migrating between different versions and use part of Microsoft's default Sql structure (MSSql12.INSTANCE, etc) *Note, to reuse destination folder structure, specify -WithReplace
```

The docs are unclear whether I should use only `-WithReplace` (in which case, issue #7956 should be reopened), or whether I should be using the two parameters together (suggested in #7956 but yields the errors reported in this bug)

My objective is to **use the target database's existing folder structure if the database exists**

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

```
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.14393.4583                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14393.4583                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1      
```

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-CU17) (KB5001092) - 13.0.5888.11 (X64) Mar 19 2021 19:41:38 Copyright (c) Microsoft Corporation Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 (Build 14393: ) (Hypervisor)

### .NET Framework Version

.NET Framework 4.7.3870.0

**Comment by andreasjordan** [comment]
I would say: If you want to use the **destination** folder structure, don't use the parameter Reuse**Source**FolderStructure.
But on the other hand, the documentation might not be clear enough for every user. Maybe @Stuart-Moore can help you, as he is the author of the command.
