### ISSUE TITLE
Possible issue with DBATools and Defender

### ISSUE THREAD

**Issue by abndrew82** [sqlcollaborative/dbatools#7963]
### Verified issue does not already exist?

Yes

### What error did you receive?

Did not see this posted, but installed DBATools today and Defender is blocking execution as a Trojan
![Dbatools](https://user-images.githubusercontent.com/6509648/142669719-54a40b03-b15a-4d09-b3c1-82f5d9268ed6.PNG)

Figure it's a false positive but probably needs to be investigated.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Import Module / Attempt to use on machine running Defender (Possible Defender Advanced Threat Protection)

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22000.282                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22000.282                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU13) (KB5005679) - 15.0.4178.1 (X64)   Sep 23 2021 16:47:49   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

4.8.04161

**Comment by andreasjordan** [comment]
Let me post a link to this tweet for reference: https://twitter.com/psdbatools/status/1462187003366285317
Will close this as it should be fixed by now.
