### ISSUE TITLE
Get-DbaNetworkConfiguration -OutputType Certificate only works with remote connection

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7966]
### Verified issue does not already exist?

Yes

### What error did you receive?

No error, just no output - when remote connection is not forced.

### Steps to Reproduce

```powershell
 Get-DbaNetworkConfiguration -SqlInstance sql01\sql2017 -OutputType Certificate
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

-

### SQL Server Edition and Build number

-

### .NET Framework Version

-

**Comment by andreasjordan** [comment]
New verbose on PSCore:
```
VERBOSE: [12:40:25][Get-DbaNetworkConfiguration] regPath = 'Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQLServer\SuperSocketNetLib'
VERBOSE: [12:40:25][Get-DbaNetworkConfiguration] itemPropertyForceEncryption = '@{ForceEncryption=0; PSPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQLServer\SuperSocketNetLib; PSParentPath=Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQLServer; PSChildName=SuperSocketNetLib; PSProvider=Microsoft.PowerShell.Core\Registry}'
```

New verbose on powershell.exe:
```
VERBOSE: [12:39:48][Get-DbaNetworkConfiguration] regPath = 'Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQLServer\SuperSocketNetLib'
VERBOSE: [12:39:48][Get-DbaNetworkConfiguration] Failure: Cannot find path 'HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQLServer\SuperSocketNetLib' because it does not exist.
```

**Comment by andreasjordan** [comment]
Found the reason:

On PSCore:
VERBOSE: [12:40:24][Invoke-ManagedComputerCommand] Local connection attempt to sql01 failed. Connecting remotely.

On powershell.exe, "direct WMI" is used - but this way we cannot read the registry.

Will try to force remote connection in any case...

**Comment by andreasjordan** [comment]
Oh, I made a big mistake with the last change to Get-DbaNetworkConfiguration - I mixed WMI-Access and Registry-Access. Will try to sort my thoughts here so I can ask the other contributors for help...

Before the change, Get-DbaNetworkConfiguration only selected properties that are available over the wmi class and we used `$wmi = New-Object Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer $ipaddr` to connect to the wmi instance on the remote computer via a local object. If that failed, we connect to the remote computer and run the code there.

But I wanted (and still want) to get all information related to the network configuration and typically managed by SQL Server Configuration Manager in this one command. So also those information, that are stored in the registry. But to read the remote registry, we have to connect to the remote computer and run the code there. Or is that only true in my setup?

So one way would be to always connect to the remote computer and run the code there. Or do some users use Get-DbaNetworkConfiguration without remote access and would then fail using the command?

Another way would be to depend on the -OutputType if remote connection is needed to get the registry or not. But that way massive code changes in Set-DbaNetworkConfiguration would be needed to be able to use piped input.


So lets start with two questions to see what the other contributors think:
* Should Get-DbaNetworkConfiguration also output information from the registry (Certificate, Force Encryption, Hide Instance, ...) or only those accessable via the wmi class?
* Can we force remote access when using Get-DbaNetworkConfiguration and Set-DbaNetworkConfiguration?

**Comment by andreasjordan** [comment]
@potatoqualitee / @niphlod / @wsmelton : If you have some time to look at this, I would be very happy to have your feedback.

**Comment by potatoqualitee** [comment]
I don't mind mixing and matching protocols. `Remote Registry` requires a port outside of WinRM to be open, however, so when I need to read the registry, I login remotely via Invoke-Command2. Perhaps for your local to work, you just need to be running as admin?
