### ISSUE TITLE
New-DbaDatabase + (Test-Bound) - DataFileSuffix & LogFileSuffix Don't trigger advancedconfig or using default 

### ISSUE THREAD

**Issue by AEaston99** [sqlcollaborative/dbatools#7981]
### Verified issue does not already exist?

Yes

### What error did you receive?

![image](https://user-images.githubusercontent.com/60107806/143074726-9631cf5b-795a-448c-bcb6-57a255ac4130.png)

When using DataFileSuffix or LogFileSuffix it does not work as it is not included in an if statement using test-bound. From my testing.
There are multiple issues in this post so please read this fully. 

### Steps to Reproduce

 `New-DbaDatabase -SqlInstance [SQL Instance] -Name DEV_ADAM -DataFileSuffix "_Data01" -LogFileSuffix "_Log01" -Verbose`
The database is created. However the Data and log file prefixes are not set.

### Are you running the latest release?

Yes

### Advanced Config Not Triggering

When running:
 `New-DbaDatabase -SqlInstance [SQL Instance] -Name DEV_ADAM -DataFileSuffix "_Data01" -LogFileSuffix "_Log01" -Verbose`
The database is created. However the Data and log file prefixes are not set.
![image](https://user-images.githubusercontent.com/60107806/143068055-9c47fe67-60ac-4392-8e02-959d3497d37f.png)

Looking at line 176-179 of New-DbaDatabase:
```
        if (Test-Bound -ParameterName DataFilePath, DefaultFileGroup, LogFilePath, LogGrowth, LogMaxSize, LogSize, PrimaryFileGrowth, PrimaryFileMaxSize, PrimaryFilesize, SecondaryFileCount, SecondaryFileGrowth, SecondaryFileMaxSize, SecondaryFilesize) {
            $advancedconfig = $true
            Write-Message -Message "Advanced data file configuration will be invoked" -Level Verbose
        }
```
The DataFileSuffix & LogFileSuffix are not included in this if statement. so they do not trigger advancedconfig and then as a result do not change the file names.

In my testing, I edited the function locally.
I changed this part to be:
```
        if (Test-Bound -ParameterName DataFileSuffix, LogFileSuffix, DataFilePath, DefaultFileGroup, LogFilePath, LogGrowth, LogMaxSize, LogSize, PrimaryFileGrowth, PrimaryFileMaxSize, PrimaryFilesize, SecondaryFileCount, SecondaryFileGrowth, SecondaryFileMaxSize, SecondaryFilesize) {
            $advancedconfig = $true
            Write-Message -Message "Advanced data file configuration will be invoked" -Level Verbose
        }
```

Then when running my code : 
`New-DbaDatabase -SqlInstance [SQLInstance] -Name DEV_ADAM -DataFileSuffix "_Data01" -LogFileSuffix "_Log01" -Verbose`
The database was created and the suffixes were set correctly.
![image](https://user-images.githubusercontent.com/60107806/143071874-4081843b-b9f3-4a0d-84cc-37a9ece0dd47.png)

### Test-Bound not working on defaults
Following on from the fix that is shown in the previous part.

When running this code : 
`New-DbaDatabase -SqlInstance [SQLInstance] -Name DEV_ADAM`
The database is created. However the Data and log file prefixes are not set to the default values.
![image](https://user-images.githubusercontent.com/60107806/143073422-69a12aa3-e8fa-4bab-bf49-46317c81c626.png)

I have had a quick look at the Test-Bound function and I believe that it is something to do with using psboundparameters. As $psboundparameters does not contain default values. This also leads me to believe that this function would not work for any of the dbatools functions when relating to defaults.

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2012 - 11.0.5343.0 (X64)   May  4 2015 19:11:32   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

### .NET Framework Version

.NET 5.0.9

**Comment by andreasjordan** [comment]
Thanks for reporting this and the analysis to the root cause. 

@potatoqualitee - As far as I can see, the "advanced" switch was introduced to be able to support SQL Server 2000. What about adding `DataFileSuffix`, `LogFileSuffix` and `SecondaryDataFileSuffix` to the `if` in line 176, but in line 261 we don't test for `$advancedconfig` but `$server.VersionMajor -gt 8` to only exclude this configuration for SQL Server 2000. That way the defaults for those parameters would have an effect.

**Comment by andreasjordan** [comment]
New suggestion: What about adding `DataFileSuffix`, `LogFileSuffix` and `SecondaryDataFileSuffix` to the if in line 176, but not changing line 261. That would not break all the tests we have and would only change the behavior for those who used one of the other advanced parameters.
Will update the pull request...

**Comment by andreasjordan** [comment]
One test still fails, but before fixing that I would like to get some feedback.

**Comment by AEaston99** [comment]
Not sure if it's my feedback your requesting, but I'll give it anyway. Firstly thanks for your rapid response on this! So is your solution to remove the defaults completely? For my use case, this is fine as I will always set this to our naming convention. However, I could see how this could be bad for the average joe. 

It's just a note. But, I believe no DBAtools scripts will work using defaults that have the same if test-bound, while test-bound works the way it does (I understand how much work it could be to change test-bound, I'm just pointing it out).

**Comment by andreasjordan** [comment]
Thanks for the feedback - now I'm waiting for @potatoqualitee to share her ideas...
