### ISSUE TITLE
Get-DBAProductKey fails on named clustered instances

### ISSUE THREAD

**Issue by Shashtsoh** [sqlcollaborative/dbatools#7994]
### Verified issue does not already exist?

Yes

### What error did you receive?

WARNING: [11:36:59][Get-DbaProductKey] Error occurred while establishing connection to @{ComputerName=<server>; InstanceName=<instancename>; SqlInstance=<FCI Cluster Resource Name>; Hive=HKLM; Path=Software\Microsoft\Microsoft SQL Server\MSSQL13.<instancename>; RegistryRoot=HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL13.<instancename>}.SqlInstance | The system cannot find the file specified.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
get-dbaproductkey <server> # I have tested using the server, cluster name, and FCI resource name; all return the same error

### Are you running the latest release?

Yes

### Other details or mentions

Based on the debugging I've done, it appears that the logic just assumes that clustered instances will not also be named instances.  because of that, the sqlinstance property being referenced only contains the cluster resource name, rather than the concatenation of cluster resource and instance name.  The root of the error appears to be in get-dbaregistryroot, but I have not dug that deep into the code yet to determine where in that function the error would be.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-GDR) (KB4583460) - 13.0.5103.6 (X64) 
	Nov  1 2020 00:13:28 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

### .NET Framework Version

.NET 6.0.0-rtm.21522.10

**Comment by Shashtsoh** [comment]
Looks like the root issue is on Lines 77-82 of get-dbaregistryroot.  That logic block assumes that the value pulled for vsroot for a cluster is all that is needed to connect to the instance, so it skips the code that would append the instance name.  

There is an advanced property that specifies whether the instance is clustered or not.  I think we may be able to leverage that to determine whether to use vsroot or computername prior to appending the instance name.

**Comment by Shashtsoh** [comment]
Suggested fix - this works for me in my environment.  This only changes the value of the SQLInstance field on return.  It should retain all previous functionality while fixing the bug.  

Change lines 77-82 of get-dbaregistryroot from:

> if ([System.String]::IsNullOrEmpty($vsname)) {
>     $vsname = $computer
>     if ($instanceName -ne "MSSQLSERVER") {
>         $vsname = "$($computer.ComputerName)\$instanceName"
>     }
> }

To this:

> if ([System.String]::IsNullOrEmpty($vsname)) {
>     $vsname = $computer.ComputerName
> }
> if ($instanceName -ne "MSSQLSERVER") {
>     $vsname = "$($vsname)\$instanceName"
> }

**Comment by u0545288** [comment]
Fix works!!! Great bug find! Hoping this gets fixed in DBATools soon, thanks for posting this!

**Comment by andreasjordan** [comment]
Thanks for reporting this and thanks for the fix - will open a pull request soon.
