### ISSUE TITLE
New-DbaDatabase - Unlimited Max Size

### ISSUE THREAD

**Issue by AEaston99** [sqlcollaborative/dbatools#8015]
### Summarize Functionality

Currently I do not see a way that I can set the database file max to unlimited. I would like this to be possible. One way I thought of doing this is by setting up a way that if the user inputs the max to be 0 then the script will take this and make the database unlimited file max.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

Line 302:

```
if (Test-Bound -ParameterName PrimaryFileMaxSize) {
    $primaryfile.MaxSize = ($PrimaryFileMaxSize * 1024)
}
elseif (Test-Bound -ParameterName PrimaryFileMaxSize -and  $PrimaryFileGrowth -eq '0') {
    $primaryfile.MaxSize = "Unlimited"
}
```

Just an example of what I am thinking. Something like this.

**Comment by andreasjordan** [comment]
Have you tried just to not use the parameter PrimaryFileMaxSize? That should use the value from model, which is unlimited if you havn't changed it. So: I don't see a need for a change here...

**Comment by AEaston99** [comment]
Hello, thank you for your time. Yes this works for my issue.
