### ISSUE TITLE
Find-DbaStoredProcedure - CR Line Ending Output On StoredProcedureFullText Property

### ISSUE THREAD

**Issue by mattcargile** [sqlcollaborative/dbatools#8036]
### Verified issue does not already exist?

Yes

### What error did you receive?

Error wasn't received. Due to how the split is happening on typical Windows installations, there is an "orphan" `CR` character.

https://github.com/sqlcollaborative/dbatools/blob/27bc0adb3357fd5933dd2c285970039a7fe3895c/functions/Find-DbaStoredProcedure.ps1#L144

Maybe we can take some of the philosophy from this [issue ](https://github.com/sqlcollaborative/dbatools/issues/7689) with  `$eol = [System.Environment]::NewLine`.

### Steps to Reproduce

```powershell
Find-DbaStoredProcedure Server -Database db -Pattern select
```

### Are you running the latest release?

Yes

### Other details or mentions

I noticed the issue when I tried to mix `CRLF` with the `CR` within SQL Server Management Studio. I did a `Find-DbaStoredProcedure | Select-Object -ExpandProperty StoredProcedureFullText | Set-Clipboard` and copied into SSMS. Then I added a `USE` and `GO` declaration at the top. When I ran the entire script, I received the below error.

```sql
Msg 102, Level 15, State 1, Line 1
Incorrect syntax near 'GO'.
```

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```powershell
[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64) 
	Sep  7 2018 01:37:51 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )
```

### .NET Framework Version

```powershell
.NET 6.0.0-rtm.21522.10
```

**Comment by niphlod** [comment]
this is multifold .... sprocs can have LF, CR or CRLF in their bodies and then there's the EOL on "client" side.
Usually if whitespace lines are not a problem this can be circumvented splitting on everything server-side and joining client-side according to the OS. In this case .... I don't really know

**Comment by mattcargile** [comment]
Ah, right. Would it be reasonable to check the OS server side and split based on that? It seemed like the intent of the output was to have the line endings removed and in place would be an array of lines?

**Comment by niphlod** [comment]
the reality is that the interface exposed right now just doesn't cut the deal. the sproc is a blurb of text, inputted by whoever edited it the last time with their convention. 
Exposing line numbers on PS's side is a side-benefit when everybody agrees on line endings, but a PITA otherwise. Would have been the same PITA if someone asked to turn tabs into spaces or viceversa.
So IMHO the sproc should be returned verbatim without splitting or joining whatsoever.

**Comment by mattcargile** [comment]
Right, I get that. It was how I was assuming the output would be anyway.

I was grabbing this property as a somewhat quicker way than clicking through SSMS to script it out.

**Comment by andreasjordan** [comment]
So can we close this?

**Comment by mattcargile** [comment]
Well it would be nice to either handle the line endings differently or not at all (i.e return the full text as a blob of text ).

**Comment by andreasjordan** [comment]
So removing the 
```
.split("`n")
```
in line 144?

That would be ok for me. Would you like to open the pull request or should I do it?

**Comment by mattcargile** [comment]
Sounds good. Yeah I can open the PR.

**Comment by mattcargile** [comment]
So for this below line. Should we create two copies of the `$row.TextBody` The `StoredProcedureTextFound` property needs the split. So I don't think we can get away with trying to resolve the line ending split in a better way. I guess we could normalize all the line endings prior to generating the `$spTextFound`.

https://github.com/sqlcollaborative/dbatools/blob/31af4729245f8073ddec3f8453b20ef16543c9b6/functions/Find-DbaStoredProcedure.ps1#L145
