### ISSUE TITLE
Website has broken link for function list

### ISSUE THREAD

**Issue by mikeblas** [sqlcollaborative/dbatools#8039]
### Verified issue does not already exist?

No

### What error did you receive?

404

### Steps to Reproduce

1. Someone told me about dbatools.io.  I don't know what it is.
2. Visit dbatools.io. 
3. I end up going to "getting started" at https://dbatools.io/getting-started/
4. There, I see "over 500 ... commands included".  I click that link.

BUG#1) I end up at this address:  https://dbatools.io/functions/   which is a 404 error

### What PowerShell host was used when producing this error

VS Code (terminal)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by wsmelton** [comment]
I do not see this issue, it shows and loads the proper page...

![image](https://user-images.githubusercontent.com/11204251/147942725-33009aa7-9da8-4ea0-aad0-e84812dae533.png)

**Comment by mikeblas** [comment]
This issue still repros for me.  The "500 commands" link goes to https://dbatools.io/functions/  , which is 404.  It does *not* go to /commands/

If I look at the source for the page, here is what I see:

```html
				<main id="main" class="site-main" role="main">

											<p>

						dbatools is a <strong>free </strong>PowerShell module with <a href="https://dbatools.io/functions/"><u>over 500</u></a> SQL Server administration, best practice and migration commands included.
						</p>
``` 

pretty clearly goes to `/functions`. 

I'm able to demonstrate this in Chrome and FireFox, as well as Microsoft Edge.

It would be a shame if you weren't able to put more effort into diagnosing it.

**Comment by gwojan** [comment]
FWIW, I can repro the issue right from my phone by following the link on the getting started page.

**Comment by andreasjordan** [comment]
For me, the link goes to https://dbatools.io/functions (without / at the end) and is redirected to https://dbatools.io/commands/ without any problems:

![image](https://user-images.githubusercontent.com/66946165/148243614-13ef283f-1cbb-4dc4-bc06-02197e5adcd5.png)

**Comment by wsmelton** [comment]
The link issue on the site is we had `https://dbatools.io/functions/` and when migrated to GitHub the ending `/` won't redirect. That has been fixed across the site now.

**Comment by mikeblas** [comment]
Yay! Looks like it's fixed.

But why is the redirect necessary?
