### ISSUE TITLE
Start-SqlMigration has issue with pssession

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#804]
﻿### Is this a *feature* OR *bug*:

Bug

### System Details

- Operating system name and version:
- Output from `$PSVersionTable`:
OS SQL 2012 R2

```
Name                           Value                                                                                                                                                                                        
----                           -----                                                                                                                                                                                        
PSVersion                      5.0.10586.117                                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                      
BuildVersion                   10.0.10586.117                                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                                          
SerializationVersion           1.1.0.1 
```
 
- Output of dbatools version:

```
0.8.904
```

- SQL Server version for source/target
SQL 2012 to SQL 2016

### Steps to Reproduce
Ran Start-SqlMigration and had a couple errors when it gets to WinRM commands.  Whole log attached.

@ctrlbold  had me run 
enter-pssession CIFPRSDBS01
and that fails, but 
Enter-PSSession 'CIFPRSDBS01.exclaim-dev.com'
succeeds.

She suggested I open the bug for review.
[dbatools-startmigration-transcript.txt](https://github.com/sqlcollaborative/dbatools/files/794065/dbatools-startmigration-transcript.txt)

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by niphlod** [comment]
I'd vote for closing this in a few days if nobody pops up. So much has been changed regarding direct access to the underlying system that this is probably already solved. @gbargsley : still having issues ?
