### ISSUE TITLE
Website displaying raw JavaScript

### ISSUE THREAD

**Issue by mikeblas** [sqlcollaborative/dbatools#8040]
### Verified issue does not already exist?

Yes

### What error did you receive?

`' } cmdlist = new List('cmdlist', options, values); var index_url = '/dbatools-index.json?v=' + new Date().toISOString().substring(0,10) var current_cmd = document.location.href.split('/') current_cmd = current_cmd.pop() || current_cmd.pop() var allcmds = jQuery.getJSON(index_url, function(data) { var basetags = '' jQuery.each(data, function(i,el) { if (el.CommandName.toLowerCase() == current_cmd.toLowerCase()) { basetags = el.Tags return false } }) if (jQuery.isArray(basetags)) { basetags = basetags.join(', ') } if (basetags == '') { return } jQuery.each(data, function(i,el) { var tags = el.Tags == undefined ? '': el.Tags; if (jQuery.isArray(tags)) { tags = tags.join(', ') } if (tags !== basetags ) { return true } if (el.CommandName.toLowerCase() == current_cmd.toLowerCase()) { return true } var partial = { CommandName: el.CommandName, Tags: tags, Synopsis: el.Synopsis, Author: el.Author == undefined ? '': el.Author } cmdlist.add(partial) }) if (cmdlist.size() > 0) {`

### Steps to Reproduce

1) Visit this page: https://dbatools.io/getting-started/

2) Observe the right-hand pane

BUG#1) It's full of raw JavaScript

### Other details or mentions

PowerShell version is irrelevant

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by niphlod** [comment]
@potatoqualitee , seems like a closing tag is missing

**Comment by mikeblas** [comment]
Here's what I see: 
![rawCode](https://user-images.githubusercontent.com/6632219/147611357-5cbcb778-3b3f-4a48-82c3-0931b646da60.png)
