### ISSUE TITLE
New command request: Remove-DbaDbTable

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#8051]
### Summarize Command's Functionality

Any chance that someone can bust out a PR for `Remove-DbaDbTable` this week? We need it for `dbatools in a Month of Lunches` and we'm currently knee-deep in edits. Right now, our alternative is ().Drop() which isn't pretty :( 

We just need a PR to add it to the book, not an approval. We hope to have most edits done by Sunday.

Thank you for your consideration 🙏🏼 

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by andreasjordan** [comment]
I can do that.
