### ISSUE TITLE
Restore-DbaDatabase feature requests from the channel

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#823]
﻿### Is this a *feature* OR *bug*:

feature

### System Details

andrekamman [9:41 PM] 
Loving the new Restore-DbaDatabase! Great work Stuart!
I have some multi TB databases that I'll try it on next week.
Some feedback:

- If I point it at a database with lots of logs it is quiet for a long time while restoring the headers. Perhaps an idea to let verbose say that it's doing that instead of that it's connecting (which can make you think there's something wrong)
-  Having an extra progressbar showing the number of files to restore would be cool, I have hundreds but can't see how far along it is.
-  Being able to restore a database with multiple files in multiple locations would be cool. I have 8 files split across 2 mount points myself, would be cool if path would be an array

Overall I love this command, can't wait to simplify my disaster recovery documents :wink: (edited)

zhunya [9:44 PM] 
for last one use - PARAMETER FileMapping

[9:45]  
1 and 2, will be very good to see, I think in version 2 )

andrekamman [9:49 PM] 
FileMapping seems to be to specify which data file goes where. However, I've got multiple backup files, which is a different thing.
The script handles it well as long as the backup files are all in the same location.
But I have backups that are too large for one mountpoint and the san guys make me divide the files across 2 mountpoints.

zhunya [9:50 PM] 
uh... thats one

[9:51]  
working on my English still ))))

andrekamman [9:52 PM] 
No worries, I just read it back and I did not specify that I meant backup files, I just said "files"
So my apologies, I was not explaining it well

**Comment by Stuart-Moore** [comment]
Hi Andre,
For point 3 do you mean striped backups like this:
Restore database SomeDb to Disk='e:\backups\backup1a.bak',disk='f:\backups\backup1a.bak'. disk='g:\backups\backup1a.bak'

If you do the we support that:
Get-ChildItem e:\backups,f:\backups,g:\backups | Restore-DbaDatabase ............

I've just tested locally and passing a simple array in works as well:
('C:\dbatools\mb1\multiback1.bak', 'C:\dbatools\mb2\multiback2.bak') | Restore-DbaDatabase -SqlServer localhost\sqlexpress2016

1 is certainly something we want to look into. we had a quick look at going parallel to speed the scans up, that needs revisiting.

2 - More progress bars sounds like progress to me, I'll look at getting those in

**Comment by Stuart-Moore** [comment]
2 -  definitely fixed with last PR
1- we've improved the speed for certain types of restores. Need to think of a way of safely doing it for restores where we don't have the details beforehand.

**Comment by Stuart-Moore** [comment]
1 was mostly fixed by sorting out the piping in from Get-DbaDatabaseBackupHistory.

Only other option to to not scan stuff at all, but that's got all sorts of ways it can go wrong in non easy to rectify ways.
