### ISSUE TITLE
contributing.md contains reference to Invoke-DbaFormatter

### ISSUE THREAD

**Issue by jbelina** [sqlcollaborative/dbatools#8436]
### Verified issue does not already exist?

Yes

### What error did you receive?

Documentation only issue:
 
Invoke-DbaFormatter should be Invoke-DbatoolsFormatter

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
**n/a** - this is a documentation only change.

Invoke-DbaFormatter should be Invoke-DbatoolsFormatter

contributing.md was not updated as part of the following commit:

[renamed Invoke-DbatoolsFormatter](https://github.com/dataplat/dbatools/commit/fe55b40c7049a1b31af5d0babefc5d24e413ac03)

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.5
PSEdition                      Core
GitCommitId                    7.3.0-preview.5
OS                             Microsoft Windows 10.0.25151
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

n/a

### .NET Framework Version

n/a

**Comment by andreasjordan** [comment]
closed via #8437
