### ISSUE TITLE
Backup-DbaDatabase - failsafe path for backups when primary path not accessible

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#861]
### Is this a *feature* OR *bug*:

Feature

### Action Results

Have ability to Backup Database with primary and secondary (failsafe) path for backup process

### Expected Results

When primary path for backups not accessible, we go for second/failsafe path, and have backup process done right and our data in safe place.

I think, its better to have some wrapper for OLA's Maintenance Solution.

Wrapper-BackupWithMaintanance -SqlServer srv-sql-01 -Databases 'ALL_DATABASES,-testdb1' -Path "\\srv1\sqlbackups,\\srv2\sqlbackups" -FailsafePath "\\remote-srv1\sqlbackup,\\remote-srv2\sqlbackup" -BackupType LOG -Compress -CheckSum -Verify -ChangeBackupType

>Function Wrapper-BackupWithMaintanance - starting
>Function Wrapper-BackupWithMaintanance - checking path \\srv1\sqlbackups - OK!
>Function Wrapper-BackupWithMaintanance - checking path \\srv2\sqlbackups - FAIL!
>Function Wrapper-BackupWithMaintanance - primary path are not accessible, checking failsafe path
>Function Wrapper-BackupWithMaintanance - checking path \\remote-srv1\sqlbackup - OK!
>Function Wrapper-BackupWithMaintanance - checking path \\remote-srv2\sqlbackup - OK!
>Function Wrapper-BackupWithMaintanance - failsafe path are accessible, proceeding with them
>.... _(and so on)_

**Comment by wsmelton** [comment]
What you are proposing sounds more geared toward adjusting Ola's stored procedure than a need to adjust function or create a wrapper in the module. Just first thoughts.

With regards to PowerShell you could just as easily do that logic in calling the command. Just call the command for each database checking if it failed for one path and use the secondary if it does. I don't think the timing would be any different.

**Comment by Stuart-Moore** [comment]
Yes, I was trying to ponder a good way of doing all this.

The other switched make good sense

But I'm not sure this is necessarily a candidate for being an ola
replacement. Would need a lot more work to be properly SQL agent proof with
output and error message handling

**Comment by Stuart-Moore** [comment]
Compress, verify and checksum now in as a PR
