### ISSUE TITLE
DbaWhoisActive

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#871]
### Is this a *feature* OR *bug*:

bug

### System Details

Show-SqlWhoisActive should be renamed to Get-DbaWhoisActive and allow the end user to pipe to OGV. It should also not prompt to Install automatically the way it's doing now. It should confirm using $confirmationpreference and then prompt there then proceed.

**Comment by SirCaptainMitch** [comment]
closing, merged
