### ISSUE TITLE
Get-DbaDatabase for multiple -SqlInstance does not return server name.

### ISSUE THREAD

**Issue by white-bee** [sqlcollaborative/dbatools#874]
When calling Get-DbaDatabase -SqlInstance SQL1, SQL2 ... the **Server** name is not part of the output like Get-DbaDiskSpace has for example (like each command supporting server list would have I suspect)

I have following properties returned:
Name           :
Status         :
RecoveryModel  :
Compatibility  :
Collation      :
Owner          :
LastFullBackup :
LastDiffBackup :
LastLogBackup  :

**Comment by ctrlbold** [comment]
Thanks for your feedback, @white-bee! It's good to know what people expect.

I have submitted a PR that fixes your request and it will be included in a small release today. Please also note that there are a lot of properties that are there that you don't immediately see, we just cherry picked a few, kinda like Microsoft does. Check out

`Get-DbaDatabase -SqlInstance localhost -Databases master | Select *` 

👍
