### ISSUE TITLE
Get-DbaDiskSpace, duplication when supplying multiple servers outside the pipeline

### ISSUE THREAD

**Issue by dansqldba** [sqlcollaborative/dbatools#901]
### Is this a *feature* OR *bug*:
Bug

### System Details

- Operating system name and version: Multiple
- Output from `$PSVersionTable`:

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```

- SQL Server version for source/target

### Steps to Reproduce
Run command against multiple servers, not through the pipeline, observe the number of servers directly influences the duplicated results, both in simple and detailed output.

For example:

Get-DbaDiskSpace -ComputerName server1,server2,server3

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

More to come, just logging the issue so I don't forget.

**Comment by ctrlbold** [comment]
Thanks for the detailed report! Can reproduce.
