### ISSUE TITLE
Get or Find-DbaOpenCursor

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#902]
New command based on this article. I lean Find because he says "hunt" ;)

http://www.sqlskills.com/blogs/joe/hunting-down-the-origins-of-fetch-api_cursor-and-sp_cursorfetch/

Note the comment too that mentions this query for finding user info as well (we could easily get this from Get-DbaProcess, also)

`SELECT c.session_id, es.program_name, es.login_name, es.host_name, DB_NAME(es.database_id) AS DatabaseName, c.properties, c.creation_time, c.is_open, t.text
FROM sys.dm_exec_cursors (0) c
LEFT JOIN sys.dm_exec_sessions AS es ON c.session_id = es.session_id
CROSS APPLY sys.dm_exec_sql_text (c.sql_handle) t`

Any comments or nay welcomed. This will be post 1.0 of course, I'd just like to keep a list.

**Comment by wsmelton** [comment]
I've got code that can be used for testing this here: http://blog.wsmelton.info/2016-11-23-extended-events-fetching-api-cursors/

**Comment by wsmelton** [comment]
What about just a more general command like "Find-DbaSessionInfo"....

Just thinking out loud but if we only have "Find-DbaOpenCursor" it would assume that some other function was used to identify the fact a session was indicating the query "FETCH API" was showing. To dig more you then have to call another function. 

Compared to saying "Find-DbaSessionInfo" is going to find out what that session is doing, and say has logic if the query is showing "FETCH API" it will include the cursor DMV output.

**Comment by potatoqualitee** [comment]
This is similar to the thing i added recently 💃 - I need to add a blog post 

Get-DbaCommand now supports:
LastQuery
HostProcessId
MinutesAsleep
