### ISSUE TITLE
Add additional objects to Copy-Dba* by 1.5

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#904]
### Is this a *feature* OR *bug*:

feature

### System Details

At a later date, from spaghettidba's list - not maintenance plans tho cuz they were too complex I believe.

![image](https://cloud.githubusercontent.com/assets/8278033/23566637/1d9c8e6c-0053-11e7-9e72-84828b3ff169.png)

**Comment by wsmelton** [comment]
I would exclude DTS packages and replication from this list. (We do not have replication commands as it is to address it.)

What is `Registry Configuration` anyway?

Trying to address `cryptographic providers` will be a bit of a challenge as well since that deals with the EKM.

**Comment by wsmelton** [comment]
Pretty sure most of these are covered that we can with SMO. Copy command wise I'm not aware that many have asked for the objects we don't include, so far. Those are better tracked by creating issues for them individually.

**Comment by potatoqualitee** [comment]
I can convert this to a discussion, but I want to keep it all in one place at least for the reminder.
