### ISSUE TITLE
Test-DbaLinkedServerConnection

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#911]
### Is this a *feature* OR *bug*:

feature

### info

Thomas LaRock wrote asking if he could contribute what is essentially Test-DbaLinkedServerConnection. I made an exception to our 1.0 no new commands edict and said hell yes for 3 reasons: 
1. it's a useful command. 
2. It's straightforward to vet and 
3. great exposure for SQLBits.

😎

**Comment by FriedrichWeinmann** [comment]
From a technical perspective I have no objections. If you say it's useful enough to warrant an exception, I can live with that.

**Comment by ConstantineK** [comment]
I dont think this would warrant questioning the BDFL.

**Comment by potatoqualitee** [comment]
done a rama
