### ISSUE TITLE
Measure-DbaParallelismCostThreshold

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#918]
### Is this a *feature* OR *bug*:

proposed command for after 1.0

### Details

http://www.scarydba.com/2017/02/28/determining-the-cost-threshold-for-parallelism/

**Comment by wsmelton** [comment]
Not sure of the possibility on this one. The query Grant has for that `QueryCost` table does not actually work for me on 2019, throws an error on max depth of XML nodes.

Query: https://www.scarydba.com/2017/02/20/estimated-costs-queries/

Which I believe plans have changed in some versions to add more detail so not sure a query to hit the XML of the execution plans would be doable in a clean manner. As well, Query Store is more likely to be of use for this than trying to do it in PowerShell. I mean you can do math in PowerShell pretty easily (part of .NET after all) but performance wise on a large dataset I don't think would be very performant; at least not in Windows PowerShell.

**Comment by potatoqualitee** [comment]
Thank you shawn, will close.
