### ISSUE TITLE
New Commands - Get-DbaSystemHealth

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#920]
### Is this a *feature* OR *bug*:
**feature**

### System Details
- SQL Server version for source/target
SQL Server 2012+

### proposal

System health session holds overall health of the server. There is a base level of information that includes the following:

- IO Subsystem
- MonitorSystemHealth (overall health of server)
- Query Processing
- Resource Memory
- Spinlock CPU

### Expected Results

[Reference for queries.](https://blogs.technet.microsoft.com/sqlpfeil/2013/03/24/sql-2012-system-healthfASt-analysis/). The attached queries were based on this article but cleaned up to pass in the event_file automatically so it does not have to be provided. More information is kept in the event_file target for the system_health than the ring buffer, hence why it reads from the file.

Will output data table of the contents found. As well will likely include a parameter to maybe output the raw XML as well. 

For post 1.0 release. 

Command name up for discussion. Possible option would be a parameter for each subset of data being pulled (IO/memory/spinlocks). 

[_SystemHealth_IOSubsystem.txt](https://github.com/sqlcollaborative/dbatools/files/825038/_SystemHealth_IOSubsystem.txt)
[_SystemHealth_MonitorSystemHealth.txt](https://github.com/sqlcollaborative/dbatools/files/825037/_SystemHealth_MonitorSystemHealth.txt)
[_SystemHealth_QueryProcessing.txt](https://github.com/sqlcollaborative/dbatools/files/825040/_SystemHealth_QueryProcessing.txt)
[_SystemHealth_ResourceMemory.txt](https://github.com/sqlcollaborative/dbatools/files/825039/_SystemHealth_ResourceMemory.txt)
[_SystemHealth_SpinlockCPU.txt](https://github.com/sqlcollaborative/dbatools/files/825066/_SystemHealth_SpinlockCPU.txt)

**Comment by potatoqualitee** [comment]
is this something that can/should be accomplished by glenn berry's scripts or spwhoisactive?

**Comment by wsmelton** [comment]
Don't know... Never used that command. It could be used to read the file in the command in place of using the query.

Purpose would be to have the xml output in readable, friendly format. As long as it is efficient to pull the information across single or multiple instance don't matter to me how it for it.

**Comment by potatoqualitee** [comment]
yeah, So in this case, shawn, it would be `Get-DbaXESession -SqlInstance sql2014 -Session System_Health | Read-DbaXEFile`
