### ISSUE TITLE
New Command New-ServerEncrypt

### ISSUE THREAD

**Issue by dbrtly** [sqlcollaborative/dbatools#921]
### Feature:

Please forgive me if this is a newbie request.
I assume it is easy for someone who knows the tricks but as a Excel/Power BI guy forced to become an accidental dba I have problems. 

When I spun up my SQL Server 2016 VM on Azure, there was no default for encrypted connections over the internet to the server. I didn't see a checkbox. Looks like assumed knowledge that I just don't have. Searching for a solution has been tedious and I have other tentpole features to build while I become a dba the hard way.

Encrypted connections out-of-the-gate would be ideal but perhaps out of scope

I would like to have a short powershell command to configure the server for best practice for data warehousing, including the encryption. Please not SHA1 or MD5.

Thanks.

**Comment by wsmelton** [comment]
> SQL Server 2016 VM on Azure, there was no default for encrypted connections over the internet to the server.

Every SQL Server version and Windows Server 2012+ OS defaults to this with connections. You have to configure and allow Internet access inbound to the server (although it is not advised in most situations). As well, enabling encryption for SQL Server, [while fairly basic](https://msdn.microsoft.com/en-us/library/ms191192.aspx), has external pieces that we would not be able to test easily. 

There are already built-in commands for managing certificates in Windows OS. We could add a command to enable encrypted connections (test/set), but that would assume all the other stuff has already been done. We would also not control the encryption level (AES, SHA1, MD5) that is controlled by the certificate you install to utilize for the connectivity.

> I would like to have a short powershell command to configure the server for best practice for data warehousing, including the encryption.

This is a tall order and not specific to a DW, best practices would be similar for OLTP/OLAP servers as well. One command to do all of that will not done (and would not be a short command by any means). We are slowly but surely adding more commands to test for best practices and then pipe those to a command that sets them properly. At some point a wrapper function may be created that accomplishes something similar but that is not in the plans at this time.

**Comment by potatoqualitee** [comment]
We can do this now thanks to @FriedrichWeinmann! Fred, would you be able to create two DbaConfigs?

![image](https://user-images.githubusercontent.com/8278033/28501749-f964a0c0-6fe2-11e7-9610-46d43f69a68d.png)

EncryptConnection and TrustCertificate

Then respond to those within `Connect-SqlInstance` by adding `EncryptConnection` and `TrustServerCertificate ` by doing

* $server.ConnectionContext.TrustServerCertificate = $true
* $server.ConnectionContext.EncryptConnection = $true


Thank you 🙇 :bowtie:

**Comment by wsmelton** [comment]
This involves configuring SQL Server Network Configuration settings (right-click top tree and go to Properties):

![image](https://user-images.githubusercontent.com/11204251/54888914-6edfae00-4e6f-11e9-9b34-658d6f207dfe.png)

If you set `Force Encryption` to yes without setting a certificate in the next tab (see below image) then it will use the default certificate that SQL Server generates (cert file stored in default path with master database on installation).  To be true best practice and enforce harder encryption you install a certificate and then set the following tab for that certificate. If any given application cannot support encryption handshake then it is closed and not allowed.

Then adding a certificate:
![image](https://user-images.githubusercontent.com/11204251/54888923-799a4300-4e6f-11e9-9faf-af5bf0f8c30c.png)

**Comment by potatoqualitee** [comment]
Thanks for looking into this, @wsmelton  

All of this can currently be accomplished with our Certificate commands and Enable-DbaForceNetworkEncryption

![image](https://user-images.githubusercontent.com/8278033/54935703-1ff25100-4f21-11e9-8397-1885d3ca3f52.png)


```
$server.ConnectionContext.TrustServerCertificate = $true
$server.ConnectionContext.EncryptConnection = $true
```

those would still be nice, i'll create a new issue for that to be a dbatools setting and not just a connect-dbainstance setting

**Comment by potatoqualitee** [comment]
ope, already exists! 
https://github.com/sqlcollaborative/dbatools/issues/3467
