### ISSUE TITLE
Cmdlet/function to get comprehensive information about environment Dbatools is executed from

### ISSUE THREAD

**Issue by DaniSQL** [sqlcollaborative/dbatools#928]
### Is this a *feature* OR *bug*:
Feature

When users file issue, Dbatools need team needs info to start helping on the issue. Having these command will cut time for everyone involved and minimize the friction to report issues(users reporting, and DBAtools member helping diagnose the issue)

A cmdlet/function that reports details about user’s environment when they are reporting issues(this will not be about testing connectivity to target SQL Servers). The cmdlet will help capture details about users environment where DBAtools is being executed: it might include 
•	Windows version
•	PowerShell version
•	Dbatools module version
•	whether Powershell console is running as admin or not
•	PowerShell console vs ISE
•	whether dbatools is installed from repositories like PSGallery or otherwise. 
•	

Potentially when the cmdlet is run it will output the result to the console, but also to clipboard that way all they need to do when reporting issue either on GitHub issues or slack is paste it. That will save time for people who report issues and also to everyone helping diagnose the issue reported. 

Potential names for the function:
Get-DbaEnvironmentInfo/Get-DbaWorkstationInfo/Get-DbaDiagnosticInfo

By default the command shouldn’t show anything that will identify the user(like machine name, or domain name) but we can have a -Detailed switch to capture more info if user choses to do so

P.S. basically the command will be used to fill some of the issue reporting form listed below

### System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```

- SQL Server version for source/target

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by ctrlbold** [comment]
Agreed, Test-SqlConnection is returning more information than we need. I'd like a dedicated command for diagnostics info (and then we can reference this command on GitHub) and Test-DbaConnection solely for testing connections. Let's do this in 1.0

**Comment by DaniSQL** [comment]
I am told another function with similar functionality is created.
