### ISSUE TITLE
Find-DbaUserObject enhancement

### ISSUE THREAD

**Issue by peturgretars** [sqlcollaborative/dbatools#929]
I needed to drop a login today and unfortunately got the error: 

`Msg 15141, Level 16, State 1, Line 1
The server principal owns one or more server role(s) and cannot be dropped.`

I figured I would use Find-DbaUserObject function to see which objects where owned by this login. I am afraid no objects were found. I searched the internet and used all T-SQL scripts I could find but always came up empty. Then after more querying in various DMVs I found what the object was. This login had created a server role and was the owner of it. It took me a little while to find this so I figured I would ask if this could be added to the "Find-DbaUserObject" check. 

To reproduce just create a new login, then create a new server role and make the new login be the owner.  Try to drop the login and you get an error. Try to use the Find-DbaUserObject and you will not find anything. You can use this query to find the object owned by the new login. 

`-- Check if login owns a server role 
SELECT r.name AS [ServerRoleName],
       r.principal_id AS [ID],
       r.modify_date AS [DateModified],
       r.create_date AS [DateCreated],
       ou.name AS [Owner],
       CAST(r.is_fixed_role AS BIT) AS [IsFixedRole]
FROM sys.server_principals r
     LEFT OUTER JOIN sys.server_principals AS ou ON ou.principal_id = r.owning_principal_id
WHERE ou.name = @LOGINNAME;
`

Can this check be added to the function?

**Comment by ctrlbold** [comment]
resolved 💃
