### ISSUE TITLE
Get-DbaDiskSpace gives error "Cannot connect to WMI"

### ISSUE THREAD

**Issue by peturgretars** [sqlcollaborative/dbatools#932]
With the latest versions of Get-DbaDiskSpace I get the error: 

> WARNING: Cannot connect to WMI on SERVERNAME

This used to work just fine in past for most against most of my servers but now it fails on all of them. I believe this is a known issue already fixed in Test-DbaPowerPlan recently by Chrissy. 

The way I was running the command was as follows: 

`Get-SqlRegisteredServerName -SqlServer INSTANCENAME -Group GROUPNAME | Get-DbaDiskSpace | SELECT Server,Name,Label,SizeInGB,FreeInGB,PercentFree,BlockSize | where-object {$_.percentfree -le 25} | Export-Csv -Path D:\Temp\Get-DiskSpace.csv -NoTypeInformation`

**Comment by ctrlbold** [comment]
Thanks Petur! So strange, many of our WMI command are failing on our own farms too. We have a plan in place and hope to have this resolved by next week.

**Comment by peturgretars** [comment]
No problem Chrissy!  
Should I report new issues if more of the commands I generally use have the same issue?

**Comment by ctrlbold** [comment]
Only if they dnot work this time next month ;) We' re about to add a new CIM subsystem that should take are of all of this. I'll email you to test once we're done.

**Comment by peturgretars** [comment]
OK thanks.

**Comment by potatoqualitee** [comment]
Petur, we have moved to a new system and this should now work. If it doesn't, please reopen and paste a pic of your issues.

thanks!
