### ISSUE TITLE
Get-DbaLogin - needed for 1.0

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#945]
### Is this a *feature* OR *bug*:

feature

### System Details

We need Get-DbaLogin like the other basic commands. Please add the last login time to SMO object and the default output

```
SELECT MAX(login_time) AS [Last Login Time], login_name [Login]
FROM sys.dm_exec_sessions where login_name = '$($login.name)'
```

per https://mohammaddarab.com/find-last-login-date-sql-server-login/

**Comment by SirCaptainMitch** [comment]
closing, merged
