### ISSUE TITLE
Test-DbaDiskAllocation fails against Windows 2016 Core server

### ISSUE THREAD

**Issue by peturgretars** [sqlcollaborative/dbatools#957]
### BUG
Test-DbaDiskAllocation fails against Windows 2016 Core server

**Target OS:**  Windows 2016 Core
**PowerShell version**: 
Name                           Value                                                                                                                                                                                         
----                           -----                                                                                                                                                                                         
PSVersion                      5.1.14393.206                                                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                       
BuildVersion                   10.0.14393.206                                                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                                                                                       

ModuleType Version    Name                                ExportedCommands                                                                                                                                                   
---------- -------    ----                                ----------------                                                                                                                                                   
Script     0.8.940    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy-SqlServerAgent...} 

### Steps to Reproduce
Run command against Windows 2016 Core server. 
Test-DbaDiskAllocation -ComputerName SERVERNAME 

### Action Results
WARNING: [Test-DbaDiskAllocation][15.17.47] Can't create CimSession on SERVERNAME
WARNING: [Get-AllDiskAllocation][15.17.47] Can't connect to WMI on SERVERNAME

**Comment by potatoqualitee** [comment]
can you try now?

**Comment by niphlod** [comment]
I don't have 2016 core handy but this should be solved from some time now. @peturgretars : can you confirm ?

**Comment by peturgretars** [comment]
Works like a charm :)

**Comment by niphlod** [comment]
perfect, thanks a lot!
