### ISSUE TITLE
Add details on what was removed for Remove-DbaBackup

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#958]
### Is this a *feature* OR *bug*:
feature

### Details
It would be nice to have a summary of what was removed.  Space saved of files removed and number of files removed and folders if that option was used.

**Comment by ctrlbold** [comment]
Totally agree! we should set a write-message -level output. i'd like to see this too without verbose

**Comment by niphlod** [comment]
refactoring remove-dbabackup with its own Find-DbaBackup (via https://github.com/sqlcollaborative/dbatools/commit/13f4de856d23fae74d21b325a8d282f8fa399434#diff-89237c3f371601ed0ef1cb14f53967e6 ) is a better fit for the job (as remove-item, e.g, doesn't really return anything)
