### ISSUE TITLE
[Enhancement] Set-DbaDatabaseOwner will not create the older owner as user and assign to db_owner role

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#965]
### Is this a Is this a *feature* OR *bug*:
enhancement :-)

### Details
This was asked by a couple of attendees on my last presentation on SQL Saturday Lisbon.
Some 3rd party (not also) applications create the database and set his "master" user as owner of the database and this user is used to do the most or all work.

If we use Set-DbaDatabaseOwner to change him to 'sa' or other account, the application will stop working. (We can't have the database owner and the user at the same time).

My suggestion is to create an user, assign to the login (older database owner) and add him to the db_owner database role. This way we can get database owner with new login and keep the older one working flawless.

Thoughts?

**Comment by niphlod** [comment]
Maybe a facility to create an user, map it to a login and assign membership
to it would be beneficial rather then implementing a particular usecase
into Set-DbaDatabaseOwner...

Il 16 mar 2017 11:33 AM, "Cláudio Silva" <notifications@github.com> ha
scritto:

**Comment by wsmelton** [comment]
That sounds more like a local issue for that scenario/DBA environment.  If the owner can't be "sa" then don't use the command.

**Comment by ClaudioESSilva** [comment]
When we use the command we don't want to break anything.
IMO, if we let the user choose when he will run or not that 2nd command, 90% of the cases the application will stop.

I agree that can be a 2nd command and we can use it alone. But, I think that by default should be used here on the Set-DbaDatabaseOwner.

We need to think on accidental DBAs. If make sense, we can have another flag to don't run the 2nd command.

@wsmelton the owner can be "sa" but also other users can be part of db_owner role.

But yeah, I see your point. That's why I said enhancement and not bug

**Comment by wsmelton** [comment]
Even as an enhancement this is specific to an environment requirement. If any enhancement request includes the statement "the application will stop working" that is up to the DBA to decided whether the command should be run...whether it is accidental DBA or not.

Having an account "own" the database then being a member of the "db_owner" role is not the same thing. Logins that own a database basically become "dbo". While you get the same permissions being a member of the "db_owner" role it is not necessarily the same.  Especially if an application requires the login to be owner of the database then it is expecting to basically be "dbo".

An example...

- Database: Woodworking
- Two SQL Logins: TestLogin (owner of DB), and TestSQLLogin (member of db_owner)

Most applications validate if they "own" a database by seeing if they are the user `dbo`. So in this scenario:

```sql
USE [Woodworking];
GO

EXECUTE AS LOGIN = 'TestLogin'
SELECT CURRENT_USER
GO

REVERT
GO

EXECUTE AS USER = 'TestSQLLogin'
SELECT CURRENT_USER
GO

REVERT
GO
```

Gives the results:

```
------------
dbo

(1 row(s) affected)

------------
TestSQLLogin

(1 row(s) affected)


```


So in the end if an application wants to see a login as the owner, just moving that login/user to the `db_owner` role is not going to keep it going...it should/will fail.

**Comment by ClaudioESSilva** [comment]
Fair point! 😃 
When I came across with the scenario I have described, by adding user to `db_owner` role keeped the application working as expected.

**Comment by niphlod** [comment]
yep. 
In any case, the accidental DBA can't be protected from all things a Set-* cmdlet does.
