### ISSUE TITLE
 New-Object : Cannot find type [sqlcollective.dbatools.Configuration.Config]

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#969]
### Is this a *feature* OR *bug*:

bug

### System Details

user writes: `I have an unrelated question. dbatools doesn't explicitly throw an error, but if i do an $error[], it shows - New-Object : Cannot find type [sqlcollective.dbatools.Configuration.Config]: verify that the assembly containing this type is loaded. Any ideas?`

Then pasted 
![image](https://cloud.githubusercontent.com/assets/8278033/24003417/ba1849ec-0a63-11e7-8a8c-70dc03bbf5f1.png)

2012 R2, but have WMF 5.1 installed on it

**Comment by FriedrichWeinmann** [comment]
Solved some time ago
