### ISSUE TITLE
[Enhancement] Restore-dbaDatabase

### ISSUE THREAD

**Issue by mvillegascuellar** [sqlcollaborative/dbatools#975]
### Is this a *feature* OR *bug*:

Feature

### Details

It would be nice to add a switch to the Restore-dbaDatabase function in order to close existing connections before doing the database restore I had this scenario and I had to switch between powershell and ssms to drop the existing connections several times.

**Comment by Stuart-Moore** [comment]
It has one. Were you using the withreplace switch?

That kills processes and does an offline/online for good measure if it
finds the db already exists

Cheers
Stuart

**Comment by mvillegascuellar** [comment]
I did used that switch, but the sessions were not killed. I though it only was used to replace the existing database.

**Comment by Stuart-Moore** [comment]
That's the only time that it would need to kill processes. 

Can you provide some more details please. Sql version, edition and also the command line you're running. 

And which commands you had to run in the end to kill the processes please.

**Comment by mvillegascuellar** [comment]
Hi, I was executing the command on a SQL Server 2014  Developer Edition. This is the exactamente command I was executing.

Restore-DbaDatabase -SqlServer ROSQLPERF1.qaxpo.pvt -Path E:\MSSQL\Backup\ROSQLPERF1\PLS_PERF -MaintenanceSolutionBackup -WithReplace

I had to put the database on restricted mode with rollback immediate to finally restore the database.  I was getting an error message indicating that the database was un use and could not be restored.

**Comment by Stuart-Moore** [comment]
Thanks for that.

Had a quick play on my home setup and couldn't get it to fail so going to try with a bigger setup now I'm back in the office.

Is it a heavily used system? wondering if something's sneaking in between the kill and the start of the restore process

**Comment by mvillegascuellar** [comment]
Hi, it is a pretty heavily used system, it has a component constantly hamering the database, I think it would be a good call to add the ALTER DATABASE SET RESTRICTED_USER in order to avoid this issue on busy databases.

**Comment by Stuart-Moore** [comment]
PR #982 was merged in the other day which should sort this one for you

It's in dev, so you'd need to pull that branch if you want to take it for a test. Not sure on chrissie's target for the next release.

**Comment by mvillegascuellar** [comment]
Thanks Stuart,

I'll take a look.
