### ISSUE TITLE
Get-DBAAvailabilityGroup - Primary AG member returns as 'Unknown'

### ISSUE THREAD

**Issue by mhouston100** [sqlcollaborative/dbatools#978]
### Is this a *feature* OR *bug*:

Bug

### System Details

- Operating system name and version: Server 2012 R2 Core
- Output from `$PSVersionTable`: 

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

- Output of dbatools version:
ModuleType Version    Name
---------- -------    ----
Script     0.8.903    dbatools
``` 
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```

- SQL Server version for source/target
2016 Enterprise

### Steps to Reproduce

Run:

Get-DbaAvailabilityGroup -SqlServer sql-prd-c01

against cluster from either a primary or secondary sync member

### Action Results

AvailabilityGroup : AG-APP-PRD
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-APP-PRD
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-InformationSystemsInternal
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-InformationSystemsInternal
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-Intramaps
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-Intramaps
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-Sharepoint
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-Sharepoint
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-SSISDB
ReplicaName       : SQL-PRD-V05
Role              : Unknown
SyncState         : Unknown
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

AvailabilityGroup : AG-SSISDB
ReplicaName       : SQL-PRD-V06
Role              : Secondary
SyncState         : Synchronized
AvailabilityMode  : SynchronousCommit
FailoverMode      : Automatic

### Expected Results

I would expect the PRIMARY member to be listed, instead it is only listed as 'Unknown'. I do recall this working at some point though, I cannot see where this is failing.

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**None of these return any errors or exceptions.**

**Comment by mhouston100** [comment]
Additional information, the user running this is a local administrator on both machines as well as 'sysadmin' on both SQL instances.

**Comment by wsmelton** [comment]
If you run this command from a secondary replica then the primary is going to return as unknown. This is by design in SMO because the secondary does have the information (only the primary replica does).

I do have plans to try and work on a different method that can be more accurate in showing the primary, no matter what replica in the AG you run it from....just going to take a bit of time.

**Comment by mhouston100** [comment]
Ah I think I know where I meesed up and what my particular issue was.

I'm writing a synchronization script to sync logins and SQL Jobs across the cluster members, when I was exctracting the AG group using 'Get-DbaAvailabilityGroup' I was actually pointing it at the CLUSTER name not the SERVER name.

That's why I was seeing the incorrect results.

Running it directly against the server returns the results expected. I'll just have to re-jig my script to take that into account.

If possible I would change this enhancement to 'Run the Get-DbaAvailabilityGroup against the cluster name and return all replica names and their correct roles' that would make things so much easier.

Whether it first checks the cluster for all members, then iterates through checking each AG and the role reported, the merge them into a single output.

My script is simply looking at the AG output, identifying which partner is the primary, then copying the logins and jobs to each secondary, for each AG.

**Comment by mhouston100** [comment]
I'm working around it now by simply pulling all the AG names, then using:

`(Get-ClusterGroup -Name $agName).OwnerNode.Name`

To pull the primary node.

**Comment by wsmelton** [comment]
@mhouston100 We have redone the command in the latest release. Let me know if that solves your issue or if we need to make some adjustments.

**Comment by potatoqualitee** [comment]
please reopen if there is an issue! thank you @wsmelton for fixing 👍

**Comment by jensenjk** [comment]
Get-DbaAvailiilityGroup does not return info about primaryReplica when run against SQL server 2017

**Comment by wsmelton** [comment]
@jensenjk if you feel there is a bug in the command of the current version of the module please open a new issue and provide all the details.
