### ISSUE TITLE
Test-DbaBackup

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#981]
### Is this a *feature* OR *bug*:

feature

### Details

@nocentino, 
Please rename Test-DbaLastBackup to Test-DbaBackup and make it awesome. 

Minimum reqs: It should have -Last and -All switches (or similar) to replicate the behavior of Test-DbaLastBackup.

It should also support -Path so that the people can say exactly which backups they'd like testing. 

Should it also accept the output of Get-DbaBackupHistory? 

I know you mentioned that your tests do Diff and Maybe log too?

Thanks!

**Comment by Stuart-Moore** [comment]
why not just a wrapper around existing functionality?

**Comment by potatoqualitee** [comment]
done and awesome af
