### ISSUE TITLE
Update Set-SqlTempDbConfiguration to work with fixed size TempDB Files

### ISSUE THREAD

**Issue by banditkd** [sqlcollaborative/dbatools#983]
feature

Is it possible to add a new parameter to Set-SqlTempDbConfiguration that will disable auto-grow on the TempDB files. 

We always allocate a fixed drive for TempDB and pre-allocate the TempDB to fill this space so auto-grow wouldn't help.

Thanks

**Comment by wsmelton** [comment]
You are one of the few I've heard that actually pre-allocate the tempdb. Wish I could get clients to do this...make them think more on how much space they really need for a drive.

I would not see any issue adding this parameter, something like "-DisableGrowth".

**Comment by banditkd** [comment]
That would be perfect, save me editing the scripts afterwards.

I know what you mean, I haven't really seen many places do this but then we have very little OLTP, more ETL stuff so we see how big TempDB gets in the non prod estate, so makes sizing for prod reasonably easy
