### ISSUE TITLE
[new-command] Get-DbaLog to more easily find error log for module

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#990]
### Is this a *feature* OR *bug*:
**Feature**

### Action Results
A function that utilizes `Get-DbaConfig -Name dbatoolslogpath` to find the log path and then offers some ability to either `type` the contents of the latest log (maybe for the current session) to the console...or switch that allows you to open the log file in the default editor for ".log" files (just use `Invoke-Item`).

### Expected Results

`Get-DbaLog -ToConsole`

Just dumps contents to the console, maybe pages it by default so it does not just scroll by...e.g `Get-DbaLog | more` type thing.

`Get-DbaLog`

Just list out the files, directory lookup for the path which just offers the users easier access to them for our benefit. `Get-ChildItem (Get-DbaConfig -Name dbatoolslogpath).Value`

`Get-DbaLog -OpenLatest`

Opens file up to Notepad or whatever is the default app for log/txt files.

**Comment by potatoqualitee** [comment]
done didley by @FriedrichWeinmann  😇
