### ISSUE TITLE
[enhancement] Copy-SqlDatabase updated to utilize Restore functions for -BackupRestore parameter

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#991]
### Is this a *feature* OR *bug*:

Copy-SqlDatabase (or soon to be Copy-DbaDatabase) needs to be updated to utilize the Restore-DbaDatabase when the backup and restore parameter is provided.

**Comment by potatoqualitee** [comment]
fasho, @Stuart-Moore implemented this 😇
