### ISSUE TITLE
Restore-DBADatabase without recovery

### ISSUE THREAD

**Issue by PsPsam** [sqlcollaborative/dbatools#995]
### Is this a *feature* OR *bug*:

Bug

### System Details

- Operating system name and version:
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                                                                                                                           
----                           -----                                                                                                                                                                                           
PSVersion                      5.1.14393.953                                                                                                                                                                                   
PSEdition                      Desktop                                                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                         
BuildVersion                   10.0.14393.953                                                                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                                                             
SerializationVersion           1.1.0.1  
```

- Output of dbatools version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      943    -1      
0      8      942    -1      
0      8      933    -1      
0      8      901    -1      
0      8      900    -1      
0      8      692    -1      
0      8      65     -1 
```

- SQL Server version for source/target
12.0.4502.0/12.0.4502.0

### Steps to Reproduce
```powershell
Restore-DbaDatabase -SqlServer 'Name' -path \\server\Path-MaintenanceSolutionBackup 
-RestoreTime $restoretime -UseDestinationDefaultDirectories 
-DatabaseName db_Powershellrestore -DestinationFilePrefix 'test_' 
-OutputScriptOnly -WithReplace -verbose
```

### Action Results
Restore without recovery

### Expected Results
Restore with recover

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`
I didnt add all the verbose when it just scanned all the files :)

> VERBOSE: Get-FilteredRestoreFile - 804 Files to filter
> VERBOSE: Get-FilteredRestoreFile - 1 database to process
> VERBOSE: Get-FilteredRestoreFile - Find Newest Full backup
> VERBOSE: Get-FilteredRestoreFile - Got a Full backup, now to find diffs if they exist
> VERBOSE: Get-FilteredRestoreFile - we have at least one diff so look for tlogs after the last one
> VERBOSE: Get-FilteredRestoreFile - Got a Full/Diff backups, now find all Tlogs needed
> VERBOSE: Get-FilteredRestoreFile - Filtered 768 down to 2
> VERBOSE: Get-FilteredRestoreFile - 3 Transaction Log backups found
> VERBOSE: Get-FilteredRestoreFile - Returning Results to caller
> VERBOSE: Restore-DbaDatabase -  dbs to restore
> VERBOSE: Restore-DbaDatabase - Starting FileSet
> VERBOSE: Test-DbaLsnChain - Testing LSN Chain
> VERBOSE: Test-DbaLsnChain - Passed LSN Chain checks
> VERBOSE: Test-DbaRestoreVersion - RestoreVersion is 12
> VERBOSE: Restore-DBFromFilteredArray - Starting
> VERBOSE: RPcount = 5
> VERBOSE: Restore-DBFromFilteredArray - Restoring DB_Powershellrestore backup starting at order 1 - LSN 202885000042010500145 in \\sodra.com\sql-backup\Produktion\vax-vs563\DB\FULL\VAX-VS563_DB_FULL_20170226_210000.b
> ak
> VERBOSE: Restore-DBFromFilteredArray - Beginning Restore of DB_Powershellrestore
> VERBOSE: Restore-DBFromFilteredArray - restoring to 03/26/2017 00:00:00
> VERBOSE: Restore-DBFromFilteredArray - restore action = Database
> VERBOSE: Restore-DBFromFilteredArray - More files to restore, NoRecovery set
> VERBOSE: Restore-DBFromFilteredArray - Adding device
> VERBOSE: Restore-DBFromFilteredArray - Performing restore action
> RESTORE DATABASE [DB_Powershellrestore] FROM  DISK = N'\\sodra.com\sql-backup\Produktion\vax-vs563\DB\FULL\VAX-VS563_DB_FULL_20170226_210000.bak' WITH  FILE = 1,  MOVE N'DBPDT' TO N'G:\Data\test_DBPDT.mdf',  M
> OVE N'DBPDT_log' TO N'H:\Data\test_DBPDT_log.LDF',  NORECOVERY,  NOUNLOAD,  REPLACE,  STATS = 1,  STOPAT = N'03/26/2017 00:00:00'
> VERBOSE: Restore-DBFromFilteredArray - Succeeded, Closing Server connection
> VERBOSE: Restore-DBFromFilteredArray - Restoring DB_Powershellrestore backup starting at order 2 - LSN 206251000024462100167 in \\share\olahallengren\\DIFF\VAX-VS563_DB_DIFF_20170325_211000.b
> ak
> VERBOSE: Restore-DBFromFilteredArray - Beginning Restore of DB_Powershellrestore
> VERBOSE: Restore-DBFromFilteredArray - restoring to 03/26/2017 00:00:00
> VERBOSE: Restore-DBFromFilteredArray - restore action = Database
> VERBOSE: Restore-DBFromFilteredArray - More files to restore, NoRecovery set
> VERBOSE: Restore-DBFromFilteredArray - Adding device
> VERBOSE: Restore-DBFromFilteredArray - Performing restore action
> RESTORE DATABASE [DB_Powershellrestore] FROM  DISK = N'\\share\olahallengren\\DIFF\VAX-VS563_DB_DIFF_20170325_211000.bak' WITH  FILE = 1,  MOVE N'DBPDT' TO N'G:\Data\test_DBPDT.mdf',  M
> OVE N'DBPDT_log' TO N'H:\Data\test_DBPDT_log.LDF',  NORECOVERY,  NOUNLOAD,  REPLACE,  STATS = 1,  STOPAT = N'03/26/2017 00:00:00'
> VERBOSE: Restore-DBFromFilteredArray - Succeeded, Closing Server connection
> VERBOSE: Restore-DBFromFilteredArray - Restoring DB_Powershellrestore backup starting at order 206251000023479400001 - LSN 206251000023479400001 in \\share\olahallengren\\LOG\VAX-VS563_DB_LOG
> _20170325_220000.trn
> VERBOSE: Restore-DBFromFilteredArray - Beginning Restore of DB_Powershellrestore
> VERBOSE: Restore-DBFromFilteredArray - restoring to 03/26/2017 00:00:00
> VERBOSE: Restore-DBFromFilteredArray - restore action = Log
> VERBOSE: Restore-DBFromFilteredArray - More files to restore, NoRecovery set
> VERBOSE: Restore-DBFromFilteredArray - Adding device
> VERBOSE: Restore-DBFromFilteredArray - Performing restore action
> RESTORE LOG [DB_Powershellrestore] FROM  DISK = N'\\share\olahallengren\\LOG\VAX-VS563_DB_LOG_20170325_220000.trn' WITH  FILE = 1,  MOVE N'DBPDT' TO N'G:\Data\test_DBPDT.mdf',  MOVE N'A
> xxosPDT_log' TO N'H:\Data\test_DBPDT_log.LDF',  NORECOVERY,  NOUNLOAD,  STATS = 1,  STOPAT = N'03/26/2017 00:00:00'
> VERBOSE: Restore-DBFromFilteredArray - Succeeded, Closing Server connection
> VERBOSE: Restore-DBFromFilteredArray - Restoring DB_Powershellrestore backup starting at order 206251000029313800001 - LSN 206251000029313800001 in \\share\olahallengren\\LOG\VAX-VS563_DB_LOG
> _20170325_230000.trn
> VERBOSE: Restore-DBFromFilteredArray - Beginning Restore of DB_Powershellrestore
> VERBOSE: Restore-DBFromFilteredArray - restoring to 03/26/2017 00:00:00
> VERBOSE: Restore-DBFromFilteredArray - restore action = Log
> VERBOSE: Restore-DBFromFilteredArray - More files to restore, NoRecovery set
> VERBOSE: Restore-DBFromFilteredArray - Adding device
> VERBOSE: Restore-DBFromFilteredArray - Performing restore action
> RESTORE LOG [DB_Powershellrestore] FROM  DISK = N'\\share\olahallengren\\LOG\VAX-VS563_DB_LOG_20170325_230000.trn' WITH  FILE = 1,  MOVE N'DBPDT' TO N'G:\Data\test_DBPDT.mdf',  MOVE N'A
> xxosPDT_log' TO N'H:\Data\test_DBPDT_log.LDF',  NORECOVERY,  NOUNLOAD,  STATS = 1,  STOPAT = N'03/26/2017 00:00:00'
> VERBOSE: Restore-DBFromFilteredArray - Succeeded, Closing Server connection
> VERBOSE: Restore-DBFromFilteredArray - Restoring DB_Powershellrestore backup starting at order 206251000035130800001 - LSN 206251000035130800001 in \\share\olahallengren\\LOG\VAX-VS563_DB_LOG
> _20170326_000001.trn
> VERBOSE: Restore-DBFromFilteredArray - Beginning Restore of DB_Powershellrestore
> VERBOSE: Restore-DBFromFilteredArray - restoring to 03/26/2017 00:00:00
> VERBOSE: Restore-DBFromFilteredArray - restore action = Log
> VERBOSE: Restore-DBFromFilteredArray - Doing Recovery on last file
> VERBOSE: Restore-DBFromFilteredArray - Adding device
> VERBOSE: Restore-DBFromFilteredArray - Performing restore action
> RESTORE LOG [DB_Powershellrestore] FROM  DISK = N'\\share\olahallengren\\LOG\VAX-VS563_DB_LOG_20170326_000001.trn' WITH  FILE = 1,  MOVE N'DBPDT' TO N'G:\Data\test_DBPDT.mdf',  MOVE N'A
> xxosPDT_log' TO N'H:\Data\test_DBPDT_log.LDF',  NOUNLOAD,  STATS = 1,  STOPAT = N'03/26/2017 00:00:00'
> VERBOSE: Restore-DBFromFilteredArray - Succeeded, Closing Server connection
> VERBOSE: Database DB_Powershellrestore restored successfully

**Comment by PsPsam** [comment]
I get the same script (without Recovery) when I create it manualy in ssms so this might not be an issue with the restore command.

**Comment by Stuart-Moore** [comment]
Hmm, that's interesting. The T-SQL generated is correct:
RESTORE LOG [DB_Powershellrestore] FROM DISK = N'\share\olahallengren\LOG\VAX-VS563_DB_LOG_20170326_000001.trn' WITH FILE = 1, MOVE N'DBPDT' TO N'G:\Data\test_DBPDT.mdf', MOVE N'A
xxosPDT_log' TO N'H:\Data\test_DBPDT_log.LDF', NOUNLOAD, STATS = 1, STOPAT = N'03/26/2017 00:00:00'

should do recovery (it's the default if there's no NORECOVERY in the with block).

Out of interest could you try it against a different SQL instance? Just wondering if there's some reason why this (and SSMS) aren't doing the recovery at the end of the restore.

**Comment by PsPsam** [comment]
I have run it succesfully after this on different servers. I Believe something went wrong at the server level.

**Comment by potatoqualitee** [comment]
@PsPsam - do you consider this issue resolved? If so, I will close it.

Thanks!

**Comment by PsPsam** [comment]
Yea it can be closed.

**Comment by potatoqualitee** [comment]
🤘
