### ISSUE TITLE
Invoke-DbaDatabaseClone

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#996]
### Is this a *feature* OR *bug*:

feature after 1.0

### Details

[Understanding data security in cloned databases created using DBCC CLONEDATABASE](https://blogs.msdn.microsoft.com/sql_server_team/understanding-data-security-in-cloned-databases-created-using-dbcc-clonedatabase/)

Perhaps we can use Clone-DbaDatabase as an alias.

**Comment by niphlod** [comment]
We have Invoke-DbaDbClone
