### ISSUE TITLE
New and Get-DbaSqlAlias

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#997]
### Is this a *feature* OR *bug*:

feature - not for 1.0. 

Basically the important parts of C:\Windows\System32\cliconfg.exe

### Details

Aliases are useful for SharePoint migrations and other stuff.

Attached is a modified version of a similar but simpler command I created for creating an alias in dbareports.

[New-DbaSqlAlias.txt](https://github.com/sqlcollaborative/dbatools/files/875441/New-DbaSqlAlias.txt)

**Comment by potatoqualitee** [comment]
gonna do this tonight, prolly

**Comment by niphlod** [comment]
done on Jul 2017.
